DarkPlaces: cap_ogg.c File Reference
cap_ogg.c File Reference
#include <sys/types.h>
#include "quakedef.h"
#include "client.h"
#include "cap_ogg.h"
Data Structures
struct oggpack_buffer
struct ogg_page
struct ogg_stream_state
struct ogg_packet
struct ogg_sync_state
struct vorbis_info
struct vorbis_dsp_state
struct vorbis_block
struct alloc_chain
struct vorbis_comment
struct yuv_buffer
struct theora_info
Theora bitstream info.
struct theora_state
Codec internal state and context.
struct theora_comment
Comment header metadata.
struct allocatedoggpage_t
struct capturevideostate_ogg_formatspecific_t
Macros
#define TH_ENCCTL_SET_VP3_COMPATIBLE (10)
#define LOAD_FORMATSPECIFIC_OGG() capturevideostate_ogg_formatspecific_t *format = (capturevideostate_ogg_formatspecific_t *) cls.capturevideo.formatspecific
Typedefs
typedef int channelmapping_t[8]
Enumerations
enum theora_colorspace { OC_CS_UNSPECIFIED , OC_CS_ITU_REC_470M , OC_CS_ITU_REC_470BG , OC_CS_NSPACES }
A Colorspace.
enum theora_pixelformat { OC_PF_420 , OC_PF_RSVD , OC_PF_422 , OC_PF_444 }
A Chroma subsampling.
Functions
static qbool SCR_CaptureVideo_Ogg_OpenLibrary (void)
void SCR_CaptureVideo_Ogg_Init (void)
qbool SCR_CaptureVideo_Ogg_Available (void)
void SCR_CaptureVideo_Ogg_CloseDLL (void)
static void SCR_CaptureVideo_Ogg_Interleave (void)
static void SCR_CaptureVideo_Ogg_FlushInterleaving (void)
static void SCR_CaptureVideo_Ogg_EndVideo (void)
static void SCR_CaptureVideo_Ogg_ConvertFrame_BGRA_to_YUV (void)
static void SCR_CaptureVideo_Ogg_VideoFrames (int num)
static void SCR_CaptureVideo_Ogg_SoundFrame (const portable_sampleframe_t *paintbuffer, size_t length)
void SCR_CaptureVideo_Ogg_BeginVideo (void)
Variables
static cvar_t cl_capturevideo_ogg_theora_vp3compat = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_vp3compat", "1", "make VP3 compatible theora streams"}
static cvar_t cl_capturevideo_ogg_theora_quality = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_quality", "48", "video quality factor (0 to 63), or -1 to use bitrate only; higher is better; setting both to -1 achieves unlimited quality"}
static cvar_t cl_capturevideo_ogg_theora_bitrate = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_bitrate", "-1", "video bitrate (45 to 2000 kbps), or -1 to use quality only; higher is better; setting both to -1 achieves unlimited quality"}
static cvar_t cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier", "1.5", "how much more bit rate to use for keyframes, specified as a factor of at least 1"}
static cvar_t cl_capturevideo_ogg_theora_keyframe_maxinterval = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_maxinterval", "64", "maximum keyframe interval (1 to 1000)"}
static cvar_t cl_capturevideo_ogg_theora_keyframe_mininterval = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_mininterval", "8", "minimum keyframe interval (1 to 1000)"}
static cvar_t cl_capturevideo_ogg_theora_keyframe_auto_threshold = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_auto_threshold", "80", "threshold for key frame decision (0 to 100)"}
static cvar_t cl_capturevideo_ogg_theora_noise_sensitivity = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_noise_sensitivity", "1", "video noise sensitivity (0 to 6); lower is better"}
static cvar_t cl_capturevideo_ogg_theora_sharpness = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_sharpness", "0", "sharpness (0 to 2); lower is sharper"}
static cvar_t cl_capturevideo_ogg_vorbis_quality = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_vorbis_quality", "3", "audio quality (-1 to 10); higher is better"}
static int(* qogg_stream_packetin)(ogg_stream_state *os, ogg_packet *op)
static int(* qogg_stream_pageout)(ogg_stream_state *os, ogg_page *og)
static int(* qogg_stream_flush)(ogg_stream_state *os, ogg_page *og)
static int(* qogg_stream_init)(ogg_stream_state *os, int serialno)
static int(* qogg_stream_clear)(ogg_stream_state *os)
static int64_t(* qogg_page_granulepos)(ogg_page *og)
static void(* qvorbis_info_init)(vorbis_info *vi)
static void(* qvorbis_info_clear)(vorbis_info *vi)
static void(* qvorbis_comment_init)(vorbis_comment *vc)
static void(* qvorbis_comment_clear)(vorbis_comment *vc)
static int(* qvorbis_block_init)(vorbis_dsp_state *v, vorbis_block *vb)
static int(* qvorbis_block_clear)(vorbis_block *vb)
static void(* qvorbis_dsp_clear)(vorbis_dsp_state *v)
static double(* qvorbis_granule_time)(vorbis_dsp_state *v, int64_t granulepos)
static int(* qvorbis_analysis_init)(vorbis_dsp_state *v, vorbis_info *vi)
static int(* qvorbis_commentheader_out)(vorbis_comment *vc, ogg_packet *op)
static int(* qvorbis_analysis_headerout)(vorbis_dsp_state *v, vorbis_comment *vc, ogg_packet *op, ogg_packet *op_comm, ogg_packet *op_code)
static float **(* qvorbis_analysis_buffer)(vorbis_dsp_state *v, int vals)
static int(* qvorbis_analysis_wrote)(vorbis_dsp_state *v, int vals)
static int(* qvorbis_analysis_blockout)(vorbis_dsp_state *v, vorbis_block *vb)
static int(* qvorbis_analysis)(vorbis_block *vb, ogg_packet *op)
static int(* qvorbis_bitrate_addblock)(vorbis_block *vb)
static int(* qvorbis_bitrate_flushpacket)(vorbis_dsp_state *vd, ogg_packet *op)
static int(* qvorbis_encode_init_vbr)(vorbis_info *vi, long channels, long rate, float base_quality)
static int(* qtheora_encode_init)(theora_state *th, theora_info *ti)
static int(* qtheora_encode_YUVin)(theora_state *t, yuv_buffer *yuv)
static int(* qtheora_encode_packetout)(theora_state *t, int last_p, ogg_packet *op)
static int(* qtheora_encode_header)(theora_state *t, ogg_packet *op)
static int(* qtheora_encode_comment)(theora_comment *tc, ogg_packet *op)
static int(* qtheora_encode_tables)(theora_state *t, ogg_packet *op)
static void(* qtheora_info_init)(theora_info *c)
static void(* qtheora_info_clear)(theora_info *c)
static void(* qtheora_clear)(theora_state *t)
static void(* qtheora_comment_init)(theora_comment *tc)
static void(* qtheora_comment_clear)(theora_comment *tc)
static double(* qtheora_granule_time)(theora_state *th, int64_t granulepos)
static int(* qtheora_control)(theora_state *th, int req, void *buf, size_t buf_sz)
static dllfunction_t oggfuncs []
static dllfunction_t vorbisencfuncs []
static dllfunction_t vorbisfuncs []
static dllfunction_t theorafuncs []
static dllhandle_t og_dll = NULL
static dllhandle_t vo_dll = NULL
static dllhandle_t ve_dll = NULL
static dllhandle_t th_dll = NULL
channelmapping_t mapping [8]
Macro Definition Documentation
LOAD_FORMATSPECIFIC_OGG
#define LOAD_FORMATSPECIFIC_OGG () capturevideostate_ogg_formatspecific_t *format = (capturevideostate_ogg_formatspecific_t *) cls.capturevideo.formatspecific
Definition at line 637 of file cap_ogg.c.
TH_ENCCTL_SET_VP3_COMPATIBLE
#define TH_ENCCTL_SET_VP3_COMPATIBLE (10)
Definition at line 297 of file cap_ogg.c.
Typedef Documentation
channelmapping_t
typedef int channelmapping_t[8]
Definition at line 878 of file cap_ogg.c.
Enumeration Type Documentation
theora_colorspace
enum theora_colorspace
A Colorspace.
Enumerator
OC_CS_UNSPECIFIED
The colorspace is unknown or unspecified.
OC_CS_ITU_REC_470M
This is the best option for 'NTSC' content.
OC_CS_ITU_REC_470BG
This is the best option for 'PAL' content.
OC_CS_NSPACES
This marks the end of the defined colorspaces.
Definition at line 316 of file cap_ogg.c.
             {
  OC_CS_UNSPECIFIED,
  OC_CS_ITU_REC_470M,
  OC_CS_ITU_REC_470BG,
  OC_CS_NSPACES
} theora_colorspace;
theora_pixelformat
enum theora_pixelformat
A Chroma subsampling.
These enumerate the available chroma subsampling options supported by the theora format. See Section 4.4 of the specification for exact definitions.
Enumerator
OC_PF_420
Chroma subsampling by 2 in each direction (4:2:0)
OC_PF_RSVD
Reserved value.
OC_PF_422
Horizonatal chroma subsampling by 2 (4:2:2)
OC_PF_444
No chroma subsampling at all (4:4:4)
Definition at line 330 of file cap_ogg.c.
             {
  OC_PF_420,
  OC_PF_RSVD,
  OC_PF_422,
  OC_PF_444
} theora_pixelformat;
Function Documentation
SCR_CaptureVideo_Ogg_Available()
qbool SCR_CaptureVideo_Ogg_Available (void)
Definition at line 593 of file cap_ogg.c.
{
    return og_dll && th_dll && vo_dll && ve_dll;
}
SCR_CaptureVideo_Ogg_BeginVideo()
void SCR_CaptureVideo_Ogg_BeginVideo (void)
Definition at line 921 of file cap_ogg.c.
{
    char vabuf[1024];
    cls.capturevideo.format = CAPTUREVIDEOFORMAT_OGG_VORBIS_THEORA;
    cls.capturevideo.formatextension = "ogv";
    cls.capturevideo.videofile = FS_OpenRealFile(va(vabuf, sizeof(vabuf), "%s.%s", cls.capturevideo.basename, cls.capturevideo.formatextension), "wb", false);
    cls.capturevideo.endvideo = SCR_CaptureVideo_Ogg_EndVideo;
    cls.capturevideo.videoframes = SCR_CaptureVideo_Ogg_VideoFrames;
    cls.capturevideo.soundframe = SCR_CaptureVideo_Ogg_SoundFrame;
    cls.capturevideo.formatspecific = Mem_Alloc(tempmempool, sizeof(capturevideostate_ogg_formatspecific_t));
    {
        LOAD_FORMATSPECIFIC_OGG();
        int num, denom, i;
        ogg_page pg;
        ogg_packet pt, pt2, pt3;
        theora_comment tc;
        vorbis_comment vc;
        theora_info ti;
        int vp3compat;
        format->serial1 = rand();
        qogg_stream_init(&format->to, format->serial1);
        if(cls.capturevideo.soundrate)
        {
            do
            {
                format->serial2 = rand();
            }
            while(format->serial1 == format->serial2);
            qogg_stream_init(&format->vo, format->serial2);
        }
        format->videopage.len = format->audiopage.len = 0;
        qtheora_info_init(&ti);
        ti.frame_width = cls.capturevideo.width;
        ti.frame_height = cls.capturevideo.height;
        ti.width = (ti.frame_width + 15) & ~15;
        ti.height = (ti.frame_height + 15) & ~15;
        //ti.offset_x = ((ti.width - ti.frame_width) / 2) & ~1;
        //ti.offset_y = ((ti.height - ti.frame_height) / 2) & ~1;
        for(i = 0; i < 2; ++i)
        {
            format->yuv[i].y_width = ti.width;
            format->yuv[i].y_height = ti.height;
            format->yuv[i].y_stride = ti.width;
            format->yuv[i].uv_width = ti.width / 2;
            format->yuv[i].uv_height = ti.height / 2;
            format->yuv[i].uv_stride = ti.width / 2;
            format->yuv[i].y = (unsigned char *) Mem_Alloc(tempmempool, format->yuv[i].y_stride * format->yuv[i].y_height);
            format->yuv[i].u = (unsigned char *) Mem_Alloc(tempmempool, format->yuv[i].uv_stride * format->yuv[i].uv_height);
            format->yuv[i].v = (unsigned char *) Mem_Alloc(tempmempool, format->yuv[i].uv_stride * format->yuv[i].uv_height);
        }
        format->yuvi = -1; // -1: no frame valid yet, write into 0
        FindFraction(cls.capturevideo.framerate / cls.capturevideo.framestep, &num, &denom, 1001);
        ti.fps_numerator = num;
        ti.fps_denominator = denom;
        FindFraction(1 / vid_pixelheight.value, &num, &denom, 1000);
        ti.aspect_numerator = num;
        ti.aspect_denominator = denom;
        ti.colorspace = OC_CS_UNSPECIFIED;
        ti.pixelformat = OC_PF_420;
        ti.quick_p = true; // http://mlblog.osdir.com/multimedia.ogg.theora.general/2004-07/index.shtml
        ti.dropframes_p = false;
        ti.target_bitrate = cl_capturevideo_ogg_theora_bitrate.integer * 1000;
        ti.quality = cl_capturevideo_ogg_theora_quality.integer;
        if(ti.target_bitrate <= 0)
        {
            ti.target_bitrate = -1;
            ti.keyframe_data_target_bitrate = (unsigned int)-1;
        }
        else
        {
            ti.keyframe_data_target_bitrate = (int) (ti.target_bitrate * max(1, cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier.value));
            if(ti.target_bitrate < 45000 || ti.target_bitrate > 2000000)
                Con_DPrintf("WARNING: requesting an odd bitrate for theora (sensible values range from 45 to 2000 kbps)\n");
        }
        if(ti.quality < 0 || ti.quality > 63)
        {
            ti.quality = 63;
            if(ti.target_bitrate <= 0)
            {
                ti.target_bitrate = 0x7FFFFFFF;
                ti.keyframe_data_target_bitrate = 0x7FFFFFFF;
            }
        }
        // this -1 magic is because ti.keyframe_frequency and ti.keyframe_mindistance use different metrics
        ti.keyframe_frequency = bound(1, cl_capturevideo_ogg_theora_keyframe_maxinterval.integer, 1000);
        ti.keyframe_mindistance = bound(1, cl_capturevideo_ogg_theora_keyframe_mininterval.integer, (int) ti.keyframe_frequency) - 1;
        ti.noise_sensitivity = bound(0, cl_capturevideo_ogg_theora_noise_sensitivity.integer, 6);
        ti.sharpness = bound(0, cl_capturevideo_ogg_theora_sharpness.integer, 2);
        ti.keyframe_auto_threshold = bound(0, cl_capturevideo_ogg_theora_keyframe_auto_threshold.integer, 100);
        ti.keyframe_frequency_force = ti.keyframe_frequency;
        ti.keyframe_auto_p = (ti.keyframe_frequency != ti.keyframe_mindistance + 1);
        qtheora_encode_init(&format->ts, &ti);
        qtheora_info_clear(&ti);
        if(cl_capturevideo_ogg_theora_vp3compat.integer)
        {
            vp3compat = 1;
            qtheora_control(&format->ts, TH_ENCCTL_SET_VP3_COMPATIBLE, &vp3compat, sizeof(vp3compat));
            if(!vp3compat)
                Con_DPrintf("Warning: theora stream is not fully VP3 compatible\n");
        }
        // vorbis?
        if(cls.capturevideo.soundrate)
        {
            qvorbis_info_init(&format->vi);
            qvorbis_encode_init_vbr(&format->vi, cls.capturevideo.soundchannels, cls.capturevideo.soundrate, bound(-1, cl_capturevideo_ogg_vorbis_quality.value, 10) * 0.099);
            qvorbis_comment_init(&vc);
            qvorbis_analysis_init(&format->vd, &format->vi);
            qvorbis_block_init(&format->vd, &format->vb);
        }
        qtheora_comment_init(&tc);
        /* create the remaining theora headers */
        qtheora_encode_header(&format->ts, &pt);
        qogg_stream_packetin(&format->to, &pt);
        if (qogg_stream_pageout (&format->to, &pg) != 1)
            fprintf (stderr, "Internal Ogg library error.\n");
        FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
        FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        qtheora_encode_comment(&tc, &pt);
        qogg_stream_packetin(&format->to, &pt);
        qtheora_encode_tables(&format->ts, &pt);
        qogg_stream_packetin (&format->to, &pt);
        qtheora_comment_clear(&tc);
        if(cls.capturevideo.soundrate)
        {
            qvorbis_analysis_headerout(&format->vd, &vc, &pt, &pt2, &pt3);
            qogg_stream_packetin(&format->vo, &pt);
            if (qogg_stream_pageout (&format->vo, &pg) != 1)
                fprintf (stderr, "Internal Ogg library error.\n");
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
            qogg_stream_packetin(&format->vo, &pt2);
            qogg_stream_packetin(&format->vo, &pt3);
            qvorbis_comment_clear(&vc);
        }
        for(;;)
        {
            int result = qogg_stream_flush (&format->to, &pg);
            if (result < 0)
                fprintf (stderr, "Internal Ogg library error.\n"); // TODO Sys_Error
            if (result <= 0)
                break;
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        }
        if(cls.capturevideo.soundrate)
        for(;;)
        {
            int result = qogg_stream_flush (&format->vo, &pg);
            if (result < 0)
                fprintf (stderr, "Internal Ogg library error.\n"); // TODO Sys_Error
            if (result <= 0)
                break;
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        }
    }
}
SCR_CaptureVideo_Ogg_CloseDLL()
void SCR_CaptureVideo_Ogg_CloseDLL (void)
Definition at line 598 of file cap_ogg.c.
{
    Sys_FreeLibrary (&ve_dll);
    Sys_FreeLibrary (&vo_dll);
    Sys_FreeLibrary (&th_dll);
    Sys_FreeLibrary (&og_dll);
}
SCR_CaptureVideo_Ogg_ConvertFrame_BGRA_to_YUV()
static void SCR_CaptureVideo_Ogg_ConvertFrame_BGRA_to_YUV (void) static
Definition at line 808 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    yuv_buffer *yuv;
    int x, y;
    int blockr, blockg, blockb;
    unsigned char *b;
    int w = cls.capturevideo.width;
    int h = cls.capturevideo.height;
    int inpitch = w*4;
    yuv = &format->yuv[format->yuvi];
    for(y = 0; y < h; ++y)
    {
        for(b = cls.capturevideo.outbuffer + (h-1-y)*w*4, x = 0; x < w; ++x)
        {
            blockr = b[2];
            blockg = b[1];
            blockb = b[0];
            yuv->y[x + yuv->y_stride * y] =
                cls.capturevideo.yuvnormalizetable[0][cls.capturevideo.rgbtoyuvscaletable[0][0][blockr] + cls.capturevideo.rgbtoyuvscaletable[0][1][blockg] + cls.capturevideo.rgbtoyuvscaletable[0][2][blockb]];
            b += 4;
        }
        if ((y & 1) == 0 && y/2 < h/2) // if h is odd, this skips the last row
        {
            for(b = cls.capturevideo.outbuffer + (h-2-y)*w*4, x = 0; x < w/2; ++x)
            {
                blockr = (b[2] + b[6] + b[inpitch+2] + b[inpitch+6]) >> 2;
                blockg = (b[1] + b[5] + b[inpitch+1] + b[inpitch+5]) >> 2;
                blockb = (b[0] + b[4] + b[inpitch+0] + b[inpitch+4]) >> 2;
                yuv->u[x + yuv->uv_stride * (y/2)] =
                    cls.capturevideo.yuvnormalizetable[1][cls.capturevideo.rgbtoyuvscaletable[1][0][blockr] + cls.capturevideo.rgbtoyuvscaletable[1][1][blockg] + cls.capturevideo.rgbtoyuvscaletable[1][2][blockb] + 128];
                yuv->v[x + yuv->uv_stride * (y/2)] =
                    cls.capturevideo.yuvnormalizetable[2][cls.capturevideo.rgbtoyuvscaletable[2][0][blockr] + cls.capturevideo.rgbtoyuvscaletable[2][1][blockg] + cls.capturevideo.rgbtoyuvscaletable[2][2][blockb] + 128];
                b += 8;
            }
        }
    }
}
Referenced by SCR_CaptureVideo_Ogg_VideoFrames().
SCR_CaptureVideo_Ogg_EndVideo()
static void SCR_CaptureVideo_Ogg_EndVideo (void) static
Definition at line 715 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    ogg_page pg;
    ogg_packet pt;
    if(format->yuvi >= 0)
    {
        // send the previous (and last) frame
        while(format->lastnum-- > 0)
        {
            qtheora_encode_YUVin(&format->ts, &format->yuv[format->yuvi]);
            while(qtheora_encode_packetout(&format->ts, !format->lastnum, &pt))
                qogg_stream_packetin(&format->to, &pt);
            SCR_CaptureVideo_Ogg_Interleave();
        }
    }
    if(cls.capturevideo.soundrate)
    {
        qvorbis_analysis_wrote(&format->vd, 0);
        while(qvorbis_analysis_blockout(&format->vd, &format->vb) == 1)
        {
            qvorbis_analysis(&format->vb, NULL);
            qvorbis_bitrate_addblock(&format->vb);
            while(qvorbis_bitrate_flushpacket(&format->vd, &pt))
                qogg_stream_packetin(&format->vo, &pt);
            SCR_CaptureVideo_Ogg_Interleave();
        }
    }
    SCR_CaptureVideo_Ogg_FlushInterleaving();
    while(qogg_stream_pageout(&format->to, &pg) > 0)
    {
        FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
        FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
    }
    if(cls.capturevideo.soundrate)
    {
        while(qogg_stream_pageout(&format->vo, &pg) > 0)
        {
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        }
    }
    while (1) {
        int result = qogg_stream_flush (&format->to, &pg);
        if (result < 0)
            fprintf (stderr, "Internal Ogg library error.\n"); // TODO Sys_Error
        if (result <= 0)
            break;
        FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
        FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
    }
    if(cls.capturevideo.soundrate)
    {
        while (1) {
            int result = qogg_stream_flush (&format->vo, &pg);
            if (result < 0)
                fprintf (stderr, "Internal Ogg library error.\n"); // TODO Sys_Error
            if (result <= 0)
                break;
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        }
        qogg_stream_clear(&format->vo);
        qvorbis_block_clear(&format->vb);
        qvorbis_dsp_clear(&format->vd);
    }
    qogg_stream_clear(&format->to);
    qtheora_clear(&format->ts);
    qvorbis_info_clear(&format->vi);
    Mem_Free(format->yuv[0].y);
    Mem_Free(format->yuv[0].u);
    Mem_Free(format->yuv[0].v);
    Mem_Free(format->yuv[1].y);
    Mem_Free(format->yuv[1].u);
    Mem_Free(format->yuv[1].v);
    Mem_Free(format);
    FS_Close(cls.capturevideo.videofile);
    cls.capturevideo.videofile = NULL;
}
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
SCR_CaptureVideo_Ogg_FlushInterleaving()
static void SCR_CaptureVideo_Ogg_FlushInterleaving (void) static
Definition at line 697 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    if(cls.capturevideo.soundrate)
    if(format->audiopage.len)
    {
        FS_Write(cls.capturevideo.videofile, format->audiopage.data, format->audiopage.len);
        format->audiopage.len = 0;
    }
    if(format->videopage.len)
    {
        FS_Write(cls.capturevideo.videofile, format->videopage.data, format->videopage.len);
        format->videopage.len = 0;
    }
}
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
SCR_CaptureVideo_Ogg_Init()
void SCR_CaptureVideo_Ogg_Init (void)
Definition at line 577 of file cap_ogg.c.
{
    SCR_CaptureVideo_Ogg_OpenLibrary();
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_vp3compat);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_quality);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_bitrate);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_keyframe_maxinterval);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_keyframe_mininterval);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_keyframe_auto_threshold);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_noise_sensitivity);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_theora_sharpness);
    Cvar_RegisterVariable(&cl_capturevideo_ogg_vorbis_quality);
}
Referenced by CL_Screen_Init().
SCR_CaptureVideo_Ogg_Interleave()
static void SCR_CaptureVideo_Ogg_Interleave (void) static
Definition at line 639 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    ogg_page pg;
    if(!cls.capturevideo.soundrate)
    {
        while(qogg_stream_pageout(&format->to, &pg) > 0)
        {
            FS_Write(cls.capturevideo.videofile, pg.header, pg.header_len);
            FS_Write(cls.capturevideo.videofile, pg.body, pg.body_len);
        }
        return;
    }
    for(;;)
    {
        // first: make sure we have a page of both types
        if(!format->videopage.len)
            if(qogg_stream_pageout(&format->to, &pg) > 0)
            {
                format->videopage.len = pg.header_len + pg.body_len;
                format->videopage.time = qtheora_granule_time(&format->ts, qogg_page_granulepos(&pg));
                if(format->videopage.len > sizeof(format->videopage.data))
                    Sys_Error("video page too long");
                memcpy(format->videopage.data, pg.header, pg.header_len);
                memcpy(format->videopage.data + pg.header_len, pg.body, pg.body_len);
            }
        if(!format->audiopage.len)
            if(qogg_stream_pageout(&format->vo, &pg) > 0)
            {
                format->audiopage.len = pg.header_len + pg.body_len;
                format->audiopage.time = qvorbis_granule_time(&format->vd, qogg_page_granulepos(&pg));
                if(format->audiopage.len > sizeof(format->audiopage.data))
                    Sys_Error("audio page too long");
                memcpy(format->audiopage.data, pg.header, pg.header_len);
                memcpy(format->audiopage.data + pg.header_len, pg.body, pg.body_len);
            }
        if(format->videopage.len && format->audiopage.len)
        {
            // output the page that ends first
            if(format->videopage.time < format->audiopage.time)
            {
                FS_Write(cls.capturevideo.videofile, format->videopage.data, format->videopage.len);
                format->videopage.len = 0;
            }
            else
            {
                FS_Write(cls.capturevideo.videofile, format->audiopage.data, format->audiopage.len);
                format->audiopage.len = 0;
            }
        }
        else
            break;
    }
}
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), SCR_CaptureVideo_Ogg_SoundFrame(), and SCR_CaptureVideo_Ogg_VideoFrames().
SCR_CaptureVideo_Ogg_OpenLibrary()
static qbool SCR_CaptureVideo_Ogg_OpenLibrary (void) static
Definition at line 508 of file cap_ogg.c.
{
    const char* dllnames_og [] =
    {
#if defined(WIN32)
        "libogg-0.dll",
        "libogg.dll",
        "ogg.dll",
#elif defined(MACOSX)
        "libogg.dylib",
#else
        "libogg.so.0",
        "libogg.so",
#endif
        NULL
    };
    const char* dllnames_vo [] =
    {
#if defined(WIN32)
        "libvorbis-0.dll",
        "libvorbis.dll",
        "vorbis.dll",
#elif defined(MACOSX)
        "libvorbis.dylib",
#else
        "libvorbis.so.0",
        "libvorbis.so",
#endif
        NULL
    };
    const char* dllnames_ve [] =
    {
#if defined(WIN32)
        "libvorbisenc-2.dll",
        "libvorbisenc.dll",
        "vorbisenc.dll",
#elif defined(MACOSX)
        "libvorbisenc.dylib",
#else
        "libvorbisenc.so.2",
        "libvorbisenc.so",
#endif
        NULL
    };
    const char* dllnames_th [] =
    {
#if defined(WIN32)
        "libtheora-0.dll",
        "libtheora.dll",
        "theora.dll",
#elif defined(MACOSX)
        "libtheora.dylib",
#else
        "libtheora.so.0",
        "libtheora.so",
#endif
        NULL
    };
    return
        Sys_LoadDependency (dllnames_og, &og_dll, oggfuncs)
        &&
        Sys_LoadDependency (dllnames_th, &th_dll, theorafuncs)
        &&
        Sys_LoadDependency (dllnames_vo, &vo_dll, vorbisfuncs)
        &&
        Sys_LoadDependency (dllnames_ve, &ve_dll, vorbisencfuncs);
}
Referenced by SCR_CaptureVideo_Ogg_Init().
SCR_CaptureVideo_Ogg_SoundFrame()
static void SCR_CaptureVideo_Ogg_SoundFrame (const portable_sampleframe_t * paintbuffer, size_t length) static
Definition at line 891 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    float **vorbis_buffer;
    size_t i;
    int j;
    ogg_packet pt;
    int *map = mapping[bound(1, cls.capturevideo.soundchannels, 8) - 1];
    vorbis_buffer = qvorbis_analysis_buffer(&format->vd, (int)length);
    for(j = 0; j < cls.capturevideo.soundchannels; ++j)
    {
        float *b = vorbis_buffer[map[j]];
        for(i = 0; i < length; ++i)
            b[i] = paintbuffer[i].sample[j];
    }
    qvorbis_analysis_wrote(&format->vd, (int)length);
    while(qvorbis_analysis_blockout(&format->vd, &format->vb) == 1)
    {
        qvorbis_analysis(&format->vb, NULL);
        qvorbis_bitrate_addblock(&format->vb);
        while(qvorbis_bitrate_flushpacket(&format->vd, &pt))
            qogg_stream_packetin(&format->vo, &pt);
    }
    SCR_CaptureVideo_Ogg_Interleave();
}
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
SCR_CaptureVideo_Ogg_VideoFrames()
static void SCR_CaptureVideo_Ogg_VideoFrames (int num) static
Definition at line 850 of file cap_ogg.c.
{
    LOAD_FORMATSPECIFIC_OGG();
    ogg_packet pt;
    // data is in cls.capturevideo.outbuffer as BGRA and has size width*height
    if(format->yuvi >= 0)
    {
        // send the previous frame
        while(format->lastnum-- > 0)
        {
            qtheora_encode_YUVin(&format->ts, &format->yuv[format->yuvi]);
            while(qtheora_encode_packetout(&format->ts, false, &pt))
                qogg_stream_packetin(&format->to, &pt);
            SCR_CaptureVideo_Ogg_Interleave();
        }
    }
    format->yuvi = (format->yuvi + 1) % 2;
    SCR_CaptureVideo_Ogg_ConvertFrame_BGRA_to_YUV();
    format->lastnum = num;
    // TODO maybe send num-1 frames from here already
}
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
Variable Documentation
cl_capturevideo_ogg_theora_bitrate
cvar_t cl_capturevideo_ogg_theora_bitrate = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_bitrate", "-1", "video bitrate (45 to 2000 kbps), or -1 to use quality only; higher is better; setting both to -1 achieves unlimited quality"} static
Definition at line 10 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_bitrate", "-1", "video bitrate (45 to 2000 kbps), or -1 to use quality only; higher is better; setting both to -1 achieves unlimited quality"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_keyframe_auto_threshold
cvar_t cl_capturevideo_ogg_theora_keyframe_auto_threshold = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_auto_threshold", "80", "threshold for key frame decision (0 to 100)"} static
Definition at line 14 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_auto_threshold", "80", "threshold for key frame decision (0 to 100)"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier
cvar_t cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier", "1.5", "how much more bit rate to use for keyframes, specified as a factor of at least 1"} static
Definition at line 11 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_bitrate_multiplier", "1.5", "how much more bit rate to use for keyframes, specified as a factor of at least 1"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_keyframe_maxinterval
cvar_t cl_capturevideo_ogg_theora_keyframe_maxinterval = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_maxinterval", "64", "maximum keyframe interval (1 to 1000)"} static
Definition at line 12 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_maxinterval", "64", "maximum keyframe interval (1 to 1000)"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_keyframe_mininterval
cvar_t cl_capturevideo_ogg_theora_keyframe_mininterval = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_mininterval", "8", "minimum keyframe interval (1 to 1000)"} static
Definition at line 13 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_keyframe_mininterval", "8", "minimum keyframe interval (1 to 1000)"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_noise_sensitivity
cvar_t cl_capturevideo_ogg_theora_noise_sensitivity = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_noise_sensitivity", "1", "video noise sensitivity (0 to 6); lower is better"} static
Definition at line 15 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_noise_sensitivity", "1", "video noise sensitivity (0 to 6); lower is better"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_quality
cvar_t cl_capturevideo_ogg_theora_quality = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_quality", "48", "video quality factor (0 to 63), or -1 to use bitrate only; higher is better; setting both to -1 achieves unlimited quality"} static
Definition at line 9 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_quality", "48", "video quality factor (0 to 63), or -1 to use bitrate only; higher is better; setting both to -1 achieves unlimited quality"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_sharpness
cvar_t cl_capturevideo_ogg_theora_sharpness = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_sharpness", "0", "sharpness (0 to 2); lower is sharper"} static
Definition at line 16 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_sharpness", "0", "sharpness (0 to 2); lower is sharper"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_theora_vp3compat
cvar_t cl_capturevideo_ogg_theora_vp3compat = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_vp3compat", "1", "make VP3 compatible theora streams"} static
Definition at line 8 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_theora_vp3compat", "1", "make VP3 compatible theora streams"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
cl_capturevideo_ogg_vorbis_quality
cvar_t cl_capturevideo_ogg_vorbis_quality = {CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_vorbis_quality", "3", "audio quality (-1 to 10); higher is better"} static
Definition at line 17 of file cap_ogg.c.
{CF_CLIENT | CF_ARCHIVE, "cl_capturevideo_ogg_vorbis_quality", "3", "audio quality (-1 to 10); higher is better"};
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_Init().
mapping
channelmapping_t mapping[8]
Initial value:
=
{
    { 0, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 2, -1, -1, -1, -1, -1 },
    { 0, 1, 2, 3, -1, -1, -1, -1 },
    { 0, 2, 3, 4, 1, -1, -1, -1 },
    { 0, 2, 3, 4, 1, 5, -1, -1 },
    { 0, 2, 3, 4, 1, 5, 6, -1 },
    { 0, 2, 3, 4, 1, 5, 6, 7 }
}
Definition at line 879 of file cap_ogg.c.
{
    { 0, -1, -1, -1, -1, -1, -1, -1 }, // mono
    { 0, 1, -1, -1, -1, -1, -1, -1 }, // stereo
    { 0, 1, 2, -1, -1, -1, -1, -1 }, // L C R
    { 0, 1, 2, 3, -1, -1, -1, -1 }, // surround40
    { 0, 2, 3, 4, 1, -1, -1, -1 }, // FL FC FR RL RR
    { 0, 2, 3, 4, 1, 5, -1, -1 }, // surround51
    { 0, 2, 3, 4, 1, 5, 6, -1 }, // (not defined by vorbis spec)
    { 0, 2, 3, 4, 1, 5, 6, 7 } // surround71 (not defined by vorbis spec)
};
Referenced by SCR_CaptureVideo_Ogg_SoundFrame().
og_dll
dllhandle_t og_dll = NULL static
Definition at line 506 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Available(), SCR_CaptureVideo_Ogg_CloseDLL(), and SCR_CaptureVideo_Ogg_OpenLibrary().
oggfuncs
dllfunction_t oggfuncs[] static
Initial value:
=
{
    {"ogg_stream_packetin", (void **) &qogg_stream_packetin},
    {"ogg_stream_pageout", (void **) &qogg_stream_pageout},
    {"ogg_stream_flush", (void **) &qogg_stream_flush},
    {"ogg_stream_init", (void **) &qogg_stream_init},
    {"ogg_stream_clear", (void **) &qogg_stream_clear},
    {"ogg_page_granulepos", (void **) &qogg_page_granulepos},
    {NULL, NULL}
}
Definition at line 449 of file cap_ogg.c.
{
    {"ogg_stream_packetin", (void **) &qogg_stream_packetin},
    {"ogg_stream_pageout", (void **) &qogg_stream_pageout},
    {"ogg_stream_flush", (void **) &qogg_stream_flush},
    {"ogg_stream_init", (void **) &qogg_stream_init},
    {"ogg_stream_clear", (void **) &qogg_stream_clear},
    {"ogg_page_granulepos", (void **) &qogg_page_granulepos},
    {NULL, NULL}
};
Referenced by SCR_CaptureVideo_Ogg_OpenLibrary().
qogg_page_granulepos
int64_t(* qogg_page_granulepos) (ogg_page *og) (ogg_page * og) static
Definition at line 113 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Interleave().
qogg_stream_clear
int(* qogg_stream_clear) (ogg_stream_state *os) (ogg_stream_state * os) static
Definition at line 112 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
qogg_stream_flush
int(* qogg_stream_flush) (ogg_stream_state *os, ogg_page *og) (ogg_stream_state * os, ogg_page * og) static
Definition at line 107 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), and SCR_CaptureVideo_Ogg_EndVideo().
qogg_stream_init
int(* qogg_stream_init) (ogg_stream_state *os, int serialno) (ogg_stream_state * os, int serialno) static
Definition at line 111 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qogg_stream_packetin
int(* qogg_stream_packetin) (ogg_stream_state *os, ogg_packet *op) (ogg_stream_state * os, ogg_packet * op) static
Definition at line 105 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), SCR_CaptureVideo_Ogg_EndVideo(), SCR_CaptureVideo_Ogg_SoundFrame(), and SCR_CaptureVideo_Ogg_VideoFrames().
qogg_stream_pageout
int(* qogg_stream_pageout) (ogg_stream_state *os, ogg_page *og) (ogg_stream_state * os, ogg_page * og) static
Definition at line 106 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo(), SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_Interleave().
qtheora_clear
void(* qtheora_clear) (theora_state *t) (theora_state * t) static
Definition at line 442 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
qtheora_comment_clear
void(* qtheora_comment_clear) (theora_comment *tc) (theora_comment * tc) static
Definition at line 444 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_comment_init
void(* qtheora_comment_init) (theora_comment *tc) (theora_comment * tc) static
Definition at line 443 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_control
int(* qtheora_control) (theora_state *th, int req, void *buf, size_t buf_sz) (theora_state * th, int req, void * buf, size_t buf_sz) static
Definition at line 446 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_encode_comment
int(* qtheora_encode_comment) (theora_comment *tc, ogg_packet *op) (theora_comment * tc, ogg_packet * op) static
Definition at line 438 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_encode_header
int(* qtheora_encode_header) (theora_state *t, ogg_packet *op) (theora_state * t, ogg_packet * op) static
Definition at line 437 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_encode_init
int(* qtheora_encode_init) (theora_state *th, theora_info *ti) (theora_state * th, theora_info * ti) static
Definition at line 433 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_encode_packetout
int(* qtheora_encode_packetout) (theora_state *t, int last_p, ogg_packet *op) (theora_state * t, int last_p, ogg_packet * op) static
Definition at line 435 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_VideoFrames().
qtheora_encode_tables
int(* qtheora_encode_tables) (theora_state *t, ogg_packet *op) (theora_state * t, ogg_packet * op) static
Definition at line 439 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_encode_YUVin
int(* qtheora_encode_YUVin) (theora_state *t, yuv_buffer *yuv) (theora_state * t, yuv_buffer * yuv) static
Definition at line 434 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_VideoFrames().
qtheora_granule_time
double(* qtheora_granule_time) (theora_state *th, int64_t granulepos) (theora_state * th, int64_t granulepos) static
Definition at line 445 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Interleave().
qtheora_info_clear
void(* qtheora_info_clear) (theora_info *c) (theora_info * c) static
Definition at line 441 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qtheora_info_init
void(* qtheora_info_init) (theora_info *c) (theora_info * c) static
Definition at line 440 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_analysis
int(* qvorbis_analysis) (vorbis_block *vb, ogg_packet *op) (vorbis_block * vb, ogg_packet * op) static
Definition at line 278 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_analysis_blockout
int(* qvorbis_analysis_blockout) (vorbis_dsp_state *v, vorbis_block *vb) (vorbis_dsp_state * v, vorbis_block * vb) static
Definition at line 277 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_analysis_buffer
float **(* qvorbis_analysis_buffer) (vorbis_dsp_state *v, int vals) (vorbis_dsp_state * v, int vals) static
Definition at line 275 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_analysis_headerout
int(* qvorbis_analysis_headerout) (vorbis_dsp_state *v, vorbis_comment *vc, ogg_packet *op, ogg_packet *op_comm, ogg_packet *op_code) (vorbis_dsp_state * v, vorbis_comment * vc, ogg_packet * op, ogg_packet * op_comm, ogg_packet * op_code) static
Definition at line 270 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_analysis_init
int(* qvorbis_analysis_init) (vorbis_dsp_state *v, vorbis_info *vi) (vorbis_dsp_state * v, vorbis_info * vi) static
Definition at line 268 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_analysis_wrote
int(* qvorbis_analysis_wrote) (vorbis_dsp_state *v, int vals) (vorbis_dsp_state * v, int vals) static
Definition at line 276 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_bitrate_addblock
int(* qvorbis_bitrate_addblock) (vorbis_block *vb) (vorbis_block * vb) static
Definition at line 280 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_bitrate_flushpacket
int(* qvorbis_bitrate_flushpacket) (vorbis_dsp_state *vd, ogg_packet *op) (vorbis_dsp_state * vd, ogg_packet * op) static
Definition at line 281 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo(), and SCR_CaptureVideo_Ogg_SoundFrame().
qvorbis_block_clear
int(* qvorbis_block_clear) (vorbis_block *vb) (vorbis_block * vb) static
Definition at line 261 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
qvorbis_block_init
int(* qvorbis_block_init) (vorbis_dsp_state *v, vorbis_block *vb) (vorbis_dsp_state * v, vorbis_block * vb) static
Definition at line 260 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_comment_clear
void(* qvorbis_comment_clear) (vorbis_comment *vc) (vorbis_comment * vc) static
Definition at line 258 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_comment_init
void(* qvorbis_comment_init) (vorbis_comment *vc) (vorbis_comment * vc) static
Definition at line 257 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_commentheader_out
int(* qvorbis_commentheader_out) (vorbis_comment *vc, ogg_packet *op) (vorbis_comment * vc, ogg_packet * op) static
Definition at line 269 of file cap_ogg.c.
qvorbis_dsp_clear
void(* qvorbis_dsp_clear) (vorbis_dsp_state *v) (vorbis_dsp_state * v) static
Definition at line 262 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
qvorbis_encode_init_vbr
int(* qvorbis_encode_init_vbr) (vorbis_info *vi, long channels, long rate, float base_quality) (vorbis_info * vi, long channels, long rate, float base_quality) static
Definition at line 287 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
qvorbis_granule_time
double(* qvorbis_granule_time) (vorbis_dsp_state *v, int64_t granulepos) (vorbis_dsp_state * v, int64_t granulepos) static
Definition at line 263 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Interleave().
qvorbis_info_clear
void(* qvorbis_info_clear) (vorbis_info *vi) (vorbis_info * vi) static
Definition at line 256 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_EndVideo().
qvorbis_info_init
void(* qvorbis_info_init) (vorbis_info *vi) (vorbis_info * vi) static
Definition at line 255 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_BeginVideo().
th_dll
dllhandle_t th_dll = NULL static
Definition at line 506 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Available(), SCR_CaptureVideo_Ogg_CloseDLL(), and SCR_CaptureVideo_Ogg_OpenLibrary().
theorafuncs
dllfunction_t theorafuncs[] static
Initial value:
=
{
    {"theora_info_init", (void **) &qtheora_info_init},
    {"theora_info_clear", (void **) &qtheora_info_clear},
    {"theora_comment_init", (void **) &qtheora_comment_init},
    {"theora_comment_clear", (void **) &qtheora_comment_clear},
    {"theora_encode_init", (void **) &qtheora_encode_init},
    {"theora_encode_YUVin", (void **) &qtheora_encode_YUVin},
    {"theora_encode_packetout", (void **) &qtheora_encode_packetout},
    {"theora_encode_header", (void **) &qtheora_encode_header},
    {"theora_encode_comment", (void **) &qtheora_encode_comment},
    {"theora_encode_tables", (void **) &qtheora_encode_tables},
    {"theora_clear", (void **) &qtheora_clear},
    {"theora_granule_time", (void **) &qtheora_granule_time},
    {"theora_control", (void **) &qtheora_control},
    {NULL, NULL}
}
Definition at line 488 of file cap_ogg.c.
{
    {"theora_info_init", (void **) &qtheora_info_init},
    {"theora_info_clear", (void **) &qtheora_info_clear},
    {"theora_comment_init", (void **) &qtheora_comment_init},
    {"theora_comment_clear", (void **) &qtheora_comment_clear},
    {"theora_encode_init", (void **) &qtheora_encode_init},
    {"theora_encode_YUVin", (void **) &qtheora_encode_YUVin},
    {"theora_encode_packetout", (void **) &qtheora_encode_packetout},
    {"theora_encode_header", (void **) &qtheora_encode_header},
    {"theora_encode_comment", (void **) &qtheora_encode_comment},
    {"theora_encode_tables", (void **) &qtheora_encode_tables},
    {"theora_clear", (void **) &qtheora_clear},
    {"theora_granule_time", (void **) &qtheora_granule_time},
    {"theora_control", (void **) &qtheora_control},
    {NULL, NULL}
};
Referenced by SCR_CaptureVideo_Ogg_OpenLibrary().
ve_dll
dllhandle_t ve_dll = NULL static
Definition at line 506 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Available(), SCR_CaptureVideo_Ogg_CloseDLL(), and SCR_CaptureVideo_Ogg_OpenLibrary().
vo_dll
dllhandle_t vo_dll = NULL static
Definition at line 506 of file cap_ogg.c.
Referenced by SCR_CaptureVideo_Ogg_Available(), SCR_CaptureVideo_Ogg_CloseDLL(), and SCR_CaptureVideo_Ogg_OpenLibrary().
vorbisencfuncs
dllfunction_t vorbisencfuncs[] static
Initial value:
=
{
    {"vorbis_encode_init_vbr", (void **) &qvorbis_encode_init_vbr},
    {NULL, NULL}
}
Definition at line 460 of file cap_ogg.c.
{
    {"vorbis_encode_init_vbr", (void **) &qvorbis_encode_init_vbr},
    {NULL, NULL}
};
Referenced by SCR_CaptureVideo_Ogg_OpenLibrary().
vorbisfuncs
dllfunction_t vorbisfuncs[] static
Initial value:
=
{
    {"vorbis_info_init", (void **) &qvorbis_info_init},
    {"vorbis_info_clear", (void **) &qvorbis_info_clear},
    {"vorbis_comment_init", (void **) &qvorbis_comment_init},
    {"vorbis_comment_clear", (void **) &qvorbis_comment_clear},
    {"vorbis_block_init", (void **) &qvorbis_block_init},
    {"vorbis_block_clear", (void **) &qvorbis_block_clear},
    {"vorbis_dsp_clear", (void **) &qvorbis_dsp_clear},
    {"vorbis_analysis_init", (void **) &qvorbis_analysis_init},
    {"vorbis_commentheader_out", (void **) &qvorbis_commentheader_out},
    {"vorbis_analysis_headerout", (void **) &qvorbis_analysis_headerout},
    {"vorbis_analysis_buffer", (void **) &qvorbis_analysis_buffer},
    {"vorbis_analysis_wrote", (void **) &qvorbis_analysis_wrote},
    {"vorbis_analysis_blockout", (void **) &qvorbis_analysis_blockout},
    {"vorbis_analysis", (void **) &qvorbis_analysis},
    {"vorbis_bitrate_addblock", (void **) &qvorbis_bitrate_addblock},
    {"vorbis_bitrate_flushpacket", (void **) &qvorbis_bitrate_flushpacket},
    {"vorbis_granule_time", (void **) &qvorbis_granule_time},
    {NULL, NULL}
}
Definition at line 466 of file cap_ogg.c.
{
    {"vorbis_info_init", (void **) &qvorbis_info_init},
    {"vorbis_info_clear", (void **) &qvorbis_info_clear},
    {"vorbis_comment_init", (void **) &qvorbis_comment_init},
    {"vorbis_comment_clear", (void **) &qvorbis_comment_clear},
    {"vorbis_block_init", (void **) &qvorbis_block_init},
    {"vorbis_block_clear", (void **) &qvorbis_block_clear},
    {"vorbis_dsp_clear", (void **) &qvorbis_dsp_clear},
    {"vorbis_analysis_init", (void **) &qvorbis_analysis_init},
    {"vorbis_commentheader_out", (void **) &qvorbis_commentheader_out},
    {"vorbis_analysis_headerout", (void **) &qvorbis_analysis_headerout},
    {"vorbis_analysis_buffer", (void **) &qvorbis_analysis_buffer},
    {"vorbis_analysis_wrote", (void **) &qvorbis_analysis_wrote},
    {"vorbis_analysis_blockout", (void **) &qvorbis_analysis_blockout},
    {"vorbis_analysis", (void **) &qvorbis_analysis},
    {"vorbis_bitrate_addblock", (void **) &qvorbis_bitrate_addblock},
    {"vorbis_bitrate_flushpacket", (void **) &qvorbis_bitrate_flushpacket},
    {"vorbis_granule_time", (void **) &qvorbis_granule_time},
    {NULL, NULL}
};
Referenced by SCR_CaptureVideo_Ogg_OpenLibrary().