DarkPlaces: cdaudio.h File Reference
cdaudio.h File Reference
#include "qtypes.h"
#include "cvar.h"
Functions
int CDAudio_Init (void)
void CDAudio_Play (int track, qbool looping)
void CDAudio_Stop (void)
void CDAudio_Pause (void)
void CDAudio_Resume (void)
int CDAudio_Startup (void)
void CDAudio_Shutdown (void)
void CDAudio_Update (void)
float CDAudio_GetPosition (void)
Variables
cvar_t cdaudioinitialized
Function Documentation
CDAudio_GetPosition()
float CDAudio_GetPosition (void)
Definition at line 220 of file cd_shared.c.
{
    if(faketrack != -1)
        return S_GetChannelPosition(faketrack);
    return -1;
}
CDAudio_Init()
int CDAudio_Init (void)
Definition at line 544 of file cd_shared.c.
{
    int i;
    if (cls.state == ca_dedicated)
        return -1;
// COMMANDLINEOPTION: Sound: -nocdaudio disables CD audio support
    if (Sys_CheckParm("-nocdaudio"))
        return -1;
#ifdef MAXTRACKS
    for (i = 0; i < MAXTRACKS; i++)
        *remap[i] = 0;
#endif
    Cvar_RegisterVariable(&cdaudioinitialized);
    Cvar_SetValueQuick(&cdaudioinitialized, true);
    enabled = true;
    Cvar_RegisterVariable(&music_playlist_index);
    for (i = 0;i < MAX_PLAYLISTS;i++)
    {
        Cvar_RegisterVariable(&music_playlist_list[i]);
        Cvar_RegisterVariable(&music_playlist_current[i]);
        Cvar_RegisterVariable(&music_playlist_random[i]);
        Cvar_RegisterVariable(&music_playlist_sampleposition[i]);
    }
    Cmd_AddCommand(CF_CLIENT | CF_CLIENT_FROM_SERVER, "cd", CD_f, "execute a CD drive command (cd on/off/reset/remap/close/play/loop/stop/pause/resume/eject/info) - use cd by itself for usage");
    return 0;
}
Referenced by S_Init().
CDAudio_Pause()
void CDAudio_Pause (void)
Definition at line 247 of file cd_shared.c.
{
    if (!enabled || !cdPlaying || faketrack == -1)
        return;
    S_SetChannelFlag (faketrack, CHANNELFLAG_PAUSED, true);
    wasPlaying = cdPlaying;
    cdPlaying = false;
}
Referenced by CD_f(), CDAudio_Play_byName(), CDAudio_SetVolume(), and CL_ParseServerMessage().
CDAudio_Play()
void CDAudio_Play (int track, qbool looping)
Definition at line 211 of file cd_shared.c.
{
    char buf[20];
    if (music_playlist_index.integer >= 0)
        return;
    dpsnprintf(buf, sizeof(buf), "%d", (int) track);
    CDAudio_Play_byName(buf, looping, true, 0);
}
Referenced by CL_ParseServerMessage().
CDAudio_Resume()
void CDAudio_Resume (void)
Definition at line 258 of file cd_shared.c.
{
    if (!enabled || cdPlaying || !wasPlaying || faketrack == -1)
        return;
    S_SetChannelFlag (faketrack, CHANNELFLAG_PAUSED, false);
    cdPlaying = true;
}
Referenced by CD_f(), CDAudio_SetVolume(), and CL_ParseServerMessage().
CDAudio_Shutdown()
void CDAudio_Shutdown (void)
Definition at line 590 of file cd_shared.c.
{
    if (!initialized)
        return;
    CDAudio_Stop();
    initialized = false;
}
Referenced by CD_f(), and S_Shutdown().
CDAudio_Startup()
int CDAudio_Startup (void)
Definition at line 578 of file cd_shared.c.
{
    if (Sys_CheckParm("-nocdaudio"))
        return -1;
    initialized = true;
    Con_Print("CD Audio Initialized\n");
    return 0;
}
Referenced by CD_f(), and S_Startup().
CDAudio_Stop()
void CDAudio_Stop (void)
Definition at line 229 of file cd_shared.c.
{
    if (!enabled)
        return;
    // save the playlist position
    CDAudio_StopPlaylistTrack();
    if (faketrack != -1)
    {
        S_StopChannel (faketrack, true, true);
        faketrack = -1;
    }
    wasPlaying = false;
    cdPlaying = false;
}
Referenced by CD_f(), CDAudio_Play_byName(), CDAudio_Shutdown(), CDAudio_StartPlaylist(), and S_StopAllSounds().
CDAudio_Update()
void CDAudio_Update (void)
Definition at line 522 of file cd_shared.c.
{
    static int lastplaylist = -1;
    if (!enabled)
        return;
    CDAudio_SetVolume (bgmvolume.value);
    if (music_playlist_playing > 0 && CDAudio_GetPosition() < 0)
    {
        // this track ended, start a new track from the beginning
        CDAudio_StartPlaylist(false);
        lastplaylist = music_playlist_index.integer;
    }
    else if (lastplaylist != music_playlist_index.integer
    || (bgmvolume.value > 0 && !music_playlist_playing && music_playlist_index.integer >= 0))
    {
        // active playlist changed, save position and switch track
        CDAudio_StartPlaylist(true);
        lastplaylist = music_playlist_index.integer;
    }
}
Referenced by CL_Frame().
Variable Documentation
cdaudioinitialized
cvar_t cdaudioinitialized extern
Definition at line 28 of file cd_shared.c.
{CF_CLIENT | CF_READONLY,"cdaudioinitialized","0","indicates if CD Audio system is active"};
Referenced by CDAudio_Init(), and M_Options_Draw().