DarkPlaces: cl_video.c File Reference
cl_video.c File Reference
#include "quakedef.h"
#include "cl_video.h"
#include "dpvsimpledecode.h"
#include "cl_video_libavw.h"
Data Structures
struct cl_video_subtitle_info_t
Functions
static clvideo_t * FindUnusedVid (void)
static qbool OpenStream (clvideo_t *video)
static void VideoUpdateCallback (rtexture_t *rt, void *data)
static void LinkVideoTexture (clvideo_t *video)
static void UnlinkVideoTexture (clvideo_t *video)
static void SuspendVideo (clvideo_t *video)
static qbool WakeVideo (clvideo_t *video)
static void LoadSubtitles (clvideo_t *video, const char *subtitlesfile)
static clvideo_t * OpenVideo (clvideo_t *video, const char *filename, const char *name, int owner, const char *subtitlesfile)
clvideo_t * CL_OpenVideo (const char *filename, const char *name, int owner, const char *subtitlesfile)
static clvideo_t * CL_GetVideoBySlot (int slot)
clvideo_t * CL_GetVideoByName (const char *name)
void CL_SetVideoState (clvideo_t *video, clvideostate_t state)
void CL_RestartVideo (clvideo_t *video)
void CL_CloseVideo (clvideo_t *video)
void CL_Video_Frame (void)
void CL_PurgeOwner (int owner)
static float CL_DrawVideo_WordWidthFunc (void *passthrough, const char *w, size_t *length, float maxWidth)
static int CL_DrawVideo_DisplaySubtitleLine (void *passthrough, const char *line, size_t length, float width, qbool isContinuation)
void CL_DrawVideo (void)
void CL_VideoStart (char *filename, const char *subtitlesfile)
void CL_Video_KeyEvent (int key, int ascii, qbool down)
void CL_VideoStop (void)
static void CL_PlayVideo_f (cmd_state_t *cmd)
static void CL_StopVideo_f (cmd_state_t *cmd)
static void cl_video_start (void)
static void cl_video_shutdown (void)
static void cl_video_newmap (void)
void CL_Video_Init (void)
void CL_Video_Shutdown (void)
Variables
cvar_t cl_video_subtitles = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles", "0", "show subtitles for videos (if they are present)"}
cvar_t cl_video_subtitles_lines = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_lines", "4", "how many lines to occupy for subtitles"}
cvar_t cl_video_subtitles_textsize = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_textsize", "16", "textsize for subtitles"}
cvar_t cl_video_scale = {CF_CLIENT | CF_ARCHIVE, "cl_video_scale", "1", "scale of video, 1 = fullscreen, 0.75 - 3/4 of screen etc."}
cvar_t cl_video_scale_vpos = {CF_CLIENT | CF_ARCHIVE, "cl_video_scale_vpos", "0", "vertical align of scaled video, -1 is top, 1 is bottom"}
cvar_t cl_video_stipple = {CF_CLIENT | CF_ARCHIVE, "cl_video_stipple", "0", "draw interlacing-like effect on videos, similar to scr_stipple but static and used only with video playing."}
cvar_t cl_video_brightness = {CF_CLIENT | CF_ARCHIVE, "cl_video_brightness", "1", "brightness of video, 1 = fullbright, 0.75 - 3/4 etc."}
cvar_t cl_video_keepaspectratio = {CF_CLIENT | CF_ARCHIVE, "cl_video_keepaspectratio", "0", "keeps aspect ratio of fullscreen videos, leaving black color on unfilled areas, a value of 2 let video to be stretched horizontally with top & bottom being sliced out"}
cvar_t cl_video_fadein = {CF_CLIENT | CF_ARCHIVE, "cl_video_fadein", "0", "fading-from-black effect once video is started, in seconds"}
cvar_t cl_video_fadeout = {CF_CLIENT | CF_ARCHIVE, "cl_video_fadeout", "0", "fading-to-black effect once video is ended, in seconds"}
cvar_t v_glslgamma_video = {CF_CLIENT | CF_ARCHIVE, "v_glslgamma_video", "1", "applies GLSL gamma to played video, could be a fraction, requires r_glslgamma_2d 1."}
static int cl_videormask
static int cl_videobmask
static int cl_videogmask
static int cl_videobytesperpixel
static int cl_num_videos
static clvideo_t cl_videos [MAXCLVIDEOS]
static rtexturepool_t * cl_videotexturepool
int cl_videoplaying = false
Function Documentation
CL_CloseVideo()
void CL_CloseVideo (clvideo_t * video)
Definition at line 327 of file cl_video.c.
{
    int i;
    if (!video || video->state == CLVIDEO_UNUSED)
        return;
    // close stream
    if (!video->suspended || video->state != CLVIDEO_FIRSTFRAME)
    {
        if (video->stream)
            video->close(video->stream);
        video->stream = NULL;
    }
    // unlink texture
    if (!video->suspended)
        UnlinkVideoTexture(video);
    // purge subtitles
    if (video->subtitles)
    {
        for (i = 0; i < video->subtitles; i++)
            Z_Free( video->subtitle_text[i] );
        video->subtitles = 0;
    }
    video->state = CLVIDEO_UNUSED;
}
Referenced by CL_PurgeOwner(), CL_Video_Shutdown(), CL_VideoStart(), CL_VideoStop(), and VM_cin_close().
CL_DrawVideo()
void CL_DrawVideo (void)
Definition at line 460 of file cl_video.c.
{
    clvideo_t *video;
    float videotime, px, py, sx, sy, st[8], b;
    cl_video_subtitle_info_t si;
    int i;
    if (!cl_videoplaying)
        return;
    video = CL_GetVideoBySlot( 0 );
    // fix cvars
    if (cl_video_scale.value <= 0 || cl_video_scale.value > 1)
        Cvar_SetValueQuick( &cl_video_scale, 1);
    if (cl_video_brightness.value <= 0 || cl_video_brightness.value > 10)
        Cvar_SetValueQuick( &cl_video_brightness, 1);
    // calc video proportions
    px = 0;
    py = 0;
    sx = vid_conwidth.integer;
    sy = vid_conheight.integer;
    st[0] = 0.0; st[1] = 0.0;
    st[2] = 1.0; st[3] = 0.0;
    st[4] = 0.0; st[5] = 1.0;
    st[6] = 1.0; st[7] = 1.0;
    if (cl_video_keepaspectratio.integer)
    {
        float a = video->getaspectratio(video->stream) / ((float)vid.width / (float)vid.height);
        if (cl_video_keepaspectratio.integer >= 2)
        {
            // clip instead of scale
            if (a < 1.0) // clip horizontally
            {
                st[1] = st[3] = (1 - a)*0.5;
                st[5] = st[7] = 1 - (1 - a)*0.5;
            }
            else if (a > 1.0) // clip vertically
            {
                st[0] = st[4] = (1 - 1/a)*0.5;
                st[2] = st[6] = (1/a)*0.5;
            }
        }
        else if (a < 1.0) // scale horizontally
        {
            px += sx * (1 - a) * 0.5;
            sx *= a;
        }
        else if (a > 1.0) // scale vertically
        {
            a = 1 / a;
            py += sy * (1 - a);
            sy *= a;
        }
    }
    if (cl_video_scale.value != 1)
    {
        px += sx * (1 - cl_video_scale.value) * 0.5;
        py += sy * (1 - cl_video_scale.value) * ((bound(-1, cl_video_scale_vpos.value, 1) + 1) / 2);
        sx *= cl_video_scale.value;
        sy *= cl_video_scale.value;
    }
    // calc brightness for fadein and fadeout effects
    b = cl_video_brightness.value;
    if (cl_video_fadein.value && (host.realtime - video->starttime) < cl_video_fadein.value)
        b = pow((host.realtime - video->starttime)/cl_video_fadein.value, 2);
    else if (cl_video_fadeout.value && ((video->starttime + video->framenum * video->framerate) - host.realtime) < cl_video_fadeout.value)
        b = pow(((video->starttime + video->framenum * video->framerate) - host.realtime)/cl_video_fadeout.value, 2);
    // draw black bg in case stipple is active or video is scaled
    if (cl_video_stipple.integer || px != 0 || py != 0 || sx != vid_conwidth.integer || sy != vid_conheight.integer)
        DrawQ_Fill(0, 0, vid_conwidth.integer, vid_conheight.integer, 0, 0, 0, 1, 0);
    // enable video-only polygon stipple (of global stipple is not active)
    if (!scr_stipple.integer && cl_video_stipple.integer)
    {
        Con_Print("FIXME: cl_video_stipple not implemented\n");
        Cvar_SetValueQuick(&cl_video_stipple, 0);
    }
    // draw video
    if (v_glslgamma_video.value >= 1)
        DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, 1, st[2], st[3], b, b, b, 1, st[4], st[5], b, b, b, 1, st[6], st[7], b, b, b, 1, 0);
    else
    {
        DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, 1, st[2], st[3], b, b, b, 1, st[4], st[5], b, b, b, 1, st[6], st[7], b, b, b, 1, DRAWFLAG_NOGAMMA);
        if (v_glslgamma_video.value > 0.0)
            DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, v_glslgamma_video.value, st[2], st[3], b, b, b, v_glslgamma_video.value, st[4], st[5], b, b, b, v_glslgamma_video.value, st[6], st[7], b, b, b, v_glslgamma_video.value, 0);
    }
    // VorteX: draw subtitle_text
    if (!video->subtitles || !cl_video_subtitles.integer)
        return;
    // find current subtitle
    videotime = host.realtime - video->starttime;
    for (i = 0; i < video->subtitles; i++)
    {
        if (videotime >= video->subtitle_start[i] && videotime <= video->subtitle_end[i])
        {
            // found, draw it
            si.font = FONT_NOTIFY;
            si.x = vid_conwidth.integer * 0.1;
            si.y = vid_conheight.integer - (max(1, cl_video_subtitles_lines.value) * cl_video_subtitles_textsize.value);
            si.width = vid_conwidth.integer * 0.8;
            si.height = max(1, cl_video_subtitles_lines.integer) * cl_video_subtitles_textsize.value;
            si.alignment = 0.5;
            si.fontsize = cl_video_subtitles_textsize.value;
            si.textalpha = min(1, (videotime - video->subtitle_start[i])/0.5) * min(1, ((video->subtitle_end[i] - videotime)/0.3)); // fade in and fade out
            COM_Wordwrap(video->subtitle_text[i], strlen(video->subtitle_text[i]), 0, si.width, CL_DrawVideo_WordWidthFunc, &si, CL_DrawVideo_DisplaySubtitleLine, &si);
            break;
        }
    }
}
Referenced by SCR_DrawScreen().
CL_DrawVideo_DisplaySubtitleLine()
static int CL_DrawVideo_DisplaySubtitleLine (void * passthrough, const char * line, size_t length, float width, qbool isContinuation) static
Definition at line 447 of file cl_video.c.
{
    cl_video_subtitle_info_t *si = (cl_video_subtitle_info_t *) passthrough;
    int x = (int) (si->x + (si->width - width) * si->alignment);
    if (length > 0)
        DrawQ_String(x, si->y, line, length, si->fontsize, si->fontsize, 1.0, 1.0, 1.0, si->textalpha, 0, NULL, false, si->font);
    si->y += si->fontsize;
    return 1;
}
Referenced by CL_DrawVideo().
CL_DrawVideo_WordWidthFunc()
static float CL_DrawVideo_WordWidthFunc (void * passthrough, const char * w, size_t * length, float maxWidth) static
Definition at line 433 of file cl_video.c.
{
    cl_video_subtitle_info_t *si = (cl_video_subtitle_info_t *) passthrough;
    if(w == NULL)
        return si->fontsize * si->font->maxwidth;
    if(maxWidth >= 0)
        return DrawQ_TextWidth_UntilWidth(w, length, si->fontsize, si->fontsize, false, si->font, -maxWidth); // -maxWidth: we want at least one char
    else if(maxWidth == -1)
        return DrawQ_TextWidth(w, *length, si->fontsize, si->fontsize, false, si->font);
    else
        return 0;
}
Referenced by CL_DrawVideo().
CL_GetVideoByName()
clvideo_t * CL_GetVideoByName (const char * name)
Definition at line 284 of file cl_video.c.
{
    int i;
    for( i = 0 ; i < cl_num_videos ; i++ )
        if( cl_videos[ i ].state != CLVIDEO_UNUSED
            &&  !strcmp( cl_videos[ i ].name , name ) )
            break;
    if( i != cl_num_videos )
        return CL_GetVideoBySlot( i );
    else
        return NULL;
}
Referenced by VM_cin_close(), VM_cin_getstate(), VM_cin_restart(), and VM_cin_setstate().
CL_GetVideoBySlot()
static clvideo_t * CL_GetVideoBySlot (int slot) static
Definition at line 267 of file cl_video.c.
{
    clvideo_t *video = &cl_videos[ slot ];
    if( video->suspended )
    {
        if( !WakeVideo( video ) )
            return NULL;
        else if( video->state == CLVIDEO_RESETONWAKEUP )
            video->framenum = -1;
    }
    video->lasttime = host.realtime;
    return video;
}
Referenced by CL_DrawVideo(), and CL_GetVideoByName().
CL_OpenVideo()
clvideo_t * CL_OpenVideo (const char * filename, const char * name, int owner, const char * subtitlesfile)
Definition at line 245 of file cl_video.c.
{
    clvideo_t *video;
    // sanity check
    if( !name || !*name || strncmp( name, CLVIDEOPREFIX, sizeof( CLVIDEOPREFIX ) - 1 ) != 0 ) {
        Con_DPrintf( "CL_OpenVideo: Bad video texture name '%s'!\n", name );
        return NULL;
    }
    video = FindUnusedVid();
    if( !video ) {
        Con_Printf(CON_ERROR "CL_OpenVideo: unable to open video \"%s\" - video limit reached\n", filename );
        return NULL;
    }
    video = OpenVideo( video, filename, name, owner, subtitlesfile );
    // expand the active range to include the new entry
    if (video) {
        cl_num_videos = max(cl_num_videos, (int)(video - cl_videos) + 1);
    }
    return video;
}
Referenced by VM_cin_open().
CL_PlayVideo_f()
static void CL_PlayVideo_f (cmd_state_t * cmd) static
Definition at line 613 of file cl_video.c.
{
    char name[MAX_QPATH], subtitlesfile[MAX_QPATH];
    const char *extension;
    CL_StartVideo();
    if (Sys_CheckParm("-benchmark"))
        return;
    if (Cmd_Argc(cmd) < 2)
    {
        Con_Print("usage: playvideo <videoname> [custom_subtitles_file]\nplays video named video/<videoname>.dpv\nif custom subtitles file is not presented\nit tries video/<videoname>.sub");
        return;
    }
    extension = FS_FileExtension(Cmd_Argv(cmd, 1));
    if (extension[0])
        dpsnprintf(name, sizeof(name), "video/%s", Cmd_Argv(cmd, 1));
    else
        dpsnprintf(name, sizeof(name), "video/%s.dpv", Cmd_Argv(cmd, 1));
    if ( Cmd_Argc(cmd) > 2)
        CL_VideoStart(name, Cmd_Argv(cmd, 2));
    else
    {
        dpsnprintf(subtitlesfile, sizeof(subtitlesfile), "video/%s.dpsubs", Cmd_Argv(cmd, 1));
        CL_VideoStart(name, subtitlesfile);
    }
}
Referenced by CL_Video_Init().
CL_PurgeOwner()
void CL_PurgeOwner (int owner)
Definition at line 411 of file cl_video.c.
{
    int i;
    for (i = 0 ; i < cl_num_videos ; i++)
        if (cl_videos[i].ownertag == owner)
            CL_CloseVideo(&cl_videos[i]);
}
Referenced by VM_Cmd_Reset().
CL_RestartVideo()
void CL_RestartVideo (clvideo_t * video)
Definition at line 309 of file cl_video.c.
{
    if (!video)
        return;
    // reset time
    video->starttime = video->lasttime = host.realtime;
    video->framenum = -1;
    // reopen stream
    if (video->stream)
        video->close(video->stream);
    video->stream = NULL;
    if (!OpenStream(video))
        video->state = CLVIDEO_UNUSED;
}
Referenced by CL_SetVideoState(), CL_Video_Frame(), CL_VideoStart(), and VM_cin_restart().
CL_SetVideoState()
void CL_SetVideoState (clvideo_t * video, clvideostate_t state)
Definition at line 298 of file cl_video.c.
{
    if (!video)
        return;
    video->lasttime = host.realtime;
    video->state = state;
    if (state == CLVIDEO_FIRSTFRAME)
        CL_RestartVideo(video);
}
Referenced by CL_VideoStart(), and VM_cin_setstate().
CL_StopVideo_f()
static void CL_StopVideo_f (cmd_state_t * cmd) static
Definition at line 643 of file cl_video.c.
{
    CL_VideoStop();
}
Referenced by CL_Video_Init().
CL_Video_Frame()
void CL_Video_Frame (void)
Definition at line 355 of file cl_video.c.
{
    clvideo_t *video;
    int destframe;
    int i;
    if (!cl_num_videos)
        return;
    for (video = cl_videos, i = 0 ; i < cl_num_videos ; video++, i++)
    {
        if (video->state != CLVIDEO_UNUSED && !video->suspended)
        {
            if (host.realtime - video->lasttime > CLTHRESHOLD)
            {
                SuspendVideo(video);
                continue;
            }
            if (video->state == CLVIDEO_PAUSE)
            {
                video->starttime = host.realtime - video->framenum * video->framerate;
                continue;
            }
            // read video frame from stream if time has come
            if (video->state == CLVIDEO_FIRSTFRAME )
                destframe = 0;
            else
                destframe = (int)((host.realtime - video->starttime) * video->framerate);
            if (destframe < 0)
                destframe = 0;
            if (video->framenum < destframe)
            {
                do {
                    video->framenum++;
                    if (video->decodeframe(video->stream, video->imagedata, cl_videormask, cl_videogmask, cl_videobmask, cl_videobytesperpixel, cl_videobytesperpixel * video->width))
                    {
                        // finished?
                        CL_RestartVideo(video);
                        if (video->state == CLVIDEO_PLAY)
                            video->state = CLVIDEO_FIRSTFRAME;
                        return;
                    }
                } while(video->framenum < destframe);
                R_MarkDirtyTexture(Draw_GetPicTexture(video->cachepic));
            }
        }
    }
    // stop main video
    if (cl_videos->state == CLVIDEO_FIRSTFRAME)
        CL_VideoStop();
    // reduce range to exclude unnecessary entries
    while(cl_num_videos > 0 && cl_videos[cl_num_videos-1].state == CLVIDEO_UNUSED)
        cl_num_videos--;
}
Referenced by CL_Frame().
CL_Video_Init()
void CL_Video_Init (void)
Definition at line 675 of file cl_video.c.
{
    union
    {
        unsigned char b[4];
        unsigned int i;
    }
    bgra;
    cl_num_videos = 0;
    cl_videobytesperpixel = 4;
    // set masks in an endian-independent way (as they really represent bytes)
    bgra.i = 0;bgra.b[0] = 0xFF;cl_videobmask = bgra.i;
    bgra.i = 0;bgra.b[1] = 0xFF;cl_videogmask = bgra.i;
    bgra.i = 0;bgra.b[2] = 0xFF;cl_videormask = bgra.i;
    Cmd_AddCommand(CF_CLIENT, "playvideo", CL_PlayVideo_f, "play a .dpv video file" );
    Cmd_AddCommand(CF_CLIENT, "stopvideo", CL_StopVideo_f, "stop playing a .dpv video file" );
    Cvar_RegisterVariable(&cl_video_subtitles);
    Cvar_RegisterVariable(&cl_video_subtitles_lines);
    Cvar_RegisterVariable(&cl_video_subtitles_textsize);
    Cvar_RegisterVariable(&cl_video_scale);
    Cvar_RegisterVariable(&cl_video_scale_vpos);
    Cvar_RegisterVariable(&cl_video_brightness);
    Cvar_RegisterVariable(&cl_video_stipple);
    Cvar_RegisterVariable(&cl_video_keepaspectratio);
    Cvar_RegisterVariable(&cl_video_fadein);
    Cvar_RegisterVariable(&cl_video_fadeout);
    Cvar_RegisterVariable(&v_glslgamma_video);
    R_RegisterModule( "CL_Video", cl_video_start, cl_video_shutdown, cl_video_newmap, NULL, NULL );
    LibAvW_OpenLibrary();
}
Referenced by CL_Init().
CL_Video_KeyEvent()
void CL_Video_KeyEvent (int key, int ascii, qbool down)
Definition at line 596 of file cl_video.c.
{
    // only react to up events, to allow the user to delay the abortion point if it suddenly becomes interesting..
    if( !down ) {
        if( key == K_ESCAPE || key == K_ENTER || key == K_SPACE ) {
            CL_VideoStop();
        }
    }
}
Referenced by Key_Event().
cl_video_newmap()
static void cl_video_newmap (void) static
Definition at line 671 of file cl_video.c.
{
}
Referenced by CL_Video_Init().
cl_video_shutdown()
static void cl_video_shutdown (void) static
Definition at line 660 of file cl_video.c.
{
    int i;
    clvideo_t *video;
    for( video = cl_videos, i = 0 ; i < cl_num_videos ; i++, video++ )
        if( video->state != CLVIDEO_UNUSED && !video->suspended )
            SuspendVideo( video );
    R_FreeTexturePool( &cl_videotexturepool );
}
Referenced by CL_Video_Init().
CL_Video_Shutdown()
void CL_Video_Shutdown (void)
Definition at line 713 of file cl_video.c.
{
    int i;
    for (i = 0 ; i < cl_num_videos ; i++)
        CL_CloseVideo(&cl_videos[ i ]);
    LibAvW_CloseLibrary();
}
Referenced by CL_Shutdown().
cl_video_start()
static void cl_video_start (void) static
Definition at line 648 of file cl_video.c.
{
    int i;
    clvideo_t *video;
    cl_videotexturepool = R_AllocTexturePool();
    for( video = cl_videos, i = 0 ; i < cl_num_videos ; i++, video++ )
        if( video->state != CLVIDEO_UNUSED && !video->suspended )
            LinkVideoTexture( video );
}
Referenced by CL_Video_Init().
CL_VideoStart()
void CL_VideoStart (char * filename, const char * subtitlesfile)
Definition at line 578 of file cl_video.c.
{
    CL_StartVideo();
    if( cl_videos->state != CLVIDEO_UNUSED )
        CL_CloseVideo( cl_videos );
    // already contains video/
    if( !OpenVideo( cl_videos, filename, filename, 0, subtitlesfile ) )
        return;
    // expand the active range to include the new entry
    cl_num_videos = max(cl_num_videos, 1);
    cl_videoplaying = true;
    CL_SetVideoState( cl_videos, CLVIDEO_PLAY );
    CL_RestartVideo( cl_videos );
}
Referenced by CL_PlayVideo_f().
CL_VideoStop()
void CL_VideoStop (void)
Definition at line 606 of file cl_video.c.
{
    cl_videoplaying = false;
    CL_CloseVideo( cl_videos );
}
Referenced by CL_ParseServerInfo(), CL_StopVideo_f(), CL_Video_Frame(), and CL_Video_KeyEvent().
FindUnusedVid()
static clvideo_t * FindUnusedVid (void) static
Definition at line 40 of file cl_video.c.
{
    int i;
    for( i = 1 ; i < MAXCLVIDEOS ; i++ )
        if( cl_videos[ i ].state == CLVIDEO_UNUSED )
            return &cl_videos[ i ];
    return NULL;
}
Referenced by CL_OpenVideo().
LinkVideoTexture()
static void LinkVideoTexture (clvideo_t * video) static
Definition at line 77 of file cl_video.c.
{
    video->cachepic = Draw_NewPic(video->name, video->width, video->height, NULL, TEXTYPE_BGRA, TEXF_CLAMP);
    // make R_GetTexture() call our VideoUpdateCallback
    R_MakeTextureDynamic(Draw_GetPicTexture(video->cachepic), VideoUpdateCallback, video);
}
Referenced by cl_video_start(), OpenVideo(), and WakeVideo().
LoadSubtitles()
static void LoadSubtitles (clvideo_t * video, const char * subtitlesfile) static
Definition at line 128 of file cl_video.c.
{
    char *subtitle_text;
    const char *data;
    float subtime, sublen;
    int numsubs = 0;
    if (gamemode == GAME_BLOODOMNICIDE)
    {
        char overridename[MAX_QPATH];
        cvar_t *langcvar;
        langcvar = Cvar_FindVar(&cvars_all, "language", CF_CLIENT | CF_SERVER);
        subtitle_text = NULL;
        if (langcvar)
        {
            dpsnprintf(overridename, sizeof(overridename), "locale/%s/%s", langcvar->string, subtitlesfile);
            subtitle_text = (char *)FS_LoadFile(overridename, cls.permanentmempool, false, NULL);
        }
        if (!subtitle_text)
            subtitle_text = (char *)FS_LoadFile(subtitlesfile, cls.permanentmempool, false, NULL);
    }
    else
    {
        subtitle_text = (char *)FS_LoadFile(subtitlesfile, cls.permanentmempool, false, NULL);
    }
    if (!subtitle_text)
    {
        Con_DPrintf( "LoadSubtitles: can't open subtitle file '%s'!\n", subtitlesfile );
        return;
    }
    // parse subtitle_text
    // line is: x y "text" where
    //    x - start time
    //    y - seconds last (if 0 - last thru next sub, if negative - last to next sub - this amount of seconds)
    data = subtitle_text;
    for (;;)
    {
        if (!COM_ParseToken_QuakeC(&data, false))
            break;
        subtime = atof( com_token );
        if (!COM_ParseToken_QuakeC(&data, false))
            break;
        sublen = atof( com_token );
        if (!COM_ParseToken_QuakeC(&data, false))
            break;
        if (!com_token[0])
            continue;
        // check limits
        if (video->subtitles == CLVIDEO_MAX_SUBTITLES)
        {
            Con_Printf(CON_WARN "WARNING: CLVIDEO_MAX_SUBTITLES = %i reached when reading subtitles from '%s'\n", CLVIDEO_MAX_SUBTITLES, subtitlesfile);
            break;
        }
        // add a sub
        video->subtitle_text[numsubs] = (char *) Mem_Alloc(cls.permanentmempool, strlen(com_token) + 1);
        memcpy(video->subtitle_text[numsubs], com_token, strlen(com_token) + 1);
        video->subtitle_start[numsubs] = subtime;
        video->subtitle_end[numsubs] = sublen;
        if (numsubs > 0) // make true len for prev sub, autofix overlapping subtitles
        {
            if (video->subtitle_end[numsubs-1] <= 0)
                video->subtitle_end[numsubs-1] = max(video->subtitle_start[numsubs-1], video->subtitle_start[numsubs] + video->subtitle_end[numsubs-1]);
            else
                video->subtitle_end[numsubs-1] = min(video->subtitle_start[numsubs-1] + video->subtitle_end[numsubs-1], video->subtitle_start[numsubs]);
        }
        numsubs++;
        // todo: check timing for consistency?
    }
    if (numsubs > 0) // make true len for prev sub, autofix overlapping subtitles
    {
        if (video->subtitle_end[numsubs-1] <= 0)
            video->subtitle_end[numsubs-1] = (float)99999999; // fixme: make it end when video ends?
        else
            video->subtitle_end[numsubs-1] = video->subtitle_start[numsubs-1] + video->subtitle_end[numsubs-1];
    }
    Z_Free( subtitle_text );
    video->subtitles = numsubs;
/*
    Con_Printf( "video->subtitles: %i\n", video->subtitles );
    for (numsubs = 0; numsubs < video->subtitles; numsubs++)
        Con_Printf( "  %03.2f %03.2f : %s\n", video->subtitle_start[numsubs], video->subtitle_end[numsubs], video->subtitle_text[numsubs] );
*/
}
Referenced by OpenVideo().
OpenStream()
static qbool OpenStream (clvideo_t * video) static
Definition at line 49 of file cl_video.c.
{
    const char *errorstring;
    video->stream = dpvsimpledecode_open( video, video->filename, &errorstring);
    if (video->stream)
        return true;
#ifdef JAMVIDEO
    video->stream = jam_open( video, video->filename, &errorstring);
    if (video->stream)
        return true;
#endif
    video->stream = LibAvW_OpenVideo( video, video->filename, &errorstring);
    if (video->stream)
        return true;
    Con_Printf(CON_ERROR "unable to open \"%s\", error: %s\n", video->filename, errorstring);
    return false;
}
Referenced by CL_RestartVideo(), OpenVideo(), and WakeVideo().
OpenVideo()
static clvideo_t * OpenVideo (clvideo_t * video, const char * filename, const char * name, int owner, const char * subtitlesfile) static
Definition at line 215 of file cl_video.c.
{
    dp_strlcpy(video->filename, filename, sizeof(video->filename));
    dpsnprintf(video->name, sizeof(video->name), CLVIDEOPREFIX "%s", name);
    video->ownertag = owner;
    if( strncmp( name, CLVIDEOPREFIX, sizeof( CLVIDEOPREFIX ) - 1 ) )
        return NULL;
    video->cachepic = Draw_CachePic_Flags(name, CACHEPICFLAG_NOTPERSISTENT | CACHEPICFLAG_QUIET);
    if( !OpenStream( video ) )
        return NULL;
    video->state = CLVIDEO_FIRSTFRAME;
    video->framenum = -1;
    video->framerate = video->getframerate( video->stream );
    video->lasttime = host.realtime;
    video->subtitles = 0;
    video->width = video->getwidth( video->stream );
    video->height = video->getheight( video->stream );
    video->imagedata = Mem_Alloc( cls.permanentmempool, video->width * video->height * cl_videobytesperpixel );
    LinkVideoTexture( video );
    // VorteX: load simple subtitle_text file
    if (subtitlesfile[0])
        LoadSubtitles( video, subtitlesfile );
    return video;
}
Referenced by CL_OpenVideo(), and CL_VideoStart().
SuspendVideo()
static void SuspendVideo (clvideo_t * video) static
Definition at line 92 of file cl_video.c.
{
    if (video->suspended)
        return;
    video->suspended = true;
    UnlinkVideoTexture(video);
    // if we are in firstframe mode, also close the stream
    if (video->state == CLVIDEO_FIRSTFRAME)
    {
        if (video->stream)
            video->close(video->stream);
        video->stream = NULL;
    }
}
Referenced by CL_Video_Frame(), and cl_video_shutdown().
UnlinkVideoTexture()
static void UnlinkVideoTexture (clvideo_t * video) static
Definition at line 84 of file cl_video.c.
{
    // free the texture (this does not destroy the cachepic_t, which is eternal)
    Draw_FreePic(video->name);
    // free the image data
    Mem_Free( video->imagedata );
}
Referenced by CL_CloseVideo(), and SuspendVideo().
VideoUpdateCallback()
static void VideoUpdateCallback (rtexture_t * rt, void * data) static
Definition at line 71 of file cl_video.c.
{
    clvideo_t *video = (clvideo_t *) data;
    Draw_NewPic(video->name, video->width, video->height, (unsigned char *)video->imagedata, TEXTYPE_BGRA, TEXF_CLAMP);
}
Referenced by LinkVideoTexture().
WakeVideo()
static qbool WakeVideo (clvideo_t * video) static
Definition at line 107 of file cl_video.c.
{
    if( !video->suspended )
        return true;
    video->suspended = false;
    if( video->state == CLVIDEO_FIRSTFRAME )
        if( !OpenStream( video ) ) {
            video->state = CLVIDEO_UNUSED;
            return false;
        }
    video->imagedata = Mem_Alloc( cls.permanentmempool, video->width * video->height * cl_videobytesperpixel );
    LinkVideoTexture( video );
    // update starttime
    video->starttime += host.realtime - video->lasttime;
    return true;
}
Referenced by CL_GetVideoBySlot().
Variable Documentation
cl_num_videos
int cl_num_videos static
Definition at line 36 of file cl_video.c.
Referenced by CL_GetVideoByName(), CL_OpenVideo(), CL_PurgeOwner(), CL_Video_Frame(), CL_Video_Init(), cl_video_shutdown(), CL_Video_Shutdown(), cl_video_start(), and CL_VideoStart().
cl_video_brightness
cvar_t cl_video_brightness = {CF_CLIENT | CF_ARCHIVE, "cl_video_brightness", "1", "brightness of video, 1 = fullbright, 0.75 - 3/4 etc."}
Definition at line 12 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_brightness", "1", "brightness of video, 1 = fullbright, 0.75 - 3/4 etc."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_fadein
cvar_t cl_video_fadein = {CF_CLIENT | CF_ARCHIVE, "cl_video_fadein", "0", "fading-from-black effect once video is started, in seconds"}
Definition at line 14 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_fadein", "0", "fading-from-black effect once video is started, in seconds"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_fadeout
cvar_t cl_video_fadeout = {CF_CLIENT | CF_ARCHIVE, "cl_video_fadeout", "0", "fading-to-black effect once video is ended, in seconds"}
Definition at line 15 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_fadeout", "0", "fading-to-black effect once video is ended, in seconds"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_keepaspectratio
cvar_t cl_video_keepaspectratio = {CF_CLIENT | CF_ARCHIVE, "cl_video_keepaspectratio", "0", "keeps aspect ratio of fullscreen videos, leaving black color on unfilled areas, a value of 2 let video to be stretched horizontally with top & bottom being sliced out"}
Definition at line 13 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_keepaspectratio", "0", "keeps aspect ratio of fullscreen videos, leaving black color on unfilled areas, a value of 2 let video to be stretched horizontally with top & bottom being sliced out"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_scale
cvar_t cl_video_scale = {CF_CLIENT | CF_ARCHIVE, "cl_video_scale", "1", "scale of video, 1 = fullscreen, 0.75 - 3/4 of screen etc."}
Definition at line 9 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_scale", "1", "scale of video, 1 = fullscreen, 0.75 - 3/4 of screen etc."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_scale_vpos
cvar_t cl_video_scale_vpos = {CF_CLIENT | CF_ARCHIVE, "cl_video_scale_vpos", "0", "vertical align of scaled video, -1 is top, 1 is bottom"}
Definition at line 10 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_scale_vpos", "0", "vertical align of scaled video, -1 is top, 1 is bottom"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_stipple
cvar_t cl_video_stipple = {CF_CLIENT | CF_ARCHIVE, "cl_video_stipple", "0", "draw interlacing-like effect on videos, similar to scr_stipple but static and used only with video playing."}
Definition at line 11 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_stipple", "0", "draw interlacing-like effect on videos, similar to scr_stipple but static and used only with video playing."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles
cvar_t cl_video_subtitles = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles", "0", "show subtitles for videos (if they are present)"}
Definition at line 6 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles", "0", "show subtitles for videos (if they are present)"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles_lines
cvar_t cl_video_subtitles_lines = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_lines", "4", "how many lines to occupy for subtitles"}
Definition at line 7 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_lines", "4", "how many lines to occupy for subtitles"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles_textsize
cvar_t cl_video_subtitles_textsize = {CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_textsize", "16", "textsize for subtitles"}
Definition at line 8 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_textsize", "16", "textsize for subtitles"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_videobmask
int cl_videobmask static
Definition at line 32 of file cl_video.c.
Referenced by CL_Video_Frame(), and CL_Video_Init().
cl_videobytesperpixel
int cl_videobytesperpixel static
Definition at line 34 of file cl_video.c.
Referenced by CL_Video_Frame(), CL_Video_Init(), OpenVideo(), and WakeVideo().
cl_videogmask
int cl_videogmask static
Definition at line 33 of file cl_video.c.
Referenced by CL_Video_Frame(), and CL_Video_Init().
cl_videoplaying
int cl_videoplaying = false
Definition at line 458 of file cl_video.c.
Referenced by CL_DrawVideo(), CL_VideoStart(), CL_VideoStop(), Key_Event(), R_RenderView(), and VM_CL_videoplaying().
cl_videormask
int cl_videormask static
Definition at line 31 of file cl_video.c.
Referenced by CL_Video_Frame(), and CL_Video_Init().
cl_videos
clvideo_t cl_videos[MAXCLVIDEOS] static
Definition at line 37 of file cl_video.c.
Referenced by CL_GetVideoByName(), CL_GetVideoBySlot(), CL_OpenVideo(), CL_PurgeOwner(), CL_Video_Frame(), cl_video_shutdown(), CL_Video_Shutdown(), cl_video_start(), CL_VideoStart(), CL_VideoStop(), and FindUnusedVid().
cl_videotexturepool
rtexturepool_t* cl_videotexturepool static
Definition at line 38 of file cl_video.c.
Referenced by cl_video_shutdown(), and cl_video_start().
v_glslgamma_video
cvar_t v_glslgamma_video = {CF_CLIENT | CF_ARCHIVE, "v_glslgamma_video", "1", "applies GLSL gamma to played video, could be a fraction, requires r_glslgamma_2d 1."}
Definition at line 17 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "v_glslgamma_video", "1", "applies GLSL gamma to played video, could be a fraction, requires r_glslgamma_2d 1."};
Referenced by CL_DrawVideo(), and CL_Video_Init().