DarkPlaces: cl_video_libavw.h File Reference
cl_video_libavw.h File Reference
#include "quakedef.h"
#include "cl_video.h"
Functions
void libavw_close (void *stream)
void * LibAvW_OpenVideo (clvideo_t *video, char *filename, const char **errorstring)
qbool LibAvW_OpenLibrary (void)
void LibAvW_CloseLibrary (void)
Function Documentation
libavw_close()
void libavw_close (void * stream)
Definition at line 222 of file cl_video_libavw.c.
{
    libavwstream_t *s = (libavwstream_t *)stream;
    if (s->stream)
        qLibAvW_RemoveStream(s->stream);
    s->stream = NULL;
    if (s->file)
        FS_Close(s->file);
    s->file = NULL;
    if (s->sndchan >= 0)
        S_StopChannel(s->sndchan, true, true);
    s->sndchan = -1;
}
Referenced by LibAvW_OpenVideo().
LibAvW_CloseLibrary()
void LibAvW_CloseLibrary (void)
Definition at line 385 of file cl_video_libavw.c.
{
    Sys_FreeLibrary(&libavw_dll);
}
Referenced by CL_Video_Shutdown().
LibAvW_OpenLibrary()
qbool LibAvW_OpenLibrary (void)
Definition at line 358 of file cl_video_libavw.c.
{
    int errorcode;
    // COMMANDLINEOPTION: Video: -nolibavw disables libavcodec wrapper support
    if (Sys_CheckParm("-nolibavw"))
        return false;
    // load DLL's
    Sys_LoadDependency(dllnames_libavw, &libavw_dll, libavwfuncs);
    if (!libavw_dll)
        return false;
    // initialize libav wrapper
    if ((errorcode = qLibAvW_Init(&libavw_message)))
    {
        Con_Printf(CON_ERROR "LibAvW failed to initialize: %s\n", qLibAvW_ErrorString(errorcode));
        Sys_FreeLibrary(&libavw_dll);
    }
    Cvar_RegisterVariable(&cl_video_libavw_minwidth);
    Cvar_RegisterVariable(&cl_video_libavw_minheight);
    Cvar_RegisterVariable(&cl_video_libavw_scaler);
    return true;
}
Referenced by CL_Video_Init().
LibAvW_OpenVideo()
void * LibAvW_OpenVideo (clvideo_t * video, char * filename, const char ** errorstring)
Definition at line 252 of file cl_video_libavw.c.
{
    libavwstream_t *s;
    char filebase[MAX_OSPATH], check[MAX_OSPATH];
    unsigned int i;
    int errorcode;
    char *wavename;
    size_t len;
    if (!libavw_dll)
        return NULL;
    // allocate stream
    s = (libavwstream_t *)Z_Malloc(sizeof(libavwstream_t));
    if (s == NULL)
    {
        *errorstring = "unable to allocate memory for stream info structure";
        return NULL;
    }
    memset(s, 0, sizeof(libavwstream_t));
    s->sndchan = -1;
    // open file
    s->file = FS_OpenVirtualFile(filename, true);
    if (!s->file)
    {
        FS_StripExtension(filename, filebase, sizeof(filebase));
        // we tried .dpv, try another extensions
        for (i = 0; libavw_extensions[i] != NULL; i++)
        {
            dpsnprintf(check, sizeof(check), "%s.%s", filebase, libavw_extensions[i]);
            s->file = FS_OpenVirtualFile(check, true);
            if (s->file)
                break;
        }
        if (!s->file)
        {
            *errorstring = "unable to open videofile";
            libavw_close(s);
            Z_Free(s);
             return NULL;
        }
    }
    // allocate libavw stream
    if ((errorcode = qLibAvW_CreateStream(&s->stream)))
    {
        *errorstring = qLibAvW_ErrorString(errorcode);
        libavw_close(s);
        Z_Free(s);
        return NULL;
    }
    // open video for playing
    if (!qLibAvW_PlayVideo(s->stream, s->file, &LibAvW_FS_Read, &LibAvW_FS_Seek, &LibAvW_FS_SeekSize))
    {
        *errorstring = qLibAvW_ErrorString(qLibAvW_StreamGetError(s->stream));
        libavw_close(s);
        Z_Free(s);
        return NULL;
    }
    // all right, start codec
    s->info_imagewidth = qLibAvW_StreamGetVideoWidth(s->stream);
    s->info_imageheight = qLibAvW_StreamGetVideoHeight(s->stream);
    s->info_framerate = qLibAvW_StreamGetFramerate(s->stream);
    s->info_aspectratio = (double)s->info_imagewidth / (double)s->info_imageheight;
    video->close = libavw_close;
    video->getwidth = libavw_getwidth;
    video->getheight = libavw_getheight;
    video->getframerate = libavw_getframerate;
    video->decodeframe = libavw_decodeframe;
    video->getaspectratio = libavw_getaspectratio;
    // apply min-width, min-height, keep aspect rate
    if (cl_video_libavw_minwidth.integer > 0)
        s->info_imagewidth = max(s->info_imagewidth, (unsigned int)cl_video_libavw_minwidth.integer);
    if (cl_video_libavw_minheight.integer > 0)
        s->info_imageheight = max(s->info_imageheight, (unsigned int)cl_video_libavw_minheight.integer);
    // provide sound in separate .wav
    len = strlen(filename) + 10;
    wavename = (char *)Z_Malloc(len);
    if (wavename)
    {
        FS_StripExtension(filename, wavename, len-1);
        dp_strlcat(wavename, ".wav", len);
        s->sfx = S_PrecacheSound(wavename, false, false);
        s->sndchan = -1;
        Z_Free(wavename);
    }
    return s;
}
Referenced by OpenStream().