DarkPlaces: cl_video_libavw.c File Reference
cl_video_libavw.c File Reference
#include "quakedef.h"
#include "client.h"
#include "cl_video.h"
#include "cl_video_libavw.h"
Data Structures
struct libavwstream_t
Macros
#define LIBAVW_SCALER_BILINEAR 0
#define LIBAVW_SCALER_BICUBIC 1
#define LIBAVW_SCALER_X 2
#define LIBAVW_SCALER_POINT 3
#define LIBAVW_SCALER_AREA 4
#define LIBAVW_SCALER_BICUBLIN 5
#define LIBAVW_SCALER_GAUSS 6
#define LIBAVW_SCALER_SINC 7
#define LIBAVW_SCALER_LANCZOS 8
#define LIBAVW_SCALER_SPLINE 9
#define LIBAVW_PIXEL_FORMAT_BGR 0
#define LIBAVW_PIXEL_FORMAT_BGRA 1
#define LIBAVW_PRINT_WARNING 1
#define LIBAVW_PRINT_ERROR 2
#define LIBAVW_PRINT_FATAL 3
#define LIBAVW_PRINT_PANIC 4
Typedefs
typedef void avwCallbackPrint(int, const char *)
typedef int avwCallbackIoRead(void *, uint8_t *, int)
typedef uint64_t avwCallbackIoSeek(void *, uint64_t, int)
typedef uint64_t avwCallbackIoSeekSize(void *)
Functions
unsigned int libavw_getwidth (void *stream)
unsigned int libavw_getheight (void *stream)
double libavw_getframerate (void *stream)
double libavw_getaspectratio (void *stream)
void libavw_close (void *stream)
static int libavw_decodeframe (void *stream, void *imagedata, unsigned int Rmask, unsigned int Gmask, unsigned int Bmask, unsigned int bytesperpixel, int imagebytesperrow)
static int LibAvW_FS_Read (void *opaque, uint8_t *buf, int buf_size)
static uint64_t LibAvW_FS_Seek (void *opaque, uint64_t pos, int whence)
static uint64_t LibAvW_FS_SeekSize (void *opaque)
void * LibAvW_OpenVideo (clvideo_t *video, char *filename, const char **errorstring)
static void libavw_message (int level, const char *message)
qbool LibAvW_OpenLibrary (void)
void LibAvW_CloseLibrary (void)
Variables
int(* qLibAvW_Init)(avwCallbackPrint *printfunction)
const char *(* qLibAvW_ErrorString)(int errorcode)
const char *(* qLibAvW_AvcVersion)(void)
float(* qLibAvW_Version)(void)
int(* qLibAvW_CreateStream)(void **stream)
void(* qLibAvW_RemoveStream)(void *stream)
int(* qLibAvW_StreamGetVideoWidth)(void *stream)
int(* qLibAvW_StreamGetVideoHeight)(void *stream)
double(* qLibAvW_StreamGetFramerate)(void *stream)
int(* qLibAvW_StreamGetError)(void *stream)
int(* qLibAvW_PlayVideo)(void *stream, void *file, avwCallbackIoRead *IoRead, avwCallbackIoSeek *IoSeek, avwCallbackIoSeekSize *IoSeekSize)
int(* qLibAvW_PlaySeekNextFrame)(void *stream)
int(* qLibAvW_PlayGetFrameImage)(void *stream, int pixel_format, void *imagedata, int imagewidth, int imageheight, int scaler)
static dllfunction_t libavwfuncs []
const char * dllnames_libavw []
static dllhandle_t libavw_dll = NULL
cvar_t cl_video_libavw_minwidth = {CF_ARCHIVE, "cl_video_libavw_minwidth", "0", "if videos width is lesser than minimal, thay will be upscaled"}
cvar_t cl_video_libavw_minheight = {CF_ARCHIVE, "cl_video_libavw_minheight", "0", "if videos height is lesser than minimal, thay will be upscaled"}
cvar_t cl_video_libavw_scaler = {CF_ARCHIVE, "cl_video_libavw_scaler", "1", "selects a scaler for libavcode played videos. Scalers are: 0 - bilinear, 1 - bicubic, 2 - x, 3 - point, 4 - area, 5 - bicublin, 6 - gauss, 7 - sinc, 8 - lanczos, 9 - spline."}
const char * libavw_extensions []
Macro Definition Documentation
LIBAVW_PIXEL_FORMAT_BGR
#define LIBAVW_PIXEL_FORMAT_BGR 0
Definition at line 43 of file cl_video_libavw.c.
LIBAVW_PIXEL_FORMAT_BGRA
#define LIBAVW_PIXEL_FORMAT_BGRA 1
Definition at line 44 of file cl_video_libavw.c.
LIBAVW_PRINT_ERROR
#define LIBAVW_PRINT_ERROR 2
Definition at line 47 of file cl_video_libavw.c.
LIBAVW_PRINT_FATAL
#define LIBAVW_PRINT_FATAL 3
Definition at line 48 of file cl_video_libavw.c.
LIBAVW_PRINT_PANIC
#define LIBAVW_PRINT_PANIC 4
Definition at line 49 of file cl_video_libavw.c.
LIBAVW_PRINT_WARNING
#define LIBAVW_PRINT_WARNING 1
Definition at line 46 of file cl_video_libavw.c.
LIBAVW_SCALER_AREA
#define LIBAVW_SCALER_AREA 4
Definition at line 36 of file cl_video_libavw.c.
LIBAVW_SCALER_BICUBIC
#define LIBAVW_SCALER_BICUBIC 1
Definition at line 33 of file cl_video_libavw.c.
LIBAVW_SCALER_BICUBLIN
#define LIBAVW_SCALER_BICUBLIN 5
Definition at line 37 of file cl_video_libavw.c.
LIBAVW_SCALER_BILINEAR
#define LIBAVW_SCALER_BILINEAR 0
Definition at line 32 of file cl_video_libavw.c.
LIBAVW_SCALER_GAUSS
#define LIBAVW_SCALER_GAUSS 6
Definition at line 38 of file cl_video_libavw.c.
LIBAVW_SCALER_LANCZOS
#define LIBAVW_SCALER_LANCZOS 8
Definition at line 40 of file cl_video_libavw.c.
LIBAVW_SCALER_POINT
#define LIBAVW_SCALER_POINT 3
Definition at line 35 of file cl_video_libavw.c.
LIBAVW_SCALER_SINC
#define LIBAVW_SCALER_SINC 7
Definition at line 39 of file cl_video_libavw.c.
LIBAVW_SCALER_SPLINE
#define LIBAVW_SCALER_SPLINE 9
Definition at line 41 of file cl_video_libavw.c.
LIBAVW_SCALER_X
#define LIBAVW_SCALER_X 2
Definition at line 34 of file cl_video_libavw.c.
Typedef Documentation
avwCallbackIoRead
typedef int avwCallbackIoRead(void *, uint8_t *, int)
Definition at line 52 of file cl_video_libavw.c.
avwCallbackIoSeek
typedef uint64_t avwCallbackIoSeek(void *, uint64_t, int)
Definition at line 53 of file cl_video_libavw.c.
avwCallbackIoSeekSize
typedef uint64_t avwCallbackIoSeekSize(void *)
Definition at line 54 of file cl_video_libavw.c.
avwCallbackPrint
typedef void avwCallbackPrint(int, const char *)
Definition at line 51 of file cl_video_libavw.c.
Function Documentation
libavw_close()
void libavw_close (void * stream)
Definition at line 222 of file cl_video_libavw.c.
{
    libavwstream_t *s = (libavwstream_t *)stream;
    if (s->stream)
        qLibAvW_RemoveStream(s->stream);
    s->stream = NULL;
    if (s->file)
        FS_Close(s->file);
    s->file = NULL;
    if (s->sndchan >= 0)
        S_StopChannel(s->sndchan, true, true);
    s->sndchan = -1;
}
Referenced by LibAvW_OpenVideo().
LibAvW_CloseLibrary()
void LibAvW_CloseLibrary (void)
Definition at line 385 of file cl_video_libavw.c.
{
    Sys_FreeLibrary(&libavw_dll);
}
Referenced by CL_Video_Shutdown().
libavw_decodeframe()
static int libavw_decodeframe (void * stream, void * imagedata, unsigned int Rmask, unsigned int Gmask, unsigned int Bmask, unsigned int bytesperpixel, int imagebytesperrow) static
Definition at line 160 of file cl_video_libavw.c.
{
    int pixel_format = LIBAVW_PIXEL_FORMAT_BGR;
    int errorcode;
    libavwstream_t *s = (libavwstream_t *)stream;
    // start sound
    if (!s->sndstarted)
    {
        if (s->sfx != NULL)
            s->sndchan = S_StartSound(-1, 0, s->sfx, vec3_origin, 1.0f, 0);
        s->sndstarted = 1;
    }
    // read frame
    if (!qLibAvW_PlaySeekNextFrame(s->stream))
    {
        // got error or file end
        errorcode = qLibAvW_StreamGetError(s->stream);
        if (errorcode)
            Con_Printf(CON_ERROR "LibAvW: %s\n", qLibAvW_ErrorString(errorcode));
        return 1;
    }
    // decode into bgr texture
    if (bytesperpixel == 4)
        pixel_format = LIBAVW_PIXEL_FORMAT_BGRA;
    else if (bytesperpixel == 3)
        pixel_format = LIBAVW_PIXEL_FORMAT_BGR;
    else
    {
        Con_Printf(CON_ERROR "LibAvW: cannot determine pixel format for bpp %i\n", bytesperpixel);
        return 1;
    }
    if (!qLibAvW_PlayGetFrameImage(s->stream, pixel_format, imagedata, s->info_imagewidth, s->info_imageheight, min(9, max(0, cl_video_libavw_scaler.integer))))
        Con_Printf(CON_ERROR "LibAvW: %s\n", qLibAvW_ErrorString(qLibAvW_StreamGetError(s->stream)));
    return 0;
}
Referenced by LibAvW_OpenVideo().
LibAvW_FS_Read()
static int LibAvW_FS_Read (void * opaque, uint8_t * buf, int buf_size) static
Definition at line 238 of file cl_video_libavw.c.
{
    return FS_Read((qfile_t *)opaque, buf, buf_size);
}
Referenced by LibAvW_OpenVideo().
LibAvW_FS_Seek()
static uint64_t LibAvW_FS_Seek (void * opaque, uint64_t pos, int whence) static
Definition at line 242 of file cl_video_libavw.c.
{
    return (uint64_t)FS_Seek((qfile_t *)opaque, pos, whence);
}
Referenced by LibAvW_OpenVideo().
LibAvW_FS_SeekSize()
static uint64_t LibAvW_FS_SeekSize (void * opaque) static
Definition at line 246 of file cl_video_libavw.c.
{
    return (uint64_t)FS_FileSize((qfile_t *)opaque);
}
Referenced by LibAvW_OpenVideo().
libavw_getaspectratio()
double libavw_getaspectratio (void * stream)
Definition at line 216 of file cl_video_libavw.c.
{
    return ((libavwstream_t *)stream)->info_aspectratio;
}
Referenced by LibAvW_OpenVideo().
libavw_getframerate()
double libavw_getframerate (void * stream)
Definition at line 211 of file cl_video_libavw.c.
{
    return ((libavwstream_t *)stream)->info_framerate;
}
Referenced by LibAvW_OpenVideo().
libavw_getheight()
unsigned int libavw_getheight (void * stream)
Definition at line 206 of file cl_video_libavw.c.
{
    return ((libavwstream_t *)stream)->info_imageheight;
}
Referenced by LibAvW_OpenVideo().
libavw_getwidth()
unsigned int libavw_getwidth (void * stream)
Definition at line 201 of file cl_video_libavw.c.
{
    return ((libavwstream_t *)stream)->info_imagewidth;
}
Referenced by LibAvW_OpenVideo().
libavw_message()
static void libavw_message (int level, const char * message) static
Definition at line 346 of file cl_video_libavw.c.
{
    if (level == LIBAVW_PRINT_WARNING)
        Con_Printf(CON_WARN "LibAvcodec warning: %s\n", message);
    else if (level == LIBAVW_PRINT_ERROR)
        Con_Printf(CON_ERROR "LibAvcodec error: %s\n", message);
    else if (level == LIBAVW_PRINT_FATAL)
        Con_Printf(CON_ERROR "LibAvcodec fatal error: %s\n", message);
    else
        Con_Printf(CON_ERROR "LibAvcodec panic: %s\n", message);
}
Referenced by LibAvW_OpenLibrary().
LibAvW_OpenLibrary()
qbool LibAvW_OpenLibrary (void)
Definition at line 358 of file cl_video_libavw.c.
{
    int errorcode;
    // COMMANDLINEOPTION: Video: -nolibavw disables libavcodec wrapper support
    if (Sys_CheckParm("-nolibavw"))
        return false;
    // load DLL's
    Sys_LoadDependency(dllnames_libavw, &libavw_dll, libavwfuncs);
    if (!libavw_dll)
        return false;
    // initialize libav wrapper
    if ((errorcode = qLibAvW_Init(&libavw_message)))
    {
        Con_Printf(CON_ERROR "LibAvW failed to initialize: %s\n", qLibAvW_ErrorString(errorcode));
        Sys_FreeLibrary(&libavw_dll);
    }
    Cvar_RegisterVariable(&cl_video_libavw_minwidth);
    Cvar_RegisterVariable(&cl_video_libavw_minheight);
    Cvar_RegisterVariable(&cl_video_libavw_scaler);
    return true;
}
Referenced by CL_Video_Init().
LibAvW_OpenVideo()
void * LibAvW_OpenVideo (clvideo_t * video, char * filename, const char ** errorstring)
Definition at line 252 of file cl_video_libavw.c.
{
    libavwstream_t *s;
    char filebase[MAX_OSPATH], check[MAX_OSPATH];
    unsigned int i;
    int errorcode;
    char *wavename;
    size_t len;
    if (!libavw_dll)
        return NULL;
    // allocate stream
    s = (libavwstream_t *)Z_Malloc(sizeof(libavwstream_t));
    if (s == NULL)
    {
        *errorstring = "unable to allocate memory for stream info structure";
        return NULL;
    }
    memset(s, 0, sizeof(libavwstream_t));
    s->sndchan = -1;
    // open file
    s->file = FS_OpenVirtualFile(filename, true);
    if (!s->file)
    {
        FS_StripExtension(filename, filebase, sizeof(filebase));
        // we tried .dpv, try another extensions
        for (i = 0; libavw_extensions[i] != NULL; i++)
        {
            dpsnprintf(check, sizeof(check), "%s.%s", filebase, libavw_extensions[i]);
            s->file = FS_OpenVirtualFile(check, true);
            if (s->file)
                break;
        }
        if (!s->file)
        {
            *errorstring = "unable to open videofile";
            libavw_close(s);
            Z_Free(s);
             return NULL;
        }
    }
    // allocate libavw stream
    if ((errorcode = qLibAvW_CreateStream(&s->stream)))
    {
        *errorstring = qLibAvW_ErrorString(errorcode);
        libavw_close(s);
        Z_Free(s);
        return NULL;
    }
    // open video for playing
    if (!qLibAvW_PlayVideo(s->stream, s->file, &LibAvW_FS_Read, &LibAvW_FS_Seek, &LibAvW_FS_SeekSize))
    {
        *errorstring = qLibAvW_ErrorString(qLibAvW_StreamGetError(s->stream));
        libavw_close(s);
        Z_Free(s);
        return NULL;
    }
    // all right, start codec
    s->info_imagewidth = qLibAvW_StreamGetVideoWidth(s->stream);
    s->info_imageheight = qLibAvW_StreamGetVideoHeight(s->stream);
    s->info_framerate = qLibAvW_StreamGetFramerate(s->stream);
    s->info_aspectratio = (double)s->info_imagewidth / (double)s->info_imageheight;
    video->close = libavw_close;
    video->getwidth = libavw_getwidth;
    video->getheight = libavw_getheight;
    video->getframerate = libavw_getframerate;
    video->decodeframe = libavw_decodeframe;
    video->getaspectratio = libavw_getaspectratio;
    // apply min-width, min-height, keep aspect rate
    if (cl_video_libavw_minwidth.integer > 0)
        s->info_imagewidth = max(s->info_imagewidth, (unsigned int)cl_video_libavw_minwidth.integer);
    if (cl_video_libavw_minheight.integer > 0)
        s->info_imageheight = max(s->info_imageheight, (unsigned int)cl_video_libavw_minheight.integer);
    // provide sound in separate .wav
    len = strlen(filename) + 10;
    wavename = (char *)Z_Malloc(len);
    if (wavename)
    {
        FS_StripExtension(filename, wavename, len-1);
        dp_strlcat(wavename, ".wav", len);
        s->sfx = S_PrecacheSound(wavename, false, false);
        s->sndchan = -1;
        Z_Free(wavename);
    }
    return s;
}
Referenced by OpenStream().
Variable Documentation
cl_video_libavw_minheight
cvar_t cl_video_libavw_minheight = {CF_ARCHIVE, "cl_video_libavw_minheight", "0", "if videos height is lesser than minimal, thay will be upscaled"}
Definition at line 121 of file cl_video_libavw.c.
{CF_ARCHIVE, "cl_video_libavw_minheight", "0", "if videos height is lesser than minimal, thay will be upscaled"};
Referenced by LibAvW_OpenLibrary(), and LibAvW_OpenVideo().
cl_video_libavw_minwidth
cvar_t cl_video_libavw_minwidth = {CF_ARCHIVE, "cl_video_libavw_minwidth", "0", "if videos width is lesser than minimal, thay will be upscaled"}
Definition at line 120 of file cl_video_libavw.c.
{CF_ARCHIVE, "cl_video_libavw_minwidth", "0", "if videos width is lesser than minimal, thay will be upscaled"};
Referenced by LibAvW_OpenLibrary(), and LibAvW_OpenVideo().
cl_video_libavw_scaler
cvar_t cl_video_libavw_scaler = {CF_ARCHIVE, "cl_video_libavw_scaler", "1", "selects a scaler for libavcode played videos. Scalers are: 0 - bilinear, 1 - bicubic, 2 - x, 3 - point, 4 - area, 5 - bicublin, 6 - gauss, 7 - sinc, 8 - lanczos, 9 - spline."}
Definition at line 122 of file cl_video_libavw.c.
{CF_ARCHIVE, "cl_video_libavw_scaler", "1", "selects a scaler for libavcode played videos. Scalers are: 0 - bilinear, 1 - bicubic, 2 - x, 3 - point, 4 - area, 5 - bicublin, 6 - gauss, 7 - sinc, 8 - lanczos, 9 - spline."};
Referenced by libavw_decodeframe(), and LibAvW_OpenLibrary().
dllnames_libavw
const char* dllnames_libavw[]
Initial value:
=
{
        "libavcodec.so",
        NULL
}
Definition at line 89 of file cl_video_libavw.c.
{
#if defined(WIN32)
        "libavcodec.dll",
#elif defined(MACOSX)
        "libavcodec.dylib",
#else
        "libavcodec.so",
#endif
        NULL
};
Referenced by LibAvW_OpenLibrary().
libavw_dll
dllhandle_t libavw_dll = NULL static
Definition at line 101 of file cl_video_libavw.c.
Referenced by LibAvW_CloseLibrary(), LibAvW_OpenLibrary(), and LibAvW_OpenVideo().
libavw_extensions
const char* libavw_extensions[]
Initial value:
=
{
    "ogv",
    "avi",
    "mpg",
    "mp4",
    "mkv",
    "webm",
    "bik",
    "roq",
    "flv",
    "wmv",
    "mpeg",
    "mjpeg",
    "mpeg4",
    NULL
}
Definition at line 125 of file cl_video_libavw.c.
{
    "ogv",
    "avi",
    "mpg",
    "mp4",
    "mkv",
    "webm",
    "bik",
    "roq",
    "flv",
    "wmv",
    "mpeg",
    "mjpeg",
    "mpeg4",
    NULL
};
Referenced by LibAvW_OpenVideo().
libavwfuncs
dllfunction_t libavwfuncs[] static
Initial value:
=
{
    {"LibAvW_Init",                (void **) &qLibAvW_Init },
    {"LibAvW_ErrorString",         (void **) &qLibAvW_ErrorString },
    {"LibAvW_AvcVersion",          (void **) &qLibAvW_AvcVersion },
    {"LibAvW_Version",             (void **) &qLibAvW_Version },
    {"LibAvW_CreateStream",        (void **) &qLibAvW_CreateStream },
    {"LibAvW_RemoveStream",        (void **) &qLibAvW_RemoveStream },
    {"LibAvW_StreamGetVideoWidth", (void **) &qLibAvW_StreamGetVideoWidth },
    {"LibAvW_StreamGetVideoHeight",(void **) &qLibAvW_StreamGetVideoHeight },
    {"LibAvW_StreamGetFramerate",  (void **) &qLibAvW_StreamGetFramerate },
    {"LibAvW_StreamGetError",      (void **) &qLibAvW_StreamGetError },
    {"LibAvW_PlayVideo",           (void **) &qLibAvW_PlayVideo },
    {"LibAvW_PlaySeekNextFrame",   (void **) &qLibAvW_PlaySeekNextFrame },
    {"LibAvW_PlayGetFrameImage",   (void **) &qLibAvW_PlayGetFrameImage },
    {NULL, NULL}
}
Definition at line 71 of file cl_video_libavw.c.
{
    {"LibAvW_Init",                (void **) &qLibAvW_Init },
    {"LibAvW_ErrorString",         (void **) &qLibAvW_ErrorString },
    {"LibAvW_AvcVersion",          (void **) &qLibAvW_AvcVersion },
    {"LibAvW_Version",             (void **) &qLibAvW_Version },
    {"LibAvW_CreateStream",        (void **) &qLibAvW_CreateStream },
    {"LibAvW_RemoveStream",        (void **) &qLibAvW_RemoveStream },
    {"LibAvW_StreamGetVideoWidth", (void **) &qLibAvW_StreamGetVideoWidth },
    {"LibAvW_StreamGetVideoHeight",(void **) &qLibAvW_StreamGetVideoHeight },
    {"LibAvW_StreamGetFramerate",  (void **) &qLibAvW_StreamGetFramerate },
    {"LibAvW_StreamGetError",      (void **) &qLibAvW_StreamGetError },
    {"LibAvW_PlayVideo",           (void **) &qLibAvW_PlayVideo },
    {"LibAvW_PlaySeekNextFrame",   (void **) &qLibAvW_PlaySeekNextFrame },
    {"LibAvW_PlayGetFrameImage",   (void **) &qLibAvW_PlayGetFrameImage },
    {NULL, NULL}
};
Referenced by LibAvW_OpenLibrary().
qLibAvW_AvcVersion
const char *(* qLibAvW_AvcVersion) (void) (void)
Definition at line 58 of file cl_video_libavw.c.
qLibAvW_CreateStream
int(* qLibAvW_CreateStream) (void **stream) (void ** stream)
Definition at line 60 of file cl_video_libavw.c.
Referenced by LibAvW_OpenVideo().
qLibAvW_ErrorString
const char *(* qLibAvW_ErrorString) (int errorcode) (int errorcode)
Definition at line 57 of file cl_video_libavw.c.
Referenced by libavw_decodeframe(), LibAvW_OpenLibrary(), and LibAvW_OpenVideo().
qLibAvW_Init
int(* qLibAvW_Init) (avwCallbackPrint *printfunction) (avwCallbackPrint * printfunction)
Definition at line 56 of file cl_video_libavw.c.
Referenced by LibAvW_OpenLibrary().
qLibAvW_PlayGetFrameImage
int(* qLibAvW_PlayGetFrameImage) (void *stream, int pixel_format, void *imagedata, int imagewidth, int imageheight, int scaler) (void * stream, int pixel_format, void * imagedata, int imagewidth, int imageheight, int scaler)
Definition at line 69 of file cl_video_libavw.c.
Referenced by libavw_decodeframe().
qLibAvW_PlaySeekNextFrame
int(* qLibAvW_PlaySeekNextFrame) (void *stream) (void * stream)
Definition at line 68 of file cl_video_libavw.c.
Referenced by libavw_decodeframe().
qLibAvW_PlayVideo
int(* qLibAvW_PlayVideo) (void *stream, void *file, avwCallbackIoRead *IoRead, avwCallbackIoSeek *IoSeek, avwCallbackIoSeekSize *IoSeekSize) (void * stream, void * file, avwCallbackIoRead * IoRead, avwCallbackIoSeek * IoSeek, avwCallbackIoSeekSize * IoSeekSize)
Definition at line 67 of file cl_video_libavw.c.
Referenced by LibAvW_OpenVideo().
qLibAvW_RemoveStream
void(* qLibAvW_RemoveStream) (void *stream) (void * stream)
Definition at line 61 of file cl_video_libavw.c.
Referenced by libavw_close().
qLibAvW_StreamGetError
int(* qLibAvW_StreamGetError) (void *stream) (void * stream)
Definition at line 65 of file cl_video_libavw.c.
Referenced by libavw_decodeframe(), and LibAvW_OpenVideo().
qLibAvW_StreamGetFramerate
double(* qLibAvW_StreamGetFramerate) (void *stream) (void * stream)
Definition at line 64 of file cl_video_libavw.c.
Referenced by LibAvW_OpenVideo().
qLibAvW_StreamGetVideoHeight
int(* qLibAvW_StreamGetVideoHeight) (void *stream) (void * stream)
Definition at line 63 of file cl_video_libavw.c.
Referenced by LibAvW_OpenVideo().
qLibAvW_StreamGetVideoWidth
int(* qLibAvW_StreamGetVideoWidth) (void *stream) (void * stream)
Definition at line 62 of file cl_video_libavw.c.
Referenced by LibAvW_OpenVideo().
qLibAvW_Version
float(* qLibAvW_Version) (void) (void)
Definition at line 59 of file cl_video_libavw.c.