DarkPlaces: cl_video.h File Reference
cl_video.h File Reference
#include "qtypes.h"
#include "qdefs.h"
Data Structures
struct clvideo_t
Macros
#define CLVIDEOPREFIX "video/"
#define CLTHRESHOLD 2.0
#define MENUOWNER 1
#define CLVIDEO_MAX_SUBTITLES 512
Enumerations
enum clvideostate_t {
CLVIDEO_UNUSED , CLVIDEO_PLAY , CLVIDEO_LOOP , CLVIDEO_PAUSE ,
CLVIDEO_FIRSTFRAME , CLVIDEO_RESETONWAKEUP , CLVIDEO_STATECOUNT
}
Functions
clvideo_t * CL_OpenVideo (const char *filename, const char *name, int owner, const char *subtitlesfile)
clvideo_t * CL_GetVideoByName (const char *name)
void CL_SetVideoState (clvideo_t *video, clvideostate_t state)
void CL_RestartVideo (clvideo_t *video)
void CL_CloseVideo (clvideo_t *video)
void CL_PurgeOwner (int owner)
void CL_Video_Frame (void)
void CL_Video_Init (void)
void CL_Video_Shutdown (void)
void CL_DrawVideo (void)
void CL_VideoStart (char *filename, const char *subtitlesfile)
void CL_VideoStop (void)
void CL_Video_KeyEvent (int key, int ascii, qbool down)
Variables
struct cvar_s cl_video_subtitles
struct cvar_s cl_video_subtitles_lines
struct cvar_s cl_video_subtitles_textsize
struct cvar_s cl_video_scale
struct cvar_s cl_video_scale_vpos
struct cvar_s cl_video_stipple
struct cvar_s cl_video_brightness
struct cvar_s cl_video_keepaspectratio
int cl_videoplaying
Macro Definition Documentation
CLTHRESHOLD
#define CLTHRESHOLD 2.0
Definition at line 9 of file cl_video.h.
CLVIDEO_MAX_SUBTITLES
#define CLVIDEO_MAX_SUBTITLES 512
Definition at line 24 of file cl_video.h.
CLVIDEOPREFIX
#define CLVIDEOPREFIX "video/"
Definition at line 8 of file cl_video.h.
MENUOWNER
#define MENUOWNER 1
Definition at line 11 of file cl_video.h.
Enumeration Type Documentation
clvideostate_t
enum clvideostate_t
Enumerator
CLVIDEO_UNUSED
CLVIDEO_PLAY
CLVIDEO_LOOP
CLVIDEO_PAUSE
CLVIDEO_FIRSTFRAME
CLVIDEO_RESETONWAKEUP
CLVIDEO_STATECOUNT
Definition at line 13 of file cl_video.h.
{
    CLVIDEO_UNUSED,
    CLVIDEO_PLAY,
    CLVIDEO_LOOP,
    CLVIDEO_PAUSE,
    CLVIDEO_FIRSTFRAME,
    CLVIDEO_RESETONWAKEUP,
    CLVIDEO_STATECOUNT
} clvideostate_t;
Function Documentation
CL_CloseVideo()
void CL_CloseVideo (clvideo_t * video)
Definition at line 327 of file cl_video.c.
{
    int i;
    if (!video || video->state == CLVIDEO_UNUSED)
        return;
    // close stream
    if (!video->suspended || video->state != CLVIDEO_FIRSTFRAME)
    {
        if (video->stream)
            video->close(video->stream);
        video->stream = NULL;
    }
    // unlink texture
    if (!video->suspended)
        UnlinkVideoTexture(video);
    // purge subtitles
    if (video->subtitles)
    {
        for (i = 0; i < video->subtitles; i++)
            Z_Free( video->subtitle_text[i] );
        video->subtitles = 0;
    }
    video->state = CLVIDEO_UNUSED;
}
Referenced by CL_PurgeOwner(), CL_Video_Shutdown(), CL_VideoStart(), CL_VideoStop(), and VM_cin_close().
CL_DrawVideo()
void CL_DrawVideo (void)
Definition at line 460 of file cl_video.c.
{
    clvideo_t *video;
    float videotime, px, py, sx, sy, st[8], b;
    cl_video_subtitle_info_t si;
    int i;
    if (!cl_videoplaying)
        return;
    video = CL_GetVideoBySlot( 0 );
    // fix cvars
    if (cl_video_scale.value <= 0 || cl_video_scale.value > 1)
        Cvar_SetValueQuick( &cl_video_scale, 1);
    if (cl_video_brightness.value <= 0 || cl_video_brightness.value > 10)
        Cvar_SetValueQuick( &cl_video_brightness, 1);
    // calc video proportions
    px = 0;
    py = 0;
    sx = vid_conwidth.integer;
    sy = vid_conheight.integer;
    st[0] = 0.0; st[1] = 0.0;
    st[2] = 1.0; st[3] = 0.0;
    st[4] = 0.0; st[5] = 1.0;
    st[6] = 1.0; st[7] = 1.0;
    if (cl_video_keepaspectratio.integer)
    {
        float a = video->getaspectratio(video->stream) / ((float)vid.width / (float)vid.height);
        if (cl_video_keepaspectratio.integer >= 2)
        {
            // clip instead of scale
            if (a < 1.0) // clip horizontally
            {
                st[1] = st[3] = (1 - a)*0.5;
                st[5] = st[7] = 1 - (1 - a)*0.5;
            }
            else if (a > 1.0) // clip vertically
            {
                st[0] = st[4] = (1 - 1/a)*0.5;
                st[2] = st[6] = (1/a)*0.5;
            }
        }
        else if (a < 1.0) // scale horizontally
        {
            px += sx * (1 - a) * 0.5;
            sx *= a;
        }
        else if (a > 1.0) // scale vertically
        {
            a = 1 / a;
            py += sy * (1 - a);
            sy *= a;
        }
    }
    if (cl_video_scale.value != 1)
    {
        px += sx * (1 - cl_video_scale.value) * 0.5;
        py += sy * (1 - cl_video_scale.value) * ((bound(-1, cl_video_scale_vpos.value, 1) + 1) / 2);
        sx *= cl_video_scale.value;
        sy *= cl_video_scale.value;
    }
    // calc brightness for fadein and fadeout effects
    b = cl_video_brightness.value;
    if (cl_video_fadein.value && (host.realtime - video->starttime) < cl_video_fadein.value)
        b = pow((host.realtime - video->starttime)/cl_video_fadein.value, 2);
    else if (cl_video_fadeout.value && ((video->starttime + video->framenum * video->framerate) - host.realtime) < cl_video_fadeout.value)
        b = pow(((video->starttime + video->framenum * video->framerate) - host.realtime)/cl_video_fadeout.value, 2);
    // draw black bg in case stipple is active or video is scaled
    if (cl_video_stipple.integer || px != 0 || py != 0 || sx != vid_conwidth.integer || sy != vid_conheight.integer)
        DrawQ_Fill(0, 0, vid_conwidth.integer, vid_conheight.integer, 0, 0, 0, 1, 0);
    // enable video-only polygon stipple (of global stipple is not active)
    if (!scr_stipple.integer && cl_video_stipple.integer)
    {
        Con_Print("FIXME: cl_video_stipple not implemented\n");
        Cvar_SetValueQuick(&cl_video_stipple, 0);
    }
    // draw video
    if (v_glslgamma_video.value >= 1)
        DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, 1, st[2], st[3], b, b, b, 1, st[4], st[5], b, b, b, 1, st[6], st[7], b, b, b, 1, 0);
    else
    {
        DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, 1, st[2], st[3], b, b, b, 1, st[4], st[5], b, b, b, 1, st[6], st[7], b, b, b, 1, DRAWFLAG_NOGAMMA);
        if (v_glslgamma_video.value > 0.0)
            DrawQ_SuperPic(px, py, video->cachepic, sx, sy, st[0], st[1], b, b, b, v_glslgamma_video.value, st[2], st[3], b, b, b, v_glslgamma_video.value, st[4], st[5], b, b, b, v_glslgamma_video.value, st[6], st[7], b, b, b, v_glslgamma_video.value, 0);
    }
    // VorteX: draw subtitle_text
    if (!video->subtitles || !cl_video_subtitles.integer)
        return;
    // find current subtitle
    videotime = host.realtime - video->starttime;
    for (i = 0; i < video->subtitles; i++)
    {
        if (videotime >= video->subtitle_start[i] && videotime <= video->subtitle_end[i])
        {
            // found, draw it
            si.font = FONT_NOTIFY;
            si.x = vid_conwidth.integer * 0.1;
            si.y = vid_conheight.integer - (max(1, cl_video_subtitles_lines.value) * cl_video_subtitles_textsize.value);
            si.width = vid_conwidth.integer * 0.8;
            si.height = max(1, cl_video_subtitles_lines.integer) * cl_video_subtitles_textsize.value;
            si.alignment = 0.5;
            si.fontsize = cl_video_subtitles_textsize.value;
            si.textalpha = min(1, (videotime - video->subtitle_start[i])/0.5) * min(1, ((video->subtitle_end[i] - videotime)/0.3)); // fade in and fade out
            COM_Wordwrap(video->subtitle_text[i], strlen(video->subtitle_text[i]), 0, si.width, CL_DrawVideo_WordWidthFunc, &si, CL_DrawVideo_DisplaySubtitleLine, &si);
            break;
        }
    }
}
Referenced by SCR_DrawScreen().
CL_GetVideoByName()
clvideo_t * CL_GetVideoByName (const char * name)
Definition at line 284 of file cl_video.c.
{
    int i;
    for( i = 0 ; i < cl_num_videos ; i++ )
        if( cl_videos[ i ].state != CLVIDEO_UNUSED
            &&  !strcmp( cl_videos[ i ].name , name ) )
            break;
    if( i != cl_num_videos )
        return CL_GetVideoBySlot( i );
    else
        return NULL;
}
Referenced by VM_cin_close(), VM_cin_getstate(), VM_cin_restart(), and VM_cin_setstate().
CL_OpenVideo()
clvideo_t * CL_OpenVideo (const char * filename, const char * name, int owner, const char * subtitlesfile)
Definition at line 245 of file cl_video.c.
{
    clvideo_t *video;
    // sanity check
    if( !name || !*name || strncmp( name, CLVIDEOPREFIX, sizeof( CLVIDEOPREFIX ) - 1 ) != 0 ) {
        Con_DPrintf( "CL_OpenVideo: Bad video texture name '%s'!\n", name );
        return NULL;
    }
    video = FindUnusedVid();
    if( !video ) {
        Con_Printf(CON_ERROR "CL_OpenVideo: unable to open video \"%s\" - video limit reached\n", filename );
        return NULL;
    }
    video = OpenVideo( video, filename, name, owner, subtitlesfile );
    // expand the active range to include the new entry
    if (video) {
        cl_num_videos = max(cl_num_videos, (int)(video - cl_videos) + 1);
    }
    return video;
}
Referenced by VM_cin_open().
CL_PurgeOwner()
void CL_PurgeOwner (int owner)
Definition at line 411 of file cl_video.c.
{
    int i;
    for (i = 0 ; i < cl_num_videos ; i++)
        if (cl_videos[i].ownertag == owner)
            CL_CloseVideo(&cl_videos[i]);
}
Referenced by VM_Cmd_Reset().
CL_RestartVideo()
void CL_RestartVideo (clvideo_t * video)
Definition at line 309 of file cl_video.c.
{
    if (!video)
        return;
    // reset time
    video->starttime = video->lasttime = host.realtime;
    video->framenum = -1;
    // reopen stream
    if (video->stream)
        video->close(video->stream);
    video->stream = NULL;
    if (!OpenStream(video))
        video->state = CLVIDEO_UNUSED;
}
Referenced by CL_SetVideoState(), CL_Video_Frame(), CL_VideoStart(), and VM_cin_restart().
CL_SetVideoState()
void CL_SetVideoState (clvideo_t * video, clvideostate_t state)
Definition at line 298 of file cl_video.c.
{
    if (!video)
        return;
    video->lasttime = host.realtime;
    video->state = state;
    if (state == CLVIDEO_FIRSTFRAME)
        CL_RestartVideo(video);
}
Referenced by CL_VideoStart(), and VM_cin_setstate().
CL_Video_Frame()
void CL_Video_Frame (void)
Definition at line 355 of file cl_video.c.
{
    clvideo_t *video;
    int destframe;
    int i;
    if (!cl_num_videos)
        return;
    for (video = cl_videos, i = 0 ; i < cl_num_videos ; video++, i++)
    {
        if (video->state != CLVIDEO_UNUSED && !video->suspended)
        {
            if (host.realtime - video->lasttime > CLTHRESHOLD)
            {
                SuspendVideo(video);
                continue;
            }
            if (video->state == CLVIDEO_PAUSE)
            {
                video->starttime = host.realtime - video->framenum * video->framerate;
                continue;
            }
            // read video frame from stream if time has come
            if (video->state == CLVIDEO_FIRSTFRAME )
                destframe = 0;
            else
                destframe = (int)((host.realtime - video->starttime) * video->framerate);
            if (destframe < 0)
                destframe = 0;
            if (video->framenum < destframe)
            {
                do {
                    video->framenum++;
                    if (video->decodeframe(video->stream, video->imagedata, cl_videormask, cl_videogmask, cl_videobmask, cl_videobytesperpixel, cl_videobytesperpixel * video->width))
                    {
                        // finished?
                        CL_RestartVideo(video);
                        if (video->state == CLVIDEO_PLAY)
                            video->state = CLVIDEO_FIRSTFRAME;
                        return;
                    }
                } while(video->framenum < destframe);
                R_MarkDirtyTexture(Draw_GetPicTexture(video->cachepic));
            }
        }
    }
    // stop main video
    if (cl_videos->state == CLVIDEO_FIRSTFRAME)
        CL_VideoStop();
    // reduce range to exclude unnecessary entries
    while(cl_num_videos > 0 && cl_videos[cl_num_videos-1].state == CLVIDEO_UNUSED)
        cl_num_videos--;
}
Referenced by CL_Frame().
CL_Video_Init()
void CL_Video_Init (void)
Definition at line 675 of file cl_video.c.
{
    union
    {
        unsigned char b[4];
        unsigned int i;
    }
    bgra;
    cl_num_videos = 0;
    cl_videobytesperpixel = 4;
    // set masks in an endian-independent way (as they really represent bytes)
    bgra.i = 0;bgra.b[0] = 0xFF;cl_videobmask = bgra.i;
    bgra.i = 0;bgra.b[1] = 0xFF;cl_videogmask = bgra.i;
    bgra.i = 0;bgra.b[2] = 0xFF;cl_videormask = bgra.i;
    Cmd_AddCommand(CF_CLIENT, "playvideo", CL_PlayVideo_f, "play a .dpv video file" );
    Cmd_AddCommand(CF_CLIENT, "stopvideo", CL_StopVideo_f, "stop playing a .dpv video file" );
    Cvar_RegisterVariable(&cl_video_subtitles);
    Cvar_RegisterVariable(&cl_video_subtitles_lines);
    Cvar_RegisterVariable(&cl_video_subtitles_textsize);
    Cvar_RegisterVariable(&cl_video_scale);
    Cvar_RegisterVariable(&cl_video_scale_vpos);
    Cvar_RegisterVariable(&cl_video_brightness);
    Cvar_RegisterVariable(&cl_video_stipple);
    Cvar_RegisterVariable(&cl_video_keepaspectratio);
    Cvar_RegisterVariable(&cl_video_fadein);
    Cvar_RegisterVariable(&cl_video_fadeout);
    Cvar_RegisterVariable(&v_glslgamma_video);
    R_RegisterModule( "CL_Video", cl_video_start, cl_video_shutdown, cl_video_newmap, NULL, NULL );
    LibAvW_OpenLibrary();
}
Referenced by CL_Init().
CL_Video_KeyEvent()
void CL_Video_KeyEvent (int key, int ascii, qbool down)
Definition at line 596 of file cl_video.c.
{
    // only react to up events, to allow the user to delay the abortion point if it suddenly becomes interesting..
    if( !down ) {
        if( key == K_ESCAPE || key == K_ENTER || key == K_SPACE ) {
            CL_VideoStop();
        }
    }
}
Referenced by Key_Event().
CL_Video_Shutdown()
void CL_Video_Shutdown (void)
Definition at line 713 of file cl_video.c.
{
    int i;
    for (i = 0 ; i < cl_num_videos ; i++)
        CL_CloseVideo(&cl_videos[ i ]);
    LibAvW_CloseLibrary();
}
Referenced by CL_Shutdown().
CL_VideoStart()
void CL_VideoStart (char * filename, const char * subtitlesfile)
Definition at line 578 of file cl_video.c.
{
    CL_StartVideo();
    if( cl_videos->state != CLVIDEO_UNUSED )
        CL_CloseVideo( cl_videos );
    // already contains video/
    if( !OpenVideo( cl_videos, filename, filename, 0, subtitlesfile ) )
        return;
    // expand the active range to include the new entry
    cl_num_videos = max(cl_num_videos, 1);
    cl_videoplaying = true;
    CL_SetVideoState( cl_videos, CLVIDEO_PLAY );
    CL_RestartVideo( cl_videos );
}
Referenced by CL_PlayVideo_f().
CL_VideoStop()
void CL_VideoStop (void)
Definition at line 606 of file cl_video.c.
{
    cl_videoplaying = false;
    CL_CloseVideo( cl_videos );
}
Referenced by CL_ParseServerInfo(), CL_StopVideo_f(), CL_Video_Frame(), and CL_Video_KeyEvent().
Variable Documentation
cl_video_brightness
struct cvar_s cl_video_brightness extern
Definition at line 12 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_brightness", "1", "brightness of video, 1 = fullbright, 0.75 - 3/4 etc."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_keepaspectratio
struct cvar_s cl_video_keepaspectratio extern
Definition at line 13 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_keepaspectratio", "0", "keeps aspect ratio of fullscreen videos, leaving black color on unfilled areas, a value of 2 let video to be stretched horizontally with top & bottom being sliced out"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_scale
struct cvar_s cl_video_scale extern
Definition at line 9 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_scale", "1", "scale of video, 1 = fullscreen, 0.75 - 3/4 of screen etc."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_scale_vpos
struct cvar_s cl_video_scale_vpos extern
Definition at line 10 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_scale_vpos", "0", "vertical align of scaled video, -1 is top, 1 is bottom"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_stipple
struct cvar_s cl_video_stipple extern
Definition at line 11 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_stipple", "0", "draw interlacing-like effect on videos, similar to scr_stipple but static and used only with video playing."};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles
struct cvar_s cl_video_subtitles extern
Definition at line 6 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles", "0", "show subtitles for videos (if they are present)"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles_lines
struct cvar_s cl_video_subtitles_lines extern
Definition at line 7 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_lines", "4", "how many lines to occupy for subtitles"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_video_subtitles_textsize
struct cvar_s cl_video_subtitles_textsize extern
Definition at line 8 of file cl_video.c.
{CF_CLIENT | CF_ARCHIVE, "cl_video_subtitles_textsize", "16", "textsize for subtitles"};
Referenced by CL_DrawVideo(), and CL_Video_Init().
cl_videoplaying
int cl_videoplaying extern
Definition at line 458 of file cl_video.c.
Referenced by CL_DrawVideo(), CL_VideoStart(), CL_VideoStop(), Key_Event(), R_RenderView(), and VM_CL_videoplaying().