DarkPlaces: clvm_cmds.h File Reference
clvm_cmds.h File Reference
Functions
void VM_CL_setmodel (void)
void VM_CL_precache_model (void)
void VM_CL_setorigin (void)
void VM_CL_R_AddDynamicLight (void)
void VM_CL_R_ClearScene (void)
void VM_CL_R_AddEntities (void)
void VM_CL_R_AddEntity (void)
void VM_CL_R_SetView (void)
void VM_CL_R_RenderScene (void)
void VM_CL_R_LoadWorldModel (void)
void VM_CL_R_PolygonBegin (void)
void VM_CL_R_PolygonVertex (void)
void VM_CL_R_PolygonEnd (void)
void VM_CL_setattachment (void)
void VM_CL_gettagindex (void)
void VM_CL_gettaginfo (void)
Function Documentation
VM_CL_gettagindex()
void VM_CL_gettagindex (void)
Referenced by VM_CL_gettagindex().
VM_CL_gettaginfo()
void VM_CL_gettaginfo (void)
Referenced by VM_CL_gettaginfo().
VM_CL_precache_model()
void VM_CL_precache_model (void)
Referenced by VM_CL_precache_model().
VM_CL_R_AddDynamicLight()
void VM_CL_R_AddDynamicLight (void)
Referenced by VM_CL_R_AddDynamicLight().
VM_CL_R_AddEntities()
void VM_CL_R_AddEntities (void)
Referenced by VM_CL_R_AddEntities().
VM_CL_R_AddEntity()
void VM_CL_R_AddEntity (void)
Referenced by VM_CL_R_AddEntity().
VM_CL_R_ClearScene()
void VM_CL_R_ClearScene (void)
Referenced by VM_CL_R_ClearScene().
VM_CL_R_LoadWorldModel()
void VM_CL_R_LoadWorldModel (void)
VM_CL_R_PolygonBegin()
void VM_CL_R_PolygonBegin (void)
Referenced by VM_CL_R_PolygonBegin().
VM_CL_R_PolygonEnd()
void VM_CL_R_PolygonEnd (void)
Referenced by VM_CL_R_PolygonEnd().
VM_CL_R_PolygonVertex()
void VM_CL_R_PolygonVertex (void)
Referenced by VM_CL_R_PolygonVertex().
VM_CL_R_RenderScene()
void VM_CL_R_RenderScene (void)
Referenced by VM_CL_R_RenderScene().
VM_CL_R_SetView()
void VM_CL_R_SetView (void)
Referenced by VM_CL_R_SetView().
VM_CL_setattachment()
void VM_CL_setattachment (void)
Referenced by VM_CL_setattachment().
VM_CL_setmodel()
void VM_CL_setmodel (void)
Referenced by VM_CL_setmodel().
VM_CL_setorigin()
void VM_CL_setorigin (void)
Referenced by VM_CL_setorigin().