DarkPlaces: collision.h File Reference
collision.h File Reference
#include "matrixlib.h"
Data Structures
union plane_t
struct trace_t
struct colpointf_t
struct colplanef_t
struct colbrushf_t
struct colboxbrushf_t
Macros
#define COLLISIONPARANOID 0
Functions
void Collision_Init (void)
void Collision_ClipTrace_Box (trace_t *trace, const vec3_t cmins, const vec3_t cmaxs, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, int boxsupercontents, int boxq3surfaceflags, const texture_t *boxtexture)
void Collision_ClipTrace_Point (trace_t *trace, const vec3_t cmins, const vec3_t cmaxs, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, int boxsupercontents, int boxq3surfaceflags, const texture_t *boxtexture)
void Collision_Cache_Reset (qbool resetlimits)
void Collision_Cache_Init (struct mempool_s *mempool)
void Collision_Cache_NewFrame (void)
void Collision_CalcPlanesForTriangleBrushFloat (colbrushf_t *brush)
colbrushf_t * Collision_NewBrushFromPlanes (struct mempool_s *mempool, int numoriginalplanes, const colplanef_t *originalplanes, int supercontents, int q3surfaceflags, const texture_t *texture, int hasaabbplanes)
void Collision_TraceBrushBrushFloat (trace_t *trace, const colbrushf_t *thisbrush_start, const colbrushf_t *thisbrush_end, const colbrushf_t *thatbrush_start, const colbrushf_t *thatbrush_end)
void Collision_TraceBrushTriangleMeshFloat (trace_t *trace, const colbrushf_t *thisbrush_start, const colbrushf_t *thisbrush_end, int numtriangles, const int *element3i, const float *vertex3f, int stride, float *bbox6f, int supercontents, int q3surfaceflags, const texture_t *texture, const vec3_t segmentmins, const vec3_t segmentmaxs)
void Collision_TraceLineBrushFloat (trace_t *trace, const vec3_t linestart, const vec3_t lineend, const colbrushf_t *thatbrush_start, const colbrushf_t *thatbrush_end)
void Collision_TraceLineTriangleMeshFloat (trace_t *trace, const vec3_t linestart, const vec3_t lineend, int numtriangles, const int *element3i, const float *vertex3f, int stride, float *bbox6f, int supercontents, int q3surfaceflags, const texture_t *texture, const vec3_t segmentmins, const vec3_t segmentmaxs)
void Collision_TracePointBrushFloat (trace_t *trace, const vec3_t point, const colbrushf_t *thatbrush)
qbool Collision_PointInsideBrushFloat (const vec3_t point, const colbrushf_t *brush)
void Collision_BrushForBox (colboxbrushf_t *boxbrush, const vec3_t mins, const vec3_t maxs, int supercontents, int q3surfaceflags, const texture_t *texture)
void Collision_BoundingBoxOfBrushTraceSegment (const colbrushf_t *start, const colbrushf_t *end, vec3_t mins, vec3_t maxs, float startfrac, float endfrac)
float Collision_ClipTrace_Line_Sphere (double *linestart, double *lineend, double *sphereorigin, double sphereradius, double *impactpoint, double *impactnormal)
void Collision_TraceLineTriangleFloat (trace_t *trace, const vec3_t linestart, const vec3_t lineend, const float *point0, const float *point1, const float *point2, int supercontents, int q3surfaceflags, const texture_t *texture)
void Collision_TraceBrushTriangleFloat (trace_t *trace, const colbrushf_t *thisbrush_start, const colbrushf_t *thisbrush_end, const float *v0, const float *v1, const float *v2, int supercontents, int q3surfaceflags, const texture_t *texture)
void Collision_ClipToGenericEntity (trace_t *trace, struct model_s *model, const struct frameblend_s *frameblend, const struct skeleton_s *skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t *matrix, matrix4x4_t *inversematrix, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend)
void Collision_ClipLineToGenericEntity (trace_t *trace, struct model_s *model, const struct frameblend_s *frameblend, const struct skeleton_s *skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t *matrix, matrix4x4_t *inversematrix, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend, qbool hitsurfaces)
void Collision_ClipPointToGenericEntity (trace_t *trace, struct model_s *model, const struct frameblend_s *frameblend, const struct skeleton_s *skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t *matrix, matrix4x4_t *inversematrix, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
void Collision_ClipToWorld (trace_t *trace, struct model_s *model, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend)
void Collision_ClipLineToWorld (trace_t *trace, struct model_s *model, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend, qbool hitsurfaces)
void Collision_ClipPointToWorld (trace_t *trace, struct model_s *model, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
void Collision_Cache_ClipLineToGenericEntitySurfaces (trace_t *trace, struct model_s *model, matrix4x4_t *matrix, matrix4x4_t *inversematrix, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
void Collision_Cache_ClipLineToWorldSurfaces (trace_t *trace, struct model_s *model, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
void Collision_CombineTraces (trace_t *cliptrace, const trace_t *trace, void *touch, qbool isbmodel)
Variables
struct cvar_s collision_impactnudge
struct cvar_s collision_extendtracelinelength
struct cvar_s collision_extendtraceboxlength
struct cvar_s collision_extendmovelength
struct cvar_s collision_bih_fullrecursion
Macro Definition Documentation
COLLISIONPARANOID
#define COLLISIONPARANOID 0
Definition at line 195 of file collision.h.
Function Documentation
Collision_BoundingBoxOfBrushTraceSegment()
void Collision_BoundingBoxOfBrushTraceSegment (const colbrushf_t * start, const colbrushf_t * end, vec3_t mins, vec3_t maxs, float startfrac, float endfrac)
Definition at line 1367 of file collision.c.
{
    int i;
    colpointf_t *ps, *pe;
    float tempstart[3], tempend[3];
    VectorLerp(start->points[0].v, startfrac, end->points[0].v, mins);
    VectorCopy(mins, maxs);
    for (i = 0, ps = start->points, pe = end->points;i < start->numpoints;i++, ps++, pe++)
    {
        VectorLerp(ps->v, startfrac, pe->v, tempstart);
        VectorLerp(ps->v, endfrac, pe->v, tempend);
        mins[0] = min(mins[0], min(tempstart[0], tempend[0]));
        mins[1] = min(mins[1], min(tempstart[1], tempend[1]));
        mins[2] = min(mins[2], min(tempstart[2], tempend[2]));
        maxs[0] = min(maxs[0], min(tempstart[0], tempend[0]));
        maxs[1] = min(maxs[1], min(tempstart[1], tempend[1]));
        maxs[2] = min(maxs[2], min(tempstart[2], tempend[2]));
    }
    mins[0] -= 1;
    mins[1] -= 1;
    mins[2] -= 1;
    maxs[0] += 1;
    maxs[1] += 1;
    maxs[2] += 1;
}
Collision_BrushForBox()
void Collision_BrushForBox (colboxbrushf_t * boxbrush, const vec3_t mins, const vec3_t maxs, int supercontents, int q3surfaceflags, const texture_t * texture)
Definition at line 1141 of file collision.c.
{
    int i;
    memset(boxbrush, 0, sizeof(*boxbrush));
    boxbrush->brush.isaabb = true;
    boxbrush->brush.hasaabbplanes = true;
    boxbrush->brush.points = boxbrush->points;
    boxbrush->brush.edgedirs = boxbrush->edgedirs;
    boxbrush->brush.planes = boxbrush->planes;
    boxbrush->brush.supercontents = supercontents;
    boxbrush->brush.q3surfaceflags = q3surfaceflags;
    boxbrush->brush.texture = texture;
    if (VectorCompare(mins, maxs))
    {
        // point brush
        boxbrush->brush.numpoints = 1;
        boxbrush->brush.numedgedirs = 0;
        boxbrush->brush.numplanes = 0;
        VectorCopy(mins, boxbrush->brush.points[0].v);
    }
    else
    {
        boxbrush->brush.numpoints = 8;
        boxbrush->brush.numedgedirs = 3;
        boxbrush->brush.numplanes = 6;
        // there are 8 points on a box
        // there are 3 edgedirs on a box (both signs are tested in collision)
        // there are 6 planes on a box
        VectorSet(boxbrush->brush.points[0].v, mins[0], mins[1], mins[2]);
        VectorSet(boxbrush->brush.points[1].v, maxs[0], mins[1], mins[2]);
        VectorSet(boxbrush->brush.points[2].v, mins[0], maxs[1], mins[2]);
        VectorSet(boxbrush->brush.points[3].v, maxs[0], maxs[1], mins[2]);
        VectorSet(boxbrush->brush.points[4].v, mins[0], mins[1], maxs[2]);
        VectorSet(boxbrush->brush.points[5].v, maxs[0], mins[1], maxs[2]);
        VectorSet(boxbrush->brush.points[6].v, mins[0], maxs[1], maxs[2]);
        VectorSet(boxbrush->brush.points[7].v, maxs[0], maxs[1], maxs[2]);
        VectorSet(boxbrush->brush.edgedirs[0].v, 1, 0, 0);
        VectorSet(boxbrush->brush.edgedirs[1].v, 0, 1, 0);
        VectorSet(boxbrush->brush.edgedirs[2].v, 0, 0, 1);
        VectorSet(boxbrush->brush.planes[0].normal, -1,  0,  0);boxbrush->brush.planes[0].dist = -mins[0];
        VectorSet(boxbrush->brush.planes[1].normal,  1,  0,  0);boxbrush->brush.planes[1].dist =  maxs[0];
        VectorSet(boxbrush->brush.planes[2].normal,  0, -1,  0);boxbrush->brush.planes[2].dist = -mins[1];
        VectorSet(boxbrush->brush.planes[3].normal,  0,  1,  0);boxbrush->brush.planes[3].dist =  maxs[1];
        VectorSet(boxbrush->brush.planes[4].normal,  0,  0, -1);boxbrush->brush.planes[4].dist = -mins[2];
        VectorSet(boxbrush->brush.planes[5].normal,  0,  0,  1);boxbrush->brush.planes[5].dist =  maxs[2];
        for (i = 0;i < 6;i++)
        {
            boxbrush->brush.planes[i].q3surfaceflags = q3surfaceflags;
            boxbrush->brush.planes[i].texture = texture;
        }
    }
    boxbrush->brush.supercontents = supercontents;
    boxbrush->brush.q3surfaceflags = q3surfaceflags;
    boxbrush->brush.texture = texture;
    VectorSet(boxbrush->brush.mins, mins[0] - 1, mins[1] - 1, mins[2] - 1);
    VectorSet(boxbrush->brush.maxs, maxs[0] + 1, maxs[1] + 1, maxs[2] + 1);
    //Collision_ValidateBrush(&boxbrush->brush);
}
Referenced by Collision_ClipToGenericEntity(), Collision_TraceLineBrushFloat(), Mod_CollisionBIH_TraceBox(), and Mod_MDLMD2MD3_TraceBox().
Collision_Cache_ClipLineToGenericEntitySurfaces()
void Collision_Cache_ClipLineToGenericEntitySurfaces (trace_t * trace, struct model_s * model, matrix4x4_t * matrix, matrix4x4_t * inversematrix, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
Collision_Cache_ClipLineToWorldSurfaces()
void Collision_Cache_ClipLineToWorldSurfaces (trace_t * trace, struct model_s * model, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
Collision_Cache_Init()
void Collision_Cache_Init (struct mempool_s * mempool)
Collision_Cache_NewFrame()
void Collision_Cache_NewFrame (void)
Definition at line 1548 of file collision.c.
{
    if (collision_cache.integer)
    {
        if (collision_cachedtrace_max < 128)
            Collision_Cache_Reset(true);
    }
    else
    {
        if (collision_cachedtrace_max > 1)
            Collision_Cache_Reset(true);
    }
    // rebuild hash if sequence would overflow byte, otherwise increment
    if (collision_cachedtrace_sequence == 255)
    {
        Collision_Cache_RebuildHash();
        collision_cachedtrace_sequence = 1;
    }
    else
    {
        collision_cachedtrace_rebuildhash = true;
        collision_cachedtrace_sequence++;
    }
}
Referenced by CL_Frame().
Collision_Cache_Reset()
void Collision_Cache_Reset (qbool resetlimits)
Definition at line 1480 of file collision.c.
{
    if (collision_cachedtrace_hash)
        Mem_Free(collision_cachedtrace_hash);
    if (collision_cachedtrace_array)
        Mem_Free(collision_cachedtrace_array);
    if (collision_cachedtrace_arrayfullhashindex)
        Mem_Free(collision_cachedtrace_arrayfullhashindex);
    if (collision_cachedtrace_arrayhashindex)
        Mem_Free(collision_cachedtrace_arrayhashindex);
    if (collision_cachedtrace_arraynext)
        Mem_Free(collision_cachedtrace_arraynext);
    if (collision_cachedtrace_arrayused)
        Mem_Free(collision_cachedtrace_arrayused);
    if (resetlimits || !collision_cachedtrace_max)
        collision_cachedtrace_max = collision_cache.integer ? 128 : 1;
    collision_cachedtrace_firstfree = 1;
    collision_cachedtrace_lastused = 0;
    collision_cachedtrace_hashsize = collision_cachedtrace_max;
    collision_cachedtrace_array = (collision_cachedtrace_t *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_max * sizeof(collision_cachedtrace_t));
    collision_cachedtrace_hash = (int *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_hashsize * sizeof(int));
    collision_cachedtrace_arrayfullhashindex = (unsigned int *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_max * sizeof(unsigned int));
    collision_cachedtrace_arrayhashindex = (unsigned int *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_max * sizeof(unsigned int));
    collision_cachedtrace_arraynext = (unsigned int *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_max * sizeof(unsigned int));
    collision_cachedtrace_arrayused = (unsigned char *)Mem_Alloc(collision_cachedtrace_mempool, collision_cachedtrace_max * sizeof(unsigned char));
    collision_cachedtrace_sequence = 1;
    collision_cachedtrace_rebuildhash = false;
}
Referenced by CL_ParseServerInfo(), Collision_Cache_Init(), Collision_Cache_Lookup(), Collision_Cache_NewFrame(), gl_main_start(), and SV_SpawnServer().
Collision_CalcPlanesForTriangleBrushFloat()
void Collision_CalcPlanesForTriangleBrushFloat (colbrushf_t * brush)
Definition at line 451 of file collision.c.
{
    float edge0[3], edge1[3], edge2[3];
    colpointf_t *p;
    TriangleNormal(brush->points[0].v, brush->points[1].v, brush->points[2].v, brush->planes[0].normal);
    if (DotProduct(brush->planes[0].normal, brush->planes[0].normal) < 0.0001f)
    {
        // there's no point in processing a degenerate triangle (GIGO - Garbage In, Garbage Out)
        // note that some of these exist in q3bsp bspline patches
        brush->numplanes = 0;
        return;
    }
    // there are 5 planes (front, back, sides) and 3 edges
    brush->numplanes = 5;
    brush->numedgedirs = 3;
    VectorNormalize(brush->planes[0].normal);
    brush->planes[0].dist = DotProduct(brush->points->v, brush->planes[0].normal);
    VectorNegate(brush->planes[0].normal, brush->planes[1].normal);
    brush->planes[1].dist = -brush->planes[0].dist;
    // edge directions are easy to calculate
    VectorSubtract(brush->points[2].v, brush->points[0].v, edge0);
    VectorSubtract(brush->points[0].v, brush->points[1].v, edge1);
    VectorSubtract(brush->points[1].v, brush->points[2].v, edge2);
    VectorCopy(edge0, brush->edgedirs[0].v);
    VectorCopy(edge1, brush->edgedirs[1].v);
    VectorCopy(edge2, brush->edgedirs[2].v);
    // now select an algorithm to generate the side planes
    if (collision_triangle_bevelsides.integer)
    {
        // use 45 degree slopes at the edges of the triangle to make a sinking trace error turn into "riding up" the slope rather than getting stuck
        CrossProduct(edge0, brush->planes->normal, brush->planes[2].normal);
        CrossProduct(edge1, brush->planes->normal, brush->planes[3].normal);
        CrossProduct(edge2, brush->planes->normal, brush->planes[4].normal);
        VectorNormalize(brush->planes[2].normal);
        VectorNormalize(brush->planes[3].normal);
        VectorNormalize(brush->planes[4].normal);
        VectorAdd(brush->planes[2].normal, brush->planes[0].normal, brush->planes[2].normal);
        VectorAdd(brush->planes[3].normal, brush->planes[0].normal, brush->planes[3].normal);
        VectorAdd(brush->planes[4].normal, brush->planes[0].normal, brush->planes[4].normal);
        VectorNormalize(brush->planes[2].normal);
        VectorNormalize(brush->planes[3].normal);
        VectorNormalize(brush->planes[4].normal);
    }
    else if (collision_triangle_axialsides.integer)
    {
        float projectionnormal[3], projectionedge0[3], projectionedge1[3], projectionedge2[3];
        int i, best;
        float dist, bestdist;
        bestdist = fabs(brush->planes[0].normal[0]);
        best = 0;
        for (i = 1;i < 3;i++)
        {
            dist = fabs(brush->planes[0].normal[i]);
            if (bestdist < dist)
            {
                bestdist = dist;
                best = i;
            }
        }
        VectorClear(projectionnormal);
        if (brush->planes[0].normal[best] < 0)
            projectionnormal[best] = -1;
        else
            projectionnormal[best] = 1;
        VectorCopy(edge0, projectionedge0);
        VectorCopy(edge1, projectionedge1);
        VectorCopy(edge2, projectionedge2);
        projectionedge0[best] = 0;
        projectionedge1[best] = 0;
        projectionedge2[best] = 0;
        CrossProduct(projectionedge0, projectionnormal, brush->planes[2].normal);
        CrossProduct(projectionedge1, projectionnormal, brush->planes[3].normal);
        CrossProduct(projectionedge2, projectionnormal, brush->planes[4].normal);
        VectorNormalize(brush->planes[2].normal);
        VectorNormalize(brush->planes[3].normal);
        VectorNormalize(brush->planes[4].normal);
    }
    else
    {
        CrossProduct(edge0, brush->planes->normal, brush->planes[2].normal);
        CrossProduct(edge1, brush->planes->normal, brush->planes[3].normal);
        CrossProduct(edge2, brush->planes->normal, brush->planes[4].normal);
        VectorNormalize(brush->planes[2].normal);
        VectorNormalize(brush->planes[3].normal);
        VectorNormalize(brush->planes[4].normal);
    }
    brush->planes[2].dist = DotProduct(brush->points[2].v, brush->planes[2].normal);
    brush->planes[3].dist = DotProduct(brush->points[0].v, brush->planes[3].normal);
    brush->planes[4].dist = DotProduct(brush->points[1].v, brush->planes[4].normal);
    if (developer_extra.integer)
    {
        int i;
        // validity check - will be disabled later
        Collision_ValidateBrush(brush);
        for (i = 0;i < brush->numplanes;i++)
        {
            int j;
            for (j = 0, p = brush->points;j < brush->numpoints;j++, p++)
                if (DotProduct(p->v, brush->planes[i].normal) > brush->planes[i].dist + COLLISION_PLANE_DIST_EPSILON)
                    Con_DPrintf("Error in brush plane generation, plane %i\n", i);
        }
    }
}
Referenced by Collision_TraceBrushTriangleFloat(), and Collision_TraceBrushTriangleMeshFloat().
Collision_ClipLineToGenericEntity()
void Collision_ClipLineToGenericEntity (trace_t * trace, struct model_s * model, const struct frameblend_s * frameblend, const struct skeleton_s * skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t * matrix, matrix4x4_t * inversematrix, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend, qbool hitsurfaces)
Collision_ClipLineToWorld()
void Collision_ClipLineToWorld (trace_t * trace, struct model_s * model, const vec3_t start, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend, qbool hitsurfaces)
Collision_ClipPointToGenericEntity()
void Collision_ClipPointToGenericEntity (trace_t * trace, struct model_s * model, const struct frameblend_s * frameblend, const struct skeleton_s * skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t * matrix, matrix4x4_t * inversematrix, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
Collision_ClipPointToWorld()
void Collision_ClipPointToWorld (trace_t * trace, struct model_s * model, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask)
Collision_ClipToGenericEntity()
void Collision_ClipToGenericEntity (trace_t * trace, struct model_s * model, const struct frameblend_s * frameblend, const struct skeleton_s * skeleton, const vec3_t bodymins, const vec3_t bodymaxs, int bodysupercontents, matrix4x4_t * matrix, matrix4x4_t * inversematrix, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend)
Collision_ClipToWorld()
void Collision_ClipToWorld (trace_t * trace, struct model_s * model, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, float extend)
Collision_ClipTrace_Box()
void Collision_ClipTrace_Box (trace_t * trace, const vec3_t cmins, const vec3_t cmaxs, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, int boxsupercontents, int boxq3surfaceflags, const texture_t * boxtexture)
Definition at line 1051 of file model_brush.c.
{
#if 1
    colbrushf_t cbox;
    colplanef_t cbox_planes[6];
    cbox.isaabb = true;
    cbox.hasaabbplanes = true;
    cbox.supercontents = boxsupercontents;
    cbox.numplanes = 6;
    cbox.numpoints = 0;
    cbox.numtriangles = 0;
    cbox.planes = cbox_planes;
    cbox.points = NULL;
    cbox.elements = NULL;
    cbox.markframe = 0;
    cbox.mins[0] = 0;
    cbox.mins[1] = 0;
    cbox.mins[2] = 0;
    cbox.maxs[0] = 0;
    cbox.maxs[1] = 0;
    cbox.maxs[2] = 0;
    cbox_planes[0].normal[0] =  1;cbox_planes[0].normal[1] =  0;cbox_planes[0].normal[2] =  0;cbox_planes[0].dist = cmaxs[0] - mins[0];
    cbox_planes[1].normal[0] = -1;cbox_planes[1].normal[1] =  0;cbox_planes[1].normal[2] =  0;cbox_planes[1].dist = maxs[0] - cmins[0];
    cbox_planes[2].normal[0] =  0;cbox_planes[2].normal[1] =  1;cbox_planes[2].normal[2] =  0;cbox_planes[2].dist = cmaxs[1] - mins[1];
    cbox_planes[3].normal[0] =  0;cbox_planes[3].normal[1] = -1;cbox_planes[3].normal[2] =  0;cbox_planes[3].dist = maxs[1] - cmins[1];
    cbox_planes[4].normal[0] =  0;cbox_planes[4].normal[1] =  0;cbox_planes[4].normal[2] =  1;cbox_planes[4].dist = cmaxs[2] - mins[2];
    cbox_planes[5].normal[0] =  0;cbox_planes[5].normal[1] =  0;cbox_planes[5].normal[2] = -1;cbox_planes[5].dist = maxs[2] - cmins[2];
    cbox_planes[0].q3surfaceflags = boxq3surfaceflags;cbox_planes[0].texture = boxtexture;
    cbox_planes[1].q3surfaceflags = boxq3surfaceflags;cbox_planes[1].texture = boxtexture;
    cbox_planes[2].q3surfaceflags = boxq3surfaceflags;cbox_planes[2].texture = boxtexture;
    cbox_planes[3].q3surfaceflags = boxq3surfaceflags;cbox_planes[3].texture = boxtexture;
    cbox_planes[4].q3surfaceflags = boxq3surfaceflags;cbox_planes[4].texture = boxtexture;
    cbox_planes[5].q3surfaceflags = boxq3surfaceflags;cbox_planes[5].texture = boxtexture;
    memset(trace, 0, sizeof(trace_t));
    trace->hitsupercontentsmask = hitsupercontentsmask;
    trace->skipsupercontentsmask = skipsupercontentsmask;
    trace->skipmaterialflagsmask = skipmaterialflagsmask;
    trace->fraction = 1;
    Collision_TraceLineBrushFloat(trace, start, end, &cbox, &cbox);
#else
    RecursiveHullCheckTraceInfo_t rhc;
    static hull_t box_hull;
    static mclipnode_t box_clipnodes[6];
    static mplane_t box_planes[6];
    // fill in a default trace
    memset(&rhc, 0, sizeof(rhc));
    memset(trace, 0, sizeof(trace_t));
    //To keep everything totally uniform, bounding boxes are turned into small
    //BSP trees instead of being compared directly.
    // create a temp hull from bounding box sizes
    box_planes[0].dist = cmaxs[0] - mins[0];
    box_planes[1].dist = cmins[0] - maxs[0];
    box_planes[2].dist = cmaxs[1] - mins[1];
    box_planes[3].dist = cmins[1] - maxs[1];
    box_planes[4].dist = cmaxs[2] - mins[2];
    box_planes[5].dist = cmins[2] - maxs[2];
#if COLLISIONPARANOID >= 3
    Con_Printf("box_planes %f:%f %f:%f %f:%f\ncbox %f %f %f:%f %f %f\nbox %f %f %f:%f %f %f\n", box_planes[0].dist, box_planes[1].dist, box_planes[2].dist, box_planes[3].dist, box_planes[4].dist, box_planes[5].dist, cmins[0], cmins[1], cmins[2], cmaxs[0], cmaxs[1], cmaxs[2], mins[0], mins[1], mins[2], maxs[0], maxs[1], maxs[2]);
#endif
    if (box_hull.clipnodes == NULL)
    {
        int i, side;
        //Set up the planes and clipnodes so that the six floats of a bounding box
        //can just be stored out and get a proper hull_t structure.
        box_hull.clipnodes = box_clipnodes;
        box_hull.planes = box_planes;
        box_hull.firstclipnode = 0;
        box_hull.lastclipnode = 5;
        for (i = 0;i < 6;i++)
        {
            box_clipnodes[i].planenum = i;
            side = i&1;
            box_clipnodes[i].children[side] = CONTENTS_EMPTY;
            if (i != 5)
                box_clipnodes[i].children[side^1] = i + 1;
            else
                box_clipnodes[i].children[side^1] = CONTENTS_SOLID;
            box_planes[i].type = i>>1;
            box_planes[i].normal[i>>1] = 1;
        }
    }
    // trace a line through the generated clipping hull
    //rhc.boxsupercontents = boxsupercontents;
    rhc.hull = &box_hull;
    rhc.trace = trace;
    rhc.trace->hitsupercontentsmask = hitsupercontentsmask;
    rhc.trace->skipsupercontentsmask = skipsupercontentsmask;
    rhc.trace->skipmaterialflagsmask = skipmaterialflagsmask;
    rhc.trace->fraction = 1;
    rhc.trace->allsolid = true;
    VectorCopy(start, rhc.start);
    VectorCopy(end, rhc.end);
    VectorSubtract(rhc.end, rhc.start, rhc.dist);
    Mod_Q1BSP_RecursiveHullCheck(&rhc, rhc.hull->firstclipnode, 0, 1, rhc.start, rhc.end);
    //VectorMA(rhc.start, rhc.trace->fraction, rhc.dist, rhc.trace->endpos);
    if (rhc.trace->startsupercontents)
        rhc.trace->startsupercontents = boxsupercontents;
#endif
}
Referenced by CL_SelectTraceLine(), Collision_ClipLineToGenericEntity(), and Collision_ClipToGenericEntity().
Collision_ClipTrace_Line_Sphere()
float Collision_ClipTrace_Line_Sphere (double * linestart, double * lineend, double * sphereorigin, double sphereradius, double * impactpoint, double * impactnormal)
Definition at line 1207 of file collision.c.
{
    double dir[3], scale, v[3], deviationdist2, impactdist, linelength;
    // make sure the impactpoint and impactnormal are valid even if there is
    // no collision
    VectorCopy(lineend, impactpoint);
    VectorClear(impactnormal);
    // calculate line direction
    VectorSubtract(lineend, linestart, dir);
    // normalize direction
    linelength = VectorLength(dir);
    if (linelength)
    {
        scale = 1.0 / linelength;
        VectorScale(dir, scale, dir);
    }
    // this dotproduct calculates the distance along the line at which the
    // sphere origin is (nearest point to the sphere origin on the line)
    impactdist = DotProduct(sphereorigin, dir) - DotProduct(linestart, dir);
    // calculate point on line at that distance, and subtract the
    // sphereorigin from it, so we have a vector to measure for the distance
    // of the line from the sphereorigin (deviation, how off-center it is)
    VectorMA(linestart, impactdist, dir, v);
    VectorSubtract(v, sphereorigin, v);
    deviationdist2 = sphereradius * sphereradius - VectorLength2(v);
    // if squared offset length is outside the squared sphere radius, miss
    if (deviationdist2 < 0)
        return 1; // miss (off to the side)
    // nudge back to find the correct impact distance
    impactdist -= sqrt(deviationdist2);
    if (impactdist >= linelength)
        return 1; // miss (not close enough)
    if (impactdist < 0)
        return 1; // miss (linestart is past or inside sphere)
    // calculate new impactpoint
    VectorMA(linestart, impactdist, dir, impactpoint);
    // calculate impactnormal (surface normal at point of impact)
    VectorSubtract(impactpoint, sphereorigin, impactnormal);
    // normalize impactnormal
    VectorNormalize(impactnormal);
    // return fraction of movement distance
    return impactdist / linelength;
}
Collision_ClipTrace_Point()
void Collision_ClipTrace_Point (trace_t * trace, const vec3_t cmins, const vec3_t cmaxs, const vec3_t start, int hitsupercontentsmask, int skipsupercontentsmask, int skipmaterialflagsmask, int boxsupercontents, int boxq3surfaceflags, const texture_t * boxtexture)
Definition at line 1159 of file model_brush.c.
{
    memset(trace, 0, sizeof(trace_t));
    trace->fraction = 1;
    trace->hitsupercontentsmask = hitsupercontentsmask;
    trace->skipsupercontentsmask = skipsupercontentsmask;
    trace->skipmaterialflagsmask = skipmaterialflagsmask;
    if (BoxesOverlap(start, start, cmins, cmaxs))
    {
        trace->startsupercontents |= boxsupercontents;
        if ((hitsupercontentsmask & boxsupercontents) && !(skipsupercontentsmask & boxsupercontents))
        {
            trace->startsolid = true;
            trace->allsolid = true;
        }
    }
}
Referenced by Collision_ClipPointToGenericEntity().
Collision_CombineTraces()
void Collision_CombineTraces (trace_t * cliptrace, const trace_t * trace, void * touch, qbool isbmodel)
Definition at line 1914 of file collision.c.
{
    // take the 'best' answers from the new trace and combine with existing data
    if (trace->allsolid)
        cliptrace->allsolid = true;
    if (trace->startsolid)
    {
        if (isbmodel)
            cliptrace->bmodelstartsolid = true;
        cliptrace->startsolid = true;
        if (cliptrace->fraction == 1)
            cliptrace->ent = touch;
        if (cliptrace->startdepth > trace->startdepth)
        {
            cliptrace->startdepth = trace->startdepth;
            VectorCopy(trace->startdepthnormal, cliptrace->startdepthnormal);
        }
    }
    // don't set this except on the world, because it can easily confuse
    // monsters underwater if there's a bmodel involved in the trace
    // (inopen && inwater is how they check water visibility)
    //if (trace->inopen)
    //  cliptrace->inopen = true;
    if (trace->inwater)
        cliptrace->inwater = true;
    if ((trace->fraction < cliptrace->fraction) && (VectorLength2(trace->plane.normal) > 0))
    {
        cliptrace->fraction = trace->fraction;
        VectorCopy(trace->endpos, cliptrace->endpos);
        cliptrace->plane = trace->plane;
        cliptrace->ent = touch;
        cliptrace->hitsupercontents = trace->hitsupercontents;
        cliptrace->hitq3surfaceflags = trace->hitq3surfaceflags;
        cliptrace->hittexture = trace->hittexture;
    }
    cliptrace->startsupercontents |= trace->startsupercontents;
}
Referenced by CL_Cache_TraceLineSurfaces(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), SV_TraceBox(), SV_TraceLine(), and SV_TracePoint().
Collision_Init()
void Collision_Init (void)
Definition at line 25 of file collision.c.
{
    Cvar_RegisterVariable(&collision_impactnudge);
    Cvar_RegisterVariable(&collision_extendmovelength);
    Cvar_RegisterVariable(&collision_extendtracelinelength);
    Cvar_RegisterVariable(&collision_extendtraceboxlength);
    Cvar_RegisterVariable(&collision_debug_tracelineasbox);
    Cvar_RegisterVariable(&collision_cache);
    Cvar_RegisterVariable(&collision_triangle_bevelsides);
    Cvar_RegisterVariable(&collision_triangle_axialsides);
    Cvar_RegisterVariable(&collision_bih_fullrecursion);
    collision_mempool = Mem_AllocPool("collision cache", 0, NULL);
    Collision_Cache_Init(collision_mempool);
}
Referenced by World_Init().
Collision_NewBrushFromPlanes()
colbrushf_t * Collision_NewBrushFromPlanes (struct mempool_s * mempool, int numoriginalplanes, const colplanef_t * originalplanes, int supercontents, int q3surfaceflags, const texture_t * texture, int hasaabbplanes)
Collision_PointInsideBrushFloat()
qbool Collision_PointInsideBrushFloat (const vec3_t point, const colbrushf_t * brush)
Definition at line 910 of file collision.c.
{
    int nplane;
    const colplanef_t *plane;
    if (!BoxesOverlap(point, point, brush->mins, brush->maxs))
        return false;
    for (nplane = 0, plane = brush->planes;nplane < brush->numplanes;nplane++, plane++)
        if (DotProduct(plane->normal, point) > plane->dist)
            return false;
    return true;
}
Collision_TraceBrushBrushFloat()
void Collision_TraceBrushBrushFloat (trace_t * trace, const colbrushf_t * thisbrush_start, const colbrushf_t * thisbrush_end, const colbrushf_t * thatbrush_start, const colbrushf_t * thatbrush_end)
Definition at line 559 of file collision.c.
{
    int nplane, nplane2, nedge1, nedge2, hitq3surfaceflags = 0;
    int tracenumedgedirs = trace_start->numedgedirs;
    //int othernumedgedirs = other_start->numedgedirs;
    int tracenumpoints = trace_start->numpoints;
    int othernumpoints = other_start->numpoints;
    int numplanes1 = other_start->numplanes;
    int numplanes2 = numplanes1 + trace_start->numplanes;
    int numplanes3 = numplanes2 + trace_start->numedgedirs * other_start->numedgedirs * 2;
    vec_t enterfrac = -1, leavefrac = 1, startdist, enddist, ie, f, imove, enterfrac2 = -1;
    vec4_t startplane;
    vec4_t endplane;
    vec4_t newimpactplane;
    const texture_t *hittexture = NULL;
    vec_t startdepth = 1;
    vec3_t startdepthnormal;
    const texture_t *starttexture = NULL;
    VectorClear(startdepthnormal);
    Vector4Clear(newimpactplane);
    // fast case for AABB vs compiled brushes (which begin with AABB planes and also have precomputed bevels for AABB collisions)
    if (trace_start->isaabb && other_start->hasaabbplanes)
        numplanes3 = numplanes2 = numplanes1;
    // Separating Axis Theorem:
    // if a supporting vector (plane normal) can be found that separates two
    // objects, they are not colliding.
    //
    // Minkowski Sum:
    // reduce the size of one object to a point while enlarging the other to
    // represent the space that point can not occupy.
    //
    // try every plane we can construct between the two brushes and measure
    // the distance between them.
    for (nplane = 0;nplane < numplanes3;nplane++)
    {
        if (nplane < numplanes1)
        {
            nplane2 = nplane;
            VectorCopy(other_start->planes[nplane2].normal, startplane);
            VectorCopy(other_end->planes[nplane2].normal, endplane);
        }
        else if (nplane < numplanes2)
        {
            nplane2 = nplane - numplanes1;
            VectorCopy(trace_start->planes[nplane2].normal, startplane);
            VectorCopy(trace_end->planes[nplane2].normal, endplane);
        }
        else
        {
            // pick an edgedir from each brush and cross them
            nplane2 = nplane - numplanes2;
            nedge1 = nplane2 >> 1;
            nedge2 = nedge1 / tracenumedgedirs;
            nedge1 -= nedge2 * tracenumedgedirs;
            if (nplane2 & 1)
            {
                CrossProduct(trace_start->edgedirs[nedge1].v, other_start->edgedirs[nedge2].v, startplane);
                CrossProduct(trace_end->edgedirs[nedge1].v, other_end->edgedirs[nedge2].v, endplane);
            }
            else
            {
                CrossProduct(other_start->edgedirs[nedge2].v, trace_start->edgedirs[nedge1].v, startplane);
                CrossProduct(other_end->edgedirs[nedge2].v, trace_end->edgedirs[nedge1].v, endplane);
            }
            if (VectorLength2(startplane) < COLLISION_EDGECROSS_MINLENGTH2 || VectorLength2(endplane) < COLLISION_EDGECROSS_MINLENGTH2)
                continue; // degenerate crossproducts
            VectorNormalize(startplane);
            VectorNormalize(endplane);
        }
        startplane[3] = furthestplanedist_float(startplane, other_start->points, othernumpoints);
        endplane[3] = furthestplanedist_float(endplane, other_end->points, othernumpoints);
        startdist = nearestplanedist_float(startplane, trace_start->points, tracenumpoints) - startplane[3];
        enddist = nearestplanedist_float(endplane, trace_end->points, tracenumpoints) - endplane[3];
        //Con_Printf("%c%i: startdist = %f, enddist = %f, startdist / (startdist - enddist) = %f\n", nplane2 != nplane ? 'b' : 'a', nplane2, startdist, enddist, startdist / (startdist - enddist));
        // aside from collisions, this is also used for error correction
        if (startdist <= 0.0f && nplane < numplanes1 && (startdepth < startdist || startdepth == 1))
        {
            startdepth = startdist;
            VectorCopy(startplane, startdepthnormal);
            starttexture = other_start->planes[nplane2].texture;
        }
        if (startdist > enddist)
        {
            // moving into brush
            if (enddist > 0.0f)
                return;
            if (startdist >= 0)
            {
                // enter
                imove = 1 / (startdist - enddist);
                f = startdist * imove;
                // check if this will reduce the collision time range
                if (enterfrac < f)
                {
                    // reduced collision time range
                    enterfrac = f;
                    // if the collision time range is now empty, no collision
                    if (enterfrac > leavefrac)
                        return;
                    // calculate the nudged fraction and impact normal we'll
                    // need if we accept this collision later
                    enterfrac2 = (startdist - collision_impactnudge.value) * imove;
                    // if the collision would be further away than the trace's
                    // existing collision data, we don't care about this
                    // collision
                    if (enterfrac2 >= trace->fraction)
                        return;
                    ie = 1.0f - enterfrac;
                    newimpactplane[0] = startplane[0] * ie + endplane[0] * enterfrac;
                    newimpactplane[1] = startplane[1] * ie + endplane[1] * enterfrac;
                    newimpactplane[2] = startplane[2] * ie + endplane[2] * enterfrac;
                    newimpactplane[3] = startplane[3] * ie + endplane[3] * enterfrac;
                    if (nplane < numplanes1)
                    {
                        // use the plane from other
                        nplane2 = nplane;
                        hitq3surfaceflags = other_start->planes[nplane2].q3surfaceflags;
                        hittexture = other_start->planes[nplane2].texture;
                    }
                    else if (nplane < numplanes2)
                    {
                        // use the plane from trace
                        nplane2 = nplane - numplanes1;
                        hitq3surfaceflags = trace_start->planes[nplane2].q3surfaceflags;
                        hittexture = trace_start->planes[nplane2].texture;
                    }
                    else
                    {
                        hitq3surfaceflags = other_start->q3surfaceflags;
                        hittexture = other_start->texture;
                    }
                }
            }
        }
        else
        {
            // moving out of brush
            if (startdist >= 0)
                return;
            if (enddist > 0)
            {
                // leave
                f = startdist / (startdist - enddist);
                // check if this will reduce the collision time range
                if (leavefrac > f)
                {
                    // reduced collision time range
                    leavefrac = f;
                    // if the collision time range is now empty, no collision
                    if (enterfrac > leavefrac)
                        return;
                }
            }
        }
    }
    // at this point we know the trace overlaps the brush because it was not
    // rejected at any point in the loop above
    // see if the trace started outside the brush or not
    if (enterfrac > -1)
    {
        // started outside, and overlaps, therefore there is a collision here
        // store out the impact information
        if ((trace->hitsupercontentsmask & other_start->supercontents) && !(trace->skipsupercontentsmask & other_start->supercontents) && !(trace->skipmaterialflagsmask & (hittexture ? hittexture->currentmaterialflags : 0)))
        {
            trace->hitsupercontents = other_start->supercontents;
            trace->hitq3surfaceflags = hitq3surfaceflags;
            trace->hittexture = hittexture;
            trace->fraction = bound(0, enterfrac2, 1);
            VectorCopy(newimpactplane, trace->plane.normal);
            trace->plane.dist = newimpactplane[3];
        }
    }
    else
    {
        // started inside, update startsolid and friends
        trace->startsupercontents |= other_start->supercontents;
        if ((trace->hitsupercontentsmask & other_start->supercontents) && !(trace->skipsupercontentsmask & other_start->supercontents) && !(trace->skipmaterialflagsmask & (starttexture ? starttexture->currentmaterialflags : 0)))
        {
            trace->startsolid = true;
            if (leavefrac < 1)
                trace->allsolid = true;
            VectorCopy(newimpactplane, trace->plane.normal);
            trace->plane.dist = newimpactplane[3];
            if (trace->startdepth > startdepth)
            {
                trace->startdepth = startdepth;
                VectorCopy(startdepthnormal, trace->startdepthnormal);
                trace->starttexture = starttexture;
            }
        }
    }
}
Referenced by Collision_TraceBrushTriangleFloat(), Collision_TraceBrushTriangleMeshFloat(), Collision_TraceLineBrushFloat(), and Mod_CollisionBIH_TraceBrush().
Collision_TraceBrushTriangleFloat()
void Collision_TraceBrushTriangleFloat (trace_t * trace, const colbrushf_t * thisbrush_start, const colbrushf_t * thisbrush_end, const float * v0, const float * v1, const float * v2, int supercontents, int q3surfaceflags, const texture_t * texture)
Definition at line 1107 of file collision.c.
{
    int i;
    colpointf_t points[3];
    colpointf_t edgedirs[3];
    colplanef_t planes[5];
    colbrushf_t brush;
    memset(&brush, 0, sizeof(brush));
    brush.isaabb = false;
    brush.hasaabbplanes = false;
    brush.numpoints = 3;
    brush.numedgedirs = 3;
    brush.numplanes = 5;
    brush.points = points;
    brush.edgedirs = edgedirs;
    brush.planes = planes;
    brush.supercontents = supercontents;
    brush.q3surfaceflags = q3surfaceflags;
    brush.texture = texture;
    for (i = 0;i < brush.numplanes;i++)
    {
        brush.planes[i].q3surfaceflags = q3surfaceflags;
        brush.planes[i].texture = texture;
    }
    VectorCopy(v0, points[0].v);
    VectorCopy(v1, points[1].v);
    VectorCopy(v2, points[2].v);
    Collision_SnapCopyPoints(brush.numpoints, points, points, COLLISION_SNAPSCALE, COLLISION_SNAP);
    Collision_CalcEdgeDirsForPolygonBrushFloat(&brush);
    Collision_CalcPlanesForTriangleBrushFloat(&brush);
    //Collision_PrintBrushAsQHull(&brush, "brush");
    Collision_TraceBrushBrushFloat(trace, thisbrush_start, thisbrush_end, &brush, &brush);
}
Referenced by Mod_CollisionBIH_TraceBrush().
Collision_TraceBrushTriangleMeshFloat()
void Collision_TraceBrushTriangleMeshFloat (trace_t * trace, const colbrushf_t * thisbrush_start, const colbrushf_t * thisbrush_end, int numtriangles, const int * element3i, const float * vertex3f, int stride, float * bbox6f, int supercontents, int q3surfaceflags, const texture_t * texture, const vec3_t segmentmins, const vec3_t segmentmaxs)
Definition at line 996 of file collision.c.
{
    int i;
    colpointf_t points[3];
    colpointf_t edgedirs[3];
    colplanef_t planes[5];
    colbrushf_t brush;
    memset(&brush, 0, sizeof(brush));
    brush.isaabb = false;
    brush.hasaabbplanes = false;
    brush.numpoints = 3;
    brush.numedgedirs = 3;
    brush.numplanes = 5;
    brush.points = points;
    brush.edgedirs = edgedirs;
    brush.planes = planes;
    brush.supercontents = supercontents;
    brush.q3surfaceflags = q3surfaceflags;
    brush.texture = texture;
    for (i = 0;i < brush.numplanes;i++)
    {
        brush.planes[i].q3surfaceflags = q3surfaceflags;
        brush.planes[i].texture = texture;
    }
    if(stride > 0)
    {
        int k, cnt, tri;
        cnt = (numtriangles + stride - 1) / stride;
        for(i = 0; i < cnt; ++i)
        {
            if(BoxesOverlap(bbox6f + i * 6, bbox6f + i * 6 + 3, segmentmins, segmentmaxs))
            {
                for(k = 0; k < stride; ++k)
                {
                    tri = i * stride + k;
                    if(tri >= numtriangles)
                        break;
                    VectorCopy(vertex3f + element3i[tri * 3 + 0] * 3, points[0].v);
                    VectorCopy(vertex3f + element3i[tri * 3 + 1] * 3, points[1].v);
                    VectorCopy(vertex3f + element3i[tri * 3 + 2] * 3, points[2].v);
                    Collision_SnapCopyPoints(brush.numpoints, points, points, COLLISION_SNAPSCALE, COLLISION_SNAP);
                    Collision_CalcEdgeDirsForPolygonBrushFloat(&brush);
                    Collision_CalcPlanesForTriangleBrushFloat(&brush);
                    //Collision_PrintBrushAsQHull(&brush, "brush");
                    Collision_TraceBrushBrushFloat(trace, thisbrush_start, thisbrush_end, &brush, &brush);
                }
            }
        }
    }
    else if(stride == 0)
    {
        for (i = 0;i < numtriangles;i++, element3i += 3)
        {
            if (TriangleBBoxOverlapsBox(vertex3f + element3i[0]*3, vertex3f + element3i[1]*3, vertex3f + element3i[2]*3, segmentmins, segmentmaxs))
            {
                VectorCopy(vertex3f + element3i[0] * 3, points[0].v);
                VectorCopy(vertex3f + element3i[1] * 3, points[1].v);
                VectorCopy(vertex3f + element3i[2] * 3, points[2].v);
                Collision_SnapCopyPoints(brush.numpoints, points, points, COLLISION_SNAPSCALE, COLLISION_SNAP);
                Collision_CalcEdgeDirsForPolygonBrushFloat(&brush);
                Collision_CalcPlanesForTriangleBrushFloat(&brush);
                //Collision_PrintBrushAsQHull(&brush, "brush");
                Collision_TraceBrushBrushFloat(trace, thisbrush_start, thisbrush_end, &brush, &brush);
            }
        }
    }
    else
    {
        for (i = 0;i < numtriangles;i++, element3i += 3)
        {
            VectorCopy(vertex3f + element3i[0] * 3, points[0].v);
            VectorCopy(vertex3f + element3i[1] * 3, points[1].v);
            VectorCopy(vertex3f + element3i[2] * 3, points[2].v);
            Collision_SnapCopyPoints(brush.numpoints, points, points, COLLISION_SNAPSCALE, COLLISION_SNAP);
            Collision_CalcEdgeDirsForPolygonBrushFloat(&brush);
            Collision_CalcPlanesForTriangleBrushFloat(&brush);
            //Collision_PrintBrushAsQHull(&brush, "brush");
            Collision_TraceBrushBrushFloat(trace, thisbrush_start, thisbrush_end, &brush, &brush);
        }
    }
}
Referenced by Mod_MDLMD2MD3_TraceBox().
Collision_TraceLineBrushFloat()
void Collision_TraceLineBrushFloat (trace_t * trace, const vec3_t linestart, const vec3_t lineend, const colbrushf_t * thatbrush_start, const colbrushf_t * thatbrush_end)
Definition at line 760 of file collision.c.
{
    int nplane, hitq3surfaceflags = 0;
    int numplanes = other_start->numplanes;
    vec_t enterfrac = -1, leavefrac = 1, startdist, enddist, ie, f, imove, enterfrac2 = -1;
    vec4_t startplane;
    vec4_t endplane;
    vec4_t newimpactplane;
    const texture_t *hittexture = NULL;
    vec_t startdepth = 1;
    vec3_t startdepthnormal;
    const texture_t *starttexture = NULL;
    if (collision_debug_tracelineasbox.integer)
    {
        colboxbrushf_t thisbrush_start, thisbrush_end;
        Collision_BrushForBox(&thisbrush_start, linestart, linestart, 0, 0, NULL);
        Collision_BrushForBox(&thisbrush_end, lineend, lineend, 0, 0, NULL);
        Collision_TraceBrushBrushFloat(trace, &thisbrush_start.brush, &thisbrush_end.brush, other_start, other_end);
        return;
    }
    VectorClear(startdepthnormal);
    Vector4Clear(newimpactplane);
    // Separating Axis Theorem:
    // if a supporting vector (plane normal) can be found that separates two
    // objects, they are not colliding.
    //
    // Minkowski Sum:
    // reduce the size of one object to a point while enlarging the other to
    // represent the space that point can not occupy.
    //
    // try every plane we can construct between the two brushes and measure
    // the distance between them.
    for (nplane = 0;nplane < numplanes;nplane++)
    {
        VectorCopy(other_start->planes[nplane].normal, startplane);
        startplane[3] = other_start->planes[nplane].dist;
        VectorCopy(other_end->planes[nplane].normal, endplane);
        endplane[3] = other_end->planes[nplane].dist;
        startdist = DotProduct(linestart, startplane) - startplane[3];
        enddist = DotProduct(lineend, endplane) - endplane[3];
        //Con_Printf("%c%i: startdist = %f, enddist = %f, startdist / (startdist - enddist) = %f\n", nplane2 != nplane ? 'b' : 'a', nplane2, startdist, enddist, startdist / (startdist - enddist));
        // aside from collisions, this is also used for error correction
        if (startdist <= 0.0f && (startdepth < startdist || startdepth == 1))
        {
            startdepth = startdist;
            VectorCopy(startplane, startdepthnormal);
            starttexture = other_start->planes[nplane].texture;
        }
        if (startdist > enddist)
        {
            // moving into brush
            if (enddist > 0.0f)
                return;
            if (startdist > 0)
            {
                // enter
                imove = 1 / (startdist - enddist);
                f = startdist * imove;
                // check if this will reduce the collision time range
                if (enterfrac < f)
                {
                    // reduced collision time range
                    enterfrac = f;
                    // if the collision time range is now empty, no collision
                    if (enterfrac > leavefrac)
                        return;
                    // calculate the nudged fraction and impact normal we'll
                    // need if we accept this collision later
                    enterfrac2 = (startdist - collision_impactnudge.value) * imove;
                    // if the collision would be further away than the trace's
                    // existing collision data, we don't care about this
                    // collision
                    if (enterfrac2 >= trace->fraction)
                        return;
                    ie = 1.0f - enterfrac;
                    newimpactplane[0] = startplane[0] * ie + endplane[0] * enterfrac;
                    newimpactplane[1] = startplane[1] * ie + endplane[1] * enterfrac;
                    newimpactplane[2] = startplane[2] * ie + endplane[2] * enterfrac;
                    newimpactplane[3] = startplane[3] * ie + endplane[3] * enterfrac;
                    hitq3surfaceflags = other_start->planes[nplane].q3surfaceflags;
                    hittexture = other_start->planes[nplane].texture;
                }
            }
        }
        else
        {
            // moving out of brush
            if (startdist > 0)
                return;
            if (enddist > 0)
            {
                // leave
                f = startdist / (startdist - enddist);
                // check if this will reduce the collision time range
                if (leavefrac > f)
                {
                    // reduced collision time range
                    leavefrac = f;
                    // if the collision time range is now empty, no collision
                    if (enterfrac > leavefrac)
                        return;
                }
            }
        }
    }
    // at this point we know the trace overlaps the brush because it was not
    // rejected at any point in the loop above
    // see if the trace started outside the brush or not
    if (enterfrac > -1)
    {
        // started outside, and overlaps, therefore there is a collision here
        // store out the impact information
        if ((trace->hitsupercontentsmask & other_start->supercontents) && !(trace->skipsupercontentsmask & other_start->supercontents) && !(trace->skipmaterialflagsmask & (hittexture ? hittexture->currentmaterialflags : 0)))
        {
            trace->hitsupercontents = other_start->supercontents;
            trace->hitq3surfaceflags = hitq3surfaceflags;
            trace->hittexture = hittexture;
            trace->fraction = bound(0, enterfrac2, 1);
            VectorCopy(newimpactplane, trace->plane.normal);
            trace->plane.dist = newimpactplane[3];
        }
    }
    else
    {
        // started inside, update startsolid and friends
        trace->startsupercontents |= other_start->supercontents;
        if ((trace->hitsupercontentsmask & other_start->supercontents) && !(trace->skipsupercontentsmask & other_start->supercontents) && !(trace->skipmaterialflagsmask & (starttexture ? starttexture->currentmaterialflags : 0)))
        {
            trace->startsolid = true;
            if (leavefrac < 1)
                trace->allsolid = true;
            VectorCopy(newimpactplane, trace->plane.normal);
            trace->plane.dist = newimpactplane[3];
            if (trace->startdepth > startdepth)
            {
                trace->startdepth = startdepth;
                VectorCopy(startdepthnormal, trace->startdepthnormal);
                trace->starttexture = starttexture;
            }
        }
    }
}
Referenced by Collision_ClipTrace_Box(), and Mod_CollisionBIH_TraceLineShared().
Collision_TraceLineTriangleFloat()
void Collision_TraceLineTriangleFloat (trace_t * trace, const vec3_t linestart, const vec3_t lineend, const float * point0, const float * point1, const float * point2, int supercontents, int q3surfaceflags, const texture_t * texture)
Definition at line 1251 of file collision.c.
{
    float d1, d2, d, f, f2, impact[3], edgenormal[3], faceplanenormal[3], faceplanedist, faceplanenormallength2, edge01[3], edge21[3], edge02[3];
    // this function executes:
    // 32 ops when line starts behind triangle
    // 38 ops when line ends infront of triangle
    // 43 ops when line fraction is already closer than this triangle
    // 72 ops when line is outside edge 01
    // 92 ops when line is outside edge 21
    // 115 ops when line is outside edge 02
    // 123 ops when line impacts triangle and updates trace results
    // this code is designed for clockwise triangles, conversion to
    // counterclockwise would require swapping some things around...
    // it is easier to simply swap the point0 and point2 parameters to this
    // function when calling it than it is to rewire the internals.
    // calculate the faceplanenormal of the triangle, this represents the front side
    // 15 ops
    VectorSubtract(point0, point1, edge01);
    VectorSubtract(point2, point1, edge21);
    CrossProduct(edge01, edge21, faceplanenormal);
    // there's no point in processing a degenerate triangle (GIGO - Garbage In, Garbage Out)
    // 6 ops
    faceplanenormallength2 = DotProduct(faceplanenormal, faceplanenormal);
    if (faceplanenormallength2 < 0.0001f)
        return;
    // calculate the distance
    // 5 ops
    faceplanedist = DotProduct(point0, faceplanenormal);
    // if start point is on the back side there is no collision
    // (we don't care about traces going through the triangle the wrong way)
    // calculate the start distance
    // 6 ops
    d1 = DotProduct(faceplanenormal, linestart);
    if (d1 <= faceplanedist)
        return;
    // calculate the end distance
    // 6 ops
    d2 = DotProduct(faceplanenormal, lineend);
    // if both are in front, there is no collision
    if (d2 >= faceplanedist)
        return;
    // from here on we know d1 is >= 0 and d2 is < 0
    // this means the line starts infront and ends behind, passing through it
    // calculate the recipricol of the distance delta,
    // so we can use it multiple times cheaply (instead of division)
    // 2 ops
    d = 1.0f / (d1 - d2);
    // calculate the impact fraction by taking the start distance (> 0)
    // and subtracting the face plane distance (this is the distance of the
    // triangle along that same normal)
    // then multiply by the recipricol distance delta
    // 4 ops
    f = (d1 - faceplanedist) * d;
    f2  = f - collision_impactnudge.value * d;
    // skip out if this impact is further away than previous ones
    // 1 ops
    if (f2 >= trace->fraction)
        return;
    // calculate the perfect impact point for classification of insidedness
    // 9 ops
    impact[0] = linestart[0] + f * (lineend[0] - linestart[0]);
    impact[1] = linestart[1] + f * (lineend[1] - linestart[1]);
    impact[2] = linestart[2] + f * (lineend[2] - linestart[2]);
    // calculate the edge normal and reject if impact is outside triangle
    // (an edge normal faces away from the triangle, to get the desired normal
    //  a crossproduct with the faceplanenormal is used, and because of the way
    // the insidedness comparison is written it does not need to be normalized)
    // first use the two edges from the triangle plane math
    // the other edge only gets calculated if the point survives that long
    // 20 ops
    CrossProduct(edge01, faceplanenormal, edgenormal);
    if (DotProduct(impact, edgenormal) > DotProduct(point1, edgenormal))
        return;
    // 20 ops
    CrossProduct(faceplanenormal, edge21, edgenormal);
    if (DotProduct(impact, edgenormal) > DotProduct(point2, edgenormal))
        return;
    // 23 ops
    VectorSubtract(point0, point2, edge02);
    CrossProduct(faceplanenormal, edge02, edgenormal);
    if (DotProduct(impact, edgenormal) > DotProduct(point0, edgenormal))
        return;
    // 8 ops (rare)
    // skip if this trace should not be blocked by these contents
    if (!(supercontents & trace->hitsupercontentsmask) || (supercontents & trace->skipsupercontentsmask) || (texture->currentmaterialflags & trace->skipmaterialflagsmask))
        return;
    // store the new trace fraction
    trace->fraction = f2;
    // store the new trace plane (because collisions only happen from
    // the front this is always simply the triangle normal, never flipped)
    d = 1.0 / sqrt(faceplanenormallength2);
    VectorScale(faceplanenormal, d, trace->plane.normal);
    trace->plane.dist = faceplanedist * d;
    trace->hitsupercontents = supercontents;
    trace->hitq3surfaceflags = q3surfaceflags;
    trace->hittexture = texture;
}
Referenced by Collision_TraceLineTriangleMeshFloat(), and Mod_CollisionBIH_TraceLineShared().
Collision_TraceLineTriangleMeshFloat()
void Collision_TraceLineTriangleMeshFloat (trace_t * trace, const vec3_t linestart, const vec3_t lineend, int numtriangles, const int * element3i, const float * vertex3f, int stride, float * bbox6f, int supercontents, int q3surfaceflags, const texture_t * texture, const vec3_t segmentmins, const vec3_t segmentmaxs)
Definition at line 1078 of file collision.c.
{
    int i;
    // FIXME: snap vertices?
    if(stride > 0)
    {
        int k, cnt, tri;
        cnt = (numtriangles + stride - 1) / stride;
        for(i = 0; i < cnt; ++i)
        {
            if(BoxesOverlap(bbox6f + i * 6, bbox6f + i * 6 + 3, segmentmins, segmentmaxs))
            {
                for(k = 0; k < stride; ++k)
                {
                    tri = i * stride + k;
                    if(tri >= numtriangles)
                        break;
                    Collision_TraceLineTriangleFloat(trace, linestart, lineend, vertex3f + element3i[tri * 3 + 0] * 3, vertex3f + element3i[tri * 3 + 1] * 3, vertex3f + element3i[tri * 3 + 2] * 3, supercontents, q3surfaceflags, texture);
                }
            }
        }
    }
    else
    {
        for (i = 0;i < numtriangles;i++, element3i += 3)
            Collision_TraceLineTriangleFloat(trace, linestart, lineend, vertex3f + element3i[0] * 3, vertex3f + element3i[1] * 3, vertex3f + element3i[2] * 3, supercontents, q3surfaceflags, texture);
    }
}
Referenced by Mod_MDLMD2MD3_TraceLine().
Collision_TracePointBrushFloat()
void Collision_TracePointBrushFloat (trace_t * trace, const vec3_t point, const colbrushf_t * thatbrush)
Definition at line 923 of file collision.c.
{
    int nplane;
    int numplanes = other_start->numplanes;
    vec_t startdist;
    vec4_t startplane;
    vec4_t newimpactplane;
    vec_t startdepth = 1;
    vec3_t startdepthnormal;
    const texture_t *starttexture = NULL;
    VectorClear(startdepthnormal);
    Vector4Clear(newimpactplane);
    // Separating Axis Theorem:
    // if a supporting vector (plane normal) can be found that separates two
    // objects, they are not colliding.
    //
    // Minkowski Sum:
    // reduce the size of one object to a point while enlarging the other to
    // represent the space that point can not occupy.
    //
    // try every plane we can construct between the two brushes and measure
    // the distance between them.
    for (nplane = 0; nplane < numplanes; nplane++)
    {
        VectorCopy(other_start->planes[nplane].normal, startplane);
        startplane[3] = other_start->planes[nplane].dist;
        startdist = DotProduct(linestart, startplane) - startplane[3];
        if (startdist > 0)
            return;
        // aside from collisions, this is also used for error correction
        if (startdepth < startdist || startdepth == 1)
        {
            startdepth = startdist;
            VectorCopy(startplane, startdepthnormal);
            starttexture = other_start->planes[nplane].texture;
        }
    }
    // at this point we know the trace overlaps the brush because it was not
    // rejected at any point in the loop above
    // started inside, update startsolid and friends
    trace->startsupercontents |= other_start->supercontents;
    if ((trace->hitsupercontentsmask & other_start->supercontents) && !(trace->skipsupercontentsmask & other_start->supercontents) && !(trace->skipmaterialflagsmask & (starttexture ? starttexture->currentmaterialflags : 0)))
    {
        trace->startsolid = true;
        trace->allsolid = true;
        VectorCopy(newimpactplane, trace->plane.normal);
        trace->plane.dist = newimpactplane[3];
        if (trace->startdepth > startdepth)
        {
            trace->startdepth = startdepth;
            VectorCopy(startdepthnormal, trace->startdepthnormal);
            trace->starttexture = starttexture;
        }
    }
}
Referenced by Mod_CollisionBIH_TracePoint().
Variable Documentation
collision_bih_fullrecursion
struct cvar_s collision_bih_fullrecursion extern
Definition at line 21 of file collision.c.
{CF_CLIENT | CF_SERVER, "collision_bih_fullrecursion", "0", "debugging option to disable the bih recursion optimizations by iterating the entire tree"};
Referenced by Collision_Init(), and Mod_CollisionBIH_TraceLineShared().
collision_extendmovelength
struct cvar_s collision_extendmovelength extern
Definition at line 14 of file collision.c.
{CF_CLIENT | CF_SERVER, "collision_extendmovelength", "16", "internal bias on trace length to ensure detection of collisions within the collision_impactnudge distance so that short moves do not degrade across frames (this does not alter the final trace length)"};
Referenced by CL_CheckBottom(), CL_ClientMovement_Move(), CL_ClientMovement_Physics_Walk(), CL_ClientMovement_Unstick(), CL_ClientMovement_UpdateStatus(), CL_LinkNetworkEntity(), CL_movestep(), CL_NewParticle(), CL_ParticleExplosion(), CL_SpawnDecalParticleForPoint(), CL_Trace_Toss(), Collision_Cache_ClipLineToGenericEntitySurfaces(), Collision_Cache_ClipLineToWorldSurfaces(), Collision_Init(), PHYS_NudgeOutOfSolid(), R_CompleteLightPoint(), R_DrawParticles(), R_MoveExplosion(), R_NewExplosion(), R_Shadow_BounceGrid_TracePhotons_Shot(), R_Shadow_SelectLightInView(), R_Shadow_SetCursorLocationForView(), Sbar_ShowFPS(), SV_CheckBottom(), SV_Ent_Create_f(), SV_Ent_Remove_f(), SV_movestep(), SV_NudgeOutOfSolid_PivotIsKnownGood(), SV_PushEntity(), SV_PushMove(), SV_SetIdealPitch(), SV_TestEntityPosition(), SV_Trace_Toss(), SV_UserFriction(), SV_WalkMove(), V_CalcRefdefUsing(), VM_CL_checkbottom(), VM_CL_droptofloor(), VM_SV_aim(), and VM_SV_droptofloor().
collision_extendtraceboxlength
struct cvar_s collision_extendtraceboxlength extern
Definition at line 15 of file collision.c.
{CF_CLIENT | CF_SERVER, "collision_extendtraceboxlength", "1", "internal bias for tracebox() qc builtin to account for collision_impactnudge (this does not alter the final trace length)"};
Referenced by Collision_Init(), VM_CL_tracebox(), and VM_SV_tracebox().
collision_extendtracelinelength
struct cvar_s collision_extendtracelinelength extern
Definition at line 16 of file collision.c.
{CF_CLIENT | CF_SERVER, "collision_extendtracelinelength", "1", "internal bias for traceline() qc builtin to account for collision_impactnudge (this does not alter the final trace length)"};
Referenced by Collision_Init(), VM_CL_traceline(), and VM_SV_traceline().
collision_impactnudge
struct cvar_s collision_impactnudge extern
Definition at line 13 of file collision.c.
{CF_CLIENT | CF_SERVER, "collision_impactnudge", "0.03125", "how much to back off from the impact"};
Referenced by Collision_Init(), Collision_TraceBrushBrushFloat(), Collision_TraceLineBrushFloat(), Collision_TraceLineTriangleFloat(), Mod_Q1BSP_RecursiveHullCheck(), and Mod_Q1BSP_TraceLineAgainstSurfacesFindTextureOnNode().