DarkPlaces: com_infostring.c File Reference
com_infostring.c File Reference
#include "darkplaces.h"
Functions
size_t InfoString_GetValue (const char *buffer, const char *key, char *value, size_t valuesize)
Returns the number of bytes written to *value excluding the \0 terminator.
void InfoString_SetValue (char *buffer, size_t bufferlength, const char *key, const char *value)
void InfoString_Print (char *buffer)
Function Documentation
InfoString_GetValue()
size_t InfoString_GetValue (const char * buffer, const char * key, char * value, size_t valuesize)
Returns the number of bytes written to *value excluding the \0 terminator.
Definition at line 23 of file com_infostring.c.
{
    unsigned pos = 0, j;
    size_t keylength;
    if (!key)
        key = "";
    keylength = strlen(key);
    if (valuesize < 1 || !value)
    {
        Con_Printf("InfoString_GetValue: no room in value\n");
        return 0;
    }
    value[0] = '\0';
    if (strchr(key, '\\'))
    {
        Con_Printf("InfoString_GetValue: key name \"%s\" contains \\ which is not possible in an infostring\n", key);
        return 0;
    }
    if (strchr(key, '\"'))
    {
        Con_Printf("InfoString_SetValue: key name \"%s\" contains \" which is not allowed in an infostring\n", key);
        return 0;
    }
    if (!key[0])
    {
        Con_Printf("InfoString_GetValue: can not look up a key with no name\n");
        return 0;
    }
    while (buffer[pos] == '\\')
    {
        if (!memcmp(buffer + pos+1, key, keylength) &&
                (buffer[pos+1 + keylength] == 0 ||
                 buffer[pos+1 + keylength] == '\\'))
        {
            pos += 1 + keylength;           // Skip \key
            if (buffer[pos] == '\\') pos++; // Skip \ before value.
            for (j = 0;buffer[pos+j] && buffer[pos+j] != '\\' && j < valuesize - 1;j++)
                value[j] = buffer[pos+j];
            value[j] = '\0';
            return j;
        }
        if (buffer[pos] == '\\') pos++; // Skip \ before value.
        for (pos++;buffer[pos] && buffer[pos] != '\\';pos++);
        if (buffer[pos] == '\\') pos++; // Skip \ before value.
        for (pos++;buffer[pos] && buffer[pos] != '\\';pos++);
    }
    // if we reach this point the key was not found
    return 0;
}
Referenced by CL_FullServerinfo_f(), CL_Reconnect_f(), Crypto_ClientParsePacket(), Crypto_ServerParsePacket(), Crypto_ServerParsePacket_Internal(), Curl_Begin(), NetConn_ClientParsePacket(), NetConn_ServerParsePacket(), QW_CL_ProcessUserInfo(), QW_CL_ServerInfo(), VM_CL_serverkey(), VM_infoget(), and VM_SV_serverkey().
InfoString_Print()
void InfoString_Print (char * buffer)
Definition at line 136 of file com_infostring.c.
{
    int i;
    char key[MAX_INPUTLINE];
    char value[MAX_INPUTLINE];
    while (*buffer)
    {
        if (*buffer != '\\')
        {
            Con_Printf("InfoString_Print: corrupt string\n");
            return;
        }
        for (buffer++, i = 0;*buffer && *buffer != '\\';buffer++)
            if (i < (int)sizeof(key)-1)
                key[i++] = *buffer;
        key[i] = 0;
        if (*buffer != '\\')
        {
            Con_Printf("InfoString_Print: corrupt string\n");
            return;
        }
        for (buffer++, i = 0;*buffer && *buffer != '\\';buffer++)
            if (i < (int)sizeof(value)-1)
                value[i++] = *buffer;
        value[i] = 0;
        // empty value is an error case
        Con_Printf("%20s %s\n", key, value[0] ? value : "NO VALUE");
    }
}
Referenced by CL_SetInfo_f(), and CL_User_f().
InfoString_SetValue()
void InfoString_SetValue (char * buffer, size_t bufferlength, const char * key, const char * value)
Definition at line 74 of file com_infostring.c.
{
    int pos = 0, pos2;
    size_t keylength;
    if (!key)
        key = "";
    if (!value)
        value = "";
    keylength = strlen(key);
    if (strchr(key, '\\') || strchr(value, '\\'))
    {
        Con_Printf("InfoString_SetValue: \"%s\" \"%s\" contains \\ which is not possible to store in an infostring\n", key, value);
        return;
    }
    if (strchr(key, '\"') || strchr(value, '\"'))
    {
        Con_Printf("InfoString_SetValue: \"%s\" \"%s\" contains \" which is not allowed in an infostring\n", key, value);
        return;
    }
    if (!key[0])
    {
        Con_Printf("InfoString_SetValue: can not set a key with no name\n");
        return;
    }
    while (buffer[pos] == '\\')
    {
        if (!memcmp(buffer + pos+1, key, keylength) &&
                (buffer[pos+1 + keylength] == 0 ||
                 buffer[pos+1 + keylength] == '\\'))
            break;
        if (buffer[pos] == '\\') pos++; // Skip \ before value.
        for (;buffer[pos] && buffer[pos] != '\\';pos++);
        if (buffer[pos] == '\\') pos++; // Skip \ before value.
        for (;buffer[pos] && buffer[pos] != '\\';pos++);
    }
    // if we found the key, find the end of it because we will be replacing it
    pos2 = pos;
    if (buffer[pos] == '\\')
    {
        pos2 += 1 + (int)keylength;  // Skip \key
        if (buffer[pos2] == '\\') pos2++; // Skip \ before value.
        for (;buffer[pos2] && buffer[pos2] != '\\';pos2++);
    }
    if (bufferlength <= pos + 1 + strlen(key) + 1 + strlen(value) + strlen(buffer + pos2))
    {
        Con_Printf("InfoString_SetValue: no room for \"%s\" \"%s\" in infostring\n", key, value);
        return;
    }
    if (value[0])
    {
        // set the key/value and append the remaining text
        char tempbuffer[MAX_INPUTLINE];
        dp_strlcpy(tempbuffer, buffer + pos2, sizeof(tempbuffer));
        dpsnprintf(buffer + pos, bufferlength - pos, "\\%s\\%s%s", key, value, tempbuffer);
    }
    else
    {
        // just remove the key from the text
        dp_strlcpy(buffer + pos, buffer + pos2, bufferlength - pos);
    }
}
Referenced by CL_EstablishConnection(), CL_SetInfo(), Cvar_SetQuick_Internal(), NetConn_ClientParsePacket(), QW_CL_ServerInfo(), QW_CL_SetInfo(), and VM_infoadd().