DarkPlaces: com_list.h File Reference
com_list.h File Reference
#include <stddef.h>
#include "qtypes.h"
#include "qdefs.h"
Data Structures
struct llist_t
Macros
#define LIST_HEAD_INIT(name) { &(name), &(name) }
#define LIST_HEAD(name) struct llist_s name = LIST_HEAD_INIT(name)
#define List_Entry(ptr, type, member) ContainerOf(ptr, type, member)
#define List_First_Entry(ptr, type, member) List_Entry((ptr)->next, type, member)
#define List_Last_Entry(ptr, type, member) List_Entry((ptr)->prev, type, member)
#define List_First_Entry_Or_Null(ptr, type, member)
#define List_Next_Entry(pos, type, member) List_Entry((pos)->member.next, type, member)
#define List_Prev_Entry(pos, type, member) List_Entry((pos)->member.prev, type, member)
#define List_For_Each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
#define List_For_Each_Continue(pos, head) for (pos = pos->next; pos != (head); pos = pos->next)
#define List_For_Each_Prev(pos, head) for (pos = (head)->prev; pos != (head); pos = pos->prev)
#define List_For_Each_Safe(pos, n, head)
#define List_For_Each_Prev_Safe(pos, n, head)
#define List_Entry_Is_Head(pos, head, member) (&pos->member == (head))
#define List_For_Each_Entry(pos, head, type, member)
#define List_For_Each_Prev_Entry(pos, head, type, member)
#define List_Prepare_Entry(pos, head, type, member) ((pos) ? : List_Entry(head, type, member))
#define List_For_Each_Entry_Continue(pos, head, type, member)
#define List_For_Each_Prev_Entry_Continue(pos, head, type, member)
#define List_For_Each_Entry_From(pos, head, type, member)
#define List_For_Each_Prev_Entry_From(pos, head, type, member)
#define List_For_Each_Entry_Safe(pos, n, head, type, member)
#define List_For_Each_Entry_Safe_Continue(pos, n, head, type, member)
#define List_For_Each_Entry_Safe_From(pos, n, head, type, member)
#define List_For_Each_Prev_Entry_Safe(pos, n, head, type, member)
#define List_Safe_Reset_Next(pos, n, type, member) n = List_Next_Entry(pos, type, member)
Functions
static qbool List_Is_Empty (const llist_t *list)
static void List_Create (llist_t *list)
static void __List_Add (llist_t *node, llist_t *prev, llist_t *next)
static void List_Add (llist_t *node, llist_t *head)
static void List_Add_Tail (llist_t *node, llist_t *head)
static void __List_Delete (llist_t *prev, llist_t *next)
static void __List_Delete_Node (llist_t *node)
static void List_Delete (llist_t *node)
static void List_Delete_Init (llist_t *node)
static void List_Replace (llist_t *old, llist_t *_new)
static void List_Replace_Init (llist_t *old, llist_t *_new)
static void List_Swap (llist_t *node1, llist_t *node2)
static void List_Move (llist_t *list, llist_t *head)
static void List_Move_Tail (llist_t *list, llist_t *head)
static void List_Bulk_Move_Tail (llist_t *head, llist_t *first, llist_t *last)
static void List_Rotate_Left (llist_t *head)
static void List_Rotate_To_Front (llist_t *list, llist_t *head)
static void __List_Splice (const llist_t *list, llist_t *prev, llist_t *next)
static void List_Splice (const llist_t *list, llist_t *head)
static void List_Splice_Tail (const llist_t *list, llist_t *head)
static qbool List_Is_First (llist_t *list, llist_t *start)
static qbool List_Is_Last (llist_t *list, llist_t *start)
Macro Definition Documentation
List_Entry
#define List_Entry (ptr, type, member) ContainerOf(ptr, type, member)
Definition at line 44 of file com_list.h.
List_Entry_Is_Head
#define List_Entry_Is_Head (pos, head, member) (&pos->member == (head))
Definition at line 115 of file com_list.h.
             : List_Entry(head, type, member))
/*
 * Continue iteration over a list of a given type, after the current position
 */
#define List_For_Each_Entry_Continue(pos, head, type, member) \
    for (pos = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Next_Entry(pos, type, member))
/*
 * Continue iteration over a list of a given type backwards, after the current position
 */
#define List_For_Each_Prev_Entry_Continue(pos, head, type, member) \
    for (pos = List_Prev_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Prev_Entry(pos, type, member))
/*
 * Continue iteration over a list of a given type, from the current position
 */
#define List_For_Each_Entry_From(pos, head, type, member) \
    for (; !List_Entry_Is_Head(pos, head, member); \
         pos = List_Next_Entry(pos, type, member))
/*
 * Continue iteration over a list of a given type backwards, from the current position
 */
#define List_For_Each_Prev_Entry_From(pos, head, type, member) \
    for (; !List_Entry_Is_Head(pos, head, member); \
         pos = List_Prev_Entry(pos, type, member))
/*
 * Iterate over a list of a given type, safe against removal of list entry
 */
#define List_For_Each_Entry_Safe(pos, n, head, type, member) \
    for (pos = List_First_Entry(head, type, member), \
         n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
/*
 * Continue iteration over a list of a given type, after the current position, safe against removal of list entry
 */
#define List_For_Each_Entry_Safe_Continue(pos, n, head, type, member) \
    for (pos = List_Next_Entry(pos, type, member), \
         n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
/*
 * Continue iteration over a list of a given type, from the current position, safe against removal of list entry
 */
#define List_For_Each_Entry_Safe_From(pos, n, head, type, member) \
    for (n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
/*
 * Iterate over a list of a given type backwards, safe against removal of list entry
 */
#define List_For_Each_Prev_Entry_Safe(pos, n, head, type, member) \
    for (pos = List_Last_Entry(head, type, member), \
         n = List_Prev_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Prev_Entry(n, type, member))
/*
 * Reset a stale List_For_Each_Entry_Safe loop
 */
#define List_Safe_Reset_Next(pos, n, type, member) \
    n = List_Next_Entry(pos, type, member)
static inline qbool List_Is_Empty(const llist_t *list)
{
    return list->next == list;
}
/*
 * Creates a new linked list. Initializes the head to point to itself.
 * If it's a list header, the result is an empty list.
 */
static inline void List_Create(llist_t *list)
{
    list->next = list->prev = list;
}
/*
 * Insert a node between two known nodes.
 *
 * Only use when prev and next are known.
 */
static inline void __List_Add(llist_t *node, llist_t *prev, llist_t *next)
{
    next->prev = node;
    node->next = next;
    node->prev = prev;
    prev->next = node;
}
/*
 * Insert a node immediately after head.
 */
static inline void List_Add(llist_t *node, llist_t *head)
{
    __List_Add(node, head, head->next);
}
/*
 * Insert a node immediately before head.
 */
static inline void List_Add_Tail(llist_t *node, llist_t *head)
{
    __List_Add(node, head->prev, head);
}
/*
 * Bridge prev and next together, when removing the parent of them.
 */
static inline void __List_Delete(llist_t *prev, llist_t *next)
{
    next->prev = prev;
    prev->next = next;
}
/*
 * Redundant?
 */
static inline void __List_Delete_Node(llist_t *node)
{
    __List_Delete(node->prev, node->next);
}
/*
 * Removes a node from its list. Sets its pointers to NULL.
 */
static inline void List_Delete(llist_t *node)
{
    __List_Delete_Node(node);
    node->next = node->prev = NULL;
}
/*
 * Removes a node from its list. Reinitialize it.
 */
static inline void List_Delete_Init(llist_t *node)
{
    __List_Delete_Node(node);
    node->next = node->prev = node;
}
/*
 * Replace old with new. Old is overwritten if empty.
 */
static inline void List_Replace(llist_t *old, llist_t *_new)
{
    _new->next = old->next;
    _new->next->prev = _new;
    _new->prev = old->prev;
    _new->prev->next = _new;
    old->next = old->prev = old;
}
/*
 * Replace old with new. Initialize old.
 * Old is overwritten if empty.
 */
static inline void List_Replace_Init(llist_t *old, llist_t *_new)
{
    List_Replace(old, _new);
    List_Create(old);
}
/*
 * Swap node1 with node2 in place.
 */
static inline void List_Swap(llist_t *node1, llist_t *node2)
{
    llist_t *pos = node2->prev;
    List_Delete_Init(node2);
    List_Replace(node1, node2);
    if(pos == node1)
        pos = node2;
    List_Add(node1, pos);
}
/*
 * Delete list from its... list, then insert after head.
 */
static inline void List_Move(llist_t *list, llist_t *head)
{
    __List_Delete_Node(list);
    List_Add(list, head);
}
/*
 * Delete list from its... list, then insert before head.
 */
static inline void List_Move_Tail(llist_t *list, llist_t *head)
{
    __List_Delete_Node(list);
    List_Add_Tail(list, head);
}
/*
 * Move the first node of a range of nodes immediately after head.
 * All three parameters must belong to the same list.
 */
static inline void List_Bulk_Move_Tail(llist_t *head, llist_t *first, llist_t *last)
{
    first->prev->next = last->next;
    last->next->prev = first->prev;
    head->prev->next = first;
    first->prev = head->prev;
    last->next = head;
    head->prev = last;
}
/*
 * Shift the head to the right (like rotating a wheel counterclockwise).
 * The node immediately to the right becomes the new head.
 */
static inline void List_Rotate_Left(llist_t *head)
{
    llist_t *first;
    if (!List_Is_Empty(head))
    {
        first = head->next;
        List_Move_Tail(first, head);
    }
}
/*
 * Make list the new head.
 */
static inline void List_Rotate_To_Front(llist_t *list, llist_t *head)
{
    List_Move_Tail(head, list);
}
/*
 * Concatenate two lists. The head of list will be discarded.
 */
static inline void __List_Splice(const llist_t *list, llist_t *prev, llist_t *next)
{
    llist_t *first = list->next;
    llist_t *last = list->prev;
    first->prev = prev;
    prev->next = first;
    last->next = next;
    next->prev = last;
}
/*
 * Concatenate two lists. The first node of list will be inserted after head.
 */
static inline void List_Splice(const llist_t *list, llist_t *head)
{
    if(!List_Is_Empty(list))
        __List_Splice(list, head, head->next);
}
/*
 * Concatenate two lists. The tail of list will be inserted before head.
 */
static inline void List_Splice_Tail(const llist_t *list, llist_t *head)
{
    if (!List_Is_Empty(list))
        __List_Splice(list, head->prev, head);
}
static inline qbool List_Is_First(llist_t *list, llist_t *start)
{
    return list->prev == start;
}
static inline qbool List_Is_Last(llist_t *list, llist_t *start)
{
    return list->next == start;
}
#endif
List_First_Entry
#define List_First_Entry (ptr, type, member) List_Entry((ptr)->next, type, member)
Definition at line 50 of file com_list.h.
List_First_Entry_Or_Null
#define List_First_Entry_Or_Null (ptr, type, member)
Value:
    ({ \
    struct llist_s *head__ = (ptr); \
    struct llist_s *pos__ = head__->next; \
    pos__ != head__ ? List_Entry(pos__, type, member) : NULL; \
})
Definition at line 61 of file com_list.h.
                                                     { \
    struct llist_s *head__ = (ptr); \
    struct llist_s *pos__ = head__->next; \
    pos__ != head__ ? List_Entry(pos__, type, member) : NULL; \
})
List_For_Each
#define List_For_Each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
Definition at line 82 of file com_list.h.
List_For_Each_Continue
#define List_For_Each_Continue (pos, head) for (pos = pos->next; pos != (head); pos = pos->next)
Definition at line 88 of file com_list.h.
List_For_Each_Entry
#define List_For_Each_Entry (pos, head, type, member)
Value:
    for (pos = List_First_Entry(head, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Next_Entry(pos, type, member))
Definition at line 121 of file com_list.h.
List_For_Each_Entry_Continue
#define List_For_Each_Entry_Continue (pos, head, type, member)
Value:
    for (pos = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Next_Entry(pos, type, member))
Definition at line 143 of file com_list.h.
List_For_Each_Entry_From
#define List_For_Each_Entry_From (pos, head, type, member)
Value:
    for (; !List_Entry_Is_Head(pos, head, member); \
         pos = List_Next_Entry(pos, type, member))
Definition at line 159 of file com_list.h.
List_For_Each_Entry_Safe
#define List_For_Each_Entry_Safe (pos, n, head, type, member)
Value:
    for (pos = List_First_Entry(head, type, member), \
         n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
Definition at line 173 of file com_list.h.
List_For_Each_Entry_Safe_Continue
#define List_For_Each_Entry_Safe_Continue (pos, n, head, type, member)
Value:
    for (pos = List_Next_Entry(pos, type, member), \
         n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
Definition at line 182 of file com_list.h.
List_For_Each_Entry_Safe_From
#define List_For_Each_Entry_Safe_From (pos, n, head, type, member)
Value:
    for (n = List_Next_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Next_Entry(n, type, member))
Definition at line 191 of file com_list.h.
List_For_Each_Prev
#define List_For_Each_Prev (pos, head) for (pos = (head)->prev; pos != (head); pos = pos->prev)
Definition at line 94 of file com_list.h.
List_For_Each_Prev_Entry
#define List_For_Each_Prev_Entry (pos, head, type, member)
Value:
    for (pos = List_Last_Entry(head, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Prev_Entry(pos, type, member))
Definition at line 129 of file com_list.h.
List_For_Each_Prev_Entry_Continue
#define List_For_Each_Prev_Entry_Continue (pos, head, type, member)
Value:
    for (pos = List_Prev_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = List_Prev_Entry(pos, type, member))
Definition at line 151 of file com_list.h.
List_For_Each_Prev_Entry_From
#define List_For_Each_Prev_Entry_From (pos, head, type, member)
Value:
    for (; !List_Entry_Is_Head(pos, head, member); \
         pos = List_Prev_Entry(pos, type, member))
Definition at line 166 of file com_list.h.
List_For_Each_Prev_Entry_Safe
#define List_For_Each_Prev_Entry_Safe (pos, n, head, type, member)
Value:
    for (pos = List_Last_Entry(head, type, member), \
         n = List_Prev_Entry(pos, type, member); \
         !List_Entry_Is_Head(pos, head, member); \
         pos = n, n = List_Prev_Entry(n, type, member))
Definition at line 199 of file com_list.h.
List_For_Each_Prev_Safe
#define List_For_Each_Prev_Safe (pos, n, head)
Value:
    for (pos = (head)->prev, n = pos->prev; \
         pos != (head); \
         pos = n, n = pos->prev)
Definition at line 107 of file com_list.h.
List_For_Each_Safe
#define List_For_Each_Safe (pos, n, head)
Value:
    for (pos = (head)->next, n = pos->next; pos != (head); \
         pos = n, n = pos->next)
Definition at line 100 of file com_list.h.
LIST_HEAD
#define LIST_HEAD (name) struct llist_s name = LIST_HEAD_INIT(name)
Definition at line 38 of file com_list.h.
LIST_HEAD_INIT
#define LIST_HEAD_INIT (name) { &(name), &(name) }
Definition at line 36 of file com_list.h.
List_Last_Entry
#define List_Last_Entry (ptr, type, member) List_Entry((ptr)->prev, type, member)
Definition at line 56 of file com_list.h.
List_Next_Entry
#define List_Next_Entry (pos, type, member) List_Entry((pos)->member.next, type, member)
Definition at line 70 of file com_list.h.
List_Prepare_Entry
#define List_Prepare_Entry (pos, head, type, member) ((pos) ? : List_Entry(head, type, member))
Definition at line 137 of file com_list.h.
             : List_Entry(head, type, member))
List_Prev_Entry
#define List_Prev_Entry (pos, type, member) List_Entry((pos)->member.prev, type, member)
Definition at line 76 of file com_list.h.
List_Safe_Reset_Next
#define List_Safe_Reset_Next (pos, n, type, member) n = List_Next_Entry(pos, type, member)
Definition at line 208 of file com_list.h.
Function Documentation
__List_Add()
static void __List_Add (llist_t * node, llist_t * prev, llist_t * next) inline static
Definition at line 230 of file com_list.h.
{
    next->prev = node;
    node->next = next;
    node->prev = prev;
    prev->next = node;
}
Referenced by List_Add(), and List_Add_Tail().
__List_Delete()
static void __List_Delete (llist_t * prev, llist_t * next) inline static
Definition at line 257 of file com_list.h.
{
    next->prev = prev;
    prev->next = next;
}
Referenced by __List_Delete_Node().
__List_Delete_Node()
static void __List_Delete_Node (llist_t * node) inline static
Definition at line 266 of file com_list.h.
{
    __List_Delete(node->prev, node->next);
}
Referenced by List_Delete(), List_Delete_Init(), List_Move(), and List_Move_Tail().
__List_Splice()
static void __List_Splice (const llist_t * list, llist_t * prev, llist_t * next) inline static
Definition at line 385 of file com_list.h.
{
    llist_t *first = list->next;
    llist_t *last = list->prev;
    first->prev = prev;
    prev->next = first;
    last->next = next;
    next->prev = last;
}
Referenced by List_Splice(), and List_Splice_Tail().
List_Add()
static void List_Add (llist_t * node, llist_t * head) inline static
Definition at line 241 of file com_list.h.
{
    __List_Add(node, head, head->next);
}
Referenced by _Mem_Alloc(), Curl_Begin(), List_Move(), and List_Swap().
List_Add_Tail()
static void List_Add_Tail (llist_t * node, llist_t * head) inline static
Definition at line 249 of file com_list.h.
{
    __List_Add(node, head->prev, head);
}
Referenced by LHNET_OpenSocket_Connectionless(), LHNET_Write(), List_Move_Tail(), and World_InsertLinkBefore().
List_Bulk_Move_Tail()
static void List_Bulk_Move_Tail (llist_t * head, llist_t * first, llist_t * last) inline static
Definition at line 347 of file com_list.h.
{
    first->prev->next = last->next;
    last->next->prev = first->prev;
    head->prev->next = first;
    first->prev = head->prev;
    last->next = head;
    head->prev = last;
}
List_Create()
static void List_Create (llist_t * list) inline static
Definition at line 220 of file com_list.h.
{
    list->next = list->prev = list;
}
Referenced by _Mem_AllocPool(), LHNET_Init(), and List_Replace_Init().
List_Delete()
static void List_Delete (llist_t * node) inline static
Definition at line 274 of file com_list.h.
{
    __List_Delete_Node(node);
    node->next = node->prev = NULL;
}
Referenced by _Mem_FreeBlock(), Curl_EndDownload(), LHNET_CloseSocket(), LHNET_Read(), LHNET_Shutdown(), and World_RemoveLink().
List_Delete_Init()
static void List_Delete_Init (llist_t * node) inline static
Definition at line 283 of file com_list.h.
{
    __List_Delete_Node(node);
    node->next = node->prev = node;
}
Referenced by List_Swap().
List_Is_Empty()
static qbool List_Is_Empty (const llist_t * list) inline static
Definition at line 211 of file com_list.h.
{
    return list->next == list;
}
Referenced by _Mem_EmptyPool(), _Mem_FreePool(), Cbuf_AddText(), Cbuf_Clear(), Cbuf_Execute(), Cbuf_InsertText(), Cbuf_NodeGet(), Cmd_Defer_f(), Curl_CancelAll(), Curl_Frame(), Curl_Running(), Curl_Select(), List_Rotate_Left(), List_Splice(), List_Splice_Tail(), and Mem_PrintStats().
List_Is_First()
static qbool List_Is_First (llist_t * list, llist_t * start) inline static
Definition at line 415 of file com_list.h.
{
    return list->prev == start;
}
List_Is_Last()
static qbool List_Is_Last (llist_t * list, llist_t * start) inline static
Definition at line 420 of file com_list.h.
{
    return list->next == start;
}
List_Move()
static void List_Move (llist_t * list, llist_t * head) inline static
Definition at line 327 of file com_list.h.
{
    __List_Delete_Node(list);
    List_Add(list, head);
}
List_Move_Tail()
static void List_Move_Tail (llist_t * list, llist_t * head) inline static
Definition at line 336 of file com_list.h.
{
    __List_Delete_Node(list);
    List_Add_Tail(list, head);
}
Referenced by Cbuf_Clear(), Cbuf_Execute(), Cbuf_Execute_Deferred(), Cbuf_LinkString(), Cmd_Defer_f(), List_Rotate_Left(), and List_Rotate_To_Front().
List_Replace()
static void List_Replace (llist_t * old, llist_t * _new) inline static
Definition at line 292 of file com_list.h.
{
    _new->next = old->next;
    _new->next->prev = _new;
    _new->prev = old->prev;
    _new->prev->next = _new;
    old->next = old->prev = old;
}
Referenced by List_Replace_Init(), and List_Swap().
List_Replace_Init()
static void List_Replace_Init (llist_t * old, llist_t * _new) inline static
Definition at line 305 of file com_list.h.
{
    List_Replace(old, _new);
    List_Create(old);
}
List_Rotate_Left()
static void List_Rotate_Left (llist_t * head) inline static
Definition at line 363 of file com_list.h.
{
    llist_t *first;
    if (!List_Is_Empty(head))
    {
        first = head->next;
        List_Move_Tail(first, head);
    }
}
List_Rotate_To_Front()
static void List_Rotate_To_Front (llist_t * list, llist_t * head) inline static
Definition at line 377 of file com_list.h.
{
    List_Move_Tail(head, list);
}
List_Splice()
static void List_Splice (const llist_t * list, llist_t * head) inline static
Definition at line 400 of file com_list.h.
{
    if(!List_Is_Empty(list))
        __List_Splice(list, head, head->next);
}
Referenced by Cbuf_InsertText().
List_Splice_Tail()
static void List_Splice_Tail (const llist_t * list, llist_t * head) inline static
Definition at line 409 of file com_list.h.
{
    if (!List_Is_Empty(list))
        __List_Splice(list, head->prev, head);
}
Referenced by Cbuf_AddText().
List_Swap()
static void List_Swap (llist_t * node1, llist_t * node2) inline static
Definition at line 314 of file com_list.h.
{
    llist_t *pos = node2->prev;
    List_Delete_Init(node2);
    List_Replace(node1, node2);
    if(pos == node1)
        pos = node2;
    List_Add(node1, pos);
}