DarkPlaces: com_msg.c File Reference
com_msg.c File Reference
#include "quakedef.h"
Functions
float BuffBigFloat (const unsigned char *buffer)
Extract a big endian 32bit float from the given buffer.
int BuffBigLong (const unsigned char *buffer)
Extract a big endian 32bit int from the given buffer.
short BuffBigShort (const unsigned char *buffer)
Extract a big endian 16bit short from the given buffer.
float BuffLittleFloat (const unsigned char *buffer)
Extract a little endian 32bit float from the given buffer.
int BuffLittleLong (const unsigned char *buffer)
Extract a little endian 32bit int from the given buffer.
short BuffLittleShort (const unsigned char *buffer)
Extract a little endian 16bit short from the given buffer.
void StoreBigLong (unsigned char *buffer, unsigned int i)
Encode a big endian 32bit int to the given buffer.
void StoreBigShort (unsigned char *buffer, unsigned short i)
Encode a big endian 16bit int to the given buffer.
void StoreLittleLong (unsigned char *buffer, unsigned int i)
Encode a little endian 32bit int to the given buffer.
void StoreLittleShort (unsigned char *buffer, unsigned short i)
Encode a little endian 16bit int to the given buffer.
void MSG_WriteChar (sizebuf_t *sb, int c)
void MSG_WriteByte (sizebuf_t *sb, int c)
void MSG_WriteShort (sizebuf_t *sb, int c)
void MSG_WriteLong (sizebuf_t *sb, int c)
void MSG_WriteFloat (sizebuf_t *sb, float f)
void MSG_WriteString (sizebuf_t *sb, const char *s)
void MSG_WriteUnterminatedString (sizebuf_t *sb, const char *s)
void MSG_WriteCoord13i (sizebuf_t *sb, float f)
void MSG_WriteCoord16i (sizebuf_t *sb, float f)
void MSG_WriteCoord32f (sizebuf_t *sb, float f)
void MSG_WriteCoord (sizebuf_t *sb, float f, protocolversion_t protocol)
void MSG_WriteVector (sizebuf_t *sb, const vec3_t v, protocolversion_t protocol)
void MSG_WriteAngle8i (sizebuf_t *sb, float f)
void MSG_WriteAngle16i (sizebuf_t *sb, float f)
void MSG_WriteAngle32f (sizebuf_t *sb, float f)
void MSG_WriteAngle (sizebuf_t *sb, float f, protocolversion_t protocol)
void MSG_InitReadBuffer (sizebuf_t *buf, unsigned char *data, int size)
void MSG_BeginReading (sizebuf_t *sb)
int MSG_ReadLittleShort (sizebuf_t *sb)
int MSG_ReadBigShort (sizebuf_t *sb)
int MSG_ReadLittleLong (sizebuf_t *sb)
int MSG_ReadBigLong (sizebuf_t *sb)
float MSG_ReadLittleFloat (sizebuf_t *sb)
float MSG_ReadBigFloat (sizebuf_t *sb)
char * MSG_ReadString (sizebuf_t *sb, char *string, size_t maxstring)
size_t MSG_ReadString_len (sizebuf_t *sb, char *string, size_t maxstring)
Same as MSG_ReadString except it returns the number of bytes written to *string excluding the \0 terminator.
size_t MSG_ReadBytes (sizebuf_t *sb, size_t numbytes, unsigned char *out)
float MSG_ReadCoord13i (sizebuf_t *sb)
float MSG_ReadCoord16i (sizebuf_t *sb)
float MSG_ReadCoord32f (sizebuf_t *sb)
float MSG_ReadCoord (sizebuf_t *sb, protocolversion_t protocol)
void MSG_ReadVector (sizebuf_t *sb, vec3_t v, protocolversion_t protocol)
float MSG_ReadAngle8i (sizebuf_t *sb)
float MSG_ReadAngle16i (sizebuf_t *sb)
float MSG_ReadAngle32f (sizebuf_t *sb)
float MSG_ReadAngle (sizebuf_t *sb, protocolversion_t protocol)
Function Documentation
BuffBigFloat()
float BuffBigFloat (const unsigned char * buffer)
Extract a big endian 32bit float from the given buffer.
Definition at line 37 of file com_msg.c.
{
    union
    {
        float f;
        unsigned int i;
    }
    u;
    u.i = ((unsigned)buffer[0] << 24) | (buffer[1] << 16) | (buffer[2] << 8) | buffer[3];
    return u.f;
}
BuffBigLong()
int BuffBigLong (const unsigned char * buffer)
Extract a big endian 32bit int from the given buffer.
Definition at line 49 of file com_msg.c.
{
    return ((unsigned)buffer[0] << 24) | (buffer[1] << 16) | (buffer[2] << 8) | buffer[3];
}
Referenced by Crypto_DecryptPacket(), Crypto_EncryptPacket(), NetConn_ClientParsePacket(), NetConn_ReceivedMessage(), NetConn_ServerParsePacket(), PK3_BuildFileList(), PK3_GetEndOfCentralDir(), and PK3_GetTrueFileOffset().
BuffBigShort()
short BuffBigShort (const unsigned char * buffer)
Extract a big endian 16bit short from the given buffer.
Definition at line 54 of file com_msg.c.
{
    return (buffer[0] << 8) | buffer[1];
}
BuffLittleFloat()
float BuffLittleFloat (const unsigned char * buffer)
Extract a little endian 32bit float from the given buffer.
Definition at line 59 of file com_msg.c.
{
    union
    {
        float f;
        unsigned int i;
    }
    u;
    u.i = ((unsigned)buffer[3] << 24) | (buffer[2] << 16) | (buffer[1] << 8) | buffer[0];
    return u.f;
}
BuffLittleLong()
int BuffLittleLong (const unsigned char * buffer)
Extract a little endian 32bit int from the given buffer.
Definition at line 71 of file com_msg.c.
{
    return ((unsigned)buffer[3] << 24) | (buffer[2] << 16) | (buffer[1] << 8) | buffer[0];
}
Referenced by Crypto_ClientParsePacket(), GetLittleLong(), GetMapList(), Mod_Q1BSP_LoadFaces(), PK3_BuildFileList(), and R_LoadTextureDDSFile().
BuffLittleShort()
short BuffLittleShort (const unsigned char * buffer)
Extract a little endian 16bit short from the given buffer.
Definition at line 76 of file com_msg.c.
{
    return (buffer[1] << 8) | buffer[0];
}
Referenced by GetLittleShort(), Mod_Q1BSP_LoadFaces(), Mod_VBSP_LoadFaces(), PK3_BuildFileList(), and PK3_GetTrueFileOffset().
MSG_BeginReading()
void MSG_BeginReading (sizebuf_t * sb)
Definition at line 257 of file com_msg.c.
{
    sb->readcount = 0;
    sb->badread = false;
}
Referenced by CL_ReadDemoMessage(), MSG_InitReadBuffer(), NetConn_ClientParsePacket(), NetConn_ReceivedMessage(), NetConn_ServerParsePacket(), and W_ConvertWAD3TextureBGRA().
MSG_InitReadBuffer()
void MSG_InitReadBuffer (sizebuf_t * buf, unsigned char * data, int size)
Definition at line 249 of file com_msg.c.
{
    memset(buf, 0, sizeof(*buf));
    buf->data = data;
    buf->maxsize = buf->cursize = size;
    MSG_BeginReading(buf);
}
Referenced by Mod_Q1BSP_Load(), Mod_Q1BSP_LoadTextures(), Mod_Q2BSP_Load(), Mod_VBSP_Load(), and W_GetTextureBGRA().
MSG_ReadAngle()
float MSG_ReadAngle (sizebuf_t * sb, protocolversion_t protocol)
Definition at line 424 of file com_msg.c.
{
    if (protocol == PROTOCOL_QUAKE || protocol == PROTOCOL_QUAKEDP || protocol == PROTOCOL_NEHAHRAMOVIE || protocol == PROTOCOL_NEHAHRABJP || protocol == PROTOCOL_NEHAHRABJP2 || protocol == PROTOCOL_NEHAHRABJP3 || protocol == PROTOCOL_DARKPLACES1 || protocol == PROTOCOL_DARKPLACES2 || protocol == PROTOCOL_DARKPLACES3 || protocol == PROTOCOL_DARKPLACES4 || protocol == PROTOCOL_QUAKEWORLD)
        return MSG_ReadAngle8i (sb);
    else
        return MSG_ReadAngle16i (sb);
}
Referenced by CL_ParseBaseline(), CL_ParseServerMessage(), EntityFrameQuake_ReadEntity(), and VM_CL_ReadAngle().
MSG_ReadAngle16i()
float MSG_ReadAngle16i (sizebuf_t * sb)
Definition at line 414 of file com_msg.c.
{
    return (signed short)MSG_ReadShort (sb) * (360.0/65536.0);
}
Referenced by CL_ParseClientdata(), EntityState5_ReadUpdate(), EntityState_ReadFields(), EntityStateQW_ReadPlayerUpdate(), MSG_ReadAngle(), and SV_ReadClientMove().
MSG_ReadAngle32f()
float MSG_ReadAngle32f (sizebuf_t * sb)
Definition at line 419 of file com_msg.c.
{
    return MSG_ReadFloat (sb);
}
Referenced by SV_ReadClientMove().
MSG_ReadAngle8i()
float MSG_ReadAngle8i (sizebuf_t * sb)
Definition at line 409 of file com_msg.c.
{
    return (signed char) MSG_ReadByte (sb) * (360.0/256.0);
}
Referenced by EntityState5_ReadUpdate(), EntityState_ReadFields(), EntityStateQW_ReadEntityUpdate(), MSG_ReadAngle(), and SV_ReadClientMove().
MSG_ReadBigFloat()
float MSG_ReadBigFloat (sizebuf_t * sb)
Definition at line 324 of file com_msg.c.
{
    union
    {
        float f;
        int l;
    } dat;
    if (sb->readcount+4 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 4;
    dat.l = ((unsigned)sb->data[sb->readcount-4]<<24) | (sb->data[sb->readcount-3]<<16) | (sb->data[sb->readcount-2]<<8) | sb->data[sb->readcount-1];
    return dat.f;
}
MSG_ReadBigLong()
int MSG_ReadBigLong (sizebuf_t * sb)
Definition at line 296 of file com_msg.c.
{
    if (sb->readcount+4 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 4;
    return ((unsigned)sb->data[sb->readcount-4]<<24) + (sb->data[sb->readcount-3]<<16) + (sb->data[sb->readcount-2]<<8) + sb->data[sb->readcount-1];
}
MSG_ReadBigShort()
int MSG_ReadBigShort (sizebuf_t * sb)
Definition at line 274 of file com_msg.c.
{
    if (sb->readcount+2 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 2;
    return (short)((sb->data[sb->readcount-2]<<8) + sb->data[sb->readcount-1]);
}
MSG_ReadBytes()
size_t MSG_ReadBytes (sizebuf_t * sb, size_t numbytes, unsigned char * out)
Definition at line 364 of file com_msg.c.
{
    size_t l = 0;
    // when numbytes have been read sb->readcount won't be advanced any further
    while (l < numbytes && !sb->badread)
        out[l++] = MSG_ReadByte_opt(sb);
    return l;
}
Referenced by CL_ParseDownload(), Mod_Q1BSP_LoadEntities(), Mod_Q1BSP_LoadVisibility(), Mod_Q2BSP_LoadLighting(), Mod_Q2BSP_LoadTexinfo(), Mod_VBSP_LoadEntities(), QW_CL_ParseDownload(), VM_CL_ReadPicture(), and W_ConvertWAD3TextureBGRA().
MSG_ReadCoord()
float MSG_ReadCoord (sizebuf_t * sb, protocolversion_t protocol)
Definition at line 389 of file com_msg.c.
{
    if (protocol == PROTOCOL_QUAKE || protocol == PROTOCOL_QUAKEDP || protocol == PROTOCOL_NEHAHRAMOVIE || protocol == PROTOCOL_NEHAHRABJP || protocol == PROTOCOL_NEHAHRABJP2 || protocol == PROTOCOL_NEHAHRABJP3 || protocol == PROTOCOL_QUAKEWORLD)
        return MSG_ReadCoord13i(sb);
    else if (protocol == PROTOCOL_DARKPLACES1)
        return MSG_ReadCoord32f(sb);
    else if (protocol == PROTOCOL_DARKPLACES2 || protocol == PROTOCOL_DARKPLACES3 || protocol == PROTOCOL_DARKPLACES4)
        return MSG_ReadCoord16i(sb);
    else
        return MSG_ReadCoord32f(sb);
}
Referenced by CL_ParseBaseline(), CL_ParseServerMessage(), CL_ParseTempEntity(), EntityFrameQuake_ReadEntity(), MSG_ReadVector(), and VM_CL_ReadCoord().
MSG_ReadCoord13i()
float MSG_ReadCoord13i (sizebuf_t * sb)
Definition at line 374 of file com_msg.c.
{
    return MSG_ReadLittleShort(sb) * (1.0/8.0);
}
Referenced by EntityState5_ReadUpdate(), EntityStateQW_ReadEntityUpdate(), and MSG_ReadCoord().
MSG_ReadCoord16i()
float MSG_ReadCoord16i (sizebuf_t * sb)
Definition at line 379 of file com_msg.c.
{
    return (signed short) MSG_ReadLittleShort(sb);
}
Referenced by CL_ParseClientdata(), EntityState_ReadFields(), MSG_ReadCoord(), and SV_ReadClientMove().
MSG_ReadCoord32f()
float MSG_ReadCoord32f (sizebuf_t * sb)
Definition at line 384 of file com_msg.c.
{
    return MSG_ReadLittleFloat(sb);
}
Referenced by CL_ParseClientdata(), EntityState5_ReadUpdate(), EntityState_ReadFields(), and MSG_ReadCoord().
MSG_ReadLittleFloat()
float MSG_ReadLittleFloat (sizebuf_t * sb)
Definition at line 307 of file com_msg.c.
{
    union
    {
        float f;
        int l;
    } dat;
    if (sb->readcount+4 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 4;
    dat.l = sb->data[sb->readcount-4] | (sb->data[sb->readcount-3]<<8) | (sb->data[sb->readcount-2]<<16) | ((unsigned)sb->data[sb->readcount-1]<<24);
    return dat.f;
}
Referenced by Mod_BSP_LoadSubmodels(), Mod_Q1BSP_LoadLeafs(), Mod_Q1BSP_LoadNodes(), Mod_Q1BSP_LoadPlanes(), Mod_Q1BSP_LoadTexinfo(), Mod_Q1BSP_LoadVertexes(), Mod_Q2BSP_LoadTexinfo(), Mod_VBSP_LoadPlanes(), Mod_VBSP_LoadTexinfo(), Mod_VBSP_LoadVertexes(), and MSG_ReadCoord32f().
MSG_ReadLittleLong()
int MSG_ReadLittleLong (sizebuf_t * sb)
Definition at line 285 of file com_msg.c.
{
    if (sb->readcount+4 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 4;
    return sb->data[sb->readcount-4] | (sb->data[sb->readcount-3]<<8) | (sb->data[sb->readcount-2]<<16) | ((unsigned)sb->data[sb->readcount-1]<<24);
}
Referenced by Mod_BSP_LoadSubmodels(), Mod_Q1BSP_Load(), Mod_Q1BSP_LoadClipnodes(), Mod_Q1BSP_LoadEdges(), Mod_Q1BSP_LoadFaces(), Mod_Q1BSP_LoadLeaffaces(), Mod_Q1BSP_LoadLeafs(), Mod_Q1BSP_LoadNodes(), Mod_Q1BSP_LoadPlanes(), Mod_Q1BSP_LoadSurfedges(), Mod_Q1BSP_LoadTexinfo(), Mod_Q1BSP_LoadTextures(), Mod_Q2BSP_Load(), Mod_Q2BSP_LoadBrushes(), Mod_Q2BSP_LoadLeafs(), Mod_Q2BSP_LoadNodes(), Mod_Q2BSP_LoadTexinfo(), Mod_Q2BSP_LoadVisibility(), Mod_VBSP_Load(), Mod_VBSP_LoadFaces(), Mod_VBSP_LoadPlanes(), Mod_VBSP_LoadSurfedges(), Mod_VBSP_LoadTexinfo(), and W_ConvertWAD3TextureBGRA().
MSG_ReadLittleShort()
int MSG_ReadLittleShort (sizebuf_t * sb)
Definition at line 263 of file com_msg.c.
{
    if (sb->readcount+2 > sb->cursize)
    {
        sb->badread = true;
        return -1;
    }
    sb->readcount += 2;
    return (short)(sb->data[sb->readcount-2] | (sb->data[sb->readcount-1]<<8));
}
Referenced by Mod_Q1BSP_LoadClipnodes(), Mod_Q1BSP_LoadEdges(), Mod_Q1BSP_LoadFaces(), Mod_Q1BSP_LoadLeaffaces(), Mod_Q1BSP_LoadLeafs(), Mod_Q1BSP_LoadNodes(), Mod_Q2BSP_LoadBrushSides(), Mod_Q2BSP_LoadLeafBrushes(), Mod_Q2BSP_LoadLeafs(), Mod_Q2BSP_LoadNodes(), Mod_VBSP_LoadEdges(), Mod_VBSP_LoadFaces(), MSG_ReadCoord13i(), and MSG_ReadCoord16i().
MSG_ReadString()
char * MSG_ReadString (sizebuf_t * sb, char * string, size_t maxstring)
Definition at line 341 of file com_msg.c.
{
    size_t l = 0;
    // read string into sbfer, but only store as many characters as will fit
    // if dest buffer is full sb->readcount will still be advanced to end of message string
    while ((string[l] = MSG_ReadByte_opt(sb)) != '\0')
        if (l < maxstring)
            ++l;
    return string;
}
Referenced by CL_ParseServerInfo(), CL_ParseServerMessage(), CL_ParseTempEntity(), NetConn_ClientParsePacket(), NetConn_ServerParsePacket(), QW_CL_ParseModelList(), QW_CL_ParseSoundList(), QW_CL_ServerInfo(), QW_CL_SetInfo(), QW_CL_UpdateUserInfo(), SHOWLMP_decodehide(), SHOWLMP_decodeshow(), and SV_ReadClientMessage().
MSG_ReadString_len()
size_t MSG_ReadString_len (sizebuf_t * sb, char * string, size_t maxstring)
Same as MSG_ReadString except it returns the number of bytes written to *string excluding the \0 terminator.
Definition at line 352 of file com_msg.c.
{
    size_t l = 0;
    // read string into sbfer, but only store as many characters as will fit
    // if dest buffer is full sb->readcount will still be advanced to end of message string
    while ((string[l] = MSG_ReadByte_opt(sb)) != '\0')
        if (l < maxstring)
            ++l;
    return l;
}
Referenced by CL_ParseServerMessage(), SV_ReadClientMessage(), VM_CL_ReadPicture(), and VM_CL_ReadString().
MSG_ReadVector()
void MSG_ReadVector (sizebuf_t * sb, vec3_t v, protocolversion_t protocol)
Definition at line 401 of file com_msg.c.
{
    v[0] = MSG_ReadCoord(sb, protocol);
    v[1] = MSG_ReadCoord(sb, protocol);
    v[2] = MSG_ReadCoord(sb, protocol);
}
Referenced by CL_ParseBeam(), CL_ParseEffect(), CL_ParseEffect2(), CL_ParseParticleEffect(), CL_ParsePointParticles(), CL_ParsePointParticles1(), CL_ParseServerMessage(), CL_ParseStartSoundPacket(), CL_ParseStaticSound(), CL_ParseTempEntity(), CL_ParseTrailParticles(), EntityStateQW_ReadPlayerUpdate(), and V_ParseDamage().
MSG_WriteAngle()
void MSG_WriteAngle (sizebuf_t * sb, float f, protocolversion_t protocol)
Definition at line 237 of file com_msg.c.
{
    if (protocol == PROTOCOL_QUAKE || protocol == PROTOCOL_QUAKEDP || protocol == PROTOCOL_NEHAHRAMOVIE || protocol == PROTOCOL_NEHAHRABJP || protocol == PROTOCOL_NEHAHRABJP2 || protocol == PROTOCOL_NEHAHRABJP3 || protocol == PROTOCOL_DARKPLACES1 || protocol == PROTOCOL_DARKPLACES2 || protocol == PROTOCOL_DARKPLACES3 || protocol == PROTOCOL_DARKPLACES4 || protocol == PROTOCOL_QUAKEWORLD)
        MSG_WriteAngle8i (sb, f);
    else
        MSG_WriteAngle16i (sb, f);
}
Referenced by EntityFrameQuake_WriteFrame(), SV_CreateBaseline(), SV_Spawn_f(), SV_WriteClientdataToMessage(), VM_M_WriteAngle(), VM_SV_makestatic(), and VM_SV_WriteAngle().
MSG_WriteAngle16i()
void MSG_WriteAngle16i (sizebuf_t * sb, float f)
Definition at line 227 of file com_msg.c.
{
    MSG_WriteShort (sb, (int)Q_rint(f*(65536.0/360.0)) & 65535);
}
Referenced by CL_SendMove(), EntityState5_WriteUpdate(), EntityState_WriteFields(), MSG_WriteAngle(), QW_MSG_WriteDeltaUsercmd(), and SV_WriteClientdataToMessage().
MSG_WriteAngle32f()
void MSG_WriteAngle32f (sizebuf_t * sb, float f)
Definition at line 232 of file com_msg.c.
{
    MSG_WriteFloat (sb, f);
}
Referenced by CL_SendMove().
MSG_WriteAngle8i()
void MSG_WriteAngle8i (sizebuf_t * sb, float f)
Definition at line 222 of file com_msg.c.
{
    MSG_WriteByte (sb, (int)Q_rint(f*(256.0/360.0)) & 255);
}
Referenced by CL_SendMove(), EntityState5_WriteUpdate(), EntityState_WriteFields(), and MSG_WriteAngle().
MSG_WriteByte()
void MSG_WriteByte (sizebuf_t * sb, int c)
Definition at line 130 of file com_msg.c.
{
    unsigned char    *buf;
    buf = SZ_GetSpace (sb, 1);
    buf[0] = c;
}
Referenced by CL_DisconnectEx(), CL_ForwardToServer(), CL_ParseServerInfo(), CL_PQRcon_f(), CL_SendMove(), CL_SendPlayerInfo(), CL_SetInfo(), CL_SignonReply(), CL_Stop_f(), Cvar_SetQuick_Internal(), EntityFrame4_WriteFrame(), EntityFrame5_WriteFrame(), EntityFrame_WriteFrame(), EntityFrameCSQC_WriteFrame(), EntityFrameQuake_WriteFrame(), EntityState5_WriteUpdate(), EntityState_WriteExtendBits(), EntityState_WriteFields(), MakeDownloadPacket(), MSG_WriteAngle8i(), NetConn_ClientFrame(), NetConn_ServerParsePacket(), Protocol_WriteStatsReliable(), QW_CL_CheckOrDownloadFile(), QW_CL_NextUpload_f(), QW_CL_ParseDownload(), QW_CL_ParseModelList(), QW_CL_ParseSoundList(), QW_CL_RequestNextDownload(), QW_MSG_WriteDeltaUsercmd(), Sbar_DeathmatchOverlay(), SV_BroadcastPrint(), SV_ClientCommands(), SV_ClientPrint(), SV_Color_f(), SV_CreateBaseline(), SV_DropClient(), SV_ModelIndex(), SV_Name(), SV_Pause_f(), SV_Pings_f(), SV_PreSpawn_f(), SV_SendClientDatagram(), SV_SendServerinfo(), SV_SoundIndex(), SV_Spawn_f(), SV_SpawnServer(), SV_StartEffect(), SV_StartParticle(), SV_StartPointSound(), SV_StartSound(), SV_StopDemoRecording(), SV_UpdateToReliableMessages(), SV_WriteClientdataToMessage(), SV_WriteNetnameIntoDemo(), VM_M_WriteByte(), VM_SV_ambientsound(), VM_SV_makestatic(), VM_SV_pointparticles(), VM_SV_setcolor(), VM_SV_setpause(), VM_SV_te_beam(), VM_SV_te_blood(), VM_SV_te_bloodshower(), VM_SV_te_customflash(), VM_SV_te_explosion(), VM_SV_te_explosion2(), VM_SV_te_explosionquad(), VM_SV_te_explosionrgb(), VM_SV_te_flamejet(), VM_SV_te_gunshot(), VM_SV_te_gunshotquad(), VM_SV_te_knightspike(), VM_SV_te_lavasplash(), VM_SV_te_lightning1(), VM_SV_te_lightning2(), VM_SV_te_lightning3(), VM_SV_te_particlecube(), VM_SV_te_particlerain(), VM_SV_te_particlesnow(), VM_SV_te_plasmaburn(), VM_SV_te_smallflash(), VM_SV_te_spark(), VM_SV_te_spike(), VM_SV_te_spikequad(), VM_SV_te_superspike(), VM_SV_te_superspikequad(), VM_SV_te_tarexplosion(), VM_SV_te_teleport(), VM_SV_te_wizspike(), VM_SV_trailparticles(), and VM_SV_WriteByte().
MSG_WriteChar()
void MSG_WriteChar (sizebuf_t * sb, int c)
Definition at line 122 of file com_msg.c.
{
    unsigned char    *buf;
    buf = SZ_GetSpace (sb, 1);
    buf[0] = c;
}
Referenced by CL_KeepaliveMessage(), CL_Reconnect_f(), MSG_WriteString(), NetConn_ConnectionEstablished(), SV_SendClientDatagram(), SV_StartParticle(), SV_StartSound(), SV_WriteClientdataToMessage(), VM_M_WriteChar(), VM_sprint(), VM_SV_centerprint(), VM_SV_lightstyle(), VM_SV_sprint(), VM_SV_te_blood(), VM_SV_te_spark(), and VM_SV_WriteChar().
MSG_WriteCoord()
void MSG_WriteCoord (sizebuf_t * sb, float f, protocolversion_t protocol)
Definition at line 202 of file com_msg.c.
{
    if (protocol == PROTOCOL_QUAKE || protocol == PROTOCOL_QUAKEDP || protocol == PROTOCOL_NEHAHRAMOVIE || protocol == PROTOCOL_NEHAHRABJP || protocol == PROTOCOL_NEHAHRABJP2 || protocol == PROTOCOL_NEHAHRABJP3 || protocol == PROTOCOL_QUAKEWORLD)
        MSG_WriteCoord13i (sb, f);
    else if (protocol == PROTOCOL_DARKPLACES1)
        MSG_WriteCoord32f (sb, f);
    else if (protocol == PROTOCOL_DARKPLACES2 || protocol == PROTOCOL_DARKPLACES3 || protocol == PROTOCOL_DARKPLACES4)
        MSG_WriteCoord16i (sb, f);
    else
        MSG_WriteCoord32f (sb, f);
}
Referenced by EntityFrameQuake_WriteFrame(), MSG_WriteVector(), SV_CreateBaseline(), SV_StartEffect(), SV_StartParticle(), SV_StartPointSound(), SV_StartSound(), SV_WriteClientdataToMessage(), VM_M_WriteCoord(), VM_SV_makestatic(), VM_SV_te_beam(), VM_SV_te_blood(), VM_SV_te_bloodshower(), VM_SV_te_customflash(), VM_SV_te_explosion(), VM_SV_te_explosion2(), VM_SV_te_explosionquad(), VM_SV_te_explosionrgb(), VM_SV_te_flamejet(), VM_SV_te_gunshot(), VM_SV_te_gunshotquad(), VM_SV_te_knightspike(), VM_SV_te_lavasplash(), VM_SV_te_lightning1(), VM_SV_te_lightning2(), VM_SV_te_lightning3(), VM_SV_te_particlecube(), VM_SV_te_particlerain(), VM_SV_te_particlesnow(), VM_SV_te_plasmaburn(), VM_SV_te_smallflash(), VM_SV_te_spark(), VM_SV_te_spike(), VM_SV_te_spikequad(), VM_SV_te_superspike(), VM_SV_te_superspikequad(), VM_SV_te_tarexplosion(), VM_SV_te_teleport(), VM_SV_te_wizspike(), and VM_SV_WriteCoord().
MSG_WriteCoord13i()
void MSG_WriteCoord13i (sizebuf_t * sb, float f)
Definition at line 187 of file com_msg.c.
{
    MSG_WriteShort (sb, Q_rint(f*8));
}
Referenced by EntityState5_WriteUpdate(), and MSG_WriteCoord().
MSG_WriteCoord16i()
void MSG_WriteCoord16i (sizebuf_t * sb, float f)
Definition at line 192 of file com_msg.c.
{
    MSG_WriteShort (sb, Q_rint(f));
}
Referenced by CL_SendMove(), EntityState_WriteFields(), MSG_WriteCoord(), and SV_WriteClientdataToMessage().
MSG_WriteCoord32f()
void MSG_WriteCoord32f (sizebuf_t * sb, float f)
Definition at line 197 of file com_msg.c.
{
    MSG_WriteFloat (sb, f);
}
Referenced by EntityState5_WriteUpdate(), EntityState_WriteFields(), MSG_WriteCoord(), and SV_WriteClientdataToMessage().
MSG_WriteFloat()
void MSG_WriteFloat (sizebuf_t * sb, float f)
Definition at line 158 of file com_msg.c.
{
    union
    {
        float   f;
        int     l;
    } dat;
    dat.f = f;
    dat.l = LittleLong (dat.l);
    SZ_Write (sb, (unsigned char *)&dat.l, 4);
}
Referenced by CL_SendMove(), EntityFrame_WriteFrame(), EntityFrameQuake_WriteFrame(), MSG_WriteAngle32f(), MSG_WriteCoord32f(), SV_SendClientDatagram(), and SV_Spawn_f().
MSG_WriteLong()
void MSG_WriteLong (sizebuf_t * sb, int c)
Definition at line 147 of file com_msg.c.
{
    unsigned char    *buf;
    buf = SZ_GetSpace (sb, 4);
    buf[0] = c&0xff;
    buf[1] = (c>>8)&0xff;
    buf[2] = (c>>16)&0xff;
    buf[3] = c>>24;
}
Referenced by CL_PQRcon_f(), CL_SendMove(), EntityFrame4_WriteFrame(), EntityFrame5_WriteFrame(), EntityFrame_WriteFrame(), EntityState5_WriteUpdate(), MakeDownloadPacket(), NetConn_ClientFrame(), NetConn_ServerParsePacket(), Protocol_WriteStatsReliable(), SCR_CaptureVideo_RIFF_IndexEntry(), SCR_CaptureVideo_RIFF_Write32(), SV_SendClientDatagram(), SV_SendServerinfo(), SV_Spawn_f(), SV_WriteClientdataToMessage(), VM_M_WriteLong(), and VM_SV_WriteLong().
MSG_WriteShort()
void MSG_WriteShort (sizebuf_t * sb, int c)
Definition at line 138 of file com_msg.c.
{
    unsigned char    *buf;
    buf = SZ_GetSpace (sb, 2);
    buf[0] = c&0xff;
    buf[1] = c>>8;
}
Referenced by CL_SendMove(), EntityFrame4_WriteFrame(), EntityFrame5_WriteFrame(), EntityFrame_WriteFrame(), EntityFrameCSQC_WriteFrame(), EntityFrameQuake_WriteFrame(), EntityState5_WriteUpdate(), EntityState_WriteFields(), EntityState_WriteUpdate(), MakeDownloadPacket(), MSG_WriteAngle16i(), MSG_WriteCoord13i(), MSG_WriteCoord16i(), QW_CL_NextUpload_f(), QW_MSG_WriteDeltaUsercmd(), SCR_CaptureVideo_RIFF_Write16(), SV_CreateBaseline(), SV_DropClient(), SV_ModelIndex(), SV_Pings_f(), SV_SendClientDatagram(), SV_SendServerinfo(), SV_SoundIndex(), SV_Spawn_f(), SV_StartEffect(), SV_StartPointSound(), SV_StartSound(), SV_UpdateToReliableMessages(), SV_WriteClientdataToMessage(), VM_M_WriteEntity(), VM_M_WriteShort(), VM_SV_ambientsound(), VM_SV_makestatic(), VM_SV_pointparticles(), VM_SV_te_beam(), VM_SV_te_bloodshower(), VM_SV_te_lightning1(), VM_SV_te_lightning2(), VM_SV_te_lightning3(), VM_SV_te_particlecube(), VM_SV_te_particlerain(), VM_SV_te_particlesnow(), VM_SV_trailparticles(), VM_SV_WriteEntity(), VM_SV_WritePicture(), and VM_SV_WriteShort().
MSG_WriteString()
void MSG_WriteString (sizebuf_t * sb, const char * s)
Definition at line 173 of file com_msg.c.
{
    if (!s || !*s)
        MSG_WriteChar (sb, 0);
    else
        SZ_Write (sb, (unsigned char *)s, (int)strlen(s)+1);
}
Referenced by CL_DisconnectEx(), CL_ParseServerInfo(), CL_PQRcon_f(), CL_Reconnect_f(), CL_SendPlayerInfo(), CL_SetInfo(), CL_SignonReply(), Cvar_SetQuick_Internal(), MakeDownloadPacket(), NetConn_ClientFrame(), NetConn_ServerParsePacket(), QW_CL_CheckOrDownloadFile(), QW_CL_ParseDownload(), QW_CL_ParseModelList(), QW_CL_ParseSoundList(), QW_CL_RequestNextDownload(), Sbar_DeathmatchOverlay(), SCR_CaptureVideo_RIFF_WriteTerminatedString(), SV_BroadcastPrint(), SV_ClientCommands(), SV_ClientPrint(), SV_DropClient(), SV_ModelIndex(), SV_Name(), SV_Pings_f(), SV_SendServerinfo(), SV_SoundIndex(), SV_Spawn_f(), SV_SpawnServer(), SV_WriteNetnameIntoDemo(), VM_M_WriteString(), VM_sprint(), VM_SV_centerprint(), VM_SV_lightstyle(), VM_SV_sprint(), VM_SV_WritePicture(), and VM_SV_WriteString().
MSG_WriteUnterminatedString()
void MSG_WriteUnterminatedString (sizebuf_t * sb, const char * s)
Definition at line 181 of file com_msg.c.
{
    if (s && *s)
        SZ_Write (sb, (unsigned char *)s, (int)strlen(s));
}
Referenced by NetConn_ServerParsePacket(), SCR_CaptureVideo_RIFF_IndexEntry(), SCR_CaptureVideo_RIFF_WriteFourCC(), SV_Pings_f(), SV_WriteNetnameIntoDemo(), and VM_SV_WriteUnterminatedString().
MSG_WriteVector()
void MSG_WriteVector (sizebuf_t * sb, const vec3_t v, protocolversion_t protocol)
Definition at line 214 of file com_msg.c.
{
    MSG_WriteCoord (sb, v[0], protocol);
    MSG_WriteCoord (sb, v[1], protocol);
    MSG_WriteCoord (sb, v[2], protocol);
}
Referenced by VM_SV_ambientsound(), VM_SV_pointparticles(), and VM_SV_trailparticles().
StoreBigLong()
void StoreBigLong (unsigned char * buffer, unsigned int i)
Encode a big endian 32bit int to the given buffer.
Definition at line 81 of file com_msg.c.
{
    buffer[0] = (i >> 24) & 0xFF;
    buffer[1] = (i >> 16) & 0xFF;
    buffer[2] = (i >>  8) & 0xFF;
    buffer[3] = i         & 0xFF;
}
Referenced by CL_PQRcon_f(), Con_Rcon_Redirect_Flush(), NetConn_ClientFrame(), NetConn_ReceivedMessage(), NetConn_SendUnreliableMessage(), and NetConn_ServerParsePacket().
StoreBigShort()
void StoreBigShort (unsigned char * buffer, unsigned short i)
Encode a big endian 16bit int to the given buffer.
Definition at line 89 of file com_msg.c.
{
    buffer[0] = (i >>  8) & 0xFF;
    buffer[1] = i         & 0xFF;
}
StoreLittleLong()
void StoreLittleLong (unsigned char * buffer, unsigned int i)
Encode a little endian 32bit int to the given buffer.
Definition at line 95 of file com_msg.c.
{
    buffer[0] = i         & 0xFF;
    buffer[1] = (i >>  8) & 0xFF;
    buffer[2] = (i >> 16) & 0xFF;
    buffer[3] = (i >> 24) & 0xFF;
}
Referenced by NetConn_SendUnreliableMessage(), and R_SaveTextureDDSFile().
StoreLittleShort()
void StoreLittleShort (unsigned char * buffer, unsigned short i)
Encode a little endian 16bit int to the given buffer.
Definition at line 103 of file com_msg.c.
{
    buffer[0] = i         & 0xFF;
    buffer[1] = (i >>  8) & 0xFF;
}