DarkPlaces: com_ents4.c File Reference
com_ents4.c File Reference
#include "quakedef.h"
#include "protocol.h"
Functions
entityframe4_database_t * EntityFrame4_AllocDatabase (mempool_t *pool)
void EntityFrame4_FreeDatabase (entityframe4_database_t *d)
void EntityFrame4_ResetDatabase (entityframe4_database_t *d)
entity_state_t * EntityFrame4_GetReferenceEntity (entityframe4_database_t *d, int number)
void EntityFrame4_AddCommitEntity (entityframe4_database_t *d, const entity_state_t *s)
int EntityFrame4_AckFrame (entityframe4_database_t *d, int framenum, int servermode)
Function Documentation
EntityFrame4_AckFrame()
int EntityFrame4_AckFrame (entityframe4_database_t * d, int framenum, int servermode)
Definition at line 74 of file com_ents4.c.
{
    int i, j, found;
    entity_database4_commit_t *commit;
    if (framenum == -1)
    {
        // reset reference, but leave commits alone
        d->referenceframenum = -1;
        for (i = 0;i < d->maxreferenceentities;i++)
            d->referenceentity[i] = defaultstate;
        // if this is the server, remove commits
        for (i = 0, commit = d->commit;i < MAX_ENTITY_HISTORY;i++, commit++)
            commit->numentities = 0;
        found = true;
    }
    else if (d->referenceframenum == framenum)
        found = true;
    else
    {
        found = false;
        for (i = 0, commit = d->commit;i < MAX_ENTITY_HISTORY;i++, commit++)
        {
            if (commit->numentities && commit->framenum <= framenum)
            {
                if (commit->framenum == framenum)
                {
                    found = true;
                    d->referenceframenum = framenum;
                    if (developer_networkentities.integer >= 3)
                    {
                        for (j = 0;j < commit->numentities;j++)
{
                            entity_state_t *s = EntityFrame4_GetReferenceEntity(d, commit->entity[j].number);
                            if (commit->entity[j].active != s->active)
{
                                if (commit->entity[j].active == ACTIVE_NETWORK)
                                    Con_Printf("commit entity %i has become active (modelindex %i)\n", commit->entity[j].number, commit->entity[j].modelindex);
                                else
                                    Con_Printf("commit entity %i has become inactive (modelindex %i)\n", commit->entity[j].number, commit->entity[j].modelindex);
                            }
                            *s = commit->entity[j];
                        }
                    }
                    else
                        for (j = 0;j < commit->numentities;j++)
                            *EntityFrame4_GetReferenceEntity(d, commit->entity[j].number) = commit->entity[j];
                }
                commit->numentities = 0;
            }
        }
    }
    if (developer_networkentities.integer >= 1)
    {
        Con_Printf("ack ref:%i database updated to: ref:%i commits:", framenum, d->referenceframenum);
        for (i = 0;i < MAX_ENTITY_HISTORY;i++)
            if (d->commit[i].numentities)
                Con_Printf(" %i", d->commit[i].framenum);
        Con_Print("\n");
    }
    return found;
}
Referenced by EntityFrame4_CL_ReadFrame(), and SV_FrameAck().
EntityFrame4_AddCommitEntity()
void EntityFrame4_AddCommitEntity (entityframe4_database_t * d, const entity_state_t * s)
Definition at line 57 of file com_ents4.c.
{
    // resize commit's entity list if full
    if (d->currentcommit->maxentities <= d->currentcommit->numentities)
    {
        entity_state_t *oldentity = d->currentcommit->entity;
        d->currentcommit->maxentities += 8;
        d->currentcommit->entity = (entity_state_t *)Mem_Alloc(d->mempool, d->currentcommit->maxentities * sizeof(*d->currentcommit->entity));
        if (oldentity)
        {
            memcpy(d->currentcommit->entity, oldentity, d->currentcommit->numentities * sizeof(*d->currentcommit->entity));
            Mem_Free(oldentity);
        }
    }
    d->currentcommit->entity[d->currentcommit->numentities++] = *s;
}
Referenced by EntityFrame4_CL_ReadFrame(), and EntityFrame4_WriteFrame().
EntityFrame4_AllocDatabase()
entityframe4_database_t * EntityFrame4_AllocDatabase (mempool_t * pool)
Definition at line 4 of file com_ents4.c.
{
    entityframe4_database_t *d;
    d = (entityframe4_database_t *)Mem_Alloc(pool, sizeof(*d));
    d->mempool = pool;
    EntityFrame4_ResetDatabase(d);
    return d;
}
Referenced by EntityFrame4_CL_ReadFrame(), and SV_SendServerinfo().
EntityFrame4_FreeDatabase()
void EntityFrame4_FreeDatabase (entityframe4_database_t * d)
Definition at line 13 of file com_ents4.c.
{
    int i;
    for (i = 0;i < MAX_ENTITY_HISTORY;i++)
        if (d->commit[i].entity)
            Mem_Free(d->commit[i].entity);
    if (d->referenceentity)
        Mem_Free(d->referenceentity);
    Mem_Free(d);
}
Referenced by SV_DropClient(), and SV_SendServerinfo().
EntityFrame4_GetReferenceEntity()
entity_state_t * EntityFrame4_GetReferenceEntity (entityframe4_database_t * d, int number)
Definition at line 34 of file com_ents4.c.
{
    if (d->maxreferenceentities <= number)
    {
        int oldmax = d->maxreferenceentities;
        entity_state_t *oldentity = d->referenceentity;
        d->maxreferenceentities = (number + 15) & ~7;
        d->referenceentity = (entity_state_t *)Mem_Alloc(d->mempool, d->maxreferenceentities * sizeof(*d->referenceentity));
        if (oldentity)
        {
            memcpy(d->referenceentity, oldentity, oldmax * sizeof(*d->referenceentity));
            Mem_Free(oldentity);
        }
        // clear the newly created entities
        for (;oldmax < d->maxreferenceentities;oldmax++)
        {
            d->referenceentity[oldmax] = defaultstate;
            d->referenceentity[oldmax].number = oldmax;
        }
    }
    return d->referenceentity + number;
}
Referenced by EntityFrame4_AckFrame(), EntityFrame4_CL_ReadFrame(), and EntityFrame4_WriteFrame().
EntityFrame4_ResetDatabase()
void EntityFrame4_ResetDatabase (entityframe4_database_t * d)
Definition at line 24 of file com_ents4.c.
{
    int i;
    d->referenceframenum = -1;
    for (i = 0;i < MAX_ENTITY_HISTORY;i++)
        d->commit[i].numentities = 0;
    for (i = 0;i < d->maxreferenceentities;i++)
        d->referenceentity[i] = defaultstate;
}
Referenced by EntityFrame4_AllocDatabase(), and EntityFrame4_CL_ReadFrame().