DarkPlaces: com_ents.c File Reference
com_ents.c File Reference
#include "quakedef.h"
#include "protocol.h"
Functions
entityframe_database_t * EntityFrame_AllocDatabase (mempool_t *mempool)
void EntityFrame_FreeDatabase (entityframe_database_t *d)
void EntityFrame_ClearDatabase (entityframe_database_t *d)
void EntityFrame_Clear (entity_frame_t *f, vec3_t eye, int framenum)
void EntityFrame_AckFrame (entityframe_database_t *d, int frame)
void EntityFrame_FetchFrame (entityframe_database_t *d, int framenum, entity_frame_t *f)
Function Documentation
EntityFrame_AckFrame()
void EntityFrame_AckFrame (entityframe_database_t * d, int frame)
Definition at line 35 of file com_ents.c.
{
    int i;
    d->ackframenum = frame;
    for (i = 0;i < d->numframes && d->frames[i].framenum < frame;i++);
    // ignore outdated frame acks (out of order packets)
    if (i == 0)
        return;
    d->numframes -= i;
    // if some queue is left, slide it down to beginning of array
    if (d->numframes)
        memmove(&d->frames[0], &d->frames[i], sizeof(d->frames[0]) * d->numframes);
}
Referenced by EntityFrame_CL_ReadFrame(), and SV_FrameAck().
EntityFrame_AllocDatabase()
entityframe_database_t * EntityFrame_AllocDatabase (mempool_t * mempool)
Definition at line 5 of file com_ents.c.
{
    return (entityframe_database_t *)Mem_Alloc(mempool, sizeof(entityframe_database_t));
}
Referenced by EntityFrame_CL_ReadFrame(), and SV_SendServerinfo().
EntityFrame_Clear()
void EntityFrame_Clear (entity_frame_t * f, vec3_t eye, int framenum)
Definition at line 23 of file com_ents.c.
{
    f->time = 0;
    f->framenum = framenum;
    f->numentities = 0;
    if (eye == NULL)
        VectorClear(f->eye);
    else
        VectorCopy(eye, f->eye);
}
Referenced by EntityFrame_CL_ReadFrame(), and EntityFrame_FetchFrame().
EntityFrame_ClearDatabase()
void EntityFrame_ClearDatabase (entityframe_database_t * d)
Definition at line 17 of file com_ents.c.
{
    memset(d, 0, sizeof(*d));
}
Referenced by EntityFrame_AddFrame_Client(), and EntityFrame_AddFrame_Server().
EntityFrame_FetchFrame()
void EntityFrame_FetchFrame (entityframe_database_t * d, int framenum, entity_frame_t * f)
Definition at line 50 of file com_ents.c.
{
    int i, n;
    EntityFrame_Clear(f, NULL, -1);
    for (i = 0;i < d->numframes && d->frames[i].framenum < framenum;i++);
    if (i < d->numframes && framenum == d->frames[i].framenum)
    {
        f->framenum = framenum;
        f->numentities = d->frames[i].endentity - d->frames[i].firstentity;
        n = MAX_ENTITY_DATABASE - (d->frames[i].firstentity % MAX_ENTITY_DATABASE);
        if (n > f->numentities)
            n = f->numentities;
        memcpy(f->entitydata, d->entitydata + d->frames[i].firstentity % MAX_ENTITY_DATABASE, sizeof(*f->entitydata) * n);
        if (f->numentities > n)
            memcpy(f->entitydata + n, d->entitydata, sizeof(*f->entitydata) * (f->numentities - n));
        VectorCopy(d->eye, f->eye);
    }
}
Referenced by EntityFrame_CL_ReadFrame(), and EntityFrame_WriteFrame().
EntityFrame_FreeDatabase()
void EntityFrame_FreeDatabase (entityframe_database_t * d)
Definition at line 11 of file com_ents.c.
{
    Mem_Free(d);
}
Referenced by SV_DropClient(), and SV_SendServerinfo().