DarkPlaces: crypto.h File Reference
crypto.h File Reference
#include <stddef.h>
#include "qtypes.h"
Data Structures
struct crypto_t
Macros
#define ENCRYPTION_REQUIRED (crypto_aeslevel.integer >= 3)
#define CRYPTO_HEADERSIZE 31
#define FP64_SIZE 44
#define DHKEY_SIZE 16
#define CRYPTO_NOMATCH 0
#define CRYPTO_MATCH 1
#define CRYPTO_DISCARD 2
#define CRYPTO_REPLACE 3
Functions
void Crypto_Init (void)
void Crypto_Init_Commands (void)
void Crypto_LoadKeys (void)
void Crypto_Shutdown (void)
qbool Crypto_Available (void)
void sha256 (unsigned char *out, const unsigned char *in, int n)
const void * Crypto_EncryptPacket (crypto_t *crypto, const void *data_src, size_t len_src, void *data_dst, size_t *len_dst, size_t len)
const void * Crypto_DecryptPacket (crypto_t *crypto, const void *data_src, size_t len_src, void *data_dst, size_t *len_dst, size_t len)
int Crypto_ClientParsePacket (const char *data_in, size_t len_in, char *data_out, size_t *len_out, lhnetaddress_t *peeraddress, const char *peeraddressstring)
int Crypto_ServerParsePacket (const char *data_in, size_t len_in, char *data_out, size_t *len_out, lhnetaddress_t *peeraddress)
qbool Crypto_ServerAppendToChallenge (const char *data_in, size_t len_in, char *data_out, size_t *len_out, size_t maxlen)
crypto_t * Crypto_ServerGetInstance (struct lhnetaddress_s *peeraddress)
qbool Crypto_FinishInstance (crypto_t *out, crypto_t *in)
const char * Crypto_GetInfoResponseDataString (void)
qbool Crypto_RetrieveHostKey (struct lhnetaddress_s *peeraddress, int *keyid, char *keyfp, size_t keyfplen, char *idfp, size_t idfplen, int *aeslevel, qbool *issigned)
int Crypto_RetrieveLocalKey (int keyid, char *keyfp, size_t keyfplen, char *idfp, size_t idfplen, qbool *issigned)
size_t Crypto_SignData (const void *data, size_t datasize, int keyid, void *signed_data, size_t signed_size)
size_t Crypto_SignDataDetached (const void *data, size_t datasize, int keyid, void *signed_data, size_t signed_size)
Variables
struct cvar_s crypto_developer
struct cvar_s crypto_aeslevel
int crypto_keyfp_recommended_length
Macro Definition Documentation
CRYPTO_DISCARD
#define CRYPTO_DISCARD 2
Definition at line 66 of file crypto.h.
CRYPTO_HEADERSIZE
#define CRYPTO_HEADERSIZE 31
Definition at line 34 of file crypto.h.
CRYPTO_MATCH
#define CRYPTO_MATCH 1
Definition at line 65 of file crypto.h.
CRYPTO_NOMATCH
#define CRYPTO_NOMATCH 0
Definition at line 64 of file crypto.h.
CRYPTO_REPLACE
#define CRYPTO_REPLACE 3
Definition at line 67 of file crypto.h.
DHKEY_SIZE
#define DHKEY_SIZE 16
Definition at line 39 of file crypto.h.
ENCRYPTION_REQUIRED
#define ENCRYPTION_REQUIRED (crypto_aeslevel.integer >= 3)
Definition at line 30 of file crypto.h.
FP64_SIZE
#define FP64_SIZE 44
Definition at line 38 of file crypto.h.
Function Documentation
Crypto_Available()
qbool Crypto_Available (void)
Definition at line 1097 of file crypto.c.
{
    if(!d0_blind_id_dll)
        return false;
    return true;
}
Referenced by checkextension(), and VM_digest_hex().
Crypto_ClientParsePacket()
int Crypto_ClientParsePacket (const char * data_in, size_t len_in, char * data_out, size_t * len_out, lhnetaddress_t * peeraddress, const char * peeraddressstring)
Definition at line 2107 of file crypto.c.
{
    crypto_t *crypto = &cls.crypto;
    const char *string = data_in;
    D0_BOOL aes;
    char *data_out_p = data_out;
    D0_BOOL status;
    char infostringvalue[MAX_INPUTLINE];
    char vabuf[1024];
    if(!d0_blind_id_dll)
        return CRYPTO_NOMATCH; // no support
    // if "challenge": verify challenge, and discard message, send next crypto protocol message instead
    // otherwise, just handle actual protocol messages
    if (len_in == 6 && !memcmp(string, "accept", 6) && cls.connect_trying && d0_rijndael_dll)
    {
        int wantserverid = -1;
        Crypto_RetrieveHostKey(&cls.connect_address, &wantserverid, NULL, 0, NULL, 0, NULL, NULL);
        if(!crypto || !crypto->authenticated) // we ALSO get here if we are using an encrypted connection, so let's rule this out
        {
            if(wantserverid >= 0)
                return Crypto_ClientError(data_out, len_out, "Server tried an unauthenticated connection even though a host key is present");
            if(crypto_aeslevel.integer >= 3)
                return Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)");
        }
        return CRYPTO_NOMATCH;
    }
    else if (len_in >= 1 && string[0] == 'j' && cls.connect_trying && d0_rijndael_dll)
    {
        int wantserverid = -1;
        Crypto_RetrieveHostKey(&cls.connect_address, &wantserverid, NULL, 0, NULL, 0, NULL, NULL);
        //if(!crypto || !crypto->authenticated)
        {
            if(wantserverid >= 0)
                return Crypto_ClientError(data_out, len_out, "Server tried an unauthenticated connection even though a host key is present");
            if(crypto_aeslevel.integer >= 3)
                return Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)");
        }
        return CRYPTO_NOMATCH;
    }
    else if (len_in >= 5 && BuffLittleLong((unsigned char *) string) == ((int)NETFLAG_CTL | (int)len_in))
    {
        int wantserverid = -1;
        // these three are harmless
        if((unsigned char) string[4] == CCREP_SERVER_INFO)
            return CRYPTO_NOMATCH;
        if((unsigned char) string[4] == CCREP_PLAYER_INFO)
            return CRYPTO_NOMATCH;
        if((unsigned char) string[4] == CCREP_RULE_INFO)
            return CRYPTO_NOMATCH;
        Crypto_RetrieveHostKey(&cls.connect_address, &wantserverid, NULL, 0, NULL, 0, NULL, NULL);
        //if(!crypto || !crypto->authenticated)
        {
            if(wantserverid >= 0)
                return Crypto_ClientError(data_out, len_out, "Server tried an unauthenticated connection even though a host key is present");
            if(crypto_aeslevel.integer >= 3)
                return Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)");
        }
        return CRYPTO_NOMATCH;
    }
    else if (len_in >= 13 && !memcmp(string, "infoResponse\x0A", 13))
    {
        if(InfoString_GetValue(string + 13, "d0_blind_id", infostringvalue, sizeof(infostringvalue)))
            Crypto_StoreHostKey(peeraddress, infostringvalue, true);
        return CRYPTO_NOMATCH;
    }
    else if (len_in >= 15 && !memcmp(string, "statusResponse\x0A", 15))
    {
        char save = 0;
        const char *p;
        p = strchr(string + 15, '\n');
        if(p)
        {
            save = *p;
            * (char *) p = 0; // cut off the string there
        }
        if(InfoString_GetValue(string + 15, "d0_blind_id", infostringvalue, sizeof(infostringvalue)))
            Crypto_StoreHostKey(peeraddress, infostringvalue, true);
        if(p)
        {
            * (char *) p = save;
            // invoking those nasal demons again (do not run this on the DS9k)
        }
        return CRYPTO_NOMATCH;
    }
    else if(len_in > 10 && !memcmp(string, "challenge ", 10) && cls.connect_trying)
    {
        const char *vlen_blind_id_ptr = NULL;
        size_t len_blind_id_ptr = 0;
        unsigned long k, v;
        const char *challenge = data_in + 10;
        const char *p;
        int i;
        int clientid = -1, serverid = -1, wantserverid = -1;
        qbool server_can_auth = true;
        char wantserver_idfp[FP64_SIZE+1];
        int wantserver_aeslevel = 0;
        qbool wantserver_issigned = false;
        // Must check the source IP here, if we want to prevent other servers' replies from falsely advancing the crypto state, preventing successful connect to the real server.
        if (net_sourceaddresscheck.integer && LHNETADDRESS_Compare(peeraddress, &cls.connect_address))
        {
            char warn_msg[128];
            dpsnprintf(warn_msg, sizeof(warn_msg), "ignoring challenge message from wrong server %s", peeraddressstring);
            return Crypto_SoftClientError(data_out, len_out, warn_msg);
        }
        // if we have a stored host key for the server, assume serverid to already be selected!
        // (the loop will refuse to overwrite this one then)
        wantserver_idfp[0] = 0;
        Crypto_RetrieveHostKey(&cls.connect_address, &wantserverid, NULL, 0, wantserver_idfp, sizeof(wantserver_idfp), &wantserver_aeslevel, &wantserver_issigned);
        // requirement: wantserver_idfp is a full ID if wantserverid set
        // if we leave, we have to consider the connection
        // unauthenticated; NOTE: this may be faked by a clever
        // attacker to force an unauthenticated connection; so we have
        // a safeguard check in place when encryption is required too
        // in place, or when authentication is required by the server
        crypto->authenticated = false;
        GetUntilNul(&data_in, &len_in);
        if(!data_in)
            return (wantserverid >= 0) ? Crypto_ClientError(data_out, len_out, "Server tried an unauthenticated connection even though a host key is present") :
                (d0_rijndael_dll && crypto_aeslevel.integer >= 3) ? Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)") :
                CRYPTO_NOMATCH;
        // FTEQW extension protocol
        while(len_in >= 8)
        {
            k = Crypto_LittleLong(data_in);
            v = Crypto_LittleLong(data_in + 4);
            data_in += 8;
            len_in -= 8;
            switch(k)
            {
                case PROTOCOL_VLEN:
                    if(len_in >= 4 + v)
                    {
                        k = Crypto_LittleLong(data_in);
                        data_in += 4;
                        len_in -= 4;
                        switch(k)
{
                            case PROTOCOL_D0_BLIND_ID:
                                vlen_blind_id_ptr = data_in;
                                len_blind_id_ptr = v;
                                break;
                        }
                        data_in += v;
                        len_in -= v;
                    }
                    break;
                default:
                    break;
            }
        }
        if(!vlen_blind_id_ptr)
            return (wantserverid >= 0) ? Crypto_ClientError(data_out, len_out, "Server tried an unauthenticated connection even though authentication is required") :
                (d0_rijndael_dll && crypto_aeslevel.integer >= 3) ? Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)") :
                CRYPTO_NOMATCH;
        data_in = vlen_blind_id_ptr;
        len_in = len_blind_id_ptr;
        // parse fingerprints
        //   once we found a fingerprint we can auth to (ANY), select it as clientfp
        //   once we found a fingerprint in the first list that we know, select it as serverfp
        for(;;)
        {
            p = GetUntilNul(&data_in, &len_in);
            if(!p)
                break;
            if(!*p)
            {
                if(!server_can_auth)
                    break; // other protocol message may follow
                server_can_auth = false;
                if(clientid >= 0)
                    break;
                continue;
            }
            // Find the highest numbered matching key for p.
            for(i = 0; i < MAX_PUBKEYS; ++i)
            {
                if(pubkeys[i])
                if(!strcmp(p, pubkeys_fp64[i]))
                {
                    if(pubkeys_havepriv[i])
                        clientid = i;
                    if(server_can_auth)
                        if(wantserverid < 0 || i == wantserverid)
                            serverid = i;
                }
            }
            // Not breaking, as higher keys in the list always have priority.
        }
        // if stored host key is not found:
        if(wantserverid >= 0 && serverid < 0)
            return Crypto_ClientError(data_out, len_out, "Server CA does not match stored host key, refusing to connect");
        if(serverid >= 0 || clientid >= 0)
        {
            MAKE_CDATA;
            CDATA->cdata_id = ++cdata_id;
            CDATA->s = serverid;
            CDATA->c = clientid;
            memset(crypto->dhkey, 0, sizeof(crypto->dhkey));
            dp_strlcpy(CDATA->challenge, challenge, sizeof(CDATA->challenge));
            crypto->client_keyfp[0] = 0;
            crypto->client_idfp[0] = 0;
            crypto->server_keyfp[0] = 0;
            crypto->server_idfp[0] = 0;
            memcpy(CDATA->wantserver_idfp, wantserver_idfp, sizeof(crypto->server_idfp));
            CDATA->wantserver_issigned = wantserver_issigned;
            if(CDATA->wantserver_idfp[0]) // if we know a host key, honor its encryption setting
            switch(bound(0, d0_rijndael_dll ? crypto_aeslevel.integer : 0, 3))
            {
                default: // dummy, never happens, but to make gcc happy...
                case 0:
                    if(wantserver_aeslevel >= 3)
                        return Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)");
                    CDATA->wantserver_aes = false;
                    break;
                case 1:
                    CDATA->wantserver_aes = (wantserver_aeslevel >= 2);
                    break;
                case 2:
                    CDATA->wantserver_aes = (wantserver_aeslevel >= 1);
                    break;
                case 3:
                    if(wantserver_aeslevel <= 0)
                        return Crypto_ClientError(data_out, len_out, "This server requires encryption to be supported (crypto_aeslevel >= 1, and d0_rijndael library must be present)");
                    CDATA->wantserver_aes = true;
                    break;
            }
            // build outgoing message
            // append regular stuff
            PutWithNul(&data_out_p, len_out, va(vabuf, sizeof(vabuf), "d0pk\\cnt\\0\\id\\%d\\aeslevel\\%d\\challenge\\%s", CDATA->cdata_id, d0_rijndael_dll ? crypto_aeslevel.integer : 0, challenge));
            PutWithNul(&data_out_p, len_out, serverid >= 0 ? pubkeys_fp64[serverid] : "");
            PutWithNul(&data_out_p, len_out, clientid >= 0 ? pubkeys_fp64[clientid] : "");
            if(clientid >= 0)
            {
                // I am the client, and my key is ok... so let's set client_keyfp and client_idfp
                dp_strlcpy(crypto->client_keyfp, pubkeys_fp64[CDATA->c], sizeof(crypto->client_keyfp));
                dp_strlcpy(crypto->client_idfp, pubkeys_priv_fp64[CDATA->c], sizeof(crypto->client_idfp));
                crypto->client_issigned = pubkeys_havesig[CDATA->c];
            }
            if(serverid >= 0)
            {
                if(!CDATA->id)
                    CDATA->id = qd0_blind_id_new();
                if(!CDATA->id)
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_new failed");
                }
                if(!qd0_blind_id_copy(CDATA->id, pubkeys[CDATA->s]))
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_copy failed");
                }
                CDATA->next_step = 1;
                *len_out = data_out_p - data_out;
            }
            else // if(clientid >= 0) // guaranteed by condition one level outside
            {
                // skip over server auth, perform client auth only
                if(!CDATA->id)
                    CDATA->id = qd0_blind_id_new();
                if(!CDATA->id)
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_new failed");
                }
                if(!qd0_blind_id_copy(CDATA->id, pubkeys[CDATA->c]))
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_copy failed");
                }
                if(!qd0_blind_id_authenticate_with_private_id_start(CDATA->id, true, false, "XONOTIC", 8, data_out_p, len_out)) // len_out receives used size by this op
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_authenticate_with_private_id_start failed");
                }
                CDATA->next_step = 5;
                data_out_p += *len_out;
                *len_out = data_out_p - data_out;
            }
            return CRYPTO_DISCARD;
        }
        else
        {
            if(wantserver_idfp[0]) // if we know a host key, honor its encryption setting
            if(wantserver_aeslevel >= 3)
                return Crypto_ClientError(data_out, len_out, "Server insists on encryption, but neither can authenticate to the other");
            return (d0_rijndael_dll && crypto_aeslevel.integer >= 3) ? Crypto_ClientError(data_out, len_out, "This server requires encryption to be not required (crypto_aeslevel <= 2)") :
                CRYPTO_NOMATCH;
        }
    }
    else if(len_in > 5 && !memcmp(string, "d0pk\\", 5) && cls.connect_trying)
    {
        const char *cnt;
        int id;
        // Must check the source IP here, if we want to prevent other servers' replies from falsely advancing the crypto state, preventing successful connect to the real server.
        if (net_sourceaddresscheck.integer && LHNETADDRESS_Compare(peeraddress, &cls.connect_address))
        {
            char warn_msg[128];
            dpsnprintf(warn_msg, sizeof(warn_msg), "ignoring d0pk\\ message from wrong server %s", peeraddressstring);
            return Crypto_SoftClientError(data_out, len_out, warn_msg);
        }
        id = (InfoString_GetValue(string + 4, "id", infostringvalue, sizeof(infostringvalue)) ? atoi(infostringvalue) : -1);
        cnt = (InfoString_GetValue(string + 4, "cnt", infostringvalue, sizeof(infostringvalue)) ? infostringvalue : NULL);
        if(!cnt)
            return Crypto_ClientError(data_out, len_out, "d0pk\\ message without cnt");
        GetUntilNul(&data_in, &len_in);
        if(!data_in)
            return Crypto_ClientError(data_out, len_out, "d0pk\\ message without attachment");
        if(!strcmp(cnt, "1"))
        {
            if(id >= 0)
                if(CDATA->cdata_id != id)
                    return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\id\\%d when expecting %d", id, CDATA->cdata_id));
            if(CDATA->next_step != 1)
                return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\cnt\\%s when expecting %d", cnt, CDATA->next_step));
            cls.connect_nextsendtime = max(cls.connect_nextsendtime, host.realtime + 1); // prevent "hammering"
            if(InfoString_GetValue(string + 4, "aes", infostringvalue, sizeof(infostringvalue)))
                aes = atoi(infostringvalue);
            else
                aes = false;
            // we CANNOT toggle the AES status any more!
            // as the server already decided
            if(CDATA->wantserver_idfp[0]) // if we know a host key, honor its encryption setting
            if(!aes && CDATA->wantserver_aes)
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "Stored host key requires encryption, but server did not enable encryption");
            }
            if(aes && (!d0_rijndael_dll || crypto_aeslevel.integer <= 0))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "Server insists on encryption too hard");
            }
            if(!aes && (d0_rijndael_dll && crypto_aeslevel.integer >= 3))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "Server insists on plaintext too hard");
            }
            crypto->use_aes = aes != 0;
            PutWithNul(&data_out_p, len_out, va(vabuf, sizeof(vabuf), "d0pk\\cnt\\2\\id\\%d", CDATA->cdata_id));
            if(!qd0_blind_id_authenticate_with_private_id_challenge(CDATA->id, true, false, data_in, len_in, data_out_p, len_out, &status))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_authenticate_with_private_id_challenge failed");
            }
            CDATA->next_step = 3;
            data_out_p += *len_out;
            *len_out = data_out_p - data_out;
            return CRYPTO_DISCARD;
        }
        else if(!strcmp(cnt, "3"))
        {
            static char msgbuf[32];
            size_t msgbuflen = sizeof(msgbuf);
            size_t fpbuflen;
            if(id >= 0)
                if(CDATA->cdata_id != id)
                    return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\id\\%d when expecting %d", id, CDATA->cdata_id));
            if(CDATA->next_step != 3)
                return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\cnt\\%s when expecting %d", cnt, CDATA->next_step));
            cls.connect_nextsendtime = max(cls.connect_nextsendtime, host.realtime + 1); // prevent "hammering"
            if(!qd0_blind_id_authenticate_with_private_id_verify(CDATA->id, data_in, len_in, msgbuf, &msgbuflen, &status))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_authenticate_with_private_id_verify failed (server authentication error)");
            }
            dp_strlcpy(crypto->server_keyfp, pubkeys_fp64[CDATA->s], sizeof(crypto->server_keyfp));
            if (!status && CDATA->wantserver_issigned)
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "Stored host key requires a valid signature, but server did not provide any");
            }
            crypto->server_issigned = status;
            memset(crypto->server_idfp, 0, sizeof(crypto->server_idfp));
            fpbuflen = FP64_SIZE;
            if(!qd0_blind_id_fingerprint64_public_id(CDATA->id, crypto->server_idfp, &fpbuflen))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_fingerprint64_public_id failed");
            }
            if(CDATA->wantserver_idfp[0])
            if(memcmp(CDATA->wantserver_idfp, crypto->server_idfp, sizeof(crypto->server_idfp)))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "Server ID does not match stored host key, refusing to connect");
            }
            fpbuflen = DHKEY_SIZE;
            if(!qd0_blind_id_sessionkey_public_id(CDATA->id, (char *) crypto->dhkey, &fpbuflen))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_sessionkey_public_id failed");
            }
            // cache the server key
            Crypto_StoreHostKey(&cls.connect_address, va(vabuf, sizeof(vabuf), "%d %s@%s%s", crypto->use_aes ? 1 : 0, crypto->server_idfp, crypto->server_issigned ? "" : "~", pubkeys_fp64[CDATA->s]), false);
            if(CDATA->c >= 0)
            {
                // client will auth next
                PutWithNul(&data_out_p, len_out, va(vabuf, sizeof(vabuf), "d0pk\\cnt\\4\\id\\%d", CDATA->cdata_id));
                if(!qd0_blind_id_copy(CDATA->id, pubkeys[CDATA->c]))
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_copy failed");
                }
                if(!qd0_blind_id_authenticate_with_private_id_start(CDATA->id, true, false, "XONOTIC", 8, data_out_p, len_out)) // len_out receives used size by this op
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "d0_blind_id_authenticate_with_private_id_start failed");
                }
                CDATA->next_step = 5;
                data_out_p += *len_out;
                *len_out = data_out_p - data_out;
                return CRYPTO_DISCARD;
            }
            else
            {
                // session key is FINISHED (no server part is to be expected)! By this, all keys are set up
                crypto->authenticated = true;
                CDATA->next_step = 0;
                // assume we got the empty challenge to finish the protocol
                PutWithNul(&data_out_p, len_out, "challenge ");
                *len_out = data_out_p - data_out;
                --*len_out; // remove NUL terminator
                return CRYPTO_REPLACE;
            }
        }
        else if(!strcmp(cnt, "5"))
        {
            size_t fpbuflen;
            unsigned char dhkey[DHKEY_SIZE];
            int i;
            if(id >= 0)
                if(CDATA->cdata_id != id)
                    return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\id\\%d when expecting %d", id, CDATA->cdata_id));
            if(CDATA->next_step != 5)
                return Crypto_SoftClientError(data_out, len_out, va(vabuf, sizeof(vabuf), "Got d0pk\\cnt\\%s when expecting %d", cnt, CDATA->next_step));
            cls.connect_nextsendtime = max(cls.connect_nextsendtime, host.realtime + 1); // prevent "hammering"
            if(CDATA->s < 0) // only if server didn't auth
            {
                if(InfoString_GetValue(string + 4, "aes", infostringvalue, sizeof(infostringvalue)))
                    aes = atoi(infostringvalue);
                else
                    aes = false;
                if(CDATA->wantserver_idfp[0]) // if we know a host key, honor its encryption setting
                if(!aes && CDATA->wantserver_aes)
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "Stored host key requires encryption, but server did not enable encryption");
                }
                if(aes && (!d0_rijndael_dll || crypto_aeslevel.integer <= 0))
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "Server insists on encryption too hard");
                }
                if(!aes && (d0_rijndael_dll && crypto_aeslevel.integer >= 3))
                {
                    CLEAR_CDATA;
                    return Crypto_ClientError(data_out, len_out, "Server insists on plaintext too hard");
                }
                crypto->use_aes = aes != 0;
            }
            PutWithNul(&data_out_p, len_out, va(vabuf, sizeof(vabuf), "d0pk\\cnt\\6\\id\\%d", CDATA->cdata_id));
            if(!qd0_blind_id_authenticate_with_private_id_response(CDATA->id, data_in, len_in, data_out_p, len_out))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_authenticate_with_private_id_response failed");
            }
            fpbuflen = DHKEY_SIZE;
            if(!qd0_blind_id_sessionkey_public_id(CDATA->id, (char *) dhkey, &fpbuflen))
            {
                CLEAR_CDATA;
                return Crypto_ClientError(data_out, len_out, "d0_blind_id_sessionkey_public_id failed");
            }
            // XOR the two DH keys together to make one
            for(i = 0; i < DHKEY_SIZE; ++i)
                crypto->dhkey[i] ^= dhkey[i];
            // session key is FINISHED! By this, all keys are set up
            crypto->authenticated = true;
            CDATA->next_step = 0;
            data_out_p += *len_out;
            *len_out = data_out_p - data_out;
            return CRYPTO_DISCARD;
        }
        return Crypto_SoftClientError(data_out, len_out, "Got unknown d0_blind_id message from server");
    }
    return CRYPTO_NOMATCH;
}
Referenced by NetConn_ClientParsePacket().
Crypto_DecryptPacket()
const void * Crypto_DecryptPacket (crypto_t * crypto, const void * data_src, size_t len_src, void * data_dst, size_t * len_dst, size_t len)
Definition at line 1584 of file crypto.c.
{
    unsigned char h[32];
    int i;
    // silently handle non-crypto packets
    i = BuffBigLong((unsigned char *) data_src);
    if(
        (i == (int)0xFFFFFFFF) // avoid QW control packet
        ||
        (i == (int)0x80000000 + (int)len_src) // avoid NQ control packet
    )
        return NULL;
    if(crypto->authenticated)
    {
        if(crypto->use_aes)
        {
            if(len_src < 16 || ((len_src - 16) % 16))
            {
                Con_Printf("Crypto_DecryptPacket failed (not enough space: %d bytes in, %d bytes out)\n", (int) len_src, (int) len);
                return NULL;
            }
            *len_dst = len_src - ((unsigned char *) data_src)[0];
            if(len < *len_dst || *len_dst > len_src - 16)
            {
                Con_Printf("Crypto_DecryptPacket failed (not enough space: %d bytes in, %d->%d bytes out)\n", (int) len_src, (int) *len_dst, (int) len);
                return NULL;
            }
            seacpy(crypto->dhkey, (unsigned char *) data_src, (unsigned char *) data_dst, ((const unsigned char *) data_src) + 16, *len_dst);
            //                    IV                          dst                         src                                      len
            if(!HMAC_SHA256_32BYTES(h, (const unsigned char *) data_dst, (int)*len_dst, crypto->dhkey, DHKEY_SIZE))
            {
                Con_Printf("HMAC fail\n");
                return NULL;
            }
            if(memcmp(((const unsigned char *) data_src)+1, h, 15)) // ignore first byte, used for length
            {
                Con_Printf("HMAC mismatch\n");
                return NULL;
            }
            if(developer_networking.integer)
            {
                Con_Print("Decrypted:\n");
                Com_HexDumpToConsole((const unsigned char *) data_dst, (int)*len_dst);
            }
            return data_dst; // no need to copy
        }
        else
        {
            if(len_src < 16)
            {
                Con_Printf("Crypto_DecryptPacket failed (not enough space: %d bytes in, %d bytes out)\n", (int) len_src, (int) len);
                return NULL;
            }
            *len_dst = len_src - 16;
            if(len < *len_dst)
            {
                Con_Printf("Crypto_DecryptPacket failed (not enough space: %d bytes in, %d->%d bytes out)\n", (int) len_src, (int) *len_dst, (int) len);
                return NULL;
            }
            //memcpy(data_dst, data_src + 16, *len_dst);
            if(!HMAC_SHA256_32BYTES(h, ((const unsigned char *) data_src) + 16, (int)*len_dst, crypto->dhkey, DHKEY_SIZE))
            {
                Con_Printf("HMAC fail\n");
                Com_HexDumpToConsole((const unsigned char *) data_src, (int)len_src);
                return NULL;
            }
            if(memcmp((const unsigned char *) data_src, h, 16)) // ignore first byte, used for length
            {
                // undo the "avoid conditions"
                if(
                        (i == (int)0x7FFFFFFF) // avoided QW control packet
                        ||
                        (i == (int)0x00000000 + (int)len_src) // avoided NQ control packet
                  )
                {
                    // do the avoidance on the hash too
                    h[0] ^= 0x80;
                    if(memcmp((const unsigned char *) data_src, h, 16)) // ignore first byte, used for length
                    {
                        Con_Printf("HMAC mismatch\n");
                        Com_HexDumpToConsole((const unsigned char *) data_src, (int)len_src);
                        return NULL;
                    }
                }
                else
                {
                    Con_Printf("HMAC mismatch\n");
                    Com_HexDumpToConsole((const unsigned char *) data_src, (int)len_src);
                    return NULL;
                }
            }
            return ((const unsigned char *) data_src) + 16; // no need to copy, so data_dst is not used
        }
    }
    else
    {
        *len_dst = len_src;
        return data_src;
    }
}
Referenced by NetConn_ReceivedMessage().
Crypto_EncryptPacket()
const void * Crypto_EncryptPacket (crypto_t * crypto, const void * data_src, size_t len_src, void * data_dst, size_t * len_dst, size_t len)
Definition at line 1527 of file crypto.c.
{
    unsigned char h[32];
    int i;
    if(crypto->authenticated)
    {
        if(crypto->use_aes)
        {
            // AES packet = 1 byte length overhead, 15 bytes from HMAC-SHA-256, data, 0..15 bytes padding
            // 15 bytes HMAC-SHA-256 (112bit) suffice as the attacker can't do more than forge a random-looking packet
            // HMAC is needed to not leak information about packet content
            if(developer_networking.integer)
            {
                Con_Print("To be encrypted:\n");
                Com_HexDumpToConsole((const unsigned char *) data_src, (int)len_src);
            }
            if(len_src + 32 > len || !HMAC_SHA256_32BYTES(h, (const unsigned char *) data_src, (int)len_src, crypto->dhkey, DHKEY_SIZE))
            {
                Con_Printf("Crypto_EncryptPacket failed (not enough space: %d bytes in, %d bytes out)\n", (int) len_src, (int) len);
                return NULL;
            }
            *len_dst = ((len_src + 15) / 16) * 16 + 16; // add 16 for HMAC, then round to 16-size for AES
            ((unsigned char *) data_dst)[0] = (unsigned char)(*len_dst - len_src);
            memcpy(((unsigned char *) data_dst)+1, h, 15);
            aescpy(crypto->dhkey, (const unsigned char *) data_dst, ((unsigned char *) data_dst) + 16, (const unsigned char *) data_src, len_src);
            //                    IV                                dst                                src                               len
        }
        else
        {
            // HMAC packet = 16 bytes HMAC-SHA-256 (truncated to 128 bits), data
            if(len_src + 16 > len || !HMAC_SHA256_32BYTES(h, (const unsigned char *) data_src, (int)len_src, crypto->dhkey, DHKEY_SIZE))
            {
                Con_Printf("Crypto_EncryptPacket failed (not enough space: %d bytes in, %d bytes out)\n", (int) len_src, (int) len);
                return NULL;
            }
            *len_dst = len_src + 16;
            memcpy(data_dst, h, 16);
            memcpy(((unsigned char *) data_dst) + 16, (unsigned char *) data_src, len_src);
            // handle the "avoid" conditions:
            i = BuffBigLong((unsigned char *) data_dst);
            if(
                (i == (int)0xFFFFFFFF) // avoid QW control packet
                ||
                (i == (int)0x80000000 + (int)*len_dst) // avoid NQ control packet
            )
                *(unsigned char *)data_dst ^= 0x80; // this will ALWAYS fix it
        }
        return data_dst;
    }
    else
    {
        *len_dst = len_src;
        return data_src;
    }
}
Referenced by NetConn_ReceivedMessage(), and NetConn_SendUnreliableMessage().
Crypto_FinishInstance()
qbool Crypto_FinishInstance (crypto_t * out, crypto_t * in)
Definition at line 558 of file crypto.c.
{
    // no check needed here (returned pointers are only used in prefilled fields)
    if(!crypto || !crypto->authenticated)
    {
        Con_Printf("Passed an invalid crypto connect instance\n");
        memset(out, 0, sizeof(*out));
        return false;
    }
    CLEAR_CDATA;
    memcpy(out, crypto, sizeof(*out));
    memset(crypto, 0, sizeof(*crypto));
    return true;
}
Referenced by NetConn_ConnectionEstablished(), and NetConn_ServerParsePacket().
Crypto_GetInfoResponseDataString()
const char * Crypto_GetInfoResponseDataString (void)
Definition at line 1689 of file crypto.c.
{
    crypto_idstring_buf[0] = '0' + crypto_aeslevel.integer;
    return crypto_idstring;
}
Referenced by NetConn_BuildStatusResponse().
Crypto_Init()
void Crypto_Init (void)
Definition at line 1072 of file crypto.c.
{
    cryptomempool = Mem_AllocPool("crypto", 0, NULL);
    if(!Crypto_OpenLibrary())
        return;
    qd0_blind_id_setmallocfuncs(Crypto_d0_malloc, Crypto_d0_free);
    if (Thread_HasThreads())
        qd0_blind_id_setmutexfuncs(Crypto_d0_createmutex, Crypto_d0_destroymutex, Crypto_d0_lockmutex, Crypto_d0_unlockmutex);
    if(!qd0_blind_id_INITIALIZE())
    {
        Crypto_Rijndael_CloseLibrary();
        Crypto_CloseLibrary();
        Con_Printf("libd0_blind_id initialization FAILED, cryptography support has been disabled\n");
        return;
    }
    (void) Crypto_Rijndael_OpenLibrary(); // if this fails, it's uncritical
    Crypto_InitHostKeys();
}
Referenced by Host_Init().
Crypto_Init_Commands()
void Crypto_Init_Commands (void)
Definition at line 1449 of file crypto.c.
{
    if(d0_blind_id_dll)
    {
        Cmd_AddCommand(CF_SHARED, "crypto_reload", Crypto_Reload_f, "reloads cryptographic keys");
        Cmd_AddCommand(CF_SHARED, "crypto_keygen", Crypto_KeyGen_f, "generates and saves a cryptographic key");
        Cmd_AddCommand(CF_SHARED, "crypto_keys", Crypto_Keys_f, "lists the loaded keys");
        Cmd_AddCommand(CF_SHARED, "crypto_hostkeys", Crypto_HostKeys_f, "lists the cached host keys");
        Cmd_AddCommand(CF_SHARED, "crypto_hostkey_clear", Crypto_HostKey_Clear_f, "clears a cached host key");
        Cvar_RegisterVariable(&crypto_developer);
        if(d0_rijndael_dll)
            Cvar_RegisterVariable(&crypto_aeslevel);
        else
            crypto_aeslevel.integer = 0; // make sure
        Cvar_RegisterVariable(&crypto_servercpupercent);
        Cvar_RegisterVariable(&crypto_servercpumaxtime);
        Cvar_RegisterVariable(&crypto_servercpudebug);
    }
}
Referenced by Host_Init().
Crypto_LoadKeys()
void Crypto_LoadKeys (void)
Definition at line 855 of file crypto.c.
{
    char buf[8192];
    size_t len, len2;
    int i;
    char vabuf[1024];
    if(!d0_blind_id_dll) // don't if we can't
        return;
    if(crypto_idstring) // already loaded? then not
        return;
    Host_LockSession(); // we use the session ID here
    // load keys
    // note: we are just a CLIENT
    // so we load:
    //   PUBLIC KEYS to accept (including modulus)
    //   PRIVATE KEY of user
    for(i = 0; i < MAX_PUBKEYS; ++i)
    {
        memset(pubkeys_fp64[i], 0, sizeof(pubkeys_fp64[i]));
        memset(pubkeys_priv_fp64[i], 0, sizeof(pubkeys_fp64[i]));
        pubkeys_havepriv[i] = false;
        pubkeys_havesig[i] = false;
        len = Crypto_LoadFile(va(vabuf, sizeof(vabuf), "key_%d.d0pk", i), buf, sizeof(buf), false);
        if((pubkeys[i] = Crypto_ReadPublicKey(buf, len)))
        {
            len2 = FP64_SIZE;
            if(qd0_blind_id_fingerprint64_public_key(pubkeys[i], pubkeys_fp64[i], &len2)) // keeps final NUL
            {
                Con_Printf("Loaded public key key_%d.d0pk (fingerprint: %s)\n", i, pubkeys_fp64[i]);
                len = Crypto_LoadFile(va(vabuf, sizeof(vabuf), "key_%d.d0si%s", i, sessionid.string), buf, sizeof(buf), true);
                if(len)
                {
                    if(Crypto_AddPrivateKey(pubkeys[i], buf, len))
                    {
                        len2 = FP64_SIZE;
                        if(qd0_blind_id_fingerprint64_public_id(pubkeys[i], pubkeys_priv_fp64[i], &len2)) // keeps final NUL
{
                            D0_BOOL status = 0;
                            Con_Printf("Loaded private ID key_%d.d0si%s for key_%d.d0pk (public key fingerprint: %s)\n", i, sessionid.string, i, pubkeys_priv_fp64[i]);
                            // verify the key we just loaded (just in case)
                            if(qd0_blind_id_verify_private_id(pubkeys[i]) && qd0_blind_id_verify_public_id(pubkeys[i], &status))
{
                                pubkeys_havepriv[i] = true;
                                pubkeys_havesig[i] = status;
                                // verify the key we just got (just in case)
                                if(!status)
                                    Con_Printf("NOTE: this ID has not yet been signed!\n");
                                Crypto_SavePubKeyTextFile(i);
                            }
                            else
{
                                Con_Printf("d0_blind_id_verify_private_id failed, this is not a valid key!\n");
                                qd0_blind_id_free(pubkeys[i]);
                                pubkeys[i] = NULL;
                            }
                        }
                        else
{
                            Con_Printf("d0_blind_id_fingerprint64_public_id failed\n");
                            qd0_blind_id_free(pubkeys[i]);
                            pubkeys[i] = NULL;
                        }
                    }
                }
            }
            else
            {
                // can't really happen
                qd0_blind_id_free(pubkeys[i]);
                pubkeys[i] = NULL;
            }
        }
    }
    keygen_i = -1;
    Crypto_BuildIdString();
    Crypto_BuildChallengeAppend();
    // find a good prefix length for all the keys we know (yes, algorithm is not perfect yet, may yield too long prefix length)
    crypto_keyfp_recommended_length = 0;
    memset(buf+256, 0, MAX_PUBKEYS + MAX_PUBKEYS);
    while(crypto_keyfp_recommended_length < FP64_SIZE)
    {
        memset(buf, 0, 256);
        for(i = 0; i < MAX_PUBKEYS; ++i)
            if(pubkeys[i])
            {
                if(!buf[256 + i])
                    ++buf[(unsigned char) pubkeys_fp64[i][crypto_keyfp_recommended_length]];
                if(pubkeys_havepriv[i])
                    if(!buf[256 + MAX_PUBKEYS + i])
                        ++buf[(unsigned char) pubkeys_priv_fp64[i][crypto_keyfp_recommended_length]];
            }
        for(i = 0; i < MAX_PUBKEYS; ++i)
            if(pubkeys[i])
            {
                if(!buf[256 + i])
                    if(buf[(unsigned char) pubkeys_fp64[i][crypto_keyfp_recommended_length]] < 2)
                        buf[256 + i] = 1;
                if(pubkeys_havepriv[i])
                    if(!buf[256 + MAX_PUBKEYS + i])
                        if(buf[(unsigned char) pubkeys_priv_fp64[i][crypto_keyfp_recommended_length]] < 2)
                            buf[256 + MAX_PUBKEYS + i] = 1;
            }
        ++crypto_keyfp_recommended_length;
        for(i = 0; i < MAX_PUBKEYS; ++i)
            if(pubkeys[i])
            {
                if(!buf[256 + i])
                    break;
                if(pubkeys_havepriv[i])
                    if(!buf[256 + MAX_PUBKEYS + i])
                        break;
            }
        if(i >= MAX_PUBKEYS)
            break;
    }
    if(crypto_keyfp_recommended_length < 7)
        crypto_keyfp_recommended_length = 7;
}
Referenced by Crypto_KeyGen_f(), Crypto_Reload_f(), NetConn_OpenClientPorts(), NetConn_OpenServerPorts(), and PRVM_Prog_Load().
Crypto_RetrieveHostKey()
qbool Crypto_RetrieveHostKey (struct lhnetaddress_s * peeraddress, int * keyid, char * keyfp, size_t keyfplen, char * idfp, size_t idfplen, int * aeslevel, qbool * issigned)
Crypto_RetrieveLocalKey()
int Crypto_RetrieveLocalKey (int keyid, char * keyfp, size_t keyfplen, char * idfp, size_t idfplen, qbool * issigned)
Definition at line 763 of file crypto.c.
{
    if(keyid < 0 || keyid >= MAX_PUBKEYS)
        return 0;
    if(keyfp)
        *keyfp = 0;
    if(idfp)
        *idfp = 0;
    if(!pubkeys[keyid])
        return -1;
    if(keyfp)
        dp_strlcpy(keyfp, pubkeys_fp64[keyid], keyfplen);
    if(idfp)
        if(pubkeys_havepriv[keyid])
            dp_strlcpy(idfp, pubkeys_priv_fp64[keyid], idfplen);
    if(issigned)
        *issigned = pubkeys_havesig[keyid];
    return 1;
}
Referenced by VM_M_crypto_getmyidfp(), VM_M_crypto_getmyidstatus(), and VM_M_crypto_getmykeyfp().
Crypto_ServerAppendToChallenge()
qbool Crypto_ServerAppendToChallenge (const char * data_in, size_t len_in, char * data_out, size_t * len_out, size_t maxlen)
Definition at line 1696 of file crypto.c.
{
    // cheap op, all is precomputed
    if(!d0_blind_id_dll)
        return false; // no support
    // append challenge
    if(maxlen_out <= *len_out + challenge_append_length)
        return false;
    memcpy(data_out + *len_out, challenge_append, challenge_append_length);
    *len_out += challenge_append_length;
    return false;
}
Referenced by NetConn_ServerParsePacket().
Crypto_ServerGetInstance()
crypto_t * Crypto_ServerGetInstance (struct lhnetaddress_s * peeraddress)
Crypto_ServerParsePacket()
int Crypto_ServerParsePacket (const char * data_in, size_t len_in, char * data_out, size_t * len_out, lhnetaddress_t * peeraddress)
Definition at line 2036 of file crypto.c.
{
    int ret;
    double t = 0;
    static double complain_time = 0;
    const char *cnt;
    qbool do_time = false;
    qbool do_reject = false;
    char infostringvalue[MAX_INPUTLINE];
    if(crypto_servercpupercent.value > 0 || crypto_servercpumaxtime.value > 0)
        if(len_in > 5 && !memcmp(data_in, "d0pk\\", 5))
        {
            do_time = true;
            cnt = (InfoString_GetValue(data_in + 4, "cnt", infostringvalue, sizeof(infostringvalue)) ? infostringvalue : NULL);
            if(cnt)
                if(!strcmp(cnt, "0"))
                    do_reject = true;
        }
    if(do_time)
    {
        // check if we may perform crypto...
        if(crypto_servercpupercent.value > 0)
        {
            crypto_servercpu_accumulator += (host.realtime - crypto_servercpu_lastrealtime) * crypto_servercpupercent.value * 0.01;
            if(crypto_servercpumaxtime.value)
                if(crypto_servercpu_accumulator > crypto_servercpumaxtime.value)
                    crypto_servercpu_accumulator = crypto_servercpumaxtime.value;
        }
        else
        {
            if(crypto_servercpumaxtime.value > 0)
                if(host.realtime != crypto_servercpu_lastrealtime)
                    crypto_servercpu_accumulator = crypto_servercpumaxtime.value;
        }
        crypto_servercpu_lastrealtime = host.realtime;
        if(do_reject && crypto_servercpu_accumulator < 0)
        {
            if(host.realtime > complain_time + 5)
                Con_Printf("crypto: cannot perform requested crypto operations; denial service attack or crypto_servercpupercent/crypto_servercpumaxtime are too low\n");
            *len_out = 0;
            return CRYPTO_DISCARD;
        }
        t = Sys_DirtyTime();
    }
    ret = Crypto_ServerParsePacket_Internal(data_in, len_in, data_out, len_out, peeraddress);
    if(do_time)
    {
        t = Sys_DirtyTime() - t;if (t < 0.0) t = 0.0; // dirtytime can step backwards
        if(crypto_servercpudebug.integer)
            Con_Printf("crypto: accumulator was %.1f ms, used %.1f ms for crypto, ", crypto_servercpu_accumulator * 1000, t * 1000);
        crypto_servercpu_accumulator -= t;
        if(crypto_servercpudebug.integer)
            Con_Printf("is %.1f ms\n", crypto_servercpu_accumulator * 1000);
    }
    return ret;
}
Referenced by NetConn_ServerParsePacket().
Crypto_Shutdown()
void Crypto_Shutdown (void)
Definition at line 1043 of file crypto.c.
{
    crypto_t *crypto;
    int i;
    Crypto_Rijndael_CloseLibrary();
    if(d0_blind_id_dll)
    {
        // free memory
        for(i = 0; i < MAX_CRYPTOCONNECTS; ++i)
        {
            crypto = &cryptoconnects[i].crypto;
            CLEAR_CDATA;
        }
        memset(cryptoconnects, 0, sizeof(cryptoconnects));
        crypto = &cls.crypto;
        CLEAR_CDATA;
        Crypto_UnloadKeys();
        qd0_blind_id_SHUTDOWN();
        Crypto_CloseLibrary();
    }
    Mem_FreePool(&cryptomempool);
}
Referenced by Host_Shutdown().
Crypto_SignData()
size_t Crypto_SignData (const void * data, size_t datasize, int keyid, void * signed_data, size_t signed_size)
Definition at line 2634 of file crypto.c.
{
    if(keyid < 0 || keyid >= MAX_PUBKEYS)
        return 0;
    if(!pubkeys_havepriv[keyid])
        return 0;
    if(qd0_blind_id_sign_with_private_id_sign(pubkeys[keyid], true, false, (const char *)data, datasize, (char *)signed_data, &signed_size))
        return signed_size;
    return 0;
}
Crypto_SignDataDetached()
size_t Crypto_SignDataDetached (const void * data, size_t datasize, int keyid, void * signed_data, size_t signed_size)
Definition at line 2645 of file crypto.c.
{
    if(keyid < 0 || keyid >= MAX_PUBKEYS)
        return 0;
    if(!pubkeys_havepriv[keyid])
        return 0;
    if(qd0_blind_id_sign_with_private_id_sign_detached(pubkeys[keyid], true, false, (const char *)data, datasize, (char *)signed_data, &signed_size))
        return signed_size;
    return 0;
}
Referenced by VM_uri_get().
sha256()
void sha256 (unsigned char * out, const unsigned char * in, int n)
Definition at line 383 of file crypto.c.
{
    qd0_blind_id_util_sha256((char *) out, (const char *) in, n);
}
Referenced by VM_digest_hex().
Variable Documentation
crypto_aeslevel
struct cvar_s crypto_aeslevel extern
Definition at line 31 of file crypto.c.
{CF_CLIENT | CF_SERVER | CF_ARCHIVE, "crypto_aeslevel", "1", "whether to support AES encryption in authenticated connections (0 = no, 1 = supported, 2 = requested, 3 = required)"};
Referenced by Crypto_BuildIdString(), Crypto_ClientParsePacket(), Crypto_GetInfoResponseDataString(), Crypto_Init_Commands(), and Crypto_ServerParsePacket_Internal().
crypto_developer
struct cvar_s crypto_developer extern
Definition at line 30 of file crypto.c.
{CF_CLIENT | CF_SERVER | CF_ARCHIVE, "crypto_developer", "0", "print extra info about crypto handshake"};
Referenced by Crypto_Init_Commands(), and NetConn_ServerParsePacket().
crypto_keyfp_recommended_length
int crypto_keyfp_recommended_length extern
Definition at line 41 of file crypto.c.
Referenced by Crypto_HostKeys_f(), Crypto_LoadKeys(), NetConn_ConnectionEstablished(), NetConn_ServerParsePacket(), and SV_ConnectClient().