DarkPlaces: csprogs.h File Reference
csprogs.h File Reference
Macros
#define CL_MAX_EDICTS MAX_EDICTS
#define ENTMASK_ENGINE 1
#define ENTMASK_ENGINEVIEWMODELS 2
#define ENTMASK_NORMAL 4
#define VF_MIN 1
#define VF_MIN_X 2
#define VF_MIN_Y 3
#define VF_SIZE 4
#define VF_SIZE_X 5
#define VF_SIZE_Y 6
#define VF_VIEWPORT 7
#define VF_FOV 8
#define VF_FOVX 9
#define VF_FOVY 10
#define VF_ORIGIN 11
#define VF_ORIGIN_X 12
#define VF_ORIGIN_Y 13
#define VF_ORIGIN_Z 14
#define VF_ANGLES 15
#define VF_ANGLES_X 16
#define VF_ANGLES_Y 17
#define VF_ANGLES_Z 18
#define VF_DRAWWORLD 19
#define VF_DRAWENGINESBAR 20
#define VF_DRAWCROSSHAIR 21
#define VF_CL_VIEWANGLES 33
#define VF_CL_VIEWANGLES_X 34
#define VF_CL_VIEWANGLES_Y 35
#define VF_CL_VIEWANGLES_Z 36
#define VF_PERSPECTIVE 200
#define VF_CLEARSCREEN 201
#define VF_FOG_DENSITY 202
#define VF_FOG_COLOR 203
#define VF_FOG_COLOR_R 204
#define VF_FOG_COLOR_G 205
#define VF_FOG_COLOR_B 206
#define VF_FOG_ALPHA 207
#define VF_FOG_START 208
#define VF_FOG_END 209
#define VF_FOG_HEIGHT 210
#define VF_FOG_FADEDEPTH 211
#define VF_MAINVIEW 400
#define VF_MINFPS_QUALITY 401
#define RF_VIEWMODEL 1
#define RF_EXTERNALMODEL 2
#define RF_DEPTHHACK 4
#define RF_ADDITIVE 8
#define RF_USEAXIS 16
#define RF_USETRANSPARENTOFFSET 64
#define RF_WORLDOBJECT 128
#define RF_MODELLIGHT 4096
#define RF_DYNAMICMODELLIGHT 8192
#define RF_FULLBRIGHT 256
#define RF_NOSHADOW 512
Functions
void CL_VM_PreventInformationLeaks (void)
qbool MakeDownloadPacket (const char *filename, unsigned char *data, size_t len, int crc, int cnt, sizebuf_t *buf, int protocol)
qbool CL_VM_GetEntitySoundOrigin (int entnum, vec3_t out)
qbool CL_VM_TransformView (int entnum, matrix4x4_t *viewmatrix, mplane_t *clipplane, vec3_t visorigin)
void CL_VM_Init (void)
void CL_VM_ShutDown (void)
void CL_VM_UpdateIntermissionState (int intermission)
void CL_VM_UpdateShowingScoresState (int showingscores)
qbool CL_VM_InputEvent (int eventtype, float x, float y)
qbool CL_VM_ConsoleCommand (const char *text, size_t textlen)
void CL_VM_UpdateDmgGlobals (int dmg_take, int dmg_save, vec3_t dmg_origin)
qbool CL_VM_Event_Sound (int sound_num, float volume, int channel, float attenuation, int ent, vec3_t pos, int flags, float speed)
qbool CL_VM_Parse_TempEntity (void)
void CL_VM_Parse_StuffCmd (const char *msg, size_t msg_len)
void CL_VM_Parse_CenterPrint (const char *msg, size_t msg_len)
int CL_GetPitchSign (prvm_prog_t *prog, prvm_edict_t *ent)
int CL_GetTagMatrix (prvm_prog_t *prog, matrix4x4_t *out, prvm_edict_t *ent, int tagindex, prvm_vec_t *shadingorigin)
void CL_GetEntityMatrix (prvm_prog_t *prog, prvm_edict_t *ent, matrix4x4_t *out, qbool viewmatrix)
void QW_CL_StartUpload (unsigned char *data, int size)
void CSQC_UpdateNetworkTimes (double newtime, double oldtime)
void CSQC_AddPrintText (const char *msg, size_t msg_len)
void CSQC_ReadEntities (void)
void CSQC_RelinkAllEntities (int drawmask)
void CSQC_RelinkCSQCEntities (void)
void CSQC_Predraw (prvm_edict_t *ed)
void CSQC_Think (prvm_edict_t *ed)
qbool CSQC_AddRenderEdict (prvm_edict_t *ed, int edictnum)
void CSQC_R_RecalcView (void)
model_t * CL_GetModelByIndex (int modelindex)
int CL_VM_GetViewEntity (void)
Variables
cvar_t csqc_progname
cvar_t csqc_progcrc
cvar_t csqc_progsize
cvar_t csqc_polygons_defaultmaterial_nocullface
Macro Definition Documentation
CL_MAX_EDICTS
#define CL_MAX_EDICTS MAX_EDICTS
Definition at line 25 of file csprogs.h.
ENTMASK_ENGINE
#define ENTMASK_ENGINE 1
Definition at line 27 of file csprogs.h.
ENTMASK_ENGINEVIEWMODELS
#define ENTMASK_ENGINEVIEWMODELS 2
Definition at line 28 of file csprogs.h.
ENTMASK_NORMAL
#define ENTMASK_NORMAL 4
Definition at line 29 of file csprogs.h.
RF_ADDITIVE
#define RF_ADDITIVE 8
Definition at line 84 of file csprogs.h.
RF_DEPTHHACK
#define RF_DEPTHHACK 4
Definition at line 83 of file csprogs.h.
RF_DYNAMICMODELLIGHT
#define RF_DYNAMICMODELLIGHT 8192
Definition at line 91 of file csprogs.h.
RF_EXTERNALMODEL
#define RF_EXTERNALMODEL 2
Definition at line 82 of file csprogs.h.
RF_FULLBRIGHT
#define RF_FULLBRIGHT 256
Definition at line 93 of file csprogs.h.
RF_MODELLIGHT
#define RF_MODELLIGHT 4096
Definition at line 90 of file csprogs.h.
RF_NOSHADOW
#define RF_NOSHADOW 512
Definition at line 94 of file csprogs.h.
RF_USEAXIS
#define RF_USEAXIS 16
Definition at line 85 of file csprogs.h.
RF_USETRANSPARENTOFFSET
#define RF_USETRANSPARENTOFFSET 64
Definition at line 88 of file csprogs.h.
RF_VIEWMODEL
#define RF_VIEWMODEL 1
Definition at line 81 of file csprogs.h.
RF_WORLDOBJECT
#define RF_WORLDOBJECT 128
Definition at line 89 of file csprogs.h.
VF_ANGLES
#define VF_ANGLES 15
Definition at line 45 of file csprogs.h.
VF_ANGLES_X
#define VF_ANGLES_X 16
Definition at line 46 of file csprogs.h.
VF_ANGLES_Y
#define VF_ANGLES_Y 17
Definition at line 47 of file csprogs.h.
VF_ANGLES_Z
#define VF_ANGLES_Z 18
Definition at line 48 of file csprogs.h.
VF_CL_VIEWANGLES
#define VF_CL_VIEWANGLES 33
Definition at line 54 of file csprogs.h.
VF_CL_VIEWANGLES_X
#define VF_CL_VIEWANGLES_X 34
Definition at line 55 of file csprogs.h.
VF_CL_VIEWANGLES_Y
#define VF_CL_VIEWANGLES_Y 35
Definition at line 56 of file csprogs.h.
VF_CL_VIEWANGLES_Z
#define VF_CL_VIEWANGLES_Z 36
Definition at line 57 of file csprogs.h.
VF_CLEARSCREEN
#define VF_CLEARSCREEN 201
Definition at line 63 of file csprogs.h.
VF_DRAWCROSSHAIR
#define VF_DRAWCROSSHAIR 21
Definition at line 52 of file csprogs.h.
VF_DRAWENGINESBAR
#define VF_DRAWENGINESBAR 20
Definition at line 51 of file csprogs.h.
VF_DRAWWORLD
#define VF_DRAWWORLD 19
Definition at line 50 of file csprogs.h.
VF_FOG_ALPHA
#define VF_FOG_ALPHA 207
Definition at line 71 of file csprogs.h.
VF_FOG_COLOR
#define VF_FOG_COLOR 203
Definition at line 67 of file csprogs.h.
VF_FOG_COLOR_B
#define VF_FOG_COLOR_B 206
Definition at line 70 of file csprogs.h.
VF_FOG_COLOR_G
#define VF_FOG_COLOR_G 205
Definition at line 69 of file csprogs.h.
VF_FOG_COLOR_R
#define VF_FOG_COLOR_R 204
Definition at line 68 of file csprogs.h.
VF_FOG_DENSITY
#define VF_FOG_DENSITY 202
Definition at line 66 of file csprogs.h.
VF_FOG_END
#define VF_FOG_END 209
Definition at line 73 of file csprogs.h.
VF_FOG_FADEDEPTH
#define VF_FOG_FADEDEPTH 211
Definition at line 75 of file csprogs.h.
VF_FOG_HEIGHT
#define VF_FOG_HEIGHT 210
Definition at line 74 of file csprogs.h.
VF_FOG_START
#define VF_FOG_START 208
Definition at line 72 of file csprogs.h.
VF_FOV
#define VF_FOV 8
Definition at line 38 of file csprogs.h.
VF_FOVX
#define VF_FOVX 9
Definition at line 39 of file csprogs.h.
VF_FOVY
#define VF_FOVY 10
Definition at line 40 of file csprogs.h.
VF_MAINVIEW
#define VF_MAINVIEW 400
Definition at line 78 of file csprogs.h.
VF_MIN
#define VF_MIN 1
Definition at line 31 of file csprogs.h.
VF_MIN_X
#define VF_MIN_X 2
Definition at line 32 of file csprogs.h.
VF_MIN_Y
#define VF_MIN_Y 3
Definition at line 33 of file csprogs.h.
VF_MINFPS_QUALITY
#define VF_MINFPS_QUALITY 401
Definition at line 79 of file csprogs.h.
VF_ORIGIN
#define VF_ORIGIN 11
Definition at line 41 of file csprogs.h.
VF_ORIGIN_X
#define VF_ORIGIN_X 12
Definition at line 42 of file csprogs.h.
VF_ORIGIN_Y
#define VF_ORIGIN_Y 13
Definition at line 43 of file csprogs.h.
VF_ORIGIN_Z
#define VF_ORIGIN_Z 14
Definition at line 44 of file csprogs.h.
VF_PERSPECTIVE
#define VF_PERSPECTIVE 200
Definition at line 60 of file csprogs.h.
VF_SIZE
#define VF_SIZE 4
Definition at line 34 of file csprogs.h.
VF_SIZE_X
#define VF_SIZE_X 5
Definition at line 35 of file csprogs.h.
VF_SIZE_Y
#define VF_SIZE_Y 6
Definition at line 36 of file csprogs.h.
VF_VIEWPORT
#define VF_VIEWPORT 7
Definition at line 37 of file csprogs.h.
Function Documentation
CL_GetEntityMatrix()
void CL_GetEntityMatrix (prvm_prog_t * prog, prvm_edict_t * ent, matrix4x4_t * out, qbool viewmatrix)
Definition at line 3210 of file clvm_cmds.c.
{
    float scale;
    float pitchsign = 1;
    scale = PRVM_clientedictfloat(ent, scale);
    if (!scale)
        scale = 1.0f;
    if(viewmatrix)
        *out = r_refdef.view.matrix;
    else if ((int)PRVM_clientedictfloat(ent, renderflags) & RF_USEAXIS)
    {
        vec3_t forward;
        vec3_t left;
        vec3_t up;
        vec3_t origin;
        VectorScale(PRVM_clientglobalvector(v_forward), scale, forward);
        VectorScale(PRVM_clientglobalvector(v_right), -scale, left);
        VectorScale(PRVM_clientglobalvector(v_up), scale, up);
        VectorCopy(PRVM_clientedictvector(ent, origin), origin);
        Matrix4x4_FromVectors(out, forward, left, up, origin);
    }
    else
    {
        pitchsign = CL_GetPitchSign(prog, ent);
        Matrix4x4_CreateFromQuakeEntity(out, PRVM_clientedictvector(ent, origin)[0], PRVM_clientedictvector(ent, origin)[1], PRVM_clientedictvector(ent, origin)[2], pitchsign * PRVM_clientedictvector(ent, angles)[0], PRVM_clientedictvector(ent, angles)[1], PRVM_clientedictvector(ent, angles)[2], scale);
    }
}
Referenced by CL_GetTagMatrix(), and getmatrix().
CL_GetModelByIndex()
model_t * CL_GetModelByIndex (int modelindex)
Definition at line 86 of file cl_collision.c.
{
    if(!modelindex)
        return NULL;
    if (modelindex < 0)
    {
        modelindex = -(modelindex+1);
        if (modelindex < MAX_MODELS)
            return cl.csqc_model_precache[modelindex];
    }
    else
    {
        if(modelindex < MAX_MODELS)
            return cl.model_precache[modelindex];
    }
    return NULL;
}
Referenced by CL_AddQWCTFFlagModel(), CL_GetModelFromEdict(), CL_LinkEdict(), CL_ModelIndexList_f(), CL_ParseEffect(), CL_ParseEffect2(), CL_ParseStatic(), CL_ParseTempEntity(), CL_RelinkQWNails(), CL_RelinkStaticEntities(), CL_SetupWorldModel(), CL_UpdateNetworkEntity(), CL_ValidateState(), EntityState5_ReadUpdate(), SND_Spatialize_WithSfx(), VM_CL_frameduration(), VM_CL_frameforname(), VM_CL_makestatic(), VM_CL_modelnameforindex(), VM_CL_setattachment(), VM_CL_setmodelindex(), VM_CL_skel_build(), and VM_CL_skel_create().
CL_GetPitchSign()
int CL_GetPitchSign (prvm_prog_t * prog, prvm_edict_t * ent)
Definition at line 3202 of file clvm_cmds.c.
{
    model_t *model;
    if ((model = CL_GetModelFromEdict(ent)) && model->type == mod_alias)
        return -1;
    return 1;
}
Referenced by CL_GetEntityMatrix().
CL_GetTagMatrix()
int CL_GetTagMatrix (prvm_prog_t * prog, matrix4x4_t * out, prvm_edict_t * ent, int tagindex, prvm_vec_t * shadingorigin)
Definition at line 3266 of file clvm_cmds.c.
{
    int ret;
    int attachloop;
    matrix4x4_t entitymatrix, tagmatrix, attachmatrix;
    model_t *model;
    vec3_t shadingorigin;
    *out = identitymatrix; // warnings and errors return identical matrix
    if (ent == prog->edicts)
        return 1;
    if (ent->free)
        return 2;
    model = CL_GetModelFromEdict(ent);
    if(!model)
        return 3;
    tagmatrix = identitymatrix;
    attachloop = 0;
    for(;;)
    {
        if(attachloop >= 256)
            return 5;
        // apply transformation by child's tagindex on parent entity and then
        // by parent entity itself
        ret = CL_GetEntityLocalTagMatrix(prog, ent, tagindex - 1, &attachmatrix);
        if(ret && attachloop == 0)
            return ret;
        CL_GetEntityMatrix(prog, ent, &entitymatrix, false);
        Matrix4x4_Concat(&tagmatrix, &attachmatrix, out);
        Matrix4x4_Concat(out, &entitymatrix, &tagmatrix);
        // next iteration we process the parent entity
        if (PRVM_clientedictedict(ent, tag_entity))
        {
            tagindex = (int)PRVM_clientedictfloat(ent, tag_index);
            ent = PRVM_EDICT_NUM(PRVM_clientedictedict(ent, tag_entity));
        }
        else
            break;
        attachloop++;
    }
    // RENDER_VIEWMODEL magic
    if ((int)PRVM_clientedictfloat(ent, renderflags) & RF_VIEWMODEL)
    {
        Matrix4x4_Copy(&tagmatrix, out);
        CL_GetEntityMatrix(prog, prog->edicts, &entitymatrix, true);
        Matrix4x4_Concat(out, &entitymatrix, &tagmatrix);
        /*
        // Cl_bob, ported from rendering code
        if (PRVM_clientedictfloat(ent, health) > 0 && cl_bob.value && cl_bobcycle.value)
        {
            double bob, cycle;
            // LadyHavoc: this code is *weird*, but not replacable (I think it
            // should be done in QC on the server, but oh well, quake is quake)
            // LadyHavoc: figured out bobup: the time at which the sin is at 180
            // degrees (which allows lengthening or squishing the peak or valley)
            cycle = cl.time/cl_bobcycle.value;
            cycle -= (int)cycle;
            if (cycle < cl_bobup.value)
                cycle = sin(M_PI * cycle / cl_bobup.value);
            else
                cycle = sin(M_PI + M_PI * (cycle-cl_bobup.value)/(1.0 - cl_bobup.value));
            // bob is proportional to velocity in the xy plane
            // (don't count Z, or jumping messes it up)
            bob = sqrt(PRVM_clientedictvector(ent, velocity)[0]*PRVM_clientedictvector(ent, velocity)[0] + PRVM_clientedictvector(ent, velocity)[1]*PRVM_clientedictvector(ent, velocity)[1])*cl_bob.value;
            bob = bob*0.3 + bob*0.7*cycle;
            Matrix4x4_AdjustOrigin(out, 0, 0, bound(-7, bob, 4));
        }
        */
        // return the origin of the view
        Matrix4x4_OriginFromMatrix(&r_refdef.view.matrix, shadingorigin);
    }
    else
    {
        // return the origin of the root entity in the chain
        Matrix4x4_OriginFromMatrix(out, shadingorigin);
    }
    if (returnshadingorigin)
        VectorCopy(shadingorigin, returnshadingorigin);
    return 0;
}
Referenced by CL_VM_GetEntitySoundOrigin(), CSQC_AddRenderEdict(), VM_CL_gettaginfo(), and VM_CL_V_CalcRefdef().
CL_VM_ConsoleCommand()
qbool CL_VM_ConsoleCommand (const char * text, size_t textlen)
Definition at line 527 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    return PRVM_ConsoleCommand(prog, text, textlen, &prog->funcoffsets.CSQC_ConsoleCommand, false, cl.csqc_server2csqcentitynumber[cl.playerentity], cl.time, "QC function CSQC_ConsoleCommand is missing");
}
Referenced by Cmd_CL_Callback().
CL_VM_Event_Sound()
qbool CL_VM_Event_Sound (int sound_num, float volume, int channel, float attenuation, int ent, vec3_t pos, int flags, float speed)
Definition at line 675 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    qbool r = false;
    if(prog->loaded)
    {
        if(PRVM_clientfunction(CSQC_Event_Sound))
        {
            PRVM_clientglobalfloat(time) = cl.time;
            PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[cl.playerentity];
            PRVM_G_FLOAT(OFS_PARM0) = ent;
            PRVM_G_FLOAT(OFS_PARM1) = CHAN_ENGINE2USER(channel);
            PRVM_G_INT(OFS_PARM2) = PRVM_SetTempString(prog, cl.sound_name[sound_num], strlen(cl.sound_name[sound_num]));
            PRVM_G_FLOAT(OFS_PARM3) = fvolume;
            PRVM_G_FLOAT(OFS_PARM4) = attenuation;
            VectorCopy(pos, PRVM_G_VECTOR(OFS_PARM5) );
            PRVM_G_FLOAT(OFS_PARM6) = speed * 100.0f;
            PRVM_G_FLOAT(OFS_PARM7) = flags; // flags
            prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Event_Sound), "QC function CSQC_Event_Sound is missing");
            r = CSQC_RETURNVAL != 0;
        }
    }
    return r;
}
Referenced by CL_ParseStartSoundPacket().
CL_VM_GetEntitySoundOrigin()
qbool CL_VM_GetEntitySoundOrigin (int entnum, vec3_t out)
Definition at line 1116 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    prvm_edict_t *ed;
    model_t *mod;
    matrix4x4_t matrix;
    qbool r = 0;
    ed = PRVM_EDICT_NUM(entnum - MAX_EDICTS);
    if(!ed->free)
    {
        mod = CL_GetModelFromEdict(ed);
        VectorCopy(PRVM_clientedictvector(ed, origin), out);
        if(CL_GetTagMatrix(prog, &matrix, ed, 0, NULL) == 0)
            Matrix4x4_OriginFromMatrix(&matrix, out);
        if (mod && mod->soundfromcenter)
            VectorMAMAM(1.0f, out, 0.5f, mod->normalmins, 0.5f, mod->normalmaxs, out);
        r = 1;
    }
    return r;
}
Referenced by SND_Spatialize_WithSfx(), and VM_CL_sound().
CL_VM_GetViewEntity()
int CL_VM_GetViewEntity (void)
Definition at line 1182 of file csprogs.c.
{
    if(cl.csqc_server2csqcentitynumber[cl.viewentity])
        return cl.csqc_server2csqcentitynumber[cl.viewentity] + MAX_EDICTS;
    return cl.viewentity;
}
Referenced by SND_PickChannel(), and SND_Spatialize_WithSfx().
CL_VM_Init()
void CL_VM_Init (void)
Definition at line 934 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    const char* csprogsfn = NULL;
    unsigned char *csprogsdata = NULL;
    fs_offset_t csprogsdatasize = 0;
    int csprogsdatacrc, requiredcrc;
    int requiredsize;
    char vabuf[1024];
    // reset csqc_progcrc after reading it, so that changing servers doesn't
    // expect csqc on the next server
    requiredcrc = csqc_progcrc.integer;
    requiredsize = csqc_progsize.integer;
    Cvar_SetValueQuick(&csqc_progcrc, -1);
    Cvar_SetValueQuick(&csqc_progsize, -1);
    // if the server is not requesting a csprogs, then we're done here
    if (requiredcrc < 0)
        return;
    // see if the requested csprogs.dat file matches the requested crc
    if (!cls.demoplayback || csqc_usedemoprogs.integer)
    {
        csprogsfn = va(vabuf, sizeof(vabuf), "dlcache/%s.%i.%i", csqc_progname.string, requiredsize, requiredcrc);
        if(cls.caughtcsprogsdata && cls.caughtcsprogsdatasize == requiredsize && CRC_Block(cls.caughtcsprogsdata, (size_t)cls.caughtcsprogsdatasize) == requiredcrc)
        {
            Con_DPrintf("Using buffered \"%s\"\n", csprogsfn);
            csprogsdata = cls.caughtcsprogsdata;
            csprogsdatasize = cls.caughtcsprogsdatasize;
            cls.caughtcsprogsdata = NULL;
            cls.caughtcsprogsdatasize = 0;
        }
        else
        {
            Con_DPrintf("Not using buffered \"%s\" (buffered: %p, %d)\n", csprogsfn, (void *)cls.caughtcsprogsdata, (int) cls.caughtcsprogsdatasize);
            csprogsdata = FS_LoadFile(csprogsfn, tempmempool, true, &csprogsdatasize);
        }
    }
    if (!csprogsdata)
    {
        csprogsfn = csqc_progname.string;
        csprogsdata = FS_LoadFile(csprogsfn, tempmempool, true, &csprogsdatasize);
    }
    if (csprogsdata)
    {
        csprogsdatacrc = CRC_Block(csprogsdata, (size_t)csprogsdatasize);
        if (csprogsdatacrc != requiredcrc || csprogsdatasize != requiredsize)
        {
            if (cls.demoplayback)
            {
                Con_Printf(CON_WARN "Warning: Your %s is not the same version as the demo was recorded with (CRC/size are %i/%i but should be %i/%i)\n", csqc_progname.string, csprogsdatacrc, (int)csprogsdatasize, requiredcrc, requiredsize);
                // Mem_Free(csprogsdata);
                // return;
                // We WANT to continue here, and play the demo with different csprogs!
                // After all, this is just a warning. Sure things may go wrong from here.
            }
            else
            {
                Mem_Free(csprogsdata);
                CL_DisconnectEx(false, "Your %s is not the same version as the server (CRC is %i/%i but should be %i/%i)\n", csqc_progname.string, csprogsdatacrc, (int)csprogsdatasize, requiredcrc, requiredsize);
                return;
            }
        }
    }
    else
    {
        if (requiredcrc >= 0)
            CL_DisconnectEx(false, CON_ERROR "CL_VM_Init: %s requires CSQC, but \"%s\" wasn't found\n", cls.demoplayback ? "demo" : "server", csqc_progname.string);
        return;
    }
    PRVM_Prog_Init(prog, cmd_local);
    // allocate the mempools
    prog->progs_mempool = Mem_AllocPool(csqc_progname.string, 0, NULL);
    prog->edictprivate_size = 0; // no private struct used
    prog->name = "client";
    prog->num_edicts = 1;
    prog->max_edicts = 512;
    prog->limit_edicts = CL_MAX_EDICTS;
    prog->reserved_edicts = 0;
    prog->edictprivate_size = sizeof(edict_engineprivate_t);
    // TODO: add a shared extension string #define and add real support for csqc extension strings [12/5/2007 Black]
    prog->extensionstring = vm_sv_extensions;
    prog->builtins = vm_cl_builtins;
    prog->numbuiltins = vm_cl_numbuiltins;
    // all callbacks must be defined (pointers are not checked before calling)
    prog->begin_increase_edicts = CLVM_begin_increase_edicts;
    prog->end_increase_edicts   = CLVM_end_increase_edicts;
    prog->init_edict            = CLVM_init_edict;
    prog->free_edict            = CLVM_free_edict;
    prog->count_edicts          = CLVM_count_edicts;
    prog->load_edict            = CLVM_load_edict;
    prog->init_cmd              = CLVM_init_cmd;
    prog->reset_cmd             = CLVM_reset_cmd;
    prog->error_cmd             = Host_Error;
    prog->ExecuteProgram        = CLVM_ExecuteProgram;
    PRVM_Prog_Load(prog, csprogsfn, csprogsdata, csprogsdatasize, cl_numrequiredfunc, cl_required_func, CL_REQFIELDS, cl_reqfields, CL_REQGLOBALS, cl_reqglobals);
    if (!prog->loaded)
    {
        Mem_Free(csprogsdata);
        Host_Error("CSQC %s failed to load\n", csprogsfn);
    }
    if(cls.demorecording)
    {
        if(cls.demo_lastcsprogssize != csprogsdatasize || cls.demo_lastcsprogscrc != csprogsdatacrc)
        {
            int i;
            static char buf[NET_MAXMESSAGE];
            sizebuf_t sb;
            unsigned char *demobuf; fs_offset_t demofilesize;
            sb.data = (unsigned char *) buf;
            sb.maxsize = sizeof(buf);
            i = 0;
            CL_CutDemo(&demobuf, &demofilesize);
            while(MakeDownloadPacket(csqc_progname.string, csprogsdata, (size_t)csprogsdatasize, csprogsdatacrc, i++, &sb, cls.protocol))
                CL_WriteDemoMessage(&sb);
            CL_PasteDemo(&demobuf, &demofilesize);
            cls.demo_lastcsprogssize = csprogsdatasize;
            cls.demo_lastcsprogscrc = csprogsdatacrc;
        }
    }
    Mem_Free(csprogsdata);
    // check if OP_STATE animation is possible in this dat file
    if (prog->fieldoffsets.nextthink >= 0 && prog->fieldoffsets.frame >= 0 && prog->fieldoffsets.think >= 0 && prog->globaloffsets.self >= 0)
        prog->flag |= PRVM_OP_STATE;
    // set time
    PRVM_clientglobalfloat(time) = cl.time;
    PRVM_clientglobaledict(self) = 0;
    PRVM_clientglobalstring(mapname) = PRVM_SetEngineString(prog, cl.worldbasename);
    PRVM_clientglobalfloat(player_localnum) = cl.realplayerentity - 1;
    PRVM_clientglobalfloat(player_localentnum) = cl.viewentity;
    // set map description (use world entity 0)
    PRVM_clientedictstring(prog->edicts, message) = PRVM_SetEngineString(prog, cl.worldmessage);
    VectorCopy(cl.world.mins, PRVM_clientedictvector(prog->edicts, mins));
    VectorCopy(cl.world.maxs, PRVM_clientedictvector(prog->edicts, maxs));
    VectorCopy(cl.world.mins, PRVM_clientedictvector(prog->edicts, absmin));
    VectorCopy(cl.world.maxs, PRVM_clientedictvector(prog->edicts, absmax));
    // call the prog init
    prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Init), "QC function CSQC_Init is missing");
    // Once CSQC_Init was called, we consider csqc code fully initialized.
    prog->inittime = host.realtime;
    cl.csqc_vidvars.drawcrosshair = false;
    cl.csqc_vidvars.drawenginesbar = false;
    // Update Coop and Deathmatch Globals (at this point the client knows them from ServerInfo)
    CL_VM_UpdateCoopDeathmatchGlobals(cl.gametype);
}
Referenced by CL_SetupWorldModel().
CL_VM_InputEvent()
qbool CL_VM_InputEvent (int eventtype, float x, float y)
Definition at line 453 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    qbool r;
    if(!prog->loaded)
        return false;
    if (!PRVM_clientfunction(CSQC_InputEvent))
        r = false;
    else
    {
        PRVM_clientglobalfloat(time) = cl.time;
        PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[cl.playerentity];
        PRVM_G_FLOAT(OFS_PARM0) = eventtype;
        PRVM_G_FLOAT(OFS_PARM1) = x; // key or x
        PRVM_G_FLOAT(OFS_PARM2) = y; // ascii or y
        prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_InputEvent), "QC function CSQC_InputEvent is missing");
        r = CSQC_RETURNVAL != 0;
    }
    return r;
}
Referenced by CL_Input(), and Key_Event().
CL_VM_Parse_CenterPrint()
void CL_VM_Parse_CenterPrint (const char * msg, size_t msg_len)
Definition at line 643 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int restorevm_tempstringsbuf_cursize;
    if(prog->loaded && PRVM_clientfunction(CSQC_Parse_CenterPrint))
    {
        PRVM_clientglobalfloat(time) = cl.time;
        PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[cl.playerentity];
        restorevm_tempstringsbuf_cursize = prog->tempstringsbuf.cursize;
        PRVM_G_INT(OFS_PARM0) = PRVM_SetTempString(prog, msg, msg_len);
        prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Parse_CenterPrint), "QC function CSQC_Parse_CenterPrint is missing");
        prog->tempstringsbuf.cursize = restorevm_tempstringsbuf_cursize;
    }
    else
        SCR_CenterPrint(msg);
}
Referenced by CL_ParseServerMessage().
CL_VM_Parse_StuffCmd()
void CL_VM_Parse_StuffCmd (const char * msg, size_t msg_len)
Definition at line 558 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int restorevm_tempstringsbuf_cursize;
    if(msg[0] == 'c')
    if(msg[1] == 's')
    if(msg[2] == 'q')
    if(msg[3] == 'c')
    {
        // if this is setting a csqc variable, deprotect csqc_progcrc
        // temporarily so that it can be set by the cvar command,
        // and then reprotect it afterwards
        int crcflags = csqc_progcrc.flags;
        csqc_progcrc.flags &= ~CF_READONLY;
        csqc_progsize.flags &= ~CF_READONLY;
        Cmd_ExecuteString(cmd_local, msg, msg_len, src_local, true);
        csqc_progcrc.flags = csqc_progsize.flags = crcflags;
        return;
    }
    if(!prog->loaded)
    {
        Cbuf_AddText(cmd_local, msg);
        return;
    }
    if(PRVM_clientfunction(CSQC_Parse_StuffCmd))
    {
        PRVM_clientglobalfloat(time) = cl.time;
        PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[cl.playerentity];
        restorevm_tempstringsbuf_cursize = prog->tempstringsbuf.cursize;
        PRVM_G_INT(OFS_PARM0) = PRVM_SetTempString(prog, msg, msg_len);
        prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Parse_StuffCmd), "QC function CSQC_Parse_StuffCmd is missing");
        prog->tempstringsbuf.cursize = restorevm_tempstringsbuf_cursize;
    }
    else
        Cbuf_AddText(cmd_local, msg);
}
Referenced by CL_ParseServerMessage().
CL_VM_Parse_TempEntity()
qbool CL_VM_Parse_TempEntity (void)
Definition at line 533 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int t;
    qbool r = false;
    if(!prog->loaded)
        return false;
    if(PRVM_clientfunction(CSQC_Parse_TempEntity))
    {
        t = cl_message.readcount;
        PRVM_clientglobalfloat(time) = cl.time;
        PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[cl.playerentity];
        prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Parse_TempEntity), "QC function CSQC_Parse_TempEntity is missing");
        r = CSQC_RETURNVAL != 0;
        if(!r)
        {
            cl_message.readcount = t;
            cl_message.badread = false;
        }
    }
    return r;
}
Referenced by CL_ParseServerMessage().
CL_VM_PreventInformationLeaks()
void CL_VM_PreventInformationLeaks (void)
Definition at line 36 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    if(!prog->loaded)
        return;
    VM_ClearTraceGlobals(prog);
    PRVM_clientglobalfloat(trace_networkentity) = 0;
}
Referenced by CL_Frame().
CL_VM_ShutDown()
void CL_VM_ShutDown (void)
Definition at line 1098 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    Cmd_ClearCSQCCommands(cmd_local);
    //Cvar_SetValueQuick(&csqc_progcrc, -1);
    //Cvar_SetValueQuick(&csqc_progsize, -1);
    if (prog->loaded)
    {
        PRVM_clientglobalfloat(time) = cl.time;
        PRVM_clientglobaledict(self) = 0;
        if (PRVM_clientfunction(CSQC_Shutdown))
            prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Shutdown), "QC function CSQC_Shutdown is missing");
    }
    PRVM_Prog_Reset(prog);
    Con_DPrint("CSQC ^1unloaded\n");
}
Referenced by CL_ClearState(), and CL_DisconnectEx().
CL_VM_TransformView()
qbool CL_VM_TransformView (int entnum, matrix4x4_t * viewmatrix, mplane_t * clipplane, vec3_t visorigin)
Definition at line 1140 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    qbool ret = false;
    prvm_edict_t *ed;
    vec3_t forward, left, up, origin, ang;
    matrix4x4_t mat, matq;
    ed = PRVM_EDICT_NUM(entnum);
    // camera:
    //   camera_transform
    if(PRVM_clientedictfunction(ed, camera_transform))
    {
        ret = true;
        if(viewmatrix && clipplane && visorigin)
        {
            Matrix4x4_ToVectors(viewmatrix, forward, left, up, origin);
            AnglesFromVectors(ang, forward, up, false);
            PRVM_clientglobalfloat(time) = cl.time;
            PRVM_clientglobaledict(self) = entnum;
            VectorCopy(origin, PRVM_G_VECTOR(OFS_PARM0));
            VectorCopy(ang, PRVM_G_VECTOR(OFS_PARM1));
            VectorCopy(forward, PRVM_clientglobalvector(v_forward));
            VectorScale(left, -1, PRVM_clientglobalvector(v_right));
            VectorCopy(up, PRVM_clientglobalvector(v_up));
            VectorCopy(origin, PRVM_clientglobalvector(trace_endpos));
            prog->ExecuteProgram(prog, PRVM_clientedictfunction(ed, camera_transform), "QC function e.camera_transform is missing");
            VectorCopy(PRVM_G_VECTOR(OFS_RETURN), origin);
            VectorCopy(PRVM_clientglobalvector(v_forward), forward);
            VectorScale(PRVM_clientglobalvector(v_right), -1, left);
            VectorCopy(PRVM_clientglobalvector(v_up), up);
            VectorCopy(PRVM_clientglobalvector(trace_endpos), visorigin);
            Matrix4x4_Invert_Full(&mat, viewmatrix);
            Matrix4x4_FromVectors(viewmatrix, forward, left, up, origin);
            Matrix4x4_Concat(&matq, viewmatrix, &mat);
            Matrix4x4_TransformPositivePlane(&matq, clipplane->normal[0], clipplane->normal[1], clipplane->normal[2], clipplane->dist, clipplane->normal_and_dist);
        }
    }
    return ret;
}
Referenced by R_Water_ProcessPlanes().
CL_VM_UpdateDmgGlobals()
void CL_VM_UpdateDmgGlobals (int dmg_take, int dmg_save, vec3_t dmg_origin)
Definition at line 216 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    if(prog->loaded)
    {
        PRVM_clientglobalfloat(dmg_take) = dmg_take;
        PRVM_clientglobalfloat(dmg_save) = dmg_save;
        VectorCopy(dmg_origin, PRVM_clientglobalvector(dmg_origin));
    }
}
Referenced by CL_VM_UpdateView(), and V_ParseDamage().
CL_VM_UpdateIntermissionState()
void CL_VM_UpdateIntermissionState (int intermission)
Definition at line 661 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    if(prog->loaded)
        PRVM_clientglobalfloat(intermission) = intermission;
}
Referenced by CL_ParseServerMessage().
CL_VM_UpdateShowingScoresState()
void CL_VM_UpdateShowingScoresState (int showingscores)
Definition at line 668 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    if(prog->loaded)
        PRVM_clientglobalfloat(sb_showscores) = showingscores;
}
Referenced by Sbar_DontShowScores_f(), and Sbar_ShowScores_f().
CSQC_AddPrintText()
void CSQC_AddPrintText (const char * msg, size_t msg_len)
Definition at line 610 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    char *start = cl.csqc_printtextbuf + cl.csqc_printtextbuf_len;
    size_t writebytes = min(msg_len + 1, MAX_INPUTLINE - cl.csqc_printtextbuf_len);
    if(prog->loaded && PRVM_clientfunction(CSQC_Parse_Print))
    {
        if(msg[msg_len - 1] != '\n' && msg[msg_len - 1] != '\r')
        {
            if(cl.csqc_printtextbuf_len + msg_len + 1 >= MAX_INPUTLINE)
            {
                CL_VM_Parse_Print(cl.csqc_printtextbuf, cl.csqc_printtextbuf_len);
                cl.csqc_printtextbuf[0] = '\0';
                cl.csqc_printtextbuf_len = 0;
            }
            else
            {
                memcpy(start, msg, writebytes);
                cl.csqc_printtextbuf_len += msg_len;
            }
            return;
        }
        memcpy(start, msg, writebytes);
        cl.csqc_printtextbuf_len += msg_len;
        CL_VM_Parse_Print(cl.csqc_printtextbuf, cl.csqc_printtextbuf_len);
        cl.csqc_printtextbuf[0] = '\0';
        cl.csqc_printtextbuf_len = 0;
    }
    else
        Con_Print(msg);
}
Referenced by CL_ParseServerMessage().
CSQC_AddRenderEdict()
qbool CSQC_AddRenderEdict (prvm_edict_t * ed, int edictnum)
Definition at line 305 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int renderflags;
    int c;
    float scale;
    entity_render_t *entrender;
    model_t *model;
    prvm_vec3_t modellight_origin;
    model = CL_GetModelFromEdict(ed);
    if (!model)
        return false;
    if (edictnum)
    {
        if (r_refdef.scene.numentities >= r_refdef.scene.maxentities)
            return false;
        entrender = cl.csqcrenderentities + edictnum;
        r_refdef.scene.entities[r_refdef.scene.numentities++] = entrender;
        entrender->entitynumber = edictnum + MAX_EDICTS;
        //entrender->shadertime = 0; // shadertime was set by spawn()
        entrender->flags = 0;
        entrender->effects = 0;
        entrender->alpha = 1;
        entrender->scale = 1;
        VectorSet(entrender->colormod, 1, 1, 1);
        VectorSet(entrender->glowmod, 1, 1, 1);
        entrender->allowdecals = true;
    }
    else
    {
        entrender = CL_NewTempEntity(0);
        if (!entrender)
            return false;
    }
    entrender->userwavefunc_param[0] = PRVM_clientedictfloat(ed, userwavefunc_param0);
    entrender->userwavefunc_param[1] = PRVM_clientedictfloat(ed, userwavefunc_param1);
    entrender->userwavefunc_param[2] = PRVM_clientedictfloat(ed, userwavefunc_param2);
    entrender->userwavefunc_param[3] = PRVM_clientedictfloat(ed, userwavefunc_param3);
    entrender->model = model;
    entrender->skinnum = (int)PRVM_clientedictfloat(ed, skin);
    entrender->effects |= entrender->model->effects;
    renderflags = (int)PRVM_clientedictfloat(ed, renderflags);
    entrender->alpha = PRVM_clientedictfloat(ed, alpha);
    entrender->scale = scale = PRVM_clientedictfloat(ed, scale);
    VectorCopy(PRVM_clientedictvector(ed, colormod), entrender->colormod);
    VectorCopy(PRVM_clientedictvector(ed, glowmod), entrender->glowmod);
    if(PRVM_clientedictfloat(ed, effects))  entrender->effects |= (int)PRVM_clientedictfloat(ed, effects);
    if (!entrender->alpha)
        entrender->alpha = 1.0f;
    if (!entrender->scale)
        entrender->scale = scale = 1.0f;
    if (!VectorLength2(entrender->colormod))
        VectorSet(entrender->colormod, 1, 1, 1);
    if (!VectorLength2(entrender->glowmod))
        VectorSet(entrender->glowmod, 1, 1, 1);
    // LadyHavoc: use the CL_GetTagMatrix function on self to ensure consistent behavior (duplicate code would be bad)
    // this also sets the custommodellight_origin for us
    CL_GetTagMatrix(prog, &entrender->matrix, ed, 0, modellight_origin);
    VectorCopy(modellight_origin, entrender->custommodellight_origin);
    // set up the animation data
    VM_GenerateFrameGroupBlend(prog, ed->priv.server->framegroupblend, ed);
    VM_FrameBlendFromFrameGroupBlend(ed->priv.server->frameblend, ed->priv.server->framegroupblend, model, cl.time);
    VM_UpdateEdictSkeleton(prog, ed, model, ed->priv.server->frameblend);
    if (PRVM_clientedictfloat(ed, shadertime)) // hack for csprogs.dat files that do not set shadertime, leaves the value at entity spawn time
        entrender->shadertime = PRVM_clientedictfloat(ed, shadertime);
    // transparent offset
    if (renderflags & RF_USETRANSPARENTOFFSET)
        entrender->transparent_offset = PRVM_clientglobalfloat(transparent_offset);
    // model light
    if (renderflags & RF_MODELLIGHT)
    {
        if (PRVM_clientedictvector(ed, modellight_ambient)) VectorCopy(PRVM_clientedictvector(ed, modellight_ambient), entrender->custommodellight_ambient); else VectorClear(entrender->custommodellight_ambient);
        if (PRVM_clientedictvector(ed, modellight_diffuse)) VectorCopy(PRVM_clientedictvector(ed, modellight_diffuse), entrender->custommodellight_diffuse); else VectorClear(entrender->custommodellight_diffuse);
        if (PRVM_clientedictvector(ed, modellight_dir))     VectorCopy(PRVM_clientedictvector(ed, modellight_dir), entrender->custommodellight_lightdir);    else VectorClear(entrender->custommodellight_lightdir);
        entrender->flags |= RENDER_CUSTOMIZEDMODELLIGHT;
    }
    if(renderflags)
    {
        if(renderflags & RF_VIEWMODEL) entrender->flags |= RENDER_VIEWMODEL | RENDER_NODEPTHTEST;
        if(renderflags & RF_EXTERNALMODEL) entrender->flags |= RENDER_EXTERIORMODEL;
        if(renderflags & RF_WORLDOBJECT) entrender->flags |= RENDER_WORLDOBJECT;
        if(renderflags & RF_DEPTHHACK) entrender->flags |= RENDER_NODEPTHTEST;
        if(renderflags & RF_ADDITIVE) entrender->flags |= RENDER_ADDITIVE;
        if(renderflags & RF_DYNAMICMODELLIGHT) entrender->flags |= RENDER_DYNAMICMODELLIGHT;
    }
    c = (int)PRVM_clientedictfloat(ed, colormap);
    if (c <= 0)
        CL_SetEntityColormapColors(entrender, -1);
    else if (c <= cl.maxclients && cl.scores != NULL)
        CL_SetEntityColormapColors(entrender, cl.scores[c-1].colors);
    else
        CL_SetEntityColormapColors(entrender, c);
    entrender->flags &= ~(RENDER_SHADOW | RENDER_LIGHT | RENDER_NOSELFSHADOW);
    // either fullbright or lit
    if(!r_fullbright.integer)
    {
        if (!(entrender->effects & EF_FULLBRIGHT) && !(renderflags & RF_FULLBRIGHT))
            entrender->flags |= RENDER_LIGHT;
    }
    // hide player shadow during intermission or nehahra movie
    if (!(entrender->effects & (EF_NOSHADOW | EF_ADDITIVE | EF_NODEPTHTEST))
     &&  (entrender->alpha >= 1)
     && !(renderflags & RF_NOSHADOW)
     && !(entrender->flags & RENDER_VIEWMODEL)
     && (!(entrender->flags & RENDER_EXTERIORMODEL) || (!cl.intermission && cls.protocol != PROTOCOL_NEHAHRAMOVIE && !cl_noplayershadow.integer)))
        entrender->flags |= RENDER_SHADOW;
    if (entrender->flags & RENDER_VIEWMODEL)
        entrender->flags |= RENDER_NOSELFSHADOW;
    if (entrender->effects & EF_NOSELFSHADOW)
        entrender->flags |= RENDER_NOSELFSHADOW;
    if (entrender->effects & EF_NODEPTHTEST)
        entrender->flags |= RENDER_NODEPTHTEST;
    if (entrender->effects & EF_ADDITIVE)
        entrender->flags |= RENDER_ADDITIVE;
    if (entrender->effects & EF_DOUBLESIDED)
        entrender->flags |= RENDER_DOUBLESIDED;
    if (entrender->effects & EF_DYNAMICMODELLIGHT)
        entrender->flags |= RENDER_DYNAMICMODELLIGHT;
    // make the other useful stuff
    memcpy(entrender->framegroupblend, ed->priv.server->framegroupblend, sizeof(ed->priv.server->framegroupblend));
    CL_UpdateRenderEntity(entrender);
    // override animation data with full control
    memcpy(entrender->frameblend, ed->priv.server->frameblend, sizeof(ed->priv.server->frameblend));
    if (ed->priv.server->skeleton.relativetransforms)
        entrender->skeleton = &ed->priv.server->skeleton;
    else
        entrender->skeleton = NULL;
    return true;
}
Referenced by VM_CL_R_AddEntities(), and VM_CL_R_AddEntity().
CSQC_Predraw()
void CSQC_Predraw (prvm_edict_t * ed)
Definition at line 277 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int b;
    if(!PRVM_clientedictfunction(ed, predraw))
        return;
    b = PRVM_clientglobaledict(self);
    PRVM_clientglobaledict(self) = PRVM_EDICT_TO_PROG(ed);
    prog->ExecuteProgram(prog, PRVM_clientedictfunction(ed, predraw), "CSQC_Predraw: NULL function\n");
    PRVM_clientglobaledict(self) = b;
}
Referenced by VM_CL_R_AddEntities().
CSQC_R_RecalcView()
void CSQC_R_RecalcView (void)
Definition at line 756 of file clvm_cmds.c.
{
    extern matrix4x4_t viewmodelmatrix_nobob;
    extern matrix4x4_t viewmodelmatrix_withbob;
    Matrix4x4_CreateFromQuakeEntity(&r_refdef.view.matrix, cl.csqc_vieworigin[0], cl.csqc_vieworigin[1], cl.csqc_vieworigin[2], cl.csqc_viewangles[0], cl.csqc_viewangles[1], cl.csqc_viewangles[2], 1);
    if (v_yshearing.value > 0)
        Matrix4x4_QuakeToDuke3D(&r_refdef.view.matrix, &r_refdef.view.matrix, v_yshearing.value);
    Matrix4x4_Copy(&viewmodelmatrix_nobob, &r_refdef.view.matrix);
    Matrix4x4_ConcatScale(&viewmodelmatrix_nobob, cl_viewmodel_scale.value);
    Matrix4x4_Concat(&viewmodelmatrix_withbob, &r_refdef.view.matrix, &cl.csqc_viewmodelmatrixfromengine);
}
Referenced by CSQC_SetGlobals(), VM_CL_R_ClearScene(), VM_CL_R_SetView(), and VM_CL_V_CalcRefdef().
CSQC_ReadEntities()
void CSQC_ReadEntities (void)
Definition at line 752 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    unsigned short entnum, oldself, realentnum;
    if(!prog->loaded)
    {
        Host_Error ("CSQC_ReadEntities: CSQC is not loaded");
        return;
    }
    PRVM_clientglobalfloat(time) = cl.time;
    oldself = PRVM_clientglobaledict(self);
    while(1)
    {
        entnum = MSG_ReadShort(&cl_message);
        if(!entnum || cl_message.badread)
            break;
        realentnum = entnum & 0x7FFF;
        PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[realentnum];
        if(entnum & 0x8000)
        {
            if(PRVM_clientglobaledict(self))
            {
                prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Ent_Remove), "QC function CSQC_Ent_Remove is missing");
                cl.csqc_server2csqcentitynumber[realentnum] = 0;
            }
            else
            {
                // LadyHavoc: removing an entity that is already gone on
                // the csqc side is possible for legitimate reasons (such
                // as a repeat of the remove message), so no warning is
                // needed
                //Con_Printf("Bad csqc_server2csqcentitynumber map\n"); //[515]: never happens ?
            }
        }
        else
        {
            if(!PRVM_clientglobaledict(self))
            {
                if(!PRVM_clientfunction(CSQC_Ent_Spawn))
                {
                    prvm_edict_t    *ed;
                    ed = PRVM_ED_Alloc(prog);
                    PRVM_clientedictfloat(ed, entnum) = realentnum;
                    PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[realentnum] = PRVM_EDICT_TO_PROG(ed);
                }
                else
                {
                    // entity( float entnum ) CSQC_Ent_Spawn;
                    // the qc function should set entnum, too (this way it also can return world [2/1/2008 Andreas]
                    PRVM_G_FLOAT(OFS_PARM0) = (float) realentnum;
                    // make sure no one gets wrong ideas
                    PRVM_clientglobaledict(self) = 0;
                    prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Ent_Spawn), "QC function CSQC_Ent_Spawn is missing");
                    PRVM_clientglobaledict(self) = cl.csqc_server2csqcentitynumber[realentnum] = PRVM_EDICT( PRVM_G_INT( OFS_RETURN ) );
                }
                PRVM_G_FLOAT(OFS_PARM0) = 1;
                prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Ent_Update), "QC function CSQC_Ent_Update is missing");
            }
            else {
                PRVM_G_FLOAT(OFS_PARM0) = 0;
                prog->ExecuteProgram(prog, PRVM_clientfunction(CSQC_Ent_Update), "QC function CSQC_Ent_Update is missing");
            }
        }
    }
    PRVM_clientglobaledict(self) = oldself;
}
Referenced by CL_ParseServerMessage().
CSQC_RelinkAllEntities()
void CSQC_RelinkAllEntities (int drawmask)
Definition at line 2023 of file cl_main.c.
{
    // link stuff
    CL_RelinkWorld();
    // the scene mesh is added first for easier debugging (consistent spot in render entities list)
    CL_MeshEntities_Scene_AddRenderEntity();
    CL_RelinkStaticEntities();
    CL_RelinkBeams();
    CL_RelinkEffects();
    CL_RelinkLightFlashes();
    // link stuff
    if (drawmask & ENTMASK_ENGINE)
    {
        CL_RelinkNetworkEntities();
        if (drawmask & ENTMASK_ENGINEVIEWMODELS)
            CL_LinkNetworkEntity(&cl.viewent); // link gun model
        CL_RelinkQWNails();
    }
    // update view blend
    V_CalcViewBlend();
}
Referenced by CL_UpdateWorld(), and VM_CL_R_AddEntities().
CSQC_RelinkCSQCEntities()
void CSQC_RelinkCSQCEntities (void)
CSQC_Think()
void CSQC_Think (prvm_edict_t * ed)
Definition at line 289 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    int b;
    if(PRVM_clientedictfunction(ed, think))
    if(PRVM_clientedictfloat(ed, nextthink) && PRVM_clientedictfloat(ed, nextthink) <= PRVM_clientglobalfloat(time))
    {
        PRVM_clientedictfloat(ed, nextthink) = 0;
        b = PRVM_clientglobaledict(self);
        PRVM_clientglobaledict(self) = PRVM_EDICT_TO_PROG(ed);
        prog->ExecuteProgram(prog, PRVM_clientedictfunction(ed, think), "CSQC_Think: NULL function\n");
        PRVM_clientglobaledict(self) = b;
    }
}
Referenced by VM_CL_R_AddEntities().
CSQC_UpdateNetworkTimes()
void CSQC_UpdateNetworkTimes (double newtime, double oldtime)
Definition at line 228 of file csprogs.c.
{
    prvm_prog_t *prog = CLVM_prog;
    if(!prog->loaded)
        return;
    PRVM_clientglobalfloat(servertime) = newtime;
    PRVM_clientglobalfloat(serverprevtime) = oldtime;
    PRVM_clientglobalfloat(serverdeltatime) = newtime - oldtime;
}
Referenced by CL_NetworkTimeReceived().
MakeDownloadPacket()
qbool MakeDownloadPacket (const char * filename, unsigned char * data, size_t len, int crc, int cnt, sizebuf_t * buf, int protocol)
Definition at line 894 of file csprogs.c.
{
    int packetsize = buf->maxsize - 7; // byte short long
    int npackets = ((int)len + packetsize - 1) / (packetsize);
    char vabuf[1024];
    if(protocol == PROTOCOL_QUAKEWORLD)
        return false; // CSQC can't run in QW anyway
    SZ_Clear(buf);
    if(cnt == 0)
    {
        MSG_WriteByte(buf, svc_stufftext);
        MSG_WriteString(buf, va(vabuf, sizeof(vabuf), "\ncl_downloadbegin %lu %s\n", (unsigned long)len, filename));
        return true;
    }
    else if(cnt >= 1 && cnt <= npackets)
    {
        unsigned long thispacketoffset = (cnt - 1) * packetsize;
        int thispacketsize = (int)len - thispacketoffset;
        if(thispacketsize > packetsize)
            thispacketsize = packetsize;
        MSG_WriteByte(buf, svc_downloaddata);
        MSG_WriteLong(buf, thispacketoffset);
        MSG_WriteShort(buf, thispacketsize);
        SZ_Write(buf, data + thispacketoffset, thispacketsize);
        return true;
    }
    else if(cnt == npackets + 1)
    {
        MSG_WriteByte(buf, svc_stufftext);
        MSG_WriteString(buf, va(vabuf, sizeof(vabuf), "\ncl_downloadfinished %lu %d\n", (unsigned long)len, crc));
        return true;
    }
    return false;
}
Referenced by CL_VM_Init(), and SV_SendServerinfo().
QW_CL_StartUpload()
void QW_CL_StartUpload (unsigned char * data, int size)
Definition at line 942 of file cl_parse.c.
{
    // do nothing in demos or if not connected
    if (!cls.netcon)
        return;
    // abort existing upload if in progress
    QW_CL_StopUpload_f(cmd_local);
    Con_DPrintf("Starting upload of %d bytes...\n", size);
    cls.qw_uploaddata = (unsigned char *)Mem_Alloc(cls.permanentmempool, size);
    memcpy(cls.qw_uploaddata, data, size);
    cls.qw_uploadsize = size;
    cls.qw_uploadpos = 0;
    QW_CL_NextUpload_f(cmd_local);
}
Variable Documentation
csqc_polygons_defaultmaterial_nocullface
cvar_t csqc_polygons_defaultmaterial_nocullface extern
Definition at line 39 of file cl_main.c.
{CF_CLIENT, "csqc_polygons_defaultmaterial_nocullface", "0", "use 'cull none' behavior in the default shader for rendering R_PolygonBegin - warning: enabling this is not consistent with FTEQW behavior on this feature"};
Referenced by CL_Init(), and VM_CL_R_PolygonEnd().
csqc_progcrc
cvar_t csqc_progcrc extern
Definition at line 36 of file cl_main.c.
{CF_CLIENT | CF_READONLY, "csqc_progcrc","-1","CRC of csprogs.dat file to load (-1 is none), only used during level changes and then reset to -1"};
Referenced by CL_BeginDownloads(), CL_DisconnectEx(), CL_VM_Init(), CL_VM_Parse_StuffCmd(), and SV_Init().
csqc_progname
cvar_t csqc_progname extern
Definition at line 35 of file cl_main.c.
{CF_CLIENT | CF_SERVER, "csqc_progname","csprogs.dat","name of csprogs.dat file to load"};
Referenced by CL_BeginDownloads(), CL_StopDownload(), CL_VM_Init(), PRVM_Prog_Load(), SV_Init(), and SV_Prepare_CSQC().
csqc_progsize
cvar_t csqc_progsize extern
Definition at line 37 of file cl_main.c.
{CF_CLIENT | CF_READONLY, "csqc_progsize","-1","file size of csprogs.dat file to load (-1 is none), only used during level changes and then reset to -1"};
Referenced by CL_BeginDownloads(), CL_DisconnectEx(), CL_VM_Init(), CL_VM_Parse_StuffCmd(), and SV_Init().