DarkPlaces: cvar.h File Reference
cvar.h File Reference
#include "qtypes.h"
#include "qdefs.h"
Data Structures
struct cvar_t
struct cvar_hash_t
struct cvar_state_t
Functions
void Cvar_RegisterVirtual (cvar_t *variable, const char *name)
void Cvar_RegisterCallback (cvar_t *variable, void(*callback)(cvar_t *))
void Cvar_RegisterVariable (cvar_t *variable)
registers a cvar that already has the name, string, and optionally the archive elements set.
qbool Cvar_Readonly (cvar_t *var, const char *cmd_name)
void Cvar_Callback (cvar_t *var)
void Cvar_Set (cvar_state_t *cvars, const char *var_name, const char *value)
equivelant to "<name> <variable>" typed at the console
void Cvar_SetValue (cvar_state_t *cvars, const char *var_name, float value)
expands value to a string and calls Cvar_Set
void Cvar_SetQuick (cvar_t *var, const char *value)
void Cvar_SetValueQuick (cvar_t *var, float value)
float Cvar_VariableValueOr (cvar_state_t *cvars, const char *var_name, float def, unsigned neededflags)
float Cvar_VariableValue (cvar_state_t *cvars, const char *var_name, unsigned neededflags)
const char * Cvar_VariableStringOr (cvar_state_t *cvars, const char *var_name, const char *def, unsigned neededflags)
const char * Cvar_VariableString (cvar_state_t *cvars, const char *var_name, unsigned neededflags)
const char * Cvar_VariableDefString (cvar_state_t *cvars, const char *var_name, unsigned neededflags)
const char * Cvar_VariableDescription (cvar_state_t *cvars, const char *var_name, unsigned neededflags)
const char * Cvar_CompleteVariable (cvar_state_t *cvars, const char *partial, unsigned neededflags)
void Cvar_PrintHelp (cvar_t *cvar, const char *name, qbool full)
void Cvar_CompleteCvarPrint (cvar_state_t *cvars, const char *partial, unsigned neededflags)
qbool Cvar_Command (struct cmd_state_s *cmd)
void Cvar_SaveInitState (cvar_state_t *cvars)
void Cvar_RestoreInitState (cvar_state_t *cvars)
void Cvar_UnlockDefaults (struct cmd_state_s *cmd)
void Cvar_LockDefaults_f (struct cmd_state_s *cmd)
void Cvar_ResetToDefaults_All_f (struct cmd_state_s *cmd)
void Cvar_ResetToDefaults_NoSaveOnly_f (struct cmd_state_s *cmd)
void Cvar_ResetToDefaults_SaveOnly_f (struct cmd_state_s *cmd)
void Cvar_WriteVariables (cvar_state_t *cvars, struct qfile_s *f)
cvar_t * Cvar_FindVar (cvar_state_t *cvars, const char *var_name, unsigned neededflags)
cvar_t * Cvar_FindVarAfter (cvar_state_t *cvars, const char *prev_var_name, unsigned neededflags)
int Cvar_CompleteCountPossible (cvar_state_t *cvars, const char *partial, unsigned neededflags)
const char ** Cvar_CompleteBuildList (cvar_state_t *cvars, const char *partial, unsigned neededflags)
void Cvar_List_f (struct cmd_state_s *cmd)
Prints a list of Cvars including a count of them to the user console Referenced in cmd.c in Cmd_Init hence it's inclusion here.
void Cvar_Set_f (struct cmd_state_s *cmd)
void Cvar_SetA_f (struct cmd_state_s *cmd)
void Cvar_Del_f (struct cmd_state_s *cmd)
cvar_t * Cvar_Get (cvar_state_t *cvars, const char *name, const char *value, unsigned flags, const char *newdescription)
allocates a cvar by name and returns its address, or merely sets its value if it already exists.
void Cvar_UpdateAllAutoCvars (cvar_state_t *cvars)
called after loading a savegame
Variables
cvar_state_t cvars_all
cvar_state_t cvars_null
const char * cvar_dummy_description
Function Documentation
Cvar_Callback()
void Cvar_Callback (cvar_t * var)
Definition at line 372 of file cvar.c.
{
    if (var == NULL)
    {
        Con_Print(CON_WARN "Cvar_Callback: var == NULL\n");
        return;
    }
    if(var->callback)
        var->callback(var);
}
Referenced by CL_DisconnectEx(), CL_FinishTimeDemo(), CL_Init(), CL_TimeDemo_f(), Cvar_SetQuick_Internal(), SV_Init(), and VID_InitModeGL().
Cvar_Command()
qbool Cvar_Command (struct cmd_state_s * cmd)
Cvar_CompleteBuildList()
const char ** Cvar_CompleteBuildList (cvar_state_t * cvars, const char * partial, unsigned neededflags)
Definition at line 250 of file cvar.c.
{
    const cvar_t *cvar;
    size_t len = 0;
    size_t bpos = 0;
    size_t sizeofbuf = (Cvar_CompleteCountPossible(cvars, partial, neededflags) + 1) * sizeof(const char *);
    const char **buf;
    len = strlen(partial);
    buf = (const char **)Mem_Alloc(tempmempool, sizeofbuf + sizeof(const char *));
    // Loop through the alias list and print all matches
    for (cvar = cvars->vars; cvar; cvar = cvar->next)
        if (!strncasecmp(partial, cvar->name, len) && (cvar->flags & neededflags))
            buf[bpos++] = cvar->name;
        else
            for (char **alias = cvar->aliases; alias && *alias; alias++)
                if (!strncasecmp(partial, *alias, len) && (cvar->flags & neededflags))
                    buf[bpos++] = *alias;
    buf[bpos] = NULL;
    return buf;
}
Referenced by Con_CompleteCommandLine().
Cvar_CompleteCountPossible()
int Cvar_CompleteCountPossible (cvar_state_t * cvars, const char * partial, unsigned neededflags)
Definition at line 217 of file cvar.c.
{
    cvar_t  *cvar;
    size_t  len;
    int     h;
    h = 0;
    len = strlen(partial);
    if (!len)
        return  0;
    // Loop through the cvars and count all possible matches
    for (cvar = cvars->vars; cvar; cvar = cvar->next)
        if (!strncasecmp(partial, cvar->name, len) && (cvar->flags & neededflags))
            h++;
        else
            for (char **alias = cvar->aliases; alias && *alias; alias++)
                if (!strncasecmp(partial, *alias, len) && (cvar->flags & neededflags))
                    h++;
    return h;
}
Referenced by Con_CompleteCommandLine(), and Cvar_CompleteBuildList().
Cvar_CompleteCvarPrint()
void Cvar_CompleteCvarPrint (cvar_state_t * cvars, const char * partial, unsigned neededflags)
Definition at line 288 of file cvar.c.
{
    cvar_t *cvar;
    size_t len = strlen(partial);
    // Loop through the command list and print all matches
    for (cvar = cvars->vars; cvar; cvar = cvar->next)
        if (!strncasecmp(partial, cvar->name, len) && (cvar->flags & neededflags))
            Cvar_PrintHelp(cvar, cvar->name, true);
        else
            for (char **alias = cvar->aliases; alias && *alias; alias++)
                if (!strncasecmp (partial, *alias, len) && (cvar->flags & neededflags))
                    Cvar_PrintHelp(cvar, *alias, true);
}
Referenced by Con_CompleteCommandLine().
Cvar_CompleteVariable()
const char * Cvar_CompleteVariable (cvar_state_t * cvars, const char * partial, unsigned neededflags)
Definition at line 190 of file cvar.c.
{
    cvar_t      *cvar;
    size_t      len;
    len = strlen(partial);
    if (!len)
        return NULL;
// check functions
    for (cvar=cvars->vars ; cvar ; cvar=cvar->next)
        if (!strncasecmp (partial,cvar->name, len) && (cvar->flags & neededflags))
            return cvar->name;
    return NULL;
}
Cvar_Del_f()
void Cvar_Del_f (struct cmd_state_s * cmd)
Cvar_FindVar()
cvar_t * Cvar_FindVar (cvar_state_t * cvars, const char * var_name, unsigned neededflags)
Definition at line 36 of file cvar.c.
{
    unsigned hashindex;
    cvar_hash_t *hash;
    // use hash lookup to minimize search time
    hashindex = CRC_Block((const unsigned char *)var_name, strlen(var_name)) % CVAR_HASHSIZE;
    for (hash = cvars->hashtable[hashindex];hash;hash = hash->next)
        if (!strcmp (var_name, hash->cvar->name) && (hash->cvar->flags & neededflags))
            return hash->cvar;
        else
            for (char **alias = hash->cvar->aliases; alias && *alias; alias++)
                if (!strcmp (var_name, *alias) && (hash->cvar->flags & neededflags))
                    return hash->cvar;
    return NULL;
}
Referenced by CL_SendCvar_f(), Cmd_AddCommand(), Cmd_GetDirectCvarValue(), Cmd_Toggle_f(), Cvar_Command(), Cvar_FindVarAfter(), Cvar_Get(), Cvar_RegisterVariable(), Cvar_RegisterVirtual(), Cvar_Set(), Cvar_Set_f(), Cvar_SetA_f(), Cvar_VariableDefString(), Cvar_VariableDescription(), Cvar_VariableStringOr(), Cvar_VariableValueOr(), LoadSubtitles(), PRVM_Cvar_ReadOk(), PRVM_ED_EdictGet_f(), PRVM_ED_GlobalGet_f(), PRVM_Prog_Load(), VID_InitMode(), VM_cvar_set(), VM_cvar_type(), and VM_registercvar().
Cvar_FindVarAfter()
cvar_t * Cvar_FindVarAfter (cvar_state_t * cvars, const char * prev_var_name, unsigned neededflags)
Definition at line 53 of file cvar.c.
{
    cvar_t *var;
    if (*prev_var_name)
    {
        var = Cvar_FindVar(cvars, prev_var_name, neededflags);
        if (!var)
            return NULL;
        var = var->next;
    }
    else
        var = cvars->vars;
    // search for the next cvar matching the needed flags
    while (var)
    {
        if (var->flags & neededflags)
            break;
        var = var->next;
    }
    return var;
}
Referenced by NetConn_ServerParsePacket().
Cvar_Get()
cvar_t * Cvar_Get (cvar_state_t * cvars, const char * name, const char * value, unsigned flags, const char * newdescription)
allocates a cvar by name and returns its address, or merely sets its value if it already exists.
Definition at line 695 of file cvar.c.
{
    cvar_t *cvar;
    int i;
    if (developer_extra.integer)
        Con_DPrintf("Cvar_Get(\"%s\", \"%s\", %i);\n", name, value, flags);
    // first check to see if it has already been defined
    cvar = Cvar_FindVar(cvars, name, ~0);
    if (cvar)
    {
        cvar->flags |= flags;
        Cvar_SetQuick_Internal (cvar, value);
        if(newdescription && (cvar->flags & CF_ALLOCATED))
        {
            if(cvar->description != cvar_dummy_description)
                Z_Free((char *)cvar->description);
            if(*newdescription)
                cvar->description = Z_strdup(newdescription);
            else
                cvar->description = cvar_dummy_description;
        }
        return cvar;
    }
    // check for pure evil
    if (!*name)
    {
        Con_Printf(CON_WARN "Cvar_Get: invalid variable name\n");
        return NULL;
    }
    // check for overlap with a command
    if (Cmd_Exists(cmd_local, name))
    {
        Con_Printf(CON_WARN "Cvar_Get: %s is a command\n", name);
        return NULL;
    }
    // allocate a new cvar, cvar name, and cvar string
    // TODO: factorize the following code with the one at the end of Cvar_RegisterVariable()
    // FIXME: these never get Z_Free'd
    cvar = (cvar_t *)Z_Malloc(sizeof(cvar_t));
    cvar->flags = flags | CF_ALLOCATED;
    cvar->name = Z_strdup(name);
    cvar->string = Z_strdup(value);
    cvar->defstring = Z_strdup(value);
    cvar->value = atof (cvar->string);
    cvar->integer = (int) cvar->value;
    cvar->aliases = NULL;
    cvar->aliases_size = 0;
    cvar->initstring = NULL;
    if(newdescription && *newdescription)
        cvar->description = Z_strdup(newdescription);
    else
        cvar->description = cvar_dummy_description; // actually checked by VM_cvar_type
    // Mark it as not an autocvar.
    for (i = 0;i < PRVM_PROG_MAX;i++)
        cvar->globaldefindex[i] = -1;
    Cvar_Link(cvar, cvars);
    return cvar;
}
Referenced by Cvar_Set_f(), Cvar_SetA_f(), Mod_VBSP_Load(), PRVM_ED_EdictGet_f(), PRVM_ED_GlobalGet_f(), PRVM_Prog_Load(), and VM_registercvar().
Cvar_List_f()
void Cvar_List_f (struct cmd_state_s * cmd)
Prints a list of Cvars including a count of them to the user console Referenced in cmd.c in Cmd_Init hence it's inclusion here.
Added by EvilTypeGuy evilt.nosp@m.ypeg.nosp@m.uy@qe.nosp@m.radi.nosp@m.ant.c.nosp@m.om Thanks to Matthias "Maddes" Buecher, http://www.inside3d.com/qip/
Cvar_LockDefaults_f()
void Cvar_LockDefaults_f (struct cmd_state_s * cmd)
Cvar_PrintHelp()
void Cvar_PrintHelp (cvar_t * cvar, const char * name, qbool full)
Definition at line 274 of file cvar.c.
{
    // Aliases are purple, cvars are yellow
    if (strcmp(cvar->name, name))
        Con_Printf("^6%s^7 (alias of ^3%s^7)", name, cvar->name);
    else
        Con_Printf("^3%s^7", name);
    Con_Printf(" is \"%s^7\" [\"%s^7\"]", ((cvar->flags & CF_PRIVATE) ? "********"/*hunter2*/ : cvar->string), cvar->defstring);
    if (full)
        Con_Printf(" %s", cvar->description);
    Con_Print("\n");
}
Referenced by Cmd_Apropos_f(), Cvar_Command(), Cvar_CompleteCvarPrint(), and Cvar_List_f().
Cvar_Readonly()
qbool Cvar_Readonly (cvar_t * var, const char * cmd_name)
Definition at line 813 of file cvar.c.
{
    if (var->flags & CF_READONLY)
    {
        Con_Print(CON_WARN);
        if(cmd_name)
            Con_Printf("%s: ",cmd_name);
        Con_Printf("%s is read-only\n", var->name);
        return true;
    }
    return false;
}
Referenced by Cvar_Command(), Cvar_Set_f(), Cvar_SetA_f(), PRVM_ED_EdictGet_f(), and PRVM_ED_GlobalGet_f().
Cvar_RegisterCallback()
void Cvar_RegisterCallback (cvar_t * variable, void(*)(cvar_t *) callback)
Definition at line 495 of file cvar.c.
{
    if (variable == NULL)
    {
        Con_Print(CON_WARN "Cvar_RegisterCallback: var == NULL\n");
        return;
    }
    if (!(variable->flags & cmd_local->cvars_flagsmask))
    {
        if (developer_extra.integer)
            Con_DPrintf("^6Cvar_RegisterCallback: rejecting cvar \"%s\"\n", variable->name);
        return;
    }
    variable->callback = callback;
}
Referenced by CL_InitCommands(), Con_Init(), Host_InitLocal(), NetConn_Init(), SV_Init(), SV_InitOperatorCommands(), Sys_Init_Commands(), and VID_Init().
Cvar_RegisterVariable()
void Cvar_RegisterVariable (cvar_t * variable)
registers a cvar that already has the name, string, and optionally the archive elements set.
Definition at line 599 of file cvar.c.
{
    cvar_state_t *cvars = &cvars_all;
    cvar_t *current, *cvar;
    int i;
    if (!(variable->flags & cmd_local->cvars_flagsmask))
    {
        if (developer_extra.integer)
            Con_DPrintf("^2Cvar_RegisterVariable: rejecting cvar \"%s\"\n", variable->name);
        return;
    }
    if (developer_extra.integer)
        Con_DPrintf("Cvar_RegisterVariable({\"%s\", \"%s\", %i});\n", variable->name, variable->string, variable->flags);
    // first check to see if it has already been defined
    cvar = Cvar_FindVar(cvars, variable->name, ~0);
    if (cvar)
    {
        if (cvar->flags & CF_ALLOCATED)
        {
            if (developer_extra.integer)
                Con_DPrintf("...  replacing existing allocated cvar {\"%s\", \"%s\", %i}\n", cvar->name, cvar->string, cvar->flags);
            // fixed variables replace allocated ones
            // (because the engine directly accesses fixed variables)
            // NOTE: this isn't actually used currently
            // (all cvars are registered before config parsing)
            variable->flags &= ~CF_ALLOCATED;
            // cvar->string is now owned by variable instead
            variable->string = cvar->string;
            variable->defstring = cvar->defstring;
            variable->value = atof (variable->string);
            variable->integer = (int) variable->value;
            // Preserve autocvar status.
            memcpy(variable->globaldefindex, cvar->globaldefindex, sizeof(variable->globaldefindex));
            memcpy(variable->globaldefindex_stringno, cvar->globaldefindex_stringno, sizeof(variable->globaldefindex_stringno));
            // replace cvar with this one...
            variable->next = cvar->next;
            if (cvars->vars == cvar)
            {
                // head of the list is easy to change
                cvars->vars = variable;
            }
            else
            {
                // otherwise find it somewhere in the list
                for (current = cvars->vars;current->next != cvar;current = current->next)
                    ;
                current->next = variable;
            }
            // get rid of old allocated cvar
            // (but not cvar->string and cvar->defstring, because we kept those)
            Z_Free((char *)cvar->name);
            Z_Free(cvar);
        }
        else
            Con_DPrintf("Can't register variable %s, already defined\n", variable->name);
        return;
    }
    // check for overlap with a command
    if (Cmd_Exists(cmd_local, variable->name))
    {
        Con_Printf(CON_WARN "Cvar_RegisterVariable: %s is a command\n", variable->name);
        return;
    }
    // copy the value off, because future sets will Z_Free it
    variable->name = Z_strdup(variable->name);
    variable->string = Z_strdup(variable->string);
    variable->defstring = Z_strdup(variable->string);
    variable->value = atof (variable->string);
    variable->integer = (int) variable->value;
    variable->aliases = NULL;
    variable->aliases_size = 0;
    variable->initstring = NULL;
    // Mark it as not an autocvar.
    for (i = 0;i < PRVM_PROG_MAX;i++)
        variable->globaldefindex[i] = -1;
    // Safe for Cvar_SetQuick()
    variable->flags |= CF_REGISTERED;
    Cvar_Link(variable, cvars);
}
Referenced by CDAudio_Init(), CL_Demo_Init(), CL_Init(), CL_InitCommands(), CL_InitInput(), CL_Parse_Init(), CL_Particles_Init(), CL_Screen_Init(), CL_Video_Init(), Collision_Init(), COM_Init_Commands(), Con_Init(), Crypto_Init_Commands(), Curl_Init_Commands(), Font_Init(), FS_Init_Commands(), gl_backend_init(), GL_Draw_Init(), GL_Main_Init(), GL_Surf_Init(), Host_InitLocal(), Host_InitSession(), Key_Init(), LibAvW_OpenLibrary(), Memory_Init_Commands(), Mod_AliasInit(), Mod_BrushInit(), Mod_Init(), Mod_SpriteInit(), MR_Init_Commands(), NetConn_Init(), Palette_Init(), PRVM_Init(), R_Explosion_Init(), R_LightningBeams_Init(), R_Particles_Init(), R_Shadow_EditLights_Init(), R_Shadow_Init(), R_Sky_Init(), R_Textures_Init(), S_Init(), Sbar_Init(), SCR_CaptureVideo_Ogg_Init(), SV_Init(), SV_InitOperatorCommands(), Sys_Init_Commands(), TaskQueue_Init(), u8_Init(), V_Init(), VID_Init(), and VID_Shared_Init().
Cvar_RegisterVirtual()
void Cvar_RegisterVirtual (cvar_t * variable, const char * name)
Definition at line 513 of file cvar.c.
{
    cvar_state_t *cvars = &cvars_all;
    cvar_hash_t *hash;
    unsigned hashindex;
    if (!(variable->flags & cmd_local->cvars_flagsmask))
    {
        if (developer_extra.integer)
            Con_DPrintf("^6Cvar_RegisterVirtual: rejecting cvar \"%s\" alias \"%s\"\n", variable->name, name);
        return;
    }
    if(!*name)
    {
        Con_Printf(CON_WARN "Cvar_RegisterVirtual: invalid virtual cvar name\n");
        return;
    }
    // check for overlap with a command
    if (Cmd_Exists(cmd_local, name))
    {
        Con_Printf(CON_WARN "Cvar_RegisterVirtual: %s is a command\n", name);
        return;
    }
    if(Cvar_FindVar(&cvars_all, name, 0))
    {
        Con_Printf(CON_WARN "Cvar_RegisterVirtual: %s is a cvar\n", name);
        return;
    }
    // Resize the variable->aliases list to have room for another entry and a null terminator.
    // This zero-pads when resizing, so we don't need to write the NULL terminator manually here.
    // Also if aliases is NULL this allocates fresh for the correct size, so it's fine to just do this.
    variable->aliases = (char **)Z_Realloc(variable->aliases, sizeof(char *) * (variable->aliases_size + 2));
    // Add the new alias, and increment the number of aliases in the list
    variable->aliases[variable->aliases_size++] = Z_strdup(name);
    // link to head of list in this hash table index
    hash = (cvar_hash_t *)Z_Malloc(sizeof(cvar_hash_t));
    hashindex = CRC_Block((const unsigned char *)name, strlen(name)) % CVAR_HASHSIZE;
    hash->next = cvars->hashtable[hashindex];
    cvars->hashtable[hashindex] = hash;
    hash->cvar = variable;
}
Referenced by CL_InitCommands(), CL_Screen_Init(), COM_Init_Commands(), Curl_Init_Commands(), NetConn_Init(), Sbar_Init(), and SV_Init().
Cvar_ResetToDefaults_All_f()
void Cvar_ResetToDefaults_All_f (struct cmd_state_s * cmd)
Cvar_ResetToDefaults_NoSaveOnly_f()
void Cvar_ResetToDefaults_NoSaveOnly_f (struct cmd_state_s * cmd)
Cvar_ResetToDefaults_SaveOnly_f()
void Cvar_ResetToDefaults_SaveOnly_f (struct cmd_state_s * cmd)
Cvar_RestoreInitState()
void Cvar_RestoreInitState (cvar_state_t * cvars)
Definition at line 901 of file cvar.c.
{
    cvar_t *c, *cp;
    for (cp = cvars->vars; (c = cp);)
    {
        cp = c->next; // get next cvar now in case we delete this cvar
        if (c->initstring)
        {
            // restore this cvar, it existed at init
            Con_DPrintf("Cvar_RestoreInitState: Restoring cvar \"%s\"\n", c->name);
            /* bones_was_here: intentionally NOT restoring defstring in this function.
             * The only callsite, Host_LoadConfig_f, will re-exec quake.rc, default.cfg, etc.
             * Defaults are unlocked here, so Cvar_LockDefaults_f will reset the defstring.
             * This is more correct than restoring the defstring here
             * because a gamedir change could load configs that should change defaults.
             */
            Cvar_SetQuick(c, c->initstring);
            c->flags &= ~CF_DEFAULTSET;
        }
        else if (!(c->flags & (CF_PERSISTENT | CF_READONLY))) // cvars with those flags have no initstring AND may not be deleted or reset
        {
            // remove this cvar, it did not exist at init
            Con_DPrintf("Cvar_RestoreInitState: cvar \"%s\"", c->name);
            if (Cvar_Delete(cvars, c->name, NULL))
                Con_DPrint("deleted.\n");
            else
            {
                // In this case, at least reset it to the default.
                Con_DPrint("reset.\n");
                Cvar_SetQuick(c, c->defstring);
            }
        }
    }
}
Referenced by Cmd_RestoreInitState().
Cvar_SaveInitState()
void Cvar_SaveInitState (cvar_state_t * cvars)
Definition at line 892 of file cvar.c.
{
    cvar_t *c;
    for (c = cvars->vars;c;c = c->next)
        if ((c->flags & (CF_PERSISTENT | CF_READONLY)) == 0)
            c->initstring = Z_strdup(c->string);
}
Referenced by Cmd_SaveInitState().
Cvar_Set()
void Cvar_Set (cvar_state_t * cvars, const char * var_name, const char * value)
equivelant to "<name> <variable>" typed at the console
Definition at line 456 of file cvar.c.
{
    cvar_t *var;
    var = Cvar_FindVar(cvars, var_name, ~0);
    if (var == NULL)
    {
        Con_Printf(CON_WARN "Cvar_Set: variable %s not found\n", var_name);
        return;
    }
    Cvar_SetQuick(var, value);
}
Referenced by CL_StopPlayback(), Cvar_SetValue(), FOG_clear(), M_GameOptions_Key(), SV_Map_f(), and SV_MaxPlayers_f().
Cvar_Set_f()
void Cvar_Set_f (struct cmd_state_s * cmd)
Cvar_SetA_f()
void Cvar_SetA_f (struct cmd_state_s * cmd)
Cvar_SetQuick()
void Cvar_SetQuick (cvar_t * var, const char * value)
Definition at line 436 of file cvar.c.
{
    if (var == NULL)
    {
        Con_Print(CON_WARN "Cvar_SetQuick: var == NULL\n");
        return;
    }
    if (!(var->flags & CF_REGISTERED) && !(var->flags & CF_ALLOCATED))
    {
        Con_Printf(CON_WARN "Warning: Cvar_SetQuick() cannot set unregistered cvar \"%s\"\n", var->name);
        return; // setting an unregistered engine cvar crashes
    }
    if (developer_extra.integer)
        Con_DPrintf("Cvar_SetQuick({\"%s\", \"%s\", %i, \"%s\"}, \"%s\");\n", var->name, var->string, var->flags, var->defstring, value);
    Cvar_SetQuick_Internal(var, value);
}
Referenced by CL_Bottomcolor_c(), CL_Color_c(), CL_Connect_f(), CL_Name_f(), CL_NetworkTimeReceived(), CL_ParseServerInfo(), CL_Screen_Init(), CL_SetupWorldModel(), CL_Topcolor_c(), Cmd_Toggle_f(), COM_Init_Commands(), Con_Init(), Con_RCon_ClearPassword_c(), Cvar_Command(), Cvar_ResetToDefaults_All_f(), Cvar_ResetToDefaults_NoSaveOnly_f(), Cvar_ResetToDefaults_SaveOnly_f(), Cvar_RestoreInitState(), Cvar_Set(), Cvar_SetValueQuick(), FS_Rescan(), GL_CheckExtension(), GL_Setup(), Host_InitSession(), Mod_BrushInit(), NetConn_Init(), R_Shadow_EditLights_DrawSelectedLightProperties(), SV_SpawnServer(), VID_ClearExtensions(), VID_InitModeGL(), VID_Start(), and VM_cvar_set().
Cvar_SetValue()
void Cvar_SetValue (cvar_state_t * cvars, const char * var_name, float value)
expands value to a string and calls Cvar_Set
Definition at line 484 of file cvar.c.
{
    char val[MAX_INPUTLINE];
    if ((float)((int)value) == value)
        dpsnprintf(val, sizeof(val), "%i", (int)value);
    else
        dpsnprintf(val, sizeof(val), "%f", value);
    Cvar_Set(cvars, var_name, val);
}
Referenced by GL_Main_Init(), M_GameOptions_Draw(), M_LanConfig_Key(), SV_Loadgame_f(), and SV_ServerOptions().
Cvar_SetValueQuick()
void Cvar_SetValueQuick (cvar_t * var, float value)
Definition at line 473 of file cvar.c.
{
    char val[MAX_INPUTLINE];
    if ((float)((int)value) == value)
        dpsnprintf(val, sizeof(val), "%i", (int)value);
    else
        dpsnprintf(val, sizeof(val), "%f", value);
    Cvar_SetQuick(var, val);
}
Referenced by CDAudio_Init(), CDAudio_StartPlaylist(), CDAudio_StopPlaylistTrack(), CL_Beams_SetupExternalTexture(), CL_BeginDownloads(), CL_Color_f(), CL_DisconnectEx(), CL_DrawVideo(), CL_Init(), CL_ParseServerInfo(), CL_UpdateScreen(), CL_VM_Init(), Cmd_Toggle_f(), Con_CheckResize(), Con_DrawNotify(), FS_Rescan(), GL_Main_Init(), GL_SetupTextureParameters(), Host_Framerate_c(), Host_Timescale_c(), Key_Console(), M_Menu_Options_AdjustSliders(), M_Menu_Options_ColorControl_AdjustSliders(), M_Menu_Options_Effects_AdjustSliders(), M_Menu_Options_Graphics_AdjustSliders(), M_Menu_Video_AdjustSliders(), M_NetStart_Change(), M_Options_ColorControl_Key(), M_Video_Key(), Memory_Init_Commands(), MR_Init(), NetConn_Heartbeat(), NetConn_Init(), NetConn_OpenClientPorts(), NetConn_OpenServerPorts(), R_Bloom_StartFrame(), R_BufferData_Resize(), R_FrameData_Alloc(), R_HDR_UpdateIrisAdaptation(), R_Mesh_Start(), R_MeshQueue_RenderTransparent(), R_Shadow_DrawModelShadowMaps(), R_Shadow_EditLights_DrawSelectedLightProperties(), R_Textures_Frame(), r_textures_start(), R_TimeReport_EndFrame(), R_UpdateVariables(), R_Water_ProcessPlanes(), S_Init(), S_SetChannelLayout(), S_Startup(), S_Terminate(), SCR_SizeDown_f(), SCR_SizeUp_f(), SCR_UpdateVars(), SndSys_Init(), SndSys_Init(), SV_SendClientDatagram(), SV_ServerOptions(), SV_SpawnServer(), Sys_DirtyTime(), Sys_SDL_HandleEvents(), VID_EnableJoystick(), VID_Init(), VID_InitMode(), VID_InitModeGL(), VID_Restart_f(), VID_SetMouse(), VID_Shared_SetJoystick(), and VID_Start().
Cvar_UnlockDefaults()
void Cvar_UnlockDefaults (struct cmd_state_s * cmd)
Cvar_UpdateAllAutoCvars()
void Cvar_UpdateAllAutoCvars (cvar_state_t * cvars)
called after loading a savegame
Definition at line 365 of file cvar.c.
{
    cvar_t *var;
    for (var = cvars->vars ; var ; var = var->next)
        Cvar_UpdateAutoCvar(var);
}
Referenced by SV_Loadgame_f().
Cvar_VariableDefString()
const char * Cvar_VariableDefString (cvar_state_t * cvars, const char * var_name, unsigned neededflags)
Definition at line 159 of file cvar.c.
{
    cvar_t *var;
    var = Cvar_FindVar(cvars, var_name, neededflags);
    if (!var)
        return cvar_null_string;
    return var->defstring;
}
Referenced by Key_Console(), and VM_cvar_defstring().
Cvar_VariableDescription()
const char * Cvar_VariableDescription (cvar_state_t * cvars, const char * var_name, unsigned neededflags)
Definition at line 174 of file cvar.c.
{
    cvar_t *var;
    var = Cvar_FindVar(cvars, var_name, neededflags);
    if (!var)
        return cvar_null_string;
    return var->description;
}
Referenced by VM_cvar_description().
Cvar_VariableString()
const char * Cvar_VariableString (cvar_state_t * cvars, const char * var_name, unsigned neededflags)
Definition at line 149 of file cvar.c.
{
    return Cvar_VariableStringOr(cvars, var_name, cvar_null_string, neededflags);
}
Referenced by Con_CompleteCommandLine(), Key_Parse_CommonKeys(), SV_Status_f(), and VM_cvar_string().
Cvar_VariableStringOr()
const char * Cvar_VariableStringOr (cvar_state_t * cvars, const char * var_name, const char * def, unsigned neededflags)
Definition at line 139 of file cvar.c.
{
    cvar_t *var;
    var = Cvar_FindVar(cvars, var_name, neededflags);
    if (!var)
        return def;
    return var->string;
}
Referenced by Cvar_VariableString().
Cvar_VariableValue()
float Cvar_VariableValue (cvar_state_t * cvars, const char * var_name, unsigned neededflags)
Definition at line 129 of file cvar.c.
{
    return Cvar_VariableValueOr(cvars, var_name, 0, neededflags);
}
Referenced by Mod_LoadQ3Shaders(), and VM_cvar().
Cvar_VariableValueOr()
float Cvar_VariableValueOr (cvar_state_t * cvars, const char * var_name, float def, unsigned neededflags)
Definition at line 119 of file cvar.c.
{
    cvar_t *var;
    var = Cvar_FindVar(cvars, var_name, neededflags);
    if (!var)
        return def;
    return atof (var->string);
}
Referenced by Cvar_VariableValue(), and SND_Spatialize_WithSfx().
Cvar_WriteVariables()
void Cvar_WriteVariables (cvar_state_t * cvars, struct qfile_s * f)
Variable Documentation
cvar_dummy_description
const char* cvar_dummy_description extern
Definition at line 25 of file cvar.c.
Referenced by Cvar_Delete(), Cvar_Get(), and VM_cvar_type().
cvars_all
cvar_state_t cvars_all extern
Definition at line 28 of file cvar.c.
Referenced by CL_SendCvar_f(), CL_StopPlayback(), Cmd_Init(), Cmd_RestoreInitState(), Cmd_SaveInitState(), Cvar_RegisterVariable(), Cvar_RegisterVirtual(), FOG_clear(), GL_Main_Init(), Host_SaveConfig(), Key_Console(), Key_Parse_CommonKeys(), LoadSubtitles(), M_GameOptions_Draw(), M_GameOptions_Key(), M_LanConfig_Key(), Mod_LoadQ3Shaders(), Mod_VBSP_Load(), NetConn_ServerParsePacket(), SND_Spatialize_WithSfx(), SV_Loadgame_f(), SV_Map_f(), SV_MaxPlayers_f(), SV_ServerOptions(), SV_Status_f(), and VID_InitMode().
cvars_null
cvar_state_t cvars_null extern
Definition at line 29 of file cvar.c.
Referenced by Cmd_Init().