DarkPlaces: dpvsimpledecode.h File Reference
dpvsimpledecode.h File Reference
#include "qtypes.h"
#include "qdefs.h"
#include "cvar.h"
#include "cl_video.h"
#include "draw.h"
Macros
#define DPVSIMPLEDECODEERROR_NONE 0
#define DPVSIMPLEDECODEERROR_EOF 1
#define DPVSIMPLEDECODEERROR_READERROR 2
#define DPVSIMPLEDECODEERROR_SOUNDBUFFERTOOSMALL 3
#define DPVSIMPLEDECODEERROR_INVALIDRMASK 4
#define DPVSIMPLEDECODEERROR_INVALIDGMASK 5
#define DPVSIMPLEDECODEERROR_INVALIDBMASK 6
#define DPVSIMPLEDECODEERROR_COLORMASKSOVERLAP 7
#define DPVSIMPLEDECODEERROR_COLORMASKSEXCEEDBPP 8
#define DPVSIMPLEDECODEERROR_UNSUPPORTEDBPP 9
Functions
void * dpvsimpledecode_open (clvideo_t *video, char *filename, const char **errorstring)
void dpvsimpledecode_close (void *stream)
int dpvsimpledecode_error (void *stream, const char **errorstring)
unsigned int dpvsimpledecode_getwidth (void *stream)
unsigned int dpvsimpledecode_getheight (void *stream)
double dpvsimpledecode_getframerate (void *stream)
double dpvsimpledecode_getaspectratio (void *stream)
int dpvsimpledecode_video (void *stream, void *imagedata, unsigned int Rmask, unsigned int Gmask, unsigned int Bmask, unsigned int bytesperpixel, int imagebytesperrow)
Macro Definition Documentation
DPVSIMPLEDECODEERROR_COLORMASKSEXCEEDBPP
#define DPVSIMPLEDECODEERROR_COLORMASKSEXCEEDBPP 8
Definition at line 38 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_COLORMASKSOVERLAP
#define DPVSIMPLEDECODEERROR_COLORMASKSOVERLAP 7
Definition at line 37 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_EOF
#define DPVSIMPLEDECODEERROR_EOF 1
Definition at line 31 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_INVALIDBMASK
#define DPVSIMPLEDECODEERROR_INVALIDBMASK 6
Definition at line 36 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_INVALIDGMASK
#define DPVSIMPLEDECODEERROR_INVALIDGMASK 5
Definition at line 35 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_INVALIDRMASK
#define DPVSIMPLEDECODEERROR_INVALIDRMASK 4
Definition at line 34 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_NONE
#define DPVSIMPLEDECODEERROR_NONE 0
Definition at line 30 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_READERROR
#define DPVSIMPLEDECODEERROR_READERROR 2
Definition at line 32 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_SOUNDBUFFERTOOSMALL
#define DPVSIMPLEDECODEERROR_SOUNDBUFFERTOOSMALL 3
Definition at line 33 of file dpvsimpledecode.h.
DPVSIMPLEDECODEERROR_UNSUPPORTEDBPP
#define DPVSIMPLEDECODEERROR_UNSUPPORTEDBPP 9
Definition at line 39 of file dpvsimpledecode.h.
Function Documentation
dpvsimpledecode_close()
void dpvsimpledecode_close (void * stream)
Definition at line 447 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    if (s == NULL)
        return;
    if (s->videopixels)
        Z_Free(s->videopixels);
    if (s->sndchan != -1)
        S_StopChannel (s->sndchan, true, true);
    if (s->framedatablocks)
        hz_bitstream_read_blocks_free(s->framedatablocks);
    if (s->bitstream)
        hz_bitstream_read_close(s->bitstream);
    Z_Free(s);
}
Referenced by dpvsimpledecode_open().
dpvsimpledecode_error()
int dpvsimpledecode_error (void * stream, const char ** errorstring)
Definition at line 469 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    int e;
    e = s->error;
    s->error = 0;
    if (errorstring)
    {
        switch (e)
        {
            case DPVSIMPLEDECODEERROR_NONE:
                *errorstring = "no error";
                break;
            case DPVSIMPLEDECODEERROR_EOF:
                *errorstring = "end of file reached (this is not an error)";
                break;
            case DPVSIMPLEDECODEERROR_READERROR:
                *errorstring = "read error (corrupt or incomplete file)";
                break;
            case DPVSIMPLEDECODEERROR_SOUNDBUFFERTOOSMALL:
                *errorstring = "sound buffer is too small for decoding frame (please allocate it as large as dpvsimpledecode_getneededsoundbufferlength suggests)";
                break;
            case DPVSIMPLEDECODEERROR_INVALIDRMASK:
                *errorstring = "invalid red bits mask";
                break;
            case DPVSIMPLEDECODEERROR_INVALIDGMASK:
                *errorstring = "invalid green bits mask";
                break;
            case DPVSIMPLEDECODEERROR_INVALIDBMASK:
                *errorstring = "invalid blue bits mask";
                break;
            case DPVSIMPLEDECODEERROR_COLORMASKSOVERLAP:
                *errorstring = "color bit masks overlap";
                break;
            case DPVSIMPLEDECODEERROR_COLORMASKSEXCEEDBPP:
                *errorstring = "color masks too big for specified bytes per pixel";
                break;
            case DPVSIMPLEDECODEERROR_UNSUPPORTEDBPP:
                *errorstring = "unsupported bytes per pixel (must be 2 for 16bit, or 4 for 32bit)";
                break;
            default:
                *errorstring = "unknown error";
                break;
        }
    }
    return e;
}
dpvsimpledecode_getaspectratio()
double dpvsimpledecode_getaspectratio (void * stream)
Definition at line 539 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    return s->info_aspectratio;
}
Referenced by dpvsimpledecode_open().
dpvsimpledecode_getframerate()
double dpvsimpledecode_getframerate (void * stream)
Definition at line 532 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    return s->info_framerate;
}
Referenced by dpvsimpledecode_open().
dpvsimpledecode_getheight()
unsigned int dpvsimpledecode_getheight (void * stream)
Definition at line 525 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    return s->info_imageheight;
}
Referenced by dpvsimpledecode_open().
dpvsimpledecode_getwidth()
unsigned int dpvsimpledecode_getwidth (void * stream)
Definition at line 518 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    return s->info_imagewidth;
}
Referenced by dpvsimpledecode_open().
dpvsimpledecode_open()
void * dpvsimpledecode_open (clvideo_t * video, char * filename, const char ** errorstring)
Definition at line 356 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s;
    char t[8], *wavename;
    if (errorstring != NULL)
        *errorstring = NULL;
    s = (dpvsimpledecodestream_t *)Z_Malloc(sizeof(dpvsimpledecodestream_t));
    if (s != NULL)
    {
        s->bitstream = hz_bitstream_read_open(filename);
        if (s->bitstream != NULL)
        {
            // check file identification
            s->framedatablocks = hz_bitstream_read_blocks_new();
            if (s->framedatablocks != NULL)
            {
                hz_bitstream_read_blocks_read(s->framedatablocks, s->bitstream, 8);
                hz_bitstream_read_bytes(s->framedatablocks, t, 8);
                if (!memcmp(t, "DPVideo", 8))
                {
                    // check version number
                    hz_bitstream_read_blocks_read(s->framedatablocks, s->bitstream, 2);
                    if (hz_bitstream_read_short(s->framedatablocks) == 1)
                    {
                        hz_bitstream_read_blocks_read(s->framedatablocks, s->bitstream, 12);
                        s->info_imagewidth = hz_bitstream_read_short(s->framedatablocks);
                        s->info_imageheight = hz_bitstream_read_short(s->framedatablocks);
                        s->info_framerate = (double) hz_bitstream_read_int(s->framedatablocks) * (1.0 / 65536.0);
                        s->info_aspectratio = (double)s->info_imagewidth / (double)s->info_imageheight;
                        if (s->info_framerate > 0.0)
{
                            s->videopixels = (unsigned int *)Z_Malloc(s->info_imagewidth * s->info_imageheight * sizeof(*s->videopixels));
                            if (s->videopixels != NULL)
{
                                size_t namelen;
                                namelen = strlen(filename) + 10;
                                wavename = (char *)Z_Malloc(namelen);
                                if (wavename)
{
                                    sfx_t* sfx;
                                    FS_StripExtension(filename, wavename, namelen);
                                    dp_strlcat(wavename, ".wav", namelen);
                                    sfx = S_PrecacheSound (wavename, false, false);
                                    if (sfx != NULL)
                                        s->sndchan = S_StartSound (-1, 0, sfx, vec3_origin, 1.0f, 0);
                                    else
                                        s->sndchan = -1;
                                    Z_Free(wavename);
                                }
                                // all is well...
                                // set the module functions
                                s->videoframenum = -10000;
                                video->close = dpvsimpledecode_close;
                                video->getwidth = dpvsimpledecode_getwidth;
                                video->getheight = dpvsimpledecode_getheight;
                                video->getframerate = dpvsimpledecode_getframerate;
                                video->decodeframe = dpvsimpledecode_video;
                                video->getaspectratio = dpvsimpledecode_getaspectratio;
                                return s;
                            }
                            else if (errorstring != NULL)
                                *errorstring = "unable to allocate video image buffer";
                        }
                        else if (errorstring != NULL)
                            *errorstring = "error in video info chunk";
                    }
                    else if (errorstring != NULL)
                        *errorstring = "read error";
                }
                else if (errorstring != NULL)
                    *errorstring = "not a dpvideo file";
                hz_bitstream_read_blocks_free(s->framedatablocks);
            }
            else if (errorstring != NULL)
                *errorstring = "unable to allocate memory for reading buffer";
            hz_bitstream_read_close(s->bitstream);
        }
        else if (errorstring != NULL)
            *errorstring = "unable to open file";
        Z_Free(s);
    }
    else if (errorstring != NULL)
        *errorstring = "unable to allocate memory for stream info structure";
    return NULL;
}
Referenced by OpenStream().
dpvsimpledecode_video()
int dpvsimpledecode_video (void * stream, void * imagedata, unsigned int Rmask, unsigned int Gmask, unsigned int Bmask, unsigned int bytesperpixel, int imagebytesperrow)
Definition at line 651 of file dpvsimpledecode.c.
{
    dpvsimpledecodestream_t *s = (dpvsimpledecodestream_t *)stream;
    unsigned int framedatasize;
    char t[4];
    s->error = DPVSIMPLEDECODEERROR_NONE;
    if (dpvsimpledecode_setpixelformat(s, Rmask, Gmask, Bmask, bytesperpixel))
        return s->error;
    hz_bitstream_read_blocks_read(s->framedatablocks, s->bitstream, 8);
    hz_bitstream_read_bytes(s->framedatablocks, t, 4);
    if (memcmp(t, "VID0", 4))
    {
        if (t[0] == 0)
            return (s->error = DPVSIMPLEDECODEERROR_EOF);
        else
            return (s->error = DPVSIMPLEDECODEERROR_READERROR);
    }
    framedatasize = hz_bitstream_read_int(s->framedatablocks);
    hz_bitstream_read_blocks_read(s->framedatablocks, s->bitstream, framedatasize);
    if (dpvsimpledecode_decompressimage(s))
        return s->error;
    dpvsimpledecode_convertpixels(s, imagedata, imagebytesperrow);
    return s->error;
}
Referenced by dpvsimpledecode_open().