DarkPlaces: draw.h File Reference
draw.h File Reference
#include <stddef.h>
#include "qtypes.h"
#include "r_textures.h"
Data Structures
struct drawqueuemesh_t
struct ft2_settings_t
struct dp_font_t
struct dp_fonts_t
Macros
#define DRAWFLAGS_BLEND 0xFF /* this matches all blending flags */
#define MAX_FONT_SIZES 16
#define MAX_FONT_FALLBACKS 3
#define MAX_FONT_CMDLINE MAX_QPATH * (MAX_FONT_FALLBACKS + 1)
#define MAX_FONTS 16
#define FONTS_EXPAND 8
#define FONT_DEFAULT (&dp_fonts.f[0])
#define FONT_CONSOLE (&dp_fonts.f[1])
#define FONT_SBAR (&dp_fonts.f[2])
#define FONT_NOTIFY (&dp_fonts.f[3])
#define FONT_CHAT (&dp_fonts.f[4])
#define FONT_CENTERPRINT (&dp_fonts.f[5])
#define FONT_INFOBAR (&dp_fonts.f[6])
#define FONT_MENU (&dp_fonts.f[7])
#define FONT_USER(i) (&dp_fonts.f[8+i])
#define MAX_USERFONTS (dp_fonts.maxsize - 8)
#define STRING_COLOR_TAG '^'
#define STRING_COLOR_DEFAULT 7
#define STRING_COLOR_DEFAULT_STR "^7"
#define STRING_COLOR_RGB_TAG_CHAR 'x'
#define STRING_COLOR_RGB_TAG "^x"
Enumerations
enum cachepicflags_t {
CACHEPICFLAG_NOTPERSISTENT = 1 , CACHEPICFLAG_QUIET = 2 , CACHEPICFLAG_NOCOMPRESSION = 4 , CACHEPICFLAG_NOCLAMP = 8 ,
CACHEPICFLAG_NEWPIC = 16 , CACHEPICFLAG_MIPMAP = 32 , CACHEPICFLAG_NEAREST = 64 , CACHEPICFLAG_LINEAR = 128 ,
CACHEPICFLAG_FAILONMISSING = 256
}
enum drawqueue_drawflag_e {
DRAWFLAG_NORMAL , DRAWFLAG_ADDITIVE , DRAWFLAG_MODULATE , DRAWFLAG_2XMODULATE ,
DRAWFLAG_SCREEN , DRAWFLAG_NUMFLAGS , DRAWFLAG_MASK = 0xFF , DRAWFLAG_MIPMAP = 0x100 ,
DRAWFLAG_NOGAMMA = 0x200
}
Functions
void Draw_Frame (void)
cachepic_t * Draw_CachePic_Flags (const char *path, unsigned int cachepicflags)
cachepic_t * Draw_CachePic (const char *path)
cachepic_t * Draw_NewPic (const char *picname, int width, int height, unsigned char *pixels, textype_t textype, int texflags)
void Draw_FreePic (const char *picname)
void DrawQ_Start (void)
void DrawQ_Finish (void)
void DrawQ_FlushUI (void)
void DrawQ_RecalcView (void)
void DrawQ_Pic (float x, float y, cachepic_t *pic, float width, float height, float red, float green, float blue, float alpha, int flags)
void DrawQ_RotPic (float x, float y, cachepic_t *pic, float width, float height, float org_x, float org_y, float angle, float red, float green, float blue, float alpha, int flags)
void DrawQ_Fill (float x, float y, float width, float height, float red, float green, float blue, float alpha, int flags)
float DrawQ_String (float x, float y, const char *text, size_t maxlen, float scalex, float scaley, float basered, float basegreen, float baseblue, float basealpha, int flags, int *outcolor, qbool ignorecolorcodes, const dp_font_t *fnt)
float DrawQ_String_Scale (float x, float y, const char *text, size_t maxlen, float sizex, float sizey, float scalex, float scaley, float basered, float basegreen, float baseblue, float basealpha, int flags, int *outcolor, qbool ignorecolorcodes, const dp_font_t *fnt)
float DrawQ_TextWidth (const char *text, size_t maxlen, float w, float h, qbool ignorecolorcodes, const dp_font_t *fnt)
float DrawQ_TextWidth_UntilWidth (const char *text, size_t *maxlen, float w, float h, qbool ignorecolorcodes, const dp_font_t *fnt, float maxWidth)
float DrawQ_TextWidth_UntilWidth_TrackColors (const char *text, size_t *maxlen, float w, float h, int *outcolor, qbool ignorecolorcodes, const dp_font_t *fnt, float maxwidth)
float DrawQ_TextWidth_UntilWidth_TrackColors_Scale (const char *text, size_t *maxlen, float w, float h, float sw, float sh, int *outcolor, qbool ignorecolorcodes, const dp_font_t *fnt, float maxwidth)
void DrawQ_SuperPic (float x, float y, cachepic_t *pic, float width, float height, float s1, float t1, float r1, float g1, float b1, float a1, float s2, float t2, float r2, float g2, float b2, float a2, float s3, float t3, float r3, float g3, float b3, float a3, float s4, float t4, float r4, float g4, float b4, float a4, int flags)
void DrawQ_SetClipArea (float x, float y, float width, float height)
void DrawQ_ResetClipArea (void)
void DrawQ_Line (float width, float x1, float y1, float x2, float y2, float r, float g, float b, float alpha, int flags)
const char * Draw_GetPicName (cachepic_t *pic)
int Draw_GetPicWidth (cachepic_t *pic)
int Draw_GetPicHeight (cachepic_t *pic)
qbool Draw_IsPicLoaded (cachepic_t *pic)
rtexture_t * Draw_GetPicTexture (cachepic_t *pic)
Variables
dp_fonts_t dp_fonts
float DrawQ_Color [4]
rtexturepool_t * drawtexturepool
Macro Definition Documentation
DRAWFLAGS_BLEND
#define DRAWFLAGS_BLEND 0xFF /* this matches all blending flags */
Definition at line 84 of file draw.h.
FONT_CENTERPRINT
#define FONT_CENTERPRINT (&dp_fonts.f[5])
Definition at line 133 of file draw.h.
FONT_CHAT
#define FONT_CHAT (&dp_fonts.f[4])
Definition at line 132 of file draw.h.
FONT_CONSOLE
#define FONT_CONSOLE (&dp_fonts.f[1])
Definition at line 129 of file draw.h.
FONT_DEFAULT
#define FONT_DEFAULT (&dp_fonts.f[0])
Definition at line 128 of file draw.h.
FONT_INFOBAR
#define FONT_INFOBAR (&dp_fonts.f[6])
Definition at line 134 of file draw.h.
FONT_MENU
#define FONT_MENU (&dp_fonts.f[7])
Definition at line 135 of file draw.h.
FONT_NOTIFY
#define FONT_NOTIFY (&dp_fonts.f[3])
Definition at line 131 of file draw.h.
FONT_SBAR
#define FONT_SBAR (&dp_fonts.f[2])
Definition at line 130 of file draw.h.
FONT_USER
#define FONT_USER (i) (&dp_fonts.f[8+i])
Definition at line 136 of file draw.h.
FONTS_EXPAND
#define FONTS_EXPAND 8
Definition at line 127 of file draw.h.
MAX_FONT_CMDLINE
#define MAX_FONT_CMDLINE MAX_QPATH * (MAX_FONT_FALLBACKS + 1)
Definition at line 96 of file draw.h.
MAX_FONT_FALLBACKS
#define MAX_FONT_FALLBACKS 3
Definition at line 95 of file draw.h.
MAX_FONT_SIZES
#define MAX_FONT_SIZES 16
Definition at line 94 of file draw.h.
MAX_FONTS
#define MAX_FONTS 16
Definition at line 126 of file draw.h.
MAX_USERFONTS
#define MAX_USERFONTS (dp_fonts.maxsize - 8)
Definition at line 137 of file draw.h.
STRING_COLOR_DEFAULT
#define STRING_COLOR_DEFAULT 7
Definition at line 141 of file draw.h.
STRING_COLOR_DEFAULT_STR
#define STRING_COLOR_DEFAULT_STR "^7"
Definition at line 142 of file draw.h.
STRING_COLOR_RGB_TAG
#define STRING_COLOR_RGB_TAG "^x"
Definition at line 144 of file draw.h.
STRING_COLOR_RGB_TAG_CHAR
#define STRING_COLOR_RGB_TAG_CHAR 'x'
Definition at line 143 of file draw.h.
STRING_COLOR_TAG
#define STRING_COLOR_TAG '^'
Definition at line 140 of file draw.h.
Enumeration Type Documentation
cachepicflags_t
enum cachepicflags_t
Enumerator
CACHEPICFLAG_NOTPERSISTENT
CACHEPICFLAG_QUIET
CACHEPICFLAG_NOCOMPRESSION
CACHEPICFLAG_NOCLAMP
CACHEPICFLAG_NEWPIC
CACHEPICFLAG_MIPMAP
CACHEPICFLAG_NEAREST
CACHEPICFLAG_LINEAR
CACHEPICFLAG_FAILONMISSING
Definition at line 34 of file draw.h.
{
    CACHEPICFLAG_NOTPERSISTENT = 1,
    CACHEPICFLAG_QUIET = 2,
    CACHEPICFLAG_NOCOMPRESSION = 4,
    CACHEPICFLAG_NOCLAMP = 8,
    CACHEPICFLAG_NEWPIC = 16, // disables matching texflags check, because a pic created with Draw_NewPic should not be subject to that
    CACHEPICFLAG_MIPMAP = 32,
    CACHEPICFLAG_NEAREST = 64, // force nearest filtering instead of linear
    CACHEPICFLAG_LINEAR = 128, // force linear filtering even if nearest_2d is enabled
    CACHEPICFLAG_FAILONMISSING = 256 // return NULL if the pic has no texture
}
drawqueue_drawflag_e
enum drawqueue_drawflag_e
Enumerator
DRAWFLAG_NORMAL
DRAWFLAG_ADDITIVE
DRAWFLAG_MODULATE
DRAWFLAG_2XMODULATE
DRAWFLAG_SCREEN
DRAWFLAG_NUMFLAGS
DRAWFLAG_MASK
DRAWFLAG_MIPMAP
DRAWFLAG_NOGAMMA
Definition at line 73 of file draw.h.
{
DRAWFLAG_NORMAL,
DRAWFLAG_ADDITIVE,
DRAWFLAG_MODULATE,
DRAWFLAG_2XMODULATE,
DRAWFLAG_SCREEN,
DRAWFLAG_NUMFLAGS,
DRAWFLAG_MASK = 0xFF,   // ONLY R_BeginPolygon()
DRAWFLAG_MIPMAP = 0x100, // ONLY R_BeginPolygon()
DRAWFLAG_NOGAMMA = 0x200 // ONLY R_DrawQSuperPic()
};
Function Documentation
Draw_CachePic()
cachepic_t * Draw_CachePic (const char * path)
Definition at line 184 of file gl_draw.c.
{
    return Draw_CachePic_Flags (path, 0); // default to persistent!
}
Referenced by DrawQ_Fill(), DrawQ_Pic(), DrawQ_RotPic(), DrawQ_SuperPic(), M_Draw(), M_DrawPic(), M_GameOptions_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_MultiPlayer_Draw(), M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), M_Transfusion_Episode_Draw(), M_Transfusion_Skill_Draw(), M_Video_Draw(), Sbar_Draw(), SCR_DrawBrand(), SCR_DrawNet(), SCR_DrawPause(), and SCR_DrawTurtle().
Draw_CachePic_Flags()
cachepic_t * Draw_CachePic_Flags (const char * path, unsigned int cachepicflags)
Definition at line 85 of file gl_draw.c.
{
    int crc, hashkey;
    cachepic_t *pic;
    int texflags;
    texflags = TEXF_ALPHA;
    if (!(cachepicflags & CACHEPICFLAG_NOCLAMP))
        texflags |= TEXF_CLAMP;
    if (cachepicflags & CACHEPICFLAG_MIPMAP)
        texflags |= TEXF_MIPMAP;
    if (!(cachepicflags & CACHEPICFLAG_NOCOMPRESSION) && gl_texturecompression_2d.integer && gl_texturecompression.integer)
        texflags |= TEXF_COMPRESS;
    if (cachepicflags & CACHEPICFLAG_LINEAR)
        texflags |= TEXF_FORCELINEAR;
    else if ((cachepicflags & CACHEPICFLAG_NEAREST) || r_nearest_2d.integer)
        texflags |= TEXF_FORCENEAREST;
    // check whether the picture has already been cached
    crc = CRC_Block((unsigned char *)path, strlen(path));
    hashkey = ((crc >> 8) ^ crc) % CACHEPICHASHSIZE;
    for (pic = cachepichash[hashkey];pic;pic = pic->chain)
    {
        if (!strcmp(path, pic->name))
        {
            // if it was created (or replaced) by Draw_NewPic, just return it
            if (!(pic->flags & CACHEPICFLAG_NEWPIC))
            {
                // reload the pic if texflags changed in important ways
                // ignore TEXF_COMPRESS when comparing, because fallback pics remove the flag, and ignore TEXF_MIPMAP because QC specifies that
                if ((pic->texflags ^ texflags) & ~(TEXF_COMPRESS | TEXF_MIPMAP))
                {
                    Con_DPrintf("Draw_CachePic(\"%s\"): frame %i: reloading pic due to mismatch on flags\n", path, draw_frame);
                    goto reload;
                }
                if (!pic->skinframe || !pic->skinframe->base)
                {
                    if (pic->flags & CACHEPICFLAG_FAILONMISSING)
                        return NULL;
                    Con_DPrintf("Draw_CachePic(\"%s\"): frame %i: reloading pic\n", path, draw_frame);
                    goto reload;
                }
                if (!(cachepicflags & CACHEPICFLAG_NOTPERSISTENT))
                    pic->autoload = false; // caller is making this pic persistent
            }
            if (pic->skinframe)
                R_SkinFrame_MarkUsed(pic->skinframe);
            pic->lastusedframe = draw_frame;
            return pic;
        }
    }
    if (numcachepics == MAX_CACHED_PICS)
    {
        Con_DPrintf ("Draw_CachePic(\"%s\"): frame %i: numcachepics == MAX_CACHED_PICS\n", path, draw_frame);
        // FIXME: support NULL in callers?
        return cachepics; // return the first one
    }
    Con_DPrintf("Draw_CachePic(\"%s\"): frame %i: loading pic%s\n", path, draw_frame, (cachepicflags & CACHEPICFLAG_NOTPERSISTENT) ? " notpersist" : "");
    pic = cachepics + (numcachepics++);
    memset(pic, 0, sizeof(*pic));
    dp_strlcpy (pic->name, path, sizeof(pic->name));
    // link into list
    pic->chain = cachepichash[hashkey];
    cachepichash[hashkey] = pic;
reload:
    if (pic->skinframe)
        R_SkinFrame_PurgeSkinFrame(pic->skinframe);
    pic->flags = cachepicflags;
    pic->texflags = texflags;
    pic->autoload = (cachepicflags & CACHEPICFLAG_NOTPERSISTENT) != 0;
    pic->lastusedframe = draw_frame;
    if (pic->skinframe)
    {
        // reload image after it was unloaded or texflags changed significantly
        R_SkinFrame_LoadExternal_SkinFrame(pic->skinframe, pic->name, texflags | TEXF_FORCE_RELOAD, (cachepicflags & CACHEPICFLAG_QUIET) == 0, (cachepicflags & CACHEPICFLAG_FAILONMISSING) == 0);
    }
    else
    {
        // load high quality image (this falls back to low quality too)
        pic->skinframe = R_SkinFrame_LoadExternal(pic->name, texflags | TEXF_FORCE_RELOAD, (cachepicflags & CACHEPICFLAG_QUIET) == 0, (cachepicflags & CACHEPICFLAG_FAILONMISSING) == 0);
    }
    // get the dimensions of the image we loaded (if it was successful)
    if (pic->skinframe && pic->skinframe->base)
    {
        pic->width = R_TextureWidth(pic->skinframe->base);
        pic->height = R_TextureHeight(pic->skinframe->base);
    }
    // check for a low quality version of the pic and use its size if possible, to match the stock hud
    Image_GetStockPicSize(pic->name, &pic->width, &pic->height);
    return pic;
}
Referenced by Con_DrawConsole(), Draw_CachePic(), LoadFont(), M_Menu_Main_f(), M_Options_ColorControl_Draw(), OpenVideo(), sbar_start(), SCR_DrawLoadingScreen(), SCR_DrawTouchscreenOverlay(), SHOWLMP_drawall(), VM_CL_ReadPicture(), VM_drawpic(), VM_drawrotpic(), VM_drawsubpic(), VM_getimagesize(), and VM_precache_pic().
Draw_Frame()
void Draw_Frame (void)
Definition at line 236 of file gl_draw.c.
{
    int i;
    cachepic_t *pic;
    static double nextpurgetime;
    if (nextpurgetime > host.realtime)
        return;
    nextpurgetime = host.realtime + 0.05;
    for (i = 0, pic = cachepics;i < numcachepics;i++, pic++)
    {
        if (pic->autoload && pic->skinframe && pic->skinframe->base && pic->lastusedframe < draw_frame - 3)
        {
            Con_DPrintf("Draw_Frame(%i): Unloading \"%s\"\n", draw_frame, pic->name);
            R_SkinFrame_PurgeSkinFrame(pic->skinframe);
        }
    }
    draw_frame++;
}
Referenced by SCR_DrawScreen().
Draw_FreePic()
void Draw_FreePic (const char * picname)
Definition at line 308 of file gl_draw.c.
{
    int crc;
    int hashkey;
    cachepic_t *pic;
    // this doesn't really free the pic, but does free its texture
    crc = CRC_Block((unsigned char *)picname, strlen(picname));
    hashkey = ((crc >> 8) ^ crc) % CACHEPICHASHSIZE;
    for (pic = cachepichash[hashkey];pic;pic = pic->chain)
    {
        if (!strcmp (picname, pic->name) && pic->skinframe)
        {
            Con_DPrintf("Draw_FreePic(\"%s\"): frame %i: freeing pic\n", picname, draw_frame);
            R_SkinFrame_PurgeSkinFrame(pic->skinframe);
            return;
        }
    }
}
Referenced by UnlinkVideoTexture(), and VM_freepic().
Draw_GetPicHeight()
int Draw_GetPicHeight (cachepic_t * pic)
Definition at line 203 of file gl_draw.c.
{
    if (pic == NULL)
        return 0;
    return pic->height;
}
Referenced by DrawQ_String_Scale(), Sbar_Draw(), SCR_DrawBrand(), SCR_DrawLoadingScreen(), SCR_DrawPause(), and VM_getimagesize().
Draw_GetPicName()
const char * Draw_GetPicName (cachepic_t * pic)
Definition at line 189 of file gl_draw.c.
{
    if (pic == NULL)
        return "";
    return pic->name;
}
Referenced by incmap_post_process().
Draw_GetPicTexture()
rtexture_t * Draw_GetPicTexture (cachepic_t * pic)
Definition at line 223 of file gl_draw.c.
{
    if (pic == NULL)
        return NULL;
    if (pic->autoload && (!pic->skinframe || !pic->skinframe->base))
    {
        Con_DPrintf("Draw_GetPicTexture(\"%s\"): Loading external skin\n", pic->name);
        pic->skinframe = R_SkinFrame_LoadExternal(pic->name, pic->texflags | TEXF_FORCE_RELOAD, false, true);
    }
    pic->lastusedframe = draw_frame;
    return pic->skinframe ? pic->skinframe->base : NULL;
}
Referenced by CL_Video_Frame(), DrawQ_Pic(), DrawQ_RotPic(), DrawQ_SuperPic(), LinkVideoTexture(), and SCR_DrawLoadingScreen().
Draw_GetPicWidth()
int Draw_GetPicWidth (cachepic_t * pic)
Definition at line 196 of file gl_draw.c.
{
    if (pic == NULL)
        return 0;
    return pic->width;
}
Referenced by DrawQ_String_Scale(), M_Draw(), M_GameOptions_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_MultiPlayer_Draw(), M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), M_Transfusion_Episode_Draw(), M_Transfusion_Skill_Draw(), M_Video_Draw(), Sbar_DeathmatchOverlay(), Sbar_Draw(), Sbar_FinaleOverlay(), SCR_DrawBrand(), SCR_DrawLoadingScreen(), SCR_DrawPause(), and VM_getimagesize().
Draw_IsPicLoaded()
qbool Draw_IsPicLoaded (cachepic_t * pic)
Definition at line 210 of file gl_draw.c.
{
    if (pic == NULL)
        return false;
    if (pic->autoload && (!pic->skinframe || !pic->skinframe->base))
    {
        Con_DPrintf("Draw_IsPicLoaded(\"%s\"): Loading external skin\n", pic->name);
        pic->skinframe = R_SkinFrame_LoadExternal(pic->name, pic->texflags | TEXF_FORCE_RELOAD, false, true);
    }
    // skinframe will only be NULL if the pic was created with CACHEPICFLAG_FAILONMISSING and not found
    return pic->skinframe != NULL && pic->skinframe->base != NULL;
}
Referenced by Con_DrawConsole(), Font_LoadMap(), LoadFont(), M_Menu_Main_f(), Sbar_Score(), SCR_DrawTouchscreenOverlay(), VM_CL_ReadPicture(), VM_getimagesize(), and VM_precache_pic().
Draw_NewPic()
cachepic_t * Draw_NewPic (const char * picname, int width, int height, unsigned char * pixels, textype_t textype, int texflags)
Definition at line 255 of file gl_draw.c.
{
    int crc, hashkey;
    cachepic_t *pic;
    crc = CRC_Block((unsigned char *)picname, strlen(picname));
    hashkey = ((crc >> 8) ^ crc) % CACHEPICHASHSIZE;
    for (pic = cachepichash[hashkey];pic;pic = pic->chain)
        if (!strcmp (picname, pic->name))
            break;
    if (pic)
    {
        if (pic->flags & CACHEPICFLAG_NEWPIC && pic->skinframe && pic->skinframe->base && pic->width == width && pic->height == height)
        {
            Con_DPrintf("Draw_NewPic(\"%s\"): frame %i: updating texture\n", picname, draw_frame);
            R_UpdateTexture(pic->skinframe->base, pixels_bgra, 0, 0, 0, width, height, 1, 0);
            R_SkinFrame_MarkUsed(pic->skinframe);
            pic->lastusedframe = draw_frame;
            return pic;
        }
        Con_DPrintf("Draw_NewPic(\"%s\"): frame %i: reloading pic because flags/size changed\n", picname, draw_frame);
    }
    else
    {
        if (numcachepics == MAX_CACHED_PICS)
        {
            Con_DPrintf ("Draw_NewPic(\"%s\"): frame %i: numcachepics == MAX_CACHED_PICS\n", picname, draw_frame);
            // FIXME: support NULL in callers?
            return cachepics; // return the first one
        }
        Con_DPrintf("Draw_NewPic(\"%s\"): frame %i: creating new cachepic\n", picname, draw_frame);
        pic = cachepics + (numcachepics++);
        memset(pic, 0, sizeof(*pic));
        dp_strlcpy (pic->name, picname, sizeof(pic->name));
        // link into list
        pic->chain = cachepichash[hashkey];
        cachepichash[hashkey] = pic;
    }
    R_SkinFrame_PurgeSkinFrame(pic->skinframe);
    pic->autoload = false;
    pic->flags = CACHEPICFLAG_NEWPIC; // disable texflags checks in Draw_CachePic
    pic->flags |= (texflags & TEXF_CLAMP) ? 0 : CACHEPICFLAG_NOCLAMP;
    pic->flags |= (texflags & TEXF_FORCENEAREST) ? CACHEPICFLAG_NEAREST : 0;
    pic->width = width;
    pic->height = height;
    pic->skinframe = R_SkinFrame_LoadInternalBGRA(picname, texflags | TEXF_FORCE_RELOAD, pixels_bgra, width, height, 0, 0, 0, vid.sRGB2D);
    pic->lastusedframe = draw_frame;
    return pic;
}
Referenced by Curl_EndDownload(), LinkVideoTexture(), M_Setup_Draw(), update_pic_for_fontmap(), VideoUpdateCallback(), and VM_CL_ReadPicture().
DrawQ_Fill()
void DrawQ_Fill (float x, float y, float width, float height, float red, float green, float blue, float alpha, int flags)
Definition at line 846 of file gl_draw.c.
{
    DrawQ_Pic(x, y, Draw_CachePic("white"), width, height, red, green, blue, alpha, flags);
}
Referenced by CL_DrawVideo(), Con_DrawConsole(), M_Background(), M_Options_ColorControl_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), M_Options_PrintSlider(), M_ServerList_Draw(), R_TimeReport_EndFrame(), Sbar_DrawFace(), Sbar_DrawFrags(), Sbar_PrintScoreboardItem(), Sbar_ShowFPS(), SCR_DrawCurlDownload(), SCR_DrawInfobarString(), SCR_DrawNetGraph_DrawGraph(), SCR_DrawQWDownload(), SCR_DrawTouchscreenOverlay(), and VM_drawfill().
DrawQ_Finish()
void DrawQ_Finish (void)
Definition at line 1454 of file gl_draw.c.
{
    DrawQ_FlushUI();
    r_refdef.draw2dstage = 0;
}
Referenced by R_RenderView(), and SCR_DrawScreen().
DrawQ_FlushUI()
void DrawQ_FlushUI (void)
Definition at line 1467 of file gl_draw.c.
{
    model_t *mod = CL_Mesh_UI();
    if (mod->num_surfaces == 0)
        return;
    if (!r_draw2d.integer && !r_draw2d_force)
    {
        Mod_Mesh_Reset(mod);
        return;
    }
    // this is roughly equivalent to R_Mod_Draw, so the UI can use full material feature set
    r_refdef.view.colorscale = 1;
    r_textureframe++; // used only by R_GetCurrentTexture
    GL_DepthMask(false);
    Mod_Mesh_Finalize(mod);
    R_DrawModelSurfaces(&cl_meshentities[MESH_UI].render, false, false, false, false, false, true);
    Mod_Mesh_Reset(mod);
}
Referenced by DrawQ_Finish(), DrawQ_RecalcView(), DrawQ_ResetClipArea(), and DrawQ_SetClipArea().
DrawQ_Line()
void DrawQ_Line (float width, float x1, float y1, float x2, float y2, float r, float g, float b, float alpha, int flags)
Definition at line 1400 of file gl_draw.c.
{
    model_t *mod = CL_Mesh_UI();
    msurface_t *surf;
    int e0, e1, e2, e3;
    float offsetx, offsety;
    // width is measured in real pixels
    if (fabs(x2 - x1) > fabs(y2 - y1))
    {
        offsetx = 0;
        offsety = 0.5f * width * vid_conheight.value / vid.height;
    }
    else
    {
        offsetx = 0.5f * width * vid_conwidth.value / vid.width;
        offsety = 0;
    }
    surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, "white", 0, 0, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
    e0 = Mod_Mesh_IndexForVertex(mod, surf, x1 - offsetx, y1 - offsety, 10, 0, 0, -1, 0, 0, 0, 0, r, g, b, alpha);
    e1 = Mod_Mesh_IndexForVertex(mod, surf, x2 - offsetx, y2 - offsety, 10, 0, 0, -1, 0, 0, 0, 0, r, g, b, alpha);
    e2 = Mod_Mesh_IndexForVertex(mod, surf, x2 + offsetx, y2 + offsety, 10, 0, 0, -1, 0, 0, 0, 0, r, g, b, alpha);
    e3 = Mod_Mesh_IndexForVertex(mod, surf, x1 + offsetx, y1 + offsety, 10, 0, 0, -1, 0, 0, 0, 0, r, g, b, alpha);
    Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
    Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
}
Referenced by R_TimeReport_EndFrame(), SCR_DrawNetGraph_DrawGraph(), and VM_drawline().
DrawQ_Pic()
void DrawQ_Pic (float x, float y, cachepic_t * pic, float width, float height, float red, float green, float blue, float alpha, int flags)
Definition at line 796 of file gl_draw.c.
{
    model_t *mod = CL_Mesh_UI();
    msurface_t *surf;
    int e0, e1, e2, e3;
    if (!pic)
        pic = Draw_CachePic("white");
    // make sure pic is loaded - we don't use the texture here, Mod_Mesh_GetTexture looks up the skinframe by name
    Draw_GetPicTexture(pic);
    if (width == 0)
        width = pic->width;
    if (height == 0)
        height = pic->height;
    surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, pic->name, flags, pic->texflags, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
    e0 = Mod_Mesh_IndexForVertex(mod, surf, x        , y         , 0, 0, 0, -1, 0, 0, 0, 0, red, green, blue, alpha);
    e1 = Mod_Mesh_IndexForVertex(mod, surf, x + width, y         , 0, 0, 0, -1, 1, 0, 0, 0, red, green, blue, alpha);
    e2 = Mod_Mesh_IndexForVertex(mod, surf, x + width, y + height, 0, 0, 0, -1, 1, 1, 0, 0, red, green, blue, alpha);
    e3 = Mod_Mesh_IndexForVertex(mod, surf, x        , y + height, 0, 0, 0, -1, 0, 1, 0, 0, red, green, blue, alpha);
    Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
    Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
}
Referenced by DrawQ_Fill(), M_Draw(), M_DrawPic(), M_ModList_Draw(), R_Shadow_EditLights_DrawSelectedLightProperties(), Sbar_DeathmatchOverlay(), Sbar_Draw(), Sbar_DrawAlphaPic(), Sbar_DrawPic(), Sbar_DrawStretchPic(), Sbar_DrawWeapon(), Sbar_DrawXNum(), Sbar_FinaleOverlay(), Sbar_IntermissionOverlay(), Sbar_Score(), SCR_DrawBrand(), SCR_DrawNet(), SCR_DrawPause(), SCR_DrawTouchscreenOverlay(), SCR_DrawTurtle(), SHOWLMP_drawall(), and VM_drawpic().
DrawQ_RecalcView()
void DrawQ_RecalcView (void)
Definition at line 1460 of file gl_draw.c.
{
    DrawQ_FlushUI();
    if(r_refdef.draw2dstage)
        r_refdef.draw2dstage = -1; // next draw call will set viewport etc. again
}
Referenced by VM_CL_R_SetView().
DrawQ_ResetClipArea()
void DrawQ_ResetClipArea (void)
Definition at line 1448 of file gl_draw.c.
{
    DrawQ_FlushUI();
    GL_ScissorTest(false);
}
Referenced by VM_drawresetcliparea().
DrawQ_RotPic()
void DrawQ_RotPic (float x, float y, cachepic_t * pic, float width, float height, float org_x, float org_y, float angle, float red, float green, float blue, float alpha, int flags)
Definition at line 818 of file gl_draw.c.
{
    float af = DEG2RAD(-angle); // forward
    float ar = DEG2RAD(-angle + 90); // right
    float sinaf = sin(af);
    float cosaf = cos(af);
    float sinar = sin(ar);
    float cosar = cos(ar);
    model_t *mod = CL_Mesh_UI();
    msurface_t *surf;
    int e0, e1, e2, e3;
    if (!pic)
        pic = Draw_CachePic("white");
    // make sure pic is loaded - we don't use the texture here, Mod_Mesh_GetTexture looks up the skinframe by name
    Draw_GetPicTexture(pic);
    if (width == 0)
        width = pic->width;
    if (height == 0)
        height = pic->height;
    surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, pic->name, flags, pic->texflags, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
    e0 = Mod_Mesh_IndexForVertex(mod, surf, x - cosaf *          org_x  - cosar *           org_y , y - sinaf *          org_x  - sinar *           org_y , 0, 0, 0, -1, 0, 0, 0, 0, red, green, blue, alpha);
    e1 = Mod_Mesh_IndexForVertex(mod, surf, x + cosaf * (width - org_x) - cosar *           org_y , y + sinaf * (width - org_x) - sinar *           org_y , 0, 0, 0, -1, 1, 0, 0, 0, red, green, blue, alpha);
    e2 = Mod_Mesh_IndexForVertex(mod, surf, x + cosaf * (width - org_x) + cosar * (height - org_y), y + sinaf * (width - org_x) + sinar * (height - org_y), 0, 0, 0, -1, 1, 1, 0, 0, red, green, blue, alpha);
    e3 = Mod_Mesh_IndexForVertex(mod, surf, x - cosaf *          org_x  + cosar * (height - org_y), y - sinaf *          org_x  + sinar * (height - org_y), 0, 0, 0, -1, 0, 1, 0, 0, red, green, blue, alpha);
    Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
    Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
}
Referenced by VM_drawrotpic().
DrawQ_SetClipArea()
void DrawQ_SetClipArea (float x, float y, float width, float height)
Definition at line 1426 of file gl_draw.c.
{
    int ix, iy, iw, ih;
    DrawQ_FlushUI();
    // We have to convert the con coords into real coords
    // OGL uses bottom to top (origin is in bottom left)
    ix = (int)(0.5 + x * ((float)r_refdef.view.width / vid_conwidth.integer)) + r_refdef.view.x;
    iy = (int)(0.5 + y * ((float)r_refdef.view.height / vid_conheight.integer)) + r_refdef.view.y;
    iw = (int)(0.5 + width * ((float)r_refdef.view.width / vid_conwidth.integer));
    ih = (int)(0.5 + height * ((float)r_refdef.view.height / vid_conheight.integer));
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        GL_Scissor(ix, vid.height - iy - ih, iw, ih);
        break;
    }
    GL_ScissorTest(true);
}
Referenced by VM_drawsetcliparea().
DrawQ_Start()
void DrawQ_Start (void)
Definition at line 788 of file gl_draw.c.
{
    r_refdef.draw2dstage = 1;
    R_ResetViewRendering2D_Common(0, NULL, NULL, 0, 0, vid.width, vid.height, vid_conwidth.integer, vid_conheight.integer);
}
Referenced by R_RenderView(), and SCR_DrawScreen().
DrawQ_String()
float DrawQ_String (float x, float y, const char * text, size_t maxlen, float scalex, float scaley, float basered, float basegreen, float baseblue, float basealpha, int flags, int * outcolor, qbool ignorecolorcodes, const dp_font_t * fnt)
Definition at line 1318 of file gl_draw.c.
{
    return DrawQ_String_Scale(startx, starty, text, maxlen, w, h, 1, 1, basered, basegreen, baseblue, basealpha, flags, outcolor, ignorecolorcodes, fnt);
}
Referenced by CL_DrawVideo_DisplaySubtitleLine(), Con_DisplayLineFunc(), Con_DrawConsole(), Con_DrawInput(), M_DrawCharacter(), M_ItemPrint(), M_Print(), M_PrintColored(), M_PrintRed(), R_Shadow_EditLights_DrawSelectedLightProperties(), R_TimeReport_EndFrame(), Sbar_DeathmatchOverlay(), Sbar_DrawCharacter(), Sbar_DrawString(), Sbar_DrawWeapon(), Sbar_PrintScoreboardItem(), Sbar_ShowFPS(), SCR_DrawCenterString(), SCR_DrawCurlDownload(), SCR_DrawInfobarString(), SCR_DrawLoadingStack_r(), SCR_DrawNetGraph_DrawGraph(), SCR_DrawQWDownload(), and SCR_DrawTouchscreenOverlay().
DrawQ_String_Scale()
float DrawQ_String_Scale (float x, float y, const char * text, size_t maxlen, float sizex, float sizey, float scalex, float scaley, float basered, float basegreen, float baseblue, float basealpha, int flags, int * outcolor, qbool ignorecolorcodes, const dp_font_t * fnt)
Definition at line 1083 of file gl_draw.c.
{
    int shadow, colorindex = STRING_COLOR_DEFAULT;
    size_t i;
    float x = startx, y, s, t, u, v, thisw;
    Uchar ch, mapch, nextch;
    Uchar prevch = 0; // used for kerning
    int map_index = 0;
    ft2_font_map_t *map = NULL;     // the currently used map
    ft2_font_map_t *fontmap = NULL; // the font map for the size
    float ftbase_y;
    const char *text_start = text;
    float kx, ky;
    ft2_font_t *ft2 = fnt->ft2;
    qbool snap = true;
    float pix_x, pix_y;
    size_t bytes_left;
    float dw, dh;
    const float *width_of;
    model_t *mod = CL_Mesh_UI();
    msurface_t *surf = NULL;
    int e0, e1, e2, e3;
    int tw, th;
    tw = Draw_GetPicWidth(fnt->pic);
    th = Draw_GetPicHeight(fnt->pic);
    if (!h) h = w;
    if (!h) {
        h = w = 1;
        snap = false;
    }
    starty -= (fnt->settings.scale - 1) * h * 0.5 - fnt->settings.voffset*h; // center & offset
    w *= fnt->settings.scale;
    h *= fnt->settings.scale;
    if (ft2 != NULL)
    {
        if (snap)
            map_index = Font_IndexForSize(ft2, h, &w, &h);
        else
            map_index = Font_IndexForSize(ft2, h, NULL, NULL);
        fontmap = Font_MapForIndex(ft2, map_index);
    }
    dw = w * sw;
    dh = h * sh;
    // draw the font at its baseline when using freetype
    //ftbase_x = 0;
    ftbase_y = dh * (4.5/6.0);
    if (maxlen < 1)
        maxlen = 1<<30;
    if(!r_draw2d.integer && !r_draw2d_force)
        return startx + DrawQ_TextWidth_UntilWidth_TrackColors_Scale(text, &maxlen, w, h, sw, sh, NULL, ignorecolorcodes, fnt, 1000000000);
    //ftbase_x = snap_to_pixel_x(ftbase_x);
    if(snap)
    {
        startx = snap_to_pixel_x(startx, 0.4);
        starty = snap_to_pixel_y(starty, 0.4);
        ftbase_y = snap_to_pixel_y(ftbase_y, 0.3);
    }
    pix_x = vid.width / vid_conwidth.value;
    pix_y = vid.height / vid_conheight.value;
    if (fontmap)
        width_of = fnt->width_of_ft2[map_index];
    else
        width_of = fnt->width_of;
    for (shadow = r_textshadow.value != 0 && basealpha > 0;shadow >= 0;shadow--)
    {
        prevch = 0;
        text = text_start;
        if (!outcolor || *outcolor == -1)
            colorindex = STRING_COLOR_DEFAULT;
        else
            colorindex = *outcolor;
        DrawQ_GetTextColor(DrawQ_Color, colorindex, basered, basegreen, baseblue, basealpha, shadow != 0);
        x = startx;
        y = starty;
        /*
        if (shadow)
        {
            x += r_textshadow.value * vid.width / vid_conwidth.value;
            y += r_textshadow.value * vid.height / vid_conheight.value;
        }
        */
        while (((bytes_left = maxlen - (text - text_start)) > 0) && *text)
        {
            nextch = ch = u8_getnchar(text, &text, bytes_left);
            i = text - text_start;
            if (!ch)
                break;
            if (ch == ' ' && !fontmap)
            {
                x += width_of[(int) ' '] * dw;
                continue;
            }
            if (ch == STRING_COLOR_TAG && !ignorecolorcodes && i < maxlen)
            {
                ch = *text; // colors are ascii, so no u8_ needed
                if (ch <= '9' && ch >= '0') // ^[0-9] found
                {
                    colorindex = ch - '0';
                    DrawQ_GetTextColor(DrawQ_Color, colorindex, basered, basegreen, baseblue, basealpha, shadow != 0);
                    ++text;
                    ++i;
                    continue;
                }
                else if (ch == STRING_COLOR_RGB_TAG_CHAR && i+3 < maxlen ) // ^x found
                {
                    const char *text_p = &text[1];
                    int tempcolorindex = RGBstring_to_colorindex(text_p);
                    if(tempcolorindex)
                    {
                        colorindex = tempcolorindex;
                        DrawQ_GetTextColor(DrawQ_Color, colorindex, basered, basegreen, baseblue, basealpha, shadow != 0);
                        i+=4;
                        text+=4;
                        continue;
                    }
                }
                else if (ch == STRING_COLOR_TAG)
                {
                    i++;
                    text++;
                }
                i--;
            }
            // get the backup
            ch = nextch;
            // using a value of -1 for the oldstyle map because NULL means uninitialized...
            // this way we don't need to rebind fnt->tex for every old-style character
            // E000..E0FF: emulate old-font characters (to still have smileys and such available)
            if (shadow)
            {
                x += 1.0/pix_x * r_textshadow.value;
                y += 1.0/pix_y * r_textshadow.value;
            }
            if (!fontmap || (ch <= 0xFF && fontmap->glyphs[ch].image) || (ch >= 0xE000 && ch <= 0xE0FF))
            {
                if (ch >= 0xE000)
                    ch -= 0xE000;
                if (ch > 0xFF)
                    goto out;
                if (fontmap)
                    map = ft2_oldstyle_map;
                prevch = 0;
                //num = (unsigned char) text[i];
                //thisw = fnt->width_of[num];
                thisw = fnt->width_of[ch];
                // FIXME make these smaller to just include the occupied part of the character for slightly faster rendering
                if (r_nearest_conchars.integer)
                {
                    s = (ch & 15)*0.0625f;
                    t = (ch >> 4)*0.0625f;
                    u = 0.0625f * thisw;
                    v = 0.0625f;
                }
                else
                {
                    s = (ch & 15)*0.0625f + (0.5f / tw);
                    t = (ch >> 4)*0.0625f + (0.5f / th);
                    u = 0.0625f * thisw - (1.0f / tw);
                    v = 0.0625f - (1.0f / th);
                }
                surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, fnt->pic->name, flags, TEXF_ALPHA | TEXF_CLAMP, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
                e0 = Mod_Mesh_IndexForVertex(mod, surf, x         , y   , 10, 0, 0, -1, s  , t  , 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e1 = Mod_Mesh_IndexForVertex(mod, surf, x+dw*thisw, y   , 10, 0, 0, -1, s+u, t  , 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e2 = Mod_Mesh_IndexForVertex(mod, surf, x+dw*thisw, y+dh, 10, 0, 0, -1, s+u, t+v, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e3 = Mod_Mesh_IndexForVertex(mod, surf, x         , y+dh, 10, 0, 0, -1, s  , t+v, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
                Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
                x += width_of[ch] * dw;
            } else {
                if (!map || map == ft2_oldstyle_map || ch != prevch)
                {
                    Font_GetMapForChar(ft2, map_index, ch, &map, &mapch);
                    if (!map)
                    {
                        shadow = -1;
                        break;
                    }
                }
                thisw = map->glyphs[mapch].advance_x;
                //x += ftbase_x;
                y += ftbase_y;
                if (prevch && Font_GetKerningForMap(ft2, map_index, w, h, prevch, ch, &kx, &ky))
                {
                    x += kx * dw;
                    y += ky * dh;
                }
                else
                    kx = ky = 0;
                surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, map->pic->name, flags, TEXF_ALPHA | TEXF_CLAMP, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
                e0 = Mod_Mesh_IndexForVertex(mod, surf, x + dw * map->glyphs[mapch].vxmin, y + dh * map->glyphs[mapch].vymin, 10, 0, 0, -1, map->glyphs[mapch].txmin, map->glyphs[mapch].tymin, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e1 = Mod_Mesh_IndexForVertex(mod, surf, x + dw * map->glyphs[mapch].vxmax, y + dh * map->glyphs[mapch].vymin, 10, 0, 0, -1, map->glyphs[mapch].txmax, map->glyphs[mapch].tymin, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e2 = Mod_Mesh_IndexForVertex(mod, surf, x + dw * map->glyphs[mapch].vxmax, y + dh * map->glyphs[mapch].vymax, 10, 0, 0, -1, map->glyphs[mapch].txmax, map->glyphs[mapch].tymax, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                e3 = Mod_Mesh_IndexForVertex(mod, surf, x + dw * map->glyphs[mapch].vxmin, y + dh * map->glyphs[mapch].vymax, 10, 0, 0, -1, map->glyphs[mapch].txmin, map->glyphs[mapch].tymax, 0, 0, DrawQ_Color[0], DrawQ_Color[1], DrawQ_Color[2], DrawQ_Color[3]);
                Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
                Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
                //x -= ftbase_x;
                y -= ftbase_y;
                x += thisw * dw;
                //prevmap = map;
                prevch = ch;
            }
out:
            if (shadow)
            {
                x -= 1.0/pix_x * r_textshadow.value;
                y -= 1.0/pix_y * r_textshadow.value;
            }
        }
    }
    if (outcolor)
        *outcolor = colorindex;
    // note: this relies on the proper text (not shadow) being drawn last
    return x;
}
Referenced by DrawQ_String(), VM_drawcharacter(), VM_drawcolorcodedstring(), and VM_drawstring().
DrawQ_SuperPic()
void DrawQ_SuperPic (float x, float y, cachepic_t * pic, float width, float height, float s1, float t1, float r1, float g1, float b1, float a1, float s2, float t2, float r2, float g2, float b2, float a2, float s3, float t3, float r3, float g3, float b3, float a3, float s4, float t4, float r4, float g4, float b4, float a4, int flags)
Definition at line 1378 of file gl_draw.c.
{
    model_t *mod = CL_Mesh_UI();
    msurface_t *surf;
    int e0, e1, e2, e3;
    if (!pic)
        pic = Draw_CachePic("white");
    // make sure pic is loaded - we don't use the texture here, Mod_Mesh_GetTexture looks up the skinframe by name
    Draw_GetPicTexture(pic);
    if (width == 0)
        width = pic->width;
    if (height == 0)
        height = pic->height;
    surf = Mod_Mesh_AddSurface(mod, Mod_Mesh_GetTexture(mod, pic->name, flags, pic->texflags, MATERIALFLAG_WALL | MATERIALFLAG_VERTEXCOLOR | MATERIALFLAG_ALPHAGEN_VERTEX | MATERIALFLAG_ALPHA | MATERIALFLAG_BLENDED | MATERIALFLAG_NOSHADOW), true);
    e0 = Mod_Mesh_IndexForVertex(mod, surf, x        , y         , 0, 0, 0, -1, s1, t1, 0, 0, r1, g1, b1, a1);
    e1 = Mod_Mesh_IndexForVertex(mod, surf, x + width, y         , 0, 0, 0, -1, s2, t2, 0, 0, r2, g2, b2, a2);
    e2 = Mod_Mesh_IndexForVertex(mod, surf, x + width, y + height, 0, 0, 0, -1, s4, t4, 0, 0, r4, g4, b4, a4);
    e3 = Mod_Mesh_IndexForVertex(mod, surf, x        , y + height, 0, 0, 0, -1, s3, t3, 0, 0, r3, g3, b3, a3);
    Mod_Mesh_AddTriangle(mod, surf, e0, e1, e2);
    Mod_Mesh_AddTriangle(mod, surf, e0, e2, e3);
}
Referenced by CL_DrawVideo(), Con_DrawConsole(), M_Options_ColorControl_Draw(), Sbar_Draw(), Sbar_DrawGauge(), and VM_drawsubpic().
DrawQ_TextWidth()
float DrawQ_TextWidth (const char * text, size_t maxlen, float w, float h, qbool ignorecolorcodes, const dp_font_t * fnt)
Definition at line 1328 of file gl_draw.c.
{
    return DrawQ_TextWidth_UntilWidth(text, &maxlen, w, h, ignorecolorcodes, fnt, 1000000000);
}
Referenced by CL_DrawVideo_WordWidthFunc(), Con_DrawConsole(), Con_DrawInput(), Con_WordWidthFunc(), Sbar_ShowFPS(), SCR_DrawCenterString(), SCR_DrawCurlDownload(), SCR_DrawInfobarString(), SCR_DrawLoadingStack_r(), SCR_DrawQWDownload(), and SCR_DrawTouchscreenOverlay().
DrawQ_TextWidth_UntilWidth()
float DrawQ_TextWidth_UntilWidth (const char * text, size_t * maxlen, float w, float h, qbool ignorecolorcodes, const dp_font_t * fnt, float maxWidth)
Definition at line 1333 of file gl_draw.c.
{
    return DrawQ_TextWidth_UntilWidth_TrackColors(text, maxlen, w, h, NULL, ignorecolorcodes, fnt, maxWidth);
}
Referenced by CL_DrawVideo_WordWidthFunc(), Con_WordWidthFunc(), and DrawQ_TextWidth().
DrawQ_TextWidth_UntilWidth_TrackColors()
float DrawQ_TextWidth_UntilWidth_TrackColors (const char * text, size_t * maxlen, float w, float h, int * outcolor, qbool ignorecolorcodes, const dp_font_t * fnt, float maxwidth)
Definition at line 1323 of file gl_draw.c.
{
    return DrawQ_TextWidth_UntilWidth_TrackColors_Scale(text, maxlen, w, h, 1, 1, outcolor, ignorecolorcodes, fnt, maxwidth);
}
Referenced by Con_DrawInput(), and DrawQ_TextWidth_UntilWidth().
DrawQ_TextWidth_UntilWidth_TrackColors_Scale()
float DrawQ_TextWidth_UntilWidth_TrackColors_Scale (const char * text, size_t * maxlen, float w, float h, float sw, float sh, int * outcolor, qbool ignorecolorcodes, const dp_font_t * fnt, float maxwidth)
Definition at line 926 of file gl_draw.c.
{
    const char *text_start = text;
    int colorindex;
    size_t i;
    float x = 0;
    Uchar ch, mapch, nextch;
    Uchar prevch = 0; // used for kerning
    float kx;
    int map_index = 0;
    size_t bytes_left;
    ft2_font_map_t *fontmap = NULL;
    ft2_font_map_t *map = NULL;
    ft2_font_t *ft2 = fnt->ft2;
    // float ftbase_x;
    qbool snap = true;
    qbool least_one = false;
    float dw; // display w
    //float dh; // display h
    const float *width_of;
    if (!h) h = w;
    if (!h) {
        w = h = 1;
        snap = false;
    }
    // do this in the end
    w *= fnt->settings.scale;
    h *= fnt->settings.scale;
    // find the most fitting size:
    if (ft2 != NULL)
    {
        if (snap)
            map_index = Font_IndexForSize(ft2, h, &w, &h);
        else
            map_index = Font_IndexForSize(ft2, h, NULL, NULL);
        fontmap = Font_MapForIndex(ft2, map_index);
    }
    dw = w * sw;
    //dh = h * sh;
    if (*maxlen < 1)
        *maxlen = 1<<30;
    if (!outcolor || *outcolor == -1)
        colorindex = STRING_COLOR_DEFAULT;
    else
        colorindex = *outcolor;
    // maxwidth /= fnt->scale; // w and h are multiplied by it already
    // ftbase_x = snap_to_pixel_x(0);
    if(maxwidth <= 0)
    {
        least_one = true;
        maxwidth = -maxwidth;
    }
    //if (snap)
    //  x = snap_to_pixel_x(x, 0.4); // haha, it's 0 anyway
    if (fontmap)
        width_of = fnt->width_of_ft2[map_index];
    else
        width_of = fnt->width_of;
    i = 0;
    while (((bytes_left = *maxlen - (text - text_start)) > 0) && *text)
    {
        size_t i0 = i;
        nextch = ch = u8_getnchar(text, &text, bytes_left);
        i = text - text_start;
        if (!ch)
            break;
        if (ch == ' ' && !fontmap)
        {
            if(!least_one || i0) // never skip the first character
                if(x + width_of[(int) ' '] * dw > maxwidth)
                {
                    i = i0;
                    break; // oops, can't draw this
                }
            x += width_of[(int) ' '] * dw;
            continue;
        }
        if (ch == STRING_COLOR_TAG && !ignorecolorcodes && i < *maxlen)
        {
            ch = *text; // colors are ascii, so no u8_ needed
            if (ch <= '9' && ch >= '0') // ^[0-9] found
            {
                colorindex = ch - '0';
                ++text;
                ++i;
                continue;
            }
            else if (ch == STRING_COLOR_RGB_TAG_CHAR && i + 3 < *maxlen ) // ^x found
            {
                const char *text_p = &text[1];
                int tempcolorindex = RGBstring_to_colorindex(text_p);
                if (tempcolorindex)
                {
                    colorindex = tempcolorindex;
                    i+=4;
                    text += 4;
                    continue;
                }
            }
            else if (ch == STRING_COLOR_TAG) // ^^ found
            {
                i++;
                text++;
            }
            i--;
        }
        ch = nextch;
        if (!fontmap || (ch <= 0xFF && fontmap->glyphs[ch].image) || (ch >= 0xE000 && ch <= 0xE0FF))
        {
            if (ch > 0xE000)
                ch -= 0xE000;
            if (ch > 0xFF)
                continue;
            if (fontmap)
                map = ft2_oldstyle_map;
            prevch = 0;
            if(!least_one || i0) // never skip the first character
                if(x + width_of[ch] * dw > maxwidth)
                {
                    i = i0;
                    break; // oops, can't draw this
                }
            x += width_of[ch] * dw;
        } else {
            if (!map || map == ft2_oldstyle_map || ch != prevch)
            {
                Font_GetMapForChar(ft2, map_index, ch, &map, &mapch);
                if (!map)
                    break;
            }
            if (prevch && Font_GetKerningForMap(ft2, map_index, w, h, prevch, ch, &kx, NULL))
                x += kx * dw;
            x += map->glyphs[mapch].advance_x * dw;
            prevch = ch;
        }
    }
    *maxlen = i;
    if (outcolor)
        *outcolor = colorindex;
    return x;
}
Referenced by DrawQ_String_Scale(), DrawQ_TextWidth_UntilWidth_TrackColors(), and VM_stringwidth().
Variable Documentation
dp_fonts
dp_fonts_t dp_fonts extern
Definition at line 50 of file gl_draw.c.
Referenced by FindFont(), font_shutdown(), getdrawfont(), getdrawfontnum(), GL_Draw_Init(), gl_draw_start(), LoadFont_f(), and VM_loadfont().
DrawQ_Color
float DrawQ_Color[4] extern
Definition at line 1082 of file gl_draw.c.
Referenced by DrawQ_String_Scale(), and VM_drawcolorcodedstring().
drawtexturepool
rtexturepool_t* drawtexturepool extern
Definition at line 75 of file gl_draw.c.
Referenced by gl_draw_shutdown(), gl_draw_start(), and LoadFont().