DarkPlaces: ft2_fontdefs.h File Reference
ft2_fontdefs.h File Reference
Data Structures
struct glyph_slot_t
struct ft2_font_map_t
struct font_incmap_t
struct ft2_attachment_t
Macros
#define FONT_CHARS_PER_LINE 16
#define FONT_CHAR_LINES 16
#define FONT_CHARS_PER_MAP (FONT_CHARS_PER_LINE * FONT_CHAR_LINES)
#define INCMAP_START 0x110000
Functions
qbool Font_LoadMapForIndex (ft2_font_t *font, int map_index, Uchar _ch, ft2_font_map_t **outmap)
void font_start (void)
void font_shutdown (void)
void font_newmap (void)
Macro Definition Documentation
FONT_CHAR_LINES
#define FONT_CHAR_LINES 16
Definition at line 7 of file ft2_fontdefs.h.
FONT_CHARS_PER_LINE
#define FONT_CHARS_PER_LINE 16
Definition at line 6 of file ft2_fontdefs.h.
FONT_CHARS_PER_MAP
#define FONT_CHARS_PER_MAP (FONT_CHARS_PER_LINE * FONT_CHAR_LINES)
Definition at line 8 of file ft2_fontdefs.h.
INCMAP_START
#define INCMAP_START 0x110000
Definition at line 11 of file ft2_fontdefs.h.
Function Documentation
Font_LoadMapForIndex()
qbool Font_LoadMapForIndex (ft2_font_t * font, int map_index, Uchar _ch, ft2_font_map_t ** outmap)
Definition at line 1899 of file ft2.c.
{
    if (map_index < 0 || map_index >= MAX_FONT_SIZES)
        return false;
    // the first map must have been loaded already
    if (!font->font_maps[map_index])
        return false;
    alert_legacy_font_api("Font_LoadMapForIndex");
    return Font_LoadMap(font, font->font_maps[map_index], ch, outmap, NULL, false);
}
font_newmap()
void font_newmap (void)
Definition at line 439 of file ft2.c.
{
}
Referenced by gl_draw_newmap().
font_shutdown()
void font_shutdown (void)
Definition at line 425 of file ft2.c.
{
    int i;
    for (i = 0; i < dp_fonts.maxsize; ++i)
    {
        if (dp_fonts.f[i].ft2)
        {
            Font_UnloadFont(dp_fonts.f[i].ft2);
            dp_fonts.f[i].ft2 = NULL;
        }
    }
    Font_CloseLibrary();
}
Referenced by gl_draw_shutdown().
font_start()
void font_start (void)
Definition at line 404 of file ft2.c.
{
    if (!Font_OpenLibrary())
        return;
    if (qFT_Init_FreeType(&font_ft2lib))
    {
        Con_Print(CON_ERROR "ERROR: Failed to initialize the FreeType2 library!\n");
        Font_CloseLibrary();
        return;
    }
    font_mempool = Mem_AllocPool("FONT", 0, NULL);
    if (!font_mempool)
    {
        Con_Print(CON_ERROR "ERROR: Failed to allocate FONT memory pool!\n");
        Font_CloseLibrary();
        return;
    }
}
Referenced by gl_draw_start().