DarkPlaces: gl_backend.h File Reference
gl_backend.h File Reference
Macros
#define POLYGONELEMENTS_MAXPOINTS 258
#define QUADELEMENTS_MAXQUADS 128
Functions
void R_Viewport_TransformToScreen (const r_viewport_t *v, const vec4_t in, vec4_t out)
qbool R_ScissorForBBox (const float *mins, const float *maxs, int *scissor)
void R_Viewport_InitOrtho (r_viewport_t *v, const matrix4x4_t *cameramatrix, int x, int y, int width, int height, float x1, float y1, float x2, float y2, float zNear, float zFar, const float *nearplane)
void R_Viewport_InitOrtho3D (r_viewport_t *v, const matrix4x4_t *cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float nearclip, float farclip, const float *nearplane)
void R_Viewport_InitPerspective (r_viewport_t *v, const matrix4x4_t *cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float zNear, float zFar, const float *nearplane)
void R_Viewport_InitPerspectiveInfinite (r_viewport_t *v, const matrix4x4_t *cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float zNear, const float *nearplane)
void R_Viewport_InitCubeSideView (r_viewport_t *v, const matrix4x4_t *cameramatrix, int side, int size, float nearclip, float farclip, const float *nearplane)
void R_Viewport_InitRectSideView (r_viewport_t *v, const matrix4x4_t *cameramatrix, int side, int size, int border, float nearclip, float farclip, const float *nearplane, int offsetx, int offsety)
void R_SetViewport (const r_viewport_t *v)
void R_GetViewport (r_viewport_t *v)
void GL_Finish (void)
void GL_BlendFunc (int blendfunc1, int blendfunc2)
void GL_BlendEquationSubtract (qbool negated)
void GL_DepthMask (int state)
void GL_DepthTest (int state)
void GL_DepthFunc (int state)
void GL_DepthRange (float nearfrac, float farfrac)
void R_SetStencil (qbool enable, int writemask, int fail, int zfail, int zpass, int compare, int comparereference, int comparemask)
void GL_PolygonOffset (float planeoffset, float depthoffset)
void GL_CullFace (int state)
void GL_AlphaToCoverage (qbool state)
void GL_ColorMask (int r, int g, int b, int a)
void GL_Color (float cr, float cg, float cb, float ca)
void GL_ActiveTexture (unsigned int num)
void GL_Scissor (int x, int y, int width, int height)
void GL_ScissorTest (int state)
void GL_Clear (int mask, const float *colorvalue, float depthvalue, int stencilvalue)
void GL_ReadPixelsBGRA (int x, int y, int width, int height, unsigned char *outpixels)
int R_Mesh_CreateFramebufferObject (rtexture_t *depthtexture, rtexture_t *colortexture, rtexture_t *colortexture2, rtexture_t *colortexture3, rtexture_t *colortexture4)
void R_Mesh_DestroyFramebufferObject (int fbo)
void R_Mesh_SetRenderTargets (int fbo, rtexture_t *depthtexture, rtexture_t *colortexture, rtexture_t *colortexture2, rtexture_t *colortexture3, rtexture_t *colortexture4)
unsigned int GL_Backend_CompileProgram (int vertexstrings_count, const char **vertexstrings_list, int geometrystrings_count, const char **geometrystrings_list, int fragmentstrings_count, const char **fragmentstrings_list)
void GL_Backend_FreeProgram (unsigned int prog)
void gl_backend_init (void)
void R_Mesh_Start (void)
void R_Mesh_Finish (void)
r_meshbuffer_t * R_Mesh_CreateMeshBuffer (const void *data, size_t size, const char *name, qbool isindexbuffer, qbool isuniformbuffer, qbool isdynamic, qbool isindex16)
void R_Mesh_UpdateMeshBuffer (r_meshbuffer_t *buffer, const void *data, size_t size, qbool subdata, size_t offset)
void R_Mesh_DestroyMeshBuffer (r_meshbuffer_t *buffer)
void GL_Mesh_ListVBOs (qbool printeach)
void R_Mesh_PrepareVertices_Vertex3f (int numvertices, const float *vertex3f, const r_meshbuffer_t *buffer, int bufferoffset)
void R_Mesh_PrepareVertices_Generic_Arrays (int numvertices, const float *vertex3f, const float *color4f, const float *texcoord2f)
void R_Mesh_PrepareVertices_Mesh_Arrays (int numvertices, const float *vertex3f, const float *svector3f, const float *tvector3f, const float *normal3f, const float *color4f, const float *texcoordtexture2f, const float *texcoordlightmap2f)
void R_EntityMatrix (const matrix4x4_t *matrix)
void R_Mesh_VertexPointer (int components, int gltype, size_t stride, const void *pointer, const r_meshbuffer_t *vertexbuffer, size_t bufferoffset)
void R_Mesh_ColorPointer (int components, int gltype, size_t stride, const void *pointer, const r_meshbuffer_t *vertexbuffer, size_t bufferoffset)
void R_Mesh_TexCoordPointer (unsigned int unitnum, int components, int gltype, size_t stride, const void *pointer, const r_meshbuffer_t *vertexbuffer, size_t bufferoffset)
int R_Mesh_TexBound (unsigned int unitnum, int id)
void R_Mesh_CopyToTexture (rtexture_t *tex, int tx, int ty, int sx, int sy, int width, int height)
void R_Mesh_TexBind (unsigned int unitnum, rtexture_t *tex)
void R_Mesh_ResetTextureState (void)
void R_Mesh_ClearBindingsForTexture (int texnum)
void R_Mesh_Draw (int firstvertex, int numvertices, int firsttriangle, int numtriangles, const int *element3i, const r_meshbuffer_t *element3i_indexbuffer, int element3i_bufferoffset, const unsigned short *element3s, const r_meshbuffer_t *element3s_indexbuffer, int element3s_bufferoffset)
qbool SCR_ScreenShot (char *filename, unsigned char *buffer1, unsigned char *buffer2, int x, int y, int width, int height, qbool flipx, qbool flipy, qbool flipdiagonal, qbool jpeg, qbool png, qbool gammacorrect, qbool keep_alpha)
void R_ClearScreen (qbool fogcolor)
Variables
r_viewport_t gl_viewport
matrix4x4_t gl_modelmatrix
matrix4x4_t gl_viewmatrix
matrix4x4_t gl_modelviewmatrix
matrix4x4_t gl_projectionmatrix
matrix4x4_t gl_modelviewprojectionmatrix
float gl_modelview16f [16]
float gl_modelviewprojection16f [16]
qbool gl_modelmatrixchanged
int polygonelement3i [(POLYGONELEMENTS_MAXPOINTS-2) *3]
unsigned short polygonelement3s [(POLYGONELEMENTS_MAXPOINTS-2) *3]
int quadelement3i [QUADELEMENTS_MAXQUADS *6]
unsigned short quadelement3s [QUADELEMENTS_MAXQUADS *6]
cvar_t gl_debug
cvar_t gl_paranoid
cvar_t gl_printcheckerror
Macro Definition Documentation
POLYGONELEMENTS_MAXPOINTS
#define POLYGONELEMENTS_MAXPOINTS 258
Definition at line 15 of file gl_backend.h.
QUADELEMENTS_MAXQUADS
#define QUADELEMENTS_MAXQUADS 128
Definition at line 18 of file gl_backend.h.
Function Documentation
GL_ActiveTexture()
void GL_ActiveTexture (unsigned int num)
Definition at line 1147 of file gl_backend.c.
{
    if (gl_state.unit != num)
    {
        gl_state.unit = num;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            qglActiveTexture(GL_TEXTURE0 + gl_state.unit);CHECKGLERROR
            break;
        }
    }
}
Referenced by GL_TextureMode_f(), R_LoadTextureDDSFile(), R_Mesh_CopyToTexture(), R_Mesh_TexBind(), R_SaveTextureDDSFile(), R_Textures_Frame(), R_UploadFullTexture(), and R_UploadPartialTexture().
GL_AlphaToCoverage()
void GL_AlphaToCoverage (qbool state)
Definition at line 1380 of file gl_backend.c.
{
    if (gl_state.alphatocoverage != state)
    {
        gl_state.alphatocoverage = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GLES2:
            break;
        case RENDERPATH_GL32:
#ifndef USE_GLES2
            // alpha to coverage turns the alpha value of the pixel into 0%, 25%, 50%, 75% or 100% by masking the multisample fragments accordingly
            CHECKGLERROR
            if (gl_state.alphatocoverage)
            {
                qglEnable(GL_SAMPLE_ALPHA_TO_COVERAGE);CHECKGLERROR
//              qglEnable(GL_MULTISAMPLE);CHECKGLERROR
            }
            else
            {
                qglDisable(GL_SAMPLE_ALPHA_TO_COVERAGE);CHECKGLERROR
//              qglDisable(GL_MULTISAMPLE);CHECKGLERROR
            }
#endif
            break;
        }
    }
}
Referenced by R_SetupShader_DeferredLight(), R_SetupShader_DepthOrShadow(), R_SetupShader_Generic(), and R_SetupShader_Surface().
GL_Backend_CompileProgram()
unsigned int GL_Backend_CompileProgram (int vertexstrings_count, const char ** vertexstrings_list, int geometrystrings_count, const char ** geometrystrings_list, int fragmentstrings_count, const char ** fragmentstrings_list)
Definition at line 1592 of file gl_backend.c.
{
    GLint programlinked;
    GLuint programobject = 0;
    char linklog[MAX_INPUTLINE];
    CHECKGLERROR
    programobject = qglCreateProgram();CHECKGLERROR
    if (!programobject)
        return 0;
    qglBindAttribLocation(programobject, GLSLATTRIB_POSITION , "Attrib_Position" );
    qglBindAttribLocation(programobject, GLSLATTRIB_COLOR    , "Attrib_Color"    );
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD0, "Attrib_TexCoord0");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD1, "Attrib_TexCoord1");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD2, "Attrib_TexCoord2");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD3, "Attrib_TexCoord3");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD4, "Attrib_TexCoord4");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD5, "Attrib_TexCoord5");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD6, "Attrib_SkeletalIndex");
    qglBindAttribLocation(programobject, GLSLATTRIB_TEXCOORD7, "Attrib_SkeletalWeight");
#ifndef USE_GLES2
    qglBindFragDataLocation(programobject, 0, "dp_FragColor");
#endif
    CHECKGLERROR
    if (vertexstrings_count && !GL_Backend_CompileShader(programobject, GL_VERTEX_SHADER, "vertex", vertexstrings_count, vertexstrings_list))
        goto cleanup;
#if defined(GL_GEOMETRY_SHADER) && !defined(USE_GLES2)
    if (geometrystrings_count && !GL_Backend_CompileShader(programobject, GL_GEOMETRY_SHADER, "geometry", geometrystrings_count, geometrystrings_list))
        goto cleanup;
#endif
    if (fragmentstrings_count && !GL_Backend_CompileShader(programobject, GL_FRAGMENT_SHADER, "fragment", fragmentstrings_count, fragmentstrings_list))
        goto cleanup;
    qglLinkProgram(programobject);CHECKGLERROR
    qglGetProgramiv(programobject, GL_LINK_STATUS, &programlinked);CHECKGLERROR
    qglGetProgramInfoLog(programobject, sizeof(linklog), NULL, linklog);CHECKGLERROR
    if (linklog[0])
    {
        if (strstr(linklog, "error") || strstr(linklog, "ERROR") || strstr(linklog, "Error") || strstr(linklog, "WARNING") || strstr(linklog, "warning") || strstr(linklog, "Warning") || developer_extra.integer)
            Con_DPrintf("program link log:\n%s\n", linklog);
        // software vertex shader is ok but software fragment shader is WAY
        // too slow, fail program if so.
        // NOTE: this string might be ATI specific, but that's ok because the
        // ATI R300 chip (Radeon 9500-9800/X300) is the most likely to use a
        // software fragment shader due to low instruction and dependent
        // texture limits.
        if (strstr(linklog, "fragment shader will run in software"))
            programlinked = false;
    }
    if (!programlinked)
        goto cleanup;
    return programobject;
cleanup:
    qglDeleteProgram(programobject);CHECKGLERROR
    return 0;
}
Referenced by R_GLSL_CompilePermutation().
GL_Backend_FreeProgram()
void GL_Backend_FreeProgram (unsigned int prog)
Definition at line 1658 of file gl_backend.c.
{
    CHECKGLERROR
    qglDeleteProgram(prog);
    CHECKGLERROR
}
Referenced by R_GLSL_Restart_f().
gl_backend_init()
void gl_backend_init (void)
Definition at line 340 of file gl_backend.c.
{
    int i;
    for (i = 0;i < POLYGONELEMENTS_MAXPOINTS - 2;i++)
    {
        polygonelement3s[i * 3 + 0] = 0;
        polygonelement3s[i * 3 + 1] = i + 1;
        polygonelement3s[i * 3 + 2] = i + 2;
    }
    // elements for rendering a series of quads as triangles
    for (i = 0;i < QUADELEMENTS_MAXQUADS;i++)
    {
        quadelement3s[i * 6 + 0] = i * 4;
        quadelement3s[i * 6 + 1] = i * 4 + 1;
        quadelement3s[i * 6 + 2] = i * 4 + 2;
        quadelement3s[i * 6 + 3] = i * 4;
        quadelement3s[i * 6 + 4] = i * 4 + 2;
        quadelement3s[i * 6 + 5] = i * 4 + 3;
    }
    for (i = 0;i < (POLYGONELEMENTS_MAXPOINTS - 2)*3;i++)
        polygonelement3i[i] = polygonelement3s[i];
    for (i = 0;i < QUADELEMENTS_MAXQUADS*6;i++)
        quadelement3i[i] = quadelement3s[i];
    Cvar_RegisterVariable(&r_render);
    Cvar_RegisterVariable(&r_renderview);
    Cvar_RegisterVariable(&r_waterwarp);
    Cvar_RegisterVariable(&gl_polyblend);
    Cvar_RegisterVariable(&v_flipped);
    Cvar_RegisterVariable(&gl_debug);
    Cvar_RegisterVariable(&gl_paranoid);
    Cvar_RegisterVariable(&gl_printcheckerror);
    Cmd_AddCommand(CF_CLIENT, "gl_vbostats", GL_VBOStats_f, "prints a list of all buffer objects (vertex data and triangle elements) and total video memory used by them");
    R_RegisterModule("GL_Backend", gl_backend_start, gl_backend_shutdown, gl_backend_newmap, gl_backend_devicelost, gl_backend_devicerestored);
}
GL_BlendEquationSubtract()
void GL_BlendEquationSubtract (qbool negated)
Definition at line 2205 of file gl_backend.c.
{
    CHECKGLERROR
    if(negated)
    {
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            qglBlendEquation(GL_FUNC_REVERSE_SUBTRACT);CHECKGLERROR
            break;
        }
    }
    else
    {
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            qglBlendEquation(GL_FUNC_ADD);CHECKGLERROR
            break;
        }
    }
}
Referenced by R_DrawCorona(), and R_Shadow_RenderLighting().
GL_BlendFunc()
void GL_BlendFunc (int blendfunc1, int blendfunc2)
Definition at line 1163 of file gl_backend.c.
{
    if (gl_state.blendfunc1 != blendfunc1 || gl_state.blendfunc2 != blendfunc2)
    {
        qbool blendenable;
        gl_state.blendfunc1 = blendfunc1;
        gl_state.blendfunc2 = blendfunc2;
        blendenable = (gl_state.blendfunc1 != GL_ONE || gl_state.blendfunc2 != GL_ZERO);
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            if (qglBlendFuncSeparate)
            {
                qglBlendFuncSeparate(gl_state.blendfunc1, gl_state.blendfunc2, GL_ZERO, GL_ONE);CHECKGLERROR // ELUAN: Adreno 225 (and others) compositing workaround
            }
            else
            {
                qglBlendFunc(gl_state.blendfunc1, gl_state.blendfunc2);CHECKGLERROR
            }
            if (gl_state.blend != blendenable)
            {
                gl_state.blend = blendenable;
                if (!gl_state.blend)
                {
                    qglDisable(GL_BLEND);CHECKGLERROR
                }
                else
                {
                    qglEnable(GL_BLEND);CHECKGLERROR
                }
            }
            break;
        }
    }
}
Referenced by R_BlendView(), R_Bloom_MakeTexture(), R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_DrawSurface_TransparentCallback(), R_DrawTextureSurfaceList_ShowSurfaces(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawDepth(), R_MotionBlurView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_SetupShader_Surface(), R_Shadow_DrawCoronas(), R_Shadow_DrawPrepass(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Lighting(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_VisibleLighting(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
GL_Clear()
void GL_Clear (int mask, const float * colorvalue, float depthvalue, int stencilvalue)
Definition at line 1477 of file gl_backend.c.
{
    // opaque black - if you want transparent black, you'll need to pass in a colorvalue
    static const float blackcolor[4] = {0.0f, 0.0f, 0.0f, 1.0f};
    // prevent warnings when trying to clear a buffer that does not exist
    if (!colorvalue)
        colorvalue = blackcolor;
    if (!vid.stencil)
    {
        mask &= ~GL_STENCIL_BUFFER_BIT;
        stencilvalue = 0;
    }
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        if (mask & GL_COLOR_BUFFER_BIT)
        {
            qglClearColor(colorvalue[0], colorvalue[1], colorvalue[2], colorvalue[3]);CHECKGLERROR
        }
        if (mask & GL_DEPTH_BUFFER_BIT)
        {
#ifdef USE_GLES2
            //qglClearDepthf(depthvalue);CHECKGLERROR
#else
            qglClearDepth(depthvalue);CHECKGLERROR
#endif
        }
        if (mask & GL_STENCIL_BUFFER_BIT)
        {
            qglClearStencil(stencilvalue);CHECKGLERROR
        }
        qglClear(mask);CHECKGLERROR
        break;
    }
}
Referenced by R_Bloom_MakeTexture(), R_ClearScreen(), R_RenderView(), R_Shadow_ClearShadowMapTexture(), R_Shadow_ClearStencil(), R_Shadow_DrawPrepass(), and VID_InitModeGL().
GL_Color()
void GL_Color (float cr, float cg, float cb, float ca)
Definition at line 1427 of file gl_backend.c.
{
    if (gl_state.pointer_color_enabled || gl_state.color4f[0] != cr || gl_state.color4f[1] != cg || gl_state.color4f[2] != cb || gl_state.color4f[3] != ca)
    {
        gl_state.color4f[0] = cr;
        gl_state.color4f[1] = cg;
        gl_state.color4f[2] = cb;
        gl_state.color4f[3] = ca;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            qglVertexAttrib4f(GLSLATTRIB_COLOR, cr, cg, cb, ca);CHECKGLERROR
            break;
        }
    }
}
Referenced by R_BlendView(), R_Bloom_MakeTexture(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawPortal_Callback(), R_DrawSurface_TransparentCallback(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawDepth(), R_MotionBlurView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_DrawPrepass(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_VisibleLighting(), and SCR_DrawLoadingScreen().
GL_ColorMask()
void GL_ColorMask (int r, int g, int b, int a)
Definition at line 1409 of file gl_backend.c.
{
    // NOTE: this matches D3DCOLORWRITEENABLE_RED, GREEN, BLUE, ALPHA
    int state = (r ? 1 : 0) | (g ? 2 : 0) | (b ? 4 : 0) | (a ? 8 : 0);
    if (gl_state.colormask != state)
    {
        gl_state.colormask = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            qglColorMask((GLboolean)r, (GLboolean)g, (GLboolean)b, (GLboolean)a);CHECKGLERROR
            break;
        }
    }
}
Referenced by CL_UpdateScreen(), R_DrawSurface_TransparentCallback(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawDepth(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawPrepass(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Lighting(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_ShadowMap().
GL_CullFace()
void GL_CullFace (int state)
Definition at line 1339 of file gl_backend.c.
{
    if(v_flipped_state)
    {
        if(state == GL_FRONT)
            state = GL_BACK;
        else if(state == GL_BACK)
            state = GL_FRONT;
    }
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        if (state != GL_NONE)
        {
            if (!gl_state.cullfaceenable)
            {
                gl_state.cullfaceenable = true;
                qglEnable(GL_CULL_FACE);CHECKGLERROR
            }
            if (gl_state.cullface != state)
            {
                gl_state.cullface = state;
                qglCullFace(gl_state.cullface);CHECKGLERROR
            }
        }
        else
        {
            if (gl_state.cullfaceenable)
            {
                gl_state.cullfaceenable = false;
                qglDisable(GL_CULL_FACE);CHECKGLERROR
            }
        }
        break;
    }
}
Referenced by R_Bloom_MakeTexture(), R_DrawDebugModel(), R_DrawEntityBBoxes_Callback(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_Mod_DrawShadowMap(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawWorldShadow_ShadowMap(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_ShadowMap(), and RSurf_SetupDepthAndCulling().
GL_DepthFunc()
void GL_DepthFunc (int state)
Definition at line 1240 of file gl_backend.c.
{
    if (gl_state.depthfunc != state)
    {
        gl_state.depthfunc = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            qglDepthFunc(gl_state.depthfunc);CHECKGLERROR
            break;
        }
    }
}
Referenced by R_BeginCoronaQuery(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Lighting(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_VisibleLighting().
GL_DepthMask()
void GL_DepthMask (int state)
Definition at line 1201 of file gl_backend.c.
{
    if (gl_state.depthmask != state)
    {
        gl_state.depthmask = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            qglDepthMask(gl_state.depthmask);CHECKGLERROR
            break;
        }
    }
}
Referenced by CL_UpdateScreen(), DrawQ_FlushUI(), R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_DrawSurface_TransparentCallback(), R_DrawTextureSurfaceList_GL20(), R_DrawTextureSurfaceList_ShowSurfaces(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawDepth(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawPrepass(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_End(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_ShadowMap().
GL_DepthRange()
void GL_DepthRange (float nearfrac, float farfrac)
Definition at line 1256 of file gl_backend.c.
{
    if (gl_state.depthrange[0] != nearfrac || gl_state.depthrange[1] != farfrac)
    {
        gl_state.depthrange[0] = nearfrac;
        gl_state.depthrange[1] = farfrac;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
#ifdef USE_GLES2
            qglDepthRangef(gl_state.depthrange[0], gl_state.depthrange[1]);CHECKGLERROR
#else
            qglDepthRange(gl_state.depthrange[0], gl_state.depthrange[1]);CHECKGLERROR
#endif
            break;
        }
    }
}
Referenced by R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_DrawCoronas(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_VisibleLighting(), RSurf_SetupDepthAndCulling(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
GL_DepthTest()
void GL_DepthTest (int state)
Definition at line 1217 of file gl_backend.c.
{
    if (gl_state.depthtest != state)
    {
        gl_state.depthtest = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            if (gl_state.depthtest)
            {
                qglEnable(GL_DEPTH_TEST);CHECKGLERROR
            }
            else
            {
                qglDisable(GL_DEPTH_TEST);CHECKGLERROR
            }
            break;
        }
    }
}
Referenced by R_Bloom_MakeTexture(), R_DrawDebugModel(), R_DrawEntityBBoxes_Callback(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_DrawSurface_TransparentCallback(), R_Mod_DrawDepth(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawPrepass(), R_Shadow_RenderLighting(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_ShadowMap(), R_Shadow_RenderMode_VisibleLighting(), RSurf_SetupDepthAndCulling(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
GL_Finish()
void GL_Finish (void)
Definition at line 398 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        qglFinish();CHECKGLERROR
        break;
    }
}
Referenced by R_TimeReport(), and VID_Finish().
GL_Mesh_ListVBOs()
void GL_Mesh_ListVBOs (qbool printeach)
Definition at line 1854 of file gl_backend.c.
{
    int i, endindex;
    int type;
    int isdynamic;
    int index16count, index16mem;
    int index32count, index32mem;
    int vertexcount, vertexmem;
    int uniformcount, uniformmem;
    int totalcount, totalmem;
    size_t bufferstat[R_BUFFERDATA_COUNT][2][2];
    r_meshbuffer_t *buffer;
    memset(bufferstat, 0, sizeof(bufferstat));
    endindex = (int)Mem_ExpandableArray_IndexRange(&gl_state.meshbufferarray);
    for (i = 0;i < endindex;i++)
    {
        buffer = (r_meshbuffer_t *) Mem_ExpandableArray_RecordAtIndex(&gl_state.meshbufferarray, i);
        if (!buffer)
            continue;
        if (buffer->isuniformbuffer)
            type = R_BUFFERDATA_UNIFORM;
        else if (buffer->isindexbuffer && buffer->isindex16)
            type = R_BUFFERDATA_INDEX16;
        else if (buffer->isindexbuffer)
            type = R_BUFFERDATA_INDEX32;
        else
            type = R_BUFFERDATA_VERTEX;
        isdynamic = buffer->isdynamic;
        bufferstat[type][isdynamic][0]++;
        bufferstat[type][isdynamic][1] += buffer->size;
        if (printeach)
            Con_Printf("buffer #%i %s = %i bytes (%s %s)\n", i, buffer->name, (int)buffer->size, isdynamic ? "dynamic" : "static", buffertypename[type]);
    }
    index16count   = (int)(bufferstat[R_BUFFERDATA_INDEX16][0][0] + bufferstat[R_BUFFERDATA_INDEX16][1][0]);
    index16mem     = (int)(bufferstat[R_BUFFERDATA_INDEX16][0][1] + bufferstat[R_BUFFERDATA_INDEX16][1][1]);
    index32count   = (int)(bufferstat[R_BUFFERDATA_INDEX32][0][0] + bufferstat[R_BUFFERDATA_INDEX32][1][0]);
    index32mem     = (int)(bufferstat[R_BUFFERDATA_INDEX32][0][1] + bufferstat[R_BUFFERDATA_INDEX32][1][1]);
    vertexcount  = (int)(bufferstat[R_BUFFERDATA_VERTEX ][0][0] + bufferstat[R_BUFFERDATA_VERTEX ][1][0]);
    vertexmem    = (int)(bufferstat[R_BUFFERDATA_VERTEX ][0][1] + bufferstat[R_BUFFERDATA_VERTEX ][1][1]);
    uniformcount = (int)(bufferstat[R_BUFFERDATA_UNIFORM][0][0] + bufferstat[R_BUFFERDATA_UNIFORM][1][0]);
    uniformmem   = (int)(bufferstat[R_BUFFERDATA_UNIFORM][0][1] + bufferstat[R_BUFFERDATA_UNIFORM][1][1]);
    totalcount = index16count + index32count + vertexcount + uniformcount;
    totalmem = index16mem + index32mem + vertexmem + uniformmem;
    Con_Printf("%i 16bit indexbuffers totalling %i bytes (%.3f MB)\n%i 32bit indexbuffers totalling %i bytes (%.3f MB)\n%i vertexbuffers totalling %i bytes (%.3f MB)\n%i uniformbuffers totalling %i bytes (%.3f MB)\ncombined %i buffers totalling %i bytes (%.3fMB)\n", index16count, index16mem, index16mem / 10248576.0, index32count, index32mem, index32mem / 10248576.0, vertexcount, vertexmem, vertexmem / 10248576.0, uniformcount, uniformmem, uniformmem / 10248576.0, totalcount, totalmem, totalmem / 10248576.0);
}
Referenced by GL_VBOStats_f().
GL_PolygonOffset()
void GL_PolygonOffset (float planeoffset, float depthoffset)
Definition at line 1300 of file gl_backend.c.
{
    if (gl_state.polygonoffset[0] != planeoffset || gl_state.polygonoffset[1] != depthoffset)
    {
        gl_state.polygonoffset[0] = planeoffset;
        gl_state.polygonoffset[1] = depthoffset;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            qglPolygonOffset(gl_state.polygonoffset[0], gl_state.polygonoffset[1]);CHECKGLERROR
            break;
        }
    }
}
Referenced by R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_ShadowMap(), RSurf_SetupDepthAndCulling(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
GL_ReadPixelsBGRA()
void GL_ReadPixelsBGRA (int x, int y, int width, int height, unsigned char * outpixels)
Definition at line 1515 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
#ifndef GL_BGRA
        {
            int i;
            int r;
        //  int g;
            int b;
        //  int a;
            qglReadPixels(x, y, width, height, GL_RGBA, GL_UNSIGNED_BYTE, outpixels);CHECKGLERROR
            for (i = 0;i < width * height * 4;i += 4)
            {
                r = outpixels[i+0];
        //      g = outpixels[i+1];
                b = outpixels[i+2];
        //      a = outpixels[i+3];
                outpixels[i+0] = b;
        //      outpixels[i+1] = g;
                outpixels[i+2] = r;
        //      outpixels[i+3] = a;
            }
        }
#else
        qglReadPixels(x, y, width, height, GL_BGRA, GL_UNSIGNED_BYTE, outpixels);CHECKGLERROR
#endif
            break;
    }
}
Referenced by SCR_ScreenShot().
GL_Scissor()
void GL_Scissor (int x, int y, int width, int height)
Definition at line 1445 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        qglScissor(x, y,width,height);CHECKGLERROR
        break;
    }
}
Referenced by DrawQ_SetClipArea(), R_RenderView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawModelShadowMaps(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_End(), R_Shadow_RenderMode_Reset(), R_Shadow_RenderMode_ShadowMap(), R_Sky(), and R_Water_ProcessPlanes().
GL_ScissorTest()
void GL_ScissorTest (int state)
Definition at line 1457 of file gl_backend.c.
{
    if (gl_state.scissortest != state)
    {
        gl_state.scissortest = state;
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            if(gl_state.scissortest)
                qglEnable(GL_SCISSOR_TEST);
            else
                qglDisable(GL_SCISSOR_TEST);
            CHECKGLERROR
            break;
        }
    }
}
Referenced by CL_UpdateScreen(), DrawQ_ResetClipArea(), DrawQ_SetClipArea(), R_RenderView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Sky(), and R_Water_ProcessPlanes().
R_ClearScreen()
void R_ClearScreen (qbool fogcolor)
Definition at line 1565 of file cl_screen.c.
{
    float clearcolor[4];
    if (scr_screenshot_alpha.integer)
        // clear to transparency (so png screenshots can contain alpha channel, useful for building model pictures)
        Vector4Set(clearcolor, 0.0f, 0.0f, 0.0f, 0.0f);
    else
        // clear to opaque black (if we're being composited it might otherwise render as transparent)
        Vector4Set(clearcolor, 0.0f, 0.0f, 0.0f, 1.0f);
    if (fogcolor && r_fog_clear.integer)
    {
        R_UpdateFog();
        VectorCopy(r_refdef.fogcolor, clearcolor);
    }
    // clear depth is 1.0
    // clear the screen
    GL_Clear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | (vid.stencil ? GL_STENCIL_BUFFER_BIT : 0), clearcolor, 1.0f, 0);
}
Referenced by CL_UpdateScreen(), R_RenderView(), and R_Water_ProcessPlanes().
R_EntityMatrix()
void R_EntityMatrix (const matrix4x4_t * matrix)
Definition at line 4417 of file gl_rmain.c.
{
    if (gl_modelmatrixchanged || memcmp(matrix, &gl_modelmatrix, sizeof(matrix4x4_t)))
    {
        gl_modelmatrixchanged = false;
        gl_modelmatrix = *matrix;
        Matrix4x4_Concat(&gl_modelviewmatrix, &gl_viewmatrix, &gl_modelmatrix);
        Matrix4x4_Concat(&gl_modelviewprojectionmatrix, &gl_projectionmatrix, &gl_modelviewmatrix);
        Matrix4x4_ToArrayFloatGL(&gl_modelviewmatrix, gl_modelview16f);
        Matrix4x4_ToArrayFloatGL(&gl_modelviewprojectionmatrix, gl_modelviewprojection16f);
        CHECKGLERROR
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            if (r_glsl_permutation && r_glsl_permutation->loc_ModelViewProjectionMatrix >= 0) qglUniformMatrix4fv(r_glsl_permutation->loc_ModelViewProjectionMatrix, 1, false, gl_modelviewprojection16f);
            if (r_glsl_permutation && r_glsl_permutation->loc_ModelViewMatrix >= 0) qglUniformMatrix4fv(r_glsl_permutation->loc_ModelViewMatrix, 1, false, gl_modelview16f);
            break;
        }
    }
}
Referenced by R_BlendView(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawPortal_Callback(), R_MotionBlurView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_SetViewport(), R_Shadow_DrawCoronas(), R_Shadow_RenderMode_DrawDeferredLight(), RSurf_ActiveCustomEntity(), and RSurf_ActiveModelEntity().
R_GetViewport()
void R_GetViewport (r_viewport_t * v)
Definition at line 921 of file gl_backend.c.
{
    *v = gl_viewport;
}
R_Mesh_ClearBindingsForTexture()
void R_Mesh_ClearBindingsForTexture (int texnum)
Definition at line 2053 of file gl_backend.c.
{
    gltextureunit_t *unit;
    unsigned int unitnum;
    // unbind the texture from any units it is bound on - this prevents accidental reuse of certain textures whose bindings can linger far too long otherwise (e.g. bouncegrid which is a 3D texture) and confuse the driver later.
    for (unitnum = 0; unitnum < MAX_TEXTUREUNITS; unitnum++)
    {
        unit = gl_state.units + unitnum;
        if (unit->texture && unit->texture->texnum == texnum)
            R_Mesh_TexBind(unitnum, NULL);
    }
}
Referenced by R_FreeTexture().
R_Mesh_ColorPointer()
void R_Mesh_ColorPointer (int components, int gltype, size_t stride, const void * pointer, const r_meshbuffer_t * vertexbuffer, size_t bufferoffset)
Definition at line 1928 of file gl_backend.c.
{
    // note: vertexbuffer may be non-NULL even if pointer is NULL, so check
    // the pointer only.
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        if (pointer)
        {
            // caller wants color array enabled
            int bufferobject = vertexbuffer ? vertexbuffer->bufferobject : 0;
            if (!gl_state.pointer_color_enabled)
            {
                gl_state.pointer_color_enabled = true;
                CHECKGLERROR
                qglEnableVertexAttribArray(GLSLATTRIB_COLOR);CHECKGLERROR
            }
            if (gl_state.pointer_color_components != components || gl_state.pointer_color_gltype != gltype || gl_state.pointer_color_stride != stride || gl_state.pointer_color_pointer != pointer || gl_state.pointer_color_vertexbuffer != vertexbuffer || gl_state.pointer_color_offset != bufferoffset)
            {
                gl_state.pointer_color_components = components;
                gl_state.pointer_color_gltype = gltype;
                gl_state.pointer_color_stride = stride;
                gl_state.pointer_color_pointer = pointer;
                gl_state.pointer_color_vertexbuffer = vertexbuffer;
                gl_state.pointer_color_offset = bufferoffset;
                CHECKGLERROR
                GL_BindVBO(bufferobject);
                // LadyHavoc: special flag added to gltype for unnormalized types
                qglVertexAttribPointer(GLSLATTRIB_COLOR, components, gltype & ~0x80000000, (gltype & 0x80000000) == 0, (GLsizei)stride, bufferobject ? (void *)bufferoffset : pointer);CHECKGLERROR
            }
        }
        else
        {
            // caller wants color array disabled
            if (gl_state.pointer_color_enabled)
            {
                gl_state.pointer_color_enabled = false;
                CHECKGLERROR
                qglDisableVertexAttribArray(GLSLATTRIB_COLOR);CHECKGLERROR
                // when color array is on the current color gets trashed, set it again
                qglVertexAttrib4f(GLSLATTRIB_COLOR, gl_state.color4f[0], gl_state.color4f[1], gl_state.color4f[2], gl_state.color4f[3]);CHECKGLERROR
            }
        }
        break;
    }
}
Referenced by R_Mesh_PrepareVertices_Generic_Arrays(), R_Mesh_PrepareVertices_Mesh_Arrays(), R_Mesh_PrepareVertices_Vertex3f(), and RSurf_UploadBuffersForBatch().
R_Mesh_CopyToTexture()
void R_Mesh_CopyToTexture (rtexture_t * tex, int tx, int ty, int sx, int sy, int width, int height)
Definition at line 2040 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        R_Mesh_TexBind(0, tex);
        GL_ActiveTexture(0);CHECKGLERROR
        qglCopyTexSubImage2D(GL_TEXTURE_2D, 0, tx, ty, sx, sy, width, height);CHECKGLERROR
        break;
    }
}
Referenced by R_MotionBlurView(), and SCR_SetLoadingScreenTexture().
R_Mesh_CreateFramebufferObject()
int R_Mesh_CreateFramebufferObject (rtexture_t * depthtexture, rtexture_t * colortexture, rtexture_t * colortexture2, rtexture_t * colortexture3, rtexture_t * colortexture4)
Definition at line 959 of file gl_backend.c.
{
    int temp;
    GLuint status;
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        qglGenFramebuffers(1, (GLuint*)&temp);CHECKGLERROR
        R_Mesh_SetRenderTargets(temp, NULL, NULL, NULL, NULL, NULL);
        // GL_ARB_framebuffer_object (GL3-class hardware) - depth stencil attachment
#ifdef USE_GLES2
        // FIXME: separate stencil attachment on GLES
        if (depthtexture  && depthtexture->texnum ) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT  , depthtexture->gltexturetypeenum , depthtexture->texnum , 0);CHECKGLERROR }
        if (depthtexture  && depthtexture->renderbuffernum ) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT  , GL_RENDERBUFFER, depthtexture->renderbuffernum );CHECKGLERROR }
#else
        if (depthtexture  && depthtexture->texnum )
        {
            qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT  , depthtexture->gltexturetypeenum , depthtexture->texnum , 0);CHECKGLERROR
            if (depthtexture->glisdepthstencil) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT  , depthtexture->gltexturetypeenum , depthtexture->texnum , 0);CHECKGLERROR }
        }
        if (depthtexture  && depthtexture->renderbuffernum )
        {
            qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT  , GL_RENDERBUFFER, depthtexture->renderbuffernum );CHECKGLERROR
            if (depthtexture->glisdepthstencil) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT  , GL_RENDERBUFFER, depthtexture->renderbuffernum );CHECKGLERROR }
        }
#endif
        if (colortexture  && colortexture->texnum ) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 , colortexture->gltexturetypeenum , colortexture->texnum , 0);CHECKGLERROR }
        if (colortexture2 && colortexture2->texnum) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT1 , colortexture2->gltexturetypeenum, colortexture2->texnum, 0);CHECKGLERROR }
        if (colortexture3 && colortexture3->texnum) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT2 , colortexture3->gltexturetypeenum, colortexture3->texnum, 0);CHECKGLERROR }
        if (colortexture4 && colortexture4->texnum) { qglFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT3 , colortexture4->gltexturetypeenum, colortexture4->texnum, 0);CHECKGLERROR }
        if (colortexture  && colortexture->renderbuffernum ) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 , GL_RENDERBUFFER, colortexture->renderbuffernum );CHECKGLERROR }
        if (colortexture2 && colortexture2->renderbuffernum) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT1 , GL_RENDERBUFFER, colortexture2->renderbuffernum);CHECKGLERROR }
        if (colortexture3 && colortexture3->renderbuffernum) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT2 , GL_RENDERBUFFER, colortexture3->renderbuffernum);CHECKGLERROR }
        if (colortexture4 && colortexture4->renderbuffernum) { qglFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT3 , GL_RENDERBUFFER, colortexture4->renderbuffernum);CHECKGLERROR }
#ifndef USE_GLES2
        if (colortexture4)
        {
            qglDrawBuffers(4, drawbuffers);CHECKGLERROR
            qglReadBuffer(GL_NONE);CHECKGLERROR
        }
        else if (colortexture3)
        {
            qglDrawBuffers(3, drawbuffers);CHECKGLERROR
            qglReadBuffer(GL_NONE);CHECKGLERROR
        }
        else if (colortexture2)
        {
            qglDrawBuffers(2, drawbuffers);CHECKGLERROR
            qglReadBuffer(GL_NONE);CHECKGLERROR
        }
        else if (colortexture)
        {
            qglDrawBuffer(GL_COLOR_ATTACHMENT0);CHECKGLERROR
            qglReadBuffer(GL_COLOR_ATTACHMENT0);CHECKGLERROR
        }
        else
        {
            qglDrawBuffer(GL_NONE);CHECKGLERROR
            qglReadBuffer(GL_NONE);CHECKGLERROR
        }
#endif
        status = qglCheckFramebufferStatus(GL_FRAMEBUFFER);CHECKGLERROR
        if (status != GL_FRAMEBUFFER_COMPLETE)
        {
            Con_Printf("R_Mesh_CreateFramebufferObject: glCheckFramebufferStatus returned %i\n", status);
            gl_state.framebufferobject = 0; // GL unbinds it for us
            qglDeleteFramebuffers(1, (GLuint*)&temp);CHECKGLERROR
            temp = 0;
        }
        return temp;
    }
    return 0;
}
Referenced by R_RenderTarget_Get(), R_Shadow_MakeShadowMap(), and R_Shadow_PrepareLights().
R_Mesh_CreateMeshBuffer()
r_meshbuffer_t * R_Mesh_CreateMeshBuffer (const void * data, size_t size, const char * name, qbool isindexbuffer, qbool isuniformbuffer, qbool isdynamic, qbool isindex16)
Definition at line 1764 of file gl_backend.c.
{
    r_meshbuffer_t *buffer;
    buffer = (r_meshbuffer_t *)Mem_ExpandableArray_AllocRecord(&gl_state.meshbufferarray);
    memset(buffer, 0, sizeof(*buffer));
    buffer->bufferobject = 0;
    buffer->devicebuffer = NULL;
    buffer->size = size;
    buffer->isindexbuffer = isindexbuffer;
    buffer->isuniformbuffer = isuniformbuffer;
    buffer->isdynamic = isdynamic;
    buffer->isindex16 = isindex16;
    dp_strlcpy(buffer->name, name, sizeof(buffer->name));
    R_Mesh_UpdateMeshBuffer(buffer, data, size, false, 0);
    return buffer;
}
Referenced by Mod_BuildVBOs(), Mod_ShadowMesh_CreateVBOs(), and R_BufferData_Resize().
R_Mesh_DestroyFramebufferObject()
void R_Mesh_DestroyFramebufferObject (int fbo)
Definition at line 1036 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        if (fbo)
        {
            // GL clears the binding if we delete something bound
            if (gl_state.framebufferobject == fbo)
                gl_state.framebufferobject = 0;
            qglDeleteFramebuffers(1, (GLuint*)&fbo);CHECKGLERROR
        }
        break;
    }
}
Referenced by R_RenderTarget_FreeUnused(), R_Shadow_FreeDeferred(), and R_Shadow_FreeShadowMaps().
R_Mesh_DestroyMeshBuffer()
void R_Mesh_DestroyMeshBuffer (r_meshbuffer_t * buffer)
Definition at line 1831 of file gl_backend.c.
{
    if (!buffer)
        return;
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        // GL clears the binding if we delete something bound
        if (gl_state.uniformbufferobject == buffer->bufferobject)
            gl_state.uniformbufferobject = 0;
        if (gl_state.vertexbufferobject == buffer->bufferobject)
            gl_state.vertexbufferobject = 0;
        if (gl_state.elementbufferobject == buffer->bufferobject)
            gl_state.elementbufferobject = 0;
        CHECKGLERROR
        qglDeleteBuffers(1, (GLuint *)&buffer->bufferobject);CHECKGLERROR
        break;
    }
    Mem_ExpandableArray_FreeRecord(&gl_state.meshbufferarray, (void *)buffer);
}
Referenced by Mod_GenerateLightmaps_UnweldTriangles(), Mod_ShadowMesh_Free(), Mod_UnloadModel(), R_BufferData_NewFrame(), and R_BufferData_Reset().
R_Mesh_Draw()
void R_Mesh_Draw (int firstvertex, int numvertices, int firsttriangle, int numtriangles, const int * element3i, const r_meshbuffer_t * element3i_indexbuffer, int element3i_bufferoffset, const unsigned short * element3s, const r_meshbuffer_t * element3s_indexbuffer, int element3s_bufferoffset)
Definition at line 1666 of file gl_backend.c.
{
    unsigned int numelements = numtriangles * 3;
    int bufferobject3i;
    size_t bufferoffset3i;
    int bufferobject3s;
    size_t bufferoffset3s;
    if (numvertices < 3 || numtriangles < 1)
    {
        if (numvertices < 0 || numtriangles < 0 || developer_extra.integer)
            Con_DPrintf("R_Mesh_Draw(%d, %d, %d, %d, %8p, %8p, %8x, %8p, %8p, %8x);\n", firstvertex, numvertices, firsttriangle, numtriangles, (void *)element3i, (void *)element3i_indexbuffer, (int)element3i_bufferoffset, (void *)element3s, (void *)element3s_indexbuffer, (int)element3s_bufferoffset);
        return;
    }
    // adjust the pointers for firsttriangle
    if (element3i)
        element3i += firsttriangle * 3;
    if (element3i_indexbuffer)
        element3i_bufferoffset += firsttriangle * 3 * sizeof(*element3i);
    if (element3s)
        element3s += firsttriangle * 3;
    if (element3s_indexbuffer)
        element3s_bufferoffset += firsttriangle * 3 * sizeof(*element3s);
    // upload a dynamic index buffer if needed
    if (element3s)
    {
        if (!element3s_indexbuffer)
            element3s_indexbuffer = R_BufferData_Store(numelements * sizeof(*element3s), (void *)element3s, R_BUFFERDATA_INDEX16, &element3s_bufferoffset);
    }
    else if (element3i)
    {
        if (!element3i_indexbuffer)
            element3i_indexbuffer = R_BufferData_Store(numelements * sizeof(*element3i), (void *)element3i, R_BUFFERDATA_INDEX32, &element3i_bufferoffset);
    }
    bufferobject3i = element3i_indexbuffer ? element3i_indexbuffer->bufferobject : 0;
    bufferoffset3i = element3i_bufferoffset;
    bufferobject3s = element3s_indexbuffer ? element3s_indexbuffer->bufferobject : 0;
    bufferoffset3s = element3s_bufferoffset;
    r_refdef.stats[r_stat_draws]++;
    r_refdef.stats[r_stat_draws_vertices] += numvertices;
    r_refdef.stats[r_stat_draws_elements] += numelements;
    if (gl_paranoid.integer)
    {
        unsigned int i;
        if (element3i)
        {
            for (i = 0;i < (unsigned int) numtriangles * 3;i++)
            {
                if (element3i[i] < firstvertex || element3i[i] >= firstvertex + numvertices)
                {
                    Con_Printf("R_Mesh_Draw: invalid vertex index %i (outside range %i - %i) in element3i array\n", element3i[i], firstvertex, firstvertex + numvertices);
                    return;
                }
            }
        }
        if (element3s)
        {
            for (i = 0;i < (unsigned int) numtriangles * 3;i++)
            {
                if (element3s[i] < firstvertex || element3s[i] >= firstvertex + numvertices)
                {
                    Con_Printf("R_Mesh_Draw: invalid vertex index %i (outside range %i - %i) in element3s array\n", element3s[i], firstvertex, firstvertex + numvertices);
                    return;
                }
            }
        }
    }
    if (r_render.integer || r_refdef.draw2dstage)
    {
        switch(vid.renderpath)
        {
        case RENDERPATH_GL32:
        case RENDERPATH_GLES2:
            CHECKGLERROR
            if (bufferobject3s)
            {
                GL_BindEBO(bufferobject3s);
                qglDrawElements(GL_TRIANGLES, numelements, GL_UNSIGNED_SHORT, (void *)bufferoffset3s);CHECKGLERROR
            }
            else if (bufferobject3i)
            {
                GL_BindEBO(bufferobject3i);
                qglDrawElements(GL_TRIANGLES, numelements, GL_UNSIGNED_INT, (void *)bufferoffset3i);CHECKGLERROR
            }
            else
            {
                qglDrawArrays(GL_TRIANGLES, firstvertex, numvertices);CHECKGLERROR
            }
            break;
        }
    }
}
Referenced by R_BeginCoronaQuery(), R_BlendView(), R_Bloom_MakeTexture(), R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_MotionBlurView(), R_Shadow_DrawWorldShadow_ShadowMap(), R_Shadow_RenderMode_DrawDeferredLight(), RSurf_DrawBatch(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
R_Mesh_Finish()
void R_Mesh_Finish (void)
Definition at line 1759 of file gl_backend.c.
{
    R_Mesh_SetRenderTargets(0, NULL, NULL, NULL, NULL, NULL);
}
Referenced by R_Envmap_f(), and SCR_DrawScreen().
R_Mesh_PrepareVertices_Generic_Arrays()
void R_Mesh_PrepareVertices_Generic_Arrays (int numvertices, const float * vertex3f, const float * color4f, const float * texcoord2f)
Definition at line 2137 of file gl_backend.c.
{
    r_meshbuffer_t *buffer_vertex3f = NULL;
    r_meshbuffer_t *buffer_color4f = NULL;
    r_meshbuffer_t *buffer_texcoord2f = NULL;
    int bufferoffset_vertex3f = 0;
    int bufferoffset_color4f = 0;
    int bufferoffset_texcoord2f = 0;
    if (color4f)
        buffer_color4f    = R_BufferData_Store(numvertices * sizeof(float[4]), color4f   , R_BUFFERDATA_VERTEX, &bufferoffset_color4f   );
    if (vertex3f)
        buffer_vertex3f   = R_BufferData_Store(numvertices * sizeof(float[3]), vertex3f  , R_BUFFERDATA_VERTEX, &bufferoffset_vertex3f  );
    if (texcoord2f)
        buffer_texcoord2f = R_BufferData_Store(numvertices * sizeof(float[2]), texcoord2f, R_BUFFERDATA_VERTEX, &bufferoffset_texcoord2f);
    R_Mesh_VertexPointer(     3, GL_FLOAT        , sizeof(float[3])        , vertex3f          , buffer_vertex3f          , bufferoffset_vertex3f          );
    R_Mesh_ColorPointer(      4, GL_FLOAT        , sizeof(float[4])        , color4f           , buffer_color4f           , bufferoffset_color4f           );
    R_Mesh_TexCoordPointer(0, 2, GL_FLOAT        , sizeof(float[2])        , texcoord2f        , buffer_texcoord2f        , bufferoffset_texcoord2f        );
    R_Mesh_TexCoordPointer(1, 3, GL_FLOAT        , sizeof(float[3])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(2, 3, GL_FLOAT        , sizeof(float[3])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(3, 3, GL_FLOAT        , sizeof(float[3])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(4, 2, GL_FLOAT        , sizeof(float[2])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(5, 2, GL_FLOAT        , sizeof(float[2])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(6, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(7, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL              , NULL                     , 0                              );
}
Referenced by R_Bloom_MakeTexture(), R_DrawBBoxMesh(), R_DrawDebugModel(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawModelDecals_Entity(), R_DrawNoModel_TransparentCallback(), R_DrawParticle_TransparentCallback(), R_DrawPortal_Callback(), R_DrawTextureSurfaceList_ShowSurfaces(), R_DrawTextureSurfaceList_Sky(), R_MotionBlurView(), R_Shadow_RenderLighting_VisibleLighting(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
R_Mesh_PrepareVertices_Mesh_Arrays()
void R_Mesh_PrepareVertices_Mesh_Arrays (int numvertices, const float * vertex3f, const float * svector3f, const float * tvector3f, const float * normal3f, const float * color4f, const float * texcoordtexture2f, const float * texcoordlightmap2f)
Definition at line 2163 of file gl_backend.c.
{
    r_meshbuffer_t *buffer_vertex3f = NULL;
    r_meshbuffer_t *buffer_color4f = NULL;
    r_meshbuffer_t *buffer_texcoordtexture2f = NULL;
    r_meshbuffer_t *buffer_svector3f = NULL;
    r_meshbuffer_t *buffer_tvector3f = NULL;
    r_meshbuffer_t *buffer_normal3f = NULL;
    r_meshbuffer_t *buffer_texcoordlightmap2f = NULL;
    int bufferoffset_vertex3f = 0;
    int bufferoffset_color4f = 0;
    int bufferoffset_texcoordtexture2f = 0;
    int bufferoffset_svector3f = 0;
    int bufferoffset_tvector3f = 0;
    int bufferoffset_normal3f = 0;
    int bufferoffset_texcoordlightmap2f = 0;
    if (color4f)
        buffer_color4f            = R_BufferData_Store(numvertices * sizeof(float[4]), color4f           , R_BUFFERDATA_VERTEX, &bufferoffset_color4f           );
    if (vertex3f)
        buffer_vertex3f           = R_BufferData_Store(numvertices * sizeof(float[3]), vertex3f          , R_BUFFERDATA_VERTEX, &bufferoffset_vertex3f          );
    if (svector3f)
        buffer_svector3f          = R_BufferData_Store(numvertices * sizeof(float[3]), svector3f         , R_BUFFERDATA_VERTEX, &bufferoffset_svector3f         );
    if (tvector3f)
        buffer_tvector3f          = R_BufferData_Store(numvertices * sizeof(float[3]), tvector3f         , R_BUFFERDATA_VERTEX, &bufferoffset_tvector3f         );
    if (normal3f)
        buffer_normal3f           = R_BufferData_Store(numvertices * sizeof(float[3]), normal3f          , R_BUFFERDATA_VERTEX, &bufferoffset_normal3f          );
    if (texcoordtexture2f)
        buffer_texcoordtexture2f  = R_BufferData_Store(numvertices * sizeof(float[2]), texcoordtexture2f , R_BUFFERDATA_VERTEX, &bufferoffset_texcoordtexture2f );
    if (texcoordlightmap2f)
        buffer_texcoordlightmap2f = R_BufferData_Store(numvertices * sizeof(float[2]), texcoordlightmap2f, R_BUFFERDATA_VERTEX, &bufferoffset_texcoordlightmap2f);
    R_Mesh_VertexPointer(     3, GL_FLOAT        , sizeof(float[3])        , vertex3f          , buffer_vertex3f          , bufferoffset_vertex3f          );
    R_Mesh_ColorPointer(      4, GL_FLOAT        , sizeof(float[4])        , color4f           , buffer_color4f           , bufferoffset_color4f           );
    R_Mesh_TexCoordPointer(0, 2, GL_FLOAT        , sizeof(float[2])        , texcoordtexture2f , buffer_texcoordtexture2f , bufferoffset_texcoordtexture2f );
    R_Mesh_TexCoordPointer(1, 3, GL_FLOAT        , sizeof(float[3])        , svector3f         , buffer_svector3f         , bufferoffset_svector3f         );
    R_Mesh_TexCoordPointer(2, 3, GL_FLOAT        , sizeof(float[3])        , tvector3f         , buffer_tvector3f         , bufferoffset_tvector3f         );
    R_Mesh_TexCoordPointer(3, 3, GL_FLOAT        , sizeof(float[3])        , normal3f          , buffer_normal3f          , bufferoffset_normal3f          );
    R_Mesh_TexCoordPointer(4, 2, GL_FLOAT        , sizeof(float[2])        , texcoordlightmap2f, buffer_texcoordlightmap2f, bufferoffset_texcoordlightmap2f);
    R_Mesh_TexCoordPointer(5, 2, GL_FLOAT        , sizeof(float[2])        , NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(6, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL              , NULL                     , 0                              );
    R_Mesh_TexCoordPointer(7, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL              , NULL                     , 0                              );
}
Referenced by R_BlendView().
R_Mesh_PrepareVertices_Vertex3f()
void R_Mesh_PrepareVertices_Vertex3f (int numvertices, const float * vertex3f, const r_meshbuffer_t * buffer, int bufferoffset)
Definition at line 2120 of file gl_backend.c.
{
    // upload temporary vertexbuffer for this rendering
    if (!vertexbuffer)
        vertexbuffer = R_BufferData_Store(numvertices * sizeof(float[3]), (void *)vertex3f, R_BUFFERDATA_VERTEX, &bufferoffset);
    R_Mesh_VertexPointer(     3, GL_FLOAT        , sizeof(float[3])        , vertex3f  , vertexbuffer     , bufferoffset           );
    R_Mesh_ColorPointer(      4, GL_FLOAT        , sizeof(float[4])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(0, 2, GL_FLOAT        , sizeof(float[2])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(1, 3, GL_FLOAT        , sizeof(float[3])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(2, 3, GL_FLOAT        , sizeof(float[3])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(3, 3, GL_FLOAT        , sizeof(float[3])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(4, 2, GL_FLOAT        , sizeof(float[2])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(5, 2, GL_FLOAT        , sizeof(float[2])        , NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(6, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL      , NULL             , 0                      );
    R_Mesh_TexCoordPointer(7, 4, GL_UNSIGNED_BYTE, sizeof(unsigned char[4]), NULL      , NULL             , 0                      );
}
Referenced by R_BeginCoronaQuery(), R_DrawSurface_TransparentCallback(), R_DrawTextureSurfaceList_DepthOnly(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawShadowMap(), R_Shadow_DrawWorldShadow_ShadowMap(), and R_Shadow_RenderMode_DrawDeferredLight().
R_Mesh_ResetTextureState()
void R_Mesh_ResetTextureState (void)
Definition at line 2108 of file gl_backend.c.
{
#if 0
    unsigned int unitnum;
    BACKENDACTIVECHECK
    for (unitnum = 0;unitnum < MAX_TEXTUREUNITS;unitnum++)
        R_Mesh_TexBind(unitnum, NULL);
#endif
}
Referenced by R_DrawBBoxMesh(), R_DrawTextureSurfaceList_Sky(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawPrepass(), R_Shadow_RenderMode_Begin(), R_Shadow_RenderMode_Lighting(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_ShadowMap().
R_Mesh_SetRenderTargets()
void R_Mesh_SetRenderTargets (int fbo, rtexture_t * depthtexture, rtexture_t * colortexture, rtexture_t * colortexture2, rtexture_t * colortexture3, rtexture_t * colortexture4)
Definition at line 1053 of file gl_backend.c.
{
    unsigned int i;
    unsigned int j;
    rtexture_t *textures[5];
    Vector4Set(textures, colortexture, colortexture2, colortexture3, colortexture4);
    textures[4] = depthtexture;
    // unbind any matching textures immediately, otherwise D3D will complain about a bound texture being used as a render target
    for (j = 0;j < 5;j++)
        if (textures[j])
            for (i = 0;i < MAX_TEXTUREUNITS;i++)
                if (gl_state.units[i].texture == textures[j])
                    R_Mesh_TexBind(i, NULL);
    // set up framebuffer object or render targets for the active rendering API
    switch (vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        if (gl_state.framebufferobject != fbo)
        {
            gl_state.framebufferobject = fbo;
            qglBindFramebuffer(GL_FRAMEBUFFER, gl_state.framebufferobject ? gl_state.framebufferobject : gl_state.defaultframebufferobject);CHECKGLERROR
        }
        break;
    }
}
Referenced by CL_UpdateScreen(), R_Bloom_MakeTexture(), R_Mesh_CreateFramebufferObject(), R_Mesh_Finish(), R_Mesh_Start(), R_RenderView(), R_ResetViewRendering2D_Common(), R_SetupView(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawPrepass(), R_Shadow_PrepareLights(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_ShadowMap().
R_Mesh_Start()
void R_Mesh_Start (void)
Definition at line 1550 of file gl_backend.c.
{
    BACKENDACTIVECHECK
    R_Mesh_SetRenderTargets(0, NULL, NULL, NULL, NULL, NULL);
    if (gl_printcheckerror.integer && !gl_paranoid.integer)
    {
        Con_Printf(CON_WARN "WARNING: gl_printcheckerror is on but gl_paranoid is off, turning it on...\n");
        Cvar_SetValueQuick(&gl_paranoid, 1);
    }
}
Referenced by R_Envmap_f(), and SCR_DrawScreen().
R_Mesh_TexBind()
void R_Mesh_TexBind (unsigned int unitnum, rtexture_t * tex)
Definition at line 2066 of file gl_backend.c.
{
    gltextureunit_t *unit = gl_state.units + unitnum;
    int texnum;
    if (unitnum >= MAX_TEXTUREUNITS)
        Sys_Error("R_Mesh_TexBind: unitnum %i > max units %i\n", unitnum, MAX_TEXTUREUNITS);
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        if (tex)
        {
            texnum = R_GetTexture(tex);
            switch (tex->gltexturetypeenum)
            {
            case GL_TEXTURE_2D:
                if (unit->t2d != texnum) { GL_ActiveTexture(unitnum);qglBindTexture(GL_TEXTURE_2D, texnum); CHECKGLERROR unit->t2d = texnum; }
                if (unit->t3d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_3D, 0); CHECKGLERROR unit->t3d = 0; }
                if (unit->tcubemap) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_CUBE_MAP, 0); CHECKGLERROR unit->tcubemap = 0; }
                break;
            case GL_TEXTURE_3D:
                if (unit->t2d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_2D, 0); CHECKGLERROR unit->t2d = 0; }
                if (unit->t3d != texnum) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_3D, texnum); CHECKGLERROR unit->t3d = texnum; }
                if (unit->tcubemap) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_CUBE_MAP, 0); CHECKGLERROR unit->tcubemap = 0; }
                break;
            case GL_TEXTURE_CUBE_MAP:
                if (unit->t2d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_2D, 0); CHECKGLERROR unit->t2d = 0; }
                if (unit->t3d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_3D, 0); CHECKGLERROR unit->t3d = 0; }
                if (unit->tcubemap != texnum) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_CUBE_MAP, texnum); CHECKGLERROR unit->tcubemap = texnum; }
                break;
            }
        }
        else
        {
            if (unit->t2d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_2D, 0); CHECKGLERROR unit->t2d = 0; }
            if (unit->t3d) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_3D, 0); CHECKGLERROR unit->t3d = 0; }
            if (unit->tcubemap) { GL_ActiveTexture(unitnum); qglBindTexture(GL_TEXTURE_CUBE_MAP, 0); CHECKGLERROR unit->tcubemap = 0; }
        }
    }
    unit->texture = tex;
}
Referenced by R_BlendView(), R_Mesh_ClearBindingsForTexture(), R_Mesh_CopyToTexture(), R_Mesh_ResetTextureState(), R_Mesh_SetRenderTargets(), R_SetupShader_DeferredLight(), R_SetupShader_Generic(), and R_SetupShader_Surface().
R_Mesh_TexBound()
int R_Mesh_TexBound (unsigned int unitnum, int id)
Definition at line 2026 of file gl_backend.c.
{
    gltextureunit_t *unit = gl_state.units + unitnum;
    if (unitnum >= MAX_TEXTUREUNITS)
        Sys_Error("R_Mesh_TexCoordPointer: unitnum %i > max units %i\n", unitnum, MAX_TEXTUREUNITS);
    if (id == GL_TEXTURE_2D)
        return unit->t2d;
    if (id == GL_TEXTURE_3D)
        return unit->t3d;
    if (id == GL_TEXTURE_CUBE_MAP)
        return unit->tcubemap;
    return 0;
}
Referenced by GL_TextureMode_f(), R_LoadTextureDDSFile(), R_SaveTextureDDSFile(), R_Textures_Frame(), R_UploadFullTexture(), and R_UploadPartialTexture().
R_Mesh_TexCoordPointer()
void R_Mesh_TexCoordPointer (unsigned int unitnum, int components, int gltype, size_t stride, const void * pointer, const r_meshbuffer_t * vertexbuffer, size_t bufferoffset)
Definition at line 1977 of file gl_backend.c.
{
    gltextureunit_t *unit = gl_state.units + unitnum;
    if (unitnum >= MAX_TEXTUREUNITS)
        Sys_Error("R_Mesh_TexCoordPointer: unitnum %i > max units %i\n", unitnum, MAX_TEXTUREUNITS);
    // update array settings
    // note: there is no need to check bufferobject here because all cases
    // that involve a valid bufferobject also supply a texcoord array
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        if (pointer)
        {
            int bufferobject = vertexbuffer ? vertexbuffer->bufferobject : 0;
            // texture array unit is enabled, enable the array
            if (!unit->arrayenabled)
            {
                unit->arrayenabled = true;
                qglEnableVertexAttribArray(unitnum+GLSLATTRIB_TEXCOORD0);CHECKGLERROR
            }
            // texcoord array
            if (unit->pointer_texcoord_components != components || unit->pointer_texcoord_gltype != gltype || unit->pointer_texcoord_stride != stride || unit->pointer_texcoord_pointer != pointer || unit->pointer_texcoord_vertexbuffer != vertexbuffer || unit->pointer_texcoord_offset != bufferoffset)
            {
                unit->pointer_texcoord_components = components;
                unit->pointer_texcoord_gltype = gltype;
                unit->pointer_texcoord_stride = stride;
                unit->pointer_texcoord_pointer = pointer;
                unit->pointer_texcoord_vertexbuffer = vertexbuffer;
                unit->pointer_texcoord_offset = bufferoffset;
                GL_BindVBO(bufferobject);
                // LadyHavoc: special flag added to gltype for unnormalized types
                qglVertexAttribPointer(unitnum+GLSLATTRIB_TEXCOORD0, components, gltype & ~0x80000000, (gltype & 0x80000000) == 0, (GLsizei)stride, bufferobject ? (void *)bufferoffset : pointer);CHECKGLERROR
            }
        }
        else
        {
            // texture array unit is disabled, disable the array
            if (unit->arrayenabled)
            {
                unit->arrayenabled = false;
                qglDisableVertexAttribArray(unitnum+GLSLATTRIB_TEXCOORD0);CHECKGLERROR
            }
        }
        break;
    }
}
Referenced by R_Mesh_PrepareVertices_Generic_Arrays(), R_Mesh_PrepareVertices_Mesh_Arrays(), R_Mesh_PrepareVertices_Vertex3f(), and RSurf_UploadBuffersForBatch().
R_Mesh_UpdateMeshBuffer()
void R_Mesh_UpdateMeshBuffer (r_meshbuffer_t * buffer, const void * data, size_t size, qbool subdata, size_t offset)
Definition at line 1781 of file gl_backend.c.
{
    if (!buffer)
        return;
    if (buffer->isindexbuffer)
    {
        r_refdef.stats[r_stat_indexbufferuploadcount]++;
        r_refdef.stats[r_stat_indexbufferuploadsize] += (int)size;
    }
    else
    {
        r_refdef.stats[r_stat_vertexbufferuploadcount]++;
        r_refdef.stats[r_stat_vertexbufferuploadsize] += (int)size;
    }
    if (!subdata)
        buffer->size = size;
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        if (!buffer->bufferobject)
            qglGenBuffers(1, (GLuint *)&buffer->bufferobject);
        CHECKGLERROR
        if (buffer->isuniformbuffer)
            GL_BindUBO(buffer->bufferobject);
        else if (buffer->isindexbuffer)
            GL_BindEBO(buffer->bufferobject);
        else
            GL_BindVBO(buffer->bufferobject);
        {
            int buffertype;
            buffertype = buffer->isindexbuffer ? GL_ELEMENT_ARRAY_BUFFER : GL_ARRAY_BUFFER;
#ifdef GL_UNIFORM_BUFFER
            if (buffer->isuniformbuffer)
                buffertype = GL_UNIFORM_BUFFER;
#endif
            CHECKGLERROR
            if (subdata)
                qglBufferSubData(buffertype, offset, size, data);
            else
                qglBufferData(buffertype, size, data, buffer->isdynamic ? GL_STREAM_DRAW : GL_STATIC_DRAW);
            CHECKGLERROR
        }
        if (buffer->isuniformbuffer)
            GL_BindUBO(0);
        break;
    }
}
Referenced by R_BufferData_Store(), and R_Mesh_CreateMeshBuffer().
R_Mesh_VertexPointer()
void R_Mesh_VertexPointer (int components, int gltype, size_t stride, const void * pointer, const r_meshbuffer_t * vertexbuffer, size_t bufferoffset)
Definition at line 1902 of file gl_backend.c.
{
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        if (gl_state.pointer_vertex_components != components || gl_state.pointer_vertex_gltype != gltype || gl_state.pointer_vertex_stride != stride || gl_state.pointer_vertex_pointer != pointer || gl_state.pointer_vertex_vertexbuffer != vertexbuffer || gl_state.pointer_vertex_offset != bufferoffset)
        {
            int bufferobject = vertexbuffer ? vertexbuffer->bufferobject : 0;
            if (!bufferobject && gl_paranoid.integer)
                Con_DPrintf("Warning: no bufferobject in R_Mesh_VertexPointer(%i, %i, %i, %p, %p, %08x)", components, gltype, (int)stride, pointer, (void *)vertexbuffer, (unsigned int)bufferoffset);
            gl_state.pointer_vertex_components = components;
            gl_state.pointer_vertex_gltype = gltype;
            gl_state.pointer_vertex_stride = stride;
            gl_state.pointer_vertex_pointer = pointer;
            gl_state.pointer_vertex_vertexbuffer = vertexbuffer;
            gl_state.pointer_vertex_offset = bufferoffset;
            CHECKGLERROR
            GL_BindVBO(bufferobject);
            // LadyHavoc: special flag added to gltype for unnormalized types
            qglVertexAttribPointer(GLSLATTRIB_POSITION, components, gltype & ~0x80000000, (gltype & 0x80000000) == 0, (GLsizei)stride, bufferobject ? (void *)bufferoffset : pointer);CHECKGLERROR
        }
        break;
    }
}
Referenced by R_Mesh_PrepareVertices_Generic_Arrays(), R_Mesh_PrepareVertices_Mesh_Arrays(), R_Mesh_PrepareVertices_Vertex3f(), and RSurf_UploadBuffersForBatch().
R_ScissorForBBox()
qbool R_ScissorForBBox (const float * mins, const float * maxs, int * scissor)
Definition at line 429 of file gl_backend.c.
{
    int i, ix1, iy1, ix2, iy2;
    float x1, y1, x2, y2;
    vec4_t v, v2;
    float vertex[20][3];
    int j, k;
    vec4_t plane4f;
    int numvertices;
    float corner[8][4];
    float dist[8];
    int sign[8];
    float f;
    scissor[0] = r_refdef.view.viewport.x;
    scissor[1] = r_refdef.view.viewport.y;
    scissor[2] = r_refdef.view.viewport.width;
    scissor[3] = r_refdef.view.viewport.height;
    // if view is inside the box, just say yes it's visible
    if (BoxesOverlap(r_refdef.view.origin, r_refdef.view.origin, mins, maxs))
        return false;
    // transform all corners that are infront of the nearclip plane
    VectorNegate(r_refdef.view.frustum[4].normal, plane4f);
    plane4f[3] = r_refdef.view.frustum[4].dist;
    numvertices = 0;
    for (i = 0;i < 8;i++)
    {
        Vector4Set(corner[i], (i & 1) ? maxs[0] : mins[0], (i & 2) ? maxs[1] : mins[1], (i & 4) ? maxs[2] : mins[2], 1);
        dist[i] = DotProduct4(corner[i], plane4f);
        sign[i] = dist[i] > 0;
        if (!sign[i])
        {
            VectorCopy(corner[i], vertex[numvertices]);
            numvertices++;
        }
    }
    // if some points are behind the nearclip, add clipped edge points to make
    // sure that the scissor boundary is complete
    if (numvertices > 0 && numvertices < 8)
    {
        // add clipped edge points
        for (i = 0;i < 12;i++)
        {
            j = bboxedges[i][0];
            k = bboxedges[i][1];
            if (sign[j] != sign[k])
            {
                f = dist[j] / (dist[j] - dist[k]);
                VectorLerp(corner[j], f, corner[k], vertex[numvertices]);
                numvertices++;
            }
        }
    }
    // if we have no points to check, it is behind the view plane
    if (!numvertices)
        return true;
    // if we have some points to transform, check what screen area is covered
    x1 = y1 = x2 = y2 = 0;
    v[3] = 1.0f;
    //Con_Printf("%i vertices to transform...\n", numvertices);
    for (i = 0;i < numvertices;i++)
    {
        VectorCopy(vertex[i], v);
        R_Viewport_TransformToScreen(&r_refdef.view.viewport, v, v2);
        //Con_Printf("%.3f %.3f %.3f %.3f transformed to %.3f %.3f %.3f %.3f\n", v[0], v[1], v[2], v[3], v2[0], v2[1], v2[2], v2[3]);
        if (i)
        {
            if (x1 > v2[0]) x1 = v2[0];
            if (x2 < v2[0]) x2 = v2[0];
            if (y1 > v2[1]) y1 = v2[1];
            if (y2 < v2[1]) y2 = v2[1];
        }
        else
        {
            x1 = x2 = v2[0];
            y1 = y2 = v2[1];
        }
    }
    // now convert the scissor rectangle to integer screen coordinates
    ix1 = (int)(x1 - 1.0f);
    //iy1 = vid.height - (int)(y2 - 1.0f);
    //iy1 = r_refdef.view.viewport.width + 2 * r_refdef.view.viewport.x - (int)(y2 - 1.0f);
    iy1 = (int)(y1 - 1.0f);
    ix2 = (int)(x2 + 1.0f);
    //iy2 = vid.height - (int)(y1 + 1.0f);
    //iy2 = r_refdef.view.viewport.height + 2 * r_refdef.view.viewport.y - (int)(y1 + 1.0f);
    iy2 = (int)(y2 + 1.0f);
    //Con_Printf("%f %f %f %f\n", x1, y1, x2, y2);
    // clamp it to the screen
    if (ix1 < r_refdef.view.viewport.x) ix1 = r_refdef.view.viewport.x;
    if (iy1 < r_refdef.view.viewport.y) iy1 = r_refdef.view.viewport.y;
    if (ix2 > r_refdef.view.viewport.x + r_refdef.view.viewport.width) ix2 = r_refdef.view.viewport.x + r_refdef.view.viewport.width;
    if (iy2 > r_refdef.view.viewport.y + r_refdef.view.viewport.height) iy2 = r_refdef.view.viewport.y + r_refdef.view.viewport.height;
    // if it is inside out, it's not visible
    if (ix2 <= ix1 || iy2 <= iy1)
        return true;
    // the light area is visible, set up the scissor rectangle
    scissor[0] = ix1;
    scissor[1] = iy1;
    scissor[2] = ix2 - ix1;
    scissor[3] = iy2 - iy1;
    // D3D Y coordinate is top to bottom, OpenGL is bottom to top, fix the D3D one
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        break;
    }
    return false;
}
Referenced by R_DrawTextureSurfaceList_Sky(), R_Shadow_ScissorForBBox(), and R_Water_ProcessPlanes().
R_SetStencil()
void R_SetStencil (qbool enable, int writemask, int fail, int zfail, int zpass, int compare, int comparereference, int comparemask)
Definition at line 1277 of file gl_backend.c.
{
    switch (vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        if (enable)
        {
            qglEnable(GL_STENCIL_TEST);CHECKGLERROR
        }
        else
        {
            qglDisable(GL_STENCIL_TEST);CHECKGLERROR
        }
        qglStencilMask(writemask);CHECKGLERROR
        qglStencilOp(fail, zfail, zpass);CHECKGLERROR
        qglStencilFunc(compare, comparereference, comparemask);CHECKGLERROR
        CHECKGLERROR
        break;
    }
}
R_SetViewport()
void R_SetViewport (const r_viewport_t * v)
Definition at line 896 of file gl_backend.c.
{
    gl_viewport = *v;
    // FIXME: v_flipped_state is evil, this probably breaks somewhere
    GL_SetMirrorState(v_flipped.integer && (v->type == R_VIEWPORTTYPE_PERSPECTIVE || v->type == R_VIEWPORTTYPE_PERSPECTIVE_INFINITEFARCLIP));
    // copy over the matrices to our state
    gl_viewmatrix = v->viewmatrix;
    gl_projectionmatrix = v->projectmatrix;
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        CHECKGLERROR
        qglViewport(v->x, v->y, v->width, v->height);CHECKGLERROR
        break;
    }
    // force an update of the derived matrices
    gl_modelmatrixchanged = true;
    R_EntityMatrix(&gl_modelmatrix);
}
Referenced by CL_UpdateScreen(), R_Bloom_MakeTexture(), R_ResetViewRendering2D_Common(), R_SetupView(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawModelShadowMaps(), R_Shadow_RenderMode_Reset(), and R_Shadow_RenderMode_ShadowMap().
R_Viewport_InitCubeSideView()
void R_Viewport_InitCubeSideView (r_viewport_t * v, const matrix4x4_t * cameramatrix, int side, int size, float nearclip, float farclip, const float * nearplane)
Definition at line 842 of file gl_backend.c.
{
    matrix4x4_t tempmatrix, basematrix;
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_PERSPECTIVECUBESIDE;
    v->cameramatrix = *cameramatrix;
    v->width = size;
    v->height = size;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[0] = m[5] = 1.0f;
    m[10] = -(farclip + nearclip) / (farclip - nearclip);
    m[11] = -1;
    m[14] = -2 * nearclip * farclip / (farclip - nearclip);
    Matrix4x4_FromArrayFloatGL(&basematrix, cubeviewmatrix[side]);
    Matrix4x4_Invert_Full(&tempmatrix, &v->cameramatrix);
    Matrix4x4_Concat(&v->viewmatrix, &basematrix, &tempmatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
}
R_Viewport_InitOrtho()
void R_Viewport_InitOrtho (r_viewport_t * v, const matrix4x4_t * cameramatrix, int x, int y, int width, int height, float x1, float y1, float x2, float y2, float zNear, float zFar, const float * nearplane)
Definition at line 586 of file gl_backend.c.
{
    float left = x1, right = x2, bottom = y2, top = y1, zNear = nearclip, zFar = farclip;
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_ORTHO;
    v->cameramatrix = *cameramatrix;
    v->x = x;
    v->y = y;
    v->z = 0;
    v->width = width;
    v->height = height;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[0]  = 2/(right - left);
    m[5]  = 2/(top - bottom);
    m[10] = -2/(zFar - zNear);
    m[12] = - (right + left)/(right - left);
    m[13] = - (top + bottom)/(top - bottom);
    m[14] = - (zFar + zNear)/(zFar - zNear);
    m[15] = 1;
    switch(vid.renderpath)
    {
    case RENDERPATH_GL32:
    case RENDERPATH_GLES2:
        break;
    }
    v->screentodepth[0] = -farclip / (farclip - nearclip);
    v->screentodepth[1] = farclip * nearclip / (farclip - nearclip);
    Matrix4x4_Invert_Full(&v->viewmatrix, &v->cameramatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
#if 0
    {
        vec4_t test1;
        vec4_t test2;
        Vector4Set(test1, (x1+x2)*0.5f, (y1+y2)*0.5f, 0.0f, 1.0f);
        R_Viewport_TransformToScreen(v, test1, test2);
        Con_Printf("%f %f %f -> %f %f %f\n", test1[0], test1[1], test1[2], test2[0], test2[1], test2[2]);
    }
#endif
}
Referenced by CL_UpdateScreen(), R_Bloom_MakeTexture(), R_ResetViewRendering2D_Common(), R_Shadow_ClearShadowMapTexture(), and R_Shadow_DrawModelShadowMaps().
R_Viewport_InitOrtho3D()
void R_Viewport_InitOrtho3D (r_viewport_t * v, const matrix4x4_t * cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float nearclip, float farclip, const float * nearplane)
Definition at line 634 of file gl_backend.c.
{
    matrix4x4_t tempmatrix, basematrix;
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_PERSPECTIVE;
    v->cameramatrix = *cameramatrix;
    v->x = x;
    v->y = y;
    v->z = 0;
    v->width = width;
    v->height = height;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[0]  = 1.0 / frustumx;
    m[5]  = 1.0 / frustumy;
    m[10] = -2 / (farclip - nearclip);
    m[14] = -(farclip + nearclip) / (farclip - nearclip);
    m[15] = 1;
    v->screentodepth[0] = -farclip / (farclip - nearclip);
    v->screentodepth[1] = farclip * nearclip / (farclip - nearclip);
    Matrix4x4_Invert_Full(&tempmatrix, &v->cameramatrix);
    Matrix4x4_CreateRotate(&basematrix, -90, 1, 0, 0);
    Matrix4x4_ConcatRotate(&basematrix, 90, 0, 0, 1);
    Matrix4x4_Concat(&v->viewmatrix, &basematrix, &tempmatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    if(v_flipped.integer)
    {
        m[0] = -m[0];
        m[4] = -m[4];
        m[8] = -m[8];
        m[12] = -m[12];
    }
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
}
Referenced by R_SetupView().
R_Viewport_InitPerspective()
void R_Viewport_InitPerspective (r_viewport_t * v, const matrix4x4_t * cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float zNear, float zFar, const float * nearplane)
Definition at line 676 of file gl_backend.c.
{
    matrix4x4_t tempmatrix, basematrix;
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_PERSPECTIVE;
    v->cameramatrix = *cameramatrix;
    v->x = x;
    v->y = y;
    v->z = 0;
    v->width = width;
    v->height = height;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[0]  = 1.0 / frustumx;
    m[5]  = 1.0 / frustumy;
    m[10] = -(farclip + nearclip) / (farclip - nearclip);
    m[11] = -1;
    m[14] = -2 * nearclip * farclip / (farclip - nearclip);
    v->screentodepth[0] = -farclip / (farclip - nearclip);
    v->screentodepth[1] = farclip * nearclip / (farclip - nearclip);
    Matrix4x4_Invert_Full(&tempmatrix, &v->cameramatrix);
    Matrix4x4_CreateRotate(&basematrix, -90, 1, 0, 0);
    Matrix4x4_ConcatRotate(&basematrix, 90, 0, 0, 1);
    Matrix4x4_Concat(&v->viewmatrix, &basematrix, &tempmatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    if(v_flipped.integer)
    {
        m[0] = -m[0];
        m[4] = -m[4];
        m[8] = -m[8];
        m[12] = -m[12];
    }
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
}
Referenced by R_SetupView().
R_Viewport_InitPerspectiveInfinite()
void R_Viewport_InitPerspectiveInfinite (r_viewport_t * v, const matrix4x4_t * cameramatrix, int x, int y, int width, int height, float frustumx, float frustumy, float zNear, const float * nearplane)
Definition at line 718 of file gl_backend.c.
{
    matrix4x4_t tempmatrix, basematrix;
    const float nudge = 1.0 - 1.0 / (1<<23);
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_PERSPECTIVE_INFINITEFARCLIP;
    v->cameramatrix = *cameramatrix;
    v->x = x;
    v->y = y;
    v->z = 0;
    v->width = width;
    v->height = height;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[ 0] = 1.0 / frustumx;
    m[ 5] = 1.0 / frustumy;
    m[10] = -nudge;
    m[11] = -1;
    m[14] = -2 * nearclip * nudge;
    v->screentodepth[0] = (m[10] + 1) * 0.5 - 1;
    v->screentodepth[1] = m[14] * -0.5;
    Matrix4x4_Invert_Full(&tempmatrix, &v->cameramatrix);
    Matrix4x4_CreateRotate(&basematrix, -90, 1, 0, 0);
    Matrix4x4_ConcatRotate(&basematrix, 90, 0, 0, 1);
    Matrix4x4_Concat(&v->viewmatrix, &basematrix, &tempmatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    if(v_flipped.integer)
    {
        m[0] = -m[0];
        m[4] = -m[4];
        m[8] = -m[8];
        m[12] = -m[12];
    }
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
}
Referenced by R_SetupView().
R_Viewport_InitRectSideView()
void R_Viewport_InitRectSideView (r_viewport_t * v, const matrix4x4_t * cameramatrix, int side, int size, int border, float nearclip, float farclip, const float * nearplane, int offsetx, int offsety)
Definition at line 868 of file gl_backend.c.
{
    matrix4x4_t tempmatrix, basematrix;
    float m[16];
    memset(v, 0, sizeof(*v));
    v->type = R_VIEWPORTTYPE_PERSPECTIVECUBESIDE;
    v->cameramatrix = *cameramatrix;
    v->x = offsetx + (side & 1) * size;
    v->y = offsety + (side >> 1) * size;
    v->width = size;
    v->height = size;
    v->depth = 1;
    memset(m, 0, sizeof(m));
    m[0] = m[5] = 1.0f * ((float)size - border) / size;
    m[10] = -(farclip + nearclip) / (farclip - nearclip);
    m[11] = -1;
    m[14] = -2 * nearclip * farclip / (farclip - nearclip);
    Matrix4x4_FromArrayFloatGL(&basematrix, rectviewmatrix[side]);
    Matrix4x4_Invert_Full(&tempmatrix, &v->cameramatrix);
    Matrix4x4_Concat(&v->viewmatrix, &basematrix, &tempmatrix);
    if (nearplane)
        R_Viewport_ApplyNearClipPlaneFloatGL(v, m, nearplane[0], nearplane[1], nearplane[2], nearplane[3]);
    Matrix4x4_FromArrayFloatGL(&v->projectmatrix, m);
}
Referenced by R_Shadow_RenderMode_ShadowMap().
R_Viewport_TransformToScreen()
void R_Viewport_TransformToScreen (const r_viewport_t * v, const vec4_t in, vec4_t out)
Definition at line 382 of file gl_backend.c.
{
    vec4_t temp;
    float iw;
    Matrix4x4_Transform4 (&v->viewmatrix, in, temp);
    Matrix4x4_Transform4 (&v->projectmatrix, temp, out);
    iw = 1.0f / out[3];
    out[0] = v->x + (out[0] * iw + 1.0f) * v->width * 0.5f;
    // for an odd reason, inverting this is wrong for R_Shadow_ScissorForBBox (we then get badly scissored lights)
    //out[1] = v->y + v->height - (out[1] * iw + 1.0f) * v->height * 0.5f;
    out[1] = v->y + (out[1] * iw + 1.0f) * v->height * 0.5f;
    out[2] = v->z + (out[2] * iw + 1.0f) * v->depth * 0.5f;
}
Referenced by R_DebugLine(), R_ScissorForBBox(), and R_Viewport_InitOrtho().
SCR_ScreenShot()
qbool SCR_ScreenShot (char * filename, unsigned char * buffer1, unsigned char * buffer2, int x, int y, int width, int height, qbool flipx, qbool flipy, qbool flipdiagonal, qbool jpeg, qbool png, qbool gammacorrect, qbool keep_alpha)
Definition at line 1474 of file cl_screen.c.
{
    int indices[4] = {0,1,2,3}; // BGRA
    qbool ret;
    GL_ReadPixelsBGRA(x, y, width, height, buffer1);
    if(gammacorrect && (scr_screenshot_gammaboost.value != 1))
    {
        int i;
        double igamma = 1.0 / scr_screenshot_gammaboost.value;
        unsigned short vidramp[256 * 3];
        // identity gamma table
        BuildGammaTable16(1.0f, 1.0f, 1.0f, 0.0f, 1.0f, vidramp, 256);
        BuildGammaTable16(1.0f, 1.0f, 1.0f, 0.0f, 1.0f, vidramp + 256, 256);
        BuildGammaTable16(1.0f, 1.0f, 1.0f, 0.0f, 1.0f, vidramp + 256*2, 256);
        if(scr_screenshot_gammaboost.value != 1)
        {
            for (i = 0;i < 256 * 3;i++)
                vidramp[i] = (unsigned short) (0.5 + pow(vidramp[i] * (1.0 / 65535.0), igamma) * 65535.0);
        }
        for (i = 0;i < width*height*4;i += 4)
        {
            buffer1[i] = (unsigned char) (vidramp[buffer1[i] + 512] * 255.0 / 65535.0 + 0.5); // B
            buffer1[i+1] = (unsigned char) (vidramp[buffer1[i+1] + 256] * 255.0 / 65535.0 + 0.5); // G
            buffer1[i+2] = (unsigned char) (vidramp[buffer1[i+2]] * 255.0 / 65535.0 + 0.5); // R
            // A
        }
    }
    if(keep_alpha && !jpeg)
    {
        if(!png)
            flipy = !flipy; // TGA: not preflipped
        Image_CopyMux (buffer2, buffer1, width, height, flipx, flipy, flipdiagonal, 4, 4, indices);
        if (png)
            ret = PNG_SaveImage_preflipped (filename, width, height, true, buffer2);
        else
            ret = Image_WriteTGABGRA(filename, width, height, buffer2);
    }
    else
    {
        if(jpeg)
        {
            indices[0] = 2;
            indices[2] = 0; // RGB
        }
        Image_CopyMux (buffer2, buffer1, width, height, flipx, flipy, flipdiagonal, 3, 4, indices);
        if (jpeg)
            ret = JPEG_SaveImage_preflipped (filename, width, height, buffer2);
        else if (png)
            ret = PNG_SaveImage_preflipped (filename, width, height, false, buffer2);
        else
            ret = Image_WriteTGABGR_preflipped (filename, width, height, buffer2);
    }
    return ret;
}
Referenced by R_Envmap_f(), SCR_DrawScreen(), and SCR_ScreenShot_f().
Variable Documentation
gl_debug
cvar_t gl_debug extern
Definition at line 7 of file gl_backend.c.
{CF_CLIENT, "gl_debug", "0", "enables OpenGL debug output, 0 = off, 1 = HIGH severity only, 2 = also MEDIUM severity, 3 = also LOW severity messages.  (note: enabling may not take effect until vid_restart on some drivers)"};
Referenced by gl_backend_init(), GL_Backend_ResetState(), and VID_InitModeGL().
gl_modelmatrix
matrix4x4_t gl_modelmatrix extern
Definition at line 20 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetViewport().
gl_modelmatrixchanged
qbool gl_modelmatrixchanged extern
Definition at line 27 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetViewport().
gl_modelview16f
float gl_modelview16f[16] extern
Definition at line 25 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetupShader_SetPermutationGLSL().
gl_modelviewmatrix
matrix4x4_t gl_modelviewmatrix extern
Definition at line 22 of file gl_backend.c.
Referenced by R_EntityMatrix().
gl_modelviewprojection16f
float gl_modelviewprojection16f[16] extern
Definition at line 26 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetupShader_SetPermutationGLSL().
gl_modelviewprojectionmatrix
matrix4x4_t gl_modelviewprojectionmatrix extern
Definition at line 24 of file gl_backend.c.
Referenced by R_EntityMatrix().
gl_paranoid
cvar_t gl_paranoid extern
Definition at line 8 of file gl_backend.c.
{CF_CLIENT, "gl_paranoid", "0", "enables OpenGL error checking and other tests"};
Referenced by gl_backend_init(), Host_Init(), Mod_BuildVBOs(), Mod_Mesh_Finalize(), R_Mesh_Draw(), R_Mesh_Start(), and R_Mesh_VertexPointer().
gl_printcheckerror
cvar_t gl_printcheckerror extern
Definition at line 9 of file gl_backend.c.
{CF_CLIENT, "gl_printcheckerror", "0", "prints all OpenGL error checks, useful to identify location of driver crashes"};
Referenced by gl_backend_init(), Host_Init(), and R_Mesh_Start().
gl_projectionmatrix
matrix4x4_t gl_projectionmatrix extern
Definition at line 23 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetViewport().
gl_viewmatrix
matrix4x4_t gl_viewmatrix extern
Definition at line 21 of file gl_backend.c.
Referenced by R_EntityMatrix(), and R_SetViewport().
gl_viewport
r_viewport_t gl_viewport extern
Definition at line 19 of file gl_backend.c.
Referenced by R_GetViewport(), and R_SetViewport().
polygonelement3i
int polygonelement3i[(POLYGONELEMENTS_MAXPOINTS-2) *3] extern
Definition at line 241 of file gl_backend.c.
Referenced by gl_backend_init(), R_BeginCoronaQuery(), R_BlendView(), R_Bloom_MakeTexture(), R_DrawCorona(), R_DrawDebugModel(), R_DrawPortal_Callback(), R_Model_Sprite_Draw_TransparentCallback(), R_MotionBlurView(), R_Shadow_DrawCursor_TransparentCallback(), R_Shadow_DrawLightSprite_TransparentCallback(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
polygonelement3s
unsigned short polygonelement3s[(POLYGONELEMENTS_MAXPOINTS-2) *3] extern
Definition at line 242 of file gl_backend.c.
Referenced by gl_backend_init(), R_BeginCoronaQuery(), R_BlendView(), R_Bloom_MakeTexture(), R_DrawCorona(), R_DrawDebugModel(), R_DrawPortal_Callback(), R_Model_Sprite_Draw_TransparentCallback(), R_MotionBlurView(), R_Shadow_DrawCursor_TransparentCallback(), R_Shadow_DrawLightSprite_TransparentCallback(), SCR_DrawLoadingScreen(), and SCR_DrawLoadingStack().
quadelement3i
int quadelement3i[QUADELEMENTS_MAXQUADS *6] extern
Definition at line 243 of file gl_backend.c.
Referenced by gl_backend_init().
quadelement3s
unsigned short quadelement3s[QUADELEMENTS_MAXQUADS *6] extern
Definition at line 244 of file gl_backend.c.
Referenced by gl_backend_init().