DarkPlaces: host.c File Reference
host.c File Reference
#include "quakedef.h"
#include <time.h>
#include "libcurl.h"
#include "taskqueue.h"
#include "utf8lib.h"
Functions
void Host_AbortCurrentFrame (void)
void Host_Error (const char *error,...)
static void Host_Quit_f (cmd_state_t *cmd)
static void Host_Version_f (cmd_state_t *cmd)
static void Host_Framerate_c (cvar_t *var)
static void SendCvar_f (cmd_state_t *cmd)
void Host_SaveConfig (const char *file)
static void Host_SaveConfig_f (cmd_state_t *cmd)
static void Host_AddConfigText (cmd_state_t *cmd)
static void Host_LoadConfig_f (cmd_state_t *cmd)
static void Host_InitLocal (void)
static void Host_InitSession (void)
void Host_LockSession (void)
void Host_UnlockSession (void)
static void Host_Init (void)
static void Host_Shutdown (void)
static double Host_Frame (double time)
static double Host_UpdateTime (double newtime, double oldtime)
void Host_Main (void)
Variables
host_static_t host
cvar_t host_framerate = {CF_CLIENT | CF_SERVER, "host_framerate","0", "locks frame timing to this value in seconds, 0.05 is 20fps for example, note that this can easily run too fast, use cl_maxfps if you want to limit your framerate instead, or sys_ticrate to limit server speed"}
cvar_t host_speeds = {CF_CLIENT | CF_SERVER, "host_speeds","0", "reports how much time is used in server/graphics/sound"}
cvar_t host_maxwait = {CF_CLIENT | CF_SERVER, "host_maxwait","1000", "maximum sleep time requested from the operating system in millisecond. Larger sleeps will be done using multiple host_maxwait length sleeps. Lowering this value will increase CPU load, but may help working around problems with accuracy of sleep times."}
cvar_t developer = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "developer","0", "shows debugging messages and information (recommended for all developers and level designers); the value -1 also suppresses buffering and logging these messages"}
cvar_t developer_extra = {CF_CLIENT | CF_SERVER, "developer_extra", "0", "prints additional debugging messages, often very verbose!"}
cvar_t developer_insane = {CF_CLIENT | CF_SERVER, "developer_insane", "0", "prints huge streams of information about internal workings, entire contents of files being read/written, etc. Not recommended!"}
cvar_t developer_loadfile = {CF_CLIENT | CF_SERVER, "developer_loadfile","0", "prints name and size of every file loaded via the FS_LoadFile function (which is almost everything)"}
cvar_t developer_loading = {CF_CLIENT | CF_SERVER, "developer_loading","0", "prints information about files as they are loaded or unloaded successfully"}
cvar_t developer_entityparsing = {CF_CLIENT, "developer_entityparsing", "0", "prints detailed network entities information each time a packet is received"}
cvar_t timestamps = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timestamps", "0", "prints timestamps on console messages"}
cvar_t timeformat = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timeformat", "[%Y-%m-%d %H:%M:%S] ", "time format to use on timestamped console messages"}
cvar_t sessionid = {CF_CLIENT | CF_SERVER | CF_READONLY, "sessionid", "", "ID of the current session (use the -sessionid parameter to set it); this is always either empty or begins with a dot (.)"}
cvar_t locksession = {CF_CLIENT | CF_SERVER, "locksession", "0", "Lock the session? 0 = no, 1 = yes and abort on failure, 2 = yes and continue on failure"}
cvar_t host_isclient = {CF_SHARED | CF_READONLY, "_host_isclient", "0", "If 1, clientside is active."}
cvar_t r_texture_jpeg_fastpicmip
char engineversion [128]
static qfile_t * locksession_fh = NULL
static qbool locksession_run = false
Function Documentation
Host_AbortCurrentFrame()
void Host_AbortCurrentFrame (void)
Definition at line 71 of file host.c.
{
    // in case we were previously nice, make us mean again
    Sys_MakeProcessMean();
    longjmp (host.abortframe, 1);
}
Referenced by Host_Error(), and MVM_error_cmd().
Host_AddConfigText()
static void Host_AddConfigText (cmd_state_t * cmd) static
Definition at line 225 of file host.c.
{
    // set up the default startmap_sp and startmap_dm aliases (mods can
    // override these) and then execute the quake.rc startup script
    if (gamemode == GAME_NEHAHRA)
        Cbuf_InsertText(cmd, "alias startmap_sp \"map nehstart\"\nalias startmap_dm \"map nehstart\"\nexec " STARTCONFIGFILENAME "\n");
    else if (gamemode == GAME_TRANSFUSION)
        Cbuf_InsertText(cmd, "alias startmap_sp \"map e1m1\"\n""alias startmap_dm \"map bb1\"\nexec " STARTCONFIGFILENAME "\n");
    else if (gamemode == GAME_TEU)
        Cbuf_InsertText(cmd, "alias startmap_sp \"map start\"\nalias startmap_dm \"map start\"\nexec teu.rc\n");
    else
        Cbuf_InsertText(cmd, "alias startmap_sp \"map start\"\nalias startmap_dm \"map start\"\nexec " STARTCONFIGFILENAME "\n");
    // if quake.rc is missing, use default
    if (!FS_FileExists(STARTCONFIGFILENAME))
        Cbuf_InsertText(cmd, "exec default.cfg\nexec " CONFIGFILENAME "\nexec autoexec.cfg\n");
}
Referenced by Host_Init(), and Host_LoadConfig_f().
Host_Error()
void Host_Error (const char * error, ...)
Definition at line 86 of file host.c.
{
    static char hosterrorstring1[MAX_INPUTLINE]; // THREAD UNSAFE
    static char hosterrorstring2[MAX_INPUTLINE]; // THREAD UNSAFE
    static qbool hosterror = false;
    va_list argptr;
    int outfd = sys.outfd;
    // set output to stderr
    sys.outfd = fileno(stderr);
    // turn off rcon redirect if it was active when the crash occurred
    // to prevent loops when it is a networking problem
    Con_Rcon_Redirect_Abort();
    va_start (argptr,error);
    dpvsnprintf (hosterrorstring1,sizeof(hosterrorstring1),error,argptr);
    va_end (argptr);
    Con_Printf(CON_ERROR "Host_Error: %s\n", hosterrorstring1);
    // LadyHavoc: if crashing very early, or currently shutting down, do
    // Sys_Error instead
    if (host.framecount < 3 || host.state == host_shutdown)
        Sys_Error ("Host_Error during %s: %s", host.framecount < 3 ? "startup" : "shutdown", hosterrorstring1);
    if (hosterror)
        Sys_Error ("Host_Error: recursively entered (original error was: %s    new error is: %s)", hosterrorstring2, hosterrorstring1);
    hosterror = true;
    dp_strlcpy(hosterrorstring2, hosterrorstring1, sizeof(hosterrorstring2));
    CL_Parse_DumpPacket();
    CL_Parse_ErrorCleanUp();
    // print out where the crash happened, if it was caused by QC (and do a cleanup)
    PRVM_Crash();
    if(host.hook.SV_Shutdown)
        host.hook.SV_Shutdown();
    if (cls.state == ca_dedicated)
        Sys_Error("Host_Error: %s", hosterrorstring1);        // dedicated servers exit
    // prevent an endless loop if the error was triggered by a command
    Cbuf_Clear(cmd_local->cbuf);
    CL_DisconnectEx(false, "Host_Error: %s", hosterrorstring1);
    cls.demonum = -1; // stop demo loop
    hosterror = false;
    // restore configured outfd
    sys.outfd = outfd;
    Host_AbortCurrentFrame();
}
Referenced by AddPortalToNodes(), CL_ExpandCSQCRenderEntities(), CL_ExpandEntities(), CL_ParseDownload(), CL_ParseServerInfo(), CL_ParseServerMessage(), CL_ParseStatic(), CL_ParseTempEntity(), CL_ValidateState(), CL_VM_Init(), CSQC_ReadEntities(), Curl_Begin(), EntityFrame_CL_ReadFrame(), EntityFrameQuake_ReadEntity(), EntityFrameQW_CL_ReadFrame(), EntityState5_ReadUpdate(), Mod_BSP_LoadSubmodels(), Mod_BSP_RecursiveNodePortals(), Mod_DARKPLACESMODEL_Load(), Mod_FindName(), Mod_IBSP_Load(), Mod_IDP0_Load(), Mod_IDP2_Load(), Mod_IDP3_Load(), Mod_IDS2_Load(), Mod_IDSP_Load(), Mod_INTERQUAKEMODEL_Load(), Mod_MAP_Load(), Mod_PSKMODEL_Load(), Mod_Q1BSP_Load(), Mod_Q1BSP_LoadClipnodes(), Mod_Q1BSP_LoadEdges(), Mod_Q1BSP_LoadFaces(), Mod_Q1BSP_LoadLeaffaces(), Mod_Q1BSP_LoadLeafs(), Mod_Q1BSP_LoadNodes(), Mod_Q1BSP_LoadPlanes(), Mod_Q1BSP_LoadSurfedges(), Mod_Q1BSP_LoadTexinfo(), Mod_Q1BSP_LoadVertexes(), Mod_Q2BSP_Load(), Mod_Q2BSP_LoadBrushes(), Mod_Q2BSP_LoadBrushSides(), Mod_Q2BSP_LoadLeafBrushes(), Mod_Q2BSP_LoadLeafs(), Mod_Q2BSP_LoadNodes(), Mod_Q2BSP_LoadTexinfo(), Mod_Q3BSP_Load(), Mod_Q3BSP_LoadBrushes(), Mod_Q3BSP_LoadBrushSides(), Mod_Q3BSP_LoadBrushSides_IG(), Mod_Q3BSP_LoadEffects(), Mod_Q3BSP_LoadFaces(), Mod_Q3BSP_LoadLeafBrushes(), Mod_Q3BSP_LoadLeafFaces(), Mod_Q3BSP_LoadLeafs(), Mod_Q3BSP_LoadLightGrid(), Mod_Q3BSP_LoadLightmaps(), Mod_Q3BSP_LoadModels(), Mod_Q3BSP_LoadNodes(), Mod_Q3BSP_LoadPlanes(), Mod_Q3BSP_LoadPVS(), Mod_Q3BSP_LoadTextures(), Mod_Q3BSP_LoadTriangles(), Mod_Q3BSP_LoadVertices(), Mod_Sprite_SharedSetup(), Mod_VBSP_Load(), Mod_VBSP_LoadEdges(), Mod_VBSP_LoadFaces(), Mod_VBSP_LoadPlanes(), Mod_VBSP_LoadSurfedges(), Mod_VBSP_LoadTexinfo(), Mod_VBSP_LoadVertexes(), Mod_ZYMOTICMODEL_Load(), NetConn_OpenServerPorts(), QW_CL_ParseDownload(), QW_CL_ParseModelList(), QW_CL_ParseSoundList(), R_FreeTexture(), R_FreeTexturePool(), R_GetTexTypeInfo(), R_MakeResizeBufferBigger(), R_UpdateTexture(), RemovePortalFromNodes(), SV_Loadgame_f(), SV_VM_Setup(), and SZ_GetSpace().
Host_Frame()
static double Host_Frame (double time) static
Definition at line 616 of file host.c.
{
    double cl_wait, sv_wait;
    TaskQueue_Frame(false);
    // keep the random time dependent, but not when playing demos/benchmarking
    if(!*sv_random_seed.string && !host.restless)
        rand();
    NetConn_UpdateSockets();
    Log_DestBuffer_Flush();
    // Run any downloads
    Curl_Frame();
    // get new SDL events and add commands from keybindings to the cbuf
    Sys_SDL_HandleEvents();
    // process console commands
    Cbuf_Frame(host.cbuf);
    R_TimeReport("---");
    // if the accumulators haven't become positive yet, wait a while
    sv_wait = - SV_Frame(time);
    cl_wait = - CL_Frame(time);
    Mem_CheckSentinelsGlobal();
    if (cls.state == ca_dedicated)
        return sv_wait; // dedicated
    else if (!sv.active || svs.threaded)
        return cl_wait; // connected to server, main menu, or server is on different thread
    else
        return min(cl_wait, sv_wait); // listen server or singleplayer
}
Referenced by Host_Main().
Host_Framerate_c()
static void Host_Framerate_c (cvar_t * var) static
Definition at line 162 of file host.c.
{
    if (var->value < 0.00001 && var->value != 0)
        Cvar_SetValueQuick(var, 0);
}
Referenced by Host_InitLocal().
Host_Init()
static void Host_Init (void) static
Definition at line 370 of file host.c.
{
    int i;
    char vabuf[1024];
    Sys_SDL_Init();
    Memory_Init();
    host.hook.ConnectLocal = NULL;
    host.hook.Disconnect = NULL;
    host.hook.ToggleMenu = NULL;
    host.hook.CL_Intermission = NULL;
    host.hook.SV_Shutdown = NULL;
    host.state = host_init;
    if (setjmp(host.abortframe)) // Huh?!
        Sys_Error("Engine initialization failed. Check the console (if available) for additional information.\n");
    if (Sys_CheckParm("-profilegameonly"))
        Sys_AllowProfiling(false);
    // LadyHavoc: quake never seeded the random number generator before... heh
    if (Sys_CheckParm("-benchmark"))
        srand(0); // predictable random sequence for -benchmark
    else
        srand((unsigned int)time(NULL));
    // FIXME: this is evil, but possibly temporary
    // LadyHavoc: doesn't seem very temporary...
    // LadyHavoc: made this a saved cvar
// COMMANDLINEOPTION: Console: -developer enables warnings and other notices (RECOMMENDED for mod developers)
    if (Sys_CheckParm("-developer"))
    {
        developer.value = developer.integer = 1;
        developer.string = "1";
    }
    if (Sys_CheckParm("-developer2") || Sys_CheckParm("-developer3"))
    {
        developer.value = developer.integer = 1;
        developer.string = "1";
        developer_extra.value = developer_extra.integer = 1;
        developer_extra.string = "1";
        developer_insane.value = developer_insane.integer = 1;
        developer_insane.string = "1";
        developer_memory.value = developer_memory.integer = 1;
        developer_memory.string = "1";
        developer_memorydebug.value = developer_memorydebug.integer = 1;
        developer_memorydebug.string = "1";
    }
    if (Sys_CheckParm("-developer3"))
    {
        gl_paranoid.integer = 1;gl_paranoid.string = "1";
        gl_printcheckerror.integer = 1;gl_printcheckerror.string = "1";
    }
    // -dedicated is checked in SV_ServerOptions() but that's too late for Cvar_RegisterVariable() to skip all the client-only cvars
    if (Sys_CheckParm ("-dedicated") || !cl_available)
        cls.state = ca_dedicated;
    // initialize console command/cvar/alias/command execution systems
    Cmd_Init();
    // initialize memory subsystem cvars/commands
    Memory_Init_Commands();
    // initialize console and logging and its cvars/commands
    // this enables Con_Printf() messages to be coloured
    Con_Init();
    // initialize various cvars that could not be initialized earlier
    u8_Init();
    Curl_Init_Commands();
    Sys_Init_Commands();
    COM_Init_Commands();
    // initialize filesystem (including fs_basedir, fs_gamedir, -game, scr_screenshot_name, gamename)
    FS_Init();
    // ASAP! construct a version string for the corner of the console and for crash messages
    dpsnprintf (engineversion, sizeof (engineversion), "%s %s%s, buildstring: %s", gamename, DP_OS_NAME, cls.state == ca_dedicated ? " dedicated" : "", buildstring);
    Con_Printf("%s\n", engineversion);
    // initialize process nice level
    Sys_InitProcessNice();
    // initialize ixtable
    Mathlib_Init();
    // register the cvars for session locking
    Host_InitSession();
    // must be after FS_Init
    Crypto_Init();
    Crypto_Init_Commands();
    NetConn_Init();
    Curl_Init();
    PRVM_Init();
    Mod_Init();
    World_Init();
    SV_Init();
    Host_InitLocal();
    Thread_Init();
    TaskQueue_Init();
    CL_Init();
    // save off current state of aliases, commands and cvars for later restore if FS_GameDir_f is called
    // NOTE: menu commands are freed by Cmd_RestoreInitState
    Cmd_SaveInitState();
    // FIXME: put this into some neat design, but the menu should be allowed to crash
    // without crashing the whole game, so this should just be a short-time solution
    // here comes the not so critical stuff
    Host_AddConfigText(cmd_local);
    Cbuf_Execute(cmd_local->cbuf); // cannot be in Host_AddConfigText as that would cause Host_LoadConfig_f to loop!
    host.state = host_active;
    CL_StartVideo();
    Log_Start();
    if (cls.state != ca_dedicated)
    {
        // put up the loading image so the user doesn't stare at a black screen...
        SCR_BeginLoadingPlaque(true);
        S_Startup();
#ifdef CONFIG_MENU
        MR_Init();
#endif
    }
    // check for special benchmark mode
// COMMANDLINEOPTION: Client: -benchmark <demoname> runs a timedemo and quits, results of any timedemo can be found in gamedir/benchmark.log (for example id1/benchmark.log)
    i = Sys_CheckParm("-benchmark");
    if (i && i + 1 < sys.argc)
    if (!sv.active && !cls.demoplayback && !cls.connect_trying)
    {
        Cbuf_AddText(cmd_local, va(vabuf, sizeof(vabuf), "timedemo %s\n", sys.argv[i + 1]));
        Cbuf_Execute(cmd_local->cbuf);
    }
    // check for special demo mode
// COMMANDLINEOPTION: Client: -demo <demoname> runs a playdemo and quits
    i = Sys_CheckParm("-demo");
    if (i && i + 1 < sys.argc)
    if (!sv.active && !cls.demoplayback && !cls.connect_trying)
    {
        Cbuf_AddText(cmd_local, va(vabuf, sizeof(vabuf), "playdemo %s\n", sys.argv[i + 1]));
        Cbuf_Execute(cmd_local->cbuf);
    }
#ifdef CONFIG_VIDEO_CAPTURE
// COMMANDLINEOPTION: Client: -capturedemo <demoname> captures a playdemo and quits
    i = Sys_CheckParm("-capturedemo");
    if (i && i + 1 < sys.argc)
    if (!sv.active && !cls.demoplayback && !cls.connect_trying)
    {
        Cbuf_AddText(cmd_local, va(vabuf, sizeof(vabuf), "playdemo %s\ncl_capturevideo 1\n", sys.argv[i + 1]));
        Cbuf_Execute((cmd_local)->cbuf);
    }
#endif
    if (cls.state == ca_dedicated || Sys_CheckParm("-listen"))
    if (!sv.active && !cls.demoplayback && !cls.connect_trying)
    {
        Cbuf_AddText(cmd_local, "startmap_dm\n");
        Cbuf_Execute(cmd_local->cbuf);
    }
    if (!sv.active && !cls.demoplayback && !cls.connect_trying)
    {
#ifdef CONFIG_MENU
        Cbuf_AddText(cmd_local, "togglemenu 1\n");
#endif
        Cbuf_Execute(cmd_local->cbuf);
    }
    Con_DPrint("========Initialized=========\n");
    if (cls.state != ca_dedicated)
        SV_StartThread();
}
Referenced by Host_Main().
Host_InitLocal()
static void Host_InitLocal (void) static
Definition at line 271 of file host.c.
{
    Cmd_AddCommand(CF_SHARED, "quit", Host_Quit_f, "quit the game");
    Cmd_AddCommand(CF_SHARED, "version", Host_Version_f, "print engine version");
    Cmd_AddCommand(CF_SHARED, "saveconfig", Host_SaveConfig_f, "save settings to config.cfg (or a specified filename) immediately (also automatic when quitting)");
    Cmd_AddCommand(CF_SHARED, "loadconfig", Host_LoadConfig_f, "reset everything and reload configs");
    Cmd_AddCommand(CF_SHARED, "sendcvar", SendCvar_f, "sends the value of a cvar to the server as a sentcvar command, for use by QuakeC");
    Cvar_RegisterVariable (&host_framerate);
    Cvar_RegisterCallback (&host_framerate, Host_Framerate_c);
    Cvar_RegisterVariable (&host_speeds);
    Cvar_RegisterVariable (&host_maxwait);
    Cvar_RegisterVariable (&host_isclient);
    Cvar_RegisterVariable (&developer);
    Cvar_RegisterVariable (&developer_extra);
    Cvar_RegisterVariable (&developer_insane);
    Cvar_RegisterVariable (&developer_loadfile);
    Cvar_RegisterVariable (&developer_loading);
    Cvar_RegisterVariable (&developer_entityparsing);
    Cvar_RegisterVariable (&timestamps);
    Cvar_RegisterVariable (&timeformat);
    Cvar_RegisterVariable (&r_texture_jpeg_fastpicmip);
}
Referenced by Host_Init().
Host_InitSession()
static void Host_InitSession (void) static
Definition at line 302 of file host.c.
{
    int i;
    char *buf;
    Cvar_RegisterVariable(&sessionid);
    Cvar_RegisterVariable(&locksession);
    // load the session ID into the read-only cvar
    if ((i = Sys_CheckParm("-sessionid")) && (i + 1 < sys.argc))
    {
        if(sys.argv[i+1][0] == '.')
            Cvar_SetQuick(&sessionid, sys.argv[i+1]);
        else
        {
            buf = (char *)Z_Malloc(strlen(sys.argv[i+1]) + 2);
            dpsnprintf(buf, sizeof(buf), ".%s", sys.argv[i+1]);
            Cvar_SetQuick(&sessionid, buf);
        }
    }
}
Referenced by Host_Init().
Host_LoadConfig_f()
static void Host_LoadConfig_f (cmd_state_t * cmd) static
Definition at line 250 of file host.c.
{
#ifdef CONFIG_MENU
    // Xonotic QC complains/breaks if its cvars are deleted before its m_shutdown() is called
    if(MR_Shutdown)
        MR_Shutdown();
    // append a menu restart command to execute after the config
    Cbuf_AddText(cmd, "\nmenu_restart\n");
#endif
    // reset all cvars, commands and aliases to init values
    Cmd_RestoreInitState();
    // reset cvars to their defaults, and then exec startup scripts again
    Host_AddConfigText(cmd);
}
Referenced by Host_InitLocal().
Host_LockSession()
void Host_LockSession (void)
Definition at line 323 of file host.c.
{
    if(locksession_run)
        return;
    locksession_run = true;
    if(locksession.integer != 0 && !Sys_CheckParm("-readonly"))
    {
        char vabuf[1024];
        char *p = va(vabuf, sizeof(vabuf), "%slock%s", *fs_userdir ? fs_userdir : fs_basedir, sessionid.string);
        FS_CreatePath(p);
        locksession_fh = FS_SysOpen(p, "wl", false);
        // TODO maybe write the pid into the lockfile, while we are at it? may help server management tools
        if(!locksession_fh)
        {
            if(locksession.integer == 2)
            {
                Con_Printf(CON_WARN "WARNING: session lock %s could not be acquired. Please run with -sessionid and an unique session name. Continuing anyway.\n", p);
            }
            else
            {
                Sys_Error("session lock %s could not be acquired. Please run with -sessionid and an unique session name.\n", p);
            }
        }
    }
}
Referenced by Crypto_LoadKeys(), and PRVM_Prog_Load().
Host_Main()
void Host_Main (void)
Definition at line 676 of file host.c.
{
    double time, oldtime, sleeptime;
    Host_Init(); // Start!
    host.realtime = 0;
    oldtime = Sys_DirtyTime();
    // Main event loop
    while(host.state < host_shutdown) // see Sys_HandleCrash() comments
    {
        // Something bad happened, or the server disconnected
        if (setjmp(host.abortframe))
        {
            host.state = host_active; // In case we were loading
            continue;
        }
        host.dirtytime = Sys_DirtyTime();
        host.realtime += time = Host_UpdateTime(host.dirtytime, oldtime);
        oldtime = host.dirtytime;
        sleeptime = Host_Frame(time);
        ++host.framecount;
        sleeptime -= Sys_DirtyTime() - host.dirtytime; // execution time
        host.sleeptime = Sys_Sleep(sleeptime);
    }
    Host_Shutdown();
}
Referenced by main().
Host_Quit_f()
static void Host_Quit_f (cmd_state_t * cmd) static
Definition at line 149 of file host.c.
{
    if(host.state == host_shutdown)
        Con_Printf("shutting down already!\n");
    else
        host.state = host_shutdown;
}
Referenced by Host_InitLocal().
Host_SaveConfig()
void Host_SaveConfig (const char * file)
Definition at line 190 of file host.c.
{
    qfile_t *f;
// dedicated servers initialize the host but don't parse and set the
// config.cfg cvars
    // LadyHavoc: don't save a config if it crashed in startup
    if (host.framecount >= 3 && cls.state != ca_dedicated && !Sys_CheckParm("-benchmark") && !Sys_CheckParm("-capturedemo"))
    {
        f = FS_OpenRealFile(file, "wb", false);
        if (!f)
        {
            Con_Printf(CON_ERROR "Couldn't write %s\n", file);
            return;
        }
        else
            Con_Printf("Saving config to %s ...\n", file);
        Key_WriteBindings (f);
        Cvar_WriteVariables (&cvars_all, f);
        FS_Close (f);
    }
}
Referenced by FS_ChangeGameDirs(), Host_SaveConfig_f(), and Host_Shutdown().
Host_SaveConfig_f()
static void Host_SaveConfig_f (cmd_state_t * cmd) static
Definition at line 215 of file host.c.
{
    const char *file = CONFIGFILENAME;
    if(Cmd_Argc(cmd) >= 2)
        file = Cmd_Argv(cmd, 1);
    Host_SaveConfig(file);
}
Referenced by Host_InitLocal().
Host_Shutdown()
static void Host_Shutdown (void) static
Definition at line 569 of file host.c.
{
    if (Sys_CheckParm("-profilegameonly"))
        Sys_AllowProfiling(false);
    if(cls.state != ca_dedicated)
        CL_Shutdown();
    // end the server thread
    if (svs.threaded)
        SV_StopThread();
    // shut down local server if active
    if(host.hook.SV_Shutdown)
        host.hook.SV_Shutdown();
    // AK shutdown PRVM
    // AK hmm, no PRVM_Shutdown(); yet
    Host_SaveConfig(CONFIGFILENAME);
    Curl_Shutdown ();
    NetConn_Shutdown ();
    SV_StopThread();
    TaskQueue_Shutdown();
    Thread_Shutdown();
    Cmd_Shutdown();
    Sys_SDL_Shutdown();
    Log_Close();
    Crypto_Shutdown();
    Host_UnlockSession();
    Con_Shutdown();
    Memory_Shutdown();
}
Referenced by Host_Main().
Host_UnlockSession()
void Host_UnlockSession (void)
Definition at line 349 of file host.c.
{
    if(!locksession_run)
        return;
    locksession_run = false;
    if(locksession_fh)
    {
        FS_Close(locksession_fh);
        // NOTE: we can NOT unlink the lock here, as doing so would
        // create a race condition if another process created it
        // between our close and our unlink
        locksession_fh = NULL;
    }
}
Referenced by Host_Shutdown().
Host_UpdateTime()
static double Host_UpdateTime (double newtime, double oldtime) inline static
Definition at line 656 of file host.c.
{
    double time = newtime - oldtime;
    if (time < 0)
    {
        // warn if it's significant
        if (time < -0.01)
            Con_Printf(CON_WARN "Host_UpdateTime: time stepped backwards (went from %f to %f, difference %f)\n", oldtime, newtime, time);
        time = 0;
    }
    else if (time >= 1800)
    {
        Con_Printf(CON_WARN "Host_UpdateTime: time stepped forward (went from %f to %f, difference %f)\n", oldtime, newtime, time);
        time = 0;
    }
    return time;
}
Referenced by Host_Main().
Host_Version_f()
static void Host_Version_f (cmd_state_t * cmd) static
Definition at line 157 of file host.c.
{
    Con_Printf("Version: %s\n", engineversion);
}
Referenced by Host_InitLocal().
SendCvar_f()
static void SendCvar_f (cmd_state_t * cmd) static
Definition at line 169 of file host.c.
{
    if(cmd->source == src_local && host.hook.SV_SendCvar)
    {
        host.hook.SV_SendCvar(cmd);
        return;
    }
    if(cmd->source == src_client && host.hook.CL_SendCvar)
    {
        host.hook.CL_SendCvar(cmd);
        return;
    }
}
Referenced by Host_InitLocal().
Variable Documentation
developer
cvar_t developer = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "developer","0", "shows debugging messages and information (recommended for all developers and level designers); the value -1 also suppresses buffering and logging these messages"}
Definition at line 49 of file host.c.
{CF_CLIENT | CF_SERVER | CF_ARCHIVE, "developer","0", "shows debugging messages and information (recommended for all developers and level designers); the value -1 also suppresses buffering and logging these messages"};
Referenced by Con_DPrint(), Con_DPrintf(), Con_DrawConsole(), Con_MaskPrint(), Curl_GetDownloadInfo(), GL_Backend_CompileShader(), Host_Init(), Host_InitLocal(), IN_Move_TouchScreen_SteelStorm(), PRVM_ED_CallSpawnFunction(), SV_ReadClientMessage(), SV_SpawnServer(), Sys_Print(), VM_physics_addforce(), VM_physics_addtorque(), VM_physics_enable(), and VM_remove().
developer_entityparsing
cvar_t developer_entityparsing = {CF_CLIENT, "developer_entityparsing", "0", "prints detailed network entities information each time a packet is received"}
Definition at line 54 of file host.c.
{CF_CLIENT, "developer_entityparsing", "0", "prints detailed network entities information each time a packet is received"};
Referenced by Host_InitLocal(), PRVM_ED_ParseEdict(), PRVM_ED_ParseGlobals(), PRVM_ED_Write(), PRVM_ED_WriteGlobals(), and SV_Loadgame_f().
developer_extra
cvar_t developer_extra = {CF_CLIENT | CF_SERVER, "developer_extra", "0", "prints additional debugging messages, often very verbose!"}
Definition at line 50 of file host.c.
{CF_CLIENT | CF_SERVER, "developer_extra", "0", "prints additional debugging messages, often very verbose!"};
Referenced by CL_IPLog_Add(), CL_NetworkTimeReceived(), CL_ValidateState(), Collision_CalcPlanesForTriangleBrushFloat(), Cvar_Command(), Cvar_Get(), Cvar_RegisterCallback(), Cvar_RegisterVariable(), Cvar_RegisterVirtual(), Cvar_Set_f(), Cvar_SetA_f(), Cvar_SetQuick(), FS_FindFile(), GetMapList(), GL_Backend_CompileProgram(), GL_Backend_CompileShader(), Host_Init(), Host_InitLocal(), Mod_BuildAliasSkinsFromSkinFiles(), Mod_LoadCustomMaterial(), Mod_LoadTextureFromQ3Shader(), Mod_PSKMODEL_Load(), Mod_Q3BSP_LoadFaces(), NetConn_ClientParsePacket(), NetConn_ServerParsePacket(), R_BuildFogTexture(), R_Mesh_Draw(), R_Q1BSP_CallRecursiveGetLightInfo(), R_RTLight_Compile(), SV_Download_f(), SV_ThreadFunc(), SV_UnstickEntity(), VM_buf_loadfile(), VM_CL_gettagindex(), VM_fclose(), VM_fgets(), VM_fopen(), VM_fputs(), VM_FrameBlendFromFrameGroupBlend(), VM_SV_gettagindex(), and World_SetSize().
developer_insane
cvar_t developer_insane = {CF_CLIENT | CF_SERVER, "developer_insane", "0", "prints huge streams of information about internal workings, entire contents of files being read/written, etc. Not recommended!"}
Definition at line 51 of file host.c.
{CF_CLIENT | CF_SERVER, "developer_insane", "0", "prints huge streams of information about internal workings, entire contents of files being read/written, etc.  Not recommended!"};
Referenced by Buffer_Callback(), CLVM_ExecuteProgram(), Host_Init(), Host_InitLocal(), Key_Event(), Mod_LoadQ3Shaders(), PRVM_SetEngineString(), PRVM_SetTempString(), and SVVM_ExecuteProgram().
developer_loadfile
cvar_t developer_loadfile = {CF_CLIENT | CF_SERVER, "developer_loadfile","0", "prints name and size of every file loaded via the FS_LoadFile function (which is almost everything)"}
Definition at line 52 of file host.c.
{CF_CLIENT | CF_SERVER, "developer_loadfile","0", "prints name and size of every file loaded via the FS_LoadFile function (which is almost everything)"};
Referenced by FS_LoadAndCloseQFile(), and Host_InitLocal().
developer_loading
cvar_t developer_loading = {CF_CLIENT | CF_SERVER, "developer_loading","0", "prints information about files as they are loaded or unloaded successfully"}
Definition at line 53 of file host.c.
{CF_CLIENT | CF_SERVER, "developer_loading","0", "prints information about files as they are loaded or unloaded successfully"};
Referenced by FS_OpenReadFile(), FS_Search(), Host_InitLocal(), loadimagepixelsbgra(), Mod_LoadModel(), Mod_LoadSkinFiles(), Mod_LoadTextureFromQ3Shader(), Mod_Q1BSP_LoadLighting(), Mod_Q3BSP_LoadLightmaps(), Mod_UnloadModel(), OGG_LoadVorbisFile(), R_LoadCubemap(), R_LoadQWSkin(), R_LoadSkyBox(), R_SkinFrame_LoadExternal_SkinFrame(), R_SkinFrame_LoadInternal8bit(), R_SkinFrame_LoadInternalBGRA(), R_SkinFrame_LoadInternalQuake(), R_SkinFrame_LoadInternalUsingTexture(), R_UnloadSkyBox(), S_FreeSfx(), S_LoadSound(), S_LoadWavFile(), XMP_LoadModFile(), and XMP_OpenLibrary().
engineversion
char engineversion[128]
Definition at line 297 of file host.c.
Referenced by CheckPendingDownloads(), CL_FinishTimeDemo(), CL_Locs_Save_f(), Con_DrawConsole(), Host_Init(), Host_Version_f(), SCR_CaptureVideo_Avi_BeginVideo(), SV_SendServerinfo(), SV_Status_f(), Sys_Error(), and Sys_HandleCrash().
host
host_static_t host
Definition at line 41 of file host.c.
Referenced by Cbuf_Execute_Deferred(), CL_DisconnectEx(), CL_DrawVideo(), CL_FinishTimeDemo(), CL_Frame(), CL_GetVideoBySlot(), CL_Init(), CL_InitCommands(), CL_ParseServerMessage(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_RestartVideo(), CL_SendMove(), CL_SetVideoState(), CL_StopPlayback(), CL_TimeDemo_f(), CL_Video_Frame(), CL_VM_Init(), Cmd_ExecuteString(), Cmd_Init(), Con_DrawConsole(), Con_DrawInput(), Crypto_ClientParsePacket(), Crypto_ServerFindInstance(), Crypto_ServerParsePacket(), CSQC_SetGlobals(), Curl_Frame(), Draw_Frame(), Host_AbortCurrentFrame(), Host_Error(), Host_Frame(), Host_Init(), Host_Main(), Host_Quit_f(), Host_SaveConfig(), Host_Shutdown(), LHNET_Read(), LHNET_Write(), LHNETADDRESS_FromString(), M_Demo_Draw(), M_Draw(), M_GameOptions_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_MultiPlayer_Draw(), M_NetStart_Change(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), M_Options_PrintSlider(), M_Quit_Key(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), M_Video_Draw(), MP_Draw(), MP_Init(), MVM_error_cmd(), NetConn_CanSend(), NetConn_ClientFrame(), NetConn_ClientParsePacket(), NetConn_Heartbeat(), NetConn_Open(), NetConn_PreventFlood(), NetConn_ReceivedMessage(), NetConn_SendUnreliableMessage(), NetConn_ServerParsePacket(), NetConn_UpdateCleartime(), NetConn_UpdateSockets(), OpenVideo(), PRVM_ED_CanAlloc(), PRVM_ED_ClearEdict(), PRVM_ED_Free(), PRVM_ED_LoadFromFile(), PRVM_ED_ParseEdict(), PRVM_Prog_Load(), R_RenderTarget_FreeUnused(), R_RenderTarget_Get(), R_Shadow_BounceGrid_AssignPhotons_Task(), R_Shadow_BounceGrid_ConvertPixelsAndUpload(), R_Shadow_PrepareLight(), R_Shadow_UpdateBounceGridTexture(), R_TimeReport_EndFrame(), R_View_UpdateEntityVisible(), R_View_WorldVisibility(), S_PaintAndSubmit(), S_Startup(), Sbar_DeathmatchOverlay(), Sbar_ShowFPS(), Sbar_ShowFPS_Update(), SCR_DrawNet(), SCR_DrawNetGraph_DrawGraph(), SCR_DrawQWDownload(), SCR_DrawScreen(), SendCvar_f(), SV_CanSave(), SV_Changelevel_f(), SV_CheckTimeouts(), SV_ConnectClient(), SV_ExecuteClientMoves(), SV_Frame(), SV_Init(), SV_InitOperatorCommands(), SV_Loadgame_f(), SV_Map_f(), SV_MarkWriteEntityStateToClient(), SV_Name_f(), SV_Restart_f(), SV_Savegame_to(), SV_SendClientDatagram(), SV_SendServerinfo(), SV_SpawnServer(), SV_Status_f(), SV_ThreadFunc(), Sys_Error(), Sys_HandleCrash(), Sys_HandleSignal(), Sys_SDL_HandleEvents(), Sys_Sleep(), VID_KeyEventForButton(), VID_TouchscreenCursor(), VM_CL_setpause(), VM_gettime(), VM_SV_setpause(), VM_Warning(), and WakeVideo().
host_framerate
cvar_t host_framerate = {CF_CLIENT | CF_SERVER, "host_framerate","0", "locks frame timing to this value in seconds, 0.05 is 20fps for example, note that this can easily run too fast, use cl_maxfps if you want to limit your framerate instead, or sys_ticrate to limit server speed"}
Definition at line 44 of file host.c.
{CF_CLIENT | CF_SERVER, "host_framerate","0", "locks frame timing to this value in seconds, 0.05 is 20fps for example, note that this can easily run too fast, use cl_maxfps if you want to limit your framerate instead, or sys_ticrate to limit server speed"};
Referenced by CL_Frame(), Host_InitLocal(), SV_Frame(), and SV_ThreadFunc().
host_isclient
cvar_t host_isclient = {CF_SHARED | CF_READONLY, "_host_isclient", "0", "If 1, clientside is active."}
Definition at line 62 of file host.c.
{CF_SHARED | CF_READONLY, "_host_isclient", "0", "If 1, clientside is active."};
Referenced by CL_Init(), Cmd_CL_Callback(), Host_InitLocal(), SV_BroadcastPrint(), SV_CheckTimeouts(), SV_IsLocalServer(), SV_Kick_f(), SV_Say(), SV_SendCvar_f(), and SV_SpawnServer().
host_maxwait
cvar_t host_maxwait = {CF_CLIENT | CF_SERVER, "host_maxwait","1000", "maximum sleep time requested from the operating system in millisecond. Larger sleeps will be done using multiple host_maxwait length sleeps. Lowering this value will increase CPU load, but may help working around problems with accuracy of sleep times."}
Definition at line 47 of file host.c.
{CF_CLIENT | CF_SERVER, "host_maxwait","1000", "maximum sleep time requested from the operating system in millisecond. Larger sleeps will be done using multiple host_maxwait length sleeps. Lowering this value will increase CPU load, but may help working around problems with accuracy of sleep times."};
Referenced by Host_InitLocal(), and Sys_Sleep().
host_speeds
cvar_t host_speeds = {CF_CLIENT | CF_SERVER, "host_speeds","0", "reports how much time is used in server/graphics/sound"}
Definition at line 46 of file host.c.
{CF_CLIENT | CF_SERVER, "host_speeds","0", "reports how much time is used in server/graphics/sound"};
Referenced by CL_Frame(), and Host_InitLocal().
locksession
cvar_t locksession = {CF_CLIENT | CF_SERVER, "locksession", "0", "Lock the session? 0 = no, 1 = yes and abort on failure, 2 = yes and continue on failure"}
Definition at line 60 of file host.c.
{CF_CLIENT | CF_SERVER, "locksession", "0", "Lock the session? 0 = no, 1 = yes and abort on failure, 2 = yes and continue on failure"};
Referenced by Host_InitSession(), and Host_LockSession().
locksession_fh
qfile_t* locksession_fh = NULL static
Definition at line 300 of file host.c.
Referenced by Host_LockSession(), and Host_UnlockSession().
locksession_run
qbool locksession_run = false static
Definition at line 301 of file host.c.
Referenced by Host_LockSession(), and Host_UnlockSession().
r_texture_jpeg_fastpicmip
cvar_t r_texture_jpeg_fastpicmip extern
Definition at line 32 of file jpeg.c.
{CF_CLIENT | CF_ARCHIVE, "r_texture_jpeg_fastpicmip", "1", "perform gl_picmip during decompression for JPEG files (faster)"};
Referenced by Host_InitLocal(), and JPEG_LoadImage_BGRA().
sessionid
cvar_t sessionid = {CF_CLIENT | CF_SERVER | CF_READONLY, "sessionid", "", "ID of the current session (use the -sessionid parameter to set it); this is always either empty or begins with a dot (.)"}
Definition at line 59 of file host.c.
{CF_CLIENT | CF_SERVER | CF_READONLY, "sessionid", "", "ID of the current session (use the -sessionid parameter to set it); this is always either empty or begins with a dot (.)"};
Referenced by Crypto_KeyGen_f(), Crypto_KeyGen_Finished(), Crypto_Keys_f(), Crypto_LoadKeys(), Crypto_SavePubKeyTextFile(), Host_InitSession(), and Host_LockSession().
timeformat
cvar_t timeformat = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timeformat", "[%Y-%m-%d %H:%M:%S] ", "time format to use on timestamped console messages"}
Definition at line 57 of file host.c.
{CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timeformat", "[%Y-%m-%d %H:%M:%S] ", "time format to use on timestamped console messages"};
Referenced by Con_MaskPrint(), Host_InitLocal(), and Sys_TimeString().
timestamps
cvar_t timestamps = {CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timestamps", "0", "prints timestamps on console messages"}
Definition at line 56 of file host.c.
{CF_CLIENT | CF_SERVER | CF_ARCHIVE, "timestamps", "0", "prints timestamps on console messages"};
Referenced by Con_MaskPrint(), and Host_InitLocal().