DarkPlaces: image_png.h File Reference
image_png.h File Reference
#include "qtypes.h"
Functions
qbool PNG_OpenLibrary (void)
void PNG_CloseLibrary (void)
unsigned char * PNG_LoadImage_BGRA (const unsigned char *f, int filesize, int *miplevel)
qbool PNG_SaveImage_preflipped (const char *filename, int width, int height, qbool has_alpha, unsigned char *data)
Function Documentation
PNG_CloseLibrary()
void PNG_CloseLibrary (void)
Definition at line 194 of file image_png.c.
{
    Sys_FreeLibrary (&png14_dll);
    Sys_FreeLibrary (&png_dll);
}
PNG_LoadImage_BGRA()
unsigned char * PNG_LoadImage_BGRA (const unsigned char * f, int filesize, int * miplevel)
Definition at line 294 of file image_png.c.
{
    unsigned int c;
    unsigned int    y;
    void *png, *pnginfo;
    unsigned char *imagedata = NULL;
    unsigned char ioBuffer[8192];
    // FIXME: register an error handler so that abort() won't be called on error
    // No DLL = no PNGs
    if (!png_dll)
        return NULL;
    if(qpng_sig_cmp(raw, 0, filesize))
        return NULL;
    png = (void *)qpng_create_read_struct(
        (qpng_access_version_number() / 100 == 102) ? PNG_LIBPNG_VER_STRING_12 :
        (qpng_access_version_number() / 100 == 104) ? PNG_LIBPNG_VER_STRING_14 :
        (qpng_access_version_number() / 100 == 105) ? PNG_LIBPNG_VER_STRING_15 :
        PNG_LIBPNG_VER_STRING_16, // nasty hack... whatever
        0, PNG_error_fn, PNG_warning_fn
    );
    if(!png)
        return NULL;
    // this must be memset before the setjmp error handler, because it relies
    // on the fields in this struct for cleanup
    memset(&my_png, 0, sizeof(my_png));
    // NOTE: this relies on jmp_buf being the first thing in the png structure
    // created by libpng! (this is correct for libpng 1.2.x)
    if (setjmp(qpng_jmpbuf(png)))
    {
        if (my_png.Data)
            Mem_Free(my_png.Data);
        my_png.Data = NULL;
        if (my_png.FRowPtrs)
            Mem_Free(my_png.FRowPtrs);
        my_png.FRowPtrs = NULL;
        qpng_destroy_read_struct(&png, &pnginfo, 0);
        return NULL;
    }
    //
    pnginfo = qpng_create_info_struct(png);
    if(!pnginfo)
    {
        qpng_destroy_read_struct(&png, &pnginfo, 0);
        return NULL;
    }
    qpng_set_sig_bytes(png, 0);
    my_png.tmpBuf = raw;
    my_png.tmpBuflength = filesize;
    my_png.tmpi = 0;
    //my_png.Data       = NULL;
    //my_png.FRowPtrs   = NULL;
    //my_png.Height     = 0;
    //my_png.Width      = 0;
    my_png.ColorType    = PNG_COLOR_TYPE_RGB;
    //my_png.Interlace  = 0;
    //my_png.Compression    = 0;
    //my_png.Filter     = 0;
    qpng_set_read_fn(png, ioBuffer, PNG_fReadData);
    qpng_read_info(png, pnginfo);
    qpng_get_IHDR(png, pnginfo, &my_png.Width, &my_png.Height,&my_png.BitDepth, &my_png.ColorType, &my_png.Interlace, &my_png.Compression, &my_png.Filter);
    // this check guards against pngconf.h with unsigned int *width/height parameters on big endian systems by detecting the strange values and shifting them down 32bits
    // (if it's little endian the unwritten bytes are the most significant
    //  ones and we don't worry about that)
    //
    // this is only necessary because of retarded 64bit png_uint_32 types in libpng 1.2, which can (conceivably) vary by platform
#if LONG_MAX > 4000000000
    if (my_png.Width > LONG_MAX || my_png.Height > LONG_MAX)
    {
        my_png.Width >>= 32;
        my_png.Height >>= 32;
    }
#endif
    if (my_png.ColorType == PNG_COLOR_TYPE_PALETTE)
        qpng_set_palette_to_rgb(png);
    if (my_png.ColorType == PNG_COLOR_TYPE_GRAY || my_png.ColorType == PNG_COLOR_TYPE_GRAY_ALPHA)
        qpng_set_gray_to_rgb(png);
    if (qpng_get_valid(png, pnginfo, PNG_INFO_tRNS))
        qpng_set_tRNS_to_alpha(png);
    if (my_png.BitDepth == 8 && !(my_png.ColorType  & PNG_COLOR_MASK_ALPHA))
        qpng_set_filler(png, 255, 1);
    if (( my_png.ColorType == PNG_COLOR_TYPE_GRAY) || (my_png.ColorType == PNG_COLOR_TYPE_GRAY_ALPHA ))
        qpng_set_gray_to_rgb(png);
    if (my_png.BitDepth < 8)
        qpng_set_expand(png);
    qpng_read_update_info(png, pnginfo);
    my_png.FRowBytes = qpng_get_rowbytes(png, pnginfo);
    my_png.BytesPerPixel = qpng_get_channels(png, pnginfo);
    my_png.FRowPtrs = (unsigned char **)Mem_Alloc(tempmempool, my_png.Height * sizeof(*my_png.FRowPtrs));
    if (my_png.FRowPtrs)
    {
        imagedata = (unsigned char *)Mem_Alloc(tempmempool, my_png.Height * my_png.FRowBytes);
        if(imagedata)
        {
            my_png.Data = imagedata;
            for(y = 0;y < my_png.Height;y++)
                my_png.FRowPtrs[y] = my_png.Data + y * my_png.FRowBytes;
            qpng_read_image(png, my_png.FRowPtrs);
        }
        else
        {
            Con_Printf("PNG_LoadImage : not enough memory\n");
            qpng_destroy_read_struct(&png, &pnginfo, 0);
            Mem_Free(my_png.FRowPtrs);
            return NULL;
        }
        Mem_Free(my_png.FRowPtrs);
        my_png.FRowPtrs = NULL;
    }
    else
    {
        Con_Printf("PNG_LoadImage : not enough memory\n");
        qpng_destroy_read_struct(&png, &pnginfo, 0);
        return NULL;
    }
    qpng_read_end(png, pnginfo);
    qpng_destroy_read_struct(&png, &pnginfo, 0);
    image_width = (int)my_png.Width;
    image_height = (int)my_png.Height;
    if (my_png.BitDepth != 8)
    {
        Con_Printf ("PNG_LoadImage : bad color depth\n");
        Mem_Free(imagedata);
        return NULL;
    }
    // swizzle RGBA to BGRA
    for (y = 0;y < (unsigned int)(image_width*image_height*4);y += 4)
    {
        c = imagedata[y+0];
        imagedata[y+0] = imagedata[y+2];
        imagedata[y+2] = c;
    }
    return imagedata;
}
Referenced by decode_image().
PNG_OpenLibrary()
qbool PNG_OpenLibrary (void)
Definition at line 143 of file image_png.c.
{
    const char* dllnames [] =
    {
#if WIN32
        "libpng16.dll",
        "libpng16-16.dll",
        "libpng15-15.dll",
        "libpng15.dll",
        "libpng14-14.dll",
        "libpng14.dll",
        "libpng12.dll",
#elif defined(MACOSX)
        "libpng16.16.dylib",
        "libpng15.15.dylib",
        "libpng14.14.dylib",
        "libpng12.0.dylib",
#else
        "libpng16.so.16",
        "libpng15.so.15", // WTF libtool guidelines anyone?
        "libpng14.so.14", // WTF libtool guidelines anyone?
        "libpng12.so.0",
        "libpng.so", // FreeBSD
#endif
        NULL
    };
    // Already loaded?
    if (png_dll)
        return true;
    // Load the DLL
    if(!Sys_LoadDependency (dllnames, &png_dll, pngfuncs))
        return false;
    if(qpng_access_version_number() / 100 >= 104)
        if(!Sys_LoadDependency (dllnames, &png14_dll, png14funcs))
        {
            Sys_FreeLibrary (&png_dll);
            return false;
        }
    return true;
}
Referenced by Image_Compress(), and r_textures_start().
PNG_SaveImage_preflipped()
qbool PNG_SaveImage_preflipped (const char * filename, int width, int height, qbool has_alpha, unsigned char * data)
Definition at line 477 of file image_png.c.
{
    unsigned int offset, linesize;
    qfile_t* file = NULL;
    void *png, *pnginfo;
    unsigned char ioBuffer[8192];
    int passes, i, j;
    // No DLL = no JPEGs
    if (!png_dll)
    {
        Con_Print("You need the libpng library to save PNG images\n");
        return false;
    }
    png = (void *)qpng_create_write_struct(
        (qpng_access_version_number() / 100 == 102) ? PNG_LIBPNG_VER_STRING_12 :
        (qpng_access_version_number() / 100 == 104) ? PNG_LIBPNG_VER_STRING_14 :
        (qpng_access_version_number() / 100 == 105) ? PNG_LIBPNG_VER_STRING_15 :
        PNG_LIBPNG_VER_STRING_16, // nasty hack... whatever
        0, PNG_error_fn, PNG_warning_fn
    );
    if(!png)
        return false;
    pnginfo = (void *)qpng_create_info_struct(png);
    if(!pnginfo)
    {
         qpng_destroy_write_struct(&png, NULL);
         return false;
    }
    // this must be memset before the setjmp error handler, because it relies
    // on the fields in this struct for cleanup
    memset(&my_png, 0, sizeof(my_png));
    // NOTE: this relies on jmp_buf being the first thing in the png structure
    // created by libpng! (this is correct for libpng 1.2.x)
#ifdef WIN64
    if (setjmp((_JBTYPE *)png))
#elif defined(MACOSX) || defined(WIN32)
    if (setjmp((int *)png))
#elif defined(__ANDROID__)
    if (setjmp((long *)png))
#else
    if (setjmp((struct __jmp_buf_tag *)png))
#endif
    {
        qpng_destroy_write_struct(&png, &pnginfo);
        return false;
    }
    // Open the file
    file = FS_OpenRealFile(filename, "wb", true);
    if (!file)
        return false;
    my_png.outfile = file;
    qpng_set_write_fn(png, ioBuffer, PNG_fWriteData, PNG_fFlushData);
    //qpng_set_compression_level(png, Z_BEST_COMPRESSION);
    qpng_set_compression_level(png, Z_BEST_SPEED);
    qpng_set_IHDR(png, pnginfo, width, height, 8, has_alpha ? PNG_COLOR_TYPE_RGB_ALPHA : PNG_COLOR_TYPE_RGB, PNG_INTERLACE_ADAM7, PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);
    qpng_set_filter(png, 0, PNG_NO_FILTERS);
    qpng_write_info(png, pnginfo);
    qpng_set_packing(png);
    qpng_set_bgr(png);
    passes = qpng_set_interlace_handling(png);
    linesize = width * (has_alpha ? 4 : 3);
    offset = linesize * (height - 1);
    for(i = 0; i < passes; ++i)
        for(j = 0; j < height; ++j)
            qpng_write_row(png, &data[offset - j * linesize]);
    qpng_write_end(png, NULL);
    qpng_destroy_write_struct(&png, &pnginfo);
    FS_Close (file);
    return true;
}
Referenced by SCR_ScreenShot().