DarkPlaces: libcurl.h File Reference
libcurl.h File Reference
#include <stddef.h>
#include "qtypes.h"
#include "qdefs.h"
Data Structures
struct Curl_downloadinfo_t
Typedefs
typedef void(* curl_callback_t) (int status, size_t length_received, unsigned char *buffer, void *cbdata)
Enumerations
enum {
CURLCBSTATUS_OK = 0 , CURLCBSTATUS_FAILED = -1 , CURLCBSTATUS_ABORTED = -2 , CURLCBSTATUS_SERVERERROR = -3 ,
CURLCBSTATUS_UNKNOWN = -4
}
Functions
void Curl_Frame (void)
int Curl_Select (int timeout_ms)
qbool Curl_Running (void)
qbool Curl_Begin_ToFile (const char *URL, double maxspeed, const char *name, int loadtype, qbool forthismap)
qbool Curl_Begin_ToMemory (const char *URL, double maxspeed, unsigned char *buf, size_t bufsize, curl_callback_t callback, void *cbdata)
qbool Curl_Begin_ToMemory_POST (const char *URL, const char *extraheaders, double maxspeed, const char *post_content_type, const unsigned char *postbuf, size_t postbufsize, unsigned char *buf, size_t bufsize, curl_callback_t callback, void *cbdata)
void Curl_Cancel_ToMemory (curl_callback_t callback, void *cbdata)
void Curl_Init (void)
void Curl_Init_Commands (void)
void Curl_Shutdown (void)
qbool Curl_Available (void)
void Curl_CancelAll (void)
void Curl_Clear_forthismap (void)
qbool Curl_Have_forthismap (void)
void Curl_Register_predownload (void)
void Curl_ClearRequirements (void)
void Curl_RequireFile (const char *filename)
void Curl_SendRequirements (void)
Curl_downloadinfo_t * Curl_GetDownloadInfo (int *nDownloads, const char **additional_info, char *addinfo, size_t addinfolength)
Typedef Documentation
curl_callback_t
typedef void(* curl_callback_t) (int status, size_t length_received, unsigned char *buffer, void *cbdata)
Definition at line 13 of file libcurl.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CURLCBSTATUS_OK
CURLCBSTATUS_FAILED
CURLCBSTATUS_ABORTED
CURLCBSTATUS_SERVERERROR
CURLCBSTATUS_UNKNOWN
Definition at line 5 of file libcurl.h.
{
    CURLCBSTATUS_OK = 0,
    CURLCBSTATUS_FAILED = -1, // failed for generic reason (e.g. buffer too small)
    CURLCBSTATUS_ABORTED = -2, // aborted by curl --cancel
    CURLCBSTATUS_SERVERERROR = -3, // only used if no HTTP status code is available
    CURLCBSTATUS_UNKNOWN = -4 // should never happen
};
Function Documentation
Curl_Available()
qbool Curl_Available (void)
Definition at line 840 of file libcurl.c.
{
    return curl_dll ? true : false;
}
Referenced by checkextension().
Curl_Begin_ToFile()
qbool Curl_Begin_ToFile (const char * URL, double maxspeed, const char * name, int loadtype, qbool forthismap)
Definition at line 1113 of file libcurl.c.
{
    return Curl_Begin(URL, NULL, maxspeed, name, loadtype, forthismap, NULL, NULL, 0, NULL, 0, NULL, NULL);
}
Referenced by Curl_Curl_f().
Curl_Begin_ToMemory()
qbool Curl_Begin_ToMemory (const char * URL, double maxspeed, unsigned char * buf, size_t bufsize, curl_callback_t callback, void * cbdata)
Definition at line 1117 of file libcurl.c.
{
    return Curl_Begin(URL, NULL, maxspeed, NULL, false, false, NULL, NULL, 0, buf, bufsize, callback, cbdata);
}
Referenced by Crypto_KeyGen_f().
Curl_Begin_ToMemory_POST()
qbool Curl_Begin_ToMemory_POST (const char * URL, const char * extraheaders, double maxspeed, const char * post_content_type, const unsigned char * postbuf, size_t postbufsize, unsigned char * buf, size_t bufsize, curl_callback_t callback, void * cbdata)
Definition at line 1121 of file libcurl.c.
{
    return Curl_Begin(URL, extraheaders, maxspeed, NULL, false, false, post_content_type, postbuf, postbufsize, buf, bufsize, callback, cbdata);
}
Referenced by VM_uri_get().
Curl_Cancel_ToMemory()
void Curl_Cancel_ToMemory (curl_callback_t callback, void * cbdata)
Definition at line 863 of file libcurl.c.
{
    downloadinfo *di, *ndi;
    if(!curl_dll)
        return;
    List_For_Each_Entry_Safe(di, ndi, &downloads, downloadinfo, list)
    {
        if(di->callback == callback && di->callback_data == cbdata)
        {
            di->callback = curl_quiet_callback; // do NOT call the callback
            Curl_EndDownload(di, CURL_DOWNLOAD_ABORTED, CURLE_OK, NULL);
        }
    }
}
Curl_CancelAll()
void Curl_CancelAll (void)
Definition at line 1285 of file libcurl.c.
{
    if(!curl_dll)
        return;
    if (curl_mutex) Thread_LockMutex(curl_mutex);
    while(!List_Is_Empty(&downloads))
    {
        Curl_EndDownload(List_First_Entry(&downloads, downloadinfo, list), CURL_DOWNLOAD_ABORTED, CURLE_OK, NULL);
        // INVARIANT: downloads will point to the next download after that!
    }
    if (curl_mutex) Thread_UnlockMutex(curl_mutex);
}
Referenced by CL_StopDownload_f(), Curl_Curl_f(), and Curl_Shutdown().
Curl_Clear_forthismap()
void Curl_Clear_forthismap (void)
Definition at line 287 of file libcurl.c.
{
    downloadinfo *di;
    if(noclear)
        return;
    if (curl_mutex) Thread_LockMutex(curl_mutex);
    List_For_Each_Entry(di, &downloads, downloadinfo, list)
        di->forthismap = false;
    Curl_CommandWhenError(NULL);
    Curl_CommandWhenDone(NULL);
    numdownloads_fail = 0;
    numdownloads_success = 0;
    numdownloads_added = 0;
    if (curl_mutex) Thread_UnlockMutex(curl_mutex);
}
Referenced by CL_DisconnectEx(), Curl_CheckCommandWhenDone(), and Curl_Curl_f().
Curl_ClearRequirements()
void Curl_ClearRequirements (void)
Definition at line 1796 of file libcurl.c.
{
    while(requirements)
    {
        requirement *req = requirements;
        requirements = requirements->next;
        Z_Free(req);
    }
}
Referenced by Curl_Shutdown(), and SV_SpawnServer().
Curl_Frame()
void Curl_Frame (void)
Definition at line 1134 of file libcurl.c.
{
    double maxspeed;
    downloadinfo *di;
    noclear = false;
    if(!curl_enabled.integer && cls.state != ca_dedicated)
        return;
    if(!curl_dll)
        return;
    if (curl_mutex) Thread_LockMutex(curl_mutex);
    Curl_CheckCommandWhenDone();
    if(List_Is_Empty(&downloads))
    {
        if (curl_mutex) Thread_UnlockMutex(curl_mutex);
        return;
    }
    if(host.realtime < curltime) // throttle
    {
        if (curl_mutex) Thread_UnlockMutex(curl_mutex);
        return;
    }
    {
        int remaining;
        CURLMcode mc;
        do
        {
            mc = qcurl_multi_perform(curlm, &remaining);
        }
        while(mc == CURLM_CALL_MULTI_PERFORM);
        List_For_Each_Entry(di, &downloads, downloadinfo, list)
        {
            double b = 0;
            if(di->curle)
            {
                qcurl_easy_getinfo(di->curle, CURLINFO_SIZE_UPLOAD, &b);
                bytes_sent += (b - di->bytes_sent_curl);
                di->bytes_sent_curl = b;
                qcurl_easy_getinfo(di->curle, CURLINFO_SIZE_DOWNLOAD, &b);
                bytes_sent += (b - di->bytes_received_curl);
                di->bytes_received_curl = b;
            }
        }
        for(;;)
        {
            CURLMsg *msg = qcurl_multi_info_read(curlm, &remaining);
            if(!msg)
                break;
            if(msg->msg == CURLMSG_DONE)
            {
                const char *ct = NULL;
                CurlStatus failed = CURL_DOWNLOAD_SUCCESS;
                CURLcode result;
                qcurl_easy_getinfo(msg->easy_handle, CURLINFO_PRIVATE, &di);
                result = msg->data.result;
                if(result)
                {
                    failed = CURL_DOWNLOAD_FAILED;
                }
                else
                {
                    long code;
                    qcurl_easy_getinfo(msg->easy_handle, CURLINFO_RESPONSE_CODE, &code);
                    switch(code / 100)
                    {
                        case 4: // e.g. 404?
                        case 5: // e.g. 500?
                            failed = CURL_DOWNLOAD_SERVERERROR;
                            result = (CURLcode) code;
                            break;
                    }
                    qcurl_easy_getinfo(msg->easy_handle, CURLINFO_CONTENT_TYPE, &ct);
                }
                Curl_EndDownload(di, failed, result, ct);
            }
        }
    }
    CheckPendingDownloads();
    // when will we curl the next time?
    // we will wait a bit to ensure our download rate is kept.
    // we now know that realtime >= curltime... so set up a new curltime
    // use the slowest allowing download to derive the maxspeed... this CAN
    // be done better, but maybe later
    maxspeed = curl_maxspeed.value;
    List_For_Each_Entry(di, &downloads, downloadinfo, list)
        if(di->maxspeed > 0)
            if(di->maxspeed < maxspeed || maxspeed <= 0)
                maxspeed = di->maxspeed;
    if(maxspeed > 0)
    {
        double bytes = bytes_sent + bytes_received; // maybe smoothen a bit?
        curltime = host.realtime + bytes / (maxspeed * 1024.0);
        bytes_sent = 0;
        bytes_received = 0;
    }
    else
        curltime = host.realtime;
    if (curl_mutex) Thread_UnlockMutex(curl_mutex);
}
Referenced by Host_Frame().
Curl_GetDownloadInfo()
Curl_downloadinfo_t * Curl_GetDownloadInfo (int * nDownloads, const char ** additional_info, char * addinfo, size_t addinfolength)
Definition at line 1613 of file libcurl.c.
{
    int i;
    downloadinfo *di;
    Curl_downloadinfo_t *downinfo;
    if(!curl_dll)
    {
        *nDownloads = 0;
        if(additional_info)
            *additional_info = NULL;
        return NULL;
    }
    if (curl_mutex) Thread_LockMutex(curl_mutex);
    i = 0;
    List_For_Each_Entry(di, &downloads, downloadinfo, list)
        ++i;
    downinfo = (Curl_downloadinfo_t *) Z_Malloc(sizeof(*downinfo) * i);
    i = 0;
    List_For_Each_Entry(di, &downloads, downloadinfo, list)
    {
        // do not show infobars for background downloads
        if(developer.integer <= 0)
            if(di->buffer)
                continue;
        dp_strlcpy(downinfo[i].filename, di->filename, sizeof(downinfo[i].filename));
        if(di->curle)
        {
            downinfo[i].progress = Curl_GetDownloadAmount(di);
            downinfo[i].speed = Curl_GetDownloadSpeed(di);
            downinfo[i].queued = false;
        }
        else
        {
            downinfo[i].queued = true;
        }
        ++i;
    }
    if(additional_info)
    {
        // TODO: can I clear command_when_done as soon as the first download fails?
        if(*command_when_done && !numdownloads_fail && numdownloads_added)
        {
            if(!strncmp(command_when_done, "connect ", 8))
                dpsnprintf(addinfo, addinfolength, "(will join %s when done)", command_when_done + 8);
            else if(!strcmp(command_when_done, "cl_begindownloads"))
                dpsnprintf(addinfo, addinfolength, "(will enter the game when done)");
            else
                dpsnprintf(addinfo, addinfolength, "(will do '%s' when done)", command_when_done);
            *additional_info = addinfo;
        }
        else
            *additional_info = NULL;
    }
    *nDownloads = i;
    if (curl_mutex) Thread_UnlockMutex(curl_mutex);
    return downinfo;
}
Referenced by SCR_DrawCurlDownload(), and SCR_InfobarHeight().
Curl_Have_forthismap()
qbool Curl_Have_forthismap (void)
Definition at line 310 of file libcurl.c.
{
    return numdownloads_added != 0;
}
Referenced by CL_BeginDownloads().
Curl_Init()
void Curl_Init (void)
Definition at line 810 of file libcurl.c.
{
    CURL_OpenLibrary();
    if(!curl_dll)
        return;
    if (Thread_HasThreads()) curl_mutex = Thread_CreateMutex();
    qcurl_global_init(CURL_GLOBAL_SSL);
    curlm = qcurl_multi_init();
}
Referenced by Host_Init().
Curl_Init_Commands()
void Curl_Init_Commands (void)
Definition at line 1579 of file libcurl.c.
{
    Cvar_RegisterVariable (&curl_enabled);
    Cvar_RegisterVariable (&curl_maxdownloads);
    Cvar_RegisterVariable (&curl_maxspeed);
    Cvar_RegisterVariable (&curl_useragent);
    Cvar_RegisterVariable (&curl_useragent_append);
    Cvar_RegisterVirtual  (&curl_enabled,          "cl_curl_enabled");
    Cvar_RegisterVirtual  (&curl_maxdownloads,     "cl_curl_maxdownloads");
    Cvar_RegisterVirtual  (&curl_maxspeed,         "cl_curl_maxspeed");
    Cvar_RegisterVirtual  (&curl_useragent,        "cl_curl_useragent");
    Cvar_RegisterVirtual  (&curl_useragent_append, "cl_curl_useragent_append");
    Cvar_RegisterVariable (&sv_curl_defaulturl);
    Cvar_RegisterVariable (&sv_curl_serverpackages);
    Cvar_RegisterVariable (&sv_curl_maxspeed);
    Cvar_RegisterVariable (&developer_curl);
    Cmd_AddCommand(CF_CLIENT | CF_CLIENT_FROM_SERVER, "curl", Curl_Curl_f, "download data from an URL and add to search path");
    //Cmd_AddCommand(cmd_local, "curlcat", Curl_CurlCat_f, "display data from an URL (debugging command)");
}
Referenced by Host_Init().
Curl_Register_predownload()
void Curl_Register_predownload (void)
Definition at line 315 of file libcurl.c.
{
    if (curl_mutex) Thread_LockMutex(curl_mutex);
    Curl_CommandWhenDone("cl_begindownloads");
    Curl_CommandWhenError("cl_begindownloads");
    if (curl_mutex) Thread_UnlockMutex(curl_mutex);
}
Referenced by CL_BeginDownloads(), and Curl_Curl_f().
Curl_RequireFile()
void Curl_RequireFile (const char * filename)
Definition at line 1780 of file libcurl.c.
{
    requirement *req = (requirement *) Z_Malloc(sizeof(*requirements));
    req->next = requirements;
    dp_strlcpy(req->filename, filename, sizeof(req->filename));
    requirements = req;
}
Referenced by SV_SpawnServer().
Curl_Running()
qbool Curl_Running (void)
Definition at line 1308 of file libcurl.c.
{
    if(!curl_dll)
        return false;
    return !List_Is_Empty(&downloads);
}
Referenced by Curl_Info_f().
Curl_Select()
int Curl_Select (int timeout_ms)
Definition at line 1263 of file libcurl.c.
{
    CURLMcode err;
    int numfds;
    if (List_Is_Empty(&downloads))
        return 0;
    err = qcurl_multi_wait(curlm, NULL, 0, timeout_ms, &numfds);
    if (err == CURLM_OK)
        return numfds;
    Con_Printf("curl_multi_wait() failed, code %d\n", err);
    return 0;
}
Referenced by Sys_Sleep().
Curl_SendRequirements()
void Curl_SendRequirements (void)
Definition at line 1854 of file libcurl.c.
{
    // for each requirement, find the pack name
    char sendbuffer[4096] = "";
    requirement *req;
    qbool foundone = false;
    const char *p;
    for(req = requirements; req; req = req->next)
        foundone = Curl_SendRequirement(req->filename, foundone, sendbuffer, sizeof(sendbuffer)) || foundone;
    p = sv_curl_serverpackages.string;
    while(COM_ParseToken_Simple(&p, false, false, true))
        foundone = Curl_SendRequirement(com_token, foundone, sendbuffer, sizeof(sendbuffer)) || foundone;
    if(foundone)
        dp_strlcat(sendbuffer, "curl --finish_autodownload\n", sizeof(sendbuffer));
    if(strlen(sendbuffer) + 1 < sizeof(sendbuffer))
        SV_ClientCommands("%s", sendbuffer);
    else
        Con_Printf("Could not initiate autodownload due to URL buffer overflow\n");
}
Referenced by SV_SendServerinfo().
Curl_Shutdown()
void Curl_Shutdown (void)
Definition at line 828 of file libcurl.c.
{
    if(!curl_dll)
        return;
    Curl_ClearRequirements();
    Curl_CancelAll();
    if (curl_mutex) Thread_DestroyMutex(curl_mutex);
    CURL_CloseLibrary();
    curl_dll = NULL;
}
Referenced by Host_Shutdown().