DarkPlaces: mathlib.h File Reference
mathlib.h File Reference
#include "qtypes.h"
Data Structures
struct tinyplane_t
LadyHavoc: minimal plane structure.
struct tinydoubleplane_t
struct randomseed_t
Macros
#define M_PI 3.14159265358979323846
#define bound(min, num, max) ((num) >= (min) ? ((num) < (max) ? (num) : (max)) : (min))
#define min(A, B) ((A) < (B) ? (A) : (B))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define lhrandom(MIN, MAX) (((double)(rand() + 0.5) / ((double)RAND_MAX + 1)) * ((MAX)-(MIN)) + (MIN))
LadyHavoc: this function never returns exactly MIN or exactly MAX, because of a QuakeC bug in id1 where the line self.nextthink = self.nexthink + random() * 0.5; can result in 0 (self.nextthink is 0 at this point in the code to begin with), causing "stone monsters" that never spawned properly, also MAX is avoided because some people use random() as an index into arrays or for loop conditions, where hitting exactly MAX may be a fatal error.
#define invpow(base, number) (log(number) / log(base))
#define log2i(n) ((((n) & 0xAAAAAAAA) != 0 ? 1 : 0) | (((n) & 0xCCCCCCCC) != 0 ? 2 : 0) | (((n) & 0xF0F0F0F0) != 0 ? 4 : 0) | (((n) & 0xFF00FF00) != 0 ? 8 : 0) | (((n) & 0xFFFF0000) != 0 ? 16 : 0))
returns log base 2 of "n" \WARNING: "n" MUST be a power of 2!
#define bit2i(n) log2i((n) << 1)
\TODO: what is this function supposed to do?
#define boolxor(a, b) (!(a) != !(b))
boolean XOR (why doesn't C have the ^^ operator for this purpose?)
#define DEG2RAD(a) ((a) * ((float) M_PI / 180.0f))
#define RAD2DEG(a) ((a) * (180.0f / (float) M_PI))
#define ANGLEMOD(a) ((a) - 360.0 * floor((a) / 360.0))
#define Q_rint(x) ((x) > 0 ? (int)((x) + 0.5) : (int)((x) - 0.5))
#define DotProduct2(a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1])
#define Vector2Clear(a) ((a)[0]=(a)[1]=0)
#define Vector2Compare(a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1]))
#define Vector2Copy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1])
#define Vector2Negate(a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]))
#define Vector2Set(a, b, c) ((a)[0]=(b),(a)[1]=(c))
#define Vector2Scale(in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale))
#define Vector2Normalize2(v, dest) {float ilength = (float)DotProduct2((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;}
#define DotProduct4(a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1]+(a)[2]*(b)[2]+(a)[3]*(b)[3])
#define Vector4Clear(a) ((a)[0]=(a)[1]=(a)[2]=(a)[3]=0)
#define Vector4Compare(a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1])&&((a)[2]==(b)[2])&&((a)[3]==(b)[3]))
#define Vector4Copy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
#define Vector4Negate(a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]),(b)[2]=-((a)[2]),(b)[3]=-((a)[3]))
#define Vector4Set(a, b, c, d, e) ((a)[0]=(b),(a)[1]=(c),(a)[2]=(d),(a)[3]=(e))
#define Vector4Normalize2(v, dest) {float ilength = (float)DotProduct4((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;dest[2] = (v)[2] * ilength;dest[3] = (v)[3] * ilength;}
#define Vector4Subtract(a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2],(c)[3]=(a)[3]-(b)[3])
#define Vector4Add(a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2],(c)[3]=(a)[3]+(b)[3])
#define Vector4Scale(in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale),(out)[2] = (in)[2] * (scale),(out)[3] = (in)[3] * (scale))
#define Vector4Multiply(a, b, c) ((c)[0]=(a)[0]*(b)[0],(c)[1]=(a)[1]*(b)[1],(c)[2]=(a)[2]*(b)[2],(c)[3]=(a)[3]*(b)[3])
#define Vector4MA(a, scale, b, c) ((c)[0] = (a)[0] + (scale) * (b)[0],(c)[1] = (a)[1] + (scale) * (b)[1],(c)[2] = (a)[2] + (scale) * (b)[2],(c)[3] = (a)[3] + (scale) * (b)[3])
#define Vector4Lerp(v1, lerp, v2, c) ((c)[0] = (v1)[0] + (lerp) * ((v2)[0] - (v1)[0]), (c)[1] = (v1)[1] + (lerp) * ((v2)[1] - (v1)[1]), (c)[2] = (v1)[2] + (lerp) * ((v2)[2] - (v1)[2]), (c)[3] = (v1)[3] + (lerp) * ((v2)[3] - (v1)[3]))
#define VectorNegate(a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]),(b)[2]=-((a)[2]))
#define VectorSet(a, b, c, d) ((a)[0]=(b),(a)[1]=(c),(a)[2]=(d))
#define VectorClear(a) ((a)[0]=(a)[1]=(a)[2]=0)
#define DotProduct(a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1]+(a)[2]*(b)[2])
#define VectorSubtract(a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
#define VectorAdd(a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
#define VectorCopy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2])
#define VectorMultiply(a, b, c) ((c)[0]=(a)[0]*(b)[0],(c)[1]=(a)[1]*(b)[1],(c)[2]=(a)[2]*(b)[2])
#define CrossProduct(a, b, c) ((c)[0]=(a)[1]*(b)[2]-(a)[2]*(b)[1],(c)[1]=(a)[2]*(b)[0]-(a)[0]*(b)[2],(c)[2]=(a)[0]*(b)[1]-(a)[1]*(b)[0])
#define VectorNormalize(v) {float ilength = (float)DotProduct((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);(v)[0] *= ilength;(v)[1] *= ilength;(v)[2] *= ilength;}
#define VectorNormalize2(v, dest) {float ilength = (float)DotProduct((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;dest[2] = (v)[2] * ilength;}
#define VectorNormalizeDouble(v) {double ilength = DotProduct((v),(v));if (ilength) ilength = 1.0 / sqrt(ilength);(v)[0] *= ilength;(v)[1] *= ilength;(v)[2] *= ilength;}
#define VectorDistance2(a, b) (((a)[0] - (b)[0]) * ((a)[0] - (b)[0]) + ((a)[1] - (b)[1]) * ((a)[1] - (b)[1]) + ((a)[2] - (b)[2]) * ((a)[2] - (b)[2]))
#define VectorDistance(a, b) (sqrt(VectorDistance2(a,b)))
#define VectorLength(a) (sqrt((double)DotProduct(a, a)))
#define VectorLength2(a) (DotProduct(a, a))
#define VectorScale(in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale),(out)[2] = (in)[2] * (scale))
#define VectorScaleCast(in, scale, outtype, out) ((out)[0] = (outtype) ((in)[0] * (scale)),(out)[1] = (outtype) ((in)[1] * (scale)),(out)[2] = (outtype) ((in)[2] * (scale)))
#define VectorCompare(a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1])&&((a)[2]==(b)[2]))
#define VectorMA(a, scale, b, c) ((c)[0] = (a)[0] + (scale) * (b)[0],(c)[1] = (a)[1] + (scale) * (b)[1],(c)[2] = (a)[2] + (scale) * (b)[2])
#define VectorM(scale1, b1, c) ((c)[0] = (scale1) * (b1)[0],(c)[1] = (scale1) * (b1)[1],(c)[2] = (scale1) * (b1)[2])
#define VectorMAM(scale1, b1, scale2, b2, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2])
#define VectorMAMAM(scale1, b1, scale2, b2, scale3, b3, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0] + (scale3) * (b3)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1] + (scale3) * (b3)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2] + (scale3) * (b3)[2])
#define VectorMAMAMAM(scale1, b1, scale2, b2, scale3, b3, scale4, b4, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0] + (scale3) * (b3)[0] + (scale4) * (b4)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1] + (scale3) * (b3)[1] + (scale4) * (b4)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2] + (scale3) * (b3)[2] + (scale4) * (b4)[2])
#define VectorRandom(v) do{(v)[0] = lhrandom(-1, 1);(v)[1] = lhrandom(-1, 1);(v)[2] = lhrandom(-1, 1);}while(DotProduct(v, v) > 1)
#define VectorLerp(v1, lerp, v2, c) ((c)[0] = (v1)[0] + (lerp) * ((v2)[0] - (v1)[0]), (c)[1] = (v1)[1] + (lerp) * ((v2)[1] - (v1)[1]), (c)[2] = (v1)[2] + (lerp) * ((v2)[2] - (v1)[2]))
#define VectorReflect(a, r, b, c) do{double d;d = DotProduct((a), (b)) * -(1.0 + (r));VectorMA((a), (d), (b), (c));}while(0)
#define BoxesOverlap(a, b, c, d) ((a)[0] <= (d)[0] && (b)[0] >= (c)[0] && (a)[1] <= (d)[1] && (b)[1] >= (c)[1] && (a)[2] <= (d)[2] && (b)[2] >= (c)[2])
#define BoxInsideBox(a, b, c, d) ((a)[0] >= (c)[0] && (b)[0] <= (d)[0] && (a)[1] >= (c)[1] && (b)[1] <= (d)[1] && (a)[2] >= (c)[2] && (b)[2] <= (d)[2])
#define TriangleBBoxOverlapsBox(a, b, c, d, e) (min((a)[0], min((b)[0], (c)[0])) < (e)[0] && max((a)[0], max((b)[0], (c)[0])) > (d)[0] && min((a)[1], min((b)[1], (c)[1])) < (e)[1] && max((a)[1], max((b)[1], (c)[1])) > (d)[1] && min((a)[2], min((b)[2], (c)[2])) < (e)[2] && max((a)[2], max((b)[2], (c)[2])) > (d)[2])
#define TriangleNormal(a, b, c, n)
#define PointInfrontOfTriangle(p, a, b, c)
#define lhcheeserand(seed) ((seed) = ((seed) * 987211u) ^ ((seed) >> 13u) ^ 914867)
#define lhcheeserandom(seed, MIN, MAX) ((double)(lhcheeserand(seed) + 0.5) / ((double)4096.0*1024.0*1024.0) * ((MAX)-(MIN)) + (MIN))
#define VectorCheeseRandom(seed, v) do{(v)[0] = lhcheeserandom(seed,-1, 1);(v)[1] = lhcheeserandom(seed,-1, 1);(v)[2] = lhcheeserandom(seed,-1, 1);}while(DotProduct(v, v) > 1)
#define VectorLehmerRandom(seed, v) do{(v)[0] = Math_crandomf(seed);(v)[1] = Math_crandomf(seed);(v)[2] = Math_crandomf(seed);}while(DotProduct(v, v) > 1)
#define VectorCopy4(a, b) {(b)[0]=(a)[0];(b)[1]=(a)[1];(b)[2]=(a)[2];(b)[3]=(a)[3];}
#define NUMVERTEXNORMALS 162
#define PlaneDist(point, plane) ((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal))
#define PlaneDiff(point, plane) (((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal)) - (plane)->dist)
Functions
unsigned int CeilPowerOf2 (unsigned int value)
returns the smallest integer greater than or equal to "value", or 0 if "value" is too big
float VectorNormalizeLength (vec3_t v)
returns vector length
unsigned char NormalToByte (const vec3_t n)
void ByteToNormal (unsigned char num, vec3_t n)
void R_ConcatRotations (const float in1[3 *3], const float in2[3 *3], float out[3 *3])
void R_ConcatTransforms (const float in1[3 *4], const float in2[3 *4], float out[3 *4])
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
void AngleVectorsFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up)
LadyHavoc: proper matrix version of AngleVectors.
void AngleVectorsDuke3DFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up, double maxShearAngle)
divVerent: improper matrix version of AngleVectors
void AngleMatrix (const vec3_t angles, const vec3_t translate, vec_t matrix[][4])
LadyHavoc: builds a [3][4] matrix.
void AnglesFromVectors (vec3_t angles, const vec3_t forward, const vec3_t up, qbool flippitch)
LadyHavoc: calculates pitch/yaw/roll angles from forward and up vectors.
void VectorVectors (const vec3_t forward, vec3_t right, vec3_t up)
LadyHavoc: like AngleVectors, but taking a forward vector instead of angles, useful!
void VectorVectorsDouble (const double *forward, double *right, double *up)
void PlaneClassify (struct mplane_s *p)
int BoxOnPlaneSide (const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p)
int BoxOnPlaneSide_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, const vec_t dist)
void BoxPlaneCorners (const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p, vec3_t outnear, vec3_t outfar)
void BoxPlaneCorners_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec3_t outnear, vec3_t outfar)
void BoxPlaneCornerDistances (const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p, vec_t *outnear, vec_t *outfar)
void BoxPlaneCornerDistances_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec_t *outnear, vec_t *outfar)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
float RadiusFromBoundsAndOrigin (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
void Matrix4x4_Print (const struct matrix4x4_s *in)
print a matrix to the console
int Math_atov (const char *s, prvm_vec3_t out)
void BoxFromPoints (vec3_t mins, vec3_t maxs, int numpoints, vec_t *point3f)
int LoopingFrameNumberFromDouble (double t, int loopframes)
void Math_RandomSeed_Reset (randomseed_t *r)
void Math_RandomSeed_FromInts (randomseed_t *r, unsigned int s0, unsigned int s1, unsigned int s2, unsigned int s3)
unsigned long long Math_rand64 (randomseed_t *r)
float Math_randomf (randomseed_t *r)
float Math_crandomf (randomseed_t *r)
float Math_randomrangef (randomseed_t *r, float minf, float maxf)
int Math_randomrangei (randomseed_t *r, int mini, int maxi)
void Mathlib_Init (void)
Variables
vec3_t vec3_origin
float m_bytenormals [NUMVERTEXNORMALS][3]
Macro Definition Documentation
ANGLEMOD
#define ANGLEMOD (a) ((a) - 360.0 * floor((a) / 360.0))
Definition at line 67 of file mathlib.h.
bit2i
#define bit2i (n) log2i((n) << 1)
\TODO: what is this function supposed to do?
Definition at line 57 of file mathlib.h.
boolxor
#define boolxor (a, b) (!(a) != !(b))
boolean XOR (why doesn't C have the ^^ operator for this purpose?)
Definition at line 60 of file mathlib.h.
bound
#define bound (min, num, max) ((num) >= (min) ? ((num) < (max) ? (num) : (max)) : (min))
Definition at line 34 of file mathlib.h.
BoxesOverlap
#define BoxesOverlap (a, b, c, d) ((a)[0] <= (d)[0] && (b)[0] >= (c)[0] && (a)[1] <= (d)[1] && (b)[1] >= (c)[1] && (a)[2] <= (d)[2] && (b)[2] >= (c)[2])
Definition at line 121 of file mathlib.h.
BoxInsideBox
#define BoxInsideBox (a, b, c, d) ((a)[0] >= (c)[0] && (b)[0] <= (d)[0] && (a)[1] >= (c)[1] && (b)[1] <= (d)[1] && (a)[2] >= (c)[2] && (b)[2] <= (d)[2])
Definition at line 122 of file mathlib.h.
CrossProduct
#define CrossProduct (a, b, c) ((c)[0]=(a)[1]*(b)[2]-(a)[2]*(b)[1],(c)[1]=(a)[2]*(b)[0]-(a)[0]*(b)[2],(c)[2]=(a)[0]*(b)[1]-(a)[1]*(b)[0])
Definition at line 102 of file mathlib.h.
DEG2RAD
#define DEG2RAD (a) ((a) * ((float) M_PI / 180.0f))
Definition at line 65 of file mathlib.h.
DotProduct
#define DotProduct (a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1]+(a)[2]*(b)[2])
Definition at line 97 of file mathlib.h.
DotProduct2
#define DotProduct2 (a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1])
Definition at line 71 of file mathlib.h.
DotProduct4
#define DotProduct4 (a, b) ((a)[0]*(b)[0]+(a)[1]*(b)[1]+(a)[2]*(b)[2]+(a)[3]*(b)[3])
Definition at line 80 of file mathlib.h.
invpow
#define invpow (base, number) (log(number) / log(base))
Definition at line 50 of file mathlib.h.
lhcheeserand
#define lhcheeserand (seed) ((seed) = ((seed) * 987211u) ^ ((seed) >> 13u) ^ 914867)
Definition at line 169 of file mathlib.h.
lhcheeserandom
#define lhcheeserandom (seed, MIN, MAX) ((double)(lhcheeserand(seed) + 0.5) / ((double)4096.0*1024.0*1024.0) * ((MAX)-(MIN)) + (MIN))
Definition at line 170 of file mathlib.h.
lhrandom
#define lhrandom (MIN, MAX) (((double)(rand() + 0.5) / ((double)RAND_MAX + 1)) * ((MAX)-(MIN)) + (MIN))
LadyHavoc: this function never returns exactly MIN or exactly MAX, because of a QuakeC bug in id1 where the line self.nextthink = self.nexthink + random() * 0.5; can result in 0 (self.nextthink is 0 at this point in the code to begin with), causing "stone monsters" that never spawned properly, also MAX is avoided because some people use random() as an index into arrays or for loop conditions, where hitting exactly MAX may be a fatal error.
Definition at line 48 of file mathlib.h.
log2i
#define log2i (n) ((((n) & 0xAAAAAAAA) != 0 ? 1 : 0) | (((n) & 0xCCCCCCCC) != 0 ? 2 : 0) | (((n) & 0xF0F0F0F0) != 0 ? 4 : 0) | (((n) & 0xFF00FF00) != 0 ? 8 : 0) | (((n) & 0xFFFF0000) != 0 ? 16 : 0))
returns log base 2 of "n" \WARNING: "n" MUST be a power of 2!
Definition at line 54 of file mathlib.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 28 of file mathlib.h.
max
#define max (A, B) ((A) > (B) ? (A) : (B))
Definition at line 38 of file mathlib.h.
min
#define min (A, B) ((A) < (B) ? (A) : (B))
Definition at line 37 of file mathlib.h.
NUMVERTEXNORMALS
#define NUMVERTEXNORMALS 162
Definition at line 224 of file mathlib.h.
PlaneDiff
#define PlaneDiff (point, plane) (((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal)) - (plane)->dist)
Definition at line 256 of file mathlib.h.
PlaneDist
#define PlaneDist (point, plane) ((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal))
Definition at line 255 of file mathlib.h.
PointInfrontOfTriangle
#define PointInfrontOfTriangle (p, a, b, c)
Value:
(((p)[0] - (a)[0]) * (((a)[1] - (b)[1]) * ((c)[2] - (b)[2]) - ((a)[2] - (b)[2]) * ((c)[1] - (b)[1])) \
+ ((p)[1] - (a)[1]) * (((a)[2] - (b)[2]) * ((c)[0] - (b)[0]) - ((a)[0] - (b)[0]) * ((c)[2] - (b)[2])) \
+ ((p)[2] - (a)[2]) * (((a)[0] - (b)[0]) * ((c)[1] - (b)[1]) - ((a)[1] - (b)[1]) * ((c)[0] - (b)[0])) > 0)
Fast PointInfrontOfTriangle. subtracts v1 from v0 and v2, combined into a crossproduct, combined with a dotproduct of the light location relative to the first point of the triangle (any point works, since any triangle is obviously flat), and finally a comparison to determine if the light is infront of the triangle (the goal of this statement) we do not need to normalize the surface normal because both sides of the comparison use it, therefore they are both multiplied the same amount... furthermore a subtract can be done on the point to eliminate one dotproduct this is ((p - a) * cross(a-b,c-b))
Definition at line 142 of file mathlib.h.
{
    float dir0[3], dir1[3], normal[3];
    // calculate two mostly perpendicular edge directions
    VectorSubtract(a, b, dir0);
    VectorSubtract(c, b, dir1);
    // we have two edge directions, we can calculate a third vector from
    // them, which is the direction of the surface normal (its magnitude
    // is not 1 however)
    CrossProduct(dir0, dir1, normal);
    // compare distance of light along normal, with distance of any point
    // of the triangle along the same normal (the triangle is planar,
    // I.E. flat, so all points give the same answer)
    return DotProduct(p, normal) > DotProduct(a, normal);
}
#endif
#define lhcheeserand(seed) ((seed) = ((seed) * 987211u) ^ ((seed) >> 13u) ^ 914867)
#define lhcheeserandom(seed,MIN,MAX) ((double)(lhcheeserand(seed) + 0.5) / ((double)4096.0*1024.0*1024.0) * ((MAX)-(MIN)) + (MIN))
#define VectorCheeseRandom(seed,v) do{(v)[0] = lhcheeserandom(seed,-1, 1);(v)[1] = lhcheeserandom(seed,-1, 1);(v)[2] = lhcheeserandom(seed,-1, 1);}while(DotProduct(v, v) > 1)
#define VectorLehmerRandom(seed,v) do{(v)[0] = Math_crandomf(seed);(v)[1] = Math_crandomf(seed);(v)[2] = Math_crandomf(seed);}while(DotProduct(v, v) > 1)
/*
// LadyHavoc: quaternion math, untested, don't know if these are correct,
// need to add conversion to/from matrices
// LadyHavoc: later note: the matrix faq is useful: http://skal.planet-d.net/demo/matrixfaq.htm
// LadyHavoc: these are probably very wrong and I'm not sure I care, not used by anything
// returns length of quaternion
#define qlen(a) ((float) sqrt((a)[0]*(a)[0]+(a)[1]*(a)[1]+(a)[2]*(a)[2]+(a)[3]*(a)[3]))
// returns squared length of quaternion
#define qlen2(a) ((a)[0]*(a)[0]+(a)[1]*(a)[1]+(a)[2]*(a)[2]+(a)[3]*(a)[3])
// makes a quaternion from x, y, z, and a rotation angle (in degrees)
#define QuatMake(x,y,z,r,c)\
{\
if (r == 0)\
{\
(c)[0]=(float) ((x) * (1.0f / 0.0f));\
(c)[1]=(float) ((y) * (1.0f / 0.0f));\
(c)[2]=(float) ((z) * (1.0f / 0.0f));\
(c)[3]=(float) 1.0f;\
}\
else\
{\
float r2 = (r) * 0.5 * (M_PI / 180);\
float r2is = 1.0f / sin(r2);\
(c)[0]=(float) ((x)/r2is);\
(c)[1]=(float) ((y)/r2is);\
(c)[2]=(float) ((z)/r2is);\
(c)[3]=(float) (cos(r2));\
}\
}
// makes a quaternion from a vector and a rotation angle (in degrees)
#define QuatFromVec(a,r,c) QuatMake((a)[0],(a)[1],(a)[2],(r))
// copies a quaternion
#define QuatCopy(a,c) {(c)[0]=(a)[0];(c)[1]=(a)[1];(c)[2]=(a)[2];(c)[3]=(a)[3];}
#define QuatSubtract(a,b,c) {(c)[0]=(a)[0]-(b)[0];(c)[1]=(a)[1]-(b)[1];(c)[2]=(a)[2]-(b)[2];(c)[3]=(a)[3]-(b)[3];}
#define QuatAdd(a,b,c) {(c)[0]=(a)[0]+(b)[0];(c)[1]=(a)[1]+(b)[1];(c)[2]=(a)[2]+(b)[2];(c)[3]=(a)[3]+(b)[3];}
#define QuatScale(a,b,c) {(c)[0]=(a)[0]*b;(c)[1]=(a)[1]*b;(c)[2]=(a)[2]*b;(c)[3]=(a)[3]*b;}
// FIXME: this is wrong, do some more research on quaternions
//#define QuatMultiply(a,b,c) {(c)[0]=(a)[0]*(b)[0];(c)[1]=(a)[1]*(b)[1];(c)[2]=(a)[2]*(b)[2];(c)[3]=(a)[3]*(b)[3];}
// FIXME: this is wrong, do some more research on quaternions
//#define QuatMultiplyAdd(a,b,d,c) {(c)[0]=(a)[0]*(b)[0]+d[0];(c)[1]=(a)[1]*(b)[1]+d[1];(c)[2]=(a)[2]*(b)[2]+d[2];(c)[3]=(a)[3]*(b)[3]+d[3];}
#define qdist(a,b) ((float) sqrt(((b)[0]-(a)[0])*((b)[0]-(a)[0])+((b)[1]-(a)[1])*((b)[1]-(a)[1])+((b)[2]-(a)[2])*((b)[2]-(a)[2])+((b)[3]-(a)[3])*((b)[3]-(a)[3])))
#define qdist2(a,b) (((b)[0]-(a)[0])*((b)[0]-(a)[0])+((b)[1]-(a)[1])*((b)[1]-(a)[1])+((b)[2]-(a)[2])*((b)[2]-(a)[2])+((b)[3]-(a)[3])*((b)[3]-(a)[3]))
*/
#define VectorCopy4(a,b) {(b)[0]=(a)[0];(b)[1]=(a)[1];(b)[2]=(a)[2];(b)[3]=(a)[3];}
float VectorNormalizeLength (vec3_t v);
#define NUMVERTEXNORMALS    162
extern float m_bytenormals[NUMVERTEXNORMALS][3];
unsigned char NormalToByte(const vec3_t n);
void ByteToNormal(unsigned char num, vec3_t n);
void R_ConcatRotations (const float in1[3*3], const float in2[3*3], float out[3*3]);
void R_ConcatTransforms (const float in1[3*4], const float in2[3*4], float out[3*4]);
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up);
void AngleVectorsFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up);
void AngleVectorsDuke3DFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up, double maxShearAngle);
void AngleMatrix (const vec3_t angles, const vec3_t translate, vec_t matrix[][4]);
void AnglesFromVectors (vec3_t angles, const vec3_t forward, const vec3_t up, qbool flippitch);
void VectorVectors(const vec3_t forward, vec3_t right, vec3_t up);
void VectorVectorsDouble(const double *forward, double *right, double *up);
void PlaneClassify(struct mplane_s *p);
int BoxOnPlaneSide(const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p);
int BoxOnPlaneSide_Separate(const vec3_t emins, const vec3_t emaxs, const vec3_t normal, const vec_t dist);
void BoxPlaneCorners(const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p, vec3_t outnear, vec3_t outfar);
void BoxPlaneCorners_Separate(const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec3_t outnear, vec3_t outfar);
void BoxPlaneCornerDistances(const vec3_t emins, const vec3_t emaxs, const struct mplane_s *p, vec_t *outnear, vec_t *outfar);
void BoxPlaneCornerDistances_Separate(const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec_t *outnear, vec_t *outfar);
#define PlaneDist(point,plane)  ((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal))
#define PlaneDiff(point,plane) (((plane)->type < 3 ? (point)[(plane)->type] : DotProduct((point), (plane)->normal)) - (plane)->dist)
typedef struct tinyplane_s
{
    float normal[3], dist;
}
tinyplane_t;
typedef struct tinydoubleplane_s
{
    double normal[3], dist;
}
tinydoubleplane_t;
void RotatePointAroundVector(vec3_t dst, const vec3_t dir, const vec3_t point, float degrees);
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs);
float RadiusFromBoundsAndOrigin (const vec3_t mins, const vec3_t maxs, const vec3_t origin);
struct matrix4x4_s;
void Matrix4x4_Print(const struct matrix4x4_s *in);
int Math_atov(const char *s, prvm_vec3_t out);
void BoxFromPoints(vec3_t mins, vec3_t maxs, int numpoints, vec_t *point3f);
int LoopingFrameNumberFromDouble(double t, int loopframes);
// implementation of 128bit Lehmer Random Number Generator with 2^126 period
// https://en.wikipedia.org/Lehmer_random_number_generator
typedef struct randomseed_s
{
    unsigned int s[4];
}
randomseed_t;
void Math_RandomSeed_Reset(randomseed_t *r);
void Math_RandomSeed_FromInts(randomseed_t *r, unsigned int s0, unsigned int s1, unsigned int s2, unsigned int s3);
unsigned long long Math_rand64(randomseed_t *r);
float Math_randomf(randomseed_t *r);
float Math_crandomf(randomseed_t *r);
float Math_randomrangef(randomseed_t *r, float minf, float maxf);
int Math_randomrangei(randomseed_t *r, int mini, int maxi);
void Mathlib_Init(void);
#endif
Q_rint
#define Q_rint (x) ((x) > 0 ? (int)((x) + 0.5) : (int)((x) - 0.5))
Definition at line 69 of file mathlib.h.
RAD2DEG
#define RAD2DEG (a) ((a) * (180.0f / (float) M_PI))
Definition at line 66 of file mathlib.h.
TriangleBBoxOverlapsBox
#define TriangleBBoxOverlapsBox (a, b, c, d, e) (min((a)[0], min((b)[0], (c)[0])) < (e)[0] && max((a)[0], max((b)[0], (c)[0])) > (d)[0] && min((a)[1], min((b)[1], (c)[1])) < (e)[1] && max((a)[1], max((b)[1], (c)[1])) > (d)[1] && min((a)[2], min((b)[2], (c)[2])) < (e)[2] && max((a)[2], max((b)[2], (c)[2])) > (d)[2])
Definition at line 123 of file mathlib.h.
TriangleNormal
#define TriangleNormal (a, b, c, n)
Value:
    ( \
    (n)[0] = ((a)[1] - (b)[1]) * ((c)[2] - (b)[2]) - ((a)[2] - (b)[2]) * ((c)[1] - (b)[1]), \
    (n)[1] = ((a)[2] - (b)[2]) * ((c)[0] - (b)[0]) - ((a)[0] - (b)[0]) * ((c)[2] - (b)[2]), \
    (n)[2] = ((a)[0] - (b)[0]) * ((c)[1] - (b)[1]) - ((a)[1] - (b)[1]) * ((c)[0] - (b)[0]) \
    )
Definition at line 125 of file mathlib.h.
Vector2Clear
#define Vector2Clear (a) ((a)[0]=(a)[1]=0)
Definition at line 72 of file mathlib.h.
Vector2Compare
#define Vector2Compare (a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1]))
Definition at line 73 of file mathlib.h.
Vector2Copy
#define Vector2Copy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1])
Definition at line 74 of file mathlib.h.
Vector2Negate
#define Vector2Negate (a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]))
Definition at line 75 of file mathlib.h.
Vector2Normalize2
#define Vector2Normalize2 (v, dest) {float ilength = (float)DotProduct2((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;}
Definition at line 78 of file mathlib.h.
Vector2Scale
#define Vector2Scale (in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale))
Definition at line 77 of file mathlib.h.
Vector2Set
#define Vector2Set (a, b, c) ((a)[0]=(b),(a)[1]=(c))
Definition at line 76 of file mathlib.h.
Vector4Add
#define Vector4Add (a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2],(c)[3]=(a)[3]+(b)[3])
Definition at line 88 of file mathlib.h.
Vector4Clear
#define Vector4Clear (a) ((a)[0]=(a)[1]=(a)[2]=(a)[3]=0)
Definition at line 81 of file mathlib.h.
Vector4Compare
#define Vector4Compare (a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1])&&((a)[2]==(b)[2])&&((a)[3]==(b)[3]))
Definition at line 82 of file mathlib.h.
Vector4Copy
#define Vector4Copy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
Definition at line 83 of file mathlib.h.
Vector4Lerp
#define Vector4Lerp (v1, lerp, v2, c) ((c)[0] = (v1)[0] + (lerp) * ((v2)[0] - (v1)[0]), (c)[1] = (v1)[1] + (lerp) * ((v2)[1] - (v1)[1]), (c)[2] = (v1)[2] + (lerp) * ((v2)[2] - (v1)[2]), (c)[3] = (v1)[3] + (lerp) * ((v2)[3] - (v1)[3]))
Definition at line 92 of file mathlib.h.
Vector4MA
#define Vector4MA (a, scale, b, c) ((c)[0] = (a)[0] + (scale) * (b)[0],(c)[1] = (a)[1] + (scale) * (b)[1],(c)[2] = (a)[2] + (scale) * (b)[2],(c)[3] = (a)[3] + (scale) * (b)[3])
Definition at line 91 of file mathlib.h.
Vector4Multiply
#define Vector4Multiply (a, b, c) ((c)[0]=(a)[0]*(b)[0],(c)[1]=(a)[1]*(b)[1],(c)[2]=(a)[2]*(b)[2],(c)[3]=(a)[3]*(b)[3])
Definition at line 90 of file mathlib.h.
Vector4Negate
#define Vector4Negate (a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]),(b)[2]=-((a)[2]),(b)[3]=-((a)[3]))
Definition at line 84 of file mathlib.h.
Vector4Normalize2
#define Vector4Normalize2 (v, dest) {float ilength = (float)DotProduct4((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;dest[2] = (v)[2] * ilength;dest[3] = (v)[3] * ilength;}
Definition at line 86 of file mathlib.h.
Vector4Scale
#define Vector4Scale (in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale),(out)[2] = (in)[2] * (scale),(out)[3] = (in)[3] * (scale))
Definition at line 89 of file mathlib.h.
Vector4Set
#define Vector4Set (a, b, c, d, e) ((a)[0]=(b),(a)[1]=(c),(a)[2]=(d),(a)[3]=(e))
Definition at line 85 of file mathlib.h.
Vector4Subtract
#define Vector4Subtract (a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2],(c)[3]=(a)[3]-(b)[3])
Definition at line 87 of file mathlib.h.
VectorAdd
#define VectorAdd (a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
Definition at line 99 of file mathlib.h.
VectorCheeseRandom
#define VectorCheeseRandom (seed, v) do{(v)[0] = lhcheeserandom(seed,-1, 1);(v)[1] = lhcheeserandom(seed,-1, 1);(v)[2] = lhcheeserandom(seed,-1, 1);}while(DotProduct(v, v) > 1)
Definition at line 171 of file mathlib.h.
VectorClear
#define VectorClear (a) ((a)[0]=(a)[1]=(a)[2]=0)
Definition at line 96 of file mathlib.h.
VectorCompare
#define VectorCompare (a, b) (((a)[0]==(b)[0])&&((a)[1]==(b)[1])&&((a)[2]==(b)[2]))
Definition at line 112 of file mathlib.h.
VectorCopy
#define VectorCopy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2])
Definition at line 100 of file mathlib.h.
VectorCopy4
#define VectorCopy4 (a, b) {(b)[0]=(a)[0];(b)[1]=(a)[1];(b)[2]=(a)[2];(b)[3]=(a)[3];}
Definition at line 219 of file mathlib.h.
VectorDistance
#define VectorDistance (a, b) (sqrt(VectorDistance2(a,b)))
Definition at line 107 of file mathlib.h.
VectorDistance2
#define VectorDistance2 (a, b) (((a)[0] - (b)[0]) * ((a)[0] - (b)[0]) + ((a)[1] - (b)[1]) * ((a)[1] - (b)[1]) + ((a)[2] - (b)[2]) * ((a)[2] - (b)[2]))
Definition at line 106 of file mathlib.h.
VectorLehmerRandom
#define VectorLehmerRandom (seed, v) do{(v)[0] = Math_crandomf(seed);(v)[1] = Math_crandomf(seed);(v)[2] = Math_crandomf(seed);}while(DotProduct(v, v) > 1)
Definition at line 172 of file mathlib.h.
VectorLength
#define VectorLength (a) (sqrt((double)DotProduct(a, a)))
Definition at line 108 of file mathlib.h.
VectorLength2
#define VectorLength2 (a) (DotProduct(a, a))
Definition at line 109 of file mathlib.h.
VectorLerp
#define VectorLerp (v1, lerp, v2, c) ((c)[0] = (v1)[0] + (lerp) * ((v2)[0] - (v1)[0]), (c)[1] = (v1)[1] + (lerp) * ((v2)[1] - (v1)[1]), (c)[2] = (v1)[2] + (lerp) * ((v2)[2] - (v1)[2]))
Definition at line 119 of file mathlib.h.
VectorM
#define VectorM (scale1, b1, c) ((c)[0] = (scale1) * (b1)[0],(c)[1] = (scale1) * (b1)[1],(c)[2] = (scale1) * (b1)[2])
Definition at line 114 of file mathlib.h.
VectorMA
#define VectorMA (a, scale, b, c) ((c)[0] = (a)[0] + (scale) * (b)[0],(c)[1] = (a)[1] + (scale) * (b)[1],(c)[2] = (a)[2] + (scale) * (b)[2])
Definition at line 113 of file mathlib.h.
VectorMAM
#define VectorMAM (scale1, b1, scale2, b2, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2])
Definition at line 115 of file mathlib.h.
VectorMAMAM
#define VectorMAMAM (scale1, b1, scale2, b2, scale3, b3, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0] + (scale3) * (b3)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1] + (scale3) * (b3)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2] + (scale3) * (b3)[2])
Definition at line 116 of file mathlib.h.
VectorMAMAMAM
#define VectorMAMAMAM (scale1, b1, scale2, b2, scale3, b3, scale4, b4, c) ((c)[0] = (scale1) * (b1)[0] + (scale2) * (b2)[0] + (scale3) * (b3)[0] + (scale4) * (b4)[0],(c)[1] = (scale1) * (b1)[1] + (scale2) * (b2)[1] + (scale3) * (b3)[1] + (scale4) * (b4)[1],(c)[2] = (scale1) * (b1)[2] + (scale2) * (b2)[2] + (scale3) * (b3)[2] + (scale4) * (b4)[2])
Definition at line 117 of file mathlib.h.
VectorMultiply
#define VectorMultiply (a, b, c) ((c)[0]=(a)[0]*(b)[0],(c)[1]=(a)[1]*(b)[1],(c)[2]=(a)[2]*(b)[2])
Definition at line 101 of file mathlib.h.
VectorNegate
#define VectorNegate (a, b) ((b)[0]=-((a)[0]),(b)[1]=-((a)[1]),(b)[2]=-((a)[2]))
Definition at line 94 of file mathlib.h.
VectorNormalize
#define VectorNormalize (v) {float ilength = (float)DotProduct((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);(v)[0] *= ilength;(v)[1] *= ilength;(v)[2] *= ilength;}
Definition at line 103 of file mathlib.h.
VectorNormalize2
#define VectorNormalize2 (v, dest) {float ilength = (float)DotProduct((v),(v));if (ilength) ilength = 1.0f / sqrt(ilength);dest[0] = (v)[0] * ilength;dest[1] = (v)[1] * ilength;dest[2] = (v)[2] * ilength;}
Definition at line 104 of file mathlib.h.
VectorNormalizeDouble
#define VectorNormalizeDouble (v) {double ilength = DotProduct((v),(v));if (ilength) ilength = 1.0 / sqrt(ilength);(v)[0] *= ilength;(v)[1] *= ilength;(v)[2] *= ilength;}
Definition at line 105 of file mathlib.h.
VectorRandom
#define VectorRandom (v) do{(v)[0] = lhrandom(-1, 1);(v)[1] = lhrandom(-1, 1);(v)[2] = lhrandom(-1, 1);}while(DotProduct(v, v) > 1)
Definition at line 118 of file mathlib.h.
VectorReflect
#define VectorReflect (a, r, b, c) do{double d;d = DotProduct((a), (b)) * -(1.0 + (r));VectorMA((a), (d), (b), (c));}while(0)
Definition at line 120 of file mathlib.h.
VectorScale
#define VectorScale (in, scale, out) ((out)[0] = (in)[0] * (scale),(out)[1] = (in)[1] * (scale),(out)[2] = (in)[2] * (scale))
Definition at line 110 of file mathlib.h.
VectorScaleCast
#define VectorScaleCast (in, scale, outtype, out) ((out)[0] = (outtype) ((in)[0] * (scale)),(out)[1] = (outtype) ((in)[1] * (scale)),(out)[2] = (outtype) ((in)[2] * (scale)))
Definition at line 111 of file mathlib.h.
VectorSet
#define VectorSet (a, b, c, d) ((a)[0]=(b),(a)[1]=(c),(a)[2]=(d))
Definition at line 95 of file mathlib.h.
VectorSubtract
#define VectorSubtract (a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
Definition at line 98 of file mathlib.h.
Function Documentation
AngleMatrix()
void AngleMatrix (const vec3_t angles, const vec3_t translate, vec_t matrix[][4])
LadyHavoc: builds a [3][4] matrix.
AnglesFromVectors()
void AnglesFromVectors (vec3_t angles, const vec3_t forward, const vec3_t up, qbool flippitch)
LadyHavoc: calculates pitch/yaw/roll angles from forward and up vectors.
Definition at line 650 of file mathlib.c.
{
    if (forward[0] == 0 && forward[1] == 0)
    {
        if(forward[2] > 0)
        {
            angles[PITCH] = -M_PI * 0.5;
            angles[YAW] = up ? atan2(-up[1], -up[0]) : 0;
        }
        else
        {
            angles[PITCH] = M_PI * 0.5;
            angles[YAW] = up ? atan2(up[1], up[0]) : 0;
        }
        angles[ROLL] = 0;
    }
    else
    {
        angles[YAW] = atan2(forward[1], forward[0]);
        angles[PITCH] = -atan2(forward[2], sqrt(forward[0]*forward[0] + forward[1]*forward[1]));
        // note: we know that angles[PITCH] is in ]-pi/2..pi/2[ due to atan2(anything, positive)
        if (up)
        {
            vec_t cp = cos(angles[PITCH]), sp = sin(angles[PITCH]);
            // note: we know cp > 0, due to the range angles[pitch] is in
            vec_t cy = cos(angles[YAW]), sy = sin(angles[YAW]);
            vec3_t tleft, tup;
            tleft[0] = -sy;
            tleft[1] = cy;
            tleft[2] = 0;
            tup[0] = sp*cy;
            tup[1] = sp*sy;
            tup[2] = cp;
            angles[ROLL] = -atan2(DotProduct(up, tleft), DotProduct(up, tup));
            // for up == '0 0 1', this is
            // angles[ROLL] = -atan2(0, cp);
            // which is 0
        }
        else
            angles[ROLL] = 0;
        // so no up vector is equivalent to '1 0 0'!
    }
    // now convert radians to degrees, and make all values positive
    VectorScale(angles, 180.0 / M_PI, angles);
    if (flippitch)
        angles[PITCH] *= -1;
    if (angles[PITCH] < 0) angles[PITCH] += 360;
    if (angles[YAW] < 0) angles[YAW] += 360;
    if (angles[ROLL] < 0) angles[ROLL] += 360;
#if 0
{
    // debugging code
    vec3_t tforward, tleft, tup, nforward, nup;
    VectorCopy(forward, nforward);
    VectorNormalize(nforward);
    if (up)
    {
        VectorCopy(up, nup);
        VectorNormalize(nup);
        AngleVectors(angles, tforward, tleft, tup);
        if (VectorDistance(tforward, nforward) > 0.01 || VectorDistance(tup, nup) > 0.01)
        {
            Con_Printf("vectoangles('%f %f %f', '%f %f %f') = %f %f %f\n", nforward[0], nforward[1], nforward[2], nup[0], nup[1], nup[2], angles[0], angles[1], angles[2]);
            Con_Printf("^3But that is '%f %f %f', '%f %f %f'\n", tforward[0], tforward[1], tforward[2], tup[0], tup[1], tup[2]);
        }
    }
    else
    {
        AngleVectors(angles, tforward, tleft, tup);
        if (VectorDistance(tforward, nforward) > 0.01)
        {
            Con_Printf("vectoangles('%f %f %f') = %f %f %f\n", nforward[0], nforward[1], nforward[2], angles[0], angles[1], angles[2]);
            Con_Printf("^3But that is '%f %f %f'\n", tforward[0], tforward[1], tforward[2]);
        }
    }
}
#endif
}
Referenced by CL_NewParticlesFromEffectinfo(), CL_RotateMoves(), CL_UpdateNetworkEntity(), CL_VM_TransformView(), Matrix4x4_QuakeToDuke3D(), Mod_Decompile_SMD(), R_DecalSystem_SplatEntity(), and VM_vectoangles().
AngleVectors()
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 444 of file mathlib.c.
{
    double angle, sr, sp, sy, cr, cp, cy;
    angle = angles[YAW] * (M_PI*2 / 360);
    sy = sin(angle);
    cy = cos(angle);
    angle = angles[PITCH] * (M_PI*2 / 360);
    sp = sin(angle);
    cp = cos(angle);
    if (forward)
    {
        forward[0] = cp*cy;
        forward[1] = cp*sy;
        forward[2] = -sp;
    }
    if (right || up)
    {
        if (angles[ROLL])
        {
            angle = angles[ROLL] * (M_PI*2 / 360);
            sr = sin(angle);
            cr = cos(angle);
            if (right)
            {
                right[0] = -1*(sr*sp*cy+cr*-sy);
                right[1] = -1*(sr*sp*sy+cr*cy);
                right[2] = -1*(sr*cp);
            }
            if (up)
            {
                up[0] = (cr*sp*cy+-sr*-sy);
                up[1] = (cr*sp*sy+-sr*cy);
                up[2] = cr*cp;
            }
        }
        else
        {
            if (right)
            {
                right[0] = sy;
                right[1] = -cy;
                right[2] = 0;
            }
            if (up)
            {
                up[0] = (sp*cy);
                up[1] = (sp*sy);
                up[2] = cp;
            }
        }
    }
}
Referenced by AnglesFromVectors(), CL_ClientMovement_Physics_Swim(), CL_ClientMovement_Physics_Walk(), CL_NewParticlesFromEffectinfo(), CL_RotateMoves(), CL_UpdateEntityShading_GetDirectedFullbright(), CL_UpdateNetworkEntity(), Com_CalcRoll(), R_DecalSystem_SplatEntity(), SV_AirMove(), SV_Physics_Follow(), SV_WallFriction(), SV_WaterMove(), V_CalcRefdefUsing(), VM_CL_makevectors(), and VM_makevectors().
AngleVectorsDuke3DFLU()
void AngleVectorsDuke3DFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up, double maxShearAngle)
divVerent: improper matrix version of AngleVectors
Definition at line 552 of file mathlib.c.
{
    double angle, sr, sy, cr, cy;
    double sxx, sxz, szx, szz;
    double cosMaxShearAngle = cos(maxShearAngle * (M_PI*2 / 360));
    double tanMaxShearAngle = tan(maxShearAngle * (M_PI*2 / 360));
    angle = angles[YAW] * (M_PI*2 / 360);
    sy = sin(angle);
    cy = cos(angle);
    angle = angles[PITCH] * (M_PI*2 / 360);
    // We will calculate a shear matrix pitch = [[sxx sxz][szx szz]].
    if (fabs(cos(angle)) > cosMaxShearAngle)
    {
        // Pure shear. Keep the original sign of the coefficients.
        sxx = 1;
        sxz = 0;
        szx = -tan(angle);
        szz = 1;
        // Covering angle per screen coordinate:
        // d/dt arctan((sxz + t*szz) / (sxx + t*szx)) @ t=0
        // d_angle = det(S) / (sxx*sxx + szx*szx)
        //         = 1 / (1 + tan^2 angle)
        //         = cos^2 angle.
    }
    else
    {
        // A mix of shear and rotation. Implementation-wise, we're
        // looking at a capsule, and making the screen surface
        // tangential to it... and if we get here, we're looking at the
        // two half-spheres of the capsule (and the cylinder part is
        // handled above).
        double x, y, h, t, d, f;
        h = tanMaxShearAngle;
        x = cos(angle);
        y = sin(angle);
        t = h * fabs(y) + sqrt(1 - (h * x) * (h * x));
        sxx =  x * t;
        sxz =  y * t - h * (y > 0 ? 1.0 : -1.0);
        szx = -y * t;
        szz =  x * t;
        // BUT: keep the amount of a sphere we see in pitch direction
        // invariant.
        // Covering angle per screen coordinate:
        // d_angle = det(S) / (sxx*sxx + szx*szx)
        d = (sxx * szz - sxz * szx) / (sxx * sxx + szx * szx);
        f = cosMaxShearAngle * cosMaxShearAngle / d;
        sxz *= f;
        szz *= f;
    }
    if (forward)
    {
        forward[0] = sxx*cy;
        forward[1] = sxx*sy;
        forward[2] = szx;
    }
    if (left || up)
    {
        if (angles[ROLL])
        {
            angle = angles[ROLL] * (M_PI*2 / 360);
            sr = sin(angle);
            cr = cos(angle);
            if (left)
            {
                left[0] = sr*sxz*cy+cr*-sy;
                left[1] = sr*sxz*sy+cr*cy;
                left[2] = sr*szz;
            }
            if (up)
            {
                up[0] = cr*sxz*cy+-sr*-sy;
                up[1] = cr*sxz*sy+-sr*cy;
                up[2] = cr*szz;
            }
        }
        else
        {
            if (left)
            {
                left[0] = -sy;
                left[1] = cy;
                left[2] = 0;
            }
            if (up)
            {
                up[0] = sxz*cy;
                up[1] = sxz*sy;
                up[2] = szz;
            }
        }
    }
}
Referenced by Matrix4x4_QuakeToDuke3D().
AngleVectorsFLU()
void AngleVectorsFLU (const vec3_t angles, vec3_t forward, vec3_t left, vec3_t up)
LadyHavoc: proper matrix version of AngleVectors.
Definition at line 498 of file mathlib.c.
{
    double angle, sr, sp, sy, cr, cp, cy;
    angle = angles[YAW] * (M_PI*2 / 360);
    sy = sin(angle);
    cy = cos(angle);
    angle = angles[PITCH] * (M_PI*2 / 360);
    sp = sin(angle);
    cp = cos(angle);
    if (forward)
    {
        forward[0] = cp*cy;
        forward[1] = cp*sy;
        forward[2] = -sp;
    }
    if (left || up)
    {
        if (angles[ROLL])
        {
            angle = angles[ROLL] * (M_PI*2 / 360);
            sr = sin(angle);
            cr = cos(angle);
            if (left)
            {
                left[0] = sr*sp*cy+cr*-sy;
                left[1] = sr*sp*sy+cr*cy;
                left[2] = sr*cp;
            }
            if (up)
            {
                up[0] = cr*sp*cy+-sr*-sy;
                up[1] = cr*sp*sy+-sr*cy;
                up[2] = cr*cp;
            }
        }
        else
        {
            if (left)
            {
                left[0] = -sy;
                left[1] = cy;
                left[2] = 0;
            }
            if (up)
            {
                up[0] = sp*cy;
                up[1] = sp*sy;
                up[2] = cp;
            }
        }
    }
}
Referenced by SV_PushMove(), and VM_CL_RotateMoves().
BoxFromPoints()
void BoxFromPoints (vec3_t mins, vec3_t maxs, int numpoints, vec_t * point3f)
Definition at line 877 of file mathlib.c.
{
    int i;
    VectorCopy(point3f, mins);
    VectorCopy(point3f, maxs);
    for (i = 1, point3f += 3;i < numpoints;i++, point3f += 3)
    {
        mins[0] = min(mins[0], point3f[0]);maxs[0] = max(maxs[0], point3f[0]);
        mins[1] = min(mins[1], point3f[1]);maxs[1] = max(maxs[1], point3f[1]);
        mins[2] = min(mins[2], point3f[2]);maxs[2] = max(maxs[2], point3f[2]);
    }
}
Referenced by Mod_BSP_FinalizePortals(), Mod_Q1BSP_LoadFaces(), and Mod_VBSP_LoadFaces().
BoxOnPlaneSide()
int BoxOnPlaneSide (const vec3_t emins, const vec3_t emaxs, const struct mplane_s * p)
BoxOnPlaneSide_Separate()
int BoxOnPlaneSide_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, const vec_t dist)
BoxPlaneCornerDistances()
void BoxPlaneCornerDistances (const vec3_t emins, const vec3_t emaxs, const struct mplane_s * p, vec_t * outnear, vec_t * outfar)
BoxPlaneCornerDistances_Separate()
void BoxPlaneCornerDistances_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec_t * outnear, vec_t * outfar)
Definition at line 428 of file mathlib.c.
{
    switch((normal[0] < 0) | ((normal[1] < 0) << 1) | ((normal[2] < 0) << 2))
    {
    default:
    case 0: *outneardist = normal[0] * emaxs[0] + normal[1] * emaxs[1] + normal[2] * emaxs[2];*outfardist = normal[0] * emins[0] + normal[1] * emins[1] + normal[2] * emins[2];break;
    case 1: *outneardist = normal[0] * emins[0] + normal[1] * emaxs[1] + normal[2] * emaxs[2];*outfardist = normal[0] * emaxs[0] + normal[1] * emins[1] + normal[2] * emins[2];break;
    case 2: *outneardist = normal[0] * emaxs[0] + normal[1] * emins[1] + normal[2] * emaxs[2];*outfardist = normal[0] * emins[0] + normal[1] * emaxs[1] + normal[2] * emins[2];break;
    case 3: *outneardist = normal[0] * emins[0] + normal[1] * emins[1] + normal[2] * emaxs[2];*outfardist = normal[0] * emaxs[0] + normal[1] * emaxs[1] + normal[2] * emins[2];break;
    case 4: *outneardist = normal[0] * emaxs[0] + normal[1] * emaxs[1] + normal[2] * emins[2];*outfardist = normal[0] * emins[0] + normal[1] * emins[1] + normal[2] * emaxs[2];break;
    case 5: *outneardist = normal[0] * emins[0] + normal[1] * emaxs[1] + normal[2] * emins[2];*outfardist = normal[0] * emaxs[0] + normal[1] * emins[1] + normal[2] * emaxs[2];break;
    case 6: *outneardist = normal[0] * emaxs[0] + normal[1] * emins[1] + normal[2] * emins[2];*outfardist = normal[0] * emins[0] + normal[1] * emaxs[1] + normal[2] * emaxs[2];break;
    case 7: *outneardist = normal[0] * emins[0] + normal[1] * emins[1] + normal[2] * emins[2];*outfardist = normal[0] * emaxs[0] + normal[1] * emaxs[1] + normal[2] * emaxs[2];break;
    }
}
BoxPlaneCorners()
void BoxPlaneCorners (const vec3_t emins, const vec3_t emaxs, const struct mplane_s * p, vec3_t outnear, vec3_t outfar)
BoxPlaneCorners_Separate()
void BoxPlaneCorners_Separate (const vec3_t emins, const vec3_t emaxs, const vec3_t normal, vec3_t outnear, vec3_t outfar)
Definition at line 390 of file mathlib.c.
{
    switch((normal[0] < 0) | ((normal[1] < 0) << 1) | ((normal[2] < 0) << 2))
    {
    default:
    case 0: outnear[0] = emaxs[0];outnear[1] = emaxs[1];outnear[2] = emaxs[2];outfar[0] = emins[0];outfar[1] = emins[1];outfar[2] = emins[2];break;
    case 1: outnear[0] = emins[0];outnear[1] = emaxs[1];outnear[2] = emaxs[2];outfar[0] = emaxs[0];outfar[1] = emins[1];outfar[2] = emins[2];break;
    case 2: outnear[0] = emaxs[0];outnear[1] = emins[1];outnear[2] = emaxs[2];outfar[0] = emins[0];outfar[1] = emaxs[1];outfar[2] = emins[2];break;
    case 3: outnear[0] = emins[0];outnear[1] = emins[1];outnear[2] = emaxs[2];outfar[0] = emaxs[0];outfar[1] = emaxs[1];outfar[2] = emins[2];break;
    case 4: outnear[0] = emaxs[0];outnear[1] = emaxs[1];outnear[2] = emins[2];outfar[0] = emins[0];outfar[1] = emins[1];outfar[2] = emaxs[2];break;
    case 5: outnear[0] = emins[0];outnear[1] = emaxs[1];outnear[2] = emins[2];outfar[0] = emaxs[0];outfar[1] = emins[1];outfar[2] = emaxs[2];break;
    case 6: outnear[0] = emaxs[0];outnear[1] = emins[1];outnear[2] = emins[2];outfar[0] = emins[0];outfar[1] = emaxs[1];outfar[2] = emaxs[2];break;
    case 7: outnear[0] = emins[0];outnear[1] = emins[1];outnear[2] = emins[2];outfar[0] = emaxs[0];outfar[1] = emaxs[1];outfar[2] = emaxs[2];break;
    }
}
ByteToNormal()
void ByteToNormal (unsigned char num, vec3_t n)
CeilPowerOf2()
unsigned int CeilPowerOf2 (unsigned int value)
returns the smallest integer greater than or equal to "value", or 0 if "value" is too big
Definition at line 292 of file mathlib.c.
{
    unsigned int ceilvalue;
    if (value > (1U << (sizeof(int) * 8 - 1)))
        return 0;
    ceilvalue = 1;
    while (ceilvalue < value)
        ceilvalue <<= 1;
    return ceilvalue;
}
Referenced by Font_LoadSize(), Mod_Q3BSP_LoadLightmaps(), SndSys_Init(), and SndSys_Init().
LoopingFrameNumberFromDouble()
int LoopingFrameNumberFromDouble (double t, int loopframes)
Definition at line 891 of file mathlib.c.
{
    if (loopframes)
        return (int)(t - floor(t/loopframes)*loopframes);
    else
        return (int)t;
}
Referenced by R_GetCurrentTexture().
Math_atov()
int Math_atov (const char * s, prvm_vec3_t out)
Definition at line 856 of file mathlib.c.
{
    int i;
    VectorClear(out);
    if (*s == '\'')
        s++;
    for (i = 0;i < 3;i++)
    {
        while (*s == ' ' || *s == '\t')
            s++;
        out[i] = atof (s);
        if (out[i] == 0 && *s != '-' && *s != '+' && (*s < '0' || *s > '9'))
            break; // not a number
        while (*s && *s != ' ' && *s !='\t' && *s != '\'')
            s++;
        if (*s == '\'')
            break;
    }
    return i;
}
Referenced by R_Shadow_DrawModelShadowMaps(), R_Shadow_PrepareModelShadows(), and VM_stov().
Math_crandomf()
float Math_crandomf (randomseed_t * r)
Definition at line 1059 of file mathlib.c.
{
    // do this with a signed number and double the result, so we make use of all parts of the cow
    long long n = (long long)Math_rand64(r);
    return n * (0.5f / 0x80000000 / 0x80000000);
}
Math_rand64()
unsigned long long Math_rand64 (randomseed_t * r)
Definition at line 1042 of file mathlib.c.
{
    unsigned int o[4];
    mul128(r->s, mul_Lecuyer, o);
    r->s[0] = o[0];
    r->s[1] = o[1];
    r->s[2] = o[2];
    r->s[3] = o[3];
    return ((unsigned long long)o[3] << 32) + o[2];
}
Referenced by Math_crandomf(), Math_randomf(), and Math_randomrangei().
Math_randomf()
float Math_randomf (randomseed_t * r)
Definition at line 1053 of file mathlib.c.
{
    unsigned long long n = Math_rand64(r);
    return n * (0.25f / 0x80000000 / 0x80000000);
}
Referenced by Math_randomrangef().
Math_randomrangef()
float Math_randomrangef (randomseed_t * r, float minf, float maxf)
Definition at line 1066 of file mathlib.c.
{
    return Math_randomf(r) * (maxf - minf) + minf;
}
Math_randomrangei()
int Math_randomrangei (randomseed_t * r, int mini, int maxi)
Definition at line 1071 of file mathlib.c.
{
    unsigned long long n = Math_rand64(r);
    return (int)(((n >> 33) * (maxi - mini) + mini) >> 31);
}
Math_RandomSeed_FromInts()
void Math_RandomSeed_FromInts (randomseed_t * r, unsigned int s0, unsigned int s1, unsigned int s2, unsigned int s3)
Definition at line 1034 of file mathlib.c.
{
    r->s[0] = s0;
    r->s[1] = s1;
    r->s[2] = s2;
    r->s[3] = s3 | 1; // the Lehmer RNG requires that the seed be odd
}
Referenced by R_Shadow_BounceGrid_AssignPhotons_Task().
Math_RandomSeed_Reset()
void Math_RandomSeed_Reset (randomseed_t * r)
Definition at line 1026 of file mathlib.c.
{
    r->s[0] = 1;
    r->s[1] = 0;
    r->s[2] = 0;
    r->s[3] = 0;
}
Mathlib_Init()
void Mathlib_Init (void)
Definition at line 833 of file mathlib.c.
{
    int a;
    // LadyHavoc: setup 1.0f / N table for quick recipricols of integers
    ixtable[0] = 0;
    for (a = 1;a < 4096;a++)
        ixtable[a] = 1.0f / a;
    Math_RandomSeed_UnitTests();
}
Referenced by Host_Init().
Matrix4x4_Print()
void Matrix4x4_Print (const struct matrix4x4_s * in)
print a matrix to the console
NormalToByte()
unsigned char NormalToByte (const vec3_t n)
PlaneClassify()
void PlaneClassify (struct mplane_s * p)
R_ConcatRotations()
void R_ConcatRotations (const float in1[3 *3], const float in2[3 *3], float out[3 *3])
Definition at line 781 of file mathlib.c.
{
    out[0*3+0] = in1[0*3+0] * in2[0*3+0] + in1[0*3+1] * in2[1*3+0] + in1[0*3+2] * in2[2*3+0];
    out[0*3+1] = in1[0*3+0] * in2[0*3+1] + in1[0*3+1] * in2[1*3+1] + in1[0*3+2] * in2[2*3+1];
    out[0*3+2] = in1[0*3+0] * in2[0*3+2] + in1[0*3+1] * in2[1*3+2] + in1[0*3+2] * in2[2*3+2];
    out[1*3+0] = in1[1*3+0] * in2[0*3+0] + in1[1*3+1] * in2[1*3+0] + in1[1*3+2] * in2[2*3+0];
    out[1*3+1] = in1[1*3+0] * in2[0*3+1] + in1[1*3+1] * in2[1*3+1] + in1[1*3+2] * in2[2*3+1];
    out[1*3+2] = in1[1*3+0] * in2[0*3+2] + in1[1*3+1] * in2[1*3+2] + in1[1*3+2] * in2[2*3+2];
    out[2*3+0] = in1[2*3+0] * in2[0*3+0] + in1[2*3+1] * in2[1*3+0] + in1[2*3+2] * in2[2*3+0];
    out[2*3+1] = in1[2*3+0] * in2[0*3+1] + in1[2*3+1] * in2[1*3+1] + in1[2*3+2] * in2[2*3+1];
    out[2*3+2] = in1[2*3+0] * in2[0*3+2] + in1[2*3+1] * in2[1*3+2] + in1[2*3+2] * in2[2*3+2];
}
R_ConcatTransforms()
void R_ConcatTransforms (const float in1[3 *4], const float in2[3 *4], float out[3 *4])
Definition at line 800 of file mathlib.c.
{
    out[0*4+0] = in1[0*4+0] * in2[0*4+0] + in1[0*4+1] * in2[1*4+0] + in1[0*4+2] * in2[2*4+0];
    out[0*4+1] = in1[0*4+0] * in2[0*4+1] + in1[0*4+1] * in2[1*4+1] + in1[0*4+2] * in2[2*4+1];
    out[0*4+2] = in1[0*4+0] * in2[0*4+2] + in1[0*4+1] * in2[1*4+2] + in1[0*4+2] * in2[2*4+2];
    out[0*4+3] = in1[0*4+0] * in2[0*4+3] + in1[0*4+1] * in2[1*4+3] + in1[0*4+2] * in2[2*4+3] + in1[0*4+3];
    out[1*4+0] = in1[1*4+0] * in2[0*4+0] + in1[1*4+1] * in2[1*4+0] + in1[1*4+2] * in2[2*4+0];
    out[1*4+1] = in1[1*4+0] * in2[0*4+1] + in1[1*4+1] * in2[1*4+1] + in1[1*4+2] * in2[2*4+1];
    out[1*4+2] = in1[1*4+0] * in2[0*4+2] + in1[1*4+1] * in2[1*4+2] + in1[1*4+2] * in2[2*4+2];
    out[1*4+3] = in1[1*4+0] * in2[0*4+3] + in1[1*4+1] * in2[1*4+3] + in1[1*4+2] * in2[2*4+3] + in1[1*4+3];
    out[2*4+0] = in1[2*4+0] * in2[0*4+0] + in1[2*4+1] * in2[1*4+0] + in1[2*4+2] * in2[2*4+0];
    out[2*4+1] = in1[2*4+0] * in2[0*4+1] + in1[2*4+1] * in2[1*4+1] + in1[2*4+2] * in2[2*4+1];
    out[2*4+2] = in1[2*4+0] * in2[0*4+2] + in1[2*4+1] * in2[1*4+2] + in1[2*4+2] * in2[2*4+2];
    out[2*4+3] = in1[2*4+0] * in2[0*4+3] + in1[2*4+1] * in2[1*4+3] + in1[2*4+2] * in2[2*4+3] + in1[2*4+3];
}
Referenced by Mod_DARKPLACESMODEL_Load(), Mod_Skeletal_BuildTransforms(), and Mod_ZYMOTICMODEL_Load().
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 816 of file mathlib.c.
{
    vec3_t m1, m2;
    VectorMultiply(mins, mins, m1);
    VectorMultiply(maxs, maxs, m2);
    return sqrt(max(m1[0], m2[0]) + max(m1[1], m2[1]) + max(m1[2], m2[2]));
}
RadiusFromBoundsAndOrigin()
float RadiusFromBoundsAndOrigin (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
Definition at line 824 of file mathlib.c.
{
    vec3_t m1, m2;
    VectorSubtract(mins, origin, m1);VectorMultiply(m1, m1, m1);
    VectorSubtract(maxs, origin, m2);VectorMultiply(m2, m2, m2);
    return sqrt(max(m1[0], m2[0]) + max(m1[1], m2[1]) + max(m1[2], m2[2]));
}
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 258 of file mathlib.c.
{
    float t0, t1;
    float angle, c, s;
    vec3_t vr, vu, vf;
    angle = DEG2RAD(degrees);
    c = cos(angle);
    s = sin(angle);
    VectorCopy(dir, vf);
    VectorVectors(vf, vr, vu);
    t0 = vr[0] *  c + vu[0] * -s;
    t1 = vr[0] *  s + vu[0] *  c;
    dst[0] = (t0 * vr[0] + t1 * vu[0] + vf[0] * vf[0]) * point[0]
           + (t0 * vr[1] + t1 * vu[1] + vf[0] * vf[1]) * point[1]
           + (t0 * vr[2] + t1 * vu[2] + vf[0] * vf[2]) * point[2];
    t0 = vr[1] *  c + vu[1] * -s;
    t1 = vr[1] *  s + vu[1] *  c;
    dst[1] = (t0 * vr[0] + t1 * vu[0] + vf[1] * vf[0]) * point[0]
           + (t0 * vr[1] + t1 * vu[1] + vf[1] * vf[1]) * point[1]
           + (t0 * vr[2] + t1 * vu[2] + vf[1] * vf[2]) * point[2];
    t0 = vr[2] *  c + vu[2] * -s;
    t1 = vr[2] *  s + vu[2] *  c;
    dst[2] = (t0 * vr[0] + t1 * vu[0] + vf[2] * vf[0]) * point[0]
           + (t0 * vr[1] + t1 * vu[1] + vf[2] * vf[1]) * point[1]
           + (t0 * vr[2] + t1 * vu[2] + vf[2] * vf[2]) * point[2];
}
VectorNormalizeLength()
float VectorNormalizeLength (vec3_t v)
returns vector length
Definition at line 763 of file mathlib.c.
{
    float length;
    length = sqrt(DotProduct(v,v));
    if (length)
        VectorScale(v, 1 / length, v);
    return length;
}
Referenced by CL_ClientMovement_Physics_CPM_PM_Aircontrol(), CL_ClientMovement_Physics_PM_AirAccelerate(), CL_ClientMovement_Physics_Swim(), CL_ClientMovement_Physics_Walk(), CL_ParticleEffect_Fallback(), CL_RelinkBeams(), DropPunchAngle(), Matrix4x4_QuakeToDuke3D(), R_Shadow_ComputeShadowCasterCullingPlanes(), SV_AirAccelerate(), and SV_AirMove().
VectorVectors()
void VectorVectors (const vec3_t forward, vec3_t right, vec3_t up)
LadyHavoc: like AngleVectors, but taking a forward vector instead of angles, useful!
Definition at line 199 of file mathlib.c.
{
    // NOTE: this is consistent to AngleVectors applied to AnglesFromVectors
    if (forward[0] == 0 && forward[1] == 0)
    {
        if(forward[2] > 0)
        {
            VectorSet(right, 0, -1, 0);
            VectorSet(up, -1, 0, 0);
        }
        else
        {
            VectorSet(right, 0, -1, 0);
            VectorSet(up, 1, 0, 0);
        }
    }
    else
    {
        right[0] = forward[1];
        right[1] = -forward[0];
        right[2] = 0;
        VectorNormalize(right);
        up[0] = (-forward[2]*forward[0]);
        up[1] = (-forward[2]*forward[1]);
        up[2] = (forward[0]*forward[0] + forward[1]*forward[1]);
        VectorNormalize(up);
    }
}
Referenced by R_DrawParticle_TransparentCallback(), RotatePointAroundVector(), and VM_vectorvectors().
VectorVectorsDouble()
void VectorVectorsDouble (const double * forward, double * right, double * up)
Definition at line 229 of file mathlib.c.
{
    if (forward[0] == 0 && forward[1] == 0)
    {
        if(forward[2] > 0)
        {
            VectorSet(right, 0, -1, 0);
            VectorSet(up, -1, 0, 0);
        }
        else
        {
            VectorSet(right, 0, -1, 0);
            VectorSet(up, 1, 0, 0);
        }
    }
    else
    {
        right[0] = forward[1];
        right[1] = -forward[0];
        right[2] = 0;
        VectorNormalize(right);
        up[0] = (-forward[2]*forward[0]);
        up[1] = (-forward[2]*forward[1]);
        up[2] = (forward[0]*forward[0] + forward[1]*forward[1]);
        VectorNormalize(up);
    }
}
Variable Documentation
m_bytenormals
float m_bytenormals[NUMVERTEXNORMALS][3] extern
Definition at line 31 of file mathlib.c.
{
{-0.525731f, 0.000000f, 0.850651f}, {-0.442863f, 0.238856f, 0.864188f},
{-0.295242f, 0.000000f, 0.955423f}, {-0.309017f, 0.500000f, 0.809017f},
{-0.162460f, 0.262866f, 0.951056f}, {0.000000f, 0.000000f, 1.000000f},
{0.000000f, 0.850651f, 0.525731f}, {-0.147621f, 0.716567f, 0.681718f},
{0.147621f, 0.716567f, 0.681718f}, {0.000000f, 0.525731f, 0.850651f},
{0.309017f, 0.500000f, 0.809017f}, {0.525731f, 0.000000f, 0.850651f},
{0.295242f, 0.000000f, 0.955423f}, {0.442863f, 0.238856f, 0.864188f},
{0.162460f, 0.262866f, 0.951056f}, {-0.681718f, 0.147621f, 0.716567f},
{-0.809017f, 0.309017f, 0.500000f}, {-0.587785f, 0.425325f, 0.688191f},
{-0.850651f, 0.525731f, 0.000000f}, {-0.864188f, 0.442863f, 0.238856f},
{-0.716567f, 0.681718f, 0.147621f}, {-0.688191f, 0.587785f, 0.425325f},
{-0.500000f, 0.809017f, 0.309017f}, {-0.238856f, 0.864188f, 0.442863f},
{-0.425325f, 0.688191f, 0.587785f}, {-0.716567f, 0.681718f, -0.147621f},
{-0.500000f, 0.809017f, -0.309017f}, {-0.525731f, 0.850651f, 0.000000f},
{0.000000f, 0.850651f, -0.525731f}, {-0.238856f, 0.864188f, -0.442863f},
{0.000000f, 0.955423f, -0.295242f}, {-0.262866f, 0.951056f, -0.162460f},
{0.000000f, 1.000000f, 0.000000f}, {0.000000f, 0.955423f, 0.295242f},
{-0.262866f, 0.951056f, 0.162460f}, {0.238856f, 0.864188f, 0.442863f},
{0.262866f, 0.951056f, 0.162460f}, {0.500000f, 0.809017f, 0.309017f},
{0.238856f, 0.864188f, -0.442863f}, {0.262866f, 0.951056f, -0.162460f},
{0.500000f, 0.809017f, -0.309017f}, {0.850651f, 0.525731f, 0.000000f},
{0.716567f, 0.681718f, 0.147621f}, {0.716567f, 0.681718f, -0.147621f},
{0.525731f, 0.850651f, 0.000000f}, {0.425325f, 0.688191f, 0.587785f},
{0.864188f, 0.442863f, 0.238856f}, {0.688191f, 0.587785f, 0.425325f},
{0.809017f, 0.309017f, 0.500000f}, {0.681718f, 0.147621f, 0.716567f},
{0.587785f, 0.425325f, 0.688191f}, {0.955423f, 0.295242f, 0.000000f},
{1.000000f, 0.000000f, 0.000000f}, {0.951056f, 0.162460f, 0.262866f},
{0.850651f, -0.525731f, 0.000000f}, {0.955423f, -0.295242f, 0.000000f},
{0.864188f, -0.442863f, 0.238856f}, {0.951056f, -0.162460f, 0.262866f},
{0.809017f, -0.309017f, 0.500000f}, {0.681718f, -0.147621f, 0.716567f},
{0.850651f, 0.000000f, 0.525731f}, {0.864188f, 0.442863f, -0.238856f},
{0.809017f, 0.309017f, -0.500000f}, {0.951056f, 0.162460f, -0.262866f},
{0.525731f, 0.000000f, -0.850651f}, {0.681718f, 0.147621f, -0.716567f},
{0.681718f, -0.147621f, -0.716567f}, {0.850651f, 0.000000f, -0.525731f},
{0.809017f, -0.309017f, -0.500000f}, {0.864188f, -0.442863f, -0.238856f},
{0.951056f, -0.162460f, -0.262866f}, {0.147621f, 0.716567f, -0.681718f},
{0.309017f, 0.500000f, -0.809017f}, {0.425325f, 0.688191f, -0.587785f},
{0.442863f, 0.238856f, -0.864188f}, {0.587785f, 0.425325f, -0.688191f},
{0.688191f, 0.587785f, -0.425325f}, {-0.147621f, 0.716567f, -0.681718f},
{-0.309017f, 0.500000f, -0.809017f}, {0.000000f, 0.525731f, -0.850651f},
{-0.525731f, 0.000000f, -0.850651f}, {-0.442863f, 0.238856f, -0.864188f},
{-0.295242f, 0.000000f, -0.955423f}, {-0.162460f, 0.262866f, -0.951056f},
{0.000000f, 0.000000f, -1.000000f}, {0.295242f, 0.000000f, -0.955423f},
{0.162460f, 0.262866f, -0.951056f}, {-0.442863f, -0.238856f, -0.864188f},
{-0.309017f, -0.500000f, -0.809017f}, {-0.162460f, -0.262866f, -0.951056f},
{0.000000f, -0.850651f, -0.525731f}, {-0.147621f, -0.716567f, -0.681718f},
{0.147621f, -0.716567f, -0.681718f}, {0.000000f, -0.525731f, -0.850651f},
{0.309017f, -0.500000f, -0.809017f}, {0.442863f, -0.238856f, -0.864188f},
{0.162460f, -0.262866f, -0.951056f}, {0.238856f, -0.864188f, -0.442863f},
{0.500000f, -0.809017f, -0.309017f}, {0.425325f, -0.688191f, -0.587785f},
{0.716567f, -0.681718f, -0.147621f}, {0.688191f, -0.587785f, -0.425325f},
{0.587785f, -0.425325f, -0.688191f}, {0.000000f, -0.955423f, -0.295242f},
{0.000000f, -1.000000f, 0.000000f}, {0.262866f, -0.951056f, -0.162460f},
{0.000000f, -0.850651f, 0.525731f}, {0.000000f, -0.955423f, 0.295242f},
{0.238856f, -0.864188f, 0.442863f}, {0.262866f, -0.951056f, 0.162460f},
{0.500000f, -0.809017f, 0.309017f}, {0.716567f, -0.681718f, 0.147621f},
{0.525731f, -0.850651f, 0.000000f}, {-0.238856f, -0.864188f, -0.442863f},
{-0.500000f, -0.809017f, -0.309017f}, {-0.262866f, -0.951056f, -0.162460f},
{-0.850651f, -0.525731f, 0.000000f}, {-0.716567f, -0.681718f, -0.147621f},
{-0.716567f, -0.681718f, 0.147621f}, {-0.525731f, -0.850651f, 0.000000f},
{-0.500000f, -0.809017f, 0.309017f}, {-0.238856f, -0.864188f, 0.442863f},
{-0.262866f, -0.951056f, 0.162460f}, {-0.864188f, -0.442863f, 0.238856f},
{-0.809017f, -0.309017f, 0.500000f}, {-0.688191f, -0.587785f, 0.425325f},
{-0.681718f, -0.147621f, 0.716567f}, {-0.442863f, -0.238856f, 0.864188f},
{-0.587785f, -0.425325f, 0.688191f}, {-0.309017f, -0.500000f, 0.809017f},
{-0.147621f, -0.716567f, 0.681718f}, {-0.425325f, -0.688191f, 0.587785f},
{-0.162460f, -0.262866f, 0.951056f}, {0.442863f, -0.238856f, 0.864188f},
{0.162460f, -0.262866f, 0.951056f}, {0.309017f, -0.500000f, 0.809017f},
{0.147621f, -0.716567f, 0.681718f}, {0.000000f, -0.525731f, 0.850651f},
{0.425325f, -0.688191f, 0.587785f}, {0.587785f, -0.425325f, 0.688191f},
{0.688191f, -0.587785f, 0.425325f}, {-0.955423f, 0.295242f, 0.000000f},
{-0.951056f, 0.162460f, 0.262866f}, {-1.000000f, 0.000000f, 0.000000f},
{-0.850651f, 0.000000f, 0.525731f}, {-0.955423f, -0.295242f, 0.000000f},
{-0.951056f, -0.162460f, 0.262866f}, {-0.864188f, 0.442863f, -0.238856f},
{-0.951056f, 0.162460f, -0.262866f}, {-0.809017f, 0.309017f, -0.500000f},
{-0.864188f, -0.442863f, -0.238856f}, {-0.951056f, -0.162460f, -0.262866f},
{-0.809017f, -0.309017f, -0.500000f}, {-0.681718f, 0.147621f, -0.716567f},
{-0.681718f, -0.147621f, -0.716567f}, {-0.850651f, 0.000000f, -0.525731f},
{-0.688191f, 0.587785f, -0.425325f}, {-0.587785f, 0.425325f, -0.688191f},
{-0.425325f, 0.688191f, -0.587785f}, {-0.425325f, -0.688191f, -0.587785f},
{-0.587785f, -0.425325f, -0.688191f}, {-0.688191f, -0.587785f, -0.425325f},
};
Referenced by CL_EntityParticles(), and Mod_MDL_AnimateVertices().
vec3_origin
vec3_t vec3_origin extern
Definition at line 26 of file mathlib.c.
{0,0,0};
Referenced by CDAudio_Play_byName(), CL_LinkNetworkEntity(), CL_ParsePointParticles1(), CL_ParseTempEntity(), CL_ParseTrailParticles(), CL_SelectTraceLine(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), CL_UpdateNetworkEntityTrail(), Collision_Cache_ClipLineToGenericEntitySurfaces(), Collision_ClipLineToGenericEntity(), dpvsimpledecode_open(), jam_open(), libavw_decodeframe(), R_DrawTextureSurfaceList_GL20(), R_Shadow_EditLights_Spawn_f(), R_Shadow_LoadLightsFile(), S_LocalSoundEx(), SV_UnstickEntityReturnOffset(), VM_CL_setmodel(), VM_CL_setmodelindex(), VM_CL_te_explosion(), VM_CL_te_explosionquad(), VM_CL_te_gunshot(), VM_CL_te_gunshotquad(), VM_CL_te_knightspike(), VM_CL_te_lavasplash(), VM_CL_te_plasmaburn(), VM_CL_te_smallflash(), VM_CL_te_spike(), VM_CL_te_spikequad(), VM_CL_te_superspike(), VM_CL_te_superspikequad(), VM_CL_te_tarexplosion(), VM_CL_te_teleport(), VM_CL_te_wizspike(), VM_SV_setmodel(), and VM_SV_setmodelindex().