DarkPlaces: matrixlib.h File Reference
matrixlib.h File Reference
#include "qtypes.h"
Data Structures
struct matrix4x4_t
Functions
void Matrix4x4_Copy (matrix4x4_t *out, const matrix4x4_t *in)
void Matrix4x4_CopyRotateOnly (matrix4x4_t *out, const matrix4x4_t *in)
void Matrix4x4_CopyTranslateOnly (matrix4x4_t *out, const matrix4x4_t *in)
void Matrix4x4_Concat (matrix4x4_t *out, const matrix4x4_t *in1, const matrix4x4_t *in2)
void Matrix4x4_Transpose (matrix4x4_t *out, const matrix4x4_t *in1)
int Matrix4x4_Invert_Full (matrix4x4_t *out, const matrix4x4_t *in1)
void Matrix4x4_Invert_Simple (matrix4x4_t *out, const matrix4x4_t *in1)
void Matrix4x4_Interpolate (matrix4x4_t *out, matrix4x4_t *in1, matrix4x4_t *in2, double frac)
void Matrix4x4_Clear (matrix4x4_t *out)
void Matrix4x4_Accumulate (matrix4x4_t *out, matrix4x4_t *in, double weight)
void Matrix4x4_Normalize (matrix4x4_t *out, matrix4x4_t *in1)
void Matrix4x4_Normalize3 (matrix4x4_t *out, matrix4x4_t *in1)
void Matrix4x4_Reflect (matrix4x4_t *out, double normalx, double normaly, double normalz, double dist, double axisscale)
void Matrix4x4_CreateIdentity (matrix4x4_t *out)
void Matrix4x4_CreateTranslate (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_CreateRotate (matrix4x4_t *out, double angle, double x, double y, double z)
void Matrix4x4_CreateScale (matrix4x4_t *out, double x)
void Matrix4x4_CreateScale3 (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_CreateFromQuakeEntity (matrix4x4_t *out, double x, double y, double z, double pitch, double yaw, double roll, double scale)
void Matrix4x4_QuakeToDuke3D (const matrix4x4_t *in, matrix4x4_t *out, double maxShearAngle)
void Matrix4x4_ToVectors (const matrix4x4_t *in, vec_t vx[3], vec_t vy[3], vec_t vz[3], vec_t t[3])
void Matrix4x4_FromVectors (matrix4x4_t *out, const vec_t vx[3], const vec_t vy[3], const vec_t vz[3], const vec_t t[3])
void Matrix4x4_ToArrayDoubleGL (const matrix4x4_t *in, double out[16])
void Matrix4x4_FromArrayDoubleGL (matrix4x4_t *out, const double in[16])
void Matrix4x4_ToArrayDoubleD3D (const matrix4x4_t *in, double out[16])
void Matrix4x4_FromArrayDoubleD3D (matrix4x4_t *out, const double in[4][4])
void Matrix4x4_ToArrayFloatGL (const matrix4x4_t *in, float out[16])
void Matrix4x4_FromArrayFloatGL (matrix4x4_t *out, const float in[16])
void Matrix4x4_ToArrayFloatD3D (const matrix4x4_t *in, float out[16])
void Matrix4x4_FromArrayFloatD3D (matrix4x4_t *out, const float in[16])
void Matrix4x4_ToArray12FloatGL (const matrix4x4_t *in, float out[4][3])
void Matrix4x4_FromArray12FloatGL (matrix4x4_t *out, const float in[12])
void Matrix4x4_ToArray12FloatD3D (const matrix4x4_t *in, float out[12])
void Matrix4x4_FromArray12FloatD3D (matrix4x4_t *out, const float in[12])
void Matrix4x4_FromOriginQuat (matrix4x4_t *m, double ox, double oy, double oz, double x, double y, double z, double w)
void Matrix4x4_ToOrigin3Quat4Float (const matrix4x4_t *m, float *origin, float *quat)
void Matrix4x4_FromDoom3Joint (matrix4x4_t *m, double ox, double oy, double oz, double x, double y, double z)
void Matrix4x4_FromBonePose7s (matrix4x4_t *m, float originscale, const short *pose7s)
void Matrix4x4_ToBonePose7s (const matrix4x4_t *m, float origininvscale, short *pose7s)
void Matrix4x4_Blend (matrix4x4_t *out, const matrix4x4_t *in1, const matrix4x4_t *in2, double blend)
void Matrix4x4_Transform (const matrix4x4_t *in, const vec_t v[3], vec_t out[3])
void Matrix4x4_Transform4 (const matrix4x4_t *in, const vec_t v[4], vec_t out[4])
void Matrix4x4_Transform3x3 (const matrix4x4_t *in, const vec_t v[3], vec_t out[3])
void Matrix4x4_TransformPositivePlane (const matrix4x4_t *in, vec_t x, vec_t y, vec_t z, vec_t d, vec_t *o)
void Matrix4x4_TransformStandardPlane (const matrix4x4_t *in, vec_t x, vec_t y, vec_t z, vec_t d, vec_t *o)
void Matrix4x4_ConcatTranslate (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_ConcatRotate (matrix4x4_t *out, double angle, double x, double y, double z)
void Matrix4x4_ConcatScale (matrix4x4_t *out, double x)
void Matrix4x4_ConcatScale3 (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_OriginFromMatrix (const matrix4x4_t *in, vec_t *out)
double Matrix4x4_ScaleFromMatrix (const matrix4x4_t *in)
void Matrix4x4_SetOrigin (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_AdjustOrigin (matrix4x4_t *out, double x, double y, double z)
void Matrix4x4_Scale (matrix4x4_t *out, double rotatescale, double originscale)
void Matrix4x4_Abs (matrix4x4_t *out)
Variables
const matrix4x4_t identitymatrix
Function Documentation
Matrix4x4_Abs()
void Matrix4x4_Abs (matrix4x4_t * out)
Definition at line 1859 of file matrixlib.c.
{
    out->m[0][0] = fabs(out->m[0][0]);
    out->m[0][1] = fabs(out->m[0][1]);
    out->m[0][2] = fabs(out->m[0][2]);
    out->m[1][0] = fabs(out->m[1][0]);
    out->m[1][1] = fabs(out->m[1][1]);
    out->m[1][2] = fabs(out->m[1][2]);
    out->m[2][0] = fabs(out->m[2][0]);
    out->m[2][1] = fabs(out->m[2][1]);
    out->m[2][2] = fabs(out->m[2][2]);
}
Referenced by R_Shadow_DrawLight(), and R_Shadow_DrawLightShadowMaps().
Matrix4x4_Accumulate()
void Matrix4x4_Accumulate (matrix4x4_t * out, matrix4x4_t * in, double weight)
Definition at line 491 of file matrixlib.c.
{
    int i, j;
    for (i = 0;i < 4;i++)
        for (j = 0;j < 4;j++)
            out->m[i][j] += in->m[i][j] * weight;
}
Referenced by Mod_Alias_GetExtendedTagInfoForIndex(), Mod_Alias_GetTagMatrix(), VM_CL_skel_build(), and VM_SV_skel_build().
Matrix4x4_AdjustOrigin()
void Matrix4x4_AdjustOrigin (matrix4x4_t * out, double x, double y, double z)
Definition at line 1824 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[3][0] += x;
    out->m[3][1] += y;
    out->m[3][2] += z;
#else
    out->m[0][3] += x;
    out->m[1][3] += y;
    out->m[2][3] += z;
#endif
}
Referenced by R_Shadow_DrawModelShadowMaps(), and V_CalcIntermissionRefdef().
Matrix4x4_Blend()
void Matrix4x4_Blend (matrix4x4_t * out, const matrix4x4_t * in1, const matrix4x4_t * in2, double blend)
Definition at line 1635 of file matrixlib.c.
{
    double iblend = 1 - blend;
    out->m[0][0] = in1->m[0][0] * iblend + in2->m[0][0] * blend;
    out->m[0][1] = in1->m[0][1] * iblend + in2->m[0][1] * blend;
    out->m[0][2] = in1->m[0][2] * iblend + in2->m[0][2] * blend;
    out->m[0][3] = in1->m[0][3] * iblend + in2->m[0][3] * blend;
    out->m[1][0] = in1->m[1][0] * iblend + in2->m[1][0] * blend;
    out->m[1][1] = in1->m[1][1] * iblend + in2->m[1][1] * blend;
    out->m[1][2] = in1->m[1][2] * iblend + in2->m[1][2] * blend;
    out->m[1][3] = in1->m[1][3] * iblend + in2->m[1][3] * blend;
    out->m[2][0] = in1->m[2][0] * iblend + in2->m[2][0] * blend;
    out->m[2][1] = in1->m[2][1] * iblend + in2->m[2][1] * blend;
    out->m[2][2] = in1->m[2][2] * iblend + in2->m[2][2] * blend;
    out->m[2][3] = in1->m[2][3] * iblend + in2->m[2][3] * blend;
    out->m[3][0] = in1->m[3][0] * iblend + in2->m[3][0] * blend;
    out->m[3][1] = in1->m[3][1] * iblend + in2->m[3][1] * blend;
    out->m[3][2] = in1->m[3][2] * iblend + in2->m[3][2] * blend;
    out->m[3][3] = in1->m[3][3] * iblend + in2->m[3][3] * blend;
}
Matrix4x4_Clear()
void Matrix4x4_Clear (matrix4x4_t * out)
Definition at line 483 of file matrixlib.c.
{
    int i, j;
    for (i = 0;i < 4;i++)
        for (j = 0;j < 4;j++)
            out->m[i][j] = 0;
}
Referenced by Mod_Alias_GetExtendedTagInfoForIndex(), and Mod_Alias_GetTagMatrix().
Matrix4x4_Concat()
void Matrix4x4_Concat (matrix4x4_t * out, const matrix4x4_t * in1, const matrix4x4_t * in2)
Definition at line 83 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in1->m[0][0] * in2->m[0][0] + in1->m[1][0] * in2->m[0][1] + in1->m[2][0] * in2->m[0][2] + in1->m[3][0] * in2->m[0][3];
    out->m[1][0] = in1->m[0][0] * in2->m[1][0] + in1->m[1][0] * in2->m[1][1] + in1->m[2][0] * in2->m[1][2] + in1->m[3][0] * in2->m[1][3];
    out->m[2][0] = in1->m[0][0] * in2->m[2][0] + in1->m[1][0] * in2->m[2][1] + in1->m[2][0] * in2->m[2][2] + in1->m[3][0] * in2->m[2][3];
    out->m[3][0] = in1->m[0][0] * in2->m[3][0] + in1->m[1][0] * in2->m[3][1] + in1->m[2][0] * in2->m[3][2] + in1->m[3][0] * in2->m[3][3];
    out->m[0][1] = in1->m[0][1] * in2->m[0][0] + in1->m[1][1] * in2->m[0][1] + in1->m[2][1] * in2->m[0][2] + in1->m[3][1] * in2->m[0][3];
    out->m[1][1] = in1->m[0][1] * in2->m[1][0] + in1->m[1][1] * in2->m[1][1] + in1->m[2][1] * in2->m[1][2] + in1->m[3][1] * in2->m[1][3];
    out->m[2][1] = in1->m[0][1] * in2->m[2][0] + in1->m[1][1] * in2->m[2][1] + in1->m[2][1] * in2->m[2][2] + in1->m[3][1] * in2->m[2][3];
    out->m[3][1] = in1->m[0][1] * in2->m[3][0] + in1->m[1][1] * in2->m[3][1] + in1->m[2][1] * in2->m[3][2] + in1->m[3][1] * in2->m[3][3];
    out->m[0][2] = in1->m[0][2] * in2->m[0][0] + in1->m[1][2] * in2->m[0][1] + in1->m[2][2] * in2->m[0][2] + in1->m[3][2] * in2->m[0][3];
    out->m[1][2] = in1->m[0][2] * in2->m[1][0] + in1->m[1][2] * in2->m[1][1] + in1->m[2][2] * in2->m[1][2] + in1->m[3][2] * in2->m[1][3];
    out->m[2][2] = in1->m[0][2] * in2->m[2][0] + in1->m[1][2] * in2->m[2][1] + in1->m[2][2] * in2->m[2][2] + in1->m[3][2] * in2->m[2][3];
    out->m[3][2] = in1->m[0][2] * in2->m[3][0] + in1->m[1][2] * in2->m[3][1] + in1->m[2][2] * in2->m[3][2] + in1->m[3][2] * in2->m[3][3];
    out->m[0][3] = in1->m[0][3] * in2->m[0][0] + in1->m[1][3] * in2->m[0][1] + in1->m[2][3] * in2->m[0][2] + in1->m[3][3] * in2->m[0][3];
    out->m[1][3] = in1->m[0][3] * in2->m[1][0] + in1->m[1][3] * in2->m[1][1] + in1->m[2][3] * in2->m[1][2] + in1->m[3][3] * in2->m[1][3];
    out->m[2][3] = in1->m[0][3] * in2->m[2][0] + in1->m[1][3] * in2->m[2][1] + in1->m[2][3] * in2->m[2][2] + in1->m[3][3] * in2->m[2][3];
    out->m[3][3] = in1->m[0][3] * in2->m[3][0] + in1->m[1][3] * in2->m[3][1] + in1->m[2][3] * in2->m[3][2] + in1->m[3][3] * in2->m[3][3];
#else
    out->m[0][0] = in1->m[0][0] * in2->m[0][0] + in1->m[0][1] * in2->m[1][0] + in1->m[0][2] * in2->m[2][0] + in1->m[0][3] * in2->m[3][0];
    out->m[0][1] = in1->m[0][0] * in2->m[0][1] + in1->m[0][1] * in2->m[1][1] + in1->m[0][2] * in2->m[2][1] + in1->m[0][3] * in2->m[3][1];
    out->m[0][2] = in1->m[0][0] * in2->m[0][2] + in1->m[0][1] * in2->m[1][2] + in1->m[0][2] * in2->m[2][2] + in1->m[0][3] * in2->m[3][2];
    out->m[0][3] = in1->m[0][0] * in2->m[0][3] + in1->m[0][1] * in2->m[1][3] + in1->m[0][2] * in2->m[2][3] + in1->m[0][3] * in2->m[3][3];
    out->m[1][0] = in1->m[1][0] * in2->m[0][0] + in1->m[1][1] * in2->m[1][0] + in1->m[1][2] * in2->m[2][0] + in1->m[1][3] * in2->m[3][0];
    out->m[1][1] = in1->m[1][0] * in2->m[0][1] + in1->m[1][1] * in2->m[1][1] + in1->m[1][2] * in2->m[2][1] + in1->m[1][3] * in2->m[3][1];
    out->m[1][2] = in1->m[1][0] * in2->m[0][2] + in1->m[1][1] * in2->m[1][2] + in1->m[1][2] * in2->m[2][2] + in1->m[1][3] * in2->m[3][2];
    out->m[1][3] = in1->m[1][0] * in2->m[0][3] + in1->m[1][1] * in2->m[1][3] + in1->m[1][2] * in2->m[2][3] + in1->m[1][3] * in2->m[3][3];
    out->m[2][0] = in1->m[2][0] * in2->m[0][0] + in1->m[2][1] * in2->m[1][0] + in1->m[2][2] * in2->m[2][0] + in1->m[2][3] * in2->m[3][0];
    out->m[2][1] = in1->m[2][0] * in2->m[0][1] + in1->m[2][1] * in2->m[1][1] + in1->m[2][2] * in2->m[2][1] + in1->m[2][3] * in2->m[3][1];
    out->m[2][2] = in1->m[2][0] * in2->m[0][2] + in1->m[2][1] * in2->m[1][2] + in1->m[2][2] * in2->m[2][2] + in1->m[2][3] * in2->m[3][2];
    out->m[2][3] = in1->m[2][0] * in2->m[0][3] + in1->m[2][1] * in2->m[1][3] + in1->m[2][2] * in2->m[2][3] + in1->m[2][3] * in2->m[3][3];
    out->m[3][0] = in1->m[3][0] * in2->m[0][0] + in1->m[3][1] * in2->m[1][0] + in1->m[3][2] * in2->m[2][0] + in1->m[3][3] * in2->m[3][0];
    out->m[3][1] = in1->m[3][0] * in2->m[0][1] + in1->m[3][1] * in2->m[1][1] + in1->m[3][2] * in2->m[2][1] + in1->m[3][3] * in2->m[3][1];
    out->m[3][2] = in1->m[3][0] * in2->m[0][2] + in1->m[3][1] * in2->m[1][2] + in1->m[3][2] * in2->m[2][2] + in1->m[3][3] * in2->m[3][2];
    out->m[3][3] = in1->m[3][0] * in2->m[0][3] + in1->m[3][1] * in2->m[1][3] + in1->m[3][2] * in2->m[2][3] + in1->m[3][3] * in2->m[3][3];
#endif
}
Referenced by CL_AddQWCTFFlagModel(), CL_GetTagMatrix(), CL_UpdateNetworkEntity(), CL_VM_TransformView(), CSQC_R_RecalcView(), Matrix4x4_ConcatRotate(), Matrix4x4_ConcatScale(), Matrix4x4_ConcatScale3(), Matrix4x4_ConcatTranslate(), Mod_Alias_GetTagMatrix(), Mod_BuildBaseBonePoses(), Mod_INTERQUAKEMODEL_Load(), Mod_PSKMODEL_Load(), R_EntityMatrix(), R_RenderView(), R_SetupShader_DeferredLight(), R_SetupShader_Surface(), R_Shadow_DrawModelShadowMaps(), R_Shadow_DrawWorldLight(), R_Shadow_SetupEntityLight(), R_tcMod_ApplyToMatrix(), R_Viewport_InitCubeSideView(), R_Viewport_InitOrtho3D(), R_Viewport_InitPerspective(), R_Viewport_InitPerspectiveInfinite(), R_Viewport_InitRectSideView(), S_Update(), SV_GetTagMatrix(), V_CalcRefdefUsing(), V_MakeViewIsometric(), VM_CL_skel_get_boneabs(), VM_CL_skel_mul_bone(), VM_CL_skel_mul_bones(), VM_SV_skel_get_boneabs(), VM_SV_skel_mul_bone(), and VM_SV_skel_mul_bones().
Matrix4x4_ConcatRotate()
void Matrix4x4_ConcatRotate (matrix4x4_t * out, double angle, double x, double y, double z)
Definition at line 1766 of file matrixlib.c.
{
    matrix4x4_t base, temp;
    base = *out;
    Matrix4x4_CreateRotate(&temp, angle, x, y, z);
    Matrix4x4_Concat(out, &base, &temp);
}
Referenced by R_tcMod_ApplyToMatrix(), R_Viewport_InitOrtho3D(), R_Viewport_InitPerspective(), and R_Viewport_InitPerspectiveInfinite().
Matrix4x4_ConcatScale()
void Matrix4x4_ConcatScale (matrix4x4_t * out, double x)
Definition at line 1775 of file matrixlib.c.
{
    matrix4x4_t base, temp;
    base = *out;
    Matrix4x4_CreateScale(&temp, x);
    Matrix4x4_Concat(out, &base, &temp);
}
Referenced by CSQC_R_RecalcView(), V_CalcIntermissionRefdef(), and V_CalcRefdefUsing().
Matrix4x4_ConcatScale3()
void Matrix4x4_ConcatScale3 (matrix4x4_t * out, double x, double y, double z)
Definition at line 1784 of file matrixlib.c.
{
    matrix4x4_t base, temp;
    base = *out;
    Matrix4x4_CreateScale3(&temp, x, y, z);
    Matrix4x4_Concat(out, &base, &temp);
}
Referenced by R_Water_ProcessPlanes().
Matrix4x4_ConcatTranslate()
void Matrix4x4_ConcatTranslate (matrix4x4_t * out, double x, double y, double z)
Definition at line 1757 of file matrixlib.c.
{
    matrix4x4_t base, temp;
    base = *out;
    Matrix4x4_CreateTranslate(&temp, x, y, z);
    Matrix4x4_Concat(out, &base, &temp);
}
Referenced by Mod_Q3BSP_LoadLightGrid(), and R_tcMod_ApplyToMatrix().
Matrix4x4_Copy()
void Matrix4x4_Copy (matrix4x4_t * out, const matrix4x4_t * in)
Definition at line 19 of file matrixlib.c.
{
    *out = *in;
}
Referenced by CL_GetTagMatrix(), CSQC_R_RecalcView(), SV_GetTagMatrix(), V_CalcIntermissionRefdef(), and V_CalcRefdefUsing().
Matrix4x4_CopyRotateOnly()
void Matrix4x4_CopyRotateOnly (matrix4x4_t * out, const matrix4x4_t * in)
Definition at line 24 of file matrixlib.c.
{
    out->m[0][0] = in->m[0][0];
    out->m[0][1] = in->m[0][1];
    out->m[0][2] = in->m[0][2];
    out->m[0][3] = 0.0f;
    out->m[1][0] = in->m[1][0];
    out->m[1][1] = in->m[1][1];
    out->m[1][2] = in->m[1][2];
    out->m[1][3] = 0.0f;
    out->m[2][0] = in->m[2][0];
    out->m[2][1] = in->m[2][1];
    out->m[2][2] = in->m[2][2];
    out->m[2][3] = 0.0f;
    out->m[3][0] = 0.0f;
    out->m[3][1] = 0.0f;
    out->m[3][2] = 0.0f;
    out->m[3][3] = 1.0f;
}
Matrix4x4_CopyTranslateOnly()
void Matrix4x4_CopyTranslateOnly (matrix4x4_t * out, const matrix4x4_t * in)
Definition at line 44 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = 1.0f;
    out->m[1][0] = 0.0f;
    out->m[2][0] = 0.0f;
    out->m[3][0] = in->m[0][3];
    out->m[0][1] = 0.0f;
    out->m[1][1] = 1.0f;
    out->m[2][1] = 0.0f;
    out->m[3][1] = in->m[1][3];
    out->m[0][2] = 0.0f;
    out->m[1][2] = 0.0f;
    out->m[2][2] = 1.0f;
    out->m[3][2] = in->m[2][3];
    out->m[0][3] = 0.0f;
    out->m[1][3] = 0.0f;
    out->m[2][3] = 0.0f;
    out->m[3][3] = 1.0f;
#else
    out->m[0][0] = 1.0f;
    out->m[0][1] = 0.0f;
    out->m[0][2] = 0.0f;
    out->m[0][3] = in->m[0][3];
    out->m[1][0] = 0.0f;
    out->m[1][1] = 1.0f;
    out->m[1][2] = 0.0f;
    out->m[1][3] = in->m[1][3];
    out->m[2][0] = 0.0f;
    out->m[2][1] = 0.0f;
    out->m[2][2] = 1.0f;
    out->m[2][3] = in->m[2][3];
    out->m[3][0] = 0.0f;
    out->m[3][1] = 0.0f;
    out->m[3][2] = 0.0f;
    out->m[3][3] = 1.0f;
#endif
}
Matrix4x4_CreateFromQuakeEntity()
void Matrix4x4_CreateFromQuakeEntity (matrix4x4_t * out, double x, double y, double z, double pitch, double yaw, double roll, double scale)
Definition at line 715 of file matrixlib.c.
{
    double angle, sr, sp, sy, cr, cp, cy;
    if (roll)
    {
        angle = yaw * (M_PI*2 / 360);
        sy = sin(angle);
        cy = cos(angle);
        angle = pitch * (M_PI*2 / 360);
        sp = sin(angle);
        cp = cos(angle);
        angle = roll * (M_PI*2 / 360);
        sr = sin(angle);
        cr = cos(angle);
#ifdef MATRIX4x4_OPENGLORIENTATION
        out->m[0][0] = (cp*cy) * scale;
        out->m[1][0] = (sr*sp*cy+cr*-sy) * scale;
        out->m[2][0] = (cr*sp*cy+-sr*-sy) * scale;
        out->m[3][0] = x;
        out->m[0][1] = (cp*sy) * scale;
        out->m[1][1] = (sr*sp*sy+cr*cy) * scale;
        out->m[2][1] = (cr*sp*sy+-sr*cy) * scale;
        out->m[3][1] = y;
        out->m[0][2] = (-sp) * scale;
        out->m[1][2] = (sr*cp) * scale;
        out->m[2][2] = (cr*cp) * scale;
        out->m[3][2] = z;
        out->m[0][3] = 0;
        out->m[1][3] = 0;
        out->m[2][3] = 0;
        out->m[3][3] = 1;
#else
        out->m[0][0] = (cp*cy) * scale;
        out->m[0][1] = (sr*sp*cy+cr*-sy) * scale;
        out->m[0][2] = (cr*sp*cy+-sr*-sy) * scale;
        out->m[0][3] = x;
        out->m[1][0] = (cp*sy) * scale;
        out->m[1][1] = (sr*sp*sy+cr*cy) * scale;
        out->m[1][2] = (cr*sp*sy+-sr*cy) * scale;
        out->m[1][3] = y;
        out->m[2][0] = (-sp) * scale;
        out->m[2][1] = (sr*cp) * scale;
        out->m[2][2] = (cr*cp) * scale;
        out->m[2][3] = z;
        out->m[3][0] = 0;
        out->m[3][1] = 0;
        out->m[3][2] = 0;
        out->m[3][3] = 1;
#endif
    }
    else if (pitch)
    {
        angle = yaw * (M_PI*2 / 360);
        sy = sin(angle);
        cy = cos(angle);
        angle = pitch * (M_PI*2 / 360);
        sp = sin(angle);
        cp = cos(angle);
#ifdef MATRIX4x4_OPENGLORIENTATION
        out->m[0][0] = (cp*cy) * scale;
        out->m[1][0] = (-sy) * scale;
        out->m[2][0] = (sp*cy) * scale;
        out->m[3][0] = x;
        out->m[0][1] = (cp*sy) * scale;
        out->m[1][1] = (cy) * scale;
        out->m[2][1] = (sp*sy) * scale;
        out->m[3][1] = y;
        out->m[0][2] = (-sp) * scale;
        out->m[1][2] = 0;
        out->m[2][2] = (cp) * scale;
        out->m[3][2] = z;
        out->m[0][3] = 0;
        out->m[1][3] = 0;
        out->m[2][3] = 0;
        out->m[3][3] = 1;
#else
        out->m[0][0] = (cp*cy) * scale;
        out->m[0][1] = (-sy) * scale;
        out->m[0][2] = (sp*cy) * scale;
        out->m[0][3] = x;
        out->m[1][0] = (cp*sy) * scale;
        out->m[1][1] = (cy) * scale;
        out->m[1][2] = (sp*sy) * scale;
        out->m[1][3] = y;
        out->m[2][0] = (-sp) * scale;
        out->m[2][1] = 0;
        out->m[2][2] = (cp) * scale;
        out->m[2][3] = z;
        out->m[3][0] = 0;
        out->m[3][1] = 0;
        out->m[3][2] = 0;
        out->m[3][3] = 1;
#endif
    }
    else if (yaw)
    {
        angle = yaw * (M_PI*2 / 360);
        sy = sin(angle);
        cy = cos(angle);
#ifdef MATRIX4x4_OPENGLORIENTATION
        out->m[0][0] = (cy) * scale;
        out->m[1][0] = (-sy) * scale;
        out->m[2][0] = 0;
        out->m[3][0] = x;
        out->m[0][1] = (sy) * scale;
        out->m[1][1] = (cy) * scale;
        out->m[2][1] = 0;
        out->m[3][1] = y;
        out->m[0][2] = 0;
        out->m[1][2] = 0;
        out->m[2][2] = scale;
        out->m[3][2] = z;
        out->m[0][3] = 0;
        out->m[1][3] = 0;
        out->m[2][3] = 0;
        out->m[3][3] = 1;
#else
        out->m[0][0] = (cy) * scale;
        out->m[0][1] = (-sy) * scale;
        out->m[0][2] = 0;
        out->m[0][3] = x;
        out->m[1][0] = (sy) * scale;
        out->m[1][1] = (cy) * scale;
        out->m[1][2] = 0;
        out->m[1][3] = y;
        out->m[2][0] = 0;
        out->m[2][1] = 0;
        out->m[2][2] = scale;
        out->m[2][3] = z;
        out->m[3][0] = 0;
        out->m[3][1] = 0;
        out->m[3][2] = 0;
        out->m[3][3] = 1;
#endif
    }
    else
    {
#ifdef MATRIX4x4_OPENGLORIENTATION
        out->m[0][0] = scale;
        out->m[1][0] = 0;
        out->m[2][0] = 0;
        out->m[3][0] = x;
        out->m[0][1] = 0;
        out->m[1][1] = scale;
        out->m[2][1] = 0;
        out->m[3][1] = y;
        out->m[0][2] = 0;
        out->m[1][2] = 0;
        out->m[2][2] = scale;
        out->m[3][2] = z;
        out->m[0][3] = 0;
        out->m[1][3] = 0;
        out->m[2][3] = 0;
        out->m[3][3] = 1;
#else
        out->m[0][0] = scale;
        out->m[0][1] = 0;
        out->m[0][2] = 0;
        out->m[0][3] = x;
        out->m[1][0] = 0;
        out->m[1][1] = scale;
        out->m[1][2] = 0;
        out->m[1][3] = y;
        out->m[2][0] = 0;
        out->m[2][1] = 0;
        out->m[2][2] = scale;
        out->m[2][3] = z;
        out->m[3][0] = 0;
        out->m[3][1] = 0;
        out->m[3][2] = 0;
        out->m[3][3] = 1;
#endif
    }
}
Referenced by CL_AddQWCTFFlagModel(), CL_Cache_TraceLineSurfaces(), CL_ClearState(), CL_GetEntityMatrix(), CL_ParseStatic(), CL_ParticleEffect_Fallback(), CL_RelinkBeams(), CL_RelinkEffects(), CL_RelinkQWNails(), CL_TimeRefresh_f(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), CL_UpdateNetworkEntity(), CSQC_R_RecalcView(), R_DecalSystem_SplatEntity(), R_Envmap_f(), R_RenderView(), R_Shadow_UpdateWorldLight(), R_Sky(), R_tcMod_ApplyToMatrix(), RotateBBox(), S_Update(), SV_CanSeeBox(), SV_GetEntityMatrix(), SV_PointSuperContents(), SV_PushMove(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), V_CalcIntermissionRefdef(), V_CalcRefdefUsing(), V_MakeViewIsometric(), and VM_CL_makestatic().
Matrix4x4_CreateIdentity()
void Matrix4x4_CreateIdentity (matrix4x4_t * out)
Definition at line 564 of file matrixlib.c.
{
    out->m[0][0]=1.0f;
    out->m[0][1]=0.0f;
    out->m[0][2]=0.0f;
    out->m[0][3]=0.0f;
    out->m[1][0]=0.0f;
    out->m[1][1]=1.0f;
    out->m[1][2]=0.0f;
    out->m[1][3]=0.0f;
    out->m[2][0]=0.0f;
    out->m[2][1]=0.0f;
    out->m[2][2]=1.0f;
    out->m[2][3]=0.0f;
    out->m[3][0]=0.0f;
    out->m[3][1]=0.0f;
    out->m[3][2]=0.0f;
    out->m[3][3]=1.0f;
}
Referenced by CL_GetExtendedTagInfo(), CL_MeshEntities_Init(), R_GetCurrentTexture(), and SV_GetExtendedTagInfo().
Matrix4x4_CreateRotate()
void Matrix4x4_CreateRotate (matrix4x4_t * out, double angle, double x, double y, double z)
Definition at line 623 of file matrixlib.c.
{
    double len, c, s;
    len = x*x+y*y+z*z;
    if (len != 0.0f)
        len = 1.0f / sqrt(len);
    x *= len;
    y *= len;
    z *= len;
    angle *= (-M_PI / 180.0);
    c = cos(angle);
    s = sin(angle);
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0]=x * x + c * (1 - x * x);
    out->m[1][0]=x * y * (1 - c) + z * s;
    out->m[2][0]=z * x * (1 - c) - y * s;
    out->m[3][0]=0.0f;
    out->m[0][1]=x * y * (1 - c) - z * s;
    out->m[1][1]=y * y + c * (1 - y * y);
    out->m[2][1]=y * z * (1 - c) + x * s;
    out->m[3][1]=0.0f;
    out->m[0][2]=z * x * (1 - c) + y * s;
    out->m[1][2]=y * z * (1 - c) - x * s;
    out->m[2][2]=z * z + c * (1 - z * z);
    out->m[3][2]=0.0f;
    out->m[0][3]=0.0f;
    out->m[1][3]=0.0f;
    out->m[2][3]=0.0f;
    out->m[3][3]=1.0f;
#else
    out->m[0][0]=x * x + c * (1 - x * x);
    out->m[0][1]=x * y * (1 - c) + z * s;
    out->m[0][2]=z * x * (1 - c) - y * s;
    out->m[0][3]=0.0f;
    out->m[1][0]=x * y * (1 - c) - z * s;
    out->m[1][1]=y * y + c * (1 - y * y);
    out->m[1][2]=y * z * (1 - c) + x * s;
    out->m[1][3]=0.0f;
    out->m[2][0]=z * x * (1 - c) + y * s;
    out->m[2][1]=y * z * (1 - c) - x * s;
    out->m[2][2]=z * z + c * (1 - z * z);
    out->m[2][3]=0.0f;
    out->m[3][0]=0.0f;
    out->m[3][1]=0.0f;
    out->m[3][2]=0.0f;
    out->m[3][3]=1.0f;
#endif
}
Referenced by Matrix4x4_ConcatRotate(), R_RotateSprite(), R_Viewport_InitOrtho3D(), R_Viewport_InitPerspective(), and R_Viewport_InitPerspectiveInfinite().
Matrix4x4_CreateScale()
void Matrix4x4_CreateScale (matrix4x4_t * out, double x)
Definition at line 675 of file matrixlib.c.
{
    out->m[0][0]=x;
    out->m[0][1]=0.0f;
    out->m[0][2]=0.0f;
    out->m[0][3]=0.0f;
    out->m[1][0]=0.0f;
    out->m[1][1]=x;
    out->m[1][2]=0.0f;
    out->m[1][3]=0.0f;
    out->m[2][0]=0.0f;
    out->m[2][1]=0.0f;
    out->m[2][2]=x;
    out->m[2][3]=0.0f;
    out->m[3][0]=0.0f;
    out->m[3][1]=0.0f;
    out->m[3][2]=0.0f;
    out->m[3][3]=1.0f;
}
Referenced by Matrix4x4_ConcatScale(), and V_CalcIntermissionRefdef().
Matrix4x4_CreateScale3()
void Matrix4x4_CreateScale3 (matrix4x4_t * out, double x, double y, double z)
Definition at line 695 of file matrixlib.c.
{
    out->m[0][0]=x;
    out->m[0][1]=0.0f;
    out->m[0][2]=0.0f;
    out->m[0][3]=0.0f;
    out->m[1][0]=0.0f;
    out->m[1][1]=y;
    out->m[1][2]=0.0f;
    out->m[1][3]=0.0f;
    out->m[2][0]=0.0f;
    out->m[2][1]=0.0f;
    out->m[2][2]=z;
    out->m[2][3]=0.0f;
    out->m[3][0]=0.0f;
    out->m[3][1]=0.0f;
    out->m[3][2]=0.0f;
    out->m[3][3]=1.0f;
}
Referenced by Matrix4x4_ConcatScale3(), Mod_Q3BSP_LoadLightGrid(), R_Shadow_DrawModelShadowMaps(), and R_tcMod_ApplyToMatrix().
Matrix4x4_CreateTranslate()
void Matrix4x4_CreateTranslate (matrix4x4_t * out, double x, double y, double z)
Definition at line 584 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0]=1.0f;
    out->m[1][0]=0.0f;
    out->m[2][0]=0.0f;
    out->m[3][0]=x;
    out->m[0][1]=0.0f;
    out->m[1][1]=1.0f;
    out->m[2][1]=0.0f;
    out->m[3][1]=y;
    out->m[0][2]=0.0f;
    out->m[1][2]=0.0f;
    out->m[2][2]=1.0f;
    out->m[3][2]=z;
    out->m[0][3]=0.0f;
    out->m[1][3]=0.0f;
    out->m[2][3]=0.0f;
    out->m[3][3]=1.0f;
#else
    out->m[0][0]=1.0f;
    out->m[0][1]=0.0f;
    out->m[0][2]=0.0f;
    out->m[0][3]=x;
    out->m[1][0]=0.0f;
    out->m[1][1]=1.0f;
    out->m[1][2]=0.0f;
    out->m[1][3]=y;
    out->m[2][0]=0.0f;
    out->m[2][1]=0.0f;
    out->m[2][2]=1.0f;
    out->m[2][3]=z;
    out->m[3][0]=0.0f;
    out->m[3][1]=0.0f;
    out->m[3][2]=0.0f;
    out->m[3][3]=1.0f;
#endif
}
Referenced by CL_NewParticlesFromEffectinfo(), CL_ParseTempEntity(), CL_ParticleEffect_Fallback(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), Matrix4x4_ConcatTranslate(), R_RenderScene(), R_SkySphere(), R_tcMod_ApplyToMatrix(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), V_MakeViewIsometric(), VM_CL_te_customflash(), VM_CL_te_explosion2(), and VM_CL_te_explosionrgb().
Matrix4x4_FromArray12FloatD3D()
void Matrix4x4_FromArray12FloatD3D (matrix4x4_t * out, const float in[12])
Definition at line 1422 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0];
    out->m[1][0] = in[1];
    out->m[2][0] = in[2];
    out->m[3][0] = in[3];
    out->m[0][1] = in[4];
    out->m[1][1] = in[5];
    out->m[2][1] = in[6];
    out->m[3][1] = in[7];
    out->m[0][2] = in[8];
    out->m[1][2] = in[9];
    out->m[2][2] = in[10];
    out->m[3][2] = in[11];
    out->m[0][3] = 0;
    out->m[1][3] = 0;
    out->m[2][3] = 0;
    out->m[3][3] = 1;
#else
    out->m[0][0] = in[0];
    out->m[0][1] = in[1];
    out->m[0][2] = in[2];
    out->m[0][3] = in[3];
    out->m[1][0] = in[4];
    out->m[1][1] = in[5];
    out->m[1][2] = in[6];
    out->m[1][3] = in[7];
    out->m[2][0] = in[8];
    out->m[2][1] = in[9];
    out->m[2][2] = in[10];
    out->m[2][3] = in[11];
    out->m[3][0] = 0;
    out->m[3][1] = 0;
    out->m[3][2] = 0;
    out->m[3][3] = 1;
#endif
}
Referenced by Mod_DARKPLACESMODEL_Load(), Mod_INTERQUAKEMODEL_Load(), Mod_ZYMOTICMODEL_Load(), and R_Shadow_DrawModelShadowMaps().
Matrix4x4_FromArray12FloatGL()
void Matrix4x4_FromArray12FloatGL (matrix4x4_t * out, const float in[12])
Definition at line 1352 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0];
    out->m[0][1] = in[1];
    out->m[0][2] = in[2];
    out->m[0][3] = 0;
    out->m[1][0] = in[3];
    out->m[1][1] = in[4];
    out->m[1][2] = in[5];
    out->m[1][3] = 0;
    out->m[2][0] = in[6];
    out->m[2][1] = in[7];
    out->m[2][2] = in[8];
    out->m[2][3] = 0;
    out->m[3][0] = in[9];
    out->m[3][1] = in[10];
    out->m[3][2] = in[11];
    out->m[3][3] = 1;
#else
    out->m[0][0] = in[0];
    out->m[1][0] = in[1];
    out->m[2][0] = in[2];
    out->m[3][0] = 0;
    out->m[0][1] = in[3];
    out->m[1][1] = in[4];
    out->m[2][1] = in[5];
    out->m[3][1] = 0;
    out->m[0][2] = in[6];
    out->m[1][2] = in[7];
    out->m[2][2] = in[8];
    out->m[3][2] = 0;
    out->m[0][3] = in[9];
    out->m[1][3] = in[10];
    out->m[2][3] = in[11];
    out->m[3][3] = 1;
#endif
}
Referenced by Mod_Alias_GetExtendedTagInfoForIndex(), Mod_Alias_GetTagMatrix(), and R_tcMod_ApplyToMatrix().
Matrix4x4_FromArrayDoubleD3D()
void Matrix4x4_FromArrayDoubleD3D (matrix4x4_t * out, const double in[4][4])
Definition at line 1126 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0][0];
    out->m[1][0] = in[0][1];
    out->m[2][0] = in[0][2];
    out->m[3][0] = in[0][3];
    out->m[0][1] = in[1][0];
    out->m[1][1] = in[1][1];
    out->m[2][1] = in[1][2];
    out->m[3][1] = in[1][3];
    out->m[0][2] = in[2][0];
    out->m[1][2] = in[2][1];
    out->m[2][2] = in[2][2];
    out->m[3][2] = in[2][3];
    out->m[0][3] = in[3][0];
    out->m[1][3] = in[3][1];
    out->m[2][3] = in[3][2];
    out->m[3][3] = in[3][3];
#else
    out->m[0][0] = in[0][0];
    out->m[0][1] = in[0][1];
    out->m[0][2] = in[0][2];
    out->m[0][3] = in[0][3];
    out->m[1][0] = in[1][0];
    out->m[1][1] = in[1][1];
    out->m[1][2] = in[1][2];
    out->m[1][3] = in[1][3];
    out->m[2][0] = in[2][0];
    out->m[2][1] = in[2][1];
    out->m[2][2] = in[2][2];
    out->m[2][3] = in[2][3];
    out->m[3][0] = in[3][0];
    out->m[3][1] = in[3][1];
    out->m[3][2] = in[3][2];
    out->m[3][3] = in[3][3];
#endif
}
Referenced by Mod_Q3BSP_LoadLightGrid().
Matrix4x4_FromArrayDoubleGL()
void Matrix4x4_FromArrayDoubleGL (matrix4x4_t * out, const double in[16])
Definition at line 1048 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0];
    out->m[0][1] = in[1];
    out->m[0][2] = in[2];
    out->m[0][3] = in[3];
    out->m[1][0] = in[4];
    out->m[1][1] = in[5];
    out->m[1][2] = in[6];
    out->m[1][3] = in[7];
    out->m[2][0] = in[8];
    out->m[2][1] = in[9];
    out->m[2][2] = in[10];
    out->m[2][3] = in[11];
    out->m[3][0] = in[12];
    out->m[3][1] = in[13];
    out->m[3][2] = in[14];
    out->m[3][3] = in[15];
#else
    out->m[0][0] = in[0];
    out->m[1][0] = in[1];
    out->m[2][0] = in[2];
    out->m[3][0] = in[3];
    out->m[0][1] = in[4];
    out->m[1][1] = in[5];
    out->m[2][1] = in[6];
    out->m[3][1] = in[7];
    out->m[0][2] = in[8];
    out->m[1][2] = in[9];
    out->m[2][2] = in[10];
    out->m[3][2] = in[11];
    out->m[0][3] = in[12];
    out->m[1][3] = in[13];
    out->m[2][3] = in[14];
    out->m[3][3] = in[15];
#endif
}
Matrix4x4_FromArrayFloatD3D()
void Matrix4x4_FromArrayFloatD3D (matrix4x4_t * out, const float in[16])
Definition at line 1282 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0];
    out->m[1][0] = in[1];
    out->m[2][0] = in[2];
    out->m[3][0] = in[3];
    out->m[0][1] = in[4];
    out->m[1][1] = in[5];
    out->m[2][1] = in[6];
    out->m[3][1] = in[7];
    out->m[0][2] = in[8];
    out->m[1][2] = in[9];
    out->m[2][2] = in[10];
    out->m[3][2] = in[11];
    out->m[0][3] = in[12];
    out->m[1][3] = in[13];
    out->m[2][3] = in[14];
    out->m[3][3] = in[15];
#else
    out->m[0][0] = in[0];
    out->m[0][1] = in[1];
    out->m[0][2] = in[2];
    out->m[0][3] = in[3];
    out->m[1][0] = in[4];
    out->m[1][1] = in[5];
    out->m[1][2] = in[6];
    out->m[1][3] = in[7];
    out->m[2][0] = in[8];
    out->m[2][1] = in[9];
    out->m[2][2] = in[10];
    out->m[2][3] = in[11];
    out->m[3][0] = in[12];
    out->m[3][1] = in[13];
    out->m[3][2] = in[14];
    out->m[3][3] = in[15];
#endif
}
Referenced by R_Shadow_BounceGrid_UpdateSpacing().
Matrix4x4_FromArrayFloatGL()
void Matrix4x4_FromArrayFloatGL (matrix4x4_t * out, const float in[16])
Definition at line 1204 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = in[0];
    out->m[0][1] = in[1];
    out->m[0][2] = in[2];
    out->m[0][3] = in[3];
    out->m[1][0] = in[4];
    out->m[1][1] = in[5];
    out->m[1][2] = in[6];
    out->m[1][3] = in[7];
    out->m[2][0] = in[8];
    out->m[2][1] = in[9];
    out->m[2][2] = in[10];
    out->m[2][3] = in[11];
    out->m[3][0] = in[12];
    out->m[3][1] = in[13];
    out->m[3][2] = in[14];
    out->m[3][3] = in[15];
#else
    out->m[0][0] = in[0];
    out->m[1][0] = in[1];
    out->m[2][0] = in[2];
    out->m[3][0] = in[3];
    out->m[0][1] = in[4];
    out->m[1][1] = in[5];
    out->m[2][1] = in[6];
    out->m[3][1] = in[7];
    out->m[0][2] = in[8];
    out->m[1][2] = in[9];
    out->m[2][2] = in[10];
    out->m[3][2] = in[11];
    out->m[0][3] = in[12];
    out->m[1][3] = in[13];
    out->m[2][3] = in[14];
    out->m[3][3] = in[15];
#endif
}
Referenced by R_Viewport_InitCubeSideView(), R_Viewport_InitOrtho(), R_Viewport_InitOrtho3D(), R_Viewport_InitPerspective(), R_Viewport_InitPerspectiveInfinite(), R_Viewport_InitRectSideView(), and V_MakeViewIsometric().
Matrix4x4_FromBonePose7s()
void Matrix4x4_FromBonePose7s (matrix4x4_t * m, float originscale, const short * pose7s)
Definition at line 1599 of file matrixlib.c.
{
    float origin[3];
    float quat[4];
    float quatscale = pose7s[6] > 0 ? -1.0f / 32767.0f : 1.0f / 32767.0f;
    origin[0] = pose7s[0] * originscale;
    origin[1] = pose7s[1] * originscale;
    origin[2] = pose7s[2] * originscale;
    quat[0] = pose7s[3] * quatscale;
    quat[1] = pose7s[4] * quatscale;
    quat[2] = pose7s[5] * quatscale;
    quat[3] = pose7s[6] * quatscale;
    Matrix4x4_FromOriginQuat(m, origin[0], origin[1], origin[2], quat[0], quat[1], quat[2], quat[3]);
}
Referenced by EntityState5_ReadUpdate(), Mod_Alias_GetExtendedTagInfoForIndex(), Mod_Alias_GetTagMatrix(), Mod_BuildBaseBonePoses(), Mod_Decompile_SMD(), VM_CL_skel_build(), and VM_SV_skel_build().
Matrix4x4_FromDoom3Joint()
void Matrix4x4_FromDoom3Joint (matrix4x4_t * m, double ox, double oy, double oz, double x, double y, double z)
Definition at line 1582 of file matrixlib.c.
{
    double w = 1.0f - (x*x+y*y+z*z);
    w = w > 0.0f ? -sqrt(w) : 0.0f;
#ifdef MATRIX4x4_OPENGLORIENTATION
    m->m[0][0]=1-2*(y*y+z*z);m->m[1][0]=  2*(x*y-z*w);m->m[2][0]=  2*(x*z+y*w);m->m[3][0]=ox;
    m->m[0][1]=  2*(x*y+z*w);m->m[1][1]=1-2*(x*x+z*z);m->m[2][1]=  2*(y*z-x*w);m->m[3][1]=oy;
    m->m[0][2]=  2*(x*z-y*w);m->m[1][2]=  2*(y*z+x*w);m->m[2][2]=1-2*(x*x+y*y);m->m[3][2]=oz;
    m->m[0][3]=  0          ;m->m[1][3]=  0          ;m->m[2][3]=  0          ;m->m[3][3]=1;
#else
    m->m[0][0]=1-2*(y*y+z*z);m->m[0][1]=  2*(x*y-z*w);m->m[0][2]=  2*(x*z+y*w);m->m[0][3]=ox;
    m->m[1][0]=  2*(x*y+z*w);m->m[1][1]=1-2*(x*x+z*z);m->m[1][2]=  2*(y*z-x*w);m->m[1][3]=oy;
    m->m[2][0]=  2*(x*z-y*w);m->m[2][1]=  2*(y*z+x*w);m->m[2][2]=1-2*(x*x+y*y);m->m[2][3]=oz;
    m->m[3][0]=  0          ;m->m[3][1]=  0          ;m->m[3][2]=  0          ;m->m[3][3]=1;
#endif
}
Referenced by Mod_INTERQUAKEMODEL_Load().
Matrix4x4_FromOriginQuat()
void Matrix4x4_FromOriginQuat (matrix4x4_t * m, double ox, double oy, double oz, double x, double y, double z, double w)
Definition at line 1461 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    m->m[0][0]=1-2*(y*y+z*z);m->m[1][0]=  2*(x*y-z*w);m->m[2][0]=  2*(x*z+y*w);m->m[3][0]=ox;
    m->m[0][1]=  2*(x*y+z*w);m->m[1][1]=1-2*(x*x+z*z);m->m[2][1]=  2*(y*z-x*w);m->m[3][1]=oy;
    m->m[0][2]=  2*(x*z-y*w);m->m[1][2]=  2*(y*z+x*w);m->m[2][2]=1-2*(x*x+y*y);m->m[3][2]=oz;
    m->m[0][3]=  0          ;m->m[1][3]=  0          ;m->m[2][3]=  0          ;m->m[3][3]=1;
#else
    m->m[0][0]=1-2*(y*y+z*z);m->m[0][1]=  2*(x*y-z*w);m->m[0][2]=  2*(x*z+y*w);m->m[0][3]=ox;
    m->m[1][0]=  2*(x*y+z*w);m->m[1][1]=1-2*(x*x+z*z);m->m[1][2]=  2*(y*z-x*w);m->m[1][3]=oy;
    m->m[2][0]=  2*(x*z-y*w);m->m[2][1]=  2*(y*z+x*w);m->m[2][2]=1-2*(x*x+y*y);m->m[2][3]=oz;
    m->m[3][0]=  0          ;m->m[3][1]=  0          ;m->m[3][2]=  0          ;m->m[3][3]=1;
#endif
}
Referenced by Matrix4x4_FromBonePose7s(), and Mod_PSKMODEL_Load().
Matrix4x4_FromVectors()
void Matrix4x4_FromVectors (matrix4x4_t * out, const vec_t vx[3], const vec_t vy[3], const vec_t vz[3], const vec_t t[3])
Definition at line 970 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = vx[0];
    out->m[1][0] = vy[0];
    out->m[2][0] = vz[0];
    out->m[3][0] = t[0];
    out->m[0][1] = vx[1];
    out->m[1][1] = vy[1];
    out->m[2][1] = vz[1];
    out->m[3][1] = t[1];
    out->m[0][2] = vx[2];
    out->m[1][2] = vy[2];
    out->m[2][2] = vz[2];
    out->m[3][2] = t[2];
    out->m[0][3] = 0.0f;
    out->m[1][3] = 0.0f;
    out->m[2][3] = 0.0f;
    out->m[3][3] = 1.0f;
#else
    out->m[0][0] = vx[0];
    out->m[0][1] = vy[0];
    out->m[0][2] = vz[0];
    out->m[0][3] = t[0];
    out->m[1][0] = vx[1];
    out->m[1][1] = vy[1];
    out->m[1][2] = vz[1];
    out->m[1][3] = t[1];
    out->m[2][0] = vx[2];
    out->m[2][1] = vy[2];
    out->m[2][2] = vz[2];
    out->m[2][3] = t[2];
    out->m[3][0] = 0.0f;
    out->m[3][1] = 0.0f;
    out->m[3][2] = 0.0f;
    out->m[3][3] = 1.0f;
#endif
}
Referenced by CL_GetEntityMatrix(), CL_VM_TransformView(), Mod_GenerateLightmaps_CreateLightmaps(), R_DecalSystem_SplatEntity(), V_MakeViewIsometric(), VM_CL_makestatic(), VM_CL_R_AddDynamicLight(), VM_CL_RotateMoves(), VM_CL_setlistener(), VM_CL_skel_mul_bone(), VM_CL_skel_mul_bones(), VM_CL_skel_set_bone(), VM_SV_skel_mul_bone(), VM_SV_skel_mul_bones(), and VM_SV_skel_set_bone().
Matrix4x4_Interpolate()
void Matrix4x4_Interpolate (matrix4x4_t * out, matrix4x4_t * in1, matrix4x4_t * in2, double frac)
Definition at line 475 of file matrixlib.c.
{
    int i, j;
    for (i = 0;i < 4;i++)
        for (j = 0;j < 4;j++)
            out->m[i][j] = in1->m[i][j] + frac * (in2->m[i][j] - in1->m[i][j]);
}
Referenced by VM_CL_skel_build(), and VM_SV_skel_build().
Matrix4x4_Invert_Full()
int Matrix4x4_Invert_Full (matrix4x4_t * out, const matrix4x4_t * in1)
Definition at line 145 of file matrixlib.c.
{
        float det;
        // note: orientation does not matter, as transpose(invert(transpose(m))) == invert(m), proof:
        //   transpose(invert(transpose(m))) * m
        // = transpose(invert(transpose(m))) * transpose(transpose(m))
        // = transpose(transpose(m) * invert(transpose(m)))
        // = transpose(identity)
        // = identity
        // this seems to help gcc's common subexpression elimination, and also makes the code look nicer
        float   m00 = in1->m[0][0], m01 = in1->m[0][1], m02 = in1->m[0][2], m03 = in1->m[0][3],
                m10 = in1->m[1][0], m11 = in1->m[1][1], m12 = in1->m[1][2], m13 = in1->m[1][3],
                m20 = in1->m[2][0], m21 = in1->m[2][1], m22 = in1->m[2][2], m23 = in1->m[2][3],
                m30 = in1->m[3][0], m31 = in1->m[3][1], m32 = in1->m[3][2], m33 = in1->m[3][3];
        // calculate the adjoint
        out->m[0][0] =  (m11*(m22*m33 - m23*m32) - m21*(m12*m33 - m13*m32) + m31*(m12*m23 - m13*m22));
        out->m[0][1] = -(m01*(m22*m33 - m23*m32) - m21*(m02*m33 - m03*m32) + m31*(m02*m23 - m03*m22));
        out->m[0][2] =  (m01*(m12*m33 - m13*m32) - m11*(m02*m33 - m03*m32) + m31*(m02*m13 - m03*m12));
        out->m[0][3] = -(m01*(m12*m23 - m13*m22) - m11*(m02*m23 - m03*m22) + m21*(m02*m13 - m03*m12));
        out->m[1][0] = -(m10*(m22*m33 - m23*m32) - m20*(m12*m33 - m13*m32) + m30*(m12*m23 - m13*m22));
        out->m[1][1] =  (m00*(m22*m33 - m23*m32) - m20*(m02*m33 - m03*m32) + m30*(m02*m23 - m03*m22));
        out->m[1][2] = -(m00*(m12*m33 - m13*m32) - m10*(m02*m33 - m03*m32) + m30*(m02*m13 - m03*m12));
        out->m[1][3] =  (m00*(m12*m23 - m13*m22) - m10*(m02*m23 - m03*m22) + m20*(m02*m13 - m03*m12));
        out->m[2][0] =  (m10*(m21*m33 - m23*m31) - m20*(m11*m33 - m13*m31) + m30*(m11*m23 - m13*m21));
        out->m[2][1] = -(m00*(m21*m33 - m23*m31) - m20*(m01*m33 - m03*m31) + m30*(m01*m23 - m03*m21));
        out->m[2][2] =  (m00*(m11*m33 - m13*m31) - m10*(m01*m33 - m03*m31) + m30*(m01*m13 - m03*m11));
        out->m[2][3] = -(m00*(m11*m23 - m13*m21) - m10*(m01*m23 - m03*m21) + m20*(m01*m13 - m03*m11));
        out->m[3][0] = -(m10*(m21*m32 - m22*m31) - m20*(m11*m32 - m12*m31) + m30*(m11*m22 - m12*m21));
        out->m[3][1] =  (m00*(m21*m32 - m22*m31) - m20*(m01*m32 - m02*m31) + m30*(m01*m22 - m02*m21));
        out->m[3][2] = -(m00*(m11*m32 - m12*m31) - m10*(m01*m32 - m02*m31) + m30*(m01*m12 - m02*m11));
        out->m[3][3] =  (m00*(m11*m22 - m12*m21) - m10*(m01*m22 - m02*m21) + m20*(m01*m12 - m02*m11));
        // calculate the determinant (as inverse == 1/det * adjoint, adjoint * m == identity * det, so this calculates the det)
        det = m00*out->m[0][0] + m10*out->m[0][1] + m20*out->m[0][2] + m30*out->m[0][3];
        if (det == 0.0f)
                return 0;
        // multiplications are faster than divisions, usually
        det = 1.0f / det;
        // manually unrolled loop to multiply all matrix elements by 1/det
        out->m[0][0] *= det; out->m[0][1] *= det; out->m[0][2] *= det; out->m[0][3] *= det;
        out->m[1][0] *= det; out->m[1][1] *= det; out->m[1][2] *= det; out->m[1][3] *= det;
        out->m[2][0] *= det; out->m[2][1] *= det; out->m[2][2] *= det; out->m[2][3] *= det;
        out->m[3][0] *= det; out->m[3][1] *= det; out->m[3][2] *= det; out->m[3][3] *= det;
        return 1;
}
Referenced by applytransform_inverted(), CL_VM_TransformView(), R_RenderView_UpdateViewVectors(), R_SetupShader_DeferredLight(), R_Shadow_DrawModelShadowMaps(), R_Viewport_InitCubeSideView(), R_Viewport_InitOrtho(), R_Viewport_InitOrtho3D(), R_Viewport_InitPerspective(), R_Viewport_InitPerspectiveInfinite(), R_Viewport_InitRectSideView(), and VM_CL_project().
Matrix4x4_Invert_Simple()
void Matrix4x4_Invert_Simple (matrix4x4_t * out, const matrix4x4_t * in1)
Definition at line 422 of file matrixlib.c.
{
    // we only support uniform scaling, so assume the first row is enough
    // (note the lack of sqrt here, because we're trying to undo the scaling,
    // this means multiplying by the inverse scale twice - squaring it, which
    // makes the sqrt a waste of time)
#if 1
    double scale = 1.0 / (in1->m[0][0] * in1->m[0][0] + in1->m[0][1] * in1->m[0][1] + in1->m[0][2] * in1->m[0][2]);
#else
    double scale = 3.0 / sqrt
         (in1->m[0][0] * in1->m[0][0] + in1->m[0][1] * in1->m[0][1] + in1->m[0][2] * in1->m[0][2]
        + in1->m[1][0] * in1->m[1][0] + in1->m[1][1] * in1->m[1][1] + in1->m[1][2] * in1->m[1][2]
        + in1->m[2][0] * in1->m[2][0] + in1->m[2][1] * in1->m[2][1] + in1->m[2][2] * in1->m[2][2]);
    scale *= scale;
#endif
    // invert the rotation by transposing and multiplying by the squared
    // recipricol of the input matrix scale as described above
    out->m[0][0] = in1->m[0][0] * scale;
    out->m[0][1] = in1->m[1][0] * scale;
    out->m[0][2] = in1->m[2][0] * scale;
    out->m[1][0] = in1->m[0][1] * scale;
    out->m[1][1] = in1->m[1][1] * scale;
    out->m[1][2] = in1->m[2][1] * scale;
    out->m[2][0] = in1->m[0][2] * scale;
    out->m[2][1] = in1->m[1][2] * scale;
    out->m[2][2] = in1->m[2][2] * scale;
#ifdef MATRIX4x4_OPENGLORIENTATION
    // invert the translate
    out->m[3][0] = -(in1->m[3][0] * out->m[0][0] + in1->m[3][1] * out->m[1][0] + in1->m[3][2] * out->m[2][0]);
    out->m[3][1] = -(in1->m[3][0] * out->m[0][1] + in1->m[3][1] * out->m[1][1] + in1->m[3][2] * out->m[2][1]);
    out->m[3][2] = -(in1->m[3][0] * out->m[0][2] + in1->m[3][1] * out->m[1][2] + in1->m[3][2] * out->m[2][2]);
    // don't know if there's anything worth doing here
    out->m[0][3] = 0;
    out->m[1][3] = 0;
    out->m[2][3] = 0;
    out->m[3][3] = 1;
#else
    // invert the translate
    out->m[0][3] = -(in1->m[0][3] * out->m[0][0] + in1->m[1][3] * out->m[0][1] + in1->m[2][3] * out->m[0][2]);
    out->m[1][3] = -(in1->m[0][3] * out->m[1][0] + in1->m[1][3] * out->m[1][1] + in1->m[2][3] * out->m[1][2]);
    out->m[2][3] = -(in1->m[0][3] * out->m[2][0] + in1->m[1][3] * out->m[2][1] + in1->m[2][3] * out->m[2][2]);
    // don't know if there's anything worth doing here
    out->m[3][0] = 0;
    out->m[3][1] = 0;
    out->m[3][2] = 0;
    out->m[3][3] = 1;
#endif
}
Referenced by CL_Cache_TraceLineSurfaces(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), CL_UpdateRenderEntity(), Mod_BuildBaseBonePoses(), Mod_INTERQUAKEMODEL_Load(), Mod_PSKMODEL_Load(), R_DecalSystem_SplatEntity(), R_RTLight_Update(), R_Sky(), S_Update(), SV_CanSeeBox(), SV_PointSuperContents(), SV_PushMove(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), V_CalcIntermissionRefdef(), and V_CalcRefdefUsing().
Matrix4x4_Normalize()
void Matrix4x4_Normalize (matrix4x4_t * out, matrix4x4_t * in1)
Definition at line 499 of file matrixlib.c.
{
    // scale rotation matrix vectors to a length of 1
    // note: this is only designed to undo uniform scaling
    double scale = 1.0 / sqrt(in1->m[0][0] * in1->m[0][0] + in1->m[0][1] * in1->m[0][1] + in1->m[0][2] * in1->m[0][2]);
    *out = *in1;
    Matrix4x4_Scale(out, scale, 1);
}
Referenced by CL_AllocLightFlash(), and CL_LinkNetworkEntity().
Matrix4x4_Normalize3()
void Matrix4x4_Normalize3 (matrix4x4_t * out, matrix4x4_t * in1)
Definition at line 508 of file matrixlib.c.
{
    int i;
    double scale;
    // scale each rotation matrix vector to a length of 1
    // intended for use after Matrix4x4_Interpolate or Matrix4x4_Accumulate
    *out = *in1;
    for (i = 0;i < 3;i++)
    {
#ifdef MATRIX4x4_OPENGLORIENTATION
        scale = sqrt(in1->m[i][0] * in1->m[i][0] + in1->m[i][1] * in1->m[i][1] + in1->m[i][2] * in1->m[i][2]);
        if (scale)
            scale = 1.0 / scale;
        out->m[i][0] *= scale;
        out->m[i][1] *= scale;
        out->m[i][2] *= scale;
#else
        scale = sqrt(in1->m[0][i] * in1->m[0][i] + in1->m[1][i] * in1->m[1][i] + in1->m[2][i] * in1->m[2][i]);
        if (scale)
            scale = 1.0 / scale;
        out->m[0][i] *= scale;
        out->m[1][i] *= scale;
        out->m[2][i] *= scale;
#endif
    }
}
Referenced by Mod_Alias_GetTagMatrix(), R_SetupShader_Surface(), VM_CL_skel_build(), and VM_SV_skel_build().
Matrix4x4_OriginFromMatrix()
void Matrix4x4_OriginFromMatrix (const matrix4x4_t * in, vec_t * out)
Definition at line 1792 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[0] = in->m[3][0];
    out[1] = in->m[3][1];
    out[2] = in->m[3][2];
#else
    out[0] = in->m[0][3];
    out[1] = in->m[1][3];
    out[2] = in->m[2][3];
#endif
}
Referenced by CL_AllocLightFlash(), CL_Beam_CalculatePositions(), CL_EntityParticles(), CL_GetTagMatrix(), CL_LinkNetworkEntity(), CL_TraceBox(), CL_TraceLine(), CL_TracePoint(), CL_UpdateEntityShading_Entity(), CL_UpdateNetworkEntity(), CL_UpdateNetworkEntityTrail(), CL_UpdatePrydonCursor(), CL_UpdateRenderEntity(), CL_UpdateScreen(), CL_VM_GetEntitySoundOrigin(), CSQC_SetGlobals(), R_DrawNoModel(), R_Model_Sprite_Draw(), R_RTLight_Update(), R_Shadow_CullFrustumSides(), R_Shadow_PrepareLight(), R_Water_ProcessPlanes(), S_Update(), Sbar_ShowFPS(), SND_Spatialize_WithSfx(), SV_Ent_Create_f(), SV_Ent_Remove_f(), V_CalcRefdefUsing(), V_CalcViewBlend(), and VM_CL_GetEntity().
Matrix4x4_QuakeToDuke3D()
void Matrix4x4_QuakeToDuke3D (const matrix4x4_t * in, matrix4x4_t * out, double maxShearAngle)
Definition at line 891 of file matrixlib.c.
{
    // Sorry - this isn't direct at all. We can't just use an alternative to
    // Matrix4x4_CreateFromQuakeEntity as in some cases the input for
    // generating the view matrix is generated externally.
    vec3_t forward, left, up, angles;
    double scaleforward, scaleleft, scaleup;
#ifdef MATRIX4x4_OPENGLORIENTATION
    VectorSet(forward, in->m[0][0], in->m[0][1], in->m[0][2]);
    VectorSet(left, in->m[1][0], in->m[1][1], in->m[1][2]);
    VectorSet(up, in->m[2][0], in->m[2][1], in->m[2][2]);
#else
    VectorSet(forward, in->m[0][0], in->m[1][0], in->m[2][0]);
    VectorSet(left, in->m[0][1], in->m[1][1], in->m[2][1]);
    VectorSet(up, in->m[0][2], in->m[1][2], in->m[2][2]);
#endif
    scaleforward = VectorNormalizeLength(forward);
    scaleleft = VectorNormalizeLength(left);
    scaleup = VectorNormalizeLength(up);
    AnglesFromVectors(angles, forward, up, false);
    AngleVectorsDuke3DFLU(angles, forward, left, up, maxShearAngle);
    VectorScale(forward, scaleforward, forward);
    VectorScale(left, scaleleft, left);
    VectorScale(up, scaleup, up);
    *out = *in;
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[0][0] = forward[0];
    out->m[1][0] = left[0];
    out->m[2][0] = up[0];
    out->m[0][1] = forward[1];
    out->m[1][1] = left[1];
    out->m[2][1] = up[1];
    out->m[0][2] = forward[2];
    out->m[1][2] = left[2];
    out->m[2][2] = up[2];
#else
    out->m[0][0] = forward[0];
    out->m[0][1] = left[0];
    out->m[0][2] = up[0];
    out->m[1][0] = forward[1];
    out->m[1][1] = left[1];
    out->m[1][2] = up[1];
    out->m[2][0] = forward[2];
    out->m[2][1] = left[2];
    out->m[2][2] = up[2];
#endif
}
Referenced by CSQC_R_RecalcView(), V_CalcIntermissionRefdef(), and V_CalcRefdefUsing().
Matrix4x4_Reflect()
void Matrix4x4_Reflect (matrix4x4_t * out, double normalx, double normaly, double normalz, double dist, double axisscale)
Definition at line 535 of file matrixlib.c.
{
    int i;
    double d;
    double p[4], p2[4];
    p[0] = normalx;
    p[1] = normaly;
    p[2] = normalz;
    p[3] = -dist;
    p2[0] = p[0] * axisscale;
    p2[1] = p[1] * axisscale;
    p2[2] = p[2] * axisscale;
    p2[3] = 0;
    for (i = 0;i < 4;i++)
    {
#ifdef MATRIX4x4_OPENGLORIENTATION
        d = out->m[i][0] * p[0] + out->m[i][1] * p[1] + out->m[i][2] * p[2] + out->m[i][3] * p[3];
        out->m[i][0] += p2[0] * d;
        out->m[i][1] += p2[1] * d;
        out->m[i][2] += p2[2] * d;
#else
        d = out->m[0][i] * p[0] + out->m[1][i] * p[1] + out->m[2][i] * p[2] + out->m[3][i] * p[3];
        out->m[0][i] += p2[0] * d;
        out->m[1][i] += p2[1] * d;
        out->m[2][i] += p2[2] * d;
#endif
    }
}
Referenced by R_Water_ProcessPlanes().
Matrix4x4_Scale()
void Matrix4x4_Scale (matrix4x4_t * out, double rotatescale, double originscale)
Definition at line 1837 of file matrixlib.c.
{
    out->m[0][0] *= rotatescale;
    out->m[0][1] *= rotatescale;
    out->m[0][2] *= rotatescale;
    out->m[1][0] *= rotatescale;
    out->m[1][1] *= rotatescale;
    out->m[1][2] *= rotatescale;
    out->m[2][0] *= rotatescale;
    out->m[2][1] *= rotatescale;
    out->m[2][2] *= rotatescale;
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[3][0] *= originscale;
    out->m[3][1] *= originscale;
    out->m[3][2] *= originscale;
#else
    out->m[0][3] *= originscale;
    out->m[1][3] *= originscale;
    out->m[2][3] *= originscale;
#endif
}
Referenced by CL_LinkNetworkEntity(), CL_NewParticlesFromEffectinfo(), CL_RelinkLightFlashes(), Matrix4x4_Normalize(), R_RTLight_Update(), and VM_CL_makestatic().
Matrix4x4_ScaleFromMatrix()
double Matrix4x4_ScaleFromMatrix (const matrix4x4_t * in)
Definition at line 1805 of file matrixlib.c.
{
    // we only support uniform scaling, so assume the first row is enough
    return sqrt(in->m[0][0] * in->m[0][0] + in->m[0][1] * in->m[0][1] + in->m[0][2] * in->m[0][2]);
}
Referenced by CL_UpdateRenderEntity(), R_RTLight_Update(), R_Shadow_DrawModelShadowMaps(), RSurf_ActiveCustomEntity(), RSurf_ActiveModelEntity(), and VM_CL_GetEntity().
Matrix4x4_SetOrigin()
void Matrix4x4_SetOrigin (matrix4x4_t * out, double x, double y, double z)
Definition at line 1811 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out->m[3][0] = x;
    out->m[3][1] = y;
    out->m[3][2] = z;
#else
    out->m[0][3] = x;
    out->m[1][3] = y;
    out->m[2][3] = z;
#endif
}
Referenced by CL_AllocLightFlash(), and CL_LinkNetworkEntity().
Matrix4x4_ToArray12FloatD3D()
void Matrix4x4_ToArray12FloatD3D (const matrix4x4_t * in, float out[12])
Definition at line 1391 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[1][0];
    out[ 2] = in->m[2][0];
    out[ 3] = in->m[3][0];
    out[ 4] = in->m[0][1];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[2][1];
    out[ 7] = in->m[3][1];
    out[ 8] = in->m[0][2];
    out[ 9] = in->m[1][2];
    out[10] = in->m[2][2];
    out[11] = in->m[3][2];
#else
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[0][1];
    out[ 2] = in->m[0][2];
    out[ 3] = in->m[0][3];
    out[ 4] = in->m[1][0];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[1][2];
    out[ 7] = in->m[1][3];
    out[ 8] = in->m[2][0];
    out[ 9] = in->m[2][1];
    out[10] = in->m[2][2];
    out[11] = in->m[2][3];
#endif
}
Referenced by Mod_BuildBaseBonePoses(), Mod_INTERQUAKEMODEL_Load(), Mod_PSKMODEL_Load(), and Mod_Skeletal_BuildTransforms().
Matrix4x4_ToArray12FloatGL()
void Matrix4x4_ToArray12FloatGL (const matrix4x4_t * in, float out[4][3])
Definition at line 1321 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[0][0] = in->m[0][0];
    out[0][1] = in->m[0][1];
    out[0][2] = in->m[0][2];
    out[1][0] = in->m[1][0];
    out[1][1] = in->m[1][1];
    out[1][2] = in->m[1][2];
    out[2][0] = in->m[2][0];
    out[2][1] = in->m[2][1];
    out[2][2] = in->m[2][2];
    out[3][0] = in->m[3][0];
    out[3][1] = in->m[3][1];
    out[3][2] = in->m[3][2];
#else
    out[0][0] = in->m[0][0];
    out[0][1] = in->m[1][0];
    out[0][2] = in->m[2][0];
    out[1][0] = in->m[0][1];
    out[1][1] = in->m[1][1];
    out[1][2] = in->m[2][1];
    out[2][0] = in->m[0][2];
    out[2][1] = in->m[1][2];
    out[2][2] = in->m[2][2];
    out[3][0] = in->m[0][3];
    out[3][1] = in->m[1][3];
    out[3][2] = in->m[2][3];
#endif
}
Referenced by Mod_Decompile_SMD().
Matrix4x4_ToArrayDoubleD3D()
void Matrix4x4_ToArrayDoubleD3D (const matrix4x4_t * in, double out[16])
Definition at line 1087 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[1][0];
    out[ 2] = in->m[2][0];
    out[ 3] = in->m[3][0];
    out[ 4] = in->m[0][1];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[2][1];
    out[ 7] = in->m[3][1];
    out[ 8] = in->m[0][2];
    out[ 9] = in->m[1][2];
    out[10] = in->m[2][2];
    out[11] = in->m[3][2];
    out[12] = in->m[0][3];
    out[13] = in->m[1][3];
    out[14] = in->m[2][3];
    out[15] = in->m[3][3];
#else
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[0][1];
    out[ 2] = in->m[0][2];
    out[ 3] = in->m[0][3];
    out[ 4] = in->m[1][0];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[1][2];
    out[ 7] = in->m[1][3];
    out[ 8] = in->m[2][0];
    out[ 9] = in->m[2][1];
    out[10] = in->m[2][2];
    out[11] = in->m[2][3];
    out[12] = in->m[3][0];
    out[13] = in->m[3][1];
    out[14] = in->m[3][2];
    out[15] = in->m[3][3];
#endif
}
Matrix4x4_ToArrayDoubleGL()
void Matrix4x4_ToArrayDoubleGL (const matrix4x4_t * in, double out[16])
Definition at line 1009 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[0][1];
    out[ 2] = in->m[0][2];
    out[ 3] = in->m[0][3];
    out[ 4] = in->m[1][0];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[1][2];
    out[ 7] = in->m[1][3];
    out[ 8] = in->m[2][0];
    out[ 9] = in->m[2][1];
    out[10] = in->m[2][2];
    out[11] = in->m[2][3];
    out[12] = in->m[3][0];
    out[13] = in->m[3][1];
    out[14] = in->m[3][2];
    out[15] = in->m[3][3];
#else
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[1][0];
    out[ 2] = in->m[2][0];
    out[ 3] = in->m[3][0];
    out[ 4] = in->m[0][1];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[2][1];
    out[ 7] = in->m[3][1];
    out[ 8] = in->m[0][2];
    out[ 9] = in->m[1][2];
    out[10] = in->m[2][2];
    out[11] = in->m[3][2];
    out[12] = in->m[0][3];
    out[13] = in->m[1][3];
    out[14] = in->m[2][3];
    out[15] = in->m[3][3];
#endif
}
Matrix4x4_ToArrayFloatD3D()
void Matrix4x4_ToArrayFloatD3D (const matrix4x4_t * in, float out[16])
Definition at line 1243 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[1][0];
    out[ 2] = in->m[2][0];
    out[ 3] = in->m[3][0];
    out[ 4] = in->m[0][1];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[2][1];
    out[ 7] = in->m[3][1];
    out[ 8] = in->m[0][2];
    out[ 9] = in->m[1][2];
    out[10] = in->m[2][2];
    out[11] = in->m[3][2];
    out[12] = in->m[0][3];
    out[13] = in->m[1][3];
    out[14] = in->m[2][3];
    out[15] = in->m[3][3];
#else
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[0][1];
    out[ 2] = in->m[0][2];
    out[ 3] = in->m[0][3];
    out[ 4] = in->m[1][0];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[1][2];
    out[ 7] = in->m[1][3];
    out[ 8] = in->m[2][0];
    out[ 9] = in->m[2][1];
    out[10] = in->m[2][2];
    out[11] = in->m[2][3];
    out[12] = in->m[3][0];
    out[13] = in->m[3][1];
    out[14] = in->m[3][2];
    out[15] = in->m[3][3];
#endif
}
Matrix4x4_ToArrayFloatGL()
void Matrix4x4_ToArrayFloatGL (const matrix4x4_t * in, float out[16])
Definition at line 1165 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[0][1];
    out[ 2] = in->m[0][2];
    out[ 3] = in->m[0][3];
    out[ 4] = in->m[1][0];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[1][2];
    out[ 7] = in->m[1][3];
    out[ 8] = in->m[2][0];
    out[ 9] = in->m[2][1];
    out[10] = in->m[2][2];
    out[11] = in->m[2][3];
    out[12] = in->m[3][0];
    out[13] = in->m[3][1];
    out[14] = in->m[3][2];
    out[15] = in->m[3][3];
#else
    out[ 0] = in->m[0][0];
    out[ 1] = in->m[1][0];
    out[ 2] = in->m[2][0];
    out[ 3] = in->m[3][0];
    out[ 4] = in->m[0][1];
    out[ 5] = in->m[1][1];
    out[ 6] = in->m[2][1];
    out[ 7] = in->m[3][1];
    out[ 8] = in->m[0][2];
    out[ 9] = in->m[1][2];
    out[10] = in->m[2][2];
    out[11] = in->m[3][2];
    out[12] = in->m[0][3];
    out[13] = in->m[1][3];
    out[14] = in->m[2][3];
    out[15] = in->m[3][3];
#endif
}
Referenced by R_EntityMatrix(), R_SetupShader_DeferredLight(), and R_SetupShader_Surface().
Matrix4x4_ToBonePose7s()
void Matrix4x4_ToBonePose7s (const matrix4x4_t * m, float origininvscale, short * pose7s)
Definition at line 1614 of file matrixlib.c.
{
    float origin[3];
    float quat[4];
    float quatscale;
    Matrix4x4_ToOrigin3Quat4Float(m, origin, quat);
    // normalize quaternion so that it is unit length
    quatscale = quat[0]*quat[0]+quat[1]*quat[1]+quat[2]*quat[2]+quat[3]*quat[3];
    if (quatscale)
        quatscale = (quat[3] >= 0 ? -32767.0f : 32767.0f) / sqrt(quatscale);
    // use a negative scale on the quat because the above function produces a
    // positive quat[3] and canonical quaternions have negative quat[3]
    pose7s[0] = origin[0] * origininvscale;
    pose7s[1] = origin[1] * origininvscale;
    pose7s[2] = origin[2] * origininvscale;
    pose7s[3] = quat[0] * quatscale;
    pose7s[4] = quat[1] * quatscale;
    pose7s[5] = quat[2] * quatscale;
    pose7s[6] = quat[3] * quatscale;
}
Referenced by EntityState5_WriteUpdate(), Mod_DARKPLACESMODEL_Load(), and Mod_ZYMOTICMODEL_Load().
Matrix4x4_ToOrigin3Quat4Float()
void Matrix4x4_ToOrigin3Quat4Float (const matrix4x4_t * m, float * origin, float * quat)
Definition at line 1477 of file matrixlib.c.
{
#if 0
    float s;
    quat[3] = sqrt(1.0f + m->m[0][0] + m->m[1][1] + m->m[2][2]) * 0.5f;
    s = 0.25f / quat[3];
#ifdef MATRIX4x4_OPENGLORIENTATION
    origin[0] = m->m[3][0];
    origin[1] = m->m[3][1];
    origin[2] = m->m[3][2];
    quat[0] = (m->m[1][2] - m->m[2][1]) * s;
    quat[1] = (m->m[2][0] - m->m[0][2]) * s;
    quat[2] = (m->m[0][1] - m->m[1][0]) * s;
#else
    origin[0] = m->m[0][3];
    origin[1] = m->m[1][3];
    origin[2] = m->m[2][3];
    quat[0] = (m->m[2][1] - m->m[1][2]) * s;
    quat[1] = (m->m[0][2] - m->m[2][0]) * s;
    quat[2] = (m->m[1][0] - m->m[0][1]) * s;
#endif
#else
#ifdef MATRIX4x4_OPENGLORIENTATION
    float trace = m->m[0][0] + m->m[1][1] + m->m[2][2];
    origin[0] = m->m[3][0];
    origin[1] = m->m[3][1];
    origin[2] = m->m[3][2];
    if(trace > 0)
    {
        float r = sqrt(1.0f + trace), inv = 0.5f / r;
        quat[0] = (m->m[1][2] - m->m[2][1]) * inv;
        quat[1] = (m->m[2][0] - m->m[0][2]) * inv;
        quat[2] = (m->m[0][1] - m->m[1][0]) * inv;
        quat[3] = 0.5f * r;
    }
    else if(m->m[0][0] > m->m[1][1] && m->m[0][0] > m->m[2][2])
    {
        float r = sqrt(1.0f + m->m[0][0] - m->m[1][1] - m->m[2][2]), inv = 0.5f / r;
        quat[0] = 0.5f * r;
        quat[1] = (m->m[0][1] + m->m[1][0]) * inv;
        quat[2] = (m->m[2][0] + m->m[0][2]) * inv;
        quat[3] = (m->m[1][2] - m->m[2][1]) * inv;
    }
    else if(m->m[1][1] > m->m[2][2])
    {
        float r = sqrt(1.0f + m->m[1][1] - m->m[0][0] - m->m[2][2]), inv = 0.5f / r;
        quat[0] = (m->m[0][1] + m->m[1][0]) * inv;
        quat[1] = 0.5f * r;
        quat[2] = (m->m[1][2] + m->m[2][1]) * inv;
        quat[3] = (m->m[2][0] - m->m[0][2]) * inv;
    }
    else
    {
        float r = sqrt(1.0f + m->m[2][2] - m->m[0][0] - m->m[1][1]), inv = 0.5f / r;
        quat[0] = (m->m[2][0] + m->m[0][2]) * inv;
        quat[1] = (m->m[1][2] + m->m[2][1]) * inv;
        quat[2] = 0.5f * r;
        quat[3] = (m->m[0][1] - m->m[1][0]) * inv;
    }
#else
    float trace = m->m[0][0] + m->m[1][1] + m->m[2][2];
    origin[0] = m->m[0][3];
    origin[1] = m->m[1][3];
    origin[2] = m->m[2][3];
    if(trace > 0)
    {
        float r = sqrt(1.0f + trace), inv = 0.5f / r;
        quat[0] = (m->m[2][1] - m->m[1][2]) * inv;
        quat[1] = (m->m[0][2] - m->m[2][0]) * inv;
        quat[2] = (m->m[1][0] - m->m[0][1]) * inv;
        quat[3] = 0.5f * r;
    }
    else if(m->m[0][0] > m->m[1][1] && m->m[0][0] > m->m[2][2])
    {
        float r = sqrt(1.0f + m->m[0][0] - m->m[1][1] - m->m[2][2]), inv = 0.5f / r;
        quat[0] = 0.5f * r;
        quat[1] = (m->m[1][0] + m->m[0][1]) * inv;
        quat[2] = (m->m[0][2] + m->m[2][0]) * inv;
        quat[3] = (m->m[2][1] - m->m[1][2]) * inv;
    }
    else if(m->m[1][1] > m->m[2][2])
    {
        float r = sqrt(1.0f + m->m[1][1] - m->m[0][0] - m->m[2][2]), inv = 0.5f / r;
        quat[0] = (m->m[1][0] + m->m[0][1]) * inv;
        quat[1] = 0.5f * r;
        quat[2] = (m->m[2][1] + m->m[1][2]) * inv;
        quat[3] = (m->m[0][2] - m->m[2][0]) * inv;
    }
    else
    {
        float r = sqrt(1.0f + m->m[2][2] - m->m[0][0] - m->m[1][1]), inv = 0.5f / r;
        quat[0] = (m->m[0][2] + m->m[2][0]) * inv;
        quat[1] = (m->m[2][1] + m->m[1][2]) * inv;
        quat[2] = 0.5f * r;
        quat[3] = (m->m[1][0] - m->m[0][1]) * inv;
    }
#endif
#endif
}
Referenced by Matrix4x4_ToBonePose7s().
Matrix4x4_ToVectors()
void Matrix4x4_ToVectors (const matrix4x4_t * in, vec_t vx[3], vec_t vy[3], vec_t vz[3], vec_t t[3])
Definition at line 939 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    vx[0] = in->m[0][0];
    vx[1] = in->m[0][1];
    vx[2] = in->m[0][2];
    vy[0] = in->m[1][0];
    vy[1] = in->m[1][1];
    vy[2] = in->m[1][2];
    vz[0] = in->m[2][0];
    vz[1] = in->m[2][1];
    vz[2] = in->m[2][2];
    t [0] = in->m[3][0];
    t [1] = in->m[3][1];
    t [2] = in->m[3][2];
#else
    vx[0] = in->m[0][0];
    vx[1] = in->m[1][0];
    vx[2] = in->m[2][0];
    vy[0] = in->m[0][1];
    vy[1] = in->m[1][1];
    vy[2] = in->m[2][1];
    vz[0] = in->m[0][2];
    vz[1] = in->m[1][2];
    vz[2] = in->m[2][2];
    t [0] = in->m[0][3];
    t [1] = in->m[1][3];
    t [2] = in->m[2][3];
#endif
}
Referenced by CL_VM_TransformView(), R_Model_Sprite_Draw_TransparentCallback(), R_RenderView_UpdateViewVectors(), R_View_SetFrustum(), V_MakeViewIsometric(), VM_CL_GetEntity(), VM_CL_gettaginfo(), VM_CL_skel_get_boneabs(), VM_CL_skel_get_bonerel(), VM_SV_gettaginfo(), VM_SV_skel_get_boneabs(), and VM_SV_skel_get_bonerel().
Matrix4x4_Transform()
void Matrix4x4_Transform (const matrix4x4_t * in, const vec_t v[3], vec_t out[3])
Definition at line 1657 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[1][0] + v[2] * in->m[2][0] + in->m[3][0];
    out[1] = v[0] * in->m[0][1] + v[1] * in->m[1][1] + v[2] * in->m[2][1] + in->m[3][1];
    out[2] = v[0] * in->m[0][2] + v[1] * in->m[1][2] + v[2] * in->m[2][2] + in->m[3][2];
#else
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[0][1] + v[2] * in->m[0][2] + in->m[0][3];
    out[1] = v[0] * in->m[1][0] + v[1] * in->m[1][1] + v[2] * in->m[1][2] + in->m[1][3];
    out[2] = v[0] * in->m[2][0] + v[1] * in->m[2][1] + v[2] * in->m[2][2] + in->m[2][3];
#endif
}
Referenced by applytransform_forward(), CL_Beam_CalculatePositions(), CL_LinkNetworkEntity(), CL_RotateMoves(), CL_SelectTraceLine(), CL_UpdateNetworkEntityTrail(), CL_UpdatePrydonCursor(), Collision_ClipLineToGenericEntity(), Collision_ClipPointToGenericEntity(), Collision_ClipToGenericEntity(), Collision_TransformBrush(), Mod_Q3BSP_LightPoint(), R_DecalSystem_SplatEntity(), R_DecalSystem_SplatTriangle(), R_DrawTextureSurfaceList_Sky(), R_Mod_DrawLight(), R_ProcessTransparentTextureSurfaceList(), R_RotateSprite(), R_SetupShader_DeferredLight(), R_Shadow_CalcBBoxSideMask(), R_Shadow_ChooseSidesFromBox(), R_Shadow_ComputeShadowCasterCullingPlanes(), R_Shadow_CullFrustumSides(), R_Shadow_DrawEntityShadow(), R_Shadow_DrawModelShadowMaps(), R_Shadow_RenderMode_DrawDeferredLight(), R_Shadow_SetupEntityLight(), R_Stain(), R_TrackSprite(), R_Viewport_ApplyNearClipPlaneFloatGL(), R_Water_AddWaterPlane(), RotateBBox(), RSurf_ActiveCustomEntity(), RSurf_ActiveModelEntity(), RSurf_FindWaterPlaneForSurface(), Sbar_ShowFPS(), SND_Spatialize_WithSfx(), SV_CanSeeBox(), SV_Ent_Create_f(), SV_Ent_Remove_f(), SV_PointSuperContents(), V_ParseDamage(), VM_CL_project(), and VM_CL_unproject().
Matrix4x4_Transform3x3()
void Matrix4x4_Transform3x3 (const matrix4x4_t * in, const vec_t v[3], vec_t out[3])
Definition at line 1685 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[1][0] + v[2] * in->m[2][0];
    out[1] = v[0] * in->m[0][1] + v[1] * in->m[1][1] + v[2] * in->m[2][1];
    out[2] = v[0] * in->m[0][2] + v[1] * in->m[1][2] + v[2] * in->m[2][2];
#else
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[0][1] + v[2] * in->m[0][2];
    out[1] = v[0] * in->m[1][0] + v[1] * in->m[1][1] + v[2] * in->m[1][2];
    out[2] = v[0] * in->m[2][0] + v[1] * in->m[2][1] + v[2] * in->m[2][2];
#endif
}
Referenced by applytransform_forward_direction(), applytransform_inverted(), CL_SelectTraceLine(), CL_UpdateEntityShading_Entity(), R_DecalSystem_SplatEntity(), R_Shadow_CalcBBoxSideMask(), R_Shadow_CullFrustumSides(), R_Shadow_DrawModelShadowMaps(), R_Viewport_ApplyNearClipPlaneFloatGL(), R_Water_AddWaterPlane(), and RSurf_PrepareVerticesForBatch().
Matrix4x4_Transform4()
void Matrix4x4_Transform4 (const matrix4x4_t * in, const vec_t v[4], vec_t out[4])
Definition at line 1670 of file matrixlib.c.
{
#ifdef MATRIX4x4_OPENGLORIENTATION
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[1][0] + v[2] * in->m[2][0] + v[3] * in->m[3][0];
    out[1] = v[0] * in->m[0][1] + v[1] * in->m[1][1] + v[2] * in->m[2][1] + v[3] * in->m[3][1];
    out[2] = v[0] * in->m[0][2] + v[1] * in->m[1][2] + v[2] * in->m[2][2] + v[3] * in->m[3][2];
    out[3] = v[0] * in->m[0][3] + v[1] * in->m[1][3] + v[2] * in->m[2][3] + v[3] * in->m[3][3];
#else
    out[0] = v[0] * in->m[0][0] + v[1] * in->m[0][1] + v[2] * in->m[0][2] + v[3] * in->m[0][3];
    out[1] = v[0] * in->m[1][0] + v[1] * in->m[1][1] + v[2] * in->m[1][2] + v[3] * in->m[1][3];
    out[2] = v[0] * in->m[2][0] + v[1] * in->m[2][1] + v[2] * in->m[2][2] + v[3] * in->m[2][3];
    out[3] = v[0] * in->m[3][0] + v[1] * in->m[3][1] + v[2] * in->m[3][2] + v[3] * in->m[3][3];
#endif
}
Referenced by R_Viewport_TransformToScreen().
Matrix4x4_TransformPositivePlane()
void Matrix4x4_TransformPositivePlane (const matrix4x4_t * in, vec_t x, vec_t y, vec_t z, vec_t d, vec_t * o)
Definition at line 1699 of file matrixlib.c.
{
    float scale = sqrt(in->m[0][0] * in->m[0][0] + in->m[0][1] * in->m[0][1] + in->m[0][2] * in->m[0][2]);
    float iscale = 1.0f / scale;
#ifdef MATRIX4x4_OPENGLORIENTATION
    o[0] = (x * in->m[0][0] + y * in->m[1][0] + z * in->m[2][0]) * iscale;
    o[1] = (x * in->m[0][1] + y * in->m[1][1] + z * in->m[2][1]) * iscale;
    o[2] = (x * in->m[0][2] + y * in->m[1][2] + z * in->m[2][2]) * iscale;
    o[3] = d * scale + (o[0] * in->m[3][0] + o[1] * in->m[3][1] + o[2] * in->m[3][2]);
#else
    o[0] = (x * in->m[0][0] + y * in->m[0][1] + z * in->m[0][2]) * iscale;
    o[1] = (x * in->m[1][0] + y * in->m[1][1] + z * in->m[1][2]) * iscale;
    o[2] = (x * in->m[2][0] + y * in->m[2][1] + z * in->m[2][2]) * iscale;
    o[3] = d * scale + (o[0] * in->m[0][3] + o[1] * in->m[1][3] + o[2] * in->m[2][3]);
#endif
}
Referenced by applytransform_forward_normal(), CL_VM_TransformView(), Collision_ClipLineToGenericEntity(), Collision_ClipPointToGenericEntity(), Collision_ClipToGenericEntity(), and Collision_TransformBrush().
Matrix4x4_TransformStandardPlane()
void Matrix4x4_TransformStandardPlane (const matrix4x4_t * in, vec_t x, vec_t y, vec_t z, vec_t d, vec_t * o)
Definition at line 1717 of file matrixlib.c.
{
    float scale = sqrt(in->m[0][0] * in->m[0][0] + in->m[0][1] * in->m[0][1] + in->m[0][2] * in->m[0][2]);
    float iscale = 1.0f / scale;
#ifdef MATRIX4x4_OPENGLORIENTATION
    o[0] = (x * in->m[0][0] + y * in->m[1][0] + z * in->m[2][0]) * iscale;
    o[1] = (x * in->m[0][1] + y * in->m[1][1] + z * in->m[2][1]) * iscale;
    o[2] = (x * in->m[0][2] + y * in->m[1][2] + z * in->m[2][2]) * iscale;
    o[3] = d * scale - (o[0] * in->m[3][0] + o[1] * in->m[3][1] + o[2] * in->m[3][2]);
#else
    o[0] = (x * in->m[0][0] + y * in->m[0][1] + z * in->m[0][2]) * iscale;
    o[1] = (x * in->m[1][0] + y * in->m[1][1] + z * in->m[1][2]) * iscale;
    o[2] = (x * in->m[2][0] + y * in->m[2][1] + z * in->m[2][2]) * iscale;
    o[3] = d * scale - (o[0] * in->m[0][3] + o[1] * in->m[1][3] + o[2] * in->m[2][3]);
#endif
}
Referenced by RSurf_ActiveCustomEntity(), and RSurf_ActiveModelEntity().
Matrix4x4_Transpose()
void Matrix4x4_Transpose (matrix4x4_t * out, const matrix4x4_t * in1)
Definition at line 122 of file matrixlib.c.
{
    out->m[0][0] = in1->m[0][0];
    out->m[0][1] = in1->m[1][0];
    out->m[0][2] = in1->m[2][0];
    out->m[0][3] = in1->m[3][0];
    out->m[1][0] = in1->m[0][1];
    out->m[1][1] = in1->m[1][1];
    out->m[1][2] = in1->m[2][1];
    out->m[1][3] = in1->m[3][1];
    out->m[2][0] = in1->m[0][2];
    out->m[2][1] = in1->m[1][2];
    out->m[2][2] = in1->m[2][2];
    out->m[2][3] = in1->m[3][2];
    out->m[3][0] = in1->m[0][3];
    out->m[3][1] = in1->m[1][3];
    out->m[3][2] = in1->m[2][3];
    out->m[3][3] = in1->m[3][3];
}
Variable Documentation
identitymatrix
const matrix4x4_t identitymatrix extern
Definition at line 9 of file matrixlib.c.
{
    {
        {1, 0, 0, 0},
        {0, 1, 0, 0},
        {0, 0, 1, 0},
        {0, 0, 0, 1}
    }
};
Referenced by CL_GetEntityLocalTagMatrix(), CL_GetTagMatrix(), CL_RelinkWorld(), CL_UpdateNetworkEntity(), CL_UpdateScreen(), CL_UpdateWorld(), Collision_Cache_ClipLineToWorldSurfaces(), EntityState5_ReadUpdate(), getmatrix(), Mod_Alias_GetTagMatrix(), R_BlendView(), R_Bloom_MakeTexture(), R_DrawCorona(), R_DrawExplosion_TransparentCallback(), R_DrawLoc_Callback(), R_DrawPortal_Callback(), R_Model_Sprite_Draw_TransparentCallback(), R_MotionBlurView(), R_ResetViewRendering2D_Common(), R_ResetViewRendering3D(), R_Shadow_ClearShadowMapTexture(), R_Shadow_DrawCoronas(), R_Shadow_DrawCursor_TransparentCallback(), R_Shadow_DrawLightSprite_TransparentCallback(), R_Shadow_RenderMode_DrawDeferredLight(), R_SkyBox(), R_tcMod_ApplyToMatrix(), SV_GetEntityLocalTagMatrix(), SV_GetTagMatrix(), V_CalcRefdef(), V_CalcRefdefUsing(), VM_CL_skel_create(), and VM_SV_skel_create().