DarkPlaces: mdfour.h File Reference
mdfour.h File Reference
#include <stdint.h>
Data Structures
struct mdfour_s
Functions
void mdfour_begin (struct mdfour_s *md)
void mdfour_update (struct mdfour_s *md, const unsigned char *in, int n)
void mdfour_result (struct mdfour_s *md, unsigned char *out)
void mdfour (unsigned char *out, const unsigned char *in, int n)
Function Documentation
mdfour()
void mdfour (unsigned char * out, const unsigned char * in, int n)
Definition at line 182 of file mdfour.c.
{
    struct mdfour_s md;
    mdfour_begin(&md);
    mdfour_update(&md, in, n);
    mdfour_result(&md, out);
}
Referenced by Com_BlockChecksum(), Com_BlockFullChecksum(), and VM_digest_hex().
mdfour_begin()
void mdfour_begin (struct mdfour_s * md)
Definition at line 115 of file mdfour.c.
{
    md->A = 0x67452301;
    md->B = 0xefcdab89;
    md->C = 0x98badcfe;
    md->D = 0x10325476;
    md->totalN = 0;
}
Referenced by mdfour().
mdfour_result()
void mdfour_result (struct mdfour_s * md, unsigned char * out)
Definition at line 173 of file mdfour.c.
{
    copy4(out, md->A);
    copy4(out+4, md->B);
    copy4(out+8, md->C);
    copy4(out+12, md->D);
}
Referenced by mdfour().
mdfour_update()
void mdfour_update (struct mdfour_s * md, const unsigned char * in, int n)
Definition at line 152 of file mdfour.c.
{
    uint32_t M[16];
// start of edit by Ashley Rose Hale (LadyHavoc)
// commented out to prevent crashing when length is 0
//  if (n == 0) mdfour_tail(in, n);
// end of edit by Ashley Rose Hale (LadyHavoc)
    while (n >= 64) {
        copy64(M, in);
        mdfour64(md, M);
        in += 64;
        n -= 64;
        md->totalN += 64;
    }
    mdfour_tail(md, in, n);
}
Referenced by mdfour().