DarkPlaces: menu.c File Reference
menu.c File Reference
#include "quakedef.h"
#include "cdaudio.h"
#include "image.h"
#include "progsvm.h"
#include "mprogdefs.h"
#include "prvm_offsets.h"
Data Structures
struct nehahrademonames_t
struct ratetable_t
struct level_t
struct episode_t
struct gamelevels_t
struct gameinfo_t
struct modlist_entry_t
Macros
#define TYPE_DEMO 1
#define TYPE_GAME 2
#define TYPE_BOTH 3
#define StartingGame (m_multiplayer_cursor == 1)
#define JoiningGame (m_multiplayer_cursor == 0)
#define NumberOfNehahraDemos 34
#define SINGLEPLAYER_ITEMS 3
#define EPISODE_ITEMS 6
#define SKILL_ITEMS 5
#define MULTIPLAYER_ITEMS 3
#define NUM_SETUP_CMDS 5
#define RATES ((int)(sizeof(setup_ratetable)/sizeof(setup_ratetable[0])))
#define SLIDER_RANGE 10
#define OPTIONS_ITEMS 27
#define OPTIONS_EFFECTS_ITEMS 35
#define OPTIONS_GRAPHICS_ITEMS 20
#define OPTIONS_COLORCONTROL_ITEMS 18
#define NUMKEYS 5
#define VIDEO_ITEMS 10
#define NUM_HELP_PAGES 6
#define NUM_LANCONFIG_CMDS 4
#define NUM_GAMEOPTIONS 12
#define MODLIST_MAXDIRS 16
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x)
#define PRVM_DECLARE_menuglobalvector(x)
#define PRVM_DECLARE_menuglobalstring(x)
#define PRVM_DECLARE_menuglobaledict(x)
#define PRVM_DECLARE_menuglobalfunction(x)
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x) {ev_float, #x},
#define PRVM_DECLARE_menufieldvector(x) {ev_vector, #x},
#define PRVM_DECLARE_menufieldstring(x) {ev_string, #x},
#define PRVM_DECLARE_menufieldedict(x) {ev_entity, #x},
#define PRVM_DECLARE_menufieldfunction(x) {ev_function, #x},
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x)
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x) {ev_float, #x},
#define PRVM_DECLARE_menuglobalvector(x) {ev_vector, #x},
#define PRVM_DECLARE_menuglobalstring(x) {ev_string, #x},
#define PRVM_DECLARE_menuglobaledict(x) {ev_entity, #x},
#define PRVM_DECLARE_menuglobalfunction(x) {ev_function, #x},
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x)
#define PRVM_DECLARE_menufieldvector(x)
#define PRVM_DECLARE_menufieldstring(x)
#define PRVM_DECLARE_menufieldedict(x)
#define PRVM_DECLARE_menufieldfunction(x)
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x)
Functions
void M_Menu_Main_f (cmd_state_t *cmd)
void M_Menu_SinglePlayer_f (cmd_state_t *cmd)
void M_Menu_Transfusion_Episode_f (cmd_state_t *cmd)
void M_Menu_Transfusion_Skill_f (cmd_state_t *cmd)
void M_Menu_Load_f (cmd_state_t *cmd)
void M_Menu_Save_f (cmd_state_t *cmd)
void M_Menu_MultiPlayer_f (cmd_state_t *cmd)
void M_Menu_Setup_f (cmd_state_t *cmd)
void M_Menu_Options_f (cmd_state_t *cmd)
void M_Menu_Options_Effects_f (cmd_state_t *cmd)
void M_Menu_Options_Graphics_f (cmd_state_t *cmd)
void M_Menu_Options_ColorControl_f (cmd_state_t *cmd)
void M_Menu_Keys_f (cmd_state_t *cmd)
void M_Menu_Reset_f (cmd_state_t *cmd)
void M_Menu_Video_f (cmd_state_t *cmd)
void M_Menu_Help_f (cmd_state_t *cmd)
void M_Menu_Credits_f (cmd_state_t *cmd)
void M_Menu_Quit_f (cmd_state_t *cmd)
void M_Menu_LanConfig_f (cmd_state_t *cmd)
void M_Menu_GameOptions_f (cmd_state_t *cmd)
void M_Menu_ServerList_f (cmd_state_t *cmd)
void M_Menu_ModList_f (cmd_state_t *cmd)
static void M_Main_Draw (void)
static void M_SinglePlayer_Draw (void)
static void M_Transfusion_Episode_Draw (void)
static void M_Transfusion_Skill_Draw (void)
static void M_Load_Draw (void)
static void M_Save_Draw (void)
static void M_MultiPlayer_Draw (void)
static void M_Setup_Draw (void)
static void M_Options_Draw (void)
static void M_Options_Effects_Draw (void)
static void M_Options_Graphics_Draw (void)
static void M_Options_ColorControl_Draw (void)
static void M_Keys_Draw (void)
static void M_Reset_Draw (void)
static void M_Video_Draw (void)
static void M_Help_Draw (void)
static void M_Credits_Draw (void)
static void M_Quit_Draw (void)
static void M_LanConfig_Draw (void)
static void M_GameOptions_Draw (void)
static void M_ServerList_Draw (void)
static void M_ModList_Draw (void)
static void M_Main_Key (cmd_state_t *cmd, int key, int ascii)
static void M_SinglePlayer_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Transfusion_Episode_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Transfusion_Skill_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Load_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Save_Key (cmd_state_t *cmd, int key, int ascii)
static void M_MultiPlayer_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Setup_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Options_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Options_Effects_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Options_Graphics_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Options_ColorControl_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Keys_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Reset_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Video_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Help_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Credits_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Quit_Key (cmd_state_t *cmd, int key, int ascii)
static void M_LanConfig_Key (cmd_state_t *cmd, int key, int ascii)
static void M_GameOptions_Key (cmd_state_t *cmd, int key, int ascii)
static void M_ServerList_Key (cmd_state_t *cmd, int key, int ascii)
static void M_ModList_Key (cmd_state_t *cmd, int key, int ascii)
static void M_Background (int width, int height)
static void M_DrawCharacter (float cx, float cy, int num)
static void M_PrintColored (float cx, float cy, const char *str)
static void M_Print (float cx, float cy, const char *str)
static void M_PrintRed (float cx, float cy, const char *str)
static void M_ItemPrint (float cx, float cy, const char *str, int unghosted)
static void M_DrawPic (float cx, float cy, const char *picname)
static void M_DrawTextBox (float x, float y, float width, float height)
static void M_ToggleMenu (int mode)
static void M_Demo_Draw (void)
static void M_Menu_Demos_f (cmd_state_t *cmd)
static void M_Demo_Key (cmd_state_t *cmd, int k, int ascii)
static void M_ScanSaves (void)
static int setup_rateindex (int rate)
static void M_DrawSlider (int x, int y, float num, float rangemin, float rangemax)
static void M_DrawCheckbox (int x, int y, int on)
static void M_Menu_Options_AdjustSliders (int dir)
static void M_Options_PrintCommand (const char *s, int enabled)
static void M_Options_PrintCheckbox (const char *s, int enabled, int yes)
static void M_Options_PrintSlider (const char *s, int enabled, float value, float minvalue, float maxvalue)
static void M_Menu_Options_Effects_AdjustSliders (int dir)
static void M_Menu_Options_Graphics_AdjustSliders (cmd_state_t *cmd, int dir)
static void M_Menu_Options_ColorControl_AdjustSliders (int dir)
static void M_UnbindCommand (const char *command)
static void M_Menu_Video_FindResolution (int w, int h, float a)
static void M_Menu_Video_AdjustSliders (int dir)
static int M_QuitMessage (const char *line1, const char *line2, const char *line3, const char *line4, const char *line5, const char *line6, const char *line7, const char *line8)
static int M_ChooseQuitMessage (int request)
static void M_NetStart_Change (int dir)
static void ModList_RebuildList (void)
static void ModList_Enable (void)
static void M_Menu_ModList_AdjustSliders (int dir)
static void M_KeyEvent (int key, int ascii, qbool downevent)
static void M_Draw (void)
static void M_Shutdown (void)
static void M_Init (void)
static void M_NewMap (void)
static int M_GetServerListEntryCategory (const serverlist_entry_t *entry)
void MR_SetRouting (qbool forceold)
void MVM_error_cmd (const char *format,...) DP_FUNC_PRINTF(1)
static void MVM_begin_increase_edicts (prvm_prog_t *prog)
static void MVM_end_increase_edicts (prvm_prog_t *prog)
static void MVM_init_edict (prvm_prog_t *prog, prvm_edict_t *edict)
static void MVM_free_edict (prvm_prog_t *prog, prvm_edict_t *ed)
static void MVM_count_edicts (prvm_prog_t *prog)
static qbool MVM_load_edict (prvm_prog_t *prog, prvm_edict_t *ent)
static void MP_KeyEvent (int key, int ascii, qbool downevent)
static void MP_Draw (void)
static void MP_ToggleMenu (int mode)
static void MP_NewMap (void)
static int MP_GetServerListEntryCategory (const serverlist_entry_t *entry)
static void MP_Shutdown (void)
static void MP_Init (void)
void MR_Restart (void)
static void MR_Restart_f (cmd_state_t *cmd)
static void Call_MR_ToggleMenu_f (cmd_state_t *cmd)
void MR_Init_Commands (void)
void MR_Init (void)
Variables
static cvar_t forceqmenu = {CF_CLIENT, "forceqmenu", "0", "enables the quake menu instead of the quakec menu.dat (if present)"}
static cvar_t menu_progs = {CF_CLIENT, "menu_progs", "menu.dat", "name of quakec menu.dat file"}
static int NehGameType
enum m_state_e m_state
static qbool m_entersound
play after drawing a frame, so caching won't disrupt the sound
static nehahrademonames_t NehahraDemos [NumberOfNehahraDemos]
static float menu_x
static float menu_y
static float menu_width
static float menu_height
static int demo_cursor
static int m_main_cursor
static qbool m_missingdata = false
static int MAIN_ITEMS = 4
static int m_singleplayer_cursor
static int load_cursor
0 < load_cursor < MAX_SAVEGAMES
static char m_filenames [MAX_SAVEGAMES][SAVEGAME_COMMENT_LENGTH+1]
static int loadable [MAX_SAVEGAMES]
static int m_episode_cursor
static int m_skill_cursor = 2
static int m_multiplayer_cursor
static int setup_cursor = 4
static int setup_cursor_table [] = {40, 64, 88, 124, 140}
static char setup_myname [MAX_SCOREBOARDNAME]
static int setup_oldtop
static int setup_oldbottom
static int setup_top
static int setup_bottom
static int setup_rate
static int setup_oldrate
cvar_t cl_topcolor
cvar_t cl_bottomcolor
static int menuplyr_width
static int menuplyr_height
static int menuplyr_top
static int menuplyr_bottom
static int menuplyr_load
static unsigned char * menuplyr_pixels
static unsigned int * menuplyr_translated
static ratetable_t setup_ratetable []
static int options_cursor
cvar_t host_timescale
dllhandle_t jpeg_dll
cvar_t gl_texture_anisotropy
cvar_t r_textshadow
cvar_t r_hdr_scenebrightness
static int m_optnum
static int m_opty
static int m_optcursor
static int options_effects_cursor
cvar_t cl_stainmaps
cvar_t cl_stainmaps_clearonload
cvar_t r_explosionclip
cvar_t r_coronas
cvar_t gl_flashblend
cvar_t cl_beams_polygons
cvar_t cl_beams_quakepositionhack
cvar_t cl_beams_instantaimhack
cvar_t cl_beams_lightatend
cvar_t r_lightningbeam_thickness
cvar_t r_lightningbeam_scroll
cvar_t r_lightningbeam_repeatdistance
cvar_t r_lightningbeam_color_red
cvar_t r_lightningbeam_color_green
cvar_t r_lightningbeam_color_blue
cvar_t r_lightningbeam_qmbtexture
static int options_graphics_cursor
cvar_t r_shadow_gloss
cvar_t r_shadow_realtime_dlight
cvar_t r_shadow_realtime_dlight_shadows
cvar_t r_shadow_realtime_world
cvar_t r_shadow_realtime_world_lightmaps
cvar_t r_shadow_realtime_world_shadows
cvar_t r_bloom
cvar_t r_bloom_colorscale
cvar_t r_bloom_colorsubtract
cvar_t r_bloom_colorexponent
cvar_t r_bloom_blur
cvar_t r_bloom_brighten
cvar_t r_bloom_resolution
cvar_t r_hdr_glowintensity
cvar_t gl_picmip
static int options_colorcontrol_cursor
static cvar_t menu_options_colorcontrol_correctionvalue = {CF_CLIENT, "menu_options_colorcontrol_correctionvalue", "0.5", "intensity value that matches up to white/black dither pattern, should be 0.5 for linear color"}
static const char * quakebindnames [][2]
static const char * transfusionbindnames [][2]
static const char * goodvsbad2bindnames [][2]
static int numcommands
static const char *(* bindnames)[2]
static int keys_cursor
static int bind_grab
video_resolution_t video_resolutions_hardcoded []
int video_resolutions_hardcoded_count = sizeof(video_resolutions_hardcoded) / sizeof(*video_resolutions_hardcoded) - 1
static int video_cursor = 0
static int video_cursor_table [VIDEO_ITEMS] = {68, 88, 96, 104, 112, 120, 128, 136, 144, 152}
static int menu_video_resolution
video_resolution_t * video_resolutions
int video_resolutions_count
static video_resolution_t * menu_video_resolutions
static int menu_video_resolutions_count
static qbool menu_video_resolutions_forfullscreen
static int help_page
static const char * m_quit_message [9]
static int m_quit_prevstate
static qbool wasInMenus
static int lanConfig_cursor = -1
static int lanConfig_cursor_table [] = {56, 76, 84, 120}
static int lanConfig_port
static char lanConfig_portname [6]
static char lanConfig_joinname [40]
static level_t quakelevels []
static episode_t quakeepisodes []
static level_t hipnoticlevels []
static episode_t hipnoticepisodes []
static level_t roguelevels []
static episode_t rogueepisodes []
static level_t nehahralevels []
static episode_t nehahraepisodes []
static level_t transfusionlevels []
static episode_t transfusionepisodes []
static level_t goodvsbad2levels []
static episode_t goodvsbad2episodes []
static level_t battlemechlevels []
static episode_t battlemechepisodes []
static level_t openquartzlevels []
static episode_t openquartzepisodes []
static level_t defeatindetail2levels []
static episode_t defeatindetail2episodes []
static level_t prydonlevels []
static episode_t prydonepisodes []
static gamelevels_t sharewarequakegame = {"Shareware Quake", quakelevels, quakeepisodes, 2}
static gamelevels_t registeredquakegame = {"Quake", quakelevels, quakeepisodes, 7}
static gamelevels_t hipnoticgame = {"Scourge of Armagon", hipnoticlevels, hipnoticepisodes, 6}
static gamelevels_t roguegame = {"Dissolution of Eternity", roguelevels, rogueepisodes, 4}
static gamelevels_t nehahragame = {"Nehahra", nehahralevels, nehahraepisodes, 4}
static gamelevels_t transfusiongame = {"Transfusion", transfusionlevels, transfusionepisodes, 11}
static gamelevels_t goodvsbad2game = {"Good Vs. Bad 2", goodvsbad2levels, goodvsbad2episodes, 1}
static gamelevels_t battlemechgame = {"Battlemech", battlemechlevels, battlemechepisodes, 1}
static gamelevels_t openquartzgame = {"OpenQuartz", openquartzlevels, openquartzepisodes, 3}
static gamelevels_t defeatindetail2game = {"Defeat In Detail 2", defeatindetail2levels, defeatindetail2episodes, 1}
static gamelevels_t prydongame = {"Prydon Gate", prydonlevels, prydonepisodes, 2}
static gameinfo_t gamelist []
static gamelevels_t * gameoptions_levels = NULL
static int startepisode
static int startlevel
static int maxplayers
static qbool m_serverInfoMessage = false
static double m_serverInfoMessageTime
static int gameoptions_cursor_table [] = {40, 56, 64, 72, 80, 88, 96, 104, 112, 140, 160, 168}
static int gameoptions_cursor
static unsigned slist_cursor
static unsigned slist_visible
static int modlist_enabled [MODLIST_MAXDIRS]
static int modlist_numenabled
static int modlist_cursor
static int modlist_count = 0
static modlist_entry_t modlist [MODLIST_TOTALSIZE]
static const char * m_required_func []
static int m_numrequiredfunc = sizeof(m_required_func) / sizeof(char*)
static prvm_required_field_t m_required_fields []
static int m_numrequiredfields = sizeof(m_required_fields) / sizeof(m_required_fields[0])
static prvm_required_field_t m_required_globals []
static int m_numrequiredglobals = sizeof(m_required_globals) / sizeof(m_required_globals[0])
const serverlist_entry_t * serverlist_callbackentry = NULL
void(* MR_KeyEvent)(int key, int ascii, qbool downevent)
void(* MR_Draw)(void)
void(* MR_ToggleMenu)(int mode)
void(* MR_Shutdown)(void)
void(* MR_NewMap)(void)
int(* MR_GetServerListEntryCategory)(const serverlist_entry_t *entry)
Macro Definition Documentation
EPISODE_ITEMS
#define EPISODE_ITEMS 6
Definition at line 1028 of file menu.c.
JoiningGame
#define JoiningGame (m_multiplayer_cursor == 0)
Definition at line 111 of file menu.c.
MODLIST_MAXDIRS
#define MODLIST_MAXDIRS 16
Definition at line 4510 of file menu.c.
MULTIPLAYER_ITEMS
#define MULTIPLAYER_ITEMS 3
Definition at line 1187 of file menu.c.
NUM_GAMEOPTIONS
#define NUM_GAMEOPTIONS 12
Definition at line 3966 of file menu.c.
NUM_HELP_PAGES
#define NUM_HELP_PAGES 6
Definition at line 3085 of file menu.c.
NUM_LANCONFIG_CMDS
#define NUM_LANCONFIG_CMDS 4
Definition at line 3318 of file menu.c.
NUM_SETUP_CMDS
#define NUM_SETUP_CMDS 5
Definition at line 1277 of file menu.c.
NumberOfNehahraDemos
#define NumberOfNehahraDemos 34
Definition at line 114 of file menu.c.
NUMKEYS
#define NUMKEYS 5
Definition at line 2580 of file menu.c.
OPTIONS_COLORCONTROL_ITEMS
#define OPTIONS_COLORCONTROL_ITEMS 18
Definition at line 2093 of file menu.c.
OPTIONS_EFFECTS_ITEMS
#define OPTIONS_EFFECTS_ITEMS 35
Definition at line 1800 of file menu.c.
OPTIONS_GRAPHICS_ITEMS
#define OPTIONS_GRAPHICS_ITEMS 20
Definition at line 1963 of file menu.c.
OPTIONS_ITEMS
#define OPTIONS_ITEMS 27
Definition at line 1567 of file menu.c.
PRVM_DECLARE_clientfieldedict [1/2]
#define PRVM_DECLARE_clientfieldedict (x)
PRVM_DECLARE_clientfieldedict [2/2]
#define PRVM_DECLARE_clientfieldedict (x)
PRVM_DECLARE_clientfieldfloat [1/2]
#define PRVM_DECLARE_clientfieldfloat (x)
PRVM_DECLARE_clientfieldfloat [2/2]
#define PRVM_DECLARE_clientfieldfloat (x)
PRVM_DECLARE_clientfieldfunction [1/2]
#define PRVM_DECLARE_clientfieldfunction (x)
PRVM_DECLARE_clientfieldfunction [2/2]
#define PRVM_DECLARE_clientfieldfunction (x)
PRVM_DECLARE_clientfieldstring [1/2]
#define PRVM_DECLARE_clientfieldstring (x)
PRVM_DECLARE_clientfieldstring [2/2]
#define PRVM_DECLARE_clientfieldstring (x)
PRVM_DECLARE_clientfieldvector [1/2]
#define PRVM_DECLARE_clientfieldvector (x)
PRVM_DECLARE_clientfieldvector [2/2]
#define PRVM_DECLARE_clientfieldvector (x)
PRVM_DECLARE_clientfunction [1/2]
#define PRVM_DECLARE_clientfunction (x)
PRVM_DECLARE_clientfunction [2/2]
#define PRVM_DECLARE_clientfunction (x)
PRVM_DECLARE_clientglobaledict [1/2]
#define PRVM_DECLARE_clientglobaledict (x)
PRVM_DECLARE_clientglobaledict [2/2]
#define PRVM_DECLARE_clientglobaledict (x)
PRVM_DECLARE_clientglobalfloat [1/2]
#define PRVM_DECLARE_clientglobalfloat (x)
PRVM_DECLARE_clientglobalfloat [2/2]
#define PRVM_DECLARE_clientglobalfloat (x)
PRVM_DECLARE_clientglobalfunction [1/2]
#define PRVM_DECLARE_clientglobalfunction (x)
PRVM_DECLARE_clientglobalfunction [2/2]
#define PRVM_DECLARE_clientglobalfunction (x)
PRVM_DECLARE_clientglobalstring [1/2]
#define PRVM_DECLARE_clientglobalstring (x)
PRVM_DECLARE_clientglobalstring [2/2]
#define PRVM_DECLARE_clientglobalstring (x)
PRVM_DECLARE_clientglobalvector [1/2]
#define PRVM_DECLARE_clientglobalvector (x)
PRVM_DECLARE_clientglobalvector [2/2]
#define PRVM_DECLARE_clientglobalvector (x)
PRVM_DECLARE_field [1/2]
#define PRVM_DECLARE_field (x)
PRVM_DECLARE_field [2/2]
#define PRVM_DECLARE_field (x)
PRVM_DECLARE_function [1/2]
#define PRVM_DECLARE_function (x)
PRVM_DECLARE_function [2/2]
#define PRVM_DECLARE_function (x)
PRVM_DECLARE_global [1/2]
#define PRVM_DECLARE_global (x)
PRVM_DECLARE_global [2/2]
#define PRVM_DECLARE_global (x)
PRVM_DECLARE_menufieldedict [1/2]
#define PRVM_DECLARE_menufieldedict (x) {ev_entity, #x},
PRVM_DECLARE_menufieldedict [2/2]
#define PRVM_DECLARE_menufieldedict (x)
PRVM_DECLARE_menufieldfloat [1/2]
#define PRVM_DECLARE_menufieldfloat (x) {ev_float, #x},
PRVM_DECLARE_menufieldfloat [2/2]
#define PRVM_DECLARE_menufieldfloat (x)
PRVM_DECLARE_menufieldfunction [1/2]
#define PRVM_DECLARE_menufieldfunction (x) {ev_function, #x},
PRVM_DECLARE_menufieldfunction [2/2]
#define PRVM_DECLARE_menufieldfunction (x)
PRVM_DECLARE_menufieldstring [1/2]
#define PRVM_DECLARE_menufieldstring (x) {ev_string, #x},
PRVM_DECLARE_menufieldstring [2/2]
#define PRVM_DECLARE_menufieldstring (x)
PRVM_DECLARE_menufieldvector [1/2]
#define PRVM_DECLARE_menufieldvector (x) {ev_vector, #x},
PRVM_DECLARE_menufieldvector [2/2]
#define PRVM_DECLARE_menufieldvector (x)
PRVM_DECLARE_menufunction [1/2]
#define PRVM_DECLARE_menufunction (x)
PRVM_DECLARE_menufunction [2/2]
#define PRVM_DECLARE_menufunction (x)
PRVM_DECLARE_menuglobaledict [1/2]
#define PRVM_DECLARE_menuglobaledict (x)
PRVM_DECLARE_menuglobaledict [2/2]
#define PRVM_DECLARE_menuglobaledict (x) {ev_entity, #x},
PRVM_DECLARE_menuglobalfloat [1/2]
#define PRVM_DECLARE_menuglobalfloat (x)
PRVM_DECLARE_menuglobalfloat [2/2]
#define PRVM_DECLARE_menuglobalfloat (x) {ev_float, #x},
PRVM_DECLARE_menuglobalfunction [1/2]
#define PRVM_DECLARE_menuglobalfunction (x)
PRVM_DECLARE_menuglobalfunction [2/2]
#define PRVM_DECLARE_menuglobalfunction (x) {ev_function, #x},
PRVM_DECLARE_menuglobalstring [1/2]
#define PRVM_DECLARE_menuglobalstring (x)
PRVM_DECLARE_menuglobalstring [2/2]
#define PRVM_DECLARE_menuglobalstring (x) {ev_string, #x},
PRVM_DECLARE_menuglobalvector [1/2]
#define PRVM_DECLARE_menuglobalvector (x)
PRVM_DECLARE_menuglobalvector [2/2]
#define PRVM_DECLARE_menuglobalvector (x) {ev_vector, #x},
PRVM_DECLARE_serverfieldedict [1/2]
#define PRVM_DECLARE_serverfieldedict (x)
PRVM_DECLARE_serverfieldedict [2/2]
#define PRVM_DECLARE_serverfieldedict (x)
PRVM_DECLARE_serverfieldfloat [1/2]
#define PRVM_DECLARE_serverfieldfloat (x)
PRVM_DECLARE_serverfieldfloat [2/2]
#define PRVM_DECLARE_serverfieldfloat (x)
PRVM_DECLARE_serverfieldfunction [1/2]
#define PRVM_DECLARE_serverfieldfunction (x)
PRVM_DECLARE_serverfieldfunction [2/2]
#define PRVM_DECLARE_serverfieldfunction (x)
PRVM_DECLARE_serverfieldstring [1/2]
#define PRVM_DECLARE_serverfieldstring (x)
PRVM_DECLARE_serverfieldstring [2/2]
#define PRVM_DECLARE_serverfieldstring (x)
PRVM_DECLARE_serverfieldvector [1/2]
#define PRVM_DECLARE_serverfieldvector (x)
PRVM_DECLARE_serverfieldvector [2/2]
#define PRVM_DECLARE_serverfieldvector (x)
PRVM_DECLARE_serverfunction [1/2]
#define PRVM_DECLARE_serverfunction (x)
PRVM_DECLARE_serverfunction [2/2]
#define PRVM_DECLARE_serverfunction (x)
PRVM_DECLARE_serverglobaledict [1/2]
#define PRVM_DECLARE_serverglobaledict (x)
PRVM_DECLARE_serverglobaledict [2/2]
#define PRVM_DECLARE_serverglobaledict (x)
PRVM_DECLARE_serverglobalfloat [1/2]
#define PRVM_DECLARE_serverglobalfloat (x)
PRVM_DECLARE_serverglobalfloat [2/2]
#define PRVM_DECLARE_serverglobalfloat (x)
PRVM_DECLARE_serverglobalfunction [1/2]
#define PRVM_DECLARE_serverglobalfunction (x)
PRVM_DECLARE_serverglobalfunction [2/2]
#define PRVM_DECLARE_serverglobalfunction (x)
PRVM_DECLARE_serverglobalstring [1/2]
#define PRVM_DECLARE_serverglobalstring (x)
PRVM_DECLARE_serverglobalstring [2/2]
#define PRVM_DECLARE_serverglobalstring (x)
PRVM_DECLARE_serverglobalvector [1/2]
#define PRVM_DECLARE_serverglobalvector (x)
PRVM_DECLARE_serverglobalvector [2/2]
#define PRVM_DECLARE_serverglobalvector (x)
RATES
#define RATES ((int)(sizeof(setup_ratetable)/sizeof(setup_ratetable[0])))
Definition at line 1304 of file menu.c.
SINGLEPLAYER_ITEMS
#define SINGLEPLAYER_ITEMS 3
Definition at line 727 of file menu.c.
SKILL_ITEMS
#define SKILL_ITEMS 5
Definition at line 1086 of file menu.c.
SLIDER_RANGE
#define SLIDER_RANGE 10
Definition at line 1537 of file menu.c.
StartingGame
#define StartingGame (m_multiplayer_cursor == 1)
Definition at line 110 of file menu.c.
TYPE_BOTH
#define TYPE_BOTH 3
Definition at line 29 of file menu.c.
TYPE_DEMO
#define TYPE_DEMO 1
Definition at line 27 of file menu.c.
TYPE_GAME
#define TYPE_GAME 2
Definition at line 28 of file menu.c.
VIDEO_ITEMS
#define VIDEO_ITEMS 10
Definition at line 2833 of file menu.c.
Function Documentation
Call_MR_ToggleMenu_f()
static void Call_MR_ToggleMenu_f (cmd_state_t * cmd) static
Definition at line 5482 of file menu.c.
{
    int m;
    m = ((Cmd_Argc(cmd) < 2) ? -1 : atoi(Cmd_Argv(cmd, 1)));
    CL_StartVideo();
    if(MR_ToggleMenu)
        MR_ToggleMenu(m);
}
Referenced by MR_Init_Commands().
M_Background()
static void M_Background (int width, int height) static
Definition at line 161 of file menu.c.
{
    menu_width = bound(1.0f, (float)width, vid_conwidth.value);
    menu_height = bound(1.0f, (float)height, vid_conheight.value);
    menu_x = (vid_conwidth.integer - menu_width) * 0.5;
    menu_y = (vid_conheight.integer - menu_height) * 0.5;
    //DrawQ_Fill(menu_x, menu_y, menu_width, menu_height, 0, 0, 0, 0.5, 0);
    DrawQ_Fill(0, 0, vid_conwidth.integer, vid_conheight.integer, 0, 0, 0, 0.5, 0);
}
Referenced by M_Credits_Draw(), M_Demo_Draw(), M_GameOptions_Draw(), M_Help_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_MultiPlayer_Draw(), M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Quit_Draw(), M_Reset_Draw(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), M_Transfusion_Episode_Draw(), M_Transfusion_Skill_Draw(), and M_Video_Draw().
M_ChooseQuitMessage()
static int M_ChooseQuitMessage (int request) static
Definition at line 3180 of file menu.c.
{
    if (m_missingdata)
    {
        // frag related quit messages are pointless for a fallback menu, so use something generic
        if (request-- == 0) return M_QuitMessage("Are you sure you want to quit?","Press Y to quit, N to stay",NULL,NULL,NULL,NULL,NULL,NULL);
        return 0;
    }
    switch (gamemode)
    {
    case GAME_NORMAL:
    case GAME_HIPNOTIC:
    case GAME_ROGUE:
    case GAME_QUOTH:
    case GAME_NEHAHRA:
    case GAME_DEFEATINDETAIL2:
        if (request-- == 0) return M_QuitMessage("Are you gonna quit","this game just like","everything else?",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Milord, methinks that","thou art a lowly","quitter. Is this true?",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Do I need to bust your","face open for trying","to quit?",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Man, I oughta smack you","for trying to quit!","Press Y to get","smacked out.",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Press Y to quit like a","big loser in life.","Press N to stay proud","and successful!",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("If you press Y to","quit, I will summon","Satan all over your","hard drive!",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Um, Asmodeus dislikes","his children trying to","quit. Press Y to return","to your Tinkertoys.",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("If you quit now, I'll","throw a blanket-party","for you next time!",NULL,NULL,NULL,NULL,NULL);
        break;
    case GAME_GOODVSBAD2:
        if (request-- == 0) return M_QuitMessage("Press Yes To Quit","...","Yes",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Do you really want to","Quit?","Play Good vs bad 3!",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("All your quit are","belong to long duck","dong",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Press Y to quit","","But are you too legit?",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("This game was made by","e@chip-web.com","It is by far the best","game ever made.",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Even I really dont","know of a game better","Press Y to quit","like rougue chedder",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("After you stop playing","tell the guys who made","counterstrike to just","kill themselves now",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Press Y to exit to DOS","","SSH login as user Y","to exit to Linux",NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Press Y like you","were waanderers","from Ys'",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("This game was made in","Nippon like the SS","announcer's saying ipon",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("you","want to quit?",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Please stop playing","this stupid game",NULL,NULL,NULL,NULL,NULL,NULL);
        break;
    case GAME_BATTLEMECH:
        if (request-- == 0) return M_QuitMessage("? WHY ?","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Leave now and your mech is scrap!","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Accept Defeat?","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Wait! There are more mechs to destroy!","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Where's your bloodlust?","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Your mech here is way more impressive","than your car out there...","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Quitting won't reduce your debt","Press Y to quit, N to keep fraggin'",NULL,NULL,NULL,NULL,NULL,NULL);
        break;
    case GAME_OPENQUARTZ:
        if (request-- == 0) return M_QuitMessage("There is nothing like free beer!","Press Y to quit, N to stay",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("GNU is not Unix!","Press Y to quit, N to stay",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("You prefer free beer over free speech?","Press Y to quit, N to stay",NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Is OpenQuartz Propaganda?","Press Y to quit, N to stay",NULL,NULL,NULL,NULL,NULL,NULL);
        break;
    default:
        if (request-- == 0) return M_QuitMessage("Tired of fragging already?",NULL,NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Quit now and forfeit your bodycount?",NULL,NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Are you sure you want to quit?",NULL,NULL,NULL,NULL,NULL,NULL,NULL);
        if (request-- == 0) return M_QuitMessage("Off to do something constructive?",NULL,NULL,NULL,NULL,NULL,NULL,NULL);
        break;
    }
    return 0;
}
Referenced by M_Menu_Quit_f().
M_Credits_Draw()
static void M_Credits_Draw (void) static
Definition at line 3143 of file menu.c.
{
    M_Background(640, 480);
    M_DrawPic (0, 0, "gfx/creditsmiddle");
    M_Print (640/2 - 14/2*8, 236, "Coming soon...");
    M_DrawPic (0, 0, "gfx/creditstop");
    M_DrawPic (0, 433, "gfx/creditsbottom");
}
Referenced by M_Draw().
M_Credits_Key()
static void M_Credits_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 3153 of file menu.c.
{
        M_Menu_Main_f(cmd);
}
Referenced by M_KeyEvent().
M_Demo_Draw()
static void M_Demo_Draw (void) static
Definition at line 290 of file menu.c.
{
    int i;
    M_Background(320, 200);
    for (i = 0;i < NumberOfNehahraDemos;i++)
        M_Print(16, 16 + 8*i, NehahraDemos[i].desc);
    // line cursor
    M_DrawCharacter (8, 16 + demo_cursor*8, 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Demo_Key()
static void M_Demo_Key (cmd_state_t * cmd, int k, int ascii) static
Definition at line 312 of file menu.c.
{
    char vabuf[1024];
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Main_f (cmd);
        break;
    case K_ENTER:
        S_LocalSound ("sound/misc/menu2.wav");
        m_state = m_none;
        key_dest = key_game;
        Cbuf_AddText (cmd, va(vabuf, sizeof(vabuf), "playdemo %s\n", NehahraDemos[demo_cursor].name));
        return;
    case K_UPARROW:
    case K_LEFTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        demo_cursor--;
        if (demo_cursor < 0)
            demo_cursor = NumberOfNehahraDemos-1;
        break;
    case K_DOWNARROW:
    case K_RIGHTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        demo_cursor++;
        if (demo_cursor >= NumberOfNehahraDemos)
            demo_cursor = 0;
        break;
    }
}
Referenced by M_KeyEvent().
M_Draw()
void M_Draw (void) static
Definition at line 4769 of file menu.c.
{
    char vabuf[1024];
    if (key_dest != key_menu && key_dest != key_menu_grabbed)
        m_state = m_none;
    if (m_state == m_none)
        return;
    switch (m_state)
    {
    case m_none:
        break;
    case m_main:
        M_Main_Draw ();
        break;
    case m_demo:
        M_Demo_Draw ();
        break;
    case m_singleplayer:
        M_SinglePlayer_Draw ();
        break;
    case m_transfusion_episode:
        M_Transfusion_Episode_Draw ();
        break;
    case m_transfusion_skill:
        M_Transfusion_Skill_Draw ();
        break;
    case m_load:
        M_Load_Draw ();
        break;
    case m_save:
        M_Save_Draw ();
        break;
    case m_multiplayer:
        M_MultiPlayer_Draw ();
        break;
    case m_setup:
        M_Setup_Draw ();
        break;
    case m_options:
        M_Options_Draw ();
        break;
    case m_options_effects:
        M_Options_Effects_Draw ();
        break;
    case m_options_graphics:
        M_Options_Graphics_Draw ();
        break;
    case m_options_colorcontrol:
        M_Options_ColorControl_Draw ();
        break;
    case m_keys:
        M_Keys_Draw ();
        break;
    case m_reset:
        M_Reset_Draw ();
        break;
    case m_video:
        M_Video_Draw ();
        break;
    case m_help:
        M_Help_Draw ();
        break;
    case m_credits:
        M_Credits_Draw ();
        break;
    case m_quit:
        M_Quit_Draw ();
        break;
    case m_lanconfig:
        M_LanConfig_Draw ();
        break;
    case m_gameoptions:
        M_GameOptions_Draw ();
        break;
    case m_slist:
        M_ServerList_Draw ();
        break;
    case m_modlist:
        M_ModList_Draw ();
        break;
    }
    if (gamemode == GAME_TRANSFUSION && !m_missingdata) {
        if (m_state != m_credits) {
            cachepic_t  *p, *drop1, *drop2, *drop3;
            int g, scale_x, scale_y, scale_y_repeat, top_offset;
            float scale_y_rate;
            scale_y_repeat = vid_conheight.integer * 2;
            g = (int)(host.realtime * 64)%96;
            scale_y_rate = (float)(g+1) / 96;
            top_offset = (g+12)/12;
            p = Draw_CachePic (va(vabuf, sizeof(vabuf), "gfx/menu/blooddrip%i", top_offset));
            drop1 = Draw_CachePic ("gfx/menu/blooddrop1");
            drop2 = Draw_CachePic ("gfx/menu/blooddrop2");
            drop3 = Draw_CachePic ("gfx/menu/blooddrop3");
            for (scale_x = 0; scale_x <= vid_conwidth.integer; scale_x += Draw_GetPicWidth(p)) {
                for (scale_y = -scale_y_repeat; scale_y <= vid_conheight.integer; scale_y += scale_y_repeat) {
                    DrawQ_Pic (scale_x + 21, scale_y_repeat * .5 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x +  116, scale_y_repeat + scale_y + scale_y_rate * scale_y_repeat, drop1, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 180, scale_y_repeat * .275 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 242, scale_y_repeat * .75 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 304, scale_y_repeat * .25 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 362, scale_y_repeat * .46125 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 402, scale_y_repeat * .1725 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 438, scale_y_repeat * .9 + scale_y + scale_y_rate * scale_y_repeat, drop1, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 484, scale_y_repeat * .5 + scale_y + scale_y_rate * scale_y_repeat, drop3, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 557, scale_y_repeat * .9425 + scale_y + scale_y_rate * scale_y_repeat, drop1, 0, 0, 1, 1, 1, 1, 0);
                    DrawQ_Pic (scale_x + 606, scale_y_repeat * .5 + scale_y + scale_y_rate * scale_y_repeat, drop2, 0, 0, 1, 1, 1, 1, 0);
                }
                DrawQ_Pic (scale_x, -1, Draw_CachePic (va(vabuf, sizeof(vabuf), "gfx/menu/blooddrip%i", top_offset)), 0, 0, 1, 1, 1, 1, 0);
            }
        }
    }
    if (m_entersound)
    {
        S_LocalSound ("sound/misc/menu2.wav");
        m_entersound = false;
    }
    S_ExtraUpdate ();
}
Referenced by MR_SetRouting().
M_DrawCharacter()
static void M_DrawCharacter (float cx, float cy, int num) static
Definition at line 178 of file menu.c.
{
    char temp[2];
    temp[0] = num;
    temp[1] = 0;
    DrawQ_String(menu_x + cx, menu_y + cy, temp, 1, 8, 8, 1, 1, 1, 1, 0, NULL, true, FONT_MENU);
}
Referenced by M_Demo_Draw(), M_DrawSlider(), M_GameOptions_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_Save_Draw(), M_Setup_Draw(), and M_Video_Draw().
M_DrawCheckbox()
static void M_DrawCheckbox (int x, int y, int on) static
Definition at line 1557 of file menu.c.
{
    if (on)
        M_Print(x, y, "on");
    else
        M_Print(x, y, "off");
}
Referenced by M_ModList_Draw(), M_Options_PrintCheckbox(), and M_Video_Draw().
M_DrawPic()
static void M_DrawPic (float cx, float cy, const char * picname) static
Definition at line 209 of file menu.c.
{
    DrawQ_Pic(menu_x + cx, menu_y + cy, Draw_CachePic (picname), 0, 0, 1, 1, 1, 1, 0);
}
Referenced by M_Credits_Draw(), M_DrawTextBox(), M_GameOptions_Draw(), M_Help_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_MultiPlayer_Draw(), M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), M_Transfusion_Episode_Draw(), M_Transfusion_Skill_Draw(), and M_Video_Draw().
M_DrawSlider()
static void M_DrawSlider (int x, int y, float num, float rangemin, float rangemax) static
Definition at line 1539 of file menu.c.
{
    char text[16];
    int i;
    float range;
    range = bound(0, (num - rangemin) / (rangemax - rangemin), 1);
    M_DrawCharacter (x-8, y, 128);
    for (i = 0;i < SLIDER_RANGE;i++)
        M_DrawCharacter (x + i*8, y, 129);
    M_DrawCharacter (x+i*8, y, 130);
    M_DrawCharacter (x + (SLIDER_RANGE-1)*8 * range, y, 131);
    if (fabs((int)num - num) < 0.01)
        dpsnprintf(text, sizeof(text), "%i", (int)num);
    else
        dpsnprintf(text, sizeof(text), "%.3f", num);
    M_Print(x + (SLIDER_RANGE+2) * 8, y, text);
}
Referenced by M_Options_PrintSlider(), and M_Video_Draw().
M_DrawTextBox()
static void M_DrawTextBox (float x, float y, float width, float height) static
Definition at line 214 of file menu.c.
{
    int n;
    float cx, cy;
    // draw left side
    cx = x;
    cy = y;
    M_DrawPic (cx, cy, "gfx/box_tl");
    for (n = 0; n < height; n++)
    {
        cy += 8;
        M_DrawPic (cx, cy, "gfx/box_ml");
    }
    M_DrawPic (cx, cy+8, "gfx/box_bl");
    // draw middle
    cx += 8;
    while (width > 0)
    {
        cy = y;
        M_DrawPic (cx, cy, "gfx/box_tm");
        for (n = 0; n < height; n++)
        {
            cy += 8;
            if (n >= 1)
                M_DrawPic (cx, cy, "gfx/box_mm2");
            else
                M_DrawPic (cx, cy, "gfx/box_mm");
        }
        M_DrawPic (cx, cy+8, "gfx/box_bm");
        width -= 2;
        cx += 16;
    }
    // draw right side
    cy = y;
    M_DrawPic (cx, cy, "gfx/box_tr");
    for (n = 0; n < height; n++)
    {
        cy += 8;
        M_DrawPic (cx, cy, "gfx/box_mr");
    }
    M_DrawPic (cx, cy+8, "gfx/box_br");
}
Referenced by M_GameOptions_Draw(), M_LanConfig_Draw(), M_Quit_Draw(), M_Reset_Draw(), M_Setup_Draw(), and M_SinglePlayer_Draw().
M_GameOptions_Draw()
void M_GameOptions_Draw (void) static
Definition at line 3969 of file menu.c.
{
    cachepic_t  *p;
    int     x;
    char vabuf[1024];
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_multi");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/p_multi");
    M_DrawTextBox (152, 32, 10, 1);
    M_Print(160, 40, "begin game");
    M_Print(0, 56, "      Max players");
    M_Print(160, 56, va(vabuf, sizeof(vabuf), "%i", maxplayers) );
    if (gamemode != GAME_GOODVSBAD2)
    {
        M_Print(0, 64, "        Game Type");
        if (gamemode == GAME_TRANSFUSION)
        {
            if (!coop.integer && !deathmatch.integer)
                Cvar_SetValue(&cvars_all, "deathmatch", 1);
            if (deathmatch.integer == 0)
                M_Print(160, 64, "Cooperative");
            else if (deathmatch.integer == 2)
                M_Print(160, 64, "Capture the Flag");
            else
                M_Print(160, 64, "Blood Bath");
        }
        else if (gamemode == GAME_BATTLEMECH)
        {
            if (!deathmatch.integer)
                Cvar_SetValue(&cvars_all, "deathmatch", 1);
            if (deathmatch.integer == 2)
                M_Print(160, 64, "Rambo Match");
            else
                M_Print(160, 64, "Deathmatch");
        }
        else
        {
            if (!coop.integer && !deathmatch.integer)
                Cvar_SetValue(&cvars_all, "deathmatch", 1);
            if (coop.integer)
                M_Print(160, 64, "Cooperative");
            else
                M_Print(160, 64, "Deathmatch");
        }
        M_Print(0, 72, "        Teamplay");
        if (gamemode == GAME_ROGUE)
        {
            const char *msg;
            switch((int)teamplay.integer)
            {
                case 1: msg = "No Friendly Fire"; break;
                case 2: msg = "Friendly Fire"; break;
                case 3: msg = "Tag"; break;
                case 4: msg = "Capture the Flag"; break;
                case 5: msg = "One Flag CTF"; break;
                case 6: msg = "Three Team CTF"; break;
                default: msg = "Off"; break;
            }
            M_Print(160, 72, msg);
        }
        else
        {
            const char *msg;
            switch (teamplay.integer)
            {
                case 0: msg = "Off"; break;
                case 2: msg = "Friendly Fire"; break;
                default: msg = "No Friendly Fire"; break;
            }
            M_Print(160, 72, msg);
        }
        M_Print(0, 80, "            Skill");
        if (gamemode == GAME_TRANSFUSION)
        {
            if (skill.integer == 1)
                M_Print(160, 80, "Still Kicking");
            else if (skill.integer == 2)
                M_Print(160, 80, "Pink On The Inside");
            else if (skill.integer == 3)
                M_Print(160, 80, "Lightly Broiled");
            else if (skill.integer == 4)
                M_Print(160, 80, "Well Done");
            else
                M_Print(160, 80, "Extra Crispy");
        }
        else
        {
            if (skill.integer == 0)
                M_Print(160, 80, "Easy difficulty");
            else if (skill.integer == 1)
                M_Print(160, 80, "Normal difficulty");
            else if (skill.integer == 2)
                M_Print(160, 80, "Hard difficulty");
            else
                M_Print(160, 80, "Nightmare difficulty");
        }
        M_Print(0, 88, "       Frag Limit");
        if (fraglimit.integer == 0)
            M_Print(160, 88, "none");
        else
            M_Print(160, 88, va(vabuf, sizeof(vabuf), "%i frags", fraglimit.integer));
        M_Print(0, 96, "       Time Limit");
        if (timelimit.integer == 0)
            M_Print(160, 96, "none");
        else
            M_Print(160, 96, va(vabuf, sizeof(vabuf), "%i minutes", timelimit.integer));
    }
    M_Print(0, 104, "    Public server");
    M_Print(160, 104, (sv_public.integer == 0) ? "no" : "yes");
    M_Print(0, 112, "   Server maxrate");
    M_Print(160, 112, va(vabuf, sizeof(vabuf), "%i", sv_maxrate.integer));
    M_Print(0, 128, "      Server name");
    M_DrawTextBox (0, 132, 38, 1);
    M_Print(8, 140, hostname.string);
    if (gamemode != GAME_GOODVSBAD2)
    {
        M_Print(0, 160, "         Episode");
        M_Print(160, 160, gameoptions_levels->episodes[startepisode].description);
    }
    M_Print(0, 168, "           Level");
    M_Print(160, 168, gameoptions_levels->levels[gameoptions_levels->episodes[startepisode].firstLevel + startlevel].description);
    M_Print(160, 176, gameoptions_levels->levels[gameoptions_levels->episodes[startepisode].firstLevel + startlevel].name);
// line cursor
    if (gameoptions_cursor == 9)
        M_DrawCharacter (8 + 8 * strlen(hostname.string), gameoptions_cursor_table[gameoptions_cursor], 10+((int)(host.realtime*4)&1));
    else
        M_DrawCharacter (144, gameoptions_cursor_table[gameoptions_cursor], 12+((int)(host.realtime*4)&1));
    if (m_serverInfoMessage)
    {
        if ((host.realtime - m_serverInfoMessageTime) < 5.0)
        {
            x = (320-26*8)/2;
            M_DrawTextBox (x, 138, 24, 4);
            x += 8;
            M_Print(x, 146, " More than 255 players??");
            M_Print(x, 154, "  First, question your  ");
            M_Print(x, 162, "   sanity, then email   ");
            M_Print(x, 170, "darkplacesengine@gmail.com");
        }
        else
            m_serverInfoMessage = false;
    }
}
Referenced by M_Draw().
M_GameOptions_Key()
static void M_GameOptions_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 4291 of file menu.c.
{
    int l;
    char hostnamebuf[128];
    char vabuf[1024];
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_MultiPlayer_f(cmd);
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        gameoptions_cursor--;
        if (gameoptions_cursor < 0)
            gameoptions_cursor = NUM_GAMEOPTIONS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        gameoptions_cursor++;
        if (gameoptions_cursor >= NUM_GAMEOPTIONS)
            gameoptions_cursor = 0;
        break;
    case K_LEFTARROW:
        if (gameoptions_cursor == 0)
            break;
        S_LocalSound ("sound/misc/menu3.wav");
        M_NetStart_Change (-1);
        break;
    case K_RIGHTARROW:
        if (gameoptions_cursor == 0)
            break;
        S_LocalSound ("sound/misc/menu3.wav");
        M_NetStart_Change (1);
        break;
    case K_ENTER:
        S_LocalSound ("sound/misc/menu2.wav");
        if (gameoptions_cursor == 0)
        {
            if (sv.active)
                Cbuf_AddText(cmd, "disconnect\n");
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "maxplayers %u\n", maxplayers) );
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "map %s\n", gameoptions_levels->levels[gameoptions_levels->episodes[startepisode].firstLevel + startlevel].name) );
            return;
        }
        M_NetStart_Change (1);
        break;
    case K_BACKSPACE:
        if (gameoptions_cursor == 9)
        {
            l = (int)strlen(hostname.string);
            if (l)
            {
                l = min(l - 1, 37);
                memcpy(hostnamebuf, hostname.string, l);
                hostnamebuf[l] = 0;
                Cvar_Set(&cvars_all, "hostname", hostnamebuf);
            }
        }
        break;
    default:
        if (ascii < 32)
            break;
        if (gameoptions_cursor == 9)
        {
            l = (int)strlen(hostname.string);
            if (l < 37)
            {
                memcpy(hostnamebuf, hostname.string, l);
                hostnamebuf[l] = ascii;
                hostnamebuf[l+1] = 0;
                Cvar_Set(&cvars_all, "hostname", hostnamebuf);
            }
        }
    }
}
Referenced by M_KeyEvent().
M_GetServerListEntryCategory()
static int M_GetServerListEntryCategory (const serverlist_entry_t * entry) static
Definition at line 5027 of file menu.c.
{
    return 0;
}
Referenced by MR_SetRouting().
M_Help_Draw()
static void M_Help_Draw (void) static
Definition at line 3098 of file menu.c.
{
    char vabuf[1024];
    M_Background(320, 200);
    M_DrawPic (0, 0, va(vabuf, sizeof(vabuf), "gfx/help%i", help_page));
}
Referenced by M_Draw().
M_Help_Key()
static void M_Help_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 3106 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Main_f(cmd);
        break;
    case K_UPARROW:
    case K_RIGHTARROW:
        m_entersound = true;
        if (++help_page >= NUM_HELP_PAGES)
            help_page = 0;
        break;
    case K_DOWNARROW:
    case K_LEFTARROW:
        m_entersound = true;
        if (--help_page < 0)
            help_page = NUM_HELP_PAGES-1;
        break;
    }
}
Referenced by M_KeyEvent().
M_Init()
static void M_Init (void) static
Definition at line 4743 of file menu.c.
{
    menuplyr_load = true;
    menuplyr_pixels = NULL;
    Cmd_AddCommand(CF_CLIENT, "menu_main", M_Menu_Main_f, "open the main menu");
    Cmd_AddCommand(CF_CLIENT, "menu_singleplayer", M_Menu_SinglePlayer_f, "open the singleplayer menu");
    Cmd_AddCommand(CF_CLIENT, "menu_load", M_Menu_Load_f, "open the loadgame menu");
    Cmd_AddCommand(CF_CLIENT, "menu_save", M_Menu_Save_f, "open the savegame menu");
    Cmd_AddCommand(CF_CLIENT, "menu_multiplayer", M_Menu_MultiPlayer_f, "open the multiplayer menu");
    Cmd_AddCommand(CF_CLIENT, "menu_setup", M_Menu_Setup_f, "open the player setup menu");
    Cmd_AddCommand(CF_CLIENT, "menu_options", M_Menu_Options_f, "open the options menu");
    Cmd_AddCommand(CF_CLIENT, "menu_options_effects", M_Menu_Options_Effects_f, "open the effects options menu");
    Cmd_AddCommand(CF_CLIENT, "menu_options_graphics", M_Menu_Options_Graphics_f, "open the graphics options menu");
    Cmd_AddCommand(CF_CLIENT, "menu_options_colorcontrol", M_Menu_Options_ColorControl_f, "open the color control menu");
    Cmd_AddCommand(CF_CLIENT, "menu_keys", M_Menu_Keys_f, "open the key binding menu");
    Cmd_AddCommand(CF_CLIENT, "menu_video", M_Menu_Video_f, "open the video options menu");
    Cmd_AddCommand(CF_CLIENT, "menu_reset", M_Menu_Reset_f, "open the reset to defaults menu");
    Cmd_AddCommand(CF_CLIENT, "menu_mods", M_Menu_ModList_f, "open the mods browser menu");
    Cmd_AddCommand(CF_CLIENT, "help", M_Menu_Help_f, "open the help menu");
    Cmd_AddCommand(CF_CLIENT, "menu_quit", M_Menu_Quit_f, "open the quit menu");
    Cmd_AddCommand(CF_CLIENT, "menu_transfusion_episode", M_Menu_Transfusion_Episode_f, "open the transfusion episode select menu");
    Cmd_AddCommand(CF_CLIENT, "menu_transfusion_skill", M_Menu_Transfusion_Skill_f, "open the transfusion skill select menu");
    Cmd_AddCommand(CF_CLIENT, "menu_credits", M_Menu_Credits_f, "open the credits menu");
}
Referenced by MR_SetRouting().
M_ItemPrint()
static void M_ItemPrint (float cx, float cy, const char * str, int unghosted) static
Definition at line 201 of file menu.c.
{
    if (unghosted)
        DrawQ_String(menu_x + cx, menu_y + cy, str, 0, 8, 8, 1, 1, 1, 1, 0, NULL, true, FONT_MENU);
    else
        DrawQ_String(menu_x + cx, menu_y + cy, str, 0, 8, 8, 0.4, 0.4, 0.4, 1, 0, NULL, true, FONT_MENU);
}
Referenced by M_ModList_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), M_Options_PrintSlider(), and M_Video_Draw().
M_KeyEvent()
void M_KeyEvent (int key, int ascii, qbool downevent) static
Definition at line 4918 of file menu.c.
{
    cmd_state_t *cmd = cmd_local;
    if (!downevent)
        return;
    switch (m_state)
    {
    case m_none:
        return;
    case m_main:
        M_Main_Key(cmd, key, ascii);
        return;
    case m_demo:
        M_Demo_Key(cmd, key, ascii);
        return;
    case m_singleplayer:
        M_SinglePlayer_Key(cmd, key, ascii);
        return;
    case m_transfusion_episode:
        M_Transfusion_Episode_Key(cmd, key, ascii);
        return;
    case m_transfusion_skill:
        M_Transfusion_Skill_Key(cmd, key, ascii);
        return;
    case m_load:
        M_Load_Key(cmd, key, ascii);
        return;
    case m_save:
        M_Save_Key(cmd, key, ascii);
        return;
    case m_multiplayer:
        M_MultiPlayer_Key(cmd, key, ascii);
        return;
    case m_setup:
        M_Setup_Key(cmd, key, ascii);
        return;
    case m_options:
        M_Options_Key(cmd, key, ascii);
        return;
    case m_options_effects:
        M_Options_Effects_Key(cmd, key, ascii);
        return;
    case m_options_graphics:
        M_Options_Graphics_Key(cmd, key, ascii);
        return;
    case m_options_colorcontrol:
        M_Options_ColorControl_Key(cmd, key, ascii);
        return;
    case m_keys:
        M_Keys_Key(cmd, key, ascii);
        return;
    case m_reset:
        M_Reset_Key(cmd, key, ascii);
        return;
    case m_video:
        M_Video_Key(cmd, key, ascii);
        return;
    case m_help:
        M_Help_Key(cmd, key, ascii);
        return;
    case m_credits:
        M_Credits_Key(cmd, key, ascii);
        return;
    case m_quit:
        M_Quit_Key(cmd, key, ascii);
        return;
    case m_lanconfig:
        M_LanConfig_Key(cmd, key, ascii);
        return;
    case m_gameoptions:
        M_GameOptions_Key(cmd, key, ascii);
        return;
    case m_slist:
        M_ServerList_Key(cmd, key, ascii);
        return;
    case m_modlist:
        M_ModList_Key(cmd, key, ascii);
        return;
    }
}
Referenced by MR_SetRouting().
M_Keys_Draw()
static void M_Keys_Draw (void) static
Definition at line 2598 of file menu.c.
{
    int     i, j;
    int     keys[NUMKEYS];
    int     y;
    cachepic_t  *p;
    char    keystring[MAX_INPUTLINE];
    M_Background(320, 48 + 8 * numcommands);
    p = Draw_CachePic ("gfx/ttl_cstm");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/ttl_cstm");
    if (bind_grab)
        M_Print(12, 32, "Press a key or button for this action");
    else
        M_Print(18, 32, "Enter to change, backspace to clear");
// search for known bindings
    for (i=0 ; i<numcommands ; i++)
    {
        y = 48 + 8*i;
        // If there's no command, it's just a section
        if (bindnames[i][0][0] == '\0')
        {
            M_PrintRed (4, y, "\x0D");  // #13 is the little arrow pointing to the right
            M_PrintRed (16, y, bindnames[i][1]);
            continue;
        }
        else
            M_Print(16, y, bindnames[i][1]);
        Key_FindKeysForCommand (bindnames[i][0], keys, NUMKEYS, 0);
        // LadyHavoc: redesigned to print more than 2 keys, inspired by Tomaz's MiniRacer
        if (keys[0] == -1)
            dp_strlcpy(keystring, "???", sizeof(keystring));
        else
        {
            char tinystr[TINYSTR_LEN];
            keystring[0] = 0;
            for (j = 0;j < NUMKEYS;j++)
            {
                if (keys[j] != -1)
                {
                    if (j > 0)
                        dp_strlcat(keystring, " or ", sizeof(keystring));
                    dp_strlcat(keystring, Key_KeynumToString (keys[j], tinystr, TINYSTR_LEN), sizeof(keystring));
                }
            }
        }
        M_Print(150, y, keystring);
    }
    if (bind_grab)
        M_DrawCharacter (140, 48 + keys_cursor*8, '=');
    else
        M_DrawCharacter (140, 48 + keys_cursor*8, 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Keys_Key()
static void M_Keys_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 2660 of file menu.c.
{
    char    line[80];
    int     keys[NUMKEYS];
    char    tinystr[TINYSTR_LEN];
    if (bind_grab)
    {   // defining a key
        S_LocalSound ("sound/misc/menu1.wav");
        if (k == K_ESCAPE)
        {
            bind_grab = false;
        }
        else //if (k != '`')
        {
            dpsnprintf(line, sizeof(line), "bind \"%s\" \"%s\"\n", Key_KeynumToString(k, tinystr, TINYSTR_LEN), bindnames[keys_cursor][0]);
            Cbuf_InsertText (cmd, line);
        }
        bind_grab = false;
        return;
    }
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Options_f(cmd);
        break;
    case K_LEFTARROW:
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        do
        {
            keys_cursor--;
            if (keys_cursor < 0)
                keys_cursor = numcommands-1;
        }
        while (bindnames[keys_cursor][0][0] == '\0');  // skip sections
        break;
    case K_DOWNARROW:
    case K_RIGHTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        do
        {
            keys_cursor++;
            if (keys_cursor >= numcommands)
                keys_cursor = 0;
        }
        while (bindnames[keys_cursor][0][0] == '\0');  // skip sections
        break;
    case K_ENTER:       // go into bind mode
        Key_FindKeysForCommand (bindnames[keys_cursor][0], keys, NUMKEYS, 0);
        S_LocalSound ("sound/misc/menu2.wav");
        if (keys[NUMKEYS - 1] != -1)
            M_UnbindCommand (bindnames[keys_cursor][0]);
        bind_grab = true;
        break;
    case K_BACKSPACE:       // delete bindings
    case K_DEL:             // delete bindings
        S_LocalSound ("sound/misc/menu2.wav");
        M_UnbindCommand (bindnames[keys_cursor][0]);
        break;
    }
}
Referenced by M_KeyEvent().
M_LanConfig_Draw()
static void M_LanConfig_Draw (void) static
Definition at line 3343 of file menu.c.
{
    cachepic_t  *p;
    int     basex;
    const char  *startJoin;
    const char  *protocol;
    char vabuf[1024];
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_multi");
    basex = (320-Draw_GetPicWidth(p))/2;
    M_DrawPic (basex, 4, "gfx/p_multi");
    if (StartingGame)
        startJoin = "New Game";
    else
        startJoin = "Join Game";
    protocol = "TCP/IP";
    M_Print(basex, 32, va(vabuf, sizeof(vabuf), "%s - %s", startJoin, protocol));
    basex += 8;
    M_Print(basex, lanConfig_cursor_table[0], "Port");
    M_DrawTextBox (basex+8*8, lanConfig_cursor_table[0]-8, sizeof(lanConfig_portname), 1);
    M_Print(basex+9*8, lanConfig_cursor_table[0], lanConfig_portname);
    if (JoiningGame)
    {
        M_Print(basex, lanConfig_cursor_table[1], "Search for DarkPlaces games...");
        M_Print(basex, lanConfig_cursor_table[2], "Search for QuakeWorld games...");
        M_Print(basex, lanConfig_cursor_table[3]-16, "Join game at:");
        M_DrawTextBox (basex+8, lanConfig_cursor_table[3]-8, sizeof(lanConfig_joinname), 1);
        M_Print(basex+16, lanConfig_cursor_table[3], lanConfig_joinname);
    }
    else
    {
        M_DrawTextBox (basex, lanConfig_cursor_table[1]-8, 2, 1);
        M_Print(basex+8, lanConfig_cursor_table[1], "OK");
    }
    M_DrawCharacter (basex-8, lanConfig_cursor_table [lanConfig_cursor], 12+((int)(host.realtime*4)&1));
    if (lanConfig_cursor == 0)
        M_DrawCharacter (basex+9*8 + 8*strlen(lanConfig_portname), lanConfig_cursor_table [lanConfig_cursor], 10+((int)(host.realtime*4)&1));
    if (lanConfig_cursor == 3)
        M_DrawCharacter (basex+16 + 8*strlen(lanConfig_joinname), lanConfig_cursor_table [lanConfig_cursor], 10+((int)(host.realtime*4)&1));
    if (*cl_connect_status)
        M_Print(basex, 168, cl_connect_status);
}
Referenced by M_Draw().
M_LanConfig_Key()
static void M_LanConfig_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 3397 of file menu.c.
{
    int     l;
    char vabuf[1024];
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_MultiPlayer_f(cmd);
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        lanConfig_cursor--;
        if (lanConfig_cursor < 0)
            lanConfig_cursor = NUM_LANCONFIG_CMDS-1;
        // when in start game menu, skip the unused search qw servers item
        if (StartingGame && lanConfig_cursor == 2)
            lanConfig_cursor = 1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        lanConfig_cursor++;
        if (lanConfig_cursor >= NUM_LANCONFIG_CMDS)
            lanConfig_cursor = 0;
        // when in start game menu, skip the unused search qw servers item
        if (StartingGame && lanConfig_cursor == 1)
            lanConfig_cursor = 2;
        break;
    case K_ENTER:
        if (lanConfig_cursor == 0)
            break;
        m_entersound = true;
        Cbuf_AddText(cmd, "stopdemo\n");
        Cvar_SetValue(&cvars_all, "port", lanConfig_port);
        if (lanConfig_cursor == 1 || lanConfig_cursor == 2)
        {
            if (StartingGame)
            {
                M_Menu_GameOptions_f(cmd);
                break;
            }
            M_Menu_ServerList_f(cmd);
            break;
        }
        if (lanConfig_cursor == 3)
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "connect \"%s\"\n", lanConfig_joinname) );
        break;
    case K_BACKSPACE:
        if (lanConfig_cursor == 0)
        {
            if (strlen(lanConfig_portname))
                lanConfig_portname[strlen(lanConfig_portname)-1] = 0;
        }
        if (lanConfig_cursor == 3)
        {
            if (strlen(lanConfig_joinname))
                lanConfig_joinname[strlen(lanConfig_joinname)-1] = 0;
        }
        break;
    default:
        if (ascii < 32)
            break;
        if (lanConfig_cursor == 3)
        {
            l = (int)strlen(lanConfig_joinname);
            if (l < (int)sizeof(lanConfig_joinname) - 1)
            {
                lanConfig_joinname[l+1] = 0;
                lanConfig_joinname[l] = ascii;
            }
        }
        if (ascii < '0' || ascii > '9')
            break;
        if (lanConfig_cursor == 0)
        {
            l = (int)strlen(lanConfig_portname);
            if (l < (int)sizeof(lanConfig_portname) - 1)
            {
                lanConfig_portname[l+1] = 0;
                lanConfig_portname[l] = ascii;
            }
        }
    }
    if (StartingGame && lanConfig_cursor == 3)
    {
        if (key == K_UPARROW)
            lanConfig_cursor = 1;
        else
            lanConfig_cursor = 0;
    }
    l =  atoi(lanConfig_portname);
    if (l <= 65535)
        lanConfig_port = l;
    dpsnprintf(lanConfig_portname, sizeof(lanConfig_portname), "%u", (unsigned int) lanConfig_port);
}
Referenced by M_KeyEvent().
M_Load_Draw()
static void M_Load_Draw (void) static
Definition at line 910 of file menu.c.
{
    int     i;
    cachepic_t  *p;
    M_Background(320, 200);
    p = Draw_CachePic ("gfx/p_load");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/p_load" );
    for (i=0 ; i< MAX_SAVEGAMES; i++)
        M_Print(16, 32 + 8*i, m_filenames[i]);
// line cursor
    M_DrawCharacter (8, 32 + load_cursor*8, 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Load_Key()
static void M_Load_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 946 of file menu.c.
{
    char vabuf[1024];
    switch (k)
    {
    case K_ESCAPE:
        if (gamemode == GAME_TRANSFUSION)
            M_Menu_Main_f(cmd);
        else
            M_Menu_SinglePlayer_f(cmd);
        break;
    case K_ENTER:
        S_LocalSound ("sound/misc/menu2.wav");
        if (!loadable[load_cursor])
            return;
        m_state = m_none;
        key_dest = key_game;
        // issue the load command
        Cbuf_AddText (cmd, va(vabuf, sizeof(vabuf), "load s%i\n", load_cursor) );
        return;
    case K_UPARROW:
    case K_LEFTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        load_cursor--;
        if (load_cursor < 0)
            load_cursor = MAX_SAVEGAMES-1;
        break;
    case K_DOWNARROW:
    case K_RIGHTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        load_cursor++;
        if (load_cursor >= MAX_SAVEGAMES)
            load_cursor = 0;
        break;
    }
}
Referenced by M_KeyEvent().
M_Main_Draw()
static void M_Main_Draw (void) static
Definition at line 424 of file menu.c.
{
    int     f;
    cachepic_t  *p;
    char vabuf[1024];
    if (m_missingdata)
    {
        float y;
        const char *s;
        M_Background(640, 480); //fall back is always to 640x480, this makes it most readable at that.
        y = 480/3-16;
        s = "You have reached this menu due to missing or unlocatable content/data";M_PrintRed ((640-strlen(s)*8)*0.5, (480/3)-16, s);y+=8;
        y+=8;
        s = "You may consider adding";M_Print ((640-strlen(s)*8)*0.5, y, s);y+=8;
        s = "-basedir /path/to/game";M_Print ((640-strlen(s)*8)*0.5, y, s);y+=8;
        s = "to your launch commandline";M_Print ((640-strlen(s)*8)*0.5, y, s);y+=8;
        M_Print (640/2 - 48, 480/2, "Open Console"); //The console usually better shows errors (failures)
        M_Print (640/2 - 48, 480/2 + 8, "Quit");
        M_DrawCharacter(640/2 - 56, 480/2 + (8 * m_main_cursor), 12+((int)(host.realtime*4)&1));
        return;
    }
    if (gamemode == GAME_TRANSFUSION) {
        int y1, y2, y3;
        M_Background(640, 480);
        p = Draw_CachePic ("gfx/menu/tb-transfusion");
        M_DrawPic (640/2 - Draw_GetPicWidth(p)/2, 40, "gfx/menu/tb-transfusion");
        y2 = 120;
        // 8 rather than MAIN_ITEMS to skip a number and not miss the last option
        for (y1 = 1; y1 <= 8; y1++)
        {
            if (MAIN_ITEMS == 7 && y1 == 4)
                y1++;
            M_DrawPic (0, y2, va(vabuf, sizeof(vabuf), "gfx/menu/mainmenu%i", y1));
            y2 += 40;
        }
        if (MAIN_ITEMS == 7 && m_main_cursor > 2)
            y3 = m_main_cursor + 2;
        else
            y3 = m_main_cursor + 1;
        M_DrawPic (0, 120 + m_main_cursor * 40, va(vabuf, sizeof(vabuf), "gfx/menu/mainmenu%iselected", y3));
        return;
    }
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/ttl_main");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/ttl_main");
// Nehahra
    if (gamemode == GAME_NEHAHRA)
    {
        if (NehGameType == TYPE_BOTH)
            M_DrawPic (72, 32, "gfx/mainmenu");
        else if (NehGameType == TYPE_GAME)
            M_DrawPic (72, 32, "gfx/gamemenu");
        else
            M_DrawPic (72, 32, "gfx/demomenu");
    }
    else
        M_DrawPic (72, 32, "gfx/mainmenu");
    f = (int)(host.realtime * 10)%6;
    M_DrawPic (54, 32 + m_main_cursor * 20, va(vabuf, sizeof(vabuf), "gfx/menudot%i", f+1));
}
Referenced by M_Draw().
M_Main_Key()
static void M_Main_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 492 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
        key_dest = key_game;
        m_state = m_none;
        //cls.demonum = m_save_demonum;
        //if (cls.demonum != -1 && !cls.demoplayback && cls.state != ca_connected)
        //  CL_NextDemo ();
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (++m_main_cursor >= MAIN_ITEMS)
            m_main_cursor = 0;
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (--m_main_cursor < 0)
            m_main_cursor = MAIN_ITEMS - 1;
        break;
    case K_ENTER:
        m_entersound = true;
        if (m_missingdata)
        {
            switch (m_main_cursor)
            {
            case 0:
                if (cls.state == ca_connected)
                {
                    m_state = m_none;
                    key_dest = key_game;
                }
                Con_ToggleConsole_f(cmd);
                break;
            case 1:
                M_Menu_Quit_f(cmd);
                break;
            }
        }
        else if (gamemode == GAME_NEHAHRA)
        {
            switch (NehGameType)
            {
            case TYPE_BOTH:
                switch (m_main_cursor)
                {
                case 0:
                    M_Menu_SinglePlayer_f(cmd);
                    break;
                case 1:
                    M_Menu_Demos_f(cmd);
                    break;
                case 2:
                    M_Menu_MultiPlayer_f(cmd);
                    break;
                case 3:
                    M_Menu_Options_f(cmd);
                    break;
                case 4:
                    key_dest = key_game;
                    if (sv.active)
                        Cbuf_AddText (cmd, "disconnect\n");
                    Cbuf_AddText (cmd, "playdemo endcred\n");
                    break;
                case 5:
                    M_Menu_Quit_f(cmd);
                    break;
                }
                break;
            case TYPE_GAME:
                switch (m_main_cursor)
                {
                case 0:
                    M_Menu_SinglePlayer_f(cmd);
                    break;
                case 1:
                    M_Menu_MultiPlayer_f(cmd);
                    break;
                case 2:
                    M_Menu_Options_f(cmd);
                    break;
                case 3:
                    key_dest = key_game;
                    if (sv.active)
                        Cbuf_AddText (cmd, "disconnect\n");
                    Cbuf_AddText (cmd, "playdemo endcred\n");
                    break;
                case 4:
                    M_Menu_Quit_f(cmd);
                    break;
                }
                break;
            case TYPE_DEMO:
                switch (m_main_cursor)
                {
                case 0:
                    M_Menu_Demos_f(cmd);
                    break;
                case 1:
                    key_dest = key_game;
                    if (sv.active)
                        Cbuf_AddText (cmd, "disconnect\n");
                    Cbuf_AddText (cmd, "playdemo endcred\n");
                    break;
                case 2:
                    M_Menu_Options_f(cmd);
                    break;
                case 3:
                    M_Menu_Quit_f(cmd);
                    break;
                }
                break;
            }
        }
        else if (gamemode == GAME_TRANSFUSION) {
            if (MAIN_ITEMS == 7)
            {
                switch (m_main_cursor)
                {
                case 0:
                    M_Menu_Transfusion_Episode_f(cmd);
                    break;
                case 1:
                    M_Menu_MultiPlayer_f(cmd);
                    break;
                case 2:
                    M_Menu_Options_f(cmd);
                    break;
                case 3:
                    M_Menu_Load_f(cmd);
                    break;
                case 4:
                    M_Menu_Help_f(cmd);
                    break;
                case 5:
                    M_Menu_Credits_f(cmd);
                    break;
                case 6:
                    M_Menu_Quit_f(cmd);
                    break;
                }
            }
            else
            {
                switch (m_main_cursor)
                {
                case 0:
                    M_Menu_Transfusion_Episode_f(cmd);
                    break;
                case 1:
                    M_Menu_MultiPlayer_f(cmd);
                    break;
                case 2:
                    M_Menu_Options_f(cmd);
                    break;
                case 3:
                    M_Menu_Save_f(cmd);
                    break;
                case 4:
                    M_Menu_Load_f(cmd);
                    break;
                case 5:
                    M_Menu_Help_f(cmd);
                    break;
                case 6:
                    M_Menu_Credits_f(cmd);
                    break;
                case 7:
                    M_Menu_Quit_f(cmd);
                    break;
                }
            }
        }
        else
        {
            switch (m_main_cursor)
            {
            case 0:
                M_Menu_SinglePlayer_f(cmd);
                break;
            case 1:
                M_Menu_MultiPlayer_f(cmd);
                break;
            case 2:
                M_Menu_Options_f(cmd);
                break;
            case 3:
                M_Menu_Help_f(cmd);
                break;
            case 4:
                M_Menu_Quit_f(cmd);
                break;
            }
        }
    }
}
Referenced by M_KeyEvent().
M_Menu_Credits_f()
void M_Menu_Credits_f (cmd_state_t * cmd)
Definition at line 3134 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_credits;
    m_entersound = true;
}
Referenced by M_Init(), and M_Main_Key().
M_Menu_Demos_f()
static void M_Menu_Demos_f (cmd_state_t * cmd) static
Definition at line 304 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_demo;
    m_entersound = true;
}
Referenced by M_Main_Key().
M_Menu_GameOptions_f()
void M_Menu_GameOptions_f (cmd_state_t * cmd)
Definition at line 3947 of file menu.c.
{
    int i;
    key_dest = key_menu;
    m_state = m_gameoptions;
    m_entersound = true;
    if (maxplayers == 0)
        maxplayers = svs.maxclients;
    if (maxplayers < 2)
        maxplayers = min(8, MAX_SCOREBOARD);
    // pick game level list based on gamemode (use GAME_NORMAL if no matches)
    gameoptions_levels = registered.integer ? gamelist[0].registered : gamelist[0].notregistered;
    for (i = 0;i < (int)(sizeof(gamelist)/sizeof(gamelist[0]));i++)
        if (gamelist[i].gameid == gamemode)
            gameoptions_levels = registered.integer ? gamelist[i].registered : gamelist[i].notregistered;
}
Referenced by M_LanConfig_Key().
M_Menu_Help_f()
void M_Menu_Help_f (cmd_state_t * cmd)
Definition at line 3088 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_help;
    m_entersound = true;
    help_page = 0;
}
Referenced by M_Init(), and M_Main_Key().
M_Menu_Keys_f()
void M_Menu_Keys_f (cmd_state_t * cmd)
Definition at line 2546 of file menu.c.
{
    key_dest = key_menu_grabbed;
    m_state = m_keys;
    m_entersound = true;
    if (gamemode == GAME_TRANSFUSION)
    {
        numcommands = sizeof(transfusionbindnames) / sizeof(transfusionbindnames[0]);
        bindnames = transfusionbindnames;
    }
    else if (gamemode == GAME_GOODVSBAD2)
    {
        numcommands = sizeof(goodvsbad2bindnames) / sizeof(goodvsbad2bindnames[0]);
        bindnames = goodvsbad2bindnames;
    }
    else
    {
        numcommands = sizeof(quakebindnames) / sizeof(quakebindnames[0]);
        bindnames = quakebindnames;
    }
    // Make sure "keys_cursor" doesn't start on a section in the binding list
    keys_cursor = 0;
    while (bindnames[keys_cursor][0][0] == '\0')
    {
        keys_cursor++;
        // Only sections? There may be a problem somewhere...
        if (keys_cursor >= numcommands)
            Sys_Error ("M_Init: The key binding list only contains sections");
    }
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_LanConfig_f()
void M_Menu_LanConfig_f (cmd_state_t * cmd)
Definition at line 3324 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_lanconfig;
    m_entersound = true;
    if (lanConfig_cursor == -1)
    {
        if (JoiningGame)
            lanConfig_cursor = 1;
    }
    if (StartingGame)
        lanConfig_cursor = 1;
    lanConfig_port = 26000;
    dpsnprintf(lanConfig_portname, sizeof(lanConfig_portname), "%u", (unsigned int) lanConfig_port);
    cl_connect_status[0] = '\0';
}
Referenced by M_MultiPlayer_Key(), and M_ServerList_Key().
M_Menu_Load_f()
void M_Menu_Load_f (cmd_state_t * cmd)
Definition at line 880 of file menu.c.
{
    m_entersound = true;
    m_state = m_load;
    key_dest = key_menu;
    M_ScanSaves ();
}
Referenced by M_Init(), M_Main_Key(), and M_SinglePlayer_Key().
M_Menu_Main_f()
void M_Menu_Main_f (cmd_state_t * cmd)
Definition at line 355 of file menu.c.
{
    const char *s;
    s = "gfx/mainmenu";
    if (gamemode == GAME_NEHAHRA)
    {
        if (FS_FileExists("maps/neh1m4.bsp"))
        {
            if (FS_FileExists("hearing.dem"))
            {
                Con_DPrint("Main menu: Nehahra movie and game detected.\n");
                NehGameType = TYPE_BOTH;
            }
            else
            {
                Con_DPrint("Nehahra game detected.\n");
                NehGameType = TYPE_GAME;
            }
        }
        else
        {
            if (FS_FileExists("hearing.dem"))
            {
                Con_DPrint("Nehahra movie detected.\n");
                NehGameType = TYPE_DEMO;
            }
            else
            {
                Con_DPrint("Nehahra not found.\n");
                NehGameType = TYPE_GAME; // could just complain, but...
            }
        }
        if (NehGameType == TYPE_DEMO)
            MAIN_ITEMS = 4;
        else if (NehGameType == TYPE_GAME)
            MAIN_ITEMS = 5;
        else
            MAIN_ITEMS = 6;
    }
    else if (gamemode == GAME_TRANSFUSION)
    {
        s = "gfx/menu/mainmenu1";
        if (sv.active && !cl.intermission && cl.islocalgame)
            MAIN_ITEMS = 8;
        else
            MAIN_ITEMS = 7;
    }
    else
        MAIN_ITEMS = 5;
    // check if the game data is missing and use a different main menu if so
    m_missingdata = !forceqmenu.integer && !Draw_IsPicLoaded(Draw_CachePic_Flags(s, CACHEPICFLAG_FAILONMISSING));
    if (m_missingdata)
        MAIN_ITEMS = 2;
    /*
    if (key_dest != key_menu)
    {
        m_save_demonum = cls.demonum;
        cls.demonum = -1;
    }
    */
    key_dest = key_menu;
    m_state = m_main;
    m_entersound = true;
}
Referenced by M_Credits_Key(), M_Demo_Key(), M_Help_Key(), M_Init(), M_Load_Key(), M_MultiPlayer_Key(), M_Options_Key(), M_Save_Key(), M_SinglePlayer_Key(), M_ToggleMenu(), and M_Transfusion_Episode_Key().
M_Menu_ModList_AdjustSliders()
static void M_Menu_ModList_AdjustSliders (int dir) static
Definition at line 4616 of file menu.c.
{
    int i;
    S_LocalSound ("sound/misc/menu3.wav");
    // stop adding mods, we reach the limit
    if (!modlist[modlist_cursor].loaded && (modlist_numenabled == MODLIST_MAXDIRS)) return;
    modlist[modlist_cursor].loaded = !modlist[modlist_cursor].loaded;
    if (modlist[modlist_cursor].loaded)
    {
        modlist[modlist_cursor].enabled = modlist_numenabled;
        //push the value on the enabled list
        modlist_enabled[modlist_numenabled++] = modlist_cursor;
    }
    else
    {
        //eliminate the value from the enabled list
        for (i = modlist[modlist_cursor].enabled; i < modlist_numenabled; i++)
        {
            modlist_enabled[i] = modlist_enabled[i+1];
            modlist[modlist_enabled[i]].enabled--;
        }
        modlist_numenabled--;
    }
}
Referenced by M_ModList_Key().
M_Menu_ModList_f()
void M_Menu_ModList_f (cmd_state_t * cmd)
Definition at line 4606 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_modlist;
    m_entersound = true;
    modlist_cursor = 0;
    cl_connect_status[0] = '\0';
    ModList_RebuildList();
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_MultiPlayer_f()
void M_Menu_MultiPlayer_f (cmd_state_t * cmd)
Definition at line 1190 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_multiplayer;
    m_entersound = true;
}
Referenced by M_GameOptions_Key(), M_Init(), M_LanConfig_Key(), M_Main_Key(), and M_Setup_Key().
M_Menu_Options_AdjustSliders()
static void M_Menu_Options_AdjustSliders (int dir) static
Definition at line 1585 of file menu.c.
{
    int optnum;
    double f;
    S_LocalSound ("sound/misc/menu3.wav");
    optnum = 0;
         if (options_cursor == optnum++) ;
    else if (options_cursor == optnum++) ;
    else if (options_cursor == optnum++) ;
    else if (options_cursor == optnum++) ;
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&crosshair, bound(0, crosshair.integer + dir, 7));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&sensitivity, bound(1, sensitivity.value + dir * 0.5, 50));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&m_pitch, -m_pitch.value);
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&scr_fov, bound(1, scr_fov.integer + dir * 1, 170));
    else if (options_cursor == optnum++)
    {
        if (cl_forwardspeed.value > 200)
        {
            Cvar_SetValueQuick (&cl_forwardspeed, 200);
            Cvar_SetValueQuick (&cl_backspeed, 200);
        }
        else
        {
            Cvar_SetValueQuick (&cl_forwardspeed, 400);
            Cvar_SetValueQuick (&cl_backspeed, 400);
        }
    }
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&cl_showfps, !cl_showfps.integer);
    else if (options_cursor == optnum++) {f = !(cl_showdate.integer && cl_showtime.integer);Cvar_SetValueQuick(&cl_showdate, f);Cvar_SetValueQuick(&cl_showtime, f);}
    else if (options_cursor == optnum++) ;
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&r_hdr_scenebrightness, bound(1, r_hdr_scenebrightness.value + dir * 0.0625, 4));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&v_contrast, bound(1, v_contrast.value + dir * 0.0625, 4));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&v_gamma, bound(0.5, v_gamma.value + dir * 0.0625, 3));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&volume, bound(0, volume.value + dir * 0.0625, 1));
    else if (options_cursor == optnum++) Cvar_SetValueQuick(&bgmvolume, bound(0, bgmvolume.value + dir * 0.0625, 1));
}
Referenced by M_Options_Key().
M_Menu_Options_ColorControl_AdjustSliders()
static void M_Menu_Options_ColorControl_AdjustSliders (int dir) static
Definition at line 2108 of file menu.c.
{
    int optnum;
    float f;
    S_LocalSound ("sound/misc/menu3.wav");
    optnum = 1;
    if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 0);
        Cvar_SetValueQuick (&v_gamma, bound(1, v_gamma.value + dir * 0.125, 5));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 0);
        Cvar_SetValueQuick (&v_contrast, bound(1, v_contrast.value + dir * 0.125, 5));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 0);
        Cvar_SetValueQuick (&v_brightness, bound(0, v_brightness.value + dir * 0.05, 0.8));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, !v_color_enable.integer);
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_black_r, bound(0, v_color_black_r.value + dir * 0.0125, 0.8));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_black_g, bound(0, v_color_black_g.value + dir * 0.0125, 0.8));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_black_b, bound(0, v_color_black_b.value + dir * 0.0125, 0.8));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        f = bound(0, (v_color_black_r.value + v_color_black_g.value + v_color_black_b.value) / 3 + dir * 0.0125, 0.8);
        Cvar_SetValueQuick (&v_color_black_r, f);
        Cvar_SetValueQuick (&v_color_black_g, f);
        Cvar_SetValueQuick (&v_color_black_b, f);
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_grey_r, bound(0, v_color_grey_r.value + dir * 0.0125, 0.95));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_grey_g, bound(0, v_color_grey_g.value + dir * 0.0125, 0.95));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_grey_b, bound(0, v_color_grey_b.value + dir * 0.0125, 0.95));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        f = bound(0, (v_color_grey_r.value + v_color_grey_g.value + v_color_grey_b.value) / 3 + dir * 0.0125, 0.95);
        Cvar_SetValueQuick (&v_color_grey_r, f);
        Cvar_SetValueQuick (&v_color_grey_g, f);
        Cvar_SetValueQuick (&v_color_grey_b, f);
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_white_r, bound(1, v_color_white_r.value + dir * 0.125, 5));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_white_g, bound(1, v_color_white_g.value + dir * 0.125, 5));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        Cvar_SetValueQuick (&v_color_white_b, bound(1, v_color_white_b.value + dir * 0.125, 5));
    }
    else if (options_colorcontrol_cursor == optnum++)
    {
        Cvar_SetValueQuick (&v_color_enable, 1);
        f = bound(1, (v_color_white_r.value + v_color_white_g.value + v_color_white_b.value) / 3 + dir * 0.125, 5);
        Cvar_SetValueQuick (&v_color_white_r, f);
        Cvar_SetValueQuick (&v_color_white_g, f);
        Cvar_SetValueQuick (&v_color_white_b, f);
    }
}
Referenced by M_Options_ColorControl_Key().
M_Menu_Options_ColorControl_f()
void M_Menu_Options_ColorControl_f (cmd_state_t * cmd)
Definition at line 2100 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_options_colorcontrol;
    m_entersound = true;
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_Options_Effects_AdjustSliders()
static void M_Menu_Options_Effects_AdjustSliders (int dir) static
Definition at line 1829 of file menu.c.
{
    int optnum;
    S_LocalSound ("sound/misc/menu3.wav");
    optnum = 0;
         if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles, !cl_particles.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_quake, !cl_particles_quake.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_quality, bound(1, cl_particles_quality.value + dir * 0.5, 4));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_explosions_shell, !cl_particles_explosions_shell.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_explosionclip, !r_explosionclip.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_stainmaps, !cl_stainmaps.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_stainmaps_clearonload, !cl_stainmaps_clearonload.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_decals, !cl_decals.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_bulletimpacts, !cl_particles_bulletimpacts.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_smoke, !cl_particles_smoke.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_sparks, !cl_particles_sparks.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_bubbles, !cl_particles_bubbles.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_blood, !cl_particles_blood.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_blood_alpha, bound(0.2, cl_particles_blood_alpha.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_particles_blood_bloodhack, !cl_particles_blood_bloodhack.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_beams_polygons, !cl_beams_polygons.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_beams_instantaimhack, !cl_beams_instantaimhack.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_beams_quakepositionhack, !cl_beams_quakepositionhack.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&cl_beams_lightatend, !cl_beams_lightatend.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_thickness, bound(1, r_lightningbeam_thickness.integer + dir, 10));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_scroll, bound(0, r_lightningbeam_scroll.integer + dir, 10));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_repeatdistance, bound(64, r_lightningbeam_repeatdistance.integer + dir * 64, 1024));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_color_red, bound(0, r_lightningbeam_color_red.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_color_green, bound(0, r_lightningbeam_color_green.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_color_blue, bound(0, r_lightningbeam_color_blue.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lightningbeam_qmbtexture, !r_lightningbeam_qmbtexture.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lerpmodels, !r_lerpmodels.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lerpsprites, !r_lerpsprites.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_lerplightstyles, !r_lerplightstyles.integer);
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&gl_polyblend, bound(0, gl_polyblend.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_skyscroll1, bound(-8, r_skyscroll1.value + dir * 0.1, 8));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_skyscroll2, bound(-8, r_skyscroll2.value + dir * 0.1, 8));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_waterwarp, bound(0, r_waterwarp.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_wateralpha, bound(0, r_wateralpha.value + dir * 0.1, 1));
    else if (options_effects_cursor == optnum++) Cvar_SetValueQuick (&r_waterscroll, bound(0, r_waterscroll.value + dir * 0.5, 10));
}
Referenced by M_Options_Effects_Key().
M_Menu_Options_Effects_f()
void M_Menu_Options_Effects_f (cmd_state_t * cmd)
Definition at line 1804 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_options_effects;
    m_entersound = true;
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_Options_f()
void M_Menu_Options_f (cmd_state_t * cmd)
Definition at line 1572 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_options;
    m_entersound = true;
}
Referenced by M_Init(), M_Keys_Key(), M_Main_Key(), M_ModList_Key(), M_Options_ColorControl_Key(), M_Options_Effects_Key(), M_Options_Graphics_Key(), and M_Video_Key().
M_Menu_Options_Graphics_AdjustSliders()
static void M_Menu_Options_Graphics_AdjustSliders (cmd_state_t * cmd, int dir) static
Definition at line 1991 of file menu.c.
{
    int optnum;
    S_LocalSound ("sound/misc/menu3.wav");
    optnum = 0;
         if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_coronas, bound(0, r_coronas.value + dir * 0.125, 4));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&gl_flashblend, !gl_flashblend.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_gloss,                          bound(0, r_shadow_gloss.integer + dir, 2));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_realtime_dlight,                !r_shadow_realtime_dlight.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_realtime_dlight_shadows,        !r_shadow_realtime_dlight_shadows.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_realtime_world,                 !r_shadow_realtime_world.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_realtime_world_lightmaps,       bound(0, r_shadow_realtime_world_lightmaps.value + dir * 0.1, 1));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_shadow_realtime_world_shadows,         !r_shadow_realtime_world_shadows.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom,                                 !r_bloom.integer);
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_hdr_scenebrightness,                   bound(0.25, r_hdr_scenebrightness.value + dir * 0.125, 4));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_hdr_glowintensity,                     bound(0, r_hdr_glowintensity.value + dir * 0.25, 4));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_colorscale,                      bound(0.0625, r_bloom_colorscale.value + dir * 0.0625, 1));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_colorsubtract,                   bound(0, r_bloom_colorsubtract.value + dir * 0.0625, 1-0.0625));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_colorexponent,                   bound(1, r_bloom_colorexponent.value * (dir > 0 ? 2.0 : 0.5), 8));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_brighten,                        bound(1, r_bloom_brighten.value + dir * 0.0625, 4));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_blur,                            bound(1, r_bloom_blur.value + dir * 1, 16));
    else if (options_graphics_cursor == optnum++) Cvar_SetValueQuick (&r_bloom_resolution,                      bound(64, r_bloom_resolution.value + dir * 64, 2048));
    else if (options_graphics_cursor == optnum++) Cbuf_AddText(cmd, "r_restart\n");
}
Referenced by M_Options_Graphics_Key().
M_Menu_Options_Graphics_f()
void M_Menu_Options_Graphics_f (cmd_state_t * cmd)
Definition at line 1967 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_options_graphics;
    m_entersound = true;
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_Quit_f()
void M_Menu_Quit_f (cmd_state_t * cmd)
Definition at line 3244 of file menu.c.
{
    int n;
    if (m_state == m_quit)
        return;
    wasInMenus = (key_dest == key_menu || key_dest == key_menu_grabbed);
    key_dest = key_menu;
    m_quit_prevstate = m_state;
    m_state = m_quit;
    m_entersound = true;
    // count how many there are
    for (n = 1;M_ChooseQuitMessage(n);n++);
    // choose one
    M_ChooseQuitMessage(rand() % n);
}
Referenced by M_Init(), and M_Main_Key().
M_Menu_Reset_f()
void M_Menu_Reset_f (cmd_state_t * cmd)
Definition at line 2729 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_reset;
    m_entersound = true;
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_Save_f()
void M_Menu_Save_f (cmd_state_t * cmd)
Definition at line 889 of file menu.c.
{
    if (!sv.active)
        return;
#if 1
    // LadyHavoc: allow saving multiplayer games
    if (cl.islocalgame && cl.intermission)
        return;
#else
    if (cl.intermission)
        return;
    if (!cl.islocalgame)
        return;
#endif
    m_entersound = true;
    m_state = m_save;
    key_dest = key_menu;
    M_ScanSaves ();
}
Referenced by M_Init(), M_Main_Key(), and M_SinglePlayer_Key().
M_Menu_ServerList_f()
void M_Menu_ServerList_f (cmd_state_t * cmd)
Definition at line 4383 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_slist;
    m_entersound = true;
    slist_cursor = 0;
    cl_connect_status[0] = '\0';
    if (lanConfig_cursor == 2)
        Net_SlistQW_f(cmd);
    else
        Net_Slist_f(cmd);
}
Referenced by M_LanConfig_Key().
M_Menu_Setup_f()
void M_Menu_Setup_f (cmd_state_t * cmd)
Definition at line 1282 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_setup;
    m_entersound = true;
    dp_strlcpy(setup_myname, cl_name.string, sizeof(setup_myname));
    setup_top = setup_oldtop = cl_topcolor.integer;
    setup_bottom = setup_oldbottom = cl_bottomcolor.integer;
    setup_rate = cl_rate.integer;
}
Referenced by M_Init(), and M_MultiPlayer_Key().
M_Menu_SinglePlayer_f()
void M_Menu_SinglePlayer_f (cmd_state_t * cmd)
Definition at line 730 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_singleplayer;
    m_entersound = true;
}
Referenced by M_Init(), M_Load_Key(), M_Main_Key(), and M_Save_Key().
M_Menu_Transfusion_Episode_f()
void M_Menu_Transfusion_Episode_f (cmd_state_t * cmd)
Definition at line 1030 of file menu.c.
{
    m_entersound = true;
    m_state = m_transfusion_episode;
    key_dest = key_menu;
}
Referenced by M_Init(), M_Main_Key(), M_SinglePlayer_Key(), and M_Transfusion_Skill_Key().
M_Menu_Transfusion_Skill_f()
void M_Menu_Transfusion_Skill_f (cmd_state_t * cmd)
Definition at line 1088 of file menu.c.
{
    m_entersound = true;
    m_state = m_transfusion_skill;
    key_dest = key_menu;
}
Referenced by M_Init(), and M_Transfusion_Episode_Key().
M_Menu_Video_AdjustSliders()
static void M_Menu_Video_AdjustSliders (int dir) static
Definition at line 2981 of file menu.c.
{
    int t;
    S_LocalSound ("sound/misc/menu3.wav");
    t = 0;
    if (video_cursor == t++)
    {
        // Resolution
        int r;
        for(r = 0;r < menu_video_resolutions_count;r++)
        {
            menu_video_resolution += dir;
            if (menu_video_resolution >= menu_video_resolutions_count)
                menu_video_resolution = 0;
            if (menu_video_resolution < 0)
                menu_video_resolution = menu_video_resolutions_count - 1;
            if (menu_video_resolutions[menu_video_resolution].width >= vid_minwidth.integer && menu_video_resolutions[menu_video_resolution].height >= vid_minheight.integer)
                break;
        }
    }
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&vid_samples, bound(1, vid_samples.value * (dir > 0 ? 2 : 0.5), 32));
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&vid_userefreshrate, !vid_userefreshrate.integer);
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&vid_refreshrate, bound(50, vid_refreshrate.value + dir, 150));
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&vid_fullscreen, !vid_fullscreen.integer);
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&vid_vsync, !vid_vsync.integer);
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&gl_texture_anisotropy, bound(1, gl_texture_anisotropy.value * (dir < 0 ? 0.5 : 2.0), vid.max_anisotropy));
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&gl_picmip, bound(0, gl_picmip.value - dir, 3));
    else if (video_cursor == t++)
        Cvar_SetValueQuick (&gl_texturecompression, !gl_texturecompression.integer);
}
Referenced by M_Video_Key().
M_Menu_Video_f()
void M_Menu_Video_f (cmd_state_t * cmd)
Definition at line 2893 of file menu.c.
{
    key_dest = key_menu;
    m_state = m_video;
    m_entersound = true;
    M_Menu_Video_FindResolution(vid.width, vid.height, vid_pixelheight.value);
}
Referenced by M_Init(), and M_Options_Key().
M_Menu_Video_FindResolution()
static void M_Menu_Video_FindResolution (int w, int h, float a) static
Definition at line 2845 of file menu.c.
{
    int i;
    if(menu_video_resolutions_forfullscreen)
    {
        menu_video_resolutions = video_resolutions;
        menu_video_resolutions_count = video_resolutions_count;
    }
    else
    {
        menu_video_resolutions = video_resolutions_hardcoded;
        menu_video_resolutions_count = video_resolutions_hardcoded_count;
    }
    // Look for the closest match to the current resolution
    menu_video_resolution = 0;
    for (i = 1;i < menu_video_resolutions_count;i++)
    {
        // if the new mode would be a worse match in width, skip it
        if (abs(menu_video_resolutions[i].width - w) > abs(menu_video_resolutions[menu_video_resolution].width - w))
            continue;
        // if it is equal in width, check height
        if (menu_video_resolutions[i].width == w && menu_video_resolutions[menu_video_resolution].width == w)
        {
            // if the new mode would be a worse match in height, skip it
            if (abs(menu_video_resolutions[i].height - h) > abs(menu_video_resolutions[menu_video_resolution].height - h))
                continue;
            // if it is equal in width and height, check pixel aspect
            if (menu_video_resolutions[i].height == h && menu_video_resolutions[menu_video_resolution].height == h)
            {
                // if the new mode would be a worse match in pixel aspect, skip it
                if (fabs(menu_video_resolutions[i].pixelheight - a) > fabs(menu_video_resolutions[menu_video_resolution].pixelheight - a))
                    continue;
                // if it is equal in everything, skip it (prefer earlier modes)
                if (menu_video_resolutions[i].pixelheight == a && menu_video_resolutions[menu_video_resolution].pixelheight == a)
                    continue;
                // better match for width, height, and pixel aspect
                menu_video_resolution = i;
            }
            else // better match for width and height
                menu_video_resolution = i;
        }
        else // better match for width
            menu_video_resolution = i;
    }
}
Referenced by M_Menu_Video_f(), M_Video_Draw(), and MR_Init().
M_ModList_Draw()
static void M_ModList_Draw (void) static
Definition at line 4642 of file menu.c.
{
    int n, y, visible, start, end;
    cachepic_t *p;
    const char *s_available = "Available Mods";
    const char *s_enabled = "Enabled Mods";
    // use as much vertical space as available
    if (gamemode == GAME_TRANSFUSION)
        M_Background(640, vid_conheight.integer - 80);
    else
        M_Background(640, vid_conheight.integer);
    M_PrintRed(48 + 32, 32, s_available);
    M_PrintRed(432, 32, s_enabled);
    // Draw a list box with all enabled mods
    DrawQ_Pic(menu_x + 432, menu_y + 48, NULL, 172, 8 * modlist_numenabled, 0, 0, 0, 0.5, 0);
    for (y = 0; y < modlist_numenabled; y++)
        M_PrintRed(432, 48 + y * 8, modlist[modlist_enabled[y]].dir);
    if (*cl_connect_status)
        M_Print(16, menu_height - 8, cl_connect_status);
    // scroll the list as the cursor moves
    y = 48;
    visible = (int)((menu_height - 16 - y) / 8 / 2);
    start = bound(0, modlist_cursor - (visible >> 1), modlist_count - visible);
    end = min(start + visible, modlist_count);
    p = Draw_CachePic ("gfx/p_option");
    M_DrawPic((640 - Draw_GetPicWidth(p)) / 2, 4, "gfx/p_option");
    if (end > start)
    {
        for (n = start;n < end;n++)
        {
            DrawQ_Pic(menu_x + 40, menu_y + y, NULL, 360, 8, n == modlist_cursor ? (0.5 + 0.2 * sin(host.realtime * M_PI)) : 0, 0, 0, 0.5, 0);
            M_ItemPrint(80, y, modlist[n].dir, true);
            M_DrawCheckbox(48, y, modlist[n].loaded);
            y +=8;
        }
    }
    else
    {
        M_Print(80, y, "No Mods found");
    }
}
Referenced by M_Draw().
M_ModList_Key()
static void M_ModList_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 4688 of file menu.c.
{
    switch (k)
    {
    case K_ESCAPE:
        ModList_Enable ();
        M_Menu_Options_f(cmd);
        break;
    case K_SPACE:
        S_LocalSound ("sound/misc/menu2.wav");
        ModList_RebuildList();
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        modlist_cursor--;
        if (modlist_cursor < 0)
            modlist_cursor = modlist_count - 1;
        break;
    case K_LEFTARROW:
        M_Menu_ModList_AdjustSliders (-1);
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        modlist_cursor++;
        if (modlist_cursor >= modlist_count)
            modlist_cursor = 0;
        break;
    case K_RIGHTARROW:
        M_Menu_ModList_AdjustSliders (1);
        break;
    case K_ENTER:
        S_LocalSound ("sound/misc/menu2.wav");
        ModList_Enable ();
        break;
    default:
        break;
    }
}
Referenced by M_KeyEvent().
M_MultiPlayer_Draw()
static void M_MultiPlayer_Draw (void) static
Definition at line 1198 of file menu.c.
{
    int     f;
    cachepic_t  *p;
    char vabuf[1024];
    if (gamemode == GAME_TRANSFUSION)
    {
        M_Background(640, 480);
        p = Draw_CachePic ("gfx/menu/tb-online");
        M_DrawPic (640/2 - Draw_GetPicWidth(p)/2, 140, "gfx/menu/tb-online");
        for (f = 1; f <= MULTIPLAYER_ITEMS; f++)
            M_DrawPic (0, 180 + f*40, va(vabuf, sizeof(vabuf), "gfx/menu/online%i", f));
        M_DrawPic (0, 220 + m_multiplayer_cursor * 40, va(vabuf, sizeof(vabuf), "gfx/menu/online%iselected", m_multiplayer_cursor + 1));
        return;
    }
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_multi");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/p_multi");
    M_DrawPic (72, 32, "gfx/mp_menu");
    f = (int)(host.realtime * 10)%6;
    M_DrawPic (54, 32 + m_multiplayer_cursor * 20, va(vabuf, sizeof(vabuf), "gfx/menudot%i", f+1));
}
Referenced by M_Draw().
M_MultiPlayer_Key()
static void M_MultiPlayer_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1227 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Main_f(cmd);
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (++m_multiplayer_cursor >= MULTIPLAYER_ITEMS)
            m_multiplayer_cursor = 0;
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (--m_multiplayer_cursor < 0)
            m_multiplayer_cursor = MULTIPLAYER_ITEMS - 1;
        break;
    case K_ENTER:
        m_entersound = true;
        switch (m_multiplayer_cursor)
        {
        case 0:
        case 1:
            M_Menu_LanConfig_f(cmd);
            break;
        case 2:
            M_Menu_Setup_f(cmd);
            break;
        }
    }
}
Referenced by M_KeyEvent().
M_NetStart_Change()
static void M_NetStart_Change (int dir) static
Definition at line 4131 of file menu.c.
{
    int count;
    switch (gameoptions_cursor)
    {
    case 1:
        maxplayers += dir;
        if (maxplayers > MAX_SCOREBOARD)
        {
            maxplayers = MAX_SCOREBOARD;
            m_serverInfoMessage = true;
            m_serverInfoMessageTime = host.realtime;
        }
        if (maxplayers < 2)
            maxplayers = 2;
        break;
    case 2:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        if (gamemode == GAME_TRANSFUSION)
        {
            switch (deathmatch.integer)
            {
                // From Cooperative to BloodBath
                case 0:
                    Cvar_SetValueQuick (&coop, 0);
                    Cvar_SetValueQuick (&deathmatch, 1);
                    break;
                // From BloodBath to CTF
                case 1:
                    Cvar_SetValueQuick (&coop, 0);
                    Cvar_SetValueQuick (&deathmatch, 2);
                    break;
                // From CTF to Cooperative
                //case 2:
                default:
                    Cvar_SetValueQuick (&coop, 1);
                    Cvar_SetValueQuick (&deathmatch, 0);
            }
        }
        else if (gamemode == GAME_BATTLEMECH)
        {
            if (deathmatch.integer == 2) // changing from Rambo to Deathmatch
                Cvar_SetValueQuick (&deathmatch, 0);
            else // changing from Deathmatch to Rambo
                Cvar_SetValueQuick (&deathmatch, 2);
        }
        else
        {
            if (deathmatch.integer) // changing from deathmatch to coop
            {
                Cvar_SetValueQuick (&coop, 1);
                Cvar_SetValueQuick (&deathmatch, 0);
            }
            else // changing from coop to deathmatch
            {
                Cvar_SetValueQuick (&coop, 0);
                Cvar_SetValueQuick (&deathmatch, 1);
            }
        }
        break;
    case 3:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        if (gamemode == GAME_ROGUE)
            count = 6;
        else
            count = 2;
        Cvar_SetValueQuick (&teamplay, teamplay.integer + dir);
        if (teamplay.integer > count)
            Cvar_SetValueQuick (&teamplay, 0);
        else if (teamplay.integer < 0)
            Cvar_SetValueQuick (&teamplay, count);
        break;
    case 4:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        Cvar_SetValueQuick (&skill, skill.integer + dir);
        if (gamemode == GAME_TRANSFUSION)
        {
            if (skill.integer > 5)
                Cvar_SetValueQuick (&skill, 1);
            if (skill.integer < 1)
                Cvar_SetValueQuick (&skill, 5);
        }
        else
        {
            if (skill.integer > 3)
                Cvar_SetValueQuick (&skill, 0);
            if (skill.integer < 0)
                Cvar_SetValueQuick (&skill, 3);
        }
        break;
    case 5:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        Cvar_SetValueQuick (&fraglimit, fraglimit.integer + dir*10);
        if (fraglimit.integer > 100)
            Cvar_SetValueQuick (&fraglimit, 0);
        if (fraglimit.integer < 0)
            Cvar_SetValueQuick (&fraglimit, 100);
        break;
    case 6:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        Cvar_SetValueQuick (&timelimit, timelimit.value + dir*5);
        if (timelimit.value > 60)
            Cvar_SetValueQuick (&timelimit, 0);
        if (timelimit.value < 0)
            Cvar_SetValueQuick (&timelimit, 60);
        break;
    case 7:
        Cvar_SetValueQuick (&sv_public, !sv_public.integer);
        break;
    case 8:
        Cvar_SetValueQuick (&sv_maxrate, sv_maxrate.integer + dir*500);
        if (sv_maxrate.integer < NET_MINRATE)
            Cvar_SetValueQuick (&sv_maxrate, NET_MINRATE);
        break;
    case 9:
        break;
    case 10:
        if (gamemode == GAME_GOODVSBAD2)
            break;
        startepisode += dir;
        if (startepisode < 0)
            startepisode = gameoptions_levels->numepisodes - 1;
        if (startepisode >= gameoptions_levels->numepisodes)
            startepisode = 0;
        startlevel = 0;
        break;
    case 11:
        startlevel += dir;
        if (startlevel < 0)
            startlevel = gameoptions_levels->episodes[startepisode].levels - 1;
        if (startlevel >= gameoptions_levels->episodes[startepisode].levels)
            startlevel = 0;
        break;
    }
}
Referenced by M_GameOptions_Key().
M_NewMap()
static void M_NewMap (void) static
Definition at line 5023 of file menu.c.
{
}
Referenced by MR_SetRouting().
M_Options_ColorControl_Draw()
static void M_Options_ColorControl_Draw (void) static
Definition at line 2205 of file menu.c.
{
    int visible;
    float x, s, t, u, v;
    float c[3];
    cachepic_t  *p, *dither;
    dither = Draw_CachePic_Flags ("gfx/colorcontrol/ditherpattern", CACHEPICFLAG_NOCLAMP);
    M_Background(320, 256);
    M_DrawPic(16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_option");
    M_DrawPic((320-Draw_GetPicWidth(p))/2, 4, "gfx/p_option");
    m_optcursor = options_colorcontrol_cursor;
    m_optnum = 0;
    visible = (int)((menu_height - 32) / 8);
    m_opty = 32 - bound(0, m_optcursor - (visible >> 1), max(0, OPTIONS_COLORCONTROL_ITEMS - visible)) * 8;
    M_Options_PrintCommand( "     Reset to defaults", true);
    M_Options_PrintSlider(  "                 Gamma", !v_color_enable.integer, v_gamma.value, 1, 5);
    M_Options_PrintSlider(  "              Contrast", !v_color_enable.integer, v_contrast.value, 1, 5);
    M_Options_PrintSlider(  "            Brightness", !v_color_enable.integer, v_brightness.value, 0, 0.8);
    M_Options_PrintCheckbox("  Color Level Controls", true, v_color_enable.integer);
    M_Options_PrintSlider(  "          Black: Red  ", v_color_enable.integer, v_color_black_r.value, 0, 0.8);
    M_Options_PrintSlider(  "          Black: Green", v_color_enable.integer, v_color_black_g.value, 0, 0.8);
    M_Options_PrintSlider(  "          Black: Blue ", v_color_enable.integer, v_color_black_b.value, 0, 0.8);
    M_Options_PrintSlider(  "          Black: Grey ", v_color_enable.integer, (v_color_black_r.value + v_color_black_g.value + v_color_black_b.value) / 3, 0, 0.8);
    M_Options_PrintSlider(  "           Grey: Red  ", v_color_enable.integer, v_color_grey_r.value, 0, 0.95);
    M_Options_PrintSlider(  "           Grey: Green", v_color_enable.integer, v_color_grey_g.value, 0, 0.95);
    M_Options_PrintSlider(  "           Grey: Blue ", v_color_enable.integer, v_color_grey_b.value, 0, 0.95);
    M_Options_PrintSlider(  "           Grey: Grey ", v_color_enable.integer, (v_color_grey_r.value + v_color_grey_g.value + v_color_grey_b.value) / 3, 0, 0.95);
    M_Options_PrintSlider(  "          White: Red  ", v_color_enable.integer, v_color_white_r.value, 1, 5);
    M_Options_PrintSlider(  "          White: Green", v_color_enable.integer, v_color_white_g.value, 1, 5);
    M_Options_PrintSlider(  "          White: Blue ", v_color_enable.integer, v_color_white_b.value, 1, 5);
    M_Options_PrintSlider(  "          White: Grey ", v_color_enable.integer, (v_color_white_r.value + v_color_white_g.value + v_color_white_b.value) / 3, 1, 5);
    m_opty += 4;
    DrawQ_Fill(menu_x, menu_y + m_opty, 320, 4 + 64 + 8 + 64 + 4, 0, 0, 0, 1, 0);m_opty += 4;
    s = (float) 312 / 2 * vid.width / vid_conwidth.integer;
    t = (float) 4 / 2 * vid.height / vid_conheight.integer;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, dither, 312, 4, 0,0, 1,0,0,1, s,0, 1,0,0,1, 0,t, 1,0,0,1, s,t, 1,0,0,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, NULL  , 312, 4, 0,0, 0,0,0,1, 1,0, 1,0,0,1, 0,1, 0,0,0,1, 1,1, 1,0,0,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, dither, 312, 4, 0,0, 0,1,0,1, s,0, 0,1,0,1, 0,t, 0,1,0,1, s,t, 0,1,0,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, NULL  , 312, 4, 0,0, 0,0,0,1, 1,0, 0,1,0,1, 0,1, 0,0,0,1, 1,1, 0,1,0,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, dither, 312, 4, 0,0, 0,0,1,1, s,0, 0,0,1,1, 0,t, 0,0,1,1, s,t, 0,0,1,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, NULL  , 312, 4, 0,0, 0,0,0,1, 1,0, 0,0,1,1, 0,1, 0,0,0,1, 1,1, 0,0,1,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, dither, 312, 4, 0,0, 1,1,1,1, s,0, 1,1,1,1, 0,t, 1,1,1,1, s,t, 1,1,1,1, 0);m_opty += 4;
    DrawQ_SuperPic(menu_x + 4, menu_y + m_opty, NULL  , 312, 4, 0,0, 0,0,0,1, 1,0, 1,1,1,1, 0,1, 0,0,0,1, 1,1, 1,1,1,1, 0);m_opty += 4;
    c[0] = menu_options_colorcontrol_correctionvalue.value; // intensity value that should be matched up to a 50% dither to 'correct' quake
    c[1] = c[0];
    c[2] = c[1];
    VID_ApplyGammaToColor(c, c);
    s = (float) 48 / 2 * vid.width / vid_conwidth.integer;
    t = (float) 48 / 2 * vid.height / vid_conheight.integer;
    u = s * 0.5;
    v = t * 0.5;
    m_opty += 8;
    x = 4;
    DrawQ_Fill(menu_x + x, menu_y + m_opty, 64, 48, c[0], 0, 0, 1, 0);
    DrawQ_SuperPic(menu_x + x + 16, menu_y + m_opty + 16, dither, 16, 16, 0,0, 1,0,0,1, s,0, 1,0,0,1, 0,t, 1,0,0,1, s,t, 1,0,0,1, 0);
    DrawQ_SuperPic(menu_x + x + 32, menu_y + m_opty + 16, dither, 16, 16, 0,0, 1,0,0,1, u,0, 1,0,0,1, 0,v, 1,0,0,1, u,v, 1,0,0,1, 0);
    x += 80;
    DrawQ_Fill(menu_x + x, menu_y + m_opty, 64, 48, 0, c[1], 0, 1, 0);
    DrawQ_SuperPic(menu_x + x + 16, menu_y + m_opty + 16, dither, 16, 16, 0,0, 0,1,0,1, s,0, 0,1,0,1, 0,t, 0,1,0,1, s,t, 0,1,0,1, 0);
    DrawQ_SuperPic(menu_x + x + 32, menu_y + m_opty + 16, dither, 16, 16, 0,0, 0,1,0,1, u,0, 0,1,0,1, 0,v, 0,1,0,1, u,v, 0,1,0,1, 0);
    x += 80;
    DrawQ_Fill(menu_x + x, menu_y + m_opty, 64, 48, 0, 0, c[2], 1, 0);
    DrawQ_SuperPic(menu_x + x + 16, menu_y + m_opty + 16, dither, 16, 16, 0,0, 0,0,1,1, s,0, 0,0,1,1, 0,t, 0,0,1,1, s,t, 0,0,1,1, 0);
    DrawQ_SuperPic(menu_x + x + 32, menu_y + m_opty + 16, dither, 16, 16, 0,0, 0,0,1,1, u,0, 0,0,1,1, 0,v, 0,0,1,1, u,v, 0,0,1,1, 0);
    x += 80;
    DrawQ_Fill(menu_x + x, menu_y + m_opty, 64, 48, c[0], c[1], c[2], 1, 0);
    DrawQ_SuperPic(menu_x + x + 16, menu_y + m_opty + 16, dither, 16, 16, 0,0, 1,1,1,1, s,0, 1,1,1,1, 0,t, 1,1,1,1, s,t, 1,1,1,1, 0);
    DrawQ_SuperPic(menu_x + x + 32, menu_y + m_opty + 16, dither, 16, 16, 0,0, 1,1,1,1, u,0, 1,1,1,1, 0,v, 1,1,1,1, u,v, 1,1,1,1, 0);
}
Referenced by M_Draw().
M_Options_ColorControl_Key()
static void M_Options_ColorControl_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 2284 of file menu.c.
{
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Options_f(cmd);
        break;
    case K_ENTER:
        m_entersound = true;
        switch (options_colorcontrol_cursor)
        {
        case 0:
            Cvar_SetValueQuick(&v_gamma, 1);
            Cvar_SetValueQuick(&v_contrast, 1);
            Cvar_SetValueQuick(&v_brightness, 0);
            Cvar_SetValueQuick(&v_color_enable, 0);
            Cvar_SetValueQuick(&v_color_black_r, 0);
            Cvar_SetValueQuick(&v_color_black_g, 0);
            Cvar_SetValueQuick(&v_color_black_b, 0);
            Cvar_SetValueQuick(&v_color_grey_r, 0);
            Cvar_SetValueQuick(&v_color_grey_g, 0);
            Cvar_SetValueQuick(&v_color_grey_b, 0);
            Cvar_SetValueQuick(&v_color_white_r, 1);
            Cvar_SetValueQuick(&v_color_white_g, 1);
            Cvar_SetValueQuick(&v_color_white_b, 1);
            break;
        default:
            M_Menu_Options_ColorControl_AdjustSliders (1);
            break;
        }
        return;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_colorcontrol_cursor--;
        if (options_colorcontrol_cursor < 0)
            options_colorcontrol_cursor = OPTIONS_COLORCONTROL_ITEMS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_colorcontrol_cursor++;
        if (options_colorcontrol_cursor >= OPTIONS_COLORCONTROL_ITEMS)
            options_colorcontrol_cursor = 0;
        break;
    case K_LEFTARROW:
        M_Menu_Options_ColorControl_AdjustSliders (-1);
        break;
    case K_RIGHTARROW:
        M_Menu_Options_ColorControl_AdjustSliders (1);
        break;
    }
}
Referenced by M_KeyEvent().
M_Options_Draw()
static void M_Options_Draw (void) static
Definition at line 1665 of file menu.c.
{
    int visible;
    cachepic_t  *p;
    M_Background(320, bound(200, 32 + OPTIONS_ITEMS * 8, vid_conheight.integer));
    M_DrawPic(16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_option");
    M_DrawPic((320-Draw_GetPicWidth(p))/2, 4, "gfx/p_option");
    m_optnum = 0;
    m_optcursor = options_cursor;
    visible = (int)((menu_height - 32) / 8);
    m_opty = 32 - bound(0, m_optcursor - (visible >> 1), max(0, OPTIONS_ITEMS - visible)) * 8;
    M_Options_PrintCommand( "    Customize controls", true);
    M_Options_PrintCommand( "         Go to console", true);
    M_Options_PrintCommand( "     Reset to defaults", true);
    M_Options_PrintCommand( "     Change Video Mode", true);
    M_Options_PrintSlider(  "             Crosshair", true, crosshair.value, 0, 7);
    M_Options_PrintSlider(  "           Mouse Speed", true, sensitivity.value, 1, 50);
    M_Options_PrintCheckbox("          Invert Mouse", true, m_pitch.value < 0);
    M_Options_PrintSlider(  "         Field of View", true, scr_fov.integer, 1, 170);
    M_Options_PrintCheckbox("            Always Run", true, cl_forwardspeed.value > 200);
    M_Options_PrintCheckbox("        Show Framerate", true, cl_showfps.integer);
    M_Options_PrintCheckbox("    Show Date and Time", true, cl_showdate.integer && cl_showtime.integer);
    M_Options_PrintCommand( "     Custom Brightness", true);
    M_Options_PrintSlider(  "       Game Brightness", true, r_hdr_scenebrightness.value, 1, 4);
    M_Options_PrintSlider(  "            Brightness", true, v_contrast.value, 1, 2);
    M_Options_PrintSlider(  "                 Gamma", true, v_gamma.value, 0.5, 3);
    M_Options_PrintSlider(  "          Sound Volume", snd_initialized.integer, volume.value, 0, 1);
    M_Options_PrintSlider(  "          Music Volume", cdaudioinitialized.integer, bgmvolume.value, 0, 1);
    M_Options_PrintCommand( "     Customize Effects", true);
    M_Options_PrintCommand( "       Effects:  Quake", true);
    M_Options_PrintCommand( "       Effects: Normal", true);
    M_Options_PrintCommand( "       Effects:   High", true);
    M_Options_PrintCommand( "    Customize Lighting", true);
    M_Options_PrintCommand( "      Lighting: Flares", true);
    M_Options_PrintCommand( "      Lighting: Normal", true);
    M_Options_PrintCommand( "      Lighting:   High", true);
    M_Options_PrintCommand( "      Lighting:   Full", true);
    M_Options_PrintCommand( "           Browse Mods", true);
}
Referenced by M_Draw().
M_Options_Effects_Draw()
static void M_Options_Effects_Draw (void) static
Definition at line 1872 of file menu.c.
{
    int visible;
    cachepic_t  *p;
    M_Background(320, bound(200, 32 + OPTIONS_EFFECTS_ITEMS * 8, vid_conheight.integer));
    M_DrawPic(16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_option");
    M_DrawPic((320-Draw_GetPicWidth(p))/2, 4, "gfx/p_option");
    m_optcursor = options_effects_cursor;
    m_optnum = 0;
    visible = (int)((menu_height - 32) / 8);
    m_opty = 32 - bound(0, m_optcursor - (visible >> 1), max(0, OPTIONS_EFFECTS_ITEMS - visible)) * 8;
    M_Options_PrintCheckbox("             Particles", true, cl_particles.integer);
    M_Options_PrintCheckbox(" Quake-style Particles", true, cl_particles_quake.integer);
    M_Options_PrintSlider(  "     Particles Quality", true, cl_particles_quality.value, 1, 4);
    M_Options_PrintCheckbox("       Explosion Shell", true, cl_particles_explosions_shell.integer);
    M_Options_PrintCheckbox("  Explosion Shell Clip", true, r_explosionclip.integer);
    M_Options_PrintCheckbox("             Stainmaps", true, cl_stainmaps.integer);
    M_Options_PrintCheckbox("Onload Clear Stainmaps", true, cl_stainmaps_clearonload.integer);
    M_Options_PrintCheckbox("                Decals", true, cl_decals.integer);
    M_Options_PrintCheckbox("        Bullet Impacts", true, cl_particles_bulletimpacts.integer);
    M_Options_PrintCheckbox("                 Smoke", true, cl_particles_smoke.integer);
    M_Options_PrintCheckbox("                Sparks", true, cl_particles_sparks.integer);
    M_Options_PrintCheckbox("               Bubbles", true, cl_particles_bubbles.integer);
    M_Options_PrintCheckbox("                 Blood", true, cl_particles_blood.integer);
    M_Options_PrintSlider(  "         Blood Opacity", true, cl_particles_blood_alpha.value, 0.2, 1);
    M_Options_PrintCheckbox("Force New Blood Effect", true, cl_particles_blood_bloodhack.integer);
    M_Options_PrintCheckbox("     Polygon Lightning", true, cl_beams_polygons.integer);
    M_Options_PrintCheckbox("Smooth Sweep Lightning", true, cl_beams_instantaimhack.integer);
    M_Options_PrintCheckbox(" Waist-level Lightning", true, cl_beams_quakepositionhack.integer);
    M_Options_PrintCheckbox("   Lightning End Light", true, cl_beams_lightatend.integer);
    M_Options_PrintSlider(  "   Lightning Thickness", cl_beams_polygons.integer, r_lightningbeam_thickness.integer, 1, 10);
    M_Options_PrintSlider(  "      Lightning Scroll", cl_beams_polygons.integer, r_lightningbeam_scroll.integer, 0, 10);
    M_Options_PrintSlider(  " Lightning Repeat Dist", cl_beams_polygons.integer, r_lightningbeam_repeatdistance.integer, 64, 1024);
    M_Options_PrintSlider(  "   Lightning Color Red", cl_beams_polygons.integer, r_lightningbeam_color_red.value, 0, 1);
    M_Options_PrintSlider(  " Lightning Color Green", cl_beams_polygons.integer, r_lightningbeam_color_green.value, 0, 1);
    M_Options_PrintSlider(  "  Lightning Color Blue", cl_beams_polygons.integer, r_lightningbeam_color_blue.value, 0, 1);
    M_Options_PrintCheckbox(" Lightning QMB Texture", cl_beams_polygons.integer, r_lightningbeam_qmbtexture.integer);
    M_Options_PrintCheckbox("   Model Interpolation", true, r_lerpmodels.integer);
    M_Options_PrintCheckbox("  Sprite Interpolation", true, r_lerpsprites.integer);
    M_Options_PrintCheckbox(" Flicker Interpolation", true, r_lerplightstyles.integer);
    M_Options_PrintSlider(  "            View Blend", true, gl_polyblend.value, 0, 1);
    M_Options_PrintSlider(  "Upper Sky Scroll Speed", true, r_skyscroll1.value, -8, 8);
    M_Options_PrintSlider(  "Lower Sky Scroll Speed", true, r_skyscroll2.value, -8, 8);
    M_Options_PrintSlider(  "  Underwater View Warp", true, r_waterwarp.value, 0, 1);
    M_Options_PrintSlider(  " Water Alpha (opacity)", true, r_wateralpha.value, 0, 1);
    M_Options_PrintSlider(  "        Water Movement", true, r_waterscroll.value, 0, 10);
}
Referenced by M_Draw().
M_Options_Effects_Key()
static void M_Options_Effects_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1926 of file menu.c.
{
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Options_f(cmd);
        break;
    case K_ENTER:
        M_Menu_Options_Effects_AdjustSliders (1);
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_effects_cursor--;
        if (options_effects_cursor < 0)
            options_effects_cursor = OPTIONS_EFFECTS_ITEMS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_effects_cursor++;
        if (options_effects_cursor >= OPTIONS_EFFECTS_ITEMS)
            options_effects_cursor = 0;
        break;
    case K_LEFTARROW:
        M_Menu_Options_Effects_AdjustSliders (-1);
        break;
    case K_RIGHTARROW:
        M_Menu_Options_Effects_AdjustSliders (1);
        break;
    }
}
Referenced by M_KeyEvent().
M_Options_Graphics_Draw()
static void M_Options_Graphics_Draw (void) static
Definition at line 2019 of file menu.c.
{
    int visible;
    cachepic_t  *p;
    M_Background(320, bound(200, 32 + OPTIONS_GRAPHICS_ITEMS * 8, vid_conheight.integer));
    M_DrawPic(16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_option");
    M_DrawPic((320-Draw_GetPicWidth(p))/2, 4, "gfx/p_option");
    m_optcursor = options_graphics_cursor;
    m_optnum = 0;
    visible = (int)((menu_height - 32) / 8);
    m_opty = 32 - bound(0, m_optcursor - (visible >> 1), max(0, OPTIONS_GRAPHICS_ITEMS - visible)) * 8;
    M_Options_PrintSlider(  "      Corona Intensity", true, r_coronas.value, 0, 4);
    M_Options_PrintCheckbox("      Use Only Coronas", true, gl_flashblend.integer);
    M_Options_PrintSlider(  "            Gloss Mode", true, r_shadow_gloss.integer, 0, 2);
    M_Options_PrintCheckbox("            RT DLights", !gl_flashblend.integer, r_shadow_realtime_dlight.integer);
    M_Options_PrintCheckbox("     RT DLight Shadows", !gl_flashblend.integer, r_shadow_realtime_dlight_shadows.integer);
    M_Options_PrintCheckbox("              RT World", true, r_shadow_realtime_world.integer);
    M_Options_PrintSlider(  "    RT World Lightmaps", true, r_shadow_realtime_world_lightmaps.value, 0, 1);
    M_Options_PrintCheckbox("       RT World Shadow", true, r_shadow_realtime_world_shadows.integer);
    M_Options_PrintCheckbox("          Bloom Effect", true, r_bloom.integer);
    M_Options_PrintSlider(  "      Scene Brightness", true, r_hdr_scenebrightness.value, 0.25, 4);
    M_Options_PrintSlider(  "       Glow Brightness", true, r_hdr_glowintensity.value, 0, 4);
    M_Options_PrintSlider(  "     Bloom Color Scale", r_bloom.integer, r_bloom_colorscale.value, 0.0625, 1);
    M_Options_PrintSlider(  "  Bloom Color Subtract", r_bloom.integer, r_bloom_colorsubtract.value, 0, 1-0.0625);
    M_Options_PrintSlider(  "  Bloom Color Exponent", r_bloom.integer, r_bloom_colorexponent.value, 1, 8);
    M_Options_PrintSlider(  "       Bloom Intensity", r_bloom.integer, r_bloom_brighten.value, 1, 4);
    M_Options_PrintSlider(  "            Bloom Blur", r_bloom.integer, r_bloom_blur.value, 1, 16);
    M_Options_PrintSlider(  "      Bloom Resolution", r_bloom.integer, r_bloom_resolution.value, 64, 2048);
    M_Options_PrintCommand( "      Restart Renderer", true);
}
Referenced by M_Draw().
M_Options_Graphics_Key()
static void M_Options_Graphics_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 2056 of file menu.c.
{
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Options_f(cmd);
        break;
    case K_ENTER:
        M_Menu_Options_Graphics_AdjustSliders (cmd, 1);
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_graphics_cursor--;
        if (options_graphics_cursor < 0)
            options_graphics_cursor = OPTIONS_GRAPHICS_ITEMS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_graphics_cursor++;
        if (options_graphics_cursor >= OPTIONS_GRAPHICS_ITEMS)
            options_graphics_cursor = 0;
        break;
    case K_LEFTARROW:
        M_Menu_Options_Graphics_AdjustSliders(cmd, -1);
        break;
    case K_RIGHTARROW:
        M_Menu_Options_Graphics_AdjustSliders(cmd, 1);
        break;
    }
}
Referenced by M_KeyEvent().
M_Options_Key()
static void M_Options_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1711 of file menu.c.
{
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_Main_f(cmd);
        break;
    case K_ENTER:
        m_entersound = true;
        switch (options_cursor)
        {
        case 0:
            M_Menu_Keys_f(cmd);
            break;
        case 1:
            m_state = m_none;
            key_dest = key_game;
            Con_ToggleConsole_f(cmd);
            break;
        case 2:
            M_Menu_Reset_f(cmd);
            break;
        case 3:
            M_Menu_Video_f(cmd);
            break;
        case 11:
            M_Menu_Options_ColorControl_f(cmd);
            break;
        case 17: // Customize Effects
            M_Menu_Options_Effects_f(cmd);
            break;
        case 18: // Effects: Quake
            Cbuf_AddText(cmd, "cl_particles 1;cl_particles_quake 1;cl_particles_quality 1;cl_particles_explosions_shell 0;r_explosionclip 1;cl_stainmaps 0;cl_stainmaps_clearonload 1;cl_decals 0;cl_particles_bulletimpacts 1;cl_particles_smoke 1;cl_particles_sparks 1;cl_particles_bubbles 1;cl_particles_blood 1;cl_particles_blood_alpha 1;cl_particles_blood_bloodhack 0;cl_beams_polygons 0;cl_beams_instantaimhack 0;cl_beams_quakepositionhack 1;cl_beams_lightatend 0;r_lerpmodels 1;r_lerpsprites 1;r_lerplightstyles 0;gl_polyblend 1;r_skyscroll1 1;r_skyscroll2 2;r_waterwarp 1;r_wateralpha 1;r_waterscroll 1\n");
            break;
        case 19: // Effects: Normal
            Cbuf_AddText(cmd, "cl_particles 1;cl_particles_quake 0;cl_particles_quality 1;cl_particles_explosions_shell 0;r_explosionclip 1;cl_stainmaps 0;cl_stainmaps_clearonload 1;cl_decals 1;cl_particles_bulletimpacts 1;cl_particles_smoke 1;cl_particles_sparks 1;cl_particles_bubbles 1;cl_particles_blood 1;cl_particles_blood_alpha 1;cl_particles_blood_bloodhack 1;cl_beams_polygons 1;cl_beams_instantaimhack 0;cl_beams_quakepositionhack 1;cl_beams_lightatend 0;r_lerpmodels 1;r_lerpsprites 1;r_lerplightstyles 0;gl_polyblend 1;r_skyscroll1 1;r_skyscroll2 2;r_waterwarp 1;r_wateralpha 1;r_waterscroll 1\n");
            break;
        case 20: // Effects: High
            Cbuf_AddText(cmd, "cl_particles 1;cl_particles_quake 0;cl_particles_quality 2;cl_particles_explosions_shell 0;r_explosionclip 1;cl_stainmaps 1;cl_stainmaps_clearonload 1;cl_decals 1;cl_particles_bulletimpacts 1;cl_particles_smoke 1;cl_particles_sparks 1;cl_particles_bubbles 1;cl_particles_blood 1;cl_particles_blood_alpha 1;cl_particles_blood_bloodhack 1;cl_beams_polygons 1;cl_beams_instantaimhack 0;cl_beams_quakepositionhack 1;cl_beams_lightatend 0;r_lerpmodels 1;r_lerpsprites 1;r_lerplightstyles 0;gl_polyblend 1;r_skyscroll1 1;r_skyscroll2 2;r_waterwarp 1;r_wateralpha 1;r_waterscroll 1\n");
            break;
        case 21:
            M_Menu_Options_Graphics_f(cmd);
            break;
        case 22: // Lighting: Flares
            Cbuf_AddText(cmd, "r_coronas 1;gl_flashblend 1;r_shadow_gloss 0;r_shadow_realtime_dlight 0;r_shadow_realtime_dlight_shadows 0;r_shadow_realtime_world 0;r_shadow_realtime_world_lightmaps 0;r_shadow_realtime_world_shadows 1;r_bloom 0");
            break;
        case 23: // Lighting: Normal
            Cbuf_AddText(cmd, "r_coronas 1;gl_flashblend 0;r_shadow_gloss 1;r_shadow_realtime_dlight 1;r_shadow_realtime_dlight_shadows 0;r_shadow_realtime_world 0;r_shadow_realtime_world_lightmaps 0;r_shadow_realtime_world_shadows 1;r_bloom 0");
            break;
        case 24: // Lighting: High
            Cbuf_AddText(cmd, "r_coronas 1;gl_flashblend 0;r_shadow_gloss 1;r_shadow_realtime_dlight 1;r_shadow_realtime_dlight_shadows 1;r_shadow_realtime_world 0;r_shadow_realtime_world_lightmaps 0;r_shadow_realtime_world_shadows 1;r_bloom 1");
            break;
        case 25: // Lighting: Full
            Cbuf_AddText(cmd, "r_coronas 1;gl_flashblend 0;r_shadow_gloss 1;r_shadow_realtime_dlight 1;r_shadow_realtime_dlight_shadows 1;r_shadow_realtime_world 1;r_shadow_realtime_world_lightmaps 0;r_shadow_realtime_world_shadows 1;r_bloom 1");
            break;
        case 26:
            M_Menu_ModList_f(cmd);
            break;
        default:
            M_Menu_Options_AdjustSliders (1);
            break;
        }
        return;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_cursor--;
        if (options_cursor < 0)
            options_cursor = OPTIONS_ITEMS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        options_cursor++;
        if (options_cursor >= OPTIONS_ITEMS)
            options_cursor = 0;
        break;
    case K_LEFTARROW:
        M_Menu_Options_AdjustSliders (-1);
        break;
    case K_RIGHTARROW:
        M_Menu_Options_AdjustSliders (1);
        break;
    }
}
Referenced by M_KeyEvent().
M_Options_PrintCheckbox()
static void M_Options_PrintCheckbox (const char * s, int enabled, int yes) static
Definition at line 1639 of file menu.c.
{
    if (m_opty >= 32)
    {
        if (m_optnum == m_optcursor)
            DrawQ_Fill(menu_x + 48, menu_y + m_opty, 320, 8, m_optnum == m_optcursor ? (0.5 + 0.2 * sin(host.realtime * M_PI)) : 0, 0, 0, 0.5, 0);
        M_ItemPrint(0 + 48, m_opty, s, enabled);
        M_DrawCheckbox(0 + 48 + (int)strlen(s) * 8 + 8, m_opty, yes);
    }
    m_opty += 8;
    m_optnum++;
}
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), and M_Options_Graphics_Draw().
M_Options_PrintCommand()
static void M_Options_PrintCommand (const char * s, int enabled) static
Definition at line 1627 of file menu.c.
{
    if (m_opty >= 32)
    {
        if (m_optnum == m_optcursor)
            DrawQ_Fill(menu_x + 48, menu_y + m_opty, 320, 8, m_optnum == m_optcursor ? (0.5 + 0.2 * sin(host.realtime * M_PI)) : 0, 0, 0, 0.5, 0);
        M_ItemPrint(0 + 48, m_opty, s, enabled);
    }
    m_opty += 8;
    m_optnum++;
}
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), and M_Options_Graphics_Draw().
M_Options_PrintSlider()
static void M_Options_PrintSlider (const char * s, int enabled, float value, float minvalue, float maxvalue) static
Definition at line 1652 of file menu.c.
{
    if (m_opty >= 32)
    {
        if (m_optnum == m_optcursor)
            DrawQ_Fill(menu_x + 48, menu_y + m_opty, 320, 8, m_optnum == m_optcursor ? (0.5 + 0.2 * sin(host.realtime * M_PI)) : 0, 0, 0, 0.5, 0);
        M_ItemPrint(0 + 48, m_opty, s, enabled);
        M_DrawSlider(0 + 48 + (int)strlen(s) * 8 + 8, m_opty, value, minvalue, maxvalue);
    }
    m_opty += 8;
    m_optnum++;
}
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), and M_Options_Graphics_Draw().
M_Print()
static void M_Print (float cx, float cy, const char * str) static
Definition at line 191 of file menu.c.
{
    DrawQ_String(menu_x + cx, menu_y + cy, str, 0, 8, 8, 1, 1, 1, 1, 0, NULL, true, FONT_MENU);
}
Referenced by M_Credits_Draw(), M_Demo_Draw(), M_DrawCheckbox(), M_DrawSlider(), M_GameOptions_Draw(), M_Keys_Draw(), M_LanConfig_Draw(), M_Load_Draw(), M_Main_Draw(), M_ModList_Draw(), M_Quit_Draw(), M_Reset_Draw(), M_Save_Draw(), M_ServerList_Draw(), M_Setup_Draw(), M_SinglePlayer_Draw(), and M_Video_Draw().
M_PrintColored()
static void M_PrintColored (float cx, float cy, const char * str) static
Definition at line 186 of file menu.c.
{
    DrawQ_String(menu_x + cx, menu_y + cy, str, 0, 8, 8, 1, 1, 1, 1, 0, NULL, false, FONT_MENU);
}
Referenced by M_ServerList_Draw(), and M_Setup_Draw().
M_PrintRed()
static void M_PrintRed (float cx, float cy, const char * str) static
Definition at line 196 of file menu.c.
{
    DrawQ_String(menu_x + cx, menu_y + cy, str, 0, 8, 8, 1, 0, 0, 1, 0, NULL, true, FONT_MENU);
}
Referenced by M_Keys_Draw(), M_Main_Draw(), M_ModList_Draw(), and M_ServerList_Draw().
M_Quit_Draw()
static void M_Quit_Draw (void) static
Definition at line 3290 of file menu.c.
{
    int i, l, linelength, firstline, lastline, lines;
    for (i = 0, linelength = 0, firstline = 9999, lastline = -1;m_quit_message[i];i++)
    {
        if ((l = (int)strlen(m_quit_message[i])))
        {
            if (firstline > i)
                firstline = i;
            if (lastline < i)
                lastline = i;
            if (linelength < l)
                linelength = l;
        }
    }
    lines = (lastline - firstline) + 1;
    M_Background(linelength * 8 + 16, lines * 8 + 16);
    if (!m_missingdata) //since this is a fallback menu for missing data, it is very hard to read with the box
        M_DrawTextBox(0, 0, linelength, lines); //this is less obtrusive than hacking up the M_DrawTextBox function
    for (i = 0, l = firstline;i < lines;i++, l++)
        M_Print(8 + 4 * (linelength - strlen(m_quit_message[l])), 8 + 8 * i, m_quit_message[l]);
}
Referenced by M_Draw().
M_Quit_Key()
static void M_Quit_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 3261 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
    case 'n':
    case 'N':
        if (wasInMenus)
        {
            m_state = (enum m_state_e)m_quit_prevstate;
            m_entersound = true;
        }
        else
        {
            key_dest = key_game;
            m_state = m_none;
        }
        break;
    case 'Y':
    case 'y':
        host.state = host_shutdown;
        break;
    default:
        break;
    }
}
Referenced by M_KeyEvent().
M_QuitMessage()
static int M_QuitMessage (const char * line1, const char * line2, const char * line3, const char * line4, const char * line5, const char * line6, const char * line7, const char * line8) static
Definition at line 3166 of file menu.c.
{
    m_quit_message[0] = line1;
    m_quit_message[1] = line2;
    m_quit_message[2] = line3;
    m_quit_message[3] = line4;
    m_quit_message[4] = line5;
    m_quit_message[5] = line6;
    m_quit_message[6] = line7;
    m_quit_message[7] = line8;
    m_quit_message[8] = NULL;
    return 1;
}
Referenced by M_ChooseQuitMessage().
M_Reset_Draw()
static void M_Reset_Draw (void) static
Definition at line 2758 of file menu.c.
{
    int lines = 2, linelength = 20;
    M_Background(linelength * 8 + 16, lines * 8 + 16);
    M_DrawTextBox(0, 0, linelength, lines);
    M_Print(8 + 4 * (linelength - 19),  8, "Really wanna reset?");
    M_Print(8 + 4 * (linelength - 11), 16, "Press y / n");
}
Referenced by M_Draw().
M_Reset_Key()
static void M_Reset_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 2737 of file menu.c.
{
    switch (key)
    {
    case 'Y':
    case 'y':
        Cbuf_AddText(cmd, "cvar_resettodefaults_all;exec default.cfg\n");
        // no break here since we also exit the menu
    case K_ESCAPE:
    case 'n':
    case 'N':
        m_state = m_options;
        m_entersound = true;
        break;
    default:
        break;
    }
}
Referenced by M_KeyEvent().
M_Save_Draw()
static void M_Save_Draw (void) static
Definition at line 928 of file menu.c.
{
    int     i;
    cachepic_t  *p;
    M_Background(320, 200);
    p = Draw_CachePic ("gfx/p_save");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/p_save");
    for (i=0 ; i<MAX_SAVEGAMES ; i++)
        M_Print(16, 32 + 8*i, m_filenames[i]);
// line cursor
    M_DrawCharacter (8, 32 + load_cursor*8, 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Save_Key()
static void M_Save_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 988 of file menu.c.
{
    char vabuf[1024];
    switch (k)
    {
    case K_ESCAPE:
        if (gamemode == GAME_TRANSFUSION)
            M_Menu_Main_f(cmd);
        else
            M_Menu_SinglePlayer_f(cmd);
        break;
    case K_ENTER:
        m_state = m_none;
        key_dest = key_game;
        Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "save s%i\n", load_cursor));
        return;
    case K_UPARROW:
    case K_LEFTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        load_cursor--;
        if (load_cursor < 0)
            load_cursor = MAX_SAVEGAMES-1;
        break;
    case K_DOWNARROW:
    case K_RIGHTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        load_cursor++;
        if (load_cursor >= MAX_SAVEGAMES)
            load_cursor = 0;
        break;
    }
}
Referenced by M_KeyEvent().
M_ScanSaves()
static void M_ScanSaves (void) static
Definition at line 841 of file menu.c.
{
    int     i, j;
    size_t  len;
    char    name[MAX_OSPATH];
    char    buf[SAVEGAME_COMMENT_LENGTH + 256];
    const char *t;
    qfile_t *f;
//  int     version;
    for (i=0 ; i<MAX_SAVEGAMES ; i++)
    {
        dp_strlcpy (m_filenames[i], "--- UNUSED SLOT ---", sizeof(m_filenames[i]));
        loadable[i] = false;
        dpsnprintf (name, sizeof(name), "s%i.sav", (int)i);
        f = FS_OpenRealFile (name, "rb", false);
        if (!f)
            continue;
        // read enough to get the comment
        len = FS_Read(f, buf, sizeof(buf) - 1);
        len = min(len, sizeof(buf)-1);
        buf[len] = 0;
        t = buf;
        // version
        COM_ParseToken_Simple(&t, false, false, true);
        //version = atoi(com_token);
        // description
        COM_ParseToken_Simple(&t, false, false, true);
        dp_strlcpy (m_filenames[i], com_token, sizeof (m_filenames[i]));
    // change _ back to space
        for (j=0 ; j<SAVEGAME_COMMENT_LENGTH ; j++)
            if (m_filenames[i][j] == '_')
                m_filenames[i][j] = ' ';
        loadable[i] = true;
        FS_Close (f);
    }
}
Referenced by M_Menu_Load_f(), and M_Menu_Save_f().
M_ServerList_Draw()
static void M_ServerList_Draw (void) static
Definition at line 4397 of file menu.c.
{
    unsigned n, y, start, end, statnumplayers, statmaxplayers;
    cachepic_t *p;
    const char *s;
    char vabuf[1024];
    // use as much vertical space as available
    if (gamemode == GAME_TRANSFUSION)
        M_Background(640, vid_conheight.integer - 80);
    else
        M_Background(640, vid_conheight.integer);
    // scroll the list as the cursor moves
    ServerList_GetPlayerStatistics(&statnumplayers, &statmaxplayers);
    s = va(vabuf, sizeof(vabuf), "%u/%u masters %u/%u servers %u/%u players", masterreplycount, masterquerycount, serverreplycount, serverquerycount, statnumplayers, statmaxplayers);
    M_PrintRed((640 - strlen(s) * 8) / 2, 32, s);
    if (*cl_connect_status)
        M_Print(16, menu_height - 8, cl_connect_status);
    y = 48;
    slist_visible = (menu_height - 16 - y) / 8 / 2;
    start = min(slist_cursor - min(slist_cursor, slist_visible >> 1), serverlist_viewcount - min(serverlist_viewcount, slist_visible));
    end = min(start + slist_visible, serverlist_viewcount);
    p = Draw_CachePic ("gfx/p_multi");
    M_DrawPic((640 - Draw_GetPicWidth(p)) / 2, 4, "gfx/p_multi");
    if (end > start)
    {
        for (n = start;n < end;n++)
        {
            serverlist_entry_t *entry = ServerList_GetViewEntry(n);
            DrawQ_Fill(menu_x, menu_y + y, 640, 16, n == slist_cursor ? (0.5 + 0.2 * sin(host.realtime * M_PI)) : 0, 0, 0, 0.5, 0);
            M_PrintColored(0, y, entry->line1);y += 8;
            M_PrintColored(0, y, entry->line2);y += 8;
        }
    }
    else if (host.realtime - masterquerytime > 10)
    {
        if (masterquerycount)
            M_Print(0, y, "No servers found");
        else
            M_Print(0, y, "No master servers found (network problem?)");
    }
    else
    {
        if (serverquerycount)
            M_Print(0, y, "Querying servers");
        else
            M_Print(0, y, "Querying master servers");
    }
}
Referenced by M_Draw().
M_ServerList_Key()
static void M_ServerList_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 4449 of file menu.c.
{
    char vabuf[1024];
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_LanConfig_f(cmd);
        break;
    case K_SPACE:
        if (lanConfig_cursor == 2)
            Net_SlistQW_f(cmd);
        else
            Net_Slist_f(cmd);
        break;
    case K_PGUP:
        slist_cursor -= slist_visible - 2;
    case K_UPARROW:
    case K_LEFTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        slist_cursor--;
        if (slist_cursor >= serverlist_viewcount)
            slist_cursor = serverlist_viewcount - 1;
        break;
    case K_PGDN:
        slist_cursor += slist_visible - 2;
    case K_DOWNARROW:
    case K_RIGHTARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        slist_cursor++;
        if (slist_cursor >= serverlist_viewcount)
            slist_cursor = 0;
        break;
    case K_HOME:
        S_LocalSound ("sound/misc/menu1.wav");
        slist_cursor = 0;
        break;
    case K_END:
        S_LocalSound ("sound/misc/menu1.wav");
        slist_cursor = serverlist_viewcount - 1;
        break;
    case K_ENTER:
        S_LocalSound ("sound/misc/menu2.wav");
        if (serverlist_viewcount)
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "connect \"%s\"\n", ServerList_GetViewEntry(slist_cursor)->info.cname));
        break;
    default:
        break;
    }
}
Referenced by M_KeyEvent().
M_Setup_Draw()
static void M_Setup_Draw (void) static
Definition at line 1330 of file menu.c.
{
    int i, j;
    cachepic_t  *p;
    char vabuf[1024];
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/p_multi");
    M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/p_multi");
    M_Print(64, 40, "Your name");
    M_DrawTextBox (160, 32, 16, 1);
    M_PrintColored(168, 40, setup_myname);
    if (gamemode != GAME_GOODVSBAD2)
    {
        M_Print(64, 64, "Shirt color");
        M_Print(64, 88, "Pants color");
    }
    M_Print(64, 124-8, "Network speed limit");
    M_Print(168, 124, va(vabuf, sizeof(vabuf), "%i (%s)", setup_rate, setup_ratetable[setup_rateindex(setup_rate)].name));
    M_DrawTextBox (64, 140-8, 14, 1);
    M_Print(72, 140, "Accept Changes");
    // LadyHavoc: rewrote this code greatly
    if (menuplyr_load)
    {
        unsigned char *f;
        fs_offset_t filesize;
        menuplyr_load = false;
        menuplyr_top = -1;
        menuplyr_bottom = -1;
        f = FS_LoadFile("gfx/menuplyr.lmp", tempmempool, true, &filesize);
        if (f && filesize >= 9)
        {
            int width, height;
            width = f[0] + f[1] * 256 + f[2] * 65536 + f[3] * 16777216;
            height = f[4] + f[5] * 256 + f[6] * 65536 + f[7] * 16777216;
            if (filesize >= 8 + width * height)
            {
                menuplyr_width = width;
                menuplyr_height = height;
                menuplyr_pixels = (unsigned char *)Mem_Alloc(cls.permanentmempool, width * height);
                menuplyr_translated = (unsigned int *)Mem_Alloc(cls.permanentmempool, width * height * 4);
                memcpy(menuplyr_pixels, f + 8, width * height);
            }
        }
        if (f)
            Mem_Free(f);
    }
    if (menuplyr_pixels)
    {
        if (menuplyr_top != setup_top || menuplyr_bottom != setup_bottom)
        {
            menuplyr_top = setup_top;
            menuplyr_bottom = setup_bottom;
            for (i = 0;i < menuplyr_width * menuplyr_height;i++)
            {
                j = menuplyr_pixels[i];
                if (j >= TOP_RANGE && j < TOP_RANGE + 16)
                {
                    if (menuplyr_top < 8 || menuplyr_top == 14)
                        j = menuplyr_top * 16 + (j - TOP_RANGE);
                    else
                        j = menuplyr_top * 16 + 15-(j - TOP_RANGE);
                }
                else if (j >= BOTTOM_RANGE && j < BOTTOM_RANGE + 16)
                {
                    if (menuplyr_bottom < 8 || menuplyr_bottom == 14)
                        j = menuplyr_bottom * 16 + (j - BOTTOM_RANGE);
                    else
                        j = menuplyr_bottom * 16 + 15-(j - BOTTOM_RANGE);
                }
                menuplyr_translated[i] = palette_bgra_transparent[j];
            }
            Draw_NewPic("gfx/menuplyr", menuplyr_width, menuplyr_height, (unsigned char *)menuplyr_translated, TEXTYPE_BGRA, TEXF_CLAMP);
        }
        M_DrawPic(160, 48, "gfx/bigbox");
        M_DrawPic(172, 56, "gfx/menuplyr");
    }
    if (setup_cursor == 0)
        M_DrawCharacter (168 + 8*strlen(setup_myname), setup_cursor_table [setup_cursor], 10+((int)(host.realtime*4)&1));
    else
        M_DrawCharacter (56, setup_cursor_table [setup_cursor], 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Setup_Key()
static void M_Setup_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1424 of file menu.c.
{
    int         l;
    char vabuf[1024];
    switch (k)
    {
    case K_ESCAPE:
        M_Menu_MultiPlayer_f(cmd);
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        setup_cursor--;
        if (setup_cursor < 0)
            setup_cursor = NUM_SETUP_CMDS-1;
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        setup_cursor++;
        if (setup_cursor >= NUM_SETUP_CMDS)
            setup_cursor = 0;
        break;
    case K_LEFTARROW:
        if (setup_cursor < 1)
            return;
        S_LocalSound ("sound/misc/menu3.wav");
        if (setup_cursor == 1)
            setup_top = setup_top - 1;
        if (setup_cursor == 2)
            setup_bottom = setup_bottom - 1;
        if (setup_cursor == 3)
        {
            l = setup_rateindex(setup_rate) - 1;
            if (l < 0)
                l = RATES - 1;
            setup_rate = setup_ratetable[l].rate;
        }
        break;
    case K_RIGHTARROW:
        if (setup_cursor < 1)
            return;
forward:
        S_LocalSound ("sound/misc/menu3.wav");
        if (setup_cursor == 1)
            setup_top = setup_top + 1;
        if (setup_cursor == 2)
            setup_bottom = setup_bottom + 1;
        if (setup_cursor == 3)
        {
            l = setup_rateindex(setup_rate) + 1;
            if (l >= RATES)
                l = 0;
            setup_rate = setup_ratetable[l].rate;
        }
        break;
    case K_ENTER:
        if (setup_cursor == 0)
            return;
        if (setup_cursor == 1 || setup_cursor == 2 || setup_cursor == 3)
            goto forward;
        // setup_cursor == 4 (Accept changes)
        if (strcmp(cl_name.string, setup_myname) != 0)
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "name \"%s\"\n", setup_myname) );
        if (setup_top != setup_oldtop || setup_bottom != setup_oldbottom)
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "color %i %i\n", setup_top, setup_bottom) );
        if (setup_rate != setup_oldrate)
            Cbuf_AddText(cmd, va(vabuf, sizeof(vabuf), "rate %i\n", setup_rate));
        m_entersound = true;
        M_Menu_MultiPlayer_f(cmd);
        break;
    case K_BACKSPACE:
        if (setup_cursor == 0)
        {
            if (strlen(setup_myname))
                setup_myname[strlen(setup_myname)-1] = 0;
        }
        break;
    default:
        if (ascii < 32)
            break;
        if (setup_cursor == 0)
        {
            l = (int)strlen(setup_myname);
            if (l < 15)
            {
                setup_myname[l+1] = 0;
                setup_myname[l] = ascii;
            }
        }
    }
    if (setup_top > 15)
        setup_top = 0;
    if (setup_top < 0)
        setup_top = 15;
    if (setup_bottom > 15)
        setup_bottom = 0;
    if (setup_bottom < 0)
        setup_bottom = 15;
}
Referenced by M_KeyEvent().
M_Shutdown()
void M_Shutdown (void) static
Definition at line 5032 of file menu.c.
{
    // reset key_dest
    key_dest = key_game;
}
Referenced by MR_SetRouting().
M_SinglePlayer_Draw()
static void M_SinglePlayer_Draw (void) static
Definition at line 738 of file menu.c.
{
    cachepic_t  *p;
    char vabuf[1024];
    M_Background(320, 200);
    M_DrawPic (16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/ttl_sgl");
    // Some mods don't have a single player mode
    if (gamemode == GAME_GOODVSBAD2 || gamemode == GAME_BATTLEMECH)
    {
        M_DrawPic ((320 - Draw_GetPicWidth(p)) / 2, 4, "gfx/ttl_sgl");
        M_DrawTextBox (60, 8 * 8, 23, 4);
        if (gamemode == GAME_GOODVSBAD2)
            M_Print(95, 10 * 8, "Good Vs Bad 2 is for");
        else  // if (gamemode == GAME_BATTLEMECH)
            M_Print(95, 10 * 8, "Battlemech is for");
        M_Print(83, 11 * 8, "multiplayer play only");
    }
    else
    {
        int     f;
        M_DrawPic ( (320-Draw_GetPicWidth(p))/2, 4, "gfx/ttl_sgl");
        M_DrawPic (72, 32, "gfx/sp_menu");
        f = (int)(host.realtime * 10)%6;
        M_DrawPic (54, 32 + m_singleplayer_cursor * 20, va(vabuf, sizeof(vabuf), "gfx/menudot%i", f+1));
    }
}
Referenced by M_Draw().
M_SinglePlayer_Key()
static void M_SinglePlayer_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 774 of file menu.c.
{
    if (gamemode == GAME_GOODVSBAD2 || gamemode == GAME_BATTLEMECH)
    {
        if (key == K_ESCAPE || key == K_ENTER)
            m_state = m_main;
        return;
    }
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Main_f(cmd);
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (++m_singleplayer_cursor >= SINGLEPLAYER_ITEMS)
            m_singleplayer_cursor = 0;
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        if (--m_singleplayer_cursor < 0)
            m_singleplayer_cursor = SINGLEPLAYER_ITEMS - 1;
        break;
    case K_ENTER:
        m_entersound = true;
        switch (m_singleplayer_cursor)
        {
        case 0:
            key_dest = key_game;
            if (sv.active)
                Cbuf_AddText(cmd, "disconnect\n");
            Cbuf_AddText(cmd, "maxplayers 1\n");
            Cbuf_AddText(cmd, "deathmatch 0\n");
            Cbuf_AddText(cmd, "coop 0\n");
            if (gamemode == GAME_TRANSFUSION)
            {
                key_dest = key_menu;
                M_Menu_Transfusion_Episode_f(cmd);
                break;
            }
            Cbuf_AddText(cmd, "startmap_sp\n");
            break;
        case 1:
            M_Menu_Load_f(cmd);
            break;
        case 2:
            M_Menu_Save_f(cmd);
            break;
        }
    }
}
Referenced by M_KeyEvent().
M_ToggleMenu()
void M_ToggleMenu (int mode) static
Definition at line 269 of file menu.c.
{
    m_entersound = true;
    if ((key_dest != key_menu && key_dest != key_menu_grabbed) || m_state != m_main)
    {
        if(mode == 0)
            return; // the menu is off, and we want it off
        M_Menu_Main_f (cmd_local);
    }
    else
    {
        if(mode == 1)
            return; // the menu is on, and we want it on
        key_dest = key_game;
        m_state = m_none;
    }
}
Referenced by MR_SetRouting().
M_Transfusion_Episode_Draw()
static void M_Transfusion_Episode_Draw (void) static
Definition at line 1037 of file menu.c.
{
    int y;
    cachepic_t *p;
    char vabuf[1024];
    M_Background(640, 480);
    p = Draw_CachePic ("gfx/menu/tb-episodes");
    M_DrawPic (640/2 - Draw_GetPicWidth(p)/2, 40, "gfx/menu/tb-episodes");
    for (y = 0; y < EPISODE_ITEMS; y++){
        M_DrawPic (0, 160 + y * 40, va(vabuf, sizeof(vabuf), "gfx/menu/episode%i", y+1));
    }
    M_DrawPic (0, 120 + (m_episode_cursor + 1) * 40, va(vabuf, sizeof(vabuf), "gfx/menu/episode%iselected", m_episode_cursor + 1));
}
Referenced by M_Draw().
M_Transfusion_Episode_Key()
static void M_Transfusion_Episode_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1053 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Main_f(cmd);
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        m_episode_cursor++;
        if (m_episode_cursor >= EPISODE_ITEMS)
            m_episode_cursor = 0;
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        m_episode_cursor--;
        if (m_episode_cursor < 0)
            m_episode_cursor = EPISODE_ITEMS - 1;
        break;
    case K_ENTER:
        Cbuf_AddText(cmd, "deathmatch 0\n");
        m_entersound = true;
        M_Menu_Transfusion_Skill_f(cmd);
    }
}
Referenced by M_KeyEvent().
M_Transfusion_Skill_Draw()
static void M_Transfusion_Skill_Draw (void) static
Definition at line 1095 of file menu.c.
{
    int y;
    cachepic_t  *p;
    char vabuf[1024];
    M_Background(640, 480);
    p = Draw_CachePic ("gfx/menu/tb-difficulty");
    M_DrawPic(640/2 - Draw_GetPicWidth(p)/2, 40, "gfx/menu/tb-difficulty");
    for (y = 0; y < SKILL_ITEMS; y++)
    {
        M_DrawPic (0, 180 + y * 40, va(vabuf, sizeof(vabuf), "gfx/menu/difficulty%i", y+1));
    }
    M_DrawPic (0, 140 + (m_skill_cursor + 1) *40, va(vabuf, sizeof(vabuf), "gfx/menu/difficulty%iselected", m_skill_cursor + 1));
}
Referenced by M_Draw().
M_Transfusion_Skill_Key()
static void M_Transfusion_Skill_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 1112 of file menu.c.
{
    switch (key)
    {
    case K_ESCAPE:
        M_Menu_Transfusion_Episode_f(cmd);
        break;
    case K_DOWNARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        m_skill_cursor++;
        if (m_skill_cursor >= SKILL_ITEMS)
            m_skill_cursor = 0;
        break;
    case K_UPARROW:
        S_LocalSound ("sound/misc/menu1.wav");
        m_skill_cursor--;
        if (m_skill_cursor < 0)
            m_skill_cursor = SKILL_ITEMS - 1;
        break;
    case K_ENTER:
        m_entersound = true;
        switch (m_skill_cursor)
        {
        case 0:
            Cbuf_AddText(cmd, "skill 1\n");
            break;
        case 1:
            Cbuf_AddText(cmd, "skill 2\n");
            break;
        case 2:
            Cbuf_AddText(cmd, "skill 3\n");
            break;
        case 3:
            Cbuf_AddText(cmd, "skill 4\n");
            break;
        case 4:
            Cbuf_AddText(cmd, "skill 5\n");
            break;
        }
        key_dest = key_game;
        if (sv.active)
            Cbuf_AddText(cmd, "disconnect\n");
        Cbuf_AddText(cmd, "maxplayers 1\n");
        Cbuf_AddText(cmd, "deathmatch 0\n");
        Cbuf_AddText(cmd, "coop 0\n");
        switch (m_episode_cursor)
        {
        case 0:
            Cbuf_AddText(cmd, "map e1m1\n");
            break;
        case 1:
            Cbuf_AddText(cmd, "map e2m1\n");
            break;
        case 2:
            Cbuf_AddText(cmd, "map e3m1\n");
            break;
        case 3:
            Cbuf_AddText(cmd, "map e4m1\n");
            break;
        case 4:
            Cbuf_AddText(cmd, "map e6m1\n");
            break;
        case 5:
            Cbuf_AddText(cmd, "map cp01\n");
            break;
        }
    }
}
Referenced by M_KeyEvent().
M_UnbindCommand()
static void M_UnbindCommand (const char * command) static
Definition at line 2582 of file menu.c.
{
    int     j;
    const char  *b;
    for (j = 0; j < (int)sizeof (keybindings[0]) / (int)sizeof (keybindings[0][0]); j++)
    {
        b = keybindings[0][j];
        if (!b)
            continue;
        if (!strcmp (b, command))
            Key_SetBinding (j, 0, "");
    }
}
Referenced by M_Keys_Key().
M_Video_Draw()
static void M_Video_Draw (void) static
Definition at line 2903 of file menu.c.
{
    int t;
    cachepic_t  *p;
    char vabuf[1024];
    if(!!vid_fullscreen.integer != menu_video_resolutions_forfullscreen)
    {
        video_resolution_t *res = &menu_video_resolutions[menu_video_resolution];
        menu_video_resolutions_forfullscreen = !!vid_fullscreen.integer;
        M_Menu_Video_FindResolution(res->width, res->height, res->pixelheight);
    }
    M_Background(320, 200);
    M_DrawPic(16, 4, "gfx/qplaque");
    p = Draw_CachePic ("gfx/vidmodes");
    M_DrawPic((320-Draw_GetPicWidth(p))/2, 4, "gfx/vidmodes");
    t = 0;
    // Current and Proposed Resolution
    M_Print(16, video_cursor_table[t] - 12, "    Current Resolution");
    if (vid_supportrefreshrate && vid.userefreshrate && vid.fullscreen)
        M_Print(220, video_cursor_table[t] - 12, va(vabuf, sizeof(vabuf), "%dx%d %.2fhz", vid.width, vid.height, vid.refreshrate));
    else
        M_Print(220, video_cursor_table[t] - 12, va(vabuf, sizeof(vabuf), "%dx%d", vid.width, vid.height));
    M_Print(16, video_cursor_table[t], "        New Resolution");
    M_Print(220, video_cursor_table[t], va(vabuf, sizeof(vabuf), "%dx%d", menu_video_resolutions[menu_video_resolution].width, menu_video_resolutions[menu_video_resolution].height));
    M_Print(96, video_cursor_table[t] + 8, va(vabuf, sizeof(vabuf), "Type: %s", menu_video_resolutions[menu_video_resolution].type));
    t++;
    // Antialiasing
    M_Print(16, video_cursor_table[t], "          Antialiasing");
    M_DrawSlider(220, video_cursor_table[t], vid_samples.value, 1, 32);
    t++;
    // Refresh Rate
    M_ItemPrint(16, video_cursor_table[t], "      Use Refresh Rate", vid_supportrefreshrate);
    M_DrawCheckbox(220, video_cursor_table[t], vid_userefreshrate.integer);
    t++;
    // Refresh Rate
    M_ItemPrint(16, video_cursor_table[t], "          Refresh Rate", vid_supportrefreshrate && vid_userefreshrate.integer);
    M_DrawSlider(220, video_cursor_table[t], vid_refreshrate.value, 50, 150);
    t++;
    // Fullscreen
    M_Print(16, video_cursor_table[t], "            Fullscreen");
    M_DrawCheckbox(220, video_cursor_table[t], vid_fullscreen.integer);
    t++;
    // Vertical Sync
    M_ItemPrint(16, video_cursor_table[t], "         Vertical Sync", true);
    M_DrawCheckbox(220, video_cursor_table[t], vid_vsync.integer);
    t++;
    M_ItemPrint(16, video_cursor_table[t], "    Anisotropic Filter", vid.support.ext_texture_filter_anisotropic);
    M_DrawSlider(220, video_cursor_table[t], gl_texture_anisotropy.integer, 1, vid.max_anisotropy);
    t++;
    M_ItemPrint(16, video_cursor_table[t], "       Texture Quality", true);
    M_DrawSlider(220, video_cursor_table[t], gl_picmip.value, 3, 0);
    t++;
    M_ItemPrint(16, video_cursor_table[t], "   Texture Compression", true);
    M_DrawCheckbox(220, video_cursor_table[t], gl_texturecompression.integer);
    t++;
    // "Apply" button
    M_Print(220, video_cursor_table[t], "Apply");
    t++;
    // Cursor
    M_DrawCharacter(200, video_cursor_table[video_cursor], 12+((int)(host.realtime*4)&1));
}
Referenced by M_Draw().
M_Video_Key()
static void M_Video_Key (cmd_state_t * cmd, int key, int ascii) static
Definition at line 3022 of file menu.c.
{
    switch (key)
    {
        case K_ESCAPE:
            // vid_shared.c has a copy of the current video config. We restore it
            Cvar_SetValueQuick(&vid_fullscreen, vid.fullscreen);
            Cvar_SetValueQuick(&vid_bitsperpixel, vid.bitsperpixel);
            Cvar_SetValueQuick(&vid_samples, vid.samples);
            if (vid_supportrefreshrate)
                Cvar_SetValueQuick(&vid_refreshrate, vid.refreshrate);
            Cvar_SetValueQuick(&vid_userefreshrate, vid.userefreshrate);
            S_LocalSound ("sound/misc/menu1.wav");
            M_Menu_Options_f(cmd);
            break;
        case K_ENTER:
            m_entersound = true;
            switch (video_cursor)
            {
                case (VIDEO_ITEMS - 1):
                    Cvar_SetValueQuick (&vid_width, menu_video_resolutions[menu_video_resolution].width);
                    Cvar_SetValueQuick (&vid_height, menu_video_resolutions[menu_video_resolution].height);
                    Cvar_SetValueQuick (&vid_conwidth, menu_video_resolutions[menu_video_resolution].conwidth);
                    Cvar_SetValueQuick (&vid_conheight, menu_video_resolutions[menu_video_resolution].conheight);
                    Cvar_SetValueQuick (&vid_pixelheight, menu_video_resolutions[menu_video_resolution].pixelheight);
                    Cbuf_AddText(cmd, "vid_restart\n");
                    M_Menu_Options_f(cmd);
                    break;
                default:
                    M_Menu_Video_AdjustSliders (1);
            }
            break;
        case K_UPARROW:
            S_LocalSound ("sound/misc/menu1.wav");
            video_cursor--;
            if (video_cursor < 0)
                video_cursor = VIDEO_ITEMS-1;
            break;
        case K_DOWNARROW:
            S_LocalSound ("sound/misc/menu1.wav");
            video_cursor++;
            if (video_cursor >= VIDEO_ITEMS)
                video_cursor = 0;
            break;
        case K_LEFTARROW:
            M_Menu_Video_AdjustSliders (-1);
            break;
        case K_RIGHTARROW:
            M_Menu_Video_AdjustSliders (1);
            break;
    }
}
Referenced by M_KeyEvent().
ModList_Enable()
static void ModList_Enable (void) static
Definition at line 4574 of file menu.c.
{
    int i;
    int numgamedirs;
    char gamedirs[MODLIST_MAXDIRS][MAX_QPATH];
    // copy our mod list into an array for FS_ChangeGameDirs
    numgamedirs = modlist_numenabled;
    for (i = 0; i < modlist_numenabled; i++)
        dp_strlcpy (gamedirs[i], modlist[modlist_enabled[i]].dir,sizeof (gamedirs[i]));
    // this code snippet is from FS_ChangeGameDirs
    if (fs_numgamedirs == numgamedirs)
    {
        for (i = 0;i < numgamedirs;i++)
            if (strcasecmp(fs_gamedirs[i], gamedirs[i]))
                break;
        if (i == numgamedirs)
            return; // already using this set of gamedirs, do nothing
    }
    // this part is basically the same as the FS_GameDir_f function
    if ((cls.state == ca_connected && !cls.demoplayback) || sv.active)
    {
        // actually, changing during game would work fine, but would be stupid
        Con_Printf("Can not change gamedir while client is connected or server is running!\n");
        return;
    }
    FS_ChangeGameDirs (modlist_numenabled, gamedirs, true, true);
}
Referenced by M_ModList_Key().
ModList_RebuildList()
static void ModList_RebuildList (void) static
Definition at line 4531 of file menu.c.
{
    int i,j;
    stringlist_t list;
    const char *description;
    stringlistinit(&list);
    listdirectory(&list, fs_basedir, "");
    stringlistsort(&list, true);
    modlist_count = 0;
    modlist_numenabled = fs_numgamedirs;
    for (i = 0;i < list.numstrings && modlist_count < MODLIST_TOTALSIZE;i++)
    {
        // quickly skip names with dot characters - generally these are files, not directories
        if (strchr(list.strings[i], '.')) continue;
        // reject any dirs that are part of the base game
        if (gamedirname1 && !strcasecmp(gamedirname1, list.strings[i])) continue;
        //if (gamedirname2 && !strcasecmp(gamedirname2, list.strings[i])) continue;
        // check if we can get a description of the gamedir (from modinfo.txt),
        // or if the directory is valid but has no description (fs_checkgamedir_missing)
        // otherwise this isn't a valid gamedir
        description = FS_CheckGameDir(list.strings[i]);
        if (description == NULL || description == fs_checkgamedir_missing) continue;
        dp_strlcpy (modlist[modlist_count].dir, list.strings[i], sizeof(modlist[modlist_count].dir));
        //check currently loaded mods
        modlist[modlist_count].loaded = false;
        if (fs_numgamedirs)
            for (j = 0; j < fs_numgamedirs; j++)
                if (!strcasecmp(fs_gamedirs[j], modlist[modlist_count].dir))
                {
                    modlist[modlist_count].loaded = true;
                    modlist[modlist_count].enabled = j;
                    modlist_enabled[j] = modlist_count;
                    break;
                }
        modlist_count ++;
    }
    stringlistfreecontents(&list);
}
Referenced by M_Menu_ModList_f(), and M_ModList_Key().
MP_Draw()
static void MP_Draw (void) static
Definition at line 5310 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    float oldquality;
    // don't crash if we draw a frame between prog shutdown and restart, see Host_LoadConfig_f
    if (!prog->loaded)
        return;
    R_SelectScene( RST_MENU );
    // reset the temp entities each frame
    r_refdef.scene.numtempentities = 0;
    // menu scenes do not use reduced rendering quality
    oldquality = r_refdef.view.quality;
    r_refdef.view.quality = 1;
    // TODO: this needs to be exposed to R_SetView (or something similar) ASAP [2/5/2008 Andreas]
    r_refdef.scene.time = host.realtime;
    // free memory for resources that are no longer referenced
    PRVM_GarbageCollection(prog);
    // FIXME: this really shouldnt error out lest we have a very broken refdef state...?
    // or does it kill the server too?
    PRVM_G_FLOAT(OFS_PARM0) = vid.width;
    PRVM_G_FLOAT(OFS_PARM1) = vid.height;
    prog->ExecuteProgram(prog, PRVM_menufunction(m_draw),"m_draw() required");
    // TODO: imo this should be moved into scene, too [1/27/2008 Andreas]
    r_refdef.view.quality = oldquality;
    R_SelectScene( RST_CLIENT );
}
Referenced by MR_SetRouting().
MP_GetServerListEntryCategory()
static int MP_GetServerListEntryCategory (const serverlist_entry_t * entry) static
Definition at line 5361 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    serverlist_callbackentry = entry;
    if (PRVM_menufunction(m_gethostcachecategory))
    {
        prog->globals.fp[OFS_PARM0] = (prvm_vec_t) -1;
        prog->ExecuteProgram(prog, PRVM_menufunction(m_gethostcachecategory),"m_gethostcachecategory(float entry) required");
        serverlist_callbackentry = NULL;
        return prog->globals.fp[OFS_RETURN];
    }
    else
    {
        return 0;
    }
}
Referenced by MR_SetRouting().
MP_Init()
static void MP_Init (void) static
Definition at line 5391 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    PRVM_Prog_Init(prog, cmd_local);
    prog->edictprivate_size = 0; // no private struct used
    prog->name = "menu";
    prog->num_edicts = 1;
    prog->limit_edicts = M_MAX_EDICTS;
    prog->extensionstring = vm_m_extensions;
    prog->builtins = vm_m_builtins;
    prog->numbuiltins = vm_m_numbuiltins;
    // all callbacks must be defined (pointers are not checked before calling)
    prog->begin_increase_edicts = MVM_begin_increase_edicts;
    prog->end_increase_edicts   = MVM_end_increase_edicts;
    prog->init_edict            = MVM_init_edict;
    prog->free_edict            = MVM_free_edict;
    prog->count_edicts          = MVM_count_edicts;
    prog->load_edict            = MVM_load_edict;
    prog->init_cmd              = MVM_init_cmd;
    prog->reset_cmd             = MVM_reset_cmd;
    prog->error_cmd             = MVM_error_cmd;
    prog->ExecuteProgram        = MVM_ExecuteProgram;
    // allocate the mempools
    prog->progs_mempool = Mem_AllocPool(menu_progs.string, 0, NULL);
    PRVM_Prog_Load(prog, menu_progs.string, NULL, 0, m_numrequiredfunc, m_required_func, m_numrequiredfields, m_required_fields, m_numrequiredglobals, m_required_globals);
    // note: OP_STATE is not supported by menu qc, we don't even try to detect
    // it here
    in_client_mouse = true;
    // call the prog init
    prog->ExecuteProgram(prog, PRVM_menufunction(m_init),"m_init() required");
    // Once m_init was called, we consider menuqc code fully initialized.
    prog->inittime = host.realtime;
}
Referenced by MR_SetRouting().
MP_KeyEvent()
static void MP_KeyEvent (int key, int ascii, qbool downevent) static
Definition at line 5297 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    // pass key
    prog->globals.fp[OFS_PARM0] = (prvm_vec_t) key;
    prog->globals.fp[OFS_PARM1] = (prvm_vec_t) ascii;
    if (downevent)
        prog->ExecuteProgram(prog, PRVM_menufunction(m_keydown),"m_keydown(float key, float ascii) required");
    else if (PRVM_menufunction(m_keyup))
        prog->ExecuteProgram(prog, PRVM_menufunction(m_keyup),"m_keyup(float key, float ascii) required");
}
Referenced by MR_SetRouting().
MP_NewMap()
static void MP_NewMap (void) static
Definition at line 5353 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    if (PRVM_menufunction(m_newmap))
        prog->ExecuteProgram(prog, PRVM_menufunction(m_newmap),"m_newmap() required");
}
Referenced by MR_SetRouting().
MP_Shutdown()
static void MP_Shutdown (void) static
Definition at line 5378 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    if (prog->loaded)
        prog->ExecuteProgram(prog, PRVM_menufunction(m_shutdown),"m_shutdown() required");
    // reset key_dest
    key_dest = key_game;
    // AK not using this cause Im not sure whether this is useful at all instead :
    PRVM_Prog_Reset(prog);
}
Referenced by MR_SetRouting().
MP_ToggleMenu()
static void MP_ToggleMenu (int mode) static
Definition at line 5345 of file menu.c.
{
    prvm_prog_t *prog = MVM_prog;
    prog->globals.fp[OFS_PARM0] = (prvm_vec_t) mode;
    prog->ExecuteProgram(prog, PRVM_menufunction(m_toggle),"m_toggle(float mode) required");
}
Referenced by MR_SetRouting().
MR_Init()
void MR_Init (void)
Definition at line 5501 of file menu.c.
{
    vid_mode_t res[1024];
    size_t res_count, i;
    res_count = VID_ListModes(res, sizeof(res) / sizeof(*res));
    res_count = VID_SortModes(res, res_count, false, false, true);
    if(res_count)
    {
        video_resolutions_count = (int)res_count;
        video_resolutions = (video_resolution_t *) Mem_Alloc(cls.permanentmempool, sizeof(*video_resolutions) * (video_resolutions_count + 1));
        memset(&video_resolutions[video_resolutions_count], 0, sizeof(video_resolutions[video_resolutions_count]));
        for(i = 0; i < res_count; ++i)
        {
            int n, d, t;
            video_resolutions[i].type = "Detected mode"; // FIXME make this more dynamic
            video_resolutions[i].width = res[i].width;
            video_resolutions[i].height = res[i].height;
            video_resolutions[i].pixelheight = res[i].pixelheight_num / (double) res[i].pixelheight_denom;
            n = res[i].pixelheight_denom * video_resolutions[i].width;
            d = res[i].pixelheight_num * video_resolutions[i].height;
            while(d)
            {
                t = n;
                n = d;
                d = t % d;
            }
            d = (res[i].pixelheight_num * video_resolutions[i].height) / n;
            n = (res[i].pixelheight_denom * video_resolutions[i].width) / n;
            switch(n * 0x10000 | d)
            {
                case 0x00040003:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 480;
                    video_resolutions[i].type = "Standard 4x3";
                    break;
                case 0x00050004:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 512;
                    if(res[i].pixelheight_denom == res[i].pixelheight_num)
                        video_resolutions[i].type = "Square Pixel (LCD) 5x4";
                    else
                        video_resolutions[i].type = "Short Pixel (CRT) 5x4";
                    break;
                case 0x00080005:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 400;
                    if(res[i].pixelheight_denom == res[i].pixelheight_num)
                        video_resolutions[i].type = "Widescreen 8x5";
                    else
                        video_resolutions[i].type = "Tall Pixel (CRT) 8x5";
                    break;
                case 0x00050003:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 384;
                    video_resolutions[i].type = "Widescreen 5x3";
                    break;
                case 0x000D0009:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 400;
                    video_resolutions[i].type = "Widescreen 14x9";
                    break;
                case 0x00100009:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 480;
                    video_resolutions[i].type = "Widescreen 16x9";
                    break;
                case 0x00030002:
                    video_resolutions[i].conwidth = 720;
                    video_resolutions[i].conheight = 480;
                    video_resolutions[i].type = "NTSC 3x2";
                    break;
                case 0x000D000B:
                    video_resolutions[i].conwidth = 720;
                    video_resolutions[i].conheight = 566;
                    video_resolutions[i].type = "PAL 14x11";
                    break;
                case 0x00080007:
                    if(video_resolutions[i].width >= 512)
                    {
                        video_resolutions[i].conwidth = 512;
                        video_resolutions[i].conheight = 448;
                        video_resolutions[i].type = "SNES 8x7";
                    }
                    else
                    {
                        video_resolutions[i].conwidth = 256;
                        video_resolutions[i].conheight = 224;
                        video_resolutions[i].type = "NES 8x7";
                    }
                    break;
                default:
                    video_resolutions[i].conwidth = 640;
                    video_resolutions[i].conheight = 640 * d / n;
                    video_resolutions[i].type = "Detected mode";
                    break;
            }
            if(video_resolutions[i].conwidth > video_resolutions[i].width || video_resolutions[i].conheight > video_resolutions[i].height)
            {
                int f1, f2;
                f1 = video_resolutions[i].conwidth > video_resolutions[i].width;
                f2 = video_resolutions[i].conheight > video_resolutions[i].height;
                if(f1 > f2)
                {
                    video_resolutions[i].conwidth = video_resolutions[i].width;
                    video_resolutions[i].conheight = video_resolutions[i].conheight / f1;
                }
                else
                {
                    video_resolutions[i].conwidth = video_resolutions[i].conwidth / f2;
                    video_resolutions[i].conheight = video_resolutions[i].height;
                }
            }
        }
    }
    else
    {
        video_resolutions = video_resolutions_hardcoded;
        video_resolutions_count = sizeof(video_resolutions_hardcoded) / sizeof(*video_resolutions_hardcoded) - 1;
    }
    menu_video_resolutions_forfullscreen = !!vid_fullscreen.integer;
    M_Menu_Video_FindResolution(vid.width, vid.height, vid_pixelheight.value);
    // use -forceqmenu to use always the normal quake menu (it sets forceqmenu to 1)
// COMMANDLINEOPTION: Client: -forceqmenu disables menu.dat (same as +forceqmenu 1)
    if(Sys_CheckParm("-forceqmenu"))
        Cvar_SetValueQuick(&forceqmenu,1);
    // use -useqmenu for debugging proposes, cause it starts
    // the normal quake menu only the first time
// COMMANDLINEOPTION: Client: -useqmenu causes the first time you open the menu to use the quake menu, then reverts to menu.dat (if forceqmenu is 0)
    if(Sys_CheckParm("-useqmenu"))
        MR_SetRouting (true);
    else
        MR_SetRouting (false);
}
Referenced by Host_Init().
MR_Init_Commands()
void MR_Init_Commands (void)
Definition at line 5491 of file menu.c.
{
    // set router console commands
    Cvar_RegisterVariable (&forceqmenu);
    Cvar_RegisterVariable (&menu_options_colorcontrol_correctionvalue);
    Cvar_RegisterVariable (&menu_progs);
    Cmd_AddCommand(CF_CLIENT, "menu_restart", MR_Restart_f, "restart menu system (reloads menu.dat)");
    Cmd_AddCommand(CF_CLIENT, "togglemenu", Call_MR_ToggleMenu_f, "opens or closes menu");
}
Referenced by CL_Init().
MR_Restart()
void MR_Restart (void)
Definition at line 5470 of file menu.c.
{
    if(MR_Shutdown)
        MR_Shutdown ();
    MR_SetRouting (false);
}
Referenced by MR_Restart_f().
MR_Restart_f()
static void MR_Restart_f (cmd_state_t * cmd) static
Definition at line 5477 of file menu.c.
{
    MR_Restart();
}
Referenced by MR_Init_Commands().
MR_SetRouting()
void MR_SetRouting (qbool forceold)
Definition at line 5443 of file menu.c.
{
    // if the menu prog isnt available or forceqmenu ist set, use the old menu
    if(!FS_FileExists(menu_progs.string) || forceqmenu.integer || forceold)
    {
        // set menu router function pointers
        MR_KeyEvent = M_KeyEvent;
        MR_Draw = M_Draw;
        MR_ToggleMenu = M_ToggleMenu;
        MR_Shutdown = M_Shutdown;
        MR_NewMap = M_NewMap;
        MR_GetServerListEntryCategory = M_GetServerListEntryCategory;
        M_Init();
    }
    else
    {
        // set menu router function pointers
        MR_KeyEvent = MP_KeyEvent;
        MR_Draw = MP_Draw;
        MR_ToggleMenu = MP_ToggleMenu;
        MR_Shutdown = MP_Shutdown;
        MR_NewMap = MP_NewMap;
        MR_GetServerListEntryCategory = MP_GetServerListEntryCategory;
        MP_Init();
    }
}
Referenced by MR_Init(), MR_Restart(), and MVM_error_cmd().
MVM_begin_increase_edicts()
static void MVM_begin_increase_edicts (prvm_prog_t * prog) static
Definition at line 5257 of file menu.c.
{
}
Referenced by MP_Init().
MVM_count_edicts()
static void MVM_count_edicts (prvm_prog_t * prog) static
Definition at line 5273 of file menu.c.
{
    int i;
    prvm_edict_t *ent;
    int active;
    active = 0;
    for (i=0 ; i<prog->num_edicts ; i++)
    {
        ent = PRVM_EDICT_NUM(i);
        if (ent->free)
            continue;
        active++;
    }
    Con_Printf("num_edicts:%3i\n", prog->num_edicts);
    Con_Printf("active    :%3i\n", active);
}
Referenced by MP_Init().
MVM_end_increase_edicts()
static void MVM_end_increase_edicts (prvm_prog_t * prog) static
Definition at line 5261 of file menu.c.
{
}
Referenced by MP_Init().
MVM_error_cmd()
void MVM_error_cmd (const char * format, ...)
Definition at line 5212 of file menu.c.
{
    static qbool processingError = false;
    char errorstring[MAX_INPUTLINE];
    va_list argptr;
    int outfd = sys.outfd;
    // set output to stderr
    sys.outfd = fileno(stderr);
    va_start (argptr, format);
    dpvsnprintf (errorstring, sizeof(errorstring), format, argptr);
    va_end (argptr);
    if (host.framecount < 3)
        Sys_Error("Menu_Error: %s", errorstring);
    Con_Printf(CON_ERROR "Menu_Error: %s\n", errorstring);
    if(!processingError)
    {
        processingError = true;
        PRVM_Crash();
        processingError = false;
    }
    else
        Sys_Error("Menu_Error: Recursive call to MVM_error_cmd (from PRVM_Crash)!");
    Con_Print("Falling back to engine menu\n");
    key_dest = key_game;
    MR_SetRouting (true);
    // reset the active scene, too (to be on the safe side ;))
    R_SelectScene( RST_CLIENT );
    // prevent an endless loop if the error was triggered by a command
    Cbuf_Clear(cmd_local->cbuf);
    // restore configured outfd
    sys.outfd = outfd;
    // Let video start at least
    Host_AbortCurrentFrame();
}
Referenced by MP_Init().
MVM_free_edict()
static void MVM_free_edict (prvm_prog_t * prog, prvm_edict_t * ed) static
Definition at line 5269 of file menu.c.
{
}
Referenced by MP_Init().
MVM_init_edict()
static void MVM_init_edict (prvm_prog_t * prog, prvm_edict_t * edict) static
Definition at line 5265 of file menu.c.
{
}
Referenced by MP_Init().
MVM_load_edict()
static qbool MVM_load_edict (prvm_prog_t * prog, prvm_edict_t * ent) static
Definition at line 5292 of file menu.c.
{
    return true;
}
Referenced by MP_Init().
setup_rateindex()
static int setup_rateindex (int rate) static
Definition at line 1321 of file menu.c.
{
    int i;
    for (i = 0;i < RATES;i++)
        if (setup_ratetable[i].rate > setup_rate)
            break;
    return bound(1, i, RATES) - 1;
}
Referenced by M_Setup_Draw(), and M_Setup_Key().
Variable Documentation
battlemechepisodes
episode_t battlemechepisodes[] static
Initial value:
=
{
    {"Time for Battle", 0, 7},
}
Definition at line 3848 of file menu.c.
{
    {"Time for Battle", 0, 7},
};
battlemechgame
gamelevels_t battlemechgame = {"Battlemech", battlemechlevels, battlemechepisodes, 1} static
Definition at line 3911 of file menu.c.
{"Battlemech", battlemechlevels, battlemechepisodes, 1};
battlemechlevels
level_t battlemechlevels[] static
Initial value:
=
{
    {"start", "Parking Level"},
    {"dm1", "Hot Dump"},
    {"dm2", "The Pits"},
    {"dm3", "Dimber Died"},
    {"dm4", "Fire in the Hole"},
    {"dm5", "Clubhouses"},
    {"dm6", "Army go Underground"},
}
Definition at line 3837 of file menu.c.
{
    {"start", "Parking Level"},
    {"dm1", "Hot Dump"},                        // 1
    {"dm2", "The Pits"},
    {"dm3", "Dimber Died"},
    {"dm4", "Fire in the Hole"},
    {"dm5", "Clubhouses"},
    {"dm6", "Army go Underground"},
};
bind_grab
int bind_grab static
Definition at line 2544 of file menu.c.
Referenced by M_Keys_Draw(), and M_Keys_Key().
bindnames
const char*(* bindnames)[2] static
Definition at line 2450 of file menu.c.
Referenced by M_Keys_Draw(), M_Keys_Key(), and M_Menu_Keys_f().
cl_beams_instantaimhack
cvar_t cl_beams_instantaimhack extern
Definition at line 78 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_beams_instantaimhack", "0", "makes your lightning gun aiming update instantly"};
Referenced by CL_Beam_CalculatePositions(), CL_Init(), M_Menu_Options_Effects_AdjustSliders(), and M_Options_Effects_Draw().
cl_beams_lightatend
cvar_t cl_beams_lightatend extern
Definition at line 79 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_beams_lightatend", "0", "make a light at the end of the beam"};
Referenced by CL_Init(), CL_RelinkBeams(), M_Menu_Options_Effects_AdjustSliders(), and M_Options_Effects_Draw().
cl_beams_polygons
cvar_t cl_beams_polygons extern
Definition at line 76 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_beams_polygons", "1","use beam polygons instead of models"};
Referenced by CL_Init(), CL_RelinkBeams(), M_Menu_Options_Effects_AdjustSliders(), and M_Options_Effects_Draw().
cl_beams_quakepositionhack
cvar_t cl_beams_quakepositionhack extern
Definition at line 77 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_beams_quakepositionhack", "1", "makes your lightning gun appear to fire from your waist (as in Quake and QuakeWorld)"};
Referenced by CL_Beam_CalculatePositions(), CL_Init(), M_Menu_Options_Effects_AdjustSliders(), and M_Options_Effects_Draw().
cl_bottomcolor
cvar_t cl_bottomcolor extern
Definition at line 36 of file cl_cmd.c.
{CF_CLIENT | CF_ARCHIVE | CF_USERINFO, "bottomcolor", "0", "color of your pants"};
Referenced by CL_Color_c(), CL_Color_f(), CL_InitCommands(), CL_Topcolor_c(), and M_Menu_Setup_f().
cl_stainmaps
cvar_t cl_stainmaps extern
Definition at line 73 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_stainmaps", "0","stains lightmaps, much faster than decals but blurred"};
Referenced by CL_Init(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), Mod_Q1BSP_LoadFaces(), and Mod_VBSP_LoadFaces().
cl_stainmaps_clearonload
cvar_t cl_stainmaps_clearonload extern
Definition at line 74 of file cl_main.c.
{CF_CLIENT | CF_ARCHIVE, "cl_stainmaps_clearonload", "1","clear stainmaps on map restart"};
Referenced by CL_Init(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and mod_newmap().
cl_topcolor
cvar_t cl_topcolor extern
Definition at line 35 of file cl_cmd.c.
{CF_CLIENT | CF_ARCHIVE | CF_USERINFO, "topcolor", "0", "color of your shirt"};
Referenced by CL_Bottomcolor_c(), CL_Color_c(), CL_Color_f(), CL_InitCommands(), and M_Menu_Setup_f().
defeatindetail2episodes
episode_t defeatindetail2episodes[] static
Initial value:
=
{
    {"ATAC Campaign", 0, 3},
}
Definition at line 3886 of file menu.c.
{
    {"ATAC Campaign", 0, 3},
};
defeatindetail2game
gamelevels_t defeatindetail2game = {"Defeat In Detail 2", defeatindetail2levels, defeatindetail2episodes, 1} static
Definition at line 3913 of file menu.c.
{"Defeat In Detail 2", defeatindetail2levels, defeatindetail2episodes, 1};
defeatindetail2levels
level_t defeatindetail2levels[] static
Initial value:
=
{
    {"atac3",   "River Crossing"},
    {"atac4",   "Canyon Chaos"},
    {"atac7",   "Desert Stormer"},
}
Definition at line 3879 of file menu.c.
{
    {"atac3",   "River Crossing"},
    {"atac4",   "Canyon Chaos"},
    {"atac7",   "Desert Stormer"},
};
demo_cursor
int demo_cursor static
Definition at line 289 of file menu.c.
Referenced by M_Demo_Draw(), and M_Demo_Key().
forceqmenu
cvar_t forceqmenu = {CF_CLIENT, "forceqmenu", "0", "enables the quake menu instead of the quakec menu.dat (if present)"} static
Definition at line 31 of file menu.c.
{CF_CLIENT, "forceqmenu", "0", "enables the quake menu instead of the quakec menu.dat (if present)"};
Referenced by M_Menu_Main_f(), MR_Init(), MR_Init_Commands(), and MR_SetRouting().
gamelist
gameinfo_t gamelist[] static
Initial value:
=
{
    {GAME_NORMAL, &sharewarequakegame, &registeredquakegame},
    {GAME_HIPNOTIC, &hipnoticgame, &hipnoticgame},
    {GAME_ROGUE, &roguegame, &roguegame},
    {GAME_QUOTH, &sharewarequakegame, &registeredquakegame},
    {GAME_NEHAHRA, &nehahragame, &nehahragame},
    {GAME_TRANSFUSION, &transfusiongame, &transfusiongame},
    {GAME_GOODVSBAD2, &goodvsbad2game, &goodvsbad2game},
    {GAME_BATTLEMECH, &battlemechgame, &battlemechgame},
    {GAME_OPENQUARTZ, &openquartzgame, &openquartzgame},
    {GAME_DEFEATINDETAIL2, &defeatindetail2game, &defeatindetail2game},
    {GAME_PRYDON, &prydongame, &prydongame},
}
Definition at line 3924 of file menu.c.
{
    {GAME_NORMAL, &sharewarequakegame, &registeredquakegame},
    {GAME_HIPNOTIC, &hipnoticgame, &hipnoticgame},
    {GAME_ROGUE, &roguegame, &roguegame},
    {GAME_QUOTH, &sharewarequakegame, &registeredquakegame},
    {GAME_NEHAHRA, &nehahragame, &nehahragame},
    {GAME_TRANSFUSION, &transfusiongame, &transfusiongame},
    {GAME_GOODVSBAD2, &goodvsbad2game, &goodvsbad2game},
    {GAME_BATTLEMECH, &battlemechgame, &battlemechgame},
    {GAME_OPENQUARTZ, &openquartzgame, &openquartzgame},
    {GAME_DEFEATINDETAIL2, &defeatindetail2game, &defeatindetail2game},
    {GAME_PRYDON, &prydongame, &prydongame},
};
Referenced by M_Menu_GameOptions_f().
gameoptions_cursor
int gameoptions_cursor static
Definition at line 3967 of file menu.c.
Referenced by M_GameOptions_Draw(), M_GameOptions_Key(), and M_NetStart_Change().
gameoptions_cursor_table
int gameoptions_cursor_table[] = {40, 56, 64, 72, 80, 88, 96, 104, 112, 140, 160, 168} static
Definition at line 3965 of file menu.c.
{40, 56, 64, 72, 80, 88, 96, 104, 112, 140, 160, 168};
Referenced by M_GameOptions_Draw().
gameoptions_levels
gamelevels_t* gameoptions_levels = NULL static
Definition at line 3939 of file menu.c.
Referenced by M_GameOptions_Draw(), M_GameOptions_Key(), M_Menu_GameOptions_f(), and M_NetStart_Change().
gl_flashblend
cvar_t gl_flashblend extern
Definition at line 236 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "gl_flashblend", "0", "render bright coronas for dynamic lights instead of actual lighting, fast but ugly"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_UpdateVariables().
gl_picmip
cvar_t gl_picmip extern
Definition at line 29 of file gl_textures.c.
{CF_CLIENT | CF_ARCHIVE, "gl_picmip", "0", "reduces resolution of textures by powers of 2, for example 1 will halve width/height, reducing texture memory usage by 75%"};
Referenced by M_Menu_Video_AdjustSliders(), M_Video_Draw(), R_PicmipForFlags(), and R_Textures_Init().
gl_texture_anisotropy
cvar_t gl_texture_anisotropy extern
Definition at line 36 of file gl_textures.c.
{CF_CLIENT | CF_ARCHIVE, "gl_texture_anisotropy", "1", "anisotropic filtering quality (if supported by hardware), 1 sample (no anisotropy) and 8 sample (8 tap anisotropy) are recommended values"};
Referenced by GL_SetupTextureParameters(), M_Menu_Video_AdjustSliders(), M_Video_Draw(), R_Textures_Frame(), and R_Textures_Init().
goodvsbad2bindnames
const char* goodvsbad2bindnames[][2] static
Initial value:
=
{
{"impulse 69",      "Power 1"},
{"impulse 70",      "Power 2"},
{"impulse 71",      "Power 3"},
{"+jump",           "jump / swim up"},
{"+forward",        "walk forward"},
{"+back",           "backpedal"},
{"+left",           "turn left"},
{"+right",          "turn right"},
{"+speed",          "run"},
{"+moveleft",       "step left"},
{"+moveright",      "step right"},
{"+strafe",         "sidestep"},
{"+lookup",         "look up"},
{"+lookdown",       "look down"},
{"centerview",      "center view"},
{"+mlook",          "mouse look"},
{"kill",            "kill yourself"},
{"+moveup",         "swim up"},
{"+movedown",       "swim down"}
}
Definition at line 2426 of file menu.c.
{
{"impulse 69",      "Power 1"},
{"impulse 70",      "Power 2"},
{"impulse 71",      "Power 3"},
{"+jump",           "jump / swim up"},
{"+forward",        "walk forward"},
{"+back",           "backpedal"},
{"+left",           "turn left"},
{"+right",          "turn right"},
{"+speed",          "run"},
{"+moveleft",       "step left"},
{"+moveright",      "step right"},
{"+strafe",         "sidestep"},
{"+lookup",         "look up"},
{"+lookdown",       "look down"},
{"centerview",      "center view"},
{"+mlook",          "mouse look"},
{"kill",            "kill yourself"},
{"+moveup",         "swim up"},
{"+movedown",       "swim down"}
};
Referenced by M_Menu_Keys_f().
goodvsbad2episodes
episode_t goodvsbad2episodes[] static
Initial value:
=
{
    {"Levels? Bevels!", 0, 8},
}
Definition at line 3832 of file menu.c.
{
    {"Levels? Bevels!", 0, 8},
};
goodvsbad2game
gamelevels_t goodvsbad2game = {"Good Vs. Bad 2", goodvsbad2levels, goodvsbad2episodes, 1} static
Definition at line 3910 of file menu.c.
{"Good Vs. Bad 2", goodvsbad2levels, goodvsbad2episodes, 1};
goodvsbad2levels
level_t goodvsbad2levels[] static
Initial value:
=
{
    {"rts", "Many Paths"},
    {"chess", "Chess, Scott Hess"},
    {"dot", "Big Wall"},
    {"city2", "The Big City"},
    {"bwall", "0 G like Psychic TV"},
    {"snow", "Wireframed"},
    {"telep", "Infinite Falling"},
    {"faces", "Facing Bases"},
    {"island", "Adventure Islands"},
}
Definition at line 3819 of file menu.c.
{
    {"rts", "Many Paths"},  // 0
    {"chess", "Chess, Scott Hess"},                         // 1
    {"dot", "Big Wall"},
    {"city2", "The Big City"},
    {"bwall", "0 G like Psychic TV"},
    {"snow", "Wireframed"},
    {"telep", "Infinite Falling"},
    {"faces", "Facing Bases"},
    {"island", "Adventure Islands"},
};
help_page
int help_page static
Definition at line 3084 of file menu.c.
Referenced by M_Help_Draw(), M_Help_Key(), and M_Menu_Help_f().
hipnoticepisodes
episode_t hipnoticepisodes[] static
Initial value:
=
{
   {"Scourge of Armagon", 0, 1},
   {"Fortress of the Dead", 1, 5},
   {"Dominion of Darkness", 6, 6},
   {"The Rift", 12, 4},
   {"Final Level", 16, 1},
   {"Deathmatch Arena", 17, 1}
}
Definition at line 3621 of file menu.c.
{
   {"Scourge of Armagon", 0, 1},
   {"Fortress of the Dead", 1, 5},
   {"Dominion of Darkness", 6, 6},
   {"The Rift", 12, 4},
   {"Final Level", 16, 1},
   {"Deathmatch Arena", 17, 1}
};
hipnoticgame
gamelevels_t hipnoticgame = {"Scourge of Armagon", hipnoticlevels, hipnoticepisodes, 6} static
Definition at line 3906 of file menu.c.
{"Scourge of Armagon", hipnoticlevels, hipnoticepisodes, 6};
hipnoticlevels
level_t hipnoticlevels[] static
Initial value:
=
{
   {"start", "Command HQ"},
   {"hip1m1", "The Pumping Station"},
   {"hip1m2", "Storage Facility"},
   {"hip1m3", "The Lost Mine"},
   {"hip1m4", "Research Facility"},
   {"hip1m5", "Military Complex"},
   {"hip2m1", "Ancient Realms"},
   {"hip2m2", "The Black Cathedral"},
   {"hip2m3", "The Catacombs"},
   {"hip2m4", "The Crypt"},
   {"hip2m5", "Mortum's Keep"},
   {"hip2m6", "The Gremlin's Domain"},
   {"hip3m1", "Tur Torment"},
   {"hip3m2", "Pandemonium"},
   {"hip3m3", "Limbo"},
   {"hip3m4", "The Gauntlet"},
   {"hipend", "Armagon's Lair"},
   {"hipdm1", "The Edge of Oblivion"}
}
Definition at line 3593 of file menu.c.
{
   {"start", "Command HQ"},  // 0
   {"hip1m1", "The Pumping Station"},          // 1
   {"hip1m2", "Storage Facility"},
   {"hip1m3", "The Lost Mine"},
   {"hip1m4", "Research Facility"},
   {"hip1m5", "Military Complex"},
   {"hip2m1", "Ancient Realms"},          // 6
   {"hip2m2", "The Black Cathedral"},
   {"hip2m3", "The Catacombs"},
   {"hip2m4", "The Crypt"},
   {"hip2m5", "Mortum's Keep"},
   {"hip2m6", "The Gremlin's Domain"},
   {"hip3m1", "Tur Torment"},       // 12
   {"hip3m2", "Pandemonium"},
   {"hip3m3", "Limbo"},
   {"hip3m4", "The Gauntlet"},
   {"hipend", "Armagon's Lair"},       // 16
   {"hipdm1", "The Edge of Oblivion"}           // 17
};
host_timescale
cvar_t host_timescale extern
Definition at line 54 of file sv_main.c.
{CF_CLIENT | CF_SERVER, "host_timescale", "1.0", "controls game speed, 0.5 is half speed, 2 is double speed"};
jpeg_dll
dllhandle_t jpeg_dll extern
Definition at line 457 of file jpeg.c.
Referenced by Image_Compress(), JPEG_CloseLibrary(), JPEG_LoadImage_BGRA(), JPEG_OpenLibrary(), JPEG_SaveImage_preflipped(), and JPEG_SaveImage_to_Buffer().
keys_cursor
int keys_cursor static
Definition at line 2543 of file menu.c.
Referenced by M_Keys_Draw(), M_Keys_Key(), and M_Menu_Keys_f().
lanConfig_cursor
int lanConfig_cursor = -1 static
Definition at line 3316 of file menu.c.
Referenced by M_LanConfig_Draw(), M_LanConfig_Key(), M_Menu_LanConfig_f(), M_Menu_ServerList_f(), and M_ServerList_Key().
lanConfig_cursor_table
int lanConfig_cursor_table[] = {56, 76, 84, 120} static
Definition at line 3317 of file menu.c.
{56, 76, 84, 120};
Referenced by M_LanConfig_Draw().
lanConfig_joinname
char lanConfig_joinname[40] static
Definition at line 3322 of file menu.c.
Referenced by M_LanConfig_Draw(), and M_LanConfig_Key().
lanConfig_port
int lanConfig_port static
Definition at line 3320 of file menu.c.
Referenced by M_LanConfig_Key(), and M_Menu_LanConfig_f().
lanConfig_portname
char lanConfig_portname[6] static
Definition at line 3321 of file menu.c.
Referenced by M_LanConfig_Draw(), M_LanConfig_Key(), and M_Menu_LanConfig_f().
load_cursor
int load_cursor static
0 < load_cursor < MAX_SAVEGAMES
Definition at line 836 of file menu.c.
Referenced by M_Load_Draw(), M_Load_Key(), M_Save_Draw(), and M_Save_Key().
loadable
int loadable[MAX_SAVEGAMES] static
Definition at line 839 of file menu.c.
Referenced by M_Load_Key(), and M_ScanSaves().
m_entersound
qbool m_entersound static
play after drawing a frame, so caching won't disrupt the sound
Definition at line 108 of file menu.c.
Referenced by M_Draw(), M_Help_Key(), M_LanConfig_Key(), M_Main_Key(), M_Menu_Credits_f(), M_Menu_Demos_f(), M_Menu_GameOptions_f(), M_Menu_Help_f(), M_Menu_Keys_f(), M_Menu_LanConfig_f(), M_Menu_Load_f(), M_Menu_Main_f(), M_Menu_ModList_f(), M_Menu_MultiPlayer_f(), M_Menu_Options_ColorControl_f(), M_Menu_Options_Effects_f(), M_Menu_Options_f(), M_Menu_Options_Graphics_f(), M_Menu_Quit_f(), M_Menu_Reset_f(), M_Menu_Save_f(), M_Menu_ServerList_f(), M_Menu_Setup_f(), M_Menu_SinglePlayer_f(), M_Menu_Transfusion_Episode_f(), M_Menu_Transfusion_Skill_f(), M_Menu_Video_f(), M_MultiPlayer_Key(), M_Options_ColorControl_Key(), M_Options_Key(), M_Quit_Key(), M_Reset_Key(), M_Setup_Key(), M_SinglePlayer_Key(), M_ToggleMenu(), M_Transfusion_Episode_Key(), M_Transfusion_Skill_Key(), and M_Video_Key().
m_episode_cursor
int m_episode_cursor static
Definition at line 1027 of file menu.c.
Referenced by M_Transfusion_Episode_Draw(), M_Transfusion_Episode_Key(), and M_Transfusion_Skill_Key().
m_filenames
char m_filenames[MAX_SAVEGAMES][SAVEGAME_COMMENT_LENGTH+1] static
Definition at line 838 of file menu.c.
Referenced by M_Load_Draw(), M_Save_Draw(), and M_ScanSaves().
m_main_cursor
int m_main_cursor static
Definition at line 349 of file menu.c.
Referenced by M_Main_Draw(), and M_Main_Key().
m_missingdata
qbool m_missingdata = false static
Definition at line 350 of file menu.c.
Referenced by M_ChooseQuitMessage(), M_Draw(), M_Main_Draw(), M_Main_Key(), M_Menu_Main_f(), and M_Quit_Draw().
m_multiplayer_cursor
int m_multiplayer_cursor static
Definition at line 1186 of file menu.c.
Referenced by M_MultiPlayer_Draw(), and M_MultiPlayer_Key().
m_numrequiredfields
int m_numrequiredfields = sizeof(m_required_fields) / sizeof(m_required_fields[0]) static
Definition at line 5128 of file menu.c.
Referenced by MP_Init().
m_numrequiredfunc
int m_numrequiredfunc = sizeof(m_required_func) / sizeof(char*) static
Definition at line 5049 of file menu.c.
Referenced by MP_Init().
m_numrequiredglobals
int m_numrequiredglobals = sizeof(m_required_globals) / sizeof(m_required_globals[0]) static
Definition at line 5207 of file menu.c.
Referenced by MP_Init().
m_optcursor
int m_optcursor static
Definition at line 1625 of file menu.c.
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), and M_Options_PrintSlider().
m_optnum
int m_optnum static
Definition at line 1623 of file menu.c.
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), and M_Options_PrintSlider().
m_opty
int m_opty static
Definition at line 1624 of file menu.c.
Referenced by M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), and M_Options_PrintSlider().
m_quit_message
const char* m_quit_message[9] static
Definition at line 3161 of file menu.c.
Referenced by M_Quit_Draw(), and M_QuitMessage().
m_quit_prevstate
int m_quit_prevstate static
Definition at line 3162 of file menu.c.
Referenced by M_Menu_Quit_f(), and M_Quit_Key().
m_required_fields
prvm_required_field_t m_required_fields[] static
Definition at line 5051 of file menu.c.
{
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x)
#define PRVM_DECLARE_menuglobalvector(x)
#define PRVM_DECLARE_menuglobalstring(x)
#define PRVM_DECLARE_menuglobaledict(x)
#define PRVM_DECLARE_menuglobalfunction(x)
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x) {ev_float, #x},
#define PRVM_DECLARE_menufieldvector(x) {ev_vector, #x},
#define PRVM_DECLARE_menufieldstring(x) {ev_string, #x},
#define PRVM_DECLARE_menufieldedict(x) {ev_entity, #x},
#define PRVM_DECLARE_menufieldfunction(x) {ev_function, #x},
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x)
#include "prvm_offsets.h"
#undef PRVM_DECLARE_serverglobalfloat
#undef PRVM_DECLARE_serverglobalvector
#undef PRVM_DECLARE_serverglobalstring
#undef PRVM_DECLARE_serverglobaledict
#undef PRVM_DECLARE_serverglobalfunction
#undef PRVM_DECLARE_clientglobalfloat
#undef PRVM_DECLARE_clientglobalvector
#undef PRVM_DECLARE_clientglobalstring
#undef PRVM_DECLARE_clientglobaledict
#undef PRVM_DECLARE_clientglobalfunction
#undef PRVM_DECLARE_menuglobalfloat
#undef PRVM_DECLARE_menuglobalvector
#undef PRVM_DECLARE_menuglobalstring
#undef PRVM_DECLARE_menuglobaledict
#undef PRVM_DECLARE_menuglobalfunction
#undef PRVM_DECLARE_serverfieldfloat
#undef PRVM_DECLARE_serverfieldvector
#undef PRVM_DECLARE_serverfieldstring
#undef PRVM_DECLARE_serverfieldedict
#undef PRVM_DECLARE_serverfieldfunction
#undef PRVM_DECLARE_clientfieldfloat
#undef PRVM_DECLARE_clientfieldvector
#undef PRVM_DECLARE_clientfieldstring
#undef PRVM_DECLARE_clientfieldedict
#undef PRVM_DECLARE_clientfieldfunction
#undef PRVM_DECLARE_menufieldfloat
#undef PRVM_DECLARE_menufieldvector
#undef PRVM_DECLARE_menufieldstring
#undef PRVM_DECLARE_menufieldedict
#undef PRVM_DECLARE_menufieldfunction
#undef PRVM_DECLARE_serverfunction
#undef PRVM_DECLARE_clientfunction
#undef PRVM_DECLARE_menufunction
#undef PRVM_DECLARE_field
#undef PRVM_DECLARE_global
#undef PRVM_DECLARE_function
};
Referenced by MP_Init().
m_required_func
const char* m_required_func[] static
Initial value:
= {
"m_init",
"m_keydown",
"m_draw",
"m_toggle",
"m_shutdown",
}
Definition at line 5041 of file menu.c.
{
"m_init",
"m_keydown",
"m_draw",
"m_toggle",
"m_shutdown",
};
Referenced by MP_Init().
m_required_globals
prvm_required_field_t m_required_globals[] static
Definition at line 5130 of file menu.c.
{
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x) {ev_float, #x},
#define PRVM_DECLARE_menuglobalvector(x) {ev_vector, #x},
#define PRVM_DECLARE_menuglobalstring(x) {ev_string, #x},
#define PRVM_DECLARE_menuglobaledict(x) {ev_entity, #x},
#define PRVM_DECLARE_menuglobalfunction(x) {ev_function, #x},
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x)
#define PRVM_DECLARE_menufieldvector(x)
#define PRVM_DECLARE_menufieldstring(x)
#define PRVM_DECLARE_menufieldedict(x)
#define PRVM_DECLARE_menufieldfunction(x)
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x)
#include "prvm_offsets.h"
#undef PRVM_DECLARE_serverglobalfloat
#undef PRVM_DECLARE_serverglobalvector
#undef PRVM_DECLARE_serverglobalstring
#undef PRVM_DECLARE_serverglobaledict
#undef PRVM_DECLARE_serverglobalfunction
#undef PRVM_DECLARE_clientglobalfloat
#undef PRVM_DECLARE_clientglobalvector
#undef PRVM_DECLARE_clientglobalstring
#undef PRVM_DECLARE_clientglobaledict
#undef PRVM_DECLARE_clientglobalfunction
#undef PRVM_DECLARE_menuglobalfloat
#undef PRVM_DECLARE_menuglobalvector
#undef PRVM_DECLARE_menuglobalstring
#undef PRVM_DECLARE_menuglobaledict
#undef PRVM_DECLARE_menuglobalfunction
#undef PRVM_DECLARE_serverfieldfloat
#undef PRVM_DECLARE_serverfieldvector
#undef PRVM_DECLARE_serverfieldstring
#undef PRVM_DECLARE_serverfieldedict
#undef PRVM_DECLARE_serverfieldfunction
#undef PRVM_DECLARE_clientfieldfloat
#undef PRVM_DECLARE_clientfieldvector
#undef PRVM_DECLARE_clientfieldstring
#undef PRVM_DECLARE_clientfieldedict
#undef PRVM_DECLARE_clientfieldfunction
#undef PRVM_DECLARE_menufieldfloat
#undef PRVM_DECLARE_menufieldvector
#undef PRVM_DECLARE_menufieldstring
#undef PRVM_DECLARE_menufieldedict
#undef PRVM_DECLARE_menufieldfunction
#undef PRVM_DECLARE_serverfunction
#undef PRVM_DECLARE_clientfunction
#undef PRVM_DECLARE_menufunction
#undef PRVM_DECLARE_field
#undef PRVM_DECLARE_global
#undef PRVM_DECLARE_function
};
Referenced by MP_Init().
m_serverInfoMessage
qbool m_serverInfoMessage = false static
Definition at line 3944 of file menu.c.
Referenced by M_GameOptions_Draw(), and M_NetStart_Change().
m_serverInfoMessageTime
double m_serverInfoMessageTime static
Definition at line 3945 of file menu.c.
Referenced by M_GameOptions_Draw(), and M_NetStart_Change().
m_singleplayer_cursor
int m_singleplayer_cursor static
Definition at line 726 of file menu.c.
Referenced by M_SinglePlayer_Draw(), and M_SinglePlayer_Key().
m_skill_cursor
int m_skill_cursor = 2 static
Definition at line 1085 of file menu.c.
Referenced by M_Transfusion_Skill_Draw(), and M_Transfusion_Skill_Key().
m_state
enum m_state_e m_state
Definition at line 36 of file menu.c.
Referenced by M_Demo_Key(), M_Draw(), M_KeyEvent(), M_Load_Key(), M_Main_Key(), M_Menu_Credits_f(), M_Menu_Demos_f(), M_Menu_GameOptions_f(), M_Menu_Help_f(), M_Menu_Keys_f(), M_Menu_LanConfig_f(), M_Menu_Load_f(), M_Menu_Main_f(), M_Menu_ModList_f(), M_Menu_MultiPlayer_f(), M_Menu_Options_ColorControl_f(), M_Menu_Options_Effects_f(), M_Menu_Options_f(), M_Menu_Options_Graphics_f(), M_Menu_Quit_f(), M_Menu_Reset_f(), M_Menu_Save_f(), M_Menu_ServerList_f(), M_Menu_Setup_f(), M_Menu_SinglePlayer_f(), M_Menu_Transfusion_Episode_f(), M_Menu_Transfusion_Skill_f(), M_Menu_Video_f(), M_Options_Key(), M_Quit_Key(), M_Reset_Key(), M_Save_Key(), M_SinglePlayer_Key(), M_ToggleMenu(), and NetConn_ConnectionEstablished().
MAIN_ITEMS
int MAIN_ITEMS = 4 static
Definition at line 352 of file menu.c.
Referenced by M_Main_Draw(), M_Main_Key(), and M_Menu_Main_f().
maxplayers
int maxplayers static
Definition at line 3943 of file menu.c.
Referenced by M_GameOptions_Draw(), M_GameOptions_Key(), M_Menu_GameOptions_f(), and M_NetStart_Change().
menu_height
float menu_height static
Definition at line 159 of file menu.c.
Referenced by M_Background(), M_ModList_Draw(), M_Options_ColorControl_Draw(), M_Options_Draw(), M_Options_Effects_Draw(), M_Options_Graphics_Draw(), and M_ServerList_Draw().
menu_options_colorcontrol_correctionvalue
cvar_t menu_options_colorcontrol_correctionvalue = {CF_CLIENT, "menu_options_colorcontrol_correctionvalue", "0.5", "intensity value that matches up to white/black dither pattern, should be 0.5 for linear color"} static
Definition at line 2098 of file menu.c.
{CF_CLIENT, "menu_options_colorcontrol_correctionvalue", "0.5", "intensity value that matches up to white/black dither pattern, should be 0.5 for linear color"};
Referenced by M_Options_ColorControl_Draw(), and MR_Init_Commands().
menu_progs
cvar_t menu_progs = {CF_CLIENT, "menu_progs", "menu.dat", "name of quakec menu.dat file"} static
Definition at line 32 of file menu.c.
{CF_CLIENT, "menu_progs", "menu.dat", "name of quakec menu.dat file"};
Referenced by MP_Init(), MR_Init_Commands(), and MR_SetRouting().
menu_video_resolution
int menu_video_resolution static
Definition at line 2836 of file menu.c.
Referenced by M_Menu_Video_AdjustSliders(), M_Menu_Video_FindResolution(), M_Video_Draw(), and M_Video_Key().
menu_video_resolutions
video_resolution_t* menu_video_resolutions static
Definition at line 2841 of file menu.c.
Referenced by M_Menu_Video_AdjustSliders(), M_Menu_Video_FindResolution(), M_Video_Draw(), and M_Video_Key().
menu_video_resolutions_count
int menu_video_resolutions_count static
Definition at line 2842 of file menu.c.
Referenced by M_Menu_Video_AdjustSliders(), and M_Menu_Video_FindResolution().
menu_video_resolutions_forfullscreen
qbool menu_video_resolutions_forfullscreen static
Definition at line 2843 of file menu.c.
Referenced by M_Menu_Video_FindResolution(), M_Video_Draw(), and MR_Init().
menu_width
float menu_width static
Definition at line 159 of file menu.c.
Referenced by M_Background().
menu_x
float menu_x static
Definition at line 159 of file menu.c.
Referenced by M_Background(), M_DrawCharacter(), M_DrawPic(), M_ItemPrint(), M_ModList_Draw(), M_Options_ColorControl_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), M_Options_PrintSlider(), M_Print(), M_PrintColored(), M_PrintRed(), and M_ServerList_Draw().
menu_y
float menu_y static
Definition at line 159 of file menu.c.
Referenced by M_Background(), M_DrawCharacter(), M_DrawPic(), M_ItemPrint(), M_ModList_Draw(), M_Options_ColorControl_Draw(), M_Options_PrintCheckbox(), M_Options_PrintCommand(), M_Options_PrintSlider(), M_Print(), M_PrintColored(), M_PrintRed(), and M_ServerList_Draw().
menuplyr_bottom
int menuplyr_bottom static
Definition at line 1293 of file menu.c.
Referenced by M_Setup_Draw().
menuplyr_height
int menuplyr_height static
Definition at line 1293 of file menu.c.
Referenced by M_Setup_Draw().
menuplyr_load
int menuplyr_load static
Definition at line 1293 of file menu.c.
Referenced by M_Init(), and M_Setup_Draw().
menuplyr_pixels
unsigned char* menuplyr_pixels static
Definition at line 1294 of file menu.c.
Referenced by M_Init(), and M_Setup_Draw().
menuplyr_top
int menuplyr_top static
Definition at line 1293 of file menu.c.
Referenced by M_Setup_Draw().
menuplyr_translated
unsigned int* menuplyr_translated static
Definition at line 1295 of file menu.c.
Referenced by M_Setup_Draw().
menuplyr_width
int menuplyr_width static
Definition at line 1293 of file menu.c.
Referenced by M_Setup_Draw().
modlist
modlist_entry_t modlist[MODLIST_TOTALSIZE] static
Definition at line 4529 of file menu.c.
Referenced by M_Menu_ModList_AdjustSliders(), M_ModList_Draw(), ModList_Enable(), and ModList_RebuildList().
modlist_count
int modlist_count = 0 static
Definition at line 4528 of file menu.c.
Referenced by M_ModList_Draw(), M_ModList_Key(), and ModList_RebuildList().
modlist_cursor
int modlist_cursor static
Definition at line 4525 of file menu.c.
Referenced by M_Menu_ModList_AdjustSliders(), M_Menu_ModList_f(), M_ModList_Draw(), and M_ModList_Key().
modlist_enabled
int modlist_enabled[MODLIST_MAXDIRS] static
Definition at line 4511 of file menu.c.
Referenced by M_Menu_ModList_AdjustSliders(), M_ModList_Draw(), ModList_Enable(), and ModList_RebuildList().
modlist_numenabled
int modlist_numenabled static
Definition at line 4512 of file menu.c.
Referenced by M_Menu_ModList_AdjustSliders(), M_ModList_Draw(), ModList_Enable(), and ModList_RebuildList().
MR_Draw
void(* MR_Draw) (void) (void)
Definition at line 5437 of file menu.c.
Referenced by MR_SetRouting(), and SCR_DrawScreen().
MR_GetServerListEntryCategory
int(* MR_GetServerListEntryCategory) (const serverlist_entry_t *entry) (const serverlist_entry_t * entry)
Definition at line 5441 of file menu.c.
Referenced by MR_SetRouting().
MR_KeyEvent
void(* MR_KeyEvent) (int key, int ascii, qbool downevent) (int key, int ascii, qbool downevent)
Definition at line 5436 of file menu.c.
Referenced by Key_Event(), and MR_SetRouting().
MR_NewMap
void(* MR_NewMap) (void) (void)
Definition at line 5440 of file menu.c.
Referenced by CL_SetupWorldModel(), and MR_SetRouting().
MR_Shutdown
void(* MR_Shutdown) (void) (void)
Definition at line 5439 of file menu.c.
Referenced by CL_Shutdown(), Host_LoadConfig_f(), MR_Restart(), and MR_SetRouting().
MR_ToggleMenu
void(* MR_ToggleMenu) (int mode) (int mode)
Definition at line 5438 of file menu.c.
Referenced by Call_MR_ToggleMenu_f(), CL_ToggleMenu_Hook(), Key_Event(), MR_SetRouting(), and SCR_SetUpToDrawConsole().
NehahraDemos
nehahrademonames_t NehahraDemos[NumberOfNehahraDemos] static
Definition at line 121 of file menu.c.
{
    {"intro", "Prologue"},
    {"genf", "The Beginning"},
    {"genlab", "A Doomed Project"},
    {"nehcre", "The New Recruits"},
    {"maxneh", "Breakthrough"},
    {"maxchar", "Renewal and Duty"},
    {"crisis", "Worlds Collide"},
    {"postcris", "Darkening Skies"},
    {"hearing", "The Hearing"},
    {"getjack", "On a Mexican Radio"},
    {"prelude", "Honor and Justice"},
    {"abase", "A Message Sent"},
    {"effect", "The Other Side"},
    {"uhoh", "Missing in Action"},
    {"prepare", "The Response"},
    {"vision", "Farsighted Eyes"},
    {"maxturns", "Enter the Immortal"},
    {"backlot", "Separate Ways"},
    {"maxside", "The Ancient Runes"},
    {"counter", "The New Initiative"},
    {"warprep", "Ghosts to the World"},
    {"counter1", "A Fate Worse Than Death"},
    {"counter2", "Friendly Fire"},
    {"counter3", "Minor Setback"},
    {"madmax", "Scores to Settle"},
    {"quake", "One Man"},
    {"cthmm", "Shattered Masks"},
    {"shades", "Deal with the Dead"},
    {"gophil", "An Unlikely Hero"},
    {"cstrike", "War in Hell"},
    {"shubset", "The Conspiracy"},
    {"shubdie", "Even Death May Die"},
    {"newranks", "An Empty Throne"},
    {"seal", "The Seal is Broken"}
};
Referenced by M_Demo_Draw(), and M_Demo_Key().
nehahraepisodes
episode_t nehahraepisodes[] static
Initial value:
=
{
    {"Welcome to Nehahra", 0, 1},
    {"The Fall of Forge", 1, 9},
    {"The Outlands", 10, 7},
    {"Dimension of the Lost", 17, 2}
}
Definition at line 3687 of file menu.c.
{
    {"Welcome to Nehahra", 0, 1},
    {"The Fall of Forge", 1, 9},
    {"The Outlands", 10, 7},
    {"Dimension of the Lost", 17, 2}
};
nehahragame
gamelevels_t nehahragame = {"Nehahra", nehahralevels, nehahraepisodes, 4} static
Definition at line 3908 of file menu.c.
{"Nehahra", nehahralevels, nehahraepisodes, 4};
nehahralevels
level_t nehahralevels[] static
Initial value:
=
{
    {"nehstart",    "Welcome to Nehahra"},
    {"neh1m1",  "Forge City1: Slipgates"},
    {"neh1m2",  "Forge City2: Boiler"},
    {"neh1m3",  "Forge City3: Escape"},
    {"neh1m4",  "Grind Core"},
    {"neh1m5",  "Industrial Silence"},
    {"neh1m6",  "Locked-Up Anger"},
    {"neh1m7",  "Wanderer of the Wastes"},
    {"neh1m8",  "Artemis System Net"},
    {"neh1m9",  "To the Death"},
    {"neh2m1",  "The Gates of Ghoro"},
    {"neh2m2",  "Sacred Trinity"},
    {"neh2m3",  "Realm of the Ancients"},
    {"neh2m4",  "Temple of the Ancients"},
    {"neh2m5",  "Dreams Made Flesh"},
    {"neh2m6",  "Your Last Cup of Sorrow"},
    {"nehsec",  "Ogre's Bane"},
    {"nehahra", "Nehahra's Den"},
    {"nehend",  "Quintessence"}
}
Definition at line 3664 of file menu.c.
{
    {"nehstart",    "Welcome to Nehahra"},
    {"neh1m1",  "Forge City1: Slipgates"},
    {"neh1m2",  "Forge City2: Boiler"},
    {"neh1m3",  "Forge City3: Escape"},
    {"neh1m4",  "Grind Core"},
    {"neh1m5",  "Industrial Silence"},
    {"neh1m6",  "Locked-Up Anger"},
    {"neh1m7",  "Wanderer of the Wastes"},
    {"neh1m8",  "Artemis System Net"},
    {"neh1m9",  "To the Death"},
    {"neh2m1",  "The Gates of Ghoro"},
    {"neh2m2",  "Sacred Trinity"},
    {"neh2m3",  "Realm of the Ancients"},
    {"neh2m4",  "Temple of the Ancients"},
    {"neh2m5",  "Dreams Made Flesh"},
    {"neh2m6",  "Your Last Cup of Sorrow"},
    {"nehsec",  "Ogre's Bane"},
    {"nehahra", "Nehahra's Den"},
    {"nehend",  "Quintessence"}
};
NehGameType
int NehGameType static
Definition at line 34 of file menu.c.
Referenced by M_Main_Draw(), M_Main_Key(), and M_Menu_Main_f().
numcommands
int numcommands static
Definition at line 2449 of file menu.c.
Referenced by M_Keys_Draw(), M_Keys_Key(), and M_Menu_Keys_f().
openquartzepisodes
episode_t openquartzepisodes[] static
Initial value:
=
{
    {"Single Player", 0, 1},
    {"Void Deathmatch", 1, 6},
    {"Contrib", 7, 6},
}
Definition at line 3872 of file menu.c.
{
    {"Single Player", 0, 1},
    {"Void Deathmatch", 1, 6},
    {"Contrib", 7, 6},
};
openquartzgame
gamelevels_t openquartzgame = {"OpenQuartz", openquartzlevels, openquartzepisodes, 3} static
Definition at line 3912 of file menu.c.
{"OpenQuartz", openquartzlevels, openquartzepisodes, 3};
openquartzlevels
level_t openquartzlevels[] static
Initial value:
=
{
    {"start", "Welcome to Openquartz"},
    {"void1", "The center of nowhere"},
    {"void2", "The place with no name"},
    {"void3", "The lost supply base"},
    {"void4", "Past the outer limits"},
    {"void5", "Into the nonexistance"},
    {"void6", "Void walk"},
    {"vtest", "Warp Central"},
    {"box", "The deathmatch box"},
    {"bunkers", "Void command"},
    {"house", "House of chaos"},
    {"office", "Overnight office kill"},
    {"am1", "The nameless chambers"},
}
Definition at line 3853 of file menu.c.
{
    {"start", "Welcome to Openquartz"},
    {"void1", "The center of nowhere"},                        // 1
    {"void2", "The place with no name"},
    {"void3", "The lost supply base"},
    {"void4", "Past the outer limits"},
    {"void5", "Into the nonexistance"},
    {"void6", "Void walk"},
    {"vtest", "Warp Central"},
    {"box", "The deathmatch box"},
    {"bunkers", "Void command"},
    {"house", "House of chaos"},
    {"office", "Overnight office kill"},
    {"am1", "The nameless chambers"},
};
options_colorcontrol_cursor
int options_colorcontrol_cursor static
Definition at line 2095 of file menu.c.
Referenced by M_Menu_Options_ColorControl_AdjustSliders(), M_Options_ColorControl_Draw(), and M_Options_ColorControl_Key().
options_cursor
int options_cursor static
Definition at line 1570 of file menu.c.
Referenced by M_Menu_Options_AdjustSliders(), M_Options_Draw(), and M_Options_Key().
options_effects_cursor
int options_effects_cursor static
Definition at line 1802 of file menu.c.
Referenced by M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and M_Options_Effects_Key().
options_graphics_cursor
int options_graphics_cursor static
Definition at line 1965 of file menu.c.
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and M_Options_Graphics_Key().
prydonepisodes
episode_t prydonepisodes[] static
Initial value:
=
{
    {"Prydon Gate", 0, 1},
    {"The Dark Age", 1, 1}
}
Definition at line 3898 of file menu.c.
{
    {"Prydon Gate", 0, 1},
    {"The Dark Age", 1, 1}
};
prydongame
gamelevels_t prydongame = {"Prydon Gate", prydonlevels, prydonepisodes, 2} static
Definition at line 3914 of file menu.c.
{"Prydon Gate", prydonlevels, prydonepisodes, 2};
prydonlevels
level_t prydonlevels[] static
Initial value:
=
{
    {"curig2", "Capel Curig"},
    {"tdastart", "Gateway"},
}
Definition at line 3891 of file menu.c.
{
    {"curig2", "Capel Curig"},  // 0
    {"tdastart", "Gateway"},                // 1
};
quakebindnames
const char* quakebindnames[][2] static
Initial value:
=
{
{"+attack",         "attack"},
{"impulse 10",      "next weapon"},
{"impulse 12",      "previous weapon"},
{"+jump",           "jump / swim up"},
{"+forward",        "walk forward"},
{"+back",           "backpedal"},
{"+left",           "turn left"},
{"+right",          "turn right"},
{"+speed",          "run"},
{"+moveleft",       "step left"},
{"+moveright",      "step right"},
{"+strafe",         "sidestep"},
{"+lookup",         "look up"},
{"+lookdown",       "look down"},
{"centerview",      "center view"},
{"+mlook",          "mouse look"},
{"+klook",          "keyboard look"},
{"+moveup",         "swim up"},
{"+movedown",       "swim down"}
}
Definition at line 2345 of file menu.c.
{
{"+attack",         "attack"},
{"impulse 10",      "next weapon"},
{"impulse 12",      "previous weapon"},
{"+jump",           "jump / swim up"},
{"+forward",        "walk forward"},
{"+back",           "backpedal"},
{"+left",           "turn left"},
{"+right",          "turn right"},
{"+speed",          "run"},
{"+moveleft",       "step left"},
{"+moveright",      "step right"},
{"+strafe",         "sidestep"},
{"+lookup",         "look up"},
{"+lookdown",       "look down"},
{"centerview",      "center view"},
{"+mlook",          "mouse look"},
{"+klook",          "keyboard look"},
{"+moveup",         "swim up"},
{"+movedown",       "swim down"}
};
Referenced by M_Menu_Keys_f().
quakeepisodes
episode_t quakeepisodes[] static
Initial value:
=
{
    {"Welcome to Quake", 0, 1},
    {"Doomed Dimension", 1, 8},
    {"Realm of Black Magic", 9, 7},
    {"Netherworld", 16, 7},
    {"The Elder World", 23, 8},
    {"Final Level", 31, 1},
    {"Deathmatch Arena", 32, 6}
}
Definition at line 3581 of file menu.c.
{
    {"Welcome to Quake", 0, 1},
    {"Doomed Dimension", 1, 8},
    {"Realm of Black Magic", 9, 7},
    {"Netherworld", 16, 7},
    {"The Elder World", 23, 8},
    {"Final Level", 31, 1},
    {"Deathmatch Arena", 32, 6}
};
quakelevels
level_t quakelevels[] static
Definition at line 3533 of file menu.c.
{
    {"start", "Entrance"},  // 0
    {"e1m1", "Slipgate Complex"},               // 1
    {"e1m2", "Castle of the Damned"},
    {"e1m3", "The Necropolis"},
    {"e1m4", "The Grisly Grotto"},
    {"e1m5", "Gloom Keep"},
    {"e1m6", "The Door To Chthon"},
    {"e1m7", "The House of Chthon"},
    {"e1m8", "Ziggurat Vertigo"},
    {"e2m1", "The Installation"},               // 9
    {"e2m2", "Ogre Citadel"},
    {"e2m3", "Crypt of Decay"},
    {"e2m4", "The Ebon Fortress"},
    {"e2m5", "The Wizard's Manse"},
    {"e2m6", "The Dismal Oubliette"},
    {"e2m7", "Underearth"},
    {"e3m1", "Termination Central"},            // 16
    {"e3m2", "The Vaults of Zin"},
    {"e3m3", "The Tomb of Terror"},
    {"e3m4", "Satan's Dark Delight"},
    {"e3m5", "Wind Tunnels"},
    {"e3m6", "Chambers of Torment"},
    {"e3m7", "The Haunted Halls"},
    {"e4m1", "The Sewage System"},              // 23
    {"e4m2", "The Tower of Despair"},
    {"e4m3", "The Elder God Shrine"},
    {"e4m4", "The Palace of Hate"},
    {"e4m5", "Hell's Atrium"},
    {"e4m6", "The Pain Maze"},
    {"e4m7", "Azure Agony"},
    {"e4m8", "The Nameless City"},
    {"end", "Shub-Niggurath's Pit"},            // 31
    {"dm1", "Place of Two Deaths"},             // 32
    {"dm2", "Claustrophobopolis"},
    {"dm3", "The Abandoned Base"},
    {"dm4", "The Bad Place"},
    {"dm5", "The Cistern"},
    {"dm6", "The Dark Zone"}
};
r_bloom
cvar_t r_bloom extern
Definition at line 208 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom", "0", "enables bloom effect (makes bright pixels affect neighboring pixels)"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_Bloom_StartFrame().
r_bloom_blur
cvar_t r_bloom_blur extern
Definition at line 212 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_blur", "4", "how large the glow is"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), R_Bloom_MakeTexture(), and R_Bloom_StartFrame().
r_bloom_brighten
cvar_t r_bloom_brighten extern
Definition at line 211 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_brighten", "1", "how bright the glow is, after subtract/power"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_Bloom_MakeTexture().
r_bloom_colorexponent
cvar_t r_bloom_colorexponent extern
Definition at line 214 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_colorexponent", "1", "how exaggerated the glow is"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_Bloom_MakeTexture().
r_bloom_colorscale
cvar_t r_bloom_colorscale extern
Definition at line 209 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_colorscale", "1", "how bright the glow is"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_Bloom_MakeTexture().
r_bloom_colorsubtract
cvar_t r_bloom_colorsubtract extern
Definition at line 215 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_colorsubtract", "0.1", "reduces bloom colors by a certain amount"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_BlendView().
r_bloom_resolution
cvar_t r_bloom_resolution extern
Definition at line 213 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_bloom_resolution", "320", "what resolution to perform the bloom effect at (independent of screen resolution)"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_Bloom_StartFrame().
r_coronas
cvar_t r_coronas extern
Definition at line 233 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_coronas", "0", "brightness of corona flare effects around certain lights, 0 disables corona effects"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), R_Shadow_DrawCoronas(), and R_Shadow_Init().
r_explosionclip
cvar_t r_explosionclip extern
Definition at line 58 of file r_explosion.c.
{CF_CLIENT | CF_ARCHIVE, "r_explosionclip", "1", "enables collision detection for explosion shell (so that it flattens against walls and floors)"};
Referenced by M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), R_Explosion_Init(), and R_NewExplosion().
r_hdr_glowintensity
cvar_t r_hdr_glowintensity extern
Definition at line 219 of file gl_rmain.c.
{CF_CLIENT | CF_ARCHIVE, "r_hdr_glowintensity", "1", "how bright light emitting textures should appear"};
Referenced by GL_Main_Init(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_SetupShader_Surface().
r_hdr_scenebrightness
cvar_t r_hdr_scenebrightness extern
Definition at line 1987 of file menu.c.
Referenced by GL_Main_Init(), M_Menu_Options_AdjustSliders(), M_Menu_Options_Graphics_AdjustSliders(), M_Options_Draw(), M_Options_Graphics_Draw(), and R_RenderView().
r_lightningbeam_color_blue
cvar_t r_lightningbeam_color_blue extern
Definition at line 10 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_color_blue", "1", "color of the lightning beam effect"};
Referenced by CL_Beam_AddQuad(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_color_green
cvar_t r_lightningbeam_color_green extern
Definition at line 9 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_color_green", "1", "color of the lightning beam effect"};
Referenced by CL_Beam_AddQuad(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_color_red
cvar_t r_lightningbeam_color_red extern
Definition at line 8 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_color_red", "1", "color of the lightning beam effect"};
Referenced by CL_Beam_AddQuad(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_qmbtexture
cvar_t r_lightningbeam_qmbtexture extern
Definition at line 11 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_qmbtexture", "0", "load the qmb textures/particles/lightning.pcx texture instead of generating one, can look better"};
Referenced by CL_Beam_AddPolygons(), CL_Beams_SetupExternalTexture(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_repeatdistance
cvar_t r_lightningbeam_repeatdistance extern
Definition at line 7 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_repeatdistance", "128", "how far to stretch the texture along the lightning beam effect"};
Referenced by CL_Beam_AddPolygons(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_scroll
cvar_t r_lightningbeam_scroll extern
Definition at line 6 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_scroll", "5", "speed of texture scrolling on the lightning beam effect"};
Referenced by CL_Beam_AddPolygons(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_lightningbeam_thickness
cvar_t r_lightningbeam_thickness extern
Definition at line 5 of file r_lightning.c.
{CF_CLIENT | CF_ARCHIVE, "r_lightningbeam_thickness", "8", "thickness of the lightning beam effect"};
Referenced by CL_Beam_AddPolygons(), M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), and R_LightningBeams_Init().
r_shadow_gloss
cvar_t r_shadow_gloss extern
Definition at line 147 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_gloss", "1", "0 disables gloss (specularity) rendering, 1 uses gloss if textures are found, 2 forces a flat metallic specular effect on everything without textures (similar to tenebrae)"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), R_GetCurrentTexture(), and R_SetupShader_DeferredLight().
r_shadow_realtime_dlight
cvar_t r_shadow_realtime_dlight extern
Definition at line 159 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_realtime_dlight", "1", "enables rendering of dynamic lights such as explosions and rocket light"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), R_UpdateVariables(), and R_Water_ProcessPlanes().
r_shadow_realtime_dlight_shadows
cvar_t r_shadow_realtime_dlight_shadows extern
Definition at line 160 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_realtime_dlight_shadows", "1", "enables rendering of shadows from dynamic lights"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_UpdateVariables().
r_shadow_realtime_world
cvar_t r_shadow_realtime_world extern
Definition at line 163 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_realtime_world", "0", "enables rendering of full world lighting (whether loaded from the map, or a .rtlights file, or a .ent file, or a .lights file produced by hlight)"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), R_UpdateVariables(), and R_Water_ProcessPlanes().
r_shadow_realtime_world_lightmaps
cvar_t r_shadow_realtime_world_lightmaps extern
Definition at line 165 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_realtime_world_lightmaps", "0", "brightness to render lightmaps when using full world lighting, try 0.5 for a tenebrae-like appearance"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_UpdateVariables().
r_shadow_realtime_world_shadows
cvar_t r_shadow_realtime_world_shadows extern
Definition at line 166 of file r_shadow.c.
{CF_CLIENT | CF_ARCHIVE, "r_shadow_realtime_world_shadows", "1", "enables rendering of shadows from world lights"};
Referenced by M_Menu_Options_Graphics_AdjustSliders(), M_Options_Graphics_Draw(), and R_UpdateVariables().
r_textshadow
cvar_t r_textshadow extern
Definition at line 53 of file gl_draw.c.
{CF_CLIENT | CF_ARCHIVE, "r_textshadow", "0", "draws a shadow on all text to improve readability (note: value controls offset, 1 = 1 pixel, 1.5 = 1.5 pixels, etc)"};
Referenced by DrawQ_String_Scale(), and GL_Draw_Init().
registeredquakegame
gamelevels_t registeredquakegame = {"Quake", quakelevels, quakeepisodes, 7} static
Definition at line 3905 of file menu.c.
{"Quake", quakelevels, quakeepisodes, 7};
rogueepisodes
episode_t rogueepisodes[] static
Initial value:
=
{
    {"Introduction", 0, 1},
    {"Hell's Fortress", 1, 7},
    {"Corridors of Time", 8, 8},
    {"Deathmatch Arena", 16, 1}
}
Definition at line 3656 of file menu.c.
{
    {"Introduction", 0, 1},
    {"Hell's Fortress", 1, 7},
    {"Corridors of Time", 8, 8},
    {"Deathmatch Arena", 16, 1}
};
roguegame
gamelevels_t roguegame = {"Dissolution of Eternity", roguelevels, rogueepisodes, 4} static
Definition at line 3907 of file menu.c.
{"Dissolution of Eternity", roguelevels, rogueepisodes, 4};
roguelevels
level_t roguelevels[] static
Initial value:
=
{
    {"start",   "Split Decision"},
    {"r1m1",    "Deviant's Domain"},
    {"r1m2",    "Dread Portal"},
    {"r1m3",    "Judgement Call"},
    {"r1m4",    "Cave of Death"},
    {"r1m5",    "Towers of Wrath"},
    {"r1m6",    "Temple of Pain"},
    {"r1m7",    "Tomb of the Overlord"},
    {"r2m1",    "Tempus Fugit"},
    {"r2m2",    "Elemental Fury I"},
    {"r2m3",    "Elemental Fury II"},
    {"r2m4",    "Curse of Osiris"},
    {"r2m5",    "Wizard's Keep"},
    {"r2m6",    "Blood Sacrifice"},
    {"r2m7",    "Last Bastion"},
    {"r2m8",    "Source of Evil"},
    {"ctf1",    "Division of Change"}
}
Definition at line 3633 of file menu.c.
{
    {"start",   "Split Decision"},
    {"r1m1",    "Deviant's Domain"},
    {"r1m2",    "Dread Portal"},
    {"r1m3",    "Judgement Call"},
    {"r1m4",    "Cave of Death"},
    {"r1m5",    "Towers of Wrath"},
    {"r1m6",    "Temple of Pain"},
    {"r1m7",    "Tomb of the Overlord"},
    {"r2m1",    "Tempus Fugit"},
    {"r2m2",    "Elemental Fury I"},
    {"r2m3",    "Elemental Fury II"},
    {"r2m4",    "Curse of Osiris"},
    {"r2m5",    "Wizard's Keep"},
    {"r2m6",    "Blood Sacrifice"},
    {"r2m7",    "Last Bastion"},
    {"r2m8",    "Source of Evil"},
    {"ctf1",    "Division of Change"}
};
serverlist_callbackentry
const serverlist_entry_t* serverlist_callbackentry = NULL
Definition at line 5360 of file menu.c.
Referenced by MP_GetServerListEntryCategory(), VM_M_getserverlistnumber(), and VM_M_getserverliststring().
setup_bottom
int setup_bottom static
Definition at line 1273 of file menu.c.
Referenced by M_Menu_Setup_f(), M_Setup_Draw(), and M_Setup_Key().
setup_cursor
int setup_cursor = 4 static
Definition at line 1266 of file menu.c.
Referenced by M_Setup_Draw(), and M_Setup_Key().
setup_cursor_table
int setup_cursor_table[] = {40, 64, 88, 124, 140} static
Definition at line 1267 of file menu.c.
{40, 64, 88, 124, 140};
Referenced by M_Setup_Draw().
setup_myname
char setup_myname[MAX_SCOREBOARDNAME] static
Definition at line 1269 of file menu.c.
Referenced by M_Menu_Setup_f(), M_Setup_Draw(), and M_Setup_Key().
setup_oldbottom
int setup_oldbottom static
Definition at line 1271 of file menu.c.
Referenced by M_Menu_Setup_f(), and M_Setup_Key().
setup_oldrate
int setup_oldrate static
Definition at line 1275 of file menu.c.
Referenced by M_Setup_Key().
setup_oldtop
int setup_oldtop static
Definition at line 1270 of file menu.c.
Referenced by M_Menu_Setup_f(), and M_Setup_Key().
setup_rate
int setup_rate static
Definition at line 1274 of file menu.c.
Referenced by M_Menu_Setup_f(), M_Setup_Draw(), M_Setup_Key(), and setup_rateindex().
setup_ratetable
ratetable_t setup_ratetable[] static
Initial value:
=
{
    {1000, "28.8 bad"},
    {1500, "28.8 mediocre"},
    {2000, "28.8 good"},
    {2500, "33.6 mediocre"},
    {3000, "33.6 good"},
    {3500, "56k bad"},
    {4000, "56k mediocre"},
    {4500, "56k adequate"},
    {5000, "56k good"},
    {7000, "64k ISDN"},
    {15000, "128k ISDN"},
    {25000, "broadband"}
}
Definition at line 1305 of file menu.c.
{
    {1000, "28.8 bad"},
    {1500, "28.8 mediocre"},
    {2000, "28.8 good"},
    {2500, "33.6 mediocre"},
    {3000, "33.6 good"},
    {3500, "56k bad"},
    {4000, "56k mediocre"},
    {4500, "56k adequate"},
    {5000, "56k good"},
    {7000, "64k ISDN"},
    {15000, "128k ISDN"},
    {25000, "broadband"}
};
Referenced by M_Setup_Draw(), M_Setup_Key(), and setup_rateindex().
setup_top
int setup_top static
Definition at line 1272 of file menu.c.
Referenced by M_Menu_Setup_f(), M_Setup_Draw(), and M_Setup_Key().
sharewarequakegame
gamelevels_t sharewarequakegame = {"Shareware Quake", quakelevels, quakeepisodes, 2} static
Definition at line 3904 of file menu.c.
{"Shareware Quake", quakelevels, quakeepisodes, 2};
slist_cursor
unsigned slist_cursor static
Definition at line 4380 of file menu.c.
Referenced by M_Menu_ServerList_f(), M_ServerList_Draw(), and M_ServerList_Key().
slist_visible
unsigned slist_visible static
Definition at line 4381 of file menu.c.
Referenced by M_ServerList_Draw(), and M_ServerList_Key().
startepisode
int startepisode static
Definition at line 3941 of file menu.c.
Referenced by M_GameOptions_Draw(), M_GameOptions_Key(), and M_NetStart_Change().
startlevel
int startlevel static
Definition at line 3942 of file menu.c.
Referenced by M_GameOptions_Draw(), M_GameOptions_Key(), and M_NetStart_Change().
transfusionbindnames
const char* transfusionbindnames[][2] static
Definition at line 2368 of file menu.c.
{
{"",                "Movement"},        // Movement commands
{"+forward",        "walk forward"},
{"+back",           "backpedal"},
{"+left",           "turn left"},
{"+right",          "turn right"},
{"+moveleft",       "step left"},
{"+moveright",      "step right"},
{"+jump",           "jump / swim up"},
{"+movedown",       "swim down"},
{"",                "Combat"},          // Combat commands
{"impulse 1",       "Pitch Fork"},
{"impulse 2",       "Flare Gun"},
{"impulse 3",       "Shotgun"},
{"impulse 4",       "Machine Gun"},
{"impulse 5",       "Incinerator"},
{"impulse 6",       "Bombs (TNT)"},
{"impulse 35",      "Proximity Bomb"},
{"impulse 36",      "Remote Detonator"},
{"impulse 7",       "Aerosol Can"},
{"impulse 8",       "Tesla Cannon"},
{"impulse 9",       "Life Leech"},
{"impulse 10",      "Voodoo Doll"},
{"impulse 21",      "next weapon"},
{"impulse 22",      "previous weapon"},
{"+attack",         "attack"},
{"+button3",        "altfire"},
{"",                "Inventory"},       // Inventory commands
{"impulse 40",      "Dr.'s Bag"},
{"impulse 41",      "Crystal Ball"},
{"impulse 42",      "Beast Vision"},
{"impulse 43",      "Jump Boots"},
{"impulse 23",      "next item"},
{"impulse 24",      "previous item"},
{"impulse 25",      "use item"},
{"",                "Misc"},            // Misc commands
{"+button4",        "use"},
{"impulse 50",      "add bot (red)"},
{"impulse 51",      "add bot (blue)"},
{"impulse 52",      "kick a bot"},
{"impulse 26",      "next armor type"},
{"impulse 27",      "identify player"},
{"impulse 55",      "voting menu"},
{"impulse 56",      "observer mode"},
{"",                "Taunts"},            // Taunts
{"impulse 70",      "taunt 0"},
{"impulse 71",      "taunt 1"},
{"impulse 72",      "taunt 2"},
{"impulse 73",      "taunt 3"},
{"impulse 74",      "taunt 4"},
{"impulse 75",      "taunt 5"},
{"impulse 76",      "taunt 6"},
{"impulse 77",      "taunt 7"},
{"impulse 78",      "taunt 8"},
{"impulse 79",      "taunt 9"}
};
Referenced by M_Menu_Keys_f().
transfusionepisodes
episode_t transfusionepisodes[] static
Initial value:
=
{
    {"The Way of All Flesh", 0, 8},
    {"Even Death May Die", 8, 9},
    {"Farewell to Arms", 17, 8},
    {"Dead Reckoning", 25, 9},
    {"BloodBath", 34, 11},
    {"Post Mortem", 45, 9},
    {"Cryptic Passage", 54, 10},
    {"Cryptic BloodBath", 64, 4},
    {"Blood 2", 68, 8},
    {"Transfusion", 76, 9},
    {"Conversions", 85, 9}
}
Definition at line 3804 of file menu.c.
{
    {"The Way of All Flesh", 0, 8},
    {"Even Death May Die", 8, 9},
    {"Farewell to Arms", 17, 8},
    {"Dead Reckoning", 25, 9},
    {"BloodBath", 34, 11},
    {"Post Mortem", 45, 9},
    {"Cryptic Passage", 54, 10},
    {"Cryptic BloodBath", 64, 4},
    {"Blood 2", 68, 8},
    {"Transfusion", 76, 9},
    {"Conversions", 85, 9}
};
transfusiongame
gamelevels_t transfusiongame = {"Transfusion", transfusionlevels, transfusionepisodes, 11} static
Definition at line 3909 of file menu.c.
{"Transfusion", transfusionlevels, transfusionepisodes, 11};
transfusionlevels
level_t transfusionlevels[] static
Definition at line 3696 of file menu.c.
{
    {"e1m1",        "Cradle to Grave"},
    {"e1m2",        "Wrong Side of the Tracks"},
    {"e1m3",        "Phantom Express"},
    {"e1m4",        "Dark Carnival"},
    {"e1m5",        "Hallowed Grounds"},
    {"e1m6",        "The Great Temple"},
    {"e1m7",        "Altar of Stone"},
    {"e1m8",        "House of Horrors"},
    {"e2m1",        "Shipwrecked"},
    {"e2m2",        "The Lumber Mill"},
    {"e2m3",        "Rest for the Wicked"},
    {"e2m4",        "The Overlooked Hotel"},
    {"e2m5",        "The Haunting"},
    {"e2m6",        "The Cold Rush"},
    {"e2m7",        "Bowels of the Earth"},
    {"e2m8",        "The Lair of Shial"},
    {"e2m9",        "Thin Ice"},
    {"e3m1",        "Ghost Town"},
    {"e3m2",        "The Siege"},
    {"e3m3",        "Raw Sewage"},
    {"e3m4",        "The Sick Ward"},
    {"e3m5",        "Spare Parts"},
    {"e3m6",        "Monster Bait"},
    {"e3m7",        "The Pit of Cerberus"},
    {"e3m8",        "Catacombs"},
    {"e4m1",        "Butchery Loves Company"},
    {"e4m2",        "Breeding Grounds"},
    {"e4m3",        "Charnel House"},
    {"e4m4",        "Crystal Lake"},
    {"e4m5",        "Fire and Brimstone"},
    {"e4m6",        "The Ganglion Depths"},
    {"e4m7",        "In the Flesh"},
    {"e4m8",        "The Hall of the Epiphany"},
    {"e4m9",        "Mall of the Dead"},
    {"bb1",         "The Stronghold"},
    {"bb2",         "Winter Wonderland"},
    {"bb3",         "Bodies"},
    {"bb4",         "The Tower"},
    {"bb5",         "Click!"},
    {"bb6",         "Twin Fortress"},
    {"bb7",         "Midgard"},
    {"bb8",         "Fun With Heads"},
    {"dm1",         "Monolith Building 11"},
    {"dm2",         "Power!"},
    {"dm3",         "Area 15"},
    {"e6m1",        "Welcome to Your Life"},
    {"e6m2",        "They Are Here"},
    {"e6m3",        "Public Storage"},
    {"e6m4",        "Aqueducts"},
    {"e6m5",        "The Ruined Temple"},
    {"e6m6",        "Forbidden Rituals"},
    {"e6m7",        "The Dungeon"},
    {"e6m8",        "Beauty and the Beast"},
    {"e6m9",        "Forgotten Catacombs"},
    {"cp01",        "Boat Docks"},
    {"cp02",        "Old Opera House"},
    {"cp03",        "Gothic Library"},
    {"cp04",        "Lost Monastery"},
    {"cp05",        "Steamboat"},
    {"cp06",        "Graveyard"},
    {"cp07",        "Mountain Pass"},
    {"cp08",        "Abysmal Mine"},
    {"cp09",        "Castle"},
    {"cps1",        "Boggy Creek"},
    {"cpbb01",      "Crypt of Despair"},
    {"cpbb02",      "Pits of Blood"},
    {"cpbb03",      "Unholy Cathedral"},
    {"cpbb04",      "Deadly Inspirations"},
    {"b2a15",       "Area 15 (B2)"},
    {"b2bodies",    "BB_Bodies (B2)"},
    {"b2cabana",    "BB_Cabana"},
    {"b2power",     "BB_Power"},
    {"barena",      "Blood Arena"},
    {"bkeep",       "Blood Keep"},
    {"bstar",       "Brown Star"},
    {"crypt",       "The Crypt"},
    {"bb3_2k1",     "Bodies Infusion"},
    {"captasao",    "Captasao"},
    {"curandero",   "Curandero"},
    {"dcamp",       "DeathCamp"},
    {"highnoon",    "HighNoon"},
    {"qbb1",        "The Confluence"},
    {"qbb2",        "KathartiK"},
    {"qbb3",        "Caleb's Woodland Retreat"},
    {"zoo",         "Zoo"},
    {"dranzbb6",    "Black Coffee"},
    {"fragm",       "Frag'M"},
    {"maim",        "Maim"},
    {"qe1m7",       "The House of Chthon"},
    {"qdm1",        "Place of Two Deaths"},
    {"qdm4",        "The Bad Place"},
    {"qdm5",        "The Cistern"},
    {"qmorbias",    "DM-Morbias"},
    {"simple",      "Dead Simple"}
};
video_cursor
int video_cursor = 0 static
Definition at line 2834 of file menu.c.
Referenced by M_Menu_Video_AdjustSliders(), M_Video_Draw(), and M_Video_Key().
video_cursor_table
int video_cursor_table[VIDEO_ITEMS] = {68, 88, 96, 104, 112, 120, 128, 136, 144, 152} static
Definition at line 2835 of file menu.c.
{68, 88, 96, 104, 112, 120, 128, 136, 144, 152};
Referenced by M_Video_Draw().
video_resolutions
video_resolution_t* video_resolutions
Definition at line 2838 of file menu.c.
Referenced by M_Menu_Video_FindResolution(), MR_Init(), and VM_M_getresolution().
video_resolutions_count
int video_resolutions_count
Definition at line 2839 of file menu.c.
Referenced by M_Menu_Video_FindResolution(), MR_Init(), and VM_M_getresolution().
video_resolutions_hardcoded
video_resolution_t video_resolutions_hardcoded[]
Definition at line 2770 of file menu.c.
{
{"Standard 4x3"              ,  320, 240, 320, 240, 1     },
{"Standard 4x3"              ,  400, 300, 400, 300, 1     },
{"Standard 4x3"              ,  512, 384, 512, 384, 1     },
{"Standard 4x3"              ,  640, 480, 640, 480, 1     },
{"Standard 4x3"              ,  800, 600, 640, 480, 1     },
{"Standard 4x3"              , 1024, 768, 640, 480, 1     },
{"Standard 4x3"              , 1152, 864, 640, 480, 1     },
{"Standard 4x3"              , 1280, 960, 640, 480, 1     },
{"Standard 4x3"              , 1400,1050, 640, 480, 1     },
{"Standard 4x3"              , 1600,1200, 640, 480, 1     },
{"Standard 4x3"              , 1792,1344, 640, 480, 1     },
{"Standard 4x3"              , 1856,1392, 640, 480, 1     },
{"Standard 4x3"              , 1920,1440, 640, 480, 1     },
{"Standard 4x3"              , 2048,1536, 640, 480, 1     },
{"Short Pixel (CRT) 5x4"     ,  320, 256, 320, 256, 0.9375},
{"Short Pixel (CRT) 5x4"     ,  640, 512, 640, 512, 0.9375},
{"Short Pixel (CRT) 5x4"     , 1280,1024, 640, 512, 0.9375},
{"Tall Pixel (CRT) 8x5"      ,  320, 200, 320, 200, 1.2   },
{"Tall Pixel (CRT) 8x5"      ,  640, 400, 640, 400, 1.2   },
{"Tall Pixel (CRT) 8x5"      ,  840, 525, 640, 400, 1.2   },
{"Tall Pixel (CRT) 8x5"      ,  960, 600, 640, 400, 1.2   },
{"Tall Pixel (CRT) 8x5"      , 1680,1050, 640, 400, 1.2   },
{"Tall Pixel (CRT) 8x5"      , 1920,1200, 640, 400, 1.2   },
{"Square Pixel (LCD) 5x4"    ,  320, 256, 320, 256, 1     },
{"Square Pixel (LCD) 5x4"    ,  640, 512, 640, 512, 1     },
{"Square Pixel (LCD) 5x4"    , 1280,1024, 640, 512, 1     },
{"WideScreen 5x3"            ,  640, 384, 640, 384, 1     },
{"WideScreen 5x3"            , 1280, 768, 640, 384, 1     },
{"WideScreen 8x5"            ,  320, 200, 320, 200, 1     },
{"WideScreen 8x5"            ,  640, 400, 640, 400, 1     },
{"WideScreen 8x5"            ,  720, 450, 720, 450, 1     },
{"WideScreen 8x5"            ,  840, 525, 640, 400, 1     },
{"WideScreen 8x5"            ,  960, 600, 640, 400, 1     },
{"WideScreen 8x5"            , 1280, 800, 640, 400, 1     },
{"WideScreen 8x5"            , 1440, 900, 720, 450, 1     },
{"WideScreen 8x5"            , 1680,1050, 640, 400, 1     },
{"WideScreen 8x5"            , 1920,1200, 640, 400, 1     },
{"WideScreen 8x5"            , 2560,1600, 640, 400, 1     },
{"WideScreen 8x5"            , 3840,2400, 640, 400, 1     },
{"WideScreen 14x9"           ,  840, 540, 640, 400, 1     },
{"WideScreen 14x9"           , 1680,1080, 640, 400, 1     },
{"WideScreen 16x9"           ,  640, 360, 640, 360, 1     },
{"WideScreen 16x9"           ,  683, 384, 683, 384, 1     },
{"WideScreen 16x9"           ,  960, 540, 640, 360, 1     },
{"WideScreen 16x9"           , 1280, 720, 640, 360, 1     },
{"WideScreen 16x9"           , 1360, 768, 680, 384, 1     },
{"WideScreen 16x9"           , 1366, 768, 683, 384, 1     },
{"WideScreen 16x9"           , 1920,1080, 640, 360, 1     },
{"WideScreen 16x9"           , 2560,1440, 640, 360, 1     },
{"WideScreen 16x9"           , 3840,2160, 640, 360, 1     },
{"NTSC 3x2"                  ,  360, 240, 360, 240, 1.125 },
{"NTSC 3x2"                  ,  720, 480, 720, 480, 1.125 },
{"PAL 14x11"                 ,  360, 283, 360, 283, 0.9545},
{"PAL 14x11"                 ,  720, 566, 720, 566, 0.9545},
{"NES 8x7"                   ,  256, 224, 256, 224, 1.1667},
{"SNES 8x7"                  ,  512, 448, 512, 448, 1.1667},
{NULL, 0, 0, 0, 0, 0}
};
Referenced by M_Menu_Video_FindResolution(), MR_Init(), and VM_M_getresolution().
video_resolutions_hardcoded_count
int video_resolutions_hardcoded_count = sizeof(video_resolutions_hardcoded) / sizeof(*video_resolutions_hardcoded) - 1
Definition at line 2831 of file menu.c.
Referenced by M_Menu_Video_FindResolution(), and VM_M_getresolution().
wasInMenus
qbool wasInMenus static
Definition at line 3163 of file menu.c.
Referenced by M_Menu_Quit_f(), and M_Quit_Key().