var model__hlmdl_8h =
[
    [ "dhlmdl_header_t", "structdhlmdl__header__t.html", "structdhlmdl__header__t" ],
    [ "dhlmdl_sequence_header_t", "structdhlmdl__sequence__header__t.html", "structdhlmdl__sequence__header__t" ],
    [ "dhlmdl_texture_t", "structdhlmdl__texture__t.html", "structdhlmdl__texture__t" ],
    [ "dhlmdl_bone_t", "structdhlmdl__bone__t.html", "structdhlmdl__bone__t" ],
    [ "dhlmdl_bone_controller_t", "structdhlmdl__bone__controller__t.html", "structdhlmdl__bone__controller__t" ],
    [ "dhlmdl_hitbox_t", "structdhlmdl__hitbox__t.html", "structdhlmdl__hitbox__t" ],
    [ "dhlmdl_sequence_group_t", "structdhlmdl__sequence__group__t.html", "structdhlmdl__sequence__group__t" ],
    [ "dhlmdl_sequence_description_t", "structdhlmdl__sequence__description__t.html", "structdhlmdl__sequence__description__t" ],
    [ "dhlmdl_animvalue_t", "uniondhlmdl__animvalue__t.html", "uniondhlmdl__animvalue__t" ],
    [ "dhlmdl_animevent_t", "structdhlmdl__animevent__t.html", "structdhlmdl__animevent__t" ],
    [ "dhlmdl_attachment_t", "structdhlmdl__attachment__t.html", "structdhlmdl__attachment__t" ],
    [ "dhlmdl_bodypart_t", "structdhlmdl__bodypart__t.html", "structdhlmdl__bodypart__t" ],
    [ "dhlmdl_t", "structdhlmdl__t.html", "structdhlmdl__t" ],
    [ "dhlmdl_mesh_t", "structdhlmdl__mesh__t.html", "structdhlmdl__mesh__t" ],
    [ "dhlmdl_trivert_t", "structdhlmdl__trivert__t.html", "structdhlmdl__trivert__t" ],
    [ "HLMDLFLAG_CHROME", "model__hlmdl_8h.html#aedd5f13d25ba0c0b473794f8a64d4b34", null ],
    [ "HLMDLFLAG_FLAT", "model__hlmdl_8h.html#a3c00450b7f7abd26e8aa37a8deffa12b", null ],
    [ "HLMDLFLAG_FULLBRIGHT", "model__hlmdl_8h.html#affdd0c9652937f6dcf5117bade18d061", null ],
    [ "HLMDLHEADER", "model__hlmdl_8h.html#a5de4d6390e29718437419fdb3580d16f", null ],
    [ "HLPOLYHEADER", "model__hlmdl_8h.html#aae802c3c780a8f19c2326456f9ad61c6", null ],
    [ "HLSEQHEADER", "model__hlmdl_8h.html#abb3117bab2f4ebe4d5eace4f184d3a87", null ],
    [ "dhlmdl_animoffset_t", "model__hlmdl_8h.html#a488ec0e8e6135574867fa95216edbe8b", null ]
];