DarkPlaces: progsvm.h File Reference
progsvm.h File Reference
#include <stddef.h>
#include "qtypes.h"
#include "qdefs.h"
#include "common.h"
#include "zone.h"
#include "pr_comp.h"
#include "progdefs.h"
#include "clprogdefs.h"
#include "prvm_offsets.h"
Data Structures
struct prvm_stack_t
union prvm_eval_t
struct prvm_required_field_t
struct prvm_edict_private_t
struct prvm_edict_t
struct prvm_prog_fieldoffsets_t
struct prvm_prog_globaloffsets_t
struct prvm_prog_funcoffsets_t
struct prvm_stringbuffer_t
struct prvm_prog_garbagecollection_state_t
struct prvm_prog_t
Macros
#define PROFILING
#define PRVM_EDICT_MARK_WAIT_FOR_SETORIGIN -1
#define PRVM_EDICT_MARK_SETORIGIN_CAUGHT -2
#define PRVM_alledictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_alledictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_alledictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_alledictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_alledictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_allglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_allglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_allglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_allglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_allglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_allfunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_drawedictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_drawedictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_drawedictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_drawedictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_drawedictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_drawglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_drawglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_drawglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_drawglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_drawglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_drawfunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_gameedictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_gameedictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_gameedictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_gameedictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_gameedictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_gameglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_gameglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_gameglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_gameglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_gameglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_gamefunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_serveredictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_serveredictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_serveredictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_serveredictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_serveredictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_serverglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_serverglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_serverglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_serverglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_serverglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_serverfunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_clientedictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_clientedictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_clientedictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_clientedictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_clientedictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_clientglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_clientglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_clientglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_clientglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_clientglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_clientfunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_menuedictfloat(ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
#define PRVM_menuedictvector(ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
#define PRVM_menuedictstring(ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
#define PRVM_menuedictedict(ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
#define PRVM_menuedictfunction(ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
#define PRVM_menuglobalfloat(fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
#define PRVM_menuglobalvector(fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
#define PRVM_menuglobalstring(fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
#define PRVM_menuglobaledict(fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
#define PRVM_menuglobalfunction(fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
#define PRVM_menufunction(funcname) (prog->funcoffsets.funcname)
#define PRVM_EDICTFIELDVALUE(ed, fieldoffset) ((fieldoffset) < 0 ? Con_Printf("Invalid fieldoffset at %s:%i\n", __FILE__, __LINE__), &prvm_badvalue : (prvm_eval_t *)((ed)->fields.fp + (fieldoffset)))
#define PRVM_EDICTFIELDFLOAT(ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->_float)
#define PRVM_EDICTFIELDVECTOR(ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->vector)
#define PRVM_EDICTFIELDSTRING(ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->string)
#define PRVM_EDICTFIELDEDICT(ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->edict)
#define PRVM_EDICTFIELDFUNCTION(ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->function)
#define PRVM_GLOBALFIELDVALUE(fieldoffset) ((fieldoffset) < 0 ? Con_Printf("Invalid fieldoffset at %s:%i\n", __FILE__, __LINE__), &prvm_badvalue : (prvm_eval_t *)(prog->globals.fp + (fieldoffset)))
#define PRVM_GLOBALFIELDFLOAT(fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->_float)
#define PRVM_GLOBALFIELDVECTOR(fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->vector)
#define PRVM_GLOBALFIELDSTRING(fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->string)
#define PRVM_GLOBALFIELDEDICT(fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->edict)
#define PRVM_GLOBALFIELDFUNCTION(fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->function)
#define PRVM_OP_STATE 1
#define PRVM_MAX_STACK_DEPTH 1024
#define PRVM_LOCALSTACK_SIZE 16384
#define PRVM_MAX_OPENFILES 256
#define PRVM_MAX_OPENSEARCHES 128
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x)
#define PRVM_DECLARE_menuglobalvector(x)
#define PRVM_DECLARE_menuglobalstring(x)
#define PRVM_DECLARE_menuglobaledict(x)
#define PRVM_DECLARE_menuglobalfunction(x)
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x)
#define PRVM_DECLARE_menufieldvector(x)
#define PRVM_DECLARE_menufieldstring(x)
#define PRVM_DECLARE_menufieldedict(x)
#define PRVM_DECLARE_menufieldfunction(x)
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x) int x;
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x)
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x)
#define PRVM_DECLARE_menuglobalvector(x)
#define PRVM_DECLARE_menuglobalstring(x)
#define PRVM_DECLARE_menuglobaledict(x)
#define PRVM_DECLARE_menuglobalfunction(x)
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x)
#define PRVM_DECLARE_menufieldvector(x)
#define PRVM_DECLARE_menufieldstring(x)
#define PRVM_DECLARE_menufieldedict(x)
#define PRVM_DECLARE_menufieldfunction(x)
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x) int x;
#define PRVM_DECLARE_function(x)
#define PRVM_DECLARE_serverglobalfloat(x)
#define PRVM_DECLARE_serverglobalvector(x)
#define PRVM_DECLARE_serverglobalstring(x)
#define PRVM_DECLARE_serverglobaledict(x)
#define PRVM_DECLARE_serverglobalfunction(x)
#define PRVM_DECLARE_clientglobalfloat(x)
#define PRVM_DECLARE_clientglobalvector(x)
#define PRVM_DECLARE_clientglobalstring(x)
#define PRVM_DECLARE_clientglobaledict(x)
#define PRVM_DECLARE_clientglobalfunction(x)
#define PRVM_DECLARE_menuglobalfloat(x)
#define PRVM_DECLARE_menuglobalvector(x)
#define PRVM_DECLARE_menuglobalstring(x)
#define PRVM_DECLARE_menuglobaledict(x)
#define PRVM_DECLARE_menuglobalfunction(x)
#define PRVM_DECLARE_serverfieldfloat(x)
#define PRVM_DECLARE_serverfieldvector(x)
#define PRVM_DECLARE_serverfieldstring(x)
#define PRVM_DECLARE_serverfieldedict(x)
#define PRVM_DECLARE_serverfieldfunction(x)
#define PRVM_DECLARE_clientfieldfloat(x)
#define PRVM_DECLARE_clientfieldvector(x)
#define PRVM_DECLARE_clientfieldstring(x)
#define PRVM_DECLARE_clientfieldedict(x)
#define PRVM_DECLARE_clientfieldfunction(x)
#define PRVM_DECLARE_menufieldfloat(x)
#define PRVM_DECLARE_menufieldvector(x)
#define PRVM_DECLARE_menufieldstring(x)
#define PRVM_DECLARE_menufieldedict(x)
#define PRVM_DECLARE_menufieldfunction(x)
#define PRVM_DECLARE_serverfunction(x)
#define PRVM_DECLARE_clientfunction(x)
#define PRVM_DECLARE_menufunction(x)
#define PRVM_DECLARE_field(x)
#define PRVM_DECLARE_global(x)
#define PRVM_DECLARE_function(x) int x;
#define STRINGBUFFER_SAVED 1
#define STRINGBUFFER_QCFLAGS 1
#define STRINGBUFFER_TEMP 128
#define KNOWNSTRINGFLAG_ENGINE 1
#define KNOWNSTRINGFLAG_GCMARK 2
#define KNOWNSTRINGFLAG_GCPRUNE 4
#define PRVM_GetProg(n) (&prvm_prog_list[(n)])
#define PRVM_ProgLoaded(n) (PRVM_GetProg(n)->loaded)
#define SVVM_prog (&prvm_prog_list[PRVM_PROG_SERVER])
#define CLVM_prog (&prvm_prog_list[PRVM_PROG_CLIENT])
#define PRVM_Alloc(buffersize) Mem_Alloc(prog->progs_mempool, buffersize)
#define PRVM_Free(buffer) Mem_Free(buffer)
#define PRVM_ED_FindFieldOffset_FromStruct(st, field) prog->fieldoffsets . field = ((int *)(&((st *)NULL)-> field) - ((int *)NULL))
#define PRVM_ED_FindGlobalOffset_FromStruct(st, field) prog->globaloffsets . field = ((int *)(&((st *)NULL)-> field) - ((int *)NULL))
#define PRVM_EDICT(n) (((unsigned)(n) < (unsigned int)prog->max_edicts) ? (unsigned int)(n) : PRVM_EDICT_NUM_ERROR(prog, (unsigned int)(n), __FILE__, __LINE__))
#define PRVM_EDICT_NUM(n) (prog->edicts + PRVM_EDICT(n))
#define PRVM_NUM_FOR_EDICT(e) ((int)((prvm_edict_t *)(e) - prog->edicts))
#define PRVM_NEXT_EDICT(e) ((e) + 1)
#define PRVM_EDICT_TO_PROG(e) (PRVM_NUM_FOR_EDICT(e))
#define PRVM_PROG_TO_EDICT(n) (PRVM_EDICT_NUM(n))
#define PRVM_G_FLOAT(o) (prog->globals.fp[o])
#define PRVM_G_INT(o) (prog->globals.ip[o])
#define PRVM_G_EDICT(o) (PRVM_PROG_TO_EDICT(prog->globals.ip[o]))
#define PRVM_G_EDICTNUM(o) PRVM_NUM_FOR_EDICT(PRVM_G_EDICT(o))
#define PRVM_G_VECTOR(o) (&prog->globals.fp[o])
#define PRVM_G_STRING(o) (PRVM_GetString(prog, prog->globals.ip[o]))
#define PRVM_E_FLOAT(e, o) (e->fields.fp[o])
#define PRVM_E_INT(e, o) (e->fields.ip[o])
#define PRVM_E_STRING(e, o) (PRVM_GetString(prog, e->fields.ip[o]))
Typedefs
typedef void(* prvm_builtin_t) (struct prvm_prog_s *prog)
Enumerations
enum prvm_prog_garbagecollection_state_stage_t {
PRVM_GC_START = 0 , PRVM_GC_GLOBALS_MARK , PRVM_GC_FIELDS_MARK , PRVM_GC_KNOWNSTRINGS_SWEEP ,
PRVM_GC_RESET
}
enum prvm_progindex_t { PRVM_PROG_SERVER , PRVM_PROG_CLIENT , PRVM_PROG_MENU , PRVM_PROG_MAX }
Functions
prvm_prog_t * PRVM_ProgFromString (const char *str)
prvm_prog_t * PRVM_FriendlyProgFromString (const char *str)
void SVVM_init_cmd (prvm_prog_t *prog)
void SVVM_reset_cmd (prvm_prog_t *prog)
void CLVM_init_cmd (prvm_prog_t *prog)
void CLVM_reset_cmd (prvm_prog_t *prog)
void VM_Cmd_Init (prvm_prog_t *prog)
void VM_Cmd_Reset (prvm_prog_t *prog)
void PRVM_Init (void)
void SVVM_ExecuteProgram (prvm_prog_t *prog, func_t fnum, const char *errormessage)
void CLVM_ExecuteProgram (prvm_prog_t *prog, func_t fnum, const char *errormessage)
void PRVM_Profile (prvm_prog_t *prog, int maxfunctions, double mintime, int sortby)
void PRVM_Profile_f (struct cmd_state_s *cmd)
void PRVM_ChildProfile_f (struct cmd_state_s *cmd)
void PRVM_CallProfile_f (struct cmd_state_s *cmd)
void PRVM_PrintFunction_f (struct cmd_state_s *cmd)
void PRVM_PrintState (prvm_prog_t *prog, int stack_index)
void PRVM_Crash (void)
void PRVM_ShortStackTrace (prvm_prog_t *prog, char *buf, size_t bufsize)
const char * PRVM_AllocationOrigin (prvm_prog_t *prog)
void PRVM_GarbageCollection (prvm_prog_t *prog)
mdef_t * PRVM_ED_FindField (prvm_prog_t *prog, const char *name)
mdef_t * PRVM_ED_FindGlobal (prvm_prog_t *prog, const char *name)
prvm_eval_t * PRVM_ED_FindGlobalEval (prvm_prog_t *prog, const char *name)
mfunction_t * PRVM_ED_FindFunction (prvm_prog_t *prog, const char *name)
int PRVM_ED_FindFieldOffset (prvm_prog_t *prog, const char *name)
int PRVM_ED_FindGlobalOffset (prvm_prog_t *prog, const char *name)
func_t PRVM_ED_FindFunctionOffset (prvm_prog_t *prog, const char *name)
void PRVM_MEM_IncreaseEdicts (prvm_prog_t *prog)
qbool PRVM_ED_CanAlloc (prvm_prog_t *prog, prvm_edict_t *e)
prvm_edict_t * PRVM_ED_Alloc (prvm_prog_t *prog)
void PRVM_ED_Free (prvm_prog_t *prog, prvm_edict_t *ed)
void PRVM_ED_ClearEdict (prvm_prog_t *prog, prvm_edict_t *e)
void PRVM_PrintFunctionStatements (prvm_prog_t *prog, const char *name)
void PRVM_ED_Print (prvm_prog_t *prog, prvm_edict_t *ed, const char *wildcard_fieldname)
void PRVM_ED_Write (prvm_prog_t *prog, struct qfile_s *f, prvm_edict_t *ed)
const char * PRVM_ED_ParseEdict (prvm_prog_t *prog, const char *data, prvm_edict_t *ent)
void PRVM_ED_WriteGlobals (prvm_prog_t *prog, struct qfile_s *f)
void PRVM_ED_ParseGlobals (prvm_prog_t *prog, const char *data)
void PRVM_ED_CallPrespawnFunction (prvm_prog_t *prog, prvm_edict_t *ent)
qbool PRVM_ED_CallSpawnFunction (prvm_prog_t *prog, prvm_edict_t *ent, const char *data, const char *start)
void PRVM_ED_CallPostspawnFunction (prvm_prog_t *prog, prvm_edict_t *ent)
void PRVM_ED_LoadFromFile (prvm_prog_t *prog, const char *data)
unsigned int PRVM_EDICT_NUM_ERROR (prvm_prog_t *prog, unsigned int n, const char *filename, int fileline)
void PRVM_Init_Exec (prvm_prog_t *prog)
void PRVM_ED_PrintEdicts_f (struct cmd_state_s *cmd)
void PRVM_ED_PrintNum (prvm_prog_t *prog, int ent, const char *wildcard_fieldname)
const char * PRVM_GetString (prvm_prog_t *prog, int num)
int PRVM_SetEngineString (prvm_prog_t *prog, const char *s)
const char * PRVM_ChangeEngineString (prvm_prog_t *prog, int i, const char *s)
int PRVM_SetTempString (prvm_prog_t *prog, const char *s, size_t slen)
Takes an strlen (not a buffer size).
int PRVM_AllocString (prvm_prog_t *prog, size_t bufferlength, char **pointer)
void PRVM_FreeString (prvm_prog_t *prog, int num)
mdef_t * PRVM_ED_FieldAtOfs (prvm_prog_t *prog, unsigned int ofs)
qbool PRVM_ED_ParseEpair (prvm_prog_t *prog, prvm_edict_t *ent, mdef_t *key, const char *s, qbool parsebackslash)
char * PRVM_UglyValueString (prvm_prog_t *prog, etype_t type, prvm_eval_t *val, char *line, size_t linelength)
char * PRVM_GlobalString (prvm_prog_t *prog, int ofs, char *line, size_t linelength)
char * PRVM_GlobalStringNoContents (prvm_prog_t *prog, int ofs, char *line, size_t linelength)
void PRVM_Prog_Init (prvm_prog_t *prog, struct cmd_state_s *cmd)
void PRVM_Prog_Load (prvm_prog_t *prog, const char *filename, unsigned char *data, int64_t size, int numrequiredfunc, const char **required_func, int numrequiredfields, prvm_required_field_t *required_field, int numrequiredglobals, prvm_required_field_t *required_global)
void PRVM_Prog_Reset (prvm_prog_t *prog)
void PRVM_StackTrace (prvm_prog_t *prog)
void PRVM_Breakpoint (prvm_prog_t *prog, int stack_index, const char *text)
void PRVM_Watchpoint (prvm_prog_t *prog, int stack_index, const char *text, etype_t type, prvm_eval_t *o, prvm_eval_t *n)
void VM_Warning (prvm_prog_t *prog, const char *fmt,...) DP_FUNC_PRINTF(2)
void VM_GenerateFrameGroupBlend (prvm_prog_t *prog, struct framegroupblend_s *framegroupblend, const prvm_edict_t *ed)
void VM_FrameBlendFromFrameGroupBlend (struct frameblend_s *frameblend, const struct framegroupblend_s *framegroupblend, const struct model_s *model, double curtime)
void VM_UpdateEdictSkeleton (prvm_prog_t *prog, prvm_edict_t *ed, const struct model_s *edmodel, const struct frameblend_s *frameblend)
void VM_RemoveEdictSkeleton (prvm_prog_t *prog, prvm_edict_t *ed)
void PRVM_ExplicitCoverageEvent (prvm_prog_t *prog, mfunction_t *func, int statement)
Variables
prvm_eval_t prvm_badvalue
prvm_prog_t prvm_prog_list [PRVM_PROG_MAX]
prvm_builtin_t vm_sv_builtins []
prvm_builtin_t vm_cl_builtins []
prvm_builtin_t vm_m_builtins []
const int vm_sv_numbuiltins
const int vm_cl_numbuiltins
const int vm_m_numbuiltins
const char * vm_sv_extensions []
const char * vm_m_extensions []
int prvm_type_size [8]
Macro Definition Documentation
CLVM_prog
#define CLVM_prog (&prvm_prog_list[PRVM_PROG_CLIENT])
Definition at line 764 of file progsvm.h.
KNOWNSTRINGFLAG_ENGINE
#define KNOWNSTRINGFLAG_ENGINE 1
Definition at line 507 of file progsvm.h.
KNOWNSTRINGFLAG_GCMARK
#define KNOWNSTRINGFLAG_GCMARK 2
Definition at line 508 of file progsvm.h.
KNOWNSTRINGFLAG_GCPRUNE
#define KNOWNSTRINGFLAG_GCPRUNE 4
Definition at line 509 of file progsvm.h.
PROFILING
#define PROFILING
Definition at line 47 of file progsvm.h.
PRVM_alledictedict
#define PRVM_alledictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 138 of file progsvm.h.
PRVM_alledictfloat
#define PRVM_alledictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 135 of file progsvm.h.
PRVM_alledictfunction
#define PRVM_alledictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 139 of file progsvm.h.
PRVM_alledictstring
#define PRVM_alledictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 137 of file progsvm.h.
PRVM_alledictvector
#define PRVM_alledictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 136 of file progsvm.h.
PRVM_allfunction
#define PRVM_allfunction (funcname) (prog->funcoffsets.funcname)
Definition at line 145 of file progsvm.h.
PRVM_allglobaledict
#define PRVM_allglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 143 of file progsvm.h.
PRVM_allglobalfloat
#define PRVM_allglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 140 of file progsvm.h.
PRVM_allglobalfunction
#define PRVM_allglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 144 of file progsvm.h.
PRVM_allglobalstring
#define PRVM_allglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 142 of file progsvm.h.
PRVM_allglobalvector
#define PRVM_allglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 141 of file progsvm.h.
PRVM_Alloc
#define PRVM_Alloc (buffersize) Mem_Alloc(prog->progs_mempool, buffersize)
Definition at line 815 of file progsvm.h.
PRVM_clientedictedict
#define PRVM_clientedictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 186 of file progsvm.h.
PRVM_clientedictfloat
#define PRVM_clientedictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 183 of file progsvm.h.
PRVM_clientedictfunction
#define PRVM_clientedictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 187 of file progsvm.h.
PRVM_clientedictstring
#define PRVM_clientedictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 185 of file progsvm.h.
PRVM_clientedictvector
#define PRVM_clientedictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 184 of file progsvm.h.
PRVM_clientfunction
#define PRVM_clientfunction (funcname) (prog->funcoffsets.funcname)
Definition at line 193 of file progsvm.h.
PRVM_clientglobaledict
#define PRVM_clientglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 191 of file progsvm.h.
PRVM_clientglobalfloat
#define PRVM_clientglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 188 of file progsvm.h.
PRVM_clientglobalfunction
#define PRVM_clientglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 192 of file progsvm.h.
PRVM_clientglobalstring
#define PRVM_clientglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 190 of file progsvm.h.
PRVM_clientglobalvector
#define PRVM_clientglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 189 of file progsvm.h.
PRVM_DECLARE_clientfieldedict [1/3]
#define PRVM_DECLARE_clientfieldedict (x)
Definition at line 281 of file progsvm.h.
PRVM_DECLARE_clientfieldedict [2/3]
#define PRVM_DECLARE_clientfieldedict (x)
Definition at line 281 of file progsvm.h.
PRVM_DECLARE_clientfieldedict [3/3]
#define PRVM_DECLARE_clientfieldedict (x)
Definition at line 281 of file progsvm.h.
PRVM_DECLARE_clientfieldfloat [1/3]
#define PRVM_DECLARE_clientfieldfloat (x)
Definition at line 278 of file progsvm.h.
PRVM_DECLARE_clientfieldfloat [2/3]
#define PRVM_DECLARE_clientfieldfloat (x)
Definition at line 278 of file progsvm.h.
PRVM_DECLARE_clientfieldfloat [3/3]
#define PRVM_DECLARE_clientfieldfloat (x)
Definition at line 278 of file progsvm.h.
PRVM_DECLARE_clientfieldfunction [1/3]
#define PRVM_DECLARE_clientfieldfunction (x)
Definition at line 282 of file progsvm.h.
PRVM_DECLARE_clientfieldfunction [2/3]
#define PRVM_DECLARE_clientfieldfunction (x)
Definition at line 282 of file progsvm.h.
PRVM_DECLARE_clientfieldfunction [3/3]
#define PRVM_DECLARE_clientfieldfunction (x)
Definition at line 282 of file progsvm.h.
PRVM_DECLARE_clientfieldstring [1/3]
#define PRVM_DECLARE_clientfieldstring (x)
Definition at line 280 of file progsvm.h.
PRVM_DECLARE_clientfieldstring [2/3]
#define PRVM_DECLARE_clientfieldstring (x)
Definition at line 280 of file progsvm.h.
PRVM_DECLARE_clientfieldstring [3/3]
#define PRVM_DECLARE_clientfieldstring (x)
Definition at line 280 of file progsvm.h.
PRVM_DECLARE_clientfieldvector [1/3]
#define PRVM_DECLARE_clientfieldvector (x)
Definition at line 279 of file progsvm.h.
PRVM_DECLARE_clientfieldvector [2/3]
#define PRVM_DECLARE_clientfieldvector (x)
Definition at line 279 of file progsvm.h.
PRVM_DECLARE_clientfieldvector [3/3]
#define PRVM_DECLARE_clientfieldvector (x)
Definition at line 279 of file progsvm.h.
PRVM_DECLARE_clientfunction [1/3]
#define PRVM_DECLARE_clientfunction (x)
Definition at line 289 of file progsvm.h.
PRVM_DECLARE_clientfunction [2/3]
#define PRVM_DECLARE_clientfunction (x)
Definition at line 289 of file progsvm.h.
PRVM_DECLARE_clientfunction [3/3]
#define PRVM_DECLARE_clientfunction (x)
Definition at line 289 of file progsvm.h.
PRVM_DECLARE_clientglobaledict [1/3]
#define PRVM_DECLARE_clientglobaledict (x)
Definition at line 266 of file progsvm.h.
PRVM_DECLARE_clientglobaledict [2/3]
#define PRVM_DECLARE_clientglobaledict (x)
Definition at line 266 of file progsvm.h.
PRVM_DECLARE_clientglobaledict [3/3]
#define PRVM_DECLARE_clientglobaledict (x)
Definition at line 266 of file progsvm.h.
PRVM_DECLARE_clientglobalfloat [1/3]
#define PRVM_DECLARE_clientglobalfloat (x)
Definition at line 263 of file progsvm.h.
PRVM_DECLARE_clientglobalfloat [2/3]
#define PRVM_DECLARE_clientglobalfloat (x)
Definition at line 263 of file progsvm.h.
PRVM_DECLARE_clientglobalfloat [3/3]
#define PRVM_DECLARE_clientglobalfloat (x)
Definition at line 263 of file progsvm.h.
PRVM_DECLARE_clientglobalfunction [1/3]
#define PRVM_DECLARE_clientglobalfunction (x)
Definition at line 267 of file progsvm.h.
PRVM_DECLARE_clientglobalfunction [2/3]
#define PRVM_DECLARE_clientglobalfunction (x)
Definition at line 267 of file progsvm.h.
PRVM_DECLARE_clientglobalfunction [3/3]
#define PRVM_DECLARE_clientglobalfunction (x)
Definition at line 267 of file progsvm.h.
PRVM_DECLARE_clientglobalstring [1/3]
#define PRVM_DECLARE_clientglobalstring (x)
Definition at line 265 of file progsvm.h.
PRVM_DECLARE_clientglobalstring [2/3]
#define PRVM_DECLARE_clientglobalstring (x)
Definition at line 265 of file progsvm.h.
PRVM_DECLARE_clientglobalstring [3/3]
#define PRVM_DECLARE_clientglobalstring (x)
Definition at line 265 of file progsvm.h.
PRVM_DECLARE_clientglobalvector [1/3]
#define PRVM_DECLARE_clientglobalvector (x)
Definition at line 264 of file progsvm.h.
PRVM_DECLARE_clientglobalvector [2/3]
#define PRVM_DECLARE_clientglobalvector (x)
Definition at line 264 of file progsvm.h.
PRVM_DECLARE_clientglobalvector [3/3]
#define PRVM_DECLARE_clientglobalvector (x)
Definition at line 264 of file progsvm.h.
PRVM_DECLARE_field [1/3]
#define PRVM_DECLARE_field (x) int x;
Definition at line 291 of file progsvm.h.
PRVM_DECLARE_field [2/3]
#define PRVM_DECLARE_field (x)
Definition at line 291 of file progsvm.h.
PRVM_DECLARE_field [3/3]
#define PRVM_DECLARE_field (x)
Definition at line 291 of file progsvm.h.
PRVM_DECLARE_function [1/3]
#define PRVM_DECLARE_function (x)
Definition at line 293 of file progsvm.h.
PRVM_DECLARE_function [2/3]
#define PRVM_DECLARE_function (x)
Definition at line 293 of file progsvm.h.
PRVM_DECLARE_function [3/3]
#define PRVM_DECLARE_function (x) int x;
Definition at line 293 of file progsvm.h.
PRVM_DECLARE_global [1/3]
#define PRVM_DECLARE_global (x)
Definition at line 292 of file progsvm.h.
PRVM_DECLARE_global [2/3]
#define PRVM_DECLARE_global (x) int x;
Definition at line 292 of file progsvm.h.
PRVM_DECLARE_global [3/3]
#define PRVM_DECLARE_global (x)
Definition at line 292 of file progsvm.h.
PRVM_DECLARE_menufieldedict [1/3]
#define PRVM_DECLARE_menufieldedict (x)
Definition at line 286 of file progsvm.h.
PRVM_DECLARE_menufieldedict [2/3]
#define PRVM_DECLARE_menufieldedict (x)
Definition at line 286 of file progsvm.h.
PRVM_DECLARE_menufieldedict [3/3]
#define PRVM_DECLARE_menufieldedict (x)
Definition at line 286 of file progsvm.h.
PRVM_DECLARE_menufieldfloat [1/3]
#define PRVM_DECLARE_menufieldfloat (x)
Definition at line 283 of file progsvm.h.
PRVM_DECLARE_menufieldfloat [2/3]
#define PRVM_DECLARE_menufieldfloat (x)
Definition at line 283 of file progsvm.h.
PRVM_DECLARE_menufieldfloat [3/3]
#define PRVM_DECLARE_menufieldfloat (x)
Definition at line 283 of file progsvm.h.
PRVM_DECLARE_menufieldfunction [1/3]
#define PRVM_DECLARE_menufieldfunction (x)
Definition at line 287 of file progsvm.h.
PRVM_DECLARE_menufieldfunction [2/3]
#define PRVM_DECLARE_menufieldfunction (x)
Definition at line 287 of file progsvm.h.
PRVM_DECLARE_menufieldfunction [3/3]
#define PRVM_DECLARE_menufieldfunction (x)
Definition at line 287 of file progsvm.h.
PRVM_DECLARE_menufieldstring [1/3]
#define PRVM_DECLARE_menufieldstring (x)
Definition at line 285 of file progsvm.h.
PRVM_DECLARE_menufieldstring [2/3]
#define PRVM_DECLARE_menufieldstring (x)
Definition at line 285 of file progsvm.h.
PRVM_DECLARE_menufieldstring [3/3]
#define PRVM_DECLARE_menufieldstring (x)
Definition at line 285 of file progsvm.h.
PRVM_DECLARE_menufieldvector [1/3]
#define PRVM_DECLARE_menufieldvector (x)
Definition at line 284 of file progsvm.h.
PRVM_DECLARE_menufieldvector [2/3]
#define PRVM_DECLARE_menufieldvector (x)
Definition at line 284 of file progsvm.h.
PRVM_DECLARE_menufieldvector [3/3]
#define PRVM_DECLARE_menufieldvector (x)
Definition at line 284 of file progsvm.h.
PRVM_DECLARE_menufunction [1/3]
#define PRVM_DECLARE_menufunction (x)
Definition at line 290 of file progsvm.h.
PRVM_DECLARE_menufunction [2/3]
#define PRVM_DECLARE_menufunction (x)
Definition at line 290 of file progsvm.h.
PRVM_DECLARE_menufunction [3/3]
#define PRVM_DECLARE_menufunction (x)
Definition at line 290 of file progsvm.h.
PRVM_DECLARE_menuglobaledict [1/3]
#define PRVM_DECLARE_menuglobaledict (x)
Definition at line 271 of file progsvm.h.
PRVM_DECLARE_menuglobaledict [2/3]
#define PRVM_DECLARE_menuglobaledict (x)
Definition at line 271 of file progsvm.h.
PRVM_DECLARE_menuglobaledict [3/3]
#define PRVM_DECLARE_menuglobaledict (x)
Definition at line 271 of file progsvm.h.
PRVM_DECLARE_menuglobalfloat [1/3]
#define PRVM_DECLARE_menuglobalfloat (x)
Definition at line 268 of file progsvm.h.
PRVM_DECLARE_menuglobalfloat [2/3]
#define PRVM_DECLARE_menuglobalfloat (x)
Definition at line 268 of file progsvm.h.
PRVM_DECLARE_menuglobalfloat [3/3]
#define PRVM_DECLARE_menuglobalfloat (x)
Definition at line 268 of file progsvm.h.
PRVM_DECLARE_menuglobalfunction [1/3]
#define PRVM_DECLARE_menuglobalfunction (x)
Definition at line 272 of file progsvm.h.
PRVM_DECLARE_menuglobalfunction [2/3]
#define PRVM_DECLARE_menuglobalfunction (x)
Definition at line 272 of file progsvm.h.
PRVM_DECLARE_menuglobalfunction [3/3]
#define PRVM_DECLARE_menuglobalfunction (x)
Definition at line 272 of file progsvm.h.
PRVM_DECLARE_menuglobalstring [1/3]
#define PRVM_DECLARE_menuglobalstring (x)
Definition at line 270 of file progsvm.h.
PRVM_DECLARE_menuglobalstring [2/3]
#define PRVM_DECLARE_menuglobalstring (x)
Definition at line 270 of file progsvm.h.
PRVM_DECLARE_menuglobalstring [3/3]
#define PRVM_DECLARE_menuglobalstring (x)
Definition at line 270 of file progsvm.h.
PRVM_DECLARE_menuglobalvector [1/3]
#define PRVM_DECLARE_menuglobalvector (x)
Definition at line 269 of file progsvm.h.
PRVM_DECLARE_menuglobalvector [2/3]
#define PRVM_DECLARE_menuglobalvector (x)
Definition at line 269 of file progsvm.h.
PRVM_DECLARE_menuglobalvector [3/3]
#define PRVM_DECLARE_menuglobalvector (x)
Definition at line 269 of file progsvm.h.
PRVM_DECLARE_serverfieldedict [1/3]
#define PRVM_DECLARE_serverfieldedict (x)
Definition at line 276 of file progsvm.h.
PRVM_DECLARE_serverfieldedict [2/3]
#define PRVM_DECLARE_serverfieldedict (x)
Definition at line 276 of file progsvm.h.
PRVM_DECLARE_serverfieldedict [3/3]
#define PRVM_DECLARE_serverfieldedict (x)
Definition at line 276 of file progsvm.h.
PRVM_DECLARE_serverfieldfloat [1/3]
#define PRVM_DECLARE_serverfieldfloat (x)
Definition at line 273 of file progsvm.h.
PRVM_DECLARE_serverfieldfloat [2/3]
#define PRVM_DECLARE_serverfieldfloat (x)
Definition at line 273 of file progsvm.h.
PRVM_DECLARE_serverfieldfloat [3/3]
#define PRVM_DECLARE_serverfieldfloat (x)
Definition at line 273 of file progsvm.h.
PRVM_DECLARE_serverfieldfunction [1/3]
#define PRVM_DECLARE_serverfieldfunction (x)
Definition at line 277 of file progsvm.h.
PRVM_DECLARE_serverfieldfunction [2/3]
#define PRVM_DECLARE_serverfieldfunction (x)
Definition at line 277 of file progsvm.h.
PRVM_DECLARE_serverfieldfunction [3/3]
#define PRVM_DECLARE_serverfieldfunction (x)
Definition at line 277 of file progsvm.h.
PRVM_DECLARE_serverfieldstring [1/3]
#define PRVM_DECLARE_serverfieldstring (x)
Definition at line 275 of file progsvm.h.
PRVM_DECLARE_serverfieldstring [2/3]
#define PRVM_DECLARE_serverfieldstring (x)
Definition at line 275 of file progsvm.h.
PRVM_DECLARE_serverfieldstring [3/3]
#define PRVM_DECLARE_serverfieldstring (x)
Definition at line 275 of file progsvm.h.
PRVM_DECLARE_serverfieldvector [1/3]
#define PRVM_DECLARE_serverfieldvector (x)
Definition at line 274 of file progsvm.h.
PRVM_DECLARE_serverfieldvector [2/3]
#define PRVM_DECLARE_serverfieldvector (x)
Definition at line 274 of file progsvm.h.
PRVM_DECLARE_serverfieldvector [3/3]
#define PRVM_DECLARE_serverfieldvector (x)
Definition at line 274 of file progsvm.h.
PRVM_DECLARE_serverfunction [1/3]
#define PRVM_DECLARE_serverfunction (x)
Definition at line 288 of file progsvm.h.
PRVM_DECLARE_serverfunction [2/3]
#define PRVM_DECLARE_serverfunction (x)
Definition at line 288 of file progsvm.h.
PRVM_DECLARE_serverfunction [3/3]
#define PRVM_DECLARE_serverfunction (x)
Definition at line 288 of file progsvm.h.
PRVM_DECLARE_serverglobaledict [1/3]
#define PRVM_DECLARE_serverglobaledict (x)
Definition at line 261 of file progsvm.h.
PRVM_DECLARE_serverglobaledict [2/3]
#define PRVM_DECLARE_serverglobaledict (x)
Definition at line 261 of file progsvm.h.
PRVM_DECLARE_serverglobaledict [3/3]
#define PRVM_DECLARE_serverglobaledict (x)
Definition at line 261 of file progsvm.h.
PRVM_DECLARE_serverglobalfloat [1/3]
#define PRVM_DECLARE_serverglobalfloat (x)
Definition at line 258 of file progsvm.h.
PRVM_DECLARE_serverglobalfloat [2/3]
#define PRVM_DECLARE_serverglobalfloat (x)
Definition at line 258 of file progsvm.h.
PRVM_DECLARE_serverglobalfloat [3/3]
#define PRVM_DECLARE_serverglobalfloat (x)
Definition at line 258 of file progsvm.h.
PRVM_DECLARE_serverglobalfunction [1/3]
#define PRVM_DECLARE_serverglobalfunction (x)
Definition at line 262 of file progsvm.h.
PRVM_DECLARE_serverglobalfunction [2/3]
#define PRVM_DECLARE_serverglobalfunction (x)
Definition at line 262 of file progsvm.h.
PRVM_DECLARE_serverglobalfunction [3/3]
#define PRVM_DECLARE_serverglobalfunction (x)
Definition at line 262 of file progsvm.h.
PRVM_DECLARE_serverglobalstring [1/3]
#define PRVM_DECLARE_serverglobalstring (x)
Definition at line 260 of file progsvm.h.
PRVM_DECLARE_serverglobalstring [2/3]
#define PRVM_DECLARE_serverglobalstring (x)
Definition at line 260 of file progsvm.h.
PRVM_DECLARE_serverglobalstring [3/3]
#define PRVM_DECLARE_serverglobalstring (x)
Definition at line 260 of file progsvm.h.
PRVM_DECLARE_serverglobalvector [1/3]
#define PRVM_DECLARE_serverglobalvector (x)
Definition at line 259 of file progsvm.h.
PRVM_DECLARE_serverglobalvector [2/3]
#define PRVM_DECLARE_serverglobalvector (x)
Definition at line 259 of file progsvm.h.
PRVM_DECLARE_serverglobalvector [3/3]
#define PRVM_DECLARE_serverglobalvector (x)
Definition at line 259 of file progsvm.h.
PRVM_drawedictedict
#define PRVM_drawedictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 150 of file progsvm.h.
PRVM_drawedictfloat
#define PRVM_drawedictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 147 of file progsvm.h.
PRVM_drawedictfunction
#define PRVM_drawedictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 151 of file progsvm.h.
PRVM_drawedictstring
#define PRVM_drawedictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 149 of file progsvm.h.
PRVM_drawedictvector
#define PRVM_drawedictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 148 of file progsvm.h.
PRVM_drawfunction
#define PRVM_drawfunction (funcname) (prog->funcoffsets.funcname)
Definition at line 157 of file progsvm.h.
PRVM_drawglobaledict
#define PRVM_drawglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 155 of file progsvm.h.
PRVM_drawglobalfloat
#define PRVM_drawglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 152 of file progsvm.h.
PRVM_drawglobalfunction
#define PRVM_drawglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 156 of file progsvm.h.
PRVM_drawglobalstring
#define PRVM_drawglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 154 of file progsvm.h.
PRVM_drawglobalvector
#define PRVM_drawglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 153 of file progsvm.h.
PRVM_E_FLOAT
#define PRVM_E_FLOAT (e, o) (e->fields.fp[o])
Definition at line 888 of file progsvm.h.
PRVM_E_INT
#define PRVM_E_INT (e, o) (e->fields.ip[o])
Definition at line 889 of file progsvm.h.
PRVM_E_STRING
#define PRVM_E_STRING (e, o) (PRVM_GetString(prog, e->fields.ip[o]))
Definition at line 891 of file progsvm.h.
PRVM_ED_FindFieldOffset_FromStruct
#define PRVM_ED_FindFieldOffset_FromStruct (st, field) prog->fieldoffsets . field = ((int *)(&((st *)NULL)-> field) - ((int *)NULL))
Definition at line 838 of file progsvm.h.
PRVM_ED_FindGlobalOffset_FromStruct
#define PRVM_ED_FindGlobalOffset_FromStruct (st, field) prog->globaloffsets . field = ((int *)(&((st *)NULL)-> field) - ((int *)NULL))
Definition at line 839 of file progsvm.h.
PRVM_EDICT
#define PRVM_EDICT (n) (((unsigned)(n) < (unsigned int)prog->max_edicts) ? (unsigned int)(n) : PRVM_EDICT_NUM_ERROR(prog, (unsigned int)(n), __FILE__, __LINE__))
Definition at line 863 of file progsvm.h.
PRVM_EDICT_MARK_SETORIGIN_CAUGHT
#define PRVM_EDICT_MARK_SETORIGIN_CAUGHT -2
Definition at line 78 of file progsvm.h.
PRVM_EDICT_MARK_WAIT_FOR_SETORIGIN
#define PRVM_EDICT_MARK_WAIT_FOR_SETORIGIN -1
Definition at line 77 of file progsvm.h.
PRVM_EDICT_NUM
#define PRVM_EDICT_NUM (n) (prog->edicts + PRVM_EDICT(n))
Definition at line 864 of file progsvm.h.
PRVM_EDICT_TO_PROG
#define PRVM_EDICT_TO_PROG (e) (PRVM_NUM_FOR_EDICT(e))
Definition at line 872 of file progsvm.h.
PRVM_EDICTFIELDEDICT
#define PRVM_EDICTFIELDEDICT (ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->edict)
Definition at line 212 of file progsvm.h.
PRVM_EDICTFIELDFLOAT
#define PRVM_EDICTFIELDFLOAT (ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->_float)
Definition at line 209 of file progsvm.h.
PRVM_EDICTFIELDFUNCTION
#define PRVM_EDICTFIELDFUNCTION (ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->function)
Definition at line 213 of file progsvm.h.
PRVM_EDICTFIELDSTRING
#define PRVM_EDICTFIELDSTRING (ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->string)
Definition at line 211 of file progsvm.h.
PRVM_EDICTFIELDVALUE
#define PRVM_EDICTFIELDVALUE (ed, fieldoffset) ((fieldoffset) < 0 ? Con_Printf("Invalid fieldoffset at %s:%i\n", __FILE__, __LINE__), &prvm_badvalue : (prvm_eval_t *)((ed)->fields.fp + (fieldoffset)))
Definition at line 208 of file progsvm.h.
PRVM_EDICTFIELDVECTOR
#define PRVM_EDICTFIELDVECTOR (ed, fieldoffset) (PRVM_EDICTFIELDVALUE(ed, fieldoffset)->vector)
Definition at line 210 of file progsvm.h.
PRVM_Free
#define PRVM_Free (buffer) Mem_Free(buffer)
Definition at line 816 of file progsvm.h.
PRVM_G_EDICT
#define PRVM_G_EDICT (o) (PRVM_PROG_TO_EDICT(prog->globals.ip[o]))
Definition at line 881 of file progsvm.h.
PRVM_G_EDICTNUM
#define PRVM_G_EDICTNUM (o) PRVM_NUM_FOR_EDICT(PRVM_G_EDICT(o))
Definition at line 882 of file progsvm.h.
PRVM_G_FLOAT
#define PRVM_G_FLOAT (o) (prog->globals.fp[o])
Definition at line 879 of file progsvm.h.
PRVM_G_INT
#define PRVM_G_INT (o) (prog->globals.ip[o])
Definition at line 880 of file progsvm.h.
PRVM_G_STRING
#define PRVM_G_STRING (o) (PRVM_GetString(prog, prog->globals.ip[o]))
Definition at line 884 of file progsvm.h.
PRVM_G_VECTOR
#define PRVM_G_VECTOR (o) (&prog->globals.fp[o])
Definition at line 883 of file progsvm.h.
PRVM_gameedictedict
#define PRVM_gameedictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 162 of file progsvm.h.
PRVM_gameedictfloat
#define PRVM_gameedictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 159 of file progsvm.h.
PRVM_gameedictfunction
#define PRVM_gameedictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 163 of file progsvm.h.
PRVM_gameedictstring
#define PRVM_gameedictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 161 of file progsvm.h.
PRVM_gameedictvector
#define PRVM_gameedictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 160 of file progsvm.h.
PRVM_gamefunction
#define PRVM_gamefunction (funcname) (prog->funcoffsets.funcname)
Definition at line 169 of file progsvm.h.
PRVM_gameglobaledict
#define PRVM_gameglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 167 of file progsvm.h.
PRVM_gameglobalfloat
#define PRVM_gameglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 164 of file progsvm.h.
PRVM_gameglobalfunction
#define PRVM_gameglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 168 of file progsvm.h.
PRVM_gameglobalstring
#define PRVM_gameglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 166 of file progsvm.h.
PRVM_gameglobalvector
#define PRVM_gameglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 165 of file progsvm.h.
PRVM_GetProg
#define PRVM_GetProg (n) (&prvm_prog_list[(n)])
Definition at line 761 of file progsvm.h.
PRVM_GLOBALFIELDEDICT
#define PRVM_GLOBALFIELDEDICT (fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->edict)
Definition at line 218 of file progsvm.h.
PRVM_GLOBALFIELDFLOAT
#define PRVM_GLOBALFIELDFLOAT (fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->_float)
Definition at line 215 of file progsvm.h.
PRVM_GLOBALFIELDFUNCTION
#define PRVM_GLOBALFIELDFUNCTION (fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->function)
Definition at line 219 of file progsvm.h.
PRVM_GLOBALFIELDSTRING
#define PRVM_GLOBALFIELDSTRING (fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->string)
Definition at line 217 of file progsvm.h.
PRVM_GLOBALFIELDVALUE
#define PRVM_GLOBALFIELDVALUE (fieldoffset) ((fieldoffset) < 0 ? Con_Printf("Invalid fieldoffset at %s:%i\n", __FILE__, __LINE__), &prvm_badvalue : (prvm_eval_t *)(prog->globals.fp + (fieldoffset)))
Definition at line 214 of file progsvm.h.
PRVM_GLOBALFIELDVECTOR
#define PRVM_GLOBALFIELDVECTOR (fieldoffset) (PRVM_GLOBALFIELDVALUE(fieldoffset)->vector)
Definition at line 216 of file progsvm.h.
PRVM_LOCALSTACK_SIZE
#define PRVM_LOCALSTACK_SIZE 16384
Definition at line 246 of file progsvm.h.
PRVM_MAX_OPENFILES
#define PRVM_MAX_OPENFILES 256
Definition at line 248 of file progsvm.h.
PRVM_MAX_OPENSEARCHES
#define PRVM_MAX_OPENSEARCHES 128
Definition at line 249 of file progsvm.h.
PRVM_MAX_STACK_DEPTH
#define PRVM_MAX_STACK_DEPTH 1024
Definition at line 245 of file progsvm.h.
PRVM_menuedictedict
#define PRVM_menuedictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 198 of file progsvm.h.
PRVM_menuedictfloat
#define PRVM_menuedictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 195 of file progsvm.h.
PRVM_menuedictfunction
#define PRVM_menuedictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 199 of file progsvm.h.
PRVM_menuedictstring
#define PRVM_menuedictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 197 of file progsvm.h.
PRVM_menuedictvector
#define PRVM_menuedictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 196 of file progsvm.h.
PRVM_menufunction
#define PRVM_menufunction (funcname) (prog->funcoffsets.funcname)
Definition at line 205 of file progsvm.h.
PRVM_menuglobaledict
#define PRVM_menuglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 203 of file progsvm.h.
PRVM_menuglobalfloat
#define PRVM_menuglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 200 of file progsvm.h.
PRVM_menuglobalfunction
#define PRVM_menuglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 204 of file progsvm.h.
PRVM_menuglobalstring
#define PRVM_menuglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 202 of file progsvm.h.
PRVM_menuglobalvector
#define PRVM_menuglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 201 of file progsvm.h.
PRVM_NEXT_EDICT
#define PRVM_NEXT_EDICT (e) ((e) + 1)
Definition at line 870 of file progsvm.h.
PRVM_NUM_FOR_EDICT
#define PRVM_NUM_FOR_EDICT (e) ((int)((prvm_edict_t *)(e) - prog->edicts))
Definition at line 867 of file progsvm.h.
PRVM_OP_STATE
#define PRVM_OP_STATE 1
Definition at line 236 of file progsvm.h.
PRVM_PROG_TO_EDICT
#define PRVM_PROG_TO_EDICT (n) (PRVM_EDICT_NUM(n))
Definition at line 874 of file progsvm.h.
PRVM_ProgLoaded
#define PRVM_ProgLoaded (n) (PRVM_GetProg(n)->loaded)
Definition at line 762 of file progsvm.h.
PRVM_serveredictedict
#define PRVM_serveredictedict (ed, fieldname) (PRVM_EDICTFIELDEDICT(ed, prog->fieldoffsets.fieldname))
Definition at line 174 of file progsvm.h.
PRVM_serveredictfloat
#define PRVM_serveredictfloat (ed, fieldname) (PRVM_EDICTFIELDFLOAT(ed, prog->fieldoffsets.fieldname))
Definition at line 171 of file progsvm.h.
PRVM_serveredictfunction
#define PRVM_serveredictfunction (ed, fieldname) (PRVM_EDICTFIELDFUNCTION(ed, prog->fieldoffsets.fieldname))
Definition at line 175 of file progsvm.h.
PRVM_serveredictstring
#define PRVM_serveredictstring (ed, fieldname) (PRVM_EDICTFIELDSTRING(ed, prog->fieldoffsets.fieldname))
Definition at line 173 of file progsvm.h.
PRVM_serveredictvector
#define PRVM_serveredictvector (ed, fieldname) (PRVM_EDICTFIELDVECTOR(ed, prog->fieldoffsets.fieldname))
Definition at line 172 of file progsvm.h.
PRVM_serverfunction
#define PRVM_serverfunction (funcname) (prog->funcoffsets.funcname)
Definition at line 181 of file progsvm.h.
PRVM_serverglobaledict
#define PRVM_serverglobaledict (fieldname) (PRVM_GLOBALFIELDEDICT(prog->globaloffsets.fieldname))
Definition at line 179 of file progsvm.h.
PRVM_serverglobalfloat
#define PRVM_serverglobalfloat (fieldname) (PRVM_GLOBALFIELDFLOAT(prog->globaloffsets.fieldname))
Definition at line 176 of file progsvm.h.
PRVM_serverglobalfunction
#define PRVM_serverglobalfunction (fieldname) (PRVM_GLOBALFIELDFUNCTION(prog->globaloffsets.fieldname))
Definition at line 180 of file progsvm.h.
PRVM_serverglobalstring
#define PRVM_serverglobalstring (fieldname) (PRVM_GLOBALFIELDSTRING(prog->globaloffsets.fieldname))
Definition at line 178 of file progsvm.h.
PRVM_serverglobalvector
#define PRVM_serverglobalvector (fieldname) (PRVM_GLOBALFIELDVECTOR(prog->globaloffsets.fieldname))
Definition at line 177 of file progsvm.h.
STRINGBUFFER_QCFLAGS
#define STRINGBUFFER_QCFLAGS 1
Definition at line 494 of file progsvm.h.
STRINGBUFFER_SAVED
#define STRINGBUFFER_SAVED 1
Definition at line 493 of file progsvm.h.
STRINGBUFFER_TEMP
#define STRINGBUFFER_TEMP 128
Definition at line 495 of file progsvm.h.
SVVM_prog
#define SVVM_prog (&prvm_prog_list[PRVM_PROG_SERVER])
Definition at line 763 of file progsvm.h.
Typedef Documentation
prvm_builtin_t
typedef void(* prvm_builtin_t) (struct prvm_prog_s *prog)
Definition at line 253 of file progsvm.h.
Enumeration Type Documentation
prvm_prog_garbagecollection_state_stage_t
enum prvm_prog_garbagecollection_state_stage_t
Enumerator
PRVM_GC_START
PRVM_GC_GLOBALS_MARK
PRVM_GC_FIELDS_MARK
PRVM_GC_KNOWNSTRINGS_SWEEP
PRVM_GC_RESET
Definition at line 511 of file progsvm.h.
{
    PRVM_GC_START = 0,
    PRVM_GC_GLOBALS_MARK,
    PRVM_GC_FIELDS_MARK,
    PRVM_GC_KNOWNSTRINGS_SWEEP,
    PRVM_GC_RESET,
}
prvm_progindex_t
enum prvm_progindex_t
Enumerator
PRVM_PROG_SERVER
PRVM_PROG_CLIENT
PRVM_PROG_MENU
PRVM_PROG_MAX
Definition at line 749 of file progsvm.h.
{
    PRVM_PROG_SERVER,
    PRVM_PROG_CLIENT,
    PRVM_PROG_MENU,
    PRVM_PROG_MAX
}
Function Documentation
CLVM_ExecuteProgram()
void CLVM_ExecuteProgram (prvm_prog_t * prog, func_t fnum, const char * errormessage)
Definition at line 1034 of file prvm_exec.c.
{
    mstatement_t    *st, *startst;
    mfunction_t     *func, *enterfunc;
    prvm_edict_t    *ed;
    prvm_eval_t *ptr;
    int     jumpcount, cachedpr_trace, exitdepth;
    int     restorevm_tempstringsbuf_cursize;
    double  calltime;
    double tm, starttm;
    prvm_vec_t tempfloat;
    // these may become out of date when a builtin is called, and are updated accordingly
    prvm_vec_t *cached_edictsfields = prog->edictsfields.fp;
    unsigned int cached_entityfields = prog->entityfields;
    unsigned int cached_entityfields_3 = prog->entityfields - 3;
    unsigned int cached_entityfieldsarea = prog->entityfieldsarea;
    unsigned int cached_entityfieldsarea_entityfields = prog->entityfieldsarea - prog->entityfields;
    unsigned int cached_entityfieldsarea_3 = prog->entityfieldsarea - 3;
    unsigned int cached_entityfieldsarea_entityfields_3 = prog->entityfieldsarea - prog->entityfields - 3;
    unsigned int cached_max_edicts = prog->max_edicts;
    // these do not change
    mstatement_t *cached_statements = prog->statements;
    qbool cached_allowworldwrites = prog->allowworldwrites;
    unsigned int cached_flag = prog->flag;
    prvm_vec_t *globals = prog->globals.fp;
    calltime = Sys_DirtyTime();
    if (!fnum || fnum >= (unsigned int)prog->numfunctions)
    {
        if (PRVM_allglobaledict(self))
            PRVM_ED_Print(prog, PRVM_PROG_TO_EDICT(PRVM_allglobaledict(self)), NULL);
        prog->error_cmd("CLVM_ExecuteProgram: %s", errormessage);
    }
    func = &prog->functions[fnum];
    // after executing this function, delete all tempstrings it created
    restorevm_tempstringsbuf_cursize = prog->tempstringsbuf.cursize;
    prog->trace = prvm_traceqc.integer;
    // we know we're done when pr_depth drops to this
    exitdepth = prog->depth;
// make a stack frame
    st = &prog->statements[PRVM_EnterFunction(prog, func)];
    // save the starting statement pointer for profiling
    // (when the function exits or jumps, the (st - startst) integer value is
    // added to the function's profile counter)
    startst = st;
    starttm = calltime;
    // instead of counting instructions, we count jumps
    jumpcount = 0;
    // add one to the callcount of this function because otherwise engine-called functions aren't counted
    if (prog->xfunction->callcount++ == 0 && (prvm_coverage.integer & 1))
        PRVM_FunctionCoverageEvent(prog, prog->xfunction);
chooseexecprogram:
    cachedpr_trace = prog->trace;
    if (prog->trace || prog->watch_global_type != ev_void || prog->watch_field_type != ev_void || prog->break_statement >= 0)
    {
#define PRVMSLOWINTERPRETER 1
        if (prvm_timeprofiling.integer)
        {
#define PRVMTIMEPROFILING 1
#include "prvm_execprogram.h"
#undef PRVMTIMEPROFILING
        }
        else
        {
#include "prvm_execprogram.h"
        }
#undef PRVMSLOWINTERPRETER
    }
    else
    {
        if (prvm_timeprofiling.integer)
        {
#define PRVMTIMEPROFILING 1
#include "prvm_execprogram.h"
#undef PRVMTIMEPROFILING
        }
        else
        {
#include "prvm_execprogram.h"
        }
    }
cleanup:
    if (developer_insane.integer && prog->tempstringsbuf.cursize > restorevm_tempstringsbuf_cursize)
        Con_DPrintf("CLVM_ExecuteProgram: %s used %i bytes of tempstrings\n", PRVM_GetString(prog, prog->functions[fnum].s_name), prog->tempstringsbuf.cursize - restorevm_tempstringsbuf_cursize);
    // delete tempstrings created by this function
    prog->tempstringsbuf.cursize = restorevm_tempstringsbuf_cursize;
    tm = Sys_DirtyTime() - calltime;if (tm < 0 || tm >= 1800) tm = 0;
    func->totaltime += tm;
    if (prog == SVVM_prog)
        SV_FlushBroadcastMessages();
}
Referenced by CL_VM_Init().
CLVM_init_cmd()
void CLVM_init_cmd (prvm_prog_t * prog)
Definition at line 5637 of file clvm_cmds.c.
{
    VM_Cmd_Init(prog);
    prog->polygonbegin_model = NULL;
    prog->polygonbegin_guess2d = 0;
}
Referenced by CL_VM_Init().
CLVM_reset_cmd()
void CLVM_reset_cmd (prvm_prog_t * prog)
Definition at line 5644 of file clvm_cmds.c.
{
    World_End(&cl.world);
    VM_Cmd_Reset(prog);
    prog->polygonbegin_model = NULL;
    prog->polygonbegin_guess2d = 0;
}
Referenced by CL_VM_Init().
PRVM_AllocationOrigin()
const char * PRVM_AllocationOrigin (prvm_prog_t * prog)
Definition at line 218 of file prvm_edict.c.
{
    char *buf = NULL;
    if(prog->leaktest_active)
    if(prog->depth > 0) // actually in QC code and not just parsing the entities block of a map/savegame
    {
        // bones_was_here: this is the smallest 64 multiple that avoids truncation in Xonotic (was 256)
        buf = (char *)PRVM_Alloc(448);
        PRVM_ShortStackTrace(prog, buf, 448);
    }
    return buf;
}
Referenced by PRVM_AllocString(), PRVM_ED_ClearEdict(), VM_buf_create(), VM_fopen(), and VM_search_begin().
PRVM_AllocString()
int PRVM_AllocString (prvm_prog_t * prog, size_t bufferlength, char ** pointer)
Definition at line 3407 of file prvm_edict.c.
{
    int i;
    char *s;
    if (!bufferlength)
    {
        if (pointer)
            *pointer = NULL;
        return 0;
    }
    for (i = prog->firstfreeknownstring;i < prog->numknownstrings;i++)
        if (!prog->knownstrings[i])
            break;
    s = (char *)PRVM_Alloc(bufferlength);
    PRVM_NewKnownString(prog, i, KNOWNSTRINGFLAG_GCMARK, s);
    if(prog->leaktest_active)
        prog->knownstrings_origin[i] = PRVM_AllocationOrigin(prog);
    if (pointer)
        *pointer = (char *)(prog->knownstrings[i]);
    return PRVM_KNOWNSTRINGBASE + i;
}
Referenced by PRVM_ED_CallSpawnFunction(), PRVM_ED_ParseEpair(), and VM_strzone().
PRVM_Breakpoint()
void PRVM_Breakpoint (prvm_prog_t * prog, int stack_index, const char * text)
Definition at line 2950 of file prvm_edict.c.
{
    char vabuf[1024];
    Con_Printf("PRVM_Breakpoint: %s\n", text);
    PRVM_PrintState(prog, stack_index);
    if (prvm_breakpointdump.integer)
        SV_Savegame_to(prog, va(vabuf, sizeof(vabuf), "breakpoint-%s.dmp", prog->name));
}
Referenced by PRVM_Watchpoint(), and while().
PRVM_CallProfile_f()
void PRVM_CallProfile_f (struct cmd_state_s * cmd)
Referenced by PRVM_Init().
PRVM_ChangeEngineString()
const char * PRVM_ChangeEngineString (prvm_prog_t * prog, int i, const char * s)
Definition at line 3293 of file prvm_edict.c.
{
    const char *old;
    i = i - PRVM_KNOWNSTRINGBASE;
    if (i < 0 || i >= prog->numknownstrings)
        prog->error_cmd("PRVM_ChangeEngineString: string index %i is out of bounds", i);
    else if ((prog->knownstrings_flags[i] & KNOWNSTRINGFLAG_ENGINE) == 0)
        prog->error_cmd("PRVM_ChangeEngineString: string index %i is not an engine string", i);
    old = prog->knownstrings[i];
    prog->knownstrings[i] = s;
    return old;
}
Referenced by Cvar_UpdateAutoCvar().
PRVM_ChildProfile_f()
void PRVM_ChildProfile_f (struct cmd_state_s * cmd)
Referenced by PRVM_Init().
PRVM_Crash()
void PRVM_Crash (void)
Definition at line 718 of file prvm_exec.c.
{
    prvm_prog_t *prog;
    char vabuf[1024];
    int i;
    // determine which program crashed
    for (i = 0; i < PRVM_PROG_MAX; ++i)
        if (PRVM_GetProg(i)->loaded && PRVM_GetProg(i)->depth > 0)
            break;
    if (i >= PRVM_PROG_MAX)
        return; // none of them crashed
    prog = PRVM_GetProg(i);
    Con_Printf("QuakeC crash report for %s:\n", prog->name);
    PRVM_PrintState(prog, 0);
    // don't call graceful shutdown on crash
    if (prog == SVVM_prog)
        PRVM_serverfunction(SV_Shutdown) = 0;
    else if (prog == CLVM_prog)
        PRVM_clientfunction(CSQC_Shutdown) = 0;
    if(prvm_errordump.integer && (prog == SVVM_prog || prog == CLVM_prog))
    {
        // make a savegame
        SV_Savegame_to(prog, va(vabuf, sizeof(vabuf), "crash-%s.dmp", prog->name));
    }
    // dump the stack so host_error can shutdown functions
    prog->depth = 0;
    prog->localstack_used = 0;
}
Referenced by Host_Error(), and MVM_error_cmd().
PRVM_ED_Alloc()
prvm_edict_t * PRVM_ED_Alloc (prvm_prog_t * prog)
Definition at line 264 of file prvm_edict.c.
{
    int i;
    prvm_edict_t *e;
    // the client qc dont need maxclients
    // thus it doesnt need to use svs.maxclients
    // AK:  changed i=svs.maxclients+1
    // AK:  changed so the edict 0 wont spawn -> used as reserved/world entity
    //      although the menu/client has no world
    for (i = prog->reserved_edicts + 1;i < prog->num_edicts;i++)
    {
        e = PRVM_EDICT_NUM(i);
        if(PRVM_ED_CanAlloc(prog, e))
        {
            PRVM_ED_ClearEdict (prog, e);
            return e;
        }
    }
    if (i == prog->limit_edicts)
        prog->error_cmd("%s: PRVM_ED_Alloc: no free edicts", prog->name);
    prog->num_edicts++;
    if (prog->num_edicts >= prog->max_edicts)
        PRVM_MEM_IncreaseEdicts(prog);
    e = PRVM_EDICT_NUM(i);
    PRVM_ED_ClearEdict(prog, e);
    return e;
}
Referenced by CSQC_ReadEntities(), PRVM_ED_LoadFromFile(), SV_Ent_Create_f(), VM_CL_spawn(), and VM_spawn().
PRVM_ED_CallPostspawnFunction()
void PRVM_ED_CallPostspawnFunction (prvm_prog_t * prog, prvm_edict_t * ent)
Definition at line 1462 of file prvm_edict.c.
{
    if(!ent->free)
    if (PRVM_serverfunction(SV_OnEntityPostSpawnFunction))
    {
        // self = ent
        PRVM_serverglobalfloat(time) = sv.time;
        PRVM_serverglobaledict(self) = PRVM_EDICT_TO_PROG(ent);
        prog->ExecuteProgram(prog, PRVM_serverfunction(SV_OnEntityPostSpawnFunction), "QC function SV_OnEntityPostSpawnFunction is missing");
    }
}
Referenced by PRVM_ED_LoadFromFile(), and SV_Ent_Create_f().
PRVM_ED_CallPrespawnFunction()
void PRVM_ED_CallPrespawnFunction (prvm_prog_t * prog, prvm_edict_t * ent)
Definition at line 1367 of file prvm_edict.c.
{
    if (PRVM_serverfunction(SV_OnEntityPreSpawnFunction))
    {
        // self = ent
        PRVM_serverglobalfloat(time) = sv.time;
        PRVM_serverglobaledict(self) = PRVM_EDICT_TO_PROG(ent);
        prog->ExecuteProgram(prog, PRVM_serverfunction(SV_OnEntityPreSpawnFunction), "QC function SV_OnEntityPreSpawnFunction is missing");
    }
}
Referenced by PRVM_ED_LoadFromFile(), and SV_Ent_Create_f().
PRVM_ED_CallSpawnFunction()
qbool PRVM_ED_CallSpawnFunction (prvm_prog_t * prog, prvm_edict_t * ent, const char * data, const char * start)
Definition at line 1378 of file prvm_edict.c.
{
    const char *funcname;
    mfunction_t *func;
    prvm_eval_t *fulldata = NULL;
    char vabuf[1024];
//
// immediately call spawn function, but only if there is a self global and a classname
//
    if (!ent->free)
    {
        if (!PRVM_alledictstring(ent, classname))
        {
            Con_Print("No classname for:\n");
            PRVM_ED_Print(prog, ent, NULL);
            PRVM_ED_Free (prog, ent);
            return false;
        }
        /*
         * This is required for FTE compatibility (FreeCS).
         * It copies the key/value pairs themselves into a
         * global for QC to parse on its own.
         */
        else if (data && start)
        {
            if((fulldata = PRVM_ED_FindGlobalEval(prog, "__fullspawndata")))
            {
                const char *in;
                char *spawndata;
                fulldata->string = PRVM_AllocString(prog, data - start + 1, &spawndata);
                for(in = start; in < data; )
                {
                    char c = *in++;
                    if(c == '\n')
                        *spawndata++ = '\t';
                    else
                        *spawndata++ = c;
                }
                *spawndata = 0;
            }
        }
        // look for the spawn function
        funcname = PRVM_GetString(prog, PRVM_alledictstring(ent, classname));
        func = PRVM_ED_FindFunction (prog, va(vabuf, sizeof(vabuf), "spawnfunc_%s", funcname));
        if(!func)
            if(!PRVM_allglobalfloat(require_spawnfunc_prefix))
                func = PRVM_ED_FindFunction (prog, funcname);
        if (!func)
        {
            // check for OnEntityNoSpawnFunction
            if (PRVM_serverfunction(SV_OnEntityNoSpawnFunction))
            {
                // self = ent
                PRVM_serverglobalfloat(time) = sv.time;
                PRVM_serverglobaledict(self) = PRVM_EDICT_TO_PROG(ent);
                prog->ExecuteProgram(prog, PRVM_serverfunction(SV_OnEntityNoSpawnFunction), "QC function SV_OnEntityNoSpawnFunction is missing");
            }
            else
            {
                Con_DPrint("No spawn function for:\n");
                if (developer.integer > 0) // don't confuse non-developers with errors
                    PRVM_ED_Print(prog, ent, NULL);
                PRVM_ED_Free (prog, ent);
                return false; // not included in "inhibited" count
            }
        }
        else
        {
            // self = ent
            PRVM_serverglobalfloat(time) = sv.time;
            PRVM_allglobaledict(self) = PRVM_EDICT_TO_PROG(ent);
            prog->ExecuteProgram(prog, func - prog->functions, "");
        }
        return true;
    }
    PRVM_ED_Free(prog, ent);
    return false;
}
Referenced by PRVM_ED_LoadFromFile(), and SV_Ent_Create_f().
PRVM_ED_CanAlloc()
qbool PRVM_ED_CanAlloc (prvm_prog_t * prog, prvm_edict_t * e)
Definition at line 238 of file prvm_edict.c.
{
    if(!e->free)
        return false;
    if(prvm_reuseedicts_always_allow == host.realtime)
        return true;
    if(host.realtime <= e->freetime + 0.1 && prvm_reuseedicts_neverinsameframe.integer)
        return false; // never allow reuse in same frame (causes networking trouble)
    if(e->freetime < prog->starttime + prvm_reuseedicts_startuptime.value)
        return true;
    if(host.realtime > e->freetime + 1)
        return true;
    return false; // entity slot still blocked because the entity was freed less than one second ago
}
Referenced by PRVM_ED_Alloc(), and SV_Physics().
PRVM_ED_ClearEdict()
void PRVM_ED_ClearEdict (prvm_prog_t * prog, prvm_edict_t * e)
Definition at line 205 of file prvm_edict.c.
{
    memset(e->fields.fp, 0, prog->entityfields * sizeof(prvm_vec_t));
    e->free = false;
    e->freetime = host.realtime;
    if(e->priv.required->allocation_origin)
        Mem_Free((char *)e->priv.required->allocation_origin);
    e->priv.required->allocation_origin = PRVM_AllocationOrigin(prog);
    // AK: Let the init_edict function determine if something needs to be initialized
    prog->init_edict(prog, e);
}
Referenced by PRVM_ED_Alloc(), SV_ConnectClient(), SV_DropClient(), SV_Ent_Remove_All_f(), SV_Ent_Remove_f(), and SV_SpawnServer().
PRVM_ED_FieldAtOfs()
mdef_t * PRVM_ED_FieldAtOfs (prvm_prog_t * prog, unsigned int ofs)
Definition at line 352 of file prvm_edict.c.
{
    mdef_t      *def;
    int         i;
    for (i = 0;i < prog->numfielddefs;i++)
    {
        def = &prog->fielddefs[i];
        if (def->ofs == ofs)
            return def;
    }
    return NULL;
}
Referenced by PRVM_UglyValueString(), PRVM_ValueString(), and while().
PRVM_ED_FindField()
mdef_t * PRVM_ED_FindField (prvm_prog_t * prog, const char * name)
Definition at line 371 of file prvm_edict.c.
{
    mdef_t *def;
    int i;
    for (i = 0;i < prog->numfielddefs;i++)
    {
        def = &prog->fielddefs[i];
        if (!strcmp(PRVM_GetString(prog, def->s_name), name))
            return def;
    }
    return NULL;
}
Referenced by PRVM_ED_EdictGet_f(), PRVM_ED_EdictSet_f(), PRVM_ED_FindFieldOffset(), PRVM_ED_ParseEdict(), PRVM_ED_ParseEpair(), PRVM_UpdateBreakpoints(), and SV_Ent_Create_f().
PRVM_ED_FindFieldOffset()
int PRVM_ED_FindFieldOffset (prvm_prog_t * prog, const char * name)
Definition at line 129 of file prvm_edict.c.
{
    mdef_t *d;
    d = PRVM_ED_FindField(prog, field);
    if (!d)
        return -1;
    return d->ofs;
}
PRVM_ED_FindFunction()
mfunction_t * PRVM_ED_FindFunction (prvm_prog_t * prog, const char * name)
Definition at line 420 of file prvm_edict.c.
{
    mfunction_t     *func;
    int             i;
    for (i = 0;i < prog->numfunctions;i++)
    {
        func = &prog->functions[i];
        if (!strcmp(PRVM_GetString(prog, func->s_name), name))
            return func;
    }
    return NULL;
}
Referenced by PRVM_ED_CallSpawnFunction(), PRVM_ED_FindFunctionOffset(), PRVM_ED_ParseEpair(), PRVM_PrintFunctionStatements(), PRVM_Prog_Load(), PRVM_UpdateBreakpoints(), VM_callfunction(), and VM_isfunction().
PRVM_ED_FindFunctionOffset()
func_t PRVM_ED_FindFunctionOffset (prvm_prog_t * prog, const char * name)
Definition at line 147 of file prvm_edict.c.
{
    mfunction_t *f;
    f = PRVM_ED_FindFunction(prog, function);
    if (!f)
        return 0;
    return (func_t)(f - prog->functions);
}
PRVM_ED_FindGlobal()
mdef_t * PRVM_ED_FindGlobal (prvm_prog_t * prog, const char * name)
Definition at line 390 of file prvm_edict.c.
{
    mdef_t *def;
    int i;
    for (i = 0;i < prog->numglobaldefs;i++)
    {
        def = &prog->globaldefs[i];
        if (!strcmp(PRVM_GetString(prog, def->s_name), name))
            return def;
    }
    return NULL;
}
Referenced by PRVM_ED_FindGlobalEval(), PRVM_ED_FindGlobalOffset(), PRVM_ED_GlobalGet_f(), PRVM_ED_ParseGlobals(), PRVM_Global_f(), PRVM_GlobalSet_f(), and PRVM_UpdateBreakpoints().
PRVM_ED_FindGlobalEval()
prvm_eval_t * PRVM_ED_FindGlobalEval (prvm_prog_t * prog, const char * name)
Definition at line 409 of file prvm_edict.c.
{
    mdef_t *def = PRVM_ED_FindGlobal(prog, name);
    return def ? (prvm_eval_t *) &prog->globals.fp[def->ofs] : NULL;
}
Referenced by PRVM_ED_CallSpawnFunction().
PRVM_ED_FindGlobalOffset()
int PRVM_ED_FindGlobalOffset (prvm_prog_t * prog, const char * name)
Definition at line 138 of file prvm_edict.c.
{
    mdef_t *d;
    d = PRVM_ED_FindGlobal(prog, global);
    if (!d)
        return -1;
    return d->ofs;
}
PRVM_ED_Free()
void PRVM_ED_Free (prvm_prog_t * prog, prvm_edict_t * ed)
Definition at line 309 of file prvm_edict.c.
{
    // dont delete the null entity (world) or reserved edicts
    if (ed - prog->edicts <= prog->reserved_edicts)
        return;
    prog->free_edict(prog, ed);
    ed->free = true;
    ed->freetime = host.realtime;
    if(ed->priv.required->allocation_origin)
    {
        Mem_Free((char *)ed->priv.required->allocation_origin);
        ed->priv.required->allocation_origin = NULL;
    }
}
Referenced by PRVM_ED_CallSpawnFunction(), PRVM_ED_LoadFromFile(), SV_Ent_Create_f(), SV_Ent_Remove_All_f(), SV_Ent_Remove_f(), VM_CL_makestatic(), VM_objerror(), VM_remove(), and VM_SV_makestatic().
PRVM_ED_LoadFromFile()
void PRVM_ED_LoadFromFile (prvm_prog_t * prog, const char * data)
Definition at line 1489 of file prvm_edict.c.
{
    prvm_edict_t *ent;
    const char *start;
    int parsed, inhibited, spawned, died;
    parsed = 0;
    inhibited = 0;
    spawned = 0;
    died = 0;
    prvm_reuseedicts_always_allow = host.realtime;
    // parse ents
    while (1)
    {
        start = data;
        // parse the opening brace
        if (!COM_ParseToken_Simple(&data, false, false, true))
            break;
        if (com_token[0] != '{')
            prog->error_cmd("PRVM_ED_LoadFromFile: %s: found %s when expecting {", prog->name, com_token);
        // CHANGED: this is not conform to PR_LoadFromFile
        if(prog->loadintoworld)
        {
            prog->loadintoworld = false;
            ent = PRVM_EDICT_NUM(0);
        }
        else
            ent = PRVM_ED_Alloc(prog);
        // clear it
        if (ent != prog->edicts)    // hack
            memset (ent->fields.fp, 0, prog->entityfields * sizeof(prvm_vec_t));
        data = PRVM_ED_ParseEdict (prog, data, ent);
        parsed++;
        // remove the entity ?
        if(!prog->load_edict(prog, ent))
        {
            PRVM_ED_Free(prog, ent);
            inhibited++;
            continue;
        }
        PRVM_ED_CallPrespawnFunction(prog, ent);
        if(ent->free)
        {
            inhibited++;
            continue;
        }
        SV_LinkEdict(ent);
        if(!PRVM_ED_CallSpawnFunction(prog, ent, data, start))
            continue;
        PRVM_ED_CallPostspawnFunction(prog, ent);
        spawned++;
        if (ent->free)
            died++;
    }
    Con_DPrintf("%s: %i new entities parsed, %i new inhibited, %i (%i new) spawned (whereas %i removed self, %i stayed)\n", prog->name, parsed, inhibited, prog->num_edicts, spawned, died, spawned - died);
    prvm_reuseedicts_always_allow = 0;
}
Referenced by SV_SpawnServer(), VM_loadfromdata(), and VM_loadfromfile().
PRVM_ED_ParseEdict()
const char * PRVM_ED_ParseEdict (prvm_prog_t * prog, const char * data, prvm_edict_t * ent)
Definition at line 1276 of file prvm_edict.c.
{
    mdef_t *key;
    qbool anglehack;
    qbool init;
    char keyname[256];
    size_t n;
    init = false;
// go through all the dictionary pairs
    while (1)
    {
    // parse key
        if (!COM_ParseToken_Simple(&data, false, false, true))
            prog->error_cmd("PRVM_ED_ParseEdict: EOF without closing brace");
        if (developer_entityparsing.integer)
            Con_Printf("Key: \"%s\"", com_token);
        if (com_token[0] == '}')
            break;
        // anglehack is to allow QuakeEd to write single scalar angles
        // and allow them to be turned into vectors. (FIXME...)
        if (!strcmp(com_token, "angle"))
        {
            dp_strlcpy (com_token, "angles", sizeof(com_token));
            anglehack = true;
        }
        else
            anglehack = false;
        // FIXME: change light to _light to get rid of this hack
        if (!strcmp(com_token, "light"))
            dp_strlcpy (com_token, "light_lev", sizeof(com_token)); // hack for single light def
        dp_strlcpy (keyname, com_token, sizeof(keyname));
        // another hack to fix keynames with trailing spaces
        n = strlen(keyname);
        while (n && keyname[n-1] == ' ')
        {
            keyname[n-1] = 0;
            n--;
        }
    // parse value
        if (!COM_ParseToken_Simple(&data, false, false, true))
            prog->error_cmd("PRVM_ED_ParseEdict: EOF without closing brace");
        if (developer_entityparsing.integer)
            Con_Printf(" \"%s\"\n", com_token);
        if (com_token[0] == '}')
            prog->error_cmd("PRVM_ED_ParseEdict: closing brace without data");
        init = true;
        // ignore attempts to set key "" (this problem occurs in nehahra neh1m8.bsp)
        if (!keyname[0])
            continue;
// keynames with a leading underscore are used for utility comments,
// and are immediately discarded by quake
        if (keyname[0] == '_')
            continue;
        key = PRVM_ED_FindField (prog, keyname);
        if (!key)
        {
            Con_DPrintf("%s: '%s' is not a field\n", prog->name, keyname);
            continue;
        }
        if (anglehack)
        {
            char    temp[32];
            dp_strlcpy (temp, com_token, sizeof(temp));
            dpsnprintf (com_token, sizeof(com_token), "0 %s 0", temp);
        }
        if (!PRVM_ED_ParseEpair(prog, ent, key, com_token, strcmp(keyname, "wad") != 0))
            prog->error_cmd("PRVM_ED_ParseEdict: parse error");
    }
    if (!init) {
        ent->free = true;
        ent->freetime = host.realtime;
    }
    return data;
}
Referenced by PRVM_ED_LoadFromFile(), SV_Loadgame_f(), and VM_parseentitydata().
PRVM_ED_ParseEpair()
qbool PRVM_ED_ParseEpair (prvm_prog_t * prog, prvm_edict_t * ent, mdef_t * key, const char * s, qbool parsebackslash)
Definition at line 986 of file prvm_edict.c.
{
    int i, l;
    char *new_p;
    mdef_t *def;
    prvm_eval_t *val;
    mfunction_t *func;
    if (ent)
        val = (prvm_eval_t *)(ent->fields.fp + key->ofs);
    else
        val = (prvm_eval_t *)(prog->globals.fp + key->ofs);
    switch (key->type & ~DEF_SAVEGLOBAL)
    {
    case ev_string:
        l = (int)strlen(s) + 1;
        val->string = PRVM_AllocString(prog, l, &new_p);
        for (i = 0;i < l;i++)
        {
            if (s[i] == '\\' && s[i+1] && parsebackslash)
            {
                i++;
                if (s[i] == 'n')
                    *new_p++ = '\n';
                else if (s[i] == 'r')
                    *new_p++ = '\r';
                else
                    *new_p++ = s[i];
            }
            else
                *new_p++ = s[i];
        }
        break;
    case ev_float:
        while (*s && ISWHITESPACE(*s))
            s++;
        val->_float = atof(s);
        break;
    case ev_vector:
        for (i = 0;i < 3;i++)
        {
            while (*s && ISWHITESPACE(*s))
                s++;
            if (!*s)
                break;
            val->vector[i] = atof(s);
            while (!ISWHITESPACE(*s))
                s++;
            if (!*s)
                break;
        }
        break;
    case ev_entity:
        while (*s && ISWHITESPACE(*s))
            s++;
        i = atoi(s);
        if (i >= prog->limit_edicts)
            Con_Printf("PRVM_ED_ParseEpair: ev_entity reference too large (edict %u >= MAX_EDICTS %u) on %s\n", (unsigned int)i, prog->limit_edicts, prog->name);
        while (i >= prog->max_edicts)
            PRVM_MEM_IncreaseEdicts(prog);
        // if IncreaseEdicts was called the base pointer needs to be updated
        if (ent)
            val = (prvm_eval_t *)(ent->fields.fp + key->ofs);
        val->edict = PRVM_EDICT_TO_PROG(PRVM_EDICT_NUM((int)i));
        break;
    case ev_field:
        if (*s != '.')
        {
            Con_DPrintf("PRVM_ED_ParseEpair: Bogus field name %s in %s\n", s, prog->name);
            return false;
        }
        def = PRVM_ED_FindField(prog, s + 1);
        if (!def)
        {
            Con_DPrintf("PRVM_ED_ParseEpair: Can't find field %s in %s\n", s, prog->name);
            return false;
        }
        val->_int = def->ofs;
        break;
    case ev_function:
        func = PRVM_ED_FindFunction(prog, s);
        if (!func)
        {
            Con_Printf("PRVM_ED_ParseEpair: Can't find function %s in %s\n", s, prog->name);
            return false;
        }
        val->function = func - prog->functions;
        break;
    default:
        Con_Printf("PRVM_ED_ParseEpair: Unknown key->type %i for key \"%s\" on %s\n", key->type, PRVM_GetString(prog, key->s_name), prog->name);
        return false;
    }
    return true;
}
Referenced by PRVM_ED_EdictSet_f(), PRVM_ED_ParseEdict(), PRVM_ED_ParseGlobals(), PRVM_GlobalSet_f(), SV_Ent_Create_f(), and VM_putentityfieldstring().
PRVM_ED_ParseGlobals()
void PRVM_ED_ParseGlobals (prvm_prog_t * prog, const char * data)
Definition at line 935 of file prvm_edict.c.
{
    char keyname[MAX_INPUTLINE];
    mdef_t *key;
    while (1)
    {
        // parse key
        if (!COM_ParseToken_Simple(&data, false, false, true))
            prog->error_cmd("PRVM_ED_ParseGlobals: EOF without closing brace");
        if (com_token[0] == '}')
            break;
        if (developer_entityparsing.integer)
            Con_Printf("Key: \"%s\"", com_token);
        dp_strlcpy (keyname, com_token, sizeof(keyname));
        // parse value
        if (!COM_ParseToken_Simple(&data, false, true, true))
            prog->error_cmd("PRVM_ED_ParseGlobals: EOF without closing brace");
        if (developer_entityparsing.integer)
            Con_Printf(" \"%s\"\n", com_token);
        if (com_token[0] == '}')
            prog->error_cmd("PRVM_ED_ParseGlobals: closing brace without data");
        key = PRVM_ED_FindGlobal (prog, keyname);
        if (!key)
        {
            Con_DPrintf("'%s' is not a global on %s\n", keyname, prog->name);
            continue;
        }
        if (!PRVM_ED_ParseEpair(prog, NULL, key, com_token, true))
            prog->error_cmd("PRVM_ED_ParseGlobals: parse error");
    }
}
Referenced by SV_Loadgame_f().
PRVM_ED_Print()
void PRVM_ED_Print (prvm_prog_t * prog, prvm_edict_t * ed, const char * wildcard_fieldname)
Definition at line 652 of file prvm_edict.c.
{
    size_t  l;
    mdef_t  *d;
    prvm_eval_t *val;
    int     i, j;
    const char  *name;
    int     type;
    char    tempstring[MAX_INPUTLINE], tempstring2[260]; // temporary string buffers
    char    valuebuf[MAX_INPUTLINE];
    if (ed->free)
    {
        Con_Printf("%s: FREE\n",prog->name);
        return;
    }
    tempstring[0] = 0;
    dpsnprintf(tempstring, sizeof(tempstring), "\n%s EDICT %i:\n", prog->name, PRVM_NUM_FOR_EDICT(ed));
    for (i = 1;i < prog->numfielddefs;i++)
    {
        d = &prog->fielddefs[i];
        name = PRVM_GetString(prog, d->s_name);
        if(strlen(name) > 1 && name[strlen(name)-2] == '_' && (name[strlen(name)-1] == 'x' || name[strlen(name)-1] == 'y' || name[strlen(name)-1] == 'z'))
            continue;   // skip _x, _y, _z vars
        // Check Field Name Wildcard
        if(wildcard_fieldname)
            if( !matchpattern(name, wildcard_fieldname, 1) )
                // Didn't match; skip
                continue;
        val = (prvm_eval_t *)(ed->fields.fp + d->ofs);
    // if the value is still all 0, skip the field
        type = d->type & ~DEF_SAVEGLOBAL;
        for (j=0 ; j<prvm_type_size[type] ; j++)
            if (val->ivector[j])
                break;
        if (j == prvm_type_size[type])
            continue;
        if (strlen(name) > sizeof(tempstring2)-4)
        {
            memcpy (tempstring2, name, sizeof(tempstring2)-4);
            tempstring2[sizeof(tempstring2)-4] = tempstring2[sizeof(tempstring2)-3] = tempstring2[sizeof(tempstring2)-2] = '.';
            tempstring2[sizeof(tempstring2)-1] = 0;
            name = tempstring2;
        }
        dp_strlcat(tempstring, name, sizeof(tempstring));
        for (l = strlen(name);l < 14;l++)
            dp_strlcat(tempstring, " ", sizeof(tempstring));
        dp_strlcat(tempstring, " ", sizeof(tempstring));
        name = PRVM_ValueString(prog, (etype_t)d->type, val, valuebuf, sizeof(valuebuf));
        if (strlen(name) > sizeof(tempstring2)-4)
        {
            memcpy (tempstring2, name, sizeof(tempstring2)-4);
            tempstring2[sizeof(tempstring2)-4] = tempstring2[sizeof(tempstring2)-3] = tempstring2[sizeof(tempstring2)-2] = '.';
            tempstring2[sizeof(tempstring2)-1] = 0;
            name = tempstring2;
        }
        dp_strlcat(tempstring, name, sizeof(tempstring));
        dp_strlcat(tempstring, "\n", sizeof(tempstring));
        if (strlen(tempstring) >= sizeof(tempstring)/2)
        {
            Con_Print(tempstring);
            tempstring[0] = 0;
        }
    }
    if (tempstring[0])
        Con_Print(tempstring);
}
Referenced by CLVM_ExecuteProgram(), PRVM_ED_CallSpawnFunction(), PRVM_ED_PrintNum(), PRVM_LeakTest(), SVVM_ExecuteProgram(), VM_error(), and VM_objerror().
PRVM_ED_PrintEdicts_f()
void PRVM_ED_PrintEdicts_f (struct cmd_state_s * cmd)
PRVM_ED_PrintNum()
void PRVM_ED_PrintNum (prvm_prog_t * prog, int ent, const char * wildcard_fieldname)
Definition at line 783 of file prvm_edict.c.
{
    PRVM_ED_Print(prog, PRVM_EDICT_NUM(ent), wildcard_fieldname);
}
Referenced by PRVM_ED_PrintEdict_f(), PRVM_ED_PrintEdicts_f(), and VM_eprint().
PRVM_ED_Write()
void PRVM_ED_Write (prvm_prog_t * prog, struct qfile_s * f, prvm_edict_t * ed)
Referenced by SV_Savegame_to(), and VM_writetofile().
PRVM_ED_WriteGlobals()
void PRVM_ED_WriteGlobals (prvm_prog_t * prog, struct qfile_s * f)
Referenced by SV_Savegame_to().
PRVM_EDICT_NUM_ERROR()
unsigned int PRVM_EDICT_NUM_ERROR (prvm_prog_t * prog, unsigned int n, const char * filename, int fileline)
Definition at line 3223 of file prvm_edict.c.
{
    prog->error_cmd("PRVM_EDICT_NUM: %s: bad number %i (called at %s:%i)", prog->name, n, filename, fileline);
    return 0;
}
PRVM_ExplicitCoverageEvent()
void PRVM_ExplicitCoverageEvent (prvm_prog_t * prog, mfunction_t * func, int statement)
Definition at line 892 of file prvm_exec.c.
{
    char vabuf[128];
    ++prog->explicit_covered;
    Con_Printf("prvm_coverage: %s just executed a coverage() statement at %s for the first time. Coverage: %.2f%%.\n", prog->name, PRVM_WhereAmI(vabuf, sizeof(vabuf), prog, func, statement), prog->explicit_covered * 100.0 / prog->numexplicitcoveragestatements);
}
Referenced by VM_coverage().
PRVM_FreeString()
void PRVM_FreeString (prvm_prog_t * prog, int num)
Definition at line 3429 of file prvm_edict.c.
{
    if (num == 0)
        prog->error_cmd("PRVM_FreeString %s: attempt to free a NULL string", prog->name);
    else if (num >= 0 && num < prog->stringssize)
        prog->error_cmd("PRVM_FreeString %s: attempt to free a constant string", prog->name);
    else if (num >= PRVM_KNOWNSTRINGBASE && num < PRVM_KNOWNSTRINGBASE + prog->numknownstrings)
    {
        num = num - PRVM_KNOWNSTRINGBASE;
        if (!prog->knownstrings[num])
            prog->error_cmd("PRVM_FreeString %s: attempt to free a non-existent or already freed string", prog->name);
        if (!prog->knownstrings_flags[num])
            prog->error_cmd("PRVM_FreeString %s: attempt to free a string owned by the engine", prog->name);
        PRVM_Free((char *)prog->knownstrings[num]);
        if(prog->leaktest_active)
            if(prog->knownstrings_origin[num])
                PRVM_Free((char *)prog->knownstrings_origin[num]);
        prog->knownstrings[num] = NULL;
        prog->knownstrings_flags[num] = 0;
        prog->firstfreeknownstring = min(prog->firstfreeknownstring, num);
    }
    else
        prog->error_cmd("PRVM_FreeString %s: invalid string offset %i", prog->name, num);
}
Referenced by VM_strunzone().
PRVM_FriendlyProgFromString()
prvm_prog_t * PRVM_FriendlyProgFromString (const char * str)
Definition at line 179 of file prvm_edict.c.
{
    prvm_prog_t *prog = PRVM_ProgFromString(str);
    if (!prog)
    {
        Con_Printf("%s: unknown program name\n", str);
        return NULL;
    }
    if (!prog->loaded)
    {
        Con_Printf("%s: program is not loaded\n", str);
        return NULL;
    }
    return prog;
}
Referenced by PRVM_Breakpoint_f(), PRVM_CallProfile_f(), PRVM_ChildProfile_f(), PRVM_ED_Count_f(), PRVM_ED_EdictGet_f(), PRVM_ED_EdictSet_f(), PRVM_ED_GlobalGet_f(), PRVM_ED_PrintEdict_f(), PRVM_ED_PrintEdicts_f(), PRVM_EdictWatchpoint_f(), PRVM_Fields_f(), PRVM_GameCommand(), PRVM_Global_f(), PRVM_Globals_f(), PRVM_GlobalSet_f(), PRVM_GlobalWatchpoint_f(), PRVM_PrintFunction_f(), and PRVM_Profile_f().
PRVM_GarbageCollection()
void PRVM_GarbageCollection (prvm_prog_t * prog)
Definition at line 3705 of file prvm_edict.c.
{
    int limit = prvm_garbagecollection_scan_limit.integer;
    prvm_prog_garbagecollection_state_t *gc = &prog->gc;
    if (!prvm_garbagecollection_enable.integer)
        return;
    // philosophy:
    // we like to limit how much scanning we do so it doesn't put a significant
    // burden on the cpu, so each of these are not complete scans, we also like
    // to have consistent cpu usage so we do a bit of work on each category of
    // leaked object every frame
    switch (gc->stage)
    {
    case PRVM_GC_START:
        gc->stage++;
        break;
    case PRVM_GC_GLOBALS_MARK:
        for (; gc->globals_mark_progress < prog->numglobaldefs && (limit--) > 0; gc->globals_mark_progress++)
        {
            mdef_t *d = &prog->globaldefs[gc->globals_mark_progress];
            switch (d->type)
            {
            case ev_string:
                {
                    prvm_int_t s = prog->globals.ip[d->ofs];
                    if (s & PRVM_KNOWNSTRINGBASE)
                    {
                        prvm_int_t num = s - PRVM_KNOWNSTRINGBASE;
                        if (!prog->knownstrings[num])
{
                            // invalid
                            Con_DPrintf("PRVM_GarbageCollection: Found bogus strzone reference in global %i (global name: \"%s\"), erasing reference", d->ofs, PRVM_GetString(prog, d->s_name));
                            prog->globals.ip[d->ofs] = 0;
                            continue;
                        }
                        prog->knownstrings_flags[num] = (prog->knownstrings_flags[num] | KNOWNSTRINGFLAG_GCMARK) & ~KNOWNSTRINGFLAG_GCPRUNE;
                    }
                }
                break;
            default:
                break;
            }
        }
        if (gc->globals_mark_progress >= prog->numglobaldefs)
            gc->stage++;
        break;
    case PRVM_GC_FIELDS_MARK:
        for (; gc->fields_mark_progress < prog->numfielddefs && limit > 0;)
        {
            mdef_t *d = &prog->fielddefs[gc->fields_mark_progress];
            switch (d->type)
            {
            case ev_string:
                //for (gc-> entityindex = 0; entityindex < prog->num_edicts; entityindex++)
                for (;gc->fields_mark_progress_entity < prog->num_edicts && (limit--) > 0;gc->fields_mark_progress_entity++)
                {
                    int entityindex = gc->fields_mark_progress_entity;
                    prvm_int_t s = prog->edictsfields.ip[entityindex * prog->entityfields + d->ofs];
                    if (s & PRVM_KNOWNSTRINGBASE)
                    {
                        prvm_int_t num = s - PRVM_KNOWNSTRINGBASE;
                        if (!prog->knownstrings[num])
{
                            // invalid
                            Con_DPrintf("PRVM_GarbageCollection: Found bogus strzone reference in edict %i field %i (field name: \"%s\"), erasing reference", entityindex, d->ofs, PRVM_GetString(prog, d->s_name));
                            prog->edictsfields.ip[entityindex * prog->entityfields + d->ofs] = 0;
                            continue;
                        }
                        prog->knownstrings_flags[num] = (prog->knownstrings_flags[num] | KNOWNSTRINGFLAG_GCMARK) & ~KNOWNSTRINGFLAG_GCPRUNE;
                    }
                }
                if (gc->fields_mark_progress_entity >= prog->num_edicts)
                {
                    gc->fields_mark_progress_entity = 0;
                    gc->fields_mark_progress++;
                }
                break;
            default:
                gc->fields_mark_progress_entity = 0;
                gc->fields_mark_progress++;
                break;
            }
        }
        if (gc->fields_mark_progress >= prog->numfielddefs)
            gc->stage++;
        break;
    case PRVM_GC_KNOWNSTRINGS_SWEEP:
        // free any strzone'd strings that are not marked
        if (!prvm_garbagecollection_strings.integer)
        {
            gc->stage++;
            break;
        }
        for (;gc->knownstrings_sweep_progress < prog->numknownstrings && (limit--) > 0;gc->knownstrings_sweep_progress++)
        {
            int num = gc->knownstrings_sweep_progress;
            if (prog->knownstrings[num] && (prog->knownstrings_flags[num] & (KNOWNSTRINGFLAG_GCMARK | KNOWNSTRINGFLAG_ENGINE)) == 0)
            {
                if (prog->knownstrings_flags[num] & KNOWNSTRINGFLAG_GCPRUNE)
                {
                    // string has been marked for pruning two passes in a row
                    if (prvm_garbagecollection_notify.integer)
                        Con_DPrintf("prvm_garbagecollection_notify: %s: freeing unreferenced string %i: \"%s\"\n", prog->name, num, prog->knownstrings[num]);
                    Mem_Free((char *)prog->knownstrings[num]);
                    prog->knownstrings[num] = NULL;
                    prog->knownstrings_flags[num] = 0;
                    prog->firstfreeknownstring = min(prog->firstfreeknownstring, num);
                }
                else
                {
                    // mark it for pruning next pass
                    prog->knownstrings_flags[num] |= KNOWNSTRINGFLAG_GCPRUNE;
                }
            }
        }
        if (gc->knownstrings_sweep_progress >= prog->numknownstrings)
            gc->stage++;
        break;
    case PRVM_GC_RESET:
    default:
        memset(gc, 0, sizeof(*gc));
    }
}
Referenced by CL_VM_UpdateView(), MP_Draw(), and SV_Physics().
PRVM_GetString()
const char * PRVM_GetString (prvm_prog_t * prog, int num)
Definition at line 3231 of file prvm_edict.c.
{
    if (num < 0)
    {
        // invalid
        if (prvm_stringdebug.integer)
            VM_Warning(prog, "PRVM_GetString: Invalid string offset (%i < 0)\n", num);
        return "";
    }
    else if (num < prog->stringssize)
    {
        // constant string from progs.dat
        return prog->strings + num;
    }
    else if (num <= prog->stringssize + prog->tempstringsbuf.maxsize)
    {
        // tempstring returned by engine to QC (becomes invalid after returning to engine)
        num -= prog->stringssize;
        if (num < prog->tempstringsbuf.cursize)
            return (char *)prog->tempstringsbuf.data + num;
        else
        {
            if (prvm_stringdebug.integer)
                VM_Warning(prog, "PRVM_GetString: Invalid temp-string offset (%i >= %i prog->tempstringsbuf.cursize)\n", num, prog->tempstringsbuf.cursize);
            return "";
        }
    }
    else if (num & PRVM_KNOWNSTRINGBASE)
    {
        // allocated string
        num = num - PRVM_KNOWNSTRINGBASE;
        if (num >= 0 && num < prog->numknownstrings)
        {
            if (!prog->knownstrings[num])
            {
                if (prvm_stringdebug.integer)
                    VM_Warning(prog, "PRVM_GetString: Invalid zone-string offset (%i has been freed)\n", num);
                return "";
            }
            // refresh the garbage collection on the string - this guards
            // against a certain sort of repeated migration to earlier
            // points in the scan that could otherwise result in the string
            // being freed for being unused
            prog->knownstrings_flags[num] = (prog->knownstrings_flags[num] & ~KNOWNSTRINGFLAG_GCPRUNE) | KNOWNSTRINGFLAG_GCMARK;
            return prog->knownstrings[num];
        }
        else
        {
            if (prvm_stringdebug.integer)
                VM_Warning(prog, "PRVM_GetString: Invalid zone-string offset (%i >= %i)\n", num, prog->numknownstrings);
            return "";
        }
    }
    else
    {
        // invalid string offset
        if (prvm_stringdebug.integer)
            VM_Warning(prog, "PRVM_GetString: Invalid constant-string offset (%i >= %i prog->stringssize)\n", num, prog->stringssize);
        return "";
    }
}
Referenced by CLVM_ExecuteProgram(), FindViewthing(), NetConn_BuildStatusResponse(), PRVM_CallProfile(), PRVM_ED_CallSpawnFunction(), PRVM_ED_FindField(), PRVM_ED_FindFunction(), PRVM_ED_FindGlobal(), PRVM_ED_ParseEpair(), PRVM_ED_Print(), PRVM_ED_Write(), PRVM_ED_WriteGlobals(), PRVM_Fields_f(), PRVM_FunctionCoverageEvent(), PRVM_GarbageCollection(), PRVM_Globals_f(), PRVM_GlobalString(), PRVM_GlobalStringNoContents(), PRVM_IsEdictReferenced(), PRVM_IsEdictRelevant(), PRVM_MarkReferencedEdicts(), PRVM_PrintStatement(), PRVM_Profile(), PRVM_Prog_Load(), PRVM_ShortStackTrace(), PRVM_StackTrace(), PRVM_UglyValueString(), PRVM_ValueString(), PRVM_WhereAmI(), SV_CheckStuck(), SV_CheckVelocity(), SV_Ent_Remove_All_f(), SV_Ent_Remove_f(), SV_PrepareEntityForSending(), SV_PushEntity(), SV_Savegame_to(), SV_SendServerinfo(), SV_SpawnServer(), SV_Status_f(), SV_UnstickEntity(), SV_UpdateToReliableMessages(), SV_WriteClientdataToMessage(), SVVM_ExecuteProgram(), VM_error(), VM_objerror(), VM_SV_droptofloor(), and while().
PRVM_GlobalString()
char * PRVM_GlobalString (prvm_prog_t * prog, int ofs, char * line, size_t linelength)
Definition at line 597 of file prvm_edict.c.
{
    char    *s;
    //size_t    i;
    mdef_t  *def;
    prvm_eval_t *val;
    char valuebuf[MAX_INPUTLINE];
    val = (prvm_eval_t *)&prog->globals.fp[ofs];
    def = PRVM_ED_GlobalAtOfs(prog, ofs);
    if (!def)
        dpsnprintf (line, linelength, "GLOBAL%i", ofs);
    else
    {
        s = PRVM_ValueString (prog, (etype_t)def->type, val, valuebuf, sizeof(valuebuf));
        dpsnprintf (line, linelength, "%s (=%s)", PRVM_GetString(prog, def->s_name), s);
    }
    //i = strlen(line);
    //for ( ; i<20 ; i++)
    //  strcat (line," ");
    //strcat (line," ");
    return line;
}
Referenced by PRVM_PrintStatement().
PRVM_GlobalStringNoContents()
char * PRVM_GlobalStringNoContents (prvm_prog_t * prog, int ofs, char * line, size_t linelength)
Definition at line 623 of file prvm_edict.c.
{
    //size_t    i;
    mdef_t  *def;
    def = PRVM_ED_GlobalAtOfs(prog, ofs);
    if (!def)
        dpsnprintf (line, linelength, "GLOBAL%i", ofs);
    else
        dpsnprintf (line, linelength, "%s", PRVM_GetString(prog, def->s_name));
    //i = strlen(line);
    //for ( ; i<20 ; i++)
    //  strcat (line," ");
    //strcat (line," ");
    return line;
}
PRVM_Init()
void PRVM_Init (void)
Definition at line 3148 of file prvm_edict.c.
{
    unsigned int i;
    Cmd_AddCommand(CF_SHARED, "prvm_edict", PRVM_ED_PrintEdict_f, "print all data about an entity number in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_edicts", PRVM_ED_PrintEdicts_f, "prints all data about all entities in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_edictcount", PRVM_ED_Count_f, "prints number of active entities in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_profile", PRVM_Profile_f, "prints execution statistics about the most used QuakeC functions in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_childprofile", PRVM_ChildProfile_f, "prints execution statistics about the most used QuakeC functions in the selected VM (server, client, menu), sorted by time taken in function with child calls");
    Cmd_AddCommand(CF_SHARED, "prvm_callprofile", PRVM_CallProfile_f, "prints execution statistics about the most time consuming QuakeC calls from the engine in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_fields", PRVM_Fields_f, "prints usage statistics on properties (how many entities have non-zero values) in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_globals", PRVM_Globals_f, "prints all global variables in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_global", PRVM_Global_f, "prints value of a specified global variable in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_globalset", PRVM_GlobalSet_f, "sets value of a specified global variable in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_edictset", PRVM_ED_EdictSet_f, "changes value of a specified property of a specified entity in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "prvm_edictget", PRVM_ED_EdictGet_f, "retrieves the value of a specified property of a specified entity in the selected VM (server, client menu) into a cvar or to the console");
    Cmd_AddCommand(CF_SHARED, "prvm_globalget", PRVM_ED_GlobalGet_f, "retrieves the value of a specified global variable in the selected VM (server, client menu) into a cvar or to the console");
    Cmd_AddCommand(CF_SHARED, "prvm_printfunction", PRVM_PrintFunction_f, "prints a disassembly (QuakeC instructions) of the specified function in the selected VM (server, client, menu)");
    Cmd_AddCommand(CF_SHARED, "cl_cmd", PRVM_GameCommand_Client_f, "calls the client QC function GameCommand with the supplied string as argument");
    Cmd_AddCommand(CF_SHARED, "menu_cmd", PRVM_GameCommand_Menu_f, "calls the menu QC function GameCommand with the supplied string as argument");
    Cmd_AddCommand(CF_SHARED, "sv_cmd", PRVM_GameCommand_Server_f, "calls the server QC function GameCommand with the supplied string as argument");
    Cmd_AddCommand(CF_SHARED, "prvm_breakpoint", PRVM_Breakpoint_f, "marks a statement or function as breakpoint (when this is executed, a stack trace is printed); to actually halt and investigate state, combine this with a gdb breakpoint on PRVM_Breakpoint, or with prvm_breakpointdump; run with just progs name to clear breakpoint");
    Cmd_AddCommand(CF_SHARED, "prvm_globalwatchpoint", PRVM_GlobalWatchpoint_f, "marks a global as watchpoint (when this is executed, a stack trace is printed); to actually halt and investigate state, combine this with a gdb breakpoint on PRVM_Breakpoint, or with prvm_breakpointdump; run with just progs name to clear watchpoint");
    Cmd_AddCommand(CF_SHARED, "prvm_edictwatchpoint", PRVM_EdictWatchpoint_f, "marks an entity field as watchpoint (when this is executed, a stack trace is printed); to actually halt and investigate state, combine this with a gdb breakpoint on PRVM_Breakpoint, or with prvm_breakpointdump; run with just progs name to clear watchpoint");
    Cvar_RegisterVariable (&prvm_language);
    Cvar_RegisterVariable (&prvm_traceqc);
    Cvar_RegisterVariable (&prvm_statementprofiling);
    Cvar_RegisterVariable (&prvm_timeprofiling);
    Cvar_RegisterVariable (&prvm_coverage);
    Cvar_RegisterVariable (&prvm_backtraceforwarnings);
    Cvar_RegisterVariable (&prvm_leaktest);
    Cvar_RegisterVariable (&prvm_leaktest_follow_targetname);
    Cvar_RegisterVariable (&prvm_leaktest_ignore_classnames);
    Cvar_RegisterVariable (&prvm_errordump);
    Cvar_RegisterVariable (&prvm_breakpointdump);
    Cvar_RegisterVariable (&prvm_reuseedicts_startuptime);
    Cvar_RegisterVariable (&prvm_reuseedicts_neverinsameframe);
    Cvar_RegisterVariable (&prvm_garbagecollection_enable);
    Cvar_RegisterVariable (&prvm_garbagecollection_notify);
    Cvar_RegisterVariable (&prvm_garbagecollection_scan_limit);
    Cvar_RegisterVariable (&prvm_garbagecollection_strings);
    Cvar_RegisterVariable (&prvm_stringdebug);
    // COMMANDLINEOPTION: PRVM: -norunaway disables the runaway loop check (it might be impossible to exit DarkPlaces if used!)
    prvm_runawaycheck = !Sys_CheckParm("-norunaway");
    //VM_Cmd_Init();
    // LadyHavoc: report supported extensions
    Con_DPrintf("\nQuakeC extensions for server and client:");
    for (i = 0; vm_sv_extensions[i]; i++)
        Con_DPrintf(" %s", vm_sv_extensions[i]);
    Con_DPrintf("\n");
#ifdef CONFIG_MENU
    Con_DPrintf("\nQuakeC extensions for menu:");
    for (i = 0; vm_m_extensions[i]; i++)
        Con_DPrintf(" %s", vm_m_extensions[i]);
    Con_DPrintf("\n");
#endif
}
Referenced by Host_Init().
PRVM_Init_Exec()
void PRVM_Init_Exec (prvm_prog_t * prog)
Definition at line 860 of file prvm_exec.c.
{
    // dump the stack
    prog->depth = 0;
    prog->localstack_used = 0;
    // reset the string table
    // nothing here yet
}
Referenced by PRVM_Prog_Load().
PRVM_MEM_IncreaseEdicts()
void PRVM_MEM_IncreaseEdicts (prvm_prog_t * prog)
Definition at line 100 of file prvm_edict.c.
{
    int     i;
    if(prog->max_edicts >= prog->limit_edicts)
        return;
    prog->begin_increase_edicts(prog);
    // increase edicts
    prog->max_edicts = min(prog->max_edicts + 256, prog->limit_edicts);
    prog->entityfieldsarea = prog->entityfields * prog->max_edicts;
    prog->edictsfields.fp = (prvm_vec_t*)Mem_Realloc(prog->progs_mempool, (void *)prog->edictsfields.fp, prog->entityfieldsarea * sizeof(prvm_vec_t));
    prog->edictprivate = (void *)Mem_Realloc(prog->progs_mempool, (void *)prog->edictprivate, prog->max_edicts * prog->edictprivate_size);
    //set e and v pointers
    for(i = 0; i < prog->max_edicts; i++)
    {
        prog->edicts[i].priv.required  = (prvm_edict_private_t *)((unsigned char  *)prog->edictprivate + i * prog->edictprivate_size);
        prog->edicts[i].fields.fp = prog->edictsfields.fp + i * prog->entityfields;
    }
    prog->end_increase_edicts(prog);
}
Referenced by PRVM_ED_Alloc(), PRVM_ED_ParseEpair(), and SV_Loadgame_f().
PRVM_PrintFunction_f()
void PRVM_PrintFunction_f (struct cmd_state_s * cmd)
Referenced by PRVM_Init().
PRVM_PrintFunctionStatements()
void PRVM_PrintFunctionStatements (prvm_prog_t * prog, const char * name)
Definition at line 342 of file prvm_exec.c.
{
    int i, firststatement, endstatement;
    mfunction_t *func;
    func = PRVM_ED_FindFunction (prog, name);
    if (!func)
    {
        Con_Printf("%s progs: no function named %s\n", prog->name, name);
        return;
    }
    firststatement = func->first_statement;
    if (firststatement < 0)
    {
        Con_Printf("%s progs: function %s is builtin #%i\n", prog->name, name, -firststatement);
        return;
    }
    // find the end statement
    endstatement = prog->numstatements;
    for (i = 0;i < prog->numfunctions;i++)
        if (endstatement > prog->functions[i].first_statement && firststatement < prog->functions[i].first_statement)
            endstatement = prog->functions[i].first_statement;
    // now print the range of statements
    Con_Printf("%s progs: disassembly of function %s (statements %i-%i, locals %i-%i):\n", prog->name, name, firststatement, endstatement, func->parm_start, func->parm_start + func->locals - 1);
    prog->xfunction = func;
    for (i = firststatement;i < endstatement;i++)
    {
        PRVM_PrintStatement(prog, prog->statements + i);
        if (!(prvm_coverage.integer & 4))
            prog->statement_profile[i] = 0;
    }
    if (prvm_coverage.integer & 4)
        Con_Printf("Collecting statement coverage, not flushing statement profile.\n");
}
Referenced by PRVM_PrintFunction_f().
PRVM_PrintState()
void PRVM_PrintState (prvm_prog_t * prog, int stack_index)
Definition at line 694 of file prvm_exec.c.
{
    int i;
    mfunction_t *func = prog->xfunction;
    int st = prog->xstatement;
    if (stack_index > 0 && stack_index <= prog->depth)
    {
        func = prog->stack[prog->depth - stack_index].f;
        st = prog->stack[prog->depth - stack_index].s;
    }
    if (prog->statestring)
    {
        Con_Printf("Caller-provided information: %s\n", prog->statestring);
    }
    if (func)
    {
        for (i = -7; i <= 0;i++)
            if (st + i >= func->first_statement)
                PRVM_PrintStatement(prog, prog->statements + st + i);
    }
    PRVM_StackTrace(prog);
}
Referenced by PRVM_Breakpoint(), PRVM_Crash(), and VM_Warning().
PRVM_Profile()
void PRVM_Profile (prvm_prog_t * prog, int maxfunctions, double mintime, int sortby)
Definition at line 507 of file prvm_exec.c.
{
    mfunction_t *f, *best;
    int i, num;
    double max;
    if(!prvm_timeprofiling.integer)
        mintime *= 10000000; // count each statement as about 0.1s
    if(prvm_timeprofiling.integer)
        Con_Printf( "%s Profile:\n[CallCount]      [Time] [BuiltinTm] [Statement] [BuiltinCt] [TimeTotal] [StmtTotal] [BltnTotal] [self]\n", prog->name );
        //                        12345678901 12345678901 12345678901 12345678901 12345678901 12345678901 12345678901 123.45%
    else
        Con_Printf( "%s Profile:\n[CallCount] [Statement] [BuiltinCt] [StmtTotal] [BltnTotal] [self]\n", prog->name );
        //                        12345678901 12345678901 12345678901 12345678901 12345678901 123.45%
    num = 0;
    do
    {
        max = 0;
        best = NULL;
        for (i=0 ; i<prog->numfunctions ; i++)
        {
            f = &prog->functions[i];
            if(prvm_timeprofiling.integer)
            {
                if(sortby)
                {
                    if(f->first_statement < 0)
                    {
                        if (max < f->tprofile)
{
                            max = f->tprofile;
                            best = f;
                        }
                    }
                    else
                    {
                        if (max < f->tprofile_total)
{
                            max = f->tprofile_total;
                            best = f;
                        }
                    }
                }
                else
                {
                    if (max < f->tprofile + f->tbprofile)
                    {
                        max = f->tprofile + f->tbprofile;
                        best = f;
                    }
                }
            }
            else
            {
                if(sortby)
                {
                    if (max < f->profile_total + f->builtinsprofile_total + f->callcount)
                    {
                        max = f->profile_total + f->builtinsprofile_total + f->callcount;
                        best = f;
                    }
                }
                else
                {
                    if (max < f->profile + f->builtinsprofile + f->callcount)
                    {
                        max = f->profile + f->builtinsprofile + f->callcount;
                        best = f;
                    }
                }
            }
        }
        if (best)
        {
            if (num < maxfunctions && max > mintime)
            {
                if(prvm_timeprofiling.integer)
                {
                    if (best->first_statement < 0)
                        Con_Printf("%11.0f %11.6f ------------- builtin ------------- %11.6f ----------- builtin ----------- %s\n", best->callcount, best->tprofile, best->tprofile, PRVM_GetString(prog, best->s_name));
                    //                 %11.6f 12345678901 12345678901 12345678901 %11.6f 12345678901 12345678901 123.45%
                    else
                        Con_Printf("%11.0f %11.6f %11.6f %11.0f %11.0f %11.6f %11.0f %11.0f %6.2f%% %s\n", best->callcount, best->tprofile, best->tbprofile, best->profile, best->builtinsprofile, best->tprofile_total, best->profile_total, best->builtinsprofile_total, (best->tprofile_total > 0) ? ((best->tprofile) * 100.0 / (best->tprofile_total)) : -99.99, PRVM_GetString(prog, best->s_name));
                }
                else
                {
                    if (best->first_statement < 0)
                        Con_Printf("%11.0f ----------------------- builtin ----------------------- %s\n", best->callcount, PRVM_GetString(prog, best->s_name));
                    //                 12345678901 12345678901 12345678901 12345678901 123.45%
                    else
                        Con_Printf("%11.0f %11.0f %11.0f %11.0f %11.0f %6.2f%% %s\n", best->callcount, best->profile, best->builtinsprofile, best->profile_total, best->builtinsprofile_total, (best->profile + best->builtinsprofile) * 100.0 / (best->profile_total + best->builtinsprofile_total), PRVM_GetString(prog, best->s_name));
                }
            }
            num++;
            best->profile = 0;
            best->tprofile = 0;
            best->tbprofile = 0;
            best->builtinsprofile = 0;
            best->profile_total = 0;
            best->tprofile_total = 0;
            best->builtinsprofile_total = 0;
            best->callcount = 0;
        }
    } while (best);
}
Referenced by PRVM_ChildProfile_f(), PRVM_Profile_f(), and while().
PRVM_Profile_f()
void PRVM_Profile_f (struct cmd_state_s * cmd)
Referenced by PRVM_Init().
PRVM_Prog_Init()
void PRVM_Prog_Init (prvm_prog_t * prog, struct cmd_state_s * cmd)
Referenced by CL_VM_Init(), MP_Init(), and SV_VM_Setup().
PRVM_Prog_Load()
void PRVM_Prog_Load (prvm_prog_t * prog, const char * filename, unsigned char * data, int64_t size, int numrequiredfunc, const char ** required_func, int numrequiredfields, prvm_required_field_t * required_field, int numrequiredglobals, prvm_required_field_t * required_global)
Definition at line 2002 of file prvm_edict.c.
{
    int i;
    dprograms_t *dprograms;
    dstatement16_t *instatements16;
    dstatement32_t *instatements32;
    ddef16_t *infielddefs16;
    ddef32_t *infielddefs32;
    ddef16_t *inglobaldefs16;
    ddef32_t *inglobaldefs32;
    int *inglobals;
    dfunction_t *infunctions;
    char *instrings;
    fs_offset_t filesize;
    int requiredglobalspace;
    opcode_t op;
    int a;
    int b;
    int c;
    union
    {
        unsigned int i;
        float f;
    }
    u;
    unsigned int d;
    char vabuf[1024];
    char vabuf2[1024];
    cvar_t *cvar;
    int structtype = 0;
    if (prog->loaded)
        prog->error_cmd("%s: there is already a %s program loaded!", __func__, prog->name);
    Host_LockSession(); // all progs can use the session cvar
    Crypto_LoadKeys(); // all progs might use the keys at init time
    if (data)
    {
        dprograms = (dprograms_t *) data;
        filesize = size;
    }
    else
        dprograms = (dprograms_t *)FS_LoadFile (filename, prog->progs_mempool, false, &filesize);
    if (dprograms == NULL || filesize < (fs_offset_t)sizeof(dprograms_t))
        prog->error_cmd("%s: couldn't load \"%s\" for %s", __func__, filename, prog->name);
    // TODO bounds check header fields (e.g. numstatements), they must never go behind end of file
    prog->profiletime = Sys_DirtyTime();
    prog->starttime = host.realtime;
    requiredglobalspace = 0;
    for (i = 0;i < numrequiredglobals;i++)
        requiredglobalspace += required_global[i].type == ev_vector ? 3 : 1;
    prog->filecrc = CRC_Block((unsigned char *)dprograms, filesize);
// byte swap the header
    prog->progs_version = LittleLong(dprograms->version);
    prog->progs_crc = LittleLong(dprograms->crc);
    if (prog->progs_version == 7)
    {
        dprograms_v7_t *v7 = (dprograms_v7_t*)dprograms;
        structtype = LittleLong(v7->secondaryversion);
        if (structtype == PROG_SECONDARYVERSION16 ||
            structtype == PROG_SECONDARYVERSION32) // barely supported
            Con_Printf(CON_WARN "WARNING: %s: %s targets FTEQW, for which support is incomplete. Proceed at your own risk.\n", prog->name, filename);
        else
            prog->error_cmd("%s: %s targets unknown engine", prog->name, filename);
        if (v7->numbodylessfuncs != 0 || v7->numtypes != 0 || v7->blockscompressed != 0)
            prog->error_cmd("%s: %s uses unsupported features.", prog->name, filename);
    }
    else if (prog->progs_version != PROG_VERSION)
        prog->error_cmd("%s: %s has wrong version number (%i should be %i)", prog->name, filename, prog->progs_version, PROG_VERSION);
    instatements16 = (dstatement16_t *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_statements));
    instatements32 = (dstatement32_t *)instatements16;
    prog->progs_numstatements = LittleLong(dprograms->numstatements);
    inglobaldefs16 = (ddef16_t *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_globaldefs));
    inglobaldefs32 = (ddef32_t *)inglobaldefs16;
    prog->progs_numglobaldefs = LittleLong(dprograms->numglobaldefs);
    infielddefs16 = (ddef16_t *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_fielddefs));
    infielddefs32 = (ddef32_t *)infielddefs16;
    prog->progs_numfielddefs = LittleLong(dprograms->numfielddefs);
    infunctions = (dfunction_t *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_functions));
    prog->progs_numfunctions = LittleLong(dprograms->numfunctions);
    instrings = (char *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_strings));
    prog->progs_numstrings = LittleLong(dprograms->numstrings);
    inglobals = (int *)((unsigned char *)dprograms + LittleLong(dprograms->ofs_globals));
    prog->progs_numglobals = LittleLong(dprograms->numglobals);
    prog->progs_entityfields = LittleLong(dprograms->entityfields);
    prog->numstatements = prog->progs_numstatements;
    prog->numglobaldefs = prog->progs_numglobaldefs;
    prog->numfielddefs = prog->progs_numfielddefs;
    prog->numfunctions = prog->progs_numfunctions;
    prog->numstrings = prog->progs_numstrings;
    prog->numglobals = prog->progs_numglobals;
    prog->entityfields = prog->progs_entityfields;
    if (LittleLong(dprograms->ofs_strings) + prog->progs_numstrings > (int)filesize)
        prog->error_cmd("%s: %s strings go past end of file", prog->name, filename);
    prog->strings = (char *)Mem_Alloc(prog->progs_mempool, prog->progs_numstrings);
    memcpy(prog->strings, instrings, prog->progs_numstrings);
    prog->stringssize = prog->progs_numstrings;
    prog->numknownstrings = 0;
    prog->maxknownstrings = 0;
    prog->knownstrings = NULL;
    prog->knownstrings_flags = NULL;
    Mem_ExpandableArray_NewArray(&prog->stringbuffersarray, prog->progs_mempool, sizeof(prvm_stringbuffer_t), 64);
    // we need to expand the globaldefs and fielddefs to include engine defs
    prog->globaldefs = (mdef_t *)Mem_Alloc(prog->progs_mempool, (prog->progs_numglobaldefs + numrequiredglobals) * sizeof(mdef_t));
    prog->globals.fp = (prvm_vec_t *)Mem_Alloc(prog->progs_mempool, (prog->progs_numglobals + requiredglobalspace + 2) * sizeof(prvm_vec_t));
        // + 2 is because of an otherwise occurring overrun in RETURN instruction
        // when trying to return the last or second-last global
        // (RETURN always returns a vector, there is no RETURN_F instruction)
    prog->fielddefs = (mdef_t *)Mem_Alloc(prog->progs_mempool, (prog->progs_numfielddefs + numrequiredfields) * sizeof(mdef_t));
    // we need to convert the statements to our memory format
    prog->statements = (mstatement_t *)Mem_Alloc(prog->progs_mempool, prog->progs_numstatements * sizeof(mstatement_t));
    // allocate space for profiling statement usage
    prog->statement_profile = (double *)Mem_Alloc(prog->progs_mempool, prog->progs_numstatements * sizeof(*prog->statement_profile));
    prog->explicit_profile = (double *)Mem_Alloc(prog->progs_mempool, prog->progs_numstatements * sizeof(*prog->statement_profile));
    // functions need to be converted to the memory format
    prog->functions = (mfunction_t *)Mem_Alloc(prog->progs_mempool, sizeof(mfunction_t) * prog->progs_numfunctions);
    for (i = 0;i < prog->progs_numfunctions;i++)
    {
        prog->functions[i].first_statement = LittleLong(infunctions[i].first_statement);
        prog->functions[i].parm_start = LittleLong(infunctions[i].parm_start);
        prog->functions[i].s_name = LittleLong(infunctions[i].s_name);
        prog->functions[i].s_file = LittleLong(infunctions[i].s_file);
        prog->functions[i].numparms = LittleLong(infunctions[i].numparms);
        prog->functions[i].locals = LittleLong(infunctions[i].locals);
        memcpy(prog->functions[i].parm_size, infunctions[i].parm_size, sizeof(infunctions[i].parm_size));
        if(prog->functions[i].first_statement >= prog->numstatements)
            prog->error_cmd("%s: out of bounds function statement (function %d) in %s", __func__, i, prog->name);
        // TODO bounds check parm_start, s_name, s_file, numparms, locals, parm_size
    }
    // copy the globaldefs to the new globaldefs list
    switch(structtype)
    {
    case PROG_SECONDARYVERSION32:
        for (i=0 ; i<prog->numglobaldefs ; i++)
        {
            prog->globaldefs[i].type = LittleLong(inglobaldefs32[i].type);
            prog->globaldefs[i].ofs = LittleLong(inglobaldefs32[i].ofs);
            prog->globaldefs[i].s_name = LittleLong(inglobaldefs32[i].s_name);
            // TODO bounds check ofs, s_name
        }
        break;
    default:
        for (i=0 ; i<prog->numglobaldefs ; i++)
        {
            prog->globaldefs[i].type = (unsigned short)LittleShort(inglobaldefs16[i].type);
            prog->globaldefs[i].ofs = (unsigned short)LittleShort(inglobaldefs16[i].ofs);
            prog->globaldefs[i].s_name = LittleLong(inglobaldefs16[i].s_name);
            // TODO bounds check ofs, s_name
        }
        break;
    }
    // append the required globals
    for (i = 0;i < numrequiredglobals;i++)
    {
        prog->globaldefs[prog->numglobaldefs].type = required_global[i].type;
        prog->globaldefs[prog->numglobaldefs].ofs = prog->numglobals;
        prog->globaldefs[prog->numglobaldefs].s_name = PRVM_SetEngineString(prog, required_global[i].name);
        if (prog->globaldefs[prog->numglobaldefs].type == ev_vector)
            prog->numglobals += 3;
        else
            prog->numglobals++;
        prog->numglobaldefs++;
    }
    // copy the progs fields to the new fields list
    switch(structtype)
    {
    case PROG_SECONDARYVERSION32:
        for (i = 0;i < prog->numfielddefs;i++)
        {
            prog->fielddefs[i].type = LittleLong(infielddefs32[i].type);
            if (prog->fielddefs[i].type & DEF_SAVEGLOBAL)
                prog->error_cmd("%s: prog->fielddefs[i].type & DEF_SAVEGLOBAL in %s", __func__, prog->name);
            prog->fielddefs[i].ofs = LittleLong(infielddefs32[i].ofs);
            prog->fielddefs[i].s_name = LittleLong(infielddefs32[i].s_name);
            // TODO bounds check ofs, s_name
        }
        break;
    default:
        for (i = 0;i < prog->numfielddefs;i++)
        {
            prog->fielddefs[i].type = (unsigned short)LittleShort(infielddefs16[i].type);
            if (prog->fielddefs[i].type & DEF_SAVEGLOBAL)
                prog->error_cmd("%s: prog->fielddefs[i].type & DEF_SAVEGLOBAL in %s", __func__, prog->name);
            prog->fielddefs[i].ofs = (unsigned short)LittleShort(infielddefs16[i].ofs);
            prog->fielddefs[i].s_name = LittleLong(infielddefs16[i].s_name);
            // TODO bounds check ofs, s_name
        }
        break;
    }
    // append the required fields
    for (i = 0;i < numrequiredfields;i++)
    {
        prog->fielddefs[prog->numfielddefs].type = required_field[i].type;
        prog->fielddefs[prog->numfielddefs].ofs = prog->entityfields;
        prog->fielddefs[prog->numfielddefs].s_name = PRVM_SetEngineString(prog, required_field[i].name);
        if (prog->fielddefs[prog->numfielddefs].type == ev_vector)
            prog->entityfields += 3;
        else
            prog->entityfields++;
        prog->numfielddefs++;
    }
    // LadyHavoc: TODO: reorder globals to match engine struct
    // LadyHavoc: TODO: reorder fields to match engine struct
#define remapglobal(index) (index)
#define remapfield(index) (index)
    // copy globals
    // FIXME: LadyHavoc: this uses a crude way to identify integer constants, rather than checking for matching globaldefs and checking their type
    for (i = 0;i < prog->progs_numglobals;i++)
    {
        u.i = LittleLong(inglobals[i]);
        // most globals are 0, we only need to deal with the ones that are not
        if (u.i)
        {
            d = u.i & 0xFF800000;
            if ((d == 0xFF800000) || (d == 0))
            {
                // Looks like an integer (expand to int64)
                prog->globals.ip[remapglobal(i)] = u.i;
            }
            else
            {
                // Looks like a float (expand to double)
                prog->globals.fp[remapglobal(i)] = u.f;
            }
        }
    }
    // copy, remap globals in statements, bounds check
    for (i = 0;i < prog->progs_numstatements;i++)
    {
        switch(structtype)
        {
        case PROG_SECONDARYVERSION32:
            op = (opcode_t)LittleLong(instatements32[i].op);
            a = (unsigned int)LittleLong(instatements32[i].a);
            b = (unsigned int)LittleLong(instatements32[i].b);
            c = (unsigned int)LittleLong(instatements32[i].c);
            break;
        default:
            op = (opcode_t)LittleShort(instatements16[i].op);
            a = (unsigned short)LittleShort(instatements16[i].a);
            b = (unsigned short)LittleShort(instatements16[i].b);
            c = (unsigned short)LittleShort(instatements16[i].c);
            break;
        }
        switch (op)
        {
        case OP_IF:
        case OP_IFNOT:
            b = (short)b;
            if (a >= prog->progs_numglobals || b + i < 0 || b + i >= prog->progs_numstatements)
                prog->error_cmd("%s: out of bounds IF/IFNOT (statement %d) in %s", __func__, i, prog->name);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = remapglobal(a);
            prog->statements[i].operand[1] = -1;
            prog->statements[i].operand[2] = -1;
            prog->statements[i].jumpabsolute = i + b;
            break;
        case OP_GOTO:
            a = (short)a;
            if (a + i < 0 || a + i >= prog->progs_numstatements)
                prog->error_cmd("%s: out of bounds GOTO (statement %d) in %s", __func__, i, prog->name);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = -1;
            prog->statements[i].operand[1] = -1;
            prog->statements[i].operand[2] = -1;
            prog->statements[i].jumpabsolute = i + a;
            break;
        default:
            Con_DPrintf("%s: unknown opcode %d at statement %d in %s\n", __func__, (int)op, i, prog->name);
            //make sure its something well defined.
            prog->statements[i].op = OP_BOUNDCHECK;
            prog->statements[i].operand[0] = 0;
            prog->statements[i].operand[1] =
            prog->statements[i].operand[2] = op;
            prog->statements[i].jumpabsolute = -1;
            break;
        case OP_STORE_I:
        case OP_ADD_I:
        case OP_ADD_FI:
        case OP_ADD_IF:
        case OP_SUB_I:
        case OP_SUB_FI:
        case OP_SUB_IF:
        case OP_CONV_IF:
        case OP_CONV_FI:
        case OP_LOAD_I:
        case OP_STOREP_I:
        case OP_BITAND_I:
        case OP_BITOR_I:
        case OP_MUL_I:
        case OP_DIV_I:
        case OP_EQ_I:
        case OP_NE_I:
        case OP_NOT_I:
        case OP_DIV_VF:
        case OP_STORE_P:
        case OP_LE_I:
        case OP_GE_I:
        case OP_LT_I:
        case OP_GT_I:
        case OP_LE_IF:
        case OP_GE_IF:
        case OP_LT_IF:
        case OP_GT_IF:
        case OP_LE_FI:
        case OP_GE_FI:
        case OP_LT_FI:
        case OP_GT_FI:
        case OP_EQ_IF:
        case OP_EQ_FI:
        case OP_MUL_IF:
        case OP_MUL_FI:
        case OP_MUL_VI:
        case OP_DIV_IF:
        case OP_DIV_FI:
        case OP_BITAND_IF:
        case OP_BITOR_IF:
        case OP_BITAND_FI:
        case OP_BITOR_FI:
        case OP_AND_I:
        case OP_OR_I:
        case OP_AND_IF:
        case OP_OR_IF:
        case OP_AND_FI:
        case OP_OR_FI:
        case OP_NE_IF:
        case OP_NE_FI:
        case OP_GSTOREP_I:
        case OP_GSTOREP_F:
        case OP_GSTOREP_ENT:
        case OP_GSTOREP_FLD:
        case OP_GSTOREP_S:
        case OP_GSTOREP_FNC:
        case OP_GSTOREP_V:
//      case OP_GADDRESS:
        case OP_GLOAD_I:
        case OP_GLOAD_F:
        case OP_GLOAD_FLD:
        case OP_GLOAD_ENT:
        case OP_GLOAD_S:
        case OP_GLOAD_FNC:
        case OP_BOUNDCHECK:
        case OP_GLOAD_V:
        // global global global
        case OP_ADD_F:
        case OP_ADD_V:
        case OP_SUB_F:
        case OP_SUB_V:
        case OP_MUL_F:
        case OP_MUL_V:
        case OP_MUL_FV:
        case OP_MUL_VF:
        case OP_DIV_F:
        case OP_BITAND:
        case OP_BITOR:
        case OP_GE:
        case OP_LE:
        case OP_GT:
        case OP_LT:
        case OP_AND:
        case OP_OR:
        case OP_EQ_F:
        case OP_EQ_V:
        case OP_EQ_S:
        case OP_EQ_E:
        case OP_EQ_FNC:
        case OP_NE_F:
        case OP_NE_V:
        case OP_NE_S:
        case OP_NE_E:
        case OP_NE_FNC:
        case OP_ADDRESS:
        case OP_LOAD_F:
        case OP_LOAD_FLD:
        case OP_LOAD_ENT:
        case OP_LOAD_S:
        case OP_LOAD_FNC:
        case OP_LOAD_V:
            if (a >= prog->progs_numglobals || b >= prog->progs_numglobals || c >= prog->progs_numglobals)
                prog->error_cmd("%s: out of bounds global index (statement %d)", __func__, i);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = remapglobal(a);
            prog->statements[i].operand[1] = remapglobal(b);
            prog->statements[i].operand[2] = remapglobal(c);
            prog->statements[i].jumpabsolute = -1;
            break;
        // global none global
        case OP_NOT_F:
        case OP_NOT_V:
        case OP_NOT_S:
        case OP_NOT_FNC:
        case OP_NOT_ENT:
            if (a >= prog->progs_numglobals || c >= prog->progs_numglobals)
                prog->error_cmd("%s: out of bounds global index (statement %d) in %s", __func__, i, prog->name);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = remapglobal(a);
            prog->statements[i].operand[1] = -1;
            prog->statements[i].operand[2] = remapglobal(c);
            prog->statements[i].jumpabsolute = -1;
            break;
        // 2 globals
        case OP_STOREP_F:
        case OP_STOREP_ENT:
        case OP_STOREP_FLD:
        case OP_STOREP_S:
        case OP_STOREP_FNC:
            if (c)  //Spike -- DP is alergic to pointers in QC. Try to avoid too many nasty surprises.
                Con_DPrintf("%s: storep-with-offset is not permitted in %s\n", __func__, prog->name);
            //fallthrough
        case OP_STORE_F:
        case OP_STORE_ENT:
        case OP_STORE_FLD:
        case OP_STORE_S:
        case OP_STORE_FNC:
        case OP_STATE:
        case OP_STOREP_V:
        case OP_STORE_V:
            if (a >= prog->progs_numglobals || b >= prog->progs_numglobals)
                prog->error_cmd("%s: out of bounds global index (statement %d) in %s", __func__, i, prog->name);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = remapglobal(a);
            prog->statements[i].operand[1] = remapglobal(b);
            prog->statements[i].operand[2] = -1;
            prog->statements[i].jumpabsolute = -1;
            break;
        // 1 global
        case OP_CALL0:
            if ( a < prog->progs_numglobals)
                if ( prog->globals.ip[remapglobal(a)] >= 0 )
                    if ( prog->globals.ip[remapglobal(a)] < prog->progs_numfunctions )
                        if ( prog->functions[prog->globals.ip[remapglobal(a)]].first_statement == -642 )
                            ++prog->numexplicitcoveragestatements;
        case OP_CALL1:
        case OP_CALL2:
        case OP_CALL3:
        case OP_CALL4:
        case OP_CALL5:
        case OP_CALL6:
        case OP_CALL7:
        case OP_CALL8:
        case OP_DONE:
        case OP_RETURN:
            if ( a >= prog->progs_numglobals)
                prog->error_cmd("%s: out of bounds global index (statement %d) in %s", __func__, i, prog->name);
            if (b || c) //Spike -- added this check just as a diagnostic...
                Con_DPrintf("%s: unexpected offset on call opcode in %s. Hexen2 format is not supported\n", __func__, prog->name);
            prog->statements[i].op = op;
            prog->statements[i].operand[0] = remapglobal(a);
            prog->statements[i].operand[1] = -1;
            prog->statements[i].operand[2] = -1;
            prog->statements[i].jumpabsolute = -1;
            break;
        }
    }
    if(prog->numstatements < 1)
    {
        prog->error_cmd("%s: empty program in %s", __func__, prog->name);
    }
    else switch(prog->statements[prog->numstatements - 1].op)
    {
        case OP_RETURN:
        case OP_GOTO:
        case OP_DONE:
            break;
        default:
            prog->error_cmd("%s: program may fall off the edge (does not end with RETURN, GOTO or DONE) in %s", __func__, prog->name);
            break;
    }
    // we're done with the file now
    if(!data)
        Mem_Free(dprograms);
    dprograms = NULL;
    // check required functions
    for(i=0 ; i < numrequiredfunc ; i++)
        if(PRVM_ED_FindFunction(prog, required_func[i]) == 0)
            prog->error_cmd("%s: %s not found in %s",prog->name, required_func[i], filename);
    PRVM_LoadLNO(prog, filename);
    PRVM_Init_Exec(prog);
    if(*prvm_language.string)
    // in CSQC we really shouldn't be able to change how stuff works... sorry for now
    // later idea: include a list of authorized .po file checksums with the csprogs
    {
        qbool deftrans = prog == CLVM_prog;
        const char *realfilename = (prog != CLVM_prog ? filename : csqc_progname.string);
        if(deftrans) // once we have dotranslate_ strings, ALWAYS use the opt-in method!
        {
            for (i=0 ; i<prog->numglobaldefs ; i++)
            {
                const char *name;
                name = PRVM_GetString(prog, prog->globaldefs[i].s_name);
                if((prog->globaldefs[i].type & ~DEF_SAVEGLOBAL) == ev_string)
                if(name && !strncmp(name, "dotranslate_", 12))
                {
                    deftrans = false;
                    break;
                }
            }
        }
        if(!strcmp(prvm_language.string, "dump"))
        {
            qfile_t *f = FS_OpenRealFile(va(vabuf, sizeof(vabuf), "%s.pot", realfilename), "w", false);
            Con_Printf("Dumping to %s.pot\n", realfilename);
            if(f)
            {
                for (i=0 ; i<prog->numglobaldefs ; i++)
                {
                    const char *name;
                    name = PRVM_GetString(prog, prog->globaldefs[i].s_name);
                    if(deftrans ? (!name || strncmp(name, "notranslate_", 12)) : (name && !strncmp(name, "dotranslate_", 12)))
                    if((prog->globaldefs[i].type & ~DEF_SAVEGLOBAL) == ev_string)
                    {
                        prvm_eval_t *val = PRVM_GLOBALFIELDVALUE(prog->globaldefs[i].ofs);
                        const char *value = PRVM_GetString(prog, val->string);
                        if(*value)
{
                            char buf[MAX_INPUTLINE];
                            PRVM_PO_UnparseString(buf, value, sizeof(buf));
                            FS_Printf(f, "msgid \"%s\"\nmsgstr \"\"\n\n", buf);
                        }
                    }
                }
                FS_Close(f);
            }
        }
        else
        {
            po_t *po = PRVM_PO_Load(
                    va(vabuf, sizeof(vabuf), "%s.%s.po", realfilename, prvm_language.string),
                    va(vabuf2, sizeof(vabuf2), "common.%s.po", prvm_language.string),
                    prog->progs_mempool);
            if(po)
            {
                for (i=0 ; i<prog->numglobaldefs ; i++)
                {
                    const char *name;
                    name = PRVM_GetString(prog, prog->globaldefs[i].s_name);
                    if(deftrans ? (!name || strncmp(name, "notranslate_", 12)) : (name && !strncmp(name, "dotranslate_", 12)))
                    if((prog->globaldefs[i].type & ~DEF_SAVEGLOBAL) == ev_string)
                    {
                        prvm_eval_t *val = PRVM_GLOBALFIELDVALUE(prog->globaldefs[i].ofs);
                        const char *value = PRVM_GetString(prog, val->string);
                        if(*value)
{
                            value = PRVM_PO_Lookup(po, value);
                            if(value)
                                val->string = PRVM_SetEngineString(prog, value);
                        }
                    }
                }
            }
        }
    }
    for (cvar = prog->console_cmd->cvars->vars; cvar; cvar = cvar->next)
        cvar->globaldefindex[prog - prvm_prog_list] = -1;
    for (i=0 ; i<prog->numglobaldefs ; i++)
    {
        const char *name;
        name = PRVM_GetString(prog, prog->globaldefs[i].s_name);
        //Con_Printf("found var %s\n", name);
        if(name
            && !strncmp(name, "autocvar_", 9)
            && !(strlen(name) > 1 && name[strlen(name)-2] == '_' && (name[strlen(name)-1] == 'x' || name[strlen(name)-1] == 'y' || name[strlen(name)-1] == 'z'))
        )
        {
            prvm_eval_t *val = PRVM_GLOBALFIELDVALUE(prog->globaldefs[i].ofs);
            cvar = Cvar_FindVar(prog->console_cmd->cvars, name + 9, prog->console_cmd->cvars_flagsmask);
            //Con_Printf("%s: autocvar global %s in %s, processing...\n", __func__, name, prog->name);
            if(!cvar)
            {
                const char *value;
                char buf[128];
                int prec[3];
                float f;
                Con_DPrintf("%s: no cvar for autocvar global %s in %s, creating...\n", __func__, name, prog->name);
                switch(prog->globaldefs[i].type & ~DEF_SAVEGLOBAL)
                {
                    case ev_float:
                        if((float)((int)(val->_float)) == val->_float)
                            dpsnprintf(buf, sizeof(buf), "%i", (int)(val->_float));
                        else
{
                            // ftos_slow
                            f = val->_float;
                            for (int precision = 7; precision <= 9; ++precision) {
                                dpsnprintf(buf, sizeof(buf), "%.*g", precision, f);
                                if ((float)atof(buf) == f) {
                                    break;
                                }
                            }
                        }
                        value = buf;
                        break;
                    case ev_vector:
                        for (i = 0; i < 3; ++i)
{
                            prec[i] = 9;
                            f = val->vector[i];
                            for (int precision = 7; precision <= 9; ++precision) {
                                dpsnprintf(buf, sizeof(buf), "%.*g", precision, f);
                                if ((float)atof(buf) == f) {
                                    prec[i] = precision;
                                    break;
                                }
                            }
                        }
                        dpsnprintf(buf, sizeof(buf), "%.*g %.*g %.*g", prec[0], val->vector[0], prec[1], val->vector[1], prec[2], val->vector[2]);
                        value = buf;
                        break;
                    case ev_string:
                        value = PRVM_GetString(prog, val->string);
                        break;
                    default:
                        Con_Printf("%s: invalid type of autocvar global %s in %s\n", __func__, name, prog->name);
                        goto fail;
                }
                cvar = Cvar_Get(prog->console_cmd->cvars, name + 9, value, prog->console_cmd->cvars_flagsmask, NULL);
                if((prog->globaldefs[i].type & ~DEF_SAVEGLOBAL) == ev_string)
                {
                    val->string = PRVM_SetEngineString(prog, cvar->string);
                    cvar->globaldefindex_stringno[prog - prvm_prog_list] = val->string;
                }
                if(!cvar)
                    prog->error_cmd("%s: could not create cvar for autocvar global %s in %s", __func__, name, prog->name);
                cvar->globaldefindex[prog - prvm_prog_list] = i;
            }
            else if((cvar->flags & CF_PRIVATE) == 0)
            {
                // MUST BE SYNCED WITH cvar.c Cvar_Set
                int j;
                const char *s;
                switch(prog->globaldefs[i].type & ~DEF_SAVEGLOBAL)
                {
                    case ev_float:
                        val->_float = cvar->value;
                        break;
                    case ev_vector:
                        s = cvar->string;
                        VectorClear(val->vector);
                        for (j = 0;j < 3;j++)
{
                            while (*s && ISWHITESPACE(*s))
                                s++;
                            if (!*s)
                                break;
                            val->vector[j] = atof(s);
                            while (!ISWHITESPACE(*s))
                                s++;
                            if (!*s)
                                break;
                        }
                        break;
                    case ev_string:
                        val->string = PRVM_SetEngineString(prog, cvar->string);
                        cvar->globaldefindex_stringno[prog - prvm_prog_list] = val->string;
                        break;
                    default:
                        Con_Printf("%s: invalid type of autocvar global %s in %s\n", __func__, name, prog->name);
                        goto fail;
                }
                cvar->globaldefindex[prog - prvm_prog_list] = i;
            }
            else
                Con_Printf("%s: private cvar for autocvar global %s in %s\n", __func__, name, prog->name);
        }
fail:
        ;
    }
    prog->loaded = true;
    PRVM_UpdateBreakpoints(prog);
    // set flags & mdef_ts in prog
    prog->flag = 0;
    PRVM_FindOffsets(prog);
    prog->init_cmd(prog);
    // init mempools
    PRVM_MEM_Alloc(prog);
    Con_Printf("%s: program loaded (crc %i, size %iK)\n", prog->name, prog->filecrc, (int)(filesize/1024));
    // Inittime is at least the time when this function finished. However,
    // later events may bump it.
    prog->inittime = host.realtime;
}
Referenced by CL_VM_Init(), MP_Init(), and SV_VM_Setup().
PRVM_Prog_Reset()
void PRVM_Prog_Reset (prvm_prog_t * prog)
Definition at line 1922 of file prvm_edict.c.
{
    if (prog->loaded)
    {
        if(prog->tempstringsbuf.cursize)
            Mem_Free(prog->tempstringsbuf.data);
        prog->tempstringsbuf.cursize = 0;
        PRVM_LeakTest(prog);
        prog->reset_cmd(prog);
        Mem_FreePool(&prog->progs_mempool);
        if(prog->po)
            PRVM_PO_Destroy((po_t *) prog->po);
    }
    memset(prog,0,sizeof(prvm_prog_t));
    prog->break_statement = -1;
    prog->watch_global_type = ev_void;
    prog->watch_field_type = ev_void;
}
Referenced by CL_VM_ShutDown(), MP_Shutdown(), PRVM_Prog_Init(), and SV_VM_Shutdown().
PRVM_ProgFromString()
prvm_prog_t * PRVM_ProgFromString (const char * str)
Definition at line 161 of file prvm_edict.c.
{
    if (!strcmp(str, "server"))
        return SVVM_prog;
    if (!strcmp(str, "client"))
        return CLVM_prog;
#ifdef CONFIG_MENU
    if (!strcmp(str, "menu"))
        return MVM_prog;
#endif
    return NULL;
}
Referenced by PRVM_Breakpoint_f(), PRVM_EdictWatchpoint_f(), PRVM_FriendlyProgFromString(), and PRVM_GlobalWatchpoint_f().
PRVM_SetEngineString()
int PRVM_SetEngineString (prvm_prog_t * prog, const char * s)
Definition at line 3338 of file prvm_edict.c.
{
    int i;
    if (!s)
        return 0;
    if (s >= prog->strings && s <= prog->strings + prog->stringssize)
        prog->error_cmd("PRVM_SetEngineString: s in prog->strings area");
    // if it's in the tempstrings area, use a reserved range
    // (otherwise we'd get millions of useless string offsets cluttering the database)
    if (s >= (char *)prog->tempstringsbuf.data && s < (char *)prog->tempstringsbuf.data + prog->tempstringsbuf.maxsize)
        return prog->stringssize + (s - (char *)prog->tempstringsbuf.data);
    // see if it's a known string address
    for (i = 0;i < prog->numknownstrings;i++)
        if (prog->knownstrings[i] == s)
            return PRVM_KNOWNSTRINGBASE + i;
    // new unknown engine string
    if (developer_insane.integer)
        Con_DPrintf("new engine string %p = \"%s\"\n", (void *)s, s);
    for (i = prog->firstfreeknownstring;i < prog->numknownstrings;i++)
        if (!prog->knownstrings[i])
            break;
    PRVM_NewKnownString(prog, i, KNOWNSTRINGFLAG_GCMARK | KNOWNSTRINGFLAG_ENGINE, s);
    return PRVM_KNOWNSTRINGBASE + i;
}
Referenced by CL_VM_Init(), PRVM_Prog_Load(), PRVM_SetTempString(), SV_Name(), SV_Playermodel_f(), SV_Playerskin_f(), SV_SpawnServer(), SV_UpdateToReliableMessages(), SVVM_init_edict(), VM_CL_modelnameforindex(), VM_CL_setmodel(), VM_CL_setmodelindex(), VM_SV_modelnameforindex(), VM_SV_setmodel(), and VM_SV_setmodelindex().
PRVM_SetTempString()
int PRVM_SetTempString (prvm_prog_t * prog, const char * s, size_t slen)
Takes an strlen (not a buffer size).
Definition at line 3371 of file prvm_edict.c.
{
    size_t size;
    char *t;
    if (!s || slen >= VM_TEMPSTRING_MAXSIZE)
        return 0;
    size = slen + 1;
    if (developer_insane.integer)
        Con_DPrintf("PRVM_SetTempString %s: cursize %i, new tempstring size %lu\n", prog->name, prog->tempstringsbuf.cursize, (unsigned long)size);
    if ((size_t)prog->tempstringsbuf.maxsize < prog->tempstringsbuf.cursize + size)
    {
        sizebuf_t old = prog->tempstringsbuf;
        if (prog->tempstringsbuf.cursize + size >= 1<<28)
            prog->error_cmd("PRVM_SetTempString %s: ran out of tempstring memory!  (refusing to grow tempstring buffer over 256MB, cursize %i, new tempstring size %lu)\n", prog->name, prog->tempstringsbuf.cursize, (unsigned long)size);
        prog->tempstringsbuf.maxsize = max(prog->tempstringsbuf.maxsize, 65536);
        while ((size_t)prog->tempstringsbuf.maxsize < prog->tempstringsbuf.cursize + size)
            prog->tempstringsbuf.maxsize *= 2;
        if (prog->tempstringsbuf.maxsize != old.maxsize || prog->tempstringsbuf.data == NULL)
        {
            Con_DPrintf("PRVM_SetTempString %s: enlarging tempstrings buffer (%iKB -> %iKB)\n", prog->name, old.maxsize/1024, prog->tempstringsbuf.maxsize/1024);
            prog->tempstringsbuf.data = (unsigned char *) Mem_Alloc(prog->progs_mempool, prog->tempstringsbuf.maxsize);
            if (old.data)
            {
                if (old.cursize)
                    memcpy(prog->tempstringsbuf.data, old.data, old.cursize);
                Mem_Free(old.data);
            }
        }
    }
    t = (char *)prog->tempstringsbuf.data + prog->tempstringsbuf.cursize;
    memcpy(t, s, size);
    prog->tempstringsbuf.cursize += size;
    return PRVM_SetEngineString(prog, t);
}
Referenced by CL_VM_Event_Sound(), CL_VM_Parse_CenterPrint(), CL_VM_Parse_Print(), CL_VM_Parse_StuffCmd(), PRVM_ConsoleCommand(), PRVM_GameCommand(), SV_ReadClientMessage(), uri_to_string_callback(), VM_altstr_get(), VM_altstr_ins(), VM_altstr_prepare(), VM_altstr_set(), VM_buf_implode(), VM_bufstr_get(), VM_chr(), VM_chr2str(), VM_CL_getextresponse(), VM_CL_getplayerkey(), VM_CL_getstats(), VM_CL_gettaginfo(), VM_CL_ReadPicture(), VM_CL_ReadString(), VM_CL_serverkey(), VM_CL_skel_get_bonename(), VM_cvar_defstring(), VM_cvar_description(), VM_cvar_string(), VM_digest_hex(), VM_entityfieldname(), VM_etos(), VM_fgets(), VM_findkeysforcommand(), VM_ftos(), VM_getentityfieldstring(), VM_getkeybind(), VM_getsurfacetexture(), VM_infoadd(), VM_infoget(), VM_keynumtostring(), VM_M_crypto_getencryptlevel(), VM_M_crypto_getidfp(), VM_M_crypto_getkeyfp(), VM_M_crypto_getmyidfp(), VM_M_crypto_getmykeyfp(), VM_M_getgamedirinfo(), VM_M_getserverliststring(), VM_netaddress_resolve(), VM_search_getfilename(), VM_SetTraceGlobals(), VM_sprintf(), VM_strcat(), VM_strconv(), VM_strdecolorize(), VM_strftime(), VM_strireplace(), VM_strpad(), VM_strreplace(), VM_strtolower(), VM_strtoupper(), VM_substring(), VM_SV_getextresponse(), VM_SV_gettaginfo(), VM_SV_serverkey(), VM_SV_skel_get_bonename(), VM_tokenize(), VM_tokenize_console(), VM_tokenizebyseparator(), VM_uncolorstring(), VM_uri_escape(), VM_uri_unescape(), VM_vtos(), and VM_whichpack().
PRVM_ShortStackTrace()
void PRVM_ShortStackTrace (prvm_prog_t * prog, char * buf, size_t bufsize)
Definition at line 432 of file prvm_exec.c.
{
    mfunction_t *f;
    int i;
    char vabuf[1024];
    char *p;
    if(prog)
    {
        i = dpsnprintf(buf, bufsize, "(%s) ", prog->name);
        p = buf + max(0, i);
    }
    else
    {
        dp_strlcpy(buf, "<NO PROG>", bufsize);
        return;
    }
    prog->stack[prog->depth].s = prog->xstatement;
    prog->stack[prog->depth].f = prog->xfunction;
    for (i = prog->depth;i > 0;i--)
    {
        f = prog->stack[i].f;
        p = dp_stpecpy(
            p,
            buf + bufsize,
            f
                ? va(vabuf, sizeof(vabuf), "%s:%s(%i) ", PRVM_GetString(prog, f->s_file), PRVM_GetString(prog, f->s_name), prog->stack[i].s - f->first_statement)
                : "<NULL> "
            );
        if (p == buf + bufsize)
            break;
    }
}
Referenced by PRVM_AllocationOrigin().
PRVM_StackTrace()
void PRVM_StackTrace (prvm_prog_t * prog)
Definition at line 404 of file prvm_exec.c.
{
    mfunction_t *f;
    int         i;
    prog->stack[prog->depth].s = prog->xstatement;
    prog->stack[prog->depth].f = prog->xfunction;
    for (i = prog->depth;i > 0;i--)
    {
        f = prog->stack[i].f;
        if (!f)
            Con_Print("<NULL FUNCTION>\n");
        else
        {
            if (prog->statement_linenums)
            {
                if (prog->statement_columnnums)
                    Con_Printf("%12s:%i:%i : %s : statement %i\n", PRVM_GetString(prog, f->s_file), prog->statement_linenums[prog->stack[i].s], prog->statement_columnnums[prog->stack[i].s], PRVM_GetString(prog, f->s_name), prog->stack[i].s - f->first_statement);
                else
                    Con_Printf("%12s:%i : %s : statement %i\n", PRVM_GetString(prog, f->s_file), prog->statement_linenums[prog->stack[i].s], PRVM_GetString(prog, f->s_name), prog->stack[i].s - f->first_statement);
            }
            else
                Con_Printf("%12s : %s : statement %i\n", PRVM_GetString(prog, f->s_file), PRVM_GetString(prog, f->s_name), prog->stack[i].s - f->first_statement);
        }
    }
}
Referenced by PRVM_PrintState(), and VM_stackdump().
PRVM_UglyValueString()
char * PRVM_UglyValueString (prvm_prog_t * prog, etype_t type, prvm_eval_t * val, char * line, size_t linelength)
Definition at line 508 of file prvm_edict.c.
{
    int i;
    const char *s;
    mdef_t *def;
    mfunction_t *f;
    type = (etype_t)((int)type & ~DEF_SAVEGLOBAL);
    switch (type)
    {
    case ev_string:
        // Parse the string a bit to turn special characters
        // (like newline, specifically) into escape codes,
        // this fixes saving games from various mods
        s = PRVM_GetString (prog, val->string);
        for (i = 0;i < (int)linelength - 2 && *s;)
        {
            if (*s == '\n')
            {
                line[i++] = '\\';
                line[i++] = 'n';
            }
            else if (*s == '\r')
            {
                line[i++] = '\\';
                line[i++] = 'r';
            }
            else if (*s == '\\')
            {
                line[i++] = '\\';
                line[i++] = '\\';
            }
            else if (*s == '"')
            {
                line[i++] = '\\';
                line[i++] = '"';
            }
            else
                line[i++] = *s;
            s++;
        }
        line[i] = '\0';
        break;
    case ev_entity:
        i = val->edict;
        dpsnprintf (line, linelength, "%i", i);
        break;
    case ev_function:
        if ((unsigned int)val->function < (unsigned int)prog->progs_numfunctions)
        {
            f = prog->functions + val->function;
            dp_strlcpy (line, PRVM_GetString (prog, f->s_name), linelength);
        }
        else
            dpsnprintf (line, linelength, "bad function %" PRVM_PRIi " (invalid!)", val->function);
        break;
    case ev_field:
        def = PRVM_ED_FieldAtOfs ( prog, val->_int );
        if (def != NULL)
            dpsnprintf (line, linelength, ".%s", PRVM_GetString(prog, def->s_name));
        else
            dpsnprintf (line, linelength, "field %" PRVM_PRIi "(invalid!)", val->_int );
        break;
    case ev_void:
        dpsnprintf (line, linelength, "void");
        break;
    case ev_float:
        dpsnprintf (line, linelength, PRVM_FLOAT_LOSSLESS_FORMAT, val->_float);
        break;
    case ev_vector:
        dpsnprintf (line, linelength, PRVM_VECTOR_LOSSLESS_FORMAT, val->vector[0], val->vector[1], val->vector[2]);
        break;
    default:
        dpsnprintf (line, linelength, "bad type %i", type);
        break;
    }
    return line;
}
Referenced by PRVM_ED_EdictGet_f(), PRVM_ED_GlobalGet_f(), PRVM_ED_Write(), PRVM_ED_WriteGlobals(), PRVM_Watchpoint(), and VM_getentityfieldstring().
PRVM_Watchpoint()
void PRVM_Watchpoint (prvm_prog_t * prog, int stack_index, const char * text, etype_t type, prvm_eval_t * o, prvm_eval_t * n)
Definition at line 2959 of file prvm_edict.c.
{
    size_t sz = sizeof(prvm_vec_t) * ((type & ~DEF_SAVEGLOBAL) == ev_vector ? 3 : 1);
    if (memcmp(o, n, sz))
    {
        char buf[1024];
        char valuebuf_o[128];
        char valuebuf_n[128];
        PRVM_UglyValueString(prog, type, o, valuebuf_o, sizeof(valuebuf_o));
        PRVM_UglyValueString(prog, type, n, valuebuf_n, sizeof(valuebuf_n));
        dpsnprintf(buf, sizeof(buf), "%s: %s -> %s", text, valuebuf_o, valuebuf_n);
        PRVM_Breakpoint(prog, stack_index, buf);
        memcpy(o, n, sz);
    }
}
Referenced by while().
SVVM_ExecuteProgram()
void SVVM_ExecuteProgram (prvm_prog_t * prog, func_t fnum, const char * errormessage)
Definition at line 1144 of file prvm_exec.c.
{
    mstatement_t    *st, *startst;
    mfunction_t     *func, *enterfunc;
    prvm_edict_t    *ed;
    prvm_eval_t *ptr;
    int     jumpcount, cachedpr_trace, exitdepth;
    int     restorevm_tempstringsbuf_cursize;
    double  calltime;
    double tm, starttm;
    prvm_vec_t tempfloat;
    // these may become out of date when a builtin is called, and are updated accordingly
    prvm_vec_t *cached_edictsfields = prog->edictsfields.fp;
    unsigned int cached_entityfields = prog->entityfields;
    unsigned int cached_entityfields_3 = prog->entityfields - 3;
    unsigned int cached_entityfieldsarea = prog->entityfieldsarea;
    unsigned int cached_entityfieldsarea_entityfields = prog->entityfieldsarea - prog->entityfields;
    unsigned int cached_entityfieldsarea_3 = prog->entityfieldsarea - 3;
    unsigned int cached_entityfieldsarea_entityfields_3 = prog->entityfieldsarea - prog->entityfields - 3;
    unsigned int cached_max_edicts = prog->max_edicts;
    // these do not change
    mstatement_t *cached_statements = prog->statements;
    qbool cached_allowworldwrites = prog->allowworldwrites;
    unsigned int cached_flag = prog->flag;
    prvm_vec_t *globals = prog->globals.fp;
    calltime = Sys_DirtyTime();
    if (!fnum || fnum >= (unsigned int)prog->numfunctions)
    {
        if (PRVM_allglobaledict(self))
            PRVM_ED_Print(prog, PRVM_PROG_TO_EDICT(PRVM_allglobaledict(self)), NULL);
        prog->error_cmd("SVVM_ExecuteProgram: %s", errormessage);
    }
    func = &prog->functions[fnum];
    // after executing this function, delete all tempstrings it created
    restorevm_tempstringsbuf_cursize = prog->tempstringsbuf.cursize;
    prog->trace = prvm_traceqc.integer;
    // we know we're done when pr_depth drops to this
    exitdepth = prog->depth;
// make a stack frame
    st = &prog->statements[PRVM_EnterFunction(prog, func)];
    // save the starting statement pointer for profiling
    // (when the function exits or jumps, the (st - startst) integer value is
    // added to the function's profile counter)
    startst = st;
    starttm = calltime;
    // instead of counting instructions, we count jumps
    jumpcount = 0;
    // add one to the callcount of this function because otherwise engine-called functions aren't counted
    if (prog->xfunction->callcount++ == 0 && (prvm_coverage.integer & 1))
        PRVM_FunctionCoverageEvent(prog, prog->xfunction);
chooseexecprogram:
    cachedpr_trace = prog->trace;
    if (prog->trace || prog->watch_global_type != ev_void || prog->watch_field_type != ev_void || prog->break_statement >= 0)
    {
#define PRVMSLOWINTERPRETER 1
        if (prvm_timeprofiling.integer)
        {
#define PRVMTIMEPROFILING 1
#include "prvm_execprogram.h"
#undef PRVMTIMEPROFILING
        }
        else
        {
#include "prvm_execprogram.h"
        }
#undef PRVMSLOWINTERPRETER
    }
    else
    {
        if (prvm_timeprofiling.integer)
        {
#define PRVMTIMEPROFILING 1
#include "prvm_execprogram.h"
#undef PRVMTIMEPROFILING
        }
        else
        {
#include "prvm_execprogram.h"
        }
    }
cleanup:
    if (developer_insane.integer && prog->tempstringsbuf.cursize > restorevm_tempstringsbuf_cursize)
        Con_DPrintf("SVVM_ExecuteProgram: %s used %i bytes of tempstrings\n", PRVM_GetString(prog, prog->functions[fnum].s_name), prog->tempstringsbuf.cursize - restorevm_tempstringsbuf_cursize);
    // delete tempstrings created by this function
    prog->tempstringsbuf.cursize = restorevm_tempstringsbuf_cursize;
    tm = Sys_DirtyTime() - calltime;if (tm < 0 || tm >= 1800) tm = 0;
    func->totaltime += tm;
    if (prog == SVVM_prog)
        SV_FlushBroadcastMessages();
}
Referenced by SV_VM_Setup().
SVVM_init_cmd()
void SVVM_init_cmd (prvm_prog_t * prog)
Definition at line 3919 of file svvm_cmds.c.
{
    VM_Cmd_Init(prog);
}
Referenced by SV_VM_Setup().
SVVM_reset_cmd()
void SVVM_reset_cmd (prvm_prog_t * prog)
Definition at line 3924 of file svvm_cmds.c.
{
    World_End(&sv.world);
    VM_Cmd_Reset(prog);
}
Referenced by SV_VM_Setup().
VM_Cmd_Init()
void VM_Cmd_Init (prvm_prog_t * prog)
Definition at line 5283 of file prvm_cmds.c.
{
    // only init the stuff for the current prog
    VM_Files_Init(prog);
    VM_Search_Init(prog);
}
Referenced by CLVM_init_cmd(), MVM_init_cmd(), and SVVM_init_cmd().
VM_Cmd_Reset()
void VM_Cmd_Reset (prvm_prog_t * prog)
Definition at line 5292 of file prvm_cmds.c.
{
    CL_PurgeOwner( MENUOWNER );
    VM_Search_Reset(prog);
    VM_Files_CloseAll(prog);
    animatemodel_reset(prog);
}
Referenced by CLVM_reset_cmd(), MVM_reset_cmd(), and SVVM_reset_cmd().
VM_FrameBlendFromFrameGroupBlend()
void VM_FrameBlendFromFrameGroupBlend (struct frameblend_s * frameblend, const struct framegroupblend_s * framegroupblend, const struct model_s * model, double curtime)
Referenced by CL_GetEntityLocalTagMatrix(), CL_RelinkStaticEntities(), CL_UpdateRenderEntity(), CSQC_AddRenderEdict(), SV_GetEntityLocalTagMatrix(), SV_GetTagMatrix(), SV_LinkEdict(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), VM_CL_gettaginfo(), VM_CL_skel_build(), VM_SV_gettaginfo(), and VM_SV_skel_build().
VM_GenerateFrameGroupBlend()
void VM_GenerateFrameGroupBlend (prvm_prog_t * prog, struct framegroupblend_s * framegroupblend, const prvm_edict_t * ed)
Referenced by CL_GetEntityLocalTagMatrix(), CSQC_AddRenderEdict(), SV_GetEntityLocalTagMatrix(), SV_GetTagMatrix(), SV_LinkEdict(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), VM_CL_gettaginfo(), VM_CL_skel_build(), VM_SV_gettaginfo(), and VM_SV_skel_build().
VM_RemoveEdictSkeleton()
void VM_RemoveEdictSkeleton (prvm_prog_t * prog, prvm_edict_t * ed)
Definition at line 261 of file prvm_cmds.c.
{
    if (ed->priv.server->skeleton.relativetransforms)
        Mem_Free(ed->priv.server->skeleton.relativetransforms);
    memset(&ed->priv.server->skeleton, 0, sizeof(ed->priv.server->skeleton));
}
Referenced by CLVM_free_edict(), SVVM_free_edict(), and VM_UpdateEdictSkeleton().
VM_UpdateEdictSkeleton()
void VM_UpdateEdictSkeleton (prvm_prog_t * prog, prvm_edict_t * ed, const struct model_s * edmodel, const struct frameblend_s * frameblend)
Referenced by CL_GetEntityLocalTagMatrix(), CSQC_AddRenderEdict(), SV_GetEntityLocalTagMatrix(), SV_GetTagMatrix(), SV_LinkEdict(), SV_TraceBox(), SV_TraceLine(), SV_TracePoint(), VM_CL_gettaginfo(), and VM_SV_gettaginfo().
VM_Warning()
void VM_Warning (prvm_prog_t * prog, const char * fmt, ...)
Definition at line 25 of file prvm_cmds.c.
{
    va_list argptr;
    char msg[MAX_INPUTLINE];
    static double recursive = -1;
    int outfd = sys.outfd;
    // set output to stderr
    sys.outfd = fileno(stderr);
    va_start(argptr,fmt);
    dpvsnprintf(msg,sizeof(msg),fmt,argptr);
    va_end(argptr);
    Con_Printf(CON_WARN "%s VM warning: %s", prog->name, msg);
    // TODO: either add a cvar/cmd to control the state dumping or replace some of the calls with Con_Printf [9/13/2006 Black]
    if(prvm_backtraceforwarnings.integer && recursive != host.realtime) // NOTE: this compares to the time, just in case if PRVM_PrintState causes a Host_Error and keeps recursive set
    {
        recursive = host.realtime;
        PRVM_PrintState(prog, 0);
        recursive = -1;
    }
    // restore configured outfd
    sys.outfd = outfd;
}
Referenced by PRVM_GetString(), VM_bprint(), VM_buf_copy(), VM_buf_cvarlist(), VM_buf_del(), VM_buf_getsize(), VM_buf_implode(), VM_buf_loadfile(), VM_buf_sort(), VM_buf_writefile(), VM_bufstr_add(), VM_bufstr_find(), VM_bufstr_free(), VM_bufstr_get(), VM_bufstr_set(), VM_changelevel(), VM_changepitch(), VM_changeyaw(), VM_CL_checkpvs(), VM_CL_copyentity(), VM_CL_droptofloor(), VM_CL_getstatf(), VM_CL_getstati(), VM_CL_getstats(), VM_CL_gettagindex(), VM_CL_gettaginfo(), VM_CL_lightstyle(), VM_CL_makestatic(), VM_CL_ParticleTheme(), VM_CL_ParticleThemeFree(), VM_CL_ParticleThemeSave(), VM_CL_pointsound(), VM_CL_precache_model(), VM_CL_R_PolygonEnd(), VM_CL_R_PolygonVertex(), VM_CL_R_SetView(), VM_CL_ResetParticle(), VM_CL_setattachment(), VM_CL_setmodel(), VM_CL_setmodelindex(), VM_CL_setorigin(), VM_CL_setsize(), VM_CL_sound(), VM_CL_SpawnParticle(), VM_CL_SpawnParticleDelayed(), VM_CL_tracetoss(), VM_CL_walkmove(), VM_cvar_set(), VM_drawcharacter(), VM_drawcolorcodedstring(), VM_drawfill(), VM_drawpic(), VM_drawrotpic(), VM_drawstring(), VM_drawsubpic(), VM_entityfieldname(), VM_entityfieldtype(), VM_fclose(), VM_fgets(), VM_fopen(), VM_fputs(), VM_getentityfieldstring(), VM_getsoundtime(), VM_gettime(), VM_loadfont(), VM_loadfromfile(), VM_localsound(), VM_M_getserverliststat(), VM_M_setserverlistmasknumber(), VM_M_setserverlistmaskstring(), VM_matchpattern(), VM_modulo(), VM_nudgeoutofsolid(), VM_physics_addforce(), VM_physics_addtorque(), VM_physics_enable(), VM_precache_sound(), VM_putentityfieldstring(), VM_registercvar(), VM_remove(), VM_search_begin(), VM_search_end(), VM_search_getfilename(), VM_search_getsize(), VM_sprint(), VM_sprintf(), VM_SV_AddStat(), VM_SV_aim(), VM_SV_centerprint(), VM_SV_checkpvs(), VM_SV_copyentity(), VM_SV_dropclient(), VM_SV_droptofloor(), VM_SV_effect(), VM_SV_gettagindex(), VM_SV_gettaginfo(), VM_SV_makestatic(), VM_SV_modelnameforindex(), VM_SV_pointsound(), VM_SV_setattachment(), VM_SV_setmodel(), VM_SV_setmodelindex(), VM_SV_setorigin(), VM_SV_setsize(), VM_SV_sound(), VM_SV_sprint(), VM_SV_stuffcmd(), VM_SV_tracetoss(), VM_SV_walkmove(), VM_uri_get(), VM_VarString(), VM_writetofile(), while(), and WriteDest().
Variable Documentation
prvm_badvalue
prvm_eval_t prvm_badvalue extern
Definition at line 31 of file prvm_edict.c.
prvm_prog_list
prvm_prog_t prvm_prog_list[PRVM_PROG_MAX] extern
Definition at line 27 of file prvm_edict.c.
Referenced by Cvar_IsAutoCvar(), Cvar_UpdateAutoCvar(), PRVM_Breakpoint_f(), PRVM_EdictWatchpoint_f(), PRVM_GlobalWatchpoint_f(), PRVM_Prog_Load(), and PRVM_UpdateBreakpoints().
prvm_type_size
int prvm_type_size[8] extern
Definition at line 29 of file prvm_edict.c.
{1,sizeof(string_t)/4,1,3,1,1,sizeof(func_t)/4,sizeof(void *)/4};
Referenced by PRVM_ED_Print(), PRVM_ED_Write(), PRVM_Fields_f(), and VM_getentityfieldstring().
vm_cl_builtins
prvm_builtin_t vm_cl_builtins[] extern
Definition at line 4984 of file clvm_cmds.c.
{
NULL,                           // #0 NULL function (not callable) (QUAKE)
VM_CL_makevectors,              // #1 void(vector ang) makevectors (QUAKE)
VM_CL_setorigin,                // #2 void(entity e, vector o) setorigin (QUAKE)
VM_CL_setmodel,                 // #3 void(entity e, string m) setmodel (QUAKE)
VM_CL_setsize,                  // #4 void(entity e, vector min, vector max) setsize (QUAKE)
NULL,                           // #5 void(entity e, vector min, vector max) setabssize (QUAKE)
VM_break,                       // #6 void() break (QUAKE)
VM_random,                      // #7 float() random (QUAKE)
VM_CL_sound,                    // #8 void(entity e, float chan, string samp, float volume, float atten[, float pitchchange[, float flags]]) sound (QUAKE)
VM_normalize,                   // #9 vector(vector v) normalize (QUAKE)
VM_error,                       // #10 void(string e) error (QUAKE)
VM_objerror,                    // #11 void(string e) objerror (QUAKE)
VM_vlen,                        // #12 float(vector v) vlen (QUAKE)
VM_vectoyaw,                    // #13 float(vector v) vectoyaw (QUAKE)
VM_CL_spawn,                    // #14 entity() spawn (QUAKE)
VM_remove,                      // #15 void(entity e) remove (QUAKE)
VM_CL_traceline,                // #16 void(vector v1, vector v2, float tryents, entity ignoreentity) traceline (QUAKE)
NULL,                           // #17 entity() checkclient (QUAKE)
VM_find,                        // #18 entity(entity start, .string fld, string match) find (QUAKE)
VM_precache_sound,              // #19 void(string s) precache_sound (QUAKE)
VM_CL_precache_model,           // #20 void(string s) precache_model (QUAKE)
NULL,                           // #21 void(entity client, string s, ...) stuffcmd (QUAKE)
VM_CL_findradius,               // #22 entity(vector org, float rad) findradius (QUAKE)
NULL,                           // #23 void(string s, ...) bprint (QUAKE)
NULL,                           // #24 void(entity client, string s, ...) sprint (QUAKE)
VM_dprint,                      // #25 void(string s, ...) dprint (QUAKE)
VM_ftos,                        // #26 string(float f) ftos (QUAKE)
VM_vtos,                        // #27 string(vector v) vtos (QUAKE)
VM_coredump,                    // #28 void() coredump (QUAKE)
VM_traceon,                     // #29 void() traceon (QUAKE)
VM_traceoff,                    // #30 void() traceoff (QUAKE)
VM_eprint,                      // #31 void(entity e) eprint (QUAKE)
VM_CL_walkmove,                 // #32 float(float yaw, float dist[, float settrace]) walkmove (QUAKE)
NULL,                           // #33 (QUAKE)
VM_CL_droptofloor,              // #34 float() droptofloor (QUAKE)
VM_CL_lightstyle,               // #35 void(float style, string value) lightstyle (QUAKE)
VM_rint,                        // #36 float(float v) rint (QUAKE)
VM_floor,                       // #37 float(float v) floor (QUAKE)
VM_ceil,                        // #38 float(float v) ceil (QUAKE)
NULL,                           // #39 (QUAKE)
VM_CL_checkbottom,              // #40 float(entity e) checkbottom (QUAKE)
VM_CL_pointcontents,            // #41 float(vector v) pointcontents (QUAKE)
NULL,                           // #42 (QUAKE)
VM_fabs,                        // #43 float(float f) fabs (QUAKE)
NULL,                           // #44 vector(entity e, float speed) aim (QUAKE)
VM_cvar,                        // #45 float(string s) cvar (QUAKE)
VM_localcmd_local,              // #46 void(string s) localcmd (QUAKE)
VM_nextent,                     // #47 entity(entity e) nextent (QUAKE)
VM_CL_particle,                 // #48 void(vector o, vector d, float color, float count) particle (QUAKE)
VM_changeyaw,                   // #49 void() ChangeYaw (QUAKE)
NULL,                           // #50 (QUAKE)
VM_vectoangles,                 // #51 vector(vector v) vectoangles (QUAKE)
NULL,                           // #52 void(float to, float f) WriteByte (QUAKE)
NULL,                           // #53 void(float to, float f) WriteChar (QUAKE)
NULL,                           // #54 void(float to, float f) WriteShort (QUAKE)
NULL,                           // #55 void(float to, float f) WriteLong (QUAKE)
NULL,                           // #56 void(float to, float f) WriteCoord (QUAKE)
NULL,                           // #57 void(float to, float f) WriteAngle (QUAKE)
NULL,                           // #58 void(float to, string s) WriteString (QUAKE)
NULL,                           // #59 (QUAKE)
VM_sin,                         // #60 float(float f) sin (DP_QC_SINCOSSQRTPOW)
VM_cos,                         // #61 float(float f) cos (DP_QC_SINCOSSQRTPOW)
VM_sqrt,                        // #62 float(float f) sqrt (DP_QC_SINCOSSQRTPOW)
VM_changepitch,                 // #63 void(entity ent) changepitch (DP_QC_CHANGEPITCH)
VM_CL_tracetoss,                // #64 void(entity e, entity ignore) tracetoss (DP_QC_TRACETOSS)
VM_etos,                        // #65 string(entity ent) etos (DP_QC_ETOS)
NULL,                           // #66 (QUAKE)
NULL,                           // #67 void(float step) movetogoal (QUAKE)
VM_precache_file,               // #68 string(string s) precache_file (QUAKE)
VM_CL_makestatic,               // #69 void(entity e) makestatic (QUAKE)
NULL,                           // #70 void(string s) changelevel (QUAKE)
NULL,                           // #71 (QUAKE)
VM_cvar_set,                    // #72 void(string var, string val) cvar_set (QUAKE)
NULL,                           // #73 void(entity client, strings) centerprint (QUAKE)
VM_CL_ambientsound,             // #74 void(vector pos, string samp, float vol, float atten) ambientsound (QUAKE)
VM_CL_precache_model,           // #75 string(string s) precache_model2 (QUAKE)
VM_precache_sound,              // #76 string(string s) precache_sound2 (QUAKE)
VM_precache_file,               // #77 string(string s) precache_file2 (QUAKE)
NULL,                           // #78 void(entity e) setspawnparms (QUAKE)
NULL,                           // #79 void(entity killer, entity killee) logfrag (QUAKEWORLD)
NULL,                           // #80 string(entity e, string keyname) infokey (QUAKEWORLD)
VM_stof,                        // #81 float(string s) stof (FRIK_FILE)
NULL,                           // #82 void(vector where, float set) multicast (QUAKEWORLD)
NULL,                           // #83 (QUAKE)
NULL,                           // #84 (QUAKE)
NULL,                           // #85 (QUAKE)
NULL,                           // #86 (QUAKE)
NULL,                           // #87 (QUAKE)
NULL,                           // #88 (QUAKE)
NULL,                           // #89 (QUAKE)
VM_CL_tracebox,                 // #90 void(vector v1, vector min, vector max, vector v2, float nomonsters, entity forent) tracebox (DP_QC_TRACEBOX)
VM_randomvec,                   // #91 vector() randomvec (DP_QC_RANDOMVEC)
VM_CL_getlight,                 // #92 vector(vector org) getlight (DP_QC_GETLIGHT)
VM_registercvar,                // #93 float(string name, string value) registercvar (DP_REGISTERCVAR)
VM_min,                         // #94 float(float a, floats) min (DP_QC_MINMAXBOUND)
VM_max,                         // #95 float(float a, floats) max (DP_QC_MINMAXBOUND)
VM_bound,                       // #96 float(float minimum, float val, float maximum) bound (DP_QC_MINMAXBOUND)
VM_pow,                         // #97 float(float f, float f) pow (DP_QC_SINCOSSQRTPOW)
VM_findfloat,                   // #98 entity(entity start, .float fld, float match) findfloat (DP_QC_FINDFLOAT)
VM_checkextension,              // #99 float(string s) checkextension (the basis of the extension system)
// FrikaC and Telejano range #100-#199
NULL,                           // #100
NULL,                           // #101
NULL,                           // #102
NULL,                           // #103
NULL,                           // #104
NULL,                           // #105
NULL,                           // #106
NULL,                           // #107
NULL,                           // #108
NULL,                           // #109
VM_fopen,                       // #110 float(string filename, float mode) fopen (FRIK_FILE)
VM_fclose,                      // #111 void(float fhandle) fclose (FRIK_FILE)
VM_fgets,                       // #112 string(float fhandle) fgets (FRIK_FILE)
VM_fputs,                       // #113 void(float fhandle, string s) fputs (FRIK_FILE)
VM_strlen,                      // #114 float(string s) strlen (FRIK_FILE)
VM_strcat,                      // #115 string(string s, string...) strcat (FRIK_FILE)
VM_substring,                   // #116 string(string s, float start, float length) substring (FRIK_FILE)
VM_stov,                        // #117 vector(string) stov (FRIK_FILE)
VM_strzone,                     // #118 string(string s) strzone (FRIK_FILE)
VM_strunzone,                   // #119 void(string s) strunzone (FRIK_FILE)
NULL,                           // #120
NULL,                           // #121
NULL,                           // #122
NULL,                           // #123
NULL,                           // #124
NULL,                           // #125
NULL,                           // #126
NULL,                           // #127
NULL,                           // #128
NULL,                           // #129
NULL,                           // #130
NULL,                           // #131
NULL,                           // #132
NULL,                           // #133
NULL,                           // #134
NULL,                           // #135
NULL,                           // #136
NULL,                           // #137
NULL,                           // #138
NULL,                           // #139
NULL,                           // #140
NULL,                           // #141
NULL,                           // #142
NULL,                           // #143
NULL,                           // #144
NULL,                           // #145
NULL,                           // #146
NULL,                           // #147
NULL,                           // #148
NULL,                           // #149
NULL,                           // #150
NULL,                           // #151
NULL,                           // #152
NULL,                           // #153
NULL,                           // #154
NULL,                           // #155
NULL,                           // #156
NULL,                           // #157
NULL,                           // #158
NULL,                           // #159
NULL,                           // #160
NULL,                           // #161
NULL,                           // #162
NULL,                           // #163
NULL,                           // #164
NULL,                           // #165
NULL,                           // #166
NULL,                           // #167
NULL,                           // #168
NULL,                           // #169
NULL,                           // #170
NULL,                           // #171
NULL,                           // #172
NULL,                           // #173
NULL,                           // #174
NULL,                           // #175
NULL,                           // #176
VM_localsound,                  // #177
NULL,                           // #178
NULL,                           // #179
NULL,                           // #180
NULL,                           // #181
NULL,                           // #182
NULL,                           // #183
NULL,                           // #184
NULL,                           // #185
NULL,                           // #186
NULL,                           // #187
NULL,                           // #188
NULL,                           // #189
NULL,                           // #190
NULL,                           // #191
NULL,                           // #192
NULL,                           // #193
NULL,                           // #194
NULL,                           // #195
NULL,                           // #196
NULL,                           // #197
NULL,                           // #198
NULL,                           // #199
// FTEQW range #200-#299
NULL,                           // #200
NULL,                           // #201
NULL,                           // #202
NULL,                           // #203
NULL,                           // #204
NULL,                           // #205
NULL,                           // #206
NULL,                           // #207
NULL,                           // #208
NULL,                           // #209
NULL,                           // #210
NULL,                           // #211
NULL,                           // #212
NULL,                           // #213
NULL,                           // #214
NULL,                           // #215
NULL,                           // #216
NULL,                           // #217
VM_bitshift,                    // #218 float(float number, float quantity) bitshift (EXT_BITSHIFT)
NULL,                           // #219
NULL,                           // #220
VM_strstrofs,                   // #221 float(string str, string sub[, float startpos]) strstrofs (FTE_STRINGS)
VM_str2chr,                     // #222 float(string str, float ofs) str2chr (FTE_STRINGS)
VM_chr2str,                     // #223 string(float c, ...) chr2str (FTE_STRINGS)
VM_strconv,                     // #224 string(float ccase, float calpha, float cnum, string s, ...) strconv (FTE_STRINGS)
VM_strpad,                      // #225 string(float chars, string s, ...) strpad (FTE_STRINGS)
VM_infoadd,                     // #226 string(string info, string key, string value, ...) infoadd (FTE_STRINGS)
VM_infoget,                     // #227 string(string info, string key) infoget (FTE_STRINGS)
VM_strncmp,                     // #228 float(string s1, string s2, float len) strncmp (FTE_STRINGS)
VM_strncasecmp,                 // #229 float(string s1, string s2) strcasecmp (FTE_STRINGS)
VM_strncasecmp,                 // #230 float(string s1, string s2, float len) strncasecmp (FTE_STRINGS)
NULL,                           // #231
NULL,                           // #232 void(float index, float type, .void field) SV_AddStat (EXT_CSQC)
NULL,                           // #233
NULL,                           // #234
NULL,                           // #235
NULL,                           // #236
NULL,                           // #237
NULL,                           // #238
NULL,                           // #239
VM_CL_checkpvs,                 // #240
NULL,                           // #241
NULL,                           // #242
NULL,                           // #243
NULL,                           // #244
VM_modulo,                      // #245
NULL,                           // #246
NULL,                           // #247
NULL,                           // #248
NULL,                           // #249
NULL,                           // #250
NULL,                           // #251
NULL,                           // #252
NULL,                           // #253
NULL,                           // #254
NULL,                           // #255
NULL,                           // #256
NULL,                           // #257
NULL,                           // #258
NULL,                           // #259
NULL,                           // #260
NULL,                           // #261
NULL,                           // #262
VM_CL_skel_create,              // #263 float(float modlindex) skel_create = #263; // (FTE_CSQC_SKELETONOBJECTS) create a skeleton (be sure to assign this value into .skeletonindex for use), returns skeleton index (1 or higher) on success, returns 0 on failure  (for example if the modelindex is not skeletal), it is recommended that you create a new skeleton if you change modelindex.
VM_CL_skel_build,               // #264 float(float skel, entity ent, float modlindex, float retainfrac, float firstbone, float lastbone) skel_build = #264; // (FTE_CSQC_SKELETONOBJECTS) blend in a percentage of standard animation, 0 replaces entirely, 1 does nothing, 0.5 blends half, etc, and this only alters the bones in the specified range for which out of bounds values like 0,100000 are safe (uses .frame, .frame2, .frame3, .frame4, .lerpfrac, .lerpfrac3, .lerpfrac4, .frame1time, .frame2time, .frame3time, .frame4time), returns skel on success, 0 on failure
VM_CL_skel_get_numbones,        // #265 float(float skel) skel_get_numbones = #265; // (FTE_CSQC_SKELETONOBJECTS) returns how many bones exist in the created skeleton
VM_CL_skel_get_bonename,        // #266 string(float skel, float bonenum) skel_get_bonename = #266; // (FTE_CSQC_SKELETONOBJECTS) returns name of bone (as a tempstring)
VM_CL_skel_get_boneparent,      // #267 float(float skel, float bonenum) skel_get_boneparent = #267; // (FTE_CSQC_SKELETONOBJECTS) returns parent num for supplied bonenum, -1 if bonenum has no parent or bone does not exist (returned value is always less than bonenum, you can loop on this)
VM_CL_skel_find_bone,           // #268 float(float skel, string tagname) skel_find_bone = #268; // (FTE_CSQC_SKELETONOBJECTS) get number of bone with specified name, 0 on failure, tagindex (bonenum+1) on success, same as using gettagindex on the modelindex
VM_CL_skel_get_bonerel,         // #269 vector(float skel, float bonenum) skel_get_bonerel = #269; // (FTE_CSQC_SKELETONOBJECTS) get matrix of bone in skeleton relative to its parent - sets v_forward, v_right, v_up, returns origin (relative to parent bone)
VM_CL_skel_get_boneabs,         // #270 vector(float skel, float bonenum) skel_get_boneabs = #270; // (FTE_CSQC_SKELETONOBJECTS) get matrix of bone in skeleton in model space - sets v_forward, v_right, v_up, returns origin (relative to entity)
VM_CL_skel_set_bone,            // #271 void(float skel, float bonenum, vector org) skel_set_bone = #271; // (FTE_CSQC_SKELETONOBJECTS) set matrix of bone relative to its parent, reads v_forward, v_right, v_up, takes origin as parameter (relative to parent bone)
VM_CL_skel_mul_bone,            // #272 void(float skel, float bonenum, vector org) skel_mul_bone = #272; // (FTE_CSQC_SKELETONOBJECTS) transform bone matrix (relative to its parent) by the supplied matrix in v_forward, v_right, v_up, takes origin as parameter (relative to parent bone)
VM_CL_skel_mul_bones,           // #273 void(float skel, float startbone, float endbone, vector org) skel_mul_bones = #273; // (FTE_CSQC_SKELETONOBJECTS) transform bone matrices (relative to their parents) by the supplied matrix in v_forward, v_right, v_up, takes origin as parameter (relative to parent bones)
VM_CL_skel_copybones,           // #274 void(float skeldst, float skelsrc, float startbone, float endbone) skel_copybones = #274; // (FTE_CSQC_SKELETONOBJECTS) copy bone matrices (relative to their parents) from one skeleton to another, useful for copying a skeleton to a corpse
VM_CL_skel_delete,              // #275 void(float skel) skel_delete = #275; // (FTE_CSQC_SKELETONOBJECTS) deletes skeleton at the beginning of the next frame (you can add the entity, delete the skeleton, renderscene, and it will still work)
VM_CL_frameforname,             // #276 float(float modlindex, string framename) frameforname = #276; // (FTE_CSQC_SKELETONOBJECTS) finds number of a specified frame in the animation, returns -1 if no match found
VM_CL_frameduration,            // #277 float(float modlindex, float framenum) frameduration = #277; // (FTE_CSQC_SKELETONOBJECTS) returns the intended play time (in seconds) of the specified framegroup, if it does not exist the result is 0, if it is a single frame it may be a small value around 0.1 or 0.
NULL,                           // #278
NULL,                           // #279
NULL,                           // #280
NULL,                           // #281
NULL,                           // #282
NULL,                           // #283
NULL,                           // #284
NULL,                           // #285
NULL,                           // #286
NULL,                           // #287
NULL,                           // #288
NULL,                           // #289
NULL,                           // #290
NULL,                           // #291
NULL,                           // #292
NULL,                           // #293
NULL,                           // #294
NULL,                           // #295
NULL,                           // #296
NULL,                           // #297
NULL,                           // #298
NULL,                           // #299
// CSQC range #300-#399
VM_CL_R_ClearScene,             // #300 void() clearscene (EXT_CSQC)
VM_CL_R_AddEntities,            // #301 void(float mask) addentities (EXT_CSQC)
VM_CL_R_AddEntity,              // #302 void(entity ent) addentity (EXT_CSQC)
VM_CL_R_SetView,                // #303 float(float property, ...) setproperty (EXT_CSQC)
VM_CL_R_RenderScene,            // #304 void() renderscene (EXT_CSQC)
VM_CL_R_AddDynamicLight,        // #305 void(vector org, float radius, vector lightcolours) adddynamiclight (EXT_CSQC)
VM_CL_R_PolygonBegin,           // #306 void(string texturename, float flag, float is2d[NYI: , float lines]) R_BeginPolygon
VM_CL_R_PolygonVertex,          // #307 void(vector org, vector texcoords, vector rgb, float alpha) R_PolygonVertex
VM_CL_R_PolygonEnd,             // #308 void() R_EndPolygon
VM_CL_R_SetView,                // #309 float(float property) getproperty (EXT_CSQC)
VM_CL_unproject,                // #310 vector (vector v) cs_unproject (EXT_CSQC)
VM_CL_project,                  // #311 vector (vector v) cs_project (EXT_CSQC)
NULL,                           // #312
NULL,                           // #313
NULL,                           // #314
VM_drawline,                    // #315 void(float width, vector pos1, vector pos2, float flag) drawline (EXT_CSQC)
VM_iscachedpic,                 // #316 float(string name) iscachedpic (EXT_CSQC)
VM_precache_pic,                // #317 string(string name, float trywad) precache_pic (EXT_CSQC)
VM_getimagesize,                // #318 vector(string picname) draw_getimagesize (EXT_CSQC)
VM_freepic,                     // #319 void(string name) freepic (EXT_CSQC)
VM_drawcharacter,               // #320 float(vector position, float character, vector scale, vector rgb, float alpha, float flag) drawcharacter (EXT_CSQC)
VM_drawstring,                  // #321 float(vector position, string text, vector scale, vector rgb, float alpha[, float flag]) drawstring (EXT_CSQC, DP_CSQC)
VM_drawpic,                     // #322 float(vector position, string pic, vector size, vector rgb, float alpha[, float flag]) drawpic (EXT_CSQC)
VM_drawfill,                    // #323 float(vector position, vector size, vector rgb, float alpha, float flag) drawfill (EXT_CSQC)
VM_drawsetcliparea,             // #324 void(float x, float y, float width, float height) drawsetcliparea
VM_drawresetcliparea,           // #325 void(void) drawresetcliparea
VM_drawcolorcodedstring,        // #326 float drawcolorcodedstring(vector position, string text, vector scale, vector rgb, float alpha, float flag) (EXT_CSQC)
VM_stringwidth,                 // #327 // FIXME is this okay?
VM_drawsubpic,                  // #328 // FIXME is this okay?
VM_drawrotpic,                  // #329 // FIXME is this okay?
VM_CL_getstatf,                 // #330 float(float stnum) getstatf (EXT_CSQC)
VM_CL_getstati,                 // #331 float(float stnum) getstati (EXT_CSQC)
VM_CL_getstats,                 // #332 string(float firststnum) getstats (EXT_CSQC)
VM_CL_setmodelindex,            // #333 void(entity e, float mdlindex) setmodelindex (EXT_CSQC)
VM_CL_modelnameforindex,        // #334 string(float mdlindex) modelnameforindex (EXT_CSQC)
VM_CL_particleeffectnum,        // #335 float(string effectname) particleeffectnum (EXT_CSQC)
VM_CL_trailparticles,           // #336 void(entity ent, float effectnum, vector start, vector end) trailparticles (EXT_CSQC)
VM_CL_pointparticles,           // #337 void(float effectnum, vector origin [, vector dir, float count]) pointparticles (EXT_CSQC)
VM_centerprint,                 // #338 void(string s, ...) centerprint (EXT_CSQC)
VM_print,                       // #339 void(string s, ...) print (EXT_CSQC, DP_SV_PRINT)
VM_keynumtostring,              // #340 string(float keynum) keynumtostring (EXT_CSQC)
VM_stringtokeynum,              // #341 float(string keyname) stringtokeynum (EXT_CSQC)
VM_getkeybind,                  // #342 string(float keynum[, float bindmap]) getkeybind (EXT_CSQC)
VM_CL_setcursormode,            // #343 void(float usecursor) setcursormode (DP_CSQC)
VM_CL_getmousepos,              // #344 vector() getmousepos (DP_CSQC)
VM_CL_getinputstate,            // #345 float(float framenum) getinputstate (EXT_CSQC)
VM_CL_setsensitivityscale,      // #346 void(float sens) setsensitivityscale (EXT_CSQC)
VM_CL_runplayerphysics,         // #347 void() runstandardplayerphysics (EXT_CSQC)
VM_CL_getplayerkey,             // #348 string(float playernum, string keyname) getplayerkeyvalue (EXT_CSQC)
VM_CL_isdemo,                   // #349 float() isdemo (EXT_CSQC)
VM_isserver,                    // #350 float() isserver (EXT_CSQC)
VM_CL_setlistener,              // #351 void(vector origin, vector forward, vector right, vector up) SetListener (EXT_CSQC)
VM_CL_registercmd,              // #352 void(string cmdname) registercommand (EXT_CSQC)
VM_wasfreed,                    // #353 float(entity ent) wasfreed (EXT_CSQC) (should be availabe on server too)
VM_CL_serverkey,                // #354 string(string key) serverkey (EXT_CSQC)
VM_CL_videoplaying,             // #355
VM_findfont,                    // #356 float(string fontname) loadfont (DP_GFX_FONTS)
VM_loadfont,                    // #357 float(string fontname, string fontmaps, string sizes, float slot) loadfont (DP_GFX_FONTS)
VM_CL_loadcubemap,              // #358 void(string cubemapname) loadcubemap (DP_GFX_)
NULL,                           // #359
VM_CL_ReadByte,                 // #360 float() ReadByte (EXT_CSQC)
VM_CL_ReadChar,                 // #361 float() ReadChar (EXT_CSQC)
VM_CL_ReadShort,                // #362 float() ReadShort (EXT_CSQC)
VM_CL_ReadLong,                 // #363 float() ReadLong (EXT_CSQC)
VM_CL_ReadCoord,                // #364 float() ReadCoord (EXT_CSQC)
VM_CL_ReadAngle,                // #365 float() ReadAngle (EXT_CSQC)
VM_CL_ReadString,               // #366 string() ReadString (EXT_CSQC)
VM_CL_ReadFloat,                // #367 float() ReadFloat (EXT_CSQC)
NULL,                       // #368
NULL,                           // #369
NULL,                           // #370
NULL,                           // #371
NULL,                           // #372
NULL,                           // #373
NULL,                           // #374
NULL,                           // #375
NULL,                           // #376
NULL,                           // #377
NULL,                           // #378
NULL,                           // #379
NULL,                           // #380
NULL,                           // #381
NULL,                           // #382
NULL,                           // #383
NULL,                           // #384
NULL,                           // #385
NULL,                           // #386
NULL,                           // #387
NULL,                           // #388
NULL,                           // #389
NULL,                           // #390
NULL,                           // #391
NULL,                           // #392
NULL,                           // #393
NULL,                           // #394
NULL,                           // #395
NULL,                           // #396
NULL,                           // #397
NULL,                           // #398
NULL,                           // #399
// LadyHavoc's range #400-#499
VM_CL_copyentity,               // #400 void(entity from, entity to) copyentity (DP_QC_COPYENTITY)
NULL,                           // #401 void(entity ent, float colors) setcolor (DP_QC_SETCOLOR)
VM_findchain,                   // #402 entity(.string fld, string match) findchain (DP_QC_FINDCHAIN)
VM_findchainfloat,              // #403 entity(.float fld, float match) findchainfloat (DP_QC_FINDCHAINFLOAT)
VM_CL_effect,                   // #404 void(vector org, string modelname, float startframe, float endframe, float framerate) effect (DP_SV_EFFECT)
VM_CL_te_blood,                 // #405 void(vector org, vector velocity, float howmany) te_blood (DP_TE_BLOOD)
VM_CL_te_bloodshower,           // #406 void(vector mincorner, vector maxcorner, float explosionspeed, float howmany) te_bloodshower (DP_TE_BLOODSHOWER)
VM_CL_te_explosionrgb,          // #407 void(vector org, vector color) te_explosionrgb (DP_TE_EXPLOSIONRGB)
VM_CL_te_particlecube,          // #408 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color, float gravityflag, float randomveljitter) te_particlecube (DP_TE_PARTICLECUBE)
VM_CL_te_particlerain,          // #409 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlerain (DP_TE_PARTICLERAIN)
VM_CL_te_particlesnow,          // #410 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlesnow (DP_TE_PARTICLESNOW)
VM_CL_te_spark,                 // #411 void(vector org, vector vel, float howmany) te_spark (DP_TE_SPARK)
VM_CL_te_gunshotquad,           // #412 void(vector org) te_gunshotquad (DP_QUADEFFECTS1)
VM_CL_te_spikequad,             // #413 void(vector org) te_spikequad (DP_QUADEFFECTS1)
VM_CL_te_superspikequad,        // #414 void(vector org) te_superspikequad (DP_QUADEFFECTS1)
VM_CL_te_explosionquad,         // #415 void(vector org) te_explosionquad (DP_QUADEFFECTS1)
VM_CL_te_smallflash,            // #416 void(vector org) te_smallflash (DP_TE_SMALLFLASH)
VM_CL_te_customflash,           // #417 void(vector org, float radius, float lifetime, vector color) te_customflash (DP_TE_CUSTOMFLASH)
VM_CL_te_gunshot,               // #418 void(vector org) te_gunshot (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_spike,                 // #419 void(vector org) te_spike (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_superspike,            // #420 void(vector org) te_superspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_explosion,             // #421 void(vector org) te_explosion (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_tarexplosion,          // #422 void(vector org) te_tarexplosion (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_wizspike,              // #423 void(vector org) te_wizspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_knightspike,           // #424 void(vector org) te_knightspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_lavasplash,            // #425 void(vector org) te_lavasplash (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_teleport,              // #426 void(vector org) te_teleport (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_explosion2,            // #427 void(vector org, float colorstart, float colorlength) te_explosion2 (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_lightning1,            // #428 void(entity own, vector start, vector end) te_lightning1 (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_lightning2,            // #429 void(entity own, vector start, vector end) te_lightning2 (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_lightning3,            // #430 void(entity own, vector start, vector end) te_lightning3 (DP_TE_STANDARDEFFECTBUILTINS)
VM_CL_te_beam,                  // #431 void(entity own, vector start, vector end) te_beam (DP_TE_STANDARDEFFECTBUILTINS)
VM_vectorvectors,               // #432 void(vector dir) vectorvectors (DP_QC_VECTORVECTORS)
VM_CL_te_plasmaburn,            // #433 void(vector org) te_plasmaburn (DP_TE_PLASMABURN)
VM_getsurfacenumpoints,     // #434 float(entity e, float s) getsurfacenumpoints (DP_QC_GETSURFACE)
VM_getsurfacepoint,         // #435 vector(entity e, float s, float n) getsurfacepoint (DP_QC_GETSURFACE)
VM_getsurfacenormal,            // #436 vector(entity e, float s) getsurfacenormal (DP_QC_GETSURFACE)
VM_getsurfacetexture,       // #437 string(entity e, float s) getsurfacetexture (DP_QC_GETSURFACE)
VM_getsurfacenearpoint,     // #438 float(entity e, vector p) getsurfacenearpoint (DP_QC_GETSURFACE)
VM_getsurfaceclippedpoint,  // #439 vector(entity e, float s, vector p) getsurfaceclippedpoint (DP_QC_GETSURFACE)
NULL,                           // #440 void(entity e, string s) clientcommand (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_tokenize,                    // #441 float(string s) tokenize (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_argv,                        // #442 string(float n) argv (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_CL_setattachment,            // #443 void(entity e, entity tagentity, string tagname) setattachment (DP_GFX_QUAKE3MODELTAGS)
VM_search_begin,                // #444 float(string pattern, float caseinsensitive, float quiet) search_begin (DP_QC_FS_SEARCH)
VM_search_end,                  // #445 void(float handle) search_end (DP_QC_FS_SEARCH)
VM_search_getsize,              // #446 float(float handle) search_getsize (DP_QC_FS_SEARCH)
VM_search_getfilename,          // #447 string(float handle, float num) search_getfilename (DP_QC_FS_SEARCH)
VM_cvar_string,                 // #448 string(string s) cvar_string (DP_QC_CVAR_STRING)
VM_findflags,                   // #449 entity(entity start, .float fld, float match) findflags (DP_QC_FINDFLAGS)
VM_findchainflags,              // #450 entity(.float fld, float match) findchainflags (DP_QC_FINDCHAINFLAGS)
VM_CL_gettagindex,              // #451 float(entity ent, string tagname) gettagindex (DP_QC_GETTAGINFO)
VM_CL_gettaginfo,               // #452 vector(entity ent, float tagindex) gettaginfo (DP_QC_GETTAGINFO)
NULL,                           // #453 void(entity clent) dropclient (DP_SV_DROPCLIENT)
NULL,                           // #454 entity() spawnclient (DP_SV_BOTCLIENT)
NULL,                           // #455 float(entity clent) clienttype (DP_SV_BOTCLIENT)
NULL,                           // #456 void(float to, string s) WriteUnterminatedString (DP_SV_WRITEUNTERMINATEDSTRING)
VM_CL_te_flamejet,              // #457 void(vector org, vector vel, float howmany) te_flamejet (DP_TE_FLAMEJET)
NULL,                           // #458
VM_ftoe,                        // #459 entity(float num) entitybyindex (DP_QC_EDICT_NUM)
VM_buf_create,                  // #460 float() buf_create (DP_QC_STRINGBUFFERS)
VM_buf_del,                     // #461 void(float bufhandle) buf_del (DP_QC_STRINGBUFFERS)
VM_buf_getsize,                 // #462 float(float bufhandle) buf_getsize (DP_QC_STRINGBUFFERS)
VM_buf_copy,                    // #463 void(float bufhandle_from, float bufhandle_to) buf_copy (DP_QC_STRINGBUFFERS)
VM_buf_sort,                    // #464 void(float bufhandle, float sortpower, float backward) buf_sort (DP_QC_STRINGBUFFERS)
VM_buf_implode,                 // #465 string(float bufhandle, string glue) buf_implode (DP_QC_STRINGBUFFERS)
VM_bufstr_get,                  // #466 string(float bufhandle, float string_index) bufstr_get (DP_QC_STRINGBUFFERS)
VM_bufstr_set,                  // #467 void(float bufhandle, float string_index, string str) bufstr_set (DP_QC_STRINGBUFFERS)
VM_bufstr_add,                  // #468 float(float bufhandle, string str, float order) bufstr_add (DP_QC_STRINGBUFFERS)
VM_bufstr_free,                 // #469 void(float bufhandle, float string_index) bufstr_free (DP_QC_STRINGBUFFERS)
NULL,                           // #470 void(float index, float type, .void field) SV_AddStat (EXT_CSQC)
VM_asin,                        // #471 float(float s) VM_asin (DP_QC_ASINACOSATANATAN2TAN)
VM_acos,                        // #472 float(float c) VM_acos (DP_QC_ASINACOSATANATAN2TAN)
VM_atan,                        // #473 float(float t) VM_atan (DP_QC_ASINACOSATANATAN2TAN)
VM_atan2,                       // #474 float(float c, float s) VM_atan2 (DP_QC_ASINACOSATANATAN2TAN)
VM_tan,                         // #475 float(float a) VM_tan (DP_QC_ASINACOSATANATAN2TAN)
VM_strlennocol,                 // #476 float(string s) : DRESK - String Length (not counting color codes) (DP_QC_STRINGCOLORFUNCTIONS)
VM_strdecolorize,               // #477 string(string s) : DRESK - Decolorized String (DP_QC_STRINGCOLORFUNCTIONS)
VM_strftime,                    // #478 string(float uselocaltime, string format, ...) (DP_QC_STRFTIME)
VM_tokenizebyseparator,         // #479 float(string s) tokenizebyseparator (DP_QC_TOKENIZEBYSEPARATOR)
VM_strtolower,                  // #480 string(string s) VM_strtolower (DP_QC_STRING_CASE_FUNCTIONS)
VM_strtoupper,                  // #481 string(string s) VM_strtoupper (DP_QC_STRING_CASE_FUNCTIONS)
VM_cvar_defstring,              // #482 string(string s) cvar_defstring (DP_QC_CVAR_DEFSTRING)
VM_CL_pointsound,               // #483 void(vector origin, string sample, float volume, float attenuation) pointsound (DP_SV_POINTSOUND)
VM_strreplace,                  // #484 string(string search, string replace, string subject) strreplace (DP_QC_STRREPLACE)
VM_strireplace,                 // #485 string(string search, string replace, string subject) strireplace (DP_QC_STRREPLACE)
VM_getsurfacepointattribute,// #486 vector(entity e, float s, float n, float a) getsurfacepointattribute
VM_gecko_create,                    // #487 float gecko_create(string name)
VM_gecko_destroy,                   // #488 void gecko_destroy(string name)
VM_gecko_navigate,              // #489 void gecko_navigate(string name, string URI)
VM_gecko_keyevent,              // #490 float gecko_keyevent(string name, float key, float eventtype)
VM_gecko_movemouse,             // #491 void gecko_mousemove(string name, float x, float y)
VM_gecko_resize,                    // #492 void gecko_resize(string name, float w, float h)
VM_gecko_get_texture_extent,    // #493 vector gecko_get_texture_extent(string name)
VM_crc16,                       // #494 float(float caseinsensitive, string s, ...) crc16 = #494 (DP_QC_CRC16)
VM_cvar_type,                   // #495 float(string name) cvar_type = #495; (DP_QC_CVAR_TYPE)
VM_numentityfields,             // #496 float() numentityfields = #496; (QP_QC_ENTITYDATA)
VM_entityfieldname,             // #497 string(float fieldnum) entityfieldname = #497; (DP_QC_ENTITYDATA)
VM_entityfieldtype,             // #498 float(float fieldnum) entityfieldtype = #498; (DP_QC_ENTITYDATA)
VM_getentityfieldstring,        // #499 string(float fieldnum, entity ent) getentityfieldstring = #499; (DP_QC_ENTITYDATA)
VM_putentityfieldstring,        // #500 float(float fieldnum, entity ent, string s) putentityfieldstring = #500; (DP_QC_ENTITYDATA)
VM_CL_ReadPicture,              // #501 string() ReadPicture = #501;
VM_CL_boxparticles,             // #502 void(float effectnum, entity own, vector origin_from, vector origin_to, vector dir_from, vector dir_to, float count) boxparticles (DP_CSQC_BOXPARTICLES)
VM_whichpack,                   // #503 string(string) whichpack = #503;
VM_CL_GetEntity,                // #504 float(float entitynum, float fldnum) getentity = #504; vector(float entitynum, float fldnum) getentityvec = #504;
NULL,                           // #505
NULL,                           // #506
NULL,                           // #507
NULL,                           // #508
NULL,                           // #509
VM_uri_escape,                  // #510 string(string in) uri_escape = #510;
VM_uri_unescape,                // #511 string(string in) uri_unescape = #511;
VM_etof,                    // #512 float(entity ent) num_for_edict = #512 (DP_QC_NUM_FOR_EDICT)
VM_uri_get,                     // #513 float(string uri, float id, [string post_contenttype, string post_delim, [float buf]]) uri_get = #513; (DP_QC_URI_GET, DP_QC_URI_POST)
VM_tokenize_console,                    // #514 float(string str) tokenize_console = #514; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_start_index,                    // #515 float(float idx) argv_start_index = #515; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_end_index,                      // #516 float(float idx) argv_end_index = #516; (DP_QC_TOKENIZE_CONSOLE)
VM_buf_cvarlist,                        // #517 void(float buf, string prefix, string antiprefix) buf_cvarlist = #517; (DP_QC_STRINGBUFFERS_CVARLIST)
VM_cvar_description,                    // #518 float(string name) cvar_description = #518; (DP_QC_CVAR_DESCRIPTION)
VM_gettime,                     // #519 float(float timer) gettime = #519; (DP_QC_GETTIME)
VM_keynumtostring,              // #520 string keynumtostring(float keynum)
VM_findkeysforcommand,          // #521 string findkeysforcommand(string command[, float bindmap])
VM_CL_InitParticleSpawner,      // #522 void(float max_themes) initparticlespawner (DP_CSQC_SPAWNPARTICLE)
VM_CL_ResetParticle,            // #523 void() resetparticle (DP_CSQC_SPAWNPARTICLE)
VM_CL_ParticleTheme,            // #524 void(float theme) particletheme (DP_CSQC_SPAWNPARTICLE)
VM_CL_ParticleThemeSave,        // #525 void() particlethemesave, void(float theme) particlethemeupdate (DP_CSQC_SPAWNPARTICLE)
VM_CL_ParticleThemeFree,        // #526 void() particlethemefree (DP_CSQC_SPAWNPARTICLE)
VM_CL_SpawnParticle,            // #527 float(vector org, vector vel, [float theme]) particle (DP_CSQC_SPAWNPARTICLE)
VM_CL_SpawnParticleDelayed,     // #528 float(vector org, vector vel, float delay, float collisiondelay, [float theme]) delayedparticle (DP_CSQC_SPAWNPARTICLE)
VM_loadfromdata,                // #529
VM_loadfromfile,                // #530
VM_CL_setpause,                 // #531 float(float ispaused) setpause = #531 (DP_CSQC_SETPAUSE)
VM_log,                         // #532
VM_getsoundtime,                // #533 float(entity e, float channel) getsoundtime = #533; (DP_SND_GETSOUNDTIME)
VM_soundlength,                 // #534 float(string sample) soundlength = #534; (DP_SND_GETSOUNDTIME)
VM_buf_loadfile,                // #535 float(string filename, float bufhandle) buf_loadfile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_buf_writefile,               // #536 float(float filehandle, float bufhandle, float startpos, float numstrings) buf_writefile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_bufstr_find,                 // #537 float(float bufhandle, string match, float matchrule, float startpos) bufstr_find (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_matchpattern,                // #538 float(string s, string pattern, float matchrule) matchpattern (DP_QC_STRINGBUFFERS_EXT_WIP)
NULL,                           // #539
VM_physics_enable,              // #540 void(entity e, float physics_enabled) physics_enable = #540; (DP_PHYSICS_ODE)
VM_physics_addforce,            // #541 void(entity e, vector force, vector relative_ofs) physics_addforce = #541; (DP_PHYSICS_ODE)
VM_physics_addtorque,           // #542 void(entity e, vector torque) physics_addtorque = #542; (DP_PHYSICS_ODE)
NULL,                           // #543
NULL,                           // #544
NULL,                           // #545
NULL,                           // #546
NULL,                           // #547
NULL,                           // #548
NULL,                           // #549
NULL,                           // #550
NULL,                           // #551
NULL,                           // #552
NULL,                           // #553
NULL,                           // #554
NULL,                           // #555
NULL,                           // #556
NULL,                           // #557
NULL,                           // #558
NULL,                           // #559
NULL,                           // #560
NULL,                           // #561
NULL,                           // #562
NULL,                           // #563
NULL,                           // #564
NULL,                           // #565
VM_CL_findbox,                  // #566 entity(vector mins, vector maxs) findbox = #566; (DP_QC_FINDBOX)
VM_nudgeoutofsolid,             // #567 float(entity ent) nudgeoutofsolid = #567; (DP_QC_NUDGEOUTOFSOLID)
NULL,                           // #568
NULL,                           // #569
NULL,                           // #570
NULL,                           // #571
NULL,                           // #572
NULL,                           // #573
NULL,                           // #574
NULL,                           // #575
NULL,                           // #576
NULL,                           // #577
NULL,                           // #578
NULL,                           // #579
NULL,                           // #580
NULL,                           // #581
NULL,                           // #582
NULL,                           // #583
NULL,                           // #584
NULL,                           // #585
NULL,                           // #586
NULL,                           // #587
NULL,                           // #588
NULL,                           // #589
NULL,                           // #590
NULL,                           // #591
NULL,                           // #592
NULL,                           // #593
NULL,                           // #594
NULL,                           // #595
NULL,                           // #596
NULL,                           // #597
NULL,                           // #598
NULL,                           // #599
NULL,                           // #600
NULL,                           // #601
NULL,                           // #602
NULL,                           // #603
NULL,                           // #604
VM_callfunction,                // #605
VM_writetofile,                 // #606
VM_isfunction,                  // #607
NULL,                           // #608
NULL,                           // #609
VM_findkeysforcommand,          // #610 string findkeysforcommand(string command[, float bindmap])
NULL,                           // #611
NULL,                           // #612
VM_parseentitydata,             // #613
NULL,                           // #614
NULL,                           // #615
NULL,                           // #616
NULL,                           // #617
NULL,                           // #618
NULL,                           // #619
NULL,                           // #620
NULL,                           // #621
NULL,                           // #622
NULL,                           // #623
VM_CL_getextresponse,           // #624 string getextresponse(void)
NULL,                           // #625
NULL,                           // #626
VM_sprintf,                     // #627 string sprintf(string format, ...)
VM_getsurfacenumtriangles,      // #628 float(entity e, float s) getsurfacenumpoints (DP_QC_GETSURFACETRIANGLE)
VM_getsurfacetriangle,          // #629 vector(entity e, float s, float n) getsurfacepoint (DP_QC_GETSURFACETRIANGLE)
VM_setkeybind,                      // #630 float(float key, string bind[, float bindmap]) setkeybind
VM_getbindmaps,                     // #631 vector(void) getbindmap
VM_setbindmaps,                     // #632 float(vector bm) setbindmap
NULL,                           // #633
NULL,                           // #634
NULL,                           // #635
NULL,                           // #636
NULL,                           // #637
VM_CL_RotateMoves,                  // #638
VM_digest_hex,                      // #639
VM_CL_V_CalcRefdef,                 // #640 void(entity e) V_CalcRefdef (DP_CSQC_V_CALCREFDEF)
NULL,                           // #641
VM_coverage,                        // #642
NULL
};
Referenced by CL_VM_Init().
vm_cl_numbuiltins
const int vm_cl_numbuiltins extern
Definition at line 5635 of file clvm_cmds.c.
Referenced by CL_VM_Init().
vm_m_builtins
prvm_builtin_t vm_m_builtins[] extern
Definition at line 1064 of file mvm_cmds.c.
{
NULL,                                   //   #0 NULL function (not callable)
VM_checkextension,              //   #1
VM_error,                           //   #2
VM_objerror,                        //   #3
VM_print,                           //   #4
VM_bprint,                          //   #5
VM_sprint,                          //   #6
VM_centerprint,                 //   #7
VM_normalize,                       //   #8
VM_vlen,                                //   #9
VM_vectoyaw,                        //  #10
VM_vectoangles,                 //  #11
VM_random,                          //  #12
VM_localcmd_local,                      //  #13
VM_cvar,                                //  #14
VM_cvar_set,                        //  #15
VM_dprint,                          //  #16
VM_ftos,                                //  #17
VM_fabs,                                //  #18
VM_vtos,                                //  #19
VM_etos,                                //  #20
VM_stof,                                //  #21
VM_spawn,                           //  #22
VM_remove,                          //  #23
VM_find,                                //  #24
VM_findfloat,                       //  #25
VM_findchain,                       //  #26
VM_findchainfloat,              //  #27
VM_precache_file,                   //  #28
VM_precache_sound,              //  #29
VM_coredump,                        //  #30
VM_traceon,                         //  #31
VM_traceoff,                        //  #32
VM_eprint,                          //  #33
VM_rint,                                //  #34
VM_floor,                           //  #35
VM_ceil,                                //  #36
VM_nextent,                         //  #37
VM_sin,                             //  #38
VM_cos,                             //  #39
VM_sqrt,                                //  #40
VM_randomvec,                       //  #41
VM_registercvar,                    //  #42
VM_min,                             //  #43
VM_max,                             //  #44
VM_bound,                           //  #45
VM_pow,                             //  #46
VM_M_copyentity,                    //  #47
VM_fopen,                           //  #48
VM_fclose,                          //  #49
VM_fgets,                           //  #50
VM_fputs,                           //  #51
VM_strlen,                          //  #52
VM_strcat,                          //  #53
VM_substring,                       //  #54
VM_stov,                                //  #55
VM_strzone,                         //  #56
VM_strunzone,                       //  #57
VM_tokenize,                        //  #58
VM_argv,                                //  #59
VM_isserver,                        //  #60
VM_clientcount,                 //  #61
VM_clientstate,                 //  #62
NULL,                       //  #63 FIXME
VM_changelevel,                 //  #64
VM_localsound,                      //  #65
VM_M_getmousepos,                   //  #66
VM_gettime,                         //  #67
VM_loadfromdata,                    //  #68
VM_loadfromfile,                    //  #69
VM_modulo,                          //  #70
VM_cvar_string,                 //  #71
VM_crash,                           //  #72
VM_stackdump,                       //  #73
VM_search_begin,                    //  #74
VM_search_end,                      //  #75
VM_search_getsize,              //  #76
VM_search_getfilename,          //  #77
VM_chr,                             //  #78
VM_itof,                                //  #79
VM_ftoe,                                //  #80
VM_itof,                                //  #81 isString
VM_altstr_count,                    //  #82
VM_altstr_prepare,              //  #83
VM_altstr_get,                      //  #84
VM_altstr_set,                      //  #85
VM_altstr_ins,                      //  #86
VM_findflags,                       //  #87
VM_findchainflags,              //  #88
VM_cvar_defstring,              //  #89
// deactivate support for model rendering in the menu until someone has time to do it right [3/2/2008 Andreas]
#if 0
VM_CL_setmodel,                 // #90 void(entity e, string m) setmodel (QUAKE)
VM_CL_precache_model,           // #91 void(string s) precache_model (QUAKE)
VM_CL_setorigin,                // #92 void(entity e, vector o) setorigin (QUAKE)
#else
NULL,
NULL,
NULL,
#endif
NULL,                                   //  #93
NULL,                                   //  #94
NULL,                                   //  #95
NULL,                                   //  #96
NULL,                                   //  #97
NULL,                                   //  #98
NULL,                                   //  #99
NULL,                                   // #100
NULL,                                   // #101
NULL,                                   // #102
NULL,                                   // #103
NULL,                                   // #104
NULL,                                   // #105
NULL,                                   // #106
NULL,                                   // #107
NULL,                                   // #108
NULL,                                   // #109
NULL,                                   // #110
NULL,                                   // #111
NULL,                                   // #112
NULL,                                   // #113
NULL,                                   // #114
NULL,                                   // #115
NULL,                                   // #116
NULL,                                   // #117
NULL,                                   // #118
NULL,                                   // #119
NULL,                                   // #120
NULL,                                   // #121
NULL,                                   // #122
NULL,                                   // #123
NULL,                                   // #124
NULL,                                   // #125
NULL,                                   // #126
NULL,                                   // #127
NULL,                                   // #128
NULL,                                   // #129
NULL,                                   // #130
NULL,                                   // #131
NULL,                                   // #132
NULL,                                   // #133
NULL,                                   // #134
NULL,                                   // #135
NULL,                                   // #136
NULL,                                   // #137
NULL,                                   // #138
NULL,                                   // #139
NULL,                                   // #140
NULL,                                   // #141
NULL,                                   // #142
NULL,                                   // #143
NULL,                                   // #144
NULL,                                   // #145
NULL,                                   // #146
NULL,                                   // #147
NULL,                                   // #148
NULL,                                   // #149
NULL,                                   // #150
NULL,                                   // #151
NULL,                                   // #152
NULL,                                   // #153
NULL,                                   // #154
NULL,                                   // #155
NULL,                                   // #156
NULL,                                   // #157
NULL,                                   // #158
NULL,                                   // #159
NULL,                                   // #160
NULL,                                   // #161
NULL,                                   // #162
NULL,                                   // #163
NULL,                                   // #164
NULL,                                   // #165
NULL,                                   // #166
NULL,                                   // #167
NULL,                                   // #168
NULL,                                   // #169
NULL,                                   // #170
NULL,                                   // #171
NULL,                                   // #172
NULL,                                   // #173
NULL,                                   // #174
NULL,                                   // #175
NULL,                                   // #176
NULL,                                   // #177
NULL,                                   // #178
NULL,                                   // #179
NULL,                                   // #180
NULL,                                   // #181
NULL,                                   // #182
NULL,                                   // #183
NULL,                                   // #184
NULL,                                   // #185
NULL,                                   // #186
NULL,                                   // #187
NULL,                                   // #188
NULL,                                   // #189
NULL,                                   // #190
NULL,                                   // #191
NULL,                                   // #192
NULL,                                   // #193
NULL,                                   // #194
NULL,                                   // #195
NULL,                                   // #196
NULL,                                   // #197
NULL,                                   // #198
NULL,                                   // #199
NULL,                                   // #200
NULL,                                   // #201
NULL,                                   // #202
NULL,                                   // #203
NULL,                                   // #204
NULL,                                   // #205
NULL,                                   // #206
NULL,                                   // #207
NULL,                                   // #208
NULL,                                   // #209
NULL,                                   // #210
NULL,                                   // #211
NULL,                                   // #212
NULL,                                   // #213
NULL,                                   // #214
NULL,                                   // #215
NULL,                                   // #216
NULL,                                   // #217
NULL,                                   // #218
NULL,                                   // #219
NULL,                                   // #220
VM_strstrofs,                       // #221 float(string str, string sub[, float startpos]) strstrofs (FTE_STRINGS)
VM_str2chr,                     // #222 float(string str, float ofs) str2chr (FTE_STRINGS)
VM_chr2str,                     // #223 string(float c, ...) chr2str (FTE_STRINGS)
VM_strconv,                     // #224 string(float ccase, float calpha, float cnum, string s, ...) strconv (FTE_STRINGS)
VM_strpad,                      // #225 string(float chars, string s, ...) strpad (FTE_STRINGS)
VM_infoadd,                     // #226 string(string info, string key, string value, ...) infoadd (FTE_STRINGS)
VM_infoget,                     // #227 string(string info, string key) infoget (FTE_STRINGS)
VM_strncmp,                         // #228 float(string s1, string s2, float len) strncmp (FTE_STRINGS)
VM_strncasecmp,                 // #229 float(string s1, string s2) strcasecmp (FTE_STRINGS)
VM_strncasecmp,                 // #230 float(string s1, string s2, float len) strncasecmp (FTE_STRINGS)
NULL,                                   // #231
NULL,                                   // #232
NULL,                                   // #233
NULL,                                   // #234
NULL,                                   // #235
NULL,                                   // #236
NULL,                                   // #237
NULL,                                   // #238
NULL,                                   // #239
NULL,                                   // #240
NULL,                                   // #241
NULL,                                   // #242
NULL,                                   // #243
NULL,                                   // #244
NULL,                                   // #245
NULL,                                   // #246
NULL,                                   // #247
NULL,                                   // #248
NULL,                                   // #249
NULL,                                   // #250
NULL,                                   // #251
NULL,                                   // #252
NULL,                                   // #253
NULL,                                   // #254
NULL,                                   // #255
NULL,                                   // #256
NULL,                                   // #257
NULL,                                   // #258
NULL,                                   // #259
NULL,                                   // #260
NULL,                                   // #261
NULL,                                   // #262
NULL,                                   // #263
NULL,                                   // #264
NULL,                                   // #265
NULL,                                   // #266
NULL,                                   // #267
NULL,                                   // #268
NULL,                                   // #269
NULL,                                   // #270
NULL,                                   // #271
NULL,                                   // #272
NULL,                                   // #273
NULL,                                   // #274
NULL,                                   // #275
NULL,                                   // #276
NULL,                                   // #277
NULL,                                   // #278
NULL,                                   // #279
NULL,                                   // #280
NULL,                                   // #281
NULL,                                   // #282
NULL,                                   // #283
NULL,                                   // #284
NULL,                                   // #285
NULL,                                   // #286
NULL,                                   // #287
NULL,                                   // #288
NULL,                                   // #289
NULL,                                   // #290
NULL,                                   // #291
NULL,                                   // #292
NULL,                                   // #293
NULL,                                   // #294
NULL,                                   // #295
NULL,                                   // #296
NULL,                                   // #297
NULL,                                   // #298
NULL,                                   // #299
// deactivate support for model rendering in the menu until someone has time to do it right [3/2/2008 Andreas]
#if 0
// CSQC range #300-#399
VM_CL_R_ClearScene,             // #300 void() clearscene (DP_QC_RENDER_SCENE)
VM_CL_R_AddEntities,            // #301 void(float mask) addentities (DP_QC_RENDER_SCENE)
VM_CL_R_AddEntity,              // #302 void(entity ent) addentity (DP_QC_RENDER_SCENE)
VM_CL_R_SetView,                // #303 float(float property, ...) setproperty (DP_QC_RENDER_SCENE)
VM_CL_R_RenderScene,            // #304 void() renderscene (DP_QC_RENDER_SCENE)
VM_CL_R_AddDynamicLight,        // #305 void(vector org, float radius, vector lightcolours) adddynamiclight (DP_QC_RENDER_SCENE)
VM_CL_R_PolygonBegin,           // #306 void(string texturename, float flag[, float is2d, float lines]) R_BeginPolygon (DP_QC_RENDER_SCENE)
VM_CL_R_PolygonVertex,          // #307 void(vector org, vector texcoords, vector rgb, float alpha) R_PolygonVertex (DP_QC_RENDER_SCENE)
VM_CL_R_PolygonEnd,             // #308 void() R_EndPolygon
NULL/*VM_CL_R_LoadWorldModel*/,             // #309 void(string modelname) R_LoadWorldModel
// TODO: rearrange and merge all builtin lists and share as many extensions as possible between all VM instances [1/27/2008 Andreas]
VM_CL_setattachment,                // #310 void(entity e, entity tagentity, string tagname) setattachment (DP_GFX_QUAKE3MODELTAGS) (DP_QC_RENDER_SCENE)
VM_CL_gettagindex,              // #311 float(entity ent, string tagname) gettagindex (DP_QC_GETTAGINFO) (DP_QC_RENDER_SCENE)
VM_CL_gettaginfo,                   // #312 vector(entity ent, float tagindex) gettaginfo (DP_QC_GETTAGINFO) (DP_QC_RENDER_SCENE)
#else
// CSQC range #300-#399
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
#endif
NULL,                                   // #313
NULL,                                   // #314
NULL,                                   // #315
NULL,                                   // #316
NULL,                                   // #317
NULL,                                   // #318
NULL,                                   // #319
NULL,                                   // #320
NULL,                                   // #321
NULL,                                   // #322
NULL,                                   // #323
NULL,                                   // #324
NULL,                                   // #325
NULL,                                   // #326
NULL,                                   // #327
NULL,                                   // #328
NULL,                                   // #329
NULL,                                   // #330
NULL,                                   // #331
NULL,                                   // #332
NULL,                                   // #333
NULL,                                   // #334
NULL,                                   // #335
NULL,                                   // #336
NULL,                                   // #337
NULL,                                   // #338
NULL,                                   // #339
VM_keynumtostring,              // #340 string keynumtostring(float keynum)
VM_stringtokeynum,              // #341 float stringtokeynum(string key)
VM_getkeybind,                          // #342 string(float keynum[, float bindmap]) getkeybind (EXT_CSQC)
NULL,                                   // #343
NULL,                                   // #344
NULL,                                   // #345
NULL,                                   // #346
NULL,                                   // #347
NULL,                                   // #348
VM_CL_isdemo,                           // #349
NULL,                                   // #350
NULL,                                   // #351
VM_M_registercommand,                   // #352 void(string cmdname)
VM_wasfreed,                            // #353 float(entity ent) wasfreed
NULL,                                   // #354
VM_CL_videoplaying,                     // #355
VM_findfont,                            // #356 float(string fontname) loadfont (DP_GFX_FONTS)
VM_loadfont,                            // #357 float(string fontname, string fontmaps, string sizes, float slot) loadfont (DP_GFX_FONTS)
NULL,                                   // #358
NULL,                                   // #359
NULL,                                   // #360
NULL,                                   // #361
NULL,                                   // #362
NULL,                                   // #363
NULL,                                   // #364
NULL,                                   // #365
NULL,                                   // #366
NULL,                                   // #367
NULL,                                   // #368
NULL,                                   // #369
NULL,                                   // #370
NULL,                                   // #371
NULL,                                   // #372
NULL,                                   // #373
NULL,                                   // #374
NULL,                                   // #375
NULL,                                   // #376
NULL,                                   // #377
NULL,                                   // #378
NULL,                                   // #379
NULL,                                   // #380
NULL,                                   // #381
NULL,                                   // #382
NULL,                                   // #383
NULL,                                   // #384
NULL,                                   // #385
NULL,                                   // #386
NULL,                                   // #387
NULL,                                   // #388
NULL,                                   // #389
NULL,                                   // #390
NULL,                                   // #391
NULL,                                   // #392
NULL,                                   // #393
NULL,                                   // #394
NULL,                                   // #395
NULL,                                   // #396
NULL,                                   // #397
NULL,                                   // #398
NULL,                                   // #399
NULL,                                   // #400
VM_M_WriteByte,                 // #401
VM_M_WriteChar,                 // #402
VM_M_WriteShort,                    // #403
VM_M_WriteLong,                 // #404
VM_M_WriteAngle,                    // #405
VM_M_WriteCoord,                    // #406
VM_M_WriteString,                   // #407
VM_M_WriteEntity,                   // #408
NULL,                                   // #409
NULL,                                   // #410
NULL,                                   // #411
NULL,                                   // #412
NULL,                                   // #413
NULL,                                   // #414
NULL,                                   // #415
NULL,                                   // #416
NULL,                                   // #417
NULL,                                   // #418
NULL,                                   // #419
NULL,                                   // #420
NULL,                                   // #421
NULL,                                   // #422
NULL,                                   // #423
NULL,                                   // #424
NULL,                                   // #425
NULL,                                   // #426
NULL,                                   // #427
NULL,                                   // #428
NULL,                                   // #429
NULL,                                   // #430
NULL,                                   // #431
NULL,                                   // #432
NULL,                                   // #433
NULL,                                   // #434
NULL,                                   // #435
NULL,                                   // #436
NULL,                                   // #437
NULL,                                   // #438
NULL,                                   // #439
VM_buf_create,                  // #440 float() buf_create (DP_QC_STRINGBUFFERS)
VM_buf_del,                     // #441 void(float bufhandle) buf_del (DP_QC_STRINGBUFFERS)
VM_buf_getsize,                 // #442 float(float bufhandle) buf_getsize (DP_QC_STRINGBUFFERS)
VM_buf_copy,                    // #443 void(float bufhandle_from, float bufhandle_to) buf_copy (DP_QC_STRINGBUFFERS)
VM_buf_sort,                    // #444 void(float bufhandle, float sortpower, float backward) buf_sort (DP_QC_STRINGBUFFERS)
VM_buf_implode,                 // #445 string(float bufhandle, string glue) buf_implode (DP_QC_STRINGBUFFERS)
VM_bufstr_get,                  // #446 string(float bufhandle, float string_index) bufstr_get (DP_QC_STRINGBUFFERS)
VM_bufstr_set,                  // #447 void(float bufhandle, float string_index, string str) bufstr_set (DP_QC_STRINGBUFFERS)
VM_bufstr_add,                  // #448 float(float bufhandle, string str, float order) bufstr_add (DP_QC_STRINGBUFFERS)
VM_bufstr_free,                 // #449 void(float bufhandle, float string_index) bufstr_free (DP_QC_STRINGBUFFERS)
NULL,                                   // #450
VM_iscachedpic,                 // #451 draw functions...
VM_precache_pic,                    // #452
VM_freepic,                         // #453
VM_drawcharacter,                   // #454
VM_drawstring,                      // #455
VM_drawpic,                         // #456
VM_drawfill,                        // #457
VM_drawsetcliparea,             // #458
VM_drawresetcliparea,           // #459
VM_getimagesize,                    // #460
VM_cin_open,                        // #461
VM_cin_close,                       // #462
VM_cin_setstate,                    // #463
VM_cin_getstate,                    // #464
VM_cin_restart,                     // #465
VM_drawline,                        // #466
VM_drawcolorcodedstring,        // #467
VM_stringwidth,                 // #468
VM_drawsubpic,                      // #469
VM_drawrotpic,                      // #470
VM_asin,                                // #471 float(float s) VM_asin (DP_QC_ASINACOSATANATAN2TAN)
VM_acos,                                // #472 float(float c) VM_acos (DP_QC_ASINACOSATANATAN2TAN)
VM_atan,                                // #473 float(float t) VM_atan (DP_QC_ASINACOSATANATAN2TAN)
VM_atan2,                           // #474 float(float c, float s) VM_atan2 (DP_QC_ASINACOSATANATAN2TAN)
VM_tan,                             // #475 float(float a) VM_tan (DP_QC_ASINACOSATANATAN2TAN)
VM_strlennocol,                 // #476 float(string s) : DRESK - String Length (not counting color codes) (DP_QC_STRINGCOLORFUNCTIONS)
VM_strdecolorize,                   // #477 string(string s) : DRESK - Decolorized String (DP_QC_STRINGCOLORFUNCTIONS)
VM_strftime,                        // #478 string(float uselocaltime, string format, ...) (DP_QC_STRFTIME)
VM_tokenizebyseparator,         // #479 float(string s) tokenizebyseparator (DP_QC_TOKENIZEBYSEPARATOR)
VM_strtolower,                      // #480 string(string s) VM_strtolower : DRESK - Return string as lowercase
VM_strtoupper,                      // #481 string(string s) VM_strtoupper : DRESK - Return string as uppercase
NULL,                                   // #482
NULL,                                   // #483
VM_strreplace,                      // #484 string(string search, string replace, string subject) strreplace (DP_QC_STRREPLACE)
VM_strireplace,                 // #485 string(string search, string replace, string subject) strireplace (DP_QC_STRREPLACE)
NULL,                                   // #486
VM_gecko_create,                    // #487 float gecko_create(string name)
VM_gecko_destroy,                   // #488 void gecko_destroy(string name)
VM_gecko_navigate,              // #489 void gecko_navigate(string name, string URI)
VM_gecko_keyevent,              // #490 float gecko_keyevent(string name, float key, float eventtype)
VM_gecko_movemouse,             // #491 void gecko_mousemove(string name, float x, float y)
VM_gecko_resize,                    // #492 void gecko_resize(string name, float w, float h)
VM_gecko_get_texture_extent,    // #493 vector gecko_get_texture_extent(string name)
VM_crc16,                       // #494 float(float caseinsensitive, string s, ...) crc16 = #494 (DP_QC_CRC16)
VM_cvar_type,                   // #495 float(string name) cvar_type = #495; (DP_QC_CVAR_TYPE)
VM_numentityfields,             // #496 float() numentityfields = #496; (QP_QC_ENTITYDATA)
VM_entityfieldname,             // #497 string(float fieldnum) entityfieldname = #497; (DP_QC_ENTITYDATA)
VM_entityfieldtype,             // #498 float(float fieldnum) entityfieldtype = #498; (DP_QC_ENTITYDATA)
VM_getentityfieldstring,        // #499 string(float fieldnum, entity ent) getentityfieldstring = #499; (DP_QC_ENTITYDATA)
VM_putentityfieldstring,        // #500 float(float fieldnum, entity ent, string s) putentityfieldstring = #500; (DP_QC_ENTITYDATA)
NULL,                                   // #501
NULL,                                   // #502
VM_whichpack,                   // #503 string(string) whichpack = #503;
NULL,                                   // #504
NULL,                                   // #505
NULL,                                   // #506
NULL,                                   // #507
NULL,                                   // #508
NULL,                                   // #509
VM_uri_escape,                  // #510 string(string in) uri_escape = #510;
VM_uri_unescape,                // #511 string(string in) uri_unescape = #511;
VM_etof,                    // #512 float(entity ent) num_for_edict = #512 (DP_QC_NUM_FOR_EDICT)
VM_uri_get,                     // #513 float(string uri, float id, [string post_contenttype, string post_delim, [float buf]]) uri_get = #513; (DP_QC_URI_GET, DP_QC_URI_POST)
VM_tokenize_console,                    // #514 float(string str) tokenize_console = #514; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_start_index,                    // #515 float(float idx) argv_start_index = #515; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_end_index,                      // #516 float(float idx) argv_end_index = #516; (DP_QC_TOKENIZE_CONSOLE)
VM_buf_cvarlist,                        // #517 void(float buf, string prefix, string antiprefix) buf_cvarlist = #517; (DP_QC_STRINGBUFFERS_CVARLIST)
VM_cvar_description,                    // #518 float(string name) cvar_description = #518; (DP_QC_CVAR_DESCRIPTION)
NULL,                                   // #519
NULL,                                   // #520
NULL,                                   // #521
NULL,                                   // #522
NULL,                                   // #523
NULL,                                   // #524
NULL,                                   // #525
NULL,                                   // #526
NULL,                                   // #527
NULL,                                   // #528
NULL,                                   // #529
NULL,                                   // #530
NULL,                                   // #531
VM_log,                                 // #532
VM_getsoundtime,                        // #533 float(entity e, float channel) getsoundtime = #533; (DP_SND_GETSOUNDTIME)
VM_soundlength,                         // #534 float(string sample) soundlength = #534; (DP_SND_GETSOUNDTIME)
VM_buf_loadfile,                        // #535 float(string filename, float bufhandle) buf_loadfile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_buf_writefile,                       // #536 float(float filehandle, float bufhandle, float startpos, float numstrings) buf_writefile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_bufstr_find,                         // #537 float(float bufhandle, string match, float matchrule, float startpos) bufstr_find (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_matchpattern,                        // #538 float(string s, string pattern, float matchrule) matchpattern (DP_QC_STRINGBUFFERS_EXT_WIP)
NULL,                                   // #539
NULL,                                   // #540
NULL,                                   // #541
NULL,                                   // #542
NULL,                                   // #543
NULL,                                   // #544
NULL,                                   // #545
NULL,                                   // #546
NULL,                                   // #547
NULL,                                   // #548
NULL,                                   // #549
NULL,                                   // #550
NULL,                                   // #551
NULL,                                   // #552
NULL,                                   // #553
NULL,                                   // #554
NULL,                                   // #555
NULL,                                   // #556
NULL,                                   // #557
NULL,                                   // #558
NULL,                                   // #559
NULL,                                   // #560
NULL,                                   // #561
NULL,                                   // #562
NULL,                                   // #563
NULL,                                   // #564
NULL,                                   // #565
NULL,                                   // #566
NULL,                                   // #567
NULL,                                   // #568
NULL,                                   // #569
NULL,                                   // #570
NULL,                                   // #571
NULL,                                   // #572
NULL,                                   // #573
NULL,                                   // #574
NULL,                                   // #575
NULL,                                   // #576
NULL,                                   // #577
NULL,                                   // #578
NULL,                                   // #579
NULL,                                   // #580
NULL,                                   // #581
NULL,                                   // #582
NULL,                                   // #583
NULL,                                   // #584
NULL,                                   // #585
NULL,                                   // #586
NULL,                                   // #587
NULL,                                   // #588
NULL,                                   // #589
NULL,                                   // #590
NULL,                                   // #591
NULL,                                   // #592
NULL,                                   // #593
NULL,                                   // #594
NULL,                                   // #595
NULL,                                   // #596
NULL,                                   // #597
NULL,                                   // #598
NULL,                                   // #599
NULL,                                   // #600
VM_M_setkeydest,                    // #601 void setkeydest(float dest)
VM_M_getkeydest,                    // #602 float getkeydest(void)
VM_M_setmousetarget,                // #603 void setmousetarget(float trg)
VM_M_getmousetarget,                // #604 float getmousetarget(void)
VM_callfunction,                // #605 void callfunction(...)
VM_writetofile,                 // #606 void writetofile(float fhandle, entity ent)
VM_isfunction,                  // #607 float isfunction(string function_name)
VM_M_getresolution,             // #608 vector getresolution(float number, [float forfullscreen])
VM_keynumtostring,              // #609 string keynumtostring(float keynum)
VM_findkeysforcommand,      // #610 string findkeysforcommand(string command[, float bindmap])
VM_M_getserverliststat,         // #611 float gethostcachevalue(float type)
VM_M_getserverliststring,       // #612 string gethostcachestring(float type, float hostnr)
VM_parseentitydata,             // #613 void parseentitydata(entity ent, string data)
VM_stringtokeynum,              // #614 float stringtokeynum(string key)
VM_M_resetserverlistmasks,      // #615 void resethostcachemasks(void)
VM_M_setserverlistmaskstring,   // #616 void sethostcachemaskstring(float mask, float fld, string str, float op)
VM_M_setserverlistmasknumber,   // #617 void sethostcachemasknumber(float mask, float fld, float num, float op)
VM_M_resortserverlist,          // #618 void resorthostcache(void)
VM_M_setserverlistsort,         // #619 void sethostcachesort(float fld, float descending)
VM_M_refreshserverlist,         // #620 void refreshhostcache(void)
VM_M_getserverlistnumber,       // #621 float gethostcachenumber(float fld, float hostnr)
VM_M_getserverlistindexforkey,// #622 float gethostcacheindexforkey(string key)
VM_M_addwantedserverlistkey,    // #623 void addwantedhostcachekey(string key)
VM_CL_getextresponse,           // #624 string getextresponse(void)
VM_netaddress_resolve,          // #625 string netaddress_resolve(string, float)
VM_M_getgamedirinfo,            // #626 string getgamedirinfo(float n, float prop)
VM_sprintf,                     // #627 string sprintf(string format, ...)
NULL, // #628
NULL, // #629
VM_setkeybind,                      // #630 float(float key, string bind[, float bindmap]) setkeybind
VM_getbindmaps,                     // #631 vector(void) getbindmap
VM_setbindmaps,                     // #632 float(vector bm) setbindmap
VM_M_crypto_getkeyfp,                   // #633 string(string addr) crypto_getkeyfp
VM_M_crypto_getidfp,                    // #634 string(string addr) crypto_getidfp
VM_M_crypto_getencryptlevel,                // #635 string(string addr) crypto_getencryptlevel
VM_M_crypto_getmykeyfp,                 // #636 string(float addr) crypto_getmykeyfp
VM_M_crypto_getmyidfp,                  // #637 string(float addr) crypto_getmyidfp
NULL,                           // #638
VM_digest_hex,                      // #639
NULL,                           // #640
VM_M_crypto_getmyidstatus,              // #641 float(float i) crypto_getmyidstatus
VM_coverage,                        // #642
VM_M_crypto_getidstatus,                // #643 float(string addr) crypto_getidstatus
NULL
};
Referenced by MP_Init().
vm_m_extensions
const char* vm_m_extensions[] extern
Definition at line 13 of file mvm_cmds.c.
{
"BX_WAL_SUPPORT",
"DP_CINEMATIC_DPV",
"DP_COVERAGE",
"DP_CRYPTO",
"DP_CSQC_BINDMAPS",
"DP_GFX_FONTS",
"DP_GFX_FONTS_FREETYPE",
"DP_UTF8",
"DP_FONT_VARIABLEWIDTH",
"DP_MENU_EXTRESPONSEPACKET",
"DP_QC_ASINACOSATANATAN2TAN",
"DP_QC_AUTOCVARS",
"DP_QC_CMD",
"DP_QC_CRC16",
"DP_QC_CVAR_TYPE",
"DP_QC_CVAR_DESCRIPTION",
"DP_QC_DIGEST",
"DP_QC_DIGEST_SHA256",
"DP_QC_FINDCHAIN_TOFIELD",
"DP_QC_I18N",
"DP_QC_LOG",
"DP_QC_RENDER_SCENE",
"DP_QC_SPRINTF",
"DP_QC_STRFTIME",
"DP_QC_STRINGBUFFERS",
"DP_QC_STRINGBUFFERS_CVARLIST",
"DP_QC_STRINGBUFFERS_EXT_WIP",
"DP_QC_STRINGCOLORFUNCTIONS",
"DP_QC_STRING_CASE_FUNCTIONS",
"DP_QC_STRREPLACE",
"DP_QC_TOKENIZEBYSEPARATOR",
"DP_QC_TOKENIZE_CONSOLE",
"DP_QC_UNLIMITEDTEMPSTRINGS",
"DP_QC_URI_ESCAPE",
"DP_QC_URI_GET",
"DP_QC_URI_POST",
"DP_QC_WHICHPACK",
"FTE_STRINGS",
"DP_QC_FS_SEARCH_PACKFILE",
NULL
};
Referenced by MP_Init(), and PRVM_Init().
vm_m_numbuiltins
const int vm_m_numbuiltins extern
Definition at line 1739 of file mvm_cmds.c.
Referenced by MP_Init().
vm_sv_builtins
prvm_builtin_t vm_sv_builtins[] extern
Definition at line 3266 of file svvm_cmds.c.
{
NULL,                           // #0 NULL function (not callable) (QUAKE)
VM_makevectors,                 // #1 void(vector ang) makevectors (QUAKE)
VM_SV_setorigin,                // #2 void(entity e, vector o) setorigin (QUAKE)
VM_SV_setmodel,                 // #3 void(entity e, string m) setmodel (QUAKE)
VM_SV_setsize,                  // #4 void(entity e, vector min, vector max) setsize (QUAKE)
NULL,                           // #5 void(entity e, vector min, vector max) setabssize (QUAKE)
VM_break,                       // #6 void() break (QUAKE)
VM_random,                      // #7 float() random (QUAKE)
VM_SV_sound,                    // #8 void(entity e, float chan, string samp, float volume[, float atten[, float pitchchange[, float flags]]]) sound (QUAKE)
VM_normalize,                   // #9 vector(vector v) normalize (QUAKE)
VM_error,                       // #10 void(string e) error (QUAKE)
VM_objerror,                    // #11 void(string e) objerror (QUAKE)
VM_vlen,                        // #12 float(vector v) vlen (QUAKE)
VM_vectoyaw,                    // #13 float(vector v) vectoyaw (QUAKE)
VM_spawn,                       // #14 entity() spawn (QUAKE)
VM_remove,                      // #15 void(entity e) remove (QUAKE)
VM_SV_traceline,                // #16 void(vector v1, vector v2, float tryents) traceline (QUAKE)
VM_SV_checkclient,              // #17 entity() checkclient (QUAKE)
VM_find,                        // #18 entity(entity start, .string fld, string match) find (QUAKE)
VM_SV_precache_sound,           // #19 void(string s) precache_sound (QUAKE)
VM_SV_precache_model,           // #20 void(string s) precache_model (QUAKE)
VM_SV_stuffcmd,                 // #21 void(entity client, string s, ...) stuffcmd (QUAKE)
VM_SV_findradius,               // #22 entity(vector org, float rad) findradius (QUAKE)
VM_bprint,                      // #23 void(string s, ...) bprint (QUAKE)
VM_SV_sprint,                   // #24 void(entity client, string s, ...) sprint (QUAKE)
VM_dprint,                      // #25 void(string s, ...) dprint (QUAKE)
VM_ftos,                        // #26 string(float f) ftos (QUAKE)
VM_vtos,                        // #27 string(vector v) vtos (QUAKE)
VM_coredump,                    // #28 void() coredump (QUAKE)
VM_traceon,                     // #29 void() traceon (QUAKE)
VM_traceoff,                    // #30 void() traceoff (QUAKE)
VM_eprint,                      // #31 void(entity e) eprint (QUAKE)
VM_SV_walkmove,                 // #32 float(float yaw, float dist) walkmove (QUAKE)
NULL,                           // #33 (QUAKE)
VM_SV_droptofloor,              // #34 float() droptofloor (QUAKE)
VM_SV_lightstyle,               // #35 void(float style, string value) lightstyle (QUAKE)
VM_rint,                        // #36 float(float v) rint (QUAKE)
VM_floor,                       // #37 float(float v) floor (QUAKE)
VM_ceil,                        // #38 float(float v) ceil (QUAKE)
NULL,                           // #39 (QUAKE)
VM_SV_checkbottom,              // #40 float(entity e) checkbottom (QUAKE)
VM_SV_pointcontents,            // #41 float(vector v) pointcontents (QUAKE)
NULL,                           // #42 (QUAKE)
VM_fabs,                        // #43 float(float f) fabs (QUAKE)
VM_SV_aim,                      // #44 vector(entity e, float speed) aim (QUAKE)
VM_cvar,                        // #45 float(string s) cvar (QUAKE)
VM_localcmd_server,             // #46 void(string s) localcmd (QUAKE)
VM_nextent,                     // #47 entity(entity e) nextent (QUAKE)
VM_SV_particle,                 // #48 void(vector o, vector d, float color, float count) particle (QUAKE)
VM_changeyaw,                   // #49 void() ChangeYaw (QUAKE)
NULL,                           // #50 (QUAKE)
VM_vectoangles,                 // #51 vector(vector v) vectoangles (QUAKE)
VM_SV_WriteByte,                // #52 void(float to, float f) WriteByte (QUAKE)
VM_SV_WriteChar,                // #53 void(float to, float f) WriteChar (QUAKE)
VM_SV_WriteShort,               // #54 void(float to, float f) WriteShort (QUAKE)
VM_SV_WriteLong,                // #55 void(float to, float f) WriteLong (QUAKE)
VM_SV_WriteCoord,               // #56 void(float to, float f) WriteCoord (QUAKE)
VM_SV_WriteAngle,               // #57 void(float to, float f) WriteAngle (QUAKE)
VM_SV_WriteString,              // #58 void(float to, string s) WriteString (QUAKE)
VM_SV_WriteEntity,              // #59 void(float to, entity e) WriteEntity (QUAKE)
VM_sin,                         // #60 float(float f) sin (DP_QC_SINCOSSQRTPOW) (QUAKE)
VM_cos,                         // #61 float(float f) cos (DP_QC_SINCOSSQRTPOW) (QUAKE)
VM_sqrt,                        // #62 float(float f) sqrt (DP_QC_SINCOSSQRTPOW) (QUAKE)
VM_changepitch,                 // #63 void(entity ent) changepitch (DP_QC_CHANGEPITCH) (QUAKE)
VM_SV_tracetoss,                // #64 void(entity e, entity ignore) tracetoss (DP_QC_TRACETOSS) (QUAKE)
VM_etos,                        // #65 string(entity ent) etos (DP_QC_ETOS) (QUAKE)
NULL,                           // #66 (QUAKE)
VM_SV_MoveToGoal,               // #67 void(float step) movetogoal (QUAKE)
VM_precache_file,               // #68 string(string s) precache_file (QUAKE)
VM_SV_makestatic,               // #69 void(entity e) makestatic (QUAKE)
VM_changelevel,                 // #70 void(string s) changelevel (QUAKE)
NULL,                           // #71 (QUAKE)
VM_cvar_set,                    // #72 void(string var, string val) cvar_set (QUAKE)
VM_SV_centerprint,              // #73 void(entity client, strings) centerprint (QUAKE)
VM_SV_ambientsound,             // #74 void(vector pos, string samp, float vol, float atten) ambientsound (QUAKE)
VM_SV_precache_model,           // #75 string(string s) precache_model2 (QUAKE)
VM_SV_precache_sound,           // #76 string(string s) precache_sound2 (QUAKE)
VM_precache_file,               // #77 string(string s) precache_file2 (QUAKE)
VM_SV_setspawnparms,            // #78 void(entity e) setspawnparms (QUAKE)
NULL,                           // #79 void(entity killer, entity killee) logfrag (QUAKEWORLD)
NULL,                           // #80 string(entity e, string keyname) infokey (QUAKEWORLD)
VM_stof,                        // #81 float(string s) stof (FRIK_FILE)
NULL,                           // #82 void(vector where, float set) multicast (QUAKEWORLD)
NULL,                           // #83 (QUAKE)
NULL,                           // #84 (QUAKE)
NULL,                           // #85 (QUAKE)
NULL,                           // #86 (QUAKE)
NULL,                           // #87 (QUAKE)
NULL,                           // #88 (QUAKE)
NULL,                           // #89 (QUAKE)
VM_SV_tracebox,                 // #90 void(vector v1, vector min, vector max, vector v2, float nomonsters, entity forent) tracebox (DP_QC_TRACEBOX)
VM_randomvec,                   // #91 vector() randomvec (DP_QC_RANDOMVEC)
VM_SV_getlight,                 // #92 vector(vector org) getlight (DP_QC_GETLIGHT)
VM_registercvar,                // #93 float(string name, string value) registercvar (DP_REGISTERCVAR)
VM_min,                         // #94 float(float a, floats) min (DP_QC_MINMAXBOUND)
VM_max,                         // #95 float(float a, floats) max (DP_QC_MINMAXBOUND)
VM_bound,                       // #96 float(float minimum, float val, float maximum) bound (DP_QC_MINMAXBOUND)
VM_pow,                         // #97 float(float f, float f) pow (DP_QC_SINCOSSQRTPOW)
VM_findfloat,                   // #98 entity(entity start, .float fld, float match) findfloat (DP_QC_FINDFLOAT)
VM_checkextension,              // #99 float(string s) checkextension (the basis of the extension system)
// FrikaC and Telejano range  #100-#199
NULL,                           // #100
NULL,                           // #101
NULL,                           // #102
NULL,                           // #103
NULL,                           // #104
NULL,                           // #105
NULL,                           // #106
NULL,                           // #107
NULL,                           // #108
NULL,                           // #109
VM_fopen,                       // #110 float(string filename, float mode) fopen (FRIK_FILE)
VM_fclose,                      // #111 void(float fhandle) fclose (FRIK_FILE)
VM_fgets,                       // #112 string(float fhandle) fgets (FRIK_FILE)
VM_fputs,                       // #113 void(float fhandle, string s) fputs (FRIK_FILE)
VM_strlen,                      // #114 float(string s) strlen (FRIK_FILE)
VM_strcat,                      // #115 string(string s, string...) strcat (FRIK_FILE)
VM_substring,                   // #116 string(string s, float start, float length) substring (FRIK_FILE)
VM_stov,                        // #117 vector(string) stov (FRIK_FILE)
VM_strzone,                     // #118 string(string s) strzone (FRIK_FILE)
VM_strunzone,                   // #119 void(string s) strunzone (FRIK_FILE)
NULL,                           // #120
NULL,                           // #121
NULL,                           // #122
NULL,                           // #123
NULL,                           // #124
NULL,                           // #125
NULL,                           // #126
NULL,                           // #127
NULL,                           // #128
NULL,                           // #129
NULL,                           // #130
NULL,                           // #131
NULL,                           // #132
NULL,                           // #133
NULL,                           // #134
NULL,                           // #135
NULL,                           // #136
NULL,                           // #137
NULL,                           // #138
NULL,                           // #139
NULL,                           // #140
NULL,                           // #141
NULL,                           // #142
NULL,                           // #143
NULL,                           // #144
NULL,                           // #145
NULL,                           // #146
NULL,                           // #147
NULL,                           // #148
NULL,                           // #149
NULL,                           // #150
NULL,                           // #151
NULL,                           // #152
NULL,                           // #153
NULL,                           // #154
NULL,                           // #155
NULL,                           // #156
NULL,                           // #157
NULL,                           // #158
NULL,                           // #159
NULL,                           // #160
NULL,                           // #161
NULL,                           // #162
NULL,                           // #163
NULL,                           // #164
NULL,                           // #165
NULL,                           // #166
NULL,                           // #167
NULL,                           // #168
NULL,                           // #169
NULL,                           // #170
NULL,                           // #171
NULL,                           // #172
NULL,                           // #173
NULL,                           // #174
NULL,                           // #175
NULL,                           // #176
NULL,                           // #177
NULL,                           // #178
NULL,                           // #179
NULL,                           // #180
NULL,                           // #181
NULL,                           // #182
NULL,                           // #183
NULL,                           // #184
NULL,                           // #185
NULL,                           // #186
NULL,                           // #187
NULL,                           // #188
NULL,                           // #189
NULL,                           // #190
NULL,                           // #191
NULL,                           // #192
NULL,                           // #193
NULL,                           // #194
NULL,                           // #195
NULL,                           // #196
NULL,                           // #197
NULL,                           // #198
NULL,                           // #199
// FTEQW range #200-#299
NULL,                           // #200
NULL,                           // #201
NULL,                           // #202
NULL,                           // #203
NULL,                           // #204
NULL,                           // #205
NULL,                           // #206
NULL,                           // #207
NULL,                           // #208
NULL,                           // #209
NULL,                           // #210
NULL,                           // #211
NULL,                           // #212
NULL,                           // #213
NULL,                           // #214
NULL,                           // #215
NULL,                           // #216
NULL,                           // #217
VM_bitshift,                    // #218 float(float number, float quantity) bitshift (EXT_BITSHIFT)
NULL,                           // #219
NULL,                           // #220
VM_strstrofs,                   // #221 float(string str, string sub[, float startpos]) strstrofs (FTE_STRINGS)
VM_str2chr,                     // #222 float(string str, float ofs) str2chr (FTE_STRINGS)
VM_chr2str,                     // #223 string(float c, ...) chr2str (FTE_STRINGS)
VM_strconv,                     // #224 string(float ccase, float calpha, float cnum, string s, ...) strconv (FTE_STRINGS)
VM_strpad,                      // #225 string(float chars, string s, ...) strpad (FTE_STRINGS)
VM_infoadd,                     // #226 string(string info, string key, string value, ...) infoadd (FTE_STRINGS)
VM_infoget,                     // #227 string(string info, string key) infoget (FTE_STRINGS)
VM_strncmp,                     // #228 float(string s1, string s2, float len) strncmp (FTE_STRINGS)
VM_strncasecmp,                 // #229 float(string s1, string s2) strcasecmp (FTE_STRINGS)
VM_strncasecmp,                 // #230 float(string s1, string s2, float len) strncasecmp (FTE_STRINGS)
NULL,                           // #231
VM_SV_AddStat,                  // #232 void(float index, float type, .void field) SV_AddStat (EXT_CSQC)
NULL,                           // #233
NULL,                           // #234
NULL,                           // #235
NULL,                           // #236
NULL,                           // #237
NULL,                           // #238
NULL,                           // #239
VM_SV_checkpvs,                 // #240 float(vector viewpos, entity viewee) checkpvs;
NULL,                           // #241
NULL,                           // #242
NULL,                           // #243
NULL,                           // #244
VM_modulo,                      // #245
NULL,                           // #246
NULL,                           // #247
NULL,                           // #248
NULL,                           // #249
NULL,                           // #250
NULL,                           // #251
NULL,                           // #252
NULL,                           // #253
NULL,                           // #254
NULL,                           // #255
NULL,                           // #256
NULL,                           // #257
NULL,                           // #258
NULL,                           // #259
NULL,                           // #260
NULL,                           // #261
NULL,                           // #262
VM_SV_skel_create,              // #263 float(float modlindex) skel_create = #263; // (DP_SKELETONOBJECTS) create a skeleton (be sure to assign this value into .skeletonindex for use), returns skeleton index (1 or higher) on success, returns 0 on failure  (for example if the modelindex is not skeletal), it is recommended that you create a new skeleton if you change modelindex.
VM_SV_skel_build,               // #264 float(float skel, entity ent, float modlindex, float retainfrac, float firstbone, float lastbone) skel_build = #264; // (DP_SKELETONOBJECTS) blend in a percentage of standard animation, 0 replaces entirely, 1 does nothing, 0.5 blends half, etc, and this only alters the bones in the specified range for which out of bounds values like 0,100000 are safe (uses .frame, .frame2, .frame3, .frame4, .lerpfrac, .lerpfrac3, .lerpfrac4, .frame1time, .frame2time, .frame3time, .frame4time), returns skel on success, 0 on failure
VM_SV_skel_get_numbones,        // #265 float(float skel) skel_get_numbones = #265; // (DP_SKELETONOBJECTS) returns how many bones exist in the created skeleton
VM_SV_skel_get_bonename,        // #266 string(float skel, float bonenum) skel_get_bonename = #266; // (DP_SKELETONOBJECTS) returns name of bone (as a tempstring)
VM_SV_skel_get_boneparent,      // #267 float(float skel, float bonenum) skel_get_boneparent = #267; // (DP_SKELETONOBJECTS) returns parent num for supplied bonenum, -1 if bonenum has no parent or bone does not exist (returned value is always less than bonenum, you can loop on this)
VM_SV_skel_find_bone,           // #268 float(float skel, string tagname) skel_find_bone = #268; // (DP_SKELETONOBJECTS) get number of bone with specified name, 0 on failure, tagindex (bonenum+1) on success, same as using gettagindex on the modelindex
VM_SV_skel_get_bonerel,         // #269 vector(float skel, float bonenum) skel_get_bonerel = #269; // (DP_SKELETONOBJECTS) get matrix of bone in skeleton relative to its parent - sets v_forward, v_right, v_up, returns origin (relative to parent bone)
VM_SV_skel_get_boneabs,         // #270 vector(float skel, float bonenum) skel_get_boneabs = #270; // (DP_SKELETONOBJECTS) get matrix of bone in skeleton in model space - sets v_forward, v_right, v_up, returns origin (relative to entity)
VM_SV_skel_set_bone,            // #271 void(float skel, float bonenum, vector org) skel_set_bone = #271; // (DP_SKELETONOBJECTS) set matrix of bone relative to its parent, reads v_forward, v_right, v_up, takes origin as parameter (relative to parent bone)
VM_SV_skel_mul_bone,            // #272 void(float skel, float bonenum, vector org) skel_mul_bone = #272; // (DP_SKELETONOBJECTS) transform bone matrix (relative to its parent) by the supplied matrix in v_forward, v_right, v_up, takes origin as parameter (relative to parent bone)
VM_SV_skel_mul_bones,           // #273 void(float skel, float startbone, float endbone, vector org) skel_mul_bones = #273; // (DP_SKELETONOBJECTS) transform bone matrices (relative to their parents) by the supplied matrix in v_forward, v_right, v_up, takes origin as parameter (relative to parent bones)
VM_SV_skel_copybones,           // #274 void(float skeldst, float skelsrc, float startbone, float endbone) skel_copybones = #274; // (DP_SKELETONOBJECTS) copy bone matrices (relative to their parents) from one skeleton to another, useful for copying a skeleton to a corpse
VM_SV_skel_delete,              // #275 void(float skel) skel_delete = #275; // (DP_SKELETONOBJECTS) deletes skeleton at the beginning of the next frame (you can add the entity, delete the skeleton, renderscene, and it will still work)
VM_SV_frameforname,             // #276 float(float modlindex, string framename) frameforname = #276; // (DP_SKELETONOBJECTS) finds number of a specified frame in the animation, returns -1 if no match found
VM_SV_frameduration,            // #277 float(float modlindex, float framenum) frameduration = #277; // (DP_SKELETONOBJECTS) returns the intended play time (in seconds) of the specified framegroup, if it does not exist the result is 0, if it is a single frame it may be a small value around 0.1 or 0.
NULL,                           // #278
NULL,                           // #279
NULL,                           // #280
NULL,                           // #281
NULL,                           // #282
NULL,                           // #283
NULL,                           // #284
NULL,                           // #285
NULL,                           // #286
NULL,                           // #287
NULL,                           // #288
NULL,                           // #289
NULL,                           // #290
NULL,                           // #291
NULL,                           // #292
NULL,                           // #293
NULL,                           // #294
NULL,                           // #295
NULL,                           // #296
NULL,                           // #297
NULL,                           // #298
NULL,                           // #299
// CSQC range #300-#399
NULL,                           // #300 void() clearscene (EXT_CSQC)
NULL,                           // #301 void(float mask) addentities (EXT_CSQC)
NULL,                           // #302 void(entity ent) addentity (EXT_CSQC)
NULL,                           // #303 float(float property, ...) setproperty (EXT_CSQC)
NULL,                           // #304 void() renderscene (EXT_CSQC)
NULL,                           // #305 void(vector org, float radius, vector lightcolours) adddynamiclight (EXT_CSQC)
NULL,                           // #306 void(string texturename, float flag[, float is2d, float lines]) R_BeginPolygon
NULL,                           // #307 void(vector org, vector texcoords, vector rgb, float alpha) R_PolygonVertex
NULL,                           // #308 void() R_EndPolygon
NULL,                           // #309
NULL,                           // #310 vector (vector v) cs_unproject (EXT_CSQC)
NULL,                           // #311 vector (vector v) cs_project (EXT_CSQC)
NULL,                           // #312
NULL,                           // #313
NULL,                           // #314
NULL,                           // #315 void(float width, vector pos1, vector pos2, float flag) drawline (EXT_CSQC)
NULL,                           // #316 float(string name) iscachedpic (EXT_CSQC)
NULL,                           // #317 string(string name, float trywad) precache_pic (EXT_CSQC)
NULL,                           // #318 vector(string picname) draw_getimagesize (EXT_CSQC)
NULL,                           // #319 void(string name) freepic (EXT_CSQC)
NULL,                           // #320 float(vector position, float character, vector scale, vector rgb, float alpha, float flag) drawcharacter (EXT_CSQC)
NULL,                           // #321 float(vector position, string text, vector scale, vector rgb, float alpha, float flag) drawstring (EXT_CSQC)
NULL,                           // #322 float(vector position, string pic, vector size, vector rgb, float alpha, float flag) drawpic (EXT_CSQC)
NULL,                           // #323 float(vector position, vector size, vector rgb, float alpha, float flag) drawfill (EXT_CSQC)
NULL,                           // #324 void(float x, float y, float width, float height) drawsetcliparea
NULL,                           // #325 void(void) drawresetcliparea
NULL,                           // #326
NULL,                           // #327
NULL,                           // #328
NULL,                           // #329
NULL,                           // #330 float(float stnum) getstatf (EXT_CSQC)
NULL,                           // #331 float(float stnum) getstati (EXT_CSQC)
NULL,                           // #332 string(float firststnum) getstats (EXT_CSQC)
VM_SV_setmodelindex,            // #333 void(entity e, float mdlindex) setmodelindex (EXT_CSQC)
VM_SV_modelnameforindex,        // #334 string(float mdlindex) modelnameforindex (EXT_CSQC)
VM_SV_particleeffectnum,        // #335 float(string effectname) particleeffectnum (EXT_CSQC)
VM_SV_trailparticles,           // #336 void(entity ent, float effectnum, vector start, vector end) trailparticles (EXT_CSQC)
VM_SV_pointparticles,           // #337 void(float effectnum, vector origin [, vector dir, float count]) pointparticles (EXT_CSQC)
NULL,                           // #338 void(string s, ...) centerprint (EXT_CSQC)
VM_print,                       // #339 void(string s, ...) print (EXT_CSQC, DP_SV_PRINT)
NULL,                           // #340 string(float keynum) keynumtostring (EXT_CSQC)
NULL,                           // #341 float(string keyname) stringtokeynum (EXT_CSQC)
NULL,                           // #342 string(float keynum) getkeybind (EXT_CSQC)
NULL,                           // #343 void(float usecursor) setcursormode (EXT_CSQC)
NULL,                           // #344 vector() getmousepos (EXT_CSQC)
NULL,                           // #345 float(float framenum) getinputstate (EXT_CSQC)
NULL,                           // #346 void(float sens) setsensitivityscaler (EXT_CSQC)
NULL,                           // #347 void() runstandardplayerphysics (EXT_CSQC)
NULL,                           // #348 string(float playernum, string keyname) getplayerkeyvalue (EXT_CSQC)
NULL,                           // #349 float() isdemo (EXT_CSQC)
VM_isserver,                    // #350 float() isserver (EXT_CSQC)
NULL,                           // #351 void(vector origin, vector forward, vector right, vector up) SetListener (EXT_CSQC)
VM_SV_registercommand,          // #352 void(string cmdname) registercommand (EXT_CSQC)
VM_wasfreed,                    // #353 float(entity ent) wasfreed (EXT_CSQC) (should be availabe on server too)
VM_SV_serverkey,                // #354 string(string key) serverkey (EXT_CSQC)
NULL,                           // #355
NULL,                           // #356
NULL,                           // #357
NULL,                           // #358
NULL,                           // #359
NULL,                           // #360 float() readbyte (EXT_CSQC)
NULL,                           // #361 float() readchar (EXT_CSQC)
NULL,                           // #362 float() readshort (EXT_CSQC)
NULL,                           // #363 float() readlong (EXT_CSQC)
NULL,                           // #364 float() readcoord (EXT_CSQC)
NULL,                           // #365 float() readangle (EXT_CSQC)
NULL,                           // #366 string() readstring (EXT_CSQC)
NULL,                           // #367 float() readfloat (EXT_CSQC)
NULL,                           // #368
NULL,                           // #369
NULL,                           // #370
NULL,                           // #371
NULL,                           // #372
NULL,                           // #373
NULL,                           // #374
NULL,                           // #375
NULL,                           // #376
NULL,                           // #377
NULL,                           // #378
NULL,                           // #379
NULL,                           // #380
NULL,                           // #381
NULL,                           // #382
NULL,                           // #383
NULL,                           // #384
NULL,                           // #385
NULL,                           // #386
NULL,                           // #387
NULL,                           // #388
NULL,                           // #389
NULL,                           // #390
NULL,                           // #391
NULL,                           // #392
NULL,                           // #393
NULL,                           // #394
NULL,                           // #395
NULL,                           // #396
NULL,                           // #397
NULL,                           // #398
NULL,                           // #399
// LadyHavoc's range #400-#499
VM_SV_copyentity,               // #400 void(entity from, entity to) copyentity (DP_QC_COPYENTITY)
VM_SV_setcolor,                 // #401 void(entity ent, float colors) setcolor (DP_QC_SETCOLOR)
VM_findchain,                   // #402 entity(.string fld, string match) findchain (DP_QC_FINDCHAIN)
VM_findchainfloat,              // #403 entity(.float fld, float match) findchainfloat (DP_QC_FINDCHAINFLOAT)
VM_SV_effect,                   // #404 void(vector org, string modelname, float startframe, float endframe, float framerate) effect (DP_SV_EFFECT)
VM_SV_te_blood,                 // #405 void(vector org, vector velocity, float howmany) te_blood (DP_TE_BLOOD)
VM_SV_te_bloodshower,           // #406 void(vector mincorner, vector maxcorner, float explosionspeed, float howmany) te_bloodshower (DP_TE_BLOODSHOWER)
VM_SV_te_explosionrgb,          // #407 void(vector org, vector color) te_explosionrgb (DP_TE_EXPLOSIONRGB)
VM_SV_te_particlecube,          // #408 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color, float gravityflag, float randomveljitter) te_particlecube (DP_TE_PARTICLECUBE)
VM_SV_te_particlerain,          // #409 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlerain (DP_TE_PARTICLERAIN)
VM_SV_te_particlesnow,          // #410 void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlesnow (DP_TE_PARTICLESNOW)
VM_SV_te_spark,                 // #411 void(vector org, vector vel, float howmany) te_spark (DP_TE_SPARK)
VM_SV_te_gunshotquad,           // #412 void(vector org) te_gunshotquad (DP_QUADEFFECTS1)
VM_SV_te_spikequad,             // #413 void(vector org) te_spikequad (DP_QUADEFFECTS1)
VM_SV_te_superspikequad,        // #414 void(vector org) te_superspikequad (DP_QUADEFFECTS1)
VM_SV_te_explosionquad,         // #415 void(vector org) te_explosionquad (DP_QUADEFFECTS1)
VM_SV_te_smallflash,            // #416 void(vector org) te_smallflash (DP_TE_SMALLFLASH)
VM_SV_te_customflash,           // #417 void(vector org, float radius, float lifetime, vector color) te_customflash (DP_TE_CUSTOMFLASH)
VM_SV_te_gunshot,               // #418 void(vector org) te_gunshot (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_spike,                 // #419 void(vector org) te_spike (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_superspike,            // #420 void(vector org) te_superspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_explosion,             // #421 void(vector org) te_explosion (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_tarexplosion,          // #422 void(vector org) te_tarexplosion (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_wizspike,              // #423 void(vector org) te_wizspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_knightspike,           // #424 void(vector org) te_knightspike (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_lavasplash,            // #425 void(vector org) te_lavasplash (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_teleport,              // #426 void(vector org) te_teleport (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_explosion2,            // #427 void(vector org, float colorstart, float colorlength) te_explosion2 (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_lightning1,            // #428 void(entity own, vector start, vector end) te_lightning1 (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_lightning2,            // #429 void(entity own, vector start, vector end) te_lightning2 (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_lightning3,            // #430 void(entity own, vector start, vector end) te_lightning3 (DP_TE_STANDARDEFFECTBUILTINS)
VM_SV_te_beam,                  // #431 void(entity own, vector start, vector end) te_beam (DP_TE_STANDARDEFFECTBUILTINS)
VM_vectorvectors,               // #432 void(vector dir) vectorvectors (DP_QC_VECTORVECTORS)
VM_SV_te_plasmaburn,            // #433 void(vector org) te_plasmaburn (DP_TE_PLASMABURN)
VM_getsurfacenumpoints,     // #434 float(entity e, float s) getsurfacenumpoints (DP_QC_GETSURFACE)
VM_getsurfacepoint,         // #435 vector(entity e, float s, float n) getsurfacepoint (DP_QC_GETSURFACE)
VM_getsurfacenormal,            // #436 vector(entity e, float s) getsurfacenormal (DP_QC_GETSURFACE)
VM_getsurfacetexture,       // #437 string(entity e, float s) getsurfacetexture (DP_QC_GETSURFACE)
VM_getsurfacenearpoint,     // #438 float(entity e, vector p) getsurfacenearpoint (DP_QC_GETSURFACE)
VM_getsurfaceclippedpoint,  // #439 vector(entity e, float s, vector p) getsurfaceclippedpoint (DP_QC_GETSURFACE)
VM_SV_clientcommand,            // #440 void(entity e, string s) clientcommand (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_tokenize,                    // #441 float(string s) tokenize (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_argv,                        // #442 string(float n) argv (KRIMZON_SV_PARSECLIENTCOMMAND)
VM_SV_setattachment,            // #443 void(entity e, entity tagentity, string tagname) setattachment (DP_GFX_QUAKE3MODELTAGS)
VM_search_begin,                // #444 float(string pattern, float caseinsensitive, float quiet) search_begin (DP_QC_FS_SEARCH)
VM_search_end,                  // #445 void(float handle) search_end (DP_QC_FS_SEARCH)
VM_search_getsize,              // #446 float(float handle) search_getsize (DP_QC_FS_SEARCH)
VM_search_getfilename,          // #447 string(float handle, float num) search_getfilename (DP_QC_FS_SEARCH)
VM_cvar_string,                 // #448 string(string s) cvar_string (DP_QC_CVAR_STRING)
VM_findflags,                   // #449 entity(entity start, .float fld, float match) findflags (DP_QC_FINDFLAGS)
VM_findchainflags,              // #450 entity(.float fld, float match) findchainflags (DP_QC_FINDCHAINFLAGS)
VM_SV_gettagindex,              // #451 float(entity ent, string tagname) gettagindex (DP_QC_GETTAGINFO)
VM_SV_gettaginfo,               // #452 vector(entity ent, float tagindex) gettaginfo (DP_QC_GETTAGINFO)
VM_SV_dropclient,               // #453 void(entity clent) dropclient (DP_SV_DROPCLIENT)
VM_SV_spawnclient,              // #454 entity() spawnclient (DP_SV_BOTCLIENT)
VM_SV_clienttype,               // #455 float(entity clent) clienttype (DP_SV_BOTCLIENT)
VM_SV_WriteUnterminatedString,  // #456 void(float to, string s) WriteUnterminatedString (DP_SV_WRITEUNTERMINATEDSTRING)
VM_SV_te_flamejet,              // #457 void(vector org, vector vel, float howmany) te_flamejet = #457 (DP_TE_FLAMEJET)
NULL,                           // #458
VM_ftoe,                        // #459 entity(float num) entitybyindex (DP_QC_EDICT_NUM)
VM_buf_create,                  // #460 float() buf_create (DP_QC_STRINGBUFFERS)
VM_buf_del,                     // #461 void(float bufhandle) buf_del (DP_QC_STRINGBUFFERS)
VM_buf_getsize,                 // #462 float(float bufhandle) buf_getsize (DP_QC_STRINGBUFFERS)
VM_buf_copy,                    // #463 void(float bufhandle_from, float bufhandle_to) buf_copy (DP_QC_STRINGBUFFERS)
VM_buf_sort,                    // #464 void(float bufhandle, float sortpower, float backward) buf_sort (DP_QC_STRINGBUFFERS)
VM_buf_implode,                 // #465 string(float bufhandle, string glue) buf_implode (DP_QC_STRINGBUFFERS)
VM_bufstr_get,                  // #466 string(float bufhandle, float string_index) bufstr_get (DP_QC_STRINGBUFFERS)
VM_bufstr_set,                  // #467 void(float bufhandle, float string_index, string str) bufstr_set (DP_QC_STRINGBUFFERS)
VM_bufstr_add,                  // #468 float(float bufhandle, string str, float order) bufstr_add (DP_QC_STRINGBUFFERS)
VM_bufstr_free,                 // #469 void(float bufhandle, float string_index) bufstr_free (DP_QC_STRINGBUFFERS)
NULL,                           // #470
VM_asin,                        // #471 float(float s) VM_asin (DP_QC_ASINACOSATANATAN2TAN)
VM_acos,                        // #472 float(float c) VM_acos (DP_QC_ASINACOSATANATAN2TAN)
VM_atan,                        // #473 float(float t) VM_atan (DP_QC_ASINACOSATANATAN2TAN)
VM_atan2,                       // #474 float(float c, float s) VM_atan2 (DP_QC_ASINACOSATANATAN2TAN)
VM_tan,                         // #475 float(float a) VM_tan (DP_QC_ASINACOSATANATAN2TAN)
VM_strlennocol,                 // #476 float(string s) : DRESK - String Length (not counting color codes) (DP_QC_STRINGCOLORFUNCTIONS)
VM_strdecolorize,               // #477 string(string s) : DRESK - Decolorized String (DP_SV_STRINGCOLORFUNCTIONS)
VM_strftime,                    // #478 string(float uselocaltime, string format, ...) (DP_QC_STRFTIME)
VM_tokenizebyseparator,         // #479 float(string s) tokenizebyseparator (DP_QC_TOKENIZEBYSEPARATOR)
VM_strtolower,                  // #480 string(string s) VM_strtolower (DP_QC_STRING_CASE_FUNCTIONS)
VM_strtoupper,                  // #481 string(string s) VM_strtoupper (DP_QC_STRING_CASE_FUNCTIONS)
VM_cvar_defstring,              // #482 string(string s) cvar_defstring (DP_QC_CVAR_DEFSTRING)
VM_SV_pointsound,               // #483 void(vector origin, string sample, float volume, float attenuation) (DP_SV_POINTSOUND)
VM_strreplace,                  // #484 string(string search, string replace, string subject) strreplace (DP_QC_STRREPLACE)
VM_strireplace,                 // #485 string(string search, string replace, string subject) strireplace (DP_QC_STRREPLACE)
VM_getsurfacepointattribute,// #486 vector(entity e, float s, float n, float a) getsurfacepointattribute = #486;
NULL,                           // #487
NULL,                           // #488
NULL,                           // #489
NULL,                           // #490
NULL,                           // #491
NULL,                           // #492
NULL,                           // #493
VM_crc16,                       // #494 float(float caseinsensitive, string s, ...) crc16 = #494 (DP_QC_CRC16)
VM_cvar_type,                   // #495 float(string name) cvar_type = #495; (DP_QC_CVAR_TYPE)
VM_numentityfields,             // #496 float() numentityfields = #496; (DP_QC_ENTITYDATA)
VM_entityfieldname,             // #497 string(float fieldnum) entityfieldname = #497; (DP_QC_ENTITYDATA)
VM_entityfieldtype,             // #498 float(float fieldnum) entityfieldtype = #498; (DP_QC_ENTITYDATA)
VM_getentityfieldstring,        // #499 string(float fieldnum, entity ent) getentityfieldstring = #499; (DP_QC_ENTITYDATA)
VM_putentityfieldstring,        // #500 float(float fieldnum, entity ent, string s) putentityfieldstring = #500; (DP_QC_ENTITYDATA)
VM_SV_WritePicture,             // #501
NULL,                           // #502
VM_whichpack,                   // #503 string(string) whichpack = #503;
NULL,                           // #504
NULL,                           // #505
NULL,                           // #506
NULL,                           // #507
NULL,                           // #508
NULL,                           // #509
VM_uri_escape,                  // #510 string(string in) uri_escape = #510;
VM_uri_unescape,                // #511 string(string in) uri_unescape = #511;
VM_etof,                    // #512 float(entity ent) num_for_edict = #512 (DP_QC_NUM_FOR_EDICT)
VM_uri_get,                     // #513 float(string uri, float id, [string post_contenttype, string post_delim, [float buf]]) uri_get = #513; (DP_QC_URI_GET, DP_QC_URI_POST)
VM_tokenize_console,                    // #514 float(string str) tokenize_console = #514; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_start_index,                    // #515 float(float idx) argv_start_index = #515; (DP_QC_TOKENIZE_CONSOLE)
VM_argv_end_index,                      // #516 float(float idx) argv_end_index = #516; (DP_QC_TOKENIZE_CONSOLE)
VM_buf_cvarlist,                        // #517 void(float buf, string prefix, string antiprefix) buf_cvarlist = #517; (DP_QC_STRINGBUFFERS_CVARLIST)
VM_cvar_description,                    // #518 float(string name) cvar_description = #518; (DP_QC_CVAR_DESCRIPTION)
VM_gettime,                     // #519 float(float timer) gettime = #519; (DP_QC_GETTIME)
NULL,                           // #520
NULL,                           // #521
NULL,                           // #522
NULL,                           // #523
NULL,                           // #524
NULL,                           // #525
NULL,                           // #526
NULL,                           // #527
NULL,                           // #528
VM_loadfromdata,                // #529
VM_loadfromfile,                // #530
VM_SV_setpause,                 // #531 void(float pause) setpause = #531;
VM_log,                         // #532
VM_getsoundtime,                // #533 float(entity e, float channel) getsoundtime = #533; (DP_SND_GETSOUNDTIME)
VM_soundlength,                 // #534 float(string sample) soundlength = #534; (DP_SND_GETSOUNDTIME)
VM_buf_loadfile,                // #535 float(string filename, float bufhandle) buf_loadfile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_buf_writefile,               // #536 float(float filehandle, float bufhandle, float startpos, float numstrings) buf_writefile (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_bufstr_find,                 // #537 float(float bufhandle, string match, float matchrule, float startpos) bufstr_find (DP_QC_STRINGBUFFERS_EXT_WIP)
VM_matchpattern,                // #538 float(string s, string pattern, float matchrule) matchpattern (DP_QC_STRINGBUFFERS_EXT_WIP)
NULL,                           // #539
VM_physics_enable,              // #540 void(entity e, float physics_enabled) physics_enable = #540; (DP_PHYSICS_ODE)
VM_physics_addforce,            // #541 void(entity e, vector force, vector relative_ofs) physics_addforce = #541; (DP_PHYSICS_ODE)
VM_physics_addtorque,           // #542 void(entity e, vector torque) physics_addtorque = #542; (DP_PHYSICS_ODE)
NULL,                           // #543
NULL,                           // #544
NULL,                           // #545
NULL,                           // #546
NULL,                           // #547
NULL,                           // #548
NULL,                           // #549
NULL,                           // #550
NULL,                           // #551
NULL,                           // #552
NULL,                           // #553
NULL,                           // #554
NULL,                           // #555
NULL,                           // #556
NULL,                           // #557
NULL,                           // #558
NULL,                           // #559
NULL,                           // #560
NULL,                           // #561
NULL,                           // #562
NULL,                           // #563
NULL,                           // #564
NULL,                           // #565
VM_SV_findbox,                  // #566 entity(vector mins, vector maxs) findbox = #566; (DP_QC_FINDBOX)
VM_nudgeoutofsolid,             // #567 float(entity ent) nudgeoutofsolid = #567; (DP_QC_NUDGEOUTOFSOLID)
NULL,                           // #568
NULL,                           // #569
NULL,                           // #570
NULL,                           // #571
NULL,                           // #572
NULL,                           // #573
NULL,                           // #574
NULL,                           // #575
NULL,                           // #576
NULL,                           // #577
NULL,                           // #578
NULL,                           // #579
NULL,                           // #580
NULL,                           // #581
NULL,                           // #582
NULL,                           // #583
NULL,                           // #584
NULL,                           // #585
NULL,                           // #586
NULL,                           // #587
NULL,                           // #588
NULL,                           // #589
NULL,                           // #590
NULL,                           // #591
NULL,                           // #592
NULL,                           // #593
NULL,                           // #594
NULL,                           // #595
NULL,                           // #596
NULL,                           // #597
NULL,                           // #598
NULL,                           // #599
NULL,                           // #600
NULL,                           // #601
NULL,                           // #602
NULL,                           // #603
NULL,                           // #604
VM_callfunction,                // #605
VM_writetofile,                 // #606
VM_isfunction,                  // #607
NULL,                           // #608
NULL,                           // #609
NULL,                           // #610
NULL,                           // #611
NULL,                           // #612
VM_parseentitydata,             // #613
NULL,                           // #614
NULL,                           // #615
NULL,                           // #616
NULL,                           // #617
NULL,                           // #618
NULL,                           // #619
NULL,                           // #620
NULL,                           // #621
NULL,                           // #622
NULL,                           // #623
VM_SV_getextresponse,           // #624 string getextresponse(void)
NULL,                           // #625
NULL,                           // #626
VM_sprintf,                     // #627 string sprintf(string format, ...)
VM_getsurfacenumtriangles,      // #628 float(entity e, float s) getsurfacenumpoints (DP_QC_GETSURFACETRIANGLE)
VM_getsurfacetriangle,          // #629 vector(entity e, float s, float n) getsurfacepoint (DP_QC_GETSURFACETRIANGLE)
NULL,                           // #630
NULL,                           // #631
NULL,                           // #632
NULL,                           // #633
NULL,                           // #634
NULL,                           // #635
NULL,                           // #636
NULL,                           // #637
NULL,                           // #638
VM_digest_hex,                      // #639
NULL,                           // #640
NULL,                           // #641
VM_coverage,                        // #642
NULL,                           // #643
};
Referenced by SV_VM_Setup().
vm_sv_extensions
const char* vm_sv_extensions[] extern
Definition at line 11 of file svvm_cmds.c.
{
"BX_WAL_SUPPORT",
"DP_BUTTONCHAT",
"DP_BUTTONUSE",
"DP_CL_LOADSKY",
"DP_CON_ALIASPARAMETERS",
"DP_CON_BESTWEAPON",
"DP_CON_EXPANDCVAR",
"DP_CON_SET",
"DP_CON_SETA",
"DP_CON_STARTMAP",
"DP_COVERAGE",
"DP_CRYPTO",
"DP_CSQC_BINDMAPS",
"DP_CSQC_ENTITYWORLDOBJECT",
"DP_CSQC_ENTITYMODELLIGHT",
"DP_CSQC_ENTITYTRANSPARENTSORTING_OFFSET",
"DP_CSQC_MAINVIEW",
"DP_CSQC_MINFPS_QUALITY",
"DP_CSQC_MULTIFRAME_INTERPOLATION",
"DP_CSQC_BOXPARTICLES",
"DP_CSQC_SPAWNPARTICLE",
"DP_CSQC_QUERYRENDERENTITY",
"DP_CSQC_ROTATEMOVES",
"DP_CSQC_SETPAUSE",
"DP_CSQC_V_CALCREFDEF_WIP1",
"DP_CSQC_V_CALCREFDEF_WIP2",
"DP_EF_ADDITIVE",
"DP_EF_BLUE",
"DP_EF_DOUBLESIDED",
"DP_EF_DYNAMICMODELLIGHT",
"DP_EF_FLAME",
"DP_EF_FULLBRIGHT",
"DP_EF_NODEPTHTEST",
"DP_EF_NODRAW",
"DP_EF_NOGUNBOB",
"DP_EF_NOSELFSHADOW",
"DP_EF_NOSHADOW",
"DP_EF_RED",
"DP_EF_RESTARTANIM_BIT",
"DP_EF_STARDUST",
"DP_EF_TELEPORT_BIT",
"DP_ENT_ALPHA",
"DP_ENT_COLORMOD",
"DP_ENT_CUSTOMCOLORMAP",
"DP_ENT_EXTERIORMODELTOCLIENT",
"DP_ENT_GLOW",
"DP_ENT_GLOWMOD",
"DP_ENT_LOWPRECISION",
"DP_ENT_SCALE",
"DP_ENT_TRAILEFFECTNUM",
"DP_ENT_VIEWMODEL",
"DP_GFX_EXTERNALTEXTURES",
"DP_GFX_EXTERNALTEXTURES_PERMAP",
"DP_GFX_FOG",
"DP_GFX_MODEL_INTERPOLATION",
"DP_GFX_QUAKE3MODELTAGS",
"DP_GFX_SKINFILES",
"DP_GFX_SKYBOX",
"DP_GFX_FONTS",
"DP_GFX_FONTS_FREETYPE",
"DP_UTF8",
"DP_FONT_VARIABLEWIDTH",
"DP_HALFLIFE_MAP",
"DP_HALFLIFE_MAP_CVAR",
"DP_HALFLIFE_SPRITE",
"DP_INPUTBUTTONS",
"DP_LIGHTSTYLE_STATICVALUE",
"DP_LITSPRITES",
"DP_LITSUPPORT",
"DP_MONSTERWALK",
"DP_MOVETYPEBOUNCEMISSILE",
"DP_MOVETYPEFLYWORLDONLY",
"DP_MOVETYPEFOLLOW",
"DP_NULL_MODEL",
"DP_QC_ASINACOSATANATAN2TAN",
"DP_QC_AUTOCVARS",
"DP_QC_CHANGEPITCH",
"DP_QC_CMD",
"DP_QC_COPYENTITY",
"DP_QC_CRC16",
"DP_QC_CVAR_DEFSTRING",
"DP_QC_CVAR_DESCRIPTION",
"DP_QC_CVAR_STRING",
"DP_QC_CVAR_TYPE",
"DP_QC_DIGEST",
"DP_QC_DIGEST_SHA256",
"DP_QC_EDICT_NUM",
"DP_QC_ENTITYDATA",
"DP_QC_ENTITYSTRING",
"DP_QC_ETOS",
"DP_QC_EXTRESPONSEPACKET",
"DP_QC_FINDBOX",
"DP_QC_FINDCHAIN",
"DP_QC_FINDCHAINFLAGS",
"DP_QC_FINDCHAINFLOAT",
"DP_QC_FINDCHAIN_TOFIELD",
"DP_QC_FINDFLAGS",
"DP_QC_FINDFLOAT",
"DP_QC_FS_SEARCH",
"DP_QC_FS_SEARCH_PACKFILE",
"DP_QC_GETLIGHT",
"DP_QC_GETSURFACE",
"DP_QC_GETSURFACETRIANGLE",
"DP_QC_GETSURFACEPOINTATTRIBUTE",
"DP_QC_GETTAGINFO",
"DP_QC_GETTAGINFO_BONEPROPERTIES",
"DP_QC_GETTIME",
"DP_QC_GETTIME_CDTRACK",
"DP_QC_I18N",
"DP_QC_LOG",
"DP_QC_MINMAXBOUND",
"DP_QC_MULTIPLETEMPSTRINGS",
"DP_QC_NUDGEOUTOFSOLID",
"DP_QC_NUM_FOR_EDICT",
"DP_QC_RANDOMVEC",
"DP_QC_SINCOSSQRTPOW",
"DP_QC_SPRINTF",
"DP_QC_STRFTIME",
"DP_QC_STRINGBUFFERS",
"DP_QC_STRINGBUFFERS_CVARLIST",
"DP_QC_STRINGBUFFERS_EXT_WIP",
"DP_QC_STRINGCOLORFUNCTIONS",
"DP_QC_STRING_CASE_FUNCTIONS",
"DP_QC_STRREPLACE",
"DP_QC_TOKENIZEBYSEPARATOR",
"DP_QC_TOKENIZE_CONSOLE",
"DP_QC_TRACEBOX",
"DP_QC_TRACETOSS",
"DP_QC_TRACE_MOVETYPE_HITMODEL",
"DP_QC_TRACE_MOVETYPE_WORLDONLY",
"DP_QC_UNLIMITEDTEMPSTRINGS",
"DP_QC_URI_ESCAPE",
"DP_QC_URI_GET",
"DP_QC_URI_POST",
"DP_QC_VECTOANGLES_WITH_ROLL",
"DP_QC_VECTORVECTORS",
"DP_QC_WHICHPACK",
"DP_QUAKE2_MODEL",
"DP_QUAKE2_SPRITE",
"DP_QUAKE3_MAP",
"DP_QUAKE3_MODEL",
"DP_REGISTERCVAR",
"DP_SKELETONOBJECTS",
"DP_SND_DIRECTIONLESSATTNNONE",
"DP_SND_FAKETRACKS",
"DP_SND_SOUND7_WIP1",
"DP_SND_SOUND7_WIP2",
"DP_SND_OGGVORBIS",
"DP_SND_SETPARAMS",
"DP_SND_STEREOWAV",
"DP_SND_GETSOUNDTIME",
"DP_VIDEO_DPV",
"DP_VIDEO_SUBTITLES",
"DP_SOLIDCORPSE",
"DP_SPRITE32",
"DP_SV_BOTCLIENT",
"DP_SV_BOUNCEFACTOR",
"DP_SV_CLIENTCAMERA",
"DP_SV_CLIENTCOLORS",
"DP_SV_CLIENTNAME",
"DP_SV_CMD",
"DP_SV_CUSTOMIZEENTITYFORCLIENT",
"DP_SV_DISABLECLIENTPREDICTION",
"DP_SV_DISCARDABLEDEMO",
"DP_SV_DRAWONLYTOCLIENT",
"DP_SV_DROPCLIENT",
"DP_SV_EFFECT",
"DP_SV_ENTITYCONTENTSTRANSITION",
"DP_SV_MODELFLAGS_AS_EFFECTS",
"DP_SV_MOVETYPESTEP_LANDEVENT",
"DP_SV_NETADDRESS",
"DP_SV_NODRAWTOCLIENT",
"DP_SV_ONENTITYNOSPAWNFUNCTION",
"DP_SV_ONENTITYPREPOSTSPAWNFUNCTION",
"DP_SV_PING",
"DP_SV_PING_PACKETLOSS",
"DP_SV_PLAYERPHYSICS",
"DP_PHYSICS_ODE",
"DP_SV_POINTPARTICLES",
"DP_SV_POINTSOUND",
"DP_SV_PRECACHEANYTIME",
"DP_SV_PRINT",
"DP_SV_PUNCHVECTOR",
"DP_SV_QCSTATUS",
"DP_SV_ROTATINGBMODEL",
"DP_SV_SETCOLOR",
"DP_SV_SHUTDOWN",
"DP_SV_SLOWMO",
"DP_SV_SPAWNFUNC_PREFIX",
"DP_SV_WRITEPICTURE",
"DP_SV_WRITEUNTERMINATEDSTRING",
"DP_TE_BLOOD",
"DP_TE_BLOODSHOWER",
"DP_TE_CUSTOMFLASH",
"DP_TE_EXPLOSIONRGB",
"DP_TE_FLAMEJET",
"DP_TE_PARTICLECUBE",
"DP_TE_PARTICLERAIN",
"DP_TE_PARTICLESNOW",
"DP_TE_PLASMABURN",
"DP_TE_QUADEFFECTS1",
"DP_TE_SMALLFLASH",
"DP_TE_SPARK",
"DP_TE_STANDARDEFFECTBUILTINS",
"DP_TRACE_HITCONTENTSMASK_SURFACEINFO"
"DP_USERMOVETYPES",
"DP_VIEWZOOM",
"EXT_BITSHIFT",
"FRIK_FILE",
"FTE_CSQC_SKELETONOBJECTS",
"FTE_QC_CHECKPVS",
"FTE_STRINGS",
"KRIMZON_SV_PARSECLIENTCOMMAND",
"NEH_CMD_PLAY2",
"NEH_RESTOREGAME",
"NEXUIZ_PLAYERMODEL",
"NXQ_GFX_LETTERBOX",
"PRYDON_CLIENTCURSOR",
"TENEBRAE_GFX_DLIGHTS",
"TW_SV_STEPCONTROL",
"ZQ_PAUSE",
"DP_RM_CLIPGROUP",
NULL
//"EXT_CSQC" // not ready yet
};
Referenced by CL_VM_Init(), PRVM_Init(), and SV_VM_Setup().
vm_sv_numbuiltins
const int vm_sv_numbuiltins extern
Definition at line 3917 of file svvm_cmds.c.
Referenced by SV_VM_Setup().