DarkPlaces: protocol.h File Reference
protocol.h File Reference
#include <stddef.h>
#include "qtypes.h"
#include "qdefs.h"
#include "qstats.h"
Data Structures
struct usercmd_t
struct framegroupblend_t
struct skeleton_t
struct entity_state_t
struct entity_frame_t
struct entity_frameinfo_t
struct entityframe_database_t
struct entity_database4_commit_t
struct entityframe4_database_t
struct entityframe5_changestate_t
struct entityframe5_packetlog_t
struct entityframe5_database_t
struct entityframeqw_snapshot_t
struct entityframeqw_database_t
Macros
#define ENTITYSIZEPROFILING_START(msg, num, flags) int entityprofiling_startsize = msg->cursize
#define ENTITYSIZEPROFILING_END(msg, num, flags)
#define SCOPE_WANTREMOVE 1
#define SCOPE_WANTUPDATE 2
#define SCOPE_WANTSEND (SCOPE_WANTREMOVE | SCOPE_WANTUPDATE)
#define SCOPE_EXISTED_ONCE 4
#define SCOPE_ASSUMED_EXISTING 8
#define MF_ROCKET 1
#define MF_GRENADE 2
#define MF_GIB 4
#define MF_ROTATE 8
#define MF_TRACER 16
#define MF_ZOMGIB 32
#define MF_TRACER2 64
#define MF_TRACER3 128
#define EF_BRIGHTFIELD 1
#define EF_MUZZLEFLASH 2
#define EF_BRIGHTLIGHT 4
#define EF_DIMLIGHT 8
#define EF_NODRAW 16
#define EF_ADDITIVE 32
#define EF_BLUE 64
#define EF_RED 128
#define EF_NOGUNBOB 256
#define EF_FULLBRIGHT 512
#define EF_FLAME 1024
#define EF_STARDUST 2048
#define EF_NOSHADOW 4096
#define EF_NODEPTHTEST 8192
#define EF_SELECTABLE 16384
#define EF_DOUBLESIDED 32768
#define EF_NOSELFSHADOW 65536
#define EF_DYNAMICMODELLIGHT 131072
#define EF_UNUSED18 262144
#define EF_UNUSED19 524288
#define EF_RESTARTANIM_BIT 1048576
#define EF_TELEPORT_BIT 2097152
#define EF_LOWPRECISION 4194304
#define EF_NOMODELFLAGS 8388608
#define EF_ROCKET 16777216
#define EF_GRENADE 33554432
#define EF_GIB 67108864
#define EF_ROTATE 134217728
#define EF_TRACER 268435456
#define EF_ZOMGIB 536870912
#define EF_TRACER2 1073741824
#define EF_TRACER3 0x80000000
#define INTEF_FLAG1QW 1
#define INTEF_FLAG2QW 2
#define PFLAGS_NOSHADOW 1
#define PFLAGS_CORONA 2
#define PFLAGS_FULLDYNAMIC 128
#define U_MOREBITS (1u<<0)
#define U_ORIGIN1 (1u<<1)
#define U_ORIGIN2 (1u<<2)
#define U_ORIGIN3 (1u<<3)
#define U_ANGLE2 (1u<<4)
#define U_STEP (1u<<5)
#define U_FRAME (1u<<6)
#define U_SIGNAL (1u<<7)
#define U_ANGLE1 (1u<<8)
#define U_ANGLE3 (1u<<9)
#define U_MODEL (1u<<10)
#define U_COLORMAP (1u<<11)
#define U_SKIN (1u<<12)
#define U_EFFECTS (1u<<13)
#define U_LONGENTITY (1u<<14)
#define U_EXTEND1 (1u<<15)
#define U_DELTA (1u<<16)
no data, while this is set the entity is delta compressed (uses previous frame as a baseline, meaning only things that have changed from the previous frame are sent, except for the forced full update every half second)
#define U_ALPHA (1u<<17)
1 byte, 0.0-1.0 maps to 0-255, not sent if exactly 1, and the entity is not sent if <=0 unless it has effects (model effects are checked as well)
#define U_SCALE (1u<<18)
1 byte, scale / 16 positive, not sent if 1.0
#define U_EFFECTS2 (1u<<19)
1 byte, this is .effects & 0xFF00 (second byte)
#define U_GLOWSIZE (1u<<20)
1 byte, encoding is float/4.0, unsigned, not sent if 0
#define U_GLOWCOLOR (1u<<21)
1 byte, palette index, default is 254 (white), this IS used for darklight (allowing colored darklight), however the particles from a darklight are always black, not sent if default value (even if glowsize or glowtrail is set)
#define U_COLORMOD (1u<<22)
1 byte, 3 bit red, 3 bit green, 2 bit blue, this lets you tint an object artifically, so you could make a red rocket, or a blue fiend...
#define U_EXTEND2 (1u<<23)
another byte to follow
#define U_GLOWTRAIL (1u<<24)
leaves a trail of particles (of color .glowcolor, or black if it is a negative glowsize)
#define U_VIEWMODEL (1u<<25)
attachs the model to the view (origin and angles become relative to it), only shown to owner, a more powerful alternative to .weaponmodel and such
#define U_FRAME2 (1u<<26)
1 byte, this is .frame & 0xFF00 (second byte)
#define U_MODEL2 (1u<<27)
1 byte, this is .modelindex & 0xFF00 (second byte)
#define U_EXTERIORMODEL (1u<<28)
causes this model to not be drawn when using a first person view (third person will draw it, first person will not)
#define U_UNUSED29 (1u<<29)
future expansion
#define U_UNUSED30 (1u<<30)
future expansion
#define U_EXTEND3 (1u<<31)
another byte to follow, future expansion
#define SU_VIEWHEIGHT (1u<<0)
#define SU_IDEALPITCH (1u<<1)
#define SU_PUNCH1 (1u<<2)
#define SU_PUNCH2 (1u<<3)
#define SU_PUNCH3 (1u<<4)
#define SU_VELOCITY1 (1u<<5)
#define SU_VELOCITY2 (1u<<6)
#define SU_VELOCITY3 (1u<<7)
#define SU_ITEMS (1u<<9)
#define SU_ONGROUND (1u<<10)
no data follows, the bit is it
#define SU_INWATER (1u<<11)
no data follows, the bit is it
#define SU_WEAPONFRAME (1u<<12)
#define SU_ARMOR (1u<<13)
#define SU_WEAPON (1u<<14)
#define SU_EXTEND1 (1u<<15)
#define SU_PUNCHVEC1 (1u<<16)
#define SU_PUNCHVEC2 (1u<<17)
#define SU_PUNCHVEC3 (1u<<18)
#define SU_VIEWZOOM (1u<<19)
byte factor (0 = 0.0 (not valid), 255 = 1.0)
#define SU_UNUSED20 (1u<<20)
#define SU_UNUSED21 (1u<<21)
#define SU_UNUSED22 (1u<<22)
#define SU_EXTEND2 (1u<<23)
another byte to follow, future expansion
#define SU_UNUSED24 (1u<<24)
#define SU_UNUSED25 (1u<<25)
#define SU_UNUSED26 (1u<<26)
#define SU_UNUSED27 (1u<<27)
#define SU_UNUSED28 (1u<<28)
#define SU_UNUSED29 (1u<<29)
#define SU_UNUSED30 (1u<<30)
#define SU_EXTEND3 (1u<<31)
another byte to follow, future expansion
#define SND_VOLUME (1<<0)
#define SND_ATTENUATION (1<<1)
#define SND_LOOPING (1<<2)
#define SND_LARGEENTITY (1<<3)
#define SND_LARGESOUND (1<<4)
#define SND_SPEEDUSHORT4000 (1<<5)
#define DEFAULT_VIEWHEIGHT 22
#define GAME_COOP 0
#define GAME_DEATHMATCH 1
#define svc_bad 0
#define svc_nop 1
#define svc_disconnect 2
#define svc_updatestat 3
#define svc_version 4
#define svc_setview 5
#define svc_sound 6
#define svc_time 7
#define svc_print 8
#define svc_stufftext 9
#define svc_setangle 10
#define svc_serverinfo 11
#define svc_lightstyle 12
#define svc_updatename 13
#define svc_updatefrags 14
#define svc_clientdata 15
#define svc_stopsound 16
#define svc_updatecolors 17
#define svc_particle 18
#define svc_damage 19
#define svc_spawnstatic 20
#define svc_spawnbaseline 22
#define svc_temp_entity 23
#define svc_setpause 24
#define svc_signonnum 25
#define svc_centerprint 26
#define svc_killedmonster 27
#define svc_foundsecret 28
#define svc_spawnstaticsound 29
#define svc_intermission 30
#define svc_finale 31
#define svc_cdtrack 32
#define svc_sellscreen 33
#define svc_cutscene 34
#define svc_showlmp 35
#define svc_hidelmp 36
#define svc_skybox 37
#define svc_downloaddata 50
#define svc_updatestatubyte 51
#define svc_effect 52
#define svc_effect2 53
#define svc_sound2 54
#define svc_precache 54
#define svc_spawnbaseline2 55
#define svc_spawnstatic2 56
#define svc_entities 57
#define svc_csqcentities 58
#define svc_spawnstaticsound2 59
#define svc_trailparticles 60
#define svc_pointparticles 61
#define svc_pointparticles1 62
#define clc_bad 0
#define clc_nop 1
#define clc_disconnect 2
#define clc_move 3
#define clc_stringcmd 4
#define clc_ackframe 50
#define clc_ackdownloaddata 51
#define clc_unusedlh2 52
#define clc_unusedlh3 53
#define clc_unusedlh4 54
#define clc_unusedlh5 55
#define clc_unusedlh6 56
#define clc_unusedlh7 57
#define clc_unusedlh8 58
#define clc_unusedlh9 59
#define TE_SPIKE 0
#define TE_SUPERSPIKE 1
#define TE_GUNSHOT 2
#define TE_EXPLOSION 3
#define TE_TAREXPLOSION 4
#define TE_LIGHTNING1 5
#define TE_LIGHTNING2 6
#define TE_WIZSPIKE 7
#define TE_KNIGHTSPIKE 8
#define TE_LIGHTNING3 9
#define TE_LAVASPLASH 10
#define TE_TELEPORT 11
#define TE_EXPLOSION2 12
#define TE_BEAM 13
#define TE_EXPLOSION3 16
#define TE_LIGHTNING4NEH 17
#define TE_BLOOD 50
#define TE_SPARK 51
#define TE_BLOODSHOWER 52
#define TE_EXPLOSIONRGB 53
#define TE_PARTICLECUBE 54
#define TE_PARTICLERAIN 55
#define TE_PARTICLESNOW 56
#define TE_GUNSHOTQUAD 57
#define TE_SPIKEQUAD 58
#define TE_SUPERSPIKEQUAD 59
#define TE_EXPLOSIONQUAD 70
#define TE_UNUSED1 71
#define TE_SMALLFLASH 72
#define TE_CUSTOMFLASH 73
#define TE_FLAMEJET 74
#define TE_PLASMABURN 75
#define TE_TEI_G3 76
#define TE_TEI_SMOKE 77
#define TE_TEI_BIGEXPLOSION 78
#define TE_TEI_PLASMAHIT 79
#define RENDER_STEP 1
#define RENDER_GLOWTRAIL 2
#define RENDER_VIEWMODEL 4
#define RENDER_EXTERIORMODEL 8
#define RENDER_LOWPRECISION 16
#define RENDER_COLORMAPPED 32
#define RENDER_WORLDOBJECT 64
#define RENDER_COMPLEXANIMATION 128
#define RENDER_SHADOW 65536
#define RENDER_LIGHT 131072
#define RENDER_NOSELFSHADOW 262144
#define RENDER_NODEPTHTEST 1048576
#define RENDER_ADDITIVE 2097152
#define RENDER_DOUBLESIDED 4194304
#define RENDER_CUSTOMIZEDMODELLIGHT 4096
#define RENDER_DYNAMICMODELLIGHT 8388608
#define MAX_FRAMEGROUPBLENDS 4
#define MAX_ENTITY_HISTORY 64
#define MAX_ENTITY_DATABASE (MAX_EDICTS * 2)
#define E_ORIGIN1 (1u<<0)
#define E_ORIGIN2 (1u<<1)
#define E_ORIGIN3 (1u<<2)
#define E_ANGLE1 (1u<<3)
#define E_ANGLE2 (1u<<4)
#define E_ANGLE3 (1u<<5)
#define E_MODEL1 (1u<<6)
#define E_EXTEND1 (1u<<7)
#define E_FRAME1 (1u<<8)
#define E_EFFECTS1 (1u<<9)
#define E_ALPHA (1u<<10)
#define E_SCALE (1u<<11)
#define E_COLORMAP (1u<<12)
#define E_SKIN (1u<<13)
#define E_FLAGS (1u<<14)
#define E_EXTEND2 (1u<<15)
#define E_FRAME2 (1u<<16)
#define E_MODEL2 (1u<<17)
#define E_EFFECTS2 (1u<<18)
#define E_GLOWSIZE (1u<<19)
#define E_GLOWCOLOR (1u<<20)
#define E_LIGHT (1u<<21)
#define E_LIGHTPFLAGS (1u<<22)
#define E_EXTEND3 (1u<<23)
#define E_SOUND1 (1u<<24)
#define E_SOUNDVOL (1u<<25)
#define E_SOUNDATTEN (1u<<26)
#define E_TAGATTACHMENT (1u<<27)
#define E_LIGHTSTYLE (1u<<28)
#define E_UNUSED6 (1u<<29)
#define E_UNUSED7 (1u<<30)
#define E_EXTEND4 (1u<<31)
#define E5_FULLUPDATE (1u<<0)
reset all entity fields (typically used if status changed)
#define E5_ORIGIN (1u<<1)
E5_ORIGIN32=0: short[3] = s->origin[0] * 8, s->origin[1] * 8, s->origin[2] * 8 E5_ORIGIN32=1: float[3] = s->origin[0], s->origin[1], s->origin[2].
#define E5_ANGLES (1u<<2)
E5_ANGLES16=0: byte[3] = s->angle[0] * 256 / 360, s->angle[1] * 256 / 360, s->angle[2] * 256 / 360 E5_ANGLES16=1: short[3] = s->angle[0] * 65536 / 360, s->angle[1] * 65536 / 360, s->angle[2] * 65536 / 360.
#define E5_MODEL (1u<<3)
E5_MODEL16=0: byte = s->modelindex E5_MODEL16=1: short = s->modelindex.
#define E5_FRAME (1u<<4)
E5_FRAME16=0: byte = s->frame E5_FRAME16=1: short = s->frame.
#define E5_SKIN (1u<<5)
byte = s->skin
#define E5_EFFECTS (1u<<6)
E5_EFFECTS16=0 && E5_EFFECTS32=0: byte = s->effects E5_EFFECTS16=1 && E5_EFFECTS32=0: short = s->effects E5_EFFECTS16=0 && E5_EFFECTS32=1: int = s->effects E5_EFFECTS16=1 && E5_EFFECTS32=1: int = s->effects.
#define E5_EXTEND1 (1u<<7)
bits >= (1<<8)
#define E5_FLAGS (1u<<8)
byte = s->renderflags
#define E5_ALPHA (1u<<9)
byte = bound(0, s->alpha * 255, 255)
#define E5_SCALE (1u<<10)
byte = bound(0, s->scale * 16, 255)
#define E5_ORIGIN32 (1u<<11)
flag
#define E5_ANGLES16 (1u<<12)
flag
#define E5_MODEL16 (1u<<13)
flag
#define E5_COLORMAP (1u<<14)
byte = s->colormap
#define E5_EXTEND2 (1u<<15)
bits >= (1<<16)
#define E5_ATTACHMENT (1u<<16)
short = s->tagentity byte = s->tagindex
#define E5_LIGHT (1u<<17)
short[4] = s->light[0], s->light[1], s->light[2], s->light[3] byte = s->lightstyle byte = s->lightpflags
#define E5_GLOW (1u<<18)
byte = s->glowsize byte = s->glowcolor
#define E5_EFFECTS16 (1u<<19)
short = s->effects
#define E5_EFFECTS32 (1u<<20)
int = s->effects
#define E5_FRAME16 (1u<<21)
flag
#define E5_COLORMOD (1u<<22)
byte[3] = s->colormod[0], s->colormod[1], s->colormod[2]
#define E5_EXTEND3 (1u<<23)
bits >= (1<<24)
#define E5_GLOWMOD (1u<<24)
byte[3] = s->glowmod[0], s->glowmod[1], s->glowmod[2]
#define E5_COMPLEXANIMATION (1u<<25)
byte type=0 short frames[1] short times[1] byte type=1 short frames[2] short times[2] byte lerps[2] byte type=2 short frames[3] short times[3] byte lerps[3] byte type=3 short frames[4] short times[4] byte lerps[4] byte type=4 short modelindex byte numbones {short pose7s[7]} see also RENDER_COMPLEXANIMATION
#define E5_TRAILEFFECTNUM (1u<<26)
ushort traileffectnum
#define E5_UNUSED27 (1u<<27)
unused
#define E5_UNUSED28 (1u<<28)
unused
#define E5_UNUSED29 (1u<<29)
unused
#define E5_UNUSED30 (1u<<30)
unused
#define E5_EXTEND4 (1u<<31)
bits2 > 0
#define ENTITYFRAME5_MAXPACKETLOGS 64
#define ENTITYFRAME5_MAXSTATES 1024
#define ENTITYFRAME5_PRIORITYLEVELS 32
#define qw_svc_bad 0
#define qw_svc_nop 1
#define qw_svc_disconnect 2
#define qw_svc_updatestat 3
#define qw_svc_setview 5
#define qw_svc_sound 6
#define qw_svc_print 8
#define qw_svc_stufftext 9
#define qw_svc_setangle 10
#define qw_svc_serverdata 11
#define qw_svc_lightstyle 12
#define qw_svc_updatefrags 14
#define qw_svc_stopsound 16
#define qw_svc_damage 19
#define qw_svc_spawnstatic 20
#define qw_svc_spawnbaseline 22
#define qw_svc_temp_entity 23
#define qw_svc_setpause 24
#define qw_svc_centerprint 26
#define qw_svc_killedmonster 27
#define qw_svc_foundsecret 28
#define qw_svc_spawnstaticsound 29
#define qw_svc_intermission 30
#define qw_svc_finale 31
#define qw_svc_cdtrack 32
#define qw_svc_sellscreen 33
#define qw_svc_smallkick 34
#define qw_svc_bigkick 35
#define qw_svc_updateping 36
#define qw_svc_updateentertime 37
#define qw_svc_updatestatlong 38
#define qw_svc_muzzleflash 39
#define qw_svc_updateuserinfo 40
#define qw_svc_download 41
#define qw_svc_playerinfo 42
#define qw_svc_nails 43
#define qw_svc_chokecount 44
#define qw_svc_modellist 45
#define qw_svc_soundlist 46
#define qw_svc_packetentities 47
#define qw_svc_deltapacketentities 48
#define qw_svc_maxspeed 49
#define qw_svc_entgravity 50
#define qw_svc_setinfo 51
#define qw_svc_serverinfo 52
#define qw_svc_updatepl 53
#define qw_clc_bad 0
#define qw_clc_nop 1
#define qw_clc_move 3
#define qw_clc_stringcmd 4
#define qw_clc_delta 5
#define qw_clc_tmove 6
#define qw_clc_upload 7
#define QW_PF_MSEC (1<<0)
#define QW_PF_COMMAND (1<<1)
#define QW_PF_VELOCITY1 (1<<2)
#define QW_PF_VELOCITY2 (1<<3)
#define QW_PF_VELOCITY3 (1<<4)
#define QW_PF_MODEL (1<<5)
#define QW_PF_SKINNUM (1<<6)
#define QW_PF_EFFECTS (1<<7)
#define QW_PF_WEAPONFRAME (1<<8)
#define QW_PF_DEAD (1<<9)
#define QW_PF_GIB (1<<10)
#define QW_PF_NOGRAV (1<<11)
#define QW_CM_ANGLE1 (1<<0)
#define QW_CM_ANGLE3 (1<<1)
#define QW_CM_FORWARD (1<<2)
#define QW_CM_SIDE (1<<3)
#define QW_CM_UP (1<<4)
#define QW_CM_BUTTONS (1<<5)
#define QW_CM_IMPULSE (1<<6)
#define QW_CM_ANGLE2 (1<<7)
#define QW_U_ORIGIN1 (1<<9)
#define QW_U_ORIGIN2 (1<<10)
#define QW_U_ORIGIN3 (1<<11)
#define QW_U_ANGLE2 (1<<12)
#define QW_U_FRAME (1<<13)
#define QW_U_REMOVE (1<<14)
#define QW_U_MOREBITS (1<<15)
#define QW_U_ANGLE1 (1<<0)
#define QW_U_ANGLE3 (1<<1)
#define QW_U_MODEL (1<<2)
#define QW_U_COLORMAP (1<<3)
#define QW_U_SKIN (1<<4)
#define QW_U_EFFECTS (1<<5)
#define QW_U_SOLID (1<<6)
#define QW_TE_SPIKE 0
#define QW_TE_SUPERSPIKE 1
#define QW_TE_GUNSHOT 2
#define QW_TE_EXPLOSION 3
#define QW_TE_TAREXPLOSION 4
#define QW_TE_LIGHTNING1 5
#define QW_TE_LIGHTNING2 6
#define QW_TE_WIZSPIKE 7
#define QW_TE_KNIGHTSPIKE 8
#define QW_TE_LIGHTNING3 9
#define QW_TE_LAVASPLASH 10
#define QW_TE_TELEPORT 11
#define QW_TE_BLOOD 12
#define QW_TE_LIGHTNINGBLOOD 13
#define QW_EF_BRIGHTFIELD 1
#define QW_EF_MUZZLEFLASH 2
#define QW_EF_BRIGHTLIGHT 4
#define QW_EF_DIMLIGHT 8
#define QW_EF_FLAG1 16
#define QW_EF_FLAG2 32
#define QW_EF_BLUE 64
#define QW_EF_RED 128
#define QW_UPDATE_BACKUP 64
#define QW_UPDATE_MASK (QW_UPDATE_BACKUP - 1)
#define QW_MAX_PACKET_ENTITIES 64
#define QW_STAT_HEALTH 0
#define QW_STAT_WEAPON 2
#define QW_STAT_AMMO 3
#define QW_STAT_ARMOR 4
#define QW_STAT_SHELLS 6
#define QW_STAT_NAILS 7
#define QW_STAT_ROCKETS 8
#define QW_STAT_CELLS 9
#define QW_STAT_ACTIVEWEAPON 10
#define QW_STAT_TOTALSECRETS 11
#define QW_STAT_TOTALMONSTERS 12
#define QW_STAT_SECRETS 13
#define QW_STAT_MONSTERS 14
#define QW_STAT_ITEMS 15
Enumerations
enum entity_state_active_t { ACTIVE_NOT = 0 , ACTIVE_NETWORK = 1 , ACTIVE_SHARED = 2 }
Functions
enum protocolversion_e Protocol_EnumForName (const char *s)
const char * Protocol_NameForEnum (enum protocolversion_e p)
enum protocolversion_e Protocol_EnumForNumber (int n)
int Protocol_NumberForEnum (enum protocolversion_e p)
void Protocol_Names (char *buffer, size_t buffersize)
void EntityFrameQuake_ReadEntity (int bits)
void Protocol_UpdateClientStats (const int *stats)
void Protocol_WriteStatsReliable (void)
qbool EntityFrameQuake_WriteFrame (struct sizebuf_s *msg, int maxsize, int numstates, const entity_state_t **states)
void EntityFrameQuake_ISeeDeadEntities (void)
int EntityState_DeltaBits (const entity_state_t *o, const entity_state_t *n)
void EntityState_WriteExtendBits (struct sizebuf_s *msg, unsigned int bits)
void EntityState_WriteFields (const entity_state_t *ent, struct sizebuf_s *msg, unsigned int bits)
void EntityState_WriteUpdate (const entity_state_t *ent, struct sizebuf_s *msg, const entity_state_t *delta)
int EntityState_ReadExtendBits (void)
void EntityState_ReadFields (entity_state_t *e, unsigned int bits)
entityframe_database_t * EntityFrame_AllocDatabase (struct mempool_s *mempool)
void EntityFrame_FreeDatabase (entityframe_database_t *d)
void EntityFrame_ClearDatabase (entityframe_database_t *d)
void EntityFrame_AckFrame (entityframe_database_t *d, int frame)
void EntityFrame_Clear (entity_frame_t *f, vec3_t eye, int framenum)
void EntityFrame_FetchFrame (entityframe_database_t *d, int framenum, entity_frame_t *f)
void EntityFrame_AddFrame_Client (entityframe_database_t *d, vec3_t eye, int framenum, int numentities, const entity_state_t *entitydata)
void EntityFrame_AddFrame_Server (entityframe_database_t *d, vec3_t eye, int framenum, int numentities, const entity_state_t **entitydata)
qbool EntityFrame_WriteFrame (struct sizebuf_s *msg, int maxsize, entityframe_database_t *d, int numstates, const entity_state_t **states, int viewentnum)
void EntityFrame_CL_ReadFrame (void)
int EntityFrame_MostRecentlyRecievedFrameNum (entityframe_database_t *d)
entity_state_t * EntityFrame4_GetReferenceEntity (entityframe4_database_t *d, int number)
void EntityFrame4_AddCommitEntity (entityframe4_database_t *d, const entity_state_t *s)
entityframe4_database_t * EntityFrame4_AllocDatabase (struct mempool_s *pool)
void EntityFrame4_FreeDatabase (entityframe4_database_t *d)
void EntityFrame4_ResetDatabase (entityframe4_database_t *d)
int EntityFrame4_AckFrame (entityframe4_database_t *d, int framenum, int servermode)
qbool EntityFrame4_WriteFrame (struct sizebuf_s *msg, int maxsize, entityframe4_database_t *d, int numstates, const entity_state_t **states)
void EntityFrame4_CL_ReadFrame (void)
entityframe5_database_t * EntityFrame5_AllocDatabase (struct mempool_s *pool)
void EntityFrame5_FreeDatabase (entityframe5_database_t *d)
void EntityState5_WriteUpdate (int number, const entity_state_t *s, int changedbits, struct sizebuf_s *msg)
int EntityState5_DeltaBitsForState (entity_state_t *o, entity_state_t *n)
void EntityFrame5_CL_ReadFrame (void)
void EntityFrame5_LostFrame (entityframe5_database_t *d, int framenum)
void EntityFrame5_AckFrame (entityframe5_database_t *d, int framenum)
qbool EntityFrame5_WriteFrame (struct sizebuf_s *msg, int maxsize, entityframe5_database_t *d, int numstates, const entity_state_t **states, int viewentnum, unsigned int movesequence, qbool need_empty)
entityframeqw_database_t * EntityFrameQW_AllocDatabase (struct mempool_s *pool)
void EntityFrameQW_FreeDatabase (entityframeqw_database_t *d)
void EntityStateQW_ReadPlayerUpdate (void)
void EntityFrameQW_CL_ReadFrame (qbool delta)
void EntityFrameCSQC_LostFrame (struct client_s *client, int framenum)
qbool EntityFrameCSQC_WriteFrame (struct sizebuf_s *msg, int maxsize, int numnumbers, const unsigned short *numbers, int framenum)
Variables
entity_state_t defaultstate
struct cvar_s developer_networkentities
Macro Definition Documentation
clc_ackdownloaddata
#define clc_ackdownloaddata 51
Definition at line 296 of file protocol.h.
clc_ackframe
#define clc_ackframe 50
Definition at line 295 of file protocol.h.
clc_bad
#define clc_bad 0
Definition at line 288 of file protocol.h.
clc_disconnect
#define clc_disconnect 2
Definition at line 290 of file protocol.h.
clc_move
#define clc_move 3
Definition at line 291 of file protocol.h.
clc_nop
#define clc_nop 1
Definition at line 289 of file protocol.h.
clc_stringcmd
#define clc_stringcmd 4
Definition at line 292 of file protocol.h.
clc_unusedlh2
#define clc_unusedlh2 52
Definition at line 297 of file protocol.h.
clc_unusedlh3
#define clc_unusedlh3 53
Definition at line 298 of file protocol.h.
clc_unusedlh4
#define clc_unusedlh4 54
Definition at line 299 of file protocol.h.
clc_unusedlh5
#define clc_unusedlh5 55
Definition at line 300 of file protocol.h.
clc_unusedlh6
#define clc_unusedlh6 56
Definition at line 301 of file protocol.h.
clc_unusedlh7
#define clc_unusedlh7 57
Definition at line 302 of file protocol.h.
clc_unusedlh8
#define clc_unusedlh8 58
Definition at line 303 of file protocol.h.
clc_unusedlh9
#define clc_unusedlh9 59
Definition at line 304 of file protocol.h.
DEFAULT_VIEWHEIGHT
#define DEFAULT_VIEWHEIGHT 22
Definition at line 199 of file protocol.h.
E5_ALPHA
#define E5_ALPHA (1u<<9)
byte = bound(0, s->alpha * 255, 255)
Definition at line 769 of file protocol.h.
E5_ANGLES
#define E5_ANGLES (1u<<2)
E5_ANGLES16=0: byte[3] = s->angle[0] * 256 / 360, s->angle[1] * 256 / 360, s->angle[2] * 256 / 360 E5_ANGLES16=1: short[3] = s->angle[0] * 65536 / 360, s->angle[1] * 65536 / 360, s->angle[2] * 65536 / 360.
Definition at line 749 of file protocol.h.
E5_ANGLES16
#define E5_ANGLES16 (1u<<12)
flag
Definition at line 775 of file protocol.h.
E5_ATTACHMENT
#define E5_ATTACHMENT (1u<<16)
short = s->tagentity byte = s->tagindex
Definition at line 785 of file protocol.h.
E5_COLORMAP
#define E5_COLORMAP (1u<<14)
byte = s->colormap
Definition at line 779 of file protocol.h.
E5_COLORMOD
#define E5_COLORMOD (1u<<22)
byte[3] = s->colormod[0], s->colormod[1], s->colormod[2]
Definition at line 800 of file protocol.h.
E5_COMPLEXANIMATION
#define E5_COMPLEXANIMATION (1u<<25)
byte type=0 short frames[1] short times[1] byte type=1 short frames[2] short times[2] byte lerps[2] byte type=2 short frames[3] short times[3] byte lerps[3] byte type=3 short frames[4] short times[4] byte lerps[4] byte type=4 short modelindex byte numbones {short pose7s[7]} see also RENDER_COMPLEXANIMATION
Definition at line 812 of file protocol.h.
E5_EFFECTS
#define E5_EFFECTS (1u<<6)
E5_EFFECTS16=0 && E5_EFFECTS32=0: byte = s->effects E5_EFFECTS16=1 && E5_EFFECTS32=0: short = s->effects E5_EFFECTS16=0 && E5_EFFECTS32=1: int = s->effects E5_EFFECTS16=1 && E5_EFFECTS32=1: int = s->effects.
Definition at line 762 of file protocol.h.
E5_EFFECTS16
#define E5_EFFECTS16 (1u<<19)
short = s->effects
Definition at line 794 of file protocol.h.
E5_EFFECTS32
#define E5_EFFECTS32 (1u<<20)
int = s->effects
Definition at line 796 of file protocol.h.
E5_EXTEND1
#define E5_EXTEND1 (1u<<7)
bits >= (1<<8)
Definition at line 764 of file protocol.h.
E5_EXTEND2
#define E5_EXTEND2 (1u<<15)
bits >= (1<<16)
Definition at line 781 of file protocol.h.
E5_EXTEND3
#define E5_EXTEND3 (1u<<23)
bits >= (1<<24)
Definition at line 802 of file protocol.h.
E5_EXTEND4
#define E5_EXTEND4 (1u<<31)
bits2 > 0
Definition at line 824 of file protocol.h.
E5_FLAGS
#define E5_FLAGS (1u<<8)
byte = s->renderflags
Definition at line 767 of file protocol.h.
E5_FRAME
#define E5_FRAME (1u<<4)
E5_FRAME16=0: byte = s->frame E5_FRAME16=1: short = s->frame.
Definition at line 755 of file protocol.h.
E5_FRAME16
#define E5_FRAME16 (1u<<21)
flag
Definition at line 798 of file protocol.h.
E5_FULLUPDATE
#define E5_FULLUPDATE (1u<<0)
reset all entity fields (typically used if status changed)
Definition at line 743 of file protocol.h.
E5_GLOW
#define E5_GLOW (1u<<18)
byte = s->glowsize byte = s->glowcolor
Definition at line 792 of file protocol.h.
E5_GLOWMOD
#define E5_GLOWMOD (1u<<24)
byte[3] = s->glowmod[0], s->glowmod[1], s->glowmod[2]
Definition at line 805 of file protocol.h.
E5_LIGHT
#define E5_LIGHT (1u<<17)
short[4] = s->light[0], s->light[1], s->light[2], s->light[3] byte = s->lightstyle byte = s->lightpflags
Definition at line 789 of file protocol.h.
E5_MODEL
#define E5_MODEL (1u<<3)
E5_MODEL16=0: byte = s->modelindex E5_MODEL16=1: short = s->modelindex.
Definition at line 752 of file protocol.h.
E5_MODEL16
#define E5_MODEL16 (1u<<13)
flag
Definition at line 777 of file protocol.h.
E5_ORIGIN
#define E5_ORIGIN (1u<<1)
E5_ORIGIN32=0: short[3] = s->origin[0] * 8, s->origin[1] * 8, s->origin[2] * 8 E5_ORIGIN32=1: float[3] = s->origin[0], s->origin[1], s->origin[2].
Definition at line 746 of file protocol.h.
E5_ORIGIN32
#define E5_ORIGIN32 (1u<<11)
flag
Definition at line 773 of file protocol.h.
E5_SCALE
#define E5_SCALE (1u<<10)
byte = bound(0, s->scale * 16, 255)
Definition at line 771 of file protocol.h.
E5_SKIN
#define E5_SKIN (1u<<5)
byte = s->skin
Definition at line 757 of file protocol.h.
E5_TRAILEFFECTNUM
#define E5_TRAILEFFECTNUM (1u<<26)
ushort traileffectnum
Definition at line 814 of file protocol.h.
E5_UNUSED27
#define E5_UNUSED27 (1u<<27)
unused
Definition at line 816 of file protocol.h.
E5_UNUSED28
#define E5_UNUSED28 (1u<<28)
unused
Definition at line 818 of file protocol.h.
E5_UNUSED29
#define E5_UNUSED29 (1u<<29)
unused
Definition at line 820 of file protocol.h.
E5_UNUSED30
#define E5_UNUSED30 (1u<<30)
unused
Definition at line 822 of file protocol.h.
E_ALPHA
#define E_ALPHA (1u<<10)
Definition at line 626 of file protocol.h.
E_ANGLE1
#define E_ANGLE1 (1u<<3)
Definition at line 617 of file protocol.h.
E_ANGLE2
#define E_ANGLE2 (1u<<4)
Definition at line 618 of file protocol.h.
E_ANGLE3
#define E_ANGLE3 (1u<<5)
Definition at line 619 of file protocol.h.
E_COLORMAP
#define E_COLORMAP (1u<<12)
Definition at line 628 of file protocol.h.
E_EFFECTS1
#define E_EFFECTS1 (1u<<9)
Definition at line 625 of file protocol.h.
E_EFFECTS2
#define E_EFFECTS2 (1u<<18)
Definition at line 636 of file protocol.h.
E_EXTEND1
#define E_EXTEND1 (1u<<7)
Definition at line 621 of file protocol.h.
E_EXTEND2
#define E_EXTEND2 (1u<<15)
Definition at line 631 of file protocol.h.
E_EXTEND3
#define E_EXTEND3 (1u<<23)
Definition at line 641 of file protocol.h.
E_EXTEND4
#define E_EXTEND4 (1u<<31)
Definition at line 650 of file protocol.h.
E_FLAGS
#define E_FLAGS (1u<<14)
Definition at line 630 of file protocol.h.
E_FRAME1
#define E_FRAME1 (1u<<8)
Definition at line 624 of file protocol.h.
E_FRAME2
#define E_FRAME2 (1u<<16)
Definition at line 634 of file protocol.h.
E_GLOWCOLOR
#define E_GLOWCOLOR (1u<<20)
Definition at line 638 of file protocol.h.
E_GLOWSIZE
#define E_GLOWSIZE (1u<<19)
Definition at line 637 of file protocol.h.
E_LIGHT
#define E_LIGHT (1u<<21)
Definition at line 639 of file protocol.h.
E_LIGHTPFLAGS
#define E_LIGHTPFLAGS (1u<<22)
Definition at line 640 of file protocol.h.
E_LIGHTSTYLE
#define E_LIGHTSTYLE (1u<<28)
Definition at line 647 of file protocol.h.
E_MODEL1
#define E_MODEL1 (1u<<6)
Definition at line 620 of file protocol.h.
E_MODEL2
#define E_MODEL2 (1u<<17)
Definition at line 635 of file protocol.h.
E_ORIGIN1
#define E_ORIGIN1 (1u<<0)
Definition at line 614 of file protocol.h.
E_ORIGIN2
#define E_ORIGIN2 (1u<<1)
Definition at line 615 of file protocol.h.
E_ORIGIN3
#define E_ORIGIN3 (1u<<2)
Definition at line 616 of file protocol.h.
E_SCALE
#define E_SCALE (1u<<11)
Definition at line 627 of file protocol.h.
E_SKIN
#define E_SKIN (1u<<13)
Definition at line 629 of file protocol.h.
E_SOUND1
#define E_SOUND1 (1u<<24)
Definition at line 643 of file protocol.h.
E_SOUNDATTEN
#define E_SOUNDATTEN (1u<<26)
Definition at line 645 of file protocol.h.
E_SOUNDVOL
#define E_SOUNDVOL (1u<<25)
Definition at line 644 of file protocol.h.
E_TAGATTACHMENT
#define E_TAGATTACHMENT (1u<<27)
Definition at line 646 of file protocol.h.
E_UNUSED6
#define E_UNUSED6 (1u<<29)
Definition at line 648 of file protocol.h.
E_UNUSED7
#define E_UNUSED7 (1u<<30)
Definition at line 649 of file protocol.h.
EF_ADDITIVE
#define EF_ADDITIVE 32
Definition at line 74 of file protocol.h.
EF_BLUE
#define EF_BLUE 64
Definition at line 75 of file protocol.h.
EF_BRIGHTFIELD
#define EF_BRIGHTFIELD 1
Definition at line 69 of file protocol.h.
EF_BRIGHTLIGHT
#define EF_BRIGHTLIGHT 4
Definition at line 71 of file protocol.h.
EF_DIMLIGHT
#define EF_DIMLIGHT 8
Definition at line 72 of file protocol.h.
EF_DOUBLESIDED
#define EF_DOUBLESIDED 32768
Definition at line 84 of file protocol.h.
EF_DYNAMICMODELLIGHT
#define EF_DYNAMICMODELLIGHT 131072
Definition at line 86 of file protocol.h.
EF_FLAME
#define EF_FLAME 1024
Definition at line 79 of file protocol.h.
EF_FULLBRIGHT
#define EF_FULLBRIGHT 512
Definition at line 78 of file protocol.h.
EF_GIB
#define EF_GIB 67108864
Definition at line 95 of file protocol.h.
EF_GRENADE
#define EF_GRENADE 33554432
Definition at line 94 of file protocol.h.
EF_LOWPRECISION
#define EF_LOWPRECISION 4194304
Definition at line 91 of file protocol.h.
EF_MUZZLEFLASH
#define EF_MUZZLEFLASH 2
Definition at line 70 of file protocol.h.
EF_NODEPTHTEST
#define EF_NODEPTHTEST 8192
Definition at line 82 of file protocol.h.
EF_NODRAW
#define EF_NODRAW 16
Definition at line 73 of file protocol.h.
EF_NOGUNBOB
#define EF_NOGUNBOB 256
Definition at line 77 of file protocol.h.
EF_NOMODELFLAGS
#define EF_NOMODELFLAGS 8388608
Definition at line 92 of file protocol.h.
EF_NOSELFSHADOW
#define EF_NOSELFSHADOW 65536
Definition at line 85 of file protocol.h.
EF_NOSHADOW
#define EF_NOSHADOW 4096
Definition at line 81 of file protocol.h.
EF_RED
#define EF_RED 128
Definition at line 76 of file protocol.h.
EF_RESTARTANIM_BIT
#define EF_RESTARTANIM_BIT 1048576
Definition at line 89 of file protocol.h.
EF_ROCKET
#define EF_ROCKET 16777216
Definition at line 93 of file protocol.h.
EF_ROTATE
#define EF_ROTATE 134217728
Definition at line 96 of file protocol.h.
EF_SELECTABLE
#define EF_SELECTABLE 16384
Definition at line 83 of file protocol.h.
EF_STARDUST
#define EF_STARDUST 2048
Definition at line 80 of file protocol.h.
EF_TELEPORT_BIT
#define EF_TELEPORT_BIT 2097152
Definition at line 90 of file protocol.h.
EF_TRACER
#define EF_TRACER 268435456
Definition at line 97 of file protocol.h.
EF_TRACER2
#define EF_TRACER2 1073741824
Definition at line 99 of file protocol.h.
EF_TRACER3
#define EF_TRACER3 0x80000000
Definition at line 100 of file protocol.h.
EF_UNUSED18
#define EF_UNUSED18 262144
Definition at line 87 of file protocol.h.
EF_UNUSED19
#define EF_UNUSED19 524288
Definition at line 88 of file protocol.h.
EF_ZOMGIB
#define EF_ZOMGIB 536870912
Definition at line 98 of file protocol.h.
ENTITYFRAME5_MAXPACKETLOGS
#define ENTITYFRAME5_MAXPACKETLOGS 64
Definition at line 827 of file protocol.h.
ENTITYFRAME5_MAXSTATES
#define ENTITYFRAME5_MAXSTATES 1024
Definition at line 828 of file protocol.h.
ENTITYFRAME5_PRIORITYLEVELS
#define ENTITYFRAME5_PRIORITYLEVELS 32
Definition at line 829 of file protocol.h.
ENTITYSIZEPROFILING_END
#define ENTITYSIZEPROFILING_END (msg, num, flags)
Value:
    if(developer_networkentities.integer >= 2) \
    { \
        prvm_edict_t *edict = prog->edicts + num; \
        Con_Printf("sent entity update of size %u for %d classname %s flags %d\n", (msg->cursize - entityprofiling_startsize), num, PRVM_serveredictstring(edict, classname) ? PRVM_GetString(prog, PRVM_serveredictstring(edict, classname)) : "(no classname)", flags); \
    }
Definition at line 43 of file protocol.h.
    { \
        prvm_edict_t *edict = prog->edicts + num; \
        Con_Printf("sent entity update of size %u for %d classname %s flags %d\n", (msg->cursize - entityprofiling_startsize), num, PRVM_serveredictstring(edict, classname) ? PRVM_GetString(prog, PRVM_serveredictstring(edict, classname)) : "(no classname)", flags); \
    }
ENTITYSIZEPROFILING_START
#define ENTITYSIZEPROFILING_START (msg, num, flags) int entityprofiling_startsize = msg->cursize
Definition at line 40 of file protocol.h.
GAME_COOP
#define GAME_COOP 0
Definition at line 204 of file protocol.h.
GAME_DEATHMATCH
#define GAME_DEATHMATCH 1
Definition at line 205 of file protocol.h.
INTEF_FLAG1QW
#define INTEF_FLAG1QW 1
Definition at line 103 of file protocol.h.
INTEF_FLAG2QW
#define INTEF_FLAG2QW 2
Definition at line 104 of file protocol.h.
MAX_ENTITY_DATABASE
#define MAX_ENTITY_DATABASE (MAX_EDICTS * 2)
Definition at line 555 of file protocol.h.
MAX_ENTITY_HISTORY
#define MAX_ENTITY_HISTORY 64
Definition at line 554 of file protocol.h.
MAX_FRAMEGROUPBLENDS
#define MAX_FRAMEGROUPBLENDS 4
Definition at line 409 of file protocol.h.
MF_GIB
#define MF_GIB 4
Definition at line 61 of file protocol.h.
MF_GRENADE
#define MF_GRENADE 2
Definition at line 60 of file protocol.h.
MF_ROCKET
#define MF_ROCKET 1
Definition at line 59 of file protocol.h.
MF_ROTATE
#define MF_ROTATE 8
Definition at line 62 of file protocol.h.
MF_TRACER
#define MF_TRACER 16
Definition at line 63 of file protocol.h.
MF_TRACER2
#define MF_TRACER2 64
Definition at line 65 of file protocol.h.
MF_TRACER3
#define MF_TRACER3 128
Definition at line 66 of file protocol.h.
MF_ZOMGIB
#define MF_ZOMGIB 32
Definition at line 64 of file protocol.h.
PFLAGS_CORONA
#define PFLAGS_CORONA 2
Definition at line 108 of file protocol.h.
PFLAGS_FULLDYNAMIC
#define PFLAGS_FULLDYNAMIC 128
Definition at line 109 of file protocol.h.
PFLAGS_NOSHADOW
#define PFLAGS_NOSHADOW 1
Definition at line 107 of file protocol.h.
qw_clc_bad
#define qw_clc_bad 0
Definition at line 955 of file protocol.h.
qw_clc_delta
#define qw_clc_delta 5
Definition at line 959 of file protocol.h.
qw_clc_move
#define qw_clc_move 3
Definition at line 957 of file protocol.h.
qw_clc_nop
#define qw_clc_nop 1
Definition at line 956 of file protocol.h.
qw_clc_stringcmd
#define qw_clc_stringcmd 4
Definition at line 958 of file protocol.h.
qw_clc_tmove
#define qw_clc_tmove 6
Definition at line 960 of file protocol.h.
qw_clc_upload
#define qw_clc_upload 7
Definition at line 961 of file protocol.h.
QW_CM_ANGLE1
#define QW_CM_ANGLE1 (1<<0)
Definition at line 981 of file protocol.h.
QW_CM_ANGLE2
#define QW_CM_ANGLE2 (1<<7)
Definition at line 988 of file protocol.h.
QW_CM_ANGLE3
#define QW_CM_ANGLE3 (1<<1)
Definition at line 982 of file protocol.h.
QW_CM_BUTTONS
#define QW_CM_BUTTONS (1<<5)
Definition at line 986 of file protocol.h.
QW_CM_FORWARD
#define QW_CM_FORWARD (1<<2)
Definition at line 983 of file protocol.h.
QW_CM_IMPULSE
#define QW_CM_IMPULSE (1<<6)
Definition at line 987 of file protocol.h.
QW_CM_SIDE
#define QW_CM_SIDE (1<<3)
Definition at line 984 of file protocol.h.
QW_CM_UP
#define QW_CM_UP (1<<4)
Definition at line 985 of file protocol.h.
QW_EF_BLUE
#define QW_EF_BLUE 64
Definition at line 1031 of file protocol.h.
QW_EF_BRIGHTFIELD
#define QW_EF_BRIGHTFIELD 1
Definition at line 1025 of file protocol.h.
QW_EF_BRIGHTLIGHT
#define QW_EF_BRIGHTLIGHT 4
Definition at line 1027 of file protocol.h.
QW_EF_DIMLIGHT
#define QW_EF_DIMLIGHT 8
Definition at line 1028 of file protocol.h.
QW_EF_FLAG1
#define QW_EF_FLAG1 16
Definition at line 1029 of file protocol.h.
QW_EF_FLAG2
#define QW_EF_FLAG2 32
Definition at line 1030 of file protocol.h.
QW_EF_MUZZLEFLASH
#define QW_EF_MUZZLEFLASH 2
Definition at line 1026 of file protocol.h.
QW_EF_RED
#define QW_EF_RED 128
Definition at line 1032 of file protocol.h.
QW_MAX_PACKET_ENTITIES
#define QW_MAX_PACKET_ENTITIES 64
Definition at line 1036 of file protocol.h.
QW_PF_COMMAND
#define QW_PF_COMMAND (1<<1)
Definition at line 966 of file protocol.h.
QW_PF_DEAD
#define QW_PF_DEAD (1<<9)
Definition at line 974 of file protocol.h.
QW_PF_EFFECTS
#define QW_PF_EFFECTS (1<<7)
Definition at line 972 of file protocol.h.
QW_PF_GIB
#define QW_PF_GIB (1<<10)
Definition at line 975 of file protocol.h.
QW_PF_MODEL
#define QW_PF_MODEL (1<<5)
Definition at line 970 of file protocol.h.
QW_PF_MSEC
#define QW_PF_MSEC (1<<0)
Definition at line 965 of file protocol.h.
QW_PF_NOGRAV
#define QW_PF_NOGRAV (1<<11)
Definition at line 976 of file protocol.h.
QW_PF_SKINNUM
#define QW_PF_SKINNUM (1<<6)
Definition at line 971 of file protocol.h.
QW_PF_VELOCITY1
#define QW_PF_VELOCITY1 (1<<2)
Definition at line 967 of file protocol.h.
QW_PF_VELOCITY2
#define QW_PF_VELOCITY2 (1<<3)
Definition at line 968 of file protocol.h.
QW_PF_VELOCITY3
#define QW_PF_VELOCITY3 (1<<4)
Definition at line 969 of file protocol.h.
QW_PF_WEAPONFRAME
#define QW_PF_WEAPONFRAME (1<<8)
Definition at line 973 of file protocol.h.
QW_STAT_ACTIVEWEAPON
#define QW_STAT_ACTIVEWEAPON 10
Definition at line 1051 of file protocol.h.
QW_STAT_AMMO
#define QW_STAT_AMMO 3
Definition at line 1044 of file protocol.h.
QW_STAT_ARMOR
#define QW_STAT_ARMOR 4
Definition at line 1045 of file protocol.h.
QW_STAT_CELLS
#define QW_STAT_CELLS 9
Definition at line 1050 of file protocol.h.
QW_STAT_HEALTH
#define QW_STAT_HEALTH 0
Definition at line 1041 of file protocol.h.
QW_STAT_ITEMS
#define QW_STAT_ITEMS 15
Definition at line 1056 of file protocol.h.
QW_STAT_MONSTERS
#define QW_STAT_MONSTERS 14
Definition at line 1055 of file protocol.h.
QW_STAT_NAILS
#define QW_STAT_NAILS 7
Definition at line 1048 of file protocol.h.
QW_STAT_ROCKETS
#define QW_STAT_ROCKETS 8
Definition at line 1049 of file protocol.h.
QW_STAT_SECRETS
#define QW_STAT_SECRETS 13
Definition at line 1054 of file protocol.h.
QW_STAT_SHELLS
#define QW_STAT_SHELLS 6
Definition at line 1047 of file protocol.h.
QW_STAT_TOTALMONSTERS
#define QW_STAT_TOTALMONSTERS 12
Definition at line 1053 of file protocol.h.
QW_STAT_TOTALSECRETS
#define QW_STAT_TOTALSECRETS 11
Definition at line 1052 of file protocol.h.
QW_STAT_WEAPON
#define QW_STAT_WEAPON 2
Definition at line 1043 of file protocol.h.
qw_svc_bad
#define qw_svc_bad 0
Definition at line 907 of file protocol.h.
qw_svc_bigkick
#define qw_svc_bigkick 35
Definition at line 934 of file protocol.h.
qw_svc_cdtrack
#define qw_svc_cdtrack 32
Definition at line 931 of file protocol.h.
qw_svc_centerprint
#define qw_svc_centerprint 26
Definition at line 925 of file protocol.h.
qw_svc_chokecount
#define qw_svc_chokecount 44
Definition at line 943 of file protocol.h.
qw_svc_damage
#define qw_svc_damage 19
Definition at line 920 of file protocol.h.
qw_svc_deltapacketentities
#define qw_svc_deltapacketentities 48
Definition at line 947 of file protocol.h.
qw_svc_disconnect
#define qw_svc_disconnect 2
Definition at line 909 of file protocol.h.
qw_svc_download
#define qw_svc_download 41
Definition at line 940 of file protocol.h.
qw_svc_entgravity
#define qw_svc_entgravity 50
Definition at line 949 of file protocol.h.
qw_svc_finale
#define qw_svc_finale 31
Definition at line 930 of file protocol.h.
qw_svc_foundsecret
#define qw_svc_foundsecret 28
Definition at line 927 of file protocol.h.
qw_svc_intermission
#define qw_svc_intermission 30
Definition at line 929 of file protocol.h.
qw_svc_killedmonster
#define qw_svc_killedmonster 27
Definition at line 926 of file protocol.h.
qw_svc_lightstyle
#define qw_svc_lightstyle 12
Definition at line 917 of file protocol.h.
qw_svc_maxspeed
#define qw_svc_maxspeed 49
Definition at line 948 of file protocol.h.
qw_svc_modellist
#define qw_svc_modellist 45
Definition at line 944 of file protocol.h.
qw_svc_muzzleflash
#define qw_svc_muzzleflash 39
Definition at line 938 of file protocol.h.
qw_svc_nails
#define qw_svc_nails 43
Definition at line 942 of file protocol.h.
qw_svc_nop
#define qw_svc_nop 1
Definition at line 908 of file protocol.h.
qw_svc_packetentities
#define qw_svc_packetentities 47
Definition at line 946 of file protocol.h.
qw_svc_playerinfo
#define qw_svc_playerinfo 42
Definition at line 941 of file protocol.h.
qw_svc_print
#define qw_svc_print 8
Definition at line 913 of file protocol.h.
qw_svc_sellscreen
#define qw_svc_sellscreen 33
Definition at line 932 of file protocol.h.
qw_svc_serverdata
#define qw_svc_serverdata 11
Definition at line 916 of file protocol.h.
qw_svc_serverinfo
#define qw_svc_serverinfo 52
Definition at line 951 of file protocol.h.
qw_svc_setangle
#define qw_svc_setangle 10
Definition at line 915 of file protocol.h.
qw_svc_setinfo
#define qw_svc_setinfo 51
Definition at line 950 of file protocol.h.
qw_svc_setpause
#define qw_svc_setpause 24
Definition at line 924 of file protocol.h.
qw_svc_setview
#define qw_svc_setview 5
Definition at line 911 of file protocol.h.
qw_svc_smallkick
#define qw_svc_smallkick 34
Definition at line 933 of file protocol.h.
qw_svc_sound
#define qw_svc_sound 6
Definition at line 912 of file protocol.h.
qw_svc_soundlist
#define qw_svc_soundlist 46
Definition at line 945 of file protocol.h.
qw_svc_spawnbaseline
#define qw_svc_spawnbaseline 22
Definition at line 922 of file protocol.h.
qw_svc_spawnstatic
#define qw_svc_spawnstatic 20
Definition at line 921 of file protocol.h.
qw_svc_spawnstaticsound
#define qw_svc_spawnstaticsound 29
Definition at line 928 of file protocol.h.
qw_svc_stopsound
#define qw_svc_stopsound 16
Definition at line 919 of file protocol.h.
qw_svc_stufftext
#define qw_svc_stufftext 9
Definition at line 914 of file protocol.h.
qw_svc_temp_entity
#define qw_svc_temp_entity 23
Definition at line 923 of file protocol.h.
qw_svc_updateentertime
#define qw_svc_updateentertime 37
Definition at line 936 of file protocol.h.
qw_svc_updatefrags
#define qw_svc_updatefrags 14
Definition at line 918 of file protocol.h.
qw_svc_updateping
#define qw_svc_updateping 36
Definition at line 935 of file protocol.h.
qw_svc_updatepl
#define qw_svc_updatepl 53
Definition at line 952 of file protocol.h.
qw_svc_updatestat
#define qw_svc_updatestat 3
Definition at line 910 of file protocol.h.
qw_svc_updatestatlong
#define qw_svc_updatestatlong 38
Definition at line 937 of file protocol.h.
qw_svc_updateuserinfo
#define qw_svc_updateuserinfo 40
Definition at line 939 of file protocol.h.
QW_TE_BLOOD
#define QW_TE_BLOOD 12
Definition at line 1021 of file protocol.h.
QW_TE_EXPLOSION
#define QW_TE_EXPLOSION 3
Definition at line 1012 of file protocol.h.
QW_TE_GUNSHOT
#define QW_TE_GUNSHOT 2
Definition at line 1011 of file protocol.h.
QW_TE_KNIGHTSPIKE
#define QW_TE_KNIGHTSPIKE 8
Definition at line 1017 of file protocol.h.
QW_TE_LAVASPLASH
#define QW_TE_LAVASPLASH 10
Definition at line 1019 of file protocol.h.
QW_TE_LIGHTNING1
#define QW_TE_LIGHTNING1 5
Definition at line 1014 of file protocol.h.
QW_TE_LIGHTNING2
#define QW_TE_LIGHTNING2 6
Definition at line 1015 of file protocol.h.
QW_TE_LIGHTNING3
#define QW_TE_LIGHTNING3 9
Definition at line 1018 of file protocol.h.
QW_TE_LIGHTNINGBLOOD
#define QW_TE_LIGHTNINGBLOOD 13
Definition at line 1022 of file protocol.h.
QW_TE_SPIKE
#define QW_TE_SPIKE 0
Definition at line 1009 of file protocol.h.
QW_TE_SUPERSPIKE
#define QW_TE_SUPERSPIKE 1
Definition at line 1010 of file protocol.h.
QW_TE_TAREXPLOSION
#define QW_TE_TAREXPLOSION 4
Definition at line 1013 of file protocol.h.
QW_TE_TELEPORT
#define QW_TE_TELEPORT 11
Definition at line 1020 of file protocol.h.
QW_TE_WIZSPIKE
#define QW_TE_WIZSPIKE 7
Definition at line 1016 of file protocol.h.
QW_U_ANGLE1
#define QW_U_ANGLE1 (1<<0)
Definition at line 1000 of file protocol.h.
QW_U_ANGLE2
#define QW_U_ANGLE2 (1<<12)
Definition at line 995 of file protocol.h.
QW_U_ANGLE3
#define QW_U_ANGLE3 (1<<1)
Definition at line 1001 of file protocol.h.
QW_U_COLORMAP
#define QW_U_COLORMAP (1<<3)
Definition at line 1003 of file protocol.h.
QW_U_EFFECTS
#define QW_U_EFFECTS (1<<5)
Definition at line 1005 of file protocol.h.
QW_U_FRAME
#define QW_U_FRAME (1<<13)
Definition at line 996 of file protocol.h.
QW_U_MODEL
#define QW_U_MODEL (1<<2)
Definition at line 1002 of file protocol.h.
QW_U_MOREBITS
#define QW_U_MOREBITS (1<<15)
Definition at line 998 of file protocol.h.
QW_U_ORIGIN1
#define QW_U_ORIGIN1 (1<<9)
Definition at line 992 of file protocol.h.
QW_U_ORIGIN2
#define QW_U_ORIGIN2 (1<<10)
Definition at line 993 of file protocol.h.
QW_U_ORIGIN3
#define QW_U_ORIGIN3 (1<<11)
Definition at line 994 of file protocol.h.
QW_U_REMOVE
#define QW_U_REMOVE (1<<14)
Definition at line 997 of file protocol.h.
QW_U_SKIN
#define QW_U_SKIN (1<<4)
Definition at line 1004 of file protocol.h.
QW_U_SOLID
#define QW_U_SOLID (1<<6)
Definition at line 1006 of file protocol.h.
QW_UPDATE_BACKUP
#define QW_UPDATE_BACKUP 64
Definition at line 1034 of file protocol.h.
QW_UPDATE_MASK
#define QW_UPDATE_MASK (QW_UPDATE_BACKUP - 1)
Definition at line 1035 of file protocol.h.
RENDER_ADDITIVE
#define RENDER_ADDITIVE 2097152
Definition at line 371 of file protocol.h.
RENDER_COLORMAPPED
#define RENDER_COLORMAPPED 32
Definition at line 362 of file protocol.h.
RENDER_COMPLEXANIMATION
#define RENDER_COMPLEXANIMATION 128
Definition at line 364 of file protocol.h.
RENDER_CUSTOMIZEDMODELLIGHT
#define RENDER_CUSTOMIZEDMODELLIGHT 4096
Definition at line 373 of file protocol.h.
RENDER_DOUBLESIDED
#define RENDER_DOUBLESIDED 4194304
Definition at line 372 of file protocol.h.
RENDER_DYNAMICMODELLIGHT
#define RENDER_DYNAMICMODELLIGHT 8388608
Definition at line 374 of file protocol.h.
RENDER_EXTERIORMODEL
#define RENDER_EXTERIORMODEL 8
Definition at line 360 of file protocol.h.
RENDER_GLOWTRAIL
#define RENDER_GLOWTRAIL 2
Definition at line 358 of file protocol.h.
RENDER_LIGHT
#define RENDER_LIGHT 131072
Definition at line 367 of file protocol.h.
RENDER_LOWPRECISION
#define RENDER_LOWPRECISION 16
Definition at line 361 of file protocol.h.
RENDER_NODEPTHTEST
#define RENDER_NODEPTHTEST 1048576
Definition at line 370 of file protocol.h.
RENDER_NOSELFSHADOW
#define RENDER_NOSELFSHADOW 262144
Definition at line 368 of file protocol.h.
RENDER_SHADOW
#define RENDER_SHADOW 65536
Definition at line 366 of file protocol.h.
RENDER_STEP
#define RENDER_STEP 1
Definition at line 357 of file protocol.h.
RENDER_VIEWMODEL
#define RENDER_VIEWMODEL 4
Definition at line 359 of file protocol.h.
RENDER_WORLDOBJECT
#define RENDER_WORLDOBJECT 64
Definition at line 363 of file protocol.h.
SCOPE_ASSUMED_EXISTING
#define SCOPE_ASSUMED_EXISTING 8
Definition at line 55 of file protocol.h.
SCOPE_EXISTED_ONCE
#define SCOPE_EXISTED_ONCE 4
Definition at line 54 of file protocol.h.
SCOPE_WANTREMOVE
#define SCOPE_WANTREMOVE 1
Definition at line 51 of file protocol.h.
SCOPE_WANTSEND
#define SCOPE_WANTSEND (SCOPE_WANTREMOVE | SCOPE_WANTUPDATE)
Definition at line 53 of file protocol.h.
SCOPE_WANTUPDATE
#define SCOPE_WANTUPDATE 2
Definition at line 52 of file protocol.h.
SND_ATTENUATION
#define SND_ATTENUATION (1<<1)
Definition at line 191 of file protocol.h.
SND_LARGEENTITY
#define SND_LARGEENTITY (1<<3)
Definition at line 193 of file protocol.h.
SND_LARGESOUND
#define SND_LARGESOUND (1<<4)
Definition at line 194 of file protocol.h.
SND_LOOPING
#define SND_LOOPING (1<<2)
Definition at line 192 of file protocol.h.
SND_SPEEDUSHORT4000
#define SND_SPEEDUSHORT4000 (1<<5)
Definition at line 195 of file protocol.h.
SND_VOLUME
#define SND_VOLUME (1<<0)
Definition at line 190 of file protocol.h.
SU_ARMOR
#define SU_ARMOR (1u<<13)
Definition at line 166 of file protocol.h.
SU_EXTEND1
#define SU_EXTEND1 (1u<<15)
Definition at line 168 of file protocol.h.
SU_EXTEND2
#define SU_EXTEND2 (1u<<23)
another byte to follow, future expansion
Definition at line 177 of file protocol.h.
SU_EXTEND3
#define SU_EXTEND3 (1u<<31)
another byte to follow, future expansion
Definition at line 186 of file protocol.h.
SU_IDEALPITCH
#define SU_IDEALPITCH (1u<<1)
Definition at line 154 of file protocol.h.
SU_INWATER
#define SU_INWATER (1u<<11)
no data follows, the bit is it
Definition at line 164 of file protocol.h.
SU_ITEMS
#define SU_ITEMS (1u<<9)
Definition at line 162 of file protocol.h.
SU_ONGROUND
#define SU_ONGROUND (1u<<10)
no data follows, the bit is it
Definition at line 163 of file protocol.h.
SU_PUNCH1
#define SU_PUNCH1 (1u<<2)
Definition at line 155 of file protocol.h.
SU_PUNCH2
#define SU_PUNCH2 (1u<<3)
Definition at line 156 of file protocol.h.
SU_PUNCH3
#define SU_PUNCH3 (1u<<4)
Definition at line 157 of file protocol.h.
SU_PUNCHVEC1
#define SU_PUNCHVEC1 (1u<<16)
Definition at line 170 of file protocol.h.
SU_PUNCHVEC2
#define SU_PUNCHVEC2 (1u<<17)
Definition at line 171 of file protocol.h.
SU_PUNCHVEC3
#define SU_PUNCHVEC3 (1u<<18)
Definition at line 172 of file protocol.h.
SU_UNUSED20
#define SU_UNUSED20 (1u<<20)
Definition at line 174 of file protocol.h.
SU_UNUSED21
#define SU_UNUSED21 (1u<<21)
Definition at line 175 of file protocol.h.
SU_UNUSED22
#define SU_UNUSED22 (1u<<22)
Definition at line 176 of file protocol.h.
SU_UNUSED24
#define SU_UNUSED24 (1u<<24)
Definition at line 179 of file protocol.h.
SU_UNUSED25
#define SU_UNUSED25 (1u<<25)
Definition at line 180 of file protocol.h.
SU_UNUSED26
#define SU_UNUSED26 (1u<<26)
Definition at line 181 of file protocol.h.
SU_UNUSED27
#define SU_UNUSED27 (1u<<27)
Definition at line 182 of file protocol.h.
SU_UNUSED28
#define SU_UNUSED28 (1u<<28)
Definition at line 183 of file protocol.h.
SU_UNUSED29
#define SU_UNUSED29 (1u<<29)
Definition at line 184 of file protocol.h.
SU_UNUSED30
#define SU_UNUSED30 (1u<<30)
Definition at line 185 of file protocol.h.
SU_VELOCITY1
#define SU_VELOCITY1 (1u<<5)
Definition at line 158 of file protocol.h.
SU_VELOCITY2
#define SU_VELOCITY2 (1u<<6)
Definition at line 159 of file protocol.h.
SU_VELOCITY3
#define SU_VELOCITY3 (1u<<7)
Definition at line 160 of file protocol.h.
SU_VIEWHEIGHT
#define SU_VIEWHEIGHT (1u<<0)
Definition at line 153 of file protocol.h.
SU_VIEWZOOM
#define SU_VIEWZOOM (1u<<19)
byte factor (0 = 0.0 (not valid), 255 = 1.0)
Definition at line 173 of file protocol.h.
SU_WEAPON
#define SU_WEAPON (1u<<14)
Definition at line 167 of file protocol.h.
SU_WEAPONFRAME
#define SU_WEAPONFRAME (1u<<12)
Definition at line 165 of file protocol.h.
svc_bad
#define svc_bad 0
Definition at line 215 of file protocol.h.
svc_cdtrack
#define svc_cdtrack 32
Definition at line 260 of file protocol.h.
svc_centerprint
#define svc_centerprint 26
Definition at line 250 of file protocol.h.
svc_clientdata
#define svc_clientdata 15
Definition at line 235 of file protocol.h.
svc_csqcentities
#define svc_csqcentities 58
Definition at line 279 of file protocol.h.
svc_cutscene
#define svc_cutscene 34
Definition at line 263 of file protocol.h.
svc_damage
#define svc_damage 19
Definition at line 239 of file protocol.h.
svc_disconnect
#define svc_disconnect 2
Definition at line 217 of file protocol.h.
svc_downloaddata
#define svc_downloaddata 50
Definition at line 270 of file protocol.h.
svc_effect
#define svc_effect 52
Definition at line 272 of file protocol.h.
svc_effect2
#define svc_effect2 53
Definition at line 273 of file protocol.h.
svc_entities
#define svc_entities 57
Definition at line 278 of file protocol.h.
svc_finale
#define svc_finale 31
Definition at line 258 of file protocol.h.
svc_foundsecret
#define svc_foundsecret 28
Definition at line 253 of file protocol.h.
svc_hidelmp
#define svc_hidelmp 36
Definition at line 266 of file protocol.h.
svc_intermission
#define svc_intermission 30
Definition at line 257 of file protocol.h.
svc_killedmonster
#define svc_killedmonster 27
Definition at line 252 of file protocol.h.
svc_lightstyle
#define svc_lightstyle 12
Definition at line 232 of file protocol.h.
svc_nop
#define svc_nop 1
Definition at line 216 of file protocol.h.
svc_particle
#define svc_particle 18
Definition at line 238 of file protocol.h.
svc_pointparticles
#define svc_pointparticles 61
Definition at line 282 of file protocol.h.
svc_pointparticles1
#define svc_pointparticles1 62
Definition at line 283 of file protocol.h.
svc_precache
#define svc_precache 54
Definition at line 275 of file protocol.h.
svc_print
#define svc_print 8
Definition at line 223 of file protocol.h.
svc_sellscreen
#define svc_sellscreen 33
Definition at line 261 of file protocol.h.
svc_serverinfo
#define svc_serverinfo 11
Definition at line 228 of file protocol.h.
svc_setangle
#define svc_setangle 10
Definition at line 226 of file protocol.h.
svc_setpause
#define svc_setpause 24
Definition at line 247 of file protocol.h.
svc_setview
#define svc_setview 5
Definition at line 220 of file protocol.h.
svc_showlmp
#define svc_showlmp 35
Definition at line 265 of file protocol.h.
svc_signonnum
#define svc_signonnum 25
Definition at line 248 of file protocol.h.
svc_skybox
#define svc_skybox 37
Definition at line 267 of file protocol.h.
svc_sound
#define svc_sound 6
Definition at line 221 of file protocol.h.
svc_sound2
#define svc_sound2 54
Definition at line 274 of file protocol.h.
svc_spawnbaseline
#define svc_spawnbaseline 22
Definition at line 243 of file protocol.h.
svc_spawnbaseline2
#define svc_spawnbaseline2 55
Definition at line 276 of file protocol.h.
svc_spawnstatic
#define svc_spawnstatic 20
Definition at line 241 of file protocol.h.
svc_spawnstatic2
#define svc_spawnstatic2 56
Definition at line 277 of file protocol.h.
svc_spawnstaticsound
#define svc_spawnstaticsound 29
Definition at line 255 of file protocol.h.
svc_spawnstaticsound2
#define svc_spawnstaticsound2 59
Definition at line 280 of file protocol.h.
svc_stopsound
#define svc_stopsound 16
Definition at line 236 of file protocol.h.
svc_stufftext
#define svc_stufftext 9
Definition at line 224 of file protocol.h.
svc_temp_entity
#define svc_temp_entity 23
Definition at line 245 of file protocol.h.
svc_time
#define svc_time 7
Definition at line 222 of file protocol.h.
svc_trailparticles
#define svc_trailparticles 60
Definition at line 281 of file protocol.h.
svc_updatecolors
#define svc_updatecolors 17
Definition at line 237 of file protocol.h.
svc_updatefrags
#define svc_updatefrags 14
Definition at line 234 of file protocol.h.
svc_updatename
#define svc_updatename 13
Definition at line 233 of file protocol.h.
svc_updatestat
#define svc_updatestat 3
Definition at line 218 of file protocol.h.
svc_updatestatubyte
#define svc_updatestatubyte 51
Definition at line 271 of file protocol.h.
svc_version
#define svc_version 4
Definition at line 219 of file protocol.h.
TE_BEAM
#define TE_BEAM 13
Definition at line 324 of file protocol.h.
TE_BLOOD
#define TE_BLOOD 50
Definition at line 332 of file protocol.h.
TE_BLOODSHOWER
#define TE_BLOODSHOWER 52
Definition at line 334 of file protocol.h.
TE_CUSTOMFLASH
#define TE_CUSTOMFLASH 73
Definition at line 346 of file protocol.h.
TE_EXPLOSION
#define TE_EXPLOSION 3
Definition at line 312 of file protocol.h.
TE_EXPLOSION2
#define TE_EXPLOSION2 12
Definition at line 321 of file protocol.h.
TE_EXPLOSION3
#define TE_EXPLOSION3 16
Definition at line 328 of file protocol.h.
TE_EXPLOSIONQUAD
#define TE_EXPLOSIONQUAD 70
Definition at line 343 of file protocol.h.
TE_EXPLOSIONRGB
#define TE_EXPLOSIONRGB 53
Definition at line 335 of file protocol.h.
TE_FLAMEJET
#define TE_FLAMEJET 74
Definition at line 347 of file protocol.h.
TE_GUNSHOT
#define TE_GUNSHOT 2
Definition at line 311 of file protocol.h.
TE_GUNSHOTQUAD
#define TE_GUNSHOTQUAD 57
Definition at line 339 of file protocol.h.
TE_KNIGHTSPIKE
#define TE_KNIGHTSPIKE 8
Definition at line 317 of file protocol.h.
TE_LAVASPLASH
#define TE_LAVASPLASH 10
Definition at line 319 of file protocol.h.
TE_LIGHTNING1
#define TE_LIGHTNING1 5
Definition at line 314 of file protocol.h.
TE_LIGHTNING2
#define TE_LIGHTNING2 6
Definition at line 315 of file protocol.h.
TE_LIGHTNING3
#define TE_LIGHTNING3 9
Definition at line 318 of file protocol.h.
TE_LIGHTNING4NEH
#define TE_LIGHTNING4NEH 17
Definition at line 329 of file protocol.h.
TE_PARTICLECUBE
#define TE_PARTICLECUBE 54
Definition at line 336 of file protocol.h.
TE_PARTICLERAIN
#define TE_PARTICLERAIN 55
Definition at line 337 of file protocol.h.
TE_PARTICLESNOW
#define TE_PARTICLESNOW 56
Definition at line 338 of file protocol.h.
TE_PLASMABURN
#define TE_PLASMABURN 75
Definition at line 348 of file protocol.h.
TE_SMALLFLASH
#define TE_SMALLFLASH 72
Definition at line 345 of file protocol.h.
TE_SPARK
#define TE_SPARK 51
Definition at line 333 of file protocol.h.
TE_SPIKE
#define TE_SPIKE 0
Definition at line 309 of file protocol.h.
TE_SPIKEQUAD
#define TE_SPIKEQUAD 58
Definition at line 340 of file protocol.h.
TE_SUPERSPIKE
#define TE_SUPERSPIKE 1
Definition at line 310 of file protocol.h.
TE_SUPERSPIKEQUAD
#define TE_SUPERSPIKEQUAD 59
Definition at line 341 of file protocol.h.
TE_TAREXPLOSION
#define TE_TAREXPLOSION 4
Definition at line 313 of file protocol.h.
TE_TEI_BIGEXPLOSION
#define TE_TEI_BIGEXPLOSION 78
Definition at line 352 of file protocol.h.
TE_TEI_G3
#define TE_TEI_G3 76
Definition at line 350 of file protocol.h.
TE_TEI_PLASMAHIT
#define TE_TEI_PLASMAHIT 79
Definition at line 353 of file protocol.h.
TE_TEI_SMOKE
#define TE_TEI_SMOKE 77
Definition at line 351 of file protocol.h.
TE_TELEPORT
#define TE_TELEPORT 11
Definition at line 320 of file protocol.h.
TE_UNUSED1
#define TE_UNUSED1 71
Definition at line 344 of file protocol.h.
TE_WIZSPIKE
#define TE_WIZSPIKE 7
Definition at line 316 of file protocol.h.
U_ALPHA
#define U_ALPHA (1u<<17)
1 byte, 0.0-1.0 maps to 0-255, not sent if exactly 1, and the entity is not sent if <=0 unless it has effects (model effects are checked as well)
Definition at line 135 of file protocol.h.
U_ANGLE1
#define U_ANGLE1 (1u<<8)
Definition at line 123 of file protocol.h.
U_ANGLE2
#define U_ANGLE2 (1u<<4)
Definition at line 116 of file protocol.h.
U_ANGLE3
#define U_ANGLE3 (1u<<9)
Definition at line 124 of file protocol.h.
U_COLORMAP
#define U_COLORMAP (1u<<11)
Definition at line 126 of file protocol.h.
U_COLORMOD
#define U_COLORMOD (1u<<22)
1 byte, 3 bit red, 3 bit green, 2 bit blue, this lets you tint an object artifically, so you could make a red rocket, or a blue fiend...
Definition at line 140 of file protocol.h.
U_DELTA
#define U_DELTA (1u<<16)
no data, while this is set the entity is delta compressed (uses previous frame as a baseline, meaning only things that have changed from the previous frame are sent, except for the forced full update every half second)
Definition at line 134 of file protocol.h.
U_EFFECTS
#define U_EFFECTS (1u<<13)
Definition at line 128 of file protocol.h.
U_EFFECTS2
#define U_EFFECTS2 (1u<<19)
1 byte, this is .effects & 0xFF00 (second byte)
Definition at line 137 of file protocol.h.
U_EXTEND1
#define U_EXTEND1 (1u<<15)
Definition at line 132 of file protocol.h.
U_EXTEND2
#define U_EXTEND2 (1u<<23)
another byte to follow
Definition at line 141 of file protocol.h.
U_EXTEND3
#define U_EXTEND3 (1u<<31)
another byte to follow, future expansion
Definition at line 150 of file protocol.h.
U_EXTERIORMODEL
#define U_EXTERIORMODEL (1u<<28)
causes this model to not be drawn when using a first person view (third person will draw it, first person will not)
Definition at line 147 of file protocol.h.
U_FRAME
#define U_FRAME (1u<<6)
Definition at line 119 of file protocol.h.
U_FRAME2
#define U_FRAME2 (1u<<26)
1 byte, this is .frame & 0xFF00 (second byte)
Definition at line 145 of file protocol.h.
U_GLOWCOLOR
#define U_GLOWCOLOR (1u<<21)
1 byte, palette index, default is 254 (white), this IS used for darklight (allowing colored darklight), however the particles from a darklight are always black, not sent if default value (even if glowsize or glowtrail is set)
Definition at line 139 of file protocol.h.
U_GLOWSIZE
#define U_GLOWSIZE (1u<<20)
1 byte, encoding is float/4.0, unsigned, not sent if 0
Definition at line 138 of file protocol.h.
U_GLOWTRAIL
#define U_GLOWTRAIL (1u<<24)
leaves a trail of particles (of color .glowcolor, or black if it is a negative glowsize)
Definition at line 143 of file protocol.h.
U_LONGENTITY
#define U_LONGENTITY (1u<<14)
Definition at line 129 of file protocol.h.
U_MODEL
#define U_MODEL (1u<<10)
Definition at line 125 of file protocol.h.
U_MODEL2
#define U_MODEL2 (1u<<27)
1 byte, this is .modelindex & 0xFF00 (second byte)
Definition at line 146 of file protocol.h.
U_MOREBITS
#define U_MOREBITS (1u<<0)
Definition at line 112 of file protocol.h.
U_ORIGIN1
#define U_ORIGIN1 (1u<<1)
Definition at line 113 of file protocol.h.
U_ORIGIN2
#define U_ORIGIN2 (1u<<2)
Definition at line 114 of file protocol.h.
U_ORIGIN3
#define U_ORIGIN3 (1u<<3)
Definition at line 115 of file protocol.h.
U_SCALE
#define U_SCALE (1u<<18)
1 byte, scale / 16 positive, not sent if 1.0
Definition at line 136 of file protocol.h.
U_SIGNAL
#define U_SIGNAL (1u<<7)
Definition at line 121 of file protocol.h.
U_SKIN
#define U_SKIN (1u<<12)
Definition at line 127 of file protocol.h.
U_STEP
#define U_STEP (1u<<5)
Definition at line 118 of file protocol.h.
U_UNUSED29
#define U_UNUSED29 (1u<<29)
future expansion
Definition at line 148 of file protocol.h.
U_UNUSED30
#define U_UNUSED30 (1u<<30)
future expansion
Definition at line 149 of file protocol.h.
U_VIEWMODEL
#define U_VIEWMODEL (1u<<25)
attachs the model to the view (origin and angles become relative to it), only shown to owner, a more powerful alternative to .weaponmodel and such
Definition at line 144 of file protocol.h.
Enumeration Type Documentation
entity_state_active_t
enum entity_state_active_t
Enumerator
ACTIVE_NOT
ACTIVE_NETWORK
ACTIVE_SHARED
Definition at line 431 of file protocol.h.
{
    ACTIVE_NOT = 0,
    ACTIVE_NETWORK = 1,
    ACTIVE_SHARED = 2
}
Function Documentation
EntityFrame4_AckFrame()
int EntityFrame4_AckFrame (entityframe4_database_t * d, int framenum, int servermode)
Definition at line 74 of file com_ents4.c.
{
    int i, j, found;
    entity_database4_commit_t *commit;
    if (framenum == -1)
    {
        // reset reference, but leave commits alone
        d->referenceframenum = -1;
        for (i = 0;i < d->maxreferenceentities;i++)
            d->referenceentity[i] = defaultstate;
        // if this is the server, remove commits
        for (i = 0, commit = d->commit;i < MAX_ENTITY_HISTORY;i++, commit++)
            commit->numentities = 0;
        found = true;
    }
    else if (d->referenceframenum == framenum)
        found = true;
    else
    {
        found = false;
        for (i = 0, commit = d->commit;i < MAX_ENTITY_HISTORY;i++, commit++)
        {
            if (commit->numentities && commit->framenum <= framenum)
            {
                if (commit->framenum == framenum)
                {
                    found = true;
                    d->referenceframenum = framenum;
                    if (developer_networkentities.integer >= 3)
                    {
                        for (j = 0;j < commit->numentities;j++)
{
                            entity_state_t *s = EntityFrame4_GetReferenceEntity(d, commit->entity[j].number);
                            if (commit->entity[j].active != s->active)
{
                                if (commit->entity[j].active == ACTIVE_NETWORK)
                                    Con_Printf("commit entity %i has become active (modelindex %i)\n", commit->entity[j].number, commit->entity[j].modelindex);
                                else
                                    Con_Printf("commit entity %i has become inactive (modelindex %i)\n", commit->entity[j].number, commit->entity[j].modelindex);
                            }
                            *s = commit->entity[j];
                        }
                    }
                    else
                        for (j = 0;j < commit->numentities;j++)
                            *EntityFrame4_GetReferenceEntity(d, commit->entity[j].number) = commit->entity[j];
                }
                commit->numentities = 0;
            }
        }
    }
    if (developer_networkentities.integer >= 1)
    {
        Con_Printf("ack ref:%i database updated to: ref:%i commits:", framenum, d->referenceframenum);
        for (i = 0;i < MAX_ENTITY_HISTORY;i++)
            if (d->commit[i].numentities)
                Con_Printf(" %i", d->commit[i].framenum);
        Con_Print("\n");
    }
    return found;
}
Referenced by EntityFrame4_CL_ReadFrame(), and SV_FrameAck().
EntityFrame4_AddCommitEntity()
void EntityFrame4_AddCommitEntity (entityframe4_database_t * d, const entity_state_t * s)
Definition at line 57 of file com_ents4.c.
{
    // resize commit's entity list if full
    if (d->currentcommit->maxentities <= d->currentcommit->numentities)
    {
        entity_state_t *oldentity = d->currentcommit->entity;
        d->currentcommit->maxentities += 8;
        d->currentcommit->entity = (entity_state_t *)Mem_Alloc(d->mempool, d->currentcommit->maxentities * sizeof(*d->currentcommit->entity));
        if (oldentity)
        {
            memcpy(d->currentcommit->entity, oldentity, d->currentcommit->numentities * sizeof(*d->currentcommit->entity));
            Mem_Free(oldentity);
        }
    }
    d->currentcommit->entity[d->currentcommit->numentities++] = *s;
}
Referenced by EntityFrame4_CL_ReadFrame(), and EntityFrame4_WriteFrame().
EntityFrame4_AllocDatabase()
entityframe4_database_t * EntityFrame4_AllocDatabase (struct mempool_s * pool)
EntityFrame4_CL_ReadFrame()
void EntityFrame4_CL_ReadFrame (void)
Definition at line 4 of file cl_ents4.c.
{
    int i, n, cnumber, referenceframenum, framenum, enumber, done, stopnumber, skip = false;
    entity_state_t *s;
    entityframe4_database_t *d;
    if (!cl.entitydatabase4)
        cl.entitydatabase4 = EntityFrame4_AllocDatabase(cls.levelmempool);
    d = cl.entitydatabase4;
    // read the number of the frame this refers to
    referenceframenum = MSG_ReadLong(&cl_message);
    // read the number of this frame
    framenum = MSG_ReadLong(&cl_message);
    CL_NewFrameReceived(framenum);
    // read the start number
    enumber = (unsigned short) MSG_ReadShort(&cl_message);
    if (developer_networkentities.integer >= 10)
    {
        Con_Printf("recv svc_entities num:%i ref:%i database: ref:%i commits:", framenum, referenceframenum, d->referenceframenum);
        for (i = 0;i < MAX_ENTITY_HISTORY;i++)
            if (d->commit[i].numentities)
                Con_Printf(" %i", d->commit[i].framenum);
        Con_Print("\n");
    }
    if (!EntityFrame4_AckFrame(d, referenceframenum, false))
    {
        Con_Print("EntityFrame4_CL_ReadFrame: reference frame invalid (VERY BAD ERROR), this update will be skipped\n");
        skip = true;
    }
    d->currentcommit = NULL;
    for (i = 0;i < MAX_ENTITY_HISTORY;i++)
    {
        if (!d->commit[i].numentities)
        {
            d->currentcommit = d->commit + i;
            d->currentcommit->framenum = framenum;
            d->currentcommit->numentities = 0;
        }
    }
    if (d->currentcommit == NULL)
    {
        Con_Printf("EntityFrame4_CL_ReadFrame: error while decoding frame %i: database full, reading but not storing this update\n", framenum);
        skip = true;
    }
    done = false;
    while (!done && !cl_message.badread)
    {
        // read the number of the modified entity
        // (gaps will be copied unmodified)
        n = (unsigned short)MSG_ReadShort(&cl_message);
        if (n == 0x8000)
        {
            // no more entities in this update, but we still need to copy the
            // rest of the reference entities (final gap)
            done = true;
            // read end of range number, then process normally
            n = (unsigned short)MSG_ReadShort(&cl_message);
        }
        // high bit means it's a remove message
        cnumber = n & 0x7FFF;
        // if this is a live entity we may need to expand the array
        if (cl.num_entities <= cnumber && !(n & 0x8000))
        {
            cl.num_entities = cnumber + 1;
            if (cnumber >= cl.max_entities)
                CL_ExpandEntities(cnumber);
        }
        // add one (the changed one) if not done
        stopnumber = cnumber + !done;
        // process entities in range from the last one to the changed one
        for (;enumber < stopnumber;enumber++)
        {
            if (skip || enumber >= cl.num_entities)
            {
                if (enumber == cnumber && (n & 0x8000) == 0)
                {
                    entity_state_t tempstate;
                    EntityState_ReadFields(&tempstate, EntityState_ReadExtendBits());
                }
                continue;
            }
            // slide the current into the previous slot
            cl.entities[enumber].state_previous = cl.entities[enumber].state_current;
            // copy a new current from reference database
            cl.entities[enumber].state_current = *EntityFrame4_GetReferenceEntity(d, enumber);
            s = &cl.entities[enumber].state_current;
            // if this is the one to modify, read more data...
            if (enumber == cnumber)
            {
                if (n & 0x8000)
                {
                    // simply removed
                    if (developer_networkentities.integer >= 2)
                        Con_Printf("entity %i: remove\n", enumber);
                    *s = defaultstate;
                }
                else
                {
                    // read the changes
                    if (developer_networkentities.integer >= 2)
                        Con_Printf("entity %i: update\n", enumber);
                    s->active = ACTIVE_NETWORK;
                    EntityState_ReadFields(s, EntityState_ReadExtendBits());
                }
            }
            else if (developer_networkentities.integer >= 4)
                Con_Printf("entity %i: copy\n", enumber);
            // set the cl.entities_active flag
            cl.entities_active[enumber] = (s->active == ACTIVE_NETWORK);
            // set the update time
            s->time = cl.mtime[0];
            // fix the number (it gets wiped occasionally by copying from defaultstate)
            s->number = enumber;
            // check if we need to update the lerp stuff
            if (s->active == ACTIVE_NETWORK)
                CL_MoveLerpEntityStates(&cl.entities[enumber]);
            // add this to the commit entry whether it is modified or not
            if (d->currentcommit)
                EntityFrame4_AddCommitEntity(d, &cl.entities[enumber].state_current);
            // print extra messages if desired
            if (developer_networkentities.integer >= 2 && cl.entities[enumber].state_current.active != cl.entities[enumber].state_previous.active)
            {
                if (cl.entities[enumber].state_current.active == ACTIVE_NETWORK)
                    Con_Printf("entity #%i has become active\n", enumber);
                else if (cl.entities[enumber].state_previous.active)
                    Con_Printf("entity #%i has become inactive\n", enumber);
            }
        }
    }
    d->currentcommit = NULL;
    if (skip)
        EntityFrame4_ResetDatabase(d);
}
Referenced by CL_ParseServerMessage().
EntityFrame4_FreeDatabase()
void EntityFrame4_FreeDatabase (entityframe4_database_t * d)
Definition at line 13 of file com_ents4.c.
{
    int i;
    for (i = 0;i < MAX_ENTITY_HISTORY;i++)
        if (d->commit[i].entity)
            Mem_Free(d->commit[i].entity);
    if (d->referenceentity)
        Mem_Free(d->referenceentity);
    Mem_Free(d);
}
Referenced by SV_DropClient(), and SV_SendServerinfo().
EntityFrame4_GetReferenceEntity()
entity_state_t * EntityFrame4_GetReferenceEntity (entityframe4_database_t * d, int number)
Definition at line 34 of file com_ents4.c.
{
    if (d->maxreferenceentities <= number)
    {
        int oldmax = d->maxreferenceentities;
        entity_state_t *oldentity = d->referenceentity;
        d->maxreferenceentities = (number + 15) & ~7;
        d->referenceentity = (entity_state_t *)Mem_Alloc(d->mempool, d->maxreferenceentities * sizeof(*d->referenceentity));
        if (oldentity)
        {
            memcpy(d->referenceentity, oldentity, oldmax * sizeof(*d->referenceentity));
            Mem_Free(oldentity);
        }
        // clear the newly created entities
        for (;oldmax < d->maxreferenceentities;oldmax++)
        {
            d->referenceentity[oldmax] = defaultstate;
            d->referenceentity[oldmax].number = oldmax;
        }
    }
    return d->referenceentity + number;
}
Referenced by EntityFrame4_AckFrame(), EntityFrame4_CL_ReadFrame(), and EntityFrame4_WriteFrame().
EntityFrame4_ResetDatabase()
void EntityFrame4_ResetDatabase (entityframe4_database_t * d)
Definition at line 24 of file com_ents4.c.
{
    int i;
    d->referenceframenum = -1;
    for (i = 0;i < MAX_ENTITY_HISTORY;i++)
        d->commit[i].numentities = 0;
    for (i = 0;i < d->maxreferenceentities;i++)
        d->referenceentity[i] = defaultstate;
}
Referenced by EntityFrame4_AllocDatabase(), and EntityFrame4_CL_ReadFrame().
EntityFrame4_WriteFrame()
qbool EntityFrame4_WriteFrame (struct sizebuf_s * msg, int maxsize, entityframe4_database_t * d, int numstates, const entity_state_t ** states)
Referenced by SV_WriteEntitiesToClient().
EntityFrame5_AckFrame()
void EntityFrame5_AckFrame (entityframe5_database_t * d, int framenum)
Definition at line 684 of file sv_ents5.c.
{
    int i;
    // scan for packets made obsolete by this ack and delete them
    for (i = 0;i < ENTITYFRAME5_MAXPACKETLOGS;i++)
        if (d->packetlog[i].packetnumber <= framenum)
            d->packetlog[i].packetnumber = 0;
}
Referenced by SV_FrameAck().
EntityFrame5_AllocDatabase()
entityframe5_database_t * EntityFrame5_AllocDatabase (struct mempool_s * pool)
Referenced by SV_SendServerinfo().
EntityFrame5_CL_ReadFrame()
void EntityFrame5_CL_ReadFrame (void)
Definition at line 289 of file cl_ents5.c.
{
    int n, enumber, framenum;
    entity_t *ent;
    entity_state_t *s;
    // read the number of this frame to echo back in next input packet
    framenum = MSG_ReadLong(&cl_message);
    CL_NewFrameReceived(framenum);
    if (cls.protocol != PROTOCOL_QUAKE && cls.protocol != PROTOCOL_QUAKEDP && cls.protocol != PROTOCOL_NEHAHRAMOVIE && cls.protocol != PROTOCOL_DARKPLACES1 && cls.protocol != PROTOCOL_DARKPLACES2 && cls.protocol != PROTOCOL_DARKPLACES3 && cls.protocol != PROTOCOL_DARKPLACES4 && cls.protocol != PROTOCOL_DARKPLACES5 && cls.protocol != PROTOCOL_DARKPLACES6)
        cls.servermovesequence = MSG_ReadLong(&cl_message);
    // read entity numbers until we find a 0x8000
    // (which would be remove world entity, but is actually a terminator)
    while ((n = (unsigned short)MSG_ReadShort(&cl_message)) != 0x8000 && !cl_message.badread)
    {
        // get the entity number
        enumber = n & 0x7FFF;
        // we may need to expand the array
        if (cl.num_entities <= enumber)
        {
            cl.num_entities = enumber + 1;
            if (enumber >= cl.max_entities)
                CL_ExpandEntities(enumber);
        }
        // look up the entity
        ent = cl.entities + enumber;
        // slide the current into the previous slot
        ent->state_previous = ent->state_current;
        // read the update
        s = &ent->state_current;
        if (n & 0x8000)
        {
            // remove entity
            *s = defaultstate;
        }
        else
        {
            // update entity
            EntityState5_ReadUpdate(s, enumber);
        }
        // set the cl.entities_active flag
        cl.entities_active[enumber] = (s->active == ACTIVE_NETWORK);
        // set the update time
        s->time = cl.mtime[0];
        // fix the number (it gets wiped occasionally by copying from defaultstate)
        s->number = enumber;
        // check if we need to update the lerp stuff
        if (s->active == ACTIVE_NETWORK)
            CL_MoveLerpEntityStates(&cl.entities[enumber]);
        // print extra messages if desired
        if (developer_networkentities.integer >= 2 && cl.entities[enumber].state_current.active != cl.entities[enumber].state_previous.active)
        {
            if (cl.entities[enumber].state_current.active == ACTIVE_NETWORK)
                Con_Printf("entity #%i has become active\n", enumber);
            else if (cl.entities[enumber].state_previous.active)
                Con_Printf("entity #%i has become inactive\n", enumber);
        }
    }
}
Referenced by CL_ParseServerMessage().
EntityFrame5_FreeDatabase()
void EntityFrame5_FreeDatabase (entityframe5_database_t * d)
Definition at line 29 of file sv_ents5.c.
{
    // all the [maxedicts] memory is allocated at once, so there's only one
    // thing to free
    if (d->maxedicts)
        Mem_Free(d->deltabits);
    Mem_Free(d);
}
Referenced by SV_DropClient(), and SV_SendServerinfo().
EntityFrame5_LostFrame()
void EntityFrame5_LostFrame (entityframe5_database_t * d, int framenum)
Definition at line 623 of file sv_ents5.c.
{
    int i, j, l, bits;
    entityframe5_changestate_t *s;
    entityframe5_packetlog_t *p;
    static unsigned char statsdeltabits[(MAX_CL_STATS+7)/8];
    static int deltabits[MAX_EDICTS];
    entityframe5_packetlog_t *packetlogs[ENTITYFRAME5_MAXPACKETLOGS];
    for (i = 0, p = d->packetlog;i < ENTITYFRAME5_MAXPACKETLOGS;i++, p++)
        packetlogs[i] = p;
    qsort(packetlogs, sizeof(*packetlogs), ENTITYFRAME5_MAXPACKETLOGS, packetlog5cmp);
    memset(deltabits, 0, sizeof(deltabits));
    memset(statsdeltabits, 0, sizeof(statsdeltabits));
    for (i = 0; i < ENTITYFRAME5_MAXPACKETLOGS; i++)
    {
        p = packetlogs[i];
        if (!p->packetnumber)
            continue;
        if (p->packetnumber <= framenum)
        {
            for (j = 0, s = p->states;j < p->numstates;j++, s++)
                deltabits[s->number] |= s->bits;
            for (l = 0;l < (MAX_CL_STATS+7)/8;l++)
                statsdeltabits[l] |= p->statsdeltabits[l];
            p->packetnumber = 0;
        }
        else
        {
            for (j = 0, s = p->states;j < p->numstates;j++, s++)
                deltabits[s->number] &= ~s->bits;
            for (l = 0;l < (MAX_CL_STATS+7)/8;l++)
                statsdeltabits[l] &= ~p->statsdeltabits[l];
        }
    }
    for(i = 0; i < d->maxedicts; ++i)
    {
        bits = deltabits[i] & ~d->deltabits[i];
        if(bits)
        {
            d->deltabits[i] |= bits;
            // if it was a very important update, set priority higher
            if (bits & (E5_FULLUPDATE | E5_ATTACHMENT | E5_MODEL | E5_COLORMAP))
                d->priorities[i] = max(d->priorities[i], 4);
            else
                d->priorities[i] = max(d->priorities[i], 1);
        }
    }
    for (l = 0;l < (MAX_CL_STATS+7)/8;l++)
        host_client->statsdeltabits[l] |= statsdeltabits[l];
        // no need to mask out the already-set bits here, as we do not
        // do that priorities stuff
}
Referenced by EntityFrame5_WriteFrame(), and SV_FrameLost().
EntityFrame5_WriteFrame()
qbool EntityFrame5_WriteFrame (struct sizebuf_s * msg, int maxsize, entityframe5_database_t * d, int numstates, const entity_state_t ** states, int viewentnum, unsigned int movesequence, qbool need_empty)
Referenced by SV_WriteEntitiesToClient().
EntityFrame_AckFrame()
void EntityFrame_AckFrame (entityframe_database_t * d, int frame)
Definition at line 35 of file com_ents.c.
{
    int i;
    d->ackframenum = frame;
    for (i = 0;i < d->numframes && d->frames[i].framenum < frame;i++);
    // ignore outdated frame acks (out of order packets)
    if (i == 0)
        return;
    d->numframes -= i;
    // if some queue is left, slide it down to beginning of array
    if (d->numframes)
        memmove(&d->frames[0], &d->frames[i], sizeof(d->frames[0]) * d->numframes);
}
Referenced by EntityFrame_CL_ReadFrame(), and SV_FrameAck().
EntityFrame_AddFrame_Client()
void EntityFrame_AddFrame_Client (entityframe_database_t * d, vec3_t eye, int framenum, int numentities, const entity_state_t * entitydata)
Definition at line 168 of file cl_ents.c.
{
    int n, e;
    entity_frameinfo_t *info;
    VectorCopy(eye, d->eye);
    // figure out how many entity slots are used already
    if (d->numframes)
    {
        n = d->frames[d->numframes - 1].endentity - d->frames[0].firstentity;
        if (n + numentities > MAX_ENTITY_DATABASE || d->numframes >= MAX_ENTITY_HISTORY)
        {
            // ran out of room, dump database
            EntityFrame_ClearDatabase(d);
        }
    }
    info = &d->frames[d->numframes];
    info->framenum = framenum;
    e = -1000;
    // make sure we check the newly added frame as well, but we haven't incremented numframes yet
    for (n = 0;n <= d->numframes;n++)
    {
        if (e >= d->frames[n].framenum)
        {
            if (e == framenum)
                Con_Print("EntityFrame_AddFrame: tried to add out of sequence frame to database\n");
            else
                Con_Print("EntityFrame_AddFrame: out of sequence frames in database\n");
            return;
        }
        e = d->frames[n].framenum;
    }
    // if database still has frames after that...
    if (d->numframes)
        info->firstentity = d->frames[d->numframes - 1].endentity;
    else
        info->firstentity = 0;
    info->endentity = info->firstentity + numentities;
    d->numframes++;
    n = info->firstentity % MAX_ENTITY_DATABASE;
    e = MAX_ENTITY_DATABASE - n;
    if (e > numentities)
        e = numentities;
    memcpy(d->entitydata + n, entitydata, sizeof(entity_state_t) * e);
    if (numentities > e)
        memcpy(d->entitydata, entitydata + e, sizeof(entity_state_t) * (numentities - e));
}
Referenced by EntityFrame_CL_ReadFrame().
EntityFrame_AddFrame_Server()
void EntityFrame_AddFrame_Server (entityframe_database_t * d, vec3_t eye, int framenum, int numentities, const entity_state_t ** entitydata)
Definition at line 216 of file sv_ents.c.
{
    int n, e;
    entity_frameinfo_t *info;
    VectorCopy(eye, d->eye);
    // figure out how many entity slots are used already
    if (d->numframes)
    {
        n = d->frames[d->numframes - 1].endentity - d->frames[0].firstentity;
        if (n + numentities > MAX_ENTITY_DATABASE || d->numframes >= MAX_ENTITY_HISTORY)
        {
            // ran out of room, dump database
            EntityFrame_ClearDatabase(d);
        }
    }
    info = &d->frames[d->numframes];
    info->framenum = framenum;
    e = -1000;
    // make sure we check the newly added frame as well, but we haven't incremented numframes yet
    for (n = 0;n <= d->numframes;n++)
    {
        if (e >= d->frames[n].framenum)
        {
            if (e == framenum)
                Con_Print("EntityFrame_AddFrame: tried to add out of sequence frame to database\n");
            else
                Con_Print("EntityFrame_AddFrame: out of sequence frames in database\n");
            return;
        }
        e = d->frames[n].framenum;
    }
    // if database still has frames after that...
    if (d->numframes)
        info->firstentity = d->frames[d->numframes - 1].endentity;
    else
        info->firstentity = 0;
    info->endentity = info->firstentity + numentities;
    d->numframes++;
    n = info->firstentity % MAX_ENTITY_DATABASE;
    e = MAX_ENTITY_DATABASE - n;
    if (e > numentities)
        e = numentities;
    memcpy(d->entitydata + n, entitydata, sizeof(entity_state_t) * e);
    if (numentities > e)
        memcpy(d->entitydata, entitydata + e, sizeof(entity_state_t) * (numentities - e));
}
Referenced by EntityFrame_WriteFrame().
EntityFrame_AllocDatabase()
entityframe_database_t * EntityFrame_AllocDatabase (struct mempool_s * mempool)
EntityFrame_CL_ReadFrame()
void EntityFrame_CL_ReadFrame (void)
Definition at line 220 of file cl_ents.c.
{
    int i, number, removed;
    entity_frame_t *f, *delta;
    entity_state_t *e, *old, *oldend;
    entity_t *ent;
    entityframe_database_t *d;
    if (!cl.entitydatabase)
        cl.entitydatabase = EntityFrame_AllocDatabase(cls.levelmempool);
    d = cl.entitydatabase;
    f = &d->framedata;
    delta = &d->deltaframe;
    EntityFrame_Clear(f, NULL, -1);
    // read the frame header info
    f->time = cl.mtime[0];
    number = MSG_ReadLong(&cl_message);
    f->framenum = MSG_ReadLong(&cl_message);
    CL_NewFrameReceived(f->framenum);
    f->eye[0] = MSG_ReadFloat(&cl_message);
    f->eye[1] = MSG_ReadFloat(&cl_message);
    f->eye[2] = MSG_ReadFloat(&cl_message);
    EntityFrame_AckFrame(d, number);
    EntityFrame_FetchFrame(d, number, delta);
    old = delta->entitydata;
    oldend = old + delta->numentities;
    // read entities until we hit the magic 0xFFFF end tag
    while ((number = (unsigned short) MSG_ReadShort(&cl_message)) != 0xFFFF && !cl_message.badread)
    {
        if (cl_message.badread)
            Host_Error("EntityFrame_Read: read error");
        removed = number & 0x8000;
        number &= 0x7FFF;
        if (number >= MAX_EDICTS)
            Host_Error("EntityFrame_Read: number (%i) >= MAX_EDICTS (%i)", number, MAX_EDICTS);
        // seek to entity, while copying any skipped entities (assume unchanged)
        while (old < oldend && old->number < number)
        {
            if (f->numentities >= MAX_ENTITY_DATABASE)
                Host_Error("EntityFrame_Read: entity list too big");
            f->entitydata[f->numentities] = *old++;
            f->entitydata[f->numentities++].time = cl.mtime[0];
        }
        if (removed)
        {
            if (old < oldend && old->number == number)
                old++;
            else
                Con_Printf("EntityFrame_Read: REMOVE on unused entity %i\n", number);
        }
        else
        {
            if (f->numentities >= MAX_ENTITY_DATABASE)
                Host_Error("EntityFrame_Read: entity list too big");
            // reserve this slot
            e = f->entitydata + f->numentities++;
            if (old < oldend && old->number == number)
            {
                // delta from old entity
                *e = *old++;
            }
            else
            {
                // delta from defaults
                *e = defaultstate;
            }
            if (cl.num_entities <= number)
            {
                cl.num_entities = number + 1;
                if (number >= cl.max_entities)
                    CL_ExpandEntities(number);
            }
            cl.entities_active[number] = true;
            e->active = ACTIVE_NETWORK;
            e->time = cl.mtime[0];
            e->number = number;
            EntityState_ReadFields(e, EntityState_ReadExtendBits());
        }
    }
    while (old < oldend)
    {
        if (f->numentities >= MAX_ENTITY_DATABASE)
            Host_Error("EntityFrame_Read: entity list too big");
        f->entitydata[f->numentities] = *old++;
        f->entitydata[f->numentities++].time = cl.mtime[0];
    }
    EntityFrame_AddFrame_Client(d, f->eye, f->framenum, f->numentities, f->entitydata);
    memset(cl.entities_active, 0, cl.num_entities * sizeof(unsigned char));
    number = 1;
    for (i = 0;i < f->numentities;i++)
    {
        for (;number < f->entitydata[i].number && number < cl.num_entities;number++)
        {
            if (cl.entities_active[number])
            {
                cl.entities_active[number] = false;
                cl.entities[number].state_current.active = ACTIVE_NOT;
            }
        }
        if (number >= cl.num_entities)
            break;
        // update the entity
        ent = &cl.entities[number];
        ent->state_previous = ent->state_current;
        ent->state_current = f->entitydata[i];
        CL_MoveLerpEntityStates(ent);
        // the entity lives again...
        cl.entities_active[number] = true;
        number++;
    }
    for (;number < cl.num_entities;number++)
    {
        if (cl.entities_active[number])
        {
            cl.entities_active[number] = false;
            cl.entities[number].state_current.active = ACTIVE_NOT;
        }
    }
}
Referenced by CL_ParseServerMessage().
EntityFrame_Clear()
void EntityFrame_Clear (entity_frame_t * f, vec3_t eye, int framenum)
Definition at line 23 of file com_ents.c.
{
    f->time = 0;
    f->framenum = framenum;
    f->numentities = 0;
    if (eye == NULL)
        VectorClear(f->eye);
    else
        VectorCopy(eye, f->eye);
}
Referenced by EntityFrame_CL_ReadFrame(), and EntityFrame_FetchFrame().
EntityFrame_ClearDatabase()
void EntityFrame_ClearDatabase (entityframe_database_t * d)
Definition at line 17 of file com_ents.c.
{
    memset(d, 0, sizeof(*d));
}
Referenced by EntityFrame_AddFrame_Client(), and EntityFrame_AddFrame_Server().
EntityFrame_FetchFrame()
void EntityFrame_FetchFrame (entityframe_database_t * d, int framenum, entity_frame_t * f)
Definition at line 50 of file com_ents.c.
{
    int i, n;
    EntityFrame_Clear(f, NULL, -1);
    for (i = 0;i < d->numframes && d->frames[i].framenum < framenum;i++);
    if (i < d->numframes && framenum == d->frames[i].framenum)
    {
        f->framenum = framenum;
        f->numentities = d->frames[i].endentity - d->frames[i].firstentity;
        n = MAX_ENTITY_DATABASE - (d->frames[i].firstentity % MAX_ENTITY_DATABASE);
        if (n > f->numentities)
            n = f->numentities;
        memcpy(f->entitydata, d->entitydata + d->frames[i].firstentity % MAX_ENTITY_DATABASE, sizeof(*f->entitydata) * n);
        if (f->numentities > n)
            memcpy(f->entitydata + n, d->entitydata, sizeof(*f->entitydata) * (f->numentities - n));
        VectorCopy(d->eye, f->eye);
    }
}
Referenced by EntityFrame_CL_ReadFrame(), and EntityFrame_WriteFrame().
EntityFrame_FreeDatabase()
void EntityFrame_FreeDatabase (entityframe_database_t * d)
Definition at line 11 of file com_ents.c.
{
    Mem_Free(d);
}
Referenced by SV_DropClient(), and SV_SendServerinfo().
EntityFrame_MostRecentlyRecievedFrameNum()
int EntityFrame_MostRecentlyRecievedFrameNum (entityframe_database_t * d)
Definition at line 348 of file cl_ents.c.
{
    if (d->numframes)
        return d->frames[d->numframes - 1].framenum;
    else
        return -1;
}
EntityFrame_WriteFrame()
qbool EntityFrame_WriteFrame (struct sizebuf_s * msg, int maxsize, entityframe_database_t * d, int numstates, const entity_state_t ** states, int viewentnum)
EntityFrameCSQC_LostFrame()
void EntityFrameCSQC_LostFrame (struct client_s * client, int framenum)
Referenced by SV_FrameLost().
EntityFrameCSQC_WriteFrame()
qbool EntityFrameCSQC_WriteFrame (struct sizebuf_s * msg, int maxsize, int numnumbers, const unsigned short * numbers, int framenum)
Referenced by SV_WriteEntitiesToClient().
EntityFrameQuake_ISeeDeadEntities()
void EntityFrameQuake_ISeeDeadEntities (void)
Definition at line 117 of file cl_ents_nq.c.
{
    int num, lastentity;
    if (cl.lastquakeentity == 0)
        return;
    lastentity = cl.lastquakeentity;
    cl.lastquakeentity = 0;
    for (num = 0;num <= lastentity;num++)
    {
        if (cl.isquakeentity[num])
        {
            if (cl.entities_active[num] && cl.entities[num].state_current.time == cl.mtime[0])
            {
                cl.isquakeentity[num] = true;
                cl.lastquakeentity = num;
            }
            else
            {
                cl.isquakeentity[num] = false;
                cl.entities_active[num] = ACTIVE_NOT;
                cl.entities[num].state_current = defaultstate;
                cl.entities[num].state_current.number = num;
            }
        }
    }
}
Referenced by CL_ParseServerMessage().
EntityFrameQuake_ReadEntity()
void EntityFrameQuake_ReadEntity (int bits)
Definition at line 4 of file cl_ents_nq.c.
{
    int num;
    entity_t *ent;
    entity_state_t s;
    if (bits & U_MOREBITS)
        bits |= (MSG_ReadByte(&cl_message)<<8);
    if ((bits & U_EXTEND1) && cls.protocol != PROTOCOL_NEHAHRAMOVIE)
    {
        bits |= MSG_ReadByte(&cl_message) << 16;
        if (bits & U_EXTEND2)
            bits |= MSG_ReadByte(&cl_message) << 24;
    }
    if (bits & U_LONGENTITY)
        num = (unsigned short) MSG_ReadShort(&cl_message);
    else
        num = MSG_ReadByte(&cl_message);
    if (num >= MAX_EDICTS)
        Host_Error("EntityFrameQuake_ReadEntity: entity number (%i) >= MAX_EDICTS (%i)", num, MAX_EDICTS);
    if (num < 1)
        Host_Error("EntityFrameQuake_ReadEntity: invalid entity number (%i)", num);
    if (cl.num_entities <= num)
    {
        cl.num_entities = num + 1;
        if (num >= cl.max_entities)
            CL_ExpandEntities(num);
    }
    ent = cl.entities + num;
    // note: this inherits the 'active' state of the baseline chosen
    // (state_baseline is always active, state_current may not be active if
    // the entity was missing in the last frame)
    if (bits & U_DELTA)
        s = ent->state_current;
    else
    {
        s = ent->state_baseline;
        s.active = ACTIVE_NETWORK;
    }
    cl.isquakeentity[num] = true;
    if (cl.lastquakeentity < num)
        cl.lastquakeentity = num;
    s.number = num;
    s.time = cl.mtime[0];
    s.flags = 0;
    if (bits & U_MODEL)
    {
        if (cls.protocol == PROTOCOL_NEHAHRABJP || cls.protocol == PROTOCOL_NEHAHRABJP2 || cls.protocol == PROTOCOL_NEHAHRABJP3)
                            s.modelindex = (unsigned short) MSG_ReadShort(&cl_message);
        else
                            s.modelindex = (s.modelindex & 0xFF00) | MSG_ReadByte(&cl_message);
    }
    if (bits & U_FRAME)     s.frame = (s.frame & 0xFF00) | MSG_ReadByte(&cl_message);
    if (bits & U_COLORMAP)  s.colormap = MSG_ReadByte(&cl_message);
    if (bits & U_SKIN)      s.skin = MSG_ReadByte(&cl_message);
    if (bits & U_EFFECTS)   s.effects = (s.effects & 0xFF00) | MSG_ReadByte(&cl_message);
    if (bits & U_ORIGIN1)   s.origin[0] = MSG_ReadCoord(&cl_message, cls.protocol);
    if (bits & U_ANGLE1)    s.angles[0] = MSG_ReadAngle(&cl_message, cls.protocol);
    if (bits & U_ORIGIN2)   s.origin[1] = MSG_ReadCoord(&cl_message, cls.protocol);
    if (bits & U_ANGLE2)    s.angles[1] = MSG_ReadAngle(&cl_message, cls.protocol);
    if (bits & U_ORIGIN3)   s.origin[2] = MSG_ReadCoord(&cl_message, cls.protocol);
    if (bits & U_ANGLE3)    s.angles[2] = MSG_ReadAngle(&cl_message, cls.protocol);
    if (bits & U_STEP)      s.flags |= RENDER_STEP;
    if (bits & U_ALPHA)     s.alpha = MSG_ReadByte(&cl_message);
    if (bits & U_SCALE)     s.scale = MSG_ReadByte(&cl_message);
    if (bits & U_EFFECTS2)  s.effects = (s.effects & 0x00FF) | (MSG_ReadByte(&cl_message) << 8);
    if (bits & U_GLOWSIZE)  s.glowsize = MSG_ReadByte(&cl_message);
    if (bits & U_GLOWCOLOR) s.glowcolor = MSG_ReadByte(&cl_message);
    if (bits & U_COLORMOD)  {int c = MSG_ReadByte(&cl_message);s.colormod[0] = (unsigned char)(((c >> 5) & 7) * (32.0f / 7.0f));s.colormod[1] = (unsigned char)(((c >> 2) & 7) * (32.0f / 7.0f));s.colormod[2] = (unsigned char)((c & 3) * (32.0f / 3.0f));}
    if (bits & U_GLOWTRAIL) s.flags |= RENDER_GLOWTRAIL;
    if (bits & U_FRAME2)    s.frame = (s.frame & 0x00FF) | (MSG_ReadByte(&cl_message) << 8);
    if (bits & U_MODEL2)    s.modelindex = (s.modelindex & 0x00FF) | (MSG_ReadByte(&cl_message) << 8);
    if (bits & U_VIEWMODEL) s.flags |= RENDER_VIEWMODEL;
    if (bits & U_EXTERIORMODEL) s.flags |= RENDER_EXTERIORMODEL;
    // LadyHavoc: to allow playback of the Nehahra movie
    if (cls.protocol == PROTOCOL_NEHAHRAMOVIE && (bits & U_EXTEND1))
    {
        // LadyHavoc: evil format
        int i = (int)MSG_ReadFloat(&cl_message);
        int j = (int)(MSG_ReadFloat(&cl_message) * 255.0f);
        if (i == 2)
        {
            i = (int)MSG_ReadFloat(&cl_message);
            if (i)
                s.effects |= EF_FULLBRIGHT;
        }
        if (j < 0)
            s.alpha = 0;
        else if (j == 0 || j >= 255)
            s.alpha = 255;
        else
            s.alpha = j;
    }
    ent->state_previous = ent->state_current;
    ent->state_current = s;
    if (ent->state_current.active == ACTIVE_NETWORK)
    {
        CL_MoveLerpEntityStates(ent);
        cl.entities_active[ent->state_current.number] = true;
    }
    if (cl_message.badread)
        Host_Error("EntityFrameQuake_ReadEntity: read error");
}
Referenced by CL_ParseServerMessage().
EntityFrameQuake_WriteFrame()
qbool EntityFrameQuake_WriteFrame (struct sizebuf_s * msg, int maxsize, int numstates, const entity_state_t ** states)
Referenced by SV_WriteEntitiesToClient().
EntityFrameQW_AllocDatabase()
entityframeqw_database_t * EntityFrameQW_AllocDatabase (struct mempool_s * pool)
EntityFrameQW_CL_ReadFrame()
void EntityFrameQW_CL_ReadFrame (qbool delta)
Definition at line 254 of file cl_ents_qw.c.
{
    qbool invalid = false;
    int number, oldsnapindex, newsnapindex, oldindex, newindex, oldnum, newnum;
    entity_t *ent;
    entityframeqw_database_t *d;
    entityframeqw_snapshot_t *oldsnap, *newsnap;
    if (!cl.entitydatabaseqw)
        cl.entitydatabaseqw = EntityFrameQW_AllocDatabase(cls.levelmempool);
    d = cl.entitydatabaseqw;
    // there is no cls.netcon in demos, so this reading code can't access
    // cls.netcon-> at all...  so cls.qw_incoming_sequence and
    // cls.qw_outgoing_sequence are updated every time the corresponding
    // cls.netcon->qw. variables are updated
    // read the number of this frame to echo back in next input packet
    cl.qw_validsequence = cls.qw_incoming_sequence;
    newsnapindex = cl.qw_validsequence & QW_UPDATE_MASK;
    newsnap = d->snapshot + newsnapindex;
    memset(newsnap, 0, sizeof(*newsnap));
    oldsnap = NULL;
    if (delta)
    {
        number = MSG_ReadByte(&cl_message);
        oldsnapindex = cl.qw_deltasequence[newsnapindex];
        if ((number & QW_UPDATE_MASK) != (oldsnapindex & QW_UPDATE_MASK))
            Con_DPrintf("WARNING: from mismatch\n");
        if (oldsnapindex != -1)
        {
            if (cls.qw_outgoing_sequence - oldsnapindex >= QW_UPDATE_BACKUP-1)
            {
                Con_DPrintf("delta update too old\n");
                newsnap->invalid = invalid = true; // too old
                delta = false;
            }
            oldsnap = d->snapshot + (oldsnapindex & QW_UPDATE_MASK);
        }
        else
            delta = false;
    }
    // if we can't decode this frame properly, report that to the server
    if (invalid)
        cl.qw_validsequence = 0;
    // read entity numbers until we find a 0x0000
    // (which would be an empty update on world entity, but is actually a terminator)
    newsnap->num_entities = 0;
    oldindex = 0;
    for (;;)
    {
        int word = (unsigned short)MSG_ReadShort(&cl_message);
        if (cl_message.badread)
            return; // just return, the main parser will print an error
        newnum = word == 0 ? 512 : (word & 511);
        oldnum = delta ? (oldindex >= oldsnap->num_entities ? 9999 : oldsnap->entities[oldindex].number) : 9999;
        // copy unmodified oldsnap entities
        while (newnum > oldnum) // delta only
        {
            if (developer_networkentities.integer >= 2)
                Con_Printf("copy %i\n", oldnum);
            // copy one of the old entities
            if (newsnap->num_entities >= QW_MAX_PACKET_ENTITIES)
                Host_Error("EntityFrameQW_CL_ReadFrame: newsnap->num_entities == MAX_PACKETENTITIES");
            newsnap->entities[newsnap->num_entities] = oldsnap->entities[oldindex++];
            newsnap->num_entities++;
            oldnum = oldindex >= oldsnap->num_entities ? 9999 : oldsnap->entities[oldindex].number;
        }
        if (word == 0)
            break;
        if (developer_networkentities.integer >= 2)
        {
            if (word & QW_U_REMOVE)
                Con_Printf("remove %i\n", newnum);
            else if (newnum == oldnum)
                Con_Printf("delta %i\n", newnum);
            else
                Con_Printf("baseline %i\n", newnum);
        }
        if (word & QW_U_REMOVE)
        {
            if (newnum != oldnum && !delta && !invalid)
            {
                cl.qw_validsequence = 0;
                Con_Printf(CON_WARN "WARNING: U_REMOVE %i on full update\n", newnum);
            }
        }
        else
        {
            if (newsnap->num_entities >= QW_MAX_PACKET_ENTITIES)
                Host_Error("EntityFrameQW_CL_ReadFrame: newsnap->num_entities == MAX_PACKETENTITIES");
            newsnap->entities[newsnap->num_entities] = (newnum == oldnum) ? oldsnap->entities[oldindex] : cl.entities[newnum].state_baseline;
            EntityStateQW_ReadEntityUpdate(newsnap->entities + newsnap->num_entities, word);
            newsnap->num_entities++;
        }
        if (newnum == oldnum)
            oldindex++;
    }
    // expand cl.num_entities to include every entity we've seen this game
    newnum = newsnap->num_entities ? newsnap->entities[newsnap->num_entities - 1].number : 1;
    if (cl.num_entities <= newnum)
    {
        cl.num_entities = newnum + 1;
        if (cl.max_entities < newnum + 1)
            CL_ExpandEntities(newnum);
    }
    // now update the non-player entities from the snapshot states
    number = cl.maxclients + 1;
    for (newindex = 0;;newindex++)
    {
        newnum = newindex >= newsnap->num_entities ? cl.num_entities : newsnap->entities[newindex].number;
        // kill any missing entities
        for (;number < newnum;number++)
        {
            if (cl.entities_active[number])
            {
                cl.entities_active[number] = false;
                cl.entities[number].state_current.active = ACTIVE_NOT;
            }
        }
        if (number >= cl.num_entities)
            break;
        // update the entity
        ent = &cl.entities[number];
        ent->state_previous = ent->state_current;
        ent->state_current = newsnap->entities[newindex];
        ent->state_current.time = cl.mtime[0];
        CL_MoveLerpEntityStates(ent);
        // the entity lives again...
        cl.entities_active[number] = true;
        number++;
    }
}
Referenced by CL_ParseServerMessage().
EntityFrameQW_FreeDatabase()
void EntityFrameQW_FreeDatabase (entityframeqw_database_t * d)
Definition at line 249 of file cl_ents_qw.c.
{
    Mem_Free(d);
}
EntityState5_DeltaBitsForState()
int EntityState5_DeltaBitsForState (entity_state_t * o, entity_state_t * n)
EntityState5_WriteUpdate()
void EntityState5_WriteUpdate (int number, const entity_state_t * s, int changedbits, struct sizebuf_s * msg)
EntityState_DeltaBits()
int EntityState_DeltaBits (const entity_state_t * o, const entity_state_t * n)
Definition at line 6 of file sv_ents.c.
{
    unsigned int bits;
    // if o is not active, delta from default
    if (o->active != ACTIVE_NETWORK)
        o = &defaultstate;
    bits = 0;
    if (fabs(n->origin[0] - o->origin[0]) > (1.0f / 256.0f))
        bits |= E_ORIGIN1;
    if (fabs(n->origin[1] - o->origin[1]) > (1.0f / 256.0f))
        bits |= E_ORIGIN2;
    if (fabs(n->origin[2] - o->origin[2]) > (1.0f / 256.0f))
        bits |= E_ORIGIN3;
    if ((unsigned char) (n->angles[0] * (256.0f / 360.0f)) != (unsigned char) (o->angles[0] * (256.0f / 360.0f)))
        bits |= E_ANGLE1;
    if ((unsigned char) (n->angles[1] * (256.0f / 360.0f)) != (unsigned char) (o->angles[1] * (256.0f / 360.0f)))
        bits |= E_ANGLE2;
    if ((unsigned char) (n->angles[2] * (256.0f / 360.0f)) != (unsigned char) (o->angles[2] * (256.0f / 360.0f)))
        bits |= E_ANGLE3;
    if ((n->modelindex ^ o->modelindex) & 0x00FF)
        bits |= E_MODEL1;
    if ((n->modelindex ^ o->modelindex) & 0xFF00)
        bits |= E_MODEL2;
    if ((n->frame ^ o->frame) & 0x00FF)
        bits |= E_FRAME1;
    if ((n->frame ^ o->frame) & 0xFF00)
        bits |= E_FRAME2;
    if ((n->effects ^ o->effects) & 0x00FF)
        bits |= E_EFFECTS1;
    if ((n->effects ^ o->effects) & 0xFF00)
        bits |= E_EFFECTS2;
    if (n->colormap != o->colormap)
        bits |= E_COLORMAP;
    if (n->skin != o->skin)
        bits |= E_SKIN;
    if (n->alpha != o->alpha)
        bits |= E_ALPHA;
    if (n->scale != o->scale)
        bits |= E_SCALE;
    if (n->glowsize != o->glowsize)
        bits |= E_GLOWSIZE;
    if (n->glowcolor != o->glowcolor)
        bits |= E_GLOWCOLOR;
    if (n->flags != o->flags)
        bits |= E_FLAGS;
    if (n->tagindex != o->tagindex || n->tagentity != o->tagentity)
        bits |= E_TAGATTACHMENT;
    if (n->light[0] != o->light[0] || n->light[1] != o->light[1] || n->light[2] != o->light[2] || n->light[3] != o->light[3])
        bits |= E_LIGHT;
    if (n->lightstyle != o->lightstyle)
        bits |= E_LIGHTSTYLE;
    if (n->lightpflags != o->lightpflags)
        bits |= E_LIGHTPFLAGS;
    if (bits)
    {
        if (bits &  0xFF000000)
            bits |= 0x00800000;
        if (bits &  0x00FF0000)
            bits |= 0x00008000;
        if (bits &  0x0000FF00)
            bits |= 0x00000080;
    }
    return bits;
}
Referenced by EntityState_WriteUpdate().
EntityState_ReadExtendBits()
int EntityState_ReadExtendBits (void)
Definition at line 4 of file cl_ents.c.
{
    unsigned int bits;
    bits = MSG_ReadByte(&cl_message);
    if (bits & 0x00000080)
    {
        bits |= MSG_ReadByte(&cl_message) << 8;
        if (bits & 0x00008000)
        {
            bits |= MSG_ReadByte(&cl_message) << 16;
            if (bits & 0x00800000)
                bits |= MSG_ReadByte(&cl_message) << 24;
        }
    }
    return bits;
}
Referenced by EntityFrame4_CL_ReadFrame(), and EntityFrame_CL_ReadFrame().
EntityState_ReadFields()
void EntityState_ReadFields (entity_state_t * e, unsigned int bits)
Definition at line 21 of file cl_ents.c.
{
    if (cls.protocol == PROTOCOL_DARKPLACES2)
    {
        if (bits & E_ORIGIN1)
            e->origin[0] = MSG_ReadCoord16i(&cl_message);
        if (bits & E_ORIGIN2)
            e->origin[1] = MSG_ReadCoord16i(&cl_message);
        if (bits & E_ORIGIN3)
            e->origin[2] = MSG_ReadCoord16i(&cl_message);
    }
    else
    {
        if (bits & E_FLAGS)
            e->flags = MSG_ReadByte(&cl_message);
        if (e->flags & RENDER_LOWPRECISION)
        {
            if (bits & E_ORIGIN1)
                e->origin[0] = MSG_ReadCoord16i(&cl_message);
            if (bits & E_ORIGIN2)
                e->origin[1] = MSG_ReadCoord16i(&cl_message);
            if (bits & E_ORIGIN3)
                e->origin[2] = MSG_ReadCoord16i(&cl_message);
        }
        else
        {
            if (bits & E_ORIGIN1)
                e->origin[0] = MSG_ReadCoord32f(&cl_message);
            if (bits & E_ORIGIN2)
                e->origin[1] = MSG_ReadCoord32f(&cl_message);
            if (bits & E_ORIGIN3)
                e->origin[2] = MSG_ReadCoord32f(&cl_message);
        }
    }
    if ((cls.protocol == PROTOCOL_DARKPLACES5 || cls.protocol == PROTOCOL_DARKPLACES6) && !(e->flags & RENDER_LOWPRECISION))
    {
        if (bits & E_ANGLE1)
            e->angles[0] = MSG_ReadAngle16i(&cl_message);
        if (bits & E_ANGLE2)
            e->angles[1] = MSG_ReadAngle16i(&cl_message);
        if (bits & E_ANGLE3)
            e->angles[2] = MSG_ReadAngle16i(&cl_message);
    }
    else
    {
        if (bits & E_ANGLE1)
            e->angles[0] = MSG_ReadAngle8i(&cl_message);
        if (bits & E_ANGLE2)
            e->angles[1] = MSG_ReadAngle8i(&cl_message);
        if (bits & E_ANGLE3)
            e->angles[2] = MSG_ReadAngle8i(&cl_message);
    }
    if (bits & E_MODEL1)
        e->modelindex = (e->modelindex & 0xFF00) | (unsigned int) MSG_ReadByte(&cl_message);
    if (bits & E_MODEL2)
        e->modelindex = (e->modelindex & 0x00FF) | ((unsigned int) MSG_ReadByte(&cl_message) << 8);
    if (bits & E_FRAME1)
        e->frame = (e->frame & 0xFF00) | (unsigned int) MSG_ReadByte(&cl_message);
    if (bits & E_FRAME2)
        e->frame = (e->frame & 0x00FF) | ((unsigned int) MSG_ReadByte(&cl_message) << 8);
    if (bits & E_EFFECTS1)
        e->effects = (e->effects & 0xFF00) | (unsigned int) MSG_ReadByte(&cl_message);
    if (bits & E_EFFECTS2)
        e->effects = (e->effects & 0x00FF) | ((unsigned int) MSG_ReadByte(&cl_message) << 8);
    if (bits & E_COLORMAP)
        e->colormap = MSG_ReadByte(&cl_message);
    if (bits & E_SKIN)
        e->skin = MSG_ReadByte(&cl_message);
    if (bits & E_ALPHA)
        e->alpha = MSG_ReadByte(&cl_message);
    if (bits & E_SCALE)
        e->scale = MSG_ReadByte(&cl_message);
    if (bits & E_GLOWSIZE)
        e->glowsize = MSG_ReadByte(&cl_message);
    if (bits & E_GLOWCOLOR)
        e->glowcolor = MSG_ReadByte(&cl_message);
    if (cls.protocol == PROTOCOL_DARKPLACES2)
        if (bits & E_FLAGS)
            e->flags = MSG_ReadByte(&cl_message);
    if (bits & E_TAGATTACHMENT)
    {
        e->tagentity = (unsigned short) MSG_ReadShort(&cl_message);
        e->tagindex = MSG_ReadByte(&cl_message);
    }
    if (bits & E_LIGHT)
    {
        e->light[0] = (unsigned short) MSG_ReadShort(&cl_message);
        e->light[1] = (unsigned short) MSG_ReadShort(&cl_message);
        e->light[2] = (unsigned short) MSG_ReadShort(&cl_message);
        e->light[3] = (unsigned short) MSG_ReadShort(&cl_message);
    }
    if (bits & E_LIGHTSTYLE)
        e->lightstyle = MSG_ReadByte(&cl_message);
    if (bits & E_LIGHTPFLAGS)
        e->lightpflags = MSG_ReadByte(&cl_message);
    if (developer_networkentities.integer >= 2)
    {
        Con_Printf("ReadFields e%i", e->number);
        if (bits & E_ORIGIN1)
            Con_Printf(" E_ORIGIN1 %f", e->origin[0]);
        if (bits & E_ORIGIN2)
            Con_Printf(" E_ORIGIN2 %f", e->origin[1]);
        if (bits & E_ORIGIN3)
            Con_Printf(" E_ORIGIN3 %f", e->origin[2]);
        if (bits & E_ANGLE1)
            Con_Printf(" E_ANGLE1 %f", e->angles[0]);
        if (bits & E_ANGLE2)
            Con_Printf(" E_ANGLE2 %f", e->angles[1]);
        if (bits & E_ANGLE3)
            Con_Printf(" E_ANGLE3 %f", e->angles[2]);
        if (bits & (E_MODEL1 | E_MODEL2))
            Con_Printf(" E_MODEL %i", e->modelindex);
        if (bits & (E_FRAME1 | E_FRAME2))
            Con_Printf(" E_FRAME %i", e->frame);
        if (bits & (E_EFFECTS1 | E_EFFECTS2))
            Con_Printf(" E_EFFECTS %i", e->effects);
        if (bits & E_ALPHA)
            Con_Printf(" E_ALPHA %f", e->alpha / 255.0f);
        if (bits & E_SCALE)
            Con_Printf(" E_SCALE %f", e->scale / 16.0f);
        if (bits & E_COLORMAP)
            Con_Printf(" E_COLORMAP %i", e->colormap);
        if (bits & E_SKIN)
            Con_Printf(" E_SKIN %i", e->skin);
        if (bits & E_GLOWSIZE)
            Con_Printf(" E_GLOWSIZE %i", e->glowsize * 4);
        if (bits & E_GLOWCOLOR)
            Con_Printf(" E_GLOWCOLOR %i", e->glowcolor);
        if (bits & E_LIGHT)
            Con_Printf(" E_LIGHT %i:%i:%i:%i", e->light[0], e->light[1], e->light[2], e->light[3]);
        if (bits & E_LIGHTPFLAGS)
            Con_Printf(" E_LIGHTPFLAGS %i", e->lightpflags);
        if (bits & E_TAGATTACHMENT)
            Con_Printf(" E_TAGATTACHMENT e%i:%i", e->tagentity, e->tagindex);
        if (bits & E_LIGHTSTYLE)
            Con_Printf(" E_LIGHTSTYLE %i", e->lightstyle);
        Con_Print("\n");
    }
}
Referenced by EntityFrame4_CL_ReadFrame(), and EntityFrame_CL_ReadFrame().
EntityState_WriteExtendBits()
void EntityState_WriteExtendBits (struct sizebuf_s * msg, unsigned int bits)
EntityState_WriteFields()
void EntityState_WriteFields (const entity_state_t * ent, struct sizebuf_s * msg, unsigned int bits)
EntityState_WriteUpdate()
void EntityState_WriteUpdate (const entity_state_t * ent, struct sizebuf_s * msg, const entity_state_t * delta)
Referenced by EntityFrame4_WriteFrame().
EntityStateQW_ReadPlayerUpdate()
void EntityStateQW_ReadPlayerUpdate (void)
Definition at line 46 of file cl_ents_qw.c.
{
    int slot = MSG_ReadByte(&cl_message);
    int enumber = slot + 1;
    int weaponframe;
    int msec;
    int playerflags;
    int bits;
    entity_state_t *s;
    // look up the entity
    entity_t *ent = cl.entities + enumber;
    vec3_t viewangles;
    vec3_t velocity;
    // slide the current state into the previous
    ent->state_previous = ent->state_current;
    // read the update
    s = &ent->state_current;
    *s = defaultstate;
    s->active = ACTIVE_NETWORK;
    s->number = enumber;
    s->colormap = enumber;
    playerflags = MSG_ReadShort(&cl_message);
    MSG_ReadVector(&cl_message, s->origin, cls.protocol);
    s->frame = MSG_ReadByte(&cl_message);
    VectorClear(viewangles);
    VectorClear(velocity);
    if (playerflags & QW_PF_MSEC)
    {
        // time difference between last update this player sent to the server,
        // and last input we sent to the server (this packet is in response to
        // our input, so msec is how long ago the last update of this player
        // entity occurred, compared to our input being received)
        msec = MSG_ReadByte(&cl_message);
    }
    else
        msec = 0;
    if (playerflags & QW_PF_COMMAND)
    {
        bits = MSG_ReadByte(&cl_message);
        if (bits & QW_CM_ANGLE1)
            viewangles[0] = MSG_ReadAngle16i(&cl_message); // cmd->angles[0]
        if (bits & QW_CM_ANGLE2)
            viewangles[1] = MSG_ReadAngle16i(&cl_message); // cmd->angles[1]
        if (bits & QW_CM_ANGLE3)
            viewangles[2] = MSG_ReadAngle16i(&cl_message); // cmd->angles[2]
        if (bits & QW_CM_FORWARD)
            MSG_ReadShort(&cl_message); // cmd->forwardmove
        if (bits & QW_CM_SIDE)
            MSG_ReadShort(&cl_message); // cmd->sidemove
        if (bits & QW_CM_UP)
            MSG_ReadShort(&cl_message); // cmd->upmove
        if (bits & QW_CM_BUTTONS)
            (void) MSG_ReadByte(&cl_message); // cmd->buttons
        if (bits & QW_CM_IMPULSE)
            (void) MSG_ReadByte(&cl_message); // cmd->impulse
        (void) MSG_ReadByte(&cl_message); // cmd->msec
    }
    if (playerflags & QW_PF_VELOCITY1)
        velocity[0] = MSG_ReadShort(&cl_message);
    if (playerflags & QW_PF_VELOCITY2)
        velocity[1] = MSG_ReadShort(&cl_message);
    if (playerflags & QW_PF_VELOCITY3)
        velocity[2] = MSG_ReadShort(&cl_message);
    if (playerflags & QW_PF_MODEL)
        s->modelindex = MSG_ReadByte(&cl_message);
    else
        s->modelindex = cl.qw_modelindex_player;
    if (playerflags & QW_PF_SKINNUM)
        s->skin = MSG_ReadByte(&cl_message);
    if (playerflags & QW_PF_EFFECTS)
        QW_TranslateEffects(s, MSG_ReadByte(&cl_message));
    if (playerflags & QW_PF_WEAPONFRAME)
        weaponframe = MSG_ReadByte(&cl_message);
    else
        weaponframe = 0;
    if (enumber == cl.playerentity)
    {
        // if this is an update on our player, update the angles
        VectorCopy(cl.viewangles, viewangles);
    }
    // calculate the entity angles from the viewangles
    s->angles[0] = viewangles[0] * -0.0333;
    s->angles[1] = viewangles[1];
    s->angles[2] = 0;
    s->angles[2] = Com_CalcRoll(s->angles, velocity, cl_rollangle.value, cl_rollspeed.value)*4;
    // if this is an update on our player, update interpolation state
    if (enumber == cl.playerentity)
    {
        VectorCopy (cl.mpunchangle[0], cl.mpunchangle[1]);
        VectorCopy (cl.mpunchvector[0], cl.mpunchvector[1]);
        VectorCopy (cl.mvelocity[0], cl.mvelocity[1]);
        cl.mviewzoom[1] = cl.mviewzoom[0];
        cl.idealpitch = 0;
        cl.mpunchangle[0][0] = 0;
        cl.mpunchangle[0][1] = 0;
        cl.mpunchangle[0][2] = 0;
        cl.mpunchvector[0][0] = 0;
        cl.mpunchvector[0][1] = 0;
        cl.mpunchvector[0][2] = 0;
        cl.mvelocity[0][0] = 0;
        cl.mvelocity[0][1] = 0;
        cl.mvelocity[0][2] = 0;
        cl.mviewzoom[0] = 1;
        VectorCopy(velocity, cl.mvelocity[0]);
        cl.stats[STAT_WEAPONFRAME] = weaponframe;
        if (playerflags & QW_PF_GIB)
            cl.stats[STAT_VIEWHEIGHT] = 8;
        else if (playerflags & QW_PF_DEAD)
            cl.stats[STAT_VIEWHEIGHT] = -16;
        else
            cl.stats[STAT_VIEWHEIGHT] = 22;
    }
    // set the cl.entities_active flag
    cl.entities_active[enumber] = (s->active == ACTIVE_NETWORK);
    // set the update time
    s->time = cl.mtime[0] - msec * 0.001; // qw has no clock
    // check if we need to update the lerp stuff
    if (s->active == ACTIVE_NETWORK)
        CL_MoveLerpEntityStates(&cl.entities[enumber]);
}
Referenced by CL_ParseServerMessage().
Protocol_EnumForName()
enum protocolversion_e Protocol_EnumForName (const char * s)
Definition at line 68 of file protocol.c.
{
    int i;
    for (i = 0;protocolversioninfo[i].name;i++)
        if (!strcasecmp(s, protocolversioninfo[i].name))
            return protocolversioninfo[i].version;
    return PROTOCOL_UNKNOWN;
}
Referenced by SV_SpawnServer().
Protocol_EnumForNumber()
enum protocolversion_e Protocol_EnumForNumber (int n)
Definition at line 86 of file protocol.c.
{
    int i;
    for (i = 0;protocolversioninfo[i].name;i++)
        if (protocolversioninfo[i].number == n)
            return protocolversioninfo[i].version;
    return PROTOCOL_UNKNOWN;
}
Referenced by CL_ParseServerInfo(), and CL_ParseServerMessage().
Protocol_NameForEnum()
const char * Protocol_NameForEnum (enum protocolversion_e p)
Protocol_Names()
void Protocol_Names (char * buffer, size_t buffersize)
Definition at line 104 of file protocol.c.
{
    int i;
    if (buffersize < 1)
        return;
    buffer[0] = 0;
    for (i = 0;protocolversioninfo[i].name;i++)
    {
        if (i > 0)
            dp_strlcat(buffer, " ", buffersize);
        dp_strlcat(buffer, protocolversioninfo[i].name, buffersize);
    }
}
Referenced by NetConn_ClientParsePacket(), and SV_SpawnServer().
Protocol_NumberForEnum()
int Protocol_NumberForEnum (enum protocolversion_e p)
Protocol_UpdateClientStats()
void Protocol_UpdateClientStats (const int * stats)
Definition at line 118 of file protocol.c.
{
    int i;
    // update the stats array and set deltabits for any changed stats
    for (i = 0;i < MAX_CL_STATS;i++)
    {
        if (host_client->stats[i] != stats[i])
        {
            host_client->statsdeltabits[i >> 3] |= 1 << (i & 7);
            host_client->stats[i] = stats[i];
        }
    }
}
Referenced by SV_SendClientDatagram().
Protocol_WriteStatsReliable()
void Protocol_WriteStatsReliable (void)
Definition at line 151 of file protocol.c.
{
    int i, j;
    if (!host_client->netconnection)
        return;
    // detect changes in stats and write reliable messages
    // this only deals with 32 stats because the older protocols which use
    // this function can only cope with 32 stats,
    // they also do not support svc_updatestatubyte which was introduced in
    // DP6 protocol (except for QW)
    for (j = 0;sendquakestats[j] >= 0;j++)
    {
        i = sendquakestats[j];
        // check if this bit is set
        if (host_client->statsdeltabits[i >> 3] & (1 << (i & 7)))
        {
            host_client->statsdeltabits[i >> 3] -= (1 << (i & 7));
            // send the stat as a byte if possible
            if (sv.protocol == PROTOCOL_QUAKEWORLD)
            {
                if (host_client->stats[i] >= 0 && host_client->stats[i] < 256)
                {
                    MSG_WriteByte(&host_client->netconnection->message, qw_svc_updatestat);
                    MSG_WriteByte(&host_client->netconnection->message, i);
                    MSG_WriteByte(&host_client->netconnection->message, host_client->stats[i]);
                }
                else
                {
                    MSG_WriteByte(&host_client->netconnection->message, qw_svc_updatestatlong);
                    MSG_WriteByte(&host_client->netconnection->message, i);
                    MSG_WriteLong(&host_client->netconnection->message, host_client->stats[i]);
                }
            }
            else
            {
                // this could make use of svc_updatestatubyte in DP6 and later
                // protocols but those protocols do not use this function
                MSG_WriteByte(&host_client->netconnection->message, svc_updatestat);
                MSG_WriteByte(&host_client->netconnection->message, i);
                MSG_WriteLong(&host_client->netconnection->message, host_client->stats[i]);
            }
        }
    }
}
Referenced by SV_WriteEntitiesToClient().
Variable Documentation
defaultstate
entity_state_t defaultstate extern
Definition at line 4 of file protocol.c.
{
    // ! means this is not sent to client
    0,//double time; // ! time this state was built (used on client for interpolation)
    {0,0,0},//float netcenter[3]; // ! for network prioritization, this is the center of the bounding box (which may differ from the origin)
    {0,0,0},//float origin[3];
    {0,0,0},//float angles[3];
    0,//int effects;
    0,//unsigned int customizeentityforclient; // !
    0,//unsigned short number; // entity number this state is for
    0,//unsigned short modelindex;
    0,//unsigned short frame;
    0,//unsigned short tagentity;
    0,//unsigned short specialvisibilityradius; // ! larger if it has effects/light
    0,//unsigned short viewmodelforclient; // !
    0,//unsigned short exteriormodelforclient; // ! not shown if first person viewing from this entity, shown in all other cases
    0,//unsigned short nodrawtoclient; // !
    0,//unsigned short drawonlytoclient; // !
    0,//unsigned short traileffectnum;
    {0,0,0,0},//unsigned short light[4]; // color*256 (0.00 to 255.996), and radius*1
    ACTIVE_NOT,//unsigned char active; // true if a valid state
    0,//unsigned char lightstyle;
    0,//unsigned char lightpflags;
    0,//unsigned char colormap;
    0,//unsigned char skin; // also chooses cubemap for rtlights if lightpflags & LIGHTPFLAGS_FULLDYNAMIC
    255,//unsigned char alpha;
    16,//unsigned char scale;
    0,//unsigned char glowsize;
    254,//unsigned char glowcolor;
    0,//unsigned char flags;
    0,//unsigned char internaleffects; // INTEF_FLAG1QW and so on
    0,//unsigned char tagindex;
    {32, 32, 32},//unsigned char colormod[3];
    {32, 32, 32},//unsigned char glowmod[3];
};
Referenced by CL_ClearState(), CL_ExpandEntities(), CL_ParseBaseline(), CL_UpdateViewModel(), EntityFrame4_AckFrame(), EntityFrame4_CL_ReadFrame(), EntityFrame4_GetReferenceEntity(), EntityFrame4_ResetDatabase(), EntityFrame4_WriteFrame(), EntityFrame5_AllocDatabase(), EntityFrame5_CL_ReadFrame(), EntityFrame5_WriteFrame(), EntityFrame_CL_ReadFrame(), EntityFrame_WriteFrame(), EntityFrameQuake_ISeeDeadEntities(), EntityState5_ReadUpdate(), EntityState_DeltaBits(), EntityStateQW_ReadPlayerUpdate(), SV_CreateBaseline(), and SV_PrepareEntityForSending().
developer_networkentities
struct cvar_s developer_networkentities extern
Definition at line 173 of file cl_parse.c.
{CF_CLIENT, "developer_networkentities", "0", "prints received entities, value is 0-10 (higher for more info, 10 being the most verbose)"};
Referenced by CL_NewFrameReceived(), CL_Parse_Init(), CL_SendMove(), EntityFrame4_AckFrame(), EntityFrame4_CL_ReadFrame(), EntityFrame4_WriteFrame(), EntityFrame5_CL_ReadFrame(), EntityFrame5_WriteFrame(), EntityFrameQW_CL_ReadFrame(), EntityState5_ReadUpdate(), EntityState_ReadFields(), EntityStateQW_ReadEntityUpdate(), and SV_ReadClientMessage().