DarkPlaces: r_explosion.c File Reference
r_explosion.c File Reference
#include "quakedef.h"
#include "cl_collision.h"
Data Structures
struct explosion_t
Macros
#define EXPLOSIONGRID 8
#define EXPLOSIONVERTS ((EXPLOSIONGRID+1)*(EXPLOSIONGRID+1))
#define EXPLOSIONTRIS (EXPLOSIONGRID*EXPLOSIONGRID*2)
Functions
static void r_explosion_start (void)
static void r_explosion_shutdown (void)
static void r_explosion_newmap (void)
static int R_ExplosionVert (int column, int row)
void R_Explosion_Init (void)
void R_NewExplosion (const vec3_t org)
static void R_DrawExplosion_TransparentCallback (const entity_render_t *ent, const rtlight_t *rtlight, int numsurfaces, int *surfacelist)
static void R_MoveExplosion (explosion_t *e)
void R_DrawExplosions (void)
Variables
static int numexplosions = 0
static float explosiontexcoord2f [EXPLOSIONVERTS][2]
static unsigned short explosiontris [EXPLOSIONTRIS][3]
static int explosionnoiseindex [EXPLOSIONVERTS]
static vec3_t explosionpoint [EXPLOSIONVERTS]
static explosion_t explosion [MAX_EXPLOSIONS]
static rtexture_t * explosiontexture
static rtexturepool_t * explosiontexturepool
cvar_t r_explosionclip = {CF_CLIENT | CF_ARCHIVE, "r_explosionclip", "1", "enables collision detection for explosion shell (so that it flattens against walls and floors)"}
static cvar_t r_drawexplosions = {CF_CLIENT, "r_drawexplosions", "1", "enables rendering of explosion shells (see also cl_particles_explosions_shell)"}
Macro Definition Documentation
EXPLOSIONGRID
#define EXPLOSIONGRID 8
Definition at line 25 of file r_explosion.c.
EXPLOSIONTRIS
#define EXPLOSIONTRIS (EXPLOSIONGRID*EXPLOSIONGRID*2)
Definition at line 27 of file r_explosion.c.
EXPLOSIONVERTS
#define EXPLOSIONVERTS ((EXPLOSIONGRID+1)*(EXPLOSIONGRID+1))
Definition at line 26 of file r_explosion.c.
Function Documentation
R_DrawExplosion_TransparentCallback()
static void R_DrawExplosion_TransparentCallback (const entity_render_t * ent, const rtlight_t * rtlight, int numsurfaces, int * surfacelist) static
Definition at line 203 of file r_explosion.c.
{
    int surfacelistindex = 0;
    const int numtriangles = EXPLOSIONTRIS, numverts = EXPLOSIONVERTS;
    GL_BlendFunc(GL_SRC_ALPHA, GL_ONE);
    GL_DepthMask(false);
    GL_DepthRange(0, 1);
    GL_PolygonOffset(r_refdef.polygonfactor, r_refdef.polygonoffset);
    GL_DepthTest(true);
    GL_CullFace(r_refdef.view.cullface_back);
    R_EntityMatrix(&identitymatrix);
//  R_Mesh_ResetTextureState();
    R_SetupShader_Generic(explosiontexture, false, false, false);
    for (surfacelistindex = 0;surfacelistindex < numsurfaces;surfacelistindex++)
    {
        const explosion_t *e = explosion + surfacelist[surfacelistindex];
        // FIXME: this can't properly handle r_refdef.view.colorscale > 1
        GL_Color(e->alpha * r_refdef.view.colorscale, e->alpha * r_refdef.view.colorscale, e->alpha * r_refdef.view.colorscale, 1);
        R_Mesh_PrepareVertices_Generic_Arrays(numverts, e->vert[0], NULL, explosiontexcoord2f[0]);
        R_Mesh_Draw(0, numverts, 0, numtriangles, NULL, NULL, 0, explosiontris[0], NULL, 0);
    }
}
Referenced by R_DrawExplosions().
R_DrawExplosions()
void R_DrawExplosions (void)
Definition at line 264 of file r_explosion.c.
{
#ifdef MAX_EXPLOSIONS
    int i;
    if (!r_drawexplosions.integer)
        return;
    for (i = 0;i < numexplosions;i++)
    {
        if (explosion[i].alpha)
        {
            R_MoveExplosion(&explosion[i]);
            if (explosion[i].alpha)
                R_MeshQueue_AddTransparent(TRANSPARENTSORT_DISTANCE, explosion[i].origin, R_DrawExplosion_TransparentCallback, NULL, i, NULL);
        }
    }
    while (numexplosions > 0 && explosion[i-1].alpha <= 0)
        numexplosions--;
#endif
}
Referenced by R_RenderScene().
R_Explosion_Init()
void R_Explosion_Init (void)
Definition at line 131 of file r_explosion.c.
{
#ifdef MAX_EXPLOSIONS
    int i, x, y;
    i = 0;
    for (y = 0;y < EXPLOSIONGRID;y++)
    {
        for (x = 0;x < EXPLOSIONGRID;x++)
        {
            explosiontris[i][0] = R_ExplosionVert(x    , y    );
            explosiontris[i][1] = R_ExplosionVert(x + 1, y    );
            explosiontris[i][2] = R_ExplosionVert(x    , y + 1);
            i++;
            explosiontris[i][0] = R_ExplosionVert(x + 1, y    );
            explosiontris[i][1] = R_ExplosionVert(x + 1, y + 1);
            explosiontris[i][2] = R_ExplosionVert(x    , y + 1);
            i++;
        }
    }
#endif
    Cvar_RegisterVariable(&r_explosionclip);
#ifdef MAX_EXPLOSIONS
    Cvar_RegisterVariable(&r_drawexplosions);
    R_RegisterModule("R_Explosions", r_explosion_start, r_explosion_shutdown, r_explosion_newmap, NULL, NULL);
#endif
}
Referenced by Render_Init().
r_explosion_newmap()
static void r_explosion_newmap (void) static
Definition at line 105 of file r_explosion.c.
{
    numexplosions = 0;
    memset(explosion, 0, sizeof(explosion));
}
Referenced by R_Explosion_Init().
r_explosion_shutdown()
static void r_explosion_shutdown (void) static
Definition at line 100 of file r_explosion.c.
{
    R_FreeTexturePool(&explosiontexturepool);
}
Referenced by R_Explosion_Init().
r_explosion_start()
static void r_explosion_start (void) static
Definition at line 63 of file r_explosion.c.
{
    int x, y;
    static unsigned char noise1[128][128], noise2[128][128], noise3[128][128], data[128][128][4];
    explosiontexturepool = R_AllocTexturePool();
    explosiontexture = NULL;
    //explosiontexturefog = NULL;
    fractalnoise(&noise1[0][0], 128, 32);
    fractalnoise(&noise2[0][0], 128, 4);
    fractalnoise(&noise3[0][0], 128, 4);
    for (y = 0;y < 128;y++)
    {
        for (x = 0;x < 128;x++)
        {
            int j, r, g, b, a;
            j = (noise1[y][x] * noise2[y][x]) * 3 / 256 - 128;
            r = (j * 512) / 256;
            g = (j * 256) / 256;
            b = (j * 128) / 256;
            a = noise3[y][x] * 3 - 128;
            data[y][x][2] = bound(0, r, 255);
            data[y][x][1] = bound(0, g, 255);
            data[y][x][0] = bound(0, b, 255);
            data[y][x][3] = bound(0, a, 255);
        }
    }
    explosiontexture = R_LoadTexture2D(explosiontexturepool, "explosiontexture", 128, 128, &data[0][0][0], TEXTYPE_BGRA, TEXF_MIPMAP | TEXF_ALPHA | TEXF_FORCELINEAR, -1, NULL);
//  if (r_loadfog)
//  {
//      for (y = 0;y < 128;y++)
//          for (x = 0;x < 128;x++)
//              data[y][x][0] = data[y][x][1] = data[y][x][2] = 255;
//      explosiontexturefog = R_LoadTexture2D(explosiontexturepool, "explosiontexture_fog", 128, 128, &data[0][0][0], TEXTYPE_BGRA, TEXF_MIPMAP | TEXF_ALPHA | TEXF_FORCELINEAR, NULL);
//  }
    // note that explosions survive the restart
}
Referenced by R_Explosion_Init().
R_ExplosionVert()
static int R_ExplosionVert (int column, int row) static
Definition at line 111 of file r_explosion.c.
{
    int i;
    float yaw, pitch;
    // top and bottom rows are all one position...
    if (row == 0 || row == EXPLOSIONGRID)
        column = 0;
    i = row * (EXPLOSIONGRID + 1) + column;
    yaw = ((double) column / EXPLOSIONGRID) * M_PI * 2;
    pitch = (((double) row / EXPLOSIONGRID) - 0.5) * M_PI;
    explosionpoint[i][0] = cos(yaw) *  cos(pitch);
    explosionpoint[i][1] = sin(yaw) *  cos(pitch);
    explosionpoint[i][2] =        1 * -sin(pitch);
    explosiontexcoord2f[i][0] = (float) column / (float) EXPLOSIONGRID;
    explosiontexcoord2f[i][1] = (float) row / (float) EXPLOSIONGRID;
    explosionnoiseindex[i] = (row % EXPLOSIONGRID) * EXPLOSIONGRID + (column % EXPLOSIONGRID);
    return i;
}
Referenced by R_Explosion_Init().
R_MoveExplosion()
static void R_MoveExplosion (explosion_t * e) static
Definition at line 227 of file r_explosion.c.
{
    int i;
    float dot, end[3], frametime;
    trace_t trace;
    frametime = cl.time - e->time;
    e->time = cl.time;
    e->alpha = e->alpha - (e->fade * frametime);
    if (e->alpha < 0 || cl.time > e->endtime)
    {
        e->alpha = 0;
        return;
    }
    for (i = 0;i < EXPLOSIONVERTS;i++)
    {
        if (e->vertvel[i][0] || e->vertvel[i][1] || e->vertvel[i][2])
        {
            VectorMA(e->vert[i], frametime, e->vertvel[i], end);
            if (e->clipping)
            {
                trace = CL_TraceLine(e->vert[i], end, MOVE_NOMONSTERS, NULL, SUPERCONTENTS_SOLID, 0, 0, collision_extendmovelength.value, true, false, NULL, false, false);
                if (trace.fraction < 1)
                {
                    // clip velocity against the wall
                    dot = -DotProduct(e->vertvel[i], trace.plane.normal);
                    VectorMA(e->vertvel[i], dot, trace.plane.normal, e->vertvel[i]);
                }
                VectorCopy(trace.endpos, e->vert[i]);
            }
            else
                VectorCopy(end, e->vert[i]);
        }
    }
}
Referenced by R_DrawExplosions().
R_NewExplosion()
void R_NewExplosion (const vec3_t org)
Definition at line 160 of file r_explosion.c.
{
#ifdef MAX_EXPLOSIONS
    int i, j;
    float dist, n;
    explosion_t *e;
    trace_t trace;
    unsigned char noise[EXPLOSIONGRID*EXPLOSIONGRID];
    fractalnoisequick(noise, EXPLOSIONGRID, 4); // adjust noise grid size according to explosion
    for (i = 0, e = explosion;i < MAX_EXPLOSIONS;i++, e++)
    {
        if (!e->alpha)
        {
            numexplosions = max(numexplosions, i + 1);
            e->starttime = cl.time;
            e->endtime = cl.time + cl_explosions_lifetime.value;
            e->time = e->starttime;
            e->alpha = cl_explosions_alpha_start.value;
            e->fade = (cl_explosions_alpha_start.value - cl_explosions_alpha_end.value) / cl_explosions_lifetime.value;
            e->clipping = r_explosionclip.integer != 0;
            VectorCopy(org, e->origin);
            for (j = 0;j < EXPLOSIONVERTS;j++)
            {
                // calculate start origin and velocity
                n = noise[explosionnoiseindex[j]] * (1.0f / 255.0f) + 0.5;
                dist = n * cl_explosions_size_start.value;
                VectorMA(e->origin, dist, explosionpoint[j], e->vert[j]);
                dist = n * (cl_explosions_size_end.value - cl_explosions_size_start.value) / cl_explosions_lifetime.value;
                VectorScale(explosionpoint[j], dist, e->vertvel[j]);
                // clip start origin
                if (e->clipping)
                {
                    trace = CL_TraceLine(e->origin, e->vert[j], MOVE_NOMONSTERS, NULL, SUPERCONTENTS_SOLID, 0, 0, collision_extendmovelength.value, true, false, NULL, false, false);
                    VectorCopy(trace.endpos, e->vert[i]);
                }
            }
            break;
        }
    }
#endif
}
Referenced by CL_ParticleExplosion().
Variable Documentation
explosion
explosion_t explosion[MAX_EXPLOSIONS] static
Definition at line 50 of file r_explosion.c.
Referenced by R_DrawExplosion_TransparentCallback(), R_DrawExplosions(), r_explosion_newmap(), and R_NewExplosion().
explosionnoiseindex
int explosionnoiseindex[EXPLOSIONVERTS] static
Definition at line 33 of file r_explosion.c.
Referenced by R_ExplosionVert(), and R_NewExplosion().
explosionpoint
vec3_t explosionpoint[EXPLOSIONVERTS] static
Definition at line 34 of file r_explosion.c.
Referenced by R_ExplosionVert(), and R_NewExplosion().
explosiontexcoord2f
float explosiontexcoord2f[EXPLOSIONVERTS][2] static
Definition at line 31 of file r_explosion.c.
Referenced by R_DrawExplosion_TransparentCallback(), and R_ExplosionVert().
explosiontexture
rtexture_t* explosiontexture static
Definition at line 52 of file r_explosion.c.
Referenced by R_DrawExplosion_TransparentCallback(), and r_explosion_start().
explosiontexturepool
rtexturepool_t* explosiontexturepool static
Definition at line 55 of file r_explosion.c.
Referenced by r_explosion_shutdown(), and r_explosion_start().
explosiontris
unsigned short explosiontris[EXPLOSIONTRIS][3] static
Definition at line 32 of file r_explosion.c.
Referenced by R_DrawExplosion_TransparentCallback(), and R_Explosion_Init().
numexplosions
int numexplosions = 0 static
Definition at line 29 of file r_explosion.c.
Referenced by R_DrawExplosions(), r_explosion_newmap(), and R_NewExplosion().
r_drawexplosions
cvar_t r_drawexplosions = {CF_CLIENT, "r_drawexplosions", "1", "enables rendering of explosion shells (see also cl_particles_explosions_shell)"} static
Definition at line 60 of file r_explosion.c.
{CF_CLIENT, "r_drawexplosions", "1", "enables rendering of explosion shells (see also cl_particles_explosions_shell)"};
Referenced by R_DrawExplosions(), and R_Explosion_Init().
r_explosionclip
cvar_t r_explosionclip = {CF_CLIENT | CF_ARCHIVE, "r_explosionclip", "1", "enables collision detection for explosion shell (so that it flattens against walls and floors)"}
Definition at line 58 of file r_explosion.c.
{CF_CLIENT | CF_ARCHIVE, "r_explosionclip", "1", "enables collision detection for explosion shell (so that it flattens against walls and floors)"};
Referenced by M_Menu_Options_Effects_AdjustSliders(), M_Options_Effects_Draw(), R_Explosion_Init(), and R_NewExplosion().