DarkPlaces: r_modules.c File Reference
r_modules.c File Reference
#include "quakedef.h"
Data Structures
struct rendermodule_t
Macros
#define MAXRENDERMODULES 20
Functions
void R_Modules_Init (void)
void R_RegisterModule (const char *name, void(*start)(void), void(*shutdown)(void), void(*newmap)(void), void(*devicelost)(void), void(*devicerestored)(void))
void R_Modules_Start (void)
void R_Modules_Shutdown (void)
void R_Modules_Restart_f (cmd_state_t *cmd)
void R_Modules_NewMap (void)
void R_Modules_DeviceLost (void)
void R_Modules_DeviceRestored (void)
Variables
rendermodule_t rendermodule [MAXRENDERMODULES]
Macro Definition Documentation
MAXRENDERMODULES
#define MAXRENDERMODULES 20
Definition at line 4 of file r_modules.c.
Function Documentation
R_Modules_DeviceLost()
void R_Modules_DeviceLost (void)
Definition at line 107 of file r_modules.c.
{
    int i;
    for (i = 0;i < MAXRENDERMODULES;i++)
    {
        if (rendermodule[i].name == NULL)
            continue;
        if (!rendermodule[i].active)
            continue;
        if (!rendermodule[i].devicelost)
            continue;
        rendermodule[i].devicelost();
    }
}
R_Modules_DeviceRestored()
void R_Modules_DeviceRestored (void)
Definition at line 123 of file r_modules.c.
{
    int i;
    for (i = 0;i < MAXRENDERMODULES;i++)
    {
        if (rendermodule[i].name == NULL)
            continue;
        if (!rendermodule[i].active)
            continue;
        if (!rendermodule[i].devicerestored)
            continue;
        rendermodule[i].devicerestored();
    }
}
R_Modules_Init()
void R_Modules_Init (void)
Definition at line 20 of file r_modules.c.
{
    Cmd_AddCommand(CF_CLIENT, "r_restart", R_Modules_Restart_f, "restarts renderer");
}
Referenced by CL_Init().
R_Modules_NewMap()
void R_Modules_NewMap (void)
Definition at line 92 of file r_modules.c.
{
    int i;
    R_SkinFrame_PrepareForPurge();
    for (i = 0;i < MAXRENDERMODULES;i++)
    {
        if (rendermodule[i].name == NULL)
            continue;
        if (!rendermodule[i].active)
            continue;
        rendermodule[i].newmap();
    }
    R_SkinFrame_Purge();
}
Referenced by CL_SetupWorldModel().
R_Modules_Restart_f()
void R_Modules_Restart_f (cmd_state_t * cmd)
Definition at line 83 of file r_modules.c.
{
    CL_StartVideo();
    Con_Print("Restarting renderer\n");
    SCR_BeginLoadingPlaque(false);
    R_Modules_Shutdown();
    R_Modules_Start();
}
Referenced by R_Modules_Init().
R_Modules_Shutdown()
void R_Modules_Shutdown (void)
Definition at line 67 of file r_modules.c.
{
    int i;
    // shutdown in reverse
    for (i = MAXRENDERMODULES - 1;i >= 0;i--)
    {
        if (rendermodule[i].name == NULL)
            continue;
        if (!rendermodule[i].active)
            continue;
        Con_DPrintf("Stopping render module \"%s\"\n", rendermodule[i].name);
        rendermodule[i].active = 0;
        rendermodule[i].shutdown();
    }
}
Referenced by CL_Shutdown(), R_Modules_Restart_f(), and VID_Restart_f().
R_Modules_Start()
void R_Modules_Start (void)
Definition at line 49 of file r_modules.c.
{
    int i;
    for (i = 0;i < MAXRENDERMODULES;i++)
    {
        if (rendermodule[i].name == NULL)
            continue;
        if (rendermodule[i].active)
        {
            Con_Printf ("R_Modules_Start: module \"%s\" already active\n", rendermodule[i].name);
            continue;
        }
        Con_DPrintf("Starting render module \"%s\"\n", rendermodule[i].name);
        rendermodule[i].active = 1;
        rendermodule[i].start();
    }
}
Referenced by R_Modules_Restart_f(), VID_Restart_f(), and VID_Start().
R_RegisterModule()
void R_RegisterModule (const char * name, void(*)(void) start, void(*)(void) shutdown, void(*)(void) newmap, void(*)(void) devicelost, void(*)(void) devicerestored)
Definition at line 25 of file r_modules.c.
{
    int i;
    for (i = 0;i < MAXRENDERMODULES;i++)
    {
        if (rendermodule[i].name == NULL)
            break;
        if (!strcmp(name, rendermodule[i].name))
        {
            Con_Printf("R_RegisterModule: module \"%s\" registered twice\n", name);
            return;
        }
    }
    if (i >= MAXRENDERMODULES)
        Sys_Error("R_RegisterModule: ran out of renderer module slots (%i)", MAXRENDERMODULES);
    rendermodule[i].active = 0;
    rendermodule[i].name = name;
    rendermodule[i].start = start;
    rendermodule[i].shutdown = shutdown;
    rendermodule[i].newmap = newmap;
    rendermodule[i].devicelost = devicelost;
    rendermodule[i].devicerestored = devicerestored;
}
Referenced by CL_MeshEntities_Init(), CL_Video_Init(), gl_backend_init(), GL_Draw_Init(), GL_Main_Init(), Mod_RenderInit(), Palette_Init(), R_Explosion_Init(), R_LightningBeams_Init(), R_Particles_Init(), R_Shadow_Init(), R_Sky_Init(), R_Textures_Init(), Sbar_Init(), and VID_Init().
Variable Documentation
rendermodule
rendermodule_t rendermodule[MAXRENDERMODULES]
Definition at line 18 of file r_modules.c.
Referenced by R_Modules_DeviceLost(), R_Modules_DeviceRestored(), R_Modules_NewMap(), R_Modules_Shutdown(), R_Modules_Start(), and R_RegisterModule().