DarkPlaces: sbar.h File Reference
sbar.h File Reference
Macros
#define SBAR_HEIGHT 24
Functions
void Sbar_Init (void)
void Sbar_Draw (void)
called every frame by screen
void Sbar_ShowFPS (void)
void Sbar_ShowFPS_Update (void)
int Sbar_GetSortedPlayerIndex (int index)
void Sbar_SortFrags (void)
void Sbar_DeathmatchOverlay (void)
Variables
int sb_lines
scan lines to draw
struct cvar_s sbar_alpha_bg
struct cvar_s sbar_alpha_fg
cvar_t cl_deathscoreboard
Macro Definition Documentation
SBAR_HEIGHT
#define SBAR_HEIGHT 24
Definition at line 24 of file sbar.h.
Function Documentation
Sbar_DeathmatchOverlay()
void Sbar_DeathmatchOverlay (void)
Definition at line 1866 of file sbar.c.
{
    int i, y, xmin, xmax, ymin, ymax;
    char vabuf[1024];
    // request new ping times every two second
    if (cl.last_ping_request < host.realtime - 2 && cls.netcon)
    {
        cl.last_ping_request = host.realtime;
        if (cls.protocol == PROTOCOL_QUAKEWORLD)
        {
            MSG_WriteByte(&cls.netcon->message, qw_clc_stringcmd);
            MSG_WriteString(&cls.netcon->message, "pings");
        }
        else if (cls.protocol == PROTOCOL_QUAKE || cls.protocol == PROTOCOL_QUAKEDP || cls.protocol == PROTOCOL_NEHAHRAMOVIE || cls.protocol == PROTOCOL_NEHAHRABJP || cls.protocol == PROTOCOL_NEHAHRABJP2 || cls.protocol == PROTOCOL_NEHAHRABJP3 || cls.protocol == PROTOCOL_DARKPLACES1 || cls.protocol == PROTOCOL_DARKPLACES2 || cls.protocol == PROTOCOL_DARKPLACES3 || cls.protocol == PROTOCOL_DARKPLACES4 || cls.protocol == PROTOCOL_DARKPLACES5 || cls.protocol == PROTOCOL_DARKPLACES6/* || cls.protocol == PROTOCOL_DARKPLACES7*/)
        {
            // these servers usually lack the pings command and so a less efficient "ping" command must be sent, which on modern DP servers will also reply with a pingplreport command after the ping listing
            static int ping_anyway_counter = 0;
            if(cl.parsingtextexpectingpingforscores == 1)
            {
                Con_DPrintf("want to send ping, but still waiting for other reply\n");
                if(++ping_anyway_counter >= 5)
                    cl.parsingtextexpectingpingforscores = 0;
            }
            if(cl.parsingtextexpectingpingforscores != 1)
            {
                ping_anyway_counter = 0;
                cl.parsingtextexpectingpingforscores = 1; // hide the output of the next ping report
                MSG_WriteByte(&cls.netcon->message, clc_stringcmd);
                MSG_WriteString(&cls.netcon->message, "ping");
            }
        }
        else
        {
            // newer server definitely has pings command, so use it for more efficiency, avoids ping reports spamming the console if they are misparsed, and saves a little bandwidth
            MSG_WriteByte(&cls.netcon->message, clc_stringcmd);
            MSG_WriteString(&cls.netcon->message, "pings");
        }
    }
    // scores
    Sbar_SortFrags ();
    ymin = 8;
    ymax = 40 + 8 + (Sbar_IsTeammatch() ? (teamlines * 8 + 5): 0) + scoreboardlines * 8 - 1;
    if (cls.protocol == PROTOCOL_QUAKEWORLD)
        xmin = (int) (vid_conwidth.integer - (26 + 15) * 8 * FONT_SBAR->maxwidth) / 2; // 26 characters until name, then we assume 15 character names (they can be longer but usually aren't)
    else
        xmin = (int) (vid_conwidth.integer - (16 + 25) * 8 * FONT_SBAR->maxwidth) / 2; // 16 characters until name, then we assume 25 character names (they can be longer but usually aren't)
    xmax = vid_conwidth.integer - xmin;
    if(IS_OLDNEXUIZ_DERIVED(gamemode))
        DrawQ_Pic (xmin - 8, ymin - 8, 0, xmax-xmin+1 + 2*8, ymax-ymin+1 + 2*8, 0, 0, 0, sbar_alpha_bg.value, 0);
    DrawQ_Pic ((vid_conwidth.integer - Draw_GetPicWidth(sb_ranking))/2, 8, sb_ranking, 0, 0, 1, 1, 1, 1 * sbar_alpha_fg.value, 0);
    // draw the text
    y = 40;
    if (cls.protocol == PROTOCOL_QUAKEWORLD)
    {
        DrawQ_String(xmin, y, va(vabuf, sizeof(vabuf), "ping pl%% time frags team  name"), 0, 8, 8, 1, 1, 1, 1 * sbar_alpha_fg.value, 0, NULL, false, FONT_SBAR );
    }
    else
    {
        DrawQ_String(xmin, y, va(vabuf, sizeof(vabuf), "ping pl%% frags  name"), 0, 8, 8, 1, 1, 1, 1 * sbar_alpha_fg.value, 0, NULL, false, FONT_SBAR );
    }
    y += 8;
    if (Sbar_IsTeammatch ())
    {
        // show team scores first
        for (i = 0;i < teamlines && y < vid_conheight.integer;i++)
            y += (int)Sbar_PrintScoreboardItem((teams + teamsort[i]), xmin, y);
        y += 5;
    }
    for (i = 0;i < scoreboardlines && y < vid_conheight.integer;i++)
        y += (int)Sbar_PrintScoreboardItem(cl.scores + fragsort[i], xmin, y);
}
Referenced by CL_VM_DrawHud(), Sbar_DrawScoreboard(), and Sbar_IntermissionOverlay().
Sbar_Draw()
void Sbar_Draw (void)
called every frame by screen
Definition at line 1372 of file sbar.c.
{
    cachepic_t *pic;
    char vabuf[1024];
    if(cl.csqc_vidvars.drawenginesbar)  //[515]: csqc drawsbar
    {
        if (sb_showscores)
            Sbar_DrawScoreboard ();
        else if (cl.intermission == 1)
        {
            if(IS_OLDNEXUIZ_DERIVED(gamemode)) // display full scoreboard (that is, show scores + map name)
            {
                Sbar_DrawScoreboard();
                return;
            }
            Sbar_IntermissionOverlay();
        }
        else if (cl.intermission == 2)
            Sbar_FinaleOverlay();
        else if (gamemode == GAME_DELUXEQUAKE)
        {
        }
        else if (IS_OLDNEXUIZ_DERIVED(gamemode))
        {
            if (sb_showscores || (cl.stats[STAT_HEALTH] <= 0 && cl_deathscoreboard.integer))
            {
                sbar_x = (vid_conwidth.integer - 640)/2;
                sbar_y = vid_conheight.integer - 47;
                Sbar_DrawAlphaPic (0, 0, sb_scorebar, sbar_alpha_bg.value);
                Sbar_DrawScoreboard ();
            }
            else if (sb_lines && sbar_hudselector.integer == 1)
            {
                int i;
                float fade;
                int redflag, blueflag;
                float x;
                sbar_x = (vid_conwidth.integer - 320)/2;
                sbar_y = vid_conheight.integer - 24 - 16;
                // calculate intensity to draw weapons bar at
                fade = 3.2 - 2 * (cl.time - cl.weapontime);
                fade = bound(0.7, fade, 1);
                for (i = 0; i < 8;i++)
                    if (cl.stats[STAT_ITEMS] & (1 << i))
                        Sbar_DrawWeapon(i + 1, fade, (i + 2 == cl.stats[STAT_ACTIVEWEAPON]));
                if((cl.stats[STAT_ITEMS] & (1<<12)))
                    Sbar_DrawWeapon(0, fade, (cl.stats[STAT_ACTIVEWEAPON] == 1));
                // flag icons
                redflag = ((cl.stats[STAT_ITEMS]>>15) & 3);
                blueflag = ((cl.stats[STAT_ITEMS]>>17) & 3);
                x = sbar_flagstatus_right.integer ? vid_conwidth.integer - 10 - sbar_x - 64 : 10 - sbar_x;
                if (redflag == 3 && blueflag == 3)
                {
                    // The Impossible Combination[tm]
                    // Can only happen in Key Hunt mode...
                    Sbar_DrawPic ((int) x, (int) ((vid_conheight.integer - sbar_y) - (sbar_flagstatus_pos.value + 128)), sb_items[14]);
                }
                else
                {
                    if (redflag)
                        Sbar_DrawPic ((int) x, (int) ((vid_conheight.integer - sbar_y) - (sbar_flagstatus_pos.value + 64)), sb_items[redflag+10]);
                    if (blueflag)
                        Sbar_DrawPic ((int) x, (int) ((vid_conheight.integer - sbar_y) - (sbar_flagstatus_pos.value + 128)), sb_items[blueflag+14]);
                }
                // armor
                if (cl.stats[STAT_ARMOR] > 0)
                {
                    Sbar_DrawStretchPic (72, 0, sb_armor[0], sbar_alpha_fg.value, 24, 24);
                    if(cl.stats[STAT_ARMOR] > 200)
                        Sbar_DrawXNum(0,0,cl.stats[STAT_ARMOR],3,24,0,1,0,1,0);
                    else if(cl.stats[STAT_ARMOR] > 100)
                        Sbar_DrawXNum(0,0,cl.stats[STAT_ARMOR],3,24,0.2,1,0.2,1,0);
                    else if(cl.stats[STAT_ARMOR] > 50)
                        Sbar_DrawXNum(0,0,cl.stats[STAT_ARMOR],3,24,0.6,0.7,0.8,1,0);
                    else if(cl.stats[STAT_ARMOR] > 25)
                        Sbar_DrawXNum(0,0,cl.stats[STAT_ARMOR],3,24,1,1,0.2,1,0);
                    else
                        Sbar_DrawXNum(0,0,cl.stats[STAT_ARMOR],3,24,0.7,0,0,1,0);
                }
                // health
                if (cl.stats[STAT_HEALTH] != 0)
                {
                    Sbar_DrawStretchPic (184, 0, sb_health, sbar_alpha_fg.value, 24, 24);
                    if(cl.stats[STAT_HEALTH] > 200)
                        Sbar_DrawXNum(112,0,cl.stats[STAT_HEALTH],3,24,0,1,0,1,0);
                    else if(cl.stats[STAT_HEALTH] > 100)
                        Sbar_DrawXNum(112,0,cl.stats[STAT_HEALTH],3,24,0.2,1,0.2,1,0);
                    else if(cl.stats[STAT_HEALTH] > 50)
                        Sbar_DrawXNum(112,0,cl.stats[STAT_HEALTH],3,24,0.6,0.7,0.8,1,0);
                    else if(cl.stats[STAT_HEALTH] > 25)
                        Sbar_DrawXNum(112,0,cl.stats[STAT_HEALTH],3,24,1,1,0.2,1,0);
                    else
                        Sbar_DrawXNum(112,0,cl.stats[STAT_HEALTH],3,24,0.7,0,0,1,0);
                }
                // ammo
                if ((cl.stats[STAT_ITEMS] & (NEX_IT_SHELLS | NEX_IT_BULLETS | NEX_IT_ROCKETS | NEX_IT_CELLS)) || cl.stats[STAT_AMMO] != 0)
                {
                    if (cl.stats[STAT_ITEMS] & NEX_IT_SHELLS)
                        Sbar_DrawStretchPic (296, 0, sb_ammo[0], sbar_alpha_fg.value, 24, 24);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_BULLETS)
                        Sbar_DrawStretchPic (296, 0, sb_ammo[1], sbar_alpha_fg.value, 24, 24);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_ROCKETS)
                        Sbar_DrawStretchPic (296, 0, sb_ammo[2], sbar_alpha_fg.value, 24, 24);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_CELLS)
                        Sbar_DrawStretchPic (296, 0, sb_ammo[3], sbar_alpha_fg.value, 24, 24);
                    if(cl.stats[STAT_AMMO] > 10)
                        Sbar_DrawXNum(224, 0, cl.stats[STAT_AMMO], 3, 24, 0.6,0.7,0.8,1,0);
                    else
                        Sbar_DrawXNum(224, 0, cl.stats[STAT_AMMO], 3, 24, 0.7,0,0,1,0);
                }
                if (sbar_x + 320 + 160 <= vid_conwidth.integer)
                    Sbar_MiniDeathmatchOverlay (sbar_x + 320, sbar_y);
                if (sbar_x > 0)
                    Sbar_Score(16);
                    // The margin can be at most 8 to support 640x480 console size:
                    //   320 + 2 * (144 + 16) = 640
            }
            else if (sb_lines)
            {
                int i;
                float fade;
                int redflag, blueflag;
                float x;
                sbar_x = (vid_conwidth.integer - 640)/2;
                sbar_y = vid_conheight.integer - 47;
                // calculate intensity to draw weapons bar at
                fade = 3 - 2 * (cl.time - cl.weapontime);
                if (fade > 0)
                {
                    fade = min(fade, 1);
                    for (i = 0; i < 8;i++)
                        if (cl.stats[STAT_ITEMS] & (1 << i))
                            Sbar_DrawWeapon(i + 1, fade, (i + 2 == cl.stats[STAT_ACTIVEWEAPON]));
                    if((cl.stats[STAT_ITEMS] & (1<<12)))
                        Sbar_DrawWeapon(0, fade, (cl.stats[STAT_ACTIVEWEAPON] == 1));
                }
                //if (!cl.islocalgame)
                //  Sbar_DrawFrags ();
                if (sb_lines > 24)
                    Sbar_DrawAlphaPic (0, 0, sb_sbar, sbar_alpha_fg.value);
                else
                    Sbar_DrawAlphaPic (0, 0, sb_sbar_minimal, sbar_alpha_fg.value);
                // flag icons
                redflag = ((cl.stats[STAT_ITEMS]>>15) & 3);
                blueflag = ((cl.stats[STAT_ITEMS]>>17) & 3);
                x = sbar_flagstatus_right.integer ? vid_conwidth.integer - 10 - sbar_x - 64 : 10 - sbar_x;
                if (redflag == 3 && blueflag == 3)
                {
                    // The Impossible Combination[tm]
                    // Can only happen in Key Hunt mode...
                    Sbar_DrawPic ((int) x, -179, sb_items[14]);
                }
                else
                {
                    if (redflag)
                        Sbar_DrawPic ((int) x, -117, sb_items[redflag+10]);
                    if (blueflag)
                        Sbar_DrawPic ((int) x, -177, sb_items[blueflag+14]);
                }
                // armor
                Sbar_DrawXNum ((340-3*24), 12, cl.stats[STAT_ARMOR], 3, 24, 0.6,0.7,0.8,1,0);
                // health
                if(cl.stats[STAT_HEALTH] > 100)
                    Sbar_DrawXNum((154-3*24),12,cl.stats[STAT_HEALTH],3,24,1,1,1,1,0);
                else if(cl.stats[STAT_HEALTH] <= 25 && cl.time - (int)cl.time > 0.5)
                    Sbar_DrawXNum((154-3*24),12,cl.stats[STAT_HEALTH],3,24,0.7,0,0,1,0);
                else
                    Sbar_DrawXNum((154-3*24),12,cl.stats[STAT_HEALTH],3,24,0.6,0.7,0.8,1,0);
                // AK dont draw ammo for the laser
                if(cl.stats[STAT_ACTIVEWEAPON] != 12)
                {
                    if (cl.stats[STAT_ITEMS] & NEX_IT_SHELLS)
                        Sbar_DrawPic (519, 0, sb_ammo[0]);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_BULLETS)
                        Sbar_DrawPic (519, 0, sb_ammo[1]);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_ROCKETS)
                        Sbar_DrawPic (519, 0, sb_ammo[2]);
                    else if (cl.stats[STAT_ITEMS] & NEX_IT_CELLS)
                        Sbar_DrawPic (519, 0, sb_ammo[3]);
                    if(cl.stats[STAT_AMMO] <= 10)
                        Sbar_DrawXNum ((519-3*24), 12, cl.stats[STAT_AMMO], 3, 24, 0.7, 0,0,1,0);
                    else
                        Sbar_DrawXNum ((519-3*24), 12, cl.stats[STAT_AMMO], 3, 24, 0.6, 0.7,0.8,1,0);
                }
                if (sb_lines > 24)
                    DrawQ_Pic(sbar_x,sbar_y,sb_sbar_overlay,0,0,1,1,1,1,DRAWFLAG_MODULATE);
                if (sbar_x + 600 + 160 <= vid_conwidth.integer)
                    Sbar_MiniDeathmatchOverlay (sbar_x + 600, sbar_y);
                if (sbar_x > 0)
                    Sbar_Score(-16);
                    // Because:
                    //   Mini scoreboard uses 12*4 per other team, that is, 144
                    //   pixels when there are four teams...
                    //   Nexuiz by default sets vid_conwidth to 800... makes
                    //   sbar_x == 80...
                    //   so we need to shift it by 64 pixels to the right to fit
                    //   BUT: then it overlaps with the image that gets drawn
                    //   for viewsize 100! Therefore, just account for 3 teams,
                    //   that is, 96 pixels mini scoreboard size, needing 16 pixels
                    //   to the right!
            }
        }
        else if (gamemode == GAME_ZYMOTIC)
        {
#if 1
            float scale = 64.0f / 256.0f;
            float kickoffset[3];
            VectorClear(kickoffset);
            if (v_dmg_time > 0)
            {
                kickoffset[0] = (v_dmg_time/v_kicktime.value*v_dmg_roll) * 10 * scale;
                kickoffset[1] = (v_dmg_time/v_kicktime.value*v_dmg_pitch) * 10 * scale;
            }
            sbar_x = (int)((vid_conwidth.integer - 256 * scale)/2 + kickoffset[0]);
            sbar_y = (int)((vid_conheight.integer - 256 * scale)/2 + kickoffset[1]);
            // left1 16, 48 : 126 -66
            // left2 16, 128 : 196 -66
            // right 176, 48 : 196 -136
            Sbar_DrawGauge(sbar_x +  16 * scale, sbar_y +  48 * scale, zymsb_crosshair_left1, 64*scale,  80*scale, 78*scale,  -66*scale, cl.stats[STAT_AMMO]  * (1.0 / 200.0), cl.stats[STAT_SHELLS]  * (1.0 / 200.0), 0.8f,0.8f,0.0f,1.0f, 0.8f,0.5f,0.0f,1.0f, 0.3f,0.3f,0.3f,1.0f, DRAWFLAG_NORMAL);
            Sbar_DrawGauge(sbar_x +  16 * scale, sbar_y + 128 * scale, zymsb_crosshair_left2, 64*scale,  80*scale, 68*scale,  -66*scale, cl.stats[STAT_NAILS] * (1.0 / 200.0), cl.stats[STAT_ROCKETS] * (1.0 / 200.0), 0.8f,0.8f,0.0f,1.0f, 0.8f,0.5f,0.0f,1.0f, 0.3f,0.3f,0.3f,1.0f, DRAWFLAG_NORMAL);
            Sbar_DrawGauge(sbar_x + 176 * scale, sbar_y +  48 * scale, zymsb_crosshair_right, 64*scale, 160*scale, 148*scale, -136*scale, cl.stats[STAT_ARMOR]  * (1.0 / 300.0), cl.stats[STAT_HEALTH]  * (1.0 / 300.0), 0.0f,0.5f,1.0f,1.0f, 1.0f,0.0f,0.0f,1.0f, 0.3f,0.3f,0.3f,1.0f, DRAWFLAG_NORMAL);
            DrawQ_Pic(sbar_x + 120 * scale, sbar_y + 120 * scale, zymsb_crosshair_center, 16 * scale, 16 * scale, 1, 1, 1, 1, DRAWFLAG_NORMAL);
#else
            float scale = 128.0f / 256.0f;
            float healthstart, healthheight, healthstarttc, healthendtc;
            float shieldstart, shieldheight, shieldstarttc, shieldendtc;
            float ammostart, ammoheight, ammostarttc, ammoendtc;
            float clipstart, clipheight, clipstarttc, clipendtc;
            float kickoffset[3], offset;
            VectorClear(kickoffset);
            if (v_dmg_time > 0)
            {
                kickoffset[0] = (v_dmg_time/v_kicktime.value*v_dmg_roll) * 10 * scale;
                kickoffset[1] = (v_dmg_time/v_kicktime.value*v_dmg_pitch) * 10 * scale;
            }
            sbar_x = (vid_conwidth.integer - 256 * scale)/2 + kickoffset[0];
            sbar_y = (vid_conheight.integer - 256 * scale)/2 + kickoffset[1];
            offset = 0; // TODO: offset should be controlled by recoil (question: how to detect firing?)
            DrawQ_SuperPic(sbar_x +  120           * scale, sbar_y + ( 88 - offset) * scale, zymsb_crosshair_line, 16 * scale, 36 * scale, 0,0, 1,1,1,1, 1,0, 1,1,1,1, 0,1, 1,1,1,1, 1,1, 1,1,1,1, 0);
            DrawQ_SuperPic(sbar_x + (132 + offset) * scale, sbar_y + 120            * scale, zymsb_crosshair_line, 36 * scale, 16 * scale, 0,1, 1,1,1,1, 0,0, 1,1,1,1, 1,1, 1,1,1,1, 1,0, 1,1,1,1, 0);
            DrawQ_SuperPic(sbar_x +  120           * scale, sbar_y + (132 + offset) * scale, zymsb_crosshair_line, 16 * scale, 36 * scale, 1,1, 1,1,1,1, 0,1, 1,1,1,1, 1,0, 1,1,1,1, 0,0, 1,1,1,1, 0);
            DrawQ_SuperPic(sbar_x + ( 88 - offset) * scale, sbar_y + 120            * scale, zymsb_crosshair_line, 36 * scale, 16 * scale, 1,0, 1,1,1,1, 1,1, 1,1,1,1, 0,0, 1,1,1,1, 0,1, 1,1,1,1, 0);
            healthheight = cl.stats[STAT_HEALTH] * (152.0f / 300.0f);
            shieldheight = cl.stats[STAT_ARMOR] * (152.0f / 300.0f);
            healthstart = 204 - healthheight;
            shieldstart = healthstart - shieldheight;
            healthstarttc = healthstart * (1.0f / 256.0f);
            healthendtc = (healthstart + healthheight) * (1.0f / 256.0f);
            shieldstarttc = shieldstart * (1.0f / 256.0f);
            shieldendtc = (shieldstart + shieldheight) * (1.0f / 256.0f);
            ammoheight = cl.stats[STAT_SHELLS] * (62.0f / 200.0f);
            ammostart = 114 - ammoheight;
            ammostarttc = ammostart * (1.0f / 256.0f);
            ammoendtc = (ammostart + ammoheight) * (1.0f / 256.0f);
            clipheight = cl.stats[STAT_AMMO] * (122.0f / 200.0f);
            clipstart = 190 - clipheight;
            clipstarttc = clipstart * (1.0f / 256.0f);
            clipendtc = (clipstart + clipheight) * (1.0f / 256.0f);
            if (healthheight > 0) DrawQ_SuperPic(sbar_x + 0 * scale, sbar_y + healthstart * scale, zymsb_crosshair_health, 256 * scale, healthheight * scale, 0,healthstarttc, 1.0f,0.0f,0.0f,1.0f, 1,healthstarttc, 1.0f,0.0f,0.0f,1.0f, 0,healthendtc, 1.0f,0.0f,0.0f,1.0f, 1,healthendtc, 1.0f,0.0f,0.0f,1.0f, DRAWFLAG_NORMAL);
            if (shieldheight > 0) DrawQ_SuperPic(sbar_x + 0 * scale, sbar_y + shieldstart * scale, zymsb_crosshair_health, 256 * scale, shieldheight * scale, 0,shieldstarttc, 0.0f,0.5f,1.0f,1.0f, 1,shieldstarttc, 0.0f,0.5f,1.0f,1.0f, 0,shieldendtc, 0.0f,0.5f,1.0f,1.0f, 1,shieldendtc, 0.0f,0.5f,1.0f,1.0f, DRAWFLAG_NORMAL);
            if (ammoheight > 0)   DrawQ_SuperPic(sbar_x + 0 * scale, sbar_y + ammostart   * scale, zymsb_crosshair_ammo,   256 * scale, ammoheight   * scale, 0,ammostarttc,   0.8f,0.8f,0.0f,1.0f, 1,ammostarttc,   0.8f,0.8f,0.0f,1.0f, 0,ammoendtc,   0.8f,0.8f,0.0f,1.0f, 1,ammoendtc,   0.8f,0.8f,0.0f,1.0f, DRAWFLAG_NORMAL);
            if (clipheight > 0)   DrawQ_SuperPic(sbar_x + 0 * scale, sbar_y + clipstart   * scale, zymsb_crosshair_clip,   256 * scale, clipheight   * scale, 0,clipstarttc,   1.0f,1.0f,0.0f,1.0f, 1,clipstarttc,   1.0f,1.0f,0.0f,1.0f, 0,clipendtc,   1.0f,1.0f,0.0f,1.0f, 1,clipendtc,   1.0f,1.0f,0.0f,1.0f, DRAWFLAG_NORMAL);
            DrawQ_Pic(sbar_x + 0 * scale, sbar_y + 0 * scale, zymsb_crosshair_background, 256 * scale, 256 * scale, 1, 1, 1, 1, DRAWFLAG_NORMAL);
            DrawQ_Pic(sbar_x + 120 * scale, sbar_y + 120 * scale, zymsb_crosshair_center, 16 * scale, 16 * scale, 1, 1, 1, 1, DRAWFLAG_NORMAL);
#endif
        }
        else // Quake and others
        {
            sbar_x = (vid_conwidth.integer - 320)/2;
            sbar_y = vid_conheight.integer - SBAR_HEIGHT;
            // LadyHavoc: changed to draw the deathmatch overlays in any multiplayer mode
            //if (cl.gametype == GAME_DEATHMATCH && gamemode != GAME_TRANSFUSION)
            if (sb_lines > 24)
            {
                if (gamemode != GAME_GOODVSBAD2)
                    Sbar_DrawInventory ();
                if (!cl.islocalgame && gamemode != GAME_TRANSFUSION)
                    Sbar_DrawFrags ();
            }
            if (sb_showscores || (cl.stats[STAT_HEALTH] <= 0 && cl_deathscoreboard.integer))
            {
                if (gamemode != GAME_GOODVSBAD2)
                    Sbar_DrawAlphaPic (0, 0, sb_scorebar, sbar_alpha_bg.value);
                Sbar_DrawScoreboard ();
            }
            else if (sb_lines)
            {
                Sbar_DrawAlphaPic (0, 0, sb_sbar, sbar_alpha_bg.value);
                // keys (hipnotic only)
                //MED 01/04/97 moved keys here so they would not be overwritten
                if (gamemode == GAME_HIPNOTIC || gamemode == GAME_QUOTH)
                {
                    if (cl.stats[STAT_ITEMS] & IT_KEY1)
                        Sbar_DrawPic (209, 3, sb_items[0]);
                    if (cl.stats[STAT_ITEMS] & IT_KEY2)
                        Sbar_DrawPic (209, 12, sb_items[1]);
                }
                // armor
                if (gamemode != GAME_GOODVSBAD2)
                {
                    if (cl.stats[STAT_ITEMS] & IT_INVULNERABILITY)
                    {
                        Sbar_DrawNum (24, 0, 666, 3, 1);
                        Sbar_DrawPic (0, 0, sb_disc);
                    }
                    else
                    {
                        if (gamemode == GAME_ROGUE)
{
                            Sbar_DrawNum (24, 0, cl.stats[STAT_ARMOR], 3, cl.stats[STAT_ARMOR] <= 25);
                            if (cl.stats[STAT_ITEMS] & RIT_ARMOR3)
                                Sbar_DrawPic (0, 0, sb_armor[2]);
                            else if (cl.stats[STAT_ITEMS] & RIT_ARMOR2)
                                Sbar_DrawPic (0, 0, sb_armor[1]);
                            else if (cl.stats[STAT_ITEMS] & RIT_ARMOR1)
                                Sbar_DrawPic (0, 0, sb_armor[0]);
                        }
                        else
{
                            Sbar_DrawNum (24, 0, cl.stats[STAT_ARMOR], 3, cl.stats[STAT_ARMOR] <= 25);
                            if (cl.stats[STAT_ITEMS] & IT_ARMOR3)
                                Sbar_DrawPic (0, 0, sb_armor[2]);
                            else if (cl.stats[STAT_ITEMS] & IT_ARMOR2)
                                Sbar_DrawPic (0, 0, sb_armor[1]);
                            else if (cl.stats[STAT_ITEMS] & IT_ARMOR1)
                                Sbar_DrawPic (0, 0, sb_armor[0]);
                        }
                    }
                }
                // face
                Sbar_DrawFace ();
                // health
                Sbar_DrawNum (136, 0, cl.stats[STAT_HEALTH], 3, cl.stats[STAT_HEALTH] <= 25);
                // ammo icon
                if (gamemode == GAME_ROGUE)
                {
                    if (cl.stats[STAT_ITEMS] & RIT_SHELLS)
                        Sbar_DrawPic (224, 0, sb_ammo[0]);
                    else if (cl.stats[STAT_ITEMS] & RIT_NAILS)
                        Sbar_DrawPic (224, 0, sb_ammo[1]);
                    else if (cl.stats[STAT_ITEMS] & RIT_ROCKETS)
                        Sbar_DrawPic (224, 0, sb_ammo[2]);
                    else if (cl.stats[STAT_ITEMS] & RIT_CELLS)
                        Sbar_DrawPic (224, 0, sb_ammo[3]);
                    else if (cl.stats[STAT_ITEMS] & RIT_LAVA_NAILS)
                        Sbar_DrawPic (224, 0, rsb_ammo[0]);
                    else if (cl.stats[STAT_ITEMS] & RIT_PLASMA_AMMO)
                        Sbar_DrawPic (224, 0, rsb_ammo[1]);
                    else if (cl.stats[STAT_ITEMS] & RIT_MULTI_ROCKETS)
                        Sbar_DrawPic (224, 0, rsb_ammo[2]);
                }
                else
                {
                    if (cl.stats[STAT_ITEMS] & IT_SHELLS)
                        Sbar_DrawPic (224, 0, sb_ammo[0]);
                    else if (cl.stats[STAT_ITEMS] & IT_NAILS)
                        Sbar_DrawPic (224, 0, sb_ammo[1]);
                    else if (cl.stats[STAT_ITEMS] & IT_ROCKETS)
                        Sbar_DrawPic (224, 0, sb_ammo[2]);
                    else if (cl.stats[STAT_ITEMS] & IT_CELLS)
                        Sbar_DrawPic (224, 0, sb_ammo[3]);
                }
                Sbar_DrawNum (248, 0, cl.stats[STAT_AMMO], 3, cl.stats[STAT_AMMO] <= 10);
                // LadyHavoc: changed to draw the deathmatch overlays in any multiplayer mode
                if ((!cl.islocalgame || cl.gametype != GAME_COOP))
                {
                    if (gamemode == GAME_TRANSFUSION)
                        Sbar_MiniDeathmatchOverlay (0, 0);
                    else
                        Sbar_MiniDeathmatchOverlay (sbar_x + 324, vid_conheight.integer - 8*8);
                    Sbar_Score(24);
                }
            }
        }
    }
    if (cl.csqc_vidvars.drawcrosshair && crosshair.integer >= 1 && !cl.intermission && !r_letterbox.value)
    {
        pic = Draw_CachePic (va(vabuf, sizeof(vabuf), "gfx/crosshair%i", crosshair.integer));
        DrawQ_Pic((vid_conwidth.integer - Draw_GetPicWidth(pic) * crosshair_size.value) * 0.5f, (vid_conheight.integer - Draw_GetPicHeight(pic) * crosshair_size.value) * 0.5f, pic, Draw_GetPicWidth(pic) * crosshair_size.value, Draw_GetPicHeight(pic) * crosshair_size.value, crosshair_color_red.value, crosshair_color_green.value, crosshair_color_blue.value, crosshair_color_alpha.value, 0);
    }
    if (cl_prydoncursor.integer > 0)
        DrawQ_Pic((cl.cmd.cursor_screen[0] + 1) * 0.5 * vid_conwidth.integer, (cl.cmd.cursor_screen[1] + 1) * 0.5 * vid_conheight.integer, Draw_CachePic (va(vabuf, sizeof(vabuf), "gfx/prydoncursor%03i", cl_prydoncursor.integer)), 0, 0, 1, 1, 1, 1, 0);
}
Referenced by SCR_DrawScreen().
Sbar_GetSortedPlayerIndex()
int Sbar_GetSortedPlayerIndex (int index)
Definition at line 546 of file sbar.c.
{
    return index >= 0 && index < scoreboardlines ? fragsort[index] : -1;
}
Referenced by VM_CL_getplayerkey().
Sbar_Init()
void Sbar_Init (void)
Definition at line 359 of file sbar.c.
{
    Cmd_AddCommand(CF_CLIENT, "+showscores", Sbar_ShowScores_f, "show scoreboard");
    Cmd_AddCommand(CF_CLIENT, "-showscores", Sbar_DontShowScores_f, "hide scoreboard");
    Cvar_RegisterVariable(&cl_showfps);
    Cvar_RegisterVariable(&cl_showsound);
    Cvar_RegisterVariable(&cl_showblur);
    Cvar_RegisterVariable(&cl_showspeed);
    Cvar_RegisterVariable(&cl_showspeed_factor);
    Cvar_RegisterVariable(&cl_showtopspeed);
    Cvar_RegisterVariable(&cl_showtime);
    Cvar_RegisterVariable(&cl_showtime_format);
    Cvar_RegisterVariable(&cl_showdate);
    Cvar_RegisterVariable(&cl_showdate_format);
    Cvar_RegisterVariable(&cl_showtex);
    Cvar_RegisterVirtual(&cl_showfps, "showfps");
    Cvar_RegisterVirtual(&cl_showsound, "showsound");
    Cvar_RegisterVirtual(&cl_showblur, "showblur");
    Cvar_RegisterVirtual(&cl_showspeed, "showspeed");
    Cvar_RegisterVirtual(&cl_showtopspeed, "showtopspeed");
    Cvar_RegisterVirtual(&cl_showtime, "showtime");
    Cvar_RegisterVirtual(&cl_showtime_format, "showtime_format");
    Cvar_RegisterVirtual(&cl_showdate, "showdate");
    Cvar_RegisterVirtual(&cl_showdate_format, "showdate_format");
    Cvar_RegisterVirtual(&cl_showtex, "showtex");
    Cvar_RegisterVariable(&sbar_alpha_bg);
    Cvar_RegisterVariable(&sbar_alpha_fg);
    Cvar_RegisterVariable(&sbar_hudselector);
    Cvar_RegisterVariable(&sbar_scorerank);
    Cvar_RegisterVariable(&sbar_gametime);
    Cvar_RegisterVariable(&sbar_miniscoreboard_size);
    Cvar_RegisterVariable(&sbar_info_pos);
    Cvar_RegisterVariable(&cl_deathscoreboard);
    // This cvar is found in Fitzquake-derived engines and FTEQW and is read by the Alkaline 1.2 and Arcane Dimensions 1.80 CSQC
    Cvar_RegisterVirtual(&sbar_alpha_bg, "scr_sbaralpha");
    Cvar_RegisterVariable(&crosshair_color_red);
    Cvar_RegisterVariable(&crosshair_color_green);
    Cvar_RegisterVariable(&crosshair_color_blue);
    Cvar_RegisterVariable(&crosshair_color_alpha);
    Cvar_RegisterVariable(&crosshair_size);
    Cvar_RegisterVariable(&sbar_flagstatus_right); // (GAME_NEXUZI ONLY)
    Cvar_RegisterVariable(&sbar_flagstatus_pos); // (GAME_NEXUIZ ONLY)
    R_RegisterModule("sbar", sbar_start, sbar_shutdown, sbar_newmap, NULL, NULL);
}
Sbar_ShowFPS()
void Sbar_ShowFPS (void)
Definition at line 1099 of file sbar.c.
{
    float fps_x, fps_y, fps_scalex, fps_scaley, fps_strings = 0;
    char soundstring[32];
    char fpsstring[32];
    char timestring[32];
    char datestring[32];
    char timedemostring1[32];
    char timedemostring2[32];
    char speedstring[32];
    char blurstring[32];
    char topspeedstring[48];
    char texstring[MAX_QPATH];
    char entstring[32];
    qbool red = false;
    soundstring[0] = 0;
    fpsstring[0] = 0;
    timedemostring1[0] = 0;
    timedemostring2[0] = 0;
    timestring[0] = 0;
    datestring[0] = 0;
    speedstring[0] = 0;
    blurstring[0] = 0;
    topspeedstring[0] = 0;
    texstring[0] = 0;
    entstring[0] = 0;
    if (cl_showfps.integer)
    {
        red = (showfps_framerate < 1.0f);
        if(cl_showfps.integer == 2)
            dpsnprintf(fpsstring, sizeof(fpsstring), "%7.3f mspf", (1000.0 / showfps_framerate));
        else if (red)
            dpsnprintf(fpsstring, sizeof(fpsstring), "%4i spf", (int)(1.0 / showfps_framerate + 0.5));
        else
            dpsnprintf(fpsstring, sizeof(fpsstring), "%4i fps", (int)(showfps_framerate + 0.5));
        fps_strings++;
        if (cls.timedemo)
        {
            dpsnprintf(timedemostring1, sizeof(timedemostring1), "frame%4i %f", cls.td_frames, host.realtime - cls.td_starttime);
            dpsnprintf(timedemostring2, sizeof(timedemostring2), "%i seconds %3.0f/%3.0f/%3.0f fps", cls.td_onesecondavgcount, cls.td_onesecondminfps, cls.td_onesecondavgfps / max(1, cls.td_onesecondavgcount), cls.td_onesecondmaxfps);
            fps_strings++;
            fps_strings++;
        }
    }
    if (cl_showtime.integer)
    {
        dp_strlcpy(timestring, Sys_TimeString(cl_showtime_format.string), sizeof(timestring));
        fps_strings++;
    }
    if (cl_showdate.integer)
    {
        dp_strlcpy(datestring, Sys_TimeString(cl_showdate_format.string), sizeof(datestring));
        fps_strings++;
    }
    if (cl_showblur.integer)
    {
        dpsnprintf(blurstring, sizeof(blurstring), "%3i%% blur", (int)(cl.motionbluralpha * 100));
        fps_strings++;
    }
    if (cl_showsound.integer)
    {
        dpsnprintf(soundstring, sizeof(soundstring), "%4i/4%i at %3ims", cls.soundstats.mixedsounds, cls.soundstats.totalsounds, cls.soundstats.latency_milliseconds);
        fps_strings++;
    }
    if (cl_showspeed.integer || cl_showtopspeed.integer)
    {
        double speed, speedxy, f;
        const char *unit;
        speed = VectorLength(cl.movement_velocity);
        speedxy = sqrt(cl.movement_velocity[0] * cl.movement_velocity[0] + cl.movement_velocity[1] * cl.movement_velocity[1]);
        if (cl_showspeed.integer)
        {
            get_showspeed_unit(cl_showspeed.integer, &f, &unit);
            dpsnprintf(speedstring, sizeof(speedstring), "%.0f (%.0f) %s", f*speed, f*speedxy, unit);
            fps_strings++;
        }
        if (cl_showtopspeed.integer)
        {
            qbool topspeed_latched = false, topspeedxy_latched = false;
            get_showspeed_unit(cl_showtopspeed.integer, &f, &unit);
            if (speed >= topspeed || current_time - top_time > 3)
            {
                topspeed = speed;
                time(&top_time);
            }
            else
                topspeed_latched = true;
            if (speedxy >= topspeedxy || current_time - topxy_time > 3)
            {
                topspeedxy = speedxy;
                time(&topxy_time);
            }
            else
                topspeedxy_latched = true;
            dpsnprintf(topspeedstring, sizeof(topspeedstring), "%s%.0f%s (%s%.0f%s) %s",
                topspeed_latched ? "^1" : "^xf88", f*topspeed, "^xf88",
                topspeedxy_latched ? "^1" : "^xf88", f*topspeedxy, "^xf88",
                unit);
            time(&current_time);
            fps_strings++;
        }
    }
    if (cl_showtex.integer)
    {
        vec3_t org;
        vec3_t dest;
        vec3_t temp;
        trace_t svtrace, cltrace;
        int hitnetentity = -1;
        Matrix4x4_OriginFromMatrix(&r_refdef.view.matrix, org);
        VectorSet(temp, 65536, 0, 0);
        Matrix4x4_Transform(&r_refdef.view.matrix, temp, dest);
        // clear the traces as we may or may not fill them out, and mark them with an invalid fraction so we know if we did
        memset(&svtrace, 0, sizeof(svtrace));
        memset(&cltrace, 0, sizeof(cltrace));
        svtrace.fraction = 2.0;
        cltrace.fraction = 2.0;
        // ray hits models (even animated ones) and ignores translucent materials
        if (sv.active)
            svtrace = SV_TraceLine(org, dest, MOVE_HITMODEL, NULL, SUPERCONTENTS_SOLID, 0, MATERIALFLAGMASK_TRANSLUCENT, collision_extendmovelength.value);
        cltrace = CL_TraceLine(org, dest, MOVE_HITMODEL, NULL, SUPERCONTENTS_SOLID, 0, MATERIALFLAGMASK_TRANSLUCENT, collision_extendmovelength.value, true, false, &hitnetentity, true, true);
        if (cltrace.hittexture)
            dp_strlcpy(texstring, cltrace.hittexture->name, sizeof(texstring));
        else
            dp_strlcpy(texstring, "(no texture hit)", sizeof(texstring));
        fps_strings++;
        if (svtrace.fraction < cltrace.fraction)
        {
            if (svtrace.ent != NULL)
            {
                prvm_prog_t *prog = SVVM_prog;
                dpsnprintf(entstring, sizeof(entstring), "server entity %i", (int)PRVM_EDICT_TO_PROG(svtrace.ent));
            }
            else
                dp_strlcpy(entstring, "(no entity hit)", sizeof(entstring));
        }
        else
        {
            if (cltrace.ent != NULL)
            {
                prvm_prog_t *prog = CLVM_prog;
                dpsnprintf(entstring, sizeof(entstring), "client entity %i", (int)PRVM_EDICT_TO_PROG(cltrace.ent));
            }
            else if (hitnetentity > 0)
                dpsnprintf(entstring, sizeof(entstring), "network entity %i", hitnetentity);
            else if (hitnetentity == 0)
                dp_strlcpy(entstring, "world entity", sizeof(entstring));
            else
                dp_strlcpy(entstring, "(no entity hit)", sizeof(entstring));
        }
        fps_strings++;
    }
    if (fps_strings)
    {
        fps_scalex = 12;
        fps_scaley = 12;
        //fps_y = vid_conheight.integer - sb_lines; // yes this may draw over the sbar
        //fps_y = bound(0, fps_y, vid_conheight.integer - fps_strings*fps_scaley);
        fps_y = vid_conheight.integer - sbar_info_pos.integer - fps_strings*fps_scaley;
        if (soundstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(soundstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, soundstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (fpsstring[0])
        {
            r_draw2d_force = true;
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(fpsstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            if (red)
                DrawQ_String(fps_x, fps_y, fpsstring, 0, fps_scalex, fps_scaley, 1, 0, 0, 1, 0, NULL, true, FONT_INFOBAR);
            else
                DrawQ_String(fps_x, fps_y, fpsstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
            r_draw2d_force = false;
        }
        if (timedemostring1[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(timedemostring1, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, timedemostring1, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (timedemostring2[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(timedemostring2, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, timedemostring2, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (timestring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(timestring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, timestring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (datestring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(datestring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, datestring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (speedstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(speedstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, speedstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (topspeedstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(topspeedstring, 0, fps_scalex, fps_scaley, false, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, topspeedstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, false, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (blurstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(blurstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, blurstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (texstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(texstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, texstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
        if (entstring[0])
        {
            fps_x = vid_conwidth.integer - DrawQ_TextWidth(entstring, 0, fps_scalex, fps_scaley, true, FONT_INFOBAR);
            DrawQ_Fill(fps_x, fps_y, vid_conwidth.integer - fps_x, fps_scaley, 0, 0, 0, 0.5, 0);
            DrawQ_String(fps_x, fps_y, entstring, 0, fps_scalex, fps_scaley, 1, 1, 1, 1, 0, NULL, true, FONT_INFOBAR);
            fps_y += fps_scaley;
        }
    }
}
Referenced by SCR_DrawScreen().
Sbar_ShowFPS_Update()
void Sbar_ShowFPS_Update (void)
Definition at line 1082 of file sbar.c.
{
    double interval = 1;
    double newtime;
    newtime = host.realtime;
    if (newtime >= showfps_nexttime)
    {
        showfps_framerate = showfps_framecount / (newtime - showfps_lasttime);
        if (showfps_nexttime < newtime - interval * 1.5)
            showfps_nexttime = newtime;
        showfps_lasttime = newtime;
        showfps_nexttime += interval;
        showfps_framecount = 0;
    }
    showfps_framecount++;
}
Referenced by CL_UpdateScreen().
Sbar_SortFrags()
void Sbar_SortFrags (void)
Definition at line 554 of file sbar.c.
{
    int i, j, k, color;
    // sort by frags
    scoreboardlines = 0;
    for (i=0 ; i<cl.maxclients ; i++)
    {
        if (cl.scores[i].name[0])
        {
            fragsort[scoreboardlines] = i;
            scoreboardlines++;
        }
    }
    for (i=0 ; i<scoreboardlines ; i++)
        for (j=0 ; j<scoreboardlines-1-i ; j++)
            if (cl.scores[fragsort[j]].frags < cl.scores[fragsort[j+1]].frags)
            {
                k = fragsort[j];
                fragsort[j] = fragsort[j+1];
                fragsort[j+1] = k;
            }
    teamlines = 0;
    if (Sbar_IsTeammatch ())
    {
        // now sort players by teams.
        for (i=0 ; i<scoreboardlines ; i++)
        {
            for (j=0 ; j<scoreboardlines-1-i ; j++)
            {
                if (cl.scores[fragsort[j]].colors < cl.scores[fragsort[j+1]].colors)
                {
                    k = fragsort[j];
                    fragsort[j] = fragsort[j+1];
                    fragsort[j+1] = k;
                }
            }
        }
        // calculate team scores
        color = -1;
        for (i=0 ; i<scoreboardlines ; i++)
        {
            if (color != (cl.scores[fragsort[i]].colors & 15))
            {
                const char* teamname;
                color = cl.scores[fragsort[i]].colors & 15;
                teamlines++;
                switch (color)
                {
                    case 4:
                        teamname = "^1Red Team";
                        break;
                    case 13:
                        teamname = "^4Blue Team";
                        break;
                    case 9:
                        teamname = "^6Pink Team";
                        break;
                    case 12:
                        teamname = "^3Yellow Team";
                        break;
                    default:
                        teamname = "Total Team Score";
                        break;
                }
                dp_strlcpy(teams[teamlines-1].name, teamname, sizeof(teams[teamlines-1].name));
                teams[teamlines-1].frags = 0;
                teams[teamlines-1].colors = color + 16 * color;
            }
            if (cl.scores[fragsort[i]].frags != -666)
            {
                // do not add spedcators
                // (ugly hack for nexuiz)
                teams[teamlines-1].frags += cl.scores[fragsort[i]].frags;
            }
        }
        // now sort teams by scores.
        for (i=0 ; i<teamlines ; i++)
            teamsort[i] = i;
        for (i=0 ; i<teamlines ; i++)
        {
            for (j=0 ; j<teamlines-1-i ; j++)
            {
                if (teams[teamsort[j]].frags < teams[teamsort[j+1]].frags)
                {
                    k = teamsort[j];
                    teamsort[j] = teamsort[j+1];
                    teamsort[j+1] = k;
                }
            }
        }
    }
}
Referenced by Sbar_DeathmatchOverlay(), Sbar_DrawFrags(), Sbar_MiniDeathmatchOverlay(), Sbar_Score(), and VM_CL_getplayerkey().
Variable Documentation
cl_deathscoreboard
cvar_t cl_deathscoreboard extern
Definition at line 110 of file sbar.c.
{CF_CLIENT, "cl_deathscoreboard", "1", "shows scoreboard (+showscores) while dead"};
Referenced by CL_VM_DrawHud(), Sbar_Draw(), and Sbar_Init().
sb_lines
int sb_lines extern
scan lines to draw
Definition at line 58 of file sbar.c.
sbar_alpha_bg
struct cvar_s sbar_alpha_bg extern
Definition at line 100 of file sbar.c.
{CF_CLIENT | CF_ARCHIVE, "sbar_alpha_bg", "0.4", "opacity value of the statusbar background image"};
Referenced by Sbar_DeathmatchOverlay(), Sbar_Draw(), Sbar_DrawInventory(), and Sbar_Init().
sbar_alpha_fg
struct cvar_s sbar_alpha_fg extern
Definition at line 101 of file sbar.c.
{CF_CLIENT | CF_ARCHIVE, "sbar_alpha_fg", "1", "opacity value of the statusbar weapon/item icons and numbers"};
Referenced by Sbar_DeathmatchOverlay(), Sbar_Draw(), Sbar_DrawCharacter(), Sbar_DrawFace(), Sbar_DrawFrags(), Sbar_DrawPic(), Sbar_DrawString(), Sbar_DrawWeapon(), Sbar_DrawXNum(), Sbar_FinaleOverlay(), Sbar_Init(), Sbar_IntermissionOverlay(), Sbar_PrintScoreboardItem(), and Sbar_Score().