DarkPlaces: shader_glsl.h File Reference
shader_glsl.h File Reference
Functions
vec4 TrippyVertex (vec4 position)\n"
void main (void)\n"
vec4 fxaa (vec4 inColor, float maxspan)\n"
for (i=1;i< SAMPLES;i++)\n"
vec3 FogVertex (vec4 surfacecolor)\n"
return mix (fogheightpixel.rgb *fc, surfacecolor.rgb, dp_texture2D(Texture_FogMask, cast_myhalf2(length(EyeVectorModelSpace) *fogfrac *FogRangeRecip, 0.0)).r)
return mix (fc, surfacecolor.rgb, dp_texture2D(Texture_FogMask, cast_myhalf2(length(EyeVectorModelSpace) *fogfrac *FogRangeRecip, 0.0)).r)
vec2 OffsetMapping (vec2 TexCoord, vec2 dPdx, vec2 dPdy)\n"
for (i=0.0, f=1.0;i< ScaleSteps.w;++i, f *=0.5)\n"
float ShadowMapCompare (vec3 dir)\n"
Variables
n
precision highp float
dp_attribute vec4 Attrib_Color
dp_attribute vec4 Attrib_TexCoord0
dp_attribute vec3 Attrib_TexCoord1
dp_attribute vec3 Attrib_TexCoord2
dp_attribute vec3 Attrib_TexCoord3
dp_attribute vec4 Attrib_TexCoord4
uniform Skeletal_Transform12_UniformBlock dp_attribute vec4 Attrib_SkeletalIndex
dp_attribute vec4 Attrib_SkeletalWeight
dp_varying mediump vec4 VertexColor
uniform highp mat4 ModelViewProjectionMatrix
uniform highp float ClientTime
vec4 worldTime position float distanceSquared = (position.x * position.x + position.z * position.z)
position y = 5.0*sin(distanceSquared*sin(worldTime/143.0)/1000.0)
float x = position.x
float om = sin(distanceSquared*sin(worldTime/256.0)/5000.0) * sin(worldTime/200.0)
return position
dp_varying highp float Depth = (ModelViewMatrix * Attrib_Position).z
void ivec4 si1 = si0 + ivec4(1, 1, 1, 1)
ivec4 si2 = si0 + ivec4(2, 2, 2, 2)
vec4 sw = Attrib_SkeletalWeight
vec4 SkeletalMatrix1 = Skeletal_Transform12[si0.x] * sw.x + Skeletal_Transform12[si0.y] * sw.y + Skeletal_Transform12[si0.z] * sw.z + Skeletal_Transform12[si0.w] * sw.w
vec4 SkeletalMatrix2 = Skeletal_Transform12[si1.x] * sw.x + Skeletal_Transform12[si1.y] * sw.y + Skeletal_Transform12[si1.z] * sw.z + Skeletal_Transform12[si1.w] * sw.w
vec4 SkeletalMatrix3 = Skeletal_Transform12[si2.x] * sw.x + Skeletal_Transform12[si2.y] * sw.y + Skeletal_Transform12[si2.z] * sw.z + Skeletal_Transform12[si2.w] * sw.w
mat4 SkeletalMatrix = mat4(SkeletalMatrix1, SkeletalMatrix2, SkeletalMatrix3, vec4(0.0, 0.0, 0.0, 1.0))
vec4 SkeletalVertex = Attrib_Position * SkeletalMatrix
dp_varying mediump vec2 TexCoord1 = Attrib_TexCoord0.xy
dp_varying mediump vec2 TexCoord2 = Attrib_TexCoord4.xy
uniform sampler2D Texture_First
uniform sampler2D Texture_Second
uniform mediump vec4 BloomColorSubtract
uniform sampler2D Texture_GammaRamps
uniform mediump float Saturation
uniform mediump vec4 ViewTintColor
uniform mediump vec4 UserVec1
uniform mediump vec4 UserVec2
uniform mediump float ColorFringe
uniform mediump vec2 PixelSize
vec4 float mulreduct = 1.0/maxspan
float minreduct = (1.0 / 128.0)
vec3 NW = dp_texture2D(Texture_First, TexCoord1 + (vec2(-1.0, -1.0) * PixelSize)).xyz
vec3 NE = dp_texture2D(Texture_First, TexCoord1 + (vec2(+1.0, -1.0) * PixelSize)).xyz
vec3 SW = dp_texture2D(Texture_First, TexCoord1 + (vec2(-1.0, +1.0) * PixelSize)).xyz
vec3 SE = dp_texture2D(Texture_First, TexCoord1 + (vec2(+1.0, +1.0) * PixelSize)).xyz
vec3 M = dp_texture2D(Texture_First, TexCoord1).xyz
vec3 luma = vec3(0.299, 0.587, 0.114)
float lNW = dot(NW, luma)
float lNE = dot(NE, luma)
float lSW = dot(SW, luma)
float lSE = dot(SE, luma)
float lM = dot(M, luma)
float lMin = min(lM, min(min(lNW, lNE), min(lSW, lSE)))
float lMax = max(lM, max(max(lNW, lNE), max(lSW, lSE)))
vec2 dir = vec2(-((lNW + lNE) - (lSW + lSE)), ((lNW + lSW) - (lNE + lSE)))
float rcp = 1.0/(min(abs(dir.x), abs(dir.y)) + max((lNW + lNE + lSW + lSE) * (0.25 * mulreduct), minreduct))
vec3 rA
vec3 rB
float lB = dot(rB, luma)
ret xyz = ((lB < lMin) || (lB > lMax)) ? rA : rB
ret a = 1.0
return ret
void float amount = distance(TexCoord1, vec2(.5f,.5f))
vec2 offset = vec2(amount*fringe,amount*fringe)
dp_FragColor xy = dp_texture2D(Texture_First, TexCoord1-offset).xy
dp_FragColor z = dp_texture2D(Texture_First, TexCoord1+offset).z
dp_FragColor = dp_texture2D(Texture_First, TexCoord1)
float sobel = 1.0
vec2 px = PixelSize
vec3 x1 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, px.y)).rgb
vec3 x2 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, 0.0)).rgb
vec3 x3 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x,-px.y)).rgb
vec3 x4 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, px.y)).rgb
vec3 x5 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, 0.0)).rgb
vec3 x6 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x,-px.y)).rgb
vec3 y1 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x,-px.y)).rgb
vec3 y2 = dp_texture2D(Texture_First, TexCoord1 + vec2(0.0,-px.y)).rgb
vec3 y3 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x,-px.y)).rgb
vec3 y4 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, px.y)).rgb
vec3 y5 = dp_texture2D(Texture_First, TexCoord1 + vec2(0.0, px.y)).rgb
vec3 y6 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, px.y)).rgb
float px1 = -1.0 * dot(vec3(0.3, 0.59, 0.11), x1)
float px2 = -2.0 * dot(vec3(0.3, 0.59, 0.11), x2)
float px3 = -1.0 * dot(vec3(0.3, 0.59, 0.11), x3)
float px4 = 1.0 * dot(vec3(0.3, 0.59, 0.11), x4)
float px5 = 2.0 * dot(vec3(0.3, 0.59, 0.11), x5)
float px6 = 1.0 * dot(vec3(0.3, 0.59, 0.11), x6)
float py1 = -1.0 * dot(vec3(0.3, 0.59, 0.11), y1)
float py2 = -2.0 * dot(vec3(0.3, 0.59, 0.11), y2)
float py3 = -1.0 * dot(vec3(0.3, 0.59, 0.11), y3)
float py4 = 1.0 * dot(vec3(0.3, 0.59, 0.11), y4)
float py5 = 2.0 * dot(vec3(0.3, 0.59, 0.11), y5)
float py6 = 1.0 * dot(vec3(0.3, 0.59, 0.11), y6)
dp_FragColor rgb = dp_FragColor.rgb * (1.0 + UserVec2.x) + vec3(max(0.0, sobel - UserVec2.z))*UserVec2.y
float rboost = max(0.0, (dp_FragColor.r - max(dp_FragColor.g, dp_FragColor.b))*(1.0 - Saturation))
dp_FragColor r = rboost
dp_FragColor g = dp_texture2D(Texture_GammaRamps, vec2(dp_FragColor.g, 0)).g
dp_FragColor b = dp_texture2D(Texture_GammaRamps, vec2(dp_FragColor.b, 0)).b
uniform myhalf Alpha
dp_FragColor rgb dp_FragColor vec4 tex2 = dp_texture2D(Texture_Second, TexCoord2)
dp_FragColor a dp_varying mediump vec2 TexCoord = Attrib_TexCoord0.xy
gl_Position = ModelViewProjectionMatrix * Attrib_Position
uniform mediump vec4 BloomBlur_Parameters
void vec2 tc = TexCoord
vec3 color = dp_texture2D(Texture_First, tc).rgb
dp_varying highp vec4 ModelViewProjectionPosition
uniform highp mat4 TexMatrix
vec2 SafeScreenTexCoord = ModelViewProjectionPosition.xy * ScreenScaleRefractReflectIW + ScreenCenterRefractReflect.xy
vec2 distort = DistortScaleRefractReflect.xy * VertexColor.a
vec4 refractcolor = mix(RefractColor, vec4(1.0, 1.0, 1.0, 1.0), VertexColor.a)
vec3 normal = dp_texture2D(Texture_Normal, (TexCoord + vec2(0.08, 0.08)*ClientTime*NormalmapScrollBlend.x*0.5)*NormalmapScrollBlend.y).rgb - vec3(1.0)
vec2 ScreenTexCoord = SafeScreenTexCoord + vec3(normalize(cast_myhalf3(normal))).xy * distort
float f = min(1.0, length(dp_texture2D(Texture_Refraction, ScreenTexCoord + vec2(0.01, 0.01)).rgb) / 0.05)
dp_varying highp vec3 EyeVector
uniform highp vec3 EyePosition
mat3 SkeletalNormalMatrix = mat3(cross(SkeletalMatrix[1].xyz, SkeletalMatrix[2].xyz), cross(SkeletalMatrix[2].xyz, SkeletalMatrix[0].xyz), cross(SkeletalMatrix[0].xyz, SkeletalMatrix[1].xyz))
vec3 SkeletalSVector = normalize(Attrib_TexCoord1.xyz * SkeletalNormalMatrix)
vec3 SkeletalTVector = normalize(Attrib_TexCoord2.xyz * SkeletalNormalMatrix)
vec3 SkeletalNormal = normalize(Attrib_TexCoord3.xyz * SkeletalNormalMatrix)
float reflectoffset = ReflectOffset * VertexColor.a
float reflectfactor = ReflectFactor * VertexColor.a
f f f ScreenTexCoord zw = mix(SafeScreenTexCoord.zw, ScreenTexCoord.zw, f)
float Fresnel = pow(min(1.0, 1.0 - float(normalize(EyeVector).z)), 2.0) * reflectfactor + reflectoffset
dp_varying mediump vec4 TexCoordSurfaceLightmap
dp_varying mediump vec3 CubeVector
dp_varying mediump vec3 LightVector
dp_varying highp vec4 EyeVectorFogDepth
dp_varying highp vec4 VectorS = (ModelViewMatrix * vec4(Attrib_TexCoord1.xyz, 0))
dp_varying highp vec4 VectorT = (ModelViewMatrix * vec4(Attrib_TexCoord2.xyz, 0))
dp_varying highp vec4 VectorR = (ModelViewMatrix * vec4(Attrib_TexCoord3.xyz, 0))
dp_varying highp vec3 EyeVectorModelSpace
uniform highp vec3 LightPosition
dp_varying highp vec4 ModelViewPosition
uniform highp vec3 LightDir
uniform highp vec4 FogPlane
dp_varying highp vec3 ShadowMapTC
dp_varying highp vec3 LightGridTC
dp_varying highp vec3 BounceGridTexCoord
uniform sampler2D Texture_Normal
uniform sampler2D Texture_Color
uniform sampler2D Texture_Gloss
uniform sampler2D Texture_Glow
uniform sampler2D Texture_SecondaryNormal
uniform sampler2D Texture_SecondaryColor
uniform sampler2D Texture_SecondaryGloss
uniform sampler2D Texture_SecondaryGlow
uniform sampler2D Texture_Pants
uniform sampler2D Texture_Shirt
uniform sampler2D Texture_FogHeightTexture
uniform sampler2D Texture_FogMask
uniform sampler2D Texture_Lightmap
uniform sampler2D Texture_Deluxemap
uniform sampler2D Texture_Reflection
uniform sampler2D Texture_ScreenNormalMap
uniform sampler2D Texture_ScreenDiffuse
uniform sampler2D Texture_ScreenSpecular
uniform mediump vec3 Color_Pants
uniform mediump vec3 Color_Shirt
uniform mediump vec3 FogColor
uniform highp float FogRangeRecip
uniform highp float FogPlaneViewDist
uniform highp float FogHeightFade
vec3 float FogPlaneVertexDist = EyeVectorFogDepth.w
float fogfrac = fogheightpixel.a
vec3 fc = FogColor
fc vec4 fogheightpixel = dp_texture2D(Texture_FogHeightTexture, vec2(1,1) + vec2(FogPlaneVertexDist, FogPlaneViewDist) * (-2.0 * FogHeightFade))
uniform mediump vec4 OffsetMapping_ScaleSteps
uniform mediump float OffsetMapping_Bias
uniform mediump float OffsetMapping_LodDistance
vec2 mediump float GuessLODFactor = min(1.0, OffsetMapping_LodDistance / EyeVectorFogDepth.z)
mediump float LODSteps = max(3.0, ceil(GuessLODFactor * OffsetMapping_ScaleSteps.y))
mediump float LODFactor = LODSteps / OffsetMapping_ScaleSteps.y
mediump vec4 ScaleSteps = vec4(OffsetMapping_ScaleSteps.x, LODSteps, 1.0 / LODSteps, OffsetMapping_ScaleSteps.w * LODFactor)
vec3 OffsetVector = vec3(normalize(EyeVectorFogDepth.xyz).xy * ScaleSteps.x * vec2(-1, 1), -1)
vec3 RT = vec3(vec2(TexCoord.xy - OffsetVector.xy*OffsetMapping_Bias), 1)
uniform sampler2D Texture_Attenuation
uniform samplerCube Texture_Cube
uniform sampler2DShadow Texture_ShadowMap2D
uniform samplerCube Texture_CubeProjection
uniform mediump vec4 ShadowMap_TextureScale
uniform mediump vec4 ShadowMap_Parameters
uniform highp mat4 BackgroundTexMatrix
uniform highp mat4 ModelViewMatrix
vec3 EyeRelative = EyePosition - Attrib_Position.xyz
EyeVectorFogDepth w = 0.0
Function Documentation
FogVertex()
vec3 FogVertex (vec4 surfacecolor)
for() [1/2]
for (i = 0.0)
for() [2/2]
OffsetVector for ()
fxaa()
vec4 fxaa (vec4 inColor, float maxspan)
main()
void main (void)
mix() [1/2]
return mix (fc , surfacecolor. rgb, dp_texture2D(Texture_FogMask, cast_myhalf2(length(EyeVectorModelSpace) *fogfrac *FogRangeRecip, 0.0)). r)
mix() [2/2]
return mix (fogheightpixel.rgb * fc, surfacecolor. rgb, dp_texture2D(Texture_FogMask, cast_myhalf2(length(EyeVectorModelSpace) *fogfrac *FogRangeRecip, 0.0)). r)
OffsetMapping()
vec2 OffsetMapping (vec2 TexCoord, vec2 dPdx, vec2 dPdy)
ShadowMapCompare()
float ShadowMapCompare (vec3 dir)
TrippyVertex()
vec4 TrippyVertex (vec4 position)
Variable Documentation
a
ret a = 1.0
Definition at line 296 of file shader_glsl.h.
Referenced by _Thread_AtomicAdd(), _Thread_AtomicAdd(), _Thread_AtomicDecRef(), _Thread_AtomicDecRef(), _Thread_AtomicGet(), _Thread_AtomicGet(), _Thread_AtomicIncRef(), _Thread_AtomicIncRef(), _Thread_AtomicSet(), _Thread_AtomicSet(), BufStr_SortStringsDOWN(), BufStr_SortStringsUP(), CL_DrawVideo(), CL_GeomLerp(), CL_UpdateEntityShading_Entity(), Cmd_Alias_f(), Cmd_ExecuteString(), Cmd_RestoreInitState(), Cmd_SaveInitState(), Cmd_UnAlias_f(), Con_CompleteCommandLine(), Curl_Curl_f(), doublecmp_withoffset(), dpvsimpledecode_convertpixels(), dpvsimpledecode_decompressimage(), DrawQ_GetTextColor(), fixtransparentpixels(), GL_ColorMask(), LHNETADDRESS_FromString(), LHNETADDRESS_ToString(), LoadPCX_BGRA(), LoadPCX_QWSkin(), M_Menu_Video_FindResolution(), Mathlib_Init(), Mod_Decompile_OBJ(), Mod_Decompile_SMD(), Mod_MakeSortedSurfaces_qsortfunc(), Mod_Mesh_IndexForVertex(), Mod_Q3BSP_LightPoint(), mul128(), NetConn_ChooseClientSocketForAddress(), NetConn_ChooseServerSocketForAddress(), Nicks_CutMatchesAlphaNumeric(), Nicks_CutMatchesNoSpaces(), Nicks_strncasecmp(), Nicks_strncasecmp_nospaces(), packetlog5cmp(), Portal_CheckBox(), PRVM_Prog_Load(), Q3PatchTesselateFloat(), R_DecalSystem_ApplySplatEntities(), R_DecalSystem_SplatEntities(), R_DecalSystem_SplatEntity(), R_DecalSystem_SplatTriangle(), R_DrawParticle_TransparentCallback(), R_DrawParticles(), r_explosion_start(), R_FillColors(), R_Q1BSP_GetLightInfo_comparefunc(), R_Shadow_LoadLightsFile(), R_Shadow_LoadWorldLights(), R_Shadow_MakeTextures_MakeCorona(), R_SkinFrame_GenerateTexturesFromQPixels(), R_SkinFrame_LoadInternalBGRA(), R_SortEntities_Compare(), R_StainNode(), RSurf_ActiveCustomEntity(), Sbar_DrawXNum(), SCR_DrawNetGraph_DrawGraph(), SCR_DrawTouchscreenOverlay(), skyspherecalc(), Squared3xCurveArea(), stringlistsort_cmp(), SV_PushMove(), testmul128(), V_CalcViewBlend(), V_MakeViewIsometric(), VID_SortModes_Compare(), VM_CL_R_PolygonVertex(), and VM_CL_RotateMoves().
Alpha
uniform myhalf Alpha
Definition at line 402 of file shader_glsl.h.
amount
void float amount = distance(TexCoord1, vec2(.5f,.5f))
Definition at line 305 of file shader_glsl.h.
Attrib_Color
dp_attribute vec4 Attrib_Color
Definition at line 95 of file shader_glsl.h.
Attrib_SkeletalIndex
uniform Skeletal_Transform12_UniformBlock dp_attribute vec4 Attrib_SkeletalIndex
Definition at line 111 of file shader_glsl.h.
Attrib_SkeletalWeight
dp_attribute vec4 Attrib_SkeletalWeight
Definition at line 112 of file shader_glsl.h.
Attrib_TexCoord0
dp_attribute vec4 Attrib_TexCoord0
Definition at line 96 of file shader_glsl.h.
Attrib_TexCoord1
dp_attribute vec3 Attrib_TexCoord1
Definition at line 97 of file shader_glsl.h.
Attrib_TexCoord2
dp_attribute vec3 Attrib_TexCoord2
Definition at line 98 of file shader_glsl.h.
Attrib_TexCoord3
dp_attribute vec3 Attrib_TexCoord3
Definition at line 99 of file shader_glsl.h.
Attrib_TexCoord4
dp_attribute vec4 Attrib_TexCoord4
Definition at line 100 of file shader_glsl.h.
b
dp_FragColor b = dp_texture2D(Texture_GammaRamps, vec2(dp_FragColor.b, 0)).b
Definition at line 386 of file shader_glsl.h.
Referenced by _Thread_CreateBarrier(), _Thread_DestroyBarrier(), _Thread_WaitBarrier(), BufStr_SortStringsDOWN(), BufStr_SortStringsUP(), CL_Beam_AddPolygons(), CL_Beam_CalculatePositions(), CL_Beams_SetupBuiltinTexture(), CL_DrawVideo(), CL_GeomLerp(), CL_NewBeam(), CL_NewParticle(), CL_RelinkBeams(), CL_Video_Init(), Con_MaskPrint(), convex_builder_add_point(), convex_builder_get_planes4f(), convex_builder_get_points3f(), convex_builder_initialize(), CSQC_Predraw(), CSQC_Think(), Curl_Begin(), Curl_Frame(), doublecmp_withoffset(), dpvsimpledecode_decompressimage(), DrawQ_GetTextColor(), DrawQ_Line(), fixtransparentpixels(), GL_ColorMask(), GL_ReadPixelsBGRA(), hz_bitstream_read_blocks_free(), hz_bitstream_read_blocks_read(), Image_HeightmapToNormalmap_BGRA(), jam_video(), Key_Bind_f(), Key_FindKeysForCommand(), Key_In_Bind_f(), Key_In_Unbind_f(), Key_Unbind_f(), KeyDown(), KeyUp(), LoadPCX_BGRA(), LoadTGA_BGRA(), M_UnbindCommand(), mdfour_tail(), Memory_Init(), Mod_Decompile_OBJ(), Mod_Decompile_SMD(), Mod_MakeSortedSurfaces_qsortfunc(), Mod_Mesh_IndexForVertex(), Mod_Q1BSP_LoadSplitSky(), Mod_Skeletal_AnimateVertices_Generic(), mul128(), Nicks_AddLastColor(), Nicks_CutMatchesAlphaNumeric(), Nicks_CutMatchesNoSpaces(), Nicks_strncasecmp(), Nicks_strncasecmp_nospaces(), packetlog5cmp(), Palette_Load(), Palette_SetupSpecialPalettes(), Portal_CheckBox(), PRVM_Prog_Load(), Q3PatchTesselateFloat(), R_BuildFogTexture(), R_DecalSystem_ApplySplatEntities(), R_DecalSystem_SplatEntities(), R_DecalSystem_SplatEntity(), R_DecalSystem_SplatTriangle(), r_explosion_start(), R_FillColors(), R_LoadTextureDDSFile(), R_ModulateColors(), R_Q1BSP_GetLightInfo_comparefunc(), R_SkinFrame_GenerateTexturesFromQPixels(), R_SkinFrame_LoadInternalBGRA(), R_SortEntities_Compare(), RSurf_ActiveCustomEntity(), RSurf_PrepareVerticesForBatch(), Sbar_DrawXNum(), SCR_CaptureVideo_ConvertFrame_BGRA_to_I420_flip(), SCR_CaptureVideo_Ogg_ConvertFrame_BGRA_to_YUV(), SCR_CaptureVideo_Ogg_SoundFrame(), SCR_DrawNetGraph_DrawGraph(), skyspherecalc(), Squared3xCurveArea(), stringlistsort_cmp(), SVBSP_AddPolygon(), SVBSP_AddPolygonNode(), SVBSP_Init(), SVBSP_InsertOccluderPolygonNodes(), Sys_Con_NearestColor(), testmul128(), and VID_SortModes_Compare().
BackgroundTexMatrix
uniform highp mat4 BackgroundTexMatrix
Definition at line 1105 of file shader_glsl.h.
BloomBlur_Parameters
uniform mediump vec4 BloomBlur_Parameters
Definition at line 499 of file shader_glsl.h.
BloomColorSubtract
uniform mediump vec4 BloomColorSubtract
Definition at line 234 of file shader_glsl.h.
BounceGridTexCoord
dp_varying highp vec3 BounceGridTexCoord
Definition at line 764 of file shader_glsl.h.
ClientTime
uniform highp float ClientTime
Definition at line 155 of file shader_glsl.h.
color
vec3 color = dp_texture2D(Texture_First, tc).rgb
Definition at line 505 of file shader_glsl.h.
Referenced by CL_LinkNetworkEntity(), CL_ParseParticleEffect(), CL_ParseTempEntity(), CL_ParticleEffect_Fallback(), CL_ParticleExplosion(), CL_SpawnDecalParticleForSurface(), Con_MaskPrint(), DrawQ_GetTextColor(), Mod_GenerateLightmaps_CreateLights(), Mod_GenerateLightmaps_LightmapSample(), Mod_GenerateLightmaps_LightPoint(), Mod_GenerateLightmaps_SamplePoint(), Nicks_AddLastColor(), R_CompleteLightPoint(), R_DrawCorona(), R_DrawEntityBBoxes_Callback(), R_DrawParticles(), R_RTLight_Update(), R_Shadow_BounceGrid_Slice(), R_Shadow_EditLights_Edit_f(), R_Shadow_EditLights_Spawn_f(), R_Shadow_GetRTLightInfo(), R_Shadow_LoadLightsFile(), R_Shadow_LoadWorldLights(), R_Shadow_LoadWorldLightsFromMap_LightArghliteTyrlite(), R_Shadow_UpdateWorldLight(), R_TimeReport_EndFrame(), Sbar_DrawNum(), Sbar_SortFrags(), SCR_DrawCenterString(), SV_PrepareEntityForSending(), SV_StartParticle(), VM_CL_particle(), VM_CL_te_explosion2(), and VM_SV_particle().
Color_Pants
uniform mediump vec3 Color_Pants
Definition at line 826 of file shader_glsl.h.
Color_Shirt
uniform mediump vec3 Color_Shirt
Definition at line 827 of file shader_glsl.h.
ColorFringe
uniform mediump float ColorFringe
Definition at line 250 of file shader_glsl.h.
CubeVector
dp_varying mediump vec3 CubeVector
Definition at line 718 of file shader_glsl.h.
Depth
dp_varying highp float Depth = (ModelViewMatrix * Attrib_Position).z
Definition at line 176 of file shader_glsl.h.
dir
dir = vec2(-((lNW + lNE) - (lSW + lSE)), ((lNW + lSW) - (lNE + lSE)))
Definition at line 281 of file shader_glsl.h.
Referenced by CL_Beam_AddQuad(), CL_Beam_CalculatePositions(), CL_ParseParticleEffect(), CL_ParseTempEntity(), CL_ParticleCube(), CL_ParticleEffect_Fallback(), CL_ParticleRain(), CL_UpdateEntityShading_Entity(), Collision_ClipTrace_Line_Sphere(), Collision_NewBrushFromPlanes(), FS_AddGameDirectory(), FS_AddGameHierarchy(), listdirectory(), M_Menu_Options_AdjustSliders(), M_Menu_Options_ColorControl_AdjustSliders(), M_Menu_Options_Effects_AdjustSliders(), M_Menu_Options_Graphics_AdjustSliders(), M_Menu_Video_AdjustSliders(), M_ModList_Draw(), M_NetStart_Change(), Mod_GenerateLightmaps_GridSample(), Mod_GenerateLightmaps_LightmapSample(), Mod_GenerateLightmaps_LightPoint(), ModList_RebuildList(), R_Bloom_MakeTexture(), R_DrawParticle_TransparentCallback(), R_RotateSprite(), RotatePointAroundVector(), SV_FlyMove(), SV_NudgeOutOfSolid_PivotIsKnownGood(), SV_SetIdealPitch(), SV_StartParticle(), VM_CL_particle(), VM_CL_SpawnParticle(), VM_CL_SpawnParticleDelayed(), VM_SV_aim(), and VM_SV_particle().
distanceSquared
vec4 worldTime position float distanceSquared = (position.x * position.x + position.z * position.z)
Definition at line 163 of file shader_glsl.h.
distort
vec4 distort = DistortScaleRefractReflect.xy * VertexColor.a
Definition at line 568 of file shader_glsl.h.
dp_FragColor
dp_FragColor dp_FragColor = dp_texture2D(Texture_First, TexCoord1)
Definition at line 310 of file shader_glsl.h.
EyePosition
uniform highp vec3 EyePosition
Definition at line 604 of file shader_glsl.h.
EyeRelative
vec3 EyeRelative = EyePosition - Attrib_Position.xyz
Definition at line 1137 of file shader_glsl.h.
EyeVector
dp_varying highp vec3 EyeVector
Definition at line 601 of file shader_glsl.h.
EyeVectorFogDepth
dp_varying highp vec4 EyeVectorFogDepth
Definition at line 726 of file shader_glsl.h.
EyeVectorModelSpace
dp_varying highp vec3 EyeVectorModelSpace
Definition at line 735 of file shader_glsl.h.
f
float float f = min(1.0, length(dp_texture2D(Texture_Refraction, ScreenTexCoord + vec2(0.01, 0.01)).rgb) / 0.05)
Definition at line 586 of file shader_glsl.h.
Referenced by AngleVectorsDuke3DFLU(), buf2file(), BuffBigFloat(), BuffLittleFloat(), CL_AddQWCTFFlagModel(), CL_ClientMovement_Move(), CL_ClientMovement_Physics_PM_Accelerate(), CL_ClientMovement_Physics_PM_AirAccelerate(), CL_ClientMovement_Physics_Swim(), CL_ClientMovement_UpdateStatus(), CL_Input(), CL_LerpPoint(), CL_ParticleEffect_Fallback(), CL_PlayDemo(), CL_ReadDemoMessage(), CL_RelinkLightFlashes(), CL_RotateMoves(), CL_UpdateScreen(), CL_WriteDemoMessage(), Cmd_AddCommand(), Cmd_Exec(), Cmd_RestoreInitState(), Cmd_SaveInitState(), Collision_TraceBrushBrushFloat(), Collision_TraceLineBrushFloat(), Collision_TraceLineTriangleFloat(), Con_CheckResize(), convex_builder_add_point(), convex_builder_get_planes4f(), Crypto_KeyGen_f(), Crypto_KeyGen_Finished(), Crypto_LoadFile(), Crypto_SavePubKeyTextFile(), Curl_Begin(), Cvar_WriteVariables(), EntityFrame_CL_ReadFrame(), EntityFrame_Clear(), EntityFrame_FetchFrame(), file2buf(), FS_SysCheckGameDir(), getdrawfont(), GetMapList(), Host_SaveConfig(), Image_Resample32Lerp(), Image_Resample32LerpLine(), JPEG_LoadImage_BGRA(), Key_WriteBindings(), LoadConChars_BGRA(), LoadFont_f(), loadimagepixelsbgra(), LoadLMP_BGRA(), LoadPCX_BGRA(), LoadPCX_PaletteOnly(), LoadPCX_QWSkin(), LoadTGA_BGRA(), LoadWAL_BGRA(), LoadWAL_GetMetadata(), M_Main_Draw(), M_Menu_Options_AdjustSliders(), M_Menu_Options_ColorControl_AdjustSliders(), M_MultiPlayer_Draw(), M_ScanSaves(), M_Setup_Draw(), M_SinglePlayer_Draw(), Memory_Init_Commands(), Mod_BSP_FindNonSolidLocation_r(), Mod_BSP_FindNonSolidLocation_r_Triangle(), Mod_BuildTextureVectorsFromNormals(), Mod_CollisionBIH_TraceBrush(), Mod_CollisionBIH_TraceLineShared(), Mod_DARKPLACESMODEL_Load(), Mod_GenerateLightmaps_LightmapSample(), Mod_INTERQUAKEMODEL_Load(), Mod_LoadQ3Shaders(), Mod_MD3_AnimateVertices(), Mod_MDL_AnimateVertices(), Mod_MDL_LoadFrames(), Mod_Skeletal_AnimateVertices_Generic(), Mod_ZYMOTICMODEL_Load(), MSG_ReadBigFloat(), MSG_ReadLittleFloat(), MSG_WriteAngle(), MSG_WriteAngle16i(), MSG_WriteAngle32f(), MSG_WriteAngle8i(), MSG_WriteCoord(), MSG_WriteCoord13i(), MSG_WriteCoord16i(), MSG_WriteCoord32f(), MSG_WriteFloat(), OGG_GetSamplesFloat(), particletextureblotch(), Portal_RecursiveFindLeafForFlow(), PRVM_CallProfile(), PRVM_ED_FindFunctionOffset(), PRVM_ED_Write(), PRVM_ED_WriteGlobals(), PRVM_EnterFunction(), PRVM_LeaveFunction(), PRVM_Profile(), PRVM_Prog_Load(), PRVM_ShortStackTrace(), PRVM_StackTrace(), PRVM_UglyValueString(), PRVM_ValueString(), Q3PatchTesselation(), R_BuildFogHeightTexture(), R_DecalSystem_SplatTriangle(), R_DrawParticles(), R_DrawPortals(), R_EvaluateQ3WaveFunc(), R_InitParticleTexture(), R_LoadQWSkin(), R_LoadTextureDDSFile(), R_ScissorForBBox(), R_Shadow_BounceGrid_AssignPhotons_Task(), R_Shadow_BounceGrid_ConvertPixelsAndUpload(), R_Shadow_PrepareLight(), R_Shadow_PrepareLights(), R_tcMod_ApplyToMatrix(), RSurf_PrepareVerticesForBatch(), Sbar_DrawFace(), Sbar_DrawFrags(), Sbar_ShowFPS(), SCR_DrawLoadingScreen(), shadebubble(), SND_Spatialize_WithSfx(), SV_PrepareEntityForSending(), SV_Savegame_to(), SV_Viewframe_f(), SV_WriteDemoMessage(), VID_Shared_BuildJoyState_Finish(), VID_UpdateGamma(), VM_CL_ambientsound(), VM_CL_getstatf(), VM_CL_pointparticles(), VM_CL_project(), VM_CL_R_SetView(), VM_CL_unproject(), VM_find(), VM_findchain(), VM_findchainflags(), VM_findchainfloat(), VM_findflags(), VM_findfloat(), VM_FrameBlendFromFrameGroupBlend(), VM_loadfont(), VM_max(), VM_min(), VM_normalize(), VM_physics_addforce(), VM_physics_addtorque(), VM_physics_enable(), VM_precache_pic(), VM_rint(), VM_sprintf(), VM_SV_UpdateCustomStats(), and XMP_GetSamplesFloat().
fc
vec3 fc = FogColor
Definition at line 841 of file shader_glsl.h.
float
precision highp float
Definition at line 45 of file shader_glsl.h.
Referenced by CL_DrawVideo(), CL_ParseClientdata(), CSQC_ReadEntities(), LoadSubtitles(), M_Draw(), M_Options_ColorControl_Draw(), Mod_AllocSurfMesh(), Mod_GenerateLightmaps_SamplePoint(), Mod_INTERQUAKEMODEL_Load(), Mod_Q1BSP_LoadFaces(), Mod_VBSP_LoadFaces(), PolygonF_QuadForPlane(), Q3PatchTesselateFloat(), R_Bloom_MakeTexture(), R_DrawParticle_TransparentCallback(), R_ExplosionVert(), R_LoadTextureDDSFile(), R_Shadow_ChooseSidesFromBox(), R_Shadow_CullFrustumSides(), R_Shadow_DrawLightShadowMaps(), R_TimeReport_EndFrame(), R_Viewport_InitRectSideView(), S_SoundLength(), S_UpdateAmbientSounds(), SCR_DrawLoadingScreen(), SCR_DrawScreen(), SndSys_Init(), SV_ApplyClientMove(), SV_ReadClientMove(), SVBSP_PlaneFromPoints(), Sys_Con_NearestColor(), and V_MakeViewIsometric().
FogColor
uniform mediump vec3 FogColor
Definition at line 828 of file shader_glsl.h.
fogfrac
fogfrac = fogheightpixel.a
Definition at line 840 of file shader_glsl.h.
Referenced by RSurf_FogPoint(), and RSurf_FogVertex().
FogHeightFade
uniform highp float FogHeightFade
Definition at line 833 of file shader_glsl.h.
Referenced by RSurf_FogPoint(), and RSurf_FogVertex().
fogheightpixel
fc vec4 fogheightpixel = dp_texture2D(Texture_FogHeightTexture, vec2(1,1) + vec2(FogPlaneVertexDist, FogPlaneViewDist) * (-2.0 * FogHeightFade))
Definition at line 846 of file shader_glsl.h.
FogPlane
uniform highp vec4 FogPlane
Definition at line 754 of file shader_glsl.h.
FogPlaneVertexDist
vec3 float FogPlaneVertexDist = EyeVectorFogDepth.w
Definition at line 839 of file shader_glsl.h.
Referenced by RSurf_FogPoint(), and RSurf_FogVertex().
FogPlaneViewDist
uniform highp float FogPlaneViewDist
Definition at line 832 of file shader_glsl.h.
Referenced by RSurf_FogPoint(), and RSurf_FogVertex().
FogRangeRecip
uniform highp float FogRangeRecip
Definition at line 831 of file shader_glsl.h.
Fresnel
float Fresnel = pow(min(1.0, 1.0 - float(normalize(EyeVector).z)), 2.0) * reflectfactor + reflectoffset
Definition at line 701 of file shader_glsl.h.
Referenced by R_Shadow_BounceGrid_TracePhotons_Shot().
g
dp_FragColor g = dp_texture2D(Texture_GammaRamps, vec2(dp_FragColor.g, 0)).g
Definition at line 385 of file shader_glsl.h.
Referenced by CL_Beams_SetupBuiltinTexture(), CL_NewParticle(), Con_MaskPrint(), dpvsimpledecode_decompressimage(), DrawQ_GetTextColor(), DrawQ_Line(), fixtransparentpixels(), fractalnoise(), fractalnoisequick(), GL_ColorMask(), M_Draw(), Mod_Mesh_IndexForVertex(), Mod_Q1BSP_LoadSplitSky(), Nicks_AddLastColor(), R_DecalSystem_ApplySplatEntities(), R_DecalSystem_SplatEntities(), R_DecalSystem_SplatEntity(), R_DecalSystem_SplatTriangle(), r_explosion_start(), R_FillColors(), R_LoadTextureDDSFile(), R_ModulateColors(), RSurf_ActiveCustomEntity(), Sbar_DrawXNum(), SCR_DrawNetGraph_DrawGraph(), Sys_Con_NearestColor(), VM_FrameBlendFromFrameGroupBlend(), and while().
gl_Position
gl_Position = ModelViewProjectionMatrix * Attrib_Position
Definition at line 493 of file shader_glsl.h.
GuessLODFactor
vec2 mediump float GuessLODFactor = min(1.0, OffsetMapping_LodDistance / EyeVectorFogDepth.z)
Definition at line 873 of file shader_glsl.h.
lB
float lB = dot(rB, luma)
Definition at line 293 of file shader_glsl.h.
LightDir
uniform highp vec3 LightDir
Definition at line 752 of file shader_glsl.h.
LightGridTC
dp_varying highp vec3 LightGridTC
Definition at line 761 of file shader_glsl.h.
LightPosition
uniform highp vec3 LightPosition
Definition at line 743 of file shader_glsl.h.
LightVector
dp_varying mediump vec3 LightVector
Definition at line 722 of file shader_glsl.h.
lM
float lM = dot(M, luma)
Definition at line 276 of file shader_glsl.h.
lMax
float lMax = max(lM, max(max(lNW, lNE), max(lSW, lSE)))
Definition at line 278 of file shader_glsl.h.
lMin
float lMin = min(lM, min(min(lNW, lNE), min(lSW, lSE)))
Definition at line 277 of file shader_glsl.h.
lNE
float lNE = dot(NE, luma)
Definition at line 273 of file shader_glsl.h.
lNW
float lNW = dot(NW, luma)
Definition at line 272 of file shader_glsl.h.
LODFactor
mediump float LODFactor = LODSteps / OffsetMapping_ScaleSteps.y
Definition at line 880 of file shader_glsl.h.
LODSteps
mediump float LODSteps = max(3.0, ceil(GuessLODFactor * OffsetMapping_ScaleSteps.y))
Definition at line 876 of file shader_glsl.h.
lSE
float lSE = dot(SE, luma)
Definition at line 275 of file shader_glsl.h.
lSW
float lSW = dot(SW, luma)
Definition at line 274 of file shader_glsl.h.
luma
vec3 luma = vec3(0.299, 0.587, 0.114)
Definition at line 271 of file shader_glsl.h.
M
vec3 M = dp_texture2D(Texture_First, TexCoord1).xyz
Definition at line 268 of file shader_glsl.h.
minreduct
float minreduct = (1.0 / 128.0)
Definition at line 261 of file shader_glsl.h.
ModelViewMatrix
uniform highp mat4 ModelViewMatrix
Definition at line 1107 of file shader_glsl.h.
ModelViewPosition
dp_varying highp vec4 ModelViewPosition
Definition at line 744 of file shader_glsl.h.
ModelViewProjectionMatrix
uniform highp mat4 ModelViewProjectionMatrix
Definition at line 148 of file shader_glsl.h.
ModelViewProjectionPosition
dp_varying highp vec4 ModelViewProjectionPosition
Definition at line 518 of file shader_glsl.h.
mulreduct
vec4 float mulreduct = 1.0/maxspan
Definition at line 260 of file shader_glsl.h.
n
void n
Initial value:
{\n",
"   vec4 Skeletal_Transform12[768]
Definition at line 4 of file shader_glsl.h.
NE
vec3 NE = dp_texture2D(Texture_First, TexCoord1 + (vec2(+1.0, -1.0) * PixelSize)).xyz
Definition at line 265 of file shader_glsl.h.
normal
vec3 normal = dp_texture2D(Texture_Normal, (TexCoord + vec2(0.08, 0.08)*ClientTime*NormalmapScrollBlend.x*0.5)*NormalmapScrollBlend.y).rgb - vec3(1.0)
Definition at line 575 of file shader_glsl.h.
Referenced by BoxPlaneCornerDistances_Separate(), BoxPlaneCorners_Separate(), CL_SelectTraceLine(), CL_SpawnDecalParticleForSurface(), ClipVelocity(), Collision_NewBrushFromPlanes(), furthestplanedist_float(), Mod_BuildTextureVectorsFromNormals(), Mod_GenerateLightmaps_CreateTriangleInformation(), Mod_GenerateLightmaps_LightmapSample(), Mod_GenerateLightmaps_SamplePoint(), Mod_GenerateLightmaps_VertexSample(), Mod_Q1BSP_TraceLineAgainstSurfacesFindTextureOnNode(), nearestplanedist_float(), Portal_CheckPolygon(), Portal_PortalThroughPortalPlanes(), Portal_RecursiveFlow(), Portal_RecursiveFlowSearch(), Portal_Visibility(), R_CalcBeam_Vertex3f(), R_Shadow_ChooseSidesFromBox(), R_Viewport_ApplyNearClipPlaneFloatGL(), R_Water_AddWaterPlane(), RSurf_PrepareVerticesForBatch(), shadebubble(), and VM_getsurfacenormal().
NW
vec3 NW = dp_texture2D(Texture_First, TexCoord1 + (vec2(-1.0, -1.0) * PixelSize)).xyz
Definition at line 264 of file shader_glsl.h.
offset
vec2 offset = vec2(amount*fringe,amount*fringe)
Definition at line 306 of file shader_glsl.h.
OffsetMapping_Bias
uniform mediump float OffsetMapping_Bias
Definition at line 862 of file shader_glsl.h.
OffsetMapping_LodDistance
uniform mediump float OffsetMapping_LodDistance
Definition at line 864 of file shader_glsl.h.
OffsetMapping_ScaleSteps
uniform mediump vec4 OffsetMapping_ScaleSteps
Definition at line 861 of file shader_glsl.h.
OffsetVector
vec2 OffsetVector = vec3(normalize(EyeVectorFogDepth.xyz).xy * ScaleSteps.x * vec2(-1, 1), -1)
Definition at line 893 of file shader_glsl.h.
om
float om = sin(distanceSquared*sin(worldTime/256.0)/5000.0) * sin(worldTime/200.0)
Definition at line 167 of file shader_glsl.h.
PixelSize
uniform mediump vec2 PixelSize
Definition at line 252 of file shader_glsl.h.
position
return position
Definition at line 170 of file shader_glsl.h.
Referenced by CDAudio_StartPlaylist(), CDAudio_StopPlaylistTrack(), and FS_Seek().
px
vec2 px = PixelSize
Definition at line 324 of file shader_glsl.h.
Referenced by CL_DrawVideo(), CL_NewParticle(), Q3PatchTesselateFloat(), VID_TouchscreenArea(), and VID_TouchscreenCursor().
px1
float px1 = -1.0 * dot(vec3(0.3, 0.59, 0.11), x1)
Definition at line 337 of file shader_glsl.h.
px2
float px2 = -2.0 * dot(vec3(0.3, 0.59, 0.11), x2)
Definition at line 338 of file shader_glsl.h.
px3
float px3 = -1.0 * dot(vec3(0.3, 0.59, 0.11), x3)
Definition at line 339 of file shader_glsl.h.
px4
float px4 = 1.0 * dot(vec3(0.3, 0.59, 0.11), x4)
Definition at line 340 of file shader_glsl.h.
px5
float px5 = 2.0 * dot(vec3(0.3, 0.59, 0.11), x5)
Definition at line 341 of file shader_glsl.h.
px6
float px6 = 1.0 * dot(vec3(0.3, 0.59, 0.11), x6)
Definition at line 342 of file shader_glsl.h.
py1
float py1 = -1.0 * dot(vec3(0.3, 0.59, 0.11), y1)
Definition at line 343 of file shader_glsl.h.
py2
float py2 = -2.0 * dot(vec3(0.3, 0.59, 0.11), y2)
Definition at line 344 of file shader_glsl.h.
py3
float py3 = -1.0 * dot(vec3(0.3, 0.59, 0.11), y3)
Definition at line 345 of file shader_glsl.h.
py4
float py4 = 1.0 * dot(vec3(0.3, 0.59, 0.11), y4)
Definition at line 346 of file shader_glsl.h.
py5
float py5 = 2.0 * dot(vec3(0.3, 0.59, 0.11), y5)
Definition at line 347 of file shader_glsl.h.
py6
float py6 = 1.0 * dot(vec3(0.3, 0.59, 0.11), y6)
Definition at line 348 of file shader_glsl.h.
r
dp_FragColor r = rboost
Definition at line 375 of file shader_glsl.h.
Referenced by _Thread_CreateThread(), CL_Beams_SetupBuiltinTexture(), CL_GetExtendedTagInfo(), CL_NewParticle(), CL_ParticleEffect_Fallback(), CL_ParticleExplosion(), CL_ReadPointFile_f(), CL_RotateMoves(), CL_UpdateNetworkEntity(), CL_VM_Event_Sound(), CL_VM_GetEntitySoundOrigin(), CL_VM_InputEvent(), CL_VM_Parse_TempEntity(), CleanURL(), Con_MaskPrint(), DrawQ_GetTextColor(), DrawQ_Line(), fixtransparentpixels(), Font_LoadSize(), GL_ColorMask(), GL_ReadPixelsBGRA(), Image_Resample32Lerp(), M_Menu_Video_AdjustSliders(), Math_crandomf(), Math_rand64(), Math_randomf(), Math_randomrangef(), Math_randomrangei(), Math_RandomSeed_FromInts(), Math_RandomSeed_Reset(), Matrix4x4_ToOrigin3Quat4Float(), Mod_MakeSortedSurfaces_qsortfunc(), Mod_Mesh_IndexForVertex(), Mod_Q1BSP_Load(), Mod_Q1BSP_LoadSplitSky(), Mod_Q2BSP_Load(), NetConn_AddCryptoFlag(), Nicks_AddLastColor(), noise4f(), PRVM_ConsoleCommand(), QW_CL_NextUpload_f(), R_BlendFuncFlags(), R_Bloom_MakeTexture(), R_BuildFogTexture(), R_DecalSystem_ApplySplatEntities(), R_DecalSystem_SplatEntities(), R_DecalSystem_SplatEntity(), R_DecalSystem_SplatTriangle(), r_explosion_start(), R_FillColors(), R_LoadTextureDDSFile(), R_ModulateColors(), R_RenderTarget_FreeUnused(), R_RenderTarget_Get(), R_ReplaceWorldTexture_f(), RSurf_ActiveCustomEntity(), Sbar_DrawGauge(), Sbar_DrawXNum(), SV_GetExtendedTagInfo(), Sys_Con_NearestColor(), Thread_WaitSemaphore(), VID_Shared_BuildJoyState_Finish(), and VM_M_getresolution().
rA
vec3 rA
Initial value:
= (1.0/2.0) * (\n",
"       dp_texture2D(Texture_First, TexCoord1 + dir * (1.0/3.0 - 0.5)).xyz +\n",
"       dp_texture2D(Texture_First, TexCoord1 + dir * (2.0/3.0 - 0.5)).xyz)
Definition at line 287 of file shader_glsl.h.
rB
vec3 rB
Initial value:
= rA * (1.0/2.0) + (1.0/4.0) * (\n",
"       dp_texture2D(Texture_First, TexCoord1 + dir * (0.0/3.0 - 0.5)).xyz +\n",
"       dp_texture2D(Texture_First, TexCoord1 + dir * (3.0/3.0 - 0.5)).xyz)
Definition at line 290 of file shader_glsl.h.
rboost
float rboost = max(0.0, (dp_FragColor.r - max(dp_FragColor.g, dp_FragColor.b))*(1.0 - Saturation))
Definition at line 373 of file shader_glsl.h.
rcp
float rcp = 1.0/(min(abs(dir.x), abs(dir.y)) + max((lNW + lNE + lSW + lSE) * (0.25 * mulreduct), minreduct))
Definition at line 282 of file shader_glsl.h.
reflectfactor
float reflectfactor = ReflectFactor * VertexColor.a
Definition at line 671 of file shader_glsl.h.
reflectoffset
float reflectoffset = ReflectOffset * VertexColor.a
Definition at line 670 of file shader_glsl.h.
refractcolor
vec4 refractcolor = mix(RefractColor, vec4(1.0, 1.0, 1.0, 1.0), VertexColor.a)
Definition at line 569 of file shader_glsl.h.
Referenced by R_Shadow_BounceGrid_TracePhotons_Shot().
ret
return ret
Definition at line 297 of file shader_glsl.h.
Referenced by CD_f(), CL_GetTagMatrix(), CL_VM_TransformView(), Cmd_ExecuteAlias(), COM_ChangeGameTypeForGameDirs(), Crypto_ServerParsePacket(), CURL_fwrite(), FS_CheckGameDir(), FS_Inflate(), Image_WriteTGABGR_preflipped(), Image_WriteTGABGRA(), Mod_Q1BSP_RecursiveHullCheck(), Mod_Q3BSP_TraceLineOfSight_RecursiveNodeCheck(), NetConn_ClientParsePacket(), NetConn_ServerParsePacket(), NetConn_Write(), OGG_GetSamplesFloat(), OGG_LoadVorbisFile(), R_SaveTextureDDSFile(), SCR_ScreenShot(), SV_GetTagMatrix(), VM_cvar_type(), VM_findkeysforcommand(), and VM_uri_get().
rgb
dp_FragColor rgb = dp_FragColor.rgb * (1.0 + UserVec2.x) + vec3(max(0.0, sobel - UserVec2.z))*UserVec2.y
Definition at line 356 of file shader_glsl.h.
Referenced by Mod_Q3BSP_LoadLightmaps(), VID_ApplyGammaToColor(), VM_drawcharacter(), VM_drawcolorcodedstring(), VM_drawfill(), VM_drawline(), VM_drawpic(), VM_drawrotpic(), VM_drawstring(), and VM_drawsubpic().
RT
OffsetVector RT = vec3(vec2(TexCoord.xy - OffsetVector.xy*OffsetMapping_Bias), 1)
Definition at line 894 of file shader_glsl.h.
SafeScreenTexCoord
vec4 SafeScreenTexCoord = ModelViewProjectionPosition.xy * ScreenScaleRefractReflectIW + ScreenCenterRefractReflect.xy
Definition at line 566 of file shader_glsl.h.
Saturation
uniform mediump float Saturation
Definition at line 240 of file shader_glsl.h.
ScaleSteps
mediump vec4 ScaleSteps = vec4(OffsetMapping_ScaleSteps.x, LODSteps, 1.0 / LODSteps, OffsetMapping_ScaleSteps.w * LODFactor)
Definition at line 881 of file shader_glsl.h.
ScreenTexCoord
vec4 ScreenTexCoord = SafeScreenTexCoord + vec3(normalize(cast_myhalf3(normal))).xy * distort
Definition at line 577 of file shader_glsl.h.
SE
vec3 SE = dp_texture2D(Texture_First, TexCoord1 + (vec2(+1.0, +1.0) * PixelSize)).xyz
Definition at line 267 of file shader_glsl.h.
ShadowMap_Parameters
uniform mediump vec4 ShadowMap_Parameters
Definition at line 935 of file shader_glsl.h.
ShadowMap_TextureScale
uniform mediump vec4 ShadowMap_TextureScale
Definition at line 934 of file shader_glsl.h.
ShadowMapTC
dp_varying highp vec3 ShadowMapTC
Definition at line 757 of file shader_glsl.h.
si1
void ivec4 si1 = si0 + ivec4(1, 1, 1, 1)
Definition at line 182 of file shader_glsl.h.
si2
ivec4 si2 = si0 + ivec4(2, 2, 2, 2)
Definition at line 183 of file shader_glsl.h.
SkeletalMatrix
mat4 SkeletalMatrix = mat4(SkeletalMatrix1, SkeletalMatrix2, SkeletalMatrix3, vec4(0.0, 0.0, 0.0, 1.0))
Definition at line 188 of file shader_glsl.h.
SkeletalMatrix1
vec4 SkeletalMatrix1 = Skeletal_Transform12[si0.x] * sw.x + Skeletal_Transform12[si0.y] * sw.y + Skeletal_Transform12[si0.z] * sw.z + Skeletal_Transform12[si0.w] * sw.w
Definition at line 185 of file shader_glsl.h.
SkeletalMatrix2
vec4 SkeletalMatrix2 = Skeletal_Transform12[si1.x] * sw.x + Skeletal_Transform12[si1.y] * sw.y + Skeletal_Transform12[si1.z] * sw.z + Skeletal_Transform12[si1.w] * sw.w
Definition at line 186 of file shader_glsl.h.
SkeletalMatrix3
vec4 SkeletalMatrix3 = Skeletal_Transform12[si2.x] * sw.x + Skeletal_Transform12[si2.y] * sw.y + Skeletal_Transform12[si2.z] * sw.z + Skeletal_Transform12[si2.w] * sw.w
Definition at line 187 of file shader_glsl.h.
SkeletalNormal
vec3 SkeletalNormal = normalize(Attrib_TexCoord3.xyz * SkeletalNormalMatrix)
Definition at line 622 of file shader_glsl.h.
SkeletalNormalMatrix
mat3 SkeletalNormalMatrix = mat3(cross(SkeletalMatrix[1].xyz, SkeletalMatrix[2].xyz), cross(SkeletalMatrix[2].xyz, SkeletalMatrix[0].xyz), cross(SkeletalMatrix[0].xyz, SkeletalMatrix[1].xyz))
Definition at line 618 of file shader_glsl.h.
SkeletalSVector
vec3 SkeletalSVector = normalize(Attrib_TexCoord1.xyz * SkeletalNormalMatrix)
Definition at line 620 of file shader_glsl.h.
SkeletalTVector
vec3 SkeletalTVector = normalize(Attrib_TexCoord2.xyz * SkeletalNormalMatrix)
Definition at line 621 of file shader_glsl.h.
SkeletalVertex
vec4 SkeletalVertex = Attrib_Position * SkeletalMatrix
Definition at line 189 of file shader_glsl.h.
sobel
sobel = 1.0
Definition at line 321 of file shader_glsl.h.
sw
vec4 sw = Attrib_SkeletalWeight
Definition at line 184 of file shader_glsl.h.
Referenced by DrawQ_String_Scale(), DrawQ_TextWidth_UntilWidth_TrackColors_Scale(), Mod_Skeletal_BuildTransforms(), RSurf_PrepareVerticesForBatch(), and SCR_DrawLoadingScreen().
SW
vec3 SW = dp_texture2D(Texture_First, TexCoord1 + (vec2(-1.0, +1.0) * PixelSize)).xyz
Definition at line 266 of file shader_glsl.h.
tc
tc = TexCoord
Definition at line 504 of file shader_glsl.h.
Referenced by R_DecalSystem_SplatTriangle(), SCR_CaptureVideo_Ogg_BeginVideo(), and VM_CL_R_PolygonVertex().
tex2
dp_FragColor rgb dp_FragColor vec4 tex2 = dp_texture2D(Texture_Second, TexCoord2)
Definition at line 460 of file shader_glsl.h.
TexCoord
return TexCoord = Attrib_TexCoord0.xy
Definition at line 487 of file shader_glsl.h.
TexCoord1
dp_varying mediump vec2 TexCoord1 = Attrib_TexCoord0.xy
Definition at line 216 of file shader_glsl.h.
TexCoord2
dp_varying mediump vec2 TexCoord2 = Attrib_TexCoord4.xy
Definition at line 217 of file shader_glsl.h.
TexCoordSurfaceLightmap
dp_varying mediump vec4 TexCoordSurfaceLightmap
Definition at line 712 of file shader_glsl.h.
TexMatrix
uniform highp mat4 TexMatrix
Definition at line 519 of file shader_glsl.h.
Texture_Attenuation
uniform sampler2D Texture_Attenuation
Definition at line 915 of file shader_glsl.h.
Texture_Color
uniform sampler2D Texture_Color
Definition at line 782 of file shader_glsl.h.
Texture_Cube
uniform samplerCube Texture_Cube
Definition at line 916 of file shader_glsl.h.
Texture_CubeProjection
uniform samplerCube Texture_CubeProjection
Definition at line 930 of file shader_glsl.h.
Texture_Deluxemap
uniform sampler2D Texture_Deluxemap
Definition at line 809 of file shader_glsl.h.
Texture_First
uniform sampler2D Texture_First
Definition at line 231 of file shader_glsl.h.
Texture_FogHeightTexture
uniform sampler2D Texture_FogHeightTexture
Definition at line 801 of file shader_glsl.h.
Texture_FogMask
uniform sampler2D Texture_FogMask
Definition at line 803 of file shader_glsl.h.
Texture_GammaRamps
uniform sampler2D Texture_GammaRamps
Definition at line 237 of file shader_glsl.h.
Texture_Gloss
uniform sampler2D Texture_Gloss
Definition at line 783 of file shader_glsl.h.
Texture_Glow
uniform sampler2D Texture_Glow
Definition at line 785 of file shader_glsl.h.
Texture_Lightmap
uniform sampler2D Texture_Lightmap
Definition at line 806 of file shader_glsl.h.
Texture_Normal
uniform sampler2D Texture_Normal
Definition at line 781 of file shader_glsl.h.
Texture_Pants
uniform sampler2D Texture_Pants
Definition at line 796 of file shader_glsl.h.
Texture_Reflection
uniform sampler2D Texture_Reflection
Definition at line 812 of file shader_glsl.h.
Texture_ScreenDiffuse
uniform sampler2D Texture_ScreenDiffuse
Definition at line 822 of file shader_glsl.h.
Texture_ScreenNormalMap
uniform sampler2D Texture_ScreenNormalMap
Definition at line 816 of file shader_glsl.h.
Texture_ScreenSpecular
uniform sampler2D Texture_ScreenSpecular
Definition at line 823 of file shader_glsl.h.
Texture_Second
uniform sampler2D Texture_Second
Definition at line 233 of file shader_glsl.h.
Texture_SecondaryColor
uniform sampler2D Texture_SecondaryColor
Definition at line 789 of file shader_glsl.h.
Texture_SecondaryGloss
uniform sampler2D Texture_SecondaryGloss
Definition at line 790 of file shader_glsl.h.
Texture_SecondaryGlow
uniform sampler2D Texture_SecondaryGlow
Definition at line 792 of file shader_glsl.h.
Texture_SecondaryNormal
uniform sampler2D Texture_SecondaryNormal
Definition at line 788 of file shader_glsl.h.
Texture_ShadowMap2D
uniform sampler2D Texture_ShadowMap2D
Definition at line 923 of file shader_glsl.h.
Texture_Shirt
uniform sampler2D Texture_Shirt
Definition at line 797 of file shader_glsl.h.
UserVec1
uniform mediump vec4 UserVec1
Definition at line 246 of file shader_glsl.h.
UserVec2
uniform mediump vec4 UserVec2
Definition at line 247 of file shader_glsl.h.
VectorR
VectorR = (ModelViewMatrix * vec4(Attrib_TexCoord3.xyz, 0))
Definition at line 732 of file shader_glsl.h.
VectorS
VectorS = (ModelViewMatrix * vec4(Attrib_TexCoord1.xyz, 0))
Definition at line 730 of file shader_glsl.h.
VectorT
VectorT = (ModelViewMatrix * vec4(Attrib_TexCoord2.xyz, 0))
Definition at line 731 of file shader_glsl.h.
VertexColor
dp_varying mediump vec4 VertexColor
Definition at line 115 of file shader_glsl.h.
ViewTintColor
uniform mediump vec4 ViewTintColor
Definition at line 243 of file shader_glsl.h.
w
EyeVectorFogDepth w = 0.0
Definition at line 1141 of file shader_glsl.h.
x
EyeVectorFogDepth x = position.x
Definition at line 166 of file shader_glsl.h.
x1
vec3 x1 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, px.y)).rgb
Definition at line 325 of file shader_glsl.h.
Referenced by dpvsimpledecode_decompressimage(), DrawQ_Line(), Font_Postprocess(), GetSide(), Image_HeightmapToNormalmap_BGRA(), R_CalcTexCoordsForView(), R_DebugLine(), R_ScissorForBBox(), R_TimeReport_EndFrame(), R_Viewport_InitOrtho(), and testmul128().
x2
vec3 x2 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, 0.0)).rgb
Definition at line 326 of file shader_glsl.h.
Referenced by DrawQ_Line(), Font_Postprocess(), GetSide(), Image_HeightmapToNormalmap_BGRA(), LoadPCX_BGRA(), LoadPCX_QWSkin(), Mod_Mesh_ComputeBounds(), R_CalcTexCoordsForView(), R_DebugLine(), R_ResetViewRendering2D_Common(), R_ScissorForBBox(), R_TimeReport_EndFrame(), R_Viewport_InitOrtho(), and testmul128().
x3
vec3 x3 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x,-px.y)).rgb
Definition at line 327 of file shader_glsl.h.
Referenced by testmul128().
x4
vec3 x4 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, px.y)).rgb
Definition at line 328 of file shader_glsl.h.
x5
vec3 x5 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, 0.0)).rgb
Definition at line 329 of file shader_glsl.h.
x6
vec3 x6 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x,-px.y)).rgb
Definition at line 330 of file shader_glsl.h.
xy
return RT xy = dp_texture2D(Texture_First, TexCoord1-offset).xy
Definition at line 307 of file shader_glsl.h.
xyz
ret xyz = ((lB < lMin) || (lB > lMax)) ? rA : rB
Definition at line 295 of file shader_glsl.h.
Referenced by Mod_IDP2_Load().
y
EyeVectorFogDepth y = 5.0*sin(distanceSquared*sin(worldTime/143.0)/1000.0)
Definition at line 164 of file shader_glsl.h.
y1
vec3 y1 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x,-px.y)).rgb
Definition at line 331 of file shader_glsl.h.
Referenced by dpvsimpledecode_decompressimage(), DrawQ_Line(), Font_Postprocess(), GetSide(), Image_HeightmapToNormalmap_BGRA(), M_Main_Draw(), R_CalcTexCoordsForView(), R_DebugLine(), R_ScissorForBBox(), R_TimeReport_EndFrame(), and R_Viewport_InitOrtho().
y2
vec3 y2 = dp_texture2D(Texture_First, TexCoord1 + vec2(0.0,-px.y)).rgb
Definition at line 332 of file shader_glsl.h.
Referenced by DrawQ_Line(), Font_Postprocess(), GetSide(), Image_HeightmapToNormalmap_BGRA(), M_Main_Draw(), Mod_Mesh_ComputeBounds(), R_CalcTexCoordsForView(), R_DebugLine(), R_ResetViewRendering2D_Common(), R_ScissorForBBox(), R_TimeReport_EndFrame(), and R_Viewport_InitOrtho().
y3
vec3 y3 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x,-px.y)).rgb
Definition at line 333 of file shader_glsl.h.
Referenced by M_Main_Draw().
y4
vec3 y4 = dp_texture2D(Texture_First, TexCoord1 + vec2(px.x, px.y)).rgb
Definition at line 334 of file shader_glsl.h.
y5
vec3 y5 = dp_texture2D(Texture_First, TexCoord1 + vec2(0.0, px.y)).rgb
Definition at line 335 of file shader_glsl.h.
y6
vec3 y6 = dp_texture2D(Texture_First, TexCoord1 + vec2(-px.x, px.y)).rgb
Definition at line 336 of file shader_glsl.h.
z
EyeVectorFogDepth z = dp_texture2D(Texture_First, TexCoord1+offset).z
Definition at line 308 of file shader_glsl.h.
zw
f f f ScreenTexCoord zw = mix(SafeScreenTexCoord.zw, ScreenTexCoord.zw, f)
Definition at line 700 of file shader_glsl.h.