DarkPlaces: snd_xmp.c File Reference
snd_xmp.c File Reference
#include "darkplaces.h"
#include "snd_main.h"
#include "snd_xmp.h"
#include "sound.h"
Data Structures
struct xmp_channel
struct xmp_module
struct xmp_module_info
struct xmp_stream_persfx_t
struct xmp_stream_perchannel_t
Macros
#define XMP_NAME_SIZE 64 /* Size of module name and type */
#define XMP_FORMAT_8BIT (1 << 0) /* Mix to 8-bit instead of 16 */
#define XMP_FORMAT_UNSIGNED (1 << 1) /* Mix to unsigned samples */
#define XMP_FORMAT_MONO (1 << 2) /* Mix to mono instead of stereo */
#define XMP_PLAYER_AMP 0 /* Amplification factor */
#define XMP_PLAYER_MIX 1 /* Stereo mixing */
#define XMP_PLAYER_INTERP 2 /* Interpolation type */
#define XMP_PLAYER_DSP 3 /* DSP effect flags */
#define XMP_PLAYER_FLAGS 4 /* Player flags */
#define XMP_PLAYER_CFLAGS 5 /* Player flags for current module */
#define XMP_PLAYER_SMPCTL 6 /* Sample control flags */
#define XMP_PLAYER_VOLUME 7 /* Player module volume */
#define XMP_PLAYER_STATE 8 /* Internal player state */
#define XMP_PLAYER_SMIX_VOLUME 9 /* SMIX volume */
#define XMP_PLAYER_DEFPAN 10 /* Default pan setting */
#define XMP_INTERP_NEAREST 0 /* Nearest neighbor */
#define XMP_INTERP_LINEAR 1 /* Linear (default) */
#define XMP_INTERP_SPLINE 2 /* Cubic spline */
#define XMP_STATE_UNLOADED 0 /* Context created */
#define XMP_STATE_LOADED 1 /* Module loaded */
#define XMP_STATE_PLAYING 2 /* Module playing */
#define XMP_SMPCTL_SKIP (1 << 0) /* Don't load samples */
#define XMP_MAX_MOD_LENGTH 256 /* Max number of patterns in module */
#define XMP_MAX_SRATE 49170 /* max sampling rate (Hz) */
#define XMP_MIN_SRATE 4000 /* min sampling rate (Hz) */
#define XMP_MAX_FRAMESIZE (5 * XMP_MAX_SRATE * 2 / XMP_MIN_BPM)
#define XMP_END 1
#define XMP_ERROR_INTERNAL 2 /* Internal error */
#define XMP_ERROR_FORMAT 3 /* Unsupported module format */
#define XMP_ERROR_LOAD 4 /* Error loading file */
#define XMP_ERROR_DEPACK 5 /* Error depacking file */
#define XMP_ERROR_SYSTEM 6 /* System error */
#define XMP_ERROR_INVALID 7 /* Invalid parameter */
#define XMP_ERROR_STATE 8 /* Invalid player state */
#define XMP_CHANNEL_SYNTH (1 << 0) /* Channel is synthesized */
#define XMP_CHANNEL_MUTE (1 << 1) /* Channel is muted */
Typedefs
typedef char * xmp_context
Functions
qbool XMP_OpenLibrary (void)
void XMP_CloseLibrary (void)
static void XMP_GetSamplesFloat (channel_t *ch, sfx_t *sfx, int firstsampleframe, int numsampleframes, float *outsamplesfloat)
static void XMP_StopChannel (channel_t *ch)
static void XMP_FreeSfx (sfx_t *sfx)
qbool XMP_LoadModFile (const char *filename, sfx_t *sfx)
Variables
static const char ** qxmp_version
static const unsigned int * qxmp_vercode
static xmp_context(* qxmp_create_context)(void)
static void(* qxmp_free_context)(xmp_context)
static void(* qxmp_release_module)(xmp_context)
static int(* qxmp_start_player)(xmp_context, int, int)
static int(* qxmp_play_frame)(xmp_context)
static int(* qxmp_play_buffer)(xmp_context, void *, int, int)
static void(* qxmp_get_frame_info)(xmp_context, struct xmp_frame_info *)
static void(* qxmp_end_player)(xmp_context)
static void(* qxmp_get_module_info)(xmp_context, struct xmp_module_info *)
static int(* qxmp_set_player)(xmp_context, int, int)
static int(* qxmp_get_player)(xmp_context, int)
static int(* qxmp_load_module_from_memory)(xmp_context, void *, long)
static dllfunction_t xmpfuncs []
static dllhandle_t xmp_dll = NULL
static const snd_fetcher_t xmp_fetcher = { XMP_GetSamplesFloat, XMP_StopChannel, XMP_FreeSfx }
Macro Definition Documentation
XMP_CHANNEL_MUTE
#define XMP_CHANNEL_MUTE (1 << 1) /* Channel is muted */
Definition at line 150 of file snd_xmp.c.
XMP_CHANNEL_SYNTH
#define XMP_CHANNEL_SYNTH (1 << 0) /* Channel is synthesized */
Definition at line 149 of file snd_xmp.c.
XMP_END
#define XMP_END 1
Definition at line 131 of file snd_xmp.c.
XMP_ERROR_DEPACK
#define XMP_ERROR_DEPACK 5 /* Error depacking file */
Definition at line 135 of file snd_xmp.c.
XMP_ERROR_FORMAT
#define XMP_ERROR_FORMAT 3 /* Unsupported module format */
Definition at line 133 of file snd_xmp.c.
XMP_ERROR_INTERNAL
#define XMP_ERROR_INTERNAL 2 /* Internal error */
Definition at line 132 of file snd_xmp.c.
XMP_ERROR_INVALID
#define XMP_ERROR_INVALID 7 /* Invalid parameter */
Definition at line 137 of file snd_xmp.c.
XMP_ERROR_LOAD
#define XMP_ERROR_LOAD 4 /* Error loading file */
Definition at line 134 of file snd_xmp.c.
XMP_ERROR_STATE
#define XMP_ERROR_STATE 8 /* Invalid player state */
Definition at line 138 of file snd_xmp.c.
XMP_ERROR_SYSTEM
#define XMP_ERROR_SYSTEM 6 /* System error */
Definition at line 136 of file snd_xmp.c.
XMP_FORMAT_8BIT
#define XMP_FORMAT_8BIT (1 << 0) /* Mix to 8-bit instead of 16 */
Definition at line 90 of file snd_xmp.c.
XMP_FORMAT_MONO
#define XMP_FORMAT_MONO (1 << 2) /* Mix to mono instead of stereo */
Definition at line 92 of file snd_xmp.c.
XMP_FORMAT_UNSIGNED
#define XMP_FORMAT_UNSIGNED (1 << 1) /* Mix to unsigned samples */
Definition at line 91 of file snd_xmp.c.
XMP_INTERP_LINEAR
#define XMP_INTERP_LINEAR 1 /* Linear (default) */
Definition at line 109 of file snd_xmp.c.
XMP_INTERP_NEAREST
#define XMP_INTERP_NEAREST 0 /* Nearest neighbor */
Definition at line 108 of file snd_xmp.c.
XMP_INTERP_SPLINE
#define XMP_INTERP_SPLINE 2 /* Cubic spline */
Definition at line 110 of file snd_xmp.c.
XMP_MAX_FRAMESIZE
#define XMP_MAX_FRAMESIZE (5 * XMP_MAX_SRATE * 2 / XMP_MIN_BPM)
Definition at line 128 of file snd_xmp.c.
XMP_MAX_MOD_LENGTH
#define XMP_MAX_MOD_LENGTH 256 /* Max number of patterns in module */
Definition at line 123 of file snd_xmp.c.
XMP_MAX_SRATE
#define XMP_MAX_SRATE 49170 /* max sampling rate (Hz) */
Definition at line 125 of file snd_xmp.c.
XMP_MIN_SRATE
#define XMP_MIN_SRATE 4000 /* min sampling rate (Hz) */
Definition at line 126 of file snd_xmp.c.
XMP_NAME_SIZE
#define XMP_NAME_SIZE 64 /* Size of module name and type */
Definition at line 87 of file snd_xmp.c.
XMP_PLAYER_AMP
#define XMP_PLAYER_AMP 0 /* Amplification factor */
Definition at line 95 of file snd_xmp.c.
XMP_PLAYER_CFLAGS
#define XMP_PLAYER_CFLAGS 5 /* Player flags for current module */
Definition at line 100 of file snd_xmp.c.
XMP_PLAYER_DEFPAN
#define XMP_PLAYER_DEFPAN 10 /* Default pan setting */
Definition at line 105 of file snd_xmp.c.
XMP_PLAYER_DSP
#define XMP_PLAYER_DSP 3 /* DSP effect flags */
Definition at line 98 of file snd_xmp.c.
XMP_PLAYER_FLAGS
#define XMP_PLAYER_FLAGS 4 /* Player flags */
Definition at line 99 of file snd_xmp.c.
XMP_PLAYER_INTERP
#define XMP_PLAYER_INTERP 2 /* Interpolation type */
Definition at line 97 of file snd_xmp.c.
XMP_PLAYER_MIX
#define XMP_PLAYER_MIX 1 /* Stereo mixing */
Definition at line 96 of file snd_xmp.c.
XMP_PLAYER_SMIX_VOLUME
#define XMP_PLAYER_SMIX_VOLUME 9 /* SMIX volume */
Definition at line 104 of file snd_xmp.c.
XMP_PLAYER_SMPCTL
#define XMP_PLAYER_SMPCTL 6 /* Sample control flags */
Definition at line 101 of file snd_xmp.c.
XMP_PLAYER_STATE
#define XMP_PLAYER_STATE 8 /* Internal player state */
Definition at line 103 of file snd_xmp.c.
XMP_PLAYER_VOLUME
#define XMP_PLAYER_VOLUME 7 /* Player module volume */
Definition at line 102 of file snd_xmp.c.
XMP_SMPCTL_SKIP
#define XMP_SMPCTL_SKIP (1 << 0) /* Don't load samples */
Definition at line 118 of file snd_xmp.c.
XMP_STATE_LOADED
#define XMP_STATE_LOADED 1 /* Module loaded */
Definition at line 114 of file snd_xmp.c.
XMP_STATE_PLAYING
#define XMP_STATE_PLAYING 2 /* Module playing */
Definition at line 115 of file snd_xmp.c.
XMP_STATE_UNLOADED
#define XMP_STATE_UNLOADED 0 /* Context created */
Definition at line 113 of file snd_xmp.c.
Typedef Documentation
xmp_context
typedef char* xmp_context
Definition at line 141 of file snd_xmp.c.
Function Documentation
XMP_CloseLibrary()
void XMP_CloseLibrary (void)
Definition at line 398 of file snd_xmp.c.
{
    Sys_FreeLibrary (&xmp_dll);
}
Referenced by S_Terminate().
XMP_FreeSfx()
static void XMP_FreeSfx (sfx_t * sfx) static
Definition at line 578 of file snd_xmp.c.
{
    xmp_stream_persfx_t* per_sfx = (xmp_stream_persfx_t *)sfx->fetcher_data;
    // free the complete file we were keeping around
    Mem_Free(per_sfx->file);
    // free the file information structure
    Mem_Free(per_sfx);
}
XMP_GetSamplesFloat()
static void XMP_GetSamplesFloat (channel_t * ch, sfx_t * sfx, int firstsampleframe, int numsampleframes, float * outsamplesfloat) static
Definition at line 436 of file snd_xmp.c.
{
    int i, len = numsampleframes * sfx->format.channels;
    int f = sfx->format.width * sfx->format.channels; // bytes per frame in the buffer
    xmp_stream_perchannel_t* per_ch = (xmp_stream_perchannel_t *)ch->fetcher_data;
    xmp_stream_persfx_t* per_sfx = (xmp_stream_persfx_t *)sfx->fetcher_data;
    const short *buf;
    int newlength, done;
    unsigned int format = 0;
    // if this channel does not yet have a channel fetcher, make one
    if (per_ch == NULL)
    {
        // allocate a struct to keep track of our file position and buffer
        per_ch = (xmp_stream_perchannel_t *)Mem_Alloc(snd_mempool, sizeof(*per_ch));
        // create an xmp file context
        if ((per_ch->playercontext = qxmp_create_context()) == NULL)
        {
            //Con_Printf("error getting a libxmp file context; while trying to load file \"%s\"\n", filename);
            Mem_Free(per_ch);
            return;
        }
        // copy file to xmp
        if (qxmp_load_module_from_memory(per_ch->playercontext, (void *)per_sfx->file, (long)per_sfx->filesize) < 0)
        {
            qxmp_free_context(per_ch->playercontext);
            Mem_Free(per_ch);
            return;
        }
        // start playing the loaded file
        if (sfx->format.width == 1)    { format |= XMP_FORMAT_8BIT | XMP_FORMAT_UNSIGNED; } // else 16bit
        if (sfx->format.channels == 1) { format |= XMP_FORMAT_MONO; } // else stereo
        if (qxmp_start_player(per_ch->playercontext, sfx->format.speed, format) < 0)
        {
            Mem_Free(per_ch);
            return;
        }
        /* percentual left/right channel separation, default is 70. */
        if (sfx->format.channels == 2 && (qxmp_set_player(per_ch->playercontext, XMP_PLAYER_MIX, 50) != 0))
        {
            Mem_Free(per_ch);
            return;
        }
        /* interpolation type, default is XMP_INTERP_LINEAR */
        if (qxmp_set_player(per_ch->playercontext, XMP_PLAYER_INTERP, XMP_INTERP_SPLINE) != 0)
        {
            Mem_Free(per_ch);
            return;
        }
        per_ch->bs = 0;
        per_ch->buffer_firstframe = 0;
        per_ch->buffer_numframes = 0;
        // attach the struct to our channel
        ch->fetcher_data = (void *)per_ch;
        // reset internal xmp state / syncs buffer start with frame start
        qxmp_play_buffer(per_ch->playercontext, NULL, 0, 0);
    }
    // if the request is too large for our buffer, loop...
    while (numsampleframes * f > (int)sizeof(per_ch->buffer))
    {
        done = sizeof(per_ch->buffer) / f;
        XMP_GetSamplesFloat(ch, sfx, firstsampleframe, done, outsamplesfloat);
        firstsampleframe += done;
        numsampleframes -= done;
        outsamplesfloat += done * sfx->format.channels;
    }
    // seek if the request is before the current buffer (loop back)
    // seek if the request starts beyond the current buffer by at least one frame (channel was zero volume for a while)
    // do not seek if the request overlaps the buffer end at all (expected behavior)
    if (per_ch->buffer_firstframe > firstsampleframe || per_ch->buffer_firstframe + per_ch->buffer_numframes < firstsampleframe)
    {
        // we expect to decode forward from here so this will be our new buffer start
        per_ch->buffer_firstframe = firstsampleframe;
        per_ch->buffer_numframes = 0;
        // no seeking at this time
    }
    // render the file to pcm as needed
    if (firstsampleframe + numsampleframes > per_ch->buffer_firstframe + per_ch->buffer_numframes)
    {
        // first slide the buffer back, discarding any data preceding the range we care about
        int offset = firstsampleframe - per_ch->buffer_firstframe;
        int keeplength = per_ch->buffer_numframes - offset;
        if (keeplength > 0)
            memmove(per_ch->buffer, per_ch->buffer + offset * sfx->format.width * sfx->format.channels, keeplength * sfx->format.width * sfx->format.channels);
        per_ch->buffer_firstframe = firstsampleframe;
        per_ch->buffer_numframes -= offset;
        // render as much as we can fit in the buffer
        newlength = sizeof(per_ch->buffer) - per_ch->buffer_numframes * f;
        done = 0;
//      while (newlength > done && qxmp_play_buffer(per_ch->playercontext, (void *)((char *)per_ch->buffer + done), (int)(newlength - done), 1) == 0) // don't loop by default (TODO: fix pcm duration calculation first)
        while (newlength > done && qxmp_play_buffer(per_ch->playercontext, (void *)((char *)per_ch->buffer + done), (int)(newlength - done), 0) == 0) // loop forever
        {
            done += (int)(newlength - done);
        }
        // clear the missing space if any
        if (done < newlength)
        {
            memset(per_ch->buffer + done, 0, newlength - done);
        }
        // we now have more data in the buffer
        per_ch->buffer_numframes += done / f;
    }
    // convert the sample format for the caller
    buf = (short *)((char *)per_ch->buffer + (firstsampleframe - per_ch->buffer_firstframe) * f);
    for (i = 0;i < len;i++)
        outsamplesfloat[i] = buf[i] * (1.0f / 32768.0f);
}
Referenced by XMP_GetSamplesFloat().
XMP_LoadModFile()
qbool XMP_LoadModFile (const char * filename, sfx_t * sfx)
Definition at line 596 of file snd_xmp.c.
{
    fs_offset_t filesize;
    unsigned char *data;
    xmp_context xc;
    xmp_stream_persfx_t* per_sfx;
    struct xmp_module_info mi;
#ifndef LINK_TO_LIBXMP
    if (!xmp_dll)
        return false;
#endif
// COMMANDLINEOPTION: Sound: -noxmp disables xmp module sound support
    if (Sys_CheckParm("-noxmp"))
        return false;
    // Return if already loaded
    if (sfx->fetcher != NULL)
        return true;
    // Load the file
    data = FS_LoadFile(filename, snd_mempool, false, &filesize);
    if (data == NULL)
        return false;
    // Create an xmp file context
    if ((xc = qxmp_create_context()) == NULL)
    {
        Con_Printf("error creating a libxmp file context; while trying to load file \"%s\"\n", filename);
        Mem_Free(data);
        return false;
    }
    if (developer_loading.integer >= 2)
        Con_Printf("Loading Module file (libxmp) \"%s\"\n", filename);
    if (qxmp_load_module_from_memory(xc, (void *)data, (long)filesize) < 0) // Added in libxmp 4.2
    {
        Con_Printf("error while trying to load xmp module \"%s\"\n", filename);
        qxmp_free_context(xc);
        Mem_Free(data);
        return false;
    }
    if (developer_loading.integer >= 2)
        Con_Printf ("\"%s\" will be streamed\n", filename);
    // keep the file around
    per_sfx = (xmp_stream_persfx_t *)Mem_Alloc (snd_mempool, sizeof (*per_sfx));
    per_sfx->file = data;
    per_sfx->filesize = filesize;
    // set dp sfx
    sfx->memsize += sizeof(*per_sfx);
    sfx->memsize += filesize; // total memory used (including sfx_t and fetcher data)
    if (S_GetSoundRate() > XMP_MAX_SRATE)
        sfx->format.speed = 48000;
    else if (S_GetSoundRate() < XMP_MIN_SRATE)
        sfx->format.speed = 8000;
    else
        sfx->format.speed = S_GetSoundRate();
    sfx->format.width = S_GetSoundWidth();  // 2 = 16 bit samples
    sfx->format.channels = S_GetSoundChannels();
    sfx->flags |= SFXFLAG_STREAMED; // cf SFXFLAG_* defines
    sfx->total_length = 1<<30; // 2147384647; // in (pcm) sample frames - they always loop (FIXME this breaks after 6 hours, we need support for a real "infinite" value!)
    sfx->loopstart = sfx->total_length; // (modplug does it) in sample frames. equals total_length if not looped
    sfx->fetcher_data = per_sfx;
    sfx->fetcher = &xmp_fetcher;
    sfx->volume_peak = 0;
    qxmp_get_module_info(xc, &mi);
    if (developer_loading.integer >= 2)
    {
        Con_Printf("Decoding module (libxmp):\n"
            "    Module name  : %s\n"
            "    Module type  : %s\n"
            "    Module length: %i patterns\n"
            "    Patterns     : %i\n"
            "    Instruments  : %i\n"
            "    Samples      : %i\n"
            "    Channels     : %i\n"
            "    Initial Speed: %i\n"
            "    Initial BPM  : %i\n"
            "    Restart Pos. : %i\n"
            "    Global Volume: %i\n",
            mi.mod->name, mi.mod->type,
            mi.mod->len, mi.mod->pat, mi.mod->ins, mi.mod->smp, mi.mod->chn,
            mi.mod->spd, mi.mod->bpm, mi.mod->rst, mi.mod->gvl
        );
    }
    else if (developer_loading.integer == 1)
        Con_Printf("Decoding module (libxmp) \"%s\" (%s)\n", mi.mod->name, mi.mod->type);
    qxmp_free_context(xc);
    return true;
}
Referenced by S_LoadSound().
XMP_OpenLibrary()
qbool XMP_OpenLibrary (void)
Definition at line 349 of file snd_xmp.c.
{
    const char* dllnames_xmp [] =
    {
#if defined(WIN32)
        "libxmp-4.dll",
        "libxmp.dll",
#elif defined(MACOSX) // FIXME: untested, please test a mac os build
        "libxmp.4.dylib",
        "libxmp.dylib",
#else
        "libxmp.so.4",
        "libxmp.so",
#endif
        NULL
    };
    if (xmp_dll) // Already loaded?
        return true;
// COMMANDLINEOPTION: Sound: -noxmp disables xmp module sound support
    if (Sys_CheckParm("-noxmp"))
        return false;
    // Load the DLL
    if (Sys_LoadDependency (dllnames_xmp, &xmp_dll, xmpfuncs))
    {
        if (*qxmp_vercode < 0x040200)
        {
            Con_Printf("Found incompatible XMP library version %s, not loading. (4.2.0 or higher required)\n", *qxmp_version);
            Sys_FreeLibrary (&xmp_dll);
            return false;
        }
        if (developer_loading.integer >= 1)
            Con_Printf("XMP library loaded, version %s (0x0%x)\n", *qxmp_version, *qxmp_vercode);
        return true;
    }
    else
        return false;
}
Referenced by S_Init().
XMP_StopChannel()
static void XMP_StopChannel (channel_t * ch) static
Definition at line 558 of file snd_xmp.c.
{
    xmp_stream_perchannel_t *per_ch = (xmp_stream_perchannel_t *)ch->fetcher_data;
    if (per_ch != NULL)
    {
        // stop the player
        qxmp_end_player(per_ch->playercontext);
        // free the module
        qxmp_release_module(per_ch->playercontext);
        // free the xmp playercontext
        qxmp_free_context(per_ch->playercontext);
        Mem_Free(per_ch);
    }
}
Variable Documentation
qxmp_create_context
xmp_context(* qxmp_create_context) (void) (void) static
Definition at line 232 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat(), and XMP_LoadModFile().
qxmp_end_player
void(* qxmp_end_player) (xmp_context) (xmp_context) static
Definition at line 242 of file snd_xmp.c.
Referenced by XMP_StopChannel().
qxmp_free_context
void(* qxmp_free_context) (xmp_context) (xmp_context) static
Definition at line 233 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat(), XMP_LoadModFile(), and XMP_StopChannel().
qxmp_get_frame_info
void(* qxmp_get_frame_info) (xmp_context, struct xmp_frame_info *) (xmp_context , struct xmp_frame_info *) static
Definition at line 241 of file snd_xmp.c.
qxmp_get_module_info
void(* qxmp_get_module_info) (xmp_context, struct xmp_module_info *) (xmp_context , struct xmp_module_info *) static
Definition at line 244 of file snd_xmp.c.
Referenced by XMP_LoadModFile().
qxmp_get_player
int(* qxmp_get_player) (xmp_context, int) (xmp_context , int) static
Definition at line 255 of file snd_xmp.c.
qxmp_load_module_from_memory
int(* qxmp_load_module_from_memory) (xmp_context, void *, long) (xmp_context , void * , long) static
Definition at line 257 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat(), and XMP_LoadModFile().
qxmp_play_buffer
int(* qxmp_play_buffer) (xmp_context, void *, int, int) (xmp_context , void * , int , int) static
Definition at line 240 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat().
qxmp_play_frame
int(* qxmp_play_frame) (xmp_context) (xmp_context) static
Definition at line 239 of file snd_xmp.c.
qxmp_release_module
void(* qxmp_release_module) (xmp_context) (xmp_context) static
Definition at line 237 of file snd_xmp.c.
Referenced by XMP_StopChannel().
qxmp_set_player
int(* qxmp_set_player) (xmp_context, int, int) (xmp_context , int , int) static
Definition at line 254 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat().
qxmp_start_player
int(* qxmp_start_player) (xmp_context, int, int) (xmp_context , int , int) static
Definition at line 238 of file snd_xmp.c.
Referenced by XMP_GetSamplesFloat().
qxmp_vercode
const unsigned int* qxmp_vercode static
Definition at line 144 of file snd_xmp.c.
Referenced by XMP_OpenLibrary().
qxmp_version
const char** qxmp_version static
Definition at line 143 of file snd_xmp.c.
Referenced by XMP_OpenLibrary().
xmp_dll
dllhandle_t xmp_dll = NULL static
Definition at line 331 of file snd_xmp.c.
Referenced by XMP_CloseLibrary(), XMP_LoadModFile(), and XMP_OpenLibrary().
xmp_fetcher
const snd_fetcher_t xmp_fetcher = { XMP_GetSamplesFloat, XMP_StopChannel, XMP_FreeSfx } static
Definition at line 587 of file snd_xmp.c.
{ XMP_GetSamplesFloat, XMP_StopChannel, XMP_FreeSfx };
Referenced by XMP_LoadModFile().
xmpfuncs
dllfunction_t xmpfuncs[] static
Definition at line 281 of file snd_xmp.c.
{
    /* libxmp ABI */
    // Version and player information
    {"xmp_version",                 (void **) &qxmp_version},
    {"xmp_vercode",                 (void **) &qxmp_vercode},
//  {"xmp_get_format_list",         (void **) &qxmp_get_format_list},
    // Context creation
    {"xmp_create_context",          (void **) &qxmp_create_context},
    {"xmp_free_context",            (void **) &qxmp_free_context},
    // Module loading
//  {"xmp_test_module",             (void **) &qxmp_test_module},
//  {"xmp_load_module",             (void **) &qxmp_load_module},
    {"xmp_load_module_from_memory", (void **) &qxmp_load_module_from_memory}, // since libxmp 4.2.0
//  {"xmp_load_module_from_file",   (void **) &qxmp_load_module_from_file},   // since libxmp 4.3.0
    {"xmp_release_module",          (void **) &qxmp_release_module},
//  {"xmp_scan_module",             (void **) &qxmp_scan_module},
    {"xmp_get_module_info",         (void **) &qxmp_get_module_info},
    // Module playing
    {"xmp_start_player",            (void **) &qxmp_start_player},
    {"xmp_play_frame",              (void **) &qxmp_play_frame},
    {"xmp_play_buffer",             (void **) &qxmp_play_buffer},
    {"xmp_get_frame_info",          (void **) &qxmp_get_frame_info},
    {"xmp_end_player",              (void **) &qxmp_end_player},
    // Player control
//  {"xmp_next_position",           (void **) &qxmp_next_position},
//  {"xmp_prev_position",           (void **) &qxmp_prev_position},
//  {"xmp_set_position",            (void **) &qxmp_set_position},
//  {"xmp_stop_module",             (void **) &qxmp_stop_module},
//  {"xmp_restart_module",          (void **) &qxmp_restart_module},
//  {"xmp_seek_time",               (void **) &qxmp_seek_time},
//  {"xmp_channel_mute",            (void **) &qxmp_channel_mute},
//  {"xmp_channel_vol",             (void **) &qxmp_channel_vol},
//  {"xmp_inject_event",            (void **) &qxmp_inject_event},
    // Player parameter setting
//  {"xmp_set_instrument_path",     (void **) &qxmp_set_instrument_path},
    {"xmp_get_player",              (void **) &qxmp_get_player},
    {"xmp_set_player",              (void **) &qxmp_set_player},
    /* smix */ // for completeness sake only, right now
//  {"xmp_start_smix",              (void **) &qxmp_start_smix},
//  {"xmp_end_smix",                (void **) &qxmp_end_smix},
//  {"xmp_smix_play_instrument",    (void **) &qxmp_smix_play_instrument},
//  {"xmp_smix_play_sample",        (void **) &qxmp_smix_play_sample},
//  {"xmp_smix_channel_pan",        (void **) &qxmp_smix_channel_pan},
//  {"xmp_smix_load_sample",        (void **) &qxmp_smix_load_sample},
//  {"xmp_smix_release_sample",     (void **) &qxmp_smix_release_sample},
    {NULL, NULL}
};
Referenced by XMP_OpenLibrary().