DarkPlaces: snd_mem.c File Reference
snd_mem.c File Reference
#include "darkplaces.h"
#include "snd_main.h"
#include "snd_ogg.h"
#include "snd_wav.h"
#include "sound.h"
Functions
void SCR_PushLoadingScreen (const char *, float)
void SCR_PopLoadingScreen (qbool)
snd_ringbuffer_t * Snd_CreateRingBuffer (const snd_format_t *format, unsigned int sampleframes, void *buffer)
qbool S_LoadSound (sfx_t *sfx, qbool complain)
Function Documentation
S_LoadSound()
qbool S_LoadSound (sfx_t * sfx, qbool complain)
Definition at line 87 of file snd_mem.c.
{
    char namebuffer[MAX_QPATH + 16];
    size_t len;
    // See if already loaded
    if (sfx->fetcher != NULL)
        return true;
    // If we weren't able to load it previously, no need to retry
    // Note: S_PrecacheSound clears this flag to cause a retry
    if (sfx->flags & SFXFLAG_FILEMISSING)
        return false;
    // No sound?
    if (snd_renderbuffer == NULL)
        return false;
    // Initialize volume peak to 0; if ReplayGain is supported, the loader will change this away
    sfx->volume_peak = 0.0;
    if (developer_loading.integer)
        Con_Printf("loading sound %s\n", sfx->name);
    SCR_PushLoadingScreen(sfx->name, 1);
    // LadyHavoc: if the sound filename does not begin with sound/, try adding it
    if (strncasecmp(sfx->name, "sound/", 6))
    {
        dpsnprintf (namebuffer, sizeof(namebuffer), "sound/%s", sfx->name);
        len = strlen(namebuffer);
        if (len >= 4 && !strcasecmp (namebuffer + len - 4, ".wav"))
        {
            if (S_LoadWavFile (namebuffer, sfx))
                goto loaded;
            memcpy (namebuffer + len - 3, "ogg", 4);
        }
        if (len >= 4 && !strcasecmp (namebuffer + len - 4, ".ogg"))
        {
            if (OGG_LoadVorbisFile (namebuffer, sfx))
                goto loaded;
        }
#ifdef USEXMP
        else if (len >= 1)
        {
            if (XMP_LoadModFile (namebuffer, sfx))
                goto loaded;
        }
#endif
    }
    // LadyHavoc: then try without the added sound/ as wav and ogg
    dpsnprintf (namebuffer, sizeof(namebuffer), "%s", sfx->name);
    len = strlen(namebuffer);
    // request foo.wav: tries foo.wav, then foo.ogg
    // request foo.ogg: tries foo.ogg only
    // request foo.mod: tries foo.mod only
    if (len >= 4 && !strcasecmp (namebuffer + len - 4, ".wav"))
    {
        if (S_LoadWavFile (namebuffer, sfx))
            goto loaded;
        memcpy (namebuffer + len - 3, "ogg", 4);
    }
    if (len >= 4 && !strcasecmp (namebuffer + len - 4, ".ogg"))
    {
        if (OGG_LoadVorbisFile (namebuffer, sfx))
            goto loaded;
    }
#ifdef USEXMP
    else if (len >= 1)
    {
        if (XMP_LoadModFile (namebuffer, sfx))
            goto loaded;
    }
#endif
    // Can't load the sound!
    sfx->flags |= SFXFLAG_FILEMISSING;
    if (complain)
        Con_Printf(CON_ERROR "Failed to load sound \"%s\"\n", sfx->name);
    SCR_PopLoadingScreen(false);
    return false;
loaded:
    SCR_PopLoadingScreen(false);
    return true;
}
SCR_PopLoadingScreen()
void SCR_PopLoadingScreen (qbool redraw)
Definition at line 1930 of file cl_screen.c.
{
    loadingscreenstack_t *s = loadingscreenstack;
    if(!s)
    {
        Con_DPrintf("Popping a loading screen item from an empty stack!\n");
        return;
    }
    loadingscreenstack = s->prev;
    if(s->prev)
        s->prev->relative_completion = (s->absolute_loading_amount_min + s->absolute_loading_amount_len - s->prev->absolute_loading_amount_min) / s->prev->absolute_loading_amount_len;
    Z_Free(s);
    if (scr_loading && redraw)
        CL_UpdateScreen();
}
Referenced by CL_BeginDownloads(), Mod_LoadModel(), Mod_Reload(), mod_start(), S_LoadSound(), and SCR_ClearLoadingScreen().
SCR_PushLoadingScreen()
void SCR_PushLoadingScreen (const char * msg, float len_in_parent)
Definition at line 1904 of file cl_screen.c.
{
    loadingscreenstack_t *s = (loadingscreenstack_t *) Z_Malloc(sizeof(loadingscreenstack_t));
    s->prev = loadingscreenstack;
    loadingscreenstack = s;
    dp_strlcpy(s->msg, msg, sizeof(s->msg));
    s->relative_completion = 0;
    if(s->prev)
    {
        s->absolute_loading_amount_min = s->prev->absolute_loading_amount_min + s->prev->absolute_loading_amount_len * s->prev->relative_completion;
        s->absolute_loading_amount_len = s->prev->absolute_loading_amount_len * len_in_parent;
        if(s->absolute_loading_amount_len > s->prev->absolute_loading_amount_min + s->prev->absolute_loading_amount_len - s->absolute_loading_amount_min)
            s->absolute_loading_amount_len = s->prev->absolute_loading_amount_min + s->prev->absolute_loading_amount_len - s->absolute_loading_amount_min;
    }
    else
    {
        s->absolute_loading_amount_min = 0;
        s->absolute_loading_amount_len = 1;
    }
    if (scr_loading)
        CL_UpdateScreen();
}
Referenced by CL_BeginDownloads(), Mod_LoadModel(), Mod_Reload(), mod_start(), and S_LoadSound().
Snd_CreateRingBuffer()
snd_ringbuffer_t * Snd_CreateRingBuffer (const snd_format_t * format, unsigned int sampleframes, void * buffer)
Definition at line 43 of file snd_mem.c.
{
    snd_ringbuffer_t *ringbuffer;
    // If the caller provides a buffer, it must give us its size
    if (sampleframes == 0 && buffer != NULL)
        return NULL;
    ringbuffer = (snd_ringbuffer_t*)Mem_Alloc(snd_mempool, sizeof (*ringbuffer));
    memset(ringbuffer, 0, sizeof(*ringbuffer));
    memcpy(&ringbuffer->format, format, sizeof(ringbuffer->format));
    // If we haven't been given a buffer
    if (buffer == NULL)
    {
        unsigned int maxframes;
        size_t memsize;
        if (sampleframes == 0)
            maxframes = (format->speed + 1) / 2;  // Make the sound buffer large enough for containing 0.5 sec of sound
        else
            maxframes = sampleframes;
        memsize = maxframes * format->width * format->channels;
        ringbuffer->ring = (unsigned char *) Mem_Alloc(snd_mempool, memsize);
        ringbuffer->maxframes = maxframes;
    }
    else
    {
        ringbuffer->ring = (unsigned char *) buffer;
        ringbuffer->maxframes = sampleframes;
    }
    return ringbuffer;
}
Referenced by S_Startup(), SndSys_Init(), and SndSys_Init().