DarkPlaces: snd_sdl.c File Reference
snd_sdl.c File Reference
#include <math.h>
#include <SDL.h>
#include "darkplaces.h"
#include "vid.h"
#include "snd_main.h"
Functions
static void Buffer_Callback (void *userdata, Uint8 *stream, int len)
qbool SndSys_Init (snd_format_t *fmt)
void SndSys_Shutdown (void)
void SndSys_Submit (void)
unsigned int SndSys_GetSoundTime (void)
qbool SndSys_LockRenderBuffer (void)
void SndSys_UnlockRenderBuffer (void)
void SndSys_SendKeyEvents (void)
Variables
static unsigned int sdlaudiotime = 0
static int audio_device = 0
Function Documentation
Buffer_Callback()
static void Buffer_Callback (void * userdata, Uint8 * stream, int len) static
Definition at line 33 of file snd_sdl.c.
{
    unsigned int factor, RequestedFrames, MaxFrames, FrameCount;
    unsigned int StartOffset, EndOffset;
    factor = snd_renderbuffer->format.channels * snd_renderbuffer->format.width;
    if ((unsigned int)len % factor != 0)
        Sys_Error("SDL sound: invalid buffer length passed to Buffer_Callback (%d bytes)\n", len);
    RequestedFrames = (unsigned int)len / factor;
    if (SndSys_LockRenderBuffer())
    {
        if (snd_usethreadedmixing)
        {
            S_MixToBuffer(stream, RequestedFrames);
            if (snd_blocked)
                memset(stream, snd_renderbuffer->format.width == 1 ? 0x80 : 0, len);
            SndSys_UnlockRenderBuffer();
            return;
        }
        // Transfert up to a chunk of samples from snd_renderbuffer to stream
        MaxFrames = snd_renderbuffer->endframe - snd_renderbuffer->startframe;
        if (MaxFrames > RequestedFrames)
            FrameCount = RequestedFrames;
        else
            FrameCount = MaxFrames;
        StartOffset = snd_renderbuffer->startframe % snd_renderbuffer->maxframes;
        EndOffset = (snd_renderbuffer->startframe + FrameCount) % snd_renderbuffer->maxframes;
        if (StartOffset > EndOffset)  // if the buffer wraps
        {
            unsigned int PartialLength1, PartialLength2;
            PartialLength1 = (snd_renderbuffer->maxframes - StartOffset) * factor;
            memcpy(stream, &snd_renderbuffer->ring[StartOffset * factor], PartialLength1);
            PartialLength2 = FrameCount * factor - PartialLength1;
            memcpy(&stream[PartialLength1], &snd_renderbuffer->ring[0], PartialLength2);
            // As of SDL 2.0 buffer needs to be fully initialized, so fill leftover part with silence
            // FIXME this is another place that assumes 8bit is always unsigned and others always signed
            memset(&stream[PartialLength1 + PartialLength2], snd_renderbuffer->format.width == 1 ? 0x80 : 0, len - (PartialLength1 + PartialLength2));
        }
        else
        {
            memcpy(stream, &snd_renderbuffer->ring[StartOffset * factor], FrameCount * factor);
            // As of SDL 2.0 buffer needs to be fully initialized, so fill leftover part with silence
            // FIXME this is another place that assumes 8bit is always unsigned and others always signed
            memset(&stream[FrameCount * factor], snd_renderbuffer->format.width == 1 ? 0x80 : 0, len - (FrameCount * factor));
        }
        snd_renderbuffer->startframe += FrameCount;
        if (FrameCount < RequestedFrames && developer_insane.integer && vid_activewindow)
            Con_DPrintf("SDL sound: %u sample frames missing\n", RequestedFrames - FrameCount);
        sdlaudiotime += RequestedFrames;
        SndSys_UnlockRenderBuffer();
    }
}
Referenced by SndSys_Init().
SndSys_GetSoundTime()
unsigned int SndSys_GetSoundTime (void)
Definition at line 211 of file snd_sdl.c.
{
    return sdlaudiotime;
}
Referenced by S_PaintAndSubmit().
SndSys_Init()
qbool SndSys_Init (snd_format_t * fmt)
Definition at line 106 of file snd_sdl.c.
{
    unsigned int buffersize;
    SDL_AudioSpec wantspec;
    SDL_AudioSpec obtainspec;
    snd_threaded = false;
    Con_DPrint ("SndSys_Init: using the SDL module\n");
    // Init the SDL Audio subsystem
    if( SDL_InitSubSystem( SDL_INIT_AUDIO ) ) {
        Con_Print( "Initializing the SDL Audio subsystem failed!\n" );
        return false;
    }
    buffersize = (unsigned int)ceil((double)fmt->speed / 25.0); // 2048 bytes on 24kHz to 48kHz
    // Init the SDL Audio subsystem
    memset(&wantspec, 0, sizeof(wantspec));
    wantspec.callback = Buffer_Callback;
    wantspec.userdata = NULL;
    wantspec.freq = fmt->speed;
    wantspec.format = fmt->width == 1 ? AUDIO_U8 : (fmt->width == 2 ? AUDIO_S16SYS : AUDIO_F32);
    wantspec.channels = fmt->channels;
    wantspec.samples = CeilPowerOf2(buffersize);  // needs to be a power of 2 on some platforms.
    Con_Printf("Wanted audio Specification:\n"
                "    Channels  : %i\n"
                "    Format    : 0x%X\n"
                "    Frequency : %i\n"
                "    Samples   : %i\n",
                wantspec.channels, wantspec.format, wantspec.freq, wantspec.samples);
    if ((audio_device = SDL_OpenAudioDevice(NULL, 0, &wantspec, &obtainspec, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE | SDL_AUDIO_ALLOW_CHANNELS_CHANGE)) == 0)
    {
        Con_Printf(CON_ERROR "Failed to open the audio device! (%s)\n", SDL_GetError() );
        return false;
    }
    Con_Printf("Obtained audio specification:\n"
                "    Channels  : %i\n"
                "    Format    : 0x%X\n"
                "    Frequency : %i\n"
                "    Samples   : %i\n",
                obtainspec.channels, obtainspec.format, obtainspec.freq, obtainspec.samples);
    fmt->speed = obtainspec.freq;
    fmt->channels = obtainspec.channels;
    snd_threaded = true;
    snd_renderbuffer = Snd_CreateRingBuffer(fmt, 0, NULL);
    if (snd_channellayout.integer == SND_CHANNELLAYOUT_AUTO)
        Cvar_SetValueQuick (&snd_channellayout, SND_CHANNELLAYOUT_STANDARD);
    sdlaudiotime = 0;
    SDL_PauseAudioDevice(audio_device, 0);
    return true;
}
Referenced by S_Startup().
SndSys_LockRenderBuffer()
qbool SndSys_LockRenderBuffer (void)
Definition at line 224 of file snd_sdl.c.
{
    SDL_LockAudioDevice(audio_device);
    return true;
}
Referenced by Buffer_Callback(), S_PaintAndSubmit(), S_StopAllSounds(), and S_StopChannel().
SndSys_SendKeyEvents()
void SndSys_SendKeyEvents (void)
Definition at line 250 of file snd_sdl.c.
{
    // not supported
}
SndSys_Shutdown()
void SndSys_Shutdown (void)
Definition at line 176 of file snd_sdl.c.
{
    if (audio_device > 0) {
        SDL_CloseAudioDevice(audio_device);
        audio_device = 0;
    }
    if (snd_renderbuffer != NULL)
    {
        Mem_Free(snd_renderbuffer->ring);
        Mem_Free(snd_renderbuffer);
        snd_renderbuffer = NULL;
    }
}
Referenced by S_Shutdown().
SndSys_Submit()
void SndSys_Submit (void)
Definition at line 198 of file snd_sdl.c.
{
    // Nothing to do here (this sound module is callback-based)
}
Referenced by S_PaintAndSubmit().
SndSys_UnlockRenderBuffer()
void SndSys_UnlockRenderBuffer (void)
Definition at line 238 of file snd_sdl.c.
{
    SDL_UnlockAudioDevice(audio_device);
}
Referenced by Buffer_Callback(), S_PaintAndSubmit(), S_StopAllSounds(), and S_StopChannel().
Variable Documentation
audio_device
int audio_device = 0 static
Definition at line 29 of file snd_sdl.c.
Referenced by SndSys_Init(), SndSys_LockRenderBuffer(), SndSys_Shutdown(), and SndSys_UnlockRenderBuffer().
sdlaudiotime
unsigned int sdlaudiotime = 0 static
Definition at line 28 of file snd_sdl.c.
Referenced by Buffer_Callback(), SndSys_GetSoundTime(), and SndSys_Init().