DarkPlaces: jpeg_destination_mgr Struct Reference
jpeg_destination_mgr Struct Reference
Data Fields
unsigned char * next_output_byte
size_t free_in_buffer
void(* init_destination)(j_compress_ptr cinfo)
jboolean(* empty_output_buffer)(j_compress_ptr cinfo)
void(* term_destination)(j_compress_ptr cinfo)
Detailed Description
Definition at line 393 of file jpeg.c.
Field Documentation
empty_output_buffer
jboolean(* jpeg_destination_mgr::empty_output_buffer) (j_compress_ptr cinfo)
Definition at line 399 of file jpeg.c.
Referenced by JPEG_FileDest(), and JPEG_MemDest().
free_in_buffer
size_t jpeg_destination_mgr::free_in_buffer
Definition at line 396 of file jpeg.c.
Referenced by JPEG_EmptyOutputBuffer(), JPEG_InitDestination(), JPEG_Mem_EmptyOutputBuffer(), JPEG_Mem_InitDestination(), and JPEG_TermDestination().
init_destination
void(* jpeg_destination_mgr::init_destination) (j_compress_ptr cinfo)
Definition at line 398 of file jpeg.c.
Referenced by JPEG_FileDest(), and JPEG_MemDest().
next_output_byte
unsigned char* jpeg_destination_mgr::next_output_byte
Definition at line 395 of file jpeg.c.
Referenced by JPEG_EmptyOutputBuffer(), JPEG_InitDestination(), JPEG_Mem_EmptyOutputBuffer(), JPEG_Mem_InitDestination(), and JPEG_Mem_TermDestination().
term_destination
void(* jpeg_destination_mgr::term_destination) (j_compress_ptr cinfo)
Definition at line 400 of file jpeg.c.
Referenced by JPEG_FileDest(), and JPEG_MemDest().
The documentation for this struct was generated from the following file:
jpeg.c