DarkPlaces: rendermodule_t Struct Reference
rendermodule_t Struct Reference
Data Fields
int active
const char * name
void(* start)(void)
void(* shutdown)(void)
void(* newmap)(void)
void(* devicelost)(void)
void(* devicerestored)(void)
Detailed Description
Definition at line 6 of file r_modules.c.
Field Documentation
active
int rendermodule_t::active
Definition at line 8 of file r_modules.c.
Referenced by R_Modules_Shutdown(), R_Modules_Start(), and R_RegisterModule().
devicelost
void(* rendermodule_t::devicelost) (void)
Definition at line 13 of file r_modules.c.
Referenced by R_Modules_DeviceLost(), and R_RegisterModule().
devicerestored
void(* rendermodule_t::devicerestored) (void)
Definition at line 14 of file r_modules.c.
Referenced by R_Modules_DeviceRestored(), and R_RegisterModule().
name
const char* rendermodule_t::name
Definition at line 9 of file r_modules.c.
Referenced by R_RegisterModule().
newmap
void(* rendermodule_t::newmap) (void)
Definition at line 12 of file r_modules.c.
Referenced by R_Modules_NewMap(), and R_RegisterModule().
shutdown
void(* rendermodule_t::shutdown) (void)
Definition at line 11 of file r_modules.c.
Referenced by R_Modules_Shutdown(), and R_RegisterModule().
start
void(* rendermodule_t::start) (void)
Definition at line 10 of file r_modules.c.
Referenced by R_Modules_Start(), and R_RegisterModule().
The documentation for this struct was generated from the following file:
r_modules.c