DarkPlaces: sys_shared.c File Reference
sys_shared.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <sys/time.h>
#include <time.h>
#include <dlfcn.h>
#include <signal.h>
#include "quakedef.h"
#include "taskqueue.h"
#include "thread.h"
#include "libcurl.h"
Macros
#define SUPPORTDLL
#define HAVE_GETTIMEOFDAY 1
#define HAVE_USLEEP 1
Functions
char * Sys_TimeString (const char *timeformat)
void Sys_AllowProfiling (qbool enable)
static qbool Sys_LoadDependencyFunctions (dllhandle_t dllhandle, const dllfunction_t *fcts, qbool complain, qbool has_next)
qbool Sys_LoadSelf (dllhandle_t *handle)
qbool Sys_LoadDependency (const char **dllnames, dllhandle_t *handle, const dllfunction_t *fcts)
qbool Sys_LoadLibrary (const char *name, dllhandle_t *handle)
void Sys_FreeLibrary (dllhandle_t *handle)
void * Sys_GetProcAddress (dllhandle_t handle, const char *name)
int Sys_CheckParm (const char *parm)
static void Sys_UpdateOutFD_c (cvar_t *var)
void Sys_Init_Commands (void)
called after command system is initialized but before first Con_Print
double Sys_DirtyTime (void)
double Sys_Sleep (double time)
called to yield for a little bit so as not to hog cpu when paused or debugging
void Sys_Print (const char *text, size_t textlen)
(may) output text to terminal which launched program is POSIX async-signal-safe textlen excludes any (optional) \0 terminator
void Sys_Printf (const char *fmt,...)
used to report failures inside Con_Printf()
char * Sys_ConsoleInput (void)
Reads a line from POSIX stdin or the Windows console.
void Sys_Error (const char *error,...)
Causes the entire program to exit ASAP.
static const char * Sys_FindInPATH (const char *name, char namesep, const char *PATH, char pathsep, char *buf, size_t bufsize)
static const char * Sys_FindExecutableName (void)
void Sys_ProvideSelfFD (void)
void Sys_InitProcessNice (void)
called to set process priority for dedicated servers
void Sys_MakeProcessNice (void)
void Sys_MakeProcessMean (void)
static const char * Sys_SigDesc (int sig)
static void Sys_HandleCrash (int sig)
Halt and try not to catch fire.
static void Sys_HandleSignal (int sig)
static void Sys_InitSignals (void)
SDL2 only handles SIGINT and SIGTERM by default and doesn't log anything.
int main (int argc, char **argv)
Variables
sys_t sys
static char sys_timestring [128]
cvar_t sys_usenoclockbutbenchmark = {CF_SHARED, "sys_usenoclockbutbenchmark", "0", "don't use ANY real timing, and simulate a clock (for benchmarking); the game then runs as fast as possible. Run a QC mod with bots that does some stuff, then does a quit at the end, to benchmark a server. NEVER do this on a public server."}
cvar_t sys_libdir = {CF_READONLY | CF_SHARED, "sys_libdir", "", "Default engine library directory"}
static cvar_t sys_debugsleep = {CF_SHARED, "sys_debugsleep", "0", "write requested and attained sleep times to standard output, to be used with gnuplot"}
static cvar_t sys_usesdlgetticks = {CF_SHARED, "sys_usesdlgetticks", "0", "use SDL_GetTicks() timer (less accurate, for debugging)"}
static cvar_t sys_usesdldelay = {CF_SHARED, "sys_usesdldelay", "0", "use SDL_Delay() (less accurate, for debugging)"}
static cvar_t sys_stdout = {CF_SHARED, "sys_stdout", "1", "0: nothing is written to stdout (-nostdout cmdline option sets this), 1: normal messages are written to stdout, 2: normal messages are written to stderr (-stderr cmdline option sets this)"}
static cvar_t sys_stdout_blocks = {CF_SHARED, "sys_stdout_blocks", "0", "1: writes to stdout and stderr streams will block (causing a stutter or complete halt) if the buffer is full, ensuring no messages are lost at a price"}
static double benchmark_time
cvar_t host_maxwait
Macro Definition Documentation
HAVE_GETTIMEOFDAY
#define HAVE_GETTIMEOFDAY 1
Definition at line 282 of file sys_shared.c.
HAVE_USLEEP
#define HAVE_USLEEP 1
Definition at line 291 of file sys_shared.c.
SUPPORTDLL
#define SUPPORTDLL
Definition at line 7 of file sys_shared.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 1061 of file sys_shared.c.
{
    sys.argc = argc;
    sys.argv = (const char **)argv;
    // COMMANDLINEOPTION: Console: -nostdout disables text output to the terminal the game was launched from
    // COMMANDLINEOPTION: -noterminal disables console output on stdout
    if(Sys_CheckParm("-noterminal") || Sys_CheckParm("-nostdout"))
        sys_stdout.string = "0";
    // COMMANDLINEOPTION: -stderr moves console output to stderr
    else if(Sys_CheckParm("-stderr"))
        sys_stdout.string = "2";
    // too early for Cvar_SetQuick
    sys_stdout.value = sys_stdout.integer = atoi(sys_stdout.string);
    Sys_UpdateOutFD_c(&sys_stdout);
#ifndef WIN32
    fcntl(fileno(stdin), F_SETFL, fcntl(fileno(stdin), F_GETFL, 0) | O_NONBLOCK);
    // stdout/stderr will be set to blocking in Sys_Print() if so configured, or during a fatal error.
    fcntl(fileno(stdout), F_SETFL, fcntl(fileno(stdout), F_GETFL, 0) | O_NONBLOCK);
    fcntl(fileno(stderr), F_SETFL, fcntl(fileno(stderr), F_GETFL, 0) | O_NONBLOCK);
#endif
    sys.selffd = -1;
    Sys_ProvideSelfFD(); // may call Con_Printf() so must be after sys.outfd is set
#ifdef __ANDROID__
    Sys_AllowProfiling(true);
#endif
    Sys_InitSignals();
    Host_Main();
#ifdef __ANDROID__
    Sys_AllowProfiling(false);
#endif
#ifndef WIN32
    fcntl(fileno(stdout), F_SETFL, fcntl(fileno(stdout), F_GETFL, 0) & ~O_NONBLOCK);
    fcntl(fileno(stderr), F_SETFL, fcntl(fileno(stderr), F_GETFL, 0) & ~O_NONBLOCK);
#endif
    fflush(stdout);
    fflush(stderr);
    return 0;
}
Sys_AllowProfiling()
void Sys_AllowProfiling (qbool enable)
on some build/platform combinations (such as Linux gcc with the -pg profiling option) this can turn on/off profiling, used primarily to limit profiling to certain areas of the code, such as ingame performance without regard for loading/shutdown performance (-profilegameonly on commandline)
Definition at line 62 of file sys_shared.c.
{
#ifdef __ANDROID__
#ifdef USE_PROFILER
    extern void monstartup(const char *libname);
    extern void moncleanup(void);
    if (enable)
        monstartup("libmain.so");
    else
        moncleanup();
#endif
#elif (defined(__linux__) && (defined(__GLIBC__) || defined(__GNU_LIBRARY__))) || defined(__FreeBSD__)
    extern int moncontrol(int);
    moncontrol(enable);
#endif
}
Referenced by CL_DisconnectEx(), CL_SignonReply(), Host_Init(), Host_Shutdown(), and main().
Sys_CheckParm()
int Sys_CheckParm (const char * parm)
Definition at line 324 of file sys_shared.c.
{
    int i;
    for (i=1 ; i<sys.argc ; i++)
    {
        if (!sys.argv[i])
            continue;               // NEXTSTEP sometimes clears appkit vars.
        if (!strcmp (parm,sys.argv[i]))
            return i;
    }
    return 0;
}
Referenced by CDAudio_Init(), CDAudio_Startup(), CL_DisconnectEx(), CL_EstablishConnection(), CL_FinishTimeDemo(), CL_PlayVideo_f(), CL_Screen_Init(), CL_SignonReply(), CL_Startdemos_f(), CL_StopPlayback(), Cmd_Exec(), COM_InitGameType(), COM_SetGameType(), Con_Init(), Con_ToggleConsole_f(), FS_Init_Dir(), FS_Init_SelfPack(), FS_mkdir(), FS_Rescan(), FS_SysOpenFiledesc(), GL_CheckExtension(), Host_Init(), Host_InitSession(), Host_LockSession(), Host_SaveConfig(), Host_Shutdown(), Key_Event(), LibAV_LoadLibrary(), LibAvW_OpenLibrary(), main(), MR_Init(), NetConn_Init(), OGG_OpenLibrary(), Palette_Load(), PRVM_Init(), S_Init(), S_Startup(), SV_ServerOptions(), Sys_SDL_Init(), VID_InitModeGL(), VID_Start(), XMP_LoadModFile(), and XMP_OpenLibrary().
Sys_ConsoleInput()
char * Sys_ConsoleInput (void)
Reads a line from POSIX stdin or the Windows console.
Definition at line 620 of file sys_shared.c.
{
    static char text[MAX_INPUTLINE];
#ifdef WIN32
    static unsigned int len = 0;
    int c;
    // read a line out
    while (_kbhit ())
    {
        c = _getch ();
        if (c == '\r')
        {
            text[len] = '\0';
            _putch ('\n');
            len = 0;
            return text;
        }
        if (c == '\b')
        {
            if (len)
            {
                _putch (c);
                _putch (' ');
                _putch (c);
                len--;
            }
            continue;
        }
        if (len < sizeof (text) - 1)
        {
            _putch (c);
            text[len] = c;
            len++;
        }
    }
#else
    fd_set fdset;
    struct timeval timeout = { .tv_sec = 0, .tv_usec = 0 };
    FD_ZERO(&fdset);
    FD_SET(fileno(stdin), &fdset);
    if (select(1, &fdset, NULL, NULL, &timeout) != -1 && FD_ISSET(fileno(stdin), &fdset))
        return fgets(text, sizeof(text), stdin);
#endif
    return NULL;
}
Referenced by Cbuf_Frame_Input().
Sys_DirtyTime()
double Sys_DirtyTime (void)
Definition at line 375 of file sys_shared.c.
{
    // first all the OPTIONAL timers
    // benchmark timer (fake clock)
    if(sys_usenoclockbutbenchmark.integer)
    {
        double old_benchmark_time = benchmark_time;
        benchmark_time += 1;
        if(benchmark_time == old_benchmark_time)
            Sys_Error("sys_usenoclockbutbenchmark cannot run any longer, sorry");
        return benchmark_time * 0.000001;
    }
#if HAVE_QUERYPERFORMANCECOUNTER
    if (sys_usequeryperformancecounter.integer)
    {
        // LadyHavoc: note to people modifying this code, DWORD is specifically defined as an unsigned 32bit number, therefore the 65536.0 * 65536.0 is fine.
        // QueryPerformanceCounter
        // platform:
        // Windows 95/98/ME/NT/2000/XP
        // features:
        // very accurate (CPU cycles)
        // known issues:
        // does not necessarily match realtime too well (tends to get faster and faster in win98)
        // wraps around occasionally on some platforms (depends on CPU speed and probably other unknown factors)
        double timescale;
        LARGE_INTEGER PerformanceFreq;
        LARGE_INTEGER PerformanceCount;
        if (QueryPerformanceFrequency (&PerformanceFreq))
        {
            QueryPerformanceCounter (&PerformanceCount);
            timescale = 1.0 / ((double) PerformanceFreq.LowPart + (double) PerformanceFreq.HighPart * 65536.0 * 65536.0);
            return ((double) PerformanceCount.LowPart + (double) PerformanceCount.HighPart * 65536.0 * 65536.0) * timescale;
        }
        else
        {
            Con_Printf("No hardware timer available\n");
            // fall back to other clock sources
            Cvar_SetValueQuick(&sys_usequeryperformancecounter, false);
        }
    }
#endif
#if HAVE_CLOCKGETTIME
    if (sys_useclockgettime.integer)
    {
        struct timespec ts;
#  ifdef CLOCK_MONOTONIC
        // linux
        clock_gettime(CLOCK_MONOTONIC, &ts);
#  else
        // sunos
        clock_gettime(CLOCK_HIGHRES, &ts);
#  endif
        return (double) ts.tv_sec + ts.tv_nsec / 1000000000.0;
    }
#endif
    // now all the FALLBACK timers
    if(sys_supportsdlgetticks && sys_usesdlgetticks.integer)
        return (double) Sys_SDL_GetTicks() / 1000.0;
#if HAVE_GETTIMEOFDAY
    {
        struct timeval tp;
        gettimeofday(&tp, NULL);
        return (double) tp.tv_sec + tp.tv_usec / 1000000.0;
    }
#elif HAVE_TIMEGETTIME
    {
        static int firsttimegettime = true;
        // timeGetTime
        // platform:
        // Windows 95/98/ME/NT/2000/XP
        // features:
        // reasonable accuracy (millisecond)
        // issues:
        // wraps around every 47 days or so (but this is non-fatal to us, odd times are rejected, only causes a one frame stutter)
        // make sure the timer is high precision, otherwise different versions of windows have varying accuracy
        if (firsttimegettime)
        {
            timeBeginPeriod(1);
            firsttimegettime = false;
        }
        return (double) timeGetTime() / 1000.0;
    }
#else
    // fallback for using the SDL timer if no other timer is available
    // this calls Sys_Error() if not linking against SDL
    return (double) Sys_SDL_GetTicks() / 1000.0;
#endif
}
Referenced by CL_Frame(), CL_KeepaliveMessage(), CL_TimeRefresh_f(), CL_UpdateScreen(), CLVM_ExecuteProgram(), Crypto_ServerParsePacket(), Host_Main(), PRVM_CallProfile(), PRVM_Prog_Load(), R_TimeReport(), R_TimeReport_BeginFrame(), R_TimeReport_EndFrame(), SV_Frame(), SV_ThreadFunc(), SVVM_ExecuteProgram(), Sys_Sleep(), VM_CL_R_AddDynamicLight(), VM_CL_R_AddEntities(), VM_CL_R_AddEntity(), VM_CL_R_RenderScene(), VM_gettime(), and while().
Sys_Error()
void Sys_Error (const char * error, ...)
Causes the entire program to exit ASAP.
Trailing
should be omitted.
Definition at line 677 of file sys_shared.c.
{
    va_list argptr;
    char string[MAX_INPUTLINE];
    int i;
    // Disable Sys_HandleSignal() but not Sys_HandleCrash()
    host.state = host_shutdown;
    // set output to blocking stderr
    sys.outfd = fileno(stderr);
#ifndef WIN32
    fcntl(sys.outfd, F_SETFL, fcntl(sys.outfd, F_GETFL, 0) & ~O_NONBLOCK);
#endif
    va_start (argptr,error);
    dpvsnprintf (string, sizeof (string), error, argptr);
    va_end (argptr);
    Con_Printf(CON_ERROR "Engine Aborted: %s\n^9%s\n", string, engineversion);
    dp_strlcat(string, "\n\n", sizeof(string));
    dp_strlcat(string, engineversion, sizeof(string));
    // Most shutdown funcs can't be called here as they could error while we error.
    // DP8 TODO: send a disconnect message indicating we aborted, see Host_Error() and Sys_HandleCrash()
    if (cls.demorecording)
        CL_Stop_f(cmd_local);
    if (sv.active)
    {
        sv.active = false; // make SV_DropClient() skip the QC stuff to avoid recursive errors
        for (i = 0, host_client = svs.clients;i < svs.maxclients;i++, host_client++)
            if (host_client->active)
                SV_DropClient(false, "Server aborted!"); // closes demo file
    }
    // don't want a dead window left blocking the OS UI or the abort dialog
    VID_Shutdown();
    S_StopAllSounds();
    host.state = host_failed; // make Sys_HandleSignal() call _Exit()
    Sys_SDL_Dialog("Engine Aborted", string);
    fflush(stderr);
    exit (1);
}
Referenced by _Mem_Alloc(), _Mem_AllocPool(), _Mem_CheckSentinels(), _Mem_CheckSentinelsGlobal(), _Mem_EmptyPool(), _Mem_Free(), _Mem_FreeBlock(), _Mem_FreePool(), Buffer_Callback(), CL_CutDemo(), CL_ExpandEntities(), Clump_AllocBlock(), Clump_FreeBlock(), GL_InitFunctions(), GL_Setup(), Host_Error(), Host_Init(), Host_LockSession(), M_Menu_Keys_f(), Mem_ExpandableArray_FreeRecord(), MVM_error_cmd(), PHYS_NudgeOutOfSolid(), R_BufferData_Store(), R_Mesh_TexBind(), R_Mesh_TexBound(), R_Mesh_TexCoordPointer(), R_RegisterModule(), R_SetupTexture(), R_UploadFullTexture(), R_UploadPartialTexture(), RSurf_DrawBatch(), SCR_CaptureVideo_Avi_BeginVideo(), SCR_CaptureVideo_Ogg_Interleave(), SCR_CaptureVideo_RIFF_IndexEntry(), SCR_CaptureVideo_RIFF_MakeIxChunk(), SCR_CaptureVideo_RIFF_OverflowCheck(), setuptex(), SndSys_Write(), SV_SendClientMessages(), Sys_DirtyTime(), Sys_SDL_Delay(), Sys_SDL_GetTicks(), Sys_SDL_Init(), Sys_Sleep(), VID_Init(), VID_InitMode(), VID_InitModeGL(), VID_Restart_f(), VID_Start(), and VM_nudgeoutofsolid().
Sys_FindExecutableName()
static const char * Sys_FindExecutableName (void) static
Definition at line 750 of file sys_shared.c.
{
#if defined(WIN32)
    return sys.argv[0];
#else
    static char exenamebuf[MAX_OSPATH+1];
    ssize_t n = -1;
#if defined(__FreeBSD__)
    int mib[4] = {CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1};
    size_t exenamebuflen = sizeof(exenamebuf)-1;
    if (sysctl(mib, 4, exenamebuf, &exenamebuflen, NULL, 0) == 0)
    {
        n = exenamebuflen;
    }
#elif defined(__linux__)
    n = readlink("/proc/self/exe", exenamebuf, sizeof(exenamebuf)-1);
#endif
    if(n > 0 && (size_t)(n) < sizeof(exenamebuf))
    {
        exenamebuf[n] = 0;
        return exenamebuf;
    }
    if(strchr(sys.argv[0], '/'))
        return sys.argv[0]; // possibly a relative path
    else
        return Sys_FindInPATH(sys.argv[0], '/', getenv("PATH"), ':', exenamebuf, sizeof(exenamebuf));
#endif
}
Referenced by Sys_ProvideSelfFD().
Sys_FindInPATH()
static const char * Sys_FindInPATH (const char * name, char namesep, const char * PATH, char pathsep, char * buf, size_t bufsize) static
Definition at line 726 of file sys_shared.c.
{
    const char *p = PATH;
    const char *q;
    if(p && name)
    {
        while((q = strchr(p, ':')))
        {
            dpsnprintf(buf, bufsize, "%.*s%c%s", (int)(q-p), p, namesep, name);
            if(FS_SysFileExists(buf))
                return buf;
            p = q + 1;
        }
        if(!q) // none found - try the last item
        {
            dpsnprintf(buf, bufsize, "%s%c%s", p, namesep, name);
            if(FS_SysFileExists(buf))
                return buf;
        }
    }
    return name;
}
Referenced by Sys_FindExecutableName().
Sys_FreeLibrary()
void Sys_FreeLibrary (dllhandle_t * handle)
Definition at line 242 of file sys_shared.c.
{
#ifdef SUPPORTDLL
    if (handle == NULL || *handle == NULL)
        return;
#ifdef WIN32
    FreeLibrary (*handle);
#else
    dlclose (*handle);
#endif
    *handle = NULL;
#endif
}
Referenced by Crypto_CloseLibrary(), Crypto_Rijndael_CloseLibrary(), CURL_CloseLibrary(), Font_CloseLibrary(), FS_Shutdown(), JPEG_CloseLibrary(), LibAV_LoadLibrary(), LibAvW_CloseLibrary(), LibAvW_OpenLibrary(), OGG_CloseLibrary(), PK3_CloseLibrary(), PNG_CloseLibrary(), PNG_OpenLibrary(), SCR_CaptureVideo_Ogg_CloseDLL(), Sys_LoadDependency(), XMP_CloseLibrary(), and XMP_OpenLibrary().
Sys_GetProcAddress()
void * Sys_GetProcAddress (dllhandle_t handle, const char * name)
Definition at line 258 of file sys_shared.c.
{
#ifdef SUPPORTDLL
#ifdef WIN32
    return (void *)GetProcAddress (handle, name);
#else
    return (void *)dlsym (handle, name);
#endif
#else
    return NULL;
#endif
}
Referenced by Sys_LoadDependencyFunctions().
Sys_HandleCrash()
static void Sys_HandleCrash (int sig) static
Halt and try not to catch fire.
Writing to any file could corrupt it, any uneccessary code could crash while we crash. Try to use only POSIX async-signal-safe library functions here (see: man signal-safety).
Definition at line 947 of file sys_shared.c.
{
#if __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 1
    // Before doing anything else grab the stack frame addresses
    #include <execinfo.h>
    void *stackframes[32];
    int framecount = backtrace(stackframes, 32);
    char **btstrings;
#endif
    char dialogtext[3072];
    const char *sigdesc;
    // Break any loop and disable Sys_HandleSignal()
    if (host.state == host_failing || host.state == host_failed)
        return;
    host.state = host_failing;
    sigdesc = Sys_SigDesc(sig);
    // set output to blocking stderr and print header, backtrace, version
    sys.outfd = fileno(stderr); // not async-signal-safe :(
#ifndef WIN32
    fcntl(sys.outfd, F_SETFL, fcntl(sys.outfd, F_GETFL, 0) & ~O_NONBLOCK);
    Sys_Print("\n\n\e[1;37;41m    Engine Crash: ", 30);
    Sys_Print(sigdesc, strlen(sigdesc));
    Sys_Print("    \e[m\n", 8);
  #if __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 1
    // the first two addresses will be in this function and in signal() in libc
    backtrace_symbols_fd(stackframes + 2, framecount - 2, sys.outfd);
  #endif
    Sys_Print("\e[1m", 4);
    Sys_Print(engineversion, strlen(engineversion));
    Sys_Print("\e[m\n", 4);
#else // Windows console doesn't support colours
    Sys_Print("\n\nEngine Crash: ", 16);
    Sys_Print(sigdesc, strlen(sigdesc));
    Sys_Print("\n", 1);
    Sys_Print(engineversion, strlen(engineversion));
    Sys_Print("\n", 1);
#endif
    // DP8 TODO: send a disconnect message indicating we crashed, see Sys_Error() and Host_Error()
    // don't want a dead window left blocking the OS UI or the crash dialog
    VID_Shutdown();
    S_StopAllSounds();
    // prepare the dialogtext: signal, backtrace, version
    // the dp_st* funcs are POSIX async-signal-safe IF we don't trigger their warnings
    dp_strlcpy(dialogtext, sigdesc, sizeof(dialogtext));
    dp_strlcat(dialogtext, "\n\n", sizeof(dialogtext));
#if __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 1
    btstrings = backtrace_symbols(stackframes + 2, framecount - 2); // calls malloc :(
    if (btstrings)
        for (int i = 0; i < framecount - 2; ++i)
        {
            dp_strlcat(dialogtext, btstrings[i], sizeof(dialogtext));
            dp_strlcat(dialogtext, "\n", sizeof(dialogtext));
        }
#endif
    dp_strlcat(dialogtext, "\n", sizeof(dialogtext));
    dp_strlcat(dialogtext, engineversion, sizeof(dialogtext));
    host.state = host_failed; // make Sys_HandleSignal() call _Exit()
    Sys_SDL_Dialog("Engine Crash", dialogtext);
    fflush(stderr); // not async-signal-safe :(
    // Continue execution with default signal handling.
    // A real crash will be re-triggered so the platform can handle it,
    // a fake crash (kill -SEGV) will cause a graceful shutdown.
    signal(sig, SIG_DFL);
}
Referenced by Sys_InitSignals().
Sys_HandleSignal()
static void Sys_HandleSignal (int sig) static
Definition at line 1021 of file sys_shared.c.
{
    const char *sigdesc;
    // Break any loop, eg if each Sys_Print triggers a SIGPIPE
    if (host.state == host_shutdown || host.state == host_failing)
        return;
    sigdesc = Sys_SigDesc(sig);
    Sys_Print("\nReceived ", 10);
    Sys_Print(sigdesc, strlen(sigdesc));
    Sys_Print(" signal, exiting...\n", 20);
    if (host.state == host_failed)
    {
        // user is trying to kill the process while the SDL dialog is open
        fflush(stderr); // not async-signal-safe :(
        _Exit(sig);
    }
    host.state = host_shutdown;
}
Referenced by Sys_InitSignals().
Sys_Init_Commands()
void Sys_Init_Commands (void)
called after command system is initialized but before first Con_Print
Definition at line 350 of file sys_shared.c.
{
    Cvar_RegisterVariable(&sys_debugsleep);
    Cvar_RegisterVariable(&sys_usenoclockbutbenchmark);
    Cvar_RegisterVariable(&sys_libdir);
#if HAVE_TIMEGETTIME || HAVE_QUERYPERFORMANCECOUNTER || HAVE_CLOCKGETTIME || HAVE_GETTIMEOFDAY
    if(sys_supportsdlgetticks)
    {
        Cvar_RegisterVariable(&sys_usesdlgetticks);
        Cvar_RegisterVariable(&sys_usesdldelay);
    }
#endif
#if HAVE_QUERYPERFORMANCECOUNTER
    Cvar_RegisterVariable(&sys_usequeryperformancecounter);
#endif
#if HAVE_CLOCKGETTIME
    Cvar_RegisterVariable(&sys_useclockgettime);
#endif
    Cvar_RegisterVariable(&sys_stdout);
    Cvar_RegisterCallback(&sys_stdout, Sys_UpdateOutFD_c);
#ifndef WIN32
    Cvar_RegisterVariable(&sys_stdout_blocks);
#endif
}
Referenced by Host_Init().
Sys_InitProcessNice()
void Sys_InitProcessNice (void)
called to set process priority for dedicated servers
Definition at line 908 of file sys_shared.c.
{
}
Referenced by Host_Init().
Sys_InitSignals()
static void Sys_InitSignals (void) static
SDL2 only handles SIGINT and SIGTERM by default and doesn't log anything.
Definition at line 1043 of file sys_shared.c.
{
    // Windows only supports the C99 signals
    signal(SIGINT,  Sys_HandleSignal);
    signal(SIGILL,  Sys_HandleCrash);
    signal(SIGABRT, Sys_HandleCrash);
    signal(SIGFPE,  Sys_HandleCrash);
    signal(SIGSEGV, Sys_HandleCrash);
    signal(SIGTERM, Sys_HandleSignal);
#ifndef WIN32
    // POSIX has several others worth catching
    signal(SIGHUP,  Sys_HandleSignal);
    signal(SIGQUIT, Sys_HandleSignal);
    signal(SIGBUS,  Sys_HandleCrash);
    signal(SIGPIPE, Sys_HandleSignal);
#endif
}
Referenced by main().
Sys_LoadDependency()
qbool Sys_LoadDependency (const char ** dllnames, dllhandle_t * handle, const dllfunction_t * fcts)
Loads a dependency library.
Parameters
dllnames a NULL terminated array of possible names for the DLL you want to load.
handle
fcts
Definition at line 128 of file sys_shared.c.
{
#ifdef SUPPORTDLL
    const dllfunction_t *func;
    dllhandle_t dllhandle = 0;
    unsigned int i;
    if (handle == NULL)
        return false;
#ifndef WIN32
#ifdef PREFER_PRELOAD
    dllhandle = dlopen(NULL, RTLD_LAZY | RTLD_GLOBAL);
    if(Sys_LoadDependencyFunctions(dllhandle, fcts, false, false))
    {
        Con_DPrintf ("All of %s's functions were already linked in! Not loading dynamically...\n", dllnames[0]);
        *handle = dllhandle;
        return true;
    }
    else
        Sys_FreeLibrary(&dllhandle);
notfound:
#endif
#endif
    // Initializations
    for (func = fcts; func && func->name != NULL; func++)
        *func->funcvariable = NULL;
    // Try every possible name
    Con_DPrintf ("Trying to load library...");
    for (i = 0; dllnames[i] != NULL; i++)
    {
        Con_DPrintf (" \"%s\"", dllnames[i]);
#ifdef WIN32
# ifndef DONT_USE_SETDLLDIRECTORY
#  ifdef _WIN64
        SetDllDirectory("bin64");
#  else
        SetDllDirectory("bin32");
#  endif
# endif
#endif
        if(Sys_LoadLibrary(dllnames[i], &dllhandle))
        {
            if (Sys_LoadDependencyFunctions(dllhandle, fcts, true, (dllnames[i+1] != NULL) || (strrchr(sys.argv[0], '/'))))
                break;
            else
                Sys_FreeLibrary (&dllhandle);
        }
    }
    // see if the names can be loaded relative to the executable path
    // (this is for Mac OSX which does not check next to the executable)
    if (!dllhandle && strrchr(sys.argv[0], '/'))
    {
        char path[MAX_OSPATH];
        dp_strlcpy(path, sys.argv[0], sizeof(path));
        strrchr(path, '/')[1] = 0;
        for (i = 0; dllnames[i] != NULL; i++)
        {
            char temp[MAX_OSPATH];
            dp_strlcpy(temp, path, sizeof(temp));
            dp_strlcat(temp, dllnames[i], sizeof(temp));
            Con_DPrintf (" \"%s\"", temp);
            if(Sys_LoadLibrary(temp, &dllhandle))
            {
                if (Sys_LoadDependencyFunctions(dllhandle, fcts, true, (dllnames[i+1] != NULL) || (strrchr(sys.argv[0], '/'))))
                    break;
                else
                    Sys_FreeLibrary (&dllhandle);
            }
        }
    }
    // No DLL found
    if (! dllhandle)
    {
        Con_DPrintf(" - failed.\n");
        return false;
    }
    Con_DPrintf(" - loaded.\n");
    Con_Printf("Loaded library \"%s\"\n", dllnames[i]);
    *handle = dllhandle;
    return true;
#else
    return false;
#endif
}
Referenced by Crypto_OpenLibrary(), Crypto_Rijndael_OpenLibrary(), CURL_OpenLibrary(), Font_OpenLibrary(), FS_ChooseUserDir(), JPEG_OpenLibrary(), LibAV_LoadLibrary(), LibAvW_OpenLibrary(), OGG_OpenLibrary(), PK3_OpenLibrary(), PNG_OpenLibrary(), SCR_CaptureVideo_Ogg_OpenLibrary(), VID_Shared_Init(), and XMP_OpenLibrary().
Sys_LoadDependencyFunctions()
static qbool Sys_LoadDependencyFunctions (dllhandle_t dllhandle, const dllfunction_t * fcts, qbool complain, qbool has_next) static
Definition at line 88 of file sys_shared.c.
{
    const dllfunction_t *func;
    if(dllhandle)
    {
        for (func = fcts; func && func->name != NULL; func++)
            if (!(*func->funcvariable = (void *) Sys_GetProcAddress (dllhandle, func->name)))
            {
                if(complain)
                {
                    Con_DPrintf (" - missing function \"%s\" - broken library!", func->name);
                    if(has_next)
                        Con_DPrintf("\nContinuing with");
                }
                goto notfound;
            }
        return true;
    notfound:
        for (func = fcts; func && func->name != NULL; func++)
            *func->funcvariable = NULL;
    }
    return false;
}
Referenced by Sys_LoadDependency().
Sys_LoadLibrary()
qbool Sys_LoadLibrary (const char * name, dllhandle_t * handle)
Loads a library.
Parameters
name a string of the library filename
handle
Returns
true if library was loaded successfully
Definition at line 221 of file sys_shared.c.
{
    dllhandle_t dllhandle = 0;
    if(handle == NULL)
        return false;
#ifdef SUPPORTDLL
# ifdef WIN32
    dllhandle = LoadLibrary (name);
# else
    dllhandle = dlopen (name, RTLD_LAZY | RTLD_GLOBAL);
# endif
#endif
    if(!dllhandle)
        return false;
    *handle = dllhandle;
    return true;
}
Referenced by Sys_LoadDependency().
Sys_LoadSelf()
qbool Sys_LoadSelf (dllhandle_t * handle)
Definition at line 113 of file sys_shared.c.
{
    dllhandle_t dllhandle = 0;
    if (handle == NULL)
        return false;
#ifdef WIN32
    dllhandle = LoadLibrary (NULL);
#else
    dllhandle = dlopen (NULL, RTLD_NOW | RTLD_GLOBAL);
#endif
    *handle = dllhandle;
    return true;
}
Sys_MakeProcessMean()
void Sys_MakeProcessMean (void)
Definition at line 914 of file sys_shared.c.
{
}
Referenced by Host_AbortCurrentFrame(), and SV_SpawnServer().
Sys_MakeProcessNice()
void Sys_MakeProcessNice (void)
Definition at line 911 of file sys_shared.c.
{
}
Referenced by SV_SpawnServer().
Sys_Print()
void Sys_Print (const char * text, size_t textlen)
(may) output text to terminal which launched program is POSIX async-signal-safe textlen excludes any (optional) \0 terminator
Definition at line 569 of file sys_shared.c.
{
#ifdef __ANDROID__
    if (developer.integer > 0)
    {
        __android_log_write(ANDROID_LOG_DEBUG, sys.argv[0], text);
    }
#else
    if(sys.outfd < 0)
        return;
  #ifndef WIN32
    // BUG: for some reason, NDELAY also affects stdout (1) when used on stdin (0).
    // this is because both go to /dev/tty by default!
    {
        int origflags = fcntl(sys.outfd, F_GETFL, 0);
        if (sys_stdout_blocks.integer)
            fcntl(sys.outfd, F_SETFL, origflags & ~O_NONBLOCK);
  #else
    #define write _write
  #endif
        while(*text)
        {
            fs_offset_t written = (fs_offset_t)write(sys.outfd, text, textlen);
            if(written <= 0)
                break; // sorry, I cannot do anything about this error - without an output
            text += written;
        }
  #ifndef WIN32
        if (sys_stdout_blocks.integer)
            fcntl(sys.outfd, F_SETFL, origflags);
    }
  #endif
    //fprintf(stdout, "%s", text);
#endif
}
Referenced by Con_MaskPrint(), Sys_HandleCrash(), Sys_HandleSignal(), and Sys_Printf().
Sys_Printf()
void Sys_Printf (const char * fmt, ...)
used to report failures inside Con_Printf()
Definition at line 605 of file sys_shared.c.
{
    va_list argptr;
    char msg[MAX_INPUTLINE];
    int msglen;
    va_start(argptr,fmt);
    msglen = dpvsnprintf(msg, sizeof(msg), fmt, argptr);
    va_end(argptr);
    if (msglen >= 0)
        Sys_Print(msg, msglen);
}
Referenced by _Thread_AtomicAdd(), _Thread_AtomicDecRef(), _Thread_AtomicGet(), _Thread_AtomicIncRef(), _Thread_AtomicLock(), _Thread_AtomicSet(), _Thread_AtomicTryLock(), _Thread_AtomicUnlock(), _Thread_CondBroadcast(), _Thread_CondSignal(), _Thread_CondWait(), _Thread_CreateBarrier(), _Thread_CreateCond(), _Thread_CreateMutex(), _Thread_CreateThread(), _Thread_DestroyBarrier(), _Thread_DestroyCond(), _Thread_DestroyMutex(), _Thread_LockMutex(), _Thread_UnlockMutex(), _Thread_WaitBarrier(), _Thread_WaitThread(), _Thread_WaitThread(), Con_WordWidthFunc(), and dpvsnprintf().
Sys_ProvideSelfFD()
void Sys_ProvideSelfFD (void)
Definition at line 779 of file sys_shared.c.
{
    if(sys.selffd != -1)
        return;
    sys.selffd = FS_SysOpenFD(Sys_FindExecutableName(), "rb", false);
}
Referenced by main().
Sys_SigDesc()
static const char * Sys_SigDesc (int sig) static
Definition at line 920 of file sys_shared.c.
{
    switch (sig)
    {
        // Windows only supports the C99 signals
        case SIGINT:  return "Interrupt";
        case SIGILL:  return "Illegal instruction";
        case SIGABRT: return "Aborted";
        case SIGFPE:  return "Floating point exception";
        case SIGSEGV: return "Segmentation fault";
        case SIGTERM: return "Termination";
#ifndef WIN32
        // POSIX has several others worth catching
        case SIGHUP:  return "Hangup";
        case SIGQUIT: return "Quit";
        case SIGBUS:  return "Bus error (bad memory access)";
        case SIGPIPE: return "Broken pipe";
#endif
        default:      return "Yo dawg, we bugged out while bugging out";
    }
}
Referenced by Sys_HandleCrash(), and Sys_HandleSignal().
Sys_Sleep()
double Sys_Sleep (double time)
called to yield for a little bit so as not to hog cpu when paused or debugging
Definition at line 472 of file sys_shared.c.
{
    double dt;
    uint32_t microseconds;
    // convert to microseconds
    time *= 1000000.0;
    if(host_maxwait.value <= 0)
        time = min(time, 1000000.0);
    else
        time = min(time, host_maxwait.value * 1000.0);
    if (time < 1 || host.restless)
        return 0; // not sleeping this frame
    microseconds = time; // post-validation to prevent overflow
    if(sys_usenoclockbutbenchmark.integer)
    {
        double old_benchmark_time = benchmark_time;
        benchmark_time += microseconds;
        if(benchmark_time == old_benchmark_time)
            Sys_Error("sys_usenoclockbutbenchmark cannot run any longer, sorry");
        return 0;
    }
    if(sys_debugsleep.integer)
        Con_Printf("sys_debugsleep: requesting %u ", microseconds);
    dt = Sys_DirtyTime();
    // less important on newer libcurl so no need to disturb dedicated servers
    if (cls.state != ca_dedicated && Curl_Select(microseconds))
    {
        // a transfer is ready or we finished sleeping
    }
    else if(sys_supportsdlgetticks && sys_usesdldelay.integer)
        Sys_SDL_Delay(microseconds / 1000);
#if HAVE_SELECT
    else
    {
        struct timeval tv;
        lhnetsocket_t *s;
        fd_set fdreadset;
        int lastfd = -1;
        FD_ZERO(&fdreadset);
        if (cls.state == ca_dedicated && sv_checkforpacketsduringsleep.integer)
        {
            List_For_Each_Entry(s, &lhnet_socketlist.list, lhnetsocket_t, list)
            {
                if (s->address.addresstype == LHNETADDRESSTYPE_INET4 || s->address.addresstype == LHNETADDRESSTYPE_INET6)
                {
                    if (lastfd < s->inetsocket)
                        lastfd = s->inetsocket;
    #if defined(WIN32) && !defined(_MSC_VER)
                    FD_SET((int)s->inetsocket, &fdreadset);
    #else
                    FD_SET((unsigned int)s->inetsocket, &fdreadset);
    #endif
                }
            }
        }
        tv.tv_sec = microseconds / 1000000;
        tv.tv_usec = microseconds % 1000000;
        // on Win32, select() cannot be used with all three FD list args being NULL according to MSDN
        // (so much for POSIX...)
        // bones_was_here: but a zeroed fd_set seems to be tolerated (tested on Win 7)
        select(lastfd + 1, &fdreadset, NULL, NULL, &tv);
    }
#elif HAVE_USLEEP
    else
        usleep(microseconds);
#elif HAVE_Sleep
    else
        Sleep(microseconds / 1000);
#else
    else
        Sys_SDL_Delay(microseconds / 1000);
#endif
    dt = Sys_DirtyTime() - dt;
    if(sys_debugsleep.integer)
        Con_Printf(" got %u oversleep %d\n", (unsigned int)(dt * 1000000), (unsigned int)(dt * 1000000) - microseconds);
    return (dt < 0 || dt >= 1800) ? 0 : dt;
}
Referenced by attempt_malloc(), CL_Frame(), Host_Main(), SV_ThreadFunc(), and TaskQueue_ThreadFunc().
Sys_TimeString()
char * Sys_TimeString (const char * timeformat)
Returns
current timestamp
Definition at line 45 of file sys_shared.c.
{
    time_t mytime = time(NULL);
#if _MSC_VER >= 1400
    struct tm mytm;
    localtime_s(&mytm, &mytime);
    strftime(sys_timestring, sizeof(sys_timestring), timeformat, &mytm);
#else
    strftime(sys_timestring, sizeof(sys_timestring), timeformat, localtime(&mytime));
#endif
    return sys_timestring;
}
Referenced by CL_FinishTimeDemo(), CL_Locs_Save_f(), CL_ParseServerInfo(), Con_MaskPrint(), Sbar_ShowFPS(), SCR_ScreenShot_f(), and SV_SendServerinfo().
Sys_UpdateOutFD_c()
static void Sys_UpdateOutFD_c (cvar_t * var) static
Definition at line 339 of file sys_shared.c.
{
    switch (sys_stdout.integer)
    {
        case 0: sys.outfd = -1; break;
        default:
        case 1: sys.outfd = fileno(stdout); break;
        case 2: sys.outfd = fileno(stderr); break;
    }
}
Referenced by main(), and Sys_Init_Commands().
Variable Documentation
benchmark_time
double benchmark_time static
Definition at line 314 of file sys_shared.c.
Referenced by Sys_DirtyTime(), and Sys_Sleep().
host_maxwait
cvar_t host_maxwait extern
Definition at line 47 of file host.c.
{CF_CLIENT | CF_SERVER, "host_maxwait","1000", "maximum sleep time requested from the operating system in millisecond. Larger sleeps will be done using multiple host_maxwait length sleeps. Lowering this value will increase CPU load, but may help working around problems with accuracy of sleep times."};
Referenced by Host_InitLocal(), and Sys_Sleep().
sys
sys_t sys
Definition at line 42 of file sys_shared.c.
Referenced by CL_FinishTimeDemo(), Cmd_StuffCmds_f(), COM_Init_Commands(), COM_InitGameType(), COM_InsertFlags(), COM_SetGameType(), Con_MaskPrint(), FS_Init_Dir(), FS_Init_SelfPack(), FS_Rescan(), Host_Error(), Host_Init(), Host_InitSession(), main(), MVM_error_cmd(), NetConn_Init(), Palette_Load(), S_Startup(), SV_ServerOptions(), Sys_CheckParm(), Sys_Error(), Sys_FindExecutableName(), Sys_HandleCrash(), Sys_LoadDependency(), Sys_Print(), Sys_ProvideSelfFD(), Sys_UpdateOutFD_c(), VID_InitModeGL(), VID_Start(), and VM_Warning().
sys_debugsleep
cvar_t sys_debugsleep = {CF_SHARED, "sys_debugsleep", "0", "write requested and attained sleep times to standard output, to be used with gnuplot"} static
Definition at line 299 of file sys_shared.c.
{CF_SHARED, "sys_debugsleep", "0", "write requested and attained sleep times to standard output, to be used with gnuplot"};
Referenced by Sys_Init_Commands(), and Sys_Sleep().
sys_libdir
cvar_t sys_libdir = {CF_READONLY | CF_SHARED, "sys_libdir", "", "Default engine library directory"}
Definition at line 296 of file sys_shared.c.
{CF_READONLY | CF_SHARED, "sys_libdir", "", "Default engine library directory"};
Referenced by Sys_Init_Commands().
sys_stdout
cvar_t sys_stdout = {CF_SHARED, "sys_stdout", "1", "0: nothing is written to stdout (-nostdout cmdline option sets this), 1: normal messages are written to stdout, 2: normal messages are written to stderr (-stderr cmdline option sets this)"} static
Definition at line 309 of file sys_shared.c.
{CF_SHARED, "sys_stdout", "1", "0: nothing is written to stdout (-nostdout cmdline option sets this), 1: normal messages are written to stdout, 2: normal messages are written to stderr (-stderr cmdline option sets this)"};
Referenced by main(), Sys_Init_Commands(), and Sys_UpdateOutFD_c().
sys_stdout_blocks
cvar_t sys_stdout_blocks = {CF_SHARED, "sys_stdout_blocks", "0", "1: writes to stdout and stderr streams will block (causing a stutter or complete halt) if the buffer is full, ensuring no messages are lost at a price"} static
Definition at line 311 of file sys_shared.c.
{CF_SHARED, "sys_stdout_blocks", "0", "1: writes to stdout and stderr streams will block (causing a stutter or complete halt) if the buffer is full, ensuring no messages are lost at a price"};
Referenced by Sys_Init_Commands(), and Sys_Print().
sys_timestring
char sys_timestring[128] static
Definition at line 44 of file sys_shared.c.
Referenced by Sys_TimeString().
sys_usenoclockbutbenchmark
cvar_t sys_usenoclockbutbenchmark = {CF_SHARED, "sys_usenoclockbutbenchmark", "0", "don't use ANY real timing, and simulate a clock (for benchmarking); the game then runs as fast as possible. Run a QC mod with bots that does some stuff, then does a quit at the end, to benchmark a server. NEVER do this on a public server."}
Definition at line 295 of file sys_shared.c.
{CF_SHARED, "sys_usenoclockbutbenchmark", "0", "don't use ANY real timing, and simulate a clock (for benchmarking); the game then runs as fast as possible. Run a QC mod with bots that does some stuff, then does a quit at the end, to benchmark a server. NEVER do this on a public server."};
Referenced by Sys_DirtyTime(), Sys_Init_Commands(), and Sys_Sleep().
sys_usesdldelay
cvar_t sys_usesdldelay = {CF_SHARED, "sys_usesdldelay", "0", "use SDL_Delay() (less accurate, for debugging)"} static
Definition at line 301 of file sys_shared.c.
{CF_SHARED, "sys_usesdldelay", "0", "use SDL_Delay() (less accurate, for debugging)"};
Referenced by Sys_Init_Commands(), and Sys_Sleep().
sys_usesdlgetticks
cvar_t sys_usesdlgetticks = {CF_SHARED, "sys_usesdlgetticks", "0", "use SDL_GetTicks() timer (less accurate, for debugging)"} static
Definition at line 300 of file sys_shared.c.
{CF_SHARED, "sys_usesdlgetticks", "0", "use SDL_GetTicks() timer (less accurate, for debugging)"};
Referenced by Sys_DirtyTime(), and Sys_Init_Commands().