DarkPlaces: sys.h File Reference
sys.h File Reference
#include "qtypes.h"
#include "qdefs.h"
Data Structures
struct sys_t
struct dllfunction_t
struct sys_cleantime_t
Macros
#define DP_OS_NAME "Unknown"
#define DP_OS_STR "unknown"
#define Sys_HaveSSE() false
#define Sys_HaveSSE2() false
Typedefs
typedef void * dllhandle_t
Functions
qbool Sys_LoadSelf (dllhandle_t *handle)
qbool Sys_LoadDependency (const char **dllnames, dllhandle_t *handle, const dllfunction_t *fcts)
qbool Sys_LoadLibrary (const char *name, dllhandle_t *handle)
void Sys_FreeLibrary (dllhandle_t *handle)
void * Sys_GetProcAddress (dllhandle_t handle, const char *name)
int Sys_CheckParm (const char *parm)
void Sys_Init_Commands (void)
called after command system is initialized but before first Con_Print
char * Sys_TimeString (const char *timeformat)
void Sys_Error (const char *error,...) DP_FUNC_PRINTF(1) DP_FUNC_NORETURN
Causes the entire program to exit ASAP.
void Sys_Print (const char *text, size_t textlen)
(may) output text to terminal which launched program is POSIX async-signal-safe textlen excludes any (optional) \0 terminator
void Sys_Printf (const char *fmt,...)
used to report failures inside Con_Printf()
void Sys_SDL_Shutdown (void)
INFO: This is only called by Host_Shutdown so we dont need testing for recursion.
void Sys_AllowProfiling (qbool enable)
double Sys_DirtyTime (void)
void Sys_ProvideSelfFD (void)
char * Sys_ConsoleInput (void)
Reads a line from POSIX stdin or the Windows console.
double Sys_Sleep (double time)
called to yield for a little bit so as not to hog cpu when paused or debugging
void Sys_SDL_Dialog (const char *title, const char *string)
void Sys_SDL_Init (void)
void Sys_SDL_HandleEvents (void)
Perform Key_Event () callbacks until the input que is empty.
char * Sys_SDL_GetClipboardData (void)
unsigned int Sys_SDL_GetTicks (void)
void Sys_SDL_Delay (unsigned int milliseconds)
void Sys_InitProcessNice (void)
called to set process priority for dedicated servers
void Sys_MakeProcessNice (void)
void Sys_MakeProcessMean (void)
Variables
sys_t sys
qbool sys_supportsdlgetticks
Macro Definition Documentation
DP_OS_NAME
#define DP_OS_NAME "Unknown"
Definition at line 91 of file sys.h.
DP_OS_STR
#define DP_OS_STR "unknown"
Definition at line 92 of file sys.h.
Sys_HaveSSE
#define Sys_HaveSSE () false
Definition at line 136 of file sys.h.
Sys_HaveSSE2
#define Sys_HaveSSE2 () false
Definition at line 137 of file sys.h.
Typedef Documentation
dllhandle_t
typedef void* dllhandle_t
Definition at line 165 of file sys.h.
Function Documentation
Sys_AllowProfiling()
void Sys_AllowProfiling (qbool enable)
on some build/platform combinations (such as Linux gcc with the -pg profiling option) this can turn on/off profiling, used primarily to limit profiling to certain areas of the code, such as ingame performance without regard for loading/shutdown performance (-profilegameonly on commandline)
Definition at line 62 of file sys_shared.c.
{
#ifdef __ANDROID__
#ifdef USE_PROFILER
    extern void monstartup(const char *libname);
    extern void moncleanup(void);
    if (enable)
        monstartup("libmain.so");
    else
        moncleanup();
#endif
#elif (defined(__linux__) && (defined(__GLIBC__) || defined(__GNU_LIBRARY__))) || defined(__FreeBSD__)
    extern int moncontrol(int);
    moncontrol(enable);
#endif
}
Referenced by CL_DisconnectEx(), CL_SignonReply(), Host_Init(), Host_Shutdown(), and main().
Sys_CheckParm()
int Sys_CheckParm (const char * parm)
Definition at line 324 of file sys_shared.c.
{
    int i;
    for (i=1 ; i<sys.argc ; i++)
    {
        if (!sys.argv[i])
            continue;               // NEXTSTEP sometimes clears appkit vars.
        if (!strcmp (parm,sys.argv[i]))
            return i;
    }
    return 0;
}
Referenced by CDAudio_Init(), CDAudio_Startup(), CL_DisconnectEx(), CL_EstablishConnection(), CL_FinishTimeDemo(), CL_PlayVideo_f(), CL_Screen_Init(), CL_SignonReply(), CL_Startdemos_f(), CL_StopPlayback(), Cmd_Exec(), COM_InitGameType(), COM_SetGameType(), Con_Init(), Con_ToggleConsole_f(), FS_Init_Dir(), FS_Init_SelfPack(), FS_mkdir(), FS_Rescan(), FS_SysOpenFiledesc(), GL_CheckExtension(), Host_Init(), Host_InitSession(), Host_LockSession(), Host_SaveConfig(), Host_Shutdown(), Key_Event(), LibAV_LoadLibrary(), LibAvW_OpenLibrary(), main(), MR_Init(), NetConn_Init(), OGG_OpenLibrary(), Palette_Load(), PRVM_Init(), S_Init(), S_Startup(), SV_ServerOptions(), Sys_SDL_Init(), VID_InitModeGL(), VID_Start(), XMP_LoadModFile(), and XMP_OpenLibrary().
Sys_ConsoleInput()
char * Sys_ConsoleInput (void)
Reads a line from POSIX stdin or the Windows console.
Definition at line 620 of file sys_shared.c.
{
    static char text[MAX_INPUTLINE];
#ifdef WIN32
    static unsigned int len = 0;
    int c;
    // read a line out
    while (_kbhit ())
    {
        c = _getch ();
        if (c == '\r')
        {
            text[len] = '\0';
            _putch ('\n');
            len = 0;
            return text;
        }
        if (c == '\b')
        {
            if (len)
            {
                _putch (c);
                _putch (' ');
                _putch (c);
                len--;
            }
            continue;
        }
        if (len < sizeof (text) - 1)
        {
            _putch (c);
            text[len] = c;
            len++;
        }
    }
#else
    fd_set fdset;
    struct timeval timeout = { .tv_sec = 0, .tv_usec = 0 };
    FD_ZERO(&fdset);
    FD_SET(fileno(stdin), &fdset);
    if (select(1, &fdset, NULL, NULL, &timeout) != -1 && FD_ISSET(fileno(stdin), &fdset))
        return fgets(text, sizeof(text), stdin);
#endif
    return NULL;
}
Referenced by Cbuf_Frame_Input().
Sys_DirtyTime()
double Sys_DirtyTime (void)
Definition at line 375 of file sys_shared.c.
{
    // first all the OPTIONAL timers
    // benchmark timer (fake clock)
    if(sys_usenoclockbutbenchmark.integer)
    {
        double old_benchmark_time = benchmark_time;
        benchmark_time += 1;
        if(benchmark_time == old_benchmark_time)
            Sys_Error("sys_usenoclockbutbenchmark cannot run any longer, sorry");
        return benchmark_time * 0.000001;
    }
#if HAVE_QUERYPERFORMANCECOUNTER
    if (sys_usequeryperformancecounter.integer)
    {
        // LadyHavoc: note to people modifying this code, DWORD is specifically defined as an unsigned 32bit number, therefore the 65536.0 * 65536.0 is fine.
        // QueryPerformanceCounter
        // platform:
        // Windows 95/98/ME/NT/2000/XP
        // features:
        // very accurate (CPU cycles)
        // known issues:
        // does not necessarily match realtime too well (tends to get faster and faster in win98)
        // wraps around occasionally on some platforms (depends on CPU speed and probably other unknown factors)
        double timescale;
        LARGE_INTEGER PerformanceFreq;
        LARGE_INTEGER PerformanceCount;
        if (QueryPerformanceFrequency (&PerformanceFreq))
        {
            QueryPerformanceCounter (&PerformanceCount);
            timescale = 1.0 / ((double) PerformanceFreq.LowPart + (double) PerformanceFreq.HighPart * 65536.0 * 65536.0);
            return ((double) PerformanceCount.LowPart + (double) PerformanceCount.HighPart * 65536.0 * 65536.0) * timescale;
        }
        else
        {
            Con_Printf("No hardware timer available\n");
            // fall back to other clock sources
            Cvar_SetValueQuick(&sys_usequeryperformancecounter, false);
        }
    }
#endif
#if HAVE_CLOCKGETTIME
    if (sys_useclockgettime.integer)
    {
        struct timespec ts;
#  ifdef CLOCK_MONOTONIC
        // linux
        clock_gettime(CLOCK_MONOTONIC, &ts);
#  else
        // sunos
        clock_gettime(CLOCK_HIGHRES, &ts);
#  endif
        return (double) ts.tv_sec + ts.tv_nsec / 1000000000.0;
    }
#endif
    // now all the FALLBACK timers
    if(sys_supportsdlgetticks && sys_usesdlgetticks.integer)
        return (double) Sys_SDL_GetTicks() / 1000.0;
#if HAVE_GETTIMEOFDAY
    {
        struct timeval tp;
        gettimeofday(&tp, NULL);
        return (double) tp.tv_sec + tp.tv_usec / 1000000.0;
    }
#elif HAVE_TIMEGETTIME
    {
        static int firsttimegettime = true;
        // timeGetTime
        // platform:
        // Windows 95/98/ME/NT/2000/XP
        // features:
        // reasonable accuracy (millisecond)
        // issues:
        // wraps around every 47 days or so (but this is non-fatal to us, odd times are rejected, only causes a one frame stutter)
        // make sure the timer is high precision, otherwise different versions of windows have varying accuracy
        if (firsttimegettime)
        {
            timeBeginPeriod(1);
            firsttimegettime = false;
        }
        return (double) timeGetTime() / 1000.0;
    }
#else
    // fallback for using the SDL timer if no other timer is available
    // this calls Sys_Error() if not linking against SDL
    return (double) Sys_SDL_GetTicks() / 1000.0;
#endif
}
Referenced by CL_Frame(), CL_KeepaliveMessage(), CL_TimeRefresh_f(), CL_UpdateScreen(), CLVM_ExecuteProgram(), Crypto_ServerParsePacket(), Host_Main(), PRVM_CallProfile(), PRVM_Prog_Load(), R_TimeReport(), R_TimeReport_BeginFrame(), R_TimeReport_EndFrame(), SV_Frame(), SV_ThreadFunc(), SVVM_ExecuteProgram(), Sys_Sleep(), VM_CL_R_AddDynamicLight(), VM_CL_R_AddEntities(), VM_CL_R_AddEntity(), VM_CL_R_RenderScene(), VM_gettime(), and while().
Sys_Error()
void Sys_Error (const char * error, ...)
Causes the entire program to exit ASAP.
Trailing
should be omitted.
Definition at line 677 of file sys_shared.c.
{
    va_list argptr;
    char string[MAX_INPUTLINE];
    int i;
    // Disable Sys_HandleSignal() but not Sys_HandleCrash()
    host.state = host_shutdown;
    // set output to blocking stderr
    sys.outfd = fileno(stderr);
#ifndef WIN32
    fcntl(sys.outfd, F_SETFL, fcntl(sys.outfd, F_GETFL, 0) & ~O_NONBLOCK);
#endif
    va_start (argptr,error);
    dpvsnprintf (string, sizeof (string), error, argptr);
    va_end (argptr);
    Con_Printf(CON_ERROR "Engine Aborted: %s\n^9%s\n", string, engineversion);
    dp_strlcat(string, "\n\n", sizeof(string));
    dp_strlcat(string, engineversion, sizeof(string));
    // Most shutdown funcs can't be called here as they could error while we error.
    // DP8 TODO: send a disconnect message indicating we aborted, see Host_Error() and Sys_HandleCrash()
    if (cls.demorecording)
        CL_Stop_f(cmd_local);
    if (sv.active)
    {
        sv.active = false; // make SV_DropClient() skip the QC stuff to avoid recursive errors
        for (i = 0, host_client = svs.clients;i < svs.maxclients;i++, host_client++)
            if (host_client->active)
                SV_DropClient(false, "Server aborted!"); // closes demo file
    }
    // don't want a dead window left blocking the OS UI or the abort dialog
    VID_Shutdown();
    S_StopAllSounds();
    host.state = host_failed; // make Sys_HandleSignal() call _Exit()
    Sys_SDL_Dialog("Engine Aborted", string);
    fflush(stderr);
    exit (1);
}
Referenced by _Mem_Alloc(), _Mem_AllocPool(), _Mem_CheckSentinels(), _Mem_CheckSentinelsGlobal(), _Mem_EmptyPool(), _Mem_Free(), _Mem_FreeBlock(), _Mem_FreePool(), Buffer_Callback(), CL_CutDemo(), CL_ExpandEntities(), Clump_AllocBlock(), Clump_FreeBlock(), GL_InitFunctions(), GL_Setup(), Host_Error(), Host_Init(), Host_LockSession(), M_Menu_Keys_f(), Mem_ExpandableArray_FreeRecord(), MVM_error_cmd(), PHYS_NudgeOutOfSolid(), R_BufferData_Store(), R_Mesh_TexBind(), R_Mesh_TexBound(), R_Mesh_TexCoordPointer(), R_RegisterModule(), R_SetupTexture(), R_UploadFullTexture(), R_UploadPartialTexture(), RSurf_DrawBatch(), SCR_CaptureVideo_Avi_BeginVideo(), SCR_CaptureVideo_Ogg_Interleave(), SCR_CaptureVideo_RIFF_IndexEntry(), SCR_CaptureVideo_RIFF_MakeIxChunk(), SCR_CaptureVideo_RIFF_OverflowCheck(), setuptex(), SndSys_Write(), SV_SendClientMessages(), Sys_DirtyTime(), Sys_SDL_Delay(), Sys_SDL_GetTicks(), Sys_SDL_Init(), Sys_Sleep(), VID_Init(), VID_InitMode(), VID_InitModeGL(), VID_Restart_f(), VID_Start(), and VM_nudgeoutofsolid().
Sys_FreeLibrary()
void Sys_FreeLibrary (dllhandle_t * handle)
Definition at line 242 of file sys_shared.c.
{
#ifdef SUPPORTDLL
    if (handle == NULL || *handle == NULL)
        return;
#ifdef WIN32
    FreeLibrary (*handle);
#else
    dlclose (*handle);
#endif
    *handle = NULL;
#endif
}
Referenced by Crypto_CloseLibrary(), Crypto_Rijndael_CloseLibrary(), CURL_CloseLibrary(), Font_CloseLibrary(), FS_Shutdown(), JPEG_CloseLibrary(), LibAV_LoadLibrary(), LibAvW_CloseLibrary(), LibAvW_OpenLibrary(), OGG_CloseLibrary(), PK3_CloseLibrary(), PNG_CloseLibrary(), PNG_OpenLibrary(), SCR_CaptureVideo_Ogg_CloseDLL(), Sys_LoadDependency(), XMP_CloseLibrary(), and XMP_OpenLibrary().
Sys_GetProcAddress()
void * Sys_GetProcAddress (dllhandle_t handle, const char * name)
Definition at line 258 of file sys_shared.c.
{
#ifdef SUPPORTDLL
#ifdef WIN32
    return (void *)GetProcAddress (handle, name);
#else
    return (void *)dlsym (handle, name);
#endif
#else
    return NULL;
#endif
}
Referenced by Sys_LoadDependencyFunctions().
Sys_Init_Commands()
void Sys_Init_Commands (void)
called after command system is initialized but before first Con_Print
Definition at line 350 of file sys_shared.c.
{
    Cvar_RegisterVariable(&sys_debugsleep);
    Cvar_RegisterVariable(&sys_usenoclockbutbenchmark);
    Cvar_RegisterVariable(&sys_libdir);
#if HAVE_TIMEGETTIME || HAVE_QUERYPERFORMANCECOUNTER || HAVE_CLOCKGETTIME || HAVE_GETTIMEOFDAY
    if(sys_supportsdlgetticks)
    {
        Cvar_RegisterVariable(&sys_usesdlgetticks);
        Cvar_RegisterVariable(&sys_usesdldelay);
    }
#endif
#if HAVE_QUERYPERFORMANCECOUNTER
    Cvar_RegisterVariable(&sys_usequeryperformancecounter);
#endif
#if HAVE_CLOCKGETTIME
    Cvar_RegisterVariable(&sys_useclockgettime);
#endif
    Cvar_RegisterVariable(&sys_stdout);
    Cvar_RegisterCallback(&sys_stdout, Sys_UpdateOutFD_c);
#ifndef WIN32
    Cvar_RegisterVariable(&sys_stdout_blocks);
#endif
}
Referenced by Host_Init().
Sys_InitProcessNice()
void Sys_InitProcessNice (void)
called to set process priority for dedicated servers
Definition at line 908 of file sys_shared.c.
{
}
Referenced by Host_Init().
Sys_LoadDependency()
qbool Sys_LoadDependency (const char ** dllnames, dllhandle_t * handle, const dllfunction_t * fcts)
Loads a dependency library.
Parameters
dllnames a NULL terminated array of possible names for the DLL you want to load.
handle
fcts
Definition at line 128 of file sys_shared.c.
{
#ifdef SUPPORTDLL
    const dllfunction_t *func;
    dllhandle_t dllhandle = 0;
    unsigned int i;
    if (handle == NULL)
        return false;
#ifndef WIN32
#ifdef PREFER_PRELOAD
    dllhandle = dlopen(NULL, RTLD_LAZY | RTLD_GLOBAL);
    if(Sys_LoadDependencyFunctions(dllhandle, fcts, false, false))
    {
        Con_DPrintf ("All of %s's functions were already linked in! Not loading dynamically...\n", dllnames[0]);
        *handle = dllhandle;
        return true;
    }
    else
        Sys_FreeLibrary(&dllhandle);
notfound:
#endif
#endif
    // Initializations
    for (func = fcts; func && func->name != NULL; func++)
        *func->funcvariable = NULL;
    // Try every possible name
    Con_DPrintf ("Trying to load library...");
    for (i = 0; dllnames[i] != NULL; i++)
    {
        Con_DPrintf (" \"%s\"", dllnames[i]);
#ifdef WIN32
# ifndef DONT_USE_SETDLLDIRECTORY
#  ifdef _WIN64
        SetDllDirectory("bin64");
#  else
        SetDllDirectory("bin32");
#  endif
# endif
#endif
        if(Sys_LoadLibrary(dllnames[i], &dllhandle))
        {
            if (Sys_LoadDependencyFunctions(dllhandle, fcts, true, (dllnames[i+1] != NULL) || (strrchr(sys.argv[0], '/'))))
                break;
            else
                Sys_FreeLibrary (&dllhandle);
        }
    }
    // see if the names can be loaded relative to the executable path
    // (this is for Mac OSX which does not check next to the executable)
    if (!dllhandle && strrchr(sys.argv[0], '/'))
    {
        char path[MAX_OSPATH];
        dp_strlcpy(path, sys.argv[0], sizeof(path));
        strrchr(path, '/')[1] = 0;
        for (i = 0; dllnames[i] != NULL; i++)
        {
            char temp[MAX_OSPATH];
            dp_strlcpy(temp, path, sizeof(temp));
            dp_strlcat(temp, dllnames[i], sizeof(temp));
            Con_DPrintf (" \"%s\"", temp);
            if(Sys_LoadLibrary(temp, &dllhandle))
            {
                if (Sys_LoadDependencyFunctions(dllhandle, fcts, true, (dllnames[i+1] != NULL) || (strrchr(sys.argv[0], '/'))))
                    break;
                else
                    Sys_FreeLibrary (&dllhandle);
            }
        }
    }
    // No DLL found
    if (! dllhandle)
    {
        Con_DPrintf(" - failed.\n");
        return false;
    }
    Con_DPrintf(" - loaded.\n");
    Con_Printf("Loaded library \"%s\"\n", dllnames[i]);
    *handle = dllhandle;
    return true;
#else
    return false;
#endif
}
Referenced by Crypto_OpenLibrary(), Crypto_Rijndael_OpenLibrary(), CURL_OpenLibrary(), Font_OpenLibrary(), FS_ChooseUserDir(), JPEG_OpenLibrary(), LibAV_LoadLibrary(), LibAvW_OpenLibrary(), OGG_OpenLibrary(), PK3_OpenLibrary(), PNG_OpenLibrary(), SCR_CaptureVideo_Ogg_OpenLibrary(), VID_Shared_Init(), and XMP_OpenLibrary().
Sys_LoadLibrary()
qbool Sys_LoadLibrary (const char * name, dllhandle_t * handle)
Loads a library.
Parameters
name a string of the library filename
handle
Returns
true if library was loaded successfully
Definition at line 221 of file sys_shared.c.
{
    dllhandle_t dllhandle = 0;
    if(handle == NULL)
        return false;
#ifdef SUPPORTDLL
# ifdef WIN32
    dllhandle = LoadLibrary (name);
# else
    dllhandle = dlopen (name, RTLD_LAZY | RTLD_GLOBAL);
# endif
#endif
    if(!dllhandle)
        return false;
    *handle = dllhandle;
    return true;
}
Referenced by Sys_LoadDependency().
Sys_LoadSelf()
qbool Sys_LoadSelf (dllhandle_t * handle)
Definition at line 113 of file sys_shared.c.
{
    dllhandle_t dllhandle = 0;
    if (handle == NULL)
        return false;
#ifdef WIN32
    dllhandle = LoadLibrary (NULL);
#else
    dllhandle = dlopen (NULL, RTLD_NOW | RTLD_GLOBAL);
#endif
    *handle = dllhandle;
    return true;
}
Sys_MakeProcessMean()
void Sys_MakeProcessMean (void)
Definition at line 914 of file sys_shared.c.
{
}
Referenced by Host_AbortCurrentFrame(), and SV_SpawnServer().
Sys_MakeProcessNice()
void Sys_MakeProcessNice (void)
Definition at line 911 of file sys_shared.c.
{
}
Referenced by SV_SpawnServer().
Sys_Print()
void Sys_Print (const char * text, size_t textlen)
(may) output text to terminal which launched program is POSIX async-signal-safe textlen excludes any (optional) \0 terminator
Definition at line 569 of file sys_shared.c.
{
#ifdef __ANDROID__
    if (developer.integer > 0)
    {
        __android_log_write(ANDROID_LOG_DEBUG, sys.argv[0], text);
    }
#else
    if(sys.outfd < 0)
        return;
  #ifndef WIN32
    // BUG: for some reason, NDELAY also affects stdout (1) when used on stdin (0).
    // this is because both go to /dev/tty by default!
    {
        int origflags = fcntl(sys.outfd, F_GETFL, 0);
        if (sys_stdout_blocks.integer)
            fcntl(sys.outfd, F_SETFL, origflags & ~O_NONBLOCK);
  #else
    #define write _write
  #endif
        while(*text)
        {
            fs_offset_t written = (fs_offset_t)write(sys.outfd, text, textlen);
            if(written <= 0)
                break; // sorry, I cannot do anything about this error - without an output
            text += written;
        }
  #ifndef WIN32
        if (sys_stdout_blocks.integer)
            fcntl(sys.outfd, F_SETFL, origflags);
    }
  #endif
    //fprintf(stdout, "%s", text);
#endif
}
Referenced by Con_MaskPrint(), Sys_HandleCrash(), Sys_HandleSignal(), and Sys_Printf().
Sys_Printf()
void Sys_Printf (const char * fmt, ...)
used to report failures inside Con_Printf()
Definition at line 605 of file sys_shared.c.
{
    va_list argptr;
    char msg[MAX_INPUTLINE];
    int msglen;
    va_start(argptr,fmt);
    msglen = dpvsnprintf(msg, sizeof(msg), fmt, argptr);
    va_end(argptr);
    if (msglen >= 0)
        Sys_Print(msg, msglen);
}
Referenced by _Thread_AtomicAdd(), _Thread_AtomicDecRef(), _Thread_AtomicGet(), _Thread_AtomicIncRef(), _Thread_AtomicLock(), _Thread_AtomicSet(), _Thread_AtomicTryLock(), _Thread_AtomicUnlock(), _Thread_CondBroadcast(), _Thread_CondSignal(), _Thread_CondWait(), _Thread_CreateBarrier(), _Thread_CreateCond(), _Thread_CreateMutex(), _Thread_CreateThread(), _Thread_DestroyBarrier(), _Thread_DestroyCond(), _Thread_DestroyMutex(), _Thread_LockMutex(), _Thread_UnlockMutex(), _Thread_WaitBarrier(), _Thread_WaitThread(), _Thread_WaitThread(), Con_WordWidthFunc(), and dpvsnprintf().
Sys_ProvideSelfFD()
void Sys_ProvideSelfFD (void)
Definition at line 779 of file sys_shared.c.
{
    if(sys.selffd != -1)
        return;
    sys.selffd = FS_SysOpenFD(Sys_FindExecutableName(), "rb", false);
}
Referenced by main().
Sys_SDL_Delay()
void Sys_SDL_Delay (unsigned int milliseconds)
Definition at line 32 of file sys_null.c.
{
    Sys_Error("Called Sys_SDL_Delay on non-SDL target");
}
Referenced by Sys_Sleep().
Sys_SDL_Dialog()
void Sys_SDL_Dialog (const char * title, const char * string)
Definition at line 13 of file sys_null.c.
{
}
Referenced by Sys_Error(), and Sys_HandleCrash().
Sys_SDL_GetClipboardData()
char * Sys_SDL_GetClipboardData (void)
Definition at line 17 of file sys_null.c.
{
    return NULL;
}
Referenced by Key_Parse_CommonKeys().
Sys_SDL_GetTicks()
unsigned int Sys_SDL_GetTicks (void)
Definition at line 27 of file sys_null.c.
{
    Sys_Error("Called Sys_SDL_GetTicks on non-SDL target");
    return 0;
}
Referenced by Sys_DirtyTime().
Sys_SDL_HandleEvents()
void Sys_SDL_HandleEvents (void)
Perform Key_Event () callbacks until the input que is empty.
Definition at line 50 of file vid_null.c.
{
}
Referenced by Host_Frame().
Sys_SDL_Init()
void Sys_SDL_Init (void)
Definition at line 22 of file sys_null.c.
{
}
Referenced by Host_Init().
Sys_SDL_Shutdown()
void Sys_SDL_Shutdown (void)
INFO: This is only called by Host_Shutdown so we dont need testing for recursion.
Definition at line 9 of file sys_null.c.
{
}
Referenced by Host_Shutdown().
Sys_Sleep()
double Sys_Sleep (double time)
called to yield for a little bit so as not to hog cpu when paused or debugging
Definition at line 472 of file sys_shared.c.
{
    double dt;
    uint32_t microseconds;
    // convert to microseconds
    time *= 1000000.0;
    if(host_maxwait.value <= 0)
        time = min(time, 1000000.0);
    else
        time = min(time, host_maxwait.value * 1000.0);
    if (time < 1 || host.restless)
        return 0; // not sleeping this frame
    microseconds = time; // post-validation to prevent overflow
    if(sys_usenoclockbutbenchmark.integer)
    {
        double old_benchmark_time = benchmark_time;
        benchmark_time += microseconds;
        if(benchmark_time == old_benchmark_time)
            Sys_Error("sys_usenoclockbutbenchmark cannot run any longer, sorry");
        return 0;
    }
    if(sys_debugsleep.integer)
        Con_Printf("sys_debugsleep: requesting %u ", microseconds);
    dt = Sys_DirtyTime();
    // less important on newer libcurl so no need to disturb dedicated servers
    if (cls.state != ca_dedicated && Curl_Select(microseconds))
    {
        // a transfer is ready or we finished sleeping
    }
    else if(sys_supportsdlgetticks && sys_usesdldelay.integer)
        Sys_SDL_Delay(microseconds / 1000);
#if HAVE_SELECT
    else
    {
        struct timeval tv;
        lhnetsocket_t *s;
        fd_set fdreadset;
        int lastfd = -1;
        FD_ZERO(&fdreadset);
        if (cls.state == ca_dedicated && sv_checkforpacketsduringsleep.integer)
        {
            List_For_Each_Entry(s, &lhnet_socketlist.list, lhnetsocket_t, list)
            {
                if (s->address.addresstype == LHNETADDRESSTYPE_INET4 || s->address.addresstype == LHNETADDRESSTYPE_INET6)
                {
                    if (lastfd < s->inetsocket)
                        lastfd = s->inetsocket;
    #if defined(WIN32) && !defined(_MSC_VER)
                    FD_SET((int)s->inetsocket, &fdreadset);
    #else
                    FD_SET((unsigned int)s->inetsocket, &fdreadset);
    #endif
                }
            }
        }
        tv.tv_sec = microseconds / 1000000;
        tv.tv_usec = microseconds % 1000000;
        // on Win32, select() cannot be used with all three FD list args being NULL according to MSDN
        // (so much for POSIX...)
        // bones_was_here: but a zeroed fd_set seems to be tolerated (tested on Win 7)
        select(lastfd + 1, &fdreadset, NULL, NULL, &tv);
    }
#elif HAVE_USLEEP
    else
        usleep(microseconds);
#elif HAVE_Sleep
    else
        Sleep(microseconds / 1000);
#else
    else
        Sys_SDL_Delay(microseconds / 1000);
#endif
    dt = Sys_DirtyTime() - dt;
    if(sys_debugsleep.integer)
        Con_Printf(" got %u oversleep %d\n", (unsigned int)(dt * 1000000), (unsigned int)(dt * 1000000) - microseconds);
    return (dt < 0 || dt >= 1800) ? 0 : dt;
}
Referenced by attempt_malloc(), CL_Frame(), Host_Main(), SV_ThreadFunc(), and TaskQueue_ThreadFunc().
Sys_TimeString()
char * Sys_TimeString (const char * timeformat)
Returns
current timestamp
Definition at line 45 of file sys_shared.c.
{
    time_t mytime = time(NULL);
#if _MSC_VER >= 1400
    struct tm mytm;
    localtime_s(&mytm, &mytime);
    strftime(sys_timestring, sizeof(sys_timestring), timeformat, &mytm);
#else
    strftime(sys_timestring, sizeof(sys_timestring), timeformat, localtime(&mytime));
#endif
    return sys_timestring;
}
Referenced by CL_FinishTimeDemo(), CL_Locs_Save_f(), CL_ParseServerInfo(), Con_MaskPrint(), Sbar_ShowFPS(), SCR_ScreenShot_f(), and SV_SendServerinfo().
Variable Documentation
sys
sys_t sys extern
Definition at line 42 of file sys_shared.c.
Referenced by CL_FinishTimeDemo(), Cmd_StuffCmds_f(), COM_Init_Commands(), COM_InitGameType(), COM_InsertFlags(), COM_SetGameType(), Con_MaskPrint(), FS_Init_Dir(), FS_Init_SelfPack(), FS_Rescan(), Host_Error(), Host_Init(), Host_InitSession(), main(), MVM_error_cmd(), NetConn_Init(), Palette_Load(), S_Startup(), SV_ServerOptions(), Sys_CheckParm(), Sys_Error(), Sys_FindExecutableName(), Sys_HandleCrash(), Sys_LoadDependency(), Sys_Print(), Sys_ProvideSelfFD(), Sys_UpdateOutFD_c(), VID_InitModeGL(), VID_Start(), and VM_Warning().
sys_supportsdlgetticks
qbool sys_supportsdlgetticks extern
Definition at line 26 of file sys_null.c.
Referenced by Sys_DirtyTime(), Sys_Init_Commands(), and Sys_Sleep().