DarkPlaces: sys_sdl.c File Reference
sys_sdl.c File Reference
#include <SDL.h>
#include "darkplaces.h"
Functions
void Sys_SDL_Shutdown (void)
INFO: This is only called by Host_Shutdown so we dont need testing for recursion.
void Sys_SDL_Dialog (const char *title, const char *string)
char * Sys_SDL_GetClipboardData (void)
void Sys_SDL_Init (void)
unsigned int Sys_SDL_GetTicks (void)
void Sys_SDL_Delay (unsigned int milliseconds)
Variables
static qbool nocrashdialog = true
qbool sys_supportsdlgetticks = true
Function Documentation
Sys_SDL_Delay()
void Sys_SDL_Delay (unsigned int milliseconds)
Definition at line 68 of file sys_sdl.c.
{
    SDL_Delay(milliseconds);
}
Referenced by Sys_Sleep().
Sys_SDL_Dialog()
void Sys_SDL_Dialog (const char * title, const char * string)
Definition at line 29 of file sys_sdl.c.
{
    if(!nocrashdialog)
        SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, title, string, NULL);
}
Referenced by Sys_Error(), and Sys_HandleCrash().
Sys_SDL_GetClipboardData()
char * Sys_SDL_GetClipboardData (void)
Definition at line 35 of file sys_sdl.c.
{
    char *data = NULL;
    char *cliptext;
    cliptext = SDL_GetClipboardText();
    if (cliptext != NULL) {
        size_t allocsize;
        allocsize = min(MAX_INPUTLINE, strlen(cliptext) + 1);
        data = (char *)Z_Malloc (allocsize);
        dp_strlcpy (data, cliptext, allocsize);
        SDL_free(cliptext);
    }
    return data;
}
Referenced by Key_Parse_CommonKeys().
Sys_SDL_GetTicks()
unsigned int Sys_SDL_GetTicks (void)
Definition at line 64 of file sys_sdl.c.
{
    return SDL_GetTicks();
}
Referenced by Sys_DirtyTime().
Sys_SDL_Init()
void Sys_SDL_Init (void)
Definition at line 52 of file sys_sdl.c.
{
    // we don't know which systems we'll want to init, yet...
    if (SDL_Init(0) < 0)
        Sys_Error("SDL_Init failed: %s\n", SDL_GetError());
    // COMMANDLINEOPTION: sdl: -nocrashdialog disables "Engine Error" crash dialog boxes
    if(!Sys_CheckParm("-nocrashdialog"))
        nocrashdialog = false;
}
Referenced by Host_Init().
Sys_SDL_Shutdown()
void Sys_SDL_Shutdown (void)
INFO: This is only called by Host_Shutdown so we dont need testing for recursion.
Definition at line 21 of file sys_sdl.c.
{
    SDL_Quit();
}
Referenced by Host_Shutdown().
Variable Documentation
nocrashdialog
qbool nocrashdialog = true static
Definition at line 28 of file sys_sdl.c.
Referenced by Sys_SDL_Dialog(), and Sys_SDL_Init().
sys_supportsdlgetticks
qbool sys_supportsdlgetticks = true
Definition at line 63 of file sys_sdl.c.
Referenced by Sys_DirtyTime(), Sys_Init_Commands(), and Sys_Sleep().