DarkPlaces: thread.h File Reference
thread.h File Reference
#include "qtypes.h"
Data Structures
struct Thread_Atomic
Macros
#define THREADRECURSIVE
#define Thread_CreateMutex() (_Thread_CreateMutex(__FILE__, __LINE__))
#define Thread_DestroyMutex(m) (_Thread_DestroyMutex(m, __FILE__, __LINE__))
#define Thread_LockMutex(m) (_Thread_LockMutex(m, __FILE__, __LINE__))
#define Thread_UnlockMutex(m) (_Thread_UnlockMutex(m, __FILE__, __LINE__))
#define Thread_CreateCond() (_Thread_CreateCond(__FILE__, __LINE__))
#define Thread_DestroyCond(cond) (_Thread_DestroyCond(cond, __FILE__, __LINE__))
#define Thread_CondSignal(cond) (_Thread_CondSignal(cond, __FILE__, __LINE__))
#define Thread_CondBroadcast(cond) (_Thread_CondBroadcast(cond, __FILE__, __LINE__))
#define Thread_CondWait(cond, mutex) (_Thread_CondWait(cond, mutex, __FILE__, __LINE__))
#define Thread_CreateThread(fn, data) (_Thread_CreateThread(fn, data, __FILE__, __LINE__))
#define Thread_WaitThread(thread, retval) (_Thread_WaitThread(thread, retval, __FILE__, __LINE__))
#define Thread_CreateBarrier(count) (_Thread_CreateBarrier(count, __FILE__, __LINE__))
#define Thread_DestroyBarrier(barrier) (_Thread_DestroyBarrier(barrier, __FILE__, __LINE__))
#define Thread_WaitBarrier(barrier) (_Thread_WaitBarrier(barrier, __FILE__, __LINE__))
#define Thread_AtomicGet(a) (_Thread_AtomicGet(a, __FILE__, __LINE__))
#define Thread_AtomicSet(a, v) (_Thread_AtomicSet(a, v, __FILE__, __LINE__))
#define Thread_AtomicAdd(a, v) (_Thread_AtomicAdd(a, v, __FILE__, __LINE__))
#define Thread_AtomicIncRef(a) (_Thread_AtomicIncRef(a, __FILE__, __LINE__))
#define Thread_AtomicDecRef(a) (_Thread_AtomicDecRef(a, __FILE__, __LINE__))
#define Thread_AtomicTryLock(lock) (_Thread_AtomicTryLock(lock, __FILE__, __LINE__))
#define Thread_AtomicLock(lock) (_Thread_AtomicLock(lock, __FILE__, __LINE__))
#define Thread_AtomicUnlock(lock) (_Thread_AtomicUnlock(lock, __FILE__, __LINE__))
Typedefs
typedef int Thread_SpinLock
Functions
int Thread_Init (void)
void Thread_Shutdown (void)
qbool Thread_HasThreads (void)
void * _Thread_CreateMutex (const char *filename, int fileline)
void _Thread_DestroyMutex (void *mutex, const char *filename, int fileline)
int _Thread_LockMutex (void *mutex, const char *filename, int fileline)
int _Thread_UnlockMutex (void *mutex, const char *filename, int fileline)
void * _Thread_CreateCond (const char *filename, int fileline)
void _Thread_DestroyCond (void *cond, const char *filename, int fileline)
int _Thread_CondSignal (void *cond, const char *filename, int fileline)
int _Thread_CondBroadcast (void *cond, const char *filename, int fileline)
int _Thread_CondWait (void *cond, void *mutex, const char *filename, int fileline)
void * _Thread_CreateThread (int(*fn)(void *), void *data, const char *filename, int fileline)
int _Thread_WaitThread (void *thread, int retval, const char *filename, int fileline)
void * _Thread_CreateBarrier (unsigned int count, const char *filename, int fileline)
void _Thread_DestroyBarrier (void *barrier, const char *filename, int fileline)
void _Thread_WaitBarrier (void *barrier, const char *filename, int fileline)
int _Thread_AtomicGet (Thread_Atomic *ref, const char *filename, int fileline)
int _Thread_AtomicSet (Thread_Atomic *ref, int v, const char *filename, int fileline)
int _Thread_AtomicAdd (Thread_Atomic *ref, int v, const char *filename, int fileline)
void _Thread_AtomicIncRef (Thread_Atomic *ref, const char *filename, int fileline)
qbool _Thread_AtomicDecRef (Thread_Atomic *ref, const char *filename, int fileline)
qbool _Thread_AtomicTryLock (Thread_SpinLock *lock, const char *filename, int fileline)
void _Thread_AtomicLock (Thread_SpinLock *lock, const char *filename, int fileline)
void _Thread_AtomicUnlock (Thread_SpinLock *lock, const char *filename, int fileline)
Macro Definition Documentation
Thread_AtomicAdd
#define Thread_AtomicAdd (a, v) (_Thread_AtomicAdd(a, v, __FILE__, __LINE__))
Definition at line 31 of file thread.h.
Thread_AtomicDecRef
#define Thread_AtomicDecRef (a) (_Thread_AtomicDecRef(a, __FILE__, __LINE__))
Definition at line 33 of file thread.h.
Thread_AtomicGet
#define Thread_AtomicGet (a) (_Thread_AtomicGet(a, __FILE__, __LINE__))
Definition at line 29 of file thread.h.
Thread_AtomicIncRef
#define Thread_AtomicIncRef (a) (_Thread_AtomicIncRef(a, __FILE__, __LINE__))
Definition at line 32 of file thread.h.
Thread_AtomicLock
#define Thread_AtomicLock (lock) (_Thread_AtomicLock(lock, __FILE__, __LINE__))
Definition at line 35 of file thread.h.
Thread_AtomicSet
#define Thread_AtomicSet (a, v) (_Thread_AtomicSet(a, v, __FILE__, __LINE__))
Definition at line 30 of file thread.h.
Thread_AtomicTryLock
#define Thread_AtomicTryLock (lock) (_Thread_AtomicTryLock(lock, __FILE__, __LINE__))
Definition at line 34 of file thread.h.
Thread_AtomicUnlock
#define Thread_AtomicUnlock (lock) (_Thread_AtomicUnlock(lock, __FILE__, __LINE__))
Definition at line 36 of file thread.h.
Thread_CondBroadcast
#define Thread_CondBroadcast (cond) (_Thread_CondBroadcast(cond, __FILE__, __LINE__))
Definition at line 22 of file thread.h.
Thread_CondSignal
#define Thread_CondSignal (cond) (_Thread_CondSignal(cond, __FILE__, __LINE__))
Definition at line 21 of file thread.h.
Thread_CondWait
#define Thread_CondWait (cond, mutex) (_Thread_CondWait(cond, mutex, __FILE__, __LINE__))
Definition at line 23 of file thread.h.
Thread_CreateBarrier
#define Thread_CreateBarrier (count) (_Thread_CreateBarrier(count, __FILE__, __LINE__))
Definition at line 26 of file thread.h.
Thread_CreateCond
#define Thread_CreateCond () (_Thread_CreateCond(__FILE__, __LINE__))
Definition at line 19 of file thread.h.
Thread_CreateMutex
#define Thread_CreateMutex () (_Thread_CreateMutex(__FILE__, __LINE__))
Definition at line 15 of file thread.h.
Thread_CreateThread
#define Thread_CreateThread (fn, data) (_Thread_CreateThread(fn, data, __FILE__, __LINE__))
Definition at line 24 of file thread.h.
Thread_DestroyBarrier
#define Thread_DestroyBarrier (barrier) (_Thread_DestroyBarrier(barrier, __FILE__, __LINE__))
Definition at line 27 of file thread.h.
Thread_DestroyCond
#define Thread_DestroyCond (cond) (_Thread_DestroyCond(cond, __FILE__, __LINE__))
Definition at line 20 of file thread.h.
Thread_DestroyMutex
#define Thread_DestroyMutex (m) (_Thread_DestroyMutex(m, __FILE__, __LINE__))
Definition at line 16 of file thread.h.
Thread_LockMutex
#define Thread_LockMutex (m) (_Thread_LockMutex(m, __FILE__, __LINE__))
Definition at line 17 of file thread.h.
Thread_UnlockMutex
#define Thread_UnlockMutex (m) (_Thread_UnlockMutex(m, __FILE__, __LINE__))
Definition at line 18 of file thread.h.
Thread_WaitBarrier
#define Thread_WaitBarrier (barrier) (_Thread_WaitBarrier(barrier, __FILE__, __LINE__))
Definition at line 28 of file thread.h.
Thread_WaitThread
#define Thread_WaitThread (thread, retval) (_Thread_WaitThread(thread, retval, __FILE__, __LINE__))
Definition at line 25 of file thread.h.
THREADRECURSIVE
#define THREADRECURSIVE
Definition at line 10 of file thread.h.
Typedef Documentation
Thread_SpinLock
typedef int Thread_SpinLock
Definition at line 12 of file thread.h.
Function Documentation
_Thread_AtomicAdd()
int _Thread_AtomicAdd (Thread_Atomic * ref, int v, const char * filename, int fileline)
Definition at line 96 of file thread_null.c.
{
    int value = a->value;
    a->value += v;
    return value;
}
_Thread_AtomicDecRef()
qbool _Thread_AtomicDecRef (Thread_Atomic * ref, const char * filename, int fileline)
Definition at line 108 of file thread_null.c.
{
    return a->value++ == 1;
}
_Thread_AtomicGet()
int _Thread_AtomicGet (Thread_Atomic * ref, const char * filename, int fileline)
Definition at line 84 of file thread_null.c.
{
    return a->value;
}
_Thread_AtomicIncRef()
void _Thread_AtomicIncRef (Thread_Atomic * ref, const char * filename, int fileline)
Definition at line 103 of file thread_null.c.
{
    a->value++;
}
_Thread_AtomicLock()
void _Thread_AtomicLock (Thread_SpinLock * lock, const char * filename, int fileline)
Definition at line 118 of file thread_null.c.
{
}
_Thread_AtomicSet()
int _Thread_AtomicSet (Thread_Atomic * ref, int v, const char * filename, int fileline)
Definition at line 89 of file thread_null.c.
{
    int value = a->value;
    a->value = v;
    return value;
}
_Thread_AtomicTryLock()
qbool _Thread_AtomicTryLock (Thread_SpinLock * lock, const char * filename, int fileline)
Definition at line 113 of file thread_null.c.
{
    return true;
}
_Thread_AtomicUnlock()
void _Thread_AtomicUnlock (Thread_SpinLock * lock, const char * filename, int fileline)
Definition at line 122 of file thread_null.c.
{
}
_Thread_CondBroadcast()
int _Thread_CondBroadcast (void * cond, const char * filename, int fileline)
Definition at line 51 of file thread_null.c.
{
    return -1;
}
_Thread_CondSignal()
int _Thread_CondSignal (void * cond, const char * filename, int fileline)
Definition at line 46 of file thread_null.c.
{
    return -1;
}
_Thread_CondWait()
int _Thread_CondWait (void * cond, void * mutex, const char * filename, int fileline)
Definition at line 56 of file thread_null.c.
{
    return -1;
}
_Thread_CreateBarrier()
void * _Thread_CreateBarrier (unsigned int count, const char * filename, int fileline)
Definition at line 71 of file thread_null.c.
{
    return NULL;
}
_Thread_CreateCond()
void * _Thread_CreateCond (const char * filename, int fileline)
Definition at line 37 of file thread_null.c.
{
    return NULL;
}
_Thread_CreateMutex()
void * _Thread_CreateMutex (const char * filename, int fileline)
Definition at line 18 of file thread_null.c.
{
    return NULL;
}
_Thread_CreateThread()
void * _Thread_CreateThread (int(*)(void *) fn, void * data, const char * filename, int fileline)
Definition at line 61 of file thread_null.c.
{
    return NULL;
}
_Thread_DestroyBarrier()
void _Thread_DestroyBarrier (void * barrier, const char * filename, int fileline)
Definition at line 76 of file thread_null.c.
{
}
_Thread_DestroyCond()
void _Thread_DestroyCond (void * cond, const char * filename, int fileline)
Definition at line 42 of file thread_null.c.
{
}
_Thread_DestroyMutex()
void _Thread_DestroyMutex (void * mutex, const char * filename, int fileline)
Definition at line 23 of file thread_null.c.
{
}
_Thread_LockMutex()
int _Thread_LockMutex (void * mutex, const char * filename, int fileline)
Definition at line 27 of file thread_null.c.
{
    return -1;
}
_Thread_UnlockMutex()
int _Thread_UnlockMutex (void * mutex, const char * filename, int fileline)
Definition at line 32 of file thread_null.c.
{
    return -1;
}
_Thread_WaitBarrier()
void _Thread_WaitBarrier (void * barrier, const char * filename, int fileline)
Definition at line 80 of file thread_null.c.
{
}
_Thread_WaitThread()
int _Thread_WaitThread (void * thread, int retval, const char * filename, int fileline)
Definition at line 66 of file thread_null.c.
{
    return retval;
}
Thread_HasThreads()
qbool Thread_HasThreads (void)
Definition at line 13 of file thread_null.c.
{
    return false;
}
Referenced by Con_Init(), Crypto_Init(), Curl_Init(), FS_Init_Dir(), Memory_Init(), NetConn_Init(), and SV_StartThread().
Thread_Init()
int Thread_Init (void)
Definition at line 4 of file thread_null.c.
{
    return 0;
}
Referenced by Host_Init().
Thread_Shutdown()
void Thread_Shutdown (void)
Definition at line 9 of file thread_null.c.
{
}
Referenced by Host_Shutdown().