DarkPlaces: world.h File Reference
world.h File Reference
#include "qtypes.h"
#include "collision.h"
Data Structures
struct link_t
struct world_physics_t
struct world_t
Macros
#define MOVE_NORMAL 0
#define MOVE_NOMONSTERS 1
#define MOVE_MISSILE 2
#define MOVE_WORLDONLY 3
#define MOVE_HITMODEL 4
#define AREA_GRID 128
#define AREA_GRIDNODES (AREA_GRID * AREA_GRID)
Functions
void World_ClearLink (link_t *l)
World_ClearLink is used for new headnodes.
void World_RemoveLink (link_t *l)
void World_InsertLinkBefore (link_t *l, link_t *before, int entitynumber)
void World_Init (void)
void World_Shutdown (void)
void World_SetSize (world_t *world, const char *filename, const vec3_t mins, const vec3_t maxs, struct prvm_prog_s *prog)
called after the world model has been loaded, before linking any entities
void World_UnlinkAll (world_t *world)
unlinks all entities (used before reallocation of edicts)
void World_PrintAreaStats (world_t *world, const char *worldname)
void World_UnlinkEdict (struct prvm_edict_s *ent)
call before removing an entity, and before trying to move one, so it doesn't clip against itself
void World_LinkEdict (world_t *world, struct prvm_edict_s *ent, const vec3_t mins, const vec3_t maxs, qbool link_solid_not)
Needs to be called any time an entity changes origin, mins, maxs.
int World_EntitiesInBox (world_t *world, const vec3_t mins, const vec3_t maxs, int maxlist, struct prvm_edict_s **list)
void World_Start (world_t *world)
void World_End (world_t *world)
void World_Physics_Frame (world_t *world, double frametime, double gravity)
void World_Physics_ApplyCmd (struct prvm_edict_s *ed, struct edict_odefunc_s *f)
void World_Physics_RemoveFromEntity (world_t *world, struct prvm_edict_s *ed)
void World_Physics_RemoveJointFromEntity (world_t *world, struct prvm_edict_s *ed)
Macro Definition Documentation
AREA_GRID
#define AREA_GRID 128
Definition at line 34 of file world.h.
AREA_GRIDNODES
#define AREA_GRIDNODES (AREA_GRID * AREA_GRID)
Definition at line 35 of file world.h.
MOVE_HITMODEL
#define MOVE_HITMODEL 4
Definition at line 32 of file world.h.
MOVE_MISSILE
#define MOVE_MISSILE 2
Definition at line 30 of file world.h.
MOVE_NOMONSTERS
#define MOVE_NOMONSTERS 1
Definition at line 29 of file world.h.
MOVE_NORMAL
#define MOVE_NORMAL 0
Definition at line 28 of file world.h.
MOVE_WORLDONLY
#define MOVE_WORLDONLY 3
Definition at line 31 of file world.h.
Function Documentation
World_ClearLink()
void World_ClearLink (link_t * l)
World_ClearLink is used for new headnodes.
Definition at line 79 of file world.c.
{
    l->entitynumber = 0;
    l->list.prev = l->list.next = &l->list;
}
Referenced by World_SetSize().
World_End()
void World_End (world_t * world)
Definition at line 69 of file world.c.
{
#ifdef USEODE
    World_Physics_End(world);
#endif
}
Referenced by CLVM_reset_cmd(), and SVVM_reset_cmd().
World_EntitiesInBox()
int World_EntitiesInBox (world_t * world, const vec3_t mins, const vec3_t maxs, int maxlist, struct prvm_edict_s ** list)
Returns
list of entities touching a box
World_Init()
void World_Init (void)
Definition at line 38 of file world.c.
{
    Collision_Init();
#ifdef USEODE
    World_Physics_Init();
#endif
}
Referenced by Host_Init().
World_InsertLinkBefore()
void World_InsertLinkBefore (link_t * l, link_t * before, int entitynumber)
Definition at line 90 of file world.c.
{
    l->entitynumber = entitynumber;
    List_Add_Tail(&l->list, &before->list);
}
Referenced by World_LinkEdict_AreaGrid().
World_LinkEdict()
void World_LinkEdict (world_t * world, struct prvm_edict_s * ent, const vec3_t mins, const vec3_t maxs, qbool link_solid_not)
Needs to be called any time an entity changes origin, mins, maxs.
World_Physics_ApplyCmd()
void World_Physics_ApplyCmd (struct prvm_edict_s * ed, struct edict_odefunc_s * f)
World_Physics_Frame()
void World_Physics_Frame (world_t * world, double frametime, double gravity)
Referenced by CL_NetworkTimeReceived(), and SV_Physics().
World_Physics_RemoveFromEntity()
void World_Physics_RemoveFromEntity (world_t * world, struct prvm_edict_s * ed)
Referenced by CLVM_free_edict(), and SVVM_free_edict().
World_Physics_RemoveJointFromEntity()
void World_Physics_RemoveJointFromEntity (world_t * world, struct prvm_edict_s * ed)
Referenced by CLVM_free_edict(), and SVVM_free_edict().
World_PrintAreaStats()
void World_PrintAreaStats (world_t * world, const char * worldname)
Definition at line 104 of file world.c.
{
    Con_Printf("%s areagrid check stats: %d calls %d nodes (%f per call) %d entities (%f per call)\n", worldname, world->areagrid_stats_calls, world->areagrid_stats_nodechecks, (double) world->areagrid_stats_nodechecks / (double) world->areagrid_stats_calls, world->areagrid_stats_entitychecks, (double) world->areagrid_stats_entitychecks / (double) world->areagrid_stats_calls);
    world->areagrid_stats_calls = 0;
    world->areagrid_stats_nodechecks = 0;
    world->areagrid_stats_entitychecks = 0;
}
Referenced by CL_AreaStats_f(), and SV_AreaStats_f().
World_RemoveLink()
void World_RemoveLink (link_t * l)
Definition at line 85 of file world.c.
{
    List_Delete(&l->list);
}
Referenced by World_UnlinkEdict().
World_SetSize()
void World_SetSize (world_t * world, const char * filename, const vec3_t mins, const vec3_t maxs, struct prvm_prog_s * prog)
called after the world model has been loaded, before linking any entities
World_Shutdown()
void World_Shutdown (void)
Definition at line 49 of file world.c.
{
#ifdef USEODE
    World_Physics_Shutdown();
#endif
}
World_Start()
void World_Start (world_t * world)
Definition at line 59 of file world.c.
{
#ifdef USEODE
    World_Physics_Start(world);
#endif
}
Referenced by CL_SetupWorldModel(), and SV_SpawnServer().
World_UnlinkAll()
void World_UnlinkAll (world_t * world)
unlinks all entities (used before reallocation of edicts)
Definition at line 159 of file world.c.
{
    prvm_prog_t *prog = world->prog;
    int i;
    link_t *grid;
    // unlink all entities one by one
    grid = &world->areagrid_outside;
    while (grid->list.next != &grid->list)
        World_UnlinkEdict(PRVM_EDICT_NUM(List_Entry(grid->list.next, link_t, list)->entitynumber));
    for (i = 0, grid = world->areagrid;i < AREA_GRIDNODES;i++, grid++)
        while (grid->list.next != &grid->list)
            World_UnlinkEdict(PRVM_EDICT_NUM(List_Entry(grid->list.next, link_t, list)->entitynumber));
}
Referenced by CLVM_begin_increase_edicts(), SV_Loadgame_f(), and SVVM_begin_increase_edicts().
World_UnlinkEdict()
void World_UnlinkEdict (struct prvm_edict_s * ent)
call before removing an entity, and before trying to move one, so it doesn't clip against itself