name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      # Testing
      - name: Testing of environment variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF_NAME
          echo ${{ github.event.pull_request.head.sha }}
          echo github.ref_type ${{ github.ref_type }}
